### PR TITLE
Issue 4097: Serialization Framework for Synchronizer Config

### LINKED ISSUE #4097: Synchronizer config should use serialization framework
**Problem description**
Most serialization within Pravega is now done in a standard way including most config objects. An exception to this is `SynchronizerConfig.java` which still relies on Java serialization.

**Problem location**
SynchronizerConfig.java

**Suggestions for an improvement**
Use the same method as the other public facing config objects such as ReaderGroupConfig

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>

**Change log description**  
Creating a custom Serializer instead of relying on Java Serializion for the SynchronizerConfig and the EventWriterConfig.

**Purpose of the change**  
Fixes #4097 

**What the code does**  
Adds a SynchronizerConfigSerializer and an EventWriterConfigSerializer for serializing the SynchronizerConfig and the EventWriterConfig objects respectively.

**How to verify it**  
All tests should pass

### CODE REVIEW

File: client/src/main/java/io/pravega/client/state/SynchronizerConfig.java [hunk 1]
```diff
@@ -41,8 +52,50 @@
...
+            byte[] b = new byte[0];
+            builder.readBufferSize(revisionDataInput.readInt());
+            revisionDataInput.readFully(b);
+            builder.eventWriterConfig(builder.eventWriterConfig.fromBytes(ByteBuffer.wrap(b)));
+        }
+
+        private void write00(SynchronizerConfig object, RevisionDataOutput revisionDataOutput) throws IOException {
+            Charset cs = Charset.forName("UTF-8");
+            revisionDataOutput.writeInt(object.getReadBufferSize());
+            revisionDataOutput.writeBytes(cs.decode(object.eventWriterConfig.toBytes()).toString());
```
[the remark this answers is not in the document]
Comment (SrishT) [reply client/src/main/java/io/pravega/client/state/SynchronizerConfig.java]: done

File: client/src/main/java/io/pravega/client/state/SynchronizerConfig.java [hunk 2]
```diff
@@ -41,8 +52,50 @@
...
+
+        @Override
+        protected void declareVersions() {
+            version(0).revision(0, this::write00, this::read00);
+        }
+
+        private void read00(RevisionDataInput revisionDataInput, SynchronizerConfigBuilder builder) throws IOException {
+            byte[] b = new byte[0];
+            builder.readBufferSize(revisionDataInput.readInt());
+            revisionDataInput.readFully(b);
```
[the remark this answers is not in the document]
Comment (SrishT) [reply client/src/main/java/io/pravega/client/state/SynchronizerConfig.java]: done

File: client/src/main/java/io/pravega/client/state/SynchronizerConfig.java [hunk 3]
```diff
@@ -41,8 +51,47 @@
...
+        }
+
+        private void read00(RevisionDataInput revisionDataInput, SynchronizerConfigBuilder builder) throws IOException {
+            builder.readBufferSize(revisionDataInput.readInt());
+            builder.eventWriterConfig.fromBytes(ByteBuffer.wrap(revisionDataInput.readArray()));
+        }
+
+        private void write00(SynchronizerConfig object, RevisionDataOutput revisionDataOutput) throws IOException {
+            revisionDataOutput.writeInt(object.getReadBufferSize());
+            revisionDataOutput.writeArray(object.eventWriterConfig.toBytes().array());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/state/SynchronizerConfig.java:83]: You need to provide arrayOffset and length as it is legal for a byteBuffer's array to have more data in in that just the buffer. (And this as calling code should not depend on anything about the implementation of eventWriter's toBytes method that is not in the signature)

File: client/src/main/java/io/pravega/client/state/SynchronizerConfig.java [hunk 4]
```diff
@@ -27,7 +36,8 @@
 @Builder
 public class SynchronizerConfig implements Serializable {
 
-    private static final long serialVersionUID = 2L;
+    private static final long serialVersionUID = 3L;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/state/SynchronizerConfig.java:39]: This isn't quite enough to get Java serialization to use our serialization. We have to override it's methods, by implementing a `writeReplace()` and a `readResolve()` method on a "SerializedFrom". Take a look at how this is done at the bottom of `StreamCutImpl` (Which also does it with byte arrays so you can basically copy and paste that code). Or `SegmentImpl` or `StreamImpl` (which do the same thing but with strings)

File: client/src/main/java/io/pravega/client/stream/EventWriterConfig.java [hunk 5]
```diff
@@ -17,15 +17,25 @@
...
+import java.nio.ByteBuffer;
+import lombok.SneakyThrows;
 
 @Data
 @Builder
 public class EventWriterConfig implements Serializable {
-    
-    private static final long serialVersionUID = 1L;
+
+    private static final long serialVersionUID = 2L;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/EventWriterConfig.java:36]: Same here

**Review by tkaitchuck — CHANGES_REQUESTED** [review]

File: client/src/main/java/io/pravega/client/state/SynchronizerConfig.java [hunk 6]
```diff
@@ -41,8 +51,63 @@
...
+        }
+
+        @Override
+        protected void declareVersions() {
+            version(0).revision(0, this::write00, this::read00);
+        }
+
+        private void read00(RevisionDataInput revisionDataInput, SynchronizerConfigBuilder builder) throws IOException {
+            builder.readBufferSize(revisionDataInput.readInt());
+            builder.eventWriterConfig.fromBytes(ByteBuffer.wrap(revisionDataInput.readArray()));
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/state/SynchronizerConfig.java:78]: This line here is the problem. `fromBytes` is a static method that returns a new event writer config. Here it should call the static method and then set the resulting EventWriterConfig on the builder. Right now it is just throwing it away.

**Review by tkaitchuck — APPROVED** [review]
Looks good.
It looks like to make code cov happy you'll need to have a test for the Java serialization.

**Review by tkaitchuck — APPROVED** [review]
