### PR TITLE
Issue 5799: Sporadic test failure DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel and RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking

### LINKED ISSUE #5481: Test failure: RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking
**Problem description**
1st stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:684
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
```
2nd stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
            at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:181)
            at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
            at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
            at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
`RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5799: Sporadic test failure DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel
**Describe the bug**
Found test `DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel` failing sporadically due to:
```
java.lang.AssertionError: Unexpected attribute for Segment_9 expected:<50> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.pravega.segmentstore.server.containers.DebugStreamSegmentContainerTests.testDataRecoveryContainerLevel(DebugStreamSegmentContainerTests.java:415)
```

**To Reproduce**
Sporadic test failure when executing `gradlew build`.

**Expected behavior**
Test must pass reliably.

**Screenshots**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ManishKumarKeshri**
**Change log description**  
-  Changed Durable log config to no truncations to avoid any flush happening before `flushToStorage` is called. 
- Make empty backup metadata segments in case of original metadata segments don't exist. This will solve the following exception:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:681)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:765)
```

- We can only check for the correctness of core attributes after recovery. Other attributes are not updated. Previously the test checked for the correctness of any attribute, which caused error like the following:
```
java.lang.AssertionError: Unexpected attribute for Segment_9 expected:<50> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
```
- Using `CompletableFuture.allOf` instead of `thenAccept` where no dependency is involved. 
- Changed method ` Map<Integer, String> createBackUpMetadataSegments` to `synchronized CompletableFuture<Map<Integer, String>>`.
- Many comments have been added to help review.
**Purpose of the change**  
Fixes #5799 
Fixes #5481 

**What the code does**  
-  Durable Log config changed.
- Changed any random attribute update to a random core attribute update. 
- Creates empty backup metadata segments and puts in the map of backup metadata segments in case when original metadat segments don't exist. 

**How to verify it**  
Build shall pass.

### CODE REVIEW

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 1]
```diff
@@ -324,7 +324,7 @@ public void testDataRecoveryContainerLevel() throws Exception {
 
         @Cleanup
         TestContext context = createContext(executorService());
-        OperationLogFactory localDurableLogFactory = new DurableLogFactory(DEFAULT_DURABLE_LOG_CONFIG, context.dataLogFactory, executorService());
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:327]: Why this is solving the problem? Please, describe this in detail in the PR, as we need to understand the purpose of the change. Also, let us know how have you verified that the original problem has been solved, as the fact that the build passes (how many times? in which environments?) does not mean that the unreliability of the test has been solved.

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java (hunk 1 above)
Comment (ManishKumarKeshri) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:327]: Hi Raul

Yes sure. It was the only problem I could find in the test then. Still working on it.

**Comment by RaulGracia** [comment]
@ManishKumarKeshri what is the status of this one? This test continues to fail often, please let's try to nail down the root cause.

**Comment by ManishKumarKeshri** [comment]
Hi @RaulGracia , One of the issues is fixed from #5799 is fixed. Still working on the timeout issue. Tried running multiple time locally, now only timeout issue occurs, assertion fail looks to be fixed.

**Comment by ManishKumarKeshri** [comment]
Now, It fixes all kinds of errors.

**Comment by RaulGracia** [comment]
@ManishKumarKeshri spotbugs is complaining:
```
* What went wrong:
Execution failed for task ':segmentstore:server:spotbugsMain'.
> A failure occurred while executing com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor
   > 1 SpotBugs violations were found. See the report at: file:///home/runner/work/pravega/pravega/segmentstore/server/build/reports/spotbugs/main.html
```

**Comment by ManishKumarKeshri** [comment]
Tried running locally many times. All issues are gone. Please have a look @sachin-j-joshi and @RaulGracia

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 2]
```diff
@@ -180,10 +180,11 @@ private static void validateContainerIds(Map<Integer, DebugStreamSegmentContaine
 
             // Store the segments in a set
             Set<String> metadataSegments = new HashSet<>();
-            keyIterator.forEachRemaining(k ->
+            Futures.exceptionallyExpecting(keyIterator.forEachRemaining(k ->
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:183]: To handle the case when metadata segment doesn't exist.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 3]
```diff
@@ -243,8 +244,8 @@ private static void validateContainerIds(Map<Integer, DebugStreamSegmentContaine
         Preconditions.checkNotNull(storage);
         String metadataSegmentName = NameUtils.getMetadataSegmentName(containerId);
         String attributeSegmentName = NameUtils.getAttributeSegmentName(metadataSegmentName);
-        return deleteSegmentFromStorage(storage, metadataSegmentName, timeout)
-                .thenAccept(x -> deleteSegmentFromStorage(storage, attributeSegmentName, timeout));
+        return  CompletableFuture.allOf(deleteSegmentFromStorage(storage, metadataSegmentName, timeout),
+                deleteSegmentFromStorage(storage, attributeSegmentName, timeout));
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:248]: both can be executed, no need for `thenAccept`.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 4]
```diff
@@ -412,33 +415,32 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
...
+                String backUpAttributeSegment = NameUtils.getAttributeSegmentName(backUpMetadataSegment);
+                log.debug("Created '{}' as a back of metadata segment of container Id '{}'", backUpMetadataSegment, containerId);
+
+                val finalContainerId = containerId;
+                futures.add(Futures.exceptionallyExpecting(
+                        ContainerRecoveryUtils.backUpMetadataAndAttributeSegments(storage, containerId,
+                                backUpMetadataSegment, backUpAttributeSegment, executorService, timeout)
+                                .thenCompose(x -> ContainerRecoveryUtils.deleteMetadataAndAttributeSegments(storage, finalContainerId, timeout))
+                                        .thenAccept(z -> backUpMetadataSegments.put(finalContainerId, backUpMetadataSegment)),
+                                        ex -> Exceptions.unwrap(ex) instanceof StreamSegmentNotExistsException, null));
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:440]: returning `completableFuture` now. 
`synchroized` to avoid multiple threads from deleting and making copies.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 5]
```diff
@@ -316,18 +317,20 @@ public void testBackUpMetadataAndAttributeSegments() {
     public void testDataRecoveryContainerLevel() throws Exception {
         int attributesUpdatesPerSegment = 50;
         int segmentsCount = 10;
-        final UUID attributeReplace = UUID.randomUUID();
+        final UUID attributeReplace = new UUID(CORE_ATTRIBUTE_ID_PREFIX, RANDOM.nextInt(10));
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:320]: Only core attributes are updated, so check only them.

**Comment by RaulGracia** [comment]
@ManishKumarKeshri we know that many times running the test locally and making it work many times does not demonstrate that the original issue is gone. Please, try to execute and keep record of Jenkins/Git Actions builds and keep track if the issue is reproduced or not.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 6]
```diff
@@ -628,17 +628,17 @@ public void testDurableDataLogFailRecoveryReadersPaused() throws Exception {
         // Flush DurableLog to Long Term Storage
         flushToStorage(pravegaRunner.segmentStoreRunner.serviceBuilder);
 
+        pravegaRunner.segmentStoreRunner.close(); // Shutdown SegmentStore
+        pravegaRunner.bookKeeperRunner.close(); // Shutdown BookKeeper & ZooKeeper
+        log.info("SegmentStore, BookKeeper & ZooKeeper shutdown");
+
```
Comment (ManishKumarKeshri) [inline test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:634]: Just changed the position. So that after we close everything and then instantiate `Storage` as it should typically happen in the use case.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 7]
```diff
@@ -750,17 +750,17 @@ public void testDurableDataLogFailRecoveryWatermarking() throws Exception {
...
```
Comment (ManishKumarKeshri) [inline test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:756]: Just changed the position. So that after we close everything and then instantiate `Storage` as it should typically happen in the use case.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 8]
```diff
@@ -322,18 +323,20 @@ public void testBackUpMetadataAndAttributeSegments() {
...
         final long expectedAttributeValue = attributesUpdatesPerSegment;
         int containerId = 0;
         int containerCount = 1;
         int maxDataSize = 1024 * 1024; // 1MB
 
+        StorageFactory storageFactory = new InMemoryStorageFactory(executorService());
+
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:333]: Created a storage factory beforehand and use it for recovery. This will make the text more clear. Previously we used the same context (`storageFactory`, `readIndexFactory`, `attributeIndexFactory` etc.) except `DurableLog` before and after the recovery.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 9]
```diff
@@ -418,33 +419,32 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
...
+                String backUpAttributeSegment = NameUtils.getAttributeSegmentName(backUpMetadataSegment);
+                log.debug("Created '{}' as a back of metadata segment of container Id '{}'", backUpMetadataSegment, containerId);
+
+                val finalContainerId = containerId;
+                futures.add(Futures.exceptionallyExpecting(
+                        ContainerRecoveryUtils.backUpMetadataAndAttributeSegments(storage, containerId,
+                                backUpMetadataSegment, backUpAttributeSegment, executorService, timeout)
+                                .thenCompose(x -> ContainerRecoveryUtils.deleteMetadataAndAttributeSegments(storage, finalContainerId, timeout)),
+                                        ex -> Exceptions.unwrap(ex) instanceof StreamSegmentNotExistsException, null));
+                backUpMetadataSegments.put(finalContainerId, backUpMetadataSegment);
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:444]: returning `completableFuture` now. 
`synchroized` to avoid multiple threads from deleting and making copies. 

Issue [#5481(here),](https://github.com/pravega/pravega/issues/5481#issuecomment-800085111) the mismatch between the number of backup metadata segments and containers is also be fixed here. In case, when metadata segment(s) don't exist, it throws `StreamSegmentNotExistsException` and the backup segment created was never put into the map of backup metadata segments. But now, an empty backup metadata segment will be created and put into the map.

**Comment by ManishKumarKeshri** [comment]
@sachin-j-joshi It will be great if you can review.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 10]
```diff
@@ -314,7 +314,8 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
                                             Duration timeout) throws InterruptedException, ExecutionException,
             TimeoutException {
         Preconditions.checkState(backUpMetadataSegments.size() == containersMap.size(), "The number of " +
-                "back-up metadata segments and containers should match.");
+                "back-up metadata segments = " + backUpMetadataSegments.size() + " and number of containers = "
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:317]: you can use % s like below
Preconditions.checkState("The number of back-up metadata segments = %s and number of containers = %s "should match.", backUpMetadataSegments.size(), containersMap.size())

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 11]
```diff
@@ -418,33 +419,32 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
...
+
+                val finalContainerId = containerId;
+                futures.add(Futures.exceptionallyExpecting(
+                        ContainerRecoveryUtils.backUpMetadataAndAttributeSegments(storage, containerId,
+                                backUpMetadataSegment, backUpAttributeSegment, executorService, timeout)
+                                .thenCompose(x -> ContainerRecoveryUtils.deleteMetadataAndAttributeSegments(storage, finalContainerId, timeout)),
+                                        ex -> Exceptions.unwrap(ex) instanceof StreamSegmentNotExistsException, null));
+                backUpMetadataSegments.put(finalContainerId, backUpMetadataSegment);
+            }
+            Futures.allOf(futures).join();
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:446]: use 

return Futures.allOf(futures).thenApply(vv -> backUpMetadataSegments);

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java (hunk 10 above)
Comment (ManishKumarKeshri) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java]: Fixed.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 12]
```diff
@@ -381,45 +384,53 @@ public void testDataRecoveryContainerLevel() throws Exception {
...
+                        byte[] actualData = new byte[expectedData.length];
+                        container2.read(sc.getKey(), 0, actualData.length, TIMEOUT).join().readRemaining(actualData, TIMEOUT);
+                        Assert.assertArrayEquals("Unexpected contents for " + sc.getKey(), expectedData, actualData);
+
+                        // Length.
+                        val si = container2.getStreamSegmentInfo(sc.getKey(), TIMEOUT).join();
+                        Assert.assertEquals("Unexpected length for " + sc.getKey(), expectedData.length, si.getLength());
+
+                        // Attributes.
+                        val attributes = container2.getAttributes(sc.getKey(), Collections.singleton(attributeReplace), false, TIMEOUT).join();
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:429]: Joining a future inside a future does not look great. Actually, is really needed this change in the test? Could you just `get()` the future related to `containerRecoveryUtils.createBackUpMetadataSegments()` and run the rest of the test sequentially as it was before? I don't see the advantage of running all this in a `thenCompose()`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 13]
```diff
@@ -322,18 +323,20 @@ public void testBackUpMetadataAndAttributeSegments() {
...
         int attributesUpdatesPerSegment = 50;
         int segmentsCount = 10;
-        final UUID attributeReplace = UUID.randomUUID();
+        final UUID attributeReplace = new UUID(CORE_ATTRIBUTE_ID_PREFIX, RANDOM.nextInt(10));
         final long expectedAttributeValue = attributesUpdatesPerSegment;
         int containerId = 0;
         int containerCount = 1;
         int maxDataSize = 1024 * 1024; // 1MB
 
+        StorageFactory storageFactory = new InMemoryStorageFactory(executorService());
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:332]: `@CleanUp`?

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 14]
```diff
@@ -486,7 +486,7 @@ private void testRecovery(int containerCount, int bookieCount, boolean withTrans
                 new SegmentRollingPolicy(DEFAULT_ROLLING_SIZE)), executorService());
 
         Map<Integer, String> backUpMetadataSegments = ContainerRecoveryUtils.createBackUpMetadataSegments(storage, containerCount,
-                executorService(), TIMEOUT);
+                executorService(), TIMEOUT).join();
```
[the remark this answers is not in the document]
Comment (ManishKumarKeshri) [reply test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java]: Done.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java (hunk 13 above)
Comment (ManishKumarKeshri) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:332]: Not required.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java (hunk 12 above)
Comment (ManishKumarKeshri) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java]: Yeah. Removed thenCompose and made it similar to before.

**Comment by ManishKumarKeshri** [comment]
@sachin-j-joshi can you please restart the build and review? Thanks.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java (hunk 6 above)
Comment (ManishKumarKeshri) [reply test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:637]: It's not. We are simulating data recovery which requires services to be closed and then restarted.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java (hunk 7 above)
Comment (ManishKumarKeshri) [reply test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:759]: No. It is required to do so.

**Review by andreipaduroiu — APPROVED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 15]
```diff
@@ -418,14 +419,13 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
      *                                  attributes segment has to be performed.
      * @param executorService           A thread pool for execution.
      * @param timeout                   Timeout for the operation.
-     * @return                          A Map of Container Ids to new container metadata segment names.
-     * @throws InterruptedException     If the operation was interrupted while waiting.
-     * @throws TimeoutException         If the timeout expired prior to being able to complete the operation.
-     * @throws ExecutionException       When execution of the opreations encountered an error.
+     * @return                          A CompletableFuture that, when completed normally, will have a Map of Container
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:422]: FYI: At line 404 above, you cannot return `null`; you need to return `CompletableFuture.<Void>completedFuture(null)`. Otherwise you'll get a (silent) NullPtrEx.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM.

**Review by RaulGracia — APPROVED** [review]
