### PR TITLE
Issue 3252: Wrong metrics configuration parameter (dynamicTTLSeconds)

### LINKED ISSUE #3252: Wrong metrics configuration parameter (dynamicTTLSeconds)
**Problem description**
Found that the parameter `dynamicTTLSeconds` in `config.properties` is not used anywhere in the code. Probably, this is referring to `dynamicCacheEvictionDurationMs` that has no entry in `config.properties`.

**Problem location**
`config.properties`

**Suggestions for an improvement**
Rename the `dynamicTTLSeconds` parameter in `config.properties` to `dynamicCacheEvictionDurationMs`.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Enable `dynamicCacheEvictionDurationMs` to be configured in `config.properties` file (replaces the existing `dynamicTTLSeconds` entry in configuration).

**Purpose of the change**  
Fixes #3252.

**What the code does**  
In `config.properties`, there is a metrics configuration parameter that is not used anywhere: `dynamicTTLSeconds`. The description of this parameter matches the purpose of `dynamicCacheEvictionDurationMs`, which is the actual one used in `MetricsConfig.java`. This PR just replaces the apparently mistaken parameter name by the correct one in the configuration.

**How to verify it**  
No changes in the code. All the tests should be working as before.

### CODE REVIEW

File: config/config.properties [hunk 1]
```diff
@@ -160,11 +160,11 @@ metrics.enableStatistics=false
...
 #metrics.dynamicCacheSize=100000
 
-# Number of seconds to keep dynamic metric statistic objects in memory.
+# Number of minutes to keep dynamic metric statistic objects in memory.
 # Valid values: Positive integer.
-# Recommended values: 60 to 300. The higher the value, the more memory used, but it may improve performance slightly
+# Recommended values: 1 to 60. The higher the value, the more memory used, but it may improve performance slightly
 # in scenarios where there are large number of active Stream Segments.
-#metrics.dynamicTTLSeconds=120
+#metrics.dynamicCacheEvictionDurationMs=30
```
Comment (andreipaduroiu) [inline config/config.properties]: `Ms` is millis
Please use `minutes`

**Comment by RaulGracia** [comment]
[Wrong metrics configuration parameter (dynamicTTLSeconds)](https://trello.com/c/5wWVgQsT/77-wrong-metrics-configuration-parameter-dynamicttlseconds)

File: shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java [hunk 2]
```diff
@@ -174,7 +174,7 @@
     private MetricsConfig(TypedProperties properties) throws ConfigurationException {
         this.enableStatistics = properties.getBoolean(ENABLE_STATISTICS);
         this.dynamicCacheSize = properties.getLong(DYNAMIC_CACHE_SIZE);
-        this.dynamicCacheEvictionDurationMs = Duration.ofMinutes(properties.getInt(DYNAMIC_CACHE_EVICTION_DURATION_MINUTES)).toMillis();
+        this.dynamicCacheEvictionDurationMinutes = Duration.ofMinutes(properties.getInt(DYNAMIC_CACHE_EVICTION_DURATION_MINUTES)).toMillis();
```
Comment (andreipaduroiu) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java]: You use `toMillis` here, but assign it to a field named `Minutes`.This looks very wrong.

Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java]: If you are fixing this class, please let's get out of the dark ages and use `Duration` instead of some `long` field that contains some value for which nobody knows what the unit is. All other config classes that use time express this as a `Duration` (or at least they should be).

File: shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java [hunk 3]
```diff
@@ -41,7 +41,7 @@ public DynamicLoggerImpl(MetricsConfig metricsConfig, MetricRegistry metrics, St
         this.metrics = metrics;
         this.underlying = statsLogger;
         this.cacheSize = metricsConfig.getDynamicCacheSize();
-        this.cacheEvictionDuration = metricsConfig.getDynamicCacheEvictionDurationMs();
+        this.cacheEvictionDuration = metricsConfig.getDynamicCacheEvictionDurationMinutes();
 
         countersCache = CacheBuilder.newBuilder().
```
Comment (andreipaduroiu) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java]: You take a value that is `minutes` and declare that it is `TimeUnit.MILLISECONDS` ... ouch! 

Please use `Duration` as requested below.

File: shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java (hunk 2 above)
Comment (RaulGracia) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/MetricsConfig.java]: You are right, using `Duration` instead.

File: shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java (hunk 3 above)
Comment (RaulGracia) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java]: Thanks for spotting this. I changed the type of both metrics time parameters to `Duration`.
