### PR TITLE
Issue 2080: Scope delete fails with directory not empty

### LINKED ISSUE #2080: Test failure: ReadWriteTest.readWriteTest
**Problem description**
After the test failure, I have found these error messages with respect to ZooKeeper suspicious. I'm attaching the full logs here for completeness in any case.

```
2017-11-15 17:00:07,418 130934 [ProcessThread(sid:0 cport:56128):] INFO  o.a.z.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x102d643f4620000 type:delete cxid:0x2d9 zxid:0xd6 txntype:-1 reqpath:n/a Error Path:/pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/buckets/0/dGVzdE11bHRpUmVhZGVyV3JpdGVyU2NvcGUvdGVzdE11bHRpUmVhZGVyV3JpdGVyU3RyZWFtMjA1NjI1MjY4MQ== Error:KeeperErrorCode = NoNode for /pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/buckets/0/dGVzdE11bHRpUmVhZGVyV3JpdGVyU2NvcGUvdGVzdE11bHRpUmVhZGVyV3JpdGVyU3RyZWFtMjA1NjI1MjY4MQ==
2017-11-15 17:00:07,419 130935 [ProcessThread(sid:0 cport:56128):] INFO  o.a.z.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x102d643f4620000 type:delete cxid:0x2da zxid:0xd7 txntype:-1 reqpath:n/a Error Path:/pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/store/testMultiReaderWriterScope/testMultiReaderWriterStream2056252681 Error:KeeperErrorCode = Directory not empty for /pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/store/testMultiReaderWriterScope/testMultiReaderWriterStream2056252681
2017-11-15 17:00:07,428 130944 [Time-limited test] INFO  i.p.test.integration.ReadWriteTest - Deleting scope testMultiReaderWriterScope
2017-11-15 17:00:07,428 130944 [ProcessThread(sid:0 cport:56128):] INFO  o.a.z.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x102d643f4620000 type:delete cxid:0x2ea zxid:0xde txntype:-1 reqpath:n/a Error Path:/pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/store/testMultiReaderWriterScope Error:KeeperErrorCode = Directory not empty for /pravega/a2066a48-ef4e-497f-9bbe-6ccd8d59025b/store/testMultiReaderWriterScope
```
[readWriteTest-logs.txt](https://github.com/pravega/pravega/files/1477530/readWriteTest-logs.txt)

**Problem location**
Integration tests.

**Suggestions for an improvement**
Fix the nasty bug!

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: shivesh ranjan <shivesh.ranjan@gmail.com>

**Change log description**
There are two issues:
1. Delete Scope fails. which is the root cause for test failure
Stream Deletion is done asynchronously. 
We used to check if delete is done by looking to access some property within the stream (like state) and on not being able to find such a property we would conclude that the stream was deleted. 

The stream may be in the process of being deleted, but not all of its data may have been deleted while a request for deletion of scope is received. 

Deletion of scopes fails with "container not empty" from zookeeper. 

2. delete stream under bucket gives NoNode
This is because we are not adding the node while creating the stream. 

**Purpose of the change**
Fixes #2080

**What the code does**
Introduces a new api on metadataStore interface to check if stream exists or not. 

**How to verify it**
Unit tests added

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java [hunk 1]
```diff
@@ -476,6 +476,26 @@ public void updateTest() throws Exception {
     }
 
     @Test
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: I see `join`s in this test case, better have a timeout, same for the test following this one.

Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: There is a global timeout in this test class.. Set to 10 seconds.
