### PR TITLE
Issue 2312: Create node with Ephemeral mode in ZkStoreHelper.createEphemeralZNode mode

### LINKED ISSUE #2312: Bug in Controller ZkStoreHelper in createEphemeral node
**Problem description**
In Controller's ZkStoreHelper we have a helper method to create ephemeral node, but this does not have EPHEMERAL mode set on the node being created. 

This causes problems for bucket failover and causes system test to fail as new controller instances do not get ownership of buckets as the ownership transfer fails. 

Another problem is whenever streams are added to bucket, we add it to an in memory map in StreamCutBucketService. Here we use putIfAbsent and pass a method that returns a future as the value. So even if the value is present in the map, the method is invoked and future is scheduled for processing nevertheless resulting in potentially multiple (2) futures for the same stream running in background. It doesnot cause  correctness problem but its wasteful. 

**Problem location**
ZKStoreHelper.java
StreamCutBucketService.java

**Suggestions for an improvement**
Actually create ephemeral node.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**

1. ZkStoreHelper.createEphemeral node to actually create ephemeral node
2. Use map.computeIfAbsent instead of putIfAbsent in StreamCutBucketService while adding new stream. 
3. Add more info and debug logging for retention workflow

**Purpose of the change**
Fixes #2312.

**What the code does**
There is a bug in ZkStoreHelper's helper method for creating ephemeral node where CreateMode.Ephemeral flag is not passed. 
Because of this issue retention buckets were not failed over in case of owning controller instance failures. So we faced system test failure. 

Apart from that, from the logs we noticed that two background processing for same stream was getting invoked because we were actually doing map.putIfAbsent instead of computeIfAbsent and the value was being computed twice even though it was not getting added to the map. The value here being future of background processing for retention. 

Added more logs to help with debugging issues in future. 

**How to verify it**
Added new unit test for ephemeral node.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java [hunk 1]
```diff
@@ -92,10 +93,12 @@ protected void doStart() {
                 final StreamImpl stream;
                 switch (notification.getType()) {
                     case StreamAdded:
+                        log.info("New stream {}/{} added to bucket {} ", notification.getScope(), notification.getStream(), bucketId);
                         stream = new StreamImpl(notification.getScope(), notification.getStream());
-                        retentionFutureMap.putIfAbsent(stream, getStreamRetentionFuture(stream));
+                        retentionFutureMap.computeIfAbsent(stream, x -> getStreamRetentionFuture(stream));
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java]: I'm not sure how this is changing anything. In the way this is done, I can't tell the difference between using `putIfAbsent` and `computeIfAbsent` (I understand the semantic difference between the two calls).

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/server/retention/StreamCutBucketService.java]: Lets say i have a map `Map<K, CompletableFuture<V>> map`.
And i have  a method called ```CompletableFuture<V> getFutureValue()```
Calling `map.putIfAbsent(key, getFutureValue())` `n` times will only put one entry in the map but create `n` futures. This is because we pass a value to this method and the value is computed before calling the method.  

however doing `map.computeIfAbsent(key, x -> getFutureValue())` any number of times will not perform the computation more than once so only one future is created. This is because we pass a lambda here which is executed only if computation should be done. 

Note: creating future implies creating some asynchronous processing work.
