### PR TITLE
Issue 3150: (SegmentStore) Table Metadata Store

### LINKED ISSUE #3074: Segment store fails to create segments if hammered with large volume of requests in short span
**Problem description**
I was attempting to create a stream with 10k segments. This meant controller sent out 10k CreateSegment requests within 8 seconds to segment store. 
However, none of the requests completed in over 1 hour and controller continued waiting forever. 

**Problem location**
SegmentStore

**Suggestions for an improvement**

### LINKED ISSUE #3075: Segment Metadata Scalability
**Problem description**
Currently the source of truth for Segments is Tier 2. We use that to determine if a segment exists and its current length and sealed status.

Upon creating a segment, we create up to 3 files at once in Tier 2 (State, Header, First Data Chunk). For HDFS, this may be problematic, especially if creating a large number of segments at the same time, since HDFS serializes file creation at the name node. 

This also forces us to make Create & Delete Tier 2 direct operations, thus making the other operations constantly having to check for the segment's existence and handling that as a special, terminal case.

**Problem location**
Segment Store/Segment Metadata/Tier 2.

**Suggestions for an improvement**
We can use Table Segments to offload the Segment Metadata for segments that are evicted from memory.

High-level points:
- **Metadata Segment** (MS) per Container which has all that Container's Segments as Keys. The values is the current contents of the State file, plus whether the Segment is sealed and its length.
    - This is essentially the information that needs to be retrieved when reactivating a segment.
- **Create segment** is a conditional update on MS (conditioned on the key not existing).
- **Delete segment** is a conditional update on MS (conditioned on the key existing) followed by an atomic **DeleteOperation** in the Segment store (new op type)
- **GetInfo** will return the contents of the state file
- **Exists** will check if the key exists

Details
- A new abstraction will be introduced inside the `SegmentContainer`, named `MetadataStore`.
- The current `StreamSegmentMapper` and `SegmentStateStore` will be merged into one class (they are almost merged now) and renamed to `StorageMetadataStore` (TBD on a better sounding name)
     - This will be used for backwards compatibility and maybe unit testing. Long term this should be deprecated and removed.
- A `TableMetadataStore` will be implemented which, as described above, stores the metadata in a special Table Segment (MS).
- The StorageWriter will be modified to treat inexistent segments as empty segments (provided the metadata indicates the length of the segment is 0). This means the segment will be created in Tier2 on the first write vs when the user requests that.

Subtasks:

- [x] Metadata  Store: #3148
- [x] Pinned Segment: #3149.
- [ ] Table Metadata Store: #3150.
- [ ] (TBD) Cleanup - remove the Storage option, replace with mock for unit tests.

This will be broken down into multiple tasks:
- Refactor

### LINKED ISSUE #3150: Segment Store: Table Metadata Store
**Problem description**
See #3075 for context.
This requires #3148, #3149 and #2878 already merged in. 

**Problem location**
StreamSegmentContainer

**Suggestions for an improvement**
Create the `TableMetadataStore` that implements `MetadataStore` (#3148) and which uses Table Segments (#2878) to store Segment Metadata.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Switched the permanent storage for the Segment Container Metadata to be an internal, pinned, Table Segment. This is managed via a new component `TableMetadataStore`.
    - This Table Segment has a reserved name, and is unique per Container (each container has one).
    - It is pinned to Memory, which means it will never be evicted. It is created (if necessary) upon bootstrapping the Container for the first time.
- Retired `StorageMetadataStore` which was storing Segment Metadata in Tier 2 state files

**Purpose of the change**  
Fixes #3150.
Fixes #3075.
Fixes #3074.

**What the code does**  
- Defined the Table Metadata Segment (TMS), which is a special, internal Segment, for each Container. This is a Table Segment, where for each Table Entry, the Keys are Segment Names, and the Values are the serialized forms of the Segment Metadata (formerly known as "State Files").
    - A bit of chicken-and-the-egg problem had to be solved here because we cannot map anything to the metadata until the Container is started, yet we want to have this special segment already mapped **before** receiving any external requests. This resulted in a bit of refactoring work in `StreamSegmentContainer`, especially in the initialization phase.
- Created `TableMetadataStore`, a subclass of `MetadataStore` that stores Segment Metadata in the TMS, as follows:
    - Segment Creation: conditional update (key=segment name, value=empty `SegmentInfo`), conditioned on the entry not existing yet. If it exists, it throws `StreamSegmentExistsException`).
    - Segment Deletion: unconditional removal (key=segment name). This is an idempotent operation, and returns true/false based on whether the Segment actually had an entry
    - GetInfo: TableSegment.get(key=segment name), which throws `StreamSegmentNotExistsException` if already exists.
    - Segment Eviction (from memory): unconditional update(key=segment name, value=current `SegmentInfo`). 
- Note that the `StreamSegmentContainer` and `MetadataStore` ensure that the methods above get invoked at the right time, so there will never be a race between create/update(evict)/delete, nor will there be an update(evict) if the Segment hasn't been created yet.

**How to verify it**  
New unit tests added to verify specific functionality.
All existing unit tests must pass consistently.
Integration and system tests must pass.
SelfTest run must pass with a setup creating and merging transactions frequently.

### CODE REVIEW

File: segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/tables/TableStore.java [hunk 1]
```diff
@@ -61,6 +65,18 @@ default int maximumValueLength() {
...
 
+    /**
+     * Generates a set of {@link AttributeUpdate}s that set the initial Attributes on a newly create Table Segment.
+     *
+     * Attributes:
+     * * {@link Attributes#TABLE_INDEX_OFFSET} is initialized to 0.
+     *
+     * @return A Collection of {@link AttributeUpdate}s.
+     */
+    static Collection<AttributeUpdate> getInitialTableAttributes() {
```
Comment (andreipaduroiu) [inline segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/tables/TableStore.java]: I will be fixing this mess with #3273 so that I don't have to pollute this interface with these details.

File: shared/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java [hunk 2]
```diff
@@ -194,6 +182,18 @@ public static String getSegmentChunkName(String segmentName, long offset) {
...
     }
 
+    /**
+     * Gets the name of the Segment that is used to store the Container's Segment Metadata. There is one such Segment
+     * per container.
+     *
+     * @param containerId The Id of the Container.
+     * @return The Metadata Segment name.
+     */
+    public static String getMetadataSegmentName(int containerId) {
```
Comment (fpj) [inline shared/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java]: I know this method is trivial, but for completeness, can we add a test case to `StreamSegmentNameUtilsTests` to exercize this method?

Comment (andreipaduroiu) [reply shared/src/main/java/io/pravega/shared/segment/StreamSegmentNameUtils.java]: Added

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/IndexWriter.java [hunk 3]
```diff
@@ -294,7 +293,7 @@ private void generateBackpointerUpdates(BucketUpdate update, UpdateInstructions
                         updateInstructions.withAttribute(generateBackpointerUpdate(keyUpdate.getOffset(), previousOffset.get()));
                     }
 
-                    updateInstructions.entryAdded();
+                  updateInstructions.entryAdded();
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/IndexWriter.java]: I'm sorry for the tiny ask, but can you fix this indentation, please?
