### PR TITLE
Issue 1433: Modify Cluster interface to return specific exceptions

### LINKED ISSUE #1433: Modify Cluster interface to return specific exceptions
**Problem description**
Cluster abstraction has an `addListener` method that returns generic `Exception`. It should instead return specific exceptions. Moreover other methods like `registerHost` and `deregisterHost` should throw checked exceptions.

**Problem location**
`Cluster.java` interface in `common/src/main/java/io/pravega/common/cluster/Cluster.java`

**Suggestions for an improvement**
Methods in the Cluster interface should throw specific checked exceptions.

### PR DESCRIPTION
**Pull request by fpj**
**Change log description**

* Creates a `ClusterException` class to create a scope for the exceptions the `Cluster` interface throws.
* Makes `ClusterException` unchecked to follow the pattern used with `StoreException`.

**Purpose of the change**
Fixes #1433 

Address the comments here:
https://github.com/pravega/pravega/pull/1334#discussion_r121228541

**What the code does**
The implementation of cluster based on zookeeper has calls that throw a generic exception. This happens because the Curator lib throws a generic exception on errors. This pull request basically reduces the scope of the exception and transforms it into a `ClusterException`, which is a class created in this pull request.

As mentioned above, I have made `ClusterException` unchecked to follow the pattern used in `StoreException`, but I could be convinced to make it checked.

**How to verify it**
Run tests.

### CODE REVIEW

**Comment by fpj** [comment]
@tkaitchuck I tried to move it out of common, and then I found at least one reference in the segment store, specifically in the segment container manager and to register the host in the zk segment container manager. If I go ahead and do it, then I'll need to do registration in a different and it will possibly entail some duplication of code, not a lot, though.

@shiveshr yeah, I thought the same thing. I had a look at the methods throwing exception in the cluster implementation, and could only find that cache initialization. I'll have another look just in case, though.

**Comment by skrishnappa** [comment]
I guess after this change, some caller code can be cleaned up, which were forced to catch this generic checked exception.

**Comment by tkaitchuck** [comment]
Ok. It sounds like it can't simply be moved into the controller impl. Right now we have packages for interfaces for the client to depend on the controller (controller-api) the client and the controller to depend on SSS (protocol). Should we put ito into one of these or move it into another package in shared? We don't really have a package for things where SSS depends on the controller. But I don't want to simply dump things meeting those criteria into common because that really isn't what common is intended for.

**Comment by fpj** [comment]
I did some further investigation on this issue. The artifact that we are generating in `shared` for the controller is `controller-api` and moving `Cluster` and related classes there seems odd because this is not really part of the controller api. One option would be make it more generic and call the artifact `controller-utils` or something similar.

Another option is that we create a new artifact in `shared` just for this. Sounds a bit excessive given that it is a small group of classes, but it is an option.

And, of course, we can just keep it where it is for now until we have a better plan.

let me know what you people think. cc/ @shiveshr @tkaitchuck

**Comment by tkaitchuck** [comment]
I think there is a larger refactoring here. Why don't we submit this PR as-is and create another to refactor/move the code as needed.

File: common/src/main/java/io/pravega/common/cluster/ClusterException.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ *
+ * Licensed under the Apache License, Version 2.0 (the "License");
+ * you may not use this file except in compliance with the License.
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.common.cluster;
+
+public class ClusterException extends RuntimeException {
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/cluster/ClusterException.java]: I'm not sure this should be runtime. Do we expect that there is nothing the caller can do about this?

**Comment by fpj** [comment]
I created issue #1529

File: common/src/main/java/io/pravega/common/cluster/ClusterException.java (hunk 1 above)
Comment (fpj) [inline common/src/main/java/io/pravega/common/cluster/ClusterException.java]: Here is my reasoning to make this runtime, you let me know if it makes sense.

We are throwing this exception because of an error while dealing with the component that backs the cluster implementation, in our case zookeeper. I'd expect the implementation internally to retry whenever possible and only throw when not possible. If this is right, then there isn't really anything the application can do.

Also, it doesn't necessarily justify, but I'm following what we adopted for `StoreException` in the controller. If we change it here, then perhaps we should change out there too.
