### PR TITLE
Issue 1916: End of Data notification for a readergroup.

### LINKED ISSUE #1916: Stream termination
**Problem description**
Say we want to process all the data of a sealed stream and notify the readers that the data has been entirely read. If the stream is sealed, then the last segments of the stream are sealed and they have no successors. This feature is useful to process the stream data with a batch job.

The previous description assumes a sealed stream, but it might be possible in a follow-up extension to relax this assumption and consider, for example, a subset containing only sealed segments, essentially discarding only the open segments.

**Problem location**
Stream reader, client.

**Suggestions for an improvement**
Enable a notification via the reader API that indicates the end of the stream, initially, for a sealed stream. To make sure that all segments are entirely read in the presence of reader crashes, we need agreement on the end of each segment across all segments. We need to implement coordination using the state synchronizer.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
Enable end of data notification for a reader group

**Purpose of the change**
Fixes #1916 

**What the code does**
Enables end of data notification for a reader group.
```
ReaderGroup readerGroup = groupManager.createReaderGroup(GROUP_NAME, ReaderGroupConfig
        .builder().build(), Collections.singleton(SEALED_STREAM));

readerGroup.getEndOfDataEventNotifier(executor).registerListener(event -> {
      //custom action e.g: close all readers
});
```
**How to verify it**
Tests should pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 1]
```diff
@@ -210,7 +210,16 @@ boolean isCheckpointComplete(String checkpointId) {
     boolean hasOngoingCheckpoint() {
         return checkpointState.hasOngoingCheckpoint();
     }
-    
+
+    /**
+     * This functions returns true if the readers part of reader group for sealed streams have completely read the data.
+     * @return true if end of data. false if there are segments to be read from.
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: New line before @return.

File: client/src/main/java/io/pravega/client/stream/notifications/events/EndOfDataEvent.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.stream.notifications.events;
+
+/**
+ * Class to represent a end of data event. This event is generated when all the streams(sealed) managed by the reader
+ * group are completely read by the readers.
+ */
+public class EndOfDataEvent extends Event {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/notifications/events/EndOfDataEvent.java]: While reviewing this, I noticed that the use of the term "event" is overloaded in our API. Is it worth changing the term "event" in this context to "notification" to disambiguate?

If we do it, then we need to change for segment event as well, so we could do it in a separate PR.

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+    public EndOfDataEventNotifier(final NotificationSystem notifySystem,
+                                  final Supplier<StateSynchronizer<ReaderGroupState>> synchronizerSupplier,
+                                  final ScheduledExecutorService executor) {
+        super(notifySystem, executor);
+        this.synchronizerSupplier = synchronizerSupplier;
+    }
+
+    @Override
+    @Synchronized
+    public void registerListener(final Listener<EndOfDataEvent> listener) {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: These register/unregister methods are identical to the ones for segment event, we should consider duplicating the code and moving it to an abstract class.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 4]
```diff
@@ -210,7 +210,16 @@ boolean isCheckpointComplete(String checkpointId) {
...
+     */
+    @Synchronized
+    public boolean isEndOfData() {
+        return futureSegments.isEmpty() && assignedSegments.values().stream().allMatch(Map::isEmpty);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: What about unassigned segments?

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+import lombok.extern.slf4j.Slf4j;
+
+@Slf4j
+public class EndOfDataEventNotifier extends AbstractEventNotifier<EndOfDataEvent> {
+    private static final int UPDATE_INTERVAL_SECONDS = Integer.parseInt(
+            System.getProperty("pravega.client.endOfDataEvent.poll.interval.seconds", String.valueOf(120)));
+    private final Supplier<StateSynchronizer<ReaderGroupState>> synchronizerSupplier;
+    private final AtomicBoolean pollingStarted = new AtomicBoolean();
+    @GuardedBy("$lock")
+    private ScheduledFuture<?> future;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: Please use a better name

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+        synchronizer.close();
+    }
+
+    @Override
+    public String getType() {
+        return EndOfDataEvent.class.getSimpleName();
+    }
+
+    private void checkAndTriggerEndOfStreamNotification() {
+        this.synchronizer.fetchUpdates();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: I think there is an opportunity for optimization here if we refactor a bit. 
There multiple types of notifications with multiple listeners which all do the same thing, they fetch the latest state, run some test against it and then trigger a notification. There is no reason for each to be running their own threads to periodically re-fetch the same data.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 1 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: done.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 4 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: done.

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java (hunk 5 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: done.

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java (hunk 3 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: Refactored the code.

File: client/src/main/java/io/pravega/client/stream/notifications/events/EndOfDataEvent.java (hunk 2 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/notifications/events/EndOfDataEvent.java]: Refactored the code to use the term notification.

File: client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java (hunk 6 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/notifications/notifier/EndOfDataEventNotifier.java]: Yes, this can be optimized. Planning to do this in the following fashion. Please review. 
Will do this optimization as part of a separate pull request.
```
// each notifier add the logic to trigger notification here.
final List<Consumer<ReaderGroupState>> listOfConsumers = new CopyOnWriteArrayList<>();
 
Supplier<ReaderGroupState> readerGroupStateSupplier = () -> {
                    synchronizer.fetchUpdates();
                    return synchronizer.getState();
                };

Supplier<CompletableFuture<Void>> chkAndNotify = () -> FutureHelpers.delayedFuture(Duration.ofSeconds(pollingIntervalInSeconds), executor)
                                                                    .thenApply(v -> readerGroupStateSupplier.get())
                                                                    .thenAccept(readerGroupState ->
																					listOfConsumers.forEach(c -> c.accept(readerGroupState)));
Supplier<Boolean> conditionSupplier = () -> isPollingNotifierPresent(); // loop only if Polling Notifier is present.

CompletableFuture<Void> r = FutureHelpers.loop(conditionSupplier, chkAndNotify, executor);
```

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 7]
```diff
@@ -214,9 +215,14 @@ private long getRemainingBytes(SegmentMetadataClientFactory metaFactory, StreamC
...
-    public Observable<SegmentEvent> getSegmentEventNotifier(ScheduledExecutorService executor) {
+    public Observable<SegmentNotification> getSegmentNotifier(ScheduledExecutorService executor) {
         checkNotNull(executor, "executor");
         return this.notifierFactory.getSegmentNotifier(this::createSynchronizer, executor);
     }
 
+    @Override
+    public Observable<EndOfDataNotification> getEndOfDataNotifier(ScheduledExecutorService executor) {
+        checkNotNull(executor, "executor");
+        return this.notifierFactory.getEndOfDataNotifier(this::createSynchronizer, executor);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Perhaps rather than a Synchronizer factory, that is re-created and re-read every time, it could just pass in the Synchronizer. They are, after all capable of updating. If the notificationSystem or NotificationFactory was given one when it was constructed, it would only ever need to get the updates by calling fetchUpdates(). I think this model would work better with an internal threadpool though...

Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Done. Refactored the code to ensure a single stateSynchronizer instance is used by the notifiers.
