### PR TITLE
Issue 5465 Re-creating Reader Group with same name fails

### LINKED ISSUE #5465: Issue when recreating a ReaderGroup with the same name as a previously deleted ReaderGroup
**Problem description**
After deleting a `ReaderGroup` on the controller using `controller.deleteReaderGroup`, recreating the group using the same name with the call `controller.createReaderGroup` fails with the following stacktrace:
```
io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
	at io.pravega.controller.task.Stream.StreamMetadataTasks.lambda$createReaderGroupTasks$34(StreamMetadataTasks.java:406)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.pravega.common.concurrent.Futures.lambda$completeOn$0(Futures.java:62)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: creationTime table: _system/_tables/test/_readergroups/group/metadata.#.6210110a-41f9-4ee9-b41b-709c640f5c49
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:550)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:126)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:39)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:72)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:204)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:121)
	... 1 more
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$13(SegmentHelper.java:419)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 8 more
```  
This can be recreated using the following snippet of code:
```java
Controller controller = controllerWrapper.getController();
String scope = "test";
String stream = "test";
controller.createScope(scope).join();
StreamConfiguration config = StreamConfiguration.builder().scalingPolicy(ScalingPolicy.fixed(1)).build();
controller.createStream(scope, stream, config).join();
String rgName = "myreadergroup";
controller.createReaderGroup(scope, rgName, ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                                                    .stream("test/test").build()).join();
ReaderGroupConfig rgConfig = controller.getReaderGroupConfig(scope, rgName).join();
controller.deleteReaderGroup(scope, rgName, rgConfig.getReaderGroupId(), rgConfig.getGeneration()).join();
controller.createReaderGroup(scope, rgName, ReaderGroupConfig.builder().disableAutomaticCheckpoints()
                                                                     .stream("test/test").build()).join();
```

**Problem location**
Controller

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by pbelgundi**
**Change log description**  

This PR fixes the following:
1. If a Reader Group is created on Controller and then deleted and then recreated again with same scope/name the new create fails with an exception.
2. Fix minor review comments in PR 5462

**Purpose of the change**  
Fixes #5465

**What the code does**  
The issue occurs because deleteReaderGroup API did not clean the Reader group cache after the ReaderGroup was deleted hence the old ReaderGroupId from cache was used for creating table for the new ReaderGroup cause conflict on Segment Store.

**How to verify it**  
All Unit and Integration tests should pass.
Added a new test to verify ReaderGroup recreation works post delete as long as it is recreated with a new UUID.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesReaderGroup.java [hunk 1]
```diff
@@ -156,7 +156,11 @@ private String getMetadataTableName(String id) {
 
     @Override
     public CompletableFuture<Void> delete() {
-        return getId().thenCompose(id -> Futures.toVoid(storeHelper.deleteTable(getMetadataTableName(id), false)));
+        return getId().thenCompose(id -> storeHelper.deleteTable(getMetadataTableName(id), false)
+        .thenCompose(v -> {
+            this.idRef = new AtomicReference<>(null);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesReaderGroup.java:161]: actually refresh the idRef in the "refresh" method of this class. otherwise this delete could have happened on a different controller while this controller actually continues to use a cached object which a stale idref.

**Review by shiveshr — APPROVED** [review]
LGTM

File: test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java [hunk 2]
```diff
@@ -163,7 +163,7 @@ public void testControllerService() throws Exception {
         //Different name in same scope
         createAStream(scope1, streamName2, controller, config3);
         createAStream(scope1, streamName3, controller, config3);
-
+        /*
```
Comment (shiveshr) [inline test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java:166]: why have we commented this out? 
we should remove the code if its not to be used

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesReaderGroup.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesReaderGroup.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java (hunk 2 above)
Comment (pbelgundi) [reply test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java]: added by mistake. removed
