### PR TITLE
Issue 4147: Adjust txn ping to perform multiple pings per transaction

### LINKED ISSUE #4147: Writers failed and reader events stalled due to aborted transactions
**Problem description**

**Writers failed (1/4 )and writer & reader events stalled from `events:9,093,571`** due to aborted transactions on running the same stream with a workload of 
writers: 4, readers: 8, routing keys: 256, max events/sec: 1000, scaling policy: events_per_sec, target rate: 200, scale factor: 2, min segments: 4, record size: 100 bytes after running for **`23 hours`**.

Stream manager pod log:
```
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Got new data  Running for 23h 7m
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:9,093,548, events/sec:109, KB/sec:83.74609
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 607922, perSec:3.642942942942943, committed:303275, failed:0, aborted:304643, aborted but read: 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,540, events/sec:109, KB/sec:83.74609
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: New runtime for 057a643e-e83f-4bb9-8b05-b6809ee3dd95  Running for 23h 7m
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Dumping stats for stream longevity/mediumScaleTx
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Writers (4/4): events:9,093,548, events/sec:109, KB/sec:83.77637
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Transactions: started: 607922, perSec:3.642942942942943, committed:303275, failed:0, aborted:304643, aborted but read: 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:12:34,795] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,540, events/sec:109, KB/sec:83.77637

INFO  [2019-08-28 13:13:06,680] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:13:06,680] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,541, events/sec:109, KB/sec:83.71582
172.28.1.3 - - [28/Aug/2019:13:13:06 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1875 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-08-28 13:13:25,509] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: 
Received Error From task taskID : Got an aborted transaction, didn't expect that
java.lang.IllegalStateException: Got an aborted transaction, didn't expect that
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState$forkWatchProcess$watchProcess$1.run(PravegaWriterState.kt:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

INFO  [2019-08-28 13:16:26,908] io.pravega.longevity.utils.PerformanceUtils:  Blocked Waiting For ACK: times blocks: 0, average block time (ms): 0
INFO  [2019-08-28 13:16:26,908] io.pravega.longevity.utils.PerformanceUtils: Readers (8/8): events:9,093,569, events/sec:108, KB/sec:83.53613
172.28.1.3 - - [28/Aug/2019:13:16:26 +0000] "POST /v1/longevity/performance HTTP/1.1" 200 1869 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_131)" 1
INFO  [2019-08-28 13:16:45,621] io.pravega.longevity.testmanager.manager.TestPerformanceCollector: 
Received Error From task taskID : io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
io.pravega.client.stream.TxnFailedException: 
io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:94)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.close(SegmentTransactionImpl.java:100)
        at io.pravega.client.stream.impl.EventStreamWriterImpl$TransactionImpl.commit(EventStreamWriterImpl.java:263)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriterState.afterWrite(PravegaWriterState.kt:74)
        at io.pravega.longevity.testworker.workers.writers.PravegaWriter.start(PravegaWriter.java:151)
        at io.pravega.longevity.testworker.workers.writers.WriterWorkerManager.lambda$start$0(WriterWorkerManager.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.client.segment.impl.SegmentSealedException: 
SegmentSealed Exception for segment:longevity/mediumScaleTx/1.#epoch.0#transaction.000000000000000000000000000946b1 sealed for writer 8511bfbe-f840-42e5-85b9-f52b36a954f8
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.flush(SegmentOutputStreamImpl.java:521)
        at io.pravega.client.stream.impl.SegmentTransactionImpl.flush(SegmentTransactionImpl.java:88)
        ... 8 more

```

Controller logs during the writer failure occured:
```
2019-08-28 13:04:16,226 85097099 [epollEventLoopGroup-2-2] INFO  i.p.client.netty.impl.FlowHandler - Closing Flow 40518164 for endpoint 172.28.69.12
2019-08-28 13:04:16,226 85097099 [epollEventLoopGroup-2-2] INFO  i.p.controller.server.SegmentHelper - ReadTable _system/_tables/longevity/mediumScaleTx/transactionsInEpoch-0.#.8fb1379a-2996-4e87-a793-9b0c179bdb38 TableRead 174024189273964544.
2019-08-28 13:04:16,227 85097100 [controllerpool-8] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller API call with tag none failed with error:
io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: 00000000-0000-0000-0000-0000000945c9 table: _system/_tables/longevity/mediumScaleTx/transactionsInEpoch-0.#.8fb1379a-2996-4e87-a793-9b0c179bdb38
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$getEntry$22(PravegaTablesStoreHelper.java:278)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2019-08-28 13:12:51,049 85611922 [controllerpool-6] WARN  i.p.c.server.ControllerService - Transaction commit failed
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: mediumScaleTx Transaction: 00000000-0000-0000-0000-0000000946af State: ABORTED
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.controller.store.stream.StoreException$IllegalStateException: Stream: mediumScaleTx Transaction: 00000000-0000-0000-0000-0000000946af State: ABORTED
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:99)
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
        at io.pravega.controller.store.stream.PersistentStreamBase.lambda$validateCompletedTxn$152(PersistentStreamBase.java:1250)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 12 common frames omitted
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.6.0-2345.298015f
Zookeeper Operator : pravega/zookeeper:0.2.2
Pravega Operator:  pravega/zookeeper-operator:0.2.2
```

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**  `
Attempt multiple pings before timing out a transaction.

**Purpose of the change**  
Fixes #4147

**What the code does**  
Uses a square root to calculate the number of ping attempts that should be made.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/EventWriterConfig.java [hunk 1]
```diff
@@ -54,6 +55,7 @@
     private final boolean automaticallyNoteTime;
 
     public static final class EventWriterConfigBuilder {
+        private static final long MIN_TRANSACTION_TIMEOUT_TIME = 10000;
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/EventWriterConfig.java]: nit: Could we rename the variable to indicate the timeout here is in seconds `MIN_TRANSACTION_TIMEOUT_TIME_SECONDS`?

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/EventWriterConfig.java]: I want it to have the same units as the timeout below.

**Comment by tkaitchuck** [comment]
> This PR ensures the minimum txn lease is 10seconds which implies minimum ping interval is 3seconds which is lower than the earlier interval of 10seconds.

Yes. That is intended.

File: client/src/main/java/io/pravega/client/stream/EventWriterConfig.java (hunk 1 above)
Comment (andreipaduroiu) [reply client/src/main/java/io/pravega/client/stream/EventWriterConfig.java]: OK, then can we give it a suffix of `MILLIS` so that we know what unit it is in?

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java [hunk 2]
```diff
@@ -79,13 +74,11 @@ void stopPing(UUID txnID) {
...
-        if (pingInterval < MINIMUM_PING_INTERVAL_MS) {
-            log.warn("Transaction ping interval is less than 10 seconds(lower bound)");
-        }
-        //Ping interval cannot be less than KeepAlive task interval of 10seconds.
-        return Math.max(MINIMUM_PING_INTERVAL_MS, (long) pingInterval);
+    private long getPingInterval() {
+        //Provides a good number of attempts: 1 for <4s, 2 for <9s, 3 for <16s, 4 for <25s, ... 10 for <100s
+        //while at the same time allowing the interval to grow as the timeout gets larger.
+        double targetNumPings = Math.sqrt(txnLeaseMillis / 1000.0);
+        return Math.round(txnLeaseMillis / targetNumPings);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: This could end up being 0, correct? (If txnLeaseMillis<500).

Should we ensure that it is at least 1?

I know you ensure that it's at least 10000, but that's in a different file, so it wouldn't hurt to be on the safe side here.

File: client/src/test/java/io/pravega/client/stream/impl/PingerTest.java [hunk 3]
```diff
@@ -41,12 +41,12 @@
 import static org.mockito.Mockito.times;
 import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.when;
+import static org.mockito.Mockito.*;
```
Comment (andreipaduroiu) [inline client/src/test/java/io/pravega/client/stream/impl/PingerTest.java]: I thought we didn't allow star imports ???

File: client/src/main/java/io/pravega/client/stream/EventWriterConfig.java (hunk 1 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/EventWriterConfig.java]: Done
