### PR TITLE
Issue 2653: Exceptions during unmarshalling of grpc auth headers pollute logs

### LINKED ISSUE #2653: Exceptions during unmarshalling of grpc auth headers pollute logs
**Problem description**
These harmless exceptions are polluting the logs.
```
2018-05-25 16:51:00,826 2784156 [grpc-default-executor-19] WARN  i.p.c.s.rpc.auth.PravegaInterceptor - Error while marshalling some of the headers
java.lang.IllegalArgumentException: ASCII header is named grpc-trace-bin.  Only binary headers may end with -bin
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
    at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
    at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:734)
    at io.grpc.Metadata$Key.of(Metadata.java:591)
    at io.grpc.Metadata$Key.of(Metadata.java:587)
    at io.pravega.controller.server.rpc.auth.PravegaInterceptor.lambda$interceptCall$0(PravegaInterceptor.java:55)
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at io.pravega.controller.server.rpc.auth.PravegaInterceptor.interceptCall(PravegaInterceptor.java:52)
    at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:520)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1700(ServerImpl.java:345)
    at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:460)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
`PravegaInterceptor.java`. 

**Suggestions for an improvement**
Drop the log or move it to `trace`.

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
* Checks only ASCII auth headers in `interceptCall`.

**Purpose of the change**
Fixes #2653.

**What the code does**
Previously, it was trying to populate `paramMap` in `interceptCall` using all headers, which was producing a large number of unnecessary stack traces. Here it checks only for the ASCII headers, which should reduce or eliminate completely the unnecessary errors. 

**How to verify it**
Observe fewer or no unnecessary stack traces coming from `interceptCall`.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 1]
```diff
@@ -54,7 +54,7 @@
                 paramMap.put(key,
                         headers.get(Metadata.Key.of(key, Metadata.ASCII_STRING_MARSHALLER)));
             } catch (IllegalArgumentException e) {
-                log.warn("Error while marshalling some of the headers", e);
+                log.trace("Error while marshalling some of the headers", e);
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: I am concerned that if we make this `trace`, we will never know that something happened. 

Would it make sense to do something different instead:
- Keep `log.warn`, but use `e.toString()` which will be a one-liner with just the exception type and message
- Add `log.trace` with `e`, which will output the stack trace, but only in trace mode.
    - We may even want to do this as `debug`.
    - Actually, is the stack trace even needed? If it's all internal to some external library, then all we'd need is the exception message and type, so no need for this second one.

**Comment by fpj** [comment]
I agree that we shouldn't silently swallow the exception by reducing the severity of the logging. As @tkaitchuck indicated in the issue, the key to reducing the occurrences of the stack trace in this issue is to avoid the exception altogether.

**Comment by arvindkandhare** [comment]
1. Reduced the log to a single line
2. Filtered the binary keys out

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 2]
```diff
@@ -49,12 +49,14 @@
     public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
 
         Map<String, String> paramMap = new HashMap<>();
-        headers.keys().stream().forEach(key -> {
+        headers.keys().stream()
+               .filter(key -> !key.endsWith(Metadata.BINARY_HEADER_SUFFIX))
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Could you explain why you are adding this filter? What is it filtering exactly and how does it help with not polluting the logs?

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 3]
```diff
@@ -49,12 +49,14 @@
...
+               .forEach(key -> {
             try {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: The indentation seems in correct with respect to the new code.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 4]
```diff
@@ -49,12 +49,14 @@
...
                 paramMap.put(key,
                         headers.get(Metadata.Key.of(key, Metadata.ASCII_STRING_MARSHALLER)));
             } catch (IllegalArgumentException e) {
-                log.warn("Error while marshalling some of the headers", e);
+                log.info("Error while marshalling some of the headers" + e);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Reducing the log message by removing the stack trace is not necessarily the right thing to do here. If there is an error, then it is best that the user knows about it and has detail. At the same time, I'm worried that we are simply logging a message and moving forward. It is like the error doesn't matter, and if it is the case, then why are we even throwing in the first place?

Comment (EronWright) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: May I suggest the following principle, that planned errors be treated differently from unplanned errors.   A planned error (i.e. an intentional part of program flow) need not have a stack trace.   For example, bad requests from a client are handled by validation logic and summarily rejected; there's no value in a server-side stack trace in that case (since the logic is working as intended).

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 2 above)
Comment (EronWright) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: I believe that this is related to the design of the auth plugin, which allows for arbitrary headers to be passed from client to server.  This filter imposes a constraint on the set of allowed headers.

I presented a more constrained and standards-based approach based on the `Authorization` header in #2385.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 4 above)
Comment (EronWright) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: (if you go with Andrei's suggestion, be sure to add `{}` to the message)

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 2 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: > I believe that this is related to the design of the auth plugin, which allows for arbitrary headers to be passed from client to server. This filter imposes a constraint on the set of allowed headers.

This is part of grpc header processing. This does not impose any new constraint on the set of allowed headers. Earlier we were trying to process all the headers but we expect only string headers. So we can ignore all the other headers safely.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 3 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Fixed.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 4 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Fixed.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 2 above)
Comment (EronWright) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Sorry, I mean that it is filtering out certain headers rather than passing all headers.
