### PR TITLE
Issue 1330: (SegmentStore) Async Writes to Tier1

### LINKED ISSUE #1330: SegmentStore Tier1 Async Writes
**Problem**
Writes to Tier1 (BookKeeper) are synchronous, which limits our ability to make most use of BK's available throughput.

**Suggestions for improvement**
Allow async writes to BookKeeper, throttled up to a value.

**BookKeeperLog**
- External API stays the same. No need to change the `DurableDataLog` contract. Perhaps a few wording changes in the JavaDoc to explain concurrent behavior.
- No write throttling in here.
- Retries/error handling
    - Remove current retry logic. If used in async mode, it is responsible for writing out-of-order - and mostly useless.
- On write failure
    - Based on empirical research (not documented anywhere I see), a write failure causes a ledger to be closed, which causes all subsequent writes to that ledger to fail with LedgerClosedException.
    - When a write fails:
        - If fatal (Fencing exception), bail out; do not do anything, and report error on all pending writes
        - If non-fatal (Not enough bookies, not reachable): retry all writes in order.
        - If LedgerClosed: create a new ledger (be wary of fencing) and do the same as for non-fatal above.
        - Care must be taken when doing retries to verify that subsequent writes haven't actually completed (after a failed write) - however as explained above, this should not happen.
- Ledger Rollover Handling
    - Normal rollover: a new ledger is created and pointer atomically swapped with old ledger, then closed.
    - Failed write: there is no new ledger. This will need to be handled above (in retries)

**DurableLogConfig** (or wherever appropriate)
- Add setting: maxConcurrentDataLogWrites (=2/3/4/8/...)
    - If this is set to 1, it will essentially behave as it is today, writing synchronously.
   - This value will likely need to be tweaked based on deployment scenario and actual performance.

**OperationProcessor**
- Allow concurrent Tier1 writes. 
    - State/OperationMetadataUpdater: careful to commit only the stuff that has been written to Tier1, not everything
    - This may require chaining States/Updates together, and we'll need to ack/commit them as acks are coming in from Tier1
- Introduce a new component between the `OperationProcessor` and `DurableDataLog` (named `DataFrameProcessor`?)
    - This accepts sealed DataFrames, and processes them in order, by shipping them to Tier1(DurableDataLog).
    - It keeps a "counter" of how many active/concurrent such requests we have at any given time.
    - If this counter is below N (N=throttle limit), any new requests will go directly to Tier1
    - If this counter is at or above N, any new requests will be put in a queue. This queue will be processed, in order, as requests to Tier1 complete and free up capacity.
    - This reduces the overhead of queuing/dequeuing for most requests (since when we are below N, we go directly to Tier1) so it should not add any extra latency for most of these calls.

### LINKED ISSUE #1355: StreamSegmentContainerTests sometimes fails
**Problem description**
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testMetadataCleanupRecovery FAILED
    java.lang.IllegalStateException: Expected the service MetadataCleanupContainer [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testMetadataCleanupRecovery(StreamSegmentContainerTests.java:918)
        Caused by:
        java.lang.IllegalArgumentException: newMetadata: New Metadata Deletion Flag is different from existing one.
```

**Problem location**
StreamSegmentReadIndex:294

### LINKED ISSUE #1419: Sporadic Unit Test/System Test Failures (log recovery)
Stack Trace:
```
Caused by: java.lang.IllegalArgumentException: newMetadata: New Metadata Deletion Flag is different from existing one.
        at io.pravega.common.Exceptions.checkArgument(Exceptions.java:118)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.exitRecoveryMode(StreamSegmentReadIndex.java:294)
        at io.pravega.segmentstore.server.reading.ContainerReadIndex.exitRecoveryMode(ContainerReadIndex.java:284)
        at io.pravega.segmentstore.server.logs.MemoryStateUpdater.exitRecoveryMode(MemoryStateUpdater.java:92)
        at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:337)

```

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Implements asynchronous, parallel writes to Tier1. Previously, the Segment Store (SSS) wrote to Tier1 in sequence, always waiting for a write to finish before issuing a new one. That was the simplest approach that could work, however it does have limitations (see parent issue).

Major changes:
- **OperationProcessor**: 
    - The Operation Queueing part stays the same.
    - The part where it writes to Tier1 via a DataFrame Builder has changed substantially. As it no longer waits for writes to Tier1 to finish, it builds Data Frames continuously and ships them to Tier1. Every Data Frame is associated with an appropriate Metadata Update Transaction (see below). Upon an ack (from Tier1) that a frame has been committed, all such update transactions up to and including the one for that frame are committed to the metadata. Should a frame fail to commit, all update transactions starting at the one associated with it will be failed.
    - Does not do any Tier1 throttling. That is the responsibility of the Tier1 implementation, since it's the closes to the wire.
- **OperationMetadataUpdater**
    - Split into 3 classes and changed to **chain** UpdateTransactions on top of each other - this is to support associating such update transaction with the corresponding Data Frame that is written to Tier1 (previously the entire class was exactly one Update Transaction, which could either be committed or rolled back).
    - ContainerMetadataUpdateTransaction is that part which deals with changes to the entire ContainerMetadata. It has a base (previous transaction), it can be rebased (when the previous transaction is committed) and can itself be committed to the main ContainerMetadata.
        - The vast majority of the code here was moved from OperationMetadataProcessor, with the rest being added to support chaining.
    - SegmenteMetadataUpdateTransaction is that part which deals with changes to a particular Segment's Metadata.
        - Similar to its ContainerMetadata counterpart, it has a base and can be applied to the main metadata.
- **DataFrameBuilder** (DFB)
    - Rewrote from being sequential to allowing frames to be committed asynchronously.
    - append(Operation) is a synchronous operation that writes the operation to the underlying DataFrameOutputStream (DFOS)
    - The DFOS has a synchronous callback that notifies the DFB when a frame is full.
    - The DFB then
        - Invokes its own callback (synchronously) that notifies the OperationProcessor that a frame is about to be committed (the OP then creates a Metadata transaction and associates it with the frame)
       - Submits the frame to Tier1 asynchronously and returns. Based on the outcome, asynchronously invokes either a success or failure callback which is then used by the OP to handle the situation (see above).
- **BookKeeperLog**
     - Significant rewrite to support parallel writes and guarantee write ordering across ledgers. This was previously "guaranteed" by the expectation that all calls would happen in sequence and never overlap.
     - Each new write is added to a queue. A Write Processor is invoked after every new add, after every write to BK completes and after every rollover.
    - The WriteProcessor: removes completed items from the head of the queue and attempts or reattempts to execute writes to BK.
    - Never will there be two writes to two different ledgers at the same time. If a rollover is detected (items in the queue start having a new ledger id), the Write Processor stops there until all writes to the current ledger are done. If a rollover and writes fail with LedgerClosedException, then such writes are upgraded to the current ledger and retried.
    - This queue also performs throttling.
- Additional Changes
    - Minor changes required to support all of these
    - Unit test changes and additions
    - DataFrames no longer have sequence numbers due to the asynchrony. This may be re-added in the future but its too complex now.

**Purpose of the change**
Fixes #1330. Performance improvement.
Fixes #1355. BugFix.
Fixes #1419. BugFix.

**What the code does**
See description.

**How to verify it**
New unit tests. Existing unit tests have been updated or enhanced.
Please refer to the Description field to figure out the general outline of the code.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java [hunk 1]
```diff
@@ -0,0 +1,857 @@
...
+import lombok.SneakyThrows;
+import lombok.extern.slf4j.Slf4j;
+import lombok.val;
+
+/**
+ * An update transaction that can apply changes to a ContainerMetadata.
+ */
+@Slf4j
+@NotThreadSafe
+class ContainerMetadataUpdateTransaction implements ContainerMetadata {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: Where is this class used?

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+ * Deque-like data structure that accepts elements in sorted order and provides optimized operations based on that.
+ * Note: This class was inspired by java.util.ArrayDeque, however that class does not allow subclassing outside of its package.
+ */
+@NotThreadSafe
+@SuppressWarnings("unchecked")
+public class SortedDeque<E extends SortedIndex.IndexEntry> {
+    //region Members
+
+    private static final int MIN_INITIAL_CAPACITY = 8;
+    private transient SortedIndex.IndexEntry[] elements;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: I copied the base code from ArrayDeque, and thus these fields too. You're right, this is not needed.

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+    private transient int lastSlotIndex;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: Added some blurb.

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+    //region Operations
+
+    /**
+     * Adds an item to the end of the Deque.
+     *
+     * @param item The Item to add
+     * @throws IllegalArgumentException If the item's key is not greater than the key of the last item in the Deque.
+     */
+    public void addLast(E item) {
+        SortedIndex.IndexEntry last = this.elements[(this.tail - 1) & this.lastSlotIndex];
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: It's alright. In that case it will not be needed since `head == tail` and all ops will fail. All these bitwise operations are there because the modulo operator is too slow. Check out the base implementation in `java.util.ArrayDeque`.

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 5]
```diff
@@ -0,0 +1,269 @@
...
+    }
+
+    /**
+     * Removes all the items from the end of the Deque up to and including the given item, but ONLY if the given item
+     * exists in the Deque.
+     *
+     * @param fromIncluding The Item to remove up to and including. If this item does not exist, no change is made.
+     * @return True if any changes were made (and thus fromIncluding exists), false otherwise.
+     */
+    public boolean removeLast(E fromIncluding) {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: 1. Renamed.
2. Yes, this is the exact behavior I want. The reason is that this is used to store checkpoints. **Before** I make any changes to the collection, I want to make sure my checkpoint exists. Otherwise I could unintentionally modify it in case of an error and lose data. If I didn't need this constraint then I wouldn't need this whole method, let alone the binary search part of it.

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 6]
```diff
@@ -0,0 +1,269 @@
...
+        this.tail = oldLength;
+    }
+
+    /**
+     * Performs a binary search in the Deque for an item whose key matches the given one.
+     *
+     * @param key The key to search.
+     * @return The index in the element in the Deque (NOT the index in the base array), or -1 if no such element exists.
+     */
+    private int binarySearch(long key) {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: I looked at that, but it's not what I need. `head` can be after `tail` in which case my array wraps around. The JRE's binary search does not handle that case, hence the need for my custom method.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java (hunk 1 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: Inside OperationMetadataUpdater. This was forked off the original OperationMetadataUpdater (which had 2 nested classes). 90% of it is unchanged code, however since this is a new file, the diff doesn' show that.

File: common/src/main/java/io/pravega/common/util/SortedDeque.java [hunk 7]
```diff
@@ -0,0 +1,269 @@
...
+    }
+
+    /**
+     * Creates a new instance of the SortedDeque class.
+     *
+     * @param initialCapacity The initial capacity.
+     */
+    public SortedDeque(int initialCapacity) {
+        this.elements = new SortedIndex.IndexEntry[Math.max(MIN_INITIAL_CAPACITY, initialCapacity)];
+        this.lastSlotIndex = this.elements.length - 1;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/SortedDeque.java]: done

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 8]
```diff
@@ -0,0 +1,253 @@
...
+
+    //region Processing
+
+    /**
+     * Processes the given item.
+     * * If the OrderedItemProcessor is below capacity, then the item will be processed immediately and the returned
+     * future is the actual result from the Processor.
+     * * If the max capacity is exceeded, the item will be queued up and it will be processed when capacity allows, after
+     * all the items added before it have been processed.
+     * * If an item before this one failed to process and this item is still in the queue (it has not yet been processed),
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: Yes. That is handled by this class auto-closing when it encounters an error. That looks like the easiest way to prevent new items from being added.. It's up to its user to create a new class and cleanup after that event.

Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: Updated the comment to describe that behavior.

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 9]
```diff
@@ -0,0 +1,253 @@
...
+     * the returned future will be cancelled with an IllegalStateException to prevent out-of-order executions.
+     * * This method guarantees ordered execution as long as its invocations are serial. That is, it only guarantees that
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: Oh yes it is. I forgot to update the comment. I made a special exception `OrderedItemProcessor.ProcessingException` which inherits from `IllegalStateException`

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 10]
```diff
@@ -0,0 +1,253 @@
...
+     * the item has begun processing or an order assigned if it returned successfully.
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: fixed

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 11]
```diff
@@ -0,0 +1,253 @@
...
+    @VisibleForTesting
+    protected void executionComplete(Throwable exception) {
+        Collection<QueueItem> toFail = null;
+        val failEx = new AtomicReference<Throwable>();
+        synchronized (this.stateLock) {
+            // Release the spot occupied by this item's execution.
+            this.activeCount--;
+            if (exception != null && !this.closed) {
+                // Need to fail all future items and close to prevent new items from being processed.
+                failEx.set(new ProcessingException("A previous item failed to commit. Cannot process new items.", exception));
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: Yes, not using AtomicReference is cleaner. However it doesn't like that I used in a lambda expression below (since i had to initialize it to either null or some value). I removed the lambda and the AtomicReference.

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 12]
```diff
@@ -0,0 +1,253 @@
...
+    //region Processing
+
+    /**
+     * Processes the given item.
+     * * If the OrderedItemProcessor is below capacity, then the item will be processed immediately and the returned
+     * future is the actual result from the Processor.
+     * * If the max capacity is exceeded, the item will be queued up and it will be processed when capacity allows, after
+     * all the items added before it have been processed.
+     * * If an item before this one failed to process and this item is still in the queue (it has not yet been processed),
+     * the returned future will be cancelled with an IllegalStateException to prevent out-of-order executions.
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: Oh yes it is. I forgot to update the comment. I made a special exception `OrderedItemProcessor.ProcessingException` which inherits from `IllegalStateException`

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java (hunk 9 above)
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: This mimics what BookKeeper LedgerHandle does and should be there regardless of the actual implementation details (this was a requirement as to how this class should function). 

I wanted it to have the same behavior. ProcessingLock is there just to ensure that executions do actually occur in order and that JVM thread scheduling (and bad luck) won't cause an out-of-order execution.

File: common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java [hunk 13]
```diff
@@ -0,0 +1,253 @@
...
+    /**
+     * Guards access to the individual item's processors. No two invocations of the processor may run at the same time.
+     */
+    private final Object processingLock = new Object();
+    @GuardedBy("stateLock")
+    private int activeCount;
+    @GuardedBy("stateLock")
+    private boolean closed;
+    @GuardedBy("stateLock")
+    private ReusableLatch emptyNotifier;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/OrderedItemProcessor.java]: I wanted something simpler and lower-level than a CompletableFuture. I looked at CF's implementation and it looked too heavyweight for what I needed. All I needed here was some sort of basic signaling.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java [hunk 14]
```diff
@@ -57,37 +63,49 @@ public void failSerializationAfterComplete(double ratio, IOException exception)
...
-            dataOutput.write(data, 0, breakPoint);
-            throw this.exception;
+    public boolean equals(Object obj) {
+        if (obj instanceof TestLogItem) {
+            TestLogItem other = (TestLogItem) obj;
+            boolean match = getSequenceNumber() == other.getSequenceNumber() && this.data.length == other.data.length;
+            if (match) {
+                for (int i = 0; i < this.data.length; i++) {
+                    if (this.data[i] != other.data[i]) {
+                        return false;
```
Comment (tkaitchuck) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java]: Do we expect that this line is reachable?

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTestHelpers.java [hunk 15]
```diff
@@ -143,8 +143,20 @@
...
+     * Returns a Consumer that, given an item, inserts that item into the given map in the order in which they were encountered.
+     */
+    static <T> Consumer<T> appendOrder(HashMap<T, Integer> map) {
+        return item -> map.put(item, map.size());
+    }
+
+    /**
+     * Empty consumer. Does nothing.
+     */
+    static <T> void doNothing(T ignored) {
```
Comment (tkaitchuck) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTestHelpers.java]: I think this could go in common

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 16]
```diff
@@ -615,4 +721,140 @@ public String toString() {
     }
 
     //endregion
+
+    //region Write
+
+    private static class Write {
+        final ArrayView data;
```
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: private?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 17]
```diff
@@ -239,101 +259,183 @@ public int getMaxAppendLength() {
...
+                // Invoke the BookKeeper write.
+                w.getLedger().asyncAddEntry(w.data.array(), w.data.arrayOffset(), w.data.getLength(), this::addCallback, w);
             } catch (Throwable ex) {
-                completionFuture.completeExceptionally(ex);
+                // Synchronous failure (or RetriesExhausted). Fail current write.
+                boolean isFinal = !isRetryable(ex);
+                w.fail(ex, isFinal);
+
+                // And fail all remaining writes as well.
+                for (int j = i + 1; j < toExecute.size(); j++) {
```
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Rather than failing this way, perhaps we could mark the class and fail them when they attempt to write.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 18]
```diff
@@ -115,12 +121,10 @@
...
         this.logNodePath = HierarchyUtils.getPath(logId, this.config.getZkHierarchyDepth());
-        this.lastAppendAddress = new AtomicReference<>(new LedgerAddress(0, 0));
         this.traceObjectId = String.format("Log[%d]", logId);
-        this.rolloverInProgress = new AtomicBoolean();
-        this.retryPolicy = config.getRetryPolicy()
-                                 .retryWhen(BookKeeperLog::isRetryable)
-                                 .throwingOn(Exception.class);
+        this.writes = new ArrayDeque<>();
+        this.writeProcessor = new SequentialAsyncProcessor(this::processWritesSync, this.executorService);
+        this.rolloverProcessor = new SequentialAsyncProcessor(this::rollover, this.executorService);
```
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Why are the write async processor and the rollover async Processor distinct?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 19]
```diff
@@ -521,66 +577,68 @@ private void persistMetadata(LogMetadata metadata, boolean create) throws Durabl
...
-            this.logMetadata = metadata;
+            // Update pointers to the new ledger and metadata.
+            LedgerHandle oldLedger;
+            synchronized (this.lock) {
+                oldLedger = this.writeLedger.ledger;
+                this.writeLedger = new WriteLedger(newLedger, ledgerMetadata);
+                this.logMetadata = metadata;
+            }
+
+            // Close the old ledger. This must be done outside of the lock, otherwise the pending writes (and their callbacks
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: minor: missing close parenthesis.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 20]
```diff
@@ -521,66 +577,68 @@ private void persistMetadata(LogMetadata metadata, boolean create) throws Durabl
...
+            // will be invoked within the lock, thus likely candidates for deadlocks).
+            Ledgers.close(oldLedger);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I'm worried about this step here. We must be absolutely sure of what goes into the ledger we are closing. Specifically, say that we close the old ledger while writing to the ledger concurrently. There are two possible outcomes:
- It closes correctly and we can determine what has gone in by calling `getLastAddConfirmed`. That will give us the number of the last entry that has gone in.
- The close call fails say because of a network partition. In this case,  another bk client could end up recovering the ledger and we won't know precisely what happened to the ledger until we are able to open it and likewise call `getLasAddConfirmed`.

In the heuristic proposed here:

http://bookkeeper.apache.org/docs/r4.4.0/bookkeeperLedgers2Logs.html

The step 4 of rollover isn't very specific about what happens in the case the close fails. The main issue we have is that if the bk client is unable to close the ledger cleanly, then it is possible that some other client will open and recover it, in which case the ledger is brought to a consistent state, but we don't really know what that state is unless we read it. In bk-land, we often use the entry ids to track what has gone in.

Note that even if we only perform the close once we have flushed all pending adds, we can still be left in an uncertain state with respect to the last write. Given that such scenarios should be rare, the right thing to do seems to be perform recovery over the tier one container data. We declare the failure to close cleanly a ledger during rollover as a fatal one and perform recovery.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java [hunk 21]
```diff
@@ -0,0 +1,857 @@
...
+     */
+    private void updateFrom(StorageMetadataCheckpointOperation operation) throws IOException, SerializationException, MetadataUpdateException {
+        Preconditions.checkState(this.recoveryMode, "Cannot bulk-update Metadata in non-recovery mode.");
+
+        DataInputStream stream = new DataInputStream(new GZIPInputStream(operation.getContents().getReader()));
+
+        // 1. Version.
+        byte version = stream.readByte();
+        if (version != CURRENT_SERIALIZATION_VERSION) {
+            throw new SerializationException("Metadata.updateFrom", String.format("Unsupported version: %d.", version));
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: As of right now we only have one Version. As we have multiple versions, this code will be updated to handle that and be backwards compatible. This check just verifies that we don't have an unsupported version - I expect that to stay there in addition to various version handling.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java [hunk 22]
```diff
@@ -35,7 +38,15 @@
...
-    private LogAddress address; // Assigned by DataFrameLog - no need to serialize.
+
+    /**
+     * The Frame Address within its serialization chain.
+     * This value is not serialized with the data frame, rather it is assigned by the DataFrameBuilder or DataFrameReader
+     * when constructing frames.
+     */
+    @Getter
+    @Setter
+    private LogAddress address;
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java]: Done.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java [hunk 23]
```diff
@@ -0,0 +1,857 @@
...
+        stream.writeByte(CURRENT_SERIALIZATION_VERSION);
+
+        // 2. Container Id.
+        stream.writeInt(this.containerId);
+
+        // Intentionally skipping over the Sequence Number. There is no need for that here; it will be set on the
+        // operation anyway when it gets serialized.
+
+        // 3. Unchanged Segment Metadata.
+        Collection<Long> unchangedSegmentIds = this.baseMetadata
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: Good idea. #1413

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java [hunk 24]
```diff
@@ -9,36 +9,43 @@
...
     private final DataFrameOutputStream outputStream;
     private final DurableDataLog targetLog;
-    private final ConsumerWithException<DataFrameCommitArgs, Exception> dataFrameCommitSuccessCallback;
-    private final Consumer<Throwable> dataFrameCommitFailureCallback;
-    private boolean closed;
+    private final Args args;
+    private final AtomicBoolean closed;
     private long lastSerializedSequenceNumber;
     private long lastStartedSequenceNumber;
+    private final AtomicReference<Throwable> failureCause;
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java]: Well, the class itself is not thread safe. `append` and `flush` cannot be called concurrently or bad things will happen. The reason I set this to AtomicReference is because it is most likely set via a callback. We submit the frame to Tier1 and then return synchronously. However we do attach an async exception listener to that call and if it fails, it sets the exception on this object. Since that's likely on a different thread, I wanted to make sure the value is properly set before the failure callback is invoked and someone else might need it.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 25]
```diff
@@ -173,75 +200,68 @@ public int getId() {
      * @param operations The initial set of operations to process (in order). Multiple operations may be processed eventually
      *                   depending on how the operationQueue changes while this is processing.
      */
+    @SneakyThrows
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: Fixed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 26]
```diff
@@ -173,75 +200,68 @@ public int getId() {
...
 
-        try {
-            // Process the operations in the queue. This loop will ensure we continue processing after a recoverable failure,
-            // as well as after we processed the entire collection, but found more items in need of processing.
-            while (!operations.isEmpty()) {
                 // Process the current set of operations.
-                processOperations(operations, state, dataFrameBuilder);
+                while (!operations.isEmpty()) {
+                    CompletableOperation o = operations.poll();
+                    if (processOperation(o, builder)) {
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: This returns false only if there was a problem with that operation's serialization(i.e., a bug in our code or some other preventable condition that affects that operation alone).

The `processOperation` will always throw if:
- It encounters `DataCorruptionException`
- It encounters `ObjectClosedException` (from the DataFrameBuilder)

In case of DCE, it's the end of the road for this container as it will shut down immediately. In case of OCE, it is handled by the catch below, and subsequent operations will get a new DataFrameBuilder instance (see `getDataFrameBuilder(recover:true)` right above)

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 27]
```diff
@@ -173,75 +200,68 @@ public int getId() {
...
+                        // Add the operation as 'pending', only if we were able to successfully append it to a data frame.
+                        // We only commit data frames when we attempt to start a new record (if it's full) or if we try to
+                        // close it, so we will not miss out on it.
+                        this.state.addPending(o);
+                    }
+                }
 
                 // Check if there are more operations to process. If so, it's more efficient to process them now (no thread
                 // context switching, better DataFrame occupancy optimization) rather than by going back to run().
                 if (operations.isEmpty()) {
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: There are two while loops. The goal of this is to see if any new operations arrived while we were busy processing the current operations. 

The Outer while loop will execute as long as we keep having new operations in. This is more efficient as it tries to fill up existing DataFrames, it does not deal with thread context switches and it adds virtually no latency.

The inner while loop simply processes all of the current operations. The if block checks to see if we have more operations to fetch (`operationQueue.poll`). If we don't, we flush the current frame out and exit. Otherwise we log a message and go back to the beginning of the outer loop.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 28]
```diff
@@ -173,75 +200,68 @@ public int getId() {
...
-     * <li> Pre-processes operation (in MetadataUpdater)
-     * <li> Assigns Sequence Number
-     * <li> Appends to DataFrameBuilder
+     * <li> Pre-processes operation (in MetadataUpdater).
+     * <li> Assigns Sequence Number.
+     * <li> Appends to DataFrameBuilder.
      * <li> Accepts operation in MetadataUpdater.
      * </ol>
-     * Any exceptions along the way will result in the immediate failure of the operations. Exceptions do not bubble out
+     * Any exceptions along the way will result in the immediate failure of the operation. Exceptions do not bubble out
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: The goal of this method is simple: Process the operation atomically (preprocess (metadata tx) + add to DataFrame + accept (into metadata txn)). If it fails to process (Metadata rejected it - which is almost always user error) the it returns false. If a more serious problem happened which was not due to this, an exception is thrown, which is handled in the parent method. 

I wanted to separate the user-errors from the actual Tier1 processing errors. I don't want to overload the user errors with yet another exception which wraps an inner exception and then handle that upstream. IMO, that would make the code look much uglier.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 29]
```diff
@@ -258,17 +278,30 @@ private boolean processOperation(CompletableOperation operation, DataFrameBuilde
...
+                dataFrameBuilder.append(operation.getOperation());
+                this.metadataUpdater.acceptOperation(entry);
+            }
 
             log.trace("{}: DataFrameBuilder.Append {}.", this.traceObjectId, operation.getOperation());
-            dataFrameBuilder.append(operation.getOperation());
-            this.metadataUpdater.acceptOperation(entry);
+        } catch (ObjectClosedException ex) {
+            // DataFrameBuilder is in a closed/failed state. We cannot proceed with this operation, or any other one,
+            // so we need to re-throw the exception for it to be handled upstream.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: Done.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 30]
```diff
@@ -258,17 +278,30 @@ private boolean processOperation(CompletableOperation operation, DataFrameBuilde
...
+
+            this.state.failOperation(operation, ex);
+            throw ex;
         } catch (Exception ex) {
-            operation.fail(ex);
+            this.state.failOperation(operation, ex);
+
             Throwable cause = ExceptionHelpers.getRealException(ex);
             if (cause instanceof DataCorruptionException) {
                 // Besides failing the operation, DataCorruptionExceptions are pretty serious. We should shut down the
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: updated the comment

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 31]
```diff
@@ -392,66 +401,213 @@ private boolean isFatalException(Throwable ex) {
...
+                            collectFailureCandidates(ex, commitArgs, toFail);
+                            if (isFatalException(ex)) {
+                                this.stopException = ex;
+                                CallbackHelpers.invokeSafely(this.fatalExceptionCallback, ex, null);
+                            }
+
+                            return;
+                        }
+
+                        if (this.stopException != null) {
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: This is the callback for a successful DataFrame commit. The line you're pointing at is reached only if the operation itself caused a fatal exception. Regardless of the operation status, it is still correct to update `highestCommittedDataFrame` since that is an accurate representation of the Tier1 state.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 32]
```diff
@@ -392,66 +401,213 @@ private boolean isFatalException(Throwable ex) {
...
+                    collectFailureCandidates(ex, commitArgs, toFail);
+                }
+            } finally {
+                toFail.forEach(this::failOperation);
+                autoCompleteIfNeeded();
+            }
+
+            if (isFatalException(ex)) {
+                synchronized (this.lock) {
+                    this.stopException = ex;
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: `collectFailureCandidates` is immediately followed by a statement that fails all of those operations, regardless of whether the exception was fatal or not (we need to fail them anyway). The line of code you point to is simply an inspector that determines if a special callback (into the OperationProcessor) should be invoked to notify of that fact.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java (hunk 14 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java]: Yes... At line 97 it does a SeqNo COmparison. Here it does an index-by-index comparison between the two items' data.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 33]
```diff
@@ -366,24 +365,34 @@ private boolean isFatalException(Throwable ex) {
...
+        @GuardedBy("lock")
+        private Throwable stopException;
+
+        QueueProcessingState(OperationMetadataUpdater metadataUpdater, MemoryStateUpdater stateUpdater, MetadataCheckpointPolicy checkpointPolicy,
+                             Consumer<Throwable> fatalExceptionCallback, Object lock, String traceObjectId) {
+            this.metadataUpdater = Preconditions.checkNotNull(metadataUpdater, "metadataUpdater");
+            this.logUpdater = Preconditions.checkNotNull(stateUpdater, "stateUpdater");
+            this.checkpointPolicy = Preconditions.checkNotNull(checkpointPolicy, "checkpointPolicy");
+            this.fatalExceptionCallback = Preconditions.checkNotNull(fatalExceptionCallback, "fatalExceptionCallback");
+            this.lock = Preconditions.checkNotNull(lock, "lock");
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: As discussed on Slack, I made this class non-static which removed the need for this, as well as a few more fields.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTestHelpers.java (hunk 15 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DataFrameTestHelpers.java]: done

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 34]
```diff
@@ -235,105 +243,153 @@ public void initialize(Duration timeout) throws DurableDataLogException {
...
+    /**
+     * Gets an ordered list of Writes to execute.
+     */
+    private List<Write> getWritesToExecute() {
+        // Clean up the write queue of all finished writes that are complete (successfully or failed for good)
+        if (!this.writes.removeFinishedWrites()) {
+            return Collections.emptyList();
+        }
+
+        // Calculate how much estimated space is there in the current ledger.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: done

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 35]
```diff
@@ -235,105 +243,153 @@ public void initialize(Duration timeout) throws DurableDataLogException {
...
-            LoggerHelpers.traceLeave(log, this.traceObjectId, "tryAppend", traceId, data.getLength(), writeLedger.ledger.getId(), !completionFuture.isCompletedExceptionally());
-        };
+            if (rc == BKException.Code.LedgerClosedException) {
+                // LedgerClosed can happen because we just rolled over the ledgers. The way to detect this is to
+                // check if the ledger we were trying to write to is closed and whether we have a new ledger.
+                // If that's the case, retry the write with the new ledger.
+                WriteLedger currentLedger = getWriteLedger();
+                if (!currentLedger.ledger.isClosed() && currentLedger.ledger.getId() != handle.getId()) {
+                    // Note that we do not set a failure for this - this is considered normal operations (so we also
+                    // roll back the attempt count).
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: done

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 19 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: It's there on the next line

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 17 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: That's exactly what it does :)
`Write.fail` only finalizes the Write (with a failure) if the second argument (the boolean) is set to true. In this call, I set the second argument to `isFinal` - which is true only when the exception is not retryable. Otherwise the Write is marked and its attempt count preserved (it's already incremented). When we attempt to process it again, we see if we exceeded the max attempt count in which case we throw `RetriesExhaustedException`.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 20 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: As discussed offline, we shall do this in a separate task. Issue #1414 was made for tracking.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 36]
```diff
@@ -392,66 +401,213 @@ private boolean isFatalException(Throwable ex) {
...
-                    throw ex;
+        void commit(DataFrameBuilder.CommitArgs commitArgs) {
+            assert commitArgs.key() >= 0 : "DataFrameBuilder.CommitArgs does not have a key set";
+            log.debug("{}: CommitSuccess ({}).", this.traceObjectId, commitArgs);
+
+            List<CompletableOperation> toComplete = new ArrayList<>();
+            Map<CompletableOperation, Throwable> toFail = new HashMap<>();
+            try {
+                // Record the end of a frame in the DurableDataLog. No need for locking here, as the metadata has its own.
+                this.metadataUpdater.recordTruncationMarker(commitArgs.getLastStartedSequenceNumber(), commitArgs.getLogAddress());
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: This is occurring outside of the lock and metadataUpdater is not threadsafe.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 37]
```diff
@@ -392,66 +441,210 @@ private boolean isFatalException(Throwable ex) {
...
-         * Gets a value indicating whether there exist any pending operations in this state.
+         * Creates a checkpoint keyed in with the given CommitArgs. This indicates that the DataFrame represented
+         * by the given args has been sealed and is about to be committed. This checkpoint will mark a point in the
+         * OperationMetadataUpdater that corresponds to the end of that DataFrame.
+         *
+         * @param commitArgs The CommitArgs to create a checkpoint for.
          */
-        boolean hasPending() {
-            return !this.pendingOperations.isEmpty();
+        void checkpoint(DataFrameBuilder.CommitArgs commitArgs) {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: This really needs a different name. It's not clear that this is not refering to a metadata checkpoint.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java (hunk 24 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java]: I don't want to add locks to append and flush since that has the potential to deadlock in case of failures (catch block happen with the lock acquired, and if the callback itself needs to acquire a lock externally (and mostly it does), and it's on a different thread, they will deadlock. My initial implementation was to have DataFrameBuilder 100% thread safe, but I stumbled across these problems so much that I decided to simplify it.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 26 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: The operation is already failed with the proper exception. It is up to the user (I.e.`AppendProcessor`, `PravegaRequestProcessor` to log the exception that it failed with). There is no point in double-logging it here.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 38]
```diff
@@ -392,66 +401,213 @@ private boolean isFatalException(Throwable ex) {
...
+         * off the pendingOperations queue that are affected. While the metadata is rolled back, the operations themselves
+         * are not failed (since this method executes while holding the lock).
+         *
+         * @param ex         The Exception that triggered the failure.
+         * @param commitArgs The CommitArgs that points to the DataFrame which failed to commit.
+         * @param target     A Map where the failure candidates will be collected. Key=Operation, Value=Failure Exception.
          */
-        void fail(Throwable ex) {
+        @GuardedBy("lock")
+        private void collectFailureCandidates(Throwable ex, DataFrameBuilder.CommitArgs commitArgs, Map<CompletableOperation, Throwable> target) {
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: There are two invocations of this method. It does what you described in one case. In the other case, I have an existing map to which I add in 3 places. So I  need this passed as an argument.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 18 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: They have different jobs and can execute in parallel. During rollover, we create a new ledger, and then update metadata and close the existing ledger (and swap pointers). Creating a new ledger takes some time (500ms or so), and there is no reason to stop processing appends while that happens. As such we keep processing appends while we are concurrently working on rolling over. 

When we close the old ledger, the in-flight writes to that one will fail with LedgerClosedException, and we will detect a new ledger is in place at which point we retry those writes on the new ledger. The WriteProcessor is designed to not start writes on a new ledger until all writes to the previous one are done (otherwise we could have out-of-order writes).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 36 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: I changed this so it it records directly onto the metadata, which is what the metadata updater was doing anyway.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 37 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: I  renamed this to `frameSealed`

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 39]
```diff
@@ -392,66 +441,210 @@ private boolean isFatalException(Throwable ex) {
...
+        void commit(DataFrameBuilder.CommitArgs commitArgs) {
+            assert commitArgs.key() >= 0 : "DataFrameBuilder.CommitArgs does not have a key set";
+            log.debug("{}: CommitSuccess ({}).", traceObjectId, commitArgs);
+
+            List<CompletableOperation> toComplete = new ArrayList<>();
+            Map<CompletableOperation, Throwable> toFail = new HashMap<>();
+            try {
+                // Record the end of a frame in the DurableDataLog directly into the base metadata. No need for locking here,
+                // as the metadata has its own.
+                OperationProcessor.this.metadata.recordTruncationMarker(commitArgs.getLastStartedSequenceNumber(), commitArgs.getLogAddress());
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: The metadata is not under guard. If you read the comment right above it explains that the metadata itself is thread safe.

File: common/src/main/java/io/pravega/common/function/Callbacks.java [hunk 40]
```diff
@@ -0,0 +1,25 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
Comment (fpj) [inline common/src/main/java/io/pravega/common/function/Callbacks.java]: You might have missed these <p>.

File: common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java [hunk 41]
```diff
@@ -26,7 +26,6 @@
 import java.util.function.Function;
 import java.util.function.Predicate;
 import java.util.stream.Collectors;
-
```
Comment (fpj) [inline common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java]: This change is unnecessary.

File: common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java [hunk 42]
```diff
@@ -0,0 +1,60 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
Comment (fpj) [inline common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java]: `<p>`.

File: config/config.properties [hunk 43]
```diff
@@ -223,6 +223,15 @@ bookkeeper.zkAddress=master.mesos:2181
 # This value must be the same for all Pravega SegmentStore instances in this cluster.
 #bookkeeper.zkMetadataPath=/segmentstore/containers
 
+# The maximum number of concurrent writes to BookKeeper. Writes are queued and will be executed in order.
+# Recommended values: 1-10. The best value will depend a lot on the installation details and BookKeeper capacity and
+# should be chosen empirically, based on performance tests.
+#bookkeeper.maxConcurrentWrites=5
```
Comment (fpj) [inline config/config.properties]: We should try to eventually get rid of this parameter, it sounds like a magic number (hard to figure out the exact value and justify).

File: common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java (hunk 42 above)
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/concurrent/SequentialAsyncProcessorTests.java]: fixed.

File: common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java (hunk 41 above)
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java]: fixed

File: common/src/main/java/io/pravega/common/function/Callbacks.java (hunk 40 above)
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/function/Callbacks.java]: This is my auto-formatter. It auto-formats all lines of code that have been touched. Proper JavaDoc is a bit HTML-like, hence the additions of all the paragraph tags.

File: common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java (hunk 41 above)
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/concurrent/FutureHelpersTests.java]: fixed

File: config/config.properties (hunk 43 above)
Comment (andreipaduroiu) [inline config/config.properties]: Well,  Sure. But I don't know how to automate it or make it dynamic. It should be set based on the performance of the actual installation of BookKeeper, and other settings, such as striping, may affect it. We may be able to make it a function of recent BK performance, but I don't have enough data points yet on how I may be able to do that.

File: common/src/test/java/io/pravega/common/util/SortedDequeTests.java [hunk 44]
```diff
@@ -0,0 +1,280 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
Comment (fpj) [inline common/src/test/java/io/pravega/common/util/SortedDequeTests.java]: I think I missed some files that have `<p>` in the license header, here is the list I got:

SortedDequeTests.java
Write.java
WriteQueue.java
WriteQueueTests.java
QueueStats.java

could you fix those, please?

Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/util/SortedDequeTests.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java (hunk 24 above)
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameBuilder.java]: I don't think you need to do all that. To protect the local state you just need to make lastSerializedSequenceNumber and lastStartedSequenceNumber into atomicLongs and do some compareAndSet / update() calls on them instead of blind assignment.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 32 above)
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: My concern is the lock is released between collectFailureCandidates and setting this exception. So what if a new pending operation is added in between? It will not be properly failed, and it may not see the stopException having been set. Either there needs to be a lock held the whole time (IE: moving this if block into the above try) or the order of these two needs to be reversed.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java (hunk 14 above)
Comment (tkaitchuck) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/TestLogItem.java]: That doesn't answer my real question: Under what circumstance would we have an item with the same sequence number but different data?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 17 above)
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: So this for loop can be deleted? If so lets remove it.
