### PR TITLE
Issue 2114 :  Ensure out of order acks are not sent by the append processor.

### LINKED ISSUE #2114: Missing DataAppended ack
**Problem description**
We have observed the following in one of the runs of `ReadTest#TestEventPointer`:

```
2017-11-22 11:55:31,100 16507 [segment-store-44] TRACE i.p.s.s.h.handler.AppendProcessor - ENTER storeAppend@218418205616 [Append(segment=Scope1/abc/0, writerId=2f6846e6-d8c1-4abc-aaff-9418e143e228, eventNumber=50, eventCount=1, data=UnpooledSlicedByteBuf(ridx: 0, widx: 29, cap: 29/29, unwrapped: CompositeByteBuf(ridx: 0, widx: 29, cap: 29, components=2)), expectedLength=null)].
2017-11-22 11:55:31,100 16507 [segment-store-44] TRACE i.p.s.s.store.StreamSegmentService - ENTER append@218418280507 [Scope1/abc/0, 29, [AttributeId = 2f6846e6-d8c1-4abc-aaff-9418e143e228, Value = 50, UpdateType = ReplaceIfEquals, AttributeId = 80000000-0000-0000-0000-000000000001, Value = 1, UpdateType = Accumulate]].

…

2017-11-22 11:55:31,105 16512 [segment-store-44] TRACE i.p.s.s.store.StreamSegmentService - LEAVE append@218418280507 [null] (elapsed=4415us).
2017-11-22 11:55:31,105 16512 [segment-store-44] TRACE i.p.s.s.h.handler.AppendProcessor - Resuming writing from connection [id: 0xed38c70a, L:/127.0.0.1:33636 - R:/127.0.0.1:42174]
2017-11-22 11:55:31,105 16512 [segment-store-44] TRACE i.p.s.s.h.handler.AppendProcessor - LEAVE storeAppend@218418205616 [null, null] (elapsed=4891us).
```

Observing the flow of:

https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java#L282

We see that between `LEAVE append@` and `LEAVE storeAppend@` there is no message other than an indication that auto-read of the channel is being reactivated (I think that log message is incorrect). We should however see a message like `Encoding message to send over the wire ` indicating that `DataAppended` has been serialized and sent.

Given the flow of log messages and the code, it feels like `AppendProcessor#handleAppendResult` is being called and `connection.send` is being invoked (otw `handleException` would have been called and we would have an error message in the logs).

Full log is 
[here](https://github.com/pravega/pravega/files/1496450/ReadTest_TestEventPointer.log)

**Problem location**
AppendProcessor, Netty.

**Suggestions for an improvement**
Fix the darn bug.

### PR DESCRIPTION
**Pull request by shrids**
Signed-off-by: shrids <sandeep.shridhar@emc.com>

**Change log description**
Ensure ack (WireCommands.DataAppended) is sent on wire before the next Append is written to the store.

**Purpose of the change**
Fixes #2114 

**What the code does**
Ensures outstandingAppend is cleared only after the ack is sent over wire, there by ensuring Acks are not send out of order.

**How to verify it**
Tests should pass.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 1]
```diff
@@ -255,9 +255,6 @@ private void handleAppendResult(final Append append, Throwable exception) {
             long previousEventNumber;
             synchronized (lock) {
                 previousEventNumber = latestEventNumbers.get(Pair.of(append.getSegment(), append.getWriterId()));
-                Preconditions.checkState(outstandingAppend == append,
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: This whole block needs to be moved to the bottom. The lastEventNumbers and waitingAppends need to be updated under the same lock. (it shouldn't be released).

I have a version of this locally, and a unit test, but it is not passing. At the moment I suspect it may be a mockito bug. I'll look into it more. But below is my test in case you want to try it out:
```
@Test(timeout=7000)
    public void testAcksInOrder() {
        String streamSegmentName = "testAppendSegment";
        UUID clientId = UUID.randomUUID();
        ReusableLatch blocker = new ReusableLatch(false);
        byte[] data = new byte[] { 1, 2, 3, 4, 6, 7, 8, 9 };
        StreamSegmentStore store = mock(StreamSegmentStore.class);
        ServerConnection connection = mock(ServerConnection.class);
        InOrder order = Mockito.inOrder(store, connection);
        Mockito.doAnswer(new Answer<Void>() {
            @Override
            public Void answer(InvocationOnMock invocation) throws Throwable {
                blocker.await();
                return null;
            }
        }).when(connection).send(any(DataAppended.class));
        AppendProcessor processor = new AppendProcessor(store, connection, new FailingRequestProcessor());

        setupGetStreamSegmentInfo(streamSegmentName, clientId, store);
        CompletableFuture<Void> result = new CompletableFuture<>();
        when(store.append(streamSegmentName, data, updateEventNumber(clientId, data.length),
                          AppendProcessor.TIMEOUT)).thenReturn(result);
        when(store.append(streamSegmentName, data, updateEventNumber(clientId, 2 * data.length, data.length, 1),
                          AppendProcessor.TIMEOUT)).thenReturn(CompletableFuture.completedFuture(null));

        processor.setupAppend(new SetupAppend(1, clientId, streamSegmentName));
        order.verify(store).getStreamSegmentInfo(anyString(), eq(true), eq(AppendProcessor.TIMEOUT));
        order.verify(connection).send(new AppendSetup(1, streamSegmentName, clientId, 0));
        order.verify(connection, atLeast(0)).resumeReading();
        processor.append(new Append(streamSegmentName, clientId, data.length, Unpooled.wrappedBuffer(data), null));
        order.verify(store).append(streamSegmentName,
                                   data,
                                   updateEventNumber(clientId, data.length),
                                   AppendProcessor.TIMEOUT);
        order.verifyNoMoreInteractions();
        Async.testBlocking(() -> {
            order.verifyNoMoreInteractions();
            result.complete(null);
        }, () -> {
            processor.append(new Append(streamSegmentName, clientId, 2*data.length, Unpooled.wrappedBuffer(data), null));
            order.verify(connection, atLeast(0)).resumeReading();
            order.verifyNoMoreInteractions();
            blocker.release();
        });
        order.verify(connection).send(new DataAppended(clientId, data.length));        
        order.verify(store).append(streamSegmentName,
                                   data,
                                   updateEventNumber(clientId, 2*data.length, data.length, 1),
                                   AppendProcessor.TIMEOUT);
        order.verify(connection).send(new DataAppended(clientId, 2*data.length));
        order.verify(connection, atLeast(0)).resumeReading();
        order.verifyNoMoreInteractions();
    }
```

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Done, updated the test case too to verify correct handling post the delayed DataAppended ack is sent.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 2]
```diff
@@ -279,10 +268,31 @@ private void handleAppendResult(final Append append, Throwable exception) {
...
                 DYNAMIC_LOGGER.incCounterValue(nameFromSegment(SEGMENT_WRITE_EVENTS, append.getSegment()), append.getEventCount());
             }
+
+            /* Reply (DataAppended in case of success, else an error Reply based on exception) has been sent. Next,
+             *   - clear outstandingAppend to handle the next Append message.
+             *   - ensure latestEventNumbers and waitingAppends are updated.
+             */
+            synchronized (lock) {
+                Preconditions.checkState(outstandingAppend == append,
+                        "Synchronization error in: %s.", AppendProcessor.this.getClass().getName());
```
Comment (fpj) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Let's change this error message to be more precise, something like: `Processing of appends out of order`. It is good practice to add the event numbers to help with the debugging in the case we ever hit here.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 3]
```diff
@@ -279,10 +268,31 @@ private void handleAppendResult(final Append append, Throwable exception) {
...
+                connection.send(dataAppendedAck);
                 DYNAMIC_LOGGER.incCounterValue(nameFromSegment(SEGMENT_WRITE_BYTES, append.getSegment()), append.getDataLength());
                 DYNAMIC_LOGGER.incCounterValue(nameFromSegment(SEGMENT_WRITE_EVENTS, append.getSegment()), append.getEventCount());
             }
+
+            /* Reply (DataAppended in case of success, else an error Reply based on exception) has been sent. Next,
+             *   - clear outstandingAppend to handle the next Append message.
+             *   - ensure latestEventNumbers and waitingAppends are updated.
+             */
+            synchronized (lock) {
```
Comment (fpj) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: I might be missing something, but I'm not convinced this is going to work. My recollection of the problem is that a segment store thread invokes this method and calls `connect.send`. The actual send is executed by a netty thread and according to the logs I have seen, the send returns without having actually sent it. I understand that the delay is due to thread scheduling.

The acks get out of order because the netty threads can also invoke this method, in which case, the send can be executed immediately causing the order issue we are observing.

If this insight is incorrect, then I need some justification of why that's the case.

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: `AppendProcessor#append` is invoked by a netty thread. This invokes `performNextWrite` which fetchs the append and writes it to the store (Async write). Once this write is complete it invokes `handleAppendResult()`. The step of writing on store is done by the segmentstore thread and most of the times `storeAppend(append).whenComplete(...) is executed on that thread.

Now `handleAppendResult()` internally sends the ack, clears `outstandingAppend` and then invokes `performNextWrite()`. PerformNextWrite will processing the next append only if  previous ack is sent, if there is a backlog then the segmentstore-store thread might be used for the next performNextWrite() invocation. Now, if there is a delay is sending ack and in the mean time a new Append is received `AppendProcessor#append and internally performNextWrite` is invoked on a different netty thread. (This used to cause a race in the older code, as the next append could cause the ack to be sent while older ack has not yet been sent.)

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java [hunk 4]
```diff
@@ -339,7 +345,80 @@ public void testEventNumbers() {
 
         verifyNoMoreInteractions(store);
     }
-    
+
+    /**
+     * Test to ensure newer appends are processed only after successfully sending the DataAppended acknowledgement
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java]: This test is good and helpful, but we also need a similar test where the first append is blocked when sending the DataAppened to the connection rather than when writing to the store.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 2 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Done, updated the comment to include the append number to help with debugging.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 5]
```diff
@@ -255,17 +255,6 @@ private void handleAppendResult(final Append append, Throwable exception) {
             long previousEventNumber;
             synchronized (lock) {
                 previousEventNumber = latestEventNumbers.get(Pair.of(append.getSegment(), append.getWriterId()));
-                Preconditions.checkState(outstandingAppend == append,
```
[the remark this answers is not in the document]
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: done, added it.

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java (hunk 4 above)
Comment (shrids) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/AppendProcessorTest.java]: The current test simulates the blocking of `Append` when sending of `DataAppended` to connection is delayed/blocked.
