### PR TITLE
Issue 3358: Fix stack overflow error caused by okhttp used by kubernetes-java client.

### LINKED ISSUE #3358: Stack overflow in system tests run
**Problem description**
These are the initial lines of the offending stack trace: 

```
io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest STANDARD_ERROR
    Exception in thread "OkHttp Dispatcher" java.lang.StackOverflowError
    	at com.sun.crypto.provider.GaloisCounterMode.processAAD(GaloisCounterMode.java)
    	at com.sun.crypto.provider.GaloisCounterMode.encryptFinal(GaloisCounterMode.java:459)
    	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1051)
    	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:1010)
    	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
    	at javax.crypto.Cipher.doFinal(Cipher.java:2376)
    	at sun.security.ssl.CipherBox.encrypt(CipherBox.java:315)
    	at sun.security.ssl.OutputRecord.encrypt(OutputRecord.java:264)
    	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:869)
    	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857)
    	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    	at okio.Okio$1.write(Okio.java:80)
    	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
    	at okio.RealBufferedSink.flush(RealBufferedSink.java:221)
    	at com.squareup.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:161)
    	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:735)
    	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
    	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
    	at io.kubernetes.client.apis.CoreV1Api$531.intercept(CoreV1Api.java:16648)
    	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
    	at io.kubernetes.client.apis.CoreV1Api$531.intercept(CoreV1Api.java:16648)
    	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
    	at io.kubernetes.client.apis.CoreV1Api$531.intercept(CoreV1Api.java:16648)
...
```

**Problem location**
System tests, kubernetes framework.

**Suggestions for an improvement**
Fix it.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Ensure networkInterceptors are cleared before invoking `io.kubernetes.client.apis.CoreV1Api#listNamespacedPodAsync`.

**Purpose of the change**  
Fixes #3358

**What the code does**  
The stack overflow error is due to `com.squareup.okhttp.OkHttpClient#networkInterceptors` being repeatedly added during the invocation of `CoreV1Api#listNamespacedPodAsync` .
This adds a workaround to ensure we clear the network interceptors before invoking the `listNamespacedPodAsync` . This workaround can be removed once this issue is resolved in the kubernetes-client /okhttp library.

**How to verify it**  
Verified that the tests run on the K8s cluster.

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 1]
```diff
@@ -196,6 +196,11 @@ public V1Namespace createNamespace(final String namespace) {
     @SneakyThrows(ApiException.class)
     public CompletableFuture<List<V1PodStatus>> getStatusOfPodWithLabel(final String namespace, final String labelName, final String labelValue) {
         CoreV1Api api = new CoreV1Api();
+
+        // Workaround based on okhttp issue https://github.com/square/okhttp/issues/2300
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Could you add issue #3361 to this comment, pls?

Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: done.

**Comment by shrids** [comment]
[Issue 3358: Fix stackoverflow error due to okhttp issue.](https://trello.com/c/79bZ0J6D/119-issue-3358-fix-stackoverflow-error-due-to-okhttp-issue)
