### PR TITLE
Issue 7036: Flush to storage for multiple segment store pods should work

### LINKED ISSUE #7036: Flush to storage for multiple segment store pods should work
**Describe the bug**
1. Right now when we are calling flush to storage, we need to pass the host IP address. If we have multiple segment store server than also we can pass only one IP address.
2. Ability to accept container range in flush to storage.

**To Reproduce**
1. Deploy pravega with multiple segment store instance
3. Call flush to storage

**Screenshots**

**Additional information**
Add any other information about the problem here, including the root cause if known.

### PR DESCRIPTION
**Pull request by Amit-Singh40**
**Change log description**  
Modify FlushToStorageCommand to detect the hosts for container automatically and accept range in flush to storage.

**Purpose of the change**  
Fixes #7036 

**What the code does**  
With this change you are not required to pass hosts and you can also pass range in flush to storage.

**How to verify it**  
At the time calling flush to storage don't pass the host.

### CODE REVIEW

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java [hunk 1]
```diff
@@ -32,7 +39,7 @@
  */
 public class FlushToStorageCommand extends ContainerCommand {
 
-    private static final int REQUEST_TIMEOUT_SECONDS = 30;
+    private static final int REQUEST_TIMEOUT_SECONDS = 60 * 5;
```
Comment (sachin-j-joshi) [inline cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:42]: Is this intentional?

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java [hunk 2]
```diff
@@ -46,35 +53,80 @@ public FlushToStorageCommand(CommandArgs args) {
...
+    }
+
+    private void validateArguments() {
+        Preconditions.checkArgument(getArgCount() > 0, "Incorrect argument count.");
+        final String container = getArg(0);
+        if (!NumberUtils.isNumber(container)) {
+            Preconditions.checkArgument(container.equalsIgnoreCase("all"), "Container argument should either be ALL/all or a container id.");
+            Preconditions.checkArgument(getArgCount() == 1, "Incorrect argument count.");
+        } else {
+            final int startContainer = Integer.parseInt(container);
```
Comment (sachin-j-joshi) [inline cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:120]: can use pass negative numbers?

**Review by sachin-j-joshi — COMMENTED** [review]
overall looks good to me.
There are couple of minor comments.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 2 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:120]: User should not pass negative values. Will add validation for that.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 1 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:42]: While testing flushtostorage we faced issue while with 30 secs timeout.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 2 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:120]: Added code to validate negative container.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 1 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:42]: This is intentional, we wanted to increase the timeout for flushtostorage. While testing flushtostorage we faced issue with 30 secs timeout.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 2 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:120]: Added code to validate negative container.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java [hunk 3]
```diff
@@ -46,35 +53,83 @@ public FlushToStorageCommand(CommandArgs args) {
...
+    }
+
+    private Map<Integer, String> getHosts() {
+        Map<Host, Set<Integer>> hostMap;
+        try {
+            @Cleanup
+            ZKHelper zkStoreHelper = ZKHelper.create(getServiceConfig().getZkURL(), getServiceConfig().getClusterName());
+            hostMap = zkStoreHelper.getCurrentHostMap();
+        } catch (Exception e) {
+            System.err.println("Exception accessing to Zookeeper cluster metadata: " + e.getMessage());
```
Comment (abhinb) [inline cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:98]: We do not keep any system.err/out .  Maybe you can add the message to the exception thrown below and remove this line or use a "output" if you have to convey something to the user.

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java [hunk 4]
```diff
@@ -46,35 +53,83 @@ public FlushToStorageCommand(CommandArgs args) {
...
+                        "if given as \"all\" all the containers will be persisted."), new ArgDescriptor("end-container-id", "The end container Id of the Segment Container that needs to be persisted, " +
+                "if given as \"all\" all the containers will be persisted."));
+    }
+
+    private Map<Integer, String> getHosts() {
+        Map<Host, Set<Integer>> hostMap;
+        try {
+            @Cleanup
+            ZKHelper zkStoreHelper = ZKHelper.create(getServiceConfig().getZkURL(), getServiceConfig().getClusterName());
+            hostMap = zkStoreHelper.getCurrentHostMap();
```
Comment (abhinb) [inline cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:96]: is empty hostmap handled elsewhere?

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java [hunk 5]
```diff
@@ -46,35 +53,83 @@ public FlushToStorageCommand(CommandArgs args) {
...
         output("Flushed the Segment Container with containerId %d to Storage.", containerId);
     }
 
     public static CommandDescriptor descriptor() {
         return new CommandDescriptor(COMPONENT, "flush-to-storage", "Persist the given Segment Container into Storage.",
-                new ArgDescriptor("container-id", "The container Id of the Segment Container that needs to be persisted, " +
-                        "if given as \"all\" all the containers will be persisted."),
-                new ArgDescriptor("segmentstore-endpoint", "Address of the Segment Store we want to send this request."));
+                new ArgDescriptor("start-container-id", "The start container Id of the Segment Container that needs to be persisted, " +
+                        "if given as \"all\" all the containers will be persisted."), new ArgDescriptor("end-container-id", "The end container Id of the Segment Container that needs to be persisted, " +
```
Comment (abhinb) [inline cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java:87]: looking at this description its not clear that it can accept a single container. i.e flush-to-storage <a_given_container_id>

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 3 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java]: Removed that line

File: cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java (hunk 5 above)
Comment (Amit-Singh40) [reply cli/admin/src/main/java/io/pravega/cli/admin/segmentstore/FlushToStorageCommand.java]: > looking at this description its not clear that it can accept a single container. i.e flush-to-storage <a_given_container_id>

I have updated it.

**Review by abhinb — APPROVED** [review]

**Review by sachin-j-joshi — APPROVED** [review]
LGTM
