### PR TITLE
Issue-4581: replaced the unsafe while loop with iterator looping

### LINKED ISSUE #4581: ConcurrentModification in StatsProviderImpl
**Problem description**
```
io.pravega.shared.metrics.MetricsProviderTest > testGauge FAILED
    java.util.ConcurrentModificationException
        at java.base/java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:735)
        at java.base/java.util.IdentityHashMap$KeyIterator.next(IdentityHashMap.java:826)
        at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
        at io.pravega.shared.metrics.StatsProviderImpl.startWithoutExporting(StatsProviderImpl.java:78)
        at io.pravega.shared.metrics.StatsProviderProxy.startWithoutExporting(StatsProviderProxy.java:45)
        at io.pravega.shared.metrics.MetricsProviderTest.setUp(MetricsProviderTest.java:35)
```

**Problem location**
```
        for (MeterRegistry registry : metrics.getRegistries()) {
            metrics.remove(registry);
        }
```

**Suggestions for an improvement**
Use the iterator to remove the item rather than modifying the map during iteration.

### PR DESCRIPTION
**Pull request by kevinhan88**
Signed-off-by: kevinhan88 <kevinhan88@gmail.com>

**Change log description**  
Replaced the unsafe while loop in cleaning up testing registries with iterator, otherwise it may sometimes got concurrentmodificationexception.

**Purpose of the change**  
Fixes #4581 

**What the code does**  
Inside StatsProviderImpl, started using iterator to loop registries inside, and then delete them one by one. However iterator.remove() is not supported.

**How to verify it**  
No functional changes, all tests should pass.

### CODE REVIEW

File: shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java [hunk 1]
```diff
@@ -75,9 +77,12 @@ public void start() {
     @Synchronized
     @Override
     public void startWithoutExporting() {
-        for (MeterRegistry registry : metrics.getRegistries()) {
-            metrics.remove(registry);
+
+        Iterator<MeterRegistry> iterator = metrics.getRegistries().iterator();
```
Comment (andreipaduroiu) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java]: I don't understand how this is any different from the code before. `for(X : Y)` is invoking `Y.iterator()` and looping through it.

What am I missing?

Comment (derekm) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java]: FWIW, I get the same failure with the new code (my line numbers will be different):
```io.pravega.shared.metrics.MetricsProviderTest > testGauge FAILED
    java.util.ConcurrentModificationException
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:735)
        at java.util.IdentityHashMap$KeyIterator.next(IdentityHashMap.java:826)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
        at io.pravega.shared.metrics.StatsProviderImpl.startWithoutExporting(StatsProviderImpl.java:85)
        at io.pravega.shared.metrics.StatsProviderProxy.startWithoutExporting(StatsProviderProxy.java:45)
        at io.pravega.shared.metrics.MetricsProviderTest.setUp(MetricsProviderTest.java:35)
```
Is this test working on some machines?

Comment (derekm) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java]: the latest change fixes it for me: `io.pravega.shared.metrics.MetricsProviderTest > testGauge PASSED`
