### PR TITLE
Issue 7388: Show total memory when validating memory settings in Segment Store

### LINKED ISSUE #7388: Show total memory when validating memory settings in Segment Store
**Describe the bug**
We validate the memory settings of the Segment Store against the total available physical memory. However, when an error occurs in this validation, the error message does not show the actual total physical memory detected. Having this number printed would help to understand how to fix the memory problems, specially in containerized environments. 

**To Reproduce**
Set some wrong memory settings in the segment store and look for the output:
```
2024-02-14 17:46:31,962 223  [main] INFO  i.p.s.server.host.ServiceStarter - MaxDirectMemorySize is 1073741824, Cache size is 1225472 and Netty DM is 1073741824
2024-02-14 17:46:31,967 228  [main] ERROR i.p.s.server.host.ServiceStarter - Could not create a Service with default config, Aborting.
java.lang.IllegalStateException: MaxDirectMemorySize(1073741824 B) along with JVM Xmx value(1073741824 B) is greater than the available system memory!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
```

**Screenshots**
n/a

**Additional information**
Include the total memory detected by the JVM in the  error message.

### PR DESCRIPTION
**Pull request by ojundi03**
**Change log description**  
Added physical memory to the output when validating memory settings in Segment Store.

**Purpose of the change**  
Fixes #7388.

**What the code does**  
Includes `totalMem` in the info output when a memory error occurs.

**How to verify it**  
Improperly configure memory.

### CODE REVIEW

**Comment by RaulGracia** [comment]
Thanks @ojundi03, but it looks like you have not signed-off your commits. Please, have a look to this https://github.com/pravega/pravega/wiki/Contributing#dco and, if you haven't, set up the security credentials to sign your commits. Thanks!

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java [hunk 1]
```diff
@@ -275,14 +275,14 @@ private void attachStorage(ServiceBuilder builder) {
     static void validateConfig(ServiceBuilderConfig config) {
         long xmx = Runtime.getRuntime().maxMemory();
         long nettyDirectMem = PlatformDependent.maxDirectMemory(); //Dio.netty.maxDirectMemory
+        long totalMem = ((com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getTotalPhysicalMemorySize(); 
         long maxDirectMemorySize = Long.parseLong(ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class)
                                                                    .getVMOption("MaxDirectMemorySize").getValue());
         maxDirectMemorySize = (maxDirectMemorySize == 0) ? xmx : maxDirectMemorySize;
         long cacheSize = config.getConfig(ServiceConfig::builder).getCachePolicy().getMaxSize();
-        log.info("MaxDirectMemorySize is {}, Cache size is {} and Netty DM is {}", maxDirectMemorySize, cacheSize, nettyDirectMem);
+        log.info("MaxDirectMemorySize is {}, TotalMem is {}, Cache size is {} and Netty DM is {}", maxDirectMemorySize, totalMem, cacheSize, nettyDirectMem);
```
Comment (RaulGracia) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java:283]: For better readability, as this is a log message, could you change the message to `Total Memory` instead of `TotalMem`? Also, I think it makes sense to put both the log message and `totalMem` as a first parameter in the log output instead of being second, as all the other parameters are in function of the total memory available in the instance.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Looks good, just a small comment.

**Review by abhinb — APPROVED** [review]

**Review by RaulGracia — APPROVED** [review]
