### PR TITLE
Issue 9207: Backup container operation seq no

### LINKED ISSUE #7314: Pravega Backup-Restore fails after node reboot or cache eviction.
**Describe the bug**
As noted in our tests, there are cases where after a node reboot or after Pravega internal cache eviction, the restored cluster seems to get into a non-functional state. It typically complains about keys not found in some internal table.

`Caused by: io.pravega.client.stream.InvalidStreamException: io.pravega.shaded.io.grpc.StatusRuntimeException: NOT_FOUND: get entry: key: _RGflinkmkzkxqqeq3spoxcnh289 table: _system/_tables/flink-longevity-0/streamsInScope.#.e82c1ef6-aaf7-4967-bf15-1d2913c099a9`

**To Reproduce**
Perform Pravega Backup-Restore.
Reboot the node.
Check if Pravega is operational.

**Screenshots**

**Additional information**
Add any other information about the problem here, including the root cause if known.

### PR DESCRIPTION
**Pull request by abhinb**
**Change log description**  
This changeset fixes the case where Pravega Backup-Restore fails as described in #7314 .  #7314 is caused due to a gap in the backup-restore process. Elaborating further. Pravega internal Tables save the operation sequence numbers running inside a Segment Store Container, into them trough a attribute called "PERSIST_SEQ_NO". It so happens that when we restore PRavega using the Backup-Resotre procedure, we install Pravega afresh, causing the operation sequence numbers to reset inside container. Due to a check present on the internal Tables, If this number hasnt run-up more than the "PERSIST_SEQ_NO", the operations on the Table will get rejected causing keys to not get stored in the tables.

**Purpose of the change**  
Fixes #7314

**What the code does**  
Backs up Operation Sequence Number of a container. Restores it and sets it in a container that is used after a container restores.

**How to verify it**  
See #7314

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 1]
```diff
@@ -984,8 +991,8 @@ private CompletableFuture<Long> readContainerEpoch() {
                     } catch (Exception e) {
                         throw new RuntimeException(e);
                     }
-                    log.info("{}: Read container epoch {} from storage", this.traceObjectId, containerEpoch.getEpoch());
-                    return CompletableFuture.completedFuture(containerEpoch.getEpoch() + 1);
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:988]: Ok got it. Missed this earlier.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM.

Please test this thoroughly before merging.

**Comment by abhinb** [comment]
@sachin-j-joshi 
the tests were positive and havent resulted in any side-effects. 
CC: @Amit-Singh40 @kuldeepk3
