### PR TITLE
Issue 4784: Release throttle in the event an unhandled exception comes from netty.

### LINKED ISSUE #4784: Prevent unhandled netty errors from stalling writer
**Problem description**
When appending data to a netty connection a throttle is used to control the rate of transmission. This throttle is released when data is written to the wire successfully of if netty encounters an error and calls into its callback. It is however possible that there could be an error and due to a bug netty fails to catch it and does not invoke the callback.

**Problem location**
ClientConnectionImpl.java 

**Suggestions for an improvement**
Add a try-catch block around the write call to make sure the callback is invoked upon exception.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**  
* Release throttle in the event an unhandled exception comes from netty.

**Purpose of the change**  
Fixes #4784 

**What the code does**  
Adds try/catch blocks around calls to `write` to ensure that unhandled exceptions are dealt with, and adds a release of the throttle in `close` as a secondary measure to ensure that the throttle always releases any blocked threads.

**How to verify it**  
@claudiofahey will verify.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java [hunk 1]
```diff
@@ -89,9 +90,17 @@ public void operationComplete(ChannelFuture future) {
...
         eventLoop.execute(() -> {
-            channel.write(cmd, promise);
+            try {
+                if (!closed.get()) {
+                    channel.write(cmd, promise);
+                }
+            } catch (Exception e) {
+                throttle.release(dataLength);
+                channel.pipeline().fireExceptionCaught(e);
+                channel.close();
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:100]: We can directly invoke `io.pravega.client.netty.impl.ClientConnectionImpl#close`.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java [hunk 2]
```diff
@@ -109,7 +118,14 @@ public void operationComplete(ChannelFuture future) {
...
         // Work around for https://github.com/netty/netty/issues/3246
         eventLoop.execute(() -> {
-            channel.write(cmd, promise);
+            try {
+                if (!closed.get()) {
+                    channel.write(cmd, promise);
+                }
+            } catch (Exception e) {
+                channel.pipeline().fireExceptionCaught(e);
+                channel.close();
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:127]: same as above.

**Comment by shrids** [comment]
triggered `test-pravega-continuous-1/711/` against this change set.

**Comment by claudiofahey** [comment]
FYI I added logs to PRAVEGA-961. I am continuing to test this PR.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java [hunk 3]
```diff
@@ -167,6 +183,7 @@ public void sendAsync(List<Append> appends, CompletedCallback callback) {
     public void close() {
         if (!closed.getAndSet(true)) {
             nettyHandler.closeFlow(this);
+            throttle.release(Integer.MAX_VALUE >> 1); //Makes sure that any blocked threads are unbloced.
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:186]: unblocked

**Comment by shrids** [comment]
`test-pravega-continuous-1/711/` is successful. (A system test does not trigger this issue!!)

**Comment by tkaitchuck** [comment]
DO NOT MERGE - Blocking for testing.

**Comment by claudiofahey** [comment]
I have tested this latest PR with a 3 TB dataset which took around 6.5 hours . The test completed successfully and no errors or warnings were reported on the task managers (Pravega clients).

Test parameters:
Job: Flink word generator batch job
total GB: 3000
output segments: 78
parallelism: 9
task manager replicas: 3
task manager process memory (per TM): 12 GiB
task manager off-heap memory (per TM): 4 GiB
cpu (per TM): 6
task slots (per TM): 6

Additional tests are ongoing.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 4]
```diff
@@ -57,6 +59,8 @@
     private final ConcurrentHashMap<Integer, AppendBatchSizeTracker> flowIDBatchSizeTrackerMap = new ConcurrentHashMap<>();
 
     private final AtomicBoolean disableFlow = new AtomicBoolean(false);
+    
+    private final Semaphore throttle = new Semaphore(AppendBatchSizeTracker.MAX_BATCH_SIZE);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java:63]: If an Append/event is greater than `MAX_BATCH_SIZE` then the `CommandEncoder` is the one which will split it.
But since the number of permits in the throttle is bounded by `MAX_BATCH_SIZE` the thread would indefinitely wait and the CommandEncoder in the subsequent pipeline stage will not be invoked... 
This caused an issue with `io.pravega.test.integration.ByteStreamTest#readLargeWrite`

**Comment by claudiofahey** [comment]
I have entered some test failures on a subsequent test. It is unknown if the failures are related to this PR. See logs and other details in PRAVEGA-961.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java [hunk 5]
```diff
@@ -103,13 +107,18 @@ private void write(WireCommand cmd) throws ConnectionFailedException {
             public void operationComplete(ChannelFuture future) {
                 if (!future.isSuccess()) {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:108]: `nettyHandler.setRecentMessage();` should be set here.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 6]
```diff
@@ -313,14 +318,28 @@ public void close() {
...
+                }
+            }
+        };
+        
         @Override
         public void run() {
-            try {
-                if (!recentMessage.getAndSet(false)) {
-                    getChannel().writeAndFlush(new WireCommands.KeepAlive()).addListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE);
+            if (recentMessage.getAndSet(false)) {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java:334]: These are the two changes in client behavior, right?
- This change implies keep-alive is sent every 20 seconds even if the connection is healthy. 
- If there is a connection stall for more than 20 seconds then the connection is closed.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 7]
```diff
@@ -313,14 +318,28 @@ public void close() {
     }
 
     private final class KeepAliveTask implements Runnable {
+        
+        private final ChannelFutureListener listener = new ChannelFutureListener() {
+            @Override
+            public void operationComplete(ChannelFuture future) throws Exception {
+                recentMessage.set(true);
+                if (!future.isSuccess()) {
+                    future.channel().pipeline().fireExceptionCaught(future.cause());
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java:327]: Can we log indicating that sending a keep-alive failed here?

File: test/integration/src/test/java/io/pravega/test/integration/AppendTest.java [hunk 8]
```diff
@@ -303,6 +308,35 @@ public void appendThroughStreamingClient() throws InterruptedException, Executio
         ack.get(5, TimeUnit.SECONDS);
     }
     
+    
+    @Test(timeout = 100000)
+    public void appendALotOfData() {
```
Comment (shrids) [inline test/integration/src/test/java/io/pravega/test/integration/AppendTest.java:313]: this test causes the `InMemoryDurableDataLog` to go OOM on my dev box...

Comment (andreipaduroiu) [reply test/integration/src/test/java/io/pravega/test/integration/AppendTest.java:313]: Looks like you're sending in 1000 x 1MB buffers for a total of 1GB. That is a bit too extreme. 

If you do want to keep this test as it is, may I recommend truncating the segment after every few writes you're sending? That should help clear memory pressure.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java (hunk 6 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java:334]: Yes

File: test/integration/src/test/java/io/pravega/test/integration/AppendTest.java (hunk 8 above)
Comment (tkaitchuck) [reply test/integration/src/test/java/io/pravega/test/integration/AppendTest.java:317]: Done

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java (hunk 7 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java:328]: Done

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java [hunk 9]
```diff
@@ -144,7 +152,6 @@ public void sendAsync(List<Append> appends, CompletedCallback callback) {
         Channel ch;
         try {
             checkClientConnectionClosed();
-            nettyHandler.setRecentMessage();
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:147]: Done

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java (hunk 5 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/netty/impl/ClientConnectionImpl.java:109]: Done
