### PR TITLE
Issue 2298: Fix reader rebalance bug, and add test coverage

### LINKED ISSUE #2298: Readers do not correctly rebalance.
**Problem description**
If there are multiple readers and they get unbalanced, such that more segments are assigned to one than the others, they do not properly rebalance segments among themselves. 
```
ERROR [2018-02-05 22:07:01.593] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (3/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[23, 0, 21, 22]
ERROR [2018-02-05 22:07:01.608] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (6/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[19, 20, 17, 18, 15, 16, 13, 14]
ERROR [2018-02-05 22:07:01.610] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (2/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[]
ERROR [2018-02-05 22:07:01.610] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (1/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[]
ERROR [2018-02-05 22:07:01.610] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (7/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[]
ERROR [2018-02-05 22:07:01.611] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (4/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[]
ERROR [2018-02-05 22:07:01.617] [Source: AnnotatedDataReader -> DecodeMapper -> BacklogMonitorMapper -> Sink: Publish-Decoded-Data (5/7)] i.p.c.s.impl.EventStreamReaderImpl: segmentNumbers=[3, 4, 1, 2, 7, 8, 5, 6, 11, 12, 9, 10]
```

**Problem location**
ReaderGroupStateManager

**Suggestions for an improvement**
Add test coverage

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**
Fix bug that prevented reader groups from properly rebalancing.

**Purpose of the change**
Fixes #2298

**What the code does**
There was a bug where the function to rank the readers in terms of ownership was using the wrong map, and was not taking into account the number of segments assigned. This fixes that bug and adds test coverage.

**How to verify it**
New tests should pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 1]
```diff
@@ -114,9 +114,9 @@ int getNumberOfReaders() {
      */
     @Synchronized
     int getRanking(String reader) {
-        List<String> sorted = distanceToTail.entrySet()
+        List<String> sorted = getRelativeSizes().entrySet()
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: getRelativeSizes() returns a size for a reader using the computation.
The size is computed by the formula : Number of assigned segments * lag for the reader / max lag of all readers. This value can be > 1.0 right?

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 2]
```diff
@@ -310,7 +310,7 @@ void update(ReaderGroupState state) {
             if (oldPos != null) {
                 throw new IllegalStateException("Attempted to add a reader that is already online: " + readerId);
             }
-            state.distanceToTail.putIfAbsent(readerId, Long.MAX_VALUE);
+            state.distanceToTail.putIfAbsent(readerId, 10 * ASSUMED_LAG_MILLIS);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: This change does not change the behavior of getRanking() method right, since the distance is always capped to ASSUMED_LAG_MILLIS.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 1 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: Yes. The idea is that 1.0 means you have one segment and the one with the largest lag. So 2.0 means the reader has twice that much data to read.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 2 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: It uses a minimum of Assumed_Lag_millis. This value shouldn't matter in practice because it should be quickly replaced by the real value. I just changed it because in my testing it was causing long overflow, which caused values to become negative.

File: client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java [hunk 3]
```diff
@@ -250,6 +252,62 @@ public void testRemoveReader() throws ReinitializationRequiredException {
         AssertExtensions.assertThrows(ReinitializationRequiredException.class,
                 () -> readerState2.acquireNewSegmentsIfNeeded(0L));
     }
+    
+    @Test(timeout = 5000)
+    public void testReleaseAndAquireTimes() throws ReinitializationRequiredException {
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java]: `testReleaseAndAquireTimes` -> `testReleaseAndAcquireTimes`

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 4]
```diff
@@ -114,9 +114,9 @@ int getNumberOfReaders() {
      */
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: In the comment about the ranking, can we say that this is ranked according to descending order?

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 5]
```diff
@@ -339,8 +345,9 @@ private int calculateNumSegmentsToAcquire(ReaderGroupState state) {
         return Math.max(Math.max(equallyDistributed, fairlyDistributed), 1);
     }
 
-    private Duration calculateAcquireTime(ReaderGroupState state) {
-        return TIME_UNIT.multipliedBy(state.getNumberOfReaders() - state.getRanking(readerId));
+    @VisibleForTesting
+    static Duration calculateAcquireTime(String readerId, ReaderGroupState state) {
+        return TIME_UNIT.multipliedBy(2 * (state.getNumberOfReaders() - state.getRanking(readerId)));
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java]: I don't understand why the `2` factor in this computation.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 2 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: > I just changed it because in my testing it was causing long overflow, which caused values to become negative.

I wonder if this is indicating a bug. If it is overflowing, then we are trying to add to the value. Why would we be trying to a value that isn't the "real" value? It looks like we are putting a placeholder value and we are trying to use this value for computations even though it isn't a valid value.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: It is never used for 'real' I checked the code. It is an artifact of the way the test works. It is injecting segment reassignments without ever updating the distance metric. I have changed the test to act like the normal code, and reverted the change here.

File: client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java (hunk 3 above)
Comment (tkaitchuck) [reply client/src/test/java/io/pravega/client/stream/impl/ReaderGroupStateManagerTest.java]: done

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java (hunk 4 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: done

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java (hunk 5 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java]: That was a hack. I have replaced it with a new check that will prevent 'full' hosts from being over-eager if they haven't acquired for a while because checkpoints are infrequent.
