### PR TITLE
Issue 2805: Improve resilience of Pinger

### LINKED ISSUE #2805: Pinger should be more resilient
**Problem description**
When pinging transactions if the Pinger throws an exception out of PingTransactions that writer will no longer ping any transactions. And each transaction only has one attempt to ping it built it, because the Ping_Interval_factor is just .5

**Problem location**
Pinger.java

**Suggestions for an improvement**
Attempt to ping each transaction multiple times, and gracefully handle exceptions.

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**
* Log and suppress exceptions when pinging transactions.

**Purpose of the change**
Fixes #2805

**What the code does**
Refactors pingTransactions() to handle unexpected exceptions rather than letting them reach the thread pool which would cancel the recurring task.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java [hunk 1]
```diff
@@ -90,26 +83,26 @@ private void startPeriodicPingTxn() {
...
-                                                  .forEach(e -> {
-                                                      log.warn("Ping Transaction for txn ID:{} failed", e.getKey(),
-                                                              getException(e.getValue()));
-                                                  }));
-        log.trace("Completed sending transaction pings.");
+        try {
+            log.info("Start sending transaction pings.");
+            txnList.stream().forEach(uuid -> {
+                log.debug("Sending ping request for txn ID: {} with lease: {}", uuid, txnLeaseMillis);
+                controller.pingTransaction(stream, uuid, txnLeaseMillis)
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: We could wrap these individual pings in retry blocks.

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java [hunk 2]
```diff
@@ -38,7 +31,7 @@
  */
 @Slf4j
 public class Pinger implements AutoCloseable {
-    private static final double PING_INTERVAL_FACTOR = 0.5; //ping interval = factor * txn lease time.
+    private static final double PING_INTERVAL_FACTOR = 0.25; //ping interval = factor * txn lease time.
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: For low txn lease times, this could make pings lot more aggressive, which will take up additional compute resources on both controller and client. 
We should either have a floor on the ping interval so that we know that we are not hammering the server with very aggressive pings. 
The intent here is to make sure that "at least" one ping per txn-lease-time period is sent so that transaction's lease gets renewed. So maybe 0.5 factor suffices, and we could just add retry block on failed pings (and only for retryable failures).

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java (hunk 1 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: Couple of points and questions:

* `controller.pingTransaction(..)` internally has a retry defined at `io.pravega.client.stream.impl.ControllerImpl#retryConfig`. This will take care of all exceptions related to connection drop.

1.  A `StatusRuntimeException` is thrown incase of connection drop which is retried because of `ControllerImpl#retryConfig`.
2. A ping `controller.pingTransaction(...)` on an aborted Txn the completableFuture is completed exceptionally e.g:
```
io.pravega.controller.store.stream.StoreException$DataNotFoundException: /transactions/activeTx/scope/stream/0/00000000-0000-0000-0000-000000000001
```

Is there any other exceptions that can be thrown ? (apart from RetriesExhaustedException.)

* In case of an exception during `controller.commitTransaction(..)` @ `io.pravega.client.stream.impl.EventStreamWriterImpl.TransactionImpl#commit` we should stop pinging, right?

Comment (shiveshr) [reply client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: > Is there any other exceptions that can be thrown ? (apart from RetriesExhaustedException which can cause the termination of the periodic ping operation )

Periodic ping operation can fail if there is an exception thrown while submitting the futures. 
For example, if `txnList` is null or if `controller`.pingTransaction has controller in null or invalid state and throws exception.

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java (hunk 2 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: Ideally, pings should be acked and retransmitted in the case an ack doesn't come back on time. It sounds fine to start a new ping at 0.5 of the interval, but then we should retransmit more aggressively in the absence of an ack.

Another way to look at this is that we are using gRPC, which builds on TCP. TCP has retransmission, so we shouldn't have to retransmit any ACK, unless there is an error bubbling up from gRPC.

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java (hunk 1 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: I would like to add support for removing aborted transactions from the pinger. But this would require a protocol change on the controller. So I've filed https://github.com/pravega/pravega/issues/2830

File: client/src/main/java/io/pravega/client/stream/impl/Pinger.java (hunk 2 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/Pinger.java]: Done
