### PR TITLE
Issue 3596:  Improved Exception handling for ReplyProcessor.

### LINKED ISSUE #3596: Ensure `io.pravega.shared.protocol.netty.ReplyProcessor#processingFailure` takes a Throwable as a parameter.
**Problem description**
We can update the `io.pravega.shared.protocol.netty.ReplyProcessor#processingFailure` method to take a `Throwable` as a parameter.

**Problem location**
All ReplyProcessor implementations.

**Suggestions for an improvement**
Refactor the api signature to remove redundant wrapping of exceptions.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Defensive exception handling for netty callbacks and `io.pravega.shared.protocol.netty.ReplyProcessor` invocations.

**Purpose of the change**  
Fixes #3596

**What the code does**  
This code does not modify/change any functionality, it enables defensive exception handling for netty related operations.

This enhancement request originally was to ensure `Throwable` is  caught for netty related operations. But on closer inspection of the code observed that catching `Throwable` is undesirable and catching `java.lang.Exception` is infact enough.
- `channel.writeAndFlush(..)` : This is now wrapped within  `try {} catch {}` block to handle any Exceptions.
- Reply processor invocation is now wrapped under a `try {} catch {}` block to ensure any exceptions (if thrown) do not cause other invocations to be skipped.
It should be noted that no exceptions were observed for any the cases handled in the pull request. This change enables defensive exception handling to ensure there are no code breakages with any future versions of the ReplyProcessor. 

**How to verify it**  
All the existing tests should continue to pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 1]
```diff
@@ -202,8 +215,13 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
     @Override
     public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
         flowIdReplyProcessorMap.forEach((flowId, rp) -> {
-            rp.processingFailure(new ConnectionFailedException(cause));
-            log.debug("Exception observed for flow id {}", flowId);
+            try {
+                log.debug("Exception observed for flow id {}", flowId, cause);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Do you want to log the entire stack trace or just the exception message?

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 2]
```diff
@@ -194,6 +206,7 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
             try {
                 processor.process(cmd);
             } catch (Exception e) {
+                log.error("Encountered exception invoking ReplyProcessor.process for reply " + cmd, e);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Not sure this is needed. The processor should be logging this with more/better context. We'll just end up with duplicated stack traces.

Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: updated it.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 3]
```diff
@@ -170,8 +170,13 @@ public void channelUnregistered(ChannelHandlerContext ctx) throws Exception {
...
         channel.set(null);
         flowIdReplyProcessorMap.forEach((flowId, rp) -> {
-            rp.connectionDropped();
-            log.debug("Connection dropped for flow id {}", flowId);
+            try {
+                log.debug("Connection dropped for flow id {}", flowId);
+                rp.connectionDropped();
+            } catch (Exception e) {
+                // Suppressing exception which prevents all ReplyProcessor.connectionDropped from being invoked.
+                log.warn("Encountered exception invoking ReplyProcessor for flow id " + flowId, e);
```
Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Is any exception caught here equally important? Just thinking in the case that there could be expected and harmless exceptions being caught here, so we could change the log level and do no print the whole stack trace for them (for the rest, this way of logging may be ok).

Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Please, use `{}` for logging arguments in log lines (e.g., `flowId`).

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 4]
```diff
@@ -182,7 +187,14 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
         log.debug(connectionName + " processing reply {} with flow {}", cmd, Flow.from(cmd.getRequestId()));
 
         if (cmd instanceof WireCommands.Hello) {
-            flowIdReplyProcessorMap.forEach((flowId, rp) -> rp.hello((WireCommands.Hello) cmd));
+            flowIdReplyProcessorMap.forEach((flowId, rp) -> {
+                try {
+                    rp.hello((WireCommands.Hello) cmd);
+                } catch (Exception e) {
+                    // Suppressing exception which prevents all ReplyProcessor.hello from being invoked.
+                    log.warn("Encountered exception invoking ReplyProcessor.hello for flow id " + flowId, e);
```
Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Same comment here as before.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 5]
```diff
@@ -194,6 +206,7 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
             try {
                 processor.process(cmd);
             } catch (Exception e) {
+                log.error("ReplyProcessor.process failed for reply {} due to {}", cmd, e.getMessage());
```
Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Same consideration here: for some expected exceptions logging the "message" may be enough (in this case, maybe `error` would be too severe), but for other unexpected exceptions it would be also useful to have the stack trace.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 6]
```diff
@@ -202,8 +215,13 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
...
     public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
         flowIdReplyProcessorMap.forEach((flowId, rp) -> {
-            rp.processingFailure(new ConnectionFailedException(cause));
-            log.debug("Exception observed for flow id {}", flowId);
+            try {
+                log.debug("Exception observed for flow id {} due to {}", flowId, cause.getMessage());
+                rp.processingFailure(new ConnectionFailedException(cause));
+            } catch (Exception e) {
+                // Suppressing exception which prevents all ReplyProcessor.processingFailure from being invoked.
+                log.warn("Encountered exception invoking ReplyProcessor.processingFailure for flow id " + flowId, e);
```
Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Please, use `{}` for the argument instead of String concatenation.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java (hunk 3 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Ideally exceptions should not be thrown by the ReplyProcessor implementations (the current ReplyProcessors do not throw it too). If thrown then it should be logged as it indicates that the newer ReplyProcessor s are incorrect and we prevent breakages with the future version of ReplyProcessors. With this in context feel that WARN with the stack trace is helpful.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java (hunk 5 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: Will change the log to warn level and since `processor.processingFailure(e)` is invoked next the stack trace will be logged there for unexpected exception.

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java (hunk 3 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: done.
