### PR TITLE
Issue 5188: Improve RawClient exception handling.

### LINKED ISSUE #5188: RawClient does not wrap all connection Failure exception with ConnectionFailedException.
**Problem description**
The following log snippet was observed on the Controller's SegmentHelper when there are a lot of network disconnects to the SegmentStore node.

```
2020-09-13 05:15:38,508 247624402 [controllerpool-9] WARN  i.p.c.connection.impl.RawClient - Closing connection to segment null with exception
java.util.concurrent.CompletionException: io.pravega.common.ObjectClosedException: Object 'FlowHandler' has been closed and cannot be accessed anymore.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at io.pravega.client.connection.impl.ConnectionPoolImpl.getClientConnection(ConnectionPoolImpl.java:131)
	at io.pravega.client.connection.impl.RawClient.<init>(RawClient.java:92)
	at io.pravega.controller.server.SegmentHelper.readTable(SegmentHelper.java:483)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$21(PravegaTablesStoreHelper.java:288)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$null$54(PravegaTablesStoreHelper.java:527)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.common.ObjectClosedException: Object 'FlowHandler' has been closed and cannot be accessed anymore.
	at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
	at io.pravega.client.connection.impl.FlowHandler.createFlow(FlowHandler.java:84)
	at io.pravega.client.connection.impl.ConnectionPoolImpl.lambda$getClientConnection$1(ConnectionPoolImpl.java:131)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 17 common frames omitted
```
Detailed logs: 
[controller.zip](https://github.com/pravega/pravega/files/5223499/controller.zip)

**Problem location**
Exception handling on RawClient.

**Suggestions for an improvement**
Improve exception handling so that the users of the RawClient can have a common retry logic.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Improve exception handling on the RawClient to handle scenarios where a connection drop can happen just before a new Flow is created as part of the obtaining/creating a new connection.

**Purpose of the change**  
Fixes #5188 

**What the code does**  
- The current `getClientConnection(..)` API does verify and if the filters out connections that are closed. But in a scenario, where a connection drop happens right after this check and before a new Flow is created the RawClient does not wrap this exception with a ConnectionFailedException.
- This fix ensures the RawClient handles this exception path correctly.
- Ensure ConditionalOutputStreamImpl throws a ObjectClosedException for writes once it is closed.

**How to verify it**  
All the existing and newly added tests should pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/connection/impl/RawClient.java [hunk 1]
```diff
@@ -87,16 +88,22 @@ public void authTokenCheckFailed(WireCommands.AuthTokenCheckFailed authTokenChec
         }
     }
 
-    public RawClient(PravegaNodeUri uri, ConnectionPool connectonPool) {
+    public RawClient(PravegaNodeUri uri, ConnectionPool connectionPool) {
         this.segmentId = null;
-        this.connection = connectonPool.getClientConnection(flow, uri, responseProcessor);
+        this.connection = connectionPool.getClientConnection(flow, uri, responseProcessor)
+        .exceptionally(e -> {
+            throw new CompletionException(new ConnectionFailedException("Failed to obtain client connection to segment " + segmentId.getScopedName()));
```
Comment (eolivelli) [inline client/src/main/java/io/pravega/client/connection/impl/RawClient.java:95]: we should al least keep a reference to `e` as "cause" of the ConnectionFailedException
otherwise we are simply "masking" any error with ConnectionFailedException

Not sure how we are dealing with special exceptions like InterruptedException

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/connection/impl/RawClient.java:95]: It's not a blocking call, so we shouldn't have to worry about Interrupted.

Comment (shrids) [reply client/src/main/java/io/pravega/client/connection/impl/RawClient.java]: improved it.

File: client/src/main/java/io/pravega/client/connection/impl/RawClient.java [hunk 2]
```diff
@@ -87,16 +88,24 @@ public void authTokenCheckFailed(WireCommands.AuthTokenCheckFailed authTokenChec
...
     }
 
-    public RawClient(PravegaNodeUri uri, ConnectionPool connectonPool) {
+    public RawClient(PravegaNodeUri uri, ConnectionPool connectionPool) {
         this.segmentId = null;
-        this.connection = connectonPool.getClientConnection(flow, uri, responseProcessor);
+        this.connection = connectionPool.getClientConnection(flow, uri, responseProcessor)
+        .exceptionally(e -> {
+            log.warn("Exception observed while attempting to obtain a connection to segment store {}", uri, e);
+            throw new CompletionException(new ConnectionFailedException("Failed to obtain client connection to  " + uri));
```
Comment (eolivelli) [inline client/src/main/java/io/pravega/client/connection/impl/RawClient.java:96]: I would add 'e' as cause

Comment (shrids) [reply client/src/main/java/io/pravega/client/connection/impl/RawClient.java]: done. ( i was about to push that change :D )

**Review by tkaitchuck — APPROVED** [review]

**Comment by shrids** [comment]
System test run : job/test-pravega-continuous-1/968/
