### PR TITLE
Issue 7420: Flakey test: PravegaTablesStoreBucketServiceTest.testFailureCase

### LINKED ISSUE #7420: Flakey test: io.pravega.controller.server.bucket.PravegaTablesStoreBucketServiceTest.testFailureCase
**Describe the bug**
io.pravega.controller.server.bucket.PravegaTablesStoreBucketServiceTest.testFailureCase test is behaving as flakey.

**To Reproduce**
1. Run the test in loop.

**Screenshots**
N/A

**Additional information**
Here is an example of it https://github.com/pravega/pravega/actions/runs/8079701537/job/22074697592#step:6:244

### PR DESCRIPTION
**Pull request by Bhupender-Y**
**Change log description**  
PravegaTablesStoreBucketServiceTest.testFailureCase is behaving as flakey and observe some GA build failures.

**Purpose of the change**  
Fixes #7420 

**What the code does**  
If some bucket is not associated with manager then it will simply skip it and will not throw NPE.

**How to verify it**  
All test should be successful.

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/server/bucket/PravegaTablesStoreBucketServiceTest.java [hunk 1]
```diff
@@ -112,26 +112,29 @@ public void testFailover() throws Exception {
...
+        assertEventuallyEquals(3, () -> watermarkingService.getBucketServices().size(), 3000);
+        assertEventuallyEquals(3, () -> retentionService.getBucketServices().size(), 3000);
         //add new controller instance in pravgea cluster.
         Host controller1 = new Host(UUID.randomUUID().toString(), 9090, null);
         addEntryToZkCluster(controller1);
+        System.out.println("!!!!!!!!!!!!");
         assertEventuallyEquals(2, () -> retentionService.getBucketServices().size(), 3000);
         assertEventuallyEquals(2, () -> watermarkingService.getBucketServices().size(), 3000);
-
+        System.out.println("!!!!!!!!!!!!");
```
Comment (tkaitchuck) [inline controller/src/test/java/io/pravega/controller/server/bucket/PravegaTablesStoreBucketServiceTest.java:123]: I assume you meant to delete these.

Comment (Bhupender-Y) [reply controller/src/test/java/io/pravega/controller/server/bucket/PravegaTablesStoreBucketServiceTest.java]: Yes, removed test logs.

**Review by munish1789 — APPROVED** [review]
Is this change tested in System test ?
LGTM

**Review by tkaitchuck — APPROVED** [review]
