### PR TITLE
Issue 6792: Removing operation versioning for table-segment recoverying command

### LINKED ISSUE #6792: Table segment recovery command throws exception due to `tableKeyDoesNotExist`
**Describe the bug**
Whele running table segment recovery command exception is thrown `data-recovery tableSegment-recovery <segment-chunks-location> <new-table-segment-name> <pravega-local-storage-dir>`

```
java.util.concurrent.ExecutionException: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.writeEntriesToNewTableSegment(TableSegmentRecoveryCommand.java:174)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.execute(TableSegmentRecoveryCommand.java:129)
	at io.pravega.cli.admin.AdminCLIRunner.execCommand(AdminCLIRunner.java:136)
	at io.pravega.cli.admin.AdminCLIRunner.processCommand(AdminCLIRunner.java:123)
	at io.pravega.cli.admin.AdminCLIRunner.interactiveMode(AdminCLIRunner.java:104)
	at io.pravega.cli.admin.AdminCLIRunner.doMain(AdminCLIRunner.java:89)
	at io.pravega.cli.admin.AdminCLIRunner.main(AdminCLIRunner.java:69)
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleExpectedReplies(SegmentHelper.java:903)
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:865)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$14(SegmentHelper.java:469)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:137)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:44)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:77)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:166)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:133)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Open admin cli
2. run the below command:
`data-recovery tableSegment-recovery <segment-chunks-location> <new-table-segment-name> <pravega-local-storage-dir>`

**Screenshots**

**Additional information**
Add any other information about the problem here, including the root cause if known.

### PR DESCRIPTION
**Pull request by kuldeepk3**
Signed-off-by: Kuldeep Kumar <kuldeep.kumar3@dell.com>

**Change log description**  
The ` data-recovery tableSegment-recovery ` tries to recover table segments but fails where table segment key is missing with the below exception:
```
java.util.concurrent.ExecutionException: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.writeEntriesToNewTableSegment(TableSegmentRecoveryCommand.java:174)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.execute(TableSegmentRecoveryCommand.java:129)
	at io.pravega.cli.admin.AdminCLIRunner.execCommand(AdminCLIRunner.java:136)
	at io.pravega.cli.admin.AdminCLIRunner.processCommand(AdminCLIRunner.java:123)
	at io.pravega.cli.admin.AdminCLIRunner.interactiveMode(AdminCLIRunner.java:104)
	at io.pravega.cli.admin.AdminCLIRunner.doMain(AdminCLIRunner.java:89)
	at io.pravega.cli.admin.AdminCLIRunner.main(AdminCLIRunner.java:69)
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleExpectedReplies(SegmentHelper.java:903)
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:865)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$14(SegmentHelper.java:469)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:137)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:44)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:77)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:166)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:133)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Purpose of the change**  
Fixes #6792 

**What the code does**  
Removing the version check while running table segment recovery command

**How to verify it**  
Follow the below steps:
1. Open  admin cli
2. run the below command
` data-recovery tableSegment-recovery <segment-chunks-location> <new-table-segment-name> <pravega-local-storage-dir>`

### CODE REVIEW

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Please, add a test that verifies that if we input keys with versions, this works well. Also, as this cli command may be reading from an existing chunk of data, it may be the case that we get as input a REMOVE operation for a non-existing key. Please, handle this case as well and add a test for it too.

**Review by ShwethaSNayak — COMMENTED** [review]
In "How to verify it", it will be great if you can add data-recovery command with input keys with versions. Also add testcase to cover this.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Please, create a test case that demonstrates that it works with data that contains higher versions, as it is legacy data.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 1]
```diff
@@ -963,6 +963,58 @@ public void testTableSegmentRecoveryCommand() throws Exception {
...
+        pravegaProperties.setProperty("filesystem.root", this.baseDir.getAbsolutePath());
+        pravegaProperties.setProperty("bookkeeper.ledger.path", "/pravega/bookkeeper/ledgers0");
+        STATE.get().getConfigBuilder().include(pravegaProperties);
+
+        // Create the data to test.
+        File testDataDir = Files.createTempDirectory("test-data-table-segment-recovery").toFile().getAbsoluteFile();
+        File pravegaStorageDir = Files.createTempDirectory("table-segment-recovery-command").toFile().getAbsoluteFile();
+
+        List<TableEntry> tableSegmentVersionedPuts = List.of(
+                TableEntry.versioned(new ByteArraySegment("kv1".getBytes()), new ByteArraySegment("vv1".getBytes()), 1L ),
```
Comment (RaulGracia) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:983]: Nit: extra space before the closing parenthesis.

File: cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/TableSegmentRecoveryCommand.java [hunk 2]
```diff
@@ -206,8 +206,8 @@ private int scanAllEntriesInTableSegmentChunks(ByteArraySegment byteArraySegment
                         .getReader().readNBytes(header.getValueLength());
                 // Add the operation to the list of operations to replay later on (PUT or DELETE).
                 tableSegmentOperations.add(valueBytes.length == 0 ?
-                        new DeleteOperation(TableSegmentEntry.versioned(keyBytes, valueBytes, header.getEntryVersion())) :
-                        new PutOperation(TableSegmentEntry.versioned(keyBytes, valueBytes, header.getEntryVersion())));
+                        new DeleteOperation(TableSegmentEntry.unversioned(keyBytes, valueBytes)) :
```
Comment (RaulGracia) [inline cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/TableSegmentRecoveryCommand.java:209]: Could it happen to parse a DELETE operation for a KEY that does not exist? Are handling that case if it can happen?

**Comment by RaulGracia** [comment]
@kuldeepk3 please, could you deploy a cluster locally, write some data for some time and then try to perform the repair process of a BTreeIndex using these changes in the tool? Just as a last step validation to make sure everything works.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 3]
```diff
@@ -963,6 +963,58 @@ public void testTableSegmentRecoveryCommand() throws Exception {
         Assert.assertArrayEquals(Files.readAllBytes(Paths.get(pravegaStorageDir.toString(), listOfFiles.get(0).getName())), serializedEntries.getCopy());
     }
 
+    @Test
+    public void testTableSegmentRecoveryCommandVersioned() throws Exception {
```
Comment (abhinb) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:967]: does this test fail without the "unversioned" change?

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 4]
```diff
@@ -963,6 +963,58 @@ public void testTableSegmentRecoveryCommand() throws Exception {
         Assert.assertArrayEquals(Files.readAllBytes(Paths.get(pravegaStorageDir.toString(), listOfFiles.get(0).getName())), serializedEntries.getCopy());
     }
 
+    @Test
```
Comment (abhinb) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:966]: A verification of this command by manually inducing corruption and then recovering using this command would help.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java (hunk 1 above)
Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java]: fixed

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java (hunk 3 above)
Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:967]: It does not fail with the changes.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java (hunk 4 above)
Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:966]: verified table segment-recovery on a pks cluster with these changes and recovery was successful.

File: cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/TableSegmentRecoveryCommand.java (hunk 2 above)
Comment (kuldeepk3) [reply cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/TableSegmentRecoveryCommand.java:209]: Added a 'DELETE' operation for a KEY that does not exist in the table-segment recovery command for manual testing and the recovery completed without any error.

**Comment by kuldeepk3** [comment]
Updated the test case. The test case fails with the below exception if we use versioned method and passes in case of unversioned method:

> io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
java.util.concurrent.ExecutionException: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.writeEntriesToNewTableSegment(TableSegmentRecoveryCommand.java:179)
	at io.pravega.cli.admin.dataRecovery.TableSegmentRecoveryCommand.execute(TableSegmentRecoveryCommand.java:134)
	at io.pravega.cli.admin.utils.TestUtils.executeCommand(TestUtils.java:94)
	at io.pravega.cli.admin.dataRecovery.DataRecoveryTest.testTableSegmentRecoveryCommandVersioned2(DataRecoveryTest.java:1053)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason TableKeyDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleExpectedReplies(SegmentHelper.java:899)
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:861)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$14(SegmentHelper.java:469)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:137)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:44)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:77)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:166)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:133)
	... 1 more

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 5]
```diff
@@ -1608,4 +1666,75 @@ private Map<Long, Long> getOperationsCountMapBySequenceNumber(List<DurableLogIns
                 originalOperations.stream().collect(Collectors.groupingBy(op -> op.getSequenceNumber(), Collectors.counting()));
         return resultMap;
     }
+
+    /*
+    * EntrySerializer's serializeUpdateWithExplicitVersion has package access and changing the scope for test
```
Comment (RaulGracia) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:1671]: Please, rephrase the comment to something like: "Create a test version of EntrySerializer to serialize Table Segment entry for recovery purposes without changing visibility of of methods from original class.". I don't think it is necessary to explain the coverage issues here, as they are too specific of the build configuration we have.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 6]
```diff
@@ -1608,4 +1666,75 @@ private Map<Long, Long> getOperationsCountMapBySequenceNumber(List<DurableLogIns
...
+    * is not really required and also causes code coverage issue.
+    * So extending EntrySerializer and using the same.
+    * */
+    static class MyEntrySerializer  extends EntrySerializer {
```
Comment (RaulGracia) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:1675]: Extra space after `MyEntrySerializer`.

**Review by RaulGracia — APPROVED** [review]

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java (hunk 5 above)
Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java]: Updated.

File: cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java [hunk 7]
```diff
@@ -963,6 +969,58 @@ public void testTableSegmentRecoveryCommand() throws Exception {
         Assert.assertArrayEquals(Files.readAllBytes(Paths.get(pravegaStorageDir.toString(), listOfFiles.get(0).getName())), serializedEntries.getCopy());
     }
 
+    @Test
+    public void testTableSegmentRecoveryCommandUnVersioned() throws Exception {
```
Comment (abhinb) [inline cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:973]: this is the versioned method right? name says unversioned

Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:973]: Will update the name in some other pr.

Comment (RaulGracia) [reply cli/admin/src/test/java/io/pravega/cli/admin/dataRecovery/DataRecoveryTest.java:973]: Well, that' very minor to create a PR for it. Not a big deal, we can change it in the next PR related to CLI.
