### PR TITLE
Issue 2133: System test code issues

### LINKED ISSUE #2133: System test issues
**Problem description**
1. Add retry logic around seal stream because it can fail if it conflicts with another stream operation (typically auto-scale). 
2. To verify if scaling has happened, look for scale operations rather than segment count. 
3. Increase timeout in ReadWithAutoScale test. 
4. Unwanted test failure because clients threw exception after stream was deleted causing test failures.

**Problem location**
AbstractFailoverTest
ReadWithAutoScaleTest
**Suggestions for an improvement**
Fix the issues

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: shivesh ranjan <shivesh.ranjan@gmail.com>

**Change log description**

1. Add retry logic around seal stream because it can fail if it conflicts with another stream operation (typically auto-scale).
2.   To verify if scaling has happened, look for scale operations rather than segment count.
3.    Increase timeout in ReadWithAutoScale test.
4. Unwanted test failure because clients threw exception after stream was deleted causing test failures.

**Purpose of the change**
Fixes #2133

**What the code does**
Fixes system test issues

**How to verify it**
We should not observe these issues in system test

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java [hunk 1]
```diff
@@ -131,7 +131,7 @@ public void createStream() throws InterruptedException, URISyntaxException, Exec
         log.debug("Create stream status {}", createStreamStatus);
     }
 
-    @Test(timeout = 6 * 60 * 1000) //timeout of 6 mins.
+    @Test(timeout = 10 * 60 * 1000) //timeout of 6 mins.
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java]: Can you change the comment to  `timeout of 10 mins`

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 2]
```diff
@@ -518,24 +519,18 @@ void validateResults() {
...
+            if (streamSegments.getSegments().stream().mapToInt(Segment::getSegmentNumber).max().orElse(-1) > initialMaxSegmentNumber) {
+                scaled = true;
                 break;
             }
         }
-        if (testState.currentNumOfSegments.get() == 2) {
-            Assert.fail("Current number of Segments reduced to less than 2. Failure of test");
-        }
+
+        assertTrue("scaling did not happen within desired time", scaled);
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Capitalise s  in scaling. also the initial letter in the above log message.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 3]
```diff
@@ -31,6 +32,9 @@
 import io.pravega.test.system.framework.services.PravegaSegmentStoreService;
 import io.pravega.test.system.framework.services.Service;
 import io.pravega.test.system.framework.services.ZookeeperService;
+import lombok.extern.slf4j.Slf4j;
+import org.junit.Assert;
+
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: extra line.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 2 above)
Comment (shiveshr) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: done

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 4]
```diff
@@ -518,24 +537,20 @@ void validateResults() {
...
-            testState.currentNumOfSegments.set(streamSegments.getSegments().size());
-            if (testState.currentNumOfSegments.get() == 2) {
-                log.info("The current number of segments is equal to 2, ScaleOperation did not happen");
-                //Scaling operation did not happen, wait
-                Exceptions.handleInterrupted(() -> Thread.sleep(10000));
-            }
-            if (testState.currentNumOfSegments.get() > 2) {
-                //scale operation successful.
-                log.info("Current Number of segments is {}", testState.currentNumOfSegments.get());
+            if (streamSegments.getSegments().stream().mapToInt(Segment::getSegmentNumber).max().orElse(-1) > initialMaxSegmentNumber) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: The controller has this API call that would be perfect to use here:
```
public CompletableFuture<List<ScaleMetadata>> getScaleRecords
```

We do not currently expose it via the `Controller` java client interface, but perhaps we could consider doing it as follow up work. If you think it is worth it, then create an issue and add a comment here. We shouldn't block this PR on this change.

**Comment by shiveshr** [comment]
@fpj I think we can take a call on exposing `getScaleRecords` in context of exposing ScaleNotifications to readerGroup. 
We dont need to explicitly expose that api on controller interface just for the sake of our tests. 
And we have a way of determining if scale happened in our tests using getCurrentSegments api on controller the way we have used it here in this test.
