### PR TITLE
Issue 4334: Fix auth and related exception handling

### LINKED ISSUE #4334: Missing message in an auth-related log makes it hard to correlate client and server errors
**Problem description**
When debugging #4216, we found an issue where it was hard to correlate an auth-related exception logged on the client-side with the exceptions logged on Controller side. 

The client-side exception was: 
```
[clientInternal-2-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 30 for endpoint 172.28.156.21. The current Channel is [id: 0x7aa9979a].
[grpc-default-executor-14] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
        at io.grpc.Status.asRuntimeException(Status.java:530)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
ControllerServiceImpl.java

**Suggestions for an improvement**
Add a custom message to the log on the server-side.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Improve exception handling and logging in gRPC interface to distinguish clearly among these three error conditions: 

1. A condition representing an authentication failure
2. A condition representing an authorization failure
3. A condition representing an internal failure

This enables easier debugging of issues, as well as enables the client to handle these different conditions properly. For example, the client can retry upon encountering the 3rd failure, but avoid doing that for the 1st and the 2nd.

**Purpose of the change**  
Fixes #4334 & #3814. 

**What the code does**  
The code does the following: 
* Makes `AuthException` (the parent of both `AuthenticationException` and `AuthorizationException`) abstract, so that it cannot be thrown (but can be caught in the calling code). 
* Makes `AuthException` a runtime exception, so that the places where the subclasses are throws do not have to wrap them in a RuntimeException (like was done before). Doing this makes it possible to just catch these exceptions directly in the  `ControllerServiceImpl` and perform the necessary handling. 
* Modify a `ControllerServiceImpl` method to throw specific exceptions disambiguating the three error conditions.  

**How to verify it**  
All tests must pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 1]
```diff
@@ -557,7 +557,7 @@ private void logIfEmpty(String delegationToken, String requestName, String scope
                         logAndUntrackRequestTag(requestTag);
                     });
         } catch (Exception e) {
-            log.error(e.getMessage(), e);
+            log.error("Encountered exception in authenticateExecuteAndProcessResults: {}", e.getMessage(), e);
             logAndUntrackRequestTag(requestTag);
             streamObserver.onError(Status.UNAUTHENTICATED
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: As discussed, we should set the status as `Status.UNAUTHENTICATED` only incase of authentication errors, else the status should be `Status.INTERNAL`.  

The client does not retry in cases of Authentication failures ref: https://github.com/pravega/pravega/blob/26bfc25eca2e76e691bc32177ef2500cccb95879/client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java#L202-L218

Doing this change will ensure the client retries on non-auth related errors.

Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Sure, thanks for spotting the issue. I've modified the code to set appropriate status: 
* `io.grpc.Status.UNAUTHENTICATED` upon authentication failures 
* `io.grpc.Status.PERMISSION_DENIED` upon authorization failures
* `io.grpc.Status.INTERNAL` upon internal failures.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/RESTAuthHelper.java [hunk 2]
```diff
@@ -106,8 +106,8 @@ public void authenticateAuthorize(List<String> authHeader, String resource, Auth
         if (isAuthEnabled()) {
             String credentials = parseCredentials(authHeader);
             if (!pravegaAuthManager.authenticateAndAuthorize(resource, credentials, permission)) {
-                throw new AuthException(
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/RESTAuthHelper.java]: The `AuthException` is the base class for both `AuthenticationException` and `AuthorizationException`. Earlier, we were throwing the more abstract exception `AuthException`, while the error condition really represents an authorization failure. Once we made `AuthException` abstract, we had to choose between either `AuthenticationException` or `AuthorizationException` while throwing the exception here, and I chose the latter as it is representative of the error condition here. Hope that explains the choice.
