### PR TITLE
Issue 1525: (SegmentStore) Fixed spurious ReadIndex merge bug

### LINKED ISSUE #1525: Jenkins test failure for test StreamSegmentContainerTests#testTransactionOperations
**Problem description**
Jenkins test failure : `StreamSegmentContainerTests#testTransactionOperations`

```Error Msg:
java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'FutureReadResultEntryCollection' has been closed and cannot be accessed anymore.

Stacktrace

java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'FutureReadResultEntryCollection' has been closed and cannot be accessed anymore.
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.mergeTransactions(StreamSegmentContainerTests.java:1237)
    at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:638)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.pravega.common.ObjectClosedException: Object 'FutureReadResultEntryCollection' has been closed and cannot be accessed anymore.
    at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:163)```

**Problem location**

StreamSegmentContainerTests#testTransactionOperations

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in ContainerReadIndex where it would erroneously report ObjectClosedException in a corner case, thus failing an already committed operation.

Scenario:
- Consider a Transaction segment T1, with an Append/Seal and a Merge in the same batch of operations.
- These operations are written to Tier1, committed to in-memory metadata.
- Since an Append/Seal is involved, the ReadIndex will need to trigger future reads (if any) for T1
- However, if the Storage Writer is fast enough (which can happen in unit tests where everything is in memory), it could already process the merge, and thus close the ReadIndex for T1.
    - In this case, it is possible that a pointer to T1's ReadIndex is obtained prior to this merge, but triggerFutureReads() is invoked after the merge, hence the ObjectClosedException.

**Purpose of the change**
Fixes #1525.

**What the code does**
Explicitly handling `ObjectClosedException` during the call to `triggerFutureReads`.

**How to verify it**
Unfortunately this situation is nearly impossible to reproduce via unit test. As the description states, a number of things need to happen in the right order, most of which are beyond the control of a unit test (such as Java's thread scheduling).

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java [hunk 1]
```diff
@@ -189,8 +190,24 @@ public void triggerFutureReads(Collection<Long> streamSegmentIds) {
...
                 index.triggerFutureReads();
+            } catch (ObjectClosedException ex) {
+                // It is possible that between the time we got the pointer to the StreamSegmentReadIndex and when we got
+                // to invoking triggerFutureReads, the StreamSegmentReadIndex has already been closed. If this is the case,
+                // ignore the error.
+                // This is possible in the following scenario: for a Transaction, we have an Append, followed by a Merge;
+                // the Append makes this index eligible for triggering future reads, and the Merge (once committed to Storage)
+                // will close it. If the StorageWriter is sufficiently fast in comparison to the OperationProcessor callbacks
+                // (which could be the case for in-memory unit tests), it may trigger this condition.
+                if (getIndex(segmentId) == null) {
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: **Clarification**: if the read index for T1 has been closed, which causes this `ObjectClosedException` to be thrown, wouldn't `getIndex` return null because the index is no longer available? The expected semantics here seems to be that `getIndex` returns the read index for the given segment id even if the read index has been closed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java [hunk 2]
```diff
@@ -189,8 +190,24 @@ public void triggerFutureReads(Collection<Long> streamSegmentIds) {
...
+                    throw ex;
+                } else {
+                    log.debug("{}: triggerFutureReads: StreamSegmentId {} was skipped because it is no longer registered.", this.traceObjectId, segmentId);
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: **Minor**: Could you break this line into multiple parts, please?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java (hunk 1 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: It would, but only if it got closed before the call to`getIndex` above. The `StorageWriter` is an async process which may invoke methods on this class from different threads. It is quite possible that the index is closed after `getIndex` and before we invoke `triggerFutureReads` on it - which causes this error.

`getIndex` will return the index if it is registered. However when we close the index (see `closeIndex`) we atomically close it and unregister it, so it will never be the case that we get a reference to a closed index.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java (hunk 2 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java (hunk 1 above)
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: got it.
