### PR TITLE
Issue 2322: (SegmentStore) More efficient recovery process

### LINKED ISSUE #2322: Optimize Tier1 data framing reading
**Problem description**
When reading from Tier1 (recovery) the following is done:
- Each Tier1 write  is read in its entirety and wrapped by an `InputStream`
- That `InputStream` is then read in its entirety into a byte array, which is then wrapped into a `DataFrame`
- DataFrames are parsed to locate individual record entry boundaries, and `InputStreams` are made for each of them
- Once all the record entries for a particular record have been located (possibly spanning multiple such frames), their `InputStreams` are stitched together in a sequence and Operations are parsed from them.

**Problem location**
Segment Store Tier1 reading.

**Suggestions for an improvement**

Reading:
- Eliminate the double buffering that is needed in order to construct DataFrames. 
- BookKeeper returns a `netty.ByteBuf`, which is currently wrapped in an `InputStream`. This is not very useful in reading at arbitrary positions, so we might need to either use the underlying ByteBuf directly or figure out some other way of interpreting the data inside it.
- Figure out a way to compose `DataFrames` from the underlying data that BK provides, preferrably without reading all of it into a new buffer.
- This may involve separating DataFrames into WriteDataFrames and ReadDataFrames
- ReadDataFrame will use an `ArrayView`/`InputStream` (which will wrap a `ByteBuf`), and its Entry reader will essentially iterate through the ByteBuf.
    - This will require that once an entry is read/consumed, we cannot store it anywhere, so we'll need to process it immediately. 
    - This can be mitigated in DataFrameReader by streaming data into the Factory.Deserialize(InputStream) instead of pre-acquiring InputStreams and then reading data from them. We can throw exceptions (such as incomplete records) while streaming out.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Enhanced the recovery process in a `StreamSegmentContainer` by eliminating an extra, unnecessary memory copy.

The recovery process is driven by the `DurableLog` component, which reads entries from Tier1, interprets them as `DataFrames`, then deserializes the sequence of Data Frame Entries into Operations. This whole process is performed by a component called `DataFrameReader`. 

What is suboptimal about this:
- The entries from Tier1 (BookKeeper) are backed by a Netty ByteBuf, and can only be accessed externally by wrapping them in an `InputStream (ByteBufInputStream)` or by copying them to a byte array. We chose the `InputStream`.
- In order to construct a `DataFrame` from such an `InputStream`, the `DataFrameReader` would read the whole `InputStream` and create a byte array from it.
- The byte array would be parsed for DataFrame Entries, which would again be converted into `InputStreams`, and serve as input to a deserializer which then constructs the Operations that were previously serialized in them.

What is being addressed:
- This changes the `DataFrameReader` to no longer parse the entire `InputStream` and read it into a `DataFrame`. 
- It creates a `DataFrameInputStream` which stitches together the individual DataFrame Entries behind the scenes (as InputStreams) and serves the data to a deserializer which then constructs the Operations.
- This processes the Tier1 entry InputStream (from BK) in sequence, never reading ahead or buffering it, thus eliminating the need for the extra memory copy.

Another benefit of this is symmetry with the write path:
- `DataFrameBuilder` accepts `Operations` which can be read back using a `DataFrameReader`
- `DataFrameOutputStream` (implementing `OutputStream`) has a notion of "records" (each record has a beginning and an end, can span multiple `DataFrames`, and all writes between those boundaries are part of the record's serialization).
- `DataFrameInputStream` (implementing `InputStream`) again has a notion of "records" and can be used to read the serialization for each of those.
- `DataFrame` is now a write-path-only concept, which only aids in organizing the data. On the read path, there is no need for an actual Data Frame; only for a means to parse it.

**Purpose of the change**
Fixes #2322.

**What the code does**
Optimizing the recovery path by eliminating a memory copy (which would've copied all data from Tier1).

**How to verify it**
Existing unit tests must pass. New tests have been added to verify newly added sub-components.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/io/BoundedInputStream.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+import com.google.common.base.Preconditions;
+import java.io.FilterInputStream;
+import java.io.IOException;
+import java.io.InputStream;
+import lombok.Getter;
+
+/**
+ * A wrapper for an InputStream that allows reading up to a specified number of bytes.
+ */
+public class BoundedInputStream extends FilterInputStream {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/io/BoundedInputStream.java]: This class was moved from `io.pravega.common.io.serialization.RevisionDataInputStream` into its own file.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/admin/commands/ContainerRecoverCommand.java [hunk 2]
```diff
@@ -124,21 +123,20 @@ static CommandDescriptor descriptor() {
         private int operationCount = 0;
         private int currentFrameUsedLength = 0;
 
-        private void newOperation(Operation op, List<DataFrame.DataFrameEntry> frameEntries) {
+        private void newOperation(Operation op, List<DataFrameReader.ReadResult.EntryInfo> frameEntries) {
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/admin/commands/ContainerRecoverCommand.java]: Inner inner classes being used from the outside is ridiculous. Promote one of those to a top level class.

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/admin/commands/ContainerRecoverCommand.java]: Good point. I extracted this class out and rearranged a few things to avoid the back-and-forth dependencies.

File: common/src/main/java/io/pravega/common/io/BoundedInputStream.java (hunk 1 above)
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/io/BoundedInputStream.java]: NotThreadSafe?

**Comment by andreipaduroiu** [comment]
[Segment Store recovery improvements](https://trello.com/c/DK3uQn0W/40-segment-store-recovery-improvements)

File: common/src/main/java/io/pravega/common/io/BoundedInputStream.java (hunk 1 above)
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/io/BoundedInputStream.java]: Fixed.
