### PR TITLE
Issue 1531: Controller gRPC client to retry DNS resolution on failures

### LINKED ISSUE #1531: Controller client should attempt controller URI resolution frequently
**Problem description**
The current controller gRPC client implementation attempts to resolve the controller URI only every 30 minutes. We have seen this to cause the controller client to be unusable for 30 minutes if the initial resolution fails. We should attempt to resolve the controller URI more frequently to handle the following issues
* Temporary DNS resolution failures (could be due to network connectivity or DNS propagation delays too)
* Controller IP address changes (hence the DNS update should be picked up sooner than later)

**Problem location**
ControllerImpl.java

**Suggestions for an improvement**
Increase frequency of controller URI resolution

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
Updated the gRPC nameresolver to retry DNS resolution on network failures. Also attempting DNS resolution at regular intervals to detect change in address (when dynamic DNS is used)
Also addressed comments from PR #1534 

**Purpose of the change**
Fixes #1531 

**What the code does**
Attempts DNS resolution on gRPC network failures and also at regular intervals (retained the earlier 2 mins scheduler used for controller discovery)

**How to verify it**
Existing ControllerImplLBTest.java covers network failure scenarios. Manually tested failure handling due to DNS propagation delays. Added unit tests for Controller URIs using IP addresses.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 1]
```diff
@@ -137,50 +155,116 @@ public void start(Listener listener) {
...
             Preconditions.checkState(started.compareAndSet(true, false));
             if (this.scheduledExecutor != null) {
                 this.scheduledExecutor.shutdownNow();
             }
         }
 
-        // The controller discovery API invoker.
+        @Override
+        @Synchronized
+        public void refresh() {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Where is this called?

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: This is called internally by gRPC on network failures as hints to retry server resolution

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 2]
```diff
@@ -137,50 +155,116 @@ public void start(Listener listener) {
...
+                    log.info("Updating client with controllers: {}", serverInfoGroup);
+                    this.resolverUpdater.onUpdate(Collections.singletonList(serverInfoGroup), Attributes.EMPTY);
+                    started.set(true);
+                    return;
+                }
+                // else case is for controllers with DNS hostnames, which needs to be resolved periodically.
             }
+
+            // Schedule the first discovery immediately.
+            this.scheduledExecutor = Executors.newScheduledThreadPool(1,
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Instead of creating a new thread pool, should we reuse the one we  have added for the client? I'd rather not increase the number of executors unnecessarily.

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: tom had a similar concern, here is my response:

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 3]
```diff
@@ -121,10 +139,10 @@ public String getServiceAuthority() {
         @Override
         @Synchronized
         public void start(Listener listener) {
-            Preconditions.checkState(started.compareAndSet(false, true));
+            Preconditions.checkState(!started.get());
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: It would be better if we either make this No Op (if its already started) Or make this method idempotent. 
This is anyway synchronized, and it appears that the contract is that this method can be called multiple times.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 2 above)
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: +1

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 4]
```diff
@@ -137,50 +155,116 @@ public void start(Listener listener) {
...
-                                .map(node ->
-                                        new ResolvedServerInfo(
-                                                new InetSocketAddress(node.getEndpoint(), node.getPort())))
-                                .collect(Collectors.toList()))
-                        .build();
+                final ResolvedServerInfoGroup serverInfoGroup;
+                if (this.enableDiscovery) {
+                    // Make an RPC call to the bootstrapped controller servers to fetch all active controllers.
+                    final ServerResponse controllerServerList =
+                            this.client.getControllerServerList(ServerRequest.getDefaultInstance());
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: do we want to block on this.. can we make this call asynchronous and update our data with response in background?

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 5]
```diff
@@ -137,50 +155,116 @@ public void start(Listener listener) {
...
-        // The controller discovery API invoker.
+        @Override
+        @Synchronized
+        public void refresh() {
+            // Refresh is called as hints when gRPC detects network failures.
+            // We don't want to repeatedly attempt discovery; following logic will limit discovery on failures to
+            // once every FAILURE_RETRY_TIMEOUT_SECONDS seconds. Also we want to trigger discovery sooner on failures.
+            if (started.get()) {
+                if (this.scheduledFuture != null &&
+                        !this.scheduledFuture.isDone() &&
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: why not simply call this::getControllers in refresh rather than cancel and reschedule periodic refreshes?
anyway getControllers is synchronized, so even if both occur concurrently, our datastructure updates are protected under lock.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 6]
```diff
@@ -137,50 +155,116 @@ public void start(Listener listener) {
...
+                                    .stream()
+                                    .map(node ->
+                                            new ResolvedServerInfo(
+                                                    new InetSocketAddress(node.getEndpoint(), node.getPort())))
+                                    .collect(Collectors.toList()))
+                            .build();
+                } else {
+                    // Resolve the bootstrapped server hostnames to get the set of controllers.
+                    final ArrayList<InetSocketAddress> resolvedAddresses = new ArrayList<>();
+                    this.bootstrapServers.forEach(address -> {
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: just a suggestion: we can make this parallelForEach as each of them is potentially a networked call for dns resolution. so we can do it concurrently for all controller instances.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 3 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: This method is not supposed to be called multiple times. gRPC's default implementation (DnsNameResolver) makes the same assumption (though the API does not document this) and throws exception if start is attempted multiple times. I have followed the same pattern here.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 5 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: This serves 2 objectives as mentioned in the comment
1. prevents unnecessary getControllers calls, I have seen this method get called aggressively on failures.
2. retry getControllers sooner on failures (instead of waiting for the regular refresh which takes 2 minutes)

Also we should never schedule getControllers more than once as it may have cascading affect by schedule getContollers multiple times again and thus increasing the calls exponentially

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 4 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: We could make this non-blocking if we really want to optimize the thread usage for this, especially if using an external executor. Since we make only one call at a time and have a dedicated thread for this, we don't need to do this. I'll file an issue for this since this is non-trivial, especially for DNS lookups. The current java apis for DNS lookups are blocking, and we may have to explore using 3rdparty libraries for a non-blocking DNS client.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Good suggestion, will do

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 2 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: I have filed an issue for this - https://github.com/pravega/pravega/issues/1546. Since apart from using external executor this will require making all calls made in the context of this executor non-blocking.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 4 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Filed - https://github.com/pravega/pravega/issues/1546 for this.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 5 above)
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: i am not suggesting that we schedule it more than once.. i am saying there is a background periodic schedule.. and there can explicit calls. 
i think your (1) is supposed to be an answer to that. but even there, i just see that with every refresh (no matter how aggressive) we will keep calling this method and rescheduling it. 
alternatively we can have something like following:
1. keep a global last update time. 
2. always check if last call and current call has enough time elapsed. if yes, run immediately, else let it be scheduled in its next cycle.

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: This is just a heuristic to attempt retry faster (instead of waiting too long), doesn't have to be entirely accurate. Will additionally keep a last update time, this will only enable retries faster in certain corner cases though.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: After reviewing the cost of using parallel streams, I would stick to the current approach. We only have limited entries here and DNS queries are cached most of the time. The cost of creating parallel streams and synchronization doesn't seem to be justified for this small set of entries.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 2 above)
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: I don't understand your point, it is not an external thread pool, this is a thread pool that exists in the connection factory impl:

https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java#L56

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: ConnectionFactoryImpl is external to ControllerImpl. Also the executor created there seems to be used by the pravega segmentstore client writer. If we re-use this in the Contoller client we need to ensure we don't use this for any blocking operations as that might impact the pravega writer. I'll filed the issue to ensure we start using this executor after we remove all blocking operations from the Controller client. If you think we should do it as part of this PR itself, I can give it a a try.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: do we need extra synchronizations? 
this method is lock protected so only one run which can start parallel operations and collect their result.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 2 above)
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: controllerImpl initialization is performed by our writers/readers and is hidden to the application.
ControllerImpl can take in an executor as input which the reader/writer can set by taking it from ConnectionFactoryImpl. Does that work?

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Yes that's how it will be done, after removing the blocking operations in the controller client task.

Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: My main worry is adding technical debt, but I'm equally worried that if we do it here, it will make it harder to verify. I'm tempted to follow your suggestion of addressing it separately as it doesn't add any correctness issue.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: I guess synchronization was the wrong word for it. I meant the cost associated with using multiple threads, i.e. for creating substreams and merging the results. Need to understand which threads get used for this operation and costs associated with it (using the fork/join pool? and any waits associated with it). Without parallelism we are sure the operations will use the current thread and doesn't need additional resources. Need to explore this further to avoid any surprises

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 2 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Its a simple change to use the external executor now (since I don't assume any more that its singlethreaded). Only worry is the executor in the connectionFactory has very limited number of threads, and the currently implementation doesn't use it for any blocking operations (hence should be sufficient and efficient). But using it here without the non-blocking implementation might impact the writers usage of this unpredictably.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Verified from the doc that there is no option to specify executor for this and always uses fork-join pool. Hence doing any blocking operations in this is not recommended.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 5 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Now used lastUpdateTimeMS to improve the retry time even further.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 3 above)
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: As a general rule, I always encourage adding a meaningful message to any exception being thrown. That message will be added to the log and make debugging easieer.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 7]
```diff
@@ -137,50 +159,127 @@ public void start(Listener listener) {
...
+            this.scheduledFuture = this.scheduledExecutor.schedule(this::getControllers, 0L, TimeUnit.SECONDS);
+            started.set(true);
         }
 
+        // This API should not be under a lock as this is already thread safe and we don't want to block the shutdown.
         @Override
-        @Synchronized
         public void shutdown() {
             Preconditions.checkState(started.compareAndSet(true, false));
             if (this.scheduledExecutor != null) {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: A good pattern for this is something along these lines:
```
val e = this.scheduledExecutor;
if (e != null) {
    e.shutdownNow();
    this.scheduledExecutor = null;
}
```
This will clear up the variable once executed. Also, if `this.scheduledExecutor` were an `AtomicReference`, then you could have used the atomic `getAndSet` to ensure that any concurrent calls don't step on each other.

Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Actually this code is not thread safe. `start` is declared as `@Synchronized` but this method is not (at least no longer). The `scheduledExecutor` needs to either be guarded by the lock variable or declared as an `AtomicReference`.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 8]
```diff
@@ -137,50 +159,127 @@ public void start(Listener listener) {
...
+                                    .map(address -> new ResolvedServerInfo(
+                                            new InetSocketAddress(address.getHostString(), address.getPort())))
+                                    .collect(Collectors.toList()))
+                            .build();
+                    log.info("Updating client with controllers: {}", serverInfoGroup);
+                    this.resolverUpdater.onUpdate(Collections.singletonList(serverInfoGroup), Attributes.EMPTY);
+                    started.set(true);
+                    return;
+                }
+                // else case is for controllers with DNS hostnames, which needs to be resolved periodically.
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Rather than commenting in an else block, please structure the conditions so this is clear

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 9]
```diff
@@ -121,10 +143,10 @@ public String getServiceAuthority() {
         @Override
         @Synchronized
         public void start(Listener listener) {
```
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: This is not a general purpose class. This is an implementation of an interface which has to be registered with gRPC, which internally manages the lifecycle of this class. Not sure why we need to make this a guava service.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 8 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Its not an else block, just a comment

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 6 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: yes, we discussed this and will do as part of https://github.com/pravega/pravega/issues/1546, when using completable futures makes sense.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 10]
```diff
@@ -137,50 +159,127 @@ public void start(Listener listener) {
...
 
                 // Update gRPC load balancer with the new set of server addresses.
                 log.info("Updating client with controllers: {}", serverInfoGroup);
                 this.resolverUpdater.onUpdate(Collections.singletonList(serverInfoGroup), Attributes.EMPTY);
-            } catch (StatusRuntimeException e) {
-                log.warn("Failed to fetch controller addresses - {}", e);
-                this.resolverUpdater.onError(e.getStatus());
+
+                // We have found at least one controller endpoint. Repeat discovery after the regular schedule.
+                this.scheduledFuture = this.scheduledExecutor.schedule(
```
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Yes thats another way to do it and makes sense when we use external executor (https://github.com/pravega/pravega/issues/1546). With the dedicated thread model current implementation is much simpler.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 11]
```diff
@@ -137,50 +159,127 @@ public void start(Listener listener) {
...
+                // Catching all exceptions here since this method should never exit without rescheduling the discovery.
+                if (e instanceof StatusRuntimeException) {
+                    this.resolverUpdater.onError(((StatusRuntimeException) e).getStatus());
+                } else {
+                    this.resolverUpdater.onError(Status.UNKNOWN);
+                }
+                log.warn("Failed to construct controller endpoint list: ", e);
+
+                // Attempt retry with a lower timeout on failures to improve re-connectivity time.
+                this.scheduledFuture = this.scheduledExecutor.schedule(
```
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: We current use a dynamic schedule to optimize on the number of times this task is invoked. When we use the async version (https://github.com/pravega/pravega/issues/1546) we could review this approach.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 7 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Need to handle a case to block all API calls once shutdown is initiated, since we don't support restarts here. Will check if this is required and update

**Comment by skrishnappa** [comment]
Created an issue to include a test case for verifying handling of DNS propagation delays with the internal periodic refreshes. https://github.com/pravega/pravega/issues/1562. Need to investigate further how to simulate this, hence not doing it as part of this PR.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 9 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Because it deals with threads for lifecycle methods correctly. As it stands the code does not. It either needs to add locking everywhere the executor is refrenced or make it an atomic reference.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 12]
```diff
@@ -137,50 +146,154 @@ public void start(Listener listener) {
...
+                } else {
+                    this.resolverUpdater.onError(Status.UNKNOWN);
+                }
+                log.warn("Failed to construct controller endpoint list: ", e);
+
+                // Attempt retry with a lower timeout on failures to improve re-connectivity time.
+                nextScheduleTimeMS = FAILURE_RETRY_TIMEOUT_MS;
+            } finally {
+                // We avoid all blocking calls under a lock.
+                synchronized (this.$lock) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Please create a private method for this so you can use the annotation normally. (It avoids false-positives from static analysis tools)

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 13]
```diff
@@ -107,24 +128,12 @@ public String getDefaultScheme() {
          * @param enableDiscovery   Whether to use the controller's discovery API.
          */
         ControllerNameResolver(final String authority, final List<InetSocketAddress> bootstrapServers,
-                                      final boolean enableDiscovery) {
+                               final boolean enableDiscovery) {
             this.authority = authority;
-            this.bootstrapServers = bootstrapServers;
+            this.bootstrapServers = new ArrayList<>(bootstrapServers);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: ImmutableList

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 14]
```diff
@@ -137,50 +146,154 @@ public void start(Listener listener) {
...
+                                    .stream()
+                                    .map(node ->
+                                            new ResolvedServerInfo(
+                                                    new InetSocketAddress(node.getEndpoint(), node.getPort())))
+                                    .collect(Collectors.toList()))
+                            .build();
+                } else {
+                    // Resolve the bootstrapped server hostnames to get the set of controllers.
+                    final ArrayList<InetSocketAddress> resolvedAddresses = new ArrayList<>();
+                    this.bootstrapServers.forEach(address -> {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: (Unrelated to the other thread on this line)
bootstrapServers is guared by $lock but is not protected on this line. This method is effectively public because it is passed as a function externally. So no lock is held.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java [hunk 15]
```diff
@@ -137,50 +146,154 @@ public void start(Listener listener) {
...
-            } catch (StatusRuntimeException e) {
-                log.warn("Failed to fetch controller addresses - {}", e);
-                this.resolverUpdater.onError(e.getStatus());
+
+                // We have found at least one controller endpoint. Repeat discovery after the regular schedule.
+                nextScheduleTimeMS = REFRESH_INTERVAL_MS;
+            } catch (Throwable e) {
+                // Catching all exceptions here since this method should never exit without rescheduling the discovery.
+                if (e instanceof StatusRuntimeException) {
+                    this.resolverUpdater.onError(((StatusRuntimeException) e).getStatus());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Here and two lines below and at the bottom of the try block above: resolverUpdater is being called without holding the lock that is supposed to guard it.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 13 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Immutable list just create a view and not a copy, so still not thread safe

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 14 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: bootstrapServers is final and not guarded

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 15 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: assignment to resolverUpdater is guarded. Access to the var here cannot contend with the assignment hence not guarded here, its guaranteed to have been assigned before this call. Also resolverUpdater is threadsafe so we can make calls to it without holding an external lock.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 12 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Done

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 7 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Converted scheduledExecutor to a final variable

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 9 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Won't we have to make internal changes to gRPC if this is made a guava service? Anyway the class is thread safe now.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 13 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Sorry, I mistook this for java's unmodifiablelist, I guess the guava version is threadsafe. Will verify and use it.

Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Done, using ImmutableList now.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 15 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: > Access to the var here cannot contend with the assignment

That is simply not true. In the Java memory model things are allowed to be arranged if there is no memory barrier. For example:
Thread 1 calls start() is assigns the listener.
Thread 2 calls refresh() because there is an @synchronize block everything in thread 2 happens after the call to start(). But at the end of refresh it sets up a call to getControllers() to run in a background thread.
The background thread starts and executes getControllers(), there is no synchronization encountered so it is free to that CPU core's cache of the variables rather than accessing main ram, it could so happen that this core has a cached version of the object before the assignment of resolverUpdater from before it was assigned in start().
So even though the external caller didn't do anything other than use this class as the interface dictated this line will thrown an NPE and it will take a long time to figure out why.

The threading rules that we put together in our contributing guidelines exist for a reason. They are a sane way to make sure everything is threadsafe. Please follow them. Because anytime you don't, I'll bet money that there is a race condition you haven't thought about, like the one here.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 14 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: yes. Sorry, I was confused.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java (hunk 15 above)
Comment (skrishnappa) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: Thanks for the explanation. The null checks in refresh and start before launching getControllers was to avoid these issues, but yeah this doesn't guard against all cases (i.e. if the object with null value was cached even before start or refresh was called).
I have made the variable volatile which should address the issue, let me know if you think otherwise. Other options were
* Use atomic reference - not necessary here since the only check and set operations are already inside of a lock.
* Move access to this variable inside of the synchronization block - This can still be done without doing any blocking operations inside of a lock, but requires a bit of not so elegant juggling in the code, so avoiding it.

Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java]: My general preference as atomic reference, because it gives a clean interface and clear semantics. Of course volatile and atomic reference are equivalent, as AtomicReference is just a bunch of utility functions and a volatile member. The other option, if you find for what ever reason you need the synchronization block anyway, is to just assign to a local variable inside of the syncronized block and then make the blocking call outside of it. 

In this case any of the above are fine.
