### PR TITLE
Issue 3404: Unit tests: Controller tests use large number of connections 

### LINKED ISSUE #3404: Controller tests use large number of connections
**Problem description**
When running tests (especially if parallelism is turned on) sometimes the controller tests fail because there are too many open file descriptors. For example:
```
        Caused by:
        io.netty.channel.ChannelException: eventfd() failed: Too many open files
            at io.netty.channel.epoll.Native.eventFd(Native Method)
            at io.netty.channel.epoll.Native.newEventFd(Native.java:93)
            at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:101)
            at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:135)
            at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
            at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
            ... 13 more

    java.lang.NullPointerException

io.pravega.controller.rest.v1.PingTest$FailingSecurePingTest > test FAILED
    java.lang.IllegalStateException: failed to create a child event loop

        Caused by:
        io.netty.channel.ChannelException: eventfd() failed: Too many open files
```

**Problem location**
Controller tests.

**Suggestions for an improvement**
This could happen is if a connectionFactory is not closed at the end of a test. That should be the first thing to check.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
Closing connection factory at the end of the tests. 

**Purpose of the change**  
Fixes #3404 

**What the code does**  
Closes ConnectionFactory at the end of tests

**How to verify it**  
No more "too many open files" while running unit tests locally.

### CODE REVIEW

File: client/src/test/java/io/pravega/client/stream/mock/MockConnectionFactoryImpl.java [hunk 1]
```diff
@@ -56,5 +56,6 @@ public ReplyProcessor getProcessor(PravegaNodeUri location) {
 
     @Override
     public void close() {
+        executor.shutdown();
```
Comment (andreipaduroiu) [inline client/src/test/java/io/pravega/client/stream/mock/MockConnectionFactoryImpl.java]: `ExecutorServiceHelpers.shutdown(executor)`

File: controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataAuthFocusedTests.java [hunk 2]
```diff
@@ -184,10 +187,11 @@ public static void initializer() throws IOException, InvalidKeySpecException, No
         mockControllerService = mock(ControllerService.class);
         serverConfig = RESTServerConfigImpl.builder().host("localhost").port(TestUtils.getAvailableListenPort()).build();
         LocalController controller = new LocalController(mockControllerService, false, "");
+        connectionFactory = new ConnectionFactoryImpl(ClientConfig.builder()
+                                                                                        .controllerURI(URI.create("tcp://localhost"))
```
Comment (andreipaduroiu) [inline controller/src/test/java/io/pravega/controller/rest/v1/StreamMetaDataAuthFocusedTests.java]: Indentation

File: controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java [hunk 3]
```diff
@@ -577,7 +578,7 @@ public ScheduledExecutorService getInternalExecutor() {
 
         @Override
         public void close() {
-
+            connection.close();
```
Comment (andreipaduroiu) [inline controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java]: What if it's null?

File: controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java [hunk 4]
```diff
@@ -67,20 +67,21 @@
 
     private final StreamMetadataStore streamStore = StreamStoreFactory.createInMemoryStore(executor);
 
-    private final StreamMetadataTasks streamMetadataTasks;
-    private final StreamTransactionMetadataTasks streamTransactionMetadataTasks;
-    private final ConnectionFactoryImpl connectionFactory;
-    private final ControllerService consumer;
+    private StreamMetadataTasks streamMetadataTasks;
```
Comment (tkaitchuck) [inline controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java]: Why is final removed from all of these? I don't see them modified elsewhere.

File: controller/src/test/java/io/pravega/controller/task/TaskTest.java [hunk 5]
```diff
@@ -83,21 +83,23 @@
     private final StreamConfiguration configuration1 = StreamConfiguration.builder().scalingPolicy(policy1).build();
     private final ScheduledExecutorService executor = Executors.newScheduledThreadPool(10);
 
-    private final StreamMetadataStore streamStore;
+    private StreamMetadataStore streamStore;
```
Comment (tkaitchuck) [inline controller/src/test/java/io/pravega/controller/task/TaskTest.java]: Same here

File: controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java [hunk 6]
```diff
@@ -74,18 +76,20 @@
...
-    private final ScheduledExecutorService executor;
-    private final TestingServer zkTestServer;
-    private final CuratorFramework client;
-    private final StreamMetadataTasks streamMetadataTasks;
-    private final StreamTransactionMetadataTasks streamTransactionMetadataTasks;
-    private final StoreClient storeClient;
-    private final RequestTracker requestTracker = new RequestTracker(true);
-
-    public TimeoutServiceTest() throws Exception {
+    private StreamMetadataStore streamStore;
```
Comment (tkaitchuck) [inline controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: And here

File: controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java]: actually they were  being initialized in a constructor in these test.. 
now i have changed it to be initialized in `@Before setUp` method and closed in `@After tearDown` which is called before and after each test. since its not initialized in constructor, rather no test constructor, so no final business..

File: controller/src/test/java/io/pravega/controller/task/TaskTest.java (hunk 5 above)
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/task/TaskTest.java]: replied above

File: controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java (hunk 6 above)
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: above
