### PR TITLE
Issue 3477: Fixes on EventProcessors during Controller graceful restart

### LINKED ISSUE #3477: Handle ZK-related exceptions from HostStore when shutting down Controller
**Problem description**
The fix for the ZK session expiration with different connection parameters issue (#3387) uncovered another problem: It seems that the modules using `ZKHostStore` will throw `HostStoreException` because of ZK session expiration. These exceptions seem not to be properly handled during the `shutDown()` process of `ControllerServiceStarter`, and then the graceful restart does not work (the process terminates):

1) Detect session expiration with different ZK connection parameters
``` 
2019-03-14 17:12:42,390 118846521 [ControllerServiceMain-EventThread] WARN  i.p.c.s.client.StoreClientFactory - Input argument for new ZooKeeper client (A:2181,B:2181,C:2181, 10000, false) changed with respect to existing client (X:2181, 10000, false).
java.lang.IllegalArgumentException: connectString differs
```
2) As expected, after the expiration the Controller now is able to initiate a graceful restart:
```
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] INFO  o.a.zookeeper.ZooKeeperTestable - injectSessionExpiration() called
2019-03-14 17:12:42,393 118846524 [ControllerServiceMain-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: LOST
2019-03-14 17:12:42,393 118846524 [controllerpool-63] ERROR i.p.c.cluster.zkImpl.ClusterZKImpl - Connection lost with Zookeeper
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] INFO  i.p.c.fault.SegmentMonitorLeader - Zookeeper connection state changed to: LOST
2019-03-14 17:12:42,393 118846524 [Curator-ConnectionStateManager-0] WARN  i.p.c.fault.SegmentContainerMonitor - Connection to zookeeper lost, attempting to interrrupt the leader thread
2019-03-14 17:12:42,393 118846524 [Curator-PathChildrenCache-0] WARN  i.p.c.s.b.ZooKeeperBucketManager - RetentionService: Received connectivity error
2019-03-14 17:12:42,394 118846525 [controllerpool-63] INFO  i.p.c.f.ControllerClusterListener - Received error event when monitoring the controller host cluster, ignoring...
2019-03-14 17:12:42,394 118846525 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - ZK session expired
2019-03-14 17:12:42,394 118846525 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Stopping ControllerServiceStarter
2019-03-14 17:12:42,410 118846541 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Awaiting termination of ControllerServiceStarter
2019-03-14 17:12:42,411 118846542 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service shutDown
2019-03-14 17:12:42,411 118846542 [RESTServer STOPPING] INFO  i.p.c.server.rest.RESTServer - Stopping REST server listening on port: 10080
2019-03-14 17:12:42,411 118846542 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller event processors
2019-03-14 17:12:42,411 118846542 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Stopping gRPC server listening on port: 9090
2019-03-14 17:12:42,413 118846544 [GRPCServer STOPPING] INFO  i.p.c.server.rpc.grpc.GRPCServer - Awaiting termination of gRPC server
2019-03-14 17:12:42,443 118846574 [ControllerServiceMain-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10002a4c8ea00e1
2019-03-14 17:12:42,443 118846574 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping the segment container monitor
2019-03-14 17:12:42,443 118846574 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping controller event processors
2019-03-14 17:12:42,443 118846574 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping controller cluster listener
2019-03-14 17:12:42,444 118846575 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Controller cluster listener shutdown
2019-03-14 17:12:42,444 118846575 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Stopping auto retention service
```

3) However, the Event Processors using `ZKHostStore` do not properly handle the fact that the ZK client is closed, and they throw `HostStoreException`:
```
2019-03-14 17:12:57,460 118861591 [EventProcessorGroupImpl STOPPING] WARN  i.p.c.e.i.EventProcessorGroupImpl - Error sealing reader group EventProcessorGroup[scaleGroup]
io.pravega.controller.store.checkpoint.CheckpointStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/eventProcessors/YYY-2b26df87-4c14-4197-b522-7ebf2daed64f/scaleGroup
	at io.pravega.controller.store.checkpoint.ZKCheckpointStore.sealReaderGroup(ZKCheckpointStore.java:114)
	at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.shutDown(EventProcessorGroupImpl.java:164)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/eventProcessors/YYY-2b26df87-4c14-4197-b522-7ebf2daed64f/scaleGroup
...
2019-03-14 17:12:59,803 118863934 [Delegate] WARN  i.p.c.e.impl.EventProcessorCell - Restarting event processor: EventProcessor[commitStreamReaders:0] due to exception: {}
io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
	at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:81)
	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:106)
	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:125)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/cluster/segmentContainerHostMapping
```

4) In the presence of any exception during shutdown, the `ControllerServiceStarter` will terminate the process:
```
java.lang.IllegalStateException: Expected the service ControllerServiceMain [FAILED] to be TERMINATED, but the service has FAILED
```

Moreover, we have not detected this issue with the test added in `testZKSessionExpiry()` in `ZKControllerServiceMainTest` because the mock Controller being instantiated does not initialize event processors (i.e., `eventProcessorConfig(Optional.empty()`), as it would require to create also a segment store for the internal streams.

**Problem location**
Controller restart process.

**Suggestions for an improvement**
Handle the case of a full graceful restart when ZK session is expired.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Allow EventProcessorCell i) to close its readers at the position of the last processed event, and ii) to handle HostStoreException derived from a ZK session expiration.

**Purpose of the change**  
Fixes #3477 (partially).

**What the code does**  
In PR #3387, we fixed a problem that prevented the Controller to restart upon a session expiration with different Zookeeper connection parameters compared to the original ones. Once this problem has been solved, during the graceful restart, we discovered that `ControllerEventProcessors` cannot shutdown correctly, which makes the whole Controller process to terminate.

In this PR, we identified and fixed 2 issues regarding the shutdown of Event Processors:
- The `EventProcessorCell` should close its readers at the position of the last "processed event". This position may be different from the last "read event". By default, invoking `close` on a reader could lead to close the reader on a position different to the last "processed event", which is not suitable. To this end, we added a new method (`closeAt`) in `EventStreamReader` to cope with this scenario. 

- One of the problems we identified is related to the fact that `EventProcessorCell` may get unhandled  `HostStoreException`s while shutting down, originated by the expiration of the Zookeeper session. This PR just handles that potential exception in `EventProcessorCell`. 

**How to verify it**  
All tests exercising Controller restarts should pass, as well as the rest of tests.

### CODE REVIEW

**Comment by RaulGracia** [comment]
[Handle ZK-related exceptions from HostStore when shutting down Controller](https://trello.com/c/JhT7BxR2/153-handle-zk-related-exceptions-from-hoststore-when-shutting-down-controller)

File: client/src/main/java/io/pravega/client/stream/EventStreamReader.java [hunk 1]
```diff
@@ -71,4 +71,12 @@
...
     @Override
     void close();
+
+    /**
+     * Close the reader. No further actions may be performed. If this reader is part of a {@link ReaderGroup}, this will
+     * automatically invoke {@link ReaderGroup#readerOffline(String, Position)} with the supplied position.
+     *
+     * @param position {@link Position} to use while reporting readerOffline on the {@link ReaderGroup}.
+     */
+    void close(Position position);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: I'm 👎 for this change. This is introducing a close call to a public facing API that has an argument while this class extends `AutoCloseable`. This is far from being elegant. If we need to remove the reader at a given position, can't we invoke `readerOffline`, which is a call that exists precisely for that purpose?

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 2]
```diff
@@ -132,11 +143,19 @@ protected final void shutDown() throws Exception {
 
                 // First close the reader, which implicitly notifies reader position to the reader group
                 log.info("Closing reader for {}", objectId);
-                reader.close();
+                try {
+                    reader.close(getCheckpoint());
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: I don't understand why we need to do this. In the case we do need to stop the reader at the latest checkpoint, then can we either produce a checkpoint right before calling close or call `readerOffline` as suggested above?

File: client/src/main/java/io/pravega/client/stream/EventStreamReader.java (hunk 1 above)
Comment (shiveshr) [reply client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: If readerOffline fails, we still want to close the reader (so that any resources taken by the object are not leaked). but since reader.close explicitly sets the position which we do not want, we want to merge the two methods into one so that we tell the close method which position to use while closing.

Comment (shiveshr) [reply client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: The alternative is to have a flag in the reader which can disable automatic update of position during close. So even if readergroup.readerOffline fails, we dont have to worry about reader updating a position that we never intended it to.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: I'm not sure readerOffline failing should be the concern. 
The larger case here is one of ergonomics. Calling close exits gracefully at the current position. 
readerOffline notifies the reader group the reader has already closed at a particular position. But it does seem weird to invoke readerOffline followed by close on the client when it wants to exit from a different position. Though it does work. 

That being said, autoclosable is a common enough of a thing that it might end up invoking close() after close(pos) just do to how code is structured. (We can tolerate that, but it's still weird.)

Comment (fpj) [reply client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: @tkaitchuck and I had an offline discussion about this and I want to reflect that conversation here along with the suggestion.

- We understand that the flow of calling `readerOffline` to stop an event reader at a given `Position` is odd because we need to instantiate a different object (a `ReaderGroup`) to be able to call it.
- Based on the previous point, we really need a call in `EventStreamReader` that stops at a given position, which is essentially the approach proposed here.
- If we are to create a new method, then we have two options:
   1- Have an additional call to set the position and then call close.
   2- Have an additional call that replaces the call to close. 
- Calling the method `close` has the problem of conflicting with the `close` from `AutoCloseable`. We started discussing options to reflect what it is that we are trying to do. We somehow are trying to close "ungracefully" because we are not closing at the last position. It is not ungraceful in the sense that reader is dropping it on the floor, but in the sense that it is not acknowledging that it has processed everything it has read. Consequently, we have gone through few options of names: `die`, `shutdown`, `stop`. To differentiate from the `close` of `AutoCloseable` but keep the semantics intact, we suggest to name it `closeAt(Position)`.

That's a minimal change and should unblock this PR.

File: controller/src/main/java/io/pravega/controller/eventProcessor/EventProcessorExecutionException.java [hunk 3]
```diff
@@ -0,0 +1,31 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/EventProcessorExecutionException.java]: Can you change the year to 2019?

File: client/src/main/java/io/pravega/client/stream/EventStreamReader.java (hunk 1 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/stream/EventStreamReader.java]: Another comment I forgot to add is that the javadoc should capture precisely why we need this call and in which cases the application should consider using it.

**Comment by RaulGracia** [comment]
@tkaitchuck @shiveshr @fpj let me update this PR with a reproduction of the issue and current PR changes:

1) The `ZKClientFactory` detects a Zookeeper session expiration with a change in `connectString`. This can be seen in this log message:
```
2019-04-11 15:05:33,329 115943414 [ControllerServiceMain-EventThread] WARN  i.p.c.s.client.StoreClientFactory - Input argument for new ZooKeeper client (172.24.52.3:2181,172.24.52.4:2181,172.24.52.5:2181, 10000, false) changed with respect to existing client (pravega-zk-client:2181, 10000, false).
```
2) The `ControllerServiceStarter` reacts to this event by starting a graceful shutdown:
```
2019-04-11 15:05:33,406 115943491 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - Initiating controller service shutDown
```
3) The most relevant part for this issue seems to be the shutdown process for EventProcessor. As we can see, the shutdown for them is started:
```
2019-04-11 15:05:33,408 115943493 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping commit event processors
2019-04-11 15:05:33,408 115943493 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping abort event processors
2019-04-11 15:05:33,408 115943493 [ControllerEventProcessors STOPPING] INFO  i.p.c.s.e.ControllerEventProcessors - Stopping request event processors
```
4) The Controller starts shutting down the different `EventProcessorGroups`:
```
2019-04-11 15:05:33,416 115943501 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2019-04-11 15:05:33,416 115943501 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
2019-04-11 15:05:33,416 115943501 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Attempting to seal the reader group entry from checkpoint store
```
5) With the new logs added, we can see that the shutdown for an `EventProcessorCell` shows a problem sealing the `ReaderGroup`:
```
log.info("Attempting to seal the reader group entry from checkpoint store");
checkpointStore.sealReaderGroup(actorSystem.getProcess(), readerGroup.getGroupName());
```
We get a `CheckpointStoreException`, given that the ZK session is lost (this happens for the 3 `EventProcessorCell`s):
```io.pravega.controller.store.checkpoint.CheckpointStoreException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /pravega/pravega/eventProcessors/172.24.52.9-b3568c2a-1593-4786-85fb-b317bbe888c3/commitStreamReaders```

6) But the worst problem comes when invoking the `stopAsync()` method of `EventProcessorCell`, where the controller gets stuck and cannot make further progress:
```
2019-04-11 15:08:11,179 116101264 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Awaiting termination of event processor cell: EventProcessor[abortStreamReaders:0][STOPPING]
2019-04-11 15:08:11,179 116101264 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Awaiting termination of event processor cell: EventProcessor[scaleGroup:0][STOPPING]
2019-04-11 15:08:11,183 116101268 [EventProcessorGroupImpl STOPPING] INFO  i.p.c.e.i.EventProcessorGroupImpl - Awaiting termination of event processor cell: EventProcessor[commitStreamReaders:0][STOPPING]
```

7) Apparently, the point in which the Controller gets stuck is while closing the Reader using the new `close(position)` call:
```
2019-04-11 15:08:12,153 116102238 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Closing reader for EventProcessor[abortStreamReaders:0]
```
The position passed to `EventStreamReaderImpl` seems to be `null` (maybe because automatic checkpoint is disabled?):
```
2019-04-11 15:08:12,153 116102238 [Delegate] INFO  i.p.c.s.impl.EventStreamReaderImpl - Closing reader EventStreamReaderImpl( id=c1cf79bb-4d22-4e78-9993-4b93d9f48cc5) at position null.
```
And then the Controller logs get stuck during the reader shutdown:
``` 
2019-04-11 15:08:12,154 116102239 [Delegate] INFO  i.p.c.s.i.ReaderGroupStateManager - Entering readerShutdown for reader c1cf79bb-4d22-4e78-9993-4b93d9f48cc5
2019-04-11 15:08:12,155 116102240 [Delegate] INFO  i.p.c.s.i.ReaderGroupStateManager - Shutting down reader c1cf79bb-4d22-4e78-9993-4b93d9f48cc5
2019-04-11 15:08:12,155 116102240 [Delegate] INFO  i.p.c.s.i.ReaderGroupStateManager - Removing reader c1cf79bb-4d22-4e78-9993-4b93d9f48cc5 from reader group. CurrentState is: ReaderGroupState{ CheckpointState { ongoingCheckpoints: [],  readersBlockingEachCheckpoint: {} } futureSegments: {} assignedSegments: {c1cf79bb-4d22-4e78-9993-4b93d9f48cc5={}, c1ffbcef-3974-4821-8956-3179073a62f4={_system/_abortStream/1.#epoch.0=0, _system/_abortStream/0.#epoch.0=0}} unassignedSegments: {} }
```
8 ) After that, there are 5 seconds without logs and then the Controller terminates:
```
2019-04-11 15:08:17,040 116107125 [Thread-1] INFO  io.pravega.controller.server.Main - Shutdown hook memory usage dump: Heap memory usage: init = 536870912(524288K) used = 243034992(237338K) committed = 672661504(656896K) max = 1431830528(1398272K), non heap memory usage init = 2555904(2496K) used = 68837088(67223K) committed = 72744960(71040K) max = -1(-1K)
2019-04-11 15:08:17,040 116107125 [Thread-1] INFO  io.pravega.controller.server.Main - Controller service shutting down
2019-04-11 15:08:17,040 116107125 [Thread-1] INFO  i.p.c.server.ControllerServiceMain - Shutting down ControllerServiceMain
```

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 4]
```diff
@@ -168,15 +168,13 @@ protected void shutDown() {
...
-                    log.info("Stopping {}", cell);
-                    // first report reader offline with the last position then shut it down.
-                    readerGroup.readerOffline(cell.getReaderId(), cell.getCheckpoint());
+                    log.info("Stopping event processor cell: {}", cell);
                     cell.stopAsync();
-                    log.info("Awaiting termination of {}", cell);
+                    log.info("Awaiting termination of event processor cell: {}", cell);
                     try {
                         cell.awaitTerminated();
                     } catch (IllegalStateException e) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: maybe we cab log on all exceptions here and not just illegal state

File: controller/src/main/java/io/pravega/controller/util/Config.java [hunk 5]
```diff
@@ -128,7 +128,7 @@
     private static final Property<Integer> PROPERTY_MIN_REBALANCE_INTERVAL_SECONDS = Property.named("minRebalanceIntervalSeconds", 10);
     private static final Property<Boolean> PROPERTY_REPLY_WITH_STACK_TRACE_ON_ERROR = Property.named("replyWithStackTraceOnError", false);
     private static final Property<Boolean> PROPERTY_REQUEST_TRACING_ENABLED = Property.named("requestTracingEnabled", true);
-    private static final Property<Boolean> PROPERTY_DUMP_STACK_ON_SHUTDOWN = Property.named("dumpStackOnShutdown", false);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/util/Config.java]: revert this before merging.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 6]
```diff
@@ -100,7 +103,16 @@ protected final void run() throws Exception {
 
             while (isRunning()) {
                 try {
-                    event = reader.readNextEvent(defaultTimeout);
+                    try {
+                        event = reader.readNextEvent(defaultTimeout);
+                    } catch (HostStoreException e) {
+                        // In the case of a SessionExpiredException, we don't want to restart (the Controller itself will).
+                        if (e.getCause() instanceof KeeperException.SessionExpiredException) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: As part of memory footprint improvements done in controller, we changed the mechanics of ZKHostStore to not make zk call for each look up. Instead we use NodeCache which populates a local map. 

So SessionExpiredException will not be thrown anymore. 

Secondly, in case of an In-Memory deployment, there is no notion of a session. So any SessionSpecific check here breaks the abstraction.

Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Thanks @shiveshr, I have removed this unnecessary exception handling.

File: controller/src/main/java/io/pravega/controller/util/Config.java (hunk 5 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/util/Config.java]: Done.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 4 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Done.

Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Done.

**Comment by RaulGracia** [comment]
@fpj @shiveshr @tkaitchuck Travis build is passing and system test do not present other failures that the ones that we are seeing in master. Please, consider merging this PR if there are not further comments.

**Comment by RaulGracia** [comment]
@fpj the code coverage check passing.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 7]
```diff
@@ -132,11 +131,19 @@ protected final void shutDown() throws Exception {
 
                 // First close the reader, which implicitly notifies reader position to the reader group
                 log.info("Closing reader for {}", objectId);
-                reader.close();
+                try {
+                    reader.closeAt(getCheckpoint());
+                } catch (Exception e) {
+                    log.error("Exception while closing EventProcessorCell reader from checkpointStore: ", e);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Given that we are in the mode of cleaning up unneeded stack traces, I'm wondering why we need to output the stack trace as part of shutting down. 

Also, if this is an "error", then it means that it is unrecoverable, which I can understand because we are not sure about what happened to the reader close call. What's the user supposed to do when seeing this log error messages?

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 8]
```diff
@@ -132,11 +131,19 @@ protected final void shutDown() throws Exception {
...
+                }
 
                 // Next, clean up the reader and its position from checkpoint store
                 log.info("Cleaning up checkpoint store for {}", objectId);
-                checkpointStore.removeReader(process, readerGroupName, readerId);
+                try {
+                    checkpointStore.removeReader(process, readerGroupName, readerId);
+                } catch (Exception e) {
+                    log.error("Exception while removing reader from checkpointStore: ", e);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Same questions here.
