### PR TITLE
Issue 2168: (SegmentStore) StorageWriter can't handle recovery with partially written appends

### LINKED ISSUE #2168: StorageWriter fails post-recovery with partially written appends
**Problem description**
We have observed the following exception in the segment store while running some tests:

```
2017-12-07 18:35:51,305 80300529 [segment-store-3] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[2]: Iteration[9376].Error.
java.lang.IllegalArgumentException: startOffset must refer to an offset beyond the Segment's StorageLength offset.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.readDirect(StreamSegmentReadIndex.java:581)
    at io.pravega.segmentstore.server.reading.ContainerReadIndex.readDirect(ContainerReadIndex.java:176)
    at io.pravega.segmentstore.server.writer.StorageWriterFactory$StorageWriterDataSource.getAppendData(StorageWriterFactory.java:123)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.getFlushArgs(SegmentAggregator.java:649)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.flushPendingAppends(SegmentAggregator.java:598)
    at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushExcess$14(SegmentAggregator.java:579)
    at io.pravega.common.concurrent.FutureHelpers$Loop.call(FutureHelpers.java:642)
    at io.pravega.common.concurrent.FutureHelpers$Loop.call(FutureHelpers.java:611)
    at io.pravega.common.concurrent.FutureHelpers.runOrFail(FutureHelpers.java:524)
    at io.pravega.common.concurrent.FutureHelpers$Loop.run(FutureHelpers.java:655)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This error has been found against our 0.1 release, so it is possible that it is not an issue any longer, but I couldn't find a related issue. Unfortunately, we don't have for now any more information that this stack trace for now, although it seems to be related to an issue with BookKeeper.

**Problem location**
Segment store.

**Suggestions for an improvement**
Determine whether it is an issue or not and fix in the case it is.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in `SegmentAggregator` where it would fail post-recovery if an append was already partially written to Storage.

Details:
- Writes to Tier2 Storage are capped (to a configurable value, default 1MB). A single write can aggregate multiple appends to a Segment, and as such, an append can be split across multiple Storage Writes.
- As such, it is quite likely that an append may be split across multiple such Tier2 writes, and some complete but at least one does not (since the process may have crashed or we failed over to some other host).
- Upon recovery, the `StorageWriter` must handle this situation and ensure that only those bytes which haven't been written are added.
- Prior to this change, the `StorageWriter` would do no such thing, and it would incorrectly attempt to rewrite the whole append. Had it not been for the safety check in the `ReadIndex` to prevent it from fetching the data, it would have corrupted the data in Tier2.

**Purpose of the change**
Fixes #2168 .

**What the code does**
See description.

**How to verify it**
New unit test added to exercise this particular case.

### CODE REVIEW

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java [hunk 1]
```diff
@@ -273,6 +274,16 @@ public InputStream getAppendData(long streamSegmentId, long startOffset, int len
         }
 
         synchronized (this.lock) {
+            // Perform the same validation checks as the ReadIndex would do.
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java]: Just so that I understand: in the case we change these checks in the `ReadIndex`, do we have to remember to do it here too? Could we avoid the duplication?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java [hunk 2]
```diff
@@ -386,6 +386,13 @@ private void acknowledgeAlreadyProcessedOperation(StorageOperation operation) {
      */
     private void aggregateAppendOperation(StorageOperation operation, AggregatedAppendOperation aggregatedAppend, int maxLength) {
         long remainingLength = operation.getLength();
+        if (operation.getStreamSegmentOffset() < aggregatedAppend.getLastStreamSegmentOffset()) {
+            // The given operation begins before the AggregatedAppendOperation. This is likely due to it having been
+            // partially written to Storage prior to some recovery event. We must make sure we only include the part that
+            // has not yet been written.
+            remainingLength -= aggregatedAppend.getLastStreamSegmentOffset() - operation.getStreamSegmentOffset();
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java]: Let's add a debug log message to indicate that this has happened.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/TestWriterDataSource.java]: This `TestWriterDataSource` is an emulation of the entire world outside of the `StorageWriter` (`ReadIndex` + `DurableLog`). I don't see an easy way to share 3 lines of code between such remote components.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java]: Fixed.
