### PR TITLE
Issue 4453: Fix bug in FileSystemStorage.doRead

### LINKED ISSUE #4453: Bug in FileSystemStorage.doRead
**Problem description**
This code in `FileSystemStorage.java#doRead`:
```
        try (FileChannel channel = FileChannel.open(path, StandardOpenOption.READ)) {
            int totalBytesRead = 0;

            do {
                ByteBuffer readBuffer = ByteBuffer.wrap(buffer, bufferOffset, length);
                int bytesRead = channel.read(readBuffer, offset);
                bufferOffset += bytesRead;
                totalBytesRead += bytesRead;
                length -= bytesRead;
            } while (length != 0);
            FileSystemMetrics.READ_LATENCY.reportSuccessEvent(timer.getElapsed());
            FileSystemMetrics.READ_BYTES.add(totalBytesRead);
            LoggerHelpers.traceLeave(log, "read", traceId, totalBytesRead);
            return totalBytesRead;
        }
```

has a bug at 
```
                int bytesRead = channel.read(readBuffer, offset);
```

The variable `offset` is never updated, which means every iteration of this loop will end up reading the same data over and over again, thus reading incorrect data. 

**Problem location**
FileSystemStorage.java.

**Suggestions for an improvement**
Update `offset` by adding `bytesRead` at the end of the loop. Verify this using unit tests.

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Fix bug in FileSystemStorage.doRead
Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
Fix bug in FileSystemStorage.doRead

**Purpose of the change**  
Fixes #4453

**What the code does**  
Fixes bug with offset.

**How to verify it**  
All tests should pass.

### CODE REVIEW

**Comment by sachin-j-joshi** [comment]
Added unit test with FileChannel mock. (later on we can add more mock based tests .)

**Comment by RaulGracia** [comment]
@sachin-j-joshi please check findbugs in this PR as the build is not passing:
```
* What went wrong:
Execution failed for task ':bindings:spotbugsTest'.
> A failure occurred while executing com.github.spotbugs.internal.spotbugs.SpotBugsRunner
   > SpotBugs rule violations were found. See the report at: file:///home/travis/build/pravega/pravega/bindings/build/reports/spotbugs/test.html
```

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java [hunk 1]
```diff
@@ -197,6 +197,14 @@ public void close() {
 
     //endregion
 
+    protected FileChannel getFileChannel(Path path, StandardOpenOption openOption) throws IOException {
```
Comment (andreipaduroiu) [inline bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: Please add `@VisibleForTesting` for both these methods.

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+        // This will break when jdk decides to change implementation.
+        Field closeLockField = AbstractInterruptibleChannel.class.getDeclaredField("closeLock");
+        closeLockField.setAccessible(true);
+        closeLockField.set(mockFileChannel, new Object());
+    }
+
+    /**
+     * Test Class.
+     */
+    class TestFileSystemStorage extends FileSystemStorage {
```
Comment (andreipaduroiu) [inline bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: `private static`

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+        FileChannel channel;
```
Comment (andreipaduroiu) [inline bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: `private final`

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+
+        @Getter
+        @Setter
+        long sizeToReturn;
```
Comment (andreipaduroiu) [inline bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: `private`

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+import java.nio.file.Path;
+import java.nio.file.StandardOpenOption;
+import java.time.Duration;
+import java.util.List;
+
+import static org.junit.Assert.assertEquals;
+import static org.mockito.ArgumentMatchers.any;
+import static org.mockito.Mockito.*;
+
+public class FileSystemMockTests {
```
Comment (andreipaduroiu) [inline bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: Why didn't you put these tests in the `FileSystemStorageTests.java` class?

Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: Because mock based tests are testing in a fundamentally different way. We need to inherit from FileSystemStorage and setup mock and calls every explicitly. Therefore keeping them in a separate file. (Plus I'll be adding more mock based tests later.)

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java (hunk 1 above)
Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: fixed.

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java (hunk 3 above)
Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: fixed.

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java (hunk 4 above)
Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: fixed.

File: bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java (hunk 2 above)
Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/filesystem/FileSystemMockTests.java]: fixed
