### PR TITLE
Issue 1542: Lock not getting transferred from a dead controller instance to the active controller instance

### LINKED ISSUE #1542: Lock not getting transferred from a dead controller instance to the active controller instance
**Problem description**
Lock is not getting transferred from a dead controller instance to the active controller instance. This is observed when multiControllerSystem test is the first test to run.

When multiController test was run there were no SSS so stream internal creation had not completed, and it was killed before the task could fail... (i.e. the number number of controllers post the test is 0)
This task is not transferred to new controller instance(created by the subsequent test ) and this new controller instance, in its own attempts to create stream keeps failing with lock failed as another controller is holding on the lock..

The reason lock is not transferring is because of a cyclic dependency -- 
1. controllerClusterListener waits on transactionMetadataTasks to become ready. 
2. transactionMetadataTasks waits on internal streams to be created. 
3. internal stream creation is stuck because task sweeper has not run and transferred locks from a failed controller
4. task sweeper starts sweeping after controllerClusterListener is ready

Logs: System test Run 433

``` 
2017-07-06 10:15:21,821 42879 [controllerpool-44] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating event processor stream _requeststream
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource _system/_requeststream.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
```

**Problem location**
Controller startup...

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
Lock is not getting transferred from a dead controller instance to the active controller instance. This is observed when multiControllerSystem test is the first test to run.

When multiController test was run there were no segment stores. Consequently, the internal creation of a stream did not completed, and it was killed before the task could fail, i.e., the number of controllers post the test is 0).

This task is not transferred to a new controller instance, but in the subsequent test, its new controller instance, in its own attempts to create stream keeps failing because another controller is holding the lock. 

The reason lock is not transferring is because of a cyclic dependency --

1. controllerClusterListener waits on transactionMetadataTasks to become ready.
2. transactionMetadataTasks waits on internal streams to be created.
3. internal stream creation is stuck because task sweeper has not run and transferred locks from a failed controller
4. task sweeper starts sweeping after controllerClusterListener is ready because it is called from controllerClusterListener after transactionMetadataTasks is ready.

**Purpose of the change**
Fixes the cyclic dependency. Fixes #1542 

**What the code does**
It starts controller cluster listener without waiting on different sweepers to get started. 
Sweepers each have two methods (define interface, see issue #1560) - 

1. initial sweep to find stray work items across hosts.  
2. handle host failure notification and sweep the hosts tasks. 

If the sweeper component has not started, then (1) waits and is blocked. 

If other cluster change notification are received (like host removed) before component had become ready, they are queued up. Otherwise they are processed immediately. 

Whenever component becomes ready, we complete (1). After this we drain and seal the queue atomically and complete all pending work of type (2) which we drained from the queue. 

Any subsequent cluster change notification is not queued up and processed immediately. 

**How to verify it**
Added unit test

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 1]
```diff
@@ -157,4 +208,28 @@ protected void shutDown() throws Exception {
...
     }
+
+    @VisibleForTesting
+    static class PendingSweepQueue {
+        private final ConcurrentLinkedQueue<Supplier<CompletableFuture<Void>>> workQueue = new ConcurrentLinkedQueue<>();
+        private final AtomicBoolean isSealed = new AtomicBoolean(false);
+
+        @Synchronized
+        @VisibleForTesting
+        boolean enqueue(Supplier<CompletableFuture<Void>> futureSupplier) {
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: I am wondering whether this pending queue is really necessary, because we need not store host lost events before eventProcessors or txnSweeper are ready. Once they get ready they would evaluate the set of failed hosts and sweep their event readers and txns, respectively.

If we sweep tasks for failed hosts before waiting for eventProcessors and txnSweepers to get ready, then that would be a simple fix for this issue, without the need for additional queue.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 2]
```diff
@@ -74,18 +88,6 @@ protected void startUp() throws InterruptedException, Exception {
             log.info("Registering host {} with controller cluster", host);
             cluster.registerHost(host);
 
-            if (eventProcessorsOpt.isPresent()) {
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: Moving line 129 `taskSweeper.sweepOrphanedTasks(processes); ` before this block that waits for eventProcessors and txnSweeper to get ready would be a simple fix the issue, isn't it?

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 1 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: there is a race between while sweep is happening and if any events come. 
they may become lost if we follow as you suggest

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 2 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: what we are doing here is to make sure that we always start clusterlisterner without depending on other components. 
I am thinking in future i will generalize all sweepers using an interface so that its all streamlined, 

Currently all three sweepers each implement similar methods but are doing things differently. 
Using a queue streamlines that.. and ensures that such issues are not encountered in future because future changes to this class will implicitly take care of ensuring that sweepers wait on independent components.. respective sweepers schedule sweeps as and when they become ready.. thus little risk of any similar mistakes in future.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 3]
```diff
@@ -157,4 +208,28 @@ protected void shutDown() throws Exception {
             LoggerHelpers.traceLeave(log, objectId, "shutDown", traceId);
         }
     }
+
+    @VisibleForTesting
+    static class PendingSweepQueue {
+        private final ConcurrentLinkedQueue<Supplier<CompletableFuture<Void>>> workQueue = new ConcurrentLinkedQueue<>();
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: This class has double-concurrency checks which are not needed. Suggestions for improvement:
1. make `workQueue` a simple `ArrayDeque`
2. make `isSealed` a regular `boolean`.
3. in `drainAndSeal`: change return type to `Collection<...>` and do not make a `List` anymore. All of your callsites work with `Collection`, which is implemented by `ArrayDeque`.

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: done

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 4]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+            log.info("Controller cluster listener startUp complete");
+        } finally {
+            LoggerHelpers.traceLeave(log, objectId, "startUp", traceId);
+        }
+    }
+
+    private void handleHostRemoved(Host host) {
+        taskSweeper.sweepOrphanedTasks(host.getHostId());
+
+        eventProcessorsOpt.ifPresent(controllerEventProcessors -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: Why is this optional? Do we ever run in production without this set? If not and it's for testing we should switch to using mocks so that is not affecting our flow.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 5]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+                return controllerEventProcessors.notifyProcessFailure(host.getHostId());
+            }, e -> log.warn(e.getMessage()), executor);
+
+            // if queue is not sealed, then add to queue. Else process asynchronously
+            if (!eventProcPendingQueue.enqueue(futureSupplier)) {
+                futureSupplier.get();
+            }
+        });
+
+        txnSweeperOpt.ifPresent(txnSweeper -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: See above.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 6]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+        } finally {
+            LoggerHelpers.traceLeave(log, objectId, "startUp", traceId);
+        }
+    }
+
+    private void handleHostRemoved(Host host) {
+        taskSweeper.sweepOrphanedTasks(host.getHostId());
+
+        eventProcessorsOpt.ifPresent(controllerEventProcessors -> {
+            Supplier<CompletableFuture<Void>> futureSupplier = () -> RetryHelper.withIndefiniteRetriesAsync(() -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: Why does this need to be retried forever?

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 7]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+                futureSupplier.get();
+            }
+        });
+    }
 
-            if (eventProcessorsOpt.isPresent()) {
+    private void sweepEventProcessorReaders(Supplier<Set<String>> processes) {
+        eventProcessorsOpt.ifPresent(eventProcessors -> {
+            // Await initialization of eventProcesorsOpt
+            RetryHelper.withIndefiniteRetriesAsync(() -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: See above.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 8]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+            // if queue is not sealed, then add to queue. Else process asynchronously
+            if (!txnPendingQueue.enqueue(futureSupplier)) {
+                futureSupplier.get();
+            }
+        });
+    }
 
-            if (eventProcessorsOpt.isPresent()) {
+    private void sweepEventProcessorReaders(Supplier<Set<String>> processes) {
+        eventProcessorsOpt.ifPresent(eventProcessors -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: See above.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 9]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+            }, e -> log.warn(e.getMessage()), executor).thenCompose((Void v) ->
+                    // drain pending queue and process
+                    FutureHelpers.allOf(eventProcPendingQueue.drainAndSeal()
+                            .stream().map(Supplier::get).collect(Collectors.toList())));
+        });
+    }
 
-            if (txnSweeperOpt.isPresent()) {
+    private void sweepTransactions(Supplier<Set<String>> processes) {
+        txnSweeperOpt.ifPresent(txnSweeper -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: See above.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 10]
```diff
@@ -126,24 +120,79 @@ protected void startUp() throws InterruptedException, Exception {
...
+            // Await initialization of transactionTasksOpt.
+            RetryHelper.withIndefiniteRetriesAsync(() -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: See above.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 6 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: This needs to be retried forever because if we fail in sweeping then we lose the opportunity to pick the left over work from another controller instance. 
So we need to make sure that transfer of ownership of the work happens conclusively

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 5 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: i agree.. issue created.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 8 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: agree and issue created.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 7 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: replied above

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 9 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: replied above

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 10 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: replied above

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 4 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: This was optional from before, and i agree with you that in production we will always have event processors system initialized so this is probably only for testing. Will remove optional as part of a separate issue though.. created issue

**Comment by shiveshr** [comment]
@tkaitchuck 
> Does this change actually resolve the circular nature of the interaction between these classes? I feel this just short cuts a step in the initialization to work around it.

Yes..  It ensures that we do not block on all sweepers to be ready in order to sweep a particular type of workload.
Which means from now on sweeper A will only wait on component A to be ready to start the sweep. 
Earlier sweeper A was waiting on all components to become ready which was causing the cyclic dependency.
More concretely --> task sweeper no longer waits for event processors or txn sweepers to be able to sweep. so tasks are failedover and swepts and as internal stream creation completes, stream metadata tasks and event processors are successfully set up.. and their sweepers can then sweep.   

@bhargav-gulavani 

> I think, we could fix the issue without resorting to a separate queue and surrounding logic.
There were two issues with the original code -- the cyclic dependency and potential notification loss while sweep happened. 
With queues we ensure that NO notification is lost while we are sweeping the first time. 
[in the existing code we were registering listeners after completing the sweep. Which means any notification between sweep and registration of listener can be lost. in new code we register listeners then start the sweep and queue any notification that is received while we sweep.]

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 2 above)
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: It is a good idea to have Sweeper interface, that has methods like `isReady`, `awaitReady`, `sweep(failedHost)`, `sweep(activeProcessSupplier)`, etc., so that ClusterListener can be initialized with the list of sweepers. 

We could then simplify the `startUp` method of `ClusterListener` as follows.
```
startup {

    cluster.addListener( HOST_REMOVED -> {
            sweepers.stream().parallel().map(sweeper -> {
                if (sweeper.isReady()) {sweeper.sweep(host.getHostId);}
            });
        }
    );

    sweepers.stream().parallel().map(sweeper -> {
        sweeper.awaitReady();
        sweeper.sweep(activeProcessesSupplier);
    });
}
```

Note that, there is no hostLost event lost with this way of organizing listener and initial sweeps.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 11]
```diff
@@ -126,24 +117,75 @@ protected void startUp() throws InterruptedException, Exception {
...
+        });
+    }
 
-            log.info("Controller cluster listener startUp complete");
-        } finally {
-            LoggerHelpers.traceLeave(log, objectId, "startUp", traceId);
-        }
+    private void sweepTasks(Supplier<Set<String>> processes) {
+        log.info("Sweeping orphaned tasks at startup");
+        RetryHelper.withIndefiniteRetriesAsync(() -> taskSweeper.sweepOrphanedTasks(processes),
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: `taskSweeper.sweepOrphanedTasks` internally retries indefinitely, isn't it? In that case an indefinite retry here may be redundant. Similarly, indefinite retries around `eventProcessorSweeper.sweep` and `txnSweeper.sweep` may be unnecessary.

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: not all code paths inside sweepers are covered with retries and exceptions can still be thrown. 
We dont want to be in a situation that because of any error we are not sweeping failed hosts. 
Will remove redundant retry blocks inside sweepers in a separate issue. created issue 1569

File: controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java [hunk 12]
```diff
@@ -58,10 +60,16 @@ public TxnSweeper(final StreamMetadataStore streamMetadataStore,
         this.transactionMetadataTasks = transactionMetadataTasks;
         this.maxTxnTimeoutMillis = maxTxnTimeoutMillis;
         this.executor = executor;
+        this.ready = new AtomicBoolean(false);
+    }
+
+    public boolean isRunning() {
+        return ready.get();
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java]: Could we rename this methods to `isReady()` as is the case with other sweepers, because `isRunning` is typically defined on a service but our sweepers have utility sweep methods that are invoked from the ClusterListener service.
Moreover, instead of adding a new `ready` variable, we could reuse the one in transactionMetadataTasks and define this method as `transactionMetadataTasks.isReady()`, similar to how we have defined `awaitInitialization` method as `transactionMetadataTasks.awaitInitialization`.

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java]: done
