### PR TITLE
Issue 2828: Limit outstanding checkpoint request to ReaderGroup

### LINKED ISSUE #2828: Limit outstanding checkpoint request to ReaderGroup
**Problem description**
Flink connector (Master Hook) triggers checkpoint request to `ReaderGroup` prior to running its own checkpoint mechanism. There is a likely chance that Pravega `ReaderGroup` may not be able to finish the checkpoint and the original request from Flink connector times out. Flink connector would issue another checkpoint request to `ReaderGroup` during the next revision cycle and it continues.

The situation above could end in having more checkpoint request triggered to `ReaderGroup` (see https://github.com/pravega/flink-connectors/issues/102 for more details).

The proposal is to enforce a limit on the number of ongoing checkpoint request through ReaderGroup configuration settings. Upon reaching a limit, the ReaderGroup will throw an exception should there be any new request?      

**Problem location**
`Client - ReaderGroup` implementation

**Suggestions for an improvement**
Provide an API to check if the threshold has been reached before triggering a checkpoint

### PR DESCRIPTION
**Pull request by vijikarthi**
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>

**Change log description**  
 - added configurable option to `readergroup` to limit outstanding checkpoint request

**Purpose of the change**  
Fixes #2828

**What the code does**  
Upon initiating checkpoint request, it validates if the current outstanding checkpoint request has reached the maximum allowed limit and throws an exception.

**How to verify it**  
Added test case to validate the configurable limits

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 1]
```diff
@@ -108,6 +108,17 @@ public void readerOffline(String readerId, Position lastPosition) {
 
     @Override
     public CompletableFuture<Checkpoint> initiateCheckpoint(String checkpointName, ScheduledExecutorService backgroundExecutor) {
+
+        synchronizer.fetchUpdates();
+        int maxOutstandingCheckpointRequest = this.synchronizer.getState().getConfig().getMaxOutstandingCheckpointRequest();
+        int currentOutstandingCheckpointRequest = synchronizer.getState().getCheckpointState().getUnCheckpointedHostsSize();
```
Comment (EronWright) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: The most clear way to count the number of outstanding checkpoints is to count the `checkpoints` list, not the `uncheckpointedHosts` map.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 2]
```diff
@@ -108,6 +108,17 @@ public void readerOffline(String readerId, Position lastPosition) {
...
+        if (currentOutstandingCheckpointRequest == maxOutstandingCheckpointRequest) {
```
Comment (EronWright) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Please use `if (currentOutstandingCheckpointRequest >= maxOutstandingCheckpointRequest)` because it more clearly expresses the intent and is more robust if the RG is reconfigured (which I believe is possible, not 100% sure).

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 3]
```diff
@@ -108,6 +108,17 @@ public void readerOffline(String readerId, Position lastPosition) {
 
     @Override
     public CompletableFuture<Checkpoint> initiateCheckpoint(String checkpointName, ScheduledExecutorService backgroundExecutor) {
+
+        synchronizer.fetchUpdates();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: This is not the correct way to use the synchronizer. You should apply a conditional update to add the checkpoint and abort if there are too many. Using it in this way doesn't guarantee anything. Instead this should be a modification to the call on line 122.

Comment (vijikarthi) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Will `fetchUpdates()` not guarantee to reflect the latest snapshot of the distributed state? Why do we need to add the checkpoint and fail later?

File: client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java [hunk 4]
```diff
@@ -258,6 +275,7 @@ private void read00(RevisionDataInput revisionDataInput, ReaderGroupConfigBuilde
             ElementDeserializer<StreamCut> valueDeserializer = in -> StreamCut.fromBytes(ByteBuffer.wrap(in.readArray()));
             builder.startFromStreamCuts(revisionDataInput.readMap(keyDeserializer, valueDeserializer));
             builder.endingStreamCuts(revisionDataInput.readMap(keyDeserializer, valueDeserializer));
+            builder.maxOutstandingCheckpointRequest(revisionDataInput.readInt());
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java]: This requires a new revision to the metadata as we are adding a field.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 5]
```diff
@@ -108,7 +108,30 @@ public void readerOffline(String readerId, Position lastPosition) {
 
     @Override
     public CompletableFuture<Checkpoint> initiateCheckpoint(String checkpointName, ScheduledExecutorService backgroundExecutor) {
-        synchronizer.updateStateUnconditionally(new CreateCheckpoint(checkpointName));
+
+        String rejectMessage = "rejecting checkpoint request since pending checkpoint reaches max allowed limit";
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Could we unit test the execution of this method by say mocking the state synchronizer? I'd like to have some nit testing in addition to the integration test that is already added below.

File: client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java [hunk 6]
```diff
@@ -173,6 +176,16 @@ public ReaderGroupConfigBuilder startFromCheckpoint(final Checkpoint checkpoint)
            return this;
        }
 
+       /**
+        * Ensure not more than maximum outstanding checkpoint requests are allowed at any given time.
+        * @param maxOutstandingCheckpointRequest Max allowed outstanding checkpoint request.
+        * @return Reader group config builder.
+        */
+       public ReaderGroupConfigBuilder maxPendingCheckpoints(final int maxOutstandingCheckpointRequest) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java]: This method is not actually needed. If you delete it it will be auto generated.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 7]
```diff
@@ -108,7 +108,30 @@ public void readerOffline(String readerId, Position lastPosition) {
...
+
+        boolean canPerformCheckpoint = synchronizer.updateState((state, updates) -> {
+            ReaderGroupConfig config = state.getConfig();
+            CheckpointState checkpointState = state.getCheckpointState();
+            int maxOutstandingCheckpointRequest = config.getMaxOutstandingCheckpointRequest();
+            int currentOutstandingCheckpointRequest = checkpointState.getOutstandingCheckpoints();
+            if (currentOutstandingCheckpointRequest >= maxOutstandingCheckpointRequest) {
+                String errorMessage = rejectMessage + maxOutstandingCheckpointRequest;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Rather than doing string concat here, you can pass it to the templated warn method below which will do it all at once.

File: client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java (hunk 6 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java]: Yes... The lombok annotation @Builder will auto generate all the simple setter methods. You only need to specify the ones that override normal behavior.

Comment (vijikarthi) [reply client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java]: (done)

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 8]
```diff
@@ -108,7 +108,29 @@ public void readerOffline(String readerId, Position lastPosition) {
...
+
+        String rejectMessage = "rejecting checkpoint request since pending checkpoint reaches max allowed limit";
+
+        boolean canPerformCheckpoint = synchronizer.updateState((state, updates) -> {
+            ReaderGroupConfig config = state.getConfig();
+            CheckpointState checkpointState = state.getCheckpointState();
+            int maxOutstandingCheckpointRequest = config.getMaxOutstandingCheckpointRequest();
+            int currentOutstandingCheckpointRequest = checkpointState.getOutstandingCheckpoints();
+            if (currentOutstandingCheckpointRequest >= maxOutstandingCheckpointRequest) {
+                log.warn("maxOutstandingCheckpointRequest: {}, currentOutstandingCheckpointRequest: {}, errorMessage: {} {}",
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: I can't remember whether we talked about throwing vs. returning false and logging. I'm worried that returning false is somewhat an ambiguous behavior. If a call to initiate checkpoint returns false, then the application is not sure whether this is a permanent or transient behavior. For example, there could some error condition such as a data corruption that prevents a new checkpoint from starting a checkpoint. I also need to check whether  a call to create checkpoint can throw, in which case we are already throwing exceptions when something doesn't work.

I feel that throwing an exception like `MaxExceededException` or `MaxNumberOfCheckpointsExceededException`.

Comment (vijikarthi) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: We are logging the error as well as throwing `CheckpointFailedException` when maximum checkpoint request exceeds ( https://github.com/pravega/pravega/blob/d805db8d6621b68d6ed360f1f933e855cd3a2690/client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java#L131). Are you suggesting to throw a different checked exception like `MaxNumberOfCheckpointsExceededException` instead of throwing `CheckpointFailedException`?
