### PR TITLE
Issue 1264: (SegmentStore) Fixed recovery sync to Tier2

### LINKED ISSUE #1264: (SegmentStore) Out of sync metadata with Tier2 reality after recovery in some scenarios.
Discovered as:
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.pravega.service.server.store.StreamSegmentStoreTestBase.checkReads(StreamSegmentStoreTestBase.java:356)
	at io.pravega.service.server.store.StreamSegmentStoreTestBase.testEndToEnd(StreamSegmentStoreTestBase.java:141)
	at io.pravega.service.server.store.StreamSegmentServiceTests.testEndToEndMulti(StreamSegmentServiceTests.java:53)

```

Root cause: 
1. A number of appends get written to Tier1 (up to offset T4)
2. Writer applies data to Tier2 up to offset (T3 < T4)
3. A truncation of data in Tier1 happens at offset T2 < T3
4. Container fails over to a new machine, but no full metadata checkpoint has been done after 3. At this point the last metadata checkpoint thinks that data in Tier2 is up to offset T0 < T1 (T0 recorded at the time of the previous checkpoint)
5. Immediately after recovery, a read request comes in. However, since during recovery we do not check for the latest state in Tier2 (since that would slow things down immensely), if this read requests data in (T0, T1), this data does not exist in Tier1 (hence in the cache) so the ReadIndex will return a "FutureRead" (until the data becomes available again).
6. It is possible that this returned FutureRead will never complete, because there may not be anything to trigger it (new appends, mergers or seals trigger it).

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Bugfix for the following scenario: 
1. A number of appends get written to Tier1 (up to offset T4)
2. Writer applies data to Tier2 up to offset (T3 < T4)
3. A truncation of data in Tier1 happens at offset T2 < T3
4. Container fails over to a new machine, but no full metadata checkpoint has been done after 3. At this point the last metadata checkpoint thinks that data in Tier2 is up to offset T0 < T1 (T0 recorded at the time of the previous checkpoint)
5. Immediately after recovery, a read request comes in. However, since during recovery we do not check for the latest state in Tier2 (since that would slow things down immensely), if this read requests data in (T0, T1), this data does not exist in Tier1 (hence in the cache) so the ReadIndex will return a "FutureRead" (until the data becomes available again).
6. It is possible that this returned FutureRead will never complete, because there may not be anything to trigger it (new appends, mergers or seals trigger it).

_Previous fixes for this bug_:
_Attempt 1_: When the writer starts processing the segment (asynchronously, after recovery), it already checks the state of the segment in Tier2 and updates the metadata accordingly. The attempt was to piggyback on this process and have it trigger those Future Reads. This fixed most of the problems, however there could have been a significant delay, or in case of other difficulties or races, it may never happen.
_Attempt 2_: Undo Attempt #1 and, instead of issuing a FutureRead, issue a StorageRead for any read that is not available in the cache but that has an offset less than the Segment's length. This fixed the perceived delays for Attempt #1, however it introduced races with appends and mergers, which first update the segment length in the metadata, and then populate the index (these are separate components and we cannot have a global sync lock for everything).

This (hopefully final) attempt does the following:
- Reverts Attempt 1 and Attempt 2.
- Introduces a new DurableLog operation called `StorageMetadataCheckpoint`. This is queued right before (and waited on) a truncation.
- This operation will collect the current Storage State (StorageOffset, StorageSealed, Deleted) for each segment and serialize it for later use
    - Upon recovery, when such an operation is encountered, the segments' metadata is updated accordingly.
    - This operation has a much smaller footprint than its sibling MetadataCheckpointOperation as it only deals with a few small fields
    - Those fields are not normally updated by regular operations, rather they're updated asynchronously by the Writer, which is why they cannot be recovered like the other fields.

**Purpose of the change**
Fix a potential hanging bug.
Fixes #1264. 

**What the code does**
See description.

**How to verify it**
New unit tests added.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/service/server/logs/DurableLog.java [hunk 1]
```diff
@@ -234,8 +235,11 @@ public int getId() {
         TimeoutTimer timer = new TimeoutTimer(timeout);
         log.info("{}: Truncate (OperationSequenceNumber = {}, DataFrameAddress = {}).", this.traceObjectId, upToSequenceNumber, truncationFrameAddress);
 
-        return this.durableDataLog
-                .truncate(truncationFrameAddress, timer.getRemaining())
+        // Before we do any real truncation, we need to mini-snapshot the metadata with only those fields that are updated
+        // asynchronously for us (i.e., not via normal Log Operations) such as the Storage State. That ensures that this
+        // info will be readily available upon recovery without delay.
+        return add(new StorageMetadataCheckpointOperation(), timer.getRemaining())
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/service/server/logs/DurableLog.java]: I have a few clarification questions here:
1- We already have `MetadataCheckpointOperation` and now we are adding `StorageMetadataCheckpoint` operation. As I understand it, the former is Tier 1 metadata while the latter is Tier 2 metadata?
2- Could we consolidate `MetadataCheckpointOperation` and `StorageMetadataCheckpoint`?
3- The comment block says: _we need to mini-snapshot the metadata with only those fields that are updated asynchronously for us_. Because it is asynchronous, is it possible that the storage metadata will contain stale data?
4- I don't actually get whether we are guaranteeing that the storage checkpoint is being flushed before the truncation. If we truncate without flushing, then it is possible that a crash will cause us to lose that checkpoint.

Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/service/server/logs/DurableLog.java]: 1. MetadataCheckpoin (MC) vs StorageMetdataCheckpoint (SMC)
    - MC checkpoints **everything**. That includes metadata updated via normal operations (length, sealed, merge status, etc.). It also records the mapping of Segment Id to Segment Names. As such, for 10K active segments, it can get large (1-2MB avg, but for very long segment names it could get up to 10MB). As such, I don't want that queued up every time we do a truncate. MCs are added periodically (every 100-200MB) based on configuration - they essentially define where we can truncate Tier1.
    - SMC is a slimmer version of that, where it only maps segment id, storage length and sealed status (in storage). Even for 10K segments, it will not exceed 170KB (less with compression). That was the main reasoning behind having another type of checkpoint. 
    - A Container recovery can only start from a full MC (which is essentially a summary of all operations up until it); subsequent MCs are ignored (since they're redundant), but every time a SMC is encountered, its contents is applied.
2. I think I managed to answer this question above. Yes, we could (I could just put MCs 
everywhere), but those tend to be big and kinda redundant, so I want something smaller.
3. What I meant by "asynchronously" was "not by the `OperationMetadataUpdater` (OMC). The OMC is the only thing updating the metadata (since it's part of the `OperationProcessor`) and it essentially runs in a single thread (ok, across many threads in a thread pool, but it runs in sequence). Async is the `Writer` updating `StorageLength` and `StorageSealed` as it applies those changes to Tier2. 
4. Check out `DurableLog.truncate`. It queues up a SMC, then after it completes it issues the Tier1 truncation.
