### PR TITLE
Issue 1733: Metrics fixes

### LINKED ISSUE #1733: Metrics Objects are never cleaned up
**Problem description**
`StatsLogger` has methods for adding metrics, however there is no mechanism for unregistering them.  The underlying framework does support de-registration, but we don't use it. 

This is pretty bad, since we leak Metrics objects by creating them and never removing them from memory.

**Problem location**
Metrics.

**Suggestions for an improvement**
Either of the following:
1. Add `remove` to `StatsLogger` which takes a metric interface/object and deregisters it.
2. Make all Metric objects implement `AutoCloseable`, and have those methods auto-remove them when invoked.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Made Metrics objects (Counters, Meters, OpStatsLoggers, Gauges) and their proxies implement `AutoCloseable` so that they may be unregistered when no longer needed.

Fixed a number of bugs in `StatsLoggerProxy`:
- Every time `setLogger` was invoked, all (four) meter lists would double in size.
- Every time `setLogger` was invoked, the existing elements in the meter list (proxies) would point to other proxies that were just created, while the newly created proxies would (correctly) point to Meter instances
- The correct behavior for this class would be: `setLogger` does not affect the size of the collections and each `MeterProxy` wraps around a `Meter` instance (not another `MeterProxy`)

**Purpose of the change**
Fixes #1733. Required for #1734 .

**What the code does**
Better metrics.

**How to verify it**
The existing Metrics unit tests must pass, as well as the newly added ones.
Metrics must still be published (correctly) when running Pravega.

### CODE REVIEW

File: shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    private final AtomicReference<T> instance = new AtomicReference<>();
+    @Getter
+    private final String proxyName;
+    private final Consumer<String> closeCallback;
+
+    /**
+     * Creates a new instance of the MetricProxy class.
+     *
+     * @param instance      The initial Metric Instance.
+     * @param proxyName          The name of the MetricProxy. This may be different from the name of the Metric's instance.
```
Comment (fpj) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java]: Fix the indentation here, please.

File: shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java]: fixed

File: shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java (hunk 1 above)
Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/metrics/MetricProxy.java]: fixed
