### PR TITLE
Issue 2054: (Bugfix) Additional health check is causing the failover tests to timeout/fail.

### LINKED ISSUE #2054: HealthCheck of bookkeeper service on marathon fails
**Problem description**
The health check of bookkeeper service started by system-test-framework on DC/OS 1.10 fails.

**Problem location**
Bookkeeperservice.java

**Suggestions for an improvement**
Add port for bookkeeper service.

### PR DESCRIPTION
**Pull request by shrids**
Signed-off-by: shrids <sandeep.shridhar@emc.com>
**Change log description**
- Ensure pravega docker images run on a mesos containerizer.
- Increase resources provided to test and pravega containers.

**Purpose of the change**
Fixes #2054 

**What the code does**
- Ensure the we use mesos containerizer to obtain better performance on a mesos cluster.
- Ensure the tests pass on the latest marathon 1.5.

**How to verify it**
Tests should pass.

Update: Tested it on the latest cluster with marathon 1.5.0. The framework is behaving as expected.

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java [hunk 1]
```diff
@@ -74,8 +74,7 @@ public boolean isRunning() {
             log.debug("App Details: {}", app);
             //app is not running until the desired instance count is equal to the number of task/docker containers
             // and the state of application is healthy.
-            if ((app.getApp().getTasksRunning().intValue() == app.getApp().getInstances().intValue())
-                    && app.getApp().getTasksRunning().intValue() == app.getApp().getTasksHealthy().intValue()) {
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java]: The description says that we are removing this because it is adding delay and causing the test to fail, but isn't waiting on the task to be healthy the right thing to do? I'm missing some context here and some reasoning on why this is the right thing to do.

File: test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java [hunk 2]
```diff
@@ -45,7 +45,7 @@
 @Slf4j
 public abstract class MarathonBasedService implements Service {
 
-    static final boolean FORCE_IMAGE = true;
+    static final boolean FORCE_IMAGE = false;
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java]: For my own education, could you elaborate on what this change is doing?

File: test/system/src/main/java/io/pravega/test/system/framework/RemoteSequential.java [hunk 3]
```diff
@@ -85,7 +84,7 @@
 
     private CompletableFuture<Void> waitForJobCompletion(final String jobId) {
         return Futures.loop(() -> isTestRunning(jobId),
-                () -> Futures.delayedFuture(Duration.ofSeconds(3), executorService),
+                () -> Futures.delayedFuture(Duration.ofSeconds(10), executorService),
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/RemoteSequential.java]: Could you argue why 10 is a better value than 3?

Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/RemoteSequential.java]: All our tests are in the order of 10s of minutes. The intent of this change is to reduce the log clutter and network io by increasing the duration to 10 seconds.

File: test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java (hunk 2 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java]: This option is not used for mesos container runtime engine. https://mesosphere.github.io/marathon/docs/native-docker.html

File: test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java (hunk 1 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/services/MarathonBasedService.java]: Yes, reverted it back.
