### PR TITLE
Issue 4925: Unit Test fix for TableMetadataTasksTest in Controller

### LINKED ISSUE #4925: Additional Unit Test for KeyValueTables in Controller
**Problem description**
TableMetadataTasksTest needs to have additional tests to cover the timeout scenario in UTs

**Problem location**
controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java

**Suggestions for an improvement**
Implement test - testWorkflowCompletionTimeout()

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
1. Added implementation for test testWorkflowCompletionTimeout() in class "controller/src/test/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasksTest.java"
which tests the usecase where Create and DeleteAPI events timeout and never complete.

2. Changed the handling for event timeout in CreateAPI to throw the timeout exception so it can be retried till DEADLINE_EXCEEDED. This makes Create and Delete APIs consistent with respect to their event timeout behavior.
Changed necessary tests for this change.

**Purpose of the change**  
Fixes #4925

### CODE REVIEW

**Comment by fpj** [comment]
This test case failed:

```
io.pravega.controller.server.v1.InMemoryControllerServiceImplTest > deleteKeyValueTableTests FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
```

it is not one introduced here, but it is related to the KVS work, is it known to be failing?

**Comment by pbelgundi** [comment]
> This test case failed:
> 
> ```
> io.pravega.controller.server.v1.InMemoryControllerServiceImplTest > deleteKeyValueTableTests FAILED
>     org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
> ```
> 
> it is not one introduced here, but it is related to the KVS work, is it known to be failing?

I have fixed it in the next commit.

**Comment by andreipaduroiu** [comment]
@pbelgundi This test is still failing
```
io.pravega.controller.task.KeyValueTable.PravegaTablesKVTMetadataTasksTest > testWorkflowCompletionTimeout FAILED

    java.lang.AssertionError: delete timedout No exception has been thrown.
```

**Comment by fpj** [comment]
... And I don't know whether it is just a coincidence, but according to the assertion message, the delete has timed out. Are they related at all?

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 1]
```diff
@@ -143,15 +143,7 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
                                        return isCreateProcessed(scope, kvtName, kvtConfig, createTimestamp, executor);
                                  });
                             });
-               }, e -> Exceptions.unwrap(e) instanceof RetryableException, NUM_RETRIES, executor)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:146]: why is this changed?

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 2]
```diff
@@ -180,10 +172,18 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
                             DeleteTableEvent deleteEvent = new DeleteTableEvent(scope, kvtName, requestId, UUID.fromString(id));
                             return eventHelper.addIndexAndSubmitTask(deleteEvent,
                                     () -> kvtMetadataStore.setState(scope, kvtName, KVTableState.DELETING, context, executor))
-                                    .thenCompose(x -> eventHelper.checkDone(() -> isDeleted(scope, kvtName, context)))
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:183]: why not pass the operation context? that will avoid fetching the table names etc again from segment store

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 3]
```diff
@@ -180,10 +172,18 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
...
+                                    .thenCompose(x -> eventHelper.checkDone(() -> isDeleted(scope, kvtName)))
                                     .thenApply(y -> DeleteKVTableStatus.Status.SUCCESS);
                         });
-            }), e -> Exceptions.unwrap(e) instanceof RetryableException, NUM_RETRIES, executor);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:186]: do we want to return a failure status from here? the request may have been submitted and still ongoing in the background. right?

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 4]
```diff
@@ -204,7 +204,7 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
                                                 false, delegationToken, requestId), executor));
     }
 
-    private CompletableFuture<Boolean> isDeleted(String scope, String kvtName, KVTOperationContext context) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:207]: why is this being removed?

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 5]
```diff
@@ -220,7 +220,7 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
                                                                                   KeyValueTableConfiguration kvtConfig,
                                                                                   final long createTimestamp,
                                                                                   Executor executor) {
-        return eventHelper.checkDone(() -> isCreated(scope, kvtName, kvtConfig, executor))
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:223]: same here -- comparing the kvt config will determine if the create was actually performed with the supplied config or a different one from a concurrent request that got executed first.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:146]: This is for delete and create to have consistent behavior on timeout.
After this change both throw timeout exception instead of Create returning FAILURE status on timeout.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:183]: When context is not present it fetches from cache.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:186]: If there is no response 2 mins after event was submitted this throws timeout exception.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:223]: Configuration is being checked in isCreateProcessed() method. It is not required in isCreated() method and was anyways passed but not used.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:207]: It was passed but not used.

Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:207]: it was passed but not used

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:146]: As discussed with Shivesh, changed both APIs to throw timeout exception when event timesout.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:186]: Changed this as discussed.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:207]: Fie this for the delete test failure: https://github.com/pravega/pravega/issues/4927
