### PR TITLE
Issue 1553: TxnSweeper should handle txnNotFound

### LINKED ISSUE #1553: TxnSweeper should handle txnNotFound
**Problem description**
A txn in host index may still be present while the actual txn may have completed and hence removed. 
Since txnSweeper simply tries to read txn data, it may get DataNotFoundException. 
It should gracefully handle such exceptions and ignore txn ownership transfer in such cases. 

**Problem location**
TxnSweeper calls getTxnData for all txns found in the host index. 
GetTxnData can throw TxnNotFound which tihs should handle gracefully. 

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
A txn in host index may still be present while the actual txn may have completed and hence removed.
Since txnSweeper simply tries to read txn data, it may get DataNotFoundException.
It should gracefully handle such exceptions and ignore txn ownership transfer in such cases.

**Purpose of the change**
TxnSweeper calls getTxnData for all txns found in the host index.
GetTxnData can throw TxnNotFound which this should handle gracefully.

**What the code does**
It captures DataNotFound exceptions and in such cases cleans up host index (removeTxnFromIndex)

Fixes #1553 

**How to verify it**
all unit tests should pass

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java [hunk 1]
```diff
@@ -133,7 +147,8 @@ public void awaitInitialization() throws InterruptedException {
                     return failOverCommittingTxn(failedHost, epoch, txn)
                             .handleAsync((v, e) -> new Result(txn, v, e), executor);
                 default:
-                    return CompletableFuture.completedFuture(new Result(txn, null, null));
+                    return streamMetadataStore.removeTxnFromIndex(failedHost, txn, true)
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java]: The default case here is pretty much the `UNKNOWN` case, yes?

File: controller/src/main/java/io/pravega/controller/store/stream/VersionedTransactionData.java [hunk 2]
```diff
@@ -20,6 +20,9 @@
 @Data
 @AllArgsConstructor
 public class VersionedTransactionData {
+    public static final VersionedTransactionData NULL = new VersionedTransactionData(Integer.MIN_VALUE, new UUID(0, 0),
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/VersionedTransactionData.java]: `NULL` is really overloaded, can we use something different? a few suggested options: `EMPTY`, `INVALID`, `VAPID`.

File: controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java (hunk 1 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/Stream/TxnSweeper.java]: yes
