### PR TITLE
Issue 5483, 5496, 5544: Flakey tests among controller unit tests

### LINKED ISSUE #5483: Unit test failure: ControllerEventProcessorsTest.testTruncate
**Problem description**
1st stack trace:
```
io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest > testTruncate FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
        at java.base@11.0.9.1/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
        at app//io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:336)
```
2nd stack trace:
```
io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest > testTruncate FAILED
    Argument(s) are different! Wanted:
    checkpointStore.getPositions(
        "p1",
        "abortStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:346)
    Actual invocations have different arguments:
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "scaleGroup"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "kvtStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getProcesses(
    
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:333)
    checkpointStore.getPositions(
        "p1",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p2",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
    checkpointStore.getPositions(
        "p3",
        "commitStreamReaders"
    );
    -> at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.truncate(ControllerEventProcessors.java:334)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessorsTest.testTruncate(ControllerEventProcessorsTest.java:346)
```

**Problem location**
`ControllerEventProcessorsTest.testTruncate`

**Suggestions for an improvement**
Test should pass reliably.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**  
 - Issue 5496: Sporadic failure in SerializedRequestHandlerTest
 - Issue 5544: Sporadic failure in ControllerClusterListenerTest
 - Issue 5483: Sporadic failure in ControllerEventProcessors.testTruncate

**Purpose of the change**  
Fixes #5483, #5496, #5544

**What the code does**  
1. SerializedRequestHandlerTest.testCancellation: make sure that the first event is picked for processing before issuing a shutdown so that we wait for it to complete. 
2. Sporadic failure in ControllerClusterListenerTest: UnfinishedStubbingException comes if we modify the mock while it is being used by some component. If that happens then we could get the aforesaid error. So the fix is to move all the mocking to the initial part of the test and manage any transition via flags. 
3. Sporadic failure in ControllerEventProcessors.testTruncate: The core of the issue seems to be similar to previous one, but it manifests in different ways including mock invocation argument coming as empty being the most common. But we have seen other assertion related errors too. This test code has been modified to move all the mocking to the top. And also have better control mechanism over which calls are being made to reduce any chances of a race. 

**How to verify it**  
All tests should pass consistently.
These fixes have been run locally with success, but that is no guarantee that they fix the stubbing related exception.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java [hunk 1]
```diff
@@ -353,15 +353,18 @@ public boolean isReady() {
                                           if (e != null) {
                                               log.warn("Submission for truncation for stream {} failed. Will be retried in next iteration.",
                                                       streamName);
-                                          } else {
+                                          } else if (r) {
                                               log.debug("truncation for stream {} at streamcut {} submitted.", streamName, streamcut);
+                                          } else {
+                                              log.debug("truncation for stream {} at streamcut {} rejected.", streamName, streamcut);
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java:359]: Can we make it a warn level debug?

File: controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java [hunk 2]
```diff
@@ -269,13 +269,66 @@ public void testTruncate() throws CheckpointStoreException, InterruptedException
...
+                    System.out.println("request called");
+                    throw new RuntimeException("inducing sporadic failure");
+                } else {
+                    System.out.println("request completed");
+                    requestStreamTruncationFuture.complete(null);
+                }
+            } else if (argument.equals(config.getCommitStreamName())) {
+                // let one of the processors throw the exception. this should still be retried in the next cycle.
+                if (commitCalled.get()) {
+                    System.out.println("commit called");
```
Comment (shrids) [inline controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java:294]: remove all system.out statements.

**Review by shrids — CHANGES_REQUESTED** [review]

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java:359]: no, this is harmless.. this rejection simply means the streamcut has not progressed beyond the head.. and it need not be published at warn level

File: controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java (hunk 2 above)
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessorsTest.java:294]: oops :)

**Review by shrids — APPROVED** [review]
LGTM...
