### PR TITLE
Issue 1480: Throw exception if request stream writer is not set

### LINKED ISSUE #1480: PostScale should fail if eventStreamWriter in streamMetadataTasks is not set
**Problem description**
Currently we are ignoring if eventStreamWriter is not set, resulting in manual scale to be stuck. 

**Problem location**
controller

**Suggestions for an improvement**
fix the bug

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
We are ignoring if stream metadata tasks does not have request stream writer initialized. 
Instead we should throw the exception and let the caller handle it if it needs to. 

**Purpose of the change**
Fixes #1480

**What the code does**
Instead of ignoring we will now throw the ScaleRequestNotEnabledException

**How to verify it**
All unit tests should pass

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java [hunk 1]
```diff
@@ -236,7 +236,7 @@ public void initializeStreamWriters(final ClientFactory clientFactory,
             } catch (Exception e) {
                 log.error("error sending request to requeststream {}", e);
                 if (e instanceof ScaleOperationExceptions.ScaleRequestNotEnabledException) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: A clarification: what does scale request not enabled mean in this context?

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Until writer is set, we cant post scale request to request stream. 
Scale is performed by picking the event from the request stream. 
So if streamMetadataTasks does not have a 'writer' for request stream initialized, it cannot post requests.
