### PR TITLE
Issue 1682: Fix race between flush and connection failure

### LINKED ISSUE #1682: Race condition in SegmentOutputStreamImpl
**Problem description**
We have observed in some test cases a behavior in which a writer stops making progress after a fail- over event, and the cause of the problem seems to be the following.

In the test case, we call write followed by flush. In the flush call, we invoke `state.getEmptyInflightFuture()`, which returns the future assigned to `emptyInflightFuture `. The variable `emptyInflightFuture ` is only set/reset in two places:

`getEmptyInflightFuture`
https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java#L116

`addToInflight`
https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java#L215 

In `getEmptyInflightFuture`, we only instantiate a new future in the case `emptyInflightFuture` is null, whereas in `addToInflight`, we make it null in the case it is not null and done. 

Say that we try a few times to reconnect following the flush logic and that eventually it succeeds. Succeeding in connecting does not reset `emptyInflightFuture` and the flush logic keeps retrying because it keeps hitting a future that completed asynchronously. In our test case, there is a single thread performing the write/flush calls, and as such, there is no call to `addToInflight`, which causes the thread to be stuck.

**Problem location**
Client.

**Suggestions for an improvement**
Fix the nasty bug.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
Fixes a race in SegmentOutputStreamImpl where if the connection failed after flush was called but reconnected before the future was used flush could get stuck retrying the connection even though it is connected and there are no events inflight.

**Purpose of the change**
Fix #1682. This should allow the system tests to pass.

**What the code does**
Changes the CompletableFuture on empty inflight back to a reusable latch and does the reconnecting in the background thread pool. This simplifies the handling, and eliminates the possibility that there could be an exception left set on the future, as the latch is single purpose: tacking if their is anything inflight rather and trying to do two jobs as the future was.

**How to verify it**
Added a new test that reproduces the error observed in the system tests. Enhanced other tests to have more assertions. All pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -293,17 +275,14 @@ public void wrongHost(WrongHost wrongHost) {
...
-                    if (ex != null) {
-                        log.error("Unexpected Error while execution SealedSegment CallBack", ex);
-                        state.sealEncountered.set(false);
-                        state.failConnection(new CompletionException(getRealException(ex)));
-                    }
-                });
+                Retry.indefinitelyWithExpBackoff(retrySchedule.getInitialMillis(), retrySchedule.getMultiplier(),
+                                                 retrySchedule.getMaxDelay(),
+                                                 t -> log.error(writerId + " to invoke sealed callback: ", t))
+                     .runAsync(() -> {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: It should be runInExecutor()

Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Done
