### PR TITLE
Issue 2564: Fix the issue with using cleanUp for controller client in multicontroller system test

### LINKED ISSUE #2564: Fix controller client close issue while creating scope in multiController system test
**Problem description**
The changes in PR #2542 introduced unintentional closing of controller client, before the `createScope` future returns. This results in 
```
Caused by: java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: 
```

**Problem location**
https://github.com/pravega/pravega/blob/master/test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java#L179

**Suggestions for an improvement**
Close the controller client only after ensuring that scope is created successfully.

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
Signed-off-by: PrabhaVeerubhotla <vvlprabha@gmail.com>

**Change log description**
As a part of the changes of the PR #2542 ,
`@cleanup` was introduced for controller client unintentionally. 
This is a problem because the createScope method returns a completable future, and we are closing the client before the future returns.

**Purpose of the change**
Fixes #2564 

**What the code does**
*  Changes the return value of `createScope()`  and `createScopeWithSimpleRetry()` from `CompletableFuture<Boolean>` to `boolean`.
*  Creates `controllerclient` seperately for both `createScope()` and `createScopeWithSimpleRetry()`
as there is some issue in passing around the `controllerclient` from former to later.
* Using `@cleanup` in both the places to ensure client is closed after the scope creation is successful.

**How to verify it**
System tests should pass

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 1]
```diff
@@ -144,11 +142,13 @@ public void multiControllerTest() throws ExecutionException, InterruptedExceptio
         AssertExtensions.assertThrows("Should throw RetriesExhaustedException",
                 createScope("scope" + RandomStringUtils.randomAlphanumeric(10), controllerURIDirect.get()),
                 throwable -> throwable instanceof RetriesExhaustedException);
+        controllerClient.close();
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Instead of doing this, could you create the controller client instance in the setup method and use the `@Cleanup` annotation? Alternatively, you could create the controller client instance in this method and pass it to `createScope` (which is a private method).

Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: As per the comment here: https://github.com/pravega/pravega/pull/2542#discussion_r186336592
I need to create new `controller client` instance every time I create a scope.  Also, I have tried the ways you have mentioned above, but it is trying to access any available controller URI in the case of `pravega://` and scope gets created, in case of 0 controller instances.

Comment (fpj) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: This is problematic as we have to remember to close the controller client every time. In the future, this makes maintenance of the code more difficult. Not to say that there is the risk that `controllerClient` is null and we end up with NPE.

I think you can refactor `createScope` to make it work.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 2]
```diff
@@ -176,8 +178,7 @@ private void withControllerURIDiscover() throws ExecutionException, InterruptedE
     }
 
     private CompletableFuture<Boolean> createScope(String scopeName, URI controllerURI) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Here is how I think you should refactor this method:

```
private Boolean createScope(String scopeName, URI controllerURI) {
      @Cleanup
       final ControllerImpl controllerClient = new ControllerImpl(ControllerImplConfig.builder()
                 .clientConfig(ClientConfig.builder()
                 .controllerURI(controllerURI)
                 .build())
                 .build(), EXECUTOR_SERVICE);
         return controllerClient.createScope(scopeName).get();
}

```

Of course, you'd need to remove the `get()` calls in the test code, but the functionality does not change as far as I can tell. And, given that this is a private method, there is no concern around methods outside this class.

Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: I have updated the PR, please check if this works.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 3]
```diff
@@ -156,32 +156,41 @@ public void multiControllerTest() throws ExecutionException, InterruptedExceptio
...
         }
 
     }
 
-    CompletableFuture<Boolean> createScopeWithSimpleRetry(String scopeName, URI controllerURI) {
+    private boolean createScopeWithSimpleRetry(String scopeName, URI controllerURI) throws ExecutionException, InterruptedException {
         // Need to retry since there is a delay for the mesos DNS name to resolve correctly.
-        return Retry.withExpBackoff(500, 2, 10, 5000)
+        @Cleanup
+        final ControllerImpl controllerClient = new ControllerImpl(ControllerImplConfig.builder()
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: This client creation seems redundant, this method can invoke createScope() directly.
runInExecutor could be used instead of `runAsync()`

Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: @Prabha-Veerubhotla please ignore my previous comment in case you have intentionally created two clients as part of the test.
