### PR TITLE
Issue 3989: Fix license headers

### LINKED ISSUE #3989: Some classes have old License Header. Clean up and use new license headers in them.
**Problem description**
Some classes continue to have an old license header. We should clean up and use a common license header across all classes. 

**Problem location**
Pravega

**Suggestions for an improvement**
Use consistent license header across classes.

### PR DESCRIPTION
**Pull request by fpj**
Signed-off-by: Flavio Junqueira (fpj) <fpj@apache.org>

**Change log description**  
* Fixes license headers that accidentally included the last paragraph of the ALv2, which was excluded by our legal.

**Purpose of the change**  
Fixes #3989 

**What the code does**  
There is no code change, only changes to license headers.

**How to verify it**  
It should build correctly as usual.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/index/HostIndex.java [hunk 1]
```diff
@@ -1,17 +1,11 @@
 /**
- * Copyright (c) 2017 Dell Inc., or its subsidiaries.
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/store/index/HostIndex.java]: Why in some files are we still keeping the year and in others we are removing it?
