### PR TITLE
Issue 3904: Fix PravegaTableStreamMetadataStore's garbage collection for old batch gc

### LINKED ISSUE #3904: Controller's PravegaTableStreamMetadataStore implementation completed txn garbage collection does not retain latest two batches
**Problem description**
PravegaTableStreamMetadataStore's garbage collection logic has a bug where instead of retaining latest two, it retains two latest in the key set order as returned by pravega tables.getAllKeys. 
This can prematurely purge transaction's completed record whereby applications trying to retrieve its status may get Unknown transaction. 

Note: ZkStreamMetadataStore implementation sorted the list of batches.

**Problem location**
PravegaTableStreamMetadataStore.java

**Suggestions for an improvement**
Retain the latest two batches.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
PravegaTableStreamMetadataStore's garbage collection had a bug where batches were not sorted by batch number and this resulted in any 2 batches being retained while everything else gc'd.

**Purpose of the change**  
Fixes #3904 

**What the code does**  
Sorts the list of batches as received from the store and then retains the latest two while purging all older batches. 

1. Fixed the issue in PravegaTableStreamMetadataStore by sorting the list of batches as received from getAllKeys on Batches table. 
2. Added a `VisibleForTesting` setter in PravegaTableStreamMetadataStore to set garbageCollector to mock new batches at the time of transaction commits. 
3. Added a new `VisibleForTesting` package level method in PravegaTableStream to get batch table name. 

**How to verify it**  
Unit test added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java [hunk 1]
```diff
@@ -73,19 +76,25 @@
...
                                                          .collectRemaining(batches::add)
                                                          .thenApply(v -> {
                                                                      // retain latest two and delete remainder.
                                                                      if (batches.size() > 2) {
-                                                                         return batches.subList(0, batches.size() - 2);
+                                                                         List<String> list = batches
+                                                                                 .stream().sorted(Comparator.comparingLong(Long::parseLong))
+                                                                                 .collect(Collectors.toList());
+
+                                                                         return list.subList(0, batches.size() - 2);
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: Why we only keep the 2 last batches? Is this an optimal value or it is just a value that sounds reasonable? In the latter case, we may want to replace that by a constant, so it can be easily modified if necessary.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: We keep the last two values because the latest batch is what is still being written to. 
And during the time when we transition from previous batch to new batch, callers may still be interested in transactions written to previous batch as the transactions written into it should be made available for at least the GC period. 
Everything before the latest two are guaranteed to be before the GC period so we can purge them.

Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: What's the expected behavior in the case that `batches.size() < 2`? This is going to throw `IndexOutOfBounds`, no?

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: This is the code path if batch.size > 2

File: controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java [hunk 2]
```diff
@@ -196,6 +209,176 @@ public void testSplitsMerges() throws Exception {
...
+    }
+
+    private Set<Integer> getAllBatches(PravegaTablesStreamMetadataStore testStore) {
+        Set<Integer> batches = new ConcurrentSkipListSet<>();
+        testStore.getStoreHelper().getAllKeys(COMPLETED_TRANSACTIONS_BATCHES_TABLE)
+                 .collectRemaining(x -> {
+                     batches.add(Integer.parseInt(x));
+                     return true;
+                 }).join();
+        System.err.println("shivesh:: batches = " + batches);
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStoreTest.java]: oops

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java [hunk 3]
```diff
@@ -73,19 +76,25 @@
...
+    CompletableFuture<Void> gcCompletedTxn() {
         List<String> batches = new ArrayList<>();
         return withCompletion(storeHelper.expectingDataNotFound(storeHelper.getAllKeys(COMPLETED_TRANSACTIONS_BATCHES_TABLE)
                                                          .collectRemaining(batches::add)
                                                          .thenApply(v -> {
                                                                      // retain latest two and delete remainder.
                                                                      if (batches.size() > 2) {
-                                                                         return batches.subList(0, batches.size() - 2);
+                                                                         List<String> list = batches
+                                                                                 .stream().sorted(Comparator.comparingLong(Long::parseLong))
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: This is a very inefficient sort. On every comparison you invoke `Long.parseInt`. Please convert the list to Long and then sort it.

Comment (andreipaduroiu) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: And since you only need the top 2, there may be more efficient methods that can do this in one pass, without sorting.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java]: Actually the list was going to be very small - typically 3 elements and this code was exercised once every day. so it would not have mattered so much. 
But i have changed it to use a one pass algorithm to exclude two largest numbers in the list.
