### PR TITLE
Issue 7414: Integration test for io.pravega.test.integration.AppendTest is failing consistently.

### LINKED ISSUE #7414: Integration test for io.pravega.test.integration.AppendTest if failing consistently.
**Describe the bug**
Integration test for io.pravega.test.integration.AppendTest if failing consistently for feature-flip-27 branch.

**To Reproduce**
Run integration test on GA.

**Screenshots**
N/A
**Additional information**
N/A

### PR DESCRIPTION
**Pull request by Bhupender-Y**
**Change log description**  
Integration test for io.pravega.test.integration.AppendTest if failing consistently. 

**Purpose of the change**  
(Fixes #7414 )

**What the code does**  
Earlier we were creating the channel for every testcase but store was common and it was happening that embedded channel was unable to reply for request and getting illegalstate exception. Now we have created a common channel and index append processor in setUp section. Also earlier we were not closing the IndexAppendProcessor. Now we are cleaning up IndexAppendProcessor as well.

**How to verify it**  
All integration test should pass.

### CODE REVIEW

File: test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java [hunk 1]
```diff
@@ -65,185 +54,142 @@
...
-
-    protected String controllerUri() {
-        return "tcp://localhost:" + controllerPort;
-    }
-
-    //endregion
+    @ClassRule
+    public static final PravegaResource PRAVEGA = new PravegaResource();
+    private static final String DATA_OF_SIZE_30 = "data of size 30"; // data length = 22 bytes , header = 8 bytes
+    private final JavaSerializer<String> serializer = new JavaSerializer<>();
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java:62]: UTF8Serializer

**Review by tkaitchuck — APPROVED** [review]

File: test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java (hunk 1 above)
Comment (Bhupender-Y) [reply test/integration/src/test/java/io/pravega/test/integration/SegmentReaderTest.java]: Done.

**Review by ShwethaSNayak — APPROVED** [review]
Changes LGTM. It will be good if you can elaborate a bit on actual issue and the fix in **what the code does section**
