### PR TITLE
Issue 1672,1683 : Fix for issues in Failover system tests.

### LINKED ISSUE #1672: Handle partially committed transactions in multireadertxnwriterfailovertest
**Problem description**
There are some transactions which are in `COMMITTING` state during the time of failover.
 The current retry logic used in checkTransactionStatus needs to be modified.
**Problem location**
System tests - multireadertxnwriterfailovertest

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
The following issues in Failover tests are fixed here
* MultiReaderTxnWriterFailoverTest - #1672  Modify the retry logic `checkTxnStatus()`, to ensure we handle txns in which are still in `COMMITING` state
* Ensure there is a 1 min delay between test runs.
* Ensure `Exceptions.handleInterrupted(() -> Thread.sleep(..)` is used.
* Remove ConnectionClosedException from the catch block of the writer.
* Increase the writer retry attempt count.
* Ensure exceptions during `close()` method do not cause failure in tests.
* Ensure auto scaling is disabled while testing manual scale in ReadWriteAndScaleWithFailoverTest.java

**Purpose of the change**
Fix test issues in failover system tests.

**What the code does**
Fixes #1672 #1683 

**How to verify it**
Run system test

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 1]
```diff
@@ -193,14 +188,19 @@ void performFailoverTest() throws InterruptedException {
                     } else {
                         log.debug("Read timeout");
                     }
-                } catch (ConnectionClosedException e) {
+                } catch (RetriesExhaustedException e) {
                     log.warn("Test exception in reading events: ", e);
                     continue;
-                } catch (ReinitializationRequiredException e) {
+                } catch (Throwable e) {
+                    if (e.getCause() instanceof RetriesExhaustedException) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: I don't understand why this is needed given that we are already catching `RetriesExhaustedException` above.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 2]
```diff
@@ -305,6 +305,7 @@ void stopReadersAndWriters(ReaderGroupManager readerGroupManager, String readerG
         testState.writersComplete.get();
         testState.newWritersComplete.get();
         if (testState.getWriteException.get() != null) {
+            log.info("Unable to write events: {}", testState.getWriteException.get());
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: I think the braces aren't needed here.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 3]
```diff
@@ -314,6 +315,7 @@ void stopReadersAndWriters(ReaderGroupManager readerGroupManager, String readerG
         log.info("Wait for readers execution to complete");
         testState.readersComplete.get();
         if (testState.getReadException.get() != null) {
+            log.info("Unable to read events: {}", testState.getReadException.get());
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Braces aren't needed here.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 4]
```diff
@@ -193,18 +199,34 @@ void performFailoverTest() throws InterruptedException {
                     } else {
                         log.debug("Read timeout");
                     }
-                } catch (ConnectionClosedException e) {
+                } catch (RetriesExhaustedException e) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: This should fail the test. We don't want this to ever occur.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 5]
```diff
@@ -193,18 +199,34 @@ void performFailoverTest() throws InterruptedException {
...
                     log.warn("Test exception in reading events: ", e);
                     continue;
-                } catch (ReinitializationRequiredException e) {
+                } catch (Throwable e) {
+                    if (e.getCause() instanceof RetriesExhaustedException) {
+                        log.warn("Test exception in reading events: ", e);
+                        continue;
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: continue will not cause the test to error with this exception. This forces us to troll through the logs to find out if anything went wrong. If something goes wrong the test should immediately fail with the exception.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 1 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Observing RetriesExhaustedException wrapped inside a RuntimeException
Created an issue for the same `https://github.com/pravega/pravega/issues/1687`

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 2 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: This is a parameter to log message.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 3 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: This is a parameter to log message.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 4 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Yes, this is never encountered. Removing this catch block completely.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 5 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Observing RetriesExhaustedException wrapped inside a RuntimeException
Created an issue for the same https://github.com/pravega/pravega/issues/1687.

Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: @shrids I think @tkaitchuck is saying something different. He is saying that we should not ignore and proceed. Even though it is harmless in our case to proceed, the retries exhaustion is not really expected in this test case, so we better fail as soon and investigate with fewer log messages to inspect. 

I can go either way, since our main goal here is to make sure we read as much as we write, but I agree that the retries exhaustion is unexpected and undesirable, so if we keep hitting it, we should investigate.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 2 above)
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Check the documentation:

https://www.slf4j.org/api/org/slf4j/Logger.html#info(java.lang.String,%20java.lang.Throwable)

one of the signatures accepts a Throwable, so it will simply print `{}` in this case, as we can see in the logs.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 3 above)
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: See comment above.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 2 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Removed the braces..

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 3 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Corrected it.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 6]
```diff
@@ -72,8 +74,10 @@
     //Duration for which the system test waits for writes/reads to happen post failover.
     //10s (SessionTimeout) + 10s (RebalanceContainers) + 20s (For Container recovery + start) + NetworkDelays
     private static final int WAIT_AFTER_FAILOVER_MILLIS = 40 * 1000;
-    private  List<CompletableFuture<Void>> txnStatusFutureList = new ArrayList<>();
-    private ExecutorService executorService;
+    private final List<EventStreamReader<Long>> readerList = new ArrayList<>();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: These need to be annotated with the lock that guards them. (Or switched for thread safe collections)

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 7]
```diff
@@ -90,10 +94,10 @@
     private final StreamConfiguration config = StreamConfiguration.builder().scope(scope)
             .streamName(STREAM_NAME).scalingPolicy(scalingPolicy).build();
     private final String readerName = "reader";
-    private Retry.RetryWithBackoff retry = Retry.withExpBackoff(10, 10, 20, ofSeconds(1).toMillis());
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: final

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 8]
```diff
@@ -305,7 +303,30 @@ public void multiReaderTxnWriterWithFailOverTest() throws Exception {
...
     }
 
-    private void performFailoverTest() throws InterruptedException {
+    private void closeReadersAndWriters() {
+        log.info("Closing writers");
+        writerList.forEach(writer -> {
+            try {
+                writer.close();
+            } catch (RetriesExhaustedException e) {
+                log.warn("Unable to close the client: ", e);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Here and below: Why are we catching and suppressing these?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 9]
```diff
@@ -310,25 +309,21 @@ private void cleanUp() {
         writerList.forEach(writer -> {
             try {
                 writer.close();
-            } catch (RetriesExhaustedException e) {
-                log.warn("Unable to close the client: ", e);
             } catch (Throwable e) {
-                Assert.fail("Unable to close the client. Test Failure");
+                log.error("Error closing reader", e);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Here and below: Why do we want the test to pass if close throws?

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 10]
```diff
@@ -153,28 +151,34 @@ void performFailoverTest() throws InterruptedException {
...
-            writer.close();
+            closeWriter(writer);
         }, executorService);
     }
 
+    private void closeWriter(EventStreamWriter<Long> writer) {
+        try {
+            log.info("Closing writer");
+            writer.close();
+        } catch (RetriesExhaustedException e) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: As we have seen, this is not going to work because the exception is wrapped. We should probably change the exception handling here.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 11]
```diff
@@ -305,7 +303,30 @@ public void multiReaderTxnWriterWithFailOverTest() throws Exception {
         log.info("Test {} succeeds ", "MultiReaderWriterTxnWithFailOver");
     }
 
-    private void performFailoverTest() throws InterruptedException {
+    private void closeReadersAndWriters() {
+        log.info("Closing writers");
+        writerList.forEach(writer -> {
+            try {
+                writer.close();
+            } catch (RetriesExhaustedException e) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: This catch is dead code giving that we are wrapping retries exhausted.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 8 above)
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: @tkaitchuck here we are closing the readers and writers, which happens at the end of the test. The goal of the test is not to test whether the client is closing correct, so it begs the question of whether we should fall the whole test case here or log and proceed. My sense is that we should be testing whether the client is closing correctly elsewhere, but I'm fine with being strict and failing if it doesn't close correctly.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 9 above)
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: @tkaitchuck see my comment above.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 8 above)
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: I think we should be strict. But I won't block the PR on that. So I'm approving it now so that it can get merged. (I hope with the change, but if both of you disagree, then leave it as is)

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 6 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Done, updated the code to use `Collections.synchronizedList(...)`

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 7 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 8 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Yes, we need to be strict. Created an issue for it. https://github.com/pravega/pravega/issues/1695

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 10 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Removed the catch block for RetriesExhaustedException.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 11 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: yes, removed it.
