### PR TITLE
Issue5900: Modify Handling of Exceptions in Commit and Abort Transactions.

### LINKED ISSUE #5900: io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest.readTxnWriteScaleWithFailoverTest
**Describe the bug**
Found that `io.pravega.test.system.ReadTxnWriteScaleWithFailoverTest.readTxnWriteScaleWithFailoverTest` fails sporadically due to:
```
2021-03-18 04:43:12,821 216321 [controllerpool-9] WARN  i.p.c.server.ControllerService - Transaction commit failed
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: 00000001-0000-0000-0000-000000009c6a table: _system/_tables/testReadTxnWriteScaleScope1162564740/testReadTxnWriteScaleStream/transactionsInEpoch-1.#.b83027b8-2a6d-4d76-b5f0-74b797a6634b
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$withRetries$58(PravegaTablesStoreHelper.java:604)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$runAsync$6(Retry.java:246)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.pravega.controller.store.stream.StoreException$UnknownException: get entry: key: 00000001-0000-0000-0000-000000009c6a table: _system/_tables/testReadTxnWriteScaleScope1162564740/testReadTxnWriteScaleStream/transactionsInEpoch-1.#.b83027b8-2a6d-4d76-b5f0-74b797a6634b
        at io.pravega.controller.store.stream.StoreException.create(StoreException.java:108)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:569)
        ... 12 common frames omitted
Caused by: io.pravega.common.ObjectClosedException: Object 'ConnectionPoolImpl' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.client.connection.impl.ConnectionPoolImpl.getClientConnection(ConnectionPoolImpl.java:101)
        at io.pravega.client.connection.impl.RawClient.<init>(RawClient.java:101)
        at io.pravega.controller.server.SegmentHelper.readTable(SegmentHelper.java:483)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$21(PravegaTablesStoreHelper.java:288)
        at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$54(PravegaTablesStoreHelper.java:527)
        ... 8 common frames omitted
2021-03-18 04:43:12,821 216321 [controllerpool-9] DEBUG i.p.c.s.r.g.v.ControllerServiceImpl - result =  status: FAILURE
{log}
```

**To Reproduce**
Run system tests a few times.

**Screenshots**
n/a

**Additional information**
Here at this [line](https://github.com/pravega/pravega/blob/a5f5d670b7f2340b8388a9a2b216aa7e5b4d7151/controller/src/main/java/io/pravega/controller/server/ControllerService.java#L507), we only retry commit if it fails due to a non `RetryableException` which should have been opposite. 
We should throw non `RetryableException`, and set `TxnStatus.Status.FAILURE` for `RetryableException` for client to retry.

### PR DESCRIPTION
**Pull request by ldr7**
**Change log description**  
Exception handling for commit and abort transaction is changed.  Only specific errors are thrown and the default way of handling exceptions is to fail the transaction so that the client can get retry.

**Purpose of the change**  
Fixes #5900 

**What the code does**  
For exceptions encountered during commit and abort transaction, they are checked against DataNotFound , IllegalState and  UnknownExceptions. For these the exception is thrown. For all other exceptions,  the transaction is failed for the client to retry.

**How to verify it**  
Build Pravega. Run the unit tests. Directly relevant ones are server/ControllerServiceTest.java and v1/ControllerServerTest.java.

### CODE REVIEW

**Review by shiveshr — COMMENTED** [review]
looks good.. please add unit tests covering this.

File: controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java [hunk 1]
```diff
@@ -260,6 +260,26 @@ public void testTransactions() {
...
+        status = consumer.abortTransaction(SCOPE, stream1, txnId).join();
+        assertEquals(status.getStatus(), Controller.TxnStatus.Status.FAILURE);
+
+        doThrow(StoreException.create(StoreException.Type.ILLEGAL_STATE, "Data Not Found"))
+                .when(streamStore).sealTransaction(eq(SCOPE), eq(stream1), eq(txnId), anyBoolean(), any(), anyString(), anyLong(),
+                any(), any());
+
+        status = consumer.commitTransaction(SCOPE, stream1, txnId, "", 0L).join();
+        assertEquals(status.getStatus(), Controller.TxnStatus.Status.FAILURE);
+
```
Comment (shiveshr) [inline controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java:282]: can you please add another test covering the case where an arbitrary exception is thrown by the store resulting in that same exception being thrown from the api

Comment (ldr7) [reply controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceTest.java:282]: Throwing of an unknown exception is tested on line 256. Just above the cases I have added.  This is for seal transaction, but since commit and abort utilize that pathway, I assumed the case is covered. Is it not?

File: controller/src/main/java/io/pravega/controller/server/ControllerService.java [hunk 2]
```diff
@@ -539,14 +538,14 @@ private Throwable getRealException(Throwable ex) {
                         log.error("Transaction abort failed for txn {} on Stream {}", txId.toString(),
                                 NameUtils.getScopedStreamName(scope, stream), ex);
                         Throwable unwrap = getRealException(ex);
-                        if (unwrap instanceof RetryableException) {
+                        if (unwrap instanceof StoreException.DataNotFoundException || unwrap instanceof StoreException.IllegalStateException || unwrap instanceof StoreException.UnknownException) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerService.java:541]: remove storeexception.unknownexception from here.

**Review by shiveshr — APPROVED** [review]
