### PR TITLE
Issue 5562: Wrong outstanding appends calculation in AppendBatchSizeTracker using connection pooling

### LINKED ISSUE #5531: Duplicate layer of AppendBatchSizeTrackers
**Problem description**
The writer uses `AppendBatchSizeTracker` objects to infer the right size of batches to be written to the server. However, currently there are 2 places in which such `AppendBatchSizeTracker` objects are being instantiated: `FlowHandler` and `TcpClientConnection`. In principle, the batching logic should be only in one place, and concretely, at the connection level. This is because, without connection pooling enabled, he number of flows should be equal to the number of connections. With connection pooling enabled, is at the connection level at where we need to track the data being written to the server, which can be a mix of multiple multiplexed flows.

In fact, after a preliminary analysis, it looks like the `AppendBatchSizeTracker` objects instantiated in `FlowHandler` are not used at all, so we can safely remove them.

**Problem location**
Unnecessary `AppendBatchSizeTracker` objects instantiated in `FlowHandler`.

**Suggestions for an improvement**
Remove unnecessary code.

### LINKED ISSUE #5562: Wrong outstanding appends calculation in AppendBatchSizeTracker using connection pooling
**Problem description**
When connection pooling is disabled, a Pravega writer instantiates as many connections with segment stores as flows are created. In turn, currently the `AppendBatchSizeTrackerImpl` objects are being used on a per-connection basis, so there is a 1:1 relationship between these three entities (connections, batch trackers, flows). 

However, when connection pooling is enabled, the current implementation keeps a limited number of connections and active batch trackers (e.g., 10 per segment store), while the number of flows is still the same as in the case of connection pooling being disabled. This leads to a situation in which a single `AppendBatchSizeTracker` instance is receiving events from multiple flows. The problem is that, currently, the `AppendBatchSizeTracker` is oblivious to the fact that multiple flows can be multiplexed and it does not take into account multiple flows in the batch calculation. This can lead to problems, as in the estimation of `appendsOutstanding`, in which the moving average calculation is polluted with event numbers of many flows without any kind of control: https://github.com/pravega/pravega/blob/11308526048aaed234ef8ee7d3d61f1a72f5ca0e/client/src/main/java/io/pravega/client/connection/impl/AppendBatchSizeTrackerImpl.java#L75

**Problem location**
`AppendBatchSizeTrackerImpl` and `FLowHandler`

**Suggestions for an improvement**
There are 2 options: i) either to fix `AppendBatchSizeTrackerImpl` to consider multiple flows (I have a prototype that works with this approach), and ii) make sure that there is a 1:1 relatioship between flows and `AppendBatchSizeTrackerImpl` instances. The latter approach may be better in the sense that it would be a smaller change and would keep intact the logic of `AppendBatchSizeTrackerImpl`.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Fixed the calculation of append batches in the client if connection pooling is enabled and multiple flows are multiplexed over the same connection.

**Purpose of the change**  
Fixes #5562.
Fixes #5531.

**What the code does**  

To solve #5562, this PR advocates to keep 1 `AppendBatchSizeTracker` object per flow. To this end:

- We introduce a new class (i.e., `FlowToBatchSizeTracker`), to keep the mapping between flows and batch trackers. It is based on `SimpleCache`, which provides us with thread-safety and an eviction mechanism, so this mapping will not grow forever.
- As `AppendBatchSizeTracker` is required at the `TCPClientConnection` and `CommandEncoder` levels, is there where we instantiate `FlowToBatchSizeTracker`. In this sense, this PR also removes the useless mapping of flow ids and batch trackers at the `FlowHandler` level, which in turn fixes #5531.
- Note that both `CommandEncoder` and `TCPClientConnection` fetch the appropriate `AppendBatchSizeTracker` by using `Flow.toFlowID(requestId)`. That is, the `AppendBatchSizeTracker` object is associated to a flow (i.e., most significant bits), irrespective of its sequence number (i.e., least significant bits).
- There is some minor and non-functional cleanup in `CommandEncoder` (e.g., wrong javadoc, redundant castings).

**How to verify it**  
Added new tests for `FlowToBatchSizeTracker`. I have tested this PR on AWS with connection pooling enabled (hundreds of segments and writers) and results are better in terms of latency.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java [hunk 1]
```diff
@@ -115,7 +113,7 @@ public void run() {
                     WireCommand command = readCommand(in, buffer);
                     if (command instanceof WireCommands.DataAppended) {
                         WireCommands.DataAppended dataAppended = (WireCommands.DataAppended) command;
-                        batchSizeTracker.recordAck(dataAppended.getEventNumber());
+                        flowToBatchSizeTracker.getAppendBatchSizeTrackerByFlowId(dataAppended.getRequestId()).recordAck(dataAppended.getEventNumber());
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java:116]: Using `io.pravega.client.connection.impl.Flow#toFlowID` api to get the requestId will ensure  only the flow id is used. This will ensure requests via the RawClient do not create multiple `AppendBatchSizeTrackers`.

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+ * Note that if a flow entry is evicted and then the flow is used again, the only consequence will be that its previous
+ * batching information would be lost and the flow will start operating with the batching algorithm defaults.
+ */
+@Slf4j
+public class FlowToBatchSizeTracker {
+
+    /**
+     * Maximum time that the want to keep an inactive flow entry in the cache.
+     */
+    private static final Duration TRACKER_CACHE_EXPIRATION_TIME = Duration.ofSeconds(60);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java:36]: This value can be same as `io.pravega.client.connection.impl.TcpClientConnection#SOCKET_TIMEOUT_MS`

**Review by shrids — COMMENTED** [review]
Great Find 👍 
The changes LGTM apart from a couple of questions...

File: client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java (hunk 1 above)
Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java]: Done.

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java (hunk 2 above)
Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java]: Done.

**Review by shrids — APPROVED** [review]
LGTM

File: client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java (hunk 1 above)
Comment (shrids) [inline client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java:116]: A response to a conditionalAppend would create a AppendBatchSizetracker instance...

Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/TcpClientConnection.java]: Thanks @shrids, that's correct, but then we need to use `Flow.toFlowID()` in `CommandEncoder` as well as I added in the last commit. Otherwise, the `CommandEncoder` and `TcpClientConnection` refer to different keys for the same `AppendBatchSizeTracker`.

File: client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java [hunk 3]
```diff
@@ -185,18 +147,6 @@ public void process(Reply cmd) {
...
-        if (cmd instanceof WireCommands.DataAppended) {
-            final WireCommands.DataAppended dataAppended = (WireCommands.DataAppended) cmd;
-            final AppendBatchSizeTracker batchSizeTracker = getAppendBatchSizeTracker(dataAppended.getRequestId());
-            if (batchSizeTracker != null) {
-                long pendingAckCount = batchSizeTracker.recordAck(dataAppended.getEventNumber());
-                // Only publish client side metrics when there is some metrics notifier configured for efficiency.
-                if (!metricNotifier.equals(MetricNotifier.NO_OP_METRIC_NOTIFIER)) {
-                    metricNotifier.updateSuccessMetric(CLIENT_OUTSTANDING_APPEND_COUNT, writerTags(dataAppended.getWriterId().toString()),
-                            pendingAckCount);
-                }
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java:197]: Are we loosing this metric?

**Review by tkaitchuck — APPROVED** [review]

File: client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java (hunk 3 above)
Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/FlowHandler.java:197]: We have never used it since it was introduced as far as I know, and it may reduce the computation overhead of the client when processing the ack. We can bring it back in the future if necessary.

**Review by shrids — APPROVED** [review]
+1

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    /**
+     * Maximum number of active flow entries in the cache.
+     */
+    private static final int TRACKER_CACHE_MAX_SIZE = 100000;
+
+    @VisibleForTesting
+    @Getter(value = AccessLevel.PACKAGE)
+    private final SimpleCache<Integer, AppendBatchSizeTracker> flowToBatchSizeTrackerMap;
+
+    public FlowToBatchSizeTracker() {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java:46]: Should this constructor and this class be package protected rather than public?

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    /**
+     * This method returns the {@link AppendBatchSizeTracker} instance for a given flow id. If the flow id does not exist
+     * yet in the cache, the new entry for the flow is created along with a new {@link AppendBatchSizeTracker} object.
+     *
+     * @param flowId    Identifier for the flow.
+     * @return The {@link AppendBatchSizeTracker} instance associated to the flow id.
+     */
+    public AppendBatchSizeTracker getAppendBatchSizeTrackerByFlowId(int flowId) {
+        if (flowToBatchSizeTrackerMap.putIfAbsent(flowId, new AppendBatchSizeTrackerImpl()) == null) {
+            log.info("Instantiating new batch sze tracker for flow: {}", flowId);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java:65]: This is a debug message.

**Review by fpj — CHANGES_REQUESTED** [review]
A couple of minor points.

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java (hunk 4 above)
Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java]: Done.

File: client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java (hunk 5 above)
Comment (RaulGracia) [reply client/src/main/java/io/pravega/client/connection/impl/FlowToBatchSizeTracker.java]: Done.

**Comment by leapsky** [comment]
Experiments with `5000 segments, 250MBps, 1KB events` and `connection pooling enabled`, `1` and `100 writers` ran successfully.
Also, I ran experiments with `1000 segments, 250MBps, 1KB events` and `connection pooling disabled` which showed similar results that we had for master.

**Comment by RaulGracia** [comment]
@fpj thanks for the feedback, I have addressed your comments. If you don't have any further comments, please try to give a go to this PR as it would be important to cherry-pick it to `r0.9`.

**Review by fpj — APPROVED** [review]
