### PR TITLE
Issue 1407: Writing into transaction and reading with failover scenarios

### LINKED ISSUE #1407: Implement a  Multi Reader Writer Transaction Test, with controller, segmentstore fail over scenarios
**Problem description**
This task is to implement a test case with some readers, writers writing using transactions and reading  in the following cases:

1. 2 controller, SSS instances
2. With 1 SSS instance failure
3. With 1 controller instance failure
4. With 1 controller, 1 SSS instances down

**Problem location**
System Tests

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
A simple test case which does the following :
Setup : 3 Controller, 3 SSS instances running.
Step 1. 5 writers writing into transactions and  5 readers reading the events in parallel.
Step 2. Failover cases will get executed in the below order : -
a. SSS failover
b. controller failover
c. SSS and controller failover
Step3 : Event read count and even write count after failover are compared with previous values(before failover) , to ensure reads and writes are happening inspite of crashes.
Step 4: At the end, we wait for read counts to be matched with write counts and then stop the writers, readers.

**Purpose of the change**
Adding new system test cases to cover failover.

**What the code does**
Fixes #1407 

**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 1]
```diff
@@ -0,0 +1,436 @@
...
+        //2. Start 3 bookies
+        Service bkService = new BookkeeperService("bookkeeper", zkUri);
+        if (!bkService.isRunning()) {
+            bkService.start(true);
+        }
+        List<URI> bkUris = bkService.getServiceDetails();
+        log.debug("Bookkeeper service details: {}", bkUris);
+
+        //3. start 3 instances of pravega controller
+        Service conService = new PravegaControllerService("controllerFailover2", zkUri);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: We need to reuse ids, this will enable us to use already running controller instances.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 2]
```diff
@@ -0,0 +1,436 @@
...
+
+        // Fetch all the RPC endpoints and construct the client URIs.
+        final List<String> uris = conUris.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+                .collect(Collectors.toList());
+
+        URI controllerURI = URI.create("tcp://" + String.join(",", uris));
+        log.info("Controller Service direct URI: {}", controllerURI);
+
+        //4.start 3 instances of pravega segmentstore
+        Service segService = new PravegaSegmentStoreService("segmentstoreFailover2", zkUri, controllerURI);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Same comment as above, reuse id.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 3]
```diff
@@ -0,0 +1,436 @@
...
+        assertTrue(segmentStoreInstance.isRunning());
+        log.info("Pravega Segmentstore service instance details: {}", segmentStoreInstance.getServiceDetails());
+
+        executorService = Executors.newFixedThreadPool(NUM_READERS + NUM_WRITERS);
+    }
+
+    @After
+    public void tearDown() {
+        if (controllerInstance != null && controllerInstance.isRunning()) {
+            controllerInstance.stop();
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: we need to scale it back to 1 if we are reusing controller ids.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 4]
```diff
@@ -0,0 +1,436 @@
...
+        log.info("Read count with SSS and controller failover after sleep {}", currentReadCount1);
+        log.info("Write count with SSS and controller failover after sleep {} ", currentWriteCount1);
+    }
+
+    private CompletableFuture<Void> startWritingIntoTxn(final AtomicLong data, final EventStreamWriter<Long> writer,
+                                                 final AtomicBoolean stopWriteFlag) {
+        return CompletableFuture.runAsync(() -> {
+            while (!stopWriteFlag.get()) {
+                    try {
+                        Transaction<Long> transaction = writer.beginTxn(5000, 3600000, 29000);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Log the transaction id created, useful for debugging.
Also we need to log any exceptions  while creating a txn.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 5]
```diff
@@ -0,0 +1,436 @@
...
+                        log.debug("Transaction {} committed", transaction);
+                        log.debug("Transaction status {}", transaction.checkStatus());
+                    } catch (Throwable e) {
+                        log.warn("Exception while writing events in the transaction : {}", e);
+                    }
+            }
+        }, executorService);
+    }
+
+    private CompletableFuture<Void> startReading(final ConcurrentLinkedQueue<Long> readResult, final AtomicLong writeCount, final
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: we can reuse the method in MultiReaderWriterWithFailOverTest

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 6]
```diff
@@ -0,0 +1,436 @@
...
+                            long value = data.incrementAndGet();
+                            transaction.writeEvent(String.valueOf(value), value);
+                            log.debug("Writing event {} into transaction {}", value, transaction);
+                        }
+                        //commit Txn
+                        transaction.commit();
+                        log.debug("Transaction {} committed", transaction);
+                        log.debug("Transaction status {}", transaction.checkStatus());
+                    } catch (Throwable e) {
+                        log.warn("Exception while writing events in the transaction : {}", e);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Log the transaction id for which transaction failed, also we need to distinguish between transaction creation failure v/s a transaction commit() failure. If there is a failure during Txn.commit() it will cause a mismatch in `event written count` and `events read count`.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 7]
```diff
@@ -0,0 +1,436 @@
...
+    private CompletableFuture<Void> startWritingIntoTxn(final AtomicLong data, final EventStreamWriter<Long> writer,
+                                                 final AtomicBoolean stopWriteFlag) {
+        return CompletableFuture.runAsync(() -> {
+            while (!stopWriteFlag.get()) {
+                    try {
+                        Transaction<Long> transaction = writer.beginTxn(5000, 3600000, 29000);
+                        //each transaction has 100 events
+                        for (int j = 0; j < 100; j++) {
+                            long value = data.incrementAndGet();
+                            transaction.writeEvent(String.valueOf(value), value);
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: include a delay and reduce the loop count so there is a chance the transaction happens across scale, which would be a good failover test case. 
You can also add a flush after writeEvent() so won't have to wait until commit for write to happen

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: reduced transaction size to 50 events and added a delay of 100ms

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 5 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 6 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done, using the logic from readwithautoscaletest.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 4 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: We need to do a cleanup after every test, which we are not doing currently. Hence, using different id and doing a teardown after test.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 8]
```diff
@@ -0,0 +1,444 @@
...
+        String scope = "testMultiReaderWriterTxnScope" + new Random().nextInt(Integer.MAX_VALUE);
+        String readerGroupName = "testMultiReaderWriterTxnReaderGroup" + new Random().nextInt(Integer.MAX_VALUE);
+        ScalingPolicy scalingPolicy = ScalingPolicy.fixed(NUM_READERS);
+        StreamConfiguration config = StreamConfiguration.builder().scope(scope)
+                .streamName(STREAM_NAME).scalingPolicy(scalingPolicy).build();
+        //get Controller Uri
+        URI controllerUri = controllerURIDirect;
+        Controller controller = new ControllerImpl(controllerUri);
+
+        eventsReadFromPravega = new ConcurrentLinkedQueue<>();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Members should be initialized in setup and cleared in teardown.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 9]
```diff
@@ -0,0 +1,444 @@
...
+                log.info("Starting writer{}", i);
+                final EventStreamWriter<Long> writer = clientFactory.createEventWriter(STREAM_NAME,
+                        new JavaSerializer<Long>(),
+                        EventWriterConfig.builder().retryAttempts(10).build());
+                writerList.add(writer);
+            }
+
+            //create a reader group
+            log.info("Creating Reader group : {}", readerGroupName);
+            log.info("Scope passed to readergroup manager {}", scope);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: COmbine these two log lines.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 10]
```diff
@@ -0,0 +1,444 @@
...
+
+        //get ClientFactory instance
+        log.info("Scope passed to client factory {}", scope);
+        try (ClientFactory clientFactory = new ClientFactoryImpl(scope, controller);
+             ReaderGroupManager readerGroupManager = ReaderGroupManager.withScope(scope, controllerUri)) {
+
+            log.info("Client factory details {}", clientFactory.toString());
+            //create writers
+            log.info("Creating {} writers", NUM_WRITERS);
+            List<EventStreamWriter<Long>> writerList = new ArrayList<>();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: ArrayList<>(NUM_WRITERS);

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 11]
```diff
@@ -0,0 +1,444 @@
...
+
+            readerGroupManager.createReaderGroup(readerGroupName, ReaderGroupConfig.builder().startingTime(0).build(),
+                    Collections.singleton(STREAM_NAME));
+            log.info("Reader group name {} ", readerGroupManager.getReaderGroup(readerGroupName).getGroupName());
+            log.info("Reader group scope {}", readerGroupManager.getReaderGroup(readerGroupName).getScope());
+            log.info("Online readers {}", readerGroupManager.getReaderGroup(readerGroupName).getOnlineReaders());
+
+            //create readers
+            log.info("Creating {} readers", NUM_READERS);
+            List<EventStreamReader<Long>> readerList = new ArrayList<>();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: ArrayList<>(NUM_READERS)

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 12]
```diff
@@ -0,0 +1,444 @@
...
+                writerList.add(writer);
+            }
+
+            //create a reader group
+            log.info("Creating Reader group : {}", readerGroupName);
+            log.info("Scope passed to readergroup manager {}", scope);
+
+            readerGroupManager.createReaderGroup(readerGroupName, ReaderGroupConfig.builder().startingTime(0).build(),
+                    Collections.singleton(STREAM_NAME));
+            log.info("Reader group name {} ", readerGroupManager.getReaderGroup(readerGroupName).getGroupName());
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Combine these log lines

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 13]
```diff
@@ -0,0 +1,444 @@
...
+            log.info("Online readers {}", readerGroupManager.getReaderGroup(readerGroupName).getOnlineReaders());
+
+            //create readers
+            log.info("Creating {} readers", NUM_READERS);
+            List<EventStreamReader<Long>> readerList = new ArrayList<>();
+            String readerName = "reader" + new Random().nextInt(Integer.MAX_VALUE);
+            log.info("Scope that is seen by readers {}", scope);
+            //start reading events
+            for (int i = 0; i < NUM_READERS; i++) {
+                log.info("Starting reader{}", i);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Combine these log lines

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 14]
```diff
@@ -0,0 +1,444 @@
...
+                log.info("Creating reader with id {}", readerName + i);
+                final EventStreamReader<Long> reader = clientFactory.createReader(readerName + i,
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: The readerName has both a random integer and a sequential one appended to it. This seems redundant. Either would be sufficient to ensure uniqueness.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 15]
```diff
@@ -0,0 +1,444 @@
...
+                        readerGroupName,
+                        new JavaSerializer<Long>(),
+                        ReaderConfig.builder().build());
+                readerList.add(reader);
+            }
+
+            // start writing asynchronously
+            List<CompletableFuture<Void>> writerFutureList = new ArrayList<>();
+            writerList.forEach(writer -> {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: This could be more concice with `writerList.stream().map(writer -> startWritingINtoTxn(...)).collect(COllections.toList());`

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 16]
```diff
@@ -0,0 +1,444 @@
...
+                CompletableFuture<Void> writerFuture = startWritingIntoTxn(eventData, writer, stopWriteFlag, eventWriteCount);
+                writerFutureList.add(writerFuture);
+            });
+
+            //start reading asynchronously
+            List<CompletableFuture<Void>> readerFutureList = new ArrayList<>();
+            readerList.forEach(reader -> {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: See above

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 17]
```diff
@@ -0,0 +1,444 @@
...
+
+        long currentWriteCount1;
+        long currentReadCount1;
+
+        log.info("Test with 2 controller, SSS instances running and without a failover scenario");
+
+        currentWriteCount1 = eventWriteCount.get();
+        currentReadCount1 = eventReadCount.get();
+
+        log.info("Read count without any failover {}", currentReadCount1);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Here and below: combine these double log lines into one.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 18]
```diff
@@ -0,0 +1,444 @@
...
+        log.info("Write count without any failover after sleep before scaling {}", currentWriteCount2);
+
+        //ensure writes are happening
+        assertTrue(currentWriteCount2 > currentWriteCount1);
+        //ensure reads are happening
+        assertTrue(currentReadCount2 > currentReadCount1);
+
+        //Scale down SSS instances to 2
+        segmentStoreInstance.scaleService(2, true);
+        //zookeeper will take about 60 seconds to detect that the node has gone down
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Is this tunable? If it's a parameter, we could refer to the same constant.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 19]
```diff
@@ -0,0 +1,444 @@
...
+
+        //ensure writes are happening
+        assertTrue(currentWriteCount2 > currentWriteCount1);
+        //ensure reads are happening
+        assertTrue(currentReadCount2 > currentReadCount1);
+
+        //Scale down SSS, controller to 1 instance each.
+        segmentStoreInstance.scaleService(1, true);
+        controllerInstance.scaleService(1, true);
+        //zookeeper will take about 60 seconds to detect that the node has gone down
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Same as above.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 20]
```diff
@@ -0,0 +1,444 @@
...
+                        for (int j = 0; j < 50; j++) {
+                            long value = data.incrementAndGet();
+                            Thread.sleep(100);
+                            transaction.writeEvent(String.valueOf(value), value);
+                            log.debug("Writing event {} into transaction {}", value, transaction);
+                        }
+                        //commit Txn
+                        transaction.commit();
+                        eventWriteCount.getAndAdd(50);
+                        log.debug("Transaction {} committed", transaction);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Combine

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 21]
```diff
@@ -0,0 +1,444 @@
...
+
+    private Transaction<Long> createTransaction(EventStreamWriter<Long> writer, final AtomicBoolean exitFlag) {
+        Transaction<Long> txn = null;
+        try {
+            //Default max scale grace period is 30000
+            txn = writer.beginTxn(5000, 3600000, 29000);
+            log.info("Transaction created with id:{} ", txn.getTxnId());
+        } catch (RuntimeException ex) {
+            log.info("Exception encountered while trying to begin Transaction ", ex.getCause());
+            final Class<? extends Throwable> exceptionClass = ex.getCause().getClass();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: instanceof is far cheaper than getClass() and it is cleaner because it can be done inline in the if and handles subclasses.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 1 above)
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: why is that? 
each test should run against same pravega set up. 
each test can create a unique scope and work under that so that they remain completely independent and hence no clean up should be required. .

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 22]
```diff
@@ -0,0 +1,444 @@
...
+        log.info("Write count with SSS and controller failover after sleep {} ", currentWriteCount1);
+    }
+
+    private CompletableFuture<Void> startWritingIntoTxn(final AtomicLong data, final EventStreamWriter<Long> writer,
+                                                 final AtomicBoolean stopWriteFlag, final AtomicLong eventWriteCount) {
+        return CompletableFuture.runAsync(() -> {
+            while (!stopWriteFlag.get()) {
+                Transaction<Long> transaction = null;
+                    try {
+                        transaction = Retry.withExpBackoff(10, 10, 20, ofSeconds(1).toMillis())
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: create a global retry object that can be reused with each txn.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 23]
```diff
@@ -0,0 +1,444 @@
...
+                                .retryingOn(MultiReaderWriterTxnWithFailoverTest.TxnCreationFailedException.class)
+                                .throwingOn(RuntimeException.class)
+                                .run(() -> createTransaction(writer, stopWriteFlag));
+
+                        //each transaction has 50 events
+                        for (int j = 0; j < 50; j++) {
+                            long value = data.incrementAndGet();
+                            Thread.sleep(100);
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: any specific reason you want to put a sleep and slow down the traffic?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 24]
```diff
@@ -0,0 +1,444 @@
...
+                            transaction.writeEvent(String.valueOf(value), value);
+                            log.debug("Writing event {} into transaction {}", value, transaction);
+                        }
+                        //commit Txn
+                        transaction.commit();
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: once we have called commit for the transaction, we need to check its status to make sure it was indeed committed. until then we cant increment 'write count' in the next line.. this is because txn.commit call merely writes to event processor and returns.. a commit may get delayed or the txn may get aborted on the server in a race scenario, whereby your test will count incorrectly and find that read and write counts mismatch

Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: so you should call txn.getStatus() and wait until the status becomes committed before adding it to the count. 
this can be scheduled in the background.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 25]
```diff
@@ -0,0 +1,444 @@
...
+        currentWriteCount1 = eventWriteCount.get();
+        currentReadCount1 = eventReadCount.get();
+
+        log.info("Read count without any failover {}", currentReadCount1);
+        log.info("Write count without any failover {}", currentWriteCount1);
+
+        int sleepTime;
+
+        //check reads and writes after some random time
+        sleepTime = new Random().nextInt(50000) + 3000;
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: what is this delay giving us.. a delay after failover is meaningful but a delay before failure is not going to serve any purpose IMO

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 18 above)
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: 60 seconds to identify failure and failover segment containers?!!! 
are you saying all reads and writes to segments whose SSS goes down will be stalled for over 60 seconds?!
@skrishnappa is that the case?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 26]
```diff
@@ -0,0 +1,444 @@
...
+
+        //ensure writes are happening
+        assertTrue(currentWriteCount1 > currentWriteCount2);
+        //ensure reads are happening
+        assertTrue(currentReadCount1 > currentReadCount2);
+
+        //Scale down controller instances to 2
+        controllerInstance.scaleService(2, true);
+        //zookeeper will take about 60 seconds to detect that the node has gone down
+        Thread.sleep(60000);
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: writes and reads should continue to happen even with controller failover.
since you are doing txn writes, make sure that while controller instance is scaled down, we are still able to commit transactions (ensure that you dont just call commit, but check txn status and ensure it reaches committed state)

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 27]
```diff
@@ -0,0 +1,444 @@
...
+            });
+
+            //start reading asynchronously
+            List<CompletableFuture<Void>> readerFutureList = new ArrayList<>();
+            readerList.forEach(reader -> {
+                CompletableFuture<Void> readerFuture = startReading(eventsReadFromPravega, eventWriteCount, eventReadCount, stopReadFlag, reader);
+                readerFutureList.add(readerFuture);
+            });
+
+            //perform the scaling operations
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: It is a bit odd to say `perform scaling...` and call the method `perform failover...`, it sounds like the comment and the method call don't match.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 8 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 10 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 9 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 12 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 11 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 13 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 14 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: removed random.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 15 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 16 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 17 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 18 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: No, it's not tunable.

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Yes, it takes 60s.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 20 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 21 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 22 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 23 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: This is a tight loop, and i have added it to address suri's comment above.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 24 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 25 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: This is just to ensure reads and writes are happening before failover.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 26 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: yes, taken care.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 27 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 2 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 3 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done

**Comment by Prabha-Veerubhotla** [comment]
DO NOT MERGE

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 18 above)
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: @shiveshr this is due to the zookeeper default session timeout, which is how we detect if a node has gone down.

Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: Wait? This means we're effectively down for 60 seconds regardless of how quickly we can run recovery?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java [hunk 28]
```diff
@@ -0,0 +1,451 @@
...
+                            long value = data.incrementAndGet();
+                            Thread.sleep(100);
+                            transaction.writeEvent(String.valueOf(value), value);
+                            log.debug("Writing event: {} into transaction: {}", value, transaction);
+                        }
+                        //commit Txn
+                        transaction.commit();
+
+                        //wait for transaction to get committed
+                        while (!transaction.checkStatus().equals(Transaction.Status.COMMITTED)) {
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: this will be stuck in infinite loop if for some reason txn gets aborted

Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: the idea i suggested was -- check txn status in background and update the 'write count' once you figure out that txn has indeed committed. 
break the loop if txn has completed, either with committed or aborted.

Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: also you may use Retry.runAsync so that you are not blocking a thread to verify txn status. 
(this way you will allow for multiple txns to run concurrently while readers are reading data from them in the background).

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 18 above)
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: zk will detect a crash using a session timeout. the session timeout is configurable, where are we configuring it for these system tests?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 28 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: done . added checkTxnStatus()

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java (hunk 18 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTxnWithFailoverTest.java]: It is a deployment value and is not configurable.
The only zk session timout , i can find is for bookkeeper :
https://github.com/pravega/pravega/blob/0c2cdc8616e272f3dc4a5157cbce5ade38f12c58/segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperConfig.java#L29

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 29]
```diff
@@ -0,0 +1,468 @@
...
+        scope = "testMultiReaderWriterTxnScope" + new Random().nextInt(Integer.MAX_VALUE);
+        scalingPolicy = ScalingPolicy.fixed(NUM_READERS);
+        config = StreamConfiguration.builder().scope(scope)
+                .streamName(STREAM_NAME).scalingPolicy(scalingPolicy).build();
+
+        readerGroupName = "testMultiReaderWriterTxnReaderGroup" + new Random().nextInt(Integer.MAX_VALUE);
+        readerName = "reader";
+    }
+
+   /* @After
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Why is this commented out?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 30]
```diff
@@ -0,0 +1,468 @@
...
+        log.info("Read count: {}, write count: {} after SSS failover after sleep", currentReadCount1, currentWriteCount1);
+
+        //ensure writes are happening
+        assertTrue(currentWriteCount1 > currentWriteCount2);
+        //ensure reads are happening
+        assertTrue(currentReadCount1 > currentReadCount2);
+
+        //Scale down controller instances to 2
+        controllerInstance.scaleService(2, true);
+        //zookeeper will take about 60 seconds to detect that the node has gone down
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: We need to find out where we are setting the zookeeper session timeout. The session timeout is set when we create the zookeeper handle (`ZooKeeper` object). The default is much smaller than this, and I'm not sure why we raised to a minute.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 31]
```diff
@@ -0,0 +1,468 @@
...
+                        log.debug("Writing event: {} into transaction: {}", value, transaction);
+                    }
+                    //commit Txn
+                    transaction.commit();
+
+                    //wait for transaction to get committed
+                    checkTxnStatus(transaction, eventWriteCount).get();
+                } catch (Throwable e) {
+                    log.warn("Exception while writing events in the transaction: {}", e);
+                    //log.debug("Transaction with id: {}  failed", transaction.getTxnId());
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Commented code.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 30 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: `org.apache.curator.framework.CuratorFrameworkFactory#DEFAULT_SESSION_TIMEOUT_MS` is 60*1000 ms. The session timeout for curator can be configured via system property `curator-default-session-timeout` .

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 31 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: uncommented.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 29 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 30 above)
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Yeah we are relying on the the curator client's default for this (I had miss-communicated this earlier; the zookeeper deployment configuration is for the min and max values based on its tickTime configuration). We need to expose the session timeout value via segment store's and controller's configuration (this is where we register to zookeeper) if we want to control the session timeout; or we can just use a lower default for the session timeout if that makes sense for our deployments. @fpj any suggestions?

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: reduced it to 30s.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 32]
```diff
@@ -0,0 +1,496 @@
...
+                log.warn("Cause for failure is {} and we need to retry", ex.getClass().getName());
+                throw new TxnCreationFailedException(); // we can retry on this exception.
+            } else {
+                throw ex;
+            }
+        }
+        return txn;
+    }
+
+    private CompletableFuture<Void> startReading(final ConcurrentLinkedQueue<Long> readResult, final AtomicLong writeCount, final
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Here and above: Rather than passing mutable members, utilize the return value for results and member variables for things like the booleans/longs that are shared.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 33]
```diff
@@ -0,0 +1,496 @@
...
+    private Service segmentStoreInstance = null;
+    private URI controllerURIDirect = null;
+    private URI controllerUri;
+    private Controller controller;
+    private String scope;
+    private String readerGroupName;
+    private ScalingPolicy scalingPolicy;
+    private StreamConfiguration config;
+    private String readerName;
+    private Retry.RetryWithBackoff retry = Retry.withExpBackoff(10, 10, 20, ofSeconds(1).toMillis());
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 34]
```diff
@@ -0,0 +1,496 @@
...
+        log.info("Controller Service direct URI: {}", controllerURIDirect);
+
+        // Verify segment store is running.
+        segmentStoreInstance = new PravegaSegmentStoreService("segmentstore", zkUri, controllerURIDirect);
+        assertTrue(segmentStoreInstance.isRunning());
+        log.info("Pravega Segmentstore service instance details: {}", segmentStoreInstance.getServiceDetails());
+        //executor service
+        executorService = Executors.newFixedThreadPool(NUM_READERS + NUM_WRITERS);
+        //get Controller Uri
+        controllerUri = controllerURIDirect;
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: removed one.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 35]
```diff
@@ -0,0 +1,496 @@
...
+        controller = new ControllerImpl(controllerUri);
+        //read and write count variables
+        eventsReadFromPravega = new ConcurrentLinkedQueue<>();
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 36]
```diff
@@ -0,0 +1,496 @@
...
+        readerGroupName = "testMultiReaderWriterTxnReaderGroup" + new Random().nextInt(Integer.MAX_VALUE);
+        readerName = "reader";
+    }
+
+    @After
+    public void tearDown() {
+        controllerInstance.scaleService(1, true);
+        segmentStoreInstance.scaleService(1, true);
+        executorService.shutdownNow();
+        controllerUri = null;
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: yeah, removed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 32 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: done.
