### PR TITLE
Issue 1570: Fix the improper event write count calculation

### LINKED ISSUE #1570: Event write count is wrongly calculated in MultiReaderTxnWriterWithFailoverTest
**Problem description**
When a transaction is committed, the event count should be increased by num of events in transaction.
in the current code , it is wrongly incremented by one.

**Problem location**
https://github.com/pravega/pravega/blob/1c12462de423b0e06d919504603a1094959eea4c/test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java#L416

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
When a transaction is committed, write count has to be increased by the size of transaction.

**Purpose of the change**
write count is wrongly calculated.

**What the code does**
Fixes #1570 

**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 1]
```diff
@@ -67,6 +67,7 @@
     private static final int NUM_WRITERS = 5;
     private static final int NUM_READERS = 5;
     private static final int ZK_DEFAULT_SESSION_TIMEOUT = 60000;
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: As i understand the default session timeout is 30 seconds and not 60 seconds, right?

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: yes, updated.
