### PR TITLE
Issue 5808: SLTS - Fix Preconditions checks to include enough information in message.

### LINKED ISSUE #5808: SLTS - Fix Preconditions checks to include enough information in message.
**Describe the bug**
Many Preconditions checks in SLTS code do not have enough enough information about why they failed.
Often in the field we do not have enough context or stack trace available to figure out exactly what failed and why.

**To Reproduce**
The checks are not supposed to fail in a working system.
So it is hard to repro. But code scan should reveal which ones need to be fixed.

**Expected behavior**
A clear and concise description in message.

**Screenshots**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Issue 5808: SLTS - Fix Preconditions checks to include enough information in message.

Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
Fix Preconditions checks to include enough information in message.

**Purpose of the change**  
Fix #5808 

**What the code does**  
Fix Preconditions checks to include enough information in message.
NOTE - Preconditions.checkNull throws NullPointerException so there are places where InvalidArgmentException is need hence we do arg != null check. I have not changed those.

**How to verify it**  
No regression

### CODE REVIEW

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java [hunk 1]
```diff
@@ -313,11 +313,11 @@ public AsyncBaseChunkStorage(Executor executor) {
     final public CompletableFuture<Integer> read(ChunkHandle handle, long fromOffset, int length, byte[] buffer, int bufferOffset) {
         Exceptions.checkNotClosed(this.closed.get(), this);
         // Validate parameters
-        Preconditions.checkArgument(null != handle, "handle");
+        Preconditions.checkArgument(null != handle, "handle must not be null");
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java:316]: Please change the null checks to one of the following:
1. `Preconditions.checkNotNull`
2. Add `@NonNull`  (from `Lombok`) as an annotation to the argument (preferred). This will save you from all this boilerplate code.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java [hunk 2]
```diff
@@ -313,11 +313,11 @@ public AsyncBaseChunkStorage(Executor executor) {
...
         checkChunkName(handle.getChunkName());
-        Preconditions.checkArgument(null != buffer, "buffer");
+        Preconditions.checkArgument(null != buffer, "buffer must not be null");
         Preconditions.checkArgument(fromOffset >= 0, "fromOffset must be non-negative");
-        Preconditions.checkArgument(length >= 0 && length <= buffer.length, "length");
+        Preconditions.checkArgument(length >= 0 && length <= buffer.length, "length must be non-negative and must not exceed buffer");
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java:320]: Please use `Exceptions.checkArrayRange`.  That will replace both this line and the next and add a couple more cases that it verifies.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java [hunk 3]
```diff
@@ -410,7 +410,7 @@ boolean isStorageSystemSegment(SegmentMetadata segmentMetadata) {
             Preconditions.checkNotNull(handle, "handle");
             String streamSegmentName = handle.getSegmentName();
             Preconditions.checkNotNull(streamSegmentName, "streamSegmentName");
-            Preconditions.checkArgument(!handle.isReadOnly(), "handle");
+            Preconditions.checkArgument(!handle.isReadOnly(), "handle must not be read only");
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:413]: Segment name?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java [hunk 4]
```diff
@@ -205,10 +205,10 @@ private void checkState() {
     }
 
     private void checkPreconditions() {
-        Preconditions.checkArgument(null != targetHandle, "targetHandle");
-        Preconditions.checkArgument(!targetHandle.isReadOnly(), "targetHandle");
-        Preconditions.checkArgument(null != sourceSegment, "targetHandle");
-        Preconditions.checkArgument(offset >= 0, "offset");
+        Preconditions.checkArgument(null != targetHandle, "targetHandle must not be null");
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java:208]: Same here. See above.

Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java:208]: And everywhere else below.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java (hunk 1 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java:316]: NOTE - Preconditions.checkNull throws NullPointerException so there are places where InvalidArgmentException is need hence we do arg != null check. I have not changed those.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java:320]: This needs to throw InvalidArgementException.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 3 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:413]: good catch.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java]: Do not want to change method signature and tests for this change.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java (hunk 1 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/AsyncBaseChunkStorage.java:316]: Do not want to change method signature and tests for this change.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java (hunk 4 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java:208]: Do not want to change method signature and tests for this change.

**Comment by sachin-j-joshi** [comment]
Fixed a few more.

**Review by andreipaduroiu — APPROVED** [review]

**Review by RaulGracia — APPROVED** [review]

**Comment by RaulGracia** [comment]
@sachin-j-joshi looks like codecov is complaining. We need to make it happy before we can merge.
