### PR TITLE
Issue 3708: Sporadic failure of HostStoreTest.zkHostStoreTests

### LINKED ISSUE #3708: Sporadic failure of HostStoreTest.zkHostStoreTests
**Problem description**
Test `HostStoreTest.zkHostStoreTests` has been recently updated (#3682) and is failing sporadically:
```
2019-04-26 08:17:34,790 367056 [Thread-6422] INFO  o.a.c.test.TestingZooKeeperMain - Starting server
2019-04-26 08:17:34,792 367058 [Time-limited test] WARN  o.a.curator.CuratorZookeeperClient - session timeout [10000] is less than connection timeout [15000]
2019-04-26 08:17:34,792 367058 [Time-limited test] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Starting
2019-04-26 08:17:34,792 367058 [Time-limited test] DEBUG o.a.curator.CuratorZookeeperClient - Starting
2019-04-26 08:17:34,792 367058 [Time-limited test] DEBUG org.apache.curator.ConnectionState - Starting
2019-04-26 08:17:34,792 367058 [Time-limited test] DEBUG org.apache.curator.ConnectionState - reset
2019-04-26 08:17:34,793 367059 [Time-limited test] INFO  o.a.c.f.imps.CuratorFrameworkImpl - Default schema
2019-04-26 08:17:34,793 367059 [Time-limited test] INFO  i.p.c.store.host.HostStoreFactory - Creating Zookeeper based host store
2019-04-26 08:17:34,801 367067 [Time-limited test-EventThread] DEBUG org.apache.curator.ConnectionState - Negotiated session timeout: 10000
2019-04-26 08:17:34,801 367067 [Time-limited test-EventThread] INFO  o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
2019-04-26 08:17:34,801 367067 [Time-limited test-EventThread] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Clearing sleep for 1 operations
2019-04-26 08:17:34,802 367068 [Time-limited test-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {}
2019-04-26 08:17:34,802 367068 [Time-limited test-EventThread] DEBUG o.a.c.f.imps.EnsembleTracker - Ignoring new config as it is empty
2019-04-26 08:17:34,802 367068 [Time-limited test-EventThread] INFO  o.a.c.f.imps.EnsembleTracker - New config event received: {}
2019-04-26 08:17:34,802 367068 [Time-limited test-EventThread] DEBUG o.a.c.f.imps.EnsembleTracker - Ignoring new config as it is empty
2019-04-26 08:17:34,810 367076 [Time-limited test] INFO  i.p.c.store.host.ZKHostStore - Successfully updated segment container map
2019-04-26 08:17:34,811 367077 [Time-limited test] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Closing
2019-04-26 08:17:34,811 367077 [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1499)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1487)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1904)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1937)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
	at org.apache.curator.framework.imps.CreateBuilderImpl$9.performBackgroundOperation(CreateBuilderImpl.java:799)
	at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:947)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:925)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:73)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:322)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-26 08:17:34,811 367077 [Curator-Framework-0] INFO  o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2019-04-26 08:17:34,811 367077 [Time-limited test] DEBUG o.a.c.f.imps.WatcherRemovalManager - Removing watcher for path: /zookeeper/config
2019-04-26 08:17:34,812 367078 [Time-limited test] DEBUG o.a.curator.CuratorZookeeperClient - Closing
2019-04-26 08:17:34,812 367078 [Time-limited test] DEBUG org.apache.curator.ConnectionState - Closing
2019-04-26 08:17:34,815 367081 [Time-limited test] ERROR i.p.c.store.stream.HostStoreTest - Unexpected error
io.pravega.controller.store.host.HostStoreException: Could not find host for container id: 2
	at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:131)
	at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:143)
	at io.pravega.controller.store.stream.HostStoreTest.validateStore(HostStoreTest.java:119)
	at io.pravega.controller.store.stream.HostStoreTest.zkHostStoreTests(HostStoreTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
If we compare the logs with a successful run of the same test, it seems that the Curator client is getting closed before it is actually used to query ZK to work on the hostContainerMap:
```
2019-04-25 09:36:09,337 384763 [Time-limited test-EventThread] DEBUG o.a.c.f.imps.EnsembleTracker - Ignoring new config as it is empty
2019-04-25 09:36:09,345 384771 [Time-limited test] INFO  i.p.c.store.host.ZKHostStore - Successfully updated segment container map
2019-04-25 09:36:09,352 384778 [Time-limited test] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: localhost:9090: for containerId: 3
2019-04-25 09:36:09,354 384780 [Time-limited test] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: localhost:9090: for containerId: 2
2019-04-25 09:36:09,354 384780 [Time-limited test] INFO  i.p.c.store.host.HostStoreFactory - Creating Zookeeper based host store
2019-04-25 09:36:09,356 384782 [Time-limited test] DEBUG o.a.c.f.imps.CuratorFrameworkImpl - Closing
```

**Problem location**
`HostStoreTest.zkHostStoreTests`

**Suggestions for an improvement**
Fix the test.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Fixes sporadic failure in zkHostStoreTests.

**Purpose of the change**  
Fixes #3708.

**What the code does**  
PR #3682 introduced a call to `updateMap()` in `ZKHostStore:tryInit()` that internally triggers the listener used for testing purposes. Such a listener is used to ensure that an update to the host store is completed before performing any assertion/check in a test case; an example of this use case is `zkHostStoreTests`.

However, the fact that the new `updateMap()` call introduced PR #3682 triggers the listener in `ZKHostStore`, breaks the logic of `zkHostStoreTests`. The reason is that `zkHostStoreTests` uses a `CompletableFuture` that is assumed to be completed when the listener is triggered after executing `hostStore.updateHostContainersMap(hostContainerMap);`. As now the listener is triggered first by `ZKHostStore:tryInit()`, the `CompletableFuture` is actually completed before the call to `updateHostContainersMap` (that also triggers the listener). This poses a race condition that makes the test to fail sporadically, specially in Jenkins. 

As the listener is now triggered twice, we just added a second `CompletableFuture` for the test to wait for completion. By doing this, the test actually waits for `updateHostContainersMap` to complete and it passes.

**How to verify it**  
Executed 2 Jenkins builds in which this test has passed (before, it was persistently failing):
`21:20:41 io.pravega.controller.store.stream.HostStoreTest > zkHostStoreTests PASSED`
`21:32:10 io.pravega.controller.store.stream.HostStoreTest > zkHostStoreTests PASSED`

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java [hunk 1]
```diff
@@ -89,20 +89,27 @@ public void zkHostStoreTests() {
...
+                // With the addition of updateMap() in tryInit(), this listener is actually called twice, and we need to
+                // wait for the second operation to complete (related to updateHostContainersMap()).
+                if (latch1.isDone()) {
+                    latch2.complete(null);
+                }
+                latch1.complete(null);
             });
-            // Update host store map.
-            Map<Host, Set<Integer>> hostContainerMap = HostMonitorConfigImpl.getHostContainerMap(host, controllerPort, containerCount);
             hostStore.updateHostContainersMap(hostContainerMap);
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java]: A couple of clarification questions:
1- Does `updateHostContainersMap` trigger `tryInit`, and if not, which call actually triggers `tryInit`?
2- I understand that the addition of a second latch is dealing with with the second invocation of the listener, but the overall behavior looks strange, why is it that we need to invoke the listener twice in this scenario? Changing the underlying behavior is beyond the scope of this PR, but I'd rather not change a test case to comply with a bad behavior, so help me understand why we have this behavior in the first place.

Comment (RaulGracia) [reply controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java]: Let me address your questions:
1.- Yes, the invocation to `updateHostContainersMap` also includes a call to `tryInit()`, which now has a call to `updateMap()` that triggers the listener.
2.- Regarding the behavior that decides when to call the listener, it has been modified in PR #3682 by adding the call to `updateMap()` in `tryInit()`. That change induces an additional listener invocation (only the first time, when `zkInit=false`) to the one that is expected from the `NodeCache` object `hostContainerMapNode`. In this PR, we only deal with that behavior change in the test. If you prefer, we can modifying how listeners are invoked in `ZKHostStore`, but as far as I understand these listeners are only used for testing purposes (i.e., the behavior of the `ZKHostStore` should not be impacted when running Pravega). Please, let me know your preferred option.

Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/store/stream/HostStoreTest.java]: The listener is added in the code only for testing purposes.. 
and every time an update to the map happens, the listener notifies whoever is listening after the update..

The test makes an explicit update and expects a notification..

With new change of calling updatemap from tryInit, the there will be two notifications.. so the test should also expect two updates and hence two futures that should be completed
