### PR TITLE
Issue 2602:  create scope should not succeed when client sends no creds

### LINKED ISSUE #2602: GRPC client without credentials is able to create a scope
**Problem description**

When using the GRPC client, and Pravega controller is deployed with auth on, if the client doesn't send any credentials at all (as opposed to bad ones or ones that don’t have proper acls), the client is able to create a scope (then fails to create streams).

The problem doesn’t appear when creating a scope with REST.  There, missing credentials appropriately results in 401 when no credentials are provided.

**Problem location**

Controller (or segment store?)

**Suggestions for an improvement**

Bring the REST and GRPC authorization check in line such that in both cases a client is not able to create a scope without credentials.

### PR DESCRIPTION
**Pull request by arvindkandhare**
**Change log description**
When using the GRPC client, and Pravega controller is deployed with auth on, if the client doesn't send any credentials at all (as opposed to bad ones or ones that don’t have proper acls), the client is able to create a scope (then fails to create streams).
Missing creds/auth method should not allow the operation to continue.

**Purpose of the change**
Fixes #2602.

**What the code does**
If creds/auth method is not specified, does not allow the access.

**How to verify it**
Added unit test to verify this.

### CODE REVIEW

File: standalone/src/test/java/io/pravega/local/PartialSecurePravegaClusterTest.java [hunk 1]
```diff
@@ -24,6 +31,29 @@ public void setUp() throws Exception {
...
     }
 
+    /**
+     * Create the test stream.
+     *
+     * @throws Exception on any errors.
+     */
+    @Test
+    public void failingCreateTestStream()
+            throws Exception {
```
Comment (andreipaduroiu) [inline standalone/src/test/java/io/pravega/local/PartialSecurePravegaClusterTest.java]: I think this fits on the line above.
