### PR TITLE
Issue 1697: Change client background reconnect logic to be asynchronous 

### LINKED ISSUE #1697: Race condition related to late connection failure after a recent reconnect
**Problem description**
Race condition uncovered in system tests:
* The segment container is not ready. SSS on receiving a `SETUP_APPEND` throws an exception. But this may close the connection after the the connection has been established but `io.pravega.client.segment.impl.SegmentOutputStreamImpl#failConnection`the `retry indefinitely` completes. since the connection was established and an AppendSetup is returned.
* The client believes the connection is setup hence does not retry;  and the flush is still waiting for the latch to be released --> This causes the test thread to wait.

This is a bit complicated to fix because just adding the failConnection call may not do anything as the thread may still be running. But delaying the reconnect thread until after the inflight events have been sent blocks the thread and cause tests to fail which assume the reconnect logic runs in parallel.

**Problem location**
SegmentOutputStreamImpl

**Suggestions for an improvement**
Change the reconnect logic to use an Async loop that done not complete until the

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
* Fixes a race condition described in #1697. 
* Changes the reconnect logic to be asynchronous to avoid tying up a thread and allow it to maintain exponential backoff even with after connection re-establishment.

**Purpose of the change**
Fixes #1697 

**What the code does**
Creates a new class ReusableAsyncLatch which abstracts out the concept of having multiple futures waiting on a single state transition, and ensuring that one of them triggers the process that will result in the transition.

**How to verify it**
New tests are added to cover the new class and to reproduce the race condition. The later of which fails against master and is passing here.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -354,68 +341,73 @@ public void processingFailure(Exception error) {
...
-                    try {
-                        connection.send(cmd);
-                    } catch (Exception e) {
-                        state.failConnection(e);
-                        throw e;
-                    }
-                }
+    CompletableFuture<ClientConnection> initiateConnectionSetup() {
+        CompletableFuture<ClientConnection> future =  new CompletableFuture<>();
+        state.connectionSetup.runReleaserAndAwait(this::setupConnection, future);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: `setupConnection()` throwing a runtime exception will cause the method `runReleaserAndAwait` to thrown a run time exception too(i.e. the future will not be completed.). 
this will also result in getConnection() method throwing this runtimeException. i.e. its retry is not exercised, since it is not of type `ConnectionFailedException`.
Also, we retry indefinitely incase of a similar exception inside `io.pravega.client.segment.impl.SegmentOutputStreamImpl#failConnection`

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -354,70 +362,47 @@ public void processingFailure(Exception error) {
...
-                        connection.send(cmd);
-                    } catch (Exception e) {
-                        state.failConnection(e);
-                        throw e;
-                    }
-                }
-            }
-        }
+        CompletableFuture<ClientConnection> future =  new CompletableFuture<>();
+        state.setupConnection.runReleaserAndAwait(this::reconnect, future);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: This leads to a nested invocation of `runReleaserAndAwait` causing the  the infinite retry connect logic to be a no-op.

Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Good catch. I totally missed that. Fortunately the integ tests failed. 
Fixed.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 3]
```diff
@@ -121,7 +125,12 @@ private boolean isInflightEmpty() {
         }
 
         private void connectionSetupComplete() {
-            connectionSetup.release();
+            CompletableFuture<Void> toComplete;
+            synchronized (lock) {
+                toComplete = connectionSetupCompleted;
+            }
+            toComplete.complete(null);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: This could be null. Should we check against that?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 4]
```diff
@@ -455,25 +443,48 @@ public void flush() throws SegmentSealedException {
...
                                              t -> log.warn(writerId + " Failed to connect: ", t))
-                 .runInExecutor(() -> {
-                     if (!state.isClosed()) {
+                 .runAsync(() -> {
+                     if (state.isClosed() || state.isAlreadySealed()) {
+                         return CompletableFuture.completedFuture(null);
+                     }
+                     Preconditions.checkState(state.getConnection() == null);
+                     log.info("Fetching endpoint for segment {}", segmentName);
+                     return controller.getEndpointForSegment(segmentName).thenCompose((PravegaNodeUri uri) -> {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: You're executing this on the Executor on which `controller.getEndpointForSegment` was running. Is this acceptable? If this does significant sync work, then we might want to transfer it to our executor by calling `thenComposeAsync`

File: common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+    @GuardedBy("lock")
+    private Long runningThreadId;
+
+    public ReusableFutureLatch() {
+        released = false;
+    }
+
+    /**
+     * Supply a future to be notified when {@link #release(Object)} is called. If release has already been
+     * called, it will be compltedImmediatly.
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java]: completed immediately

File: common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+     * 
+     * @param toNotify The future that should be completed.
+     */
+    public void await(CompletableFuture<T> toNotify) {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java]: I wonder if `await` is the right name for this method. Just by looking at it, I'd expect the method to await the future (i.e., block sync until the future is done). Maybe rename it to `notify`?

Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ReusableFutureLatch.java]: If you do rename it, there's a few other related methods below that should be renamed too.
