### PR TITLE
Issue 6437: Fix flaky test EventProcessorGroupTest.testFailingCellShutdown

### LINKED ISSUE #6437: Fix flaky test EventProcessorGroupTest.testFailingCellShutdown fails intermittently
**Describe the bug**
Test EventProcessorGroupTest.testFailingCellShutdown fails intermittently with the following exception:

```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at io.pravega.controller.eventprocessor.EventProcessorGroupTest.testFailingCellShutdown(EventProcessorGroupTest.java:150)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
```

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Test EventProcessorGroupTest.testFailingCellShutdown used to fail intermittently with a mockito exception. Fixed this by removing the `Mockito.doThrow()` as the exception did not help with testing additional code paths in EventProccessorGroup.shutdown()

**Purpose of the change**  
Fixes #6437

**What the code does**  
Removed the doThrow() for reader.closeAt() since it was anyways not help with throwing an exception on `cell.awaitTerminated()`

**How to verify it**  
All tests should pass and EventProcessorGroupTest.testFailingCellShutdown should consistently pass.

### CODE REVIEW

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Please, let's validate in Jenkins that the problem does not appear again with various runs.

**Comment by pbelgundi** [comment]
> Please, let's validate in Jenkins that the problem does not appear again with various runs.

Submitted jobs: pravega-branch-builder/1764 and pravega-branch-builder/1765

**Comment by pbelgundi** [comment]
> > Please, let's validate in Jenkins that the problem does not appear again with various runs.
> 
> Submitted jobs: pravega-branch-builder/1768 and pravega-branch-builder/1769

In both above jobs all EventProcessorGroupTests completed successfully.

**Comment by pbelgundi** [comment]
Started 2 more test runs : _pravega-branch-builder/1770_ and _pravega-branch-builder/1771_ to make sure test does not fail intermittently.

**Comment by pbelgundi** [comment]
> Started 2 more test runs : _pravega-branch-builder/1770_ and _pravega-branch-builder/1771_ to make sure test does not fail intermittently.

Both runs completed successfully with any failures.

File: controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java [hunk 1]
```diff
@@ -139,15 +139,12 @@ public void testFailingSealReaderGroupInShutdown() throws CheckpointStoreExcepti
...
-    public void testFailingCellShutdown() throws CheckpointStoreException {
+    public void testShutdown() throws CheckpointStoreException {
         this.requestEventProcessors = system.createEventProcessorGroup(requestConfig, checkpointStore, rebalanceExecutor);
         requestEventProcessors.awaitRunning();
         assertTrue(requestEventProcessors.isRunning());
-
         Position mockReaderPosition = mock(Position.class);
         doReturn(ImmutableMap.of("reader1", mockReaderPosition)).when(checkpointStore).sealReaderGroup("host1", "scaleGroup");
-        String exceptionMsg = "Exception marking reader offline.";
-        doThrow(new RuntimeException(exceptionMsg)).when(reader).closeAt(any());
```
Comment (shrids) [inline controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java:150]: Do we need a seperate test where `reader.closeAt(..)` throws an exception ?

Comment (pbelgundi) [reply controller/src/test/java/io/pravega/controller/eventprocessor/EventProcessorGroupTest.java:150]: No we don't because even if reader.closeAt() throws an exception that does impact cell.awaitTerminated() and the code flow in the shutdown method.

**Review by RaulGracia — APPROVED** [review]

**Review by shrids — APPROVED** [review]
