### PR TITLE
Issue 3278: List Streams in scope

### LINKED ISSUE #3278: Add listStreams() method to the gRPC client
**Problem description**

The current implementation of the StreamManager for Java allows users to manage scopes and streams, but is missing an important method: listing streams. This is particularly useful when wanting to delete a scope that contains streams (this fails and streams need to be manually purged). There is a `.deleteStream()` method in the implementation but no methods to actually list out the current streams.

This is available to the REST API, but not to the Java gRPC-enabled client.

**Problem location**

`io.pravega.client.admin.impl.StreamManagerImpl`

**Suggestions for an improvement**

Add the following method to the implementation of the StreamManager for the Java client:

`streamManager.listStreams()`

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
Add listStreamsInScope api to `StreamManager` and `Controller Grpc`

**Purpose of the change**  
Fixed #3278 

**What the code does**  
This PR adds a new api to Controller client (grpc) and StreamManager interfaces. This is paginated api on controller client.

* `StreamManager` returns an iterator _I_ to the application.
* Controller client returns an async iterator _AI_ that _I_ builds upon. 
* Grpc returns a continuation token, which _AI_ uses to fetch next batch.

On the service side, instead of fetching all streams under scope, we fetch only a limited number of streams and use the last fetched stream as the continuation token. The streams in scope are added as a separate listing stored under a hierarchical znode formed of 2 digists + 4 digits. 
A continuation token is essentially a serialized integer that is broken into three parts - 
msb 2 bytes, middle 4 bytes and lsb 4 bytes. Stream references are stored as /01/2345/stream-6789. 
So effectively all streams under the scope are ordered by the stream position. Stream position is monotonically increasing and any new stream that is added to the scope will be done at a higher position.  
So now the continuation token basically signifies the position of last stream that was returned in previous iteration. 
And continuing from the continuation token, we simply retrieve next `limit` number of streams under the scope. 
Since the streams are stored under the aforesaid hierarchy, we start with all children of the `middle` part of continuation token and only include streams whose position is greater than token.
If we are not able to get `limit` number of streams from this, we go to the next higher available `middle` znode and fetch its children. If middle is exhausted, we increment the `msb` and repeat until we have found `limit` number of streams or reached the end. 

**How to verify it**  
unit tests added

### CODE REVIEW

File: client/src/main/java/io/pravega/client/admin/StreamManager.java [hunk 1]
```diff
@@ -105,6 +107,14 @@ public static StreamManager create(ClientConfig clientConfig) {
      */
     boolean createScope(String scopeName);
 
+    /**
+     * Gets a map of all streams in scope with their current configuration.
+     * 
+     * @param scopeName The name of the scope for which to list streams in.
+     * @return Map of Stream to Configuration for all streams in the scope. 
+     */
+    Map<Stream, StreamConfiguration> streamsInScope(String scopeName);
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply client/src/main/java/io/pravega/client/admin/StreamManager.java]: So this has been kept in parity with listStreams REST api where we return stream configuration.

Ideally we should also have additional information wrt stream that could be queried (like say stream status: active sealed etc) and we could have separate apis.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java [hunk 2]
```diff
@@ -75,6 +76,12 @@ public LocalController(ControllerService controller, boolean authorizationEnable
         });
     }
 
+    @Override
+    public CompletableFuture<Map<Stream, StreamConfiguration>> streamsInScope(String scopeName) {
+        return controller.listStreamsInScope(scopeName)
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java]: yes, i am thinking about what could be the best way. pagination has the problem that subsequent grpc call could land up on a different controller instance.
so we could use grpc-streaming for sending a stream of response. But the problem is on the store front at the moment. 
But the concern i have is on the server side. We get the entire list of streams from the underlying store within a scope. 
what we can do for now is to not return configuration as you have suggested in another comment and only return stream names. 
the client can call getStreamConfig api to retrieve config information.

[the remark this answers is not in the document]
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java]: Yes, fetching only Stream names will make it possible to retrieve many more objects in single request. Then, if the user needs more information about a specific Stream, s/he can execute an additional call (wondering if we would need to add a `getStreamConfig` call in `StreamManager` as well, or we could extend the `StreamInfo` object with the config/status of a Stream, or just rely on the REST API). Still, fetching only Stream names alleviates the problem, but does not completely removes it (what about having 50K streams in a scope and then execute `listStreamsInScope`?).

**Comment by shiveshr** [comment]
@tom @Raul I have incorporated pagination. Please review

File: client/src/main/java/io/pravega/client/admin/StreamManager.java [hunk 3]
```diff
@@ -105,6 +107,14 @@ public static StreamManager create(ClientConfig clientConfig) {
      */
     boolean createScope(String scopeName);
 
+    /**
+     * Gets an iterator for all streams in scope. 
+     * 
+     * @param scopeName The name of the scope for which to list streams in.
+     * @return Iterator of Stream to iterator over all streams in scope. 
+     */
+    Iterator<Stream> listStreamsInScope(String scopeName);
```
Comment (RaulGracia) [inline client/src/main/java/io/pravega/client/admin/StreamManager.java]: Exercising this call in an existing integration test would be great to assess the end to end functionality.

File: client/src/main/java/io/pravega/client/stream/impl/StreamsInScopeIterator.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+     * To mitigate this, we add streams to queue only if the token used in the request and existing value of token are same. 
+     * So if multiple getNext are concurrently called for same continuation token, the result from exactly one of them
+     * is processed and included while others are ignored because first one will update the token as well. 
+     */
+    @Override
+    public CompletableFuture<Stream> getNext() {
+        final Controller.ContinuationToken continuationToken = token.get();
+        return function.apply(continuationToken).thenApply(streamsInScope -> {
+            synchronized (lock) {
+                token.getAndUpdate(existing -> {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/StreamsInScopeIterator.java]: If you are inside of the lock, you don't need the getAndUpdate. You can just do:
```
            if (token.get() == continuationToken) {
                log.debug("Received the following data after calling the function {}", streamsInScope.getStreamsList());
                streams.addAll(streamsInScope.getStreamsList().stream()
                                             .map(x -> (Stream) new StreamImpl(x.getScope(), x.getStream()))
                                             .collect(Collectors.toList()));
                token.set(streamsInScope.getContinuationToken());
            }
```

File: client/src/main/java/io/pravega/client/admin/impl/StreamsIterator.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+/**
+ * This class is a wrapper over async iterator for iterating over streams.
+ * This is blocking wrapper on async iterator's getNext method which implements blocking hasNext and next methods of 
+ * iterator interface. 
+ * We have also made this class threadsafe but that has the drawback of blocking on asyncIterator's getNext within a lock. 
+ */
+@ThreadSafe
+@VisibleForTesting
+class StreamsIterator implements Iterator<Stream> {
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply client/src/main/java/io/pravega/client/admin/impl/StreamsIterator.java]: That is a good suggestion. I have added it for both iterator implementations. 
One being ContinuationToken based async iterator. Other being Sync Wrapper over async iterator.

File: client/src/main/java/io/pravega/client/admin/StreamManager.java (hunk 3 above)
Comment (shiveshr) [reply client/src/main/java/io/pravega/client/admin/StreamManager.java]: done. added new test called ScopeTest

File: client/src/main/java/io/pravega/client/stream/impl/StreamsInScopeIterator.java (hunk 4 above)
Comment (shiveshr) [reply client/src/main/java/io/pravega/client/stream/impl/StreamsInScopeIterator.java]: Addressed. In fact, generalized this class into a new Utility class called `ContinuationTokenAsyncIterator`

File: common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+
+/**
+ * This class is a wrapper over async iterator that implements java.util.Iterator interface.
+ * This is blocking wrapper on async iterator's getNext method which implements blocking hasNext and next methods of 
+ * iterator interface. 
+ * This class is threadsafe but that has the drawback of blocking on asyncIterator's getNext within a lock. 
+ */
+@ThreadSafe
+@VisibleForTesting
+public class BlockingAsyncIterator<T> implements Iterator<T> {
```
Comment (RaulGracia) [inline common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java]: Just to be on the safe side, would we need unit tests for checking the functionality of `BlockingAsyncIterator` and `ContinuationTokenAsyncIterator`?

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java [hunk 7]
```diff
@@ -245,7 +246,7 @@ Scope newScope(final String scopeName) {
             return Futures.failedFuture(StoreException.create(StoreException.Type.DATA_NOT_FOUND, scopeName));
         }
     }
-
+
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java]: Remove unnecessary spaces.

File: controller/src/main/java/io/pravega/controller/store/stream/Scope.java [hunk 8]
```diff
@@ -39,6 +44,35 @@
      */
     CompletableFuture<Void> deleteScope();
 
+    /**
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/Scope.java]: I don't understand these two API calls being added here. Why do we need to add `addStreamToScope` and `removeStreamFromScope` here for listing streams?

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+        this.function = function;
+        this.token = new AtomicReference<>(tokenIdentity);
+        this.queue = new LinkedBlockingQueue<>();
+    }
+
+    /**
+     * If multiple getNext are called concurrently it will result in multiple remote calls with
+     * same continuation token. This can mean same set of result can get added to the queue multiple times.
+     * To mitigate this, we add result to queue only if the token used in the request and existing value of token are same. 
+     * So if multiple getNext are concurrently called for same continuation token, the result from exactly one of them
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: So if there are more than one concurrent getNext calls and our queue was empty, then we had two options --
1. let concurrent function calls with same continuation token be made remotely and only include result from one such call
2. ensure exactly one `function` call is outstanding. 

I went with `1` where i let multiple `function` calls be made and handle the result and put only one result in the queue.

File: controller/src/main/java/io/pravega/controller/store/stream/Scope.java (hunk 8 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/Scope.java]: The reason we are doing this is so that we allow store to keep list of stream grouping separate from stream metadata for all streams. 
This allows us to break down list of streams such that we can group them and bring in a continuation token based logic. 

For example, in zookeeper based store, rest of the stream metadata is structured as /<scope>/<stream>
If we were to list all streams in scope, we only had the option of fetching all children of `/<scope>`. 
And if we had to restructure stream metadata into different sets, it would have been backward incompatible. 
So i simply introduced these new apis which allows `store` to group streams under scope which is optimal for listStreamsInScope. 
So the stream metadata continues to be under `/<scope>/<stream>` but stream identifiers are also stored under a new znode hierarchy `/streamsInScope/scope/<set>/<stream>->creationTime`. So all streams under the scope are now divided under these predetermined number of sets. 
So a listStreamsInScope starts from a continuation token (initially null/empty) from which it extracts set and last record identifier. 
So when we do getChildren on `/streamsInScope/scope/<set>` we fetch an order of magnitude smaller number of streams in one query. And only take the limited number of entries that are ahead of continuation token. 
If we found less than `limit` number of entries from one set, we move to the next set. so on and so forth.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: this is what the code will look like:

```
    @GuardedBy("lock")
    private CompletableFuture<Void> outstanding;

    @Override
    public CompletableFuture<U> getNext() {
        final T continuationToken;
        synchronized (lock) {
            // if the result is available, return it without making function call
            if (!queue.isEmpty()) {
                return CompletableFuture.completedFuture(queue.poll());
            } else {
                continuationToken = token.get();
                // make the function call if previous outstanding call completed.
                if (outstanding.isDone()) {
                    outstanding = function.apply(continuationToken)
                            .thenAccept(resultPair -> {
                                synchronized (lock) {
                                    if (token.get().equals(continuationToken)) {
                                        log.debug("Received the following collection after calling the function: {} with continuation token: {}",
                                                resultPair.getValue(), resultPair.getKey());
                                        queue.addAll(resultPair.getValue());
                                        token.set(resultPair.getKey());
                                    }
                                }
                            }).whenComplete((x, e) -> {
                                              if (e != null) {
                                                  log.warn("Async iteration failed: ", e);
                                              }
                                          });
                }
            }
        }

        return outstanding.thenCompose(v -> getNext());
    }
```

[the remark this answers is not in the document]
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: I have made the change. The only thing is we call a method under a lock. And this method is supplied by an external entity to this class. So we dont know how long it will take or what it will do while under the lock before it returns the future. 
I am thinking i can improve that aspect though. I will try and update the code and see if it helps.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+        final T continuationToken;
+        synchronized (lock) {
+            // if the result is available, return it without making function call
+            if (!queue.isEmpty()) {
+                return CompletableFuture.completedFuture(queue.poll());
+            } else {
+                continuationToken = token.get();
+                // make the function call if previous outstanding call completed.
+                if (outstanding.isDone()) {
+                    // We are making this call under the lock!
```
Comment (fpj) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Ok, now I understand what you meant in your first response. It does look odd to hold a lock while making this call given that we are returning a future. In your previous implementation, you were not duplicating elements, but possibly duplicating calls for a given continuation token. My concern was with the high-level semantics of the iterator and not so much the efficiency of the implementation.

My preference is that we do not hold the lock for this call, but at the same time, I think we should return a future without waiting on this call. Would it be possible?

If this is getting unnecessarily complicated, we can perhaps create an issue to optimize this later.

File: controller/src/main/java/io/pravega/controller/store/stream/Scope.java (hunk 8 above)
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/Scope.java]: This observation made me thing of the hierarchical ledger manager scheme we introduced in BK to solve precisely this problem, see Hierarchical Ledger Manager here:

https://bookkeeper.apache.org/docs/4.5.0/getting-started/concepts/

Can we apply this concept of a hierarchy based on ID here?

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 11]
```diff
@@ -125,7 +125,8 @@ public OperationContext createContext(String scope, String name) {
                                                    final Executor executor) {
         return getSafeStartingSegmentNumberFor(scope, name)
                 .thenCompose(startingSegmentNumber ->
-                    withCompletion(getStream(scope, name, context).create(configuration, createTimestamp, startingSegmentNumber), executor));
+                    withCompletion(getStream(scope, name, context).create(configuration, createTimestamp, startingSegmentNumber)
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: So that I understand, this is adding a new stream twice: once under `scope/` and another under `scope/<set>`?

If so, is there a risk of inconsistencies, like when I'm deleting a stream and I get a concurrent list streams in scope?

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 10 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: One of the hacky alternatives i could think of was something along these lines:
```
                    outstanding = CompletableFuture.runAsync(() -> {}).thenCompose(x -> function.apply(continuationToken)
                            .thenAccept(resultPair -> {
```

This hack will return a future immediately while running the chained callbacks on an external thread.
If we had our executor, we could have scheduled this on our executor. and in its absence it will go to forkjoinpool. 
But it takes ticks all the boxes.. does not make multiple remote calls for same continuation token.. neither does it hold the lock while making a remote call.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 11 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: so delete will "eventually" delete both records. 
So while listing streams, if a delete is happening, its a simple race.. either we retrieve the record under `scope/<set>` before it is deleted or we dont retrieve it. 
Either way we return a list of streams where any of these streams could be deleted as we are delivering these records to the caller. 

There is more nuance in stream creation actually.
we first create stream under `scope` then we add stream to `scope/<set>`. So any partially created stream is not listed by `listStreamsInScope` method. 
Only after streams metadata are created completely does the stream become eligible for listing.
the drawback is, someone could list streams and not find a partially created stream.. attempt to create stream by that name and get a response `EXISTS_CREATING`. 

```
    public enum CreateStatus {
        NEW,
        EXISTS_CREATING,
        EXISTS_ACTIVE,
        FAILED
    }
```

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 10 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: I think there is a simple way we can achieve what we desire.. updating the code. Please take a look

File: controller/src/main/java/io/pravega/controller/store/stream/Scope.java (hunk 8 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/Scope.java]: this looks good too. I will make the change to incorporate this. it will take care of several nuances for us. 
the only thing is we will need to store this "path" under stream's metadata too which is not necessarily a problem.. but adds another step in stream creation and its handling for failures.. 

And well its a neat idea that takes care of some nuances with the current scheme.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+
+@ThreadSafe
+@Slf4j
+/**
+ * This is a continuation token based async iterator implementation. This class takes a function that when completed will 
+ * have next batch of results with continuation token. 
+ * This class determines when to call the next iteration of function (if all existing results have been exhausted) and 
+ * ensures there is only one outstanding call. 
+ */
+public class ContinuationTokenAsyncIterator<T, U> implements AsyncIterator<U> {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Please use more specific names for the type args. `T` and `U` are not very indicative.
Also, doesn't checkstyle complain about not having `@param` args for these type params?

File: common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java [hunk 13]
```diff
@@ -0,0 +1,68 @@
...
+    private final AsyncIterator<T> asyncIterator;
+    private T next;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java]: GuardedBy("$lock")

File: common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java [hunk 14]
```diff
@@ -0,0 +1,68 @@
...
+    private boolean canHaveNext;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java]: GuardedBy("$lock")

File: common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java [hunk 15]
```diff
@@ -0,0 +1,68 @@
...
+    public BlockingAsyncIterator(AsyncIterator<T> asyncIterator) {
+        this.canHaveNext = true;
+        this.next = null;
+        this.asyncIterator = asyncIterator;
+    }
+
+    @Synchronized
+    private void load() {
+        if (next == null && canHaveNext) {
+            next = asyncIterator.getNext().join();
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java]: Waiting on a future while holding a lock is never a good idea. Here's my suggestion for avoiding this:
- make `next` a `CompletableFuture<T>` and still guard it by a lock
- In this method
    - While holding the lock, check `next` for null, and if so, then set it to `asyncInterator.getNext()` (no `join`)
    - After releasing the lock, invoke `join` on `next` and inspect its result.

You may have to do a bit more bookkeeping (in this method) to track whether you actually invoked `getNext` or not.

I think you can also get rid of `canHaveNext`. If `next` is completed (it should always be once this method exits), if its contents is `null`, then `hasNext()` should return `false` and `next()` should throw.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 16]
```diff
@@ -0,0 +1,110 @@
...
+    private final Object lock = new Object();
+    @GuardedBy("lock")
+    @VisibleForTesting
+    @Getter(AccessLevel.PACKAGE)
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: The Lombok getter is not thread safe. Write your own getter where you take care of this.

Also you should make a copy of it in your getter. Even if you return the reference to the queue, the contents can still be iterated and/or modified externally, without holding the lock.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 17]
```diff
@@ -0,0 +1,110 @@
...
+    private final Queue<U> queue;
+    @GuardedBy("lock")
+    @VisibleForTesting
+    @Getter(AccessLevel.PACKAGE)
+    private final AtomicReference<T> token;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Why do you have an `AtomicReference` that is guarded by a synchronized lock?

And why do you expose the whole `AtomicReference` to the outside via a getter? You should have explicit methods that access only its contents.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 18]
```diff
@@ -0,0 +1,110 @@
...
+    private final Function<T, CompletableFuture<Map.Entry<T, Collection<U>>>> function;
+    @GuardedBy("lock")
+    private CompletableFuture<Void> outstanding;
+    private final AtomicBoolean canContinue;
+    private final AtomicBoolean isOutstanding;
+    
+    public ContinuationTokenAsyncIterator(Function<T, CompletableFuture<Map.Entry<T, Collection<U>>>> function, T tokenIdentity) {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: 1. Check for nulls in the args.
2. Javadoc for constructor

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 19]
```diff
@@ -0,0 +1,110 @@
...
+        this.isOutstanding = new AtomicBoolean(false);
+    }
+
+    @Override
+    public CompletableFuture<U> getNext() {
+        final T continuationToken;
+        boolean toCall = false;
+        synchronized (lock) {
+            // if the result is available, return it without making function call
+            if (!queue.isEmpty()) {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: So you check this queue here and if it's not empty, you return the first element, else you invoke the function and add to the queue and reinvoke this method.

I think you can greatly simplify this class by removing the queue altogether and invoking your function (in a loop, maybe) and returning the result. You can also get rid of a few other fields as well.

File: common/src/test/java/io/pravega/common/util/IteratorTest.java [hunk 20]
```diff
@@ -0,0 +1,163 @@
...
+import java.util.stream.IntStream;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertNull;
+import static org.junit.Assert.assertTrue;
+import static org.mockito.Mockito.atLeast;
+import static org.mockito.Mockito.spy;
+import static org.mockito.Mockito.verify;
+
+public class IteratorTest {
```
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/util/IteratorTest.java]: This should be named `ContinuationTokenIteratorTest`

File: client/src/main/java/io/pravega/client/stream/impl/Controller.java [hunk 21]
```diff
@@ -42,6 +44,14 @@
      */
     CompletableFuture<Boolean> createScope(final String scopeName);
 
+    /**
+     * Gets an async iterator on streams in scope.
+     *
+     * @param scopeName The name of the scope for which to list streams in.
+     * @return A future which when completed will contain an iterator for all Streams in the scope.
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/Controller.java]: This does not return a future.

File: controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java [hunk 22]
```diff
@@ -189,6 +190,19 @@
...
 
+    /**
+     * List existing streams in scopes with pagination. This api continues listing streams from the supplied continuation token
+     * and returns a count limited list of streams and a new continuation token.
+     *
+     * @param scopeName Name of the scope
+     * @param continuationToken continuation token
+     * @param limit limit on number of streams to return.
+     * @param executor 
+     * @return A map of streams in scope to their configurations
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java]: This does not return a map

File: common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java (hunk 15 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/BlockingAsyncIterator.java]: Actually this class is supposed to implement java.util Iterator interface that we can give out to applications so they know what to do with it.
It’s used in streamManager class.

That’s why it has canhavenext implementation and all the future.join under a lock

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 16 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: The getter is only for testing.. that’s why it’s only at package level.. I will write my own getter

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 17 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Atomic reference and queue are guarded by lock because we want to do atomic updates to both those fields while under the lock.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 19 above)
Comment (shiveshr) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Actually the whole idea is that each  function call can give you a bunch of results. 
We only want income function again once we exhaust all available results. 
Hence the whole queue logic.
If it was retrieving one element at a time, we would have called getNext in a loop. 

Also we have  supported concurrent getNext calls on the same async iterator. Which would hard to achieve with a future.loop call

File: common/src/test/java/io/pravega/common/util/IteratorTest.java (hunk 20 above)
Comment (shiveshr) [reply common/src/test/java/io/pravega/common/util/IteratorTest.java]: This has test for both blockingIterator and continuationtoken iterator

**Comment by shiveshr** [comment]
@andreipaduroiu thanks for the comments. I have addressed/replied to the comments.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java (hunk 19 above)
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: Ok, I missed the `addAll`. I thought it was just `add`.

File: common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java [hunk 23]
```diff
@@ -0,0 +1,129 @@
...
+ * have next batch of results with continuation token. 
+ * This class determines when to call the next iteration of function (if all existing results have been exhausted) and 
+ * ensures there is only one outstanding call. 
+ */
+public class ContinuationTokenAsyncIterator<Token, T> implements AsyncIterator<T> {
+    private final Object lock = new Object();
+    @GuardedBy("lock")
+    private final Queue<T> queue;
+    @GuardedBy("lock")
+    private final AtomicReference<Token> token;
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ContinuationTokenAsyncIterator.java]: If you guard it by a lock there is no need to use an `AtomicReference`. It just adds overhead. Make the field non-final and only access it under the lock; it's the same with less overhead.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 24]
```diff
@@ -37,16 +72,207 @@ public String getName() {
...
+            if (top >= floor.getMsb()) {
+                String topPath = ZKPaths.makePath(streamsInScopePath, topChild);
+                // set middle floor = supplied floor OR 0 if top floor has been incremented
+                int middleFloor = top == floor.getMsb() ? floor.getMiddle() : 0;
+
+                // compute on all available middle level children (0-9999) of current top level that are greater than middle floor
+                CompletableFuture<Void> voidCompletableFuture = computeOnChildren(topPath, middleChild -> {
+                    final int middle = Integer.parseInt(middleChild);
+                    if (middle >= middleFloor) {
+                        String middlePah = ZKPaths.makePath(topPath, middleChild.toString());
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: Typo in `middlePath`.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 25]
```diff
@@ -37,16 +72,207 @@ public String getName() {
...
+        return Integer.parseInt(x.substring(x.length() - 4, x.length()));
     }
 
     @Override
     public CompletableFuture<List<String>> listStreamsInScope() {
         return store.getChildren(scopePath);
     }
 
+    @Override
+    public CompletableFuture<Pair<List<String>, String>> listStreamsInScope(int limit, String continuationToken, Executor executor) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: I haven't reviewed this logic carefully, but my suggestion is that we add more comments here to make it easier to follow what it is trying to do. In particular, I'd like to understand how this is paginating.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 26]
```diff
@@ -37,16 +72,207 @@ public String getName() {
...
+    }
+
+    private CompletableFuture<Void> computeOnChildren(String path, Function<String, CompletableFuture<Boolean>> function,
+                                                      Executor executor) {
+        return store.getChildren(path)
+                    .thenCompose(children -> {
+                        AtomicInteger index = new AtomicInteger(0);
+                        AtomicBoolean canContinue = new AtomicBoolean(true);
+                        return Futures.loop(canContinue::get,
+                                () -> function.apply(children.get(index.get())).thenAccept(canCont -> {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: It is odd that we have `canContinue` and `canCont`, can we find better names?

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java [hunk 27]
```diff
@@ -122,6 +124,7 @@
         committingTxnsPath = String.format(COMMITTING_TXNS_PATH, scopeName, streamName);
         waitingRequestProcessorPath = String.format(WAITING_REQUEST_PROCESSOR_PATH, scopeName, streamName);
         markerPath = String.format(MARKER_PATH, scopeName, streamName);
+        idPath = String.format(ID_PATH, scopeName, streamName);
         currentEpochRecordPath = String.format(CURRENT_EPOCH_RECORD, scopeName, streamName);
         epochRecordPathFormat = String.format(EPOCH_RECORD, scopeName, streamName) + "/%d";
         historyTimeSeriesChunkPathFormat = String.format(HISTORY_TIMESERES_CHUNK_PATH, scopeName, streamName) + "/%d";
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java]: There is a typo in `TIMESERIES`.

File: controller/src/main/java/io/pravega/controller/util/Config.java [hunk 28]
```diff
@@ -30,10 +30,10 @@
 @Slf4j
 public final class Config {
     private final static com.typesafe.config.Config CONFIG = ConfigFactory.defaultApplication()
-            .withFallback(ConfigFactory.defaultOverrides().resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true)))
-            .withFallback(ConfigFactory.systemEnvironment())
-            .withFallback(ConfigFactory.defaultReference())
-            .resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true));
+                                                                          .withFallback(ConfigFactory.defaultOverrides().resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true)))
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/util/Config.java]: Let's undo the changes in this file, please.

File: controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java [hunk 29]
```diff
@@ -65,10 +68,12 @@
     protected static final String SCOPE3 = "scope3";
     protected static final String STREAM1 = "stream1";
     protected static final String STREAM2 = "stream2";
+    protected static final String STREAM3 = "stream3";
 
     //Ensure each test completes within 10 seconds.
     @Rule
-    public final Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
+    // TODO: shivesh
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java]: I don't know what this TODO is, sounds like you forgot to address it.

File: client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java [hunk 30]
```diff
@@ -68,7 +74,7 @@ public void testCreateAndDeleteScope() {
         Assert.assertFalse(streamManager.deleteScope(defaultScope));
     }
 
-    @Test(timeout = 5000)
+    @Test(timeout = 15000)
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java]: the test timed out for me couple of times during local run, and 5 seconds was too less.. so i had increased its timeout.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java (hunk 27 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java]: fixed

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java [hunk 31]
```diff
@@ -72,7 +72,8 @@
 
     //Ensure each test completes within 10 seconds.
     @Rule
-    public Timeout globalTimeout = new Timeout(30, TimeUnit.SECONDS);
+    // TODO: shivesh
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: that was on an outdated change set (i had already removed that todo).
i add todos when i increase test timeouts for testing under debugger and clean them up after completing the testing.. this may have slipped into a commit.

File: client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java (hunk 30 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java]: this test was failing for me with timedout exception quite regularly. and increasing the timeout fixed it.

[the remark this answers is not in the document]
Comment (fpj) [reply client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java]: The question is whether this was failing before the changes here. If it wasn't, then it might not be a simple issue of increasing the time out.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 32]
```diff
@@ -37,16 +72,207 @@ public String getName() {
...
+
+    private String getPathForStreamPosition(String name, int streamPosition) {
+        Preconditions.checkArgument(streamPosition >= 0);
+        Token token = new Token(streamPosition);
+
+        // root path represents most significant 2 digits of the position.
+        String root = ZKPaths.makePath(streamsInScopePath, token.getMsb().toString());
+        // container path represents most significant 3rd to 6th digits of the position.
+        String container = ZKPaths.makePath(root, token.getMiddle().toString());
+        // the path is composed of stream name followed by last 4 chars that represent least significant 4 digits of the position.
```
[the remark this answers is not in the document]
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: Do we need this unique id for anything? Could we, for example, hash the stream name and use a prefix of the digits? It is fine if there is a collision on the hash because for pagination purposes, we are grouping streams anyway. It is a different story in the case you need the id for something else.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 33]
```diff
@@ -37,16 +72,207 @@ public String getName() {
 
     @Override
     public CompletableFuture<Void> deleteScope() {
-        return store.deleteNode(scopePath);
+        return store.deleteNode(scopePath)
+                    .thenCompose(v -> Futures.exceptionallyExpecting(store.deleteTree(counterPath), DATA_NOT_FOUND_PREDICATE, null))
+                    .thenCompose(v -> Futures.exceptionallyExpecting(store.deleteTree(streamsInScopePath), DATA_NOT_FOUND_PREDICATE, null));
+    }
+
+    CompletableFuture<Void> addStreamToScope(String name, int streamPosition) {
```
[the remark this answers is not in the document]
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: I asked below whether we can do this with hashing the stream name, in which case, we don't need the sequential znode.

But, I'm also concerned about this use of a sequential znode. Which new sequential znode you create is a new child to the same parent, so this is limiting us to have at most 1 million streams. It is pretty large number, but it might be unnecessarily capping the number of streams we can have.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java [hunk 34]
```diff
@@ -622,4 +625,16 @@ String getActiveTxPath(final int epoch, final String txId) {
...
+    CompletableFuture<Void> createStreamIdIfAbsent(int id) {
+        byte[] b = new byte[Integer.BYTES];
+        BitConverter.writeInt(b, 0, id);
+
+        return Futures.toVoid(store.createZNodeIfNotExist(idPath, b));
+    }
+    
+    CompletableFuture<Integer> getStreamId() {
+        return store.getData(idPath)
+                .thenApply(data -> BitConverter.readInt(data.getData(), 0));
```
[the remark this answers is not in the document]
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java]: I see, so you need this reference id for deletion.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 35]
```diff
@@ -37,16 +72,245 @@ public String getName() {
...
     }
 
     @Override
     public CompletableFuture<List<String>> listStreamsInScope() {
         return store.getChildren(scopePath);
     }
 
+    @Override
+    public CompletableFuture<Pair<List<String>, String>> listStreams(int limit, String continuationToken, Executor executor) {
+        // Stream references are stored under a hierarchy of nodes as described in `addStreamsInScope method.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: Missing  closing `.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 36]
```diff
@@ -37,16 +72,245 @@ public String getName() {
...
         return store.getChildren(scopePath);
     }
 
+    @Override
+    public CompletableFuture<Pair<List<String>, String>> listStreams(int limit, String continuationToken, Executor executor) {
+        // Stream references are stored under a hierarchy of nodes as described in `addStreamsInScope method. 
+        // A continuation token is essentially a serialized integer that is broken into three parts - 
+        // msb 2 bytes, middle 4 bytes and lsb 4 bytes. 
+        // stream references are stored as /01/2345/stream-6789. 
+        // So effectively all streams under the scope are ordered by the stream position. Stream position is monotonically
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: It is strictly increasing, not only monotonically increasing, right?

File: client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java (hunk 30 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply client/src/test/java/io/pravega/client/admin/impl/StreamManagerImplTest.java]: yes, sporadically.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java [hunk 37]
```diff
@@ -37,16 +72,245 @@ public String getName() {
...
+        // So effectively all streams under the scope are ordered by the stream position. Stream position is monotonically 
+        // increasing and any new stream that is added to the scope will be done at a higher position. 
+        // Streams can be deleted though. 
+        // So now the continuation token basically signifies the position of last stream that was returned in previous iteration. 
+        // And continuing from the continuation token, we simply retrieve next `limit` number of streams under the scope. 
+        // Since the streams are stored under the aforesaid hierarchy, we start with all children of the `middle` part of 
+        // continuation token and only include streams whose position is greater than token.
+        // If we are not able to get `limit` number of streams from this, we go to the next higher available `middle` znode 
+        // and fetch its children. If middle is exhausted, we increment the `msb` and repeat until we have found `limit` 
+        // number of streams or reached the end.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: Thanks for the description, it makes it very clear. I'm now wondering if it would simplify significantly the logic changing the way we determine what stream names to return. What if instead of making it based on a `limit` number of streams, we use the second level of the hierarchy? For example:

- We first return the streams under `00/0000` and continuation token is `00/0001`.
- We second return the streams under `00/0001` and continuation token is `00/0002`
- And so on

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: > But, I'm also concerned about this use of a sequential znode. Which new sequential znode you create is a new child to the same parent, so this is limiting us to have at most 1 million streams. It is pretty large number, but it might be unnecessarily capping the number of streams we can have.

We are capping the number of streams under a scope to a 10 digit number. Which is essentially Integer.Max ==> 2 billion.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java (hunk 32 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: we store this unique id for when we attempt to delete the stream, we should know where we will find it.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java (hunk 37 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: Streams can be deleted too.. So some of these nodes may only have a very small number of streams. 
And returning from multiple nodes in one query is fine because a) its not complex b) new streams can only be added in a strictly increasing fashion

File: controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: PS: my original implementation was based on a hashing scheme itself.. but that had several nuances. This hierarchy approach is much cleaner and has monotonically increasing stream position so continuation token is fairly straightforward. only caveat is to store the stream position for deletion.

[the remark this answers is not in the document]
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: I don't think this is right. In `getNextStreamPosition`, we are creating a sequential znode under the same parent. Each time we do that, it will create a new znode with an incremented value appended to the name. There is a limit on the number of children of a parent znode, which is 1 million. I think your 2 billion reference is talking about the ids, while I'm talking about the number of children under a parent znode.

[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKScope.java]: The counter is an ephemeral sequential znode. 
But yes, theoretically we can have more than a million concurrent ephemeral znodes under the same scope. So i could delete the counter ephemeral node immediately after i create it.
