### PR TITLE
Issue 2543: Segment range mismatch between auto scale request and range in metadata store

### LINKED ISSUE #2543: Hot segment not scaling due to input mismatch
**Problem description**
In our scaling test with a variable event rate on a stream with event-rate triggered scaling policy we observe one of the segment (number 4604) not being scaled up despite being hot:
midscale_7d

The controller logs have a repeating error of the kind:
```
2018-05-03 14:36:57,946 675370275 [controllerpool-44] ERROR i.p.c.s.stream.PersistentStreamBase - scale input invalid [4604] [0.1706574888245243=0.4395872725666938, 0.4395872725666938=0.7085170563088632]
2018-05-03 14:36:57,946 675370275 [controllerpool-44] WARN  i.p.c.s.e.r.ScaleOperationTask - processing scale request for hulk/midScale segments [4604] failed {}
io.pravega.controller.store.stream.ScaleOperationExceptions$ScaleInputInvalidException: null
    at io.pravega.controller.store.stream.PersistentStreamBase.lambda$null$69(PersistentStreamBase.java:489)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.pravega.controller.store.stream.ZKStoreHelper.lambda$null$8(ZKStoreHelper.java:156)
    at io.pravega.controller.store.stream.ZKStoreHelper.lambda$callback$24(ZKStoreHelper.java:326)
    at org.apache.curator.framework.imps.Backgrounding$1$1.run(Backgrounding.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
2018-05-03 14:36:57,946 675370275 [controllerpool-72] WARN  i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed java.util.concurrent.CompletionException
2018-05-03 14:36:57,951 675370280 [controllerpool-72] ERROR i.p.c.e.i.ConcurrentEventProcessor - ConcurrentEventProcessor Processing failed, exiting {}
java.util.concurrent.CompletionException: io.pravega.controller.store.stream.ScaleOperationExceptions$ScaleInputInvalidException
    at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
    at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
    at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
    at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
    at io.pravega.controller.eventProcessor.impl.SerializedRequestHandler.lambda$run$1(SerializedRequestHandler.java:94)
...
```
The scaling-events API reports this segment as `{"number":4604,"epoch":3007,"start":1525197396380,"keyStart":0.1706574888245243,"keyEnd":0.7085170563088633}`,
so the key end is 
`0.7085170563088632` in the logs, but 
`0.7085170563088633` when reported by the controller API. 

**Problem location**
Controller

**Suggestions for an improvement**
There should be no input mismatch when processing a segment key range

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh <shivesh.ranjan@gmail.com>

**Change log description**
We observed that there was a mismatch between range posted in auto-scale event and the range present in metadata store. This led to scale input being declared invalid and hence hot segment was never scaled. 

**Purpose of the change**
Fixes #2543

**What the code does**
In autoscale task, to compute new ranges we actually did some computations using `double` which can cause precision loss and hence the ranges submitted in scale input did not match that in the metadata store.

The way we were earlier doing new range computation was as follows:
e.g. compute range for a segment S split in 2
```
delta = (s.keyEnd - s.keyStart)/2;
newRanges = [s.keystart, s.keyStart + delta) [s.keyStart + delta, s.keyStart + 2*delta)
```
Now mathematically, `s.keyStart+ 2*delta = s.keyStart + 2 * (s.keyEnd - s.keyStart)/2 = s.keyEnd`
However, since the computations are done using double, there could be precision errors causing last value to mismatch. 
So as a fix, we always use the last value as key.end rather than the computation. Elsewhere the computation is fine, because to each new subsequent segment getting created we supply the same value. 
 
We also thought the issue could have been induced by Java serialization of double causing some precision loss. So we have used the same approach that we use in metadata store where we serialize doubles by converting them to long. 
So now we have changed the ScaleOpEvent to internally use a long instead of double. Only the accessors are changed to take and return double. But the field stores a long so the serialization will serialize and deserialize long which does not suffer from precision problems. 

**How to verify it**
Issue should be fixed

### CODE REVIEW

**Comment by shiveshr** [comment]
[Bug: Hot segment not scaling due to input mismatch](https://trello.com/c/8zsPTP7F/39-bug-hot-segment-not-scaling-due-to-input-mismatch)

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java [hunk 1]
```diff
@@ -9,24 +9,40 @@
...
+        this.stream = stream;
+        this.segmentsToSeal = segmentsToSeal;
+        this.newRanges = newRange.stream()
+                .map(x -> new AbstractMap.SimpleEntry<>(Double.doubleToRawLongBits(x.getKey()), Double.doubleToRawLongBits(x.getValue())))
+                .collect(Collectors.toList());
+        this.runOnlyIfStarted = runOnlyIfStarted;
+        this.scaleTime = scaleTime;
+    }
+
+    public List<AbstractMap.SimpleEntry<Double, Double>> getNewRanges() {
```
Comment (fpj) [inline shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: I don't see this method used or tested anywhere.

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java [hunk 2]
```diff
@@ -9,24 +9,40 @@
...
 
 @Data
-@AllArgsConstructor
 public class ScaleOpEvent implements ControllerEvent {
     private static final long serialVersionUID = 1L;
     private final String scope;
     private final String stream;
     private final List<Integer> segmentsToSeal;
-    private final List<AbstractMap.SimpleEntry<Double, Double>> newRanges;
+    private final List<AbstractMap.SimpleEntry<Long, Long>> newRanges;
```
Comment (andreipaduroiu) [inline shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: `Map.Entry`?

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java [hunk 3]
```diff
@@ -9,24 +9,40 @@
...
     private final boolean runOnlyIfStarted;
     private final long scaleTime;
 
+    public ScaleOpEvent(String scope, String stream, List<Integer> segmentsToSeal, List<AbstractMap.SimpleEntry<Double, Double>> newRange, boolean runOnlyIfStarted, long scaleTime) {
+        this.scope = scope;
```
Comment (andreipaduroiu) [inline shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: I suggest adding argument checks. This will help avoiding downstream errors and catching problems early.

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java (hunk 1 above)
Comment (andreipaduroiu) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: This looks similar to some code in the constructor. Should we invoke it from there?

Comment (shiveshr) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: I thought the issue was because of serialization and deserialization using JavaSerializer causing precision loss. 
but i was wrong. I am able to reproduce it and found the problem source.

Comment (shiveshr) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: @andreipaduroiu constructor takes double and converts it to long.
getter converts the field from long back into double and returns it.

So the contract for callers appears to be `double` but the field stores `long`

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java (hunk 2 above)
Comment (shiveshr) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: That will mean changing signatures of methods where these values are used which expects it to be AbstractMap.SimpleEntry.

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java (hunk 3 above)
Comment (shiveshr) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: Will address it in a separate issue. #2554

File: shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java (hunk 1 above)
Comment (fpj) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: @shiveshr 

> I thought the issue was because of serialization and deserialization using JavaSerializer causing precision loss. I am not sure if that can be an issue though, so this is a safe fix that has been put inhere.
>
> Also, I am able to reproduce the issue and have been able to identify the real source of problem.
The real fix for the problem observed is in AutoScaleTask.java and we have a corresponding unit test added too.

This is not really answering my question, why are we adding a method that we aren't using anywhere?

Comment (shiveshr) [reply shared/controller-api/src/main/java/io/pravega/shared/controller/event/ScaleOpEvent.java]: This method It is being used to take scale inputs to start the scale workflow. 
The method signature of the getter has been kept identical to earlier, while the field is changed from a map<double, double> to map<long, long>
