### PR TITLE
Issue 1606: Tier2 filesystem implementation should not treat AccessDeniedException as SegmentSealedException

### LINKED ISSUE #1606: Tier2 filesystem implementation should not treat AccessDeniedException as SegmentSealedException always
**Problem description**
Tier2 filesystem implementation converts all `AccessDeniedException` to `SegmentSealedException`. This should be done according to the context and a different exception should be thrown in case.

**Problem location**
`Storage` contract and `FileSystemStorage` implementation.

**Suggestions for an improvement**
Define an exception if required which covers this case and update the contract and implementation.

### PR DESCRIPTION
**Pull request by arvindkandhare**
**Change log description**
Translate AccessControlException to StreamSegmentSealedException and let AccessDeniedException fall through.

**Purpose of the change**
Streamsegmentstore should not translate the AccessDeniedException.

Fixes #1606 

**What the code does**
Translate AccessControlException to StreamSegmentSealedException and let AccessDeniedException fall through.

**How to verify it**

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java [hunk 1]
```diff
@@ -429,7 +429,7 @@ private Throwable translateException(String segmentName, Throwable e) {
             retVal = new ArrayIndexOutOfBoundsException(e.getMessage());
         }
 
-        if (e instanceof AccessDeniedException) {
+        if (e instanceof AccessControlException) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java]: I'm not sure this is correct because of the following argument:

`S3JerseyClient` requests invoke this method to execute requests:

https://github.com/EMCECS/ecs-object-client-java/blob/master/src/main/java/com/emc/object/s3/jersey/S3JerseyClient.java#L719

`executeRequest` invokes this method `ErrorFilter.parseErrorResponse`:

https://github.com/EMCECS/ecs-object-client-java/blob/master/src/main/java/com/emc/object/s3/jersey/ErrorFilter.java#L104

which returns an `S3Exception` with the HTTP status code:

https://github.com/EMCECS/ecs-object-client-java/blob/master/src/main/java/com/emc/object/s3/jersey/ErrorFilter.java#L141

As such, I don't think this exception handling here is correct.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java [hunk 2]
```diff
@@ -409,7 +409,7 @@ private Throwable translateException(String segmentName, Throwable e) {
             retVal = new IllegalArgumentException(e.getMessage());
         }
 
-        if (e instanceof AccessDeniedException) {
+        if (e instanceof AccessControlException) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java]: I'm not sure this is correct either, if we check the code for openjdk, there is no `AccessControlException` being thrown:

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/nio/fs/UnixException.java?av=f#77

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java [hunk 3]
```diff
@@ -412,15 +411,19 @@ private Throwable translateException(String segmentName, Throwable e) {
...
-            if (((S3Exception) e).getErrorCode().equals("PreconditionFailed")) {
+            if (errorCode.equals("PreconditionFailed")) {
                 retVal = new StreamSegmentExistsException(segmentName);
             }
 
-            if (((S3Exception) e).getErrorCode().equals("InvalidRange")) {
+            if (errorCode.equals("InvalidRange")
+                    || errorCode.equals("InvalidArgument")
+                    || errorCode.equals("MethodNotAllowed")) {
                 retVal = new IllegalArgumentException(segmentName, e);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java]: Does it make sense to wrap instead with something that derives from `StreamSegmentException`?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java [hunk 4]
```diff
@@ -409,7 +411,9 @@ private Throwable translateException(String segmentName, Throwable e) {
             retVal = new IllegalArgumentException(e.getMessage());
         }
 
-        if (e instanceof AccessDeniedException) {
+        if (e instanceof AccessControlException
+                || e instanceof AccessDeniedException
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java]: One more point. In the S3 case, we are letting the `AccessDeniedException` to fall through, but not for file system. Is this the correct behavior?

Comment (arvindkandhare) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/filesystem/FileSystemStorage.java]: In case of S3, we should have translated "AccessDenied" S3Exception. This is equivalent of `AccessDeniedException` for file system. Updated code to do this,

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java (hunk 3 above)
Comment (arvindkandhare) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/extendeds3/ExtendedS3Storage.java]: As discussed offline: `IllegalArgumentException` is the most suitable exception here.
