### PR TITLE
Issue 7428: Fix junit test failure for InProcPravegaClusterTest.

### LINKED ISSUE #7428: Fix junit test failure for InProcPravegaClusterTest.
**Describe the bug**
In Pravega master junit test for InProcPravegaClusterTest failing consistently.

**To Reproduce**
1. Run **./gradlew clean :standalone:test**

**Screenshots**
N/A

**Additional information**
N/A

### PR DESCRIPTION
**Pull request by Bhupender-Y**
**Change log description**  
In Pravega master junit test for InProcPravegaClusterTest failing consistently.

**Purpose of the change**  
Fixes #7428.

**What the code does**  
This change will clear secure ZKClient properties from system properties so that next test subsequent test will not have stale client properties. I have also removed `@RunWith(SerializedClassRunner.class)` from standalone tests as it will improve standalone test execution time (i found that running tests in parallel is not causing any issue).

**How to verify it**  
Run **./gradlew clean :standalone:test**, all tests should succeed.

### CODE REVIEW

**Comment by RaulGracia** [comment]
@Bhupender-Y thanks for this PR. Please, improve the description of the changes by adding the reason why `@RunWith(SerializedClassRunner.class)` has been removed.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java [hunk 1]
```diff
@@ -487,6 +487,10 @@ public void close() throws Exception {
             }
         }
 
+        if (secureZK) {
+            ZKTLSUtils.unsetSecureZKClientProperties();
```
Comment (RaulGracia) [inline standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java:491]: Could the fact of running these tests in parallel now be problematic when calling this static method concurrently?

**Review by RaulGracia — COMMENTED** [review]
I have one minor comment. Also, do you know if both changes are needed or is only one (ZK properties, parallel execution) the one that fixes the problem?

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java (hunk 1 above)
Comment (Bhupender-Y) [reply standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java:491]: We have tried it multiple times and test cases are passing consistently.

**Comment by Bhupender-Y** [comment]
> I have one minor comment. Also, do you know if both changes are needed or is only one (ZK properties, parallel execution) the one that fixes the problem?

Thanks @RaulGracia , only `parallel execution` is not helping here. After clearing up `ZK properties`, we could see test passing consistently. I didn't revert the `parallel execution` as it will improve our execution time for AllOthersUnitTest.

**Review by RaulGracia — APPROVED** [review]

**Review by abhinb — APPROVED** [review]
