### PR TITLE
Issue 2159: NPE in SegmentInputStreamImpl

### LINKED ISSUE #2159: outstandingRequest can be null in SegmentInputStreamImpl
**Problem description**
I don't understand how we guarantee that `outstandingRequest` is not null upon an invocation of:

```
read -> readEventData -> handleRequest
```

In fact, we have observed an NPE in the r0.1 branch, which might still be present in master:

```
java.lang.NullPointerException: null
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.handleRequest(SegmentInputStreamImpl.java:160)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:148)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:111) 
    at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:94) 
```

**Problem location**
Client, reader.

**Suggestions for an improvement**
Fix the NPE if it is there in master.

### PR DESCRIPTION
**Pull request by fpj**
Signed-off-by: Flavio Junqueira (fpj) <fpj@apache.org>

**Change log description**
* Fixes a bug in SegmentInputStreamImpl that causes an NPE to be thrown when events are larger than the read length.

* Adds a call to issueRequestIfNecessary to the loop that handles the case in which the event is greater than the read length.

* Changes the sign in issueRequestIfNeeded from greater to greater or equal.

**Purpose of the change**
Fixes #2159 

**What the code does**
In `SegmentInputStreamImpl.issueRequestIfNeeded`, in the case we are reading an event that is greater than read length, we end up with `buffer.capacityAvailable() <= readLength`, which causes the value of `outstandingRequest` to remain null and induces the NPE when handleRequest is invoked next. The solution to this scenario is to simply make the predicate of the `if` greater or equal rather than just greater:

```
buffer.capacityAvailable() >= readLength
```

Additionally, we need to add a call to `SegmentInputStreamImpl.issueRequestIfNeeded` to the loop that handles events that are greater than the read length before invoking `handleRequest`.

It also adds a couple of scenarios to `ReadTest` integration test to verify that this fixes the issue with larger events. If we remove the changes, we can see the test case failing with NPE.

**How to verify it**
Tests should pass. Removing the equal sign added in this PR causes the `ReadTest` integration test to fail.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ private void verifyIsAtCorrectOffset(WireCommands.SegmentRead segmentRead) {
      * Issues a request if there is enough room for another request, and we aren't already waiting on one
      */
     private void issueRequestIfNeeded() {
-        if (!receivedEndOfSegment && buffer.capacityAvailable() > readLength) {
+        if (!receivedEndOfSegment && buffer.capacityAvailable() >= readLength) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: This line is good but it will not prevent the NPE.
we need to modify the loop on line 147 to look like:
```
        while (result.hasRemaining()) {
            issueRequestIfNeeded();  // <- added
            handleRequest();
            offset += buffer.read(result);
        }
```

File: test/integration/src/test/java/io/pravega/test/integration/ReadTest.java [hunk 2]
```diff
@@ -181,6 +181,10 @@ public void readThroughSegmentClient() throws SegmentSealedException, EndOfSegme
         SegmentInputStream in = segmentConsumerClient.createInputStreamForSegment(segment);
         ByteBuffer result = in.read();
         assertEquals(ByteBuffer.wrap(testString.getBytes()), result);
+
+        // Test large write followed by read
+        out.write(new PendingEvent(null, ByteBuffer.wrap(new byte[150000]), new CompletableFuture<>()));
+        in.read();
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/ReadTest.java]: This covers the case you found. But you should also add:
```
        out.write(new PendingEvent(null, ByteBuffer.wrap(new byte[15]), new CompletableFuture<>()));
        out.write(new PendingEvent(null, ByteBuffer.wrap(new byte[15]), new CompletableFuture<>()));
        out.write(new PendingEvent(null, ByteBuffer.wrap(new byte[150000]), new CompletableFuture<>()));
        in.read();
        in.read();
        in.read();
```
Which will fail the way the change is now.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java (hunk 1 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: You might be right, but I'm not entirely convinced and let me give you my argument so that you can show me  where it is incorrect. The flow I observed is the following:

1. We call `SegmentInputStreamImpl.read`, which calls `SegmentInputStreamImpl.readEventData`.
2. It invokes `SegmentInputStreamImpl.handleRequest` once in line 131.
3. It executes the `if` block of line 167, which sets `outstandingRequest` to `null` and invokes `SegmentInputStreamImpl.issueRequestIfNeeded`. The expectation as I understand this flow is that the call to `issueRequestIfNeeded` is that it will populate `outstadingRequest` because it is null. However, it doesn't because of the sign mismatch, which is fixed by making it greater or equal.

Adding `issueRequestIfNeeded` in line 147 is not wrong, but it does not seem to match my understanding of the flow because `outstandingRequest` should really have been populated previously in the execution of the while loop of line 124 (I'm assuming this will run for at least one interaction, is that correct?). The only way I have to justify the addition of the line you suggest is by assuming that it is possible for the while loop of line 124 to not run for a single iteration during an invocation of `readNextEvent`.

I have actually implemented your suggestion for the test case, and I couldn't observe the NPE. In fact, you can see that the latest Travis build has been successful and it contains the test case changes, but not the addition of `issueRequestIfNeeded();` to line 147.

Let me know what you think and help me understand the expected flow here better, please.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Unfortunately the test case being an integration test, the timing to repro the more complicated case is not guaranteed. If you run the test case in a debugger and set breakpoints on the first read call and then do 'step over' three times to introduce a pause between the reads to allow other threads to complete the future reads, the test will fail.

The reason for the issue is what you highlight, the loop on line 124 may never execute. It's condition is there is less than 8 bytes in the buffer. Which under normal circumstances is not the case. 
So what ends up happening is that fillBuffer() on 123 moves the data from the outstanding request into the buffer, and then calls issueRequestIfNeeded(), but it does not issue a request because the buffer is more than half full. Then on 145 when the data is read out of the buffer it may be that the event being read is larger than the buffer so it enters the while loop on 146 and gets the NPE. If there were an issueRequestIfNeeded() call between the read on 145 and the handleRequest() on 147 then it would not throw a null pointer.

The case you fixed is just a special case of this error condition where the buffer is empty before readEventData() is called. In this case when fillBuffer() invokes issueRequestIfNeeded() and it will end up issuing a request because the pending request fills exactly half of the buffer. But if there were a few extra bytes left in the buffer before readEventData(), then more than half would be filled and no request would be issued.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: I believe that the `issueRequestIfNeeded()` could also go right before the loop. But if we wanted to avoid calling it in the event that there is not data remaining we would have to do:
```
if(result.hasRemaining()) {
    issueRequestIfNeeded();
    while (result.hasRemaining()) {
        handleRequest();
        offset += buffer.read(result);
    }
}
```
Which is a bit longer...

Comment (fpj) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Added call to `issueRequestIfNeeded`.
