### PR TITLE
Issue 6874: Flaky test SecureStreamMetadataTasksTest.readerGroupsTest is failing

### LINKED ISSUE #6874: Flaky test SecureStreamMetadataTasksTest.readerGroupsTest is failing
**Describe the bug**
Unit test io.pravega.controller.task.Stream.SecureStreamMetadataTasksTest.readerGroupsTest is failing with below exception in jenkins job. This never fails in local. 

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at io.pravega.controller.task.Stream.StreamMetadataTasksTest.readerGroupsTest(StreamMetadataTasksTest.java:720)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Fixed assertions in readerGroupsTest.

**Purpose of the change**  
Fixes #6874.

**What the code does**  
The test was asserting that 3 metrics were present (`CONTROLLER_EVENT_PROCESSOR_CREATE_READER_GROUP_LATENCY`, `CONTROLLER_EVENT_PROCESSOR_DELETE_READER_GROUP_LATENCY`, and `CONTROLLER_EVENT_PROCESSOR_UPDATE_READER_GROUP_LATENCY`), and the last latency value recorded for them was strictly higher than 0ms. While this was normally the case for latency related to delete and create Reader Groups, for Reader Group update operations latency could be lower than 1ms (i.e., 0ms). This was making the assertion to fail, despite taking 0ms for some operation is a perfectly valid case. Note that if the latency was not reported, `MetricsTestUtil.getTimerMillis()` would throw a NPE, not returning 0.

Additionally, the PR simplifies some assertions throughout the test (not strictly necessary, just some cleanup).

**How to verify it**  
Test was locally failing when executing it 4-6 times in a row.
After the change, it was executed +100 times without problem.

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java [hunk 1]
```diff
@@ -715,9 +715,9 @@ public void readerGroupsTest() throws InterruptedException, ExecutionException {
...
         assertEquals(subscriberToNonSubscriberConfig.getStartingStreamCuts().size(), responseRG3.getConfig().getStartingStreamCutsCount());
         assertEquals(subscriberToNonSubscriberConfig.getEndingStreamCuts().size(), responseRG3.getConfig().getEndingStreamCutsCount());
-        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_CREATE_READER_GROUP_LATENCY) > 0);
-        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_DELETE_READER_GROUP_LATENCY) > 0);
-        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_UPDATE_READER_GROUP_LATENCY) > 0);
+        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_CREATE_READER_GROUP_LATENCY) >= 0);
+        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_DELETE_READER_GROUP_LATENCY) >= 0);
+        assertTrue(MetricsTestUtil.getTimerMillis(MetricsNames.CONTROLLER_EVENT_PROCESSOR_UPDATE_READER_GROUP_LATENCY) >= 0);
     }
```
Comment (munish1789) [inline controller/src/test/java/io/pravega/controller/task/Stream/StreamMetadataTasksTest.java:721]: logic/understanding was even if takes very less time then also value should be grater then 0

**Review by sachin-j-joshi — APPROVED** [review]
LGTM
