### PR TITLE
Issue 2139: Bugfix conditional append

### LINKED ISSUE #2139: Failed conditional writes mishandled following connection failure.
**Problem description**
If a conditional append has it's check fail but is immediately followed by a non-conditional append from the same writer, then before receiving the reply from the server for either append the client drops the connection, then upon reconnecting it will receive the higher sequence number of the successful non-conditional append and incorrectly ack the conditional append whose check failed.

**Problem location**
SegmentOutputStreamImpl

**Suggestions for an improvement**
Conditional appends need to be moved to a separate code path and passed one at a time as standard commands.

- [x] Create Raw Client (PR #2373)

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
Add ConditionalOutputStream as an internal low level client for use by RevisionedStreamClient to perform conditional appends.

**Purpose of the change**
Fixes #2139

**What the code does**
Add ConditionalOutputStream which only allows one request to be outstanding at a time. This ensures that the race described in  #2139 cannot occur, as it goes through a dedicated code path.

**How to verify it**
Unit tests added to cover the new classes.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * Allows data to be conditionally appended to the end of the segment
+ */
+public interface ConditionalOutputStream extends AutoCloseable {
+
+    /**
+     * Returns the name of the segment associated to this output stream.
+     *
+     * @return The name of the segment associated to this output stream.
+     */
+    public abstract String getSegmentName();
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: why do you have `public abstract` in interfaces? These are not necessary.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    
+    /**
+     * Writes the provided data to the SegmentOutputStream. If
+     * {@link PendingEvent#getExpectedOffset()} the data will be written only if the
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: the "If" clause is not a sentence. Did you forget to add something?

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+     * SegmentOutputStream is currently of expectedLength.
+     * 
+     * This is a synchronous and blocking method.
+     * 
+     * @param data The data to be added to the segment.
+     * @param expectedOffset The location is the segment that the data will be written to.
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: "in the segment"
"written at"

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamFactory.java [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.segment.impl;
+
+/**
+ * Creates {@link ConditionalOutputStream} for conditional appends on existing segments.
+ */
+public interface ConditionalOutputStreamFactory {
+    /**
+     * Opens an existing segment for conditional append operations. This operation will fail if the
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamFactory.java]: If it fails, what exception does it throw? We should document this.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+            long appendSequence = requestIdGenerator.get();
+            return RETRY_SCHEDULE.retryingOn(ConnectionFailedException.class)
+                    .throwingOn(SegmentSealedException.class)
+                    .run(() -> {
+                        if (client == null || client.isClosed()) {
+                            client = new RawClient(controller, connectionFactory, segmentId);
+                            long requestId = requestIdGenerator.get();
+                            log.debug("Setting up append on segment: {}", segmentId);
+                            val reply = client.sendRequest(requestId, new WireCommands.SetupAppend(requestId, writerId, segmentId.getScopedName(), delegationToken));
+                            AppendSetup appendSetup = transformAppendSetup(reply.join());
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java]: I prefer not to use `join` since you could be waiting forever if something got stuck on the server or in between. Can we use `get` with a timeout, and in case of a timeout, we close the stream?

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java]: If I call get with a timeout and the timeout fires the caller will not know if the event was written or not and has no way to find out. This is very difficult to code against. As it is written it will retry until retry exhausted, but if it sends a request and the connection remains alive it will block for a response, however long that takes. I think this is acceptable, because if we are dropping requests or replies on the floor on the server (without sending an error), that is a severe bug and we should deal it immediately rather than forcing the client to code around the race condition it creates.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+import javax.annotation.concurrent.GuardedBy;
+import lombok.Lombok;
+import lombok.RequiredArgsConstructor;
+import lombok.val;
+import lombok.extern.slf4j.Slf4j;
+
+@RequiredArgsConstructor
+@Slf4j
+class ConditionalOutputStreamImpl implements ConditionalOutputStream {
+    private static final RetryWithBackoff RETRY_SCHEDULE = Retry.withExpBackoff(1, 10, 9, 30000);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java]: Can we use the same retry config as that of SegmentOutputStreamImpl?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 7]
```diff
@@ -362,7 +354,7 @@ public void appendSetup(AppendSetup appendSetup) {
                                              .map(entry -> new Append(segmentName, writerId, entry.getKey(),
                                                                       Unpooled.wrappedBuffer(entry.getValue()
                                                                                                   .getData()),
-                                                                      entry.getValue().getExpectedOffset()))
+                                                                      null))
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: ok, this is null because all conditional writes are done via the new `ConditionalOutputStream` and we need not specify the `expectedSegmentOffset` inside Append.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java [hunk 8]
```diff
@@ -83,7 +81,7 @@
     private final CheckpointStore checkpointStore;
     private final EventProcessorSystem system;
     private final Controller controller;
-    private final ClientFactory clientFactory;
+    private final ClientFactoryImpl clientFactory;
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java]: this change is not required, right?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 7 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: ConditionalAppend gets deserialized on the server side as an Append object, because it is simpler to keep the server side as a single code path.

File: client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java [hunk 9]
```diff
@@ -49,29 +49,27 @@
...
+        boolean wasWritten;
         long offset = latestRevision.asImpl().getOffsetInSegment();
         ByteBuffer serialized = serializer.serialize(value);
         int size = serialized.remaining();
-        try {
-            PendingEvent event = new PendingEvent(null, serialized, wasWritten, offset);
-            synchronized (lock) {
-                out.write(event);
-                out.flush();
+        synchronized (lock) {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java]: What do you mean? Unconditional appends hold the same lock.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java [hunk 10]
```diff
@@ -0,0 +1,146 @@
...
+    
+
+    @Override
+    public String getSegmentName() {
+        return segmentId.getScopedName();
+    }
+
+    @Override
+    public boolean write(ByteBuffer data, long expectedOffset) throws SegmentSealedException {
+        synchronized (lock) { //Used to preserver order.
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java]: yes

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+     * Writes the provided data to the SegmentOutputStream. The data will be written only if the
+     * SegmentOutputStream's writeOffset is currently expectedOffset.
+     * 
+     * This is a synchronous and blocking method.
+     * 
+     * @param data The data to be added to the segment.
+     * @param expectedOffset The location in the segment that the data will be written at.
+     * @throws SegmentSealedException If the segment is closed for modifications.
+     */
+    public boolean write(ByteBuffer data, long expectedOffset) throws SegmentSealedException;
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: This is somewhat of a subjective call but the rule is that exceptions should be unexpected.
If for example we were not able to write the data because the storage system failed then that is clearly an exception. Here it depends on your point of view. There are two ways this API could be used:
1. You have a single writer at a time and occasionally switch which process is doing the writing. Similar to what we do with BK ledgers on the server side. 
2. There are many processes writing at the same time and contention is normal. 

Both are possible, in the first case an exception is called for. I was thinking on the second case when I was writing this, so it uses a return value. Though the class could be used in either situation.

File: client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java [hunk 12]
```diff
@@ -0,0 +1,164 @@
...
+import org.mockito.Mockito;
+import org.mockito.invocation.InvocationOnMock;
+import org.mockito.stubbing.Answer;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertFalse;
+import static org.junit.Assert.assertTrue;
+import static org.mockito.ArgumentMatchers.any;
+
+public class ConditionalOutputStreamTest {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java]: We can't exactly test the original case, because it was predicated on mixed conditional and unconditional appends, which as they are now on different interfaces is totally impossible. 
However I have added another test that verifies that the conditional writes are serialized, which should rule out any possibility of having the same bug.

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 13]
```diff
@@ -48,4 +53,87 @@ public static int getAvailableListenPort() {
         throw new IllegalStateException(
                 String.format("Could not assign port in range %d - %d", BASE_PORT, MAX_PORT_COUNT + BASE_PORT));
     }
+
+    public static void testBlocking(RunnableWithException blockingFunction, Runnable unblocker) {
```
Comment (andreipaduroiu) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: I would really like some javadoc on this method. It looks useful, but it's not clear to me how to use it should I need something like this.

Also would this method not be more suited to live in `AssertExtensions`, since that's where we put all the verification methods? `TestUtils` has common utility methods, but nothing that does verification.

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 14]
```diff
@@ -48,4 +53,87 @@ public static int getAvailableListenPort() {
...
+        final AtomicReference<Exception> exception = new AtomicReference<>(null);
+        final Semaphore isBlocked = new Semaphore(0);
+        Thread t = new Thread(new Runnable() {
+            @Override
+            public void run() {
+                try {
+                    blockingFunction.run();
+                } catch (Exception e) {
```
Comment (andreipaduroiu) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: `Throwable` since we may want to include `AssertionErrors` too.

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 15]
```diff
@@ -48,4 +53,87 @@ public static int getAvailableListenPort() {
...
+                    exception.set(e);
+                }
+                isBlocked.release();
+            }
+        });
+        t.start();
+        try {
+            if (isBlocked.tryAcquire(200, TimeUnit.MILLISECONDS)) {
+                if (exception.get() != null) {
+                    throw new RuntimeException("Blocking code threw an exception", exception.get());
```
Comment (andreipaduroiu) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: `AssertionError`? or `Assert.fail`?

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 16]
```diff
@@ -48,4 +53,87 @@ public static int getAvailableListenPort() {
...
+                } else {
+                    throw new RuntimeException("Failed to block.");
+                }
+            }
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
```
Comment (andreipaduroiu) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: Maybe use `Exceptions.handleInterruptibly`?

Comment (tkaitchuck) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: I can't depend on that. It's in common and this is in TestCommon which does not depend on common.

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java (hunk 15 above)
Comment (tkaitchuck) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: Changed to AssertionFailedError

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java (hunk 14 above)
Comment (tkaitchuck) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: fixed

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java (hunk 13 above)
Comment (tkaitchuck) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: done

File: client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (fpj) [reply client/src/test/java/io/pravega/client/segment/impl/ConditionalOutputStreamTest.java]: Ok.

File: client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (fpj) [reply client/src/main/java/io/pravega/client/state/impl/RevisionedStreamClientImpl.java]: Ok, you're right, I missed it because it was not in the set of new or removed lines.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (fpj) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: Ok.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java [hunk 17]
```diff
@@ -0,0 +1,46 @@
...
+    
+    /**
+     * Writes the provided data to the SegmentOutputStream. The data will be written only if the
+     * SegmentOutputStream's writeOffset is currently expectedOffset.
+     * 
+     * This is a synchronous and blocking method.
+     * 
+     * @param data The data to be added to the segment.
+     * @param expectedOffset The location in the segment that the data will be written at.
+     * @throws SegmentSealedException If the segment is closed for modifications.
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStream.java]: This javadoc is missing a line for the `@return` value.

**Comment by fpj** [comment]
@tkaitchuck there is a checkstyle error in the build:

```
:test:testcommon:checkstyleMain[ant:checkstyle] [ERROR] /home/travis/build/pravega/pravega/test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java:373:20: Expected @param tag for '<ResultT>'. [JavadocMethod]
```
