### PR TITLE
Issue 3228: Fix the issues that cause failure in bootstrap of TLS-enabled standalone cluster

### LINKED ISSUE #2566: REST api - TLS connection was non-properly terminated
**Problem description**
How to reproduce (with pravega master as of 5/9/2018).

Enable TLS in standalone-config.properties
```
singlenode.certFile=../config/cert.pem
singlenode.keyFile=../config/key.pem
singlenode.enableTls=true
```

Start with standalone pravega with 
```
gradlew startstandalone
```

Run the curl command below:
```
curl -v https://localhost:9091/v1/scopes
```
eventual the curl command times out with the following output
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9091 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
```

However,  request to http continues to work, e.g., `curl http://localhost:9091/v1/scopes` would still list the scopes.

**Problem location**

**Suggestions for an improvement**

### LINKED ISSUE #3228: Pravega fails to start up in standalone mode when TLS is enabled
**Problem description**

1) Enable SSL/TLS in standalone-config.properties:
```
singlenode.certFile=../config/cert.pem
singlenode.keyFile=../config/key.pem
singlenode.enableTls=true
```
2) Start Pravega in standalone mode:
```
./gradlew startStandalone
```
The Gradle build task fails with the following messages: 

```
> Task :standalone:startStandalone FAILED
...
2018-12-27 00:56:01,668 914  [main] ERROR i.p.local.LocalPravegaEmulator - Exception occurred running emulator
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at java.lang.System.setProperty(System.java:796)
        at io.pravega.segmentstore.storage.impl.bookkeeper.ZooKeeperServiceRunner.initialize(ZooKeeperServiceRunner.java:94)
        at io.pravega.local.InProcPravegaCluster.startLocalZK(InProcPravegaCluster.java:204)
        at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:177)
        at io.pravega.local.LocalPravegaEmulator.start(LocalPravegaEmulator.java:142)
        at io.pravega.local.LocalPravegaEmulator.main(LocalPravegaEmulator.java:118)
2018-12-27 00:56:01,675 921  [Thread-1] WARN  i.p.local.LocalPravegaEmulator - Exception running local Pravega emulator: null

FAILURE: Build failed with an exception.
```

**Problem location**
LocalPravegaEmulator.java, SingleNodeConfig.java, standalone-config.properties

**Suggestions for an improvement**
The "startStandalone" Gradle task runs the LocalPravegaEmulator class, the properties of which are loaded from the config/standalone-config.properties file. Some of the LocalPravegaEmulator's properties that are necessary for bootstrapping it are not being set. Fix that.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Fix the issues that prevented Pravega to run in standalone mode with TLS enabled

**Purpose of the change**  
Fixes #3228, fixes #2566. 

**What the code does**  
Here's what the modified code does for the fix:
* Adds missing configuration properties for running Pravega in standalone mode with TLS enabled
* Adds new standalone mode-specific key store with existing server certificate and key
* Adds new standalone mode-specific trust store with the existing server certificate

The modified code also includes the following anciliary changes:
* Updates comments for standalone mode configuration properties in standalone-config.properties
* Sets sensible defaults for TLS-specific file configuration properties for standalone mode.

**How to verify it**  
* TlsEnabledInProcPravegaClusterTest - new test class that runs standalone mode with TLS
* InProcPravegaClusterTest - existing test class that runs standalone mode without TLS

### CODE REVIEW

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java [hunk 1]
```diff
@@ -16,21 +16,26 @@
...
+    public final static String PROPERTY_FILE = "singlenode.configurationFile";
+
     public final static Property<Integer> ZK_PORT = Property.named("zkPort", 4000);
     public final static Property<Integer> SEGMENTSTORE_PORT = Property.named("segmentstorePort", 6000);
     public final static Property<Integer> CONTROLLER_PORT = Property.named("controllerPort", 9090);
     public final static Property<Integer> REST_SERVER_PORT = Property.named("restServerPort", 9091);
-    public final static Property<String> CERT_FILE = Property.named("certFile", "");
-    public final static Property<String> KEY_FILE = Property.named("keyFile", "");
-    public final static Property<String> PASSWD_FILE = Property.named("passwdFile", "");
+    public final static Property<String> CERT_FILE = Property.named("certFile", "../config/cert.pem");
```
Comment (andreipaduroiu) [inline standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: I'd much rather you left these as they were (empty) and only modify the config file.

File: config/standalone-config.properties [hunk 2]
```diff
@@ -10,38 +10,64 @@
 
 ##region General Segment Store Settings
 
-# Port on which a ZK server is started
+# Port on which a ZK server is started.
+# Default value: 4000
```
Comment (RaulGracia) [inline config/standalone-config.properties]: According to other `.properties` files (and their respective `XXXConfig.java`), the value set here is assumed to be the default value. I don't know if we need an additional note on each field specifying that this is the default.

File: config/standalone-config.properties [hunk 3]
```diff
@@ -10,38 +10,64 @@
...
+# Whether to enable TLS for segmentstore and controller.
+# Valid values: 'true' or 'false'
+# Default value: false
+singlenode.enableTls=false
 
-# Enable authentication/authorization.
+# Whether to enable authentication/authorization.
+# Valid values: 'true' or 'false'
+# Default value: false
 #singlenode.enableAuth=true
```
Comment (RaulGracia) [inline config/standalone-config.properties]: This parameter may cause confusion, as `true` and `false` appear here as possible defaults. Moreover, in `SingleNodeConfig.java` we still have `public final static Property<Boolean> ENABLE_AUTH = Property.named("enableAuth", false);`. It would be nice to clarify this.

File: config/standalone-config.properties [hunk 4]
```diff
@@ -10,38 +10,64 @@
...
 
 # Port on which the controller server grpc is started.
+# Default value: 9090
 #singlenode.controllerPort=9090
 
-# Enable REST server.
-#singlenode.enableRestServer=true
+# Whether to enable REST server.
+# Default value: false
+singlenode.enableRestServer=false
```
Comment (RaulGracia) [inline config/standalone-config.properties]: Is this change related to the original issue? Moreover, this property can be commented as the other ones that do not modify the default value set in `SingleNodeConfig.java`.

File: standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+        writer.writeEvent("hello").get();
+        // If the control reaches here, the write event operation was successful.
+    }
+
+    @After
+    @Override
+    public void tearDown() throws Exception {
+        super.tearDown();
+    }
+
```
Comment (RaulGracia) [inline standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: Minor: extra blank lines.

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java (hunk 1 above)
Comment (ravisharda) [reply standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: @andreipaduroiu - The rationale for setting defaults for the certificate, key, keystore and truststore files here was so that it's easier to deploy TLS-enabled Pravega standalone mode. With this change, one can do so simply by setting "singlenode.enableTls=true" if one is OK with using provided default certificates, keys, keystores and truststores. Without these defaults, the user will have to mandatorily specify all of the following properties for TLS, as well: 
* singlenode.certFile
* singlenode.keyFile
* singlenode.keyStoreJKS
* singlenode.keyStoreJKSPasswordFile
* singlenode.trustStoreJKS

What do you say?

File: config/standalone-config.properties (hunk 2 above)
Comment (ravisharda) [reply config/standalone-config.properties]: For some of the properties in config.properties, we have a note that explicitly specify the default value. For example: 
```
...
# Default value: BOOKKEEPER
pravegaservice.dataLogImplementation=BOOKKEEPER
...
# Default value: HDFS
# pravegaservice.storageImplementation=HDFS
```

The note might turn out to be useful sometimes if the user has modified the value and wants to go back to the default.

What do you say?

File: config/standalone-config.properties (hunk 3 above)
Comment (ravisharda) [reply config/standalone-config.properties]: @Raul - The thinking was that since the default value for this boolean propery is false, one'd really need to change it only for setting it to true. So, why not just set it to "true" in that case, so that the user only needs to uncomment the line if he wants to change the default behavior. 

That said, if our convention is to set the property values to default values even if the property is commented out, it'd make more sense to follow that convention and change that line to #singlenode.enableAuth=false. 

What do you say?

File: standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java (hunk 5 above)
Comment (ravisharda) [reply standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: Have fixed it and pushed the change.

File: config/standalone-config.properties (hunk 4 above)
Comment (ravisharda) [reply config/standalone-config.properties]: This was a bug. I have pushed a commit to restore the default back to true in ``SingleNodeConfig.java``.

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java (hunk 1 above)
Comment (EronWright) [reply standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: Seems to me that the standalone mode has a config file with good defaults.   Putting the defaults into code may inadvertently affect the embedded mode and would be duplicative?

It is probably a bad practice to ship any private keys or default passwords, since you wouldn't want anyone to use them.  

In any case, please ensure that these changes don't affect the embedded mode.

File: config/standalone-config.properties [hunk 6]
```diff
@@ -10,38 +10,62 @@
...
 
 # Port on which the controller server grpc is started.
+# Default value: 9090
 #singlenode.controllerPort=9090
 
-# Enable REST server.
-#singlenode.enableRestServer=true
+# Whether to enable REST server.
+# Default value: true
+#singlenode.enableRestServer=false
```
Comment (adrianmo) [inline config/standalone-config.properties]: To be consistent with the configuration settings, we should probably use the default values for the new commented out settings.

e.g. change

```
# Default value: true
#singlenode.enableRestServer=false
```

to 

```
# Default value: true
#singlenode.enableRestServer=true
```

File: config/standalone-config.properties (hunk 3 above)
Comment (ravisharda) [reply config/standalone-config.properties]: @raul, I've now pushed a change that uses the default value as the value in the commented out property.

File: standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+                .scalingPolicy(ScalingPolicy.fixed(numSegments))
+                .build());
+        Assert.assertTrue("Failed to create the stream ", isStreamCreated);
+
+        EventStreamClientFactory clientFactory = EventStreamClientFactory.withScope(scope, clientConfig);
+        EventStreamWriter<String> writer = clientFactory.createEventWriter(streamName,
+                new JavaSerializer<String>(),
+                EventWriterConfig.builder().build());
+        writer.writeEvent("hello").get();
+        // If the control reaches here, the write event operation was successful.
```
Comment (RaulGracia) [inline standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: Maybe it would be a good idea to check that we can create a `ReaderGroup` and a reader can correctly read the event just published as well.

Comment (ravisharda) [reply standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: Thanks @RaulGracia. I just addressed this feedback and have pushed the change as you suggested.

**Comment by RaulGracia** [comment]
I executed `pravega-standalone` with the changes of this PR (in Windows) and enabled the TLS security settings. The process starts, but it keeps throwing the following error:

```
2019-01-09 09:51:03,357 24631 [core-11] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
2019-01-09 09:51:03,775 25049 [fetch-controllers-1] INFO  i.p.c.s.i.ControllerResolverFactory - Attempting to refresh the controller server endpoints
2019-01-09 09:51:03,776 25050 [fetch-controllers-1] INFO  i.p.c.s.i.ControllerResolverFactory - Updating client with controllers: [[addrs=[localhost/127.0.0.1:9090], attrs={}]]
2019-01-09 09:51:03,777 25051 [fetch-controllers-1] INFO  i.p.c.s.i.ControllerResolverFactory - Rescheduling ControllerNameResolver task for after 120000 ms
2019-01-09 09:51:05,025 26299 [grpc-default-executor-1] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)```
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:648)
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:482)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1020)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1127)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:210)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:221)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:644)
        ... 26 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
        ... 33 common frames omitted
```

So, there is any problem with the default certificate or do we need to add extra flags to the JVM before execution?

**Comment by RaulGracia** [comment]
Thanks @ravisharda. If these steps should be executed by the user for running `pravega-standalone` with TLS enabled, then probably we may need to add them in the [documentation](http://pravega.io/docs/latest/deployment/run-local/).

**Comment by EronWright** [comment]
@ravisharda I would be very careful about necessitating a change to the user's root certificates.   The justification is non-intuitive to say the least.

**Comment by ravisharda** [comment]
@RaulGracia and @EronWright Thanks. I agree that the documentation needs an update, and have created an issue (#3268) to track that. 

@EronWright Just to clarify, importing the CA certificate to JVM's truststore when using the provided PKI material for TLS is not a new requirement imposed by the fix, but was rather required earlier too but not documented. Note the 1st comment in #2580.

**Comment by EronWright** [comment]
@ravisharda rather than mutating the JVM truststore, could the instructions be to create a new truststore and then configure the controller to use it in lieu of (or in addition to?) the system truststore?

**Comment by ravisharda** [comment]
@EronWright Ability to use a custom trust store is a nice feature to have, but IMHO out of the scope of the issue at hand. Would you agree?

**Comment by adrianmo** [comment]
@ravisharda I'm getting authentication errors after enabling auth (not TLS) and starting standalone:

```
...
2019-01-11 14:38:37,020 113503 [grpc-default-executor-0] ERROR i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with authenticator error
2019-01-11 14:38:37,020 113503 [grpc-default-worker-ELG-6-3] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xabc06d14, L:/127.0.0.1:9090 - R:/127.0.0.1:43244] OUTBOUND HEADERS: streamId=33 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 16, grpc-message: Authentication failed] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
2019-01-11 14:38:37,022 113505 [grpc-default-worker-ELG-6-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x84f559d7, L:/127.0.0.1:43244 - R:localhost/127.0.0.1:9090] INBOUND HEADERS: streamId=33 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-status: 16, grpc-message: Authentication failed] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
2019-01-11 14:38:37,023 113506 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019
...
```

Any ideas?

**Comment by ravisharda** [comment]
@adrianmo Not sure about this one, but a similar I found a similar stack trace in issue #2998.

**Comment by adrianmo** [comment]
Not sure, Am I the only one getting those authentication errors?

**Comment by ravisharda** [comment]
@adrianmo I just pulled the code from the master (which doesn't have the code from this pull request), enabled auth (without TLS), and executed "./gradlew startStandalone". On the console, I noticed the same error as you have encountered (shown below). I shall create a separate issue for this error, as it is unrelated to this issue that this pull request solves.

iled] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
2019-01-14 14:26:26,012 25829 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
    .....

**Comment by RaulGracia** [comment]
@ravisharda I still experience problems in Windows after executing the steps provided. As it could be a problem of my specific environment, if you confirm that you could run `pravega-standalone` in Windows with TLS configuration I will unblock the PR.

**Comment by ravisharda** [comment]
@RaulGracia  Standalone doesn't work on Windows for me (both without and with TLS). I get an error message `` "Createprocess error=206; the filename or extension is too long"``, when the startStandalone attempts to load the Java process. This seems to happen because the number of characters passed to Windows CreateProcess exceeds the max limit due to lengthy classpath entries. 

Curious, does anyone else successfully run standalone mode in Windows?

**Comment by RaulGracia** [comment]
Thanks, @ravisharda. Actually, you are right, this error appears when using the `pravega-standalone.bat` executable produced after running `./gradlew distribution` in the branch of this PR. However, I noticed that doing the same in `master` I could execute the standalone executable correctly (tested without TLS):
```
λ pravega-standalone.bat
Listening for transport dt_socket at address: 8000
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/gracir1/Documents/workspace/mine/pravega/build/distributions/pravega-0.5.0-2089.f18ac01-SNAPSHOT/pravega-0.5.0-2089.f18ac01-SNAPSHOT/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/gracir1/Documents/workspace/mine/pravega/build/distributions/pravega-0.5.0-2089.f18ac01-SNAPSHOT/pravega-0.5.0-2089.f18ac01-SNAPSHOT/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16:25:37,274 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [C:\Users\gracir1\Documents\workspace\mine\pravega\build\distributions\pravega-0.5.0-2089.f18ac01-SNAPSHOT\pravega-0.5.0-2089.f18ac01-SNAPSHOT\bin\../conf/logback.xml] at [file:/C:/Users/gracir1/Documents/workspace/mine/pravega/build/distributions/pravega-0.5.0-2089.f18ac01-SNAPSHOT/pravega-0.5.0-2089.f18ac01-SNAPSHOT/bin/../conf/logback.xml]
16:25:37,447 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:25:37,463 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:25:37,463 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [consoleAppender]
16:25:37,463 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:25:37,509 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:25:37,525 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
16:25:37,541 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@96406857 - Will use gz compression
16:25:37,541 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@96406857 - Will use the pattern C:/Users/gracir1/Documents/workspace/mine/pravega/build/distributions/pravega-0.5.0-2089.f18ac01-SNAPSHOT/pravega-0.5.0-2089.f18ac01-SNAPSHOT/bin/../logs/pravega_%d{yyyy-MM-dd}.%i.log for the active file
``` 

Could you confirm that, please?

**Comment by ravisharda** [comment]
@RaulGracia Thanks. Yes, I could run standalone on Windows using the batch file generated out of ``./gradlew distribution`` command on the branch code. This was true both with plaintext and TLS. 

With plaintext, the client reader/writer, as well as REST API, worked fine with plaintext/tcp protocol. 

With TLS enabled on Windows the clients, as well as REST API, don't appear to work properly. The gRPC and REST API's appear to be listening on HTTP (and not HTTPS); I noticed if I use the plaintext/TCP protocol in the controller URI and HTTPS in the REST URI, I get a proper response from the server. 

I'm investigating this Windows-specific issue.

**Comment by ravisharda** [comment]
@RaulGracia actually I was making a mistake in configuring TLS properties, causing the issue I mentioned in my last comment about running TLS-enabled standalone on Windows. 

After I corrected the configuration error and imported the server's certificate to the local JVM trust store, TLS-enabled standalone mode ran successfully on Windows. Also, my reader/writer client applications performed read/write successfully using `tls` method. Moreover, the REST endpoint is also exposed over `https` as expected.

**Comment by RaulGracia** [comment]
According to @ravisharda, the TLS issue related to this PR is solved in `pravega-standalone` for both Linux/Windows. It would be great to have a description for users of the procedure to follow, as pointed out in #3268. Given that, I will approve this PR, so other issues (as the ones reported by @adrianmo) can be addressed separately.

**Comment by ravisharda** [comment]
@RaulGracia / @adrianmo  just following up to see if this PR can be merged in - now that it's been in approved status for some time.

**Comment by adrianmo** [comment]
@ravisharda can you please rebase and retest this branch? We have updated many dependencies that can affect this PR in #3192

**Comment by ravisharda** [comment]
@adrianmo Sure, will do.

**Comment by ravisharda** [comment]
@adrianmo, @RaulGracia i'm done rebasing the branch and re-verifying the branch:
1. Travis CI build passed. Tests in ``TlsEnabledInProcPravegaClusterTest`` class passed, along with rest of the tests. 
2. Ran reader and writer applications to verify that reads and writes work successfully when TLS is enabled with standalone. Also verified the same when TLS is disabled. 
3. Verified that the REST API terminates SSL/TLS properly when TLS is enabled, by hitting ``https://localhost:9091/v1/scopes`` manually using cURL. 
4. Ran the tests (2 and 3 above) on both Linux and Windows.

**Comment by ravisharda** [comment]
Can we have this PR merged in soon? I'd like to be able to inspect the behavior of standalone mode with both auth and TLS enabled, for an issue I'm currently working on.

File: standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+    public void setUp() throws Exception {
+        this.authEnabled = false;
+        this.tlsEnabled = true;
+        super.setUp();
+    }
+
+    // Note: Strictly speaking, this test is really an "integration test" and is a little
+    // time consuming. For now, its intended to run as a unit test, but it could be moved
+    // to an integration test suite if and when necessary.
+    @Test
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: Done.
