### PR TITLE
Issue 4706: Fix SegmentStoreMetrics

### LINKED ISSUE #4706: Failing SegmentStoreMetricsTest.
**Problem description**

It appears there is intermittent issues with one of the SegmentStore tests failing.

**Problem location**

`io.pravega.segmentstore.server.SegmentStoreMetricsTests.testThrottlerMetrics`

**Suggestions for an improvement**

Close the `OperationProcessor` used within the `testThrottlerMetrics` test and assert the touched metrics are now `null`.

### PR DESCRIPTION
**Pull request by co-jo**
**Change log description**  
* Clean up redundancies in `ThrottlerTests.java`.
* Capture observed throttling sources in order to freeze gauge metrics.
* Randomize `containerId` in `SegmentStoreMetricsTests.java` to prevent gauge conflicts.

**Purpose of the change**  
Fixes #4706 

**What the code does**  
* Freezes gauge values upon `SegmentStoreMetrics.OperationProcessor` shutdown.

**How to verify it**  
Run unit tests.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java [hunk 1]
```diff
@@ -144,6 +146,7 @@ private void report() {
         private final OpStatsLogger processOperationsBatchSize;
         private final int containerId;
         private final String[] containerTag;
+        private Set<String> throttlers = new HashSet<>();
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java:149]: This is not thread safe. Use `Collections.synchronizedSet`
