### PR TITLE
Issue 5454: Fixing Segment Store flaky tests and other bugs

### LINKED ISSUE #5454: Various Segment Store Unit Test Fixes
## Problem description
**1.**
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testMixedReads FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20 seconds
```

**2.**
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testWriteFenceOut FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base@11.0.9.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at app//com.google.common.util.concurrent.Monitor.enterIf(Monitor.java:679)
        at app//com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:264)
        at app//io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
        at app//io.pravega.segmentstore.server.containers.StreamSegmentContainer.close(StreamSegmentContainer.java:231)
        at app//io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$TestContext.close(StreamSegmentContainerTests.java:2422)
        at app//io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testWriteFenceOut(StreamSegmentContainerTests.java:1653)

io.pravega.segmentstore.server.StreamSegmentStoreTestBase.testEndToEndWithFencingWithChunkedStorage
    org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
```
(These two have a shared root cause)

**3.**
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testFutureReads FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 100000 milliseconds
        at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
        at java.base@11.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
        at app//io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testFutureReads(StreamSegmentContainerTests.java:1340)
```

**4**
```
io.pravega.segmentstore.server.logs.OperationProcessorTests > testWithDataLogFailures FAILED
7339    org.junit.runners.model.TestTimedOutException: test timed out after 30 seconds
7340        at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
7341        at java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
7342        at java.base@11.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
7343        at java.base@11.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
7344        at java.base@11.0.2/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
7345        at java.base@11.0.2/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
7346        at app//io.pravega.segmentstore.server.logs.OperationProcessorTests.readUpToSequenceNumber(OperationProcessorTests.java:659)
7347        at app//io.pravega.segmentstore.server.logs.OperationProcessorTests.performLogOperationChecks(OperationProcessorTests.java:583)
7348        at app//io.pravega.segmentstore.server.logs.OperationProcessorTests.performLogOperationChecks(OperationProcessorTests.java:563)
7349        at app//io.pravega.segmentstore.server.logs.OperationProcessorTests.testWithDataLogFailures(OperationProcessorTests.java:331)
```

**5.**
```
io.pravega.segmentstore.server.logs.DurableLogTests > testTruncateWithoutRecovery FAILED
    java.lang.AssertionError: No truncation occurred even though a valid Truncation Point was passed: 1062
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.logs.DurableLogTests.testTruncateWithoutRecovery(DurableLogTests.java:1148)	
```

**6.**
```
io.pravega.storage.extendeds3.ExtendedS3SimpleStorageTests > testParallelWriteTwoHosts FAILED
    java.io.IOException: Failed to bind to /127.0.0.1:48852
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.gaul.s3proxy.S3Proxy.start(S3Proxy.java:389)
        at io.pravega.storage.extendeds3.S3ProxyImpl.start(S3ProxyImpl.java:83)
        at io.pravega.storage.extendeds3.ExtendedS3TestContext.<init>(ExtendedS3TestContext.java:47)
        at io.pravega.storage.extendeds3.ExtendedS3SimpleStorageTests.before(ExtendedS3SimpleStorageTests.java:32)
        Caused by:
        java.net.BindException: Address already in use
            at java.base/sun.nio.ch.Net.bind0(Native Method)
            at java.base/sun.nio.ch.Net.bind(Net.java:461)
            at java.base/sun.nio.ch.Net.bind(Net.java:453)
            at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
            at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
            at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
            ... 10 more
    java.lang.NullPointerException
        at io.pravega.test.common.ThreadPooledTestSuite.after(ThreadPooledTestSuite.java:34)
        at io.pravega.storage.extendeds3.ExtendedS3SimpleStorageTests.after(ExtendedS3SimpleStorageTests.java:41)
```

**7.**
```
io.pravega.segmentstore.server.logs.ThrottlerTests > testTemporaryDisabled FAILED
4769
    java.util.concurrent.TimeoutException: Timeout expired prior to the condition becoming true.
4770
        at io.pravega.test.common.TestUtils.await(TestUtils.java:79)
4771
        at io.pravega.segmentstore.server.logs.ThrottlerTests.testTemporaryDisabled(ThrottlerTests.java:382)
4772
        at io.pravega.segmentstore.server.logs.ThrottlerTests.testTemporaryDisabled(ThrottlerTests.java:347)
4773
```

**8.**
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testStorageReadsConcurrentNoOverwrite FAILED
5037
    org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
5038
        at java.base@11.0.9.1/java.lang.Thread.sleep(Native Method)
5039
        at app//io.pravega.test.common.TestUtils.await(TestUtils.java:74)
5040
        at app//io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:61)
5041
        at app//io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:87)
5042
        at app//io.pravega.segmentstore.server.reading.ContainerReadIndexTests$TestContext.close(ContainerReadIndexTests.java:2403)
5043
        at app//io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testStorageReadsConcurrent(ContainerReadIndexTests.java:887)
5044
        at app//io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite(ContainerReadIndexTests.java:857)
5045
        at app//io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite(ContainerReadIndexTests.java:851)
```

**Problem location**
Unit tests.

**Suggestions for an improvement**
Fix them.

### LINKED ISSUE #5480: Unit test failure: StreamSegmentContainerTests.testTransactionOperations
**Problem description**
1st stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    java.lang.UnsupportedOperationException: fail() not supported on RedirectedReadResultEntry
        at io.pravega.segmentstore.server.reading.RedirectedReadResultEntry.fail(RedirectedReadResultEntry.java:123)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.close(StreamSegmentReadResult.java:136)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2026)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2011)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2006)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```
2nd stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testTransactionOperations FAILED
    io.pravega.common.ObjectClosedException: Object 'StreamSegmentReadIndex' has been closed and cannot be accessed anymore.
        at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getSingleReadResultEntry(StreamSegmentReadIndex.java:884)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.createRedirectedRead(StreamSegmentReadIndex.java:1042)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getSingleReadResultEntry(StreamSegmentReadIndex.java:928)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getMultiReadResultEntry(StreamSegmentReadIndex.java:955)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:189)
        at io.pravega.segmentstore.server.reading.StreamSegmentReadResult.next(StreamSegmentReadResult.java:26)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2032)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2011)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.checkReadIndex(StreamSegmentContainerTests.java:2006)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testTransactionOperations(StreamSegmentContainerTests.java:1256)
```

**Problem location**
`StreamSegmentContainerTests.testTransactionOperations`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5484: Unit test failure: DurableLogTests.testTruncateWithoutRecovery
**Problem description**
1st stack trace:
```
io.pravega.segmentstore.server.logs.DurableLogTests > testTruncateWithoutRecovery FAILED
    java.lang.AssertionError: No truncation occurred even though a valid Truncation Point was passed: 1062
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.segmentstore.server.logs.DurableLogTests.testTruncateWithoutRecovery(DurableLogTests.java:1148)
```
2nd stack trace:
```
io.pravega.segmentstore.server.logs.DurableLogTests > testTruncateWithoutRecovery FAILED
    java.lang.AssertionError:  Unexpected Sequence Number expected:<353> but was:<253>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at io.pravega.segmentstore.server.logs.operations.OperationComparer.assertSame(OperationComparer.java:78)
        at io.pravega.segmentstore.server.logs.operations.OperationComparer.assertEquals(OperationComparer.java:66)
        at io.pravega.segmentstore.server.logs.DurableLogTests.testTruncateWithoutRecovery(DurableLogTests.java:1177)
```
**Problem location**
`DurableLogTests.testTruncateWithoutRecovery`

**Suggestions for an improvement**
Test should pass reliably. (Related to #5483 or #5454?)

### LINKED ISSUE #5485: Unit test failure: PriorityBlockingDrainingQueue ObjectClosedException in StreamSegmentContainerTests
**Problem description**
1st stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testAttributeCleanup FAILED
    java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testAttributeCleanup(StreamSegmentContainerTests.java:1633)
        Caused by:
        io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
            at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
            at io.pravega.common.util.AbstractDrainingQueue.poll(AbstractDrainingQueue.java:124)
            at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:334)
            at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```
2nd stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testMetadataCleanupRecovery FAILED
    java.util.concurrent.ExecutionException: io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testMetadataCleanupRecovery(StreamSegmentContainerTests.java:1496)

        Caused by:
        io.pravega.common.ObjectClosedException: Object 'PriorityBlockingDrainingQueue' has been closed and cannot be accessed anymore.
            at io.pravega.common.Exceptions.checkNotClosed(Exceptions.java:255)
            at io.pravega.common.util.AbstractDrainingQueue.poll(AbstractDrainingQueue.java:124)
            at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:334)
            at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
`StreamSegmentContainerTests.testAttributeCleanup`
`StreamSegmentContainerTests.testMetadataCleanupRecovery`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5487: Unit test failure: ThrottlerTests.testTemporaryDisabled
**Problem description**
Stack trace:
```
io.pravega.segmentstore.server.logs.ThrottlerTests > testTemporaryDisabled FAILED
    java.util.concurrent.TimeoutException: Timeout expired prior to the condition becoming true.
        at io.pravega.test.common.TestUtils.await(TestUtils.java:79)
        at io.pravega.segmentstore.server.logs.ThrottlerTests.testTemporaryDisabled(ThrottlerTests.java:382)
        at io.pravega.segmentstore.server.logs.ThrottlerTests.testTemporaryDisabled(ThrottlerTests.java:347)
```

**Problem location**
`ThrottlerTests.testTemporaryDisabled`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5490: Unit test failure on unexpected read index length: StreamSegmentServiceTests.testEndToEndWithFencing
**Problem description**
1st stack trace:
```
io.pravega.segmentstore.server.store.StreamSegmentServiceTests > testEndToEndWithFencing FAILED
    java.lang.AssertionError: Unexpected Read Index length for segment Segment_8 expected:<1190> but was:<1202>
```
2nd stack trace:
```
io.pravega.segmentstore.server.store.StreamSegmentServiceNoOpWriteReadTests > testEndToEndWithFencingWithChunkedStorage FAILED
    java.lang.AssertionError: Unexpected Read Index length for segment Segment_5 expected:<1190> but was:<1202>
```

**Problem location**
`StreamSegmentServiceTests.testEndToEndWithFencing`
`StreamSegmentServiceNoOpWriteReadTests.testEndToEndWithFencingWithChunkedStorage`

**Suggestions for an improvement**
Tests should pass reliably. May be related to #4089.

### LINKED ISSUE #5491: Unit test failure: StreamSegmentContainerTests.testForcedMetadataCleanup
**Problem description**
Stack trace:
```
io.pravega.segmentstore.server.containers.StreamSegmentContainerTests > testForcedMetadataCleanup FAILED
    java.lang.AssertionError: CacheManager closed with 1 outstanding bytes.
        at io.pravega.segmentstore.server.CacheManager.close(CacheManager.java:129)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$TestContext.close(StreamSegmentContainerTests.java:2240)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testForcedMetadataCleanup(StreamSegmentContainerTests.java:1379)
```

**Problem location**
`StreamSegmentContainerTests.testForcedMetadataCleanup`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5492: Unit test failure: ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite
**Problem description**
Stack trace:
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testStorageReadsConcurrentNoOverwrite FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20 seconds
        at java.lang.Thread.sleep(Native Method)
        at io.pravega.test.common.TestUtils.await(TestUtils.java:71)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:61)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:87)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests$TestContext.close(ContainerReadIndexTests.java:2072)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testConcurrentStorageReads(ContainerReadIndexTests.java:833)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite(ContainerReadIndexTests.java:803)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite(ContainerReadIndexTests.java:798)
```

**Problem location**
`ContainerReadIndexTests.testStorageReadsConcurrentNoOverwrite`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5495: Unit test failure: ContainerReadIndexTests.testFutureReads
**Problem description**
Stack trace:
```
io.pravega.segmentstore.server.reading.ContainerReadIndexTests > testFutureReads FAILED
    java.lang.AssertionError: Unexpected error happened while processing Segment 2: java.util.concurrent.CancellationException
        at org.junit.Assert.fail(Assert.java:88)
        at io.pravega.segmentstore.server.reading.ContainerReadIndexTests.testFutureReads(ContainerReadIndexTests.java:539)
```

**Problem location**
`ContainerReadIndexTests.testFutureReads`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5499: Unit test failure: deadlock after StreamSegmentServiceTests.testEndToEndWithChunkedStorage
**Problem description**
Build got locked-up on a test and took more than 6 hours to fail.

**Problem location**
After `StreamSegmentServiceTests.testEndToEndWithChunkedStorage` as seen here: https://github.com/pravega/pravega/runs/1673700574?check_suite_focus=true

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5500: Unit test failure: io.pravega.common.util.BlockingDrainingQueueTests.testTakeTimeout
**Problem description**
Found this unit test failing on Travis:
```
io.pravega.common.util.BlockingDrainingQueueTests > testTakeTimeout FAILED
    java.lang.AssertionError: poll() succeeded even though there was another incomplete take() request. Exception thrown failed tester: java.lang.AssertionError: poll() succeeded even though there was another incomplete take() request. No exception has been thrown.
        at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:133)
        at io.pravega.common.util.BlockingDrainingQueueTests.testTakeTimeout(BlockingDrainingQueueTests.java:181)
        Caused by:
        java.lang.AssertionError: poll() succeeded even though there was another incomplete take() request. No exception has been thrown.
            at org.junit.Assert.fail(Assert.java:88)
            at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:126)
            ... 1 more
```

**Problem location**
`BlockingDrainingQueueTests`

**Suggestions for an improvement**
Understand if it is a problem with the test or the class being tested and fix it.

### LINKED ISSUE #5505: Unit test failure: io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates
**Problem description**
Found failure in the following unit test:
```
java.util.concurrent.ExecutionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
Stacktrace
java.util.concurrent.ExecutionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests.testExtendedAttributesConditionalUpdates(StreamSegmentContainerTests.java:804)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.segmentstore.server.IllegalContainerStateException: Container 1234567 is in an invalid state for this operation. Expected: RUNNING; Actual: FAILED.
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:852)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.append(StreamSegmentContainer.java:398)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainerTests$MetadataCleanupContainer.lambda$appendRandomly$4(StreamSegmentContainerTests.java:2512)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:784)
	at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:753)
	at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:644)
	at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:797)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**Problem location**
`StreamSegmentContainerTests`

**Suggestions for an improvement**
Understand whether this is a test issue or a real bug and fix it.

### LINKED ISSUE #5516: Possible Data Loss due to #5345
**Problem description**
Issue #5345 introduced a possibility for undetected data loss while transferring data to LTS.

How?
- StorageWriter uses a `BlockingDrainingQueue` as source (which is used as sink from the `OperationProcessor`).
- StorageWriter uses a `take(with-timeout)` call on `BlockingDrainingQueue`
- The implementation of `BlockingDrainingQueue.take(with-timeout)` is buggy. If the timeout expires at the same time that we add a new element to the collection (which would have triggered the resulting future to complete), there was a possibility for the timeout to preempt the normal completion of the future, which resulted in data loss.
    - The data loss comes from the fact that the `add` method needs to complete the `take` future outside of the synchronization lock. It first picks up the data from the collection, stores it in a temp buffer, and outside of the lock it completes the `take` future. If the `take` future has just been completed (between the lock exit and the `.complete` call), the `.complete` call would have no effect and the fetched items lost.

**Problem location**
`AbstractDrainingQueue.java`

**Suggestions for an improvement**
Fix it.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
1. Fixing various unit tests in the Segment Store package(s) that caused builds to randomly fail.
2. Fixed a bug in `BlockingDrainingQueue` that would have resulted in data loss if a TimeoutException preempted the completion of a timeout-eligible take future (#5516).
3. Fixed a bug in `OperationProcessor` error handler to initiate the service shutdown in an async manner (to avoid deadlocks)
4. Fixed a bug in `OperationProcessor` to "unaccount" for the cache effects of operations that are in flight but have failed to be committed due to the service shutting down (byte accounting leak).
5. Fixed a bug in `StreamSegmentReadIndex` that would have caused a ReadResult to hang if certain concurrency conditions occur (merging a source segment into a parent one at the same time as either issuing the ReadResultEntry or completing it).
6. Fixed a bug in `RedirectedReadIndexEntry` that would throw an `UnsupportedOperationException` when attempting to close. This is invoked when a `ReadResult` is cancelled/cleaned up (so if it's sitting on one of those entries, the operation would fail).
7. Fixed a bug in `StreamSegmentContainer` that would incorrectly report as "Failed" if it is immediately shut down after startup (i.e., if the secondary services haven't yet been started).

**Purpose of the change**  
Fixes #5516.
Fixes #5454.
Fixes #5499.
Fixes #5492.
Fixes #5490.
Fixes #5487.
Fixes #5484.
Fixes #5500.
Fixes #5495.
Fixes #5491.
Fixes #5485.
Fixes #5505.
Fixes #5480.

**What the code does**  
See description above.

**How to verify it**  
Build must pass both on Travis and GitHub actions. This PR does not address all sporadic failures, but should be a good step towards a more stable build.

### CODE REVIEW

**Comment by RaulGracia** [comment]
FYI @andreipaduroiu Travis is failing with an error for one of the targeted tests of this PR:
```
io.pravega.segmentstore.server.logs.DurableLogTests > testAddWithDataLogFailures FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 30 seconds
        at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
        at java.base@11.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
        at java.base@11.0.2/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
        at app//io.pravega.segmentstore.server.logs.OperationLogTestBase.performReadIndexChecks(OperationLogTestBase.java:277)
        at app//io.pravega.segmentstore.server.logs.DurableLogTests.testAddWithDataLogFailures(DurableLogTests.java:342)
```

**Comment by andreipaduroiu** [comment]
Unfortunately the diff code coverage for this PR is a bit on the low side. Codecov indicates that some new code added is not covered by unit tests. This is true. I also cannot write any unit test that can possibly cover those two cases (lines 613-617 in OperationProcessor.java and lines 1071-1080 in StreamSegmentReadIndex). These cases cover deadlock situations or other concurrency scenarios which I cannot reliably simulate in any tests - I would need to add new code hooks to suspend thread execution at certain points in order to do that (not worth it IMO).

@fpj I may need your help in merging this one in. 

cc @RaulGracia

**Comment by fpj** [comment]
Code coverage seems to be complaining about the code in a catch block in a private method in `StreamSegmentReadIndex`. Could you clarify why we are adding that catch block? As it main code and it is not being tested, I don't follow how that's helping with fixing flaky tests, which is the target of this PR.

In the case we do need to have that change in this PR, my question is how we validate the code path in the catch block if not via unit tests. It is simple but it is not trivial and it is part of an exceptional code path. 

On the bright side, it does improve project code coverage.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java [hunk 1]
```diff
@@ -1039,20 +1052,33 @@ private CompletableReadResultEntry createRedirectedRead(long streamSegmentOffset
...
+        } catch (ObjectClosedException ex) {
+            // Similarly to above, but the source Segment (Transaction) has been merged between when getSingleReadResultEntry
+            // (our caller) and redirectedIndex.getSingleReadResultEntry() was invoked. Since we are not holding the lock
+            // while executing this method (due to deadlock considerations), this scenario is plausible. If this does
+            // indeed happen, we need to reissue the read against ourself, in which case an updated result/entry will be
+            // returned.
+            if (!redirectedIndex.closed) {
+                throw ex;
+            }
+            return getSingleReadResultEntry(streamSegmentOffset, maxLength, makeCopy);
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java:1080]: In line with @fpj comment, it may be the case that this catch block does not does what we expect, despite you have already mentioned why testing this may be hard to do.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentServiceNoOpWriteOnlyTests.java [hunk 2]
```diff
@@ -1,97 +0,0 @@
-/**
- * Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentServiceNoOpWriteOnlyTests.java:2]: Can you elaborate the reason to remove these tests?

**Review by RaulGracia — APPROVED** [review]
LGTM, just couple of comments.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentServiceNoOpWriteOnlyTests.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentServiceNoOpWriteOnlyTests.java:2]: These are end-to-end segment store integration tests, which test LTS and recovery from LTS. With No-Op mode there is no data written to LTS so any attempt to read it from there will fail. It was by pure chance that these tests passed when they did, and any attribute or cache eviction that might have happened would have caused it to fail. 

There is no point in doing this kind of test with No-Op, so I removed both of them.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java:1080]: @RaulGracia @fpj Isn't that comment explanatory enough? I cannot write a unit test to deterministically test this path because of this (quote from the comment): `the source Segment (Transaction) has been merged between when getSingleReadResultEntry (our caller) and redirectedIndex.getSingleReadResultEntry() was invoked`.

Those calls execute on the same thread in short sequence, with no breaks. It was the case that in the past they were both protected by a mutex, but I had to remove that protection because of a deadlock we found a while back. So the second call happens outside of that lock. Without introducing code hooks (empty methods that I override in special, test-only subclasses), I cannot stop the execution of the thread so I can simulate this kind of scenario (i.e., merge the other segment). In the real world, the merger happens async, triggered by the OperationProcessor, which runs separately from read execution

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java:1080]: I asked a different question:

https://github.com/pravega/pravega/pull/5472#issuecomment-758589501

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java:1080]: @fpj I added a pretty lengthy comment inside that catch block explaining how we get there. I believe that is pretty self-explanatory.

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java:1080]: The confusion for me is that there are many issues conflated in one PR, and I initially didn't understand why we had changes in `main` code while the code changes are not being tested. You have edited the description to clarify some of the changes, and you have also clarified offline that you are working on a single branch to fix a series of issues with flaky tests and bugs. Thanks for both clarifications.

**Review by fpj — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 3]
```diff
@@ -605,6 +607,17 @@ void commit(DataFrameBuilder.CommitArgs commitArgs) {
             }
         }
 
+        private void queueMemoryCommit(List<List<CompletableOperation>> toAck) {
+            try {
+                toAck.forEach(OperationProcessor.this.commitQueue::add);
+            } catch (Exception ex) {
+                // If we are unable to queue up these operations for whatever reason, we must unregister them from the
+                // CacheUtilizationProvider, otherwise we will be "leaking" bytes (i.e., overcounting).
+                toAck.forEach(l -> l.forEach(this::notifyOperationCommitted));
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:616]: If you look at what that method does, it decrements a byte counter. If we failed the operation we need to subtract its effect from the counter that we use for cache throttling.

[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:616]: Ok, I checked the method and it only adjust pending bytes, so to confirm, you are saying that the adjustment needs to be done independent of whether we can add the operation to the commit queue at this point, yes? There is no other important side-effect, correct? Please confirm that to me.

[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:616]: When we pick operations from the OP queue, we need to check how many bytes they would eventually add to the cache. We use this aggregated amount to calculate how much to throttle (otherwise we risk accepting more data than we can eventually fit into the cache - in cases of ingestion spikes).

We need to unaccount for these bytes when:
1. We add those operations to the cache (commit success)
2. We reject those operations
3. We fail the operations (because of bad Tier 1 writes, because of OP shutting down or other failure reasons).

1 and 2 are already accounted for in `processOperations`. For 3, we covered all the paths of failure except one. The one that was missing was if those operations have been acked from Tier 1 but were in the process of being added to the commit queue; the commit queue has just been closed so we fail them there. This change here plugs this hole.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 4]
```diff
@@ -183,7 +183,10 @@ protected void errorHandler(Throwable ex) {
             // Shutdown exceptions means we are already stopping, so no need to do anything else. For all other cases,
             // record the failure and then stop the OperationProcessor.
             super.errorHandler(ex);
-            stopAsync();
+
+            // Run async to prevent deadlocks. closeQueue() above is the most important thing when shutting down as it
+            // will prevent anything new from being added while also cancelling in-flight requests.
+            this.executor.execute(this::stopAsync);
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:189]: I'm missing something silly here, isn't `stopAsync` asynchronous already?

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java [hunk 5]
```diff
@@ -87,7 +91,7 @@
             .with(ReadIndexConfig.MEMORY_READ_MIN_LENGTH, 0) // Default: Off (we have a special test for this).
             .with(ReadIndexConfig.STORAGE_READ_ALIGNMENT, 1024)
             .build();
-    private static final Duration TIMEOUT = Duration.ofSeconds(20);
+    private static final Duration TIMEOUT = Duration.ofSeconds(60);
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java:94]: Do we expect operations using this timeout to last for a minute or are we just trying to choose a conservative value? 1 minute is a long time for a test.

**Review by fpj — CHANGES_REQUESTED** [review]
A few more clarification questions on the bug fixes, and otherwise it looks good.

File: common/src/main/java/io/pravega/common/util/AbstractDrainingQueue.java [hunk 6]
```diff
@@ -174,6 +175,12 @@ public void add(T item) {
                 synchronized (this.lock) {
                     if (this.pendingTake == result) {
                         this.pendingTake = null;
+                    } else {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/util/AbstractDrainingQueue.java:178]: No. It is a very bad practice to complete a `CompletableFuture` (that others have callbacks registered on) while holding a lock. It invites opportunities for deadlocks.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 7]
```diff
@@ -283,10 +282,12 @@ protected void doStart() {
                     if (ex == null) {
                         // Successful start.
                         log.info("{}: Started.", this.traceObjectId);
-                    } else if (!(Exceptions.unwrap(ex) instanceof ObjectClosedException) || !Services.isTerminating(state())) {
+                    } else if (Services.isTerminating(state())) {
                         // If the delayed start fails, immediately shut down the Segment Container with the appropriate
-                        // exception. We should ignore ObjectClosedExceptions or other exceptions during a shutdown phase
-                        // since that's most likely due to us shutting down.
+                        // exception. However if we are already shut down (or in the process of), it is sufficient to
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:287]: "already shut down" is the correct representation ("to be shut down" == in a state where we are not operating).
"in the process of" is indeed missing "shutting down" but it can be inferred from the rest of the sentence. 

This comment indicates that we can either be totally shut down or be in the process of shutting down (they are different states when it concerns a Service).

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java (hunk 5 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java:94]: I increased the timeout because one of the failed tests reported (that failed with timeout) was not deadlocked or hung on anything. It got interrupted inside a `String.format`, which was inside a for loop, which was happy executing. It was a perfect example of the test getting delayed for whatever reason beyond its control. The test normally takes <1s to run. I suspect that GC pauses or other background tasks on the host VM caused the test to run incredibly slow.

As a rule, I want to standardize test timeouts. Ideally I want to see either 30s or 60s across the board, and enforced via Gradle. Right now we have a combination of timeouts that range from 5s to a few minutes. A task for another day, however.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 4 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:189]: StopAsync initiates an async stop, but the initiation is not async. Furthermore, `stopAsync` acquires a lock (synchronously) which may or may not be already acquired. Normally it is not. However in test cases, if a test fails in a certain way, this lock is acquired by a thread (that caused the failure), then some Future that was also waiting on that operation is failed; this causes the test itself to fail (because it was waiting for the result of that future) which causes the `@Cleanup` to be invoked (i.e., `AutoCloseable.close`) for all the services involved. This causes the `stopAsync` to be invoked from a different thread (`close` must invoke `stopAsync` and await its termination), which causes a deadlock (since `stopAsync` is going to try to acquire the lock that was already acquired - on a different thread).

(See my comment above about why completing a future while holding a lock can cause deadlocks). 

I don't see a way for this to happen in production code. In production code, we have a clear path on how services are shut down in case of failure, and there is no "cycle" that causes an external actor (such as the JUnit test) to try to shut it down again.

This was the cause for several different test timeouts that are linked to this PR.

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java:189]: I'm wondering if we could have instead refactored `doStop` to execute its logic asynchronously.

**Review by fpj — APPROVED** [review]
