### PR TITLE
Issue 5802: Controller fails with OOM on aggressive scaling and transactions.

### LINKED ISSUE #5802: Aggressive scaling and rolling transactions cause Controller to go OOM
**Describe the bug**
Controller fails with OOM on aggressive scaling and rolling transactions.

**To Reproduce**
Start a Pravega cluster and run 2 longevity medium scale workloads one that triggers scaling and the other with rolling transactions both at the same time on this cluster.

**Expected behavior**
Controller should not go OOM

### PR DESCRIPTION
**Pull request by pbelgundi**
**Change log description**  
Controller fails with OOM on aggressive scaling and rolling transactions.
This is because on every scale/rolling-txn operation we compute the number of _splits_ and _merges_ on the set of all epochs for this Stream. This is done so we can emit a metric on the number of splits & merges on the Stream at that point.
This computation is an expensive operation and having a large number of scales and rolling transactions causes us to go OOM. 

**Purpose of the change**  
Fixes #5802

**What the code does**  
Instead of computing the total number of splits/merges on **every scale** we could pre-compute and store the cumulative split/merge count till this Epoch inside the `Epoch Record` when it is created and then just fetch the number from this record.

**How to verify it**  
All Unit, Integration and System Tests should pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java [hunk 1]
```diff
@@ -37,25 +38,52 @@
...
     private final int referenceEpoch;
     private final ImmutableList<StreamSegmentRecord> segments;
     private final long creationTime;
     @Getter(AccessLevel.PRIVATE)
     private final Map<Long, StreamSegmentRecord> segmentMap;
-    
+    /**
+     * Number of splits performed as part of scale operation.
+     */
+    private final long splits;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:53]: is it number of splits in this scale operation or overall so far?

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java [hunk 2]
```diff
@@ -37,25 +38,52 @@
...
+     *
+     * Principle to calculate the number of splits and merges:
+     * 1- An event has occurred if a reference range is present (overlaps) in at least two consecutive target ranges.
+     * 2- If the direction of the check in 1 is forward, then it is a split, otherwise it is a merge.
+     *
+     * @param referenceSegmentsList Reference segment list.
+     * @param targetSegmentsList Target segment list.
+     * @return Number of splits/merges.
+     */
+    public static long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegmentsList, List<StreamSegmentRecord> targetSegmentsList) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:82]: this method doesnt seem fit here as neither of the input params are EpochRecord. we should keep this in its original place.

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java [hunk 3]
```diff
@@ -37,25 +38,52 @@
...
+        return referenceSegmentsList.stream().filter(
+                segment -> targetSegmentsList.stream().filter(target -> target.overlaps(segment)).count() > 1 ).count();
     }
-    
+
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:86]: nit: please revert this and all other lines where only indentation is changed

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:53]: It is overall so far, since the Epoch Record will maintain only cumulative counts.

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:97]: Ok

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:93]: Its a static method, so input params don't need to be members of EpochRecord class.
Its a utility method to find the splits/merges given the segments of earlier and this epoch, I think it fits better here.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 4]
```diff
@@ -533,33 +533,17 @@ private boolean streamCutEqualOrAfter(Map<Long, Long> cut1, Map<StreamSegmentRec
...
-     * 2- If the direction of the check in 1 is forward, then it is a split, otherwise it is a merge.
-     *
-     * @param referenceSegmentsList Reference segment list.
-     * @param targetSegmentsList Target segment list.
-     * @return Number of splits/merges.
-     */
-    private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegmentsList, List<StreamSegmentRecord> targetSegmentsList) {
-        return referenceSegmentsList.stream().filter(
-                segment -> targetSegmentsList.stream().filter(target -> target.overlaps(segment)).count() > 1 ).count();
+                .map(record -> {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:536]: i dont see any changes here other than indentation, please revert this.

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:53]: please make that explicit in the comment above that its cumulative count

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 2 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:93]: then it should be in a utility class and not in an unrelated data class (epoch record).
there is a utility class called record helper that can be used for this. 

secondly, moving this method out of persistent stream base should be done if we see this method being used in multiple places.. otherwise it can be a private method there the way it is.

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:53]: Sure.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 5]
```diff
@@ -1,11 +1,11 @@
 /**
  * Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
- *
+ * <p>
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: nit: please revert changes to the license.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 6]
```diff
@@ -130,12 +132,12 @@ public String getScopeName() {
 
         long creationTime = createStreamResponse.getTimestamp();
         final ImmutableList.Builder<StreamSegmentRecord> builder = ImmutableList.builder();
-        
+
         IntStream.range(0, numSegments).boxed()
-                 .forEach(x -> builder.add(newSegmentRecord(0, startingSegmentNumber + x, creationTime,
-                                                                    x * keyRangeChunk, (x + 1) * keyRangeChunk)));
+                .forEach(x -> builder.add(newSegmentRecord(0, startingSegmentNumber + x, creationTime,
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: nit: revert

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 7]
```diff
@@ -173,19 +175,19 @@ public String getScopeName() {
...
-                            StreamTruncationRecord previous = existing.getObject();
-                            // check greater than
-                            Exceptions.checkArgument(streamCutEqualOrAfter(streamCut, span, previous.getStreamCut(), previous.getSpan()),
-                                    "StreamCut", "Supplied streamcut is behind previous truncation point");
-
-                            return computeTruncationRecord(previous, streamCut, span)
-                                    .thenCompose(prop ->
-                                            Futures.toVoid(setTruncationData(new VersionedMetadata<>(prop, existing.getVersion()))));
-                        });
+                            .thenCompose(epochs -> {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: nit: revert

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 8]
```diff
@@ -199,8 +201,8 @@ private boolean streamCutEqualOrAfter(Map<Long, Long> cut1, Map<StreamSegmentRec
                                 cut1.get(e1.getKey().segmentId()) < cut2.get(e2.getKey().segmentId()))
                                 || (e2.getKey().overlaps(e1.getKey()) && e1.getValue() < e2.getValue())));
     }
-    
-    private CompletableFuture<StreamTruncationRecord> computeTruncationRecord(StreamTruncationRecord previous, 
+
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:202]: nit: revert

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 9]
```diff
@@ -212,19 +214,19 @@ private boolean streamCutEqualOrAfter(Map<Long, Long> cut1, Map<StreamSegmentRec
...
-                                             ImmutableSet.Builder<Long> builder = ImmutableSet.builder();
-                                             segmentsBetween.stream().map(StreamSegmentRecord::segmentId)
-                                                            .filter(x -> !streamCut.containsKey(x))
-                                                            .forEach(builder::add);
-
-                                             return new StreamTruncationRecord(ImmutableMap.copyOf(streamCut), span, previous.getDeletedSegments(), 
-                                                     builder.build(),
-                                                     previous.getSizeTill() + sizeBetween, true);
-                                         }));
+                .thenCompose(segmentsBetween -> sizeBetweenStreamCuts(previous.getStreamCut(), streamCut, segmentsBetween)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:215]: and here

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 10]
```diff
@@ -259,53 +261,53 @@ private boolean streamCutEqualOrAfter(Map<Long, Long> cut1, Map<StreamSegmentRec
...
-                                } else if (e2.getKey().overlaps(e1.getKey())) {
-                                    // overlapping segment. compare segment id.
-                                    comparison = Long.compare(e1.getKey().segmentId(), e2.getKey().segmentId());
-                                } else {
-                                    continue;
-                                }
-                                foundGt = !foundGt ? comparison > 0 : foundGt;
-                                foundLt = !foundLt ? comparison < 0 : foundLt;
+                .thenApply(v -> {
+                    ImmutableMap<StreamSegmentRecord, Integer> span1 = span1Future.join();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:271]: revert please

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java [hunk 11]
```diff
@@ -70,23 +92,22 @@ public static EpochRecord fromBytes(final byte[] record) {
...
     public Set<Long> getSegmentIds() {
         return segmentMap.keySet();
     }
 
     public StreamSegmentRecord getSegment(long segmentId) {
         return segmentMap.get(segmentId);
     }
-    
+
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:103]: nit: revert

File: controller/src/main/java/io/pravega/controller/store/stream/ScaleMetadata.java [hunk 12]
```diff
@@ -10,7 +10,6 @@
 package io.pravega.controller.store.stream;
 
 import lombok.Data;
-
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ScaleMetadata.java:13]: revert

File: controller/src/main/java/io/pravega/controller/store/stream/Stream.java [hunk 13]
```diff
@@ -704,4 +704,6 @@
      * is strictly before the supplied streamcut. 
      */
     CompletableFuture<StreamCutReferenceRecord> findStreamCutReferenceRecordBefore(Map<Long, Long> streamCut, RetentionSet retentionSet);
+
+    CompletableFuture<SimpleEntry<Long, Long>> getSplitMergeCountsTillEpoch(EpochRecord epochRecord);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/Stream.java:708]: please add javadoc

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java [hunk 14]
```diff
@@ -1,11 +1,11 @@
 /**
  * Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
- *
+ * <p>
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java:3]: revert

File: controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java [hunk 15]
```diff
@@ -861,7 +861,7 @@ private void concurrentDistinctScaleRun(String stream, String funcToWaitOn, bool
         streamStore2.close();
     }
 
-    @Test(timeout = 30000)
+    @Test(timeout = 50000)
```
Comment (shiveshr) [inline controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java:864]: why are we increasing this timeout?

**Review by shiveshr — CHANGES_REQUESTED** [review]
some nitpicks for indentation changes

File: controller/src/main/java/io/pravega/controller/store/stream/Stream.java (hunk 13 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/Stream.java:715]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 16]
```diff
@@ -1036,16 +1035,29 @@ protected ReaderGroup getReaderGroup(String scope, final String name, RGOperatio
...
-            AtomicLong totalNumMerges = new AtomicLong(0L);
-            scaleMetadataList.forEach(x -> {
-                totalNumMerges.addAndGet(x.getMerges());
-                totalNumSplits.addAndGet(x.getSplits());
-            });
-
-            return new SimpleEntry<>(totalNumSplits.get(), totalNumMerges.get());
+        Stream stream = getStream(scopeName, streamName, context);
+        return stream.getActiveEpoch(true).thenCompose(lastEpoch -> stream.getSplitMergeCountsTillEpoch(lastEpoch));
+        /*
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 17]
```diff
@@ -533,33 +533,17 @@ private boolean streamCutEqualOrAfter(Map<Long, Long> cut1, Map<StreamSegmentRec
...
-     *
-     * Principle to calculate the number of splits and merges:
-     * 1- An event has occurred if a reference range is present (overlaps) in at least two consecutive target ranges.
-     * 2- If the direction of the check in 1 is forward, then it is a split, otherwise it is a merge.
-     *
-     * @param referenceSegmentsList Reference segment list.
-     * @param targetSegmentsList Target segment list.
-     * @return Number of splits/merges.
-     */
-    private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegmentsList, List<StreamSegmentRecord> targetSegmentsList) {
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 18]
```diff
@@ -1100,7 +1084,7 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
                         // sealed segments
                         ImmutableList.Builder<StreamSegmentRecord> sealedSegmentsBuilder = ImmutableList.builder();
                         epochTransition.getSegmentsToSeal().forEach(x -> sealedSegmentsBuilder.add(currentEpoch.getSegment(x)));
-                        
+
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 6 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 11 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/ScaleMetadata.java (hunk 12 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/ScaleMetadata.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java (hunk 14 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/records/EpochRecord.java]: fixed

File: controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java (hunk 15 above)
Comment (pbelgundi) [reply controller/src/test/java/io/pravega/controller/server/eventProcessor/ScaleRequestHandlerTest.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 19]
```diff
@@ -1118,10 +1118,13 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
                         ImmutableList<StreamSegmentRecord> newSegments = newSegmentsBuilder.build();
                         builder.addAll(newSegments);
                         // epoch record
-                        EpochRecord epochRecord = new EpochRecord(epochTransition.getNewEpoch(), epochTransition.getNewEpoch(), 
-                                builder.build(), time);
-
-                        HistoryTimeSeriesRecord timeSeriesRecord = 
+                        SimpleEntry<Long, Long> splitMergeCountLastEpoch = getSplitMergeCountsTillEpoch(currentEpoch).join();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1121]: we should not be blocking here.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1121]: we should get the future and add callbacks to perform any subsequent processing.. 
we use join in the code only in following pattern:
create future1 and future2..
```
future1 = getFuture();
future2 = getFuture();
CompletableFuture.allOf(future1, future2) 
    .thenApply(v -> {// chain subsequent processing to completion of "both" futures.
           result1 = future1.join(); // this join is going to return the result immediately without blocking as the result is available with future1 which is completed for sure.
           result2 = future2.join(); // same here
           // use my results to do some computation.
     });
```

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 20]
```diff
@@ -1118,10 +1118,13 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
...
+                        ImmutableList<StreamSegmentRecord> epochSegments = builder.build();
+                        List<StreamSegmentRecord> newEpochSegments = epochSegments.stream().collect(Collectors.toList());
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1123]: dont epoch segments capture new epoch segments? because we are building the new segment list in that builder.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 21]
```diff
@@ -1133,6 +1136,39 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
...
                 });
     }
+
+    @Override
+    public CompletableFuture<SimpleEntry<Long, Long>> getSplitMergeCountsTillEpoch(EpochRecord epochRecord) {
+        if (epochRecord.hasSplitMergeCounts()) {
+            return CompletableFuture.completedFuture(new SimpleEntry<>(epochRecord.getSplits(), epochRecord.getMerges()));
+        } else {
+            //migration case: build the cumulative count from all previous epochs
+            return fetchEpochs(0, epochRecord.getEpoch(), true).thenApply(this::mapToScaleMetadata)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1146]: even in this case, i was thinking we can actually do better -- we dont need to create each of the epochs. fetchEpochs actually computes epochs from history timeseries. 
what we need is the history timeseries only. and doing one pass on history timeseries will enable us to get the splits and merges count. so we dont actually have to do the fetchEpochs and then maptoscalemetadata here. which will even avoid lots of objects being created in memory. It will be O(number of segments) memory that we will use if we just travese history time series as opposed to working with epoch records.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1146]: we dont need to do this now.. i have created #5885 that we can work on for 0.10.0 and it will also help with streamcut related operations too.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 22]
```diff
@@ -1257,11 +1293,21 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
                                             committingTxnRecord.getNewActiveEpoch()),
                                             timeStamp + 1, x.getKeyStart(), x.getKeyEnd())));
 
-                            EpochRecord duplicateTxnEpoch = new EpochRecord(committingTxnRecord.getNewTxnEpoch(), 
-                                    transactionEpochRecord.getReferenceEpoch(), duplicateTxnSegmentsBuilder.build(), timeStamp);
-
+                            SimpleEntry<Long, Long> splitMergeCountTillLastEpoch = getSplitMergeCountsTillEpoch(transactionEpochRecord).join();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1296]: same comment about `join`

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 20 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1123]: epochSegments is an ImmutableList and `findSegmentSplitsMerges` needs a List as input, hence the conversion.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 21 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1146]: Ok. got it.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 22 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 20 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 19 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed as suggested.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 23]
```diff
@@ -1254,34 +1290,47 @@ private boolean isStreamCutValidInternal(Map<Long, Long> streamCut, int epochLow
...
-                                    .thenCompose(x -> updateHistoryTimeSeries(timeSeriesRecordActiveEpoch))
-                                    .thenCompose(x -> createSegmentSealedEpochRecords(
-                                            activeEpochRecord.getSegments().stream().map(StreamSegmentRecord::segmentId)
-                                                             .collect(Collectors.toList()), duplicateTxnEpoch.getEpoch()))
-                                    .thenCompose(x -> createSegmentSealedEpochRecords(
-                                            duplicateTxnEpoch.getSegments().stream().map(StreamSegmentRecord::segmentId)
-                                                             .collect(Collectors.toList()), duplicateActiveEpoch.getEpoch()));
-                        })
-                        .thenCompose(r -> updateSealedSegmentSizes(sealedTxnEpochSegments)));
+                                                    committingTxnRecord.getNewActiveEpoch()),
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java:1293]: i dont see any code change in this block. could you please revert this. thanks

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java [hunk 24]
```diff
@@ -96,6 +96,21 @@
         this.executor = executor;
     }
 
+    @VisibleForTesting
+    PravegaTablesStreamMetadataStore(CuratorFramework curatorClient, ScheduledExecutorService executor,
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java:100]: do we need this new constructor? can we reuse one of the existing constructors that takes segment helper for which we have a test mock that mocks the underlying store's behaviour.

**Review by shiveshr — APPROVED** [review]
LGTM, some minor comments

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java (hunk 24 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStreamMetadataStore.java:100]: Yes, needed to create this constructor, because I had to mock getCachedData() on PravegaTablesStoreHelper. I tried mocking getEntry() on SegmentHelper mock, but it required metadataTableName which is not available in the test case and without the table name, just with the 'key' for getEntry set to "epoch-0" the mock method did not return the expected value.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 23 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: fixed.
