### PR TITLE
Issue 6210: Configure REST ServerConfig's (SegmentStore) TLS Certificates in JKS format

### LINKED ISSUE #6210: Segmentstore's health REST endpoint doesn't return any response if TLS is enabled.
**Describe the bug**
Segmentstore's health api REST endpoint doesn't return any response when TLS is enabled in pravega.

- Both standalone and distributed modes are affected with this. When trying to hit `https://localhost:9092/v1/health/liveness` got the following logs

Logs:
```
2021-08-05 03:55:26,025 58129 [ControllerServiceMain] INFO  i.p.c.server.ControllerServiceMain - Controller Services started successfully.
Aug 05, 2021 3:55:32 AM org.glassfish.grizzly.filterchain.DefaultFilterChain execute
WARNING: GRIZZLY0013: Exception during FilterChain execution
org.glassfish.grizzly.ssl.SSLContextConfigurator$GenericStoreException: java.io.IOException: toDerInputStream rejects tag type 66
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:511)
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:185)
        at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:162)
        at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1112)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:79)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:66)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:391)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:360)
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:324)
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:255)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: toDerInputStream rejects tag type 66
        at java.base/sun.security.util.DerValue.toDerInputStream(DerValue.java:873)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1997)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.loadBytes(SSLContextConfigurator.java:644)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:476)
        ... 20 more
```

**To Reproduce**
1. Enabled `TLS` in pravega.
2. Start Pravega standalone - `./gradlew startStandalone`
3. Run `curl -s -k -X GET https://localhost:9092/v1/health/liveness` in terminal.
4. Doesn't return any response and above error can be seen in standalone logs.

**Screenshots**

**Additional information**

- Issue is only in segmentstore Health endpoint that too when TLS is enabled.
- Controller's health endpoint works fine with TLS enabled and disabled.
- With the logs it seems to be a issue with Certificates.

### PR DESCRIPTION
**Pull request by kotlasaicharanreddy**
Signed-off-by: SaiCharan <kotlasaicharan@yahoo.com>

**Change log description**  

- `restServerConfig`  in `ServiceConfig` class was receiving TLS related certificates and keys in `.pem` format.
- Because of the above point, `restListeningPort ` of SegmentStore was not accessible when `TLS ` is `enabled`.
- REST Interface accepts certificates and keys only in `.jks` format.
- Added new properties which loads the TLS Certificates and keys.

**Purpose of the change**  
Fixes #6210 

**What the code does**  

- Added two new properties in `ServiceConfig` class : 
      1. REST_KEYSTORE_FILE 
      2. REST_KEYSTORE_PASSWORD_FILE 
- These properties are passed into `restServerConfig`  as it requires its certificate and keys in Java JKS format.

**How to verify it**  
Invoking REST's `liveness` or `readiness` endpoint of Segmentstore with TLS enabled should return `"true"` as response. 
Ex: In Standalone mode : `curl -s -k -X GET https://localhost:9092/v1/health/liveness` command returns response: `true`

### CODE REVIEW

**Review by SrishT — APPROVED** [review]
The changes LGTM. I have also verified these changes in a distributed deployment, and it does fix the issue we observed earlier.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java [hunk 1]
```diff
@@ -58,6 +58,8 @@
     public static final Property<String> REST_LISTENING_HOST = Property.named("rest.listener.host", "localhost");
     public static final Property<Integer> REST_LISTENING_PORT = Property.named("rest.listener.port", 6061);
     public static final Property<Boolean> REST_LISTENING_ENABLE = Property.named("rest.listener.enable", true);
+    public static final Property<String> REST_KEYSTORE_FILE = Property.named("security.tls.server.keyStore.location", "", "rest.tlsKeyStoreFile");
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java:61]: You don't need the third argument to `Property.named` here as this is not a setting that has been upgraded from 0.8 (when we renamed all these settings). Let's remove the `rest.tlsKeyStoreFile` (this line) and `rest.tlsKeyStorePasswordFile` (next line).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java [hunk 2]
```diff
@@ -417,11 +425,13 @@ private ServiceConfig(TypedProperties properties) throws ConfigurationException
...
                 .tlsEnabled(properties.getBoolean(ENABLE_TLS))
                 .tlsProtocolVersion(TLSProtocolVersion.parse(properties.get(TLS_PROTOCOL_VERSION)))
-                .keyFilePath(properties.get(KEY_FILE))
-                .keyFilePasswordPath(properties.get(KEY_PASSWORD_FILE))
+                .keyFilePath(properties.get(REST_KEYSTORE_FILE))
+                .keyFilePasswordPath(properties.get(REST_KEYSTORE_PASSWORD_FILE))
                 .build();
         this.restServerEnabled = properties.getBoolean(REST_LISTENING_ENABLE);
         this.healthCheckInterval = Duration.ofSeconds(properties.getInt(HEALTH_CHECK_INTERVAL_SECONDS));
+        this.restKeyStoreFile = properties.get(REST_KEYSTORE_FILE);
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java:433]: Why do we need to keep these properties twice? (Once here and once in `restServerConfig`. Since these are used only in the latter, let's get rid of these two extra fields.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java (hunk 1 above)
Comment (kotlasaicharanreddy) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java:61]: Fixed, removed the legacy names.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java (hunk 2 above)
Comment (kotlasaicharanreddy) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java:433]: They are used again to initialize the class variables restkeyStoreFile and restKeyStorePasswordFile of Service Class

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java:433]: They aren't used anywhere from what I see. You declared them in this PR and outside of this class they aren't used anywhere else. I was referring to the class variables - why do you need them when they're already accesisible via the `RestConfig`?

Comment (kotlasaicharanreddy) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java]: Fixed. Yes they were never used except in this class. Removed them. Thanks.

**Review by andreipaduroiu — APPROVED** [review]
