### PR TITLE
Issue 1718: Fix failing unit tests in Jenkins

### LINKED ISSUE #1718: Build Failure: jenkins: io.pravega.segmentstore.server.containers.StreamSegmentMapperTests.testGetOrAssignStreamSegmentIdWithMetadataLimit
**Problem description**
Observing the following build failure on jenkins.
Error Message

java.lang.AssertionError: Unexpected outcome when trying to map a segment name to a full metadata that cannot be cleaned. Exception thrown was of unexpected type: io.pravega.segmentstore.contracts.TooManyActiveSegmentsException: [Container 2] The maximum number of active Segments (0) has been reached..

Stacktrace

```
java.lang.AssertionError: Unexpected outcome when trying to map a segment name to a full metadata that cannot be cleaned. Exception thrown was of unexpected type: io.pravega.segmentstore.contracts.TooManyActiveSegmentsException: [Container 2] The maximum number of active Segments (0) has been reached..
	at org.junit.Assert.fail(Assert.java:88)
	at io.pravega.test.common.AssertExtensions.assertThrows(AssertExtensions.java:86)
	at io.pravega.segmentstore.server.containers.StreamSegmentMapperTests.testGetOrAssignStreamSegmentIdWithMetadataLimit(StreamSegmentMapperTests.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**

StreamSegmentMapperTests

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Test 1: `StreamSegmentMapperTests.testGetOrAssignStreamSegmentIdWithMetadataLimit`
- It turns out the fix merged with PR #1732 did not address the underlying issue, which was that subsequent requests would piggyback on the first one and never actually invoke the `DurableLog.add()` method which would've thrown the exception (and thus recorded that it happened). 
- This was fixed now by using different segment names, so we don't end up piggybacking on previous segments' callbacks.

Test 2: `ReadIndex.triggerFutureReads`
- This was not due to the unit test, rather it looks like a bug in the code with the original implementation of a fix for a unit test in the past. The conditions were reversed (compared to the description).

**Purpose of the change**
Fixes #1718.

**What the code does**
Bugfix.

**How to verify it**
Unit tests must pass on Travis and Jenkins.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java [hunk 1]
```diff
@@ -199,11 +199,11 @@ public void triggerFutureReads(Collection<Long> streamSegmentIds) {
...
                 // to invoking triggerFutureReads, the StreamSegmentReadIndex has already been closed. If this is the case,
                 // ignore the error.
-                // This is possible in the following scenario: for a Transaction, we have an Append, followed by a Merge;
-                // the Append makes this index eligible for triggering future reads, and the Merge (once committed to Storage)
+                // This is possible in the following scenario: for a Transaction, we have an Append/Seal, followed by a Merge;
+                // the Append/Seal makes this index eligible for triggering future reads, and the Merge (once committed to Storage)
                 // will close it. If the StorageWriter is sufficiently fast in comparison to the OperationProcessor callbacks
                 // (which could be the case for in-memory unit tests), it may trigger this condition.
-                if (getIndex(segmentId) == null) {
+                if (getIndex(segmentId) != null) {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: This is quite a change! Is there a unit test verifying this now?

Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: No. I can't verify this because it's due to a bunch of things happening at the same time, in a specific order, the sequence of which I have no control over. If you read the comment right above this line, you'd see that it said the exact opposite of what the code was doing. This is just fixing it

Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/ContainerReadIndex.java]: I agree, and I assume this change is innocent. But I am worried that there are whole code paths that we can't add tests for. I get not catching the problem the first time, but perhaps it's worth taking some time to work out if there is a way to refactor things here so they can be more easily tested.
