### PR TITLE
Issue 5171: (Bugfix) Ensure ByteStreamReader can read from deleted and recreated streams

### LINKED ISSUE #5171: ByteStreamReader cannot read from deleted and recreated stream
**Problem description**
When a stream used with the byte stream client is deleted and recreated, it can be used by a new ByteStreamWriter, but it cannot be used with a new ByteStreamReader.

The ByteStreamReader reports:
```
[nioEventLoopGroup-21-2] INFO io.pravega.client.netty.impl.FlowHandler - Connection established with endpoint 127.0.1.1 on channel [id: 0x4886b167, L:/127.0.0.1:56977 - R:/127.0.1.1:6000]
[nioEventLoopGroup-21-2] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=10, lowVersion=5)
[nioEventLoopGroup-21-2] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Received noSuchSegment No such segment: tutorial/int-bytestream/0.#epoch.0
[nioEventLoopGroup-21-2] WARN io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Exception while reading from Segment tutorial/int-bytestream/0.#epoch.0 at offset 0 :
io.pravega.client.segment.impl.SegmentTruncatedException: Segment no longer exists.
```

When a stream is deleted and recreated, it's initial segment ID won't be 0, as it was in its 1st creation. You can see the ByteStreamWriter writing to the correct segment ID:

```
[nioEventLoopGroup-21-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Received appendSetup WireCommands.AppendSetup(type=APPEND_SETUP, requestId=347892350976, segment=tutorial/int-bytestream/1.#epoch.0, writerId=713e78ac-5a09-4938-8f07-f1be08a75cf8, lastEventNumber=-9223372036854775808)
```

**Problem location**
ByteStreamReader on a recreated stream.

Tested on 0.7.1 and 0.8.0-SNAPSHOT.

**Suggestions for an improvement**
Use the correct segment ID as the initial segment when reading from a recreated byte stream.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Ensure ByteStreamReader can read from deleted and recreated streams

**Purpose of the change**  
Fixes #5171 

**What the code does**  
- Fetch the segment details from the controller instead of reading directly from segment 0.

**How to verify it**  
All the existing and newly added tests should continue to pass.

### CODE REVIEW

**Comment by eolivelli** [comment]
@shrids 
why do you think that there is no need to add a new testcase ?
is there any existing test case that reproduces the case ?
and if there is one, why is it passing ?

File: test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java [hunk 1]
```diff
@@ -280,7 +281,47 @@ public void testBlockingRead() throws IOException {
...
+        verify_byte_client_read_write(scope, stream);
+        // delete the stream and recreate
+        assertTrue("Seal stream operation failed", streamManager.sealStream(scope, stream));
+        assertTrue("Delete Stream operation failed", streamManager.deleteStream(scope, stream));
+        assertTrue("Recreate stream failed", streamManager.createStream(scope, stream, config));
+        // verify read and write.
+        verify_byte_client_read_write(scope, stream);
+    }
+
+    private void verify_byte_client_read_write(String scope, String stream) {
```
Comment (eolivelli) [inline test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java:307]: please use Java conventions for method names:
verifyByteClientReadWrite

**Review by eolivelli — CHANGES_REQUESTED** [review]
just last nit from my side

File: test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java (hunk 1 above)
Comment (shrids) [reply test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java]: fixed it.

**Review by eolivelli — APPROVED** [review]
LGTM

File: client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java [hunk 2]
```diff
@@ -48,16 +48,11 @@
...
-    private ByteStreamReader createByteStreamReaders(Segment segment) {
-        String delegationToken = Futures.getAndHandleExceptions(controller.getOrRefreshDelegationTokenFor(segment.getScope(),
-                                                                                                          segment.getStream()
-                                                                                                                 .getStreamName()),
-                                                                RuntimeException::new);
-
-        DelegationTokenProvider tokenProvider = DelegationTokenProviderFactory.create(delegationToken, controller, segment);
+        StreamSegments segments = Futures.getThrowingException(controller.getCurrentSegments(scope, streamName));
+        Preconditions.checkState(segments.getNumberOfSegments() > 0, "Stream is sealed");
+        Preconditions.checkState(segments.getNumberOfSegments() == 1, "Stream is configured with more than one segment");
```
Comment (derekm) [inline client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java:53]: If we want a version of this fix to go into 0.7.2, we will have to use `segments.getSegments().size()` here.

**Review by derekm — APPROVED** [review]
Thanks for addressing this so quickly!

File: client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java [hunk 3]
```diff
@@ -48,16 +48,11 @@
...
-
-    private ByteStreamReader createByteStreamReaders(Segment segment) {
-        String delegationToken = Futures.getAndHandleExceptions(controller.getOrRefreshDelegationTokenFor(segment.getScope(),
-                                                                                                          segment.getStream()
-                                                                                                                 .getStreamName()),
-                                                                RuntimeException::new);
-
-        DelegationTokenProvider tokenProvider = DelegationTokenProviderFactory.create(delegationToken, controller, segment);
+        StreamSegments segments = Futures.getThrowingException(controller.getCurrentSegments(scope, streamName));
+        Preconditions.checkState(segments.getNumberOfSegments() > 0, "Stream is sealed");
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java:52]: Why is it an error to create a reader on a sealed stream?

Comment (shrids) [reply client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java]: Good catch, fixed it.

File: client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java [hunk 4]
```diff
@@ -48,7 +51,11 @@
 
     @Override
     public ByteStreamReader createByteStreamReader(String streamName) {
-        return createByteStreamReaders(new Segment(scope, streamName, 0));
+        // Fetch the segments pointing to the current HEAD of the stream.
+        Map<Segment, Long> segments = Futures.getThrowingException(controller.getSegmentsAtTime(Stream.of(scope, streamName), 0L));
```
Comment (derekm) [inline client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java:55]: Will this correctly handle truncated streams? Is timestamp here the same as epoch?

Comment (shrids) [reply client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java:55]: yes, this API returns the segment pointing to the HEAD of the stream even for truncated streams.

File: client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java [hunk 5]
```diff
@@ -48,7 +51,11 @@
...
+        Preconditions.checkState(segments.size() == 1, "Stream is configured with more than one segment or has none");
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java:56]: For debug-ability it would be good to have two different errors or include the size in the error message.

**Review by tkaitchuck — APPROVED** [review]

File: client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java (hunk 5 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/byteStream/impl/ByteStreamClientImpl.java]: improved it.
