### PR TITLE
Issue 7209: Makes Connect Timeout configurable for system test

### LINKED ISSUE #7209: System test are failing due to some timeout exception
**Describe the bug**
Failover System test are failing due to some timeout issue. This timeout is passed from revisionStreamClientimpl.java

**To Reproduce**
Run the system test 

**Additional information**
```023-08-17 09:58:09,200 98955 [BookieFailoverTest-main-10] ERROR i.p.t.system.AbstractReadWriteTest - Test exception in reading events: 
io.pravega.client.segment.impl.ServerTimeoutException: Timeout occurred while reading the segment Info for segment {} from revision {}
	at io.pravega.client.state.impl.RevisionedStreamClientImpl.readFrom(RevisionedStreamClientImpl.java:155)
	at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:88)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.fetchUpdatesIfNeeded(ReaderGroupStateManager.java:359)
	at io.pravega.client.stream.impl.ReaderGroupStateManager.getCheckpoint(ReaderGroupStateManager.java:478)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.updateGroupStateIfNeeded(EventStreamReaderImpl.java:289)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:148)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:133)
	at io.pravega.test.system.AbstractReadWriteTest.lambda$startReading$5(AbstractReadWriteTest.java:284)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:197)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by a6dulaleem**
**Change log description**  
This PR is created to solve the timeout issue happening with failover system test. This PR changes following 

- Make ConnectTimout Configurable for system test
- Set 2 minute timeout for all the system test 

**Purpose of the change**  
fixes #7209 

**What the code does**  
Set Timeout for failover to Two minutes and make it configurable for system test

**How to verify it**  
Run the system test and All test should work fine

### CODE REVIEW

File: client/src/main/java/io/pravega/client/EventStreamClientFactory.java [hunk 1]
```diff
@@ -137,6 +137,29 @@ static EventStreamClientFactory withScope(String scope, ClientConfig config) {
...
+     *
+     * @param readerId A unique name (within the group) for this reader.
+     * @param readerGroup The name of the group to join.
+     * @param s The serializer for events.
+     * @param config The reader's configuration.
+     * @param clientConfig The Client's Configuration.
+     * @param <T> The type of events.
+     * @return Newly created reader object that is a part of reader group
+     */
+    <T> EventStreamReader<T> createReader(String readerId, String readerGroup, Serializer<T> s, ReaderConfig config, ClientConfig clientConfig);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/EventStreamClientFactory.java:161]: This is not needed. The client config is already available to the implementation of this method as a member variable passed in above on line 64.

**Review by tkaitchuck — CHANGES_REQUESTED** [review]

**Review by tkaitchuck — APPROVED** [review]
Change looks good. I do worry that if the system tests are running into timeouts here, real deployments might hit them under similar circumstances. Do we have an issue to track the investigation into that?

**Comment by a6dulaleem** [comment]
> Change looks good. I do worry that if the system tests are running into timeouts here, real deployments might hit them under similar circumstances. Do we have an issue to track the investigation into that?

Yeah I created One
https://github.com/pravega/pravega/issues/7221
