### PR TITLE
Issue 5100: In Integration Tests, KVTable Creation should fail when partition count is 0

### LINKED ISSUE #5100: Integration tests pass when creating a KeyValueTable with 0 partitions
**Problem description**
Pravega Integration Tests, create a KeyValueTable successfully with 0 partitions in the KeyValueTable configuration.
This not expected as '0' is an invalid value for number of partitions and so KVTable creation should fail with "IllegalArgumentException"

**Problem location**
Integration tests for creating a KVTable with 0 partitions pass

**Suggestions for an improvement**
Integration tests use "LocalController" implementation of "Controller" interface, which is **not** used by client. 
The Client uses ControllerImpl implementation of Controller interface which has a check for partitionCount and hence the table creation errors out when using ControllerImpl with '0' partitionCount.
As such this is not a real code issue but only an issue in the Integration Tests.

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Integration tests use "LocalController" implementation of "Controller" interface, which is not used by the client.
The Client uses ControllerImpl implementation of Controller interface which has a check for partitionCount and hence the table creation errors out when using ControllerImpl with '0' partitionCount.
However, LocalController does not have this check and so creates the KVTable successfully even with a parititonCount=0.

**Purpose of the change**  
Fixes #5100

**What the code does**  
Added a check to ControllerService to check for partitionCount > 0 and throw and IllegalArgumentException if it is <=0.

**How to verify it**  
Added a new UT to ControllerServiceImplTest to cover the 0 partitionCount scenario.
Added a new test case to Integration Tests for creating a KeyValueTable with partitionCount 0.
Both above tests should return IllegalArgumentException for partitionCount=0.
All other unit and integration tests should pass.

### CODE REVIEW

File: client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java [hunk 1]
```diff
@@ -1898,6 +1898,11 @@ public void testCreateKeyValueTable() throws Exception {
                 KeyValueTableConfiguration.builder().partitionCount(1).build());
         AssertExtensions.assertFutureThrows("Server should throw exception",
                 createKVTableStatus, Throwable -> true);
+
+        createKVTableStatus = controllerClient.createKeyValueTable("scope1", "kvtable6",
+                KeyValueTableConfiguration.builder().partitionCount(0).build());
+        AssertExtensions.assertFutureThrows("Server should throw exception",
+                createKVTableStatus, Throwable -> true);
```
Comment (shiveshr) [inline client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java:1905]: it is better to have a stronger predicate check which looks for expected exception

**Review by shiveshr — APPROVED** [review]
LGTM, one minor comment

File: client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java (hunk 1 above)
Comment (pbelgundi) [reply client/src/test/java/io/pravega/client/control/impl/ControllerImplTest.java]: Sure. Fixed.
