### PR TITLE
Issue 6281: Reduce connection pool size in Controller

### LINKED ISSUE #6281: Java OOM in pravega-controller
**Describe the bug**
If we use the high number of SSs, we will see the Java OOM in pravega-controller because of the high number of connections between the pravega-controller and segment stores.
By default, in the code there are 10 connections per SS.

**To Reproduce**
1. Deploy pravega with 54 SSs.
2. Run the benchmark workload during the long period (12+ hours). 
3. Hit the OOM exception in pravega-controller:
```
2021-09-05 15:00:00,230 24035209 [clientInternal-1-2] WARN  i.p.c.connection.impl.RawClient - Closing connection to segment null with exception
io.pravega.shared.protocol.netty.ConnectionFailedException: java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at io.pravega.client.connection.impl.ConnectionPoolImpl.lambda$getClientConnection$3(ConnectionPoolImpl.java:159)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:186)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        ... 6 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
        at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:286)
        at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:39)
        at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144)
        at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:59)
        at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:34)
        at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139)
        at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
        at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168)
        at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:159)
        at io.netty.buffer.Unpooled.buffer(Unpooled.java:118)
        at io.pravega.client.connection.impl.CommandEncoder.<init>(CommandEncoder.java:84)
        at io.pravega.client.connection.impl.TcpClientConnection.lambda$connect$1(TcpClientConnection.java:221)
        at io.pravega.client.connection.impl.TcpClientConnection$$Lambda$706/0x0000000100680440.get(Unknown Source)
        ... 6 common frames omitted
```

**Screenshots**
You will hit the heap memory limit (1 GB) in the Pravega System dashboard for the controller pod:
image2021-9-6_15-42-14

**Additional information**
Add any other information about the problem here, including the root cause if known.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Sets to 1 the number of connections per Segment Store in Controller connection pool.

**Purpose of the change**  
Fixes #6281.

**What the code does**  
Sets to 1 the max connections per Segment Store in the Controller connection pool via `ClientConfig`. In Controller, having more connections does not provide any significant performance gain, while it may be resource consuming in scenarios with tens of Segment Stores.

Also, retired `SegmentStoreConnectionManager` class as it is not used in the whole project (seems to have been replaced by connection pool).

**How to verify it**  
Only configuration changes, all tests should be working as before.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 1]
```diff
@@ -252,7 +252,8 @@ protected void startUp() {
                 clientConfigBuilder.enableTlsToSegmentStore(tlsEnabledForSegmentStore.get());
             }
             
-            ClientConfig clientConfig = clientConfigBuilder.build();
+            // Use one connection per Segment Store to save up resources.
+            ClientConfig clientConfig = clientConfigBuilder.maxConnectionsPerSegmentStore(1).build();
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java:256]: It would be super nice if we could make this configurable.

**Comment by shrids** [comment]
The Event writers spawned inside the controller (e.g: for streamMetadataTask, tableMetadataTasks) can have connection pooling turned on, this would also reduce the connections spawned by the controller.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java (hunk 1 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java:256]: If having more connections is going to waste resources without adding any performance benefit in this case, I don't see the point of adding yet another configuration parameter. I also don't know how many users will use that knob and, for those who use it, if they will know what to do with it. Overall, in this specific case, I think that 1 is the right setting as changing it can give just resource consumption (leading to OOM) and there is no observed benefit from increasing it.

**Comment by RaulGracia** [comment]
@shrids I have turned on connection pooling for EventWriters.

**Review by andreipaduroiu — APPROVED** [review]
LGTM. @shrids this is in your hands now.

File: controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java [hunk 2]
```diff
@@ -101,7 +101,7 @@ public void initializeStreamWriters(final EventStreamClientFactory clientFactory
         }
         this.eventHelper = new EventHelper(clientFactory.createEventWriter(streamName,
                 ControllerEventProcessors.CONTROLLER_EVENT_SERIALIZER,
-                EventWriterConfig.builder().retryAttempts(Integer.MAX_VALUE).build()), this.executor, this.eventExecutor, hostId,
+                EventWriterConfig.builder().enableConnectionPooling(true).retryAttempts(Integer.MAX_VALUE).build()), this.executor, this.eventExecutor, hostId,
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/task/KeyValueTable/TableMetadataTasks.java:104]: A similar change is warrented @ `io.pravega.controller.task.Stream.StreamTransactionMetadataTasks#initializeStreamWriters`
This spawns 4 more connections to the Segment Store.

**Comment by shrids** [comment]
+1 Thanks @RaulGracia, we can merge this once we have a green system test run.

**Review by shrids — APPROVED** [review]
+1 Thanks @RaulGracia, we can merge this once we have a green system test run.
