### PR TITLE
Issue 1411: Docker swarm based system test framework

### LINKED ISSUE #1411: Implement System test framework based on Docker Swarm
**Problem description**
Currently system tests for Pravega runs only on a Jarvis deployed cluster which has DCOS installed. It uses Marathon and Metronome to provision Pravega and run system tests on the cluster.
The system test framework should also support
1. running locally (on our development machine/laptops)
2. running on cloud, AWS being one among them.

The new System test framework should:
- Enable running  system tests locally.
- Enable running system tests to run on the cloud.
- Reduce the time taken to run System tests. (Currently deploying a DCOS on a cluster takes around 25 mins.)
- Enable logs of services to be downloaded easily.
Using this approach will help us to run system tests locally too by deploying services using the docker daemon running locally on the development machines.

Sub tasks:
- [x]  scaleService- increase/decrease the replicas ( Networks should be added to TaskSpec before updating)
- [x]  Segmentstore deployment without exceptions (Illegal container state execption)
- [x]  Deploy controller successfully ( Internal streams are stuck in `CREATING` state)
- [ ]  System tests local execution 
- [x]  Execution of system tests on jarvis
- [ ]  Execution of system tests on AWS. https://github.com/pravega/pravega/issues/2173

**Problem location**
System Test Framework

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
The idea is to use docker (along with docker-swarm) to deploy various components / services  and execute system tests in Pravega i.e. zookeeper, bookkeeper, hdfs, Segmentstore, Controller 
**Purpose of the change**
Fixes #1411
This docker based system test framework supports running of system tests locally i.e (on our development machine/laptops).
**What the code does**
Deploys servcies and executes test using docker swarm
**How to verify it**
./gradlew clean --info startSystemTestsWithDocker -PdockerRegistryUrl= -DmasterIP=  -DimageVersion=  -DskipServiceInstallation=false -Dlog.level=DEBUG -DexecType=DOCKER -PCLUSTER_NAME= -PMASTER=  -PNUM_SLAVES=

The flag `-DexecType`  should be set to `DOCKER`  for this execution to be invoked.

### CODE REVIEW

**Comment by Prabha-Veerubhotla** [comment]
There are still some TODOs and refinements to be done. Please `DO NOT MERGE`.
Note : This is tested locally, yet to be tested on the jarvis cluster.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+            ContainerCreation containerCreation = CLIENT.createContainer(setContainerConfig(methodName, className), containerName);
+            assertFalse(containerCreation.id().toString().equals(null));
+
+              id = containerCreation.id();
+
+            final Path dockerDirectory = Paths.get(System.getProperty("user.dir"));
+            try {
+                CLIENT.copyToContainer(dockerDirectory, id, "/data");
+            } catch (IOException | DockerException | InterruptedException e) {
+                log.error("Exception while copying test jar to the container {}", e);
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: we should not suppress exceptions here and below.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+        HostConfig hostConfig = HostConfig.builder()
+                .portBindings(ImmutableMap.of( "2375/tcp", Arrays.asList( PortBinding.of( System.getProperty("masterIP"), "2375" ) ) ) ).networkMode("host").build();
+
+        ContainerConfig containerConfig = ContainerConfig.builder()
+                .hostConfig(hostConfig)
+                .image(IMAGE)
+                .user("root")
+                .workingDir("/data")
+                .cmd("sh", "-c", "java -DdockerExecLocal="+ Utils.isDockerLocalExecEnabled()+ " -DmasterIP="+System.getProperty("masterIP")+ " -DskipServiceInstallation=" + Utils.isSkipServiceInstallationEnabled() + " -cp /data/build/libs/test-collection.jar io.pravega.test.system.SingleJUnitTestRunner " +
+                        className + "#" + methodName + " > "+  className + "#" + methodName + "server.log 2>&1" + "; exit $?")
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: The test log file name should include test name

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+
+        HostConfig hostConfig = HostConfig.builder()
+                .portBindings(ImmutableMap.of( "2375/tcp", Arrays.asList( PortBinding.of( System.getProperty("masterIP"), "2375" ) ) ) ).networkMode("host").build();
+
+        ContainerConfig containerConfig = ContainerConfig.builder()
+                .hostConfig(hostConfig)
+                .image(IMAGE)
+                .user("root")
+                .workingDir("/data")
+                .cmd("sh", "-c", "java -DdockerExecLocal="+ Utils.isDockerLocalExecEnabled()+ " -DmasterIP="+System.getProperty("masterIP")+ " -DskipServiceInstallation=" + Utils.isSkipServiceInstallationEnabled() + " -cp /data/build/libs/test-collection.jar io.pravega.test.system.SingleJUnitTestRunner " +
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: We should use the version for test-collection.jar.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+                        className + "#" + methodName + " > "+  className + "#" + methodName + "server.log 2>&1" + "; exit $?")
+                .labels(labels)
+                .build();
+
+        return containerConfig;
+    }
+
+    private void stopContainer(String containerName) {
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: We can use the container ID returned by startContainer()

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+        throw new org.apache.commons.lang.NotImplementedException("Stop Execution is not used for Remote sequential execution");
+    }
+
+    private CompletableFuture<Void> waitForJobCompletion(final String containerName) {
+        return FutureHelpers.loop(() -> isTestRunning(containerName),
+                () -> FutureHelpers.delayedFuture(Duration.ofSeconds(3), executorService),
+                executorService);
+    }
+
+    private boolean isTestRunning(String containerName) {
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: We can reuse the containerID returned by startContainer.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+        }  catch (InterruptedException | DockerException e) {
+            log.error("unable to list service details {}", e);
+        }
+        return uriList;
+    }
+
+    @Override
+    public void scaleService(final int instanceCount, final boolean wait) {
+        try {
+            Preconditions.checkArgument(instanceCount >= 0, "negative value: %s", instanceCount);
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: wait is not used, is it always blocking ?

File: build.gradle [hunk 7]
```diff
@@ -509,8 +511,70 @@ project('test:system') {
         from sourceSets.test.output
     }
 
+    task testJarForDocker(type: Jar) {
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: There is a problem with using the existing signed jar. Need to exclude the  `.SF, .RSA, .DSA` files. Hence, a new jar is required.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 2 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: It includes . the file name is` className#methodNameserver.log`

File: build.gradle [hunk 8]
```diff
@@ -493,6 +493,8 @@ project('test:system') {
         compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: javaxwsrsApiVersion
         compile group: 'org.glassfish.jersey.core', name: 'jersey-client', version: jerseyVersion
         compile group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: jerseyVersion
+        // https://mvnrepository.com/artifact/com.spotify/docker-client
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: done.

File: build.gradle [hunk 9]
```diff
@@ -534,6 +599,10 @@ project('test:system') {
         if (System.getProperty("imageVersion") == null) {
             systemProperty "imageVersion", "INVALID_IMAGE_VERSION"
         }
+
+        if (System.getProperty("dockerExecLocal") == null) {
+            systemProperty "dockerExecLocal", "false"
+        }
         if (System.getProperty("skipServiceInstallation") == null) {
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: it is needed to invoke the code under `@envirnoment`

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 10]
```diff
@@ -0,0 +1,162 @@
...
+import java.util.Map;
+import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.Executors;
+import java.util.concurrent.ScheduledExecutorService;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public final static DockerClient CLIENT = DefaultDockerClient.builder().uri("http://"+ System.getProperty("masterIP")+ ":2375").build();
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 11]
```diff
@@ -0,0 +1,162 @@
...
+    private final static String IMAGE = System.getProperty("dockerImageRegistry")+ "/java:8";
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done. doing a `docker pull java:8`

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 5 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 12]
```diff
@@ -0,0 +1,162 @@
...
+            List<Container> containers = CLIENT.listContainers(DockerClient.ListContainersFilterParam.withStatusRunning());
+            for (int i = 0; i < containers.size(); i++) {
+                ContainerInfo info = CLIENT.inspectContainer(containers.get(i).id());
+                if (info.name().equals(containerName)) {
+                    value = true;
+                    break;
+                }
+            }
+        } catch (DockerException | InterruptedException e) {
+            log.error("unable to list docker services {}", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 4 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 6 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: using wait.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 13]
```diff
@@ -0,0 +1,162 @@
...
+                                methodName);
+                    }
+                }
+                );
+    }
+
+
+    @Override
+    public CompletableFuture<Void> stopTestExecution(String testID) {
+        throw new org.apache.commons.lang.NotImplementedException("Stop Execution is not used for Remote sequential execution");
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: build.gradle [hunk 14]
```diff
@@ -520,6 +584,7 @@ project('test:system') {
 
         systemProperty "test_collection_jar_path", "$jar.archivePath.path"
         systemProperty "execType", System.getProperty("execType")
+        systemProperty "dockerExecLocal", System.getProperty("dockerExecLocal")
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: done. using `execType = docker ` for docker based execution.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 3 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: The task `startSystemTestsWithDocker` creates a `test-collection.jar ` as a part of doFirst task, so the version is not required.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Failing the test , if not able to start container or copying the test jar to container.

File: test/system/preTestScript.sh [hunk 15]
```diff
@@ -0,0 +1,12 @@
...
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# TODO: advertise address should not be hard coded.
+docker swarm init --advertise-addr 127.0.0.1
```
[the remark this answers is not in the document]
Comment (shrids) [reply test/system/preTestScript.sh]: We need to add a check for the docker api version. For the swarm/service API and copy operations (+ bugfixes) we require the docker version to be >= 1.30 .
This version check should also be checked before running the test docker container too.

File: test/system/Change_Docker_Config.sh [hunk 16]
```diff
@@ -0,0 +1,16 @@
...
+#
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+
```
Comment (tkaitchuck) [inline test/system/Change_Docker_Config.sh]: I think you want a `set -e` here

File: test/system/preTestScript.sh [hunk 17]
```diff
@@ -0,0 +1,49 @@
...
+#
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+
```
Comment (tkaitchuck) [inline test/system/preTestScript.sh]: I think you want a `set -e` here

File: test/system/preTestScript.sh [hunk 18]
```diff
@@ -0,0 +1,49 @@
...
+else
+  jarvis save $CLUSTER_NAME
+    if [ $MASTER_1 != null ]; then
+      #master
+      jarvis ssh master-1 "bash -s" -- < ./Change_Docker_Config.sh
+      jarvis ssh master-1 'docker swarm init --advertise-addr $MASTER_1; TOKEN = `docker swarm join-token worker`; echo $TOKEN; exit'
+
+      #slave-1
+      jarvis ssh slave-1 "bash -s" -- < ./Change_Docker_Config.sh
+      jarvis ssh slave-1 'sed -i 's/"live-restore": true/"live-restore": false/' /etc/docker/daemon.json;
```
Comment (tkaitchuck) [inline test/system/preTestScript.sh]: The quotes on a few of these lines, this one in particular are confusing. Maybe you could use a local variable?

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 19]
```diff
@@ -0,0 +1,154 @@
...
+import java.util.concurrent.ScheduledExecutorService;
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public final static DockerClient CLIENT = DefaultDockerClient.builder().uri("http://"+ getConfig("masterIP", "Invalid Master IP")+ ":2375").build();
+    private final static String IMAGE = "java:8";
+    public String id;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Make this member threadsafe somehow.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 20]
```diff
@@ -0,0 +1,154 @@
...
+import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.Executors;
+import java.util.concurrent.ScheduledExecutorService;
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public final static DockerClient CLIENT = DefaultDockerClient.builder().uri("http://"+ getConfig("masterIP", "Invalid Master IP")+ ":2375").build();
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Should this be static?

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 21]
```diff
@@ -0,0 +1,154 @@
...
+        return FutureHelpers.loop(() -> isTestRunning(containerName),
+                () -> FutureHelpers.delayedFuture(Duration.ofSeconds(3), executorService),
+                executorService);
+    }
+
+    private boolean isTestRunning(String containerName) {
+        boolean value = false;
+        try {
+            ContainerInfo info = CLIENT.inspectContainer(id);
+                if (info.name().equals(containerName)) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Weird indentation in this file. Run it through an autoformatter.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 22]
```diff
@@ -0,0 +1,154 @@
...
+            assertFalse(containerCreation.id().toString().equals(null));
+
+              id = containerCreation.id();
+
+            final Path dockerDirectory = Paths.get(System.getProperty("user.dir"));
+            try {
+                CLIENT.copyToContainer(dockerDirectory, id, "/data");
+            } catch (IOException | DockerException | InterruptedException e) {
+                log.error("Exception while copying test jar to the container ", e);
+                Assert.fail("Unable to copy test jar to the container.Test failure");
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Here an elsewhere when an exception causes a test to fail, it is better to do something like `new AssertionError("...",e);` or similar because it allows the stack trace to show up when someone sees the failure in Gradle, or Jankens, or their IDE.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 23]
```diff
@@ -0,0 +1,154 @@
...
+                .build();
+
+        return containerConfig;
+    }
+
+    private void stopContainer() {
+        try {
+            CLIENT.stopContainer(id, 0);
+        } catch (DockerException | InterruptedException e) {
+            log.error("Exception while stopping the container ", e);
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: This is logged at error level and suppressed.  Perhaps it should just throw and let the test fail.

File: test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java [hunk 24]
```diff
@@ -9,21 +9,29 @@
...
 package io.pravega.test.system.framework;
 
+import lombok.Getter;
 import org.apache.commons.lang3.NotImplementedException;
 
 public class TestExecutorFactory {
+    @Getter(lazy = true)
     private static final TestExecutor MARATHON_SEQUENTIAL_EXECUTOR = new RemoteSequential();
 
+    @Getter(lazy = true)
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java]: Using a static lazy=true getter is equivalent to a static AtomicReference. See: https://projectlombok.org/features/GetterLazy
We disallow this by convention. If these need to be static and they don't need to be lazy, we can just make them normal static final variables. If they need to be lazy they should be made non-static.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 25]
```diff
@@ -0,0 +1,116 @@
...
+import java.util.concurrent.TimeoutException;
+import static org.hamcrest.core.Is.is;
+import static org.hamcrest.core.IsNull.notNullValue;
+import static org.junit.Assert.assertThat;
+
+@Slf4j
+public class BookkeeperDockerService extends DockerBasedService {
+
+    private static final int BK_PORT = 3181;
+    private int instances = 3;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: These need to be final

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 26]
```diff
@@ -0,0 +1,158 @@
...
+import java.util.concurrent.ScheduledExecutorService;
+
+@Slf4j
+public abstract class DockerBasedService  implements io.pravega.test.system.framework.services.Service {
+
+    static final int ZKSERVICE_ZKPORT = 2181;
+    static final int CONTROLLER_PORT = 9092;
+    static final String IMAGE_PATH = System.getProperty("dockerImageRegistry");
+    static final String PRAVEGA_VERSION = System.getProperty("imageVersion");
+    DockerClient dockerClient;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: These two should be private and final, or private and @guardedBy some lock.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 27]
```diff
@@ -0,0 +1,158 @@
...
+        dockerClient = DefaultDockerClient.builder().uri("http://"+ System.getProperty("masterIP")+ ":2375").build();
+        try {
+            if (dockerClient.listNetworks(DockerClient.ListNetworksParam.byNetworkName("docker-network")).isEmpty()) {
+                dockerClient.createNetwork(NetworkConfig.builder().driver("overlay").name("docker-network").build());
+            }
+        } catch (DockerException | InterruptedException e) {
+            log.error("Unable to create network {}", e);
+        }
+        this.serviceName = serviceName;
+        }
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Weird indentation here.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 28]
```diff
@@ -0,0 +1,158 @@
...
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
+
+    DockerBasedService(String serviceName) {
+        dockerClient = DefaultDockerClient.builder().uri("http://"+ System.getProperty("masterIP")+ ":2375").build();
+        try {
+            if (dockerClient.listNetworks(DockerClient.ListNetworksParam.byNetworkName("docker-network")).isEmpty()) {
+                dockerClient.createNetwork(NetworkConfig.builder().driver("overlay").name("docker-network").build());
+            }
+        } catch (DockerException | InterruptedException e) {
+            log.error("Unable to create network {}", e);
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Should this be returning successfully?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 29]
```diff
@@ -0,0 +1,158 @@
...
+    static final int ZKSERVICE_ZKPORT = 2181;
+    static final int CONTROLLER_PORT = 9092;
+    static final String IMAGE_PATH = System.getProperty("dockerImageRegistry");
+    static final String PRAVEGA_VERSION = System.getProperty("imageVersion");
+    DockerClient dockerClient;
+    String serviceName;
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
+
+    DockerBasedService(String serviceName) {
+        dockerClient = DefaultDockerClient.builder().uri("http://"+ System.getProperty("masterIP")+ ":2375").build();
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Please make this port into a constant.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 30]
```diff
@@ -0,0 +1,158 @@
...
+
+
+    @Override
+    public String getID() {
+        Service.Criteria criteria = Service.Criteria.builder().serviceName(this.serviceName).build();
+        String serviceId = null;
+        try {
+            List<Service> serviceList = dockerClient.listServices(criteria);
+            serviceId = serviceList.get(0).id();
+        }  catch (DockerException | InterruptedException  e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: This is not the proper way to handle interruptedException. We have a helper method in common.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 31]
```diff
@@ -0,0 +1,158 @@
...
+            List<Service> serviceList = dockerClient.listServices(criteria);
+
+            for (int i = 0; i < serviceList.size(); i++) {
+                String serviceId = serviceList.get(i).id();
+                if (!serviceId.isEmpty()) {
+                    value = true;
+                    break;
+                }
+            }
+        } catch (DockerException | InterruptedException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Same here.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 32]
```diff
@@ -0,0 +1,158 @@
...
+        try {
+            List<Service> serviceList = dockerClient.listServices(criteria);
+
+            for (int i = 0; i < serviceList.size(); i++) {
+                URI uri = URI.create("tcp://" + dockerClient.getHost() + ":"
+                        + serviceList.get(i).spec().endpointSpec()
+                        .ports().get(i).targetPort());
+                uriList.add(uri);
+            }
+        }  catch (InterruptedException | DockerException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Same here.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 33]
```diff
@@ -0,0 +1,158 @@
...
+import java.time.Duration;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.Executors;
+import java.util.concurrent.ScheduledExecutorService;
+
+@Slf4j
+public abstract class DockerBasedService  implements io.pravega.test.system.framework.services.Service {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Import this, so the path is shorter.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 34]
```diff
@@ -0,0 +1,158 @@
...
+                uriList.add(uri);
+            }
+        }  catch (InterruptedException | DockerException e) {
+            log.error("Unable to list service details {}", e);
+        }
+        return uriList;
+    }
+
+    @Override
+    public void scaleService(final int instanceCount, final boolean wait) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Rather than a boolean to block or not, it should return a future which the caller can decide to call get() on or not.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 35]
```diff
@@ -0,0 +1,158 @@
...
+            Preconditions.checkArgument(instanceCount >= 0, "negative value: %s", instanceCount);
+            Service.Criteria criteria = Service.Criteria.builder().serviceName(this.serviceName).build();
+            String serviceId = dockerClient.listServices(criteria).get(0).id();
+            dockerClient.updateService(serviceId, 1L, ServiceSpec.builder().mode(ServiceMode.withReplicas(instanceCount)).build());
+            String updateState = dockerClient.inspectService(serviceId).updateStatus().state();
+            log.info("update state {}", updateState);
+            if (wait) {
+                waitUntilServiceRunning().get();
+            }
+        } catch (ExecutionException | DockerException | InterruptedException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: I don't think we want to be suppressing exception all over like this. 
Also, do not suppress Interrupted

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 36]
```diff
@@ -0,0 +1,158 @@
...
+
+    @Override
+    public void stop() {
+        try {
+            List<com.spotify.docker.client.messages.Network> networkList =  dockerClient.listNetworks(DockerClient.ListNetworksParam.byNetworkName("network-name"));
+            for (int i = 0; i < networkList.size(); i++) {
+                dockerClient.removeNetwork(networkList.get(i).id());
+            }
+            dockerClient.leaveSwarm(true);
+        } catch (DockerException | InterruptedException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Same here

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 37]
```diff
@@ -0,0 +1,106 @@
...
+
+    public HDFSDockerService(final String serviceName) {
+        super(serviceName);
+    }
+
+    @Override
+    public void stop() {
+        try {
+            dockerClient.removeService(getID());
+        } catch (DockerException | InterruptedException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: ExceptonHanlders.handleInterupted()

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 38]
```diff
@@ -0,0 +1,106 @@
...
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+import static org.hamcrest.core.Is.is;
+import static org.hamcrest.core.IsNull.notNullValue;
+import static org.junit.Assert.assertThat;
+
+@Slf4j
+public class HDFSDockerService extends DockerBasedService {
+
+    private int instances = 1;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: These need to be final

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 39]
```diff
@@ -0,0 +1,106 @@
...
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = dockerClient.createService(setServiceSpec());
+            if (wait) {
+                waitUntilServiceRunning().get(5, TimeUnit.MINUTES);
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
+        } catch (InterruptedException | DockerException | TimeoutException | ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: Please don't suppress exception like this.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 40]
```diff
@@ -0,0 +1,106 @@
...
+            log.error("unable to create service {}", e);
+        }
+    }
+
+    private ServiceSpec setServiceSpec() {
+        Mount mount = Mount.builder().type("volume").source("hadoop-logs-volume").target("/opt/hadoop/logs").build();
+        final TaskSpec taskSpec = TaskSpec
+                .builder()
+                .containerSpec(ContainerSpec.builder().image("dsrw/hdfs:2.7.3-1")
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: Please make this into a constant.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java [hunk 41]
```diff
@@ -0,0 +1,112 @@
...
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+
+@Slf4j
+public class PravegaControllerDockerService extends DockerBasedService {
+
+    static final int CONTROLLER_PORT = 9092;
+    private static final int REST_PORT = 10080;
+    private int instances = 1;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: These need to be final

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java [hunk 42]
```diff
@@ -0,0 +1,112 @@
...
+    private double cpu = 0.1;
+    private double mem = 700.0;
+
+    public PravegaControllerDockerService(final String serviceName) {
+        super(serviceName);
+    }
+
+    @Override
+    public void stop() {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: This is overriding a method without calling super. Perhaps the parent class could be refactored to make it harder to make this mistake. Perhaps by having an abstract doStop or something. Also look into Guava's Service abstraction. It might simplify things.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 43]
```diff
@@ -0,0 +1,143 @@
...
+import static org.hamcrest.core.IsNull.notNullValue;
+import static org.junit.Assert.assertThat;
+
+@Slf4j
+public class PravegaSegmentStoreDockerService extends DockerBasedService {
+
+    private static final int SEGMENTSTORE_PORT = 12345;
+    private static final String SEGMENTSTORE_EXTRA_ENV = System.getProperty("segmentStoreExtraEnv");
+    private static final String ENV_SEPARATOR = ";;";
+    private static final java.lang.String KEY_VALUE_SEPARATOR = "::";
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: import

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 44]
```diff
@@ -0,0 +1,143 @@
...
+    private int instances = 1;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: final

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 45]
```diff
@@ -0,0 +1,143 @@
...
+    private double cpu = 0.1;
+    private double mem = 1000.0;
+
+    public PravegaSegmentStoreDockerService(final String serviceName) {
+        super(serviceName);
+    }
+
+    @Override
+    public void stop() {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: See my earlier comment

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 46]
```diff
@@ -0,0 +1,143 @@
...
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = dockerClient.createService(setServiceSpec());
+            if (wait) {
+                waitUntilServiceRunning().get(5, TimeUnit.MINUTES);
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
+        } catch (InterruptedException | DockerException | TimeoutException | ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: Suppressing exceptions

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 47]
```diff
@@ -0,0 +1,143 @@
...
+        return spec;
+    }
+
+    private void getCustomEnvVars(List<String> stringList, String segmentstoreExtraEnv) {
+        log.info("Extra segment store env variables are {}", segmentstoreExtraEnv);
+        if (!Strings.isNullOrEmpty(segmentstoreExtraEnv)) {
+            Arrays.stream(segmentstoreExtraEnv.split(ENV_SEPARATOR)).forEach(str -> {
+                String[] pair = str.split(KEY_VALUE_SEPARATOR);
+                if (pair.length != 2) {
+                    log.warn("Key Value not present {}", str);
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: throw?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 48]
```diff
@@ -0,0 +1,143 @@
...
+        String hostSystemProperties =
+                setSystemProperty("autoScale.muteInSeconds", "120") +
+                setSystemProperty("autoScale.cooldownInSeconds", "120") +
+                setSystemProperty("autoScale.cacheExpiryInSeconds", "120") +
+                setSystemProperty("autoScale.cacheCleanUpInSeconds", "120") +
+                setSystemProperty("log.level", "DEBUG") +
+                setSystemProperty("curator-default-session-timeout", String.valueOf(30 * 1000))+
+                        setSystemProperty("hdfs.replaceDataNodesOnFailure", "false");
+
+        String env1 = "PRAVEGA_SEGMENTSTORE_OPTS=" + hostSystemProperties;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: These look to only be used once. Perhaps they should be inlined.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 49]
```diff
@@ -0,0 +1,158 @@
...
+    }
+
+    CompletableFuture<Void> waitUntilServiceRunning() {
+        log.debug("IS RUNNING {}", isRunning());
+        return FutureHelpers.loop(() -> !isRunning(), //condition
+                () -> FutureHelpers.delayedFuture(Duration.ofSeconds(5), executorService),
+                executorService);
+    }
+
+    String setSystemProperty(final String propertyName, final String propertyValue) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: This isn't a great abstraction because it just causes the callers to call it over and over again concating the results. Perhaps it should take a string builder. Also this method could be static.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 50]
```diff
@@ -0,0 +1,100 @@
...
+import static org.hamcrest.core.Is.is;
+import static org.hamcrest.core.IsNull.notNullValue;
+import static org.junit.Assert.assertThat;
+
+
+@Slf4j
+public class ZookeeperDockerService extends DockerBasedService {
+
+    private static final String ZK_IMAGE = "jplock/zookeeper:3.5.2-alpha";
+    private int instances = 1;
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: final

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 51]
```diff
@@ -0,0 +1,100 @@
...
+    @Override
+    public void stop() {
+        try {
+            Service.Criteria criteria = Service.Criteria.builder().serviceName(this.serviceName).build();
+            List<Service> serviceList = dockerClient.listServices(criteria);
+            for (int i = 0; i < serviceList.size(); i++) {
+                String serviceId = serviceList.get(i).id();
+                dockerClient.removeService(serviceId);
+            }
+        } catch (DockerException | InterruptedException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: interupted

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 52]
```diff
@@ -0,0 +1,100 @@
...
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = dockerClient.createService(setServiceSpec());
+            if (wait) {
+                waitUntilServiceRunning().get(5, TimeUnit.MINUTES);
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
+        } catch (InterruptedException | DockerException | ExecutionException | TimeoutException e) {
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: suppressing errors

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 53]
```diff
@@ -0,0 +1,100 @@
...
+            log.error("Unable to create service", e);
+        }
+    }
+
+    private ServiceSpec setServiceSpec() {
+
+        final TaskSpec taskSpec = TaskSpec
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: Indentation

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 20 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: removed static.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 21 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 25 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 33 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Cannot import this, intellij is not allowing this somehow.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 26 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: made it final, as these not bed accessed in the package, rather than only in the class, cannot make them private.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 29 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 28 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: moved this logic into shell script.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 27 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: formatted the file.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 30 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Changed to use helper method.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 31 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 32 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java (hunk 38 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java (hunk 37 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java (hunk 40 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java (hunk 41 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 43 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 44 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 48 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java (hunk 50 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java (hunk 51 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: changed to use helper method.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java (hunk 53 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: formatted it.

File: test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java (hunk 24 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java]: removed static.

File: test/system/preTestScript.sh (hunk 15 above)
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: done.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 54]
```diff
@@ -63,34 +74,55 @@ public static void setup() throws InterruptedException, MarathonException, URISy
...
         List<URI> conUris = controllerService.getServiceDetails();
-        log.debug("Pravega Controller service instance details: {}", conUris);
-
-        List<URI> testConUris = testControllerService.getServiceDetails();
-        log.debug("Pravega test Controller service instance details: {}", testConUris);
+        log.info("conuris {} {}", conUris.get(0), conUris.get(1));
+        log.debug("Pravega Controller service  details: {}", conUris);
+        // Fetch all the RPC endpoints and construct the client URIs.
+        List<String> uris;
+        if (Utils.isDockerLocalExecEnabled()) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: This class seems to be half if/else blocks. Perhaps the test could go into an abstract parent class and there could be two child classes for the two cases.

File: test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java [hunk 55]
```diff
@@ -98,7 +103,9 @@ public ControllerRestApiTest() {
     public static void setup() throws InterruptedException, MarathonException, URISyntaxException {
 
         //1. check if zk is running, if not start it
-        Service zkService = new ZookeeperService("zookeeper");
+        Service zkService = Utils.isDockerLocalExecEnabled()
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java]: This and the next few classes seem to have the same pattern as the previous one. Perhaps there is a way to share code?

File: test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java [hunk 56]
```diff
@@ -73,35 +77,50 @@
...
+            Service hdfsService = new HDFSDockerService("hdfs");
+            if (!hdfsService.isRunning()) {
+                hdfsService.start(true);
+            }
+            hdfsUri = hdfsService.getServiceDetails().get(0);
+            log.debug("HDFS service details: {}", hdfsService.getServiceDetails());
+        }
         // Verify controller is running.
-        controllerInstance = new PravegaControllerService("controller", zkUri);
+        controllerInstance = Utils.isDockerLocalExecEnabled()
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java]: This line is repeated a lot. Perhaps it could be made into a facotory method.

File: test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java [hunk 57]
```diff
@@ -87,22 +92,39 @@ public static void setup() throws Exception {
 
         //get the zk ip details and pass it to bk, host, controller
         //2, check if bk is running, otherwise start, get the zk ip
-        Service bkService = new BookkeeperService("bookkeeper", zkUris.get(0));
+        Service bkService = Utils.isDockerLocalExecEnabled() ?
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java]: This could also be made into a factory method

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java [hunk 58]
```diff
@@ -68,34 +72,49 @@
...
+        controllerInstance = Utils.isDockerLocalExecEnabled()
+                ? new PravegaControllerDockerService("controller", zkUri)
+                : new PravegaControllerService("controller", zkUri);
         assertTrue(controllerInstance.isRunning());
         List<URI> conURIs = controllerInstance.getServiceDetails();
         log.info("Pravega Controller service instance details: {}", conURIs);
 
         // Fetch all the RPC endpoints and construct the client URIs.
-        final List<String> uris = conURIs.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+        final List<String> uris = conURIs.stream().filter(uri -> Utils.isDockerLocalExecEnabled() ? uri.getPort() == 9090 : uri.getPort() == 9092).map(URI::getAuthority)
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: Please don't hardcode constants inline like this

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java [hunk 59]
```diff
@@ -73,34 +77,49 @@
...
+        controllerInstance = Utils.isDockerLocalExecEnabled()
+                ? new PravegaControllerDockerService("controller", zkUri)
+                : new PravegaControllerService("controller", zkUri);
         assertTrue(controllerInstance.isRunning());
         List<URI> conURIs = controllerInstance.getServiceDetails();
         log.info("Pravega Controller service instance details: {}", conURIs);
 
         // Fetch all the RPC endpoints and construct the client URIs.
-        final List<String> uris = conURIs.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+        final List<String> uris = conURIs.stream().filter(uri -> Utils.isDockerLocalExecEnabled() ? uri.getPort() == 9090 :  uri.getPort() == 9092).map(URI::getAuthority)
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: Here and elsewhere 9090 and 9092 should be defined somewhere. Perhaps on Utils.

Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java (hunk 58 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: removed the harcoding.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 60]
```diff
@@ -0,0 +1,154 @@
...
+public class PravegaSegmentStoreDockerService extends DockerBasedService {
+
+    private static final int SEGMENTSTORE_PORT = 12345;
+    private static final String SEGMENTSTORE_EXTRA_ENV = System.getProperty("segmentStoreExtraEnv");
+    private static final String ENV_SEPARATOR = ";;";
+    private static final String KEY_VALUE_SEPARATOR = "::";
+    private final long instances = 1;
+    private final double cpu = 0.1;
+    private final double mem = 1000.0;
+    private URI zkUri;
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 61]
```diff
@@ -0,0 +1,117 @@
...
+    }
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: updated.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 62]
```diff
@@ -0,0 +1,154 @@
...
+    }
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 63]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 64]
```diff
@@ -0,0 +1,122 @@
...
+    }
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 65]
```diff
@@ -0,0 +1,122 @@
...
+import static org.junit.Assert.assertThat;
+
+@Slf4j
+public class BookkeeperDockerService extends DockerBasedService {
+
+    private static final int BK_PORT = 3181;
+    private final long instances = 3;
+    private final double cpu = 0.1;
+    private final double mem = 1024.0;
+    private URI zkUri;
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 66]
```diff
@@ -0,0 +1,164 @@
...
+
+            ContainerCreation containerCreation = client.createContainer(setContainerConfig(methodName, className), containerName);
+            assertFalse(containerCreation.id().toString().equals(null));
+
+            id = containerCreation.id();
+
+            final Path dockerDirectory = Paths.get(System.getProperty("user.dir"));
+            try {
+                client.copyToContainer(dockerDirectory, id, "/data");
+            } catch (IOException | DockerException | InterruptedException e) {
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 67]
```diff
@@ -0,0 +1,164 @@
...
+                executorService);
+    }
+
+    private boolean isTestRunning() {
+        boolean value = false;
+        try {
+            if (client.inspectContainer(this.id).state().running()) {
+                value = true;
+            }
+        } catch (DockerException | InterruptedException e) {
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 68]
```diff
@@ -0,0 +1,164 @@
...
+                        log.error("Unable to get container exit status", e);
+                    }
+                    return null;
+                });
+    }
+
+
+    @Override
+    public CompletableFuture<Void> stopTestExecution(String testID) {
+        throw new NotImplementedException("Stop Execution is not used for Remote sequential execution");
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Implementing it. stopping the test execution.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 69]
```diff
@@ -0,0 +1,164 @@
...
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public static final int DOCKER_CLIENT_PORT = 2375;
+    private final static String IMAGE = "java:8";
+    public final DockerClient client = DefaultDockerClient.builder().uri("http://" + getConfig("masterIP", "Invalid Master IP") + ":" + DOCKER_CLIENT_PORT).build();
+    public String id;
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done. Using Atomic Reference for the same.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 70]
```diff
@@ -0,0 +1,164 @@
...
+import java.util.concurrent.ScheduledExecutorService;
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public static final int DOCKER_CLIENT_PORT = 2375;
+    private final static String IMAGE = "java:8";
+    public final DockerClient client = DefaultDockerClient.builder().uri("http://" + getConfig("masterIP", "Invalid Master IP") + ":" + DOCKER_CLIENT_PORT).build();
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: made it private.

File: test/system/preTestScript.sh (hunk 18 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: moved this into slave config script.  `live-restore` needs to be made `false` from `true` to make it compatible with docker swarm mode. and it should be in that way( quotes)  for the DOCKER_OPTS to be accepted.

File: test/system/Change_Docker_Config.sh (hunk 16 above)
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config.sh]: using ` sed -e` , when needed.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 19 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/preTestScript.sh (hunk 17 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: using sed -i , when needed.

File: test/system/Change_Docker_Config.sh (hunk 16 above)
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config.sh]: done, for both ` Change_Docker_Config_Master.sh`, `Change_Docker_Config_Slave.sh`.

File: test/system/preTestScript.sh (hunk 17 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: I cannot use it here, though , we have a command `jarvis save $CLUSTER_NAME`. It gives the following log, even though the execution is susccessful. 
```
jarvis save glorian
[jarvis login] failed: Post https://10.240.124.131/auth/v1/login: dial tcp 10.240.124.131:443: getsockopt: connection refused
Post https://10.240.124.131/auth/v1/login: dial tcp 10.240.124.131:443: getsockopt: connection refused
```
If i add ` set -e` , the execution stops and fails here, which is not necessary, as there is no problem with the function of the command.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 22 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 23 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 35 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 36 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java (hunk 39 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 46 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: throwing, done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 47 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: throwing `RunTimeException`, done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java (hunk 52 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 71]
```diff
@@ -0,0 +1,164 @@
...
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
+
+    public CompletableFuture<Void> startTestExecution(Method testMethod) {
+        try {
+            final String dockerApiVersion = Exceptions.handleInterrupted(() -> client.version().apiVersion());
+            if (!(VersionCompare.compareVersion(dockerApiVersion, expectedDockerApiVersion) >= 0)) {
+                throw new AssertionError("Docker API doesnt match.Cannot Invoke Tests.Excepected = " + expectedDockerApiVersion + "Actual = " + dockerApiVersion);
+            }
+        } catch (DockerException e) {
+            log.error("Unable to find docker client version", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 72]
```diff
@@ -0,0 +1,164 @@
...
+            assertFalse(containerCreation.id().toString().equals(null));
+
+            id = containerCreation.id();
+
+            final Path dockerDirectory = Paths.get(System.getProperty("user.dir"));
+            try {
+                client.copyToContainer(dockerDirectory, id, "/data");
+            } catch (IOException | DockerException | InterruptedException e) {
+                log.error("Exception while copying test jar to the container ", e);
+                Assert.fail("Unable to copy test jar to the container.Test failure");
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 73]
```diff
@@ -0,0 +1,122 @@
...
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
+        } catch (Exception e) {
+            log.error("Unable to create service", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 74]
```diff
@@ -0,0 +1,191 @@
...
+    @Override
+    public boolean isRunning() {
+        boolean value = false;
+        int taskRunningCount = 0;
+        try {
+            //list the service with filter 'serviceName'
+            Service.Criteria criteria1 = Service.Criteria.builder().serviceName(serviceName).build();
+            List<Service> serviceList1 = Exceptions.handleInterrupted(() -> dockerClient.listServices(criteria1));
+            log.info("service list size {}", serviceList1.size());
+            com.spotify.docker.client.messages.swarm.Task.Criteria taskCriteria1 = com.spotify.docker.client.messages.swarm.Task.Criteria.builder().serviceName(serviceName).build();
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 75]
```diff
@@ -0,0 +1,191 @@
...
+            List<com.spotify.docker.client.messages.swarm.Task> taskList1 = Exceptions.handleInterrupted(() ->  dockerClient.listTasks(taskCriteria1));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 71 above)
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: throwing, done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 76]
```diff
@@ -0,0 +1,164 @@
...
+            startTest(containerName, className, methodName);
+        }).thenCompose(v2 -> waitForJobCompletion())
+                .<Void>thenApply(v1 -> {
+                    try {
+                        if (Exceptions.handleInterrupted(() -> client.inspectContainer(id).state().exitCode() != 0)) {
+                            throw new AssertionError("Test failed "
+                                    + className + "#" + methodName);
+                        }
+                    } catch (DockerException e) {
+                        log.error("Unable to get container exit status", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: throwing, done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 77]
```diff
@@ -0,0 +1,122 @@
...
+        super(serviceName);
+        this.zkUri = zkUri;
+    }
+
+    @Override
+    public void stop() {
+        try {
+            Exceptions.handleInterrupted(() -> dockerClient.removeService(getID()));
+        } catch (DockerException e) {
+            log.error("Unable to remove service", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 78]
```diff
@@ -0,0 +1,191 @@
...
+            if (!serviceList1.isEmpty()) {
+                long replicas = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceList1.get(0).id()).spec().mode().replicated().replicas());
+                log.info("replicas {}", replicas);
+                log.info("task running count {}", taskRunningCount);
+                if (((long) taskRunningCount) == replicas) {
+                    return true;
+                }
+            }
+        } catch (DockerException e) {
+            log.error("Unable to list docker services", e);
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: We should not suppress exceptions.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 79]
```diff
@@ -99,23 +131,38 @@ public static void setup() throws InterruptedException, MarathonException, URISy
...
+            controllerService1.start(true);
+        }
+        //controllerService1.scaleService(3, true);
+        List<URI> conUris = controllerService1.getServiceDetails();
+        log.info("conuris {} {}", conUris.get(0), conUris.get(1));
+        log.debug("Pravega Controller service  details: {}", conUris);
+        // Fetch all the RPC endpoints and construct the client URIs.
+        List<String> uris;
+        if (Utils.isDockerLocalExecEnabled()) {
+            uris = conUris.stream().filter(uri -> uri.getPort() ==  Utils.DOCKER_CONTROLLER_PORT).map(URI::getAuthority)
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Why have different ports for Docker v/s marathon?

Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: In marathon we had a problem using the default `9090` and hence had to use , `9092`. now , in docker am using the default as the ports are already exposed in docker file.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 80]
```diff
@@ -0,0 +1,160 @@
...
+            Exceptions.handleInterrupted(() -> client.pull(IMAGE));
+
+            ContainerCreation containerCreation = Exceptions.handleInterrupted(() -> client.createContainer(setContainerConfig(methodName, className), containerName));
+            assertFalse(containerCreation.id().toString().equals(null));
+
+            id.set(containerCreation.id());
+
+            final Path dockerDirectory = Paths.get(System.getProperty("user.dir"));
+            try {
+                Exceptions.handleInterrupted(() -> client.copyToContainer(dockerDirectory, id.get(), "/data"));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: The `startContainer` method already logs the same statement. 
`log.info("Starting container with Id: {}", containerId);`

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/GRPCServer.java [hunk 81]
```diff
@@ -49,6 +49,7 @@ public GRPCServer(ControllerService controllerService, GRPCServerConfig serverCo
     protected void startUp() throws Exception {
         long traceId = LoggerHelpers.traceEnterWithContext(log, this.objectId, "startUp");
         try {
+            log.info("Satrting gRPC server on ip: {}", this.config.getPublishedRPCHost());
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/GRPCServer.java]: It was unintentional , added for debugging purpose. removed now.

[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/GRPCServer.java]: It was unintentional , added for debugging purpose. removed now.

File: gradle.properties [hunk 82]
```diff
@@ -51,3 +53,7 @@ bookkeeperBaseTag=pravega/bookkeeper
 signing.keyId=05949AF6
 # This will be defaulted to ~/.gnupg/secring.gpg if not provided as a command line property
 signing.secretKeyRingFile=
+
+CLUSTER_NAME=ant-man
+MASTER=127.0.0.1
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply gradle.properties]: This is just that we should have some default value for properties, the actual values are provided with gradle task ,  
`./gradlew startSystemTestsWithDocker. ....   -PCLUSTER_NAME=  -PMASTER=  -PNUM_SLAVES`
If the default some value is not set, gradle complains.

File: gradle.properties [hunk 83]
```diff
@@ -51,3 +53,7 @@ bookkeeperBaseTag=pravega/bookkeeper
...
+NUM_SLAVES=3
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply gradle.properties]: Yes, answered above.

File: test/system/Change_Docker_Config_Master.sh [hunk 84]
```diff
@@ -0,0 +1,22 @@
...
+set -e
+MASTER=${1:-null}
+sed -i '1i {"hosts":["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"]}' /etc/docker/daemon.json
+sed -i 's/"live-restore": true,/"live-restore": false,/' /etc/docker/daemon.json
+cat /etc/docker/daemon.json
+service docker stop
+service docker start
+docker swarm init --advertise-addr $MASTER
+docker network create -d overlay --attachable docker-network
+docker swarm join-token worker > token.sh
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config_Master.sh]: done.

File: test/system/Change_Docker_Config_Slave.sh [hunk 85]
```diff
@@ -0,0 +1,16 @@
...
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+set -e
+sed -i 's/"live-restore": true,/"live-restore": false,/' /etc/docker/daemon.json
+cat /etc/docker/daemon.json
+service docker stop
+service docker start
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config_Slave.sh]: The `token.sh`  file into which the output of ` docker swarm join-token worker` has that information , to join the swarm . The token will be different for each node ( hence diff for each cluster) . It depends on the manager's ip.

[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config_Slave.sh]: answered above.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 86]
```diff
@@ -0,0 +1,160 @@
...
+            startTest(containerName, className, methodName);
+        }).thenCompose(v2 -> waitForJobCompletion())
+                .<Void>thenApply(v1 -> {
+                    try {
+                        if (Exceptions.handleInterrupted(() -> client.inspectContainer(id.get()).state().exitCode() != 0)) {
+                            throw new AssertionError("Test failed "
+                                    + className + "#" + methodName);
+                        }
+                    } catch (DockerException e) {
+                        throw new AssertionError("Unable to get container exit status and test result.", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 78 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 87]
```diff
@@ -0,0 +1,191 @@
...
+
+    @Override
+    public String getID() {
+        Service.Criteria criteria = Service.Criteria.builder().serviceName(this.serviceName).build();
+        String serviceId = null;
+        try {
+            List<Service> serviceList = Exceptions.handleInterrupted(() -> dockerClient.listServices(criteria));
+            serviceId = serviceList.get(0).id();
+        } catch (DockerException e) {
+            log.error("Unable to get service id", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: we use getID() only in certain places, to stop the service and it's rarely called.  it should be fine, as we fail the test in case we are unable to stop/remove the service.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java [hunk 88]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    @Override
+    public void start(final boolean wait) {
+        try {
+            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterrupted(() -> dockerClient.createService(setServiceSpec()));
+            if (wait) {
+                Exceptions.handleInterrupted(() -> waitUntilServiceRunning().get(5, TimeUnit.MINUTES));
+            }
+            assertThat(serviceCreateResponse.id(), is(notNullValue()));
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: Done

File: test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java (hunk 56 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadTxnWriteScaleWithFailoverTest.java]: Done

File: test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java (hunk 57 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java]: Done

File: test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java (hunk 55 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerRestApiTest.java]: done. using factory method. `createServiceInstance` for the same.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 54 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: This number reduced greatly with use of factory method. `createServiceInstance`

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java (hunk 42 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 34 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 89]
```diff
@@ -0,0 +1,191 @@
...
+@Slf4j
+public abstract class DockerBasedService implements io.pravega.test.system.framework.services.Service {
+
+    static final int ZKSERVICE_ZKPORT = 2181;
+    static final String IMAGE_PATH = System.getProperty("dockerImageRegistry");
+    static final String PRAVEGA_VERSION = System.getProperty("imageVersion");
+    static final String DOCKER_NETWORK = "docker-network";
+    final DockerClient dockerClient;
+    final String serviceName;
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: shutting it , after test completion.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 90]
```diff
@@ -0,0 +1,164 @@
...
+public class DockerRemoteSequential implements TestExecutor {
+
+    public static final int DOCKER_CLIENT_PORT = 2375;
+    private final static String IMAGE = "java:8";
+    public final DockerClient client = DefaultDockerClient.builder().uri("http://" + getConfig("masterIP", "Invalid Master IP") + ":" + DOCKER_CLIENT_PORT).build();
+    public String id;
+    final String expectedDockerApiVersion = "1.25";
+
+
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: shutting it , after test completion.

File: build.gradle [hunk 91]
```diff
@@ -562,6 +578,48 @@ project('test:system') {
 
         onlyIf { dockerRegistryUrl && repoUrl }
     }
+
+    task execShellScript(type: Exec) {
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: I tried moving it into its own directory ` test/system` , but then we need to import all the dependencies, configurations separately  and we need to place this only into a file with  name  `build.gradle`. Also, moving into gradle sub directory doesnt work , also the current files there are configs, checkstyle and all other factors needed to build all projects instead of single project .

File: build.gradle [hunk 92]
```diff
@@ -509,6 +509,8 @@ project('test:system') {
         compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: javaxwsrsApiVersion
         compile group: 'org.glassfish.jersey.core', name: 'jersey-client', version: jerseyVersion
         compile group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: jerseyVersion
+        compile group: 'org.glassfish.jersey.bundles.repackaged', name: 'jersey-guava', version: jerseyGuavaVersion
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply build.gradle]: done.  using `compile group: 'org.glassfish.jersey.connectors', name:'jersey-apache-connector', version:jerseyVersion`

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 49 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 45 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 90 above)
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: shutting it after test completion.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 89 above)
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: shutting it after test completion.

File: gradle.properties [hunk 93]
```diff
@@ -26,6 +27,7 @@ hadoopVersion=2.8.1
 javaxServletApiVersion=4.0.0
 javaxwsrsApiVersion=2.1
 jerseyVersion=2.26
+jerseyGuavaVersion=2.6
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply gradle.properties]: done.

[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply gradle.properties]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 94]
```diff
@@ -0,0 +1,199 @@
...
+
+@Slf4j
+public abstract class DockerBasedService implements io.pravega.test.system.framework.services.Service {
+
+    static final int ZKSERVICE_ZKPORT = 2181;
+    static final String IMAGE_PATH = System.getProperty("dockerImageRegistry");
+    static final String PRAVEGA_VERSION = System.getProperty("imageVersion");
+    final DockerClient dockerClient;
+    final String serviceName;
+    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(3);
```
Comment (tkaitchuck) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: I don't see this shutdown. Perhaps it should be tied to the start/stop lifecycle?

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 95]
```diff
@@ -173,24 +185,36 @@ void performFailoverForTestsInvolvingTxns() {
...
         Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
         log.info("Scaling down Segment Store instances from 3 to 2");
         log.info("Read count: {}, write count: {} after Segment Store  failover after sleep",
                 testState.eventReadCount.get(),  testState.eventWriteCount.get());
 
         //Scale down controller instances to 2
-        controllerInstance.scaleService(2, true);
+        try {
+            Exceptions.handleInterrupted(() -> controllerInstance.scaleService(2).get());
+        } catch (ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Here and elsewhere in this file FutureHelpers.getAndHandleExceptions() would do this more concisely.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 96]
```diff
@@ -63,34 +69,53 @@ public static void setup() throws InterruptedException, MarathonException, URISy
...
             controllerService.start(true);
         }
-
-        //4. start test controller instances
-        Service testControllerService = new PravegaControllerService(TEST_CONTROLLER_SERVICE_NAME, zkUri);
-        if (!testControllerService.isRunning()) {
-            testControllerService.start(true);
+        try {
+            Exceptions.handleInterrupted(() -> controllerService.scaleService(2).get());
+        } catch (ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Futures.getAndHandleExceptions()

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 97]
```diff
@@ -158,12 +193,16 @@ public void failoverTest() throws URISyntaxException, InterruptedException {
         Assert.assertTrue(!scaleStatus);
 
         // Now stop the controller instance executing scale operation.
-        stopTestControllerService();
+        try {
+            Exceptions.handleInterrupted(() -> controllerService1.scaleService(1).get());
+        } catch (ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Same here

File: test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java [hunk 98]
```diff
@@ -127,21 +155,33 @@ public void testMultiSegmentStores() throws InterruptedException {
...
         // Wait for all containers to be up and registered.
         Thread.sleep(60000);
         log.info("Test with 2 segment stores running");
         testReadWrite();
 
         // Rescale to single instance and verify.
-        this.segmentServiceInstance.scaleService(1, true);
+        try {
+            Exceptions.handleInterrupted(() -> this.segmentServiceInstance.scaleService(1).get());
+        } catch (ExecutionException e) {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java]: Here and above Futures.getAndHandleExceptions().

File: test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java [hunk 99]
```diff
@@ -148,8 +166,16 @@ public void readTxnWriteAutoScaleWithFailoverTest() throws Exception {
         performFailoverForTestsInvolvingTxns();
 
         //bring the instances back to 3 before performing failover during scaling
-        controllerInstance.scaleService(3, true);
-        segmentStoreInstance.scaleService(3, true);
+        try {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java]: Same here

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java [hunk 100]
```diff
@@ -160,8 +185,16 @@ public void readWriteAndAutoScaleWithFailoverTest() throws Exception {
         waitForScaling(scope, AUTO_SCALE_STREAM);
 
         //bring the instances back to 3 before performing failover
-        controllerInstance.scaleService(3, true);
-        segmentStoreInstance.scaleService(3, true);
+        try {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: same here

**Comment by Prabha-Veerubhotla** [comment]
`This is working on plain jarvis cluster, on jenkins and on local-machine.`

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 101]
```diff
@@ -0,0 +1,176 @@
...
+import static io.pravega.test.system.framework.Utils.DOCKER_NETWORK;
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
+
+    public static final int DOCKER_CLIENT_PORT = 2375;
+    private final static String IMAGE = "java:8";
+    final AtomicReference<String> id = new AtomicReference();
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: done.

File: test/system/Change_Docker_Config_Master.sh [hunk 102]
```diff
@@ -0,0 +1,21 @@
...
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+set -e
+MASTER=${1:-null}
+sed -i '1i {"hosts":["tcp://0.0.0.0:2375","unix:///var/run/docker.sock"]}' /etc/docker/daemon.json
+sed -i 's/"live-restore": true,/"live-restore": false,/' /etc/docker/daemon.json
+cat /etc/docker/daemon.json
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config_Master.sh]: `Error response from daemon: –live-restore daemon configuration is incompatible with swarm mode` . here and below it is not usual to edit config file from a script file. but as the clusters are deployed by platform team with the config, that is not compatible with docker-swarm and they are not willing to change this.

File: test/system/Change_Docker_Config_Slave.sh [hunk 103]
```diff
@@ -0,0 +1,16 @@
...
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+set -e
+sed -i 's/"live-restore": true,/"live-restore": false,/' /etc/docker/daemon.json
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/Change_Docker_Config_Slave.sh]: answered above.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 94 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: its done here, 
```
return CompletableFuture.runAsync(() -> {
            startTest(containerName, className, methodName);
        }).thenCompose(v2 -> waitForJobCompletion())
                .<Void>thenApply(v1 -> {
                    try {
                        if (Exceptions.handleInterrupted(() -> client.inspectContainer(id.get()).state().exitCode() != 0)) {
                            throw new AssertionError("Test failed "
                                    + className + "#" + methodName);
                        }
                        executorService.shutdown();
```

**Comment by Prabha-Veerubhotla** [comment]
> This comment was referring to the cat which does not send the file anywhere. Is it just printing it to the screen for debugging?

Yes, this was for debugging purpose. Sorry for the confusion.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 104]
```diff
@@ -0,0 +1,177 @@
...
+                        executorService.shutdown();
+                    } catch (DockerException e) {
+                        throw new TestFrameworkException(TestFrameworkException.Type.RequestFailed, "Unable to get container exit status and test result.", e);
+                    }
+                    return null;
+                }).whenComplete((v, ex) -> {
+            try {
+                InputStream inputStream = Exceptions.handleInterrupted(() -> client.archiveContainer(id.get(), "/data"));
+            } catch (DockerException e) {
+                log.error("Unable to copy test logs", e);
```
[the remark this answers is not in the document]
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: No, actually this is not working. the logs are copied using a script after the test execution is completed. Removed this part of  code.

**Comment by Prabha-Veerubhotla** [comment]
> Responding here. We shouldn't be tieing these scripts to some particular configuration that exists on hosts we have, rather it should be tied to the docker image that our build produces.
I agree, but the case is bit different here, first we join the swarm and then deploy our services(using docker image).

**Comment by Prabha-Veerubhotla** [comment]
> It's fine if it fails the test. Just make sure it is not causing an NPE at any of the call sites

done.

**Comment by Prabha-Veerubhotla** [comment]
> I don't see any change.
We do a check if the service is running, before deploying. 
So in the case where the service is being deployed for the first time.
`dockerClient.listServices(...)` throws exception , as there is no information about the service name.
So i cannot fail the test  only here.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java (hunk 100 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java (hunk 99 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ReadTxnWriteAutoScaleWithFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java (hunk 98 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 97 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 96 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 95 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: done.

File: build.gradle [hunk 105]
```diff
@@ -563,6 +579,48 @@ project('test:system') {
...
+        ext.dockerRegistryUrl = project.hasProperty("dockerRegistryUrl") ? project.dockerRegistryUrl : ""
+
+        description 'Used to invoke docker based system tests, example usage: gradle startSystemTests -DmasterIP=xx.xx.xx.xx'
+        testClassesDir = sourceSets.test.output.classesDir
+        classpath = sourceSets.test.runtimeClasspath
+
+        systemProperty "execType", System.getProperty("execType")
+        systemProperty "masterIP", System.getProperty("masterIP")
+        systemProperty "imageVersion", System.getProperty("imageVersion")
+        systemProperty "skipServiceInstallation", System.getProperty("skipServiceInstallation")
```
Comment (shrids) [inline build.gradle]: We do not require this property for docker based run.

File: build.gradle [hunk 106]
```diff
@@ -563,6 +579,48 @@ project('test:system') {
...
+        systemProperty "segmentStoreExtraEnv", System.getProperty("segmentStoreExtraEnv")
+
+
+        if (System.getProperty("execType") == null) {
+            systemProperty "execType", "REMOTE_SEQUENTIAL"
```
Comment (shrids) [inline build.gradle]: we should change the default for gradle task `startSystemTestsWithDocker`

File: gradle.properties (hunk 82 above)
[the remark this answers is not in the document]
Comment (shrids) [reply gradle.properties]: minor: can we change the number of slaves to the right number? since we know that tests will not work with 3.

File: test/system/preTestScript.sh [hunk 107]
```diff
@@ -0,0 +1,42 @@
...
+#
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+CLUSTER_NAME=${1:-null}
```
Comment (shrids) [inline test/system/preTestScript.sh]: The script is only for jarvis environments and jarvis client should be installed. Could you add a comment stating the same?
This will be modified in future for handling cloud deployements too right?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 108]
```diff
@@ -0,0 +1,104 @@
...
+    private final double cpu = 0.1;
+    private final double mem = 1024.0;
+    private final URI zkUri;
+
+    public BookkeeperDockerService(String serviceName, final URI zkUri) {
+        super(serviceName);
+        this.zkUri = zkUri;
+    }
+
+    @Override
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: No need to override if we are just using the super method, this will reduce the amount of code ...

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 109]
```diff
@@ -0,0 +1,140 @@
...
+
+    private ServiceSpec setServiceSpec() {
+        Map<String, String> labels = new HashMap<>();
+        labels.put("com.docker.swarm.task.name", serviceName);
+
+        Mount mount = Mount.builder().type("volume").source("logs-volume").target("/tmp/logs").build();
+        String zk = zkUri.getHost() + ":" + ZKSERVICE_ZKPORT;
+        //System properties to configure SS service.
+        StringBuilder systemPropertyBuilder = new StringBuilder();
+        systemPropertyBuilder.append("-D").append("autoScale.muteInSeconds").append("=").append("120").append(" ")
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: We can refactor this...

File: test/system/src/main/java/io/pravega/test/system/framework/Utils.java [hunk 110]
```diff
@@ -24,6 +41,34 @@ public static String getConfig(final String key, final String defaultValue) {
         return System.getenv().getOrDefault(key, System.getProperty(key, defaultValue));
     }
 
+    public static Service createServiceInstance(final String serviceType, final URI zkUri, final URI hdfsUri, final  URI contUri) {
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/Utils.java]: We could break this separate methods likes createZookeeperService(), createBookkeeperService() and so on.
This would further simplify the test code...

**Comment by Prabha-Veerubhotla** [comment]
> minor: can we change the number of slaves to the right number? since we know that tests will not work with 3.

The docker based execution works with a cluster with 3 slaves. Tested it already.  In fact most of the plain clusters created are of 3 slaves.

File: test/system/preTestScript.sh (hunk 107 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: done, yes it might be modified , atleast we dont need jarvis commands there.

File: build.gradle (hunk 106 above)
Comment (Prabha-Veerubhotla) [reply build.gradle]: done.

File: build.gradle (hunk 105 above)
Comment (Prabha-Veerubhotla) [reply build.gradle]: It is needed, but we dont provide anything while running gradle task, because am setting the default to `false` down here, and System.getProperty() is defined here for the same.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 109 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 108 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: removed.

File: test/system/src/main/java/io/pravega/test/system/framework/Utils.java (hunk 110 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/Utils.java]: done.

File: gradle.properties (hunk 82 above)
[the remark this answers is not in the document]
Comment (fpj) [reply gradle.properties]: Please add a comment explaining these defaults. Say that they are defaults and explain how to set different values when running the task.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 111]
```diff
@@ -0,0 +1,171 @@
...
+    }
+
+    private ContainerConfig setContainerConfig(String methodName, String className) {
+
+        Map<String, String> labels = new HashMap<>(2);
+        labels.put("testMethodName", methodName);
+        labels.put("testClassName", className);
+
+        HostConfig hostConfig = HostConfig.builder()
+                .portBindings(ImmutableMap.of(DOCKER_CLIENT_PORT + "/tcp", Arrays.asList(PortBinding.of(LoginClient.MESOS_MASTER, DOCKER_CLIENT_PORT)))).networkMode("docker_gwbridge").build();
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Please break the long lines in this file, there are a few of them.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 112]
```diff
@@ -0,0 +1,103 @@
...
+
+        Map<String, String> labels = new HashMap<>();
+        labels.put("com.docker.swarm.service.name", serviceName);
+
+        Mount mount1 = Mount.builder().type("volume").source("index-volume").target("/bk/index")
+                .build();
+        Mount mount2 = Mount.builder().type("volume").source("logs-volume")
+                .target("/opt/dl_all/distributedlog-service/logs/")
+                .build();
+        //TODO: add journal and ledger mounted volumes
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: TODOs in the code should have an associated issue. Also, how does the missing configuration affects the behavior of BK? In other words, if we don't add journal and ledger volumes here, what happens?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java [hunk 113]
```diff
@@ -0,0 +1,98 @@
...
+import java.util.Map;
+import static io.pravega.test.system.framework.Utils.DOCKER_NETWORK;
+
+@Slf4j
+public class HDFSDockerService extends DockerBasedService {
+
+    private final int instances = 1;
+    private final double cpu = 0.5;
+    private final double mem = 2048.0;
+    private final String hdfsimage = "dsrw/hdfs:2.7.3-1";
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: What's `dsrw`?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java [hunk 114]
```diff
@@ -0,0 +1,143 @@
...
+import java.util.Arrays;
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import static io.pravega.test.system.framework.Utils.DOCKER_NETWORK;
+
+@Slf4j
+public class PravegaSegmentStoreDockerService extends DockerBasedService {
+
+    private static final int SEGMENTSTORE_PORT = 12345;
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: Is making the port constant going to cause conflicts? Should we randomize port instead?

File: test/system/preTestScript.sh [hunk 115]
```diff
@@ -0,0 +1,43 @@
...
+#
+# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+#The script is only for jarvis environments and jarvis client should be installed.
```
Comment (fpj) [inline test/system/preTestScript.sh]: Separate this comment from the license header, please. Put at least one new line in between.

File: build.gradle [hunk 116]
```diff
@@ -511,6 +511,8 @@ project('test:system') {
         compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: javaxwsrsApiVersion
         compile group: 'org.glassfish.jersey.core', name: 'jersey-client', version: jerseyVersion
         compile group: 'org.glassfish.jersey.media', name: 'jersey-media-json-jackson', version: jerseyVersion
+        compile group: 'org.glassfish.jersey.connectors', name:'jersey-apache-connector', version:jerseyVersion
+        compile group: 'com.spotify', name: 'docker-client', version: dockerClientVersion
```
Comment (fpj) [inline build.gradle]: What kind of license is this?

File: checkstyle/import-control.xml [hunk 117]
```diff
@@ -41,5 +41,7 @@
     <allow pkg="org.gaul.s3proxy" />
     <allow pkg="org.jclouds" />
     <allow pkg="org.glassfish.grizzly" />
+    <allow pkg="com.spotify" />
+    <allow pkg="org.hamcrest.core" />
```
Comment (fpj) [inline checkstyle/import-control.xml]: What's this dependency?

File: test/system/preTestScript.sh [hunk 118]
```diff
@@ -0,0 +1,43 @@
...
+if [ $CLUSTER_NAME != null ]; then
+    jarvis save $CLUSTER_NAME
+    if [ $MASTER != null ]; then
+      #master
+      jarvis ssh $CLUSTER_NAME "bash -s" -- < ./Change_Docker_Config_Master.sh $MASTER
+      echo "Copying token to host machine"
+      jarvis scp master-1:/home/nautilus/token.sh .
+
+      #slaves
+
```
Comment (fpj) [inline test/system/preTestScript.sh]: Unnecessary new line.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java [hunk 119]
```diff
@@ -0,0 +1,171 @@
...
+import java.util.concurrent.Executors;
+import java.util.concurrent.ScheduledExecutorService;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicReference;
+import static io.pravega.test.system.framework.Utils.DOCKER_NETWORK;
+import static io.pravega.test.system.framework.Utils.getConfig;
+import static org.junit.Assert.assertFalse;
+
+@Slf4j
+public class DockerRemoteSequential implements TestExecutor {
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: This is confusing. There is a class called `RemoteSequential` that extends `TestExecutor`. This is creating a `DockerRemoteSequential` class, which logical should extend `RemoteSequential`, but it does. The naming of classes isn't working well.

File: test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java [hunk 120]
```diff
@@ -9,21 +9,29 @@
...
+    private final TestExecutor marathonSequentialExecutor = new RemoteSequential();
+
+    @Getter(lazy = true)
+    private final TestExecutor dockerExecutor = new DockerRemoteSequential();
 
     public enum TestExecutorType {
         LOCAL,
+        DOCKER,
         REMOTE_SEQUENTIAL,
         REMOTE_DISTRIBUTED //TODO: Yet to be implemented.
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java]: I know this is not changed here, but we need an issue for this TODO.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 121]
```diff
@@ -0,0 +1,103 @@
...
+        String env1 = "ZK_URL=" + zk;
+        String env2 = "ZK=" + zk;
+        String env3 = "bookiePort=" + String.valueOf(BK_PORT);
+        String env4 = "DLOG_EXTRA_OPTS=-Xms512m";
+        stringList.add(env1);
+        stringList.add(env2);
+        stringList.add(env3);
+        stringList.add(env4);
+        final TaskSpec taskSpec = TaskSpec
+                .builder().restartPolicy(RestartPolicy.builder().maxAttempts(0).condition("none").build())
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: If I'm reading this right, then we aren't retrying here, is this the expected behavior?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java [hunk 122]
```diff
@@ -0,0 +1,103 @@
...
+                .containerSpec(ContainerSpec.builder()
+                        .hostname(serviceName)
+                        .labels(labels)
+                        .image(IMAGE_PATH + "/nautilus/bookkeeper:" + PRAVEGA_VERSION)
+                        .healthcheck(ContainerConfig.Healthcheck.create(null, 1000000000L, 1000000000L, 3))
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: What are these large values in this health check? Is this right?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 123]
```diff
@@ -0,0 +1,198 @@
...
+            log.error("Unable to list service details", e);
+        }
+        return uriList;
+    }
+
+    @Override
+    public CompletableFuture<Void> scaleService(final int instanceCount) {
+        try {
+            Preconditions.checkArgument(instanceCount >= 0, "negative value: %s", instanceCount);
+            Service.Criteria criteria = Service.Criteria.builder().serviceName(this.serviceName).build();
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: new line after the precondition check.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 124]
```diff
@@ -0,0 +1,198 @@
...
+            TaskSpec taskSpec = Exceptions.handleInterrupted(() -> dockerClient.listServices(criteria).get(0).spec().taskTemplate());
+            String serviceId = Exceptions.handleInterrupted(() -> dockerClient.listServices(criteria).get(0).id());
+            EndpointSpec endpointSpec = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId).spec().endpointSpec());
+            Service service = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId));
+            Exceptions.handleInterrupted(() -> dockerClient.updateService(serviceId, service.version().index(), ServiceSpec.builder().endpointSpec(endpointSpec).mode(ServiceMode.withReplicas(instanceCount)).taskTemplate(taskSpec).name(serviceName).build()));
+            String updateState = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId).updateStatus().state());
+            log.info("Update state {}", updateState);
+            return Exceptions.handleInterrupted(() -> waitUntilServiceRunning());
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: new line before the return statement.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 125]
```diff
@@ -0,0 +1,198 @@
...
+                        String[] uriArray = taskList.get(i).networkAttachments().get(0).addresses().get(0).split("/");
+                        ImmutableList<PortConfig> numPorts = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceList.get(0).id()).endpoint().spec().ports());
+                        for (int k = 0; k < numPorts.size(); k++) {
+                            int port = numPorts.get(k).publishedPort();
+                            log.info("Port {}", port);
+                            log.info("Uri list {}", uriArray[0]);
+                            URI uri = URI.create("tcp://" + uriArray[0] + ":" + port);
+                            uriList.add(uri);
+                        }
+
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: unnecessary new line.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 126]
```diff
@@ -0,0 +1,198 @@
...
+            String serviceId = Exceptions.handleInterrupted(() -> dockerClient.listServices(criteria).get(0).id());
+            EndpointSpec endpointSpec = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId).spec().endpointSpec());
+            Service service = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId));
+            Exceptions.handleInterrupted(() -> dockerClient.updateService(serviceId, service.version().index(), ServiceSpec.builder().endpointSpec(endpointSpec).mode(ServiceMode.withReplicas(instanceCount)).taskTemplate(taskSpec).name(serviceName).build()));
+            String updateState = Exceptions.handleInterrupted(() -> dockerClient.inspectService(serviceId).updateStatus().state());
+            log.info("Update state {}", updateState);
+            return Exceptions.handleInterrupted(() -> waitUntilServiceRunning());
+        } catch (DockerException e) {
+            throw new TestFrameworkException(TestFrameworkException.Type.RequestFailed, "Unable to scale service to given instances.Test Failure", e);
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Can we add more detail to the exception message? In particular, about `given instances`. Also, add a colon like this: `... Test failure: `.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 47 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: Why is throwing a generic `RuntimeException` right here? Should it be more specific? Note that I'm not following the upstream flow, so I don't know how this is being handled.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java [hunk 127]
```diff
@@ -0,0 +1,78 @@
...
+        Map<String, String> labels = new HashMap<>();
+        labels.put("com.docker.swarm.service.name", serviceName);
+
+        final TaskSpec taskSpec = TaskSpec
+                .builder()
+                .containerSpec(ContainerSpec.builder().image(ZK_IMAGE)
+                        .hostname(serviceName)
+                        .labels(labels)
+                        .healthcheck(ContainerConfig.Healthcheck.create(null,
+                                1000000000L, 1000000000L, 3)).build())
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: Same question about the large values in the health check.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 128]
```diff
@@ -549,41 +546,61 @@ static URI startZookeeperInstance() {
...
-        controllerService.scaleService(3, true);
+        Futures.getAndHandleExceptions(controllerService.scaleService(3), ExecutionException::new);
         List<URI> conUris = controllerService.getServiceDetails();
+        log.info("conuris {} {}", conUris.get(0), conUris.get(1));
         log.debug("Pravega Controller service  details: {}", conUris);
         // Fetch all the RPC endpoints and construct the client URIs.
-        final List<String> uris = conUris.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
-                .collect(Collectors.toList());
+        List<String> uris;
+        if (Utils.isDockerLocalExecEnabled()) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: It is a bit odd that the test case needs to know whether it is running on docker or something else. Any specific behavior so be abstracted away from the test cases.

File: test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java [hunk 129]
```diff
@@ -84,16 +81,27 @@ public static void setup() {
...
         if (!bkService.isRunning()) {
             bkService.start(true);
         }
 
         List<URI> bkUris = bkService.getServiceDetails();
         log.debug("bookkeeper service details: {}", bkUris);
 
+        //start HDFS
+        URI hdfsUri = null;
+        if (Utils.isDockerLocalExecEnabled()) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java]: Same comment here about environment specific logic.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 130]
```diff
@@ -46,14 +48,15 @@
...
 @RunWith(SystemTestRunner.class)
 public class ControllerFailoverTest {
-    private static final String TEST_CONTROLLER_SERVICE_NAME = "testcontroller";
     private static final ScheduledExecutorService EXECUTOR_SERVICE = Executors.newScheduledThreadPool(5);
+    private Service controllerService1 = null;
+    private URI controllerURIDirect = null;
 
     @Environment
-    public static void setup() throws InterruptedException, MarathonException, URISyntaxException {
+    public static void initialize() throws InterruptedException, MarathonException, URISyntaxException, ExecutionException {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Why is it changing from setup to initialize? The change seems to be gratuitous.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 131]
```diff
@@ -63,34 +66,49 @@ public static void setup() throws InterruptedException, MarathonException, URISy
...
         if (!bkService.isRunning()) {
             bkService.start(true);
         }
 
         List<URI> bkUris = bkService.getServiceDetails();
         log.debug("bookkeeper service details: {}", bkUris);
 
+        //start HDFS
+        URI hdfsUri = null;
+        if (Utils.isDockerLocalExecEnabled()) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Same comment about environment specific behavior on test cases.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java [hunk 132]
```diff
@@ -99,27 +117,38 @@ public static void setup() throws InterruptedException, MarathonException, URISy
...
-    private static void stopTestControllerService() {
-        log.info("Stopping test controller service");
-        Service controllerService = new PravegaControllerService(TEST_CONTROLLER_SERVICE_NAME, null);
-        controllerService.stop();
+        List<URI> conUris = controllerService1.getServiceDetails();
+        log.info("conuris {} {}", conUris.get(0), conUris.get(1));
+        log.debug("Pravega Controller service  details: {}", conUris);
+        // Fetch all the RPC endpoints and construct the client URIs.
+        List<String> uris;
+        if (Utils.isDockerLocalExecEnabled()) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: There are lots of these environment specific blocks, please revisit all those and abstract away the behavior.

File: build.gradle (hunk 116 above)
Comment (Prabha-Veerubhotla) [reply build.gradle]:
```
spotify/docker-client is licensed under the
Apache License 2.0
```

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java (hunk 113 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/HDFSDockerService.java]: It's the repo  info of @dsrw in docker-hub repo, from which  we are pulling the hdfs image.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 114 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: No, it shouldnt cause any problem and also the docker file used to build segmentstore image exposes this ports. The docker client needs to access only the port `2375` of master node. Apart from that all the other ports on master and slave nodes are free.
zk : 2181
bk: 3181
controller :9090, 9091
segmentstore: 12345.

So, it won't be a problem.

File: test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java (hunk 129 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java]: As we are using a plain cluster, with nothing installed apart from docker daemon, we need to deploy even hdfs  with other pravega components, when we are executing system tests through docker swarm .
In our previous usages, we always have hdfs deployed in the cluster as a part of cluster creation.
So you will seeing this in every test case.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 131 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: answered above.  need to deploy hdfs as it will not come as a part of cluster.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 132 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: answered above.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 130 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: This is changed because another method  with name `setup`  was added which ensures everything is deployed and collects the `controllerUri` to use it in @Test method. The  instances instantiated in a method with `@Environment` cannot be accessed else where in code. So, this leads to defining new method, which just collects the required information of the services deployed and pass into on the code wherever required.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 121 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: Yes, if we enable this. If there is a problem with container, it will still keep on restarting and we might never know that it has some issue. This ensures that the container fails/exits with a status other than `0`, if there is an issue with container deployment with that config.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 128 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: So here, the test case, we try to access controller using both `tcp://` and `pravega://`  networks. And in the docker based execution ,  the communication works only in `tcp` network.
so , docker based execution tries to access controller only on `tcp://`

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 119 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: The name `DockerRemoteSequential` is used as the tests are running via docker swarm and they are executed remotely in a sequential manner. As this is not using any method from `RemoteSequential` , the inheritance is not required. But,  all the files which are needed for 
 different ways of execution  like docker based/ marathon based/ local exec/ distributed will extend from  TestExecutor, as they are different types of execution.

If there is a problem with this naming convention, I will change it . Can you please suggest a better one ?

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 112 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: Actually, i don't see any difference without these mounted volumes.

File: checkstyle/import-control.xml (hunk 117 above)
Comment (Prabha-Veerubhotla) [reply checkstyle/import-control.xml]: removed. initially it was used for  cases like `assertThat` , later i have resorted to junit and forgot to remove this.

**Comment by Prabha-Veerubhotla** [comment]
> Please add a comment explaining these defaults. Say that they are defaults and explain how to set different values when running the task.

done.

File: test/system/preTestScript.sh (hunk 115 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: done.

File: test/system/preTestScript.sh (hunk 118 above)
Comment (Prabha-Veerubhotla) [reply test/system/preTestScript.sh]: removed.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 111 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: formatted.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 125 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: removed.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 123 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: added.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 124 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: added.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 126 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: done.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 122 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: Yes, it is . The create()  accepts parameters in nano seconds` create(cmd, interval, Timeout, retries).`

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java (hunk 127 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/ZookeeperDockerService.java]: answered above.

File: test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java (hunk 120 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/TestExecutorFactory.java]: done.

**Comment by Prabha-Veerubhotla** [comment]
> Why is throwing a generic RuntimeException right here? Should it be more specific? Note that I'm not following the upstream flow, so I don't know how this is being handled.

This particular code is not added by me. And as a part of pr comments,  i have added `throws` so as to not suppress the stack trace. The context here is ,  this method `getCustomEnvVars` sets the 
env for Tier-2 storage. The key-value pairs are passed as a string.  If the length is not = 2 , that is if both key and value doesn't exist, we need to throw an exception. I am not really sure of what to throw here specifically. Please suggest.
key-value pair example `TIER2_STORAGE::HDFS`

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 132 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: Apart from in places where hdfs has to be deployed, and in Controllerfailovertest which accesses controller via `tcp://`  and `pravega://` ,  the abstraction is done in remaining places already using methods like `createZookeeperService ` .

File: build.gradle (hunk 116 above)
Comment (fpj) [reply build.gradle]: OK.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 119 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: Let's talk in generic terms. Say I want to implement two kinds of servers that have some common functionality. I'd do, for example, something like:

```
interface Server {
...
}

class BlueServer implements Server {
... 
}

class YellowServer implements Server {
...
}
```

Both of the implementation classes have `Server` as a common suffix and that indicates some commonality. In the concrete case here, if I have one class called  `RemoteSequential` and another `DockerRemoteSequential`, then it sounds like the latter extends the former, which is not true at all here. Consequently, you have a couple of choices to make this right:

1- If `DockerRemoteSequential` and `RemoteSequential` have anything in common, then you need to rename the latter to say `DCOSRemoteSequential` and have them both extend or implement some common base class or interface called `RemoteSequential`.
2- If they share nothing other than the `TestExecutor`, then you better rename `DockerRemoteSequential` to something else.

It all boils down to understanding how much the two classes have in common.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 121 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: Ok.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 122 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: If I'm reading this right, the interval and timeout values are of 1s, and at least the timeout seems short to me.

For clarity, consider doing something like:

```
Duration.ofSeconds(10).toNanos()
```

To represent a duration of 10 seconds in nanoseconds.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 114 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: Ok.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 128 above)
Comment (fpj) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: I understand, but it doesn't make sense to ask developers of test cases to implement environment specific functionality. This should be abstracted away in some helper class .

File: test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java (hunk 129 above)
Comment (fpj) [reply test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java]: Same issue, we need to abstract away any behavior that is specific to the environment and encapsulate it in some helper class.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 130 above)
Comment (fpj) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: It is odd to have both a setup method and an initialize method, they in principle imply very similar concepts, which is to do any necessary wiring and setting that the instance needs to start executing. To me this smells like a problem with the abstractions.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java (hunk 47 above)
Comment (fpj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaSegmentStoreDockerService.java]: OK, I followed that paths through which the exception will bubble up, and it seems fine.

File: test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java (hunk 119 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/DockerRemoteSequential.java]: ok. done,  renamed it to `DockerBasedTestExecutor` as it doesn't have anything in common with `RemoteSequential` .

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java (hunk 122 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/BookkeeperDockerService.java]: done.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 128 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: Created a parent and two sub classes for the same.

File: test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java (hunk 129 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AutoScaleTest.java]: Done, taken care in helper method.

File: test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java (hunk 130 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/ControllerFailoverTest.java]: renamed the `setup` to `getControllerInfo`  as we use it for the same.

**Comment by Prabha-Veerubhotla** [comment]
[Docker swarm based system test framework](https://trello.com/c/28kkoNrw/23-docker-swarm-based-system-test-framework)
