### PR TITLE
Issue 7147: New client API to cancel all outstanding checkpoints

### LINKED ISSUE #7147: New client API to cancel all outstanding checkpoints
**Problem description**
In certain scenario when Client application call for `initiateCheckpoint()` by passing executor threadpool and because of any reason if thread poll is shutdown with some unexpected runtime exception(Observed in case of DNS down scenario), then it's been observed that outstanding checkpoint completion gets impacted. In such scenario adding new API to cancel all outstanding checkpoint helps in recovery.

**Problem location**
ReaderGroupImpl.java

**Suggestions for an improvement**
Adding new API to cancel all outstanding checkpoint.

### PR DESCRIPTION
**Pull request by PrajnaU**
**Change log description**  
Adding a new client API, which will cancel all outstanding checkpoints.
**Purpose of the change**  
Fixes #7147 

**What the code does**  
Addition of cancelOutstandingCheckpoints() in ReaderGroup which calls removeOutstandingCheckpoints() in checkpointState class to remove the outstanding checkpoints.

**How to verify it**  
When cancelOutstandingCheckpoints() is called, it must clear the outstanding checkpoints.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/ReaderGroup.java [hunk 1]
```diff
@@ -47,6 +47,8 @@ public interface ReaderGroup extends ReaderGroupNotificationListener, AutoClosea
      */
     String getScope();
 
+    boolean cancelOutstandingCheckpoints();
```
Comment (a6dulaleem) [inline client/src/main/java/io/pravega/client/stream/ReaderGroup.java:50]: put some info regarding this method

File: client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java [hunk 2]
```diff
@@ -196,6 +196,23 @@ List<String> getOutstandingCheckpoints() {
...
+    boolean removeOutstandingCheckpoints() {
+       List<String> checkpoint = getOutstandingCheckpoints();
+       if (checkpoint.isEmpty()) {
+           return false;
+       }
+       for (String cp:checkpoint) {
+           uncheckpointedHosts.remove(cp);
+           checkpointPositions.remove(cp);
+       }
+    recomputeCheckpointIndex();
```
Comment (a6dulaleem) [inline client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java:212]: indent it correctly

File: client/src/main/java/io/pravega/client/stream/ReaderGroup.java (hunk 1 above)
Comment (PrajnaU) [reply client/src/main/java/io/pravega/client/stream/ReaderGroup.java:56]: I have added the information now

File: client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java (hunk 2 above)
Comment (PrajnaU) [reply client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java]: Indentation has been corrected now.

File: client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java [hunk 3]
```diff
@@ -196,6 +196,23 @@ List<String> getOutstandingCheckpoints() {
                           .collect(Collectors.toList());
     }
 
+    /**
+     * Removes the outstanding checkpoints.
+     * @return false when there are no outstanding checkpoints otherwise true
+     */
+    boolean removeOutstandingCheckpoints() {
+       List<String> checkpoint = getOutstandingCheckpoints();
+       if (checkpoint.isEmpty()) {
```
Comment (ShwethaSNayak) [inline client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java:205]: If checkpoint map is empty then log message and return true

Comment (a6dulaleem) [reply client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java:205]: If we are always returning true, in that case its redundant to put return type Boolean. May be we can make it void and put some logs in the method ?

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 4]
```diff
@@ -541,4 +541,13 @@ public void close() {
...
         sequentialProcessor.close();
     }
+
+    /**
+     * Cancels the outStanding checkpoints.
+     * @returns true if the outStanding checkpoints are cleared.
+     */
+    public boolean cancelOutstandingCheckpoints() {
+        ReaderGroupState state = synchronizer.getState();
+        return state.getCheckpointState().removeOutstandingCheckpoints();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java:551]: Do not modify the state synchronizer state without going through the synchronizer. This will result in different hosts having different states. There needs to be an update to the ReaderGroupState object to cancel the checkpoints. See the stateSynchronizer documentation and the existing updates in ReaderGroupState to see how this is done.

**Review by tkaitchuck — CHANGES_REQUESTED** [review]

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java (hunk 4 above)
Comment (PrajnaU) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: I have implemented the above suggestion.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 5]
```diff
@@ -1228,6 +1229,51 @@ private void write00(ClearCheckpointsBefore object, RevisionDataOutput out) thro
...
+            protected void declareVersions() {
+                version(0).revision(0, this::write00, this::read00);
+            }
+
+           private void read00(RevisionDataInput in, RemoveOutstandingCheckpointsBuilder builder) throws IOException {
+               builder.build();
+            }
+
+            private void write00(RemoveOutstandingCheckpoints object, RevisionDataOutput out) throws IOException {
+                out.writeUTF(object.toString());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java:1272]: Here a string is being written when serializing but it not being read when deserializing. So what's the point in writing it?

Comment (PrajnaU) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: Have made the above suggested change.

**Review by tkaitchuck — APPROVED** [review]
