### PR TITLE
Issue 7269: Update valid offset on SegmentIterator next TruncatedDataException case

### LINKED ISSUE #7269: SegemntIterator next call fails on a TruncatedDataException.
**Describe the bug**
If  a SegmentIterator is iterating on truncated segment then it throws TruncatedDataException and there is no way to move iterator on the next available item. Currently we need to iterate all the truncated events to reach a valid available event.

**To Reproduce**
1. Create a stream with 1 segment.
2. Add events in stream. 
3. Scale up the stream to 2 segments.
4. Truncate the stream on segment 1 using streamcut.
5. Try to read events from segment 1 offset 0.
6. This will throw TruncatedDataException.  

**Screenshots**
NA

**Additional information**
By introducing this change, if TruncatedDataException occurs and call iterator.next . it will continue from valid event after truncation.

### PR DESCRIPTION
**Pull request by munish1789**
**Change log description**  
Update valid offset on SegmentIterator next TruncatedDataException case, so that iterator next call can start reading from valid offset

**Purpose of the change**  
Fixes #7269 

**What the code does**  
It updates the valid offset when TruncateddataException is catched.

**How to verify it**  
After setting Truncation policy Longevity read should not due to TruncatedDataException.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java [hunk 1]
```diff
@@ -43,14 +50,19 @@ public class SegmentIteratorImpl<T> implements SegmentIterator<T> {
     private final long startingOffset;
     private final long endingOffset;
     private final EventSegmentReader input;
+    private final long timeoutInMilli = 2000L;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java:53]: This seems needlessly aggressive given that there are no retries or way to configure the value.

**Review by tkaitchuck — APPROVED** [review]

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java [hunk 2]
```diff
@@ -78,13 +90,27 @@ public T next() {
                                        }
                                        return buffer;
                                    } catch (NoSuchSegmentException | SegmentTruncatedException e) {
+                                       handleSegmentTruncated(segment);
                                        throw new TruncatedDataException("Segment " + segment + " has been truncated.");
```
Comment (crazyzhou) [inline client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java:94]: It throws a `TruncatedDataException` in the impl class, but there is no hint for this from the base method `next()`. Can we improve it?

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java [hunk 3]
```diff
@@ -78,13 +90,27 @@ public T next() {
...
+    private void handleSegmentTruncated(Segment segmentId)  {
+        log.info("{} encountered truncation for segment while read{} ", this, segmentId);
+        @Cleanup
+        SegmentMetadataClient metadataClient = segmentMetadataClientFactory.createSegmentMetadataClient(segmentId,
+                DelegationTokenProviderFactory.create(controller, segmentId, AccessOperation.READ));
+        try {
+            long startingOffset = Futures.getThrowingExceptionWithTimeout(metadataClient.getSegmentInfo(), timeoutInMilli).getStartingOffset();
+            input.setOffset(startingOffset);
+        } catch (TimeoutException te) {
+            log.warn("A timeout has occurred while attempting to retrieve segment information from the server");
```
Comment (ShwethaSNayak) [inline client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java:110]: Can add info about segment in warning log for better clarity

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java (hunk 1 above)
Comment (Bhupender-Y) [reply client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java:53]: Can we use clientConfig defaultTimeout here?

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java (hunk 3 above)
Comment (munish1789) [reply client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java]: done

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java (hunk 2 above)
Comment (munish1789) [reply client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java:94]: Added java docs https://github.com/pravega/pravega/blob/7bf8054c45d5cf3755a09724aa34b87a15ccb702/client/src/main/java/io/pravega/client/batch/SegmentIterator.java#L31C1-L31C1

File: client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java (hunk 1 above)
Comment (munish1789) [reply client/src/main/java/io/pravega/client/batch/impl/SegmentIteratorImpl.java]: Updated to use timeout from clientConfig.
