### PR TITLE
Issue 2438: (SegmentStore) Cannot truncate sealed segments

### LINKED ISSUE #2438: Truncating Sealed Segments may pose issues
**Problem description**
```
2018-04-05 01:15:39,615 19383498 [core-8] DEBUG i.p.s.s.reading.ContainerReadIndex - ReadIndex[3]: readDirect (StreamSegmentId = 730257, Offset = 67108864, Length = 4194304).
2018-04-05 01:15:39,637 19383520 [core-9] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[474865].Error.
java.lang.IllegalArgumentException: handle must not be read-only.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.asWritableHandle(RollingStorage.java:759)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.truncate(RollingStorage.java:464)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$truncate$6(AsyncStorageWrapper.java:120)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$runAsync$15(AsyncStorageWrapper.java:206)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
Segment Store

**Suggestions for an improvement**
Theory is:
1. A Segment is Sealed, and the Seal gets applied to Storage.
2. The Segment is forgotten in the Segment Store due to inactivity
3. A Segment Truncate request is issued for the Segment. The Store processes that very well, however the StorageWriter cannot apply it to Storage due to the fact that the handle it gets from `openWrite` is read-only (this is by design: open-writing a sealed segment will result in a read-only handle).

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in `RollingStorage` where it was not possible to truncate a sealed segment if the given SegmentHandle was acquired after sealing the segment.
- When calling `openWrite` on a sealed segment, the returned handle is read-only (since no further changes are allowed on the segment)
- When calling `truncate`, `RollingStorage` expected a read-write handle, which was causing the problem described in the issue associated with this change.
    - This was changed to accept a read-only handle, but only if the Segment is Sealed (otherwise a read-write handle is required.
    - The only difference in truncation between a Sealed and Non-sealed segment is that for a Sealed segment we will not be able to fully truncate the whole segment. Since we cannot modify the header file for a Sealed segment, deleting the last chunk would cause us to lose valuable information required to compute the Segment's length. As such, for Sealed segments, if we have to truncate the whole thing, we will leave the last chunk in there.

**Purpose of the change**
Fixes #2438.

**What the code does**
Allows RollingStorage to truncate sealed segments.

**How to verify it**
New unit test added to verify this scenario.

### CODE REVIEW

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java [hunk 1]
```diff
@@ -472,13 +476,20 @@ public void truncate(SegmentHandle handle, long truncationOffset) throws StreamS
...
+            // all existing data.
             rollover(h);
+
+            // We are free to delete all chunks.
+            deleteChunks(h, s -> canTruncate(s, truncationOffset));
+        } else {
+            // Either we were asked not to truncate the whole segment, or we were, and the Segment is sealed. If the latter,
+            // then the Header is also sealed, we could not have done a quick rollover; as such we have no option but to
+            // preserve the last chunk so that we can recalculate the length of the Segment if we need it again.
+            deleteChunks(h, s -> canTruncate(s, truncationOffset) && s.getLastOffset() < h.length());
```
Comment (fpj) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: I'm not sure I understand the predicate here because of the following.

`canTruncate` only evaluates to `true` in the case that the segment is entirely under the truncation offset:

```
return segmentChunk.getStartOffset() < truncationOffset
                && segmentChunk.getLastOffset() <= truncationOffset;
```

We have already verified above that: `truncationOffset <= h.length()` (Line 476).  Consequently, the only case in which `canTruncate` evaluates to `true` and `s.getLastOffset() < h.length()` to `false`, which prevents the chunk from being deleted, is the one in which ` s.getLastOffset() = truncationOffset = h.length()`. But, if these three values are all equal, then I think we are saying that we want to delete the whole segment, no? If this analysis is right, then using `canTruncate` alone should be sufficient.

Could you help me sort out my confusion? 

Another related but separate question is where we update `h.length()` upon truncation. I understand that is not related to this bug, it is for my own understanding.

**Comment by RaulGracia** [comment]
I'm currently working on #2011 (integration/system tests on segment truncation). As this issue is related to this PR, please let me know if there is any specific scenario that you would like to test (integration/system test) that could be interesting to include in #2011.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: You are correct, but only in the case when `h.isSealed() == false` (segment is not sealed). As you can see from this `if-else` block, you are commenting on the `else` part, which means this applies only for a `sealed` segment. 

What I am doing with this condition is, if we were asked to truncate on the last offset (otherwise this would not be a problem), then delete all chunks but the last. So, if `truncationOffset == h.length()`,  the condition `canTruncate(s, truncationOffset) && s.getLastOffset() < h.length()` is:
- `true` for all chunks but the last chunk
- `false` for the last chunk (because `canTruncate == true` but the second part evaluates to `false`.

This is the intended behavior, which is fixed with this PR.

`h.length()` is never updated during truncation. As per our design, truncating a segment does not change its length, otherwise we'd have a mess with offsets remapping to smaller offsets, thus leading to inconsistent writes. The length is only modified upon a successful write or concat operation. 

There is no `StartOffset` concept in Tier2 (that is stored in the Segment's Metadata in the Store, in an upstream layer). If you issue a truncate at offset N in Tier2, then the `RollingStorage` will delete everyting before offset M<=N in the segment, where M is the last rolling point for that segment. The range [M,N) will still be accessible in Tier2, but it will not via the Store's API (due to the latter enforcing the StartOffset, which it can stash away into the metadata).

Comment (fpj) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: Thanks for the clarification @andreipaduroiu . The thing I'm missing now is that I don't understand why we want to keep the last chunk and header around in the case that `truncationOffset == h.length()`. Aren't we saying in this case that we want to delete any remaining data in the segment? 

There is probably something really basic that is escaping my attention.

Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: Hmm, I hoped the comment right above this line would be doing a better job at explaining the problem (also explained in the last bullet in the PR description). 

At this point the Header file is sealed, wo we cannot make any more modifications to it. The header file only has pointers to the individual chunks. In order to calculate the length of the segment, it needs information from Tier2 for the last chunk (starting offset + length). If we delete the last chunk, then we will have no way of re-acquiring this information. For non-sealed segments, it's simpler, since we just force a rollover at that point and create an empty chunk. but for sealed ones, we cannot do that since we cannot modify the header file.

Comment (fpj) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: > the Header file is sealed, wo we cannot make any more modifications to it

Ok.

>  In order to calculate the length of the segment, it needs information from Tier2 for the last chunk (starting offset + length).

Ok.

> If we delete the last chunk, then we will have no way of re-acquiring this information.

Ok.

I don't think any of that answers my question, though:

In the case that `truncationOffset == h.length()`,  aren't we saying that we want to delete any remaining data in the segment? My interpretation is that we are essentially getting rid of the segment in this case, and consequently, there is no reason to keep anything around. Again, I'm focusing on the `truncationOffset == h.length()` scenario.

Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/rolling/RollingStorage.java]: No. Just because we truncate a sealed segment at the end doesn't mean we want to delete it. If we want to delete it then the controller or client needs to request that explicitly.
