### PR TITLE
Issue 5535: (SegmentStore) Refactoring ExtendedS3 Test Mocks

### LINKED ISSUE #5535: Flaky tests in ExtendedS3SimpleStorageTests due to S3Proxy
**Problem description**
```
io.pravega.storage.extendeds3.ExtendedS3SimpleStorageTests$ExtendedS3ChunkStorageTests > testDeleteAfterOpen FAILED
    java.io.IOException: Failed to bind to /127.0.0.1:36664
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.gaul.s3proxy.S3Proxy.start(S3Proxy.java:389)
        at io.pravega.storage.extendeds3.S3ProxyImpl.start(S3ProxyImpl.java:83)
        at io.pravega.storage.extendeds3.ExtendedS3TestContext.<init>(ExtendedS3TestContext.java:47)
        at io.pravega.storage.extendeds3.ExtendedS3SimpleStorageTests$ExtendedS3ChunkStorageTests.before(ExtendedS3SimpleStorageTests.java:81)

        Caused by:
        java.net.BindException: Address already in use
            at java.base/sun.nio.ch.Net.bind0(Native Method)
            at java.base/sun.nio.ch.Net.bind(Net.java:455)
            at java.base/sun.nio.ch.Net.bind(Net.java:447)
            at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
            at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
            at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
            ... 10 more
```

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Created `S3Mock` which is an in-memory mock for S3 Storage. This is to be used in conjunction with `S3ClientMock` (which subclasses `S3JerseyClient` and overrides any methods that go over the network).
- Retired `S3ProxyImpl.java` (and `org.gaul.s3proxy`).
- Retired `S3FileSystemImpl.java` and replaced its usages with `S3Mock`.
- Simplified `ExtendedS3Storage.listSegments` iterator by invoking actual iterator only once.

**Purpose of the change**  
Fixes #5535.

**What the code does**  
See description above. The `S3Mock` class is essentially the former `S3FileSystemImpl` class but with all file access replaced by in-memory buffer access. Very little new code was added as part of this change.

This also reduces the overall build time by about 2-3 minutes.

**How to verify it**  
Build must pass.

### CODE REVIEW

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 1]
```diff
@@ -0,0 +1,315 @@
...
+    }
+
+    public PutObjectResult putObject(PutObjectRequest request) {
+        if (request.getObjectMetadata() != null) {
+            request.setObjectMetadata(null);
+        }
+        String objectName = getObjectName(request.getBucketName(), request.getKey());
+        synchronized (this.objects) {
+            if (this.objects.containsKey(objectName)) {
+                throw new S3Exception(String.format("Object '%s/%s' exists.", request.getBucketName(), request.getKey()), 0, "PreconditionFailed", "");
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:82]: HTTP code for precondition failed is 412. Let's use constant from org.apache.http.HttpStatus

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3ClientMock.java [hunk 2]
```diff
@@ -86,6 +87,15 @@ public ListObjectsResult listObjects(String bucketName, String prefix) {
         return s3Impl.listObjects(bucketName, prefix);
     }
 
+    @Override
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3ClientMock.java:90]: list object needs to return paginated results.
For now it may be okay , but we need to fix this to implement pagination.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 3]
```diff
@@ -0,0 +1,315 @@
...
+                throw new S3Exception(String.format("Object '%s/%s' does not exist.", bucketName, key), 404, "NoSuchKey", key);
+            }
+
+            final int startOffset = (int) (long) range.getFirst();
+            final int length = (int) (range.getLast() + 1 - range.getFirst());
+            BufferView objectContent = od.content;
+            if (startOffset < objectContent.getLength()) {
+                objectContent = new ByteArraySegment(objectContent.slice(0, startOffset).getCopy());
+            } else if (startOffset > objectContent.getLength()) {
+                throw new S3Exception("", 0, "InvalidRange", "");
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:104]: http code for invalid range  is 416.
Let's use org.apache.http.HttpStatus.SC_REQUESTED_RANGE_NOT_SATISFIABLE

Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:104]: what happens when requested length is more than length of object?

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 4]
```diff
@@ -0,0 +1,315 @@
...
+            deleteObject(request.getBucketName(), obj.getKey());
+        }
+        return new DeleteObjectsResult();
+    }
+
+    public ListObjectsResult listObjects(String bucketName, String prefix) {
+        ListObjectsResult result = new ListObjectsResult();
+        List<S3Object> list;
+        String objectPrefix = getObjectName(bucketName, prefix);
+        String bucketPrefix = getObjectName(bucketName, "");
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:189]: Seems bit hacky doing it this way.
may be use a special separator char eg.  `:` --> `bucket_name:object_name` 

or simply use bucketName.length+1

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 5]
```diff
@@ -0,0 +1,315 @@
...
+            Map<Integer, CopyPartRequest> partMap = this.multipartUploads.get(objectName);
+            if (partMap == null) {
+                throw new S3Exception("NoSuchKey", 404, "NoSuchKey", "");
+            }
+
+            if (!this.objects.containsKey(objectName)) {
+                throw new S3Exception("NoSuchKey", 404, "NoSuchKey", "");
+            }
+
+            val partObjects = partMap.entrySet().stream().sorted(Comparator.comparingInt(Map.Entry::getKey))
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:261]: I am not sure what is the expected behavior here.
What if we have part 1, 3, 7 only.
Is it still a valid MPU request ? Or it is expected to throw in such cases?

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 6]
```diff
@@ -0,0 +1,315 @@
...
+                throw new S3Exception("InvalidRange", org.apache.http.HttpStatus.SC_REQUESTED_RANGE_NOT_SATISFIABLE, "InvalidRange", "");
+            }
+        }
+    }
+
+    public String initiateMultipartUpload(String bucketName, String key) {
+        String objectName = getObjectName(bucketName, key);
+        synchronized (this.objects) {
+            this.multipartUploads.put(objectName, new HashMap<>());
+            return Integer.toString(this.multipartUploads.size());
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:245]: where is this string used?

I believe you can have multiple MPU requests against the same object.

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3ClientMock.java (hunk 2 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3ClientMock.java:90]: This is the same behavior as in the defunct `S3FileSystemImpl.java`.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 1 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:82]: Would love to do so, but that package is not defined as a dependency of this project (segmentstore:storage(test)).

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 3 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:104]: HTTP code - see above.

Length out of bounds - the `.slice` invocation above will throw.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 6 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:245]: From what I could tell, it returns some identifier that is then used to reference this MPU.

This implementation was taken from the defunct `S3ProxyFileSystemImpl.java`.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java [hunk 7]
```diff
@@ -0,0 +1,315 @@
...
+            if (od == null) {
+                throw new S3Exception("NoSuchKey", 404, "NoSuchKey", "");
+            }
+
+            final int offset = (int) (long) range.getFirst();
+            final int length = (int) (range.getLast() - range.getFirst() + 1);
+            try {
+                return od.content.slice(offset, length).getReader();
+            } catch (Exception ex) {
+                throw new S3Exception("InvalidRange", org.apache.http.HttpStatus.SC_REQUESTED_RANGE_NOT_SATISFIABLE, "InvalidRange", "");
```
Comment (sachin-j-joshi) [inline bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:236]: Looks like you do have the reference to org.apache.http.HttpStatus

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 3 above)
Comment (sachin-j-joshi) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:104]: I think we do have that reference on line 236

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 1 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:82]: Thanks for the pointer. I was looking at the wrong thing. I updated all response codes in this class.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 3 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:104]: Duh. Fixed all of them.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 4 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:189]: Fixed.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 6 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:245]: I changed to a monotonically increasing AtomicLong so we don't ever have collisions.

File: bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java (hunk 5 above)
Comment (andreipaduroiu) [reply bindings/src/test/java/io/pravega/storage/extendeds3/S3Mock.java:261]: Fixed.

**Review by sachin-j-joshi — APPROVED** [review]
Thanks for fixing this.
Once tests pass in jenkins and github. Then let's just ship it !
If there are subtle issues that crop up, we'll fix them as we find them.
