### PR TITLE
Issue 6739: Changed Kubernetes Version from 8.0.0 to 15.0.1. #6739

### LINKED ISSUE #6739: Test Pravega continuous and Test Pravega continuous-1 failing with fluent bit related error.
**Describe the bug**
TPC and TPC-1 is failing due to some reason. The build is failing at this line in the fluentBitSetUp.sh `pravega/test/system/kubernetes/fluentBitSetup.sh fetch-all-logs --export-path=archive --skip-bundle-compression`. The error due to which the build is failing   ```15:40:38  env: can't execute 'bash': No such file or directory```

### PR DESCRIPTION
**Pull request by a6dulaleem**
**Change log description**  
Changed the Kubernetes version from 8.0.0 to 15.0.1 and also done the necessary changes in the kubernetes files for that specific version. 

**Purpose of the change**  
To fix #6739 

**What the code does**  
Changed api are listed below for a classes:

K8sClient.java

- readNamespace(namespace, PRETTY_PRINT)
- createNamespace(body, PRETTY_PRINT, DRY_RUN, FIELD_MANAGER, null)
- createNamespacedPodAsync(namespace, pod, PRETTY_PRINT, DRY_RUN, FIELD_MANAGER, null, callback)
- listNamespacedPodAsync(namespace, PRETTY_PRINT, ALLOW_WATCH_BOOKMARKS, null, null, podName, null, null, null, null, false, callback)
- createNamespacedDeploymentAsync(namespace, deploy, PRETTY_PRINT, DRY_RUN, FIELD_MANAGER, null, callback)
- createNamespacedCustomObjectAsync(customResourceGroup, version, namespace, plural, request, PRETTY_PRINT, null,  null, callback)
- deleteNamespacedCustomObjectAsync(customResourceGroup, version, namespace, plural, name, 0, false, null, null, options, callback);
- createCRD(final V1CustomResourceDefinition crd)
- public CompletableFuture<V1ClusterRole> createClusterRole(V1ClusterRole role)
- public CompletableFuture<V1ClusterRoleBinding> createClusterRoleBinding(V1ClusterRoleBinding binding)
-  public CompletableFuture<V1RoleBinding> createRoleBinding(String namespace, V1RoleBinding binding)
- createNamespacedServiceAccountAsync(namespace, account, PRETTY_PRINT, DRY_RUN, FIELD_MANAGER, null, callback)
- listNamespacedPodCall(namespace, PRETTY_PRINT, ALLOW_WATCH_BOOKMARKS, null, null, podName, null, null, null, null,  Boolean.TRUE, callback)
- readNamespacedConfigMapAsync(name, namespace, PRETTY_PRINT,  callback)
- createNamespacedConfigMapAsync(namespace, binding, PRETTY_PRINT, DRY_RUN, FIELD_MANAGER, null, callback)
- createNamespacedSecretAsync(namespace, secret, PRETTY_PRINT, null, null, null, callback)
- readNamespacedSecretAsync(name, namespace, PRETTY_PRINT, callback)

In AbstractService.java
- Using V1Secret() in place of V1SecretBuilder().
- Using V1ConfigMap() in place of V1ConfigMapBuilder()

In K8sSequentialExecutor.java
- Using V1Pod() in place of V1PodBuilder().
- Using V1ServiceAccount() in place of V1ServiceAccountBuilder()
- Using V1ClusterRoleBinding in place of V1beta1ClusterRoleBinding

**How to verify the change**
Logs are collected and system tests passing.

### CODE REVIEW

**Review by RaulGracia — COMMENTED** [review]
Looks good, just a couple of quesitons.

**Comment by RaulGracia** [comment]
@a6dulaleem @anishakj system tests are not working with this change, apparently they have problems deploying Controller pods:
```
15:17:56      2022-05-16 13:17:50,828 12579126 [OkHttp https://namora.k8s-api.lagunitas.sdp.hop.lab.emc.com:8443/...] INFO  i.p.t.s.f.kubernetes.K8sClient - 1 pod(s) found with label component=pravega-controller.
15:17:56      2022-05-16 13:17:50,829 12579127 [OkHttp https://namora.k8s-api.lagunitas.sdp.hop.lab.emc.com:8443/...] INFO  i.p.t.s.f.kubernetes.K8sClient - Expected running pod count of pravega-controller:3, actual running pod count of pravega-controller:1.
```
The system tests job gets stuck like this. Please, have a look.

**Comment by RaulGracia** [comment]
@a6dulaleem what is the status of this PR? Have we validated that the changes work consistently?
Also, please sing-off your commits, as the DCO plugin is failing: https://github.com/pravega/pravega/wiki/Contributing#signing-your-commits

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 1]
```diff
@@ -308,7 +308,7 @@ public CompletableFuture<Object> createCustomObject(String customResourceGroup,
                                                         String plural, Map<String, Object> request) {
         CustomObjectsApi api = new CustomObjectsApi();
         K8AsyncCallback<Object> callback = new K8AsyncCallback<>("createCustomObject-" + customResourceGroup);
-        api.createNamespacedCustomObjectAsync(customResourceGroup, version, namespace, plural, request, PRETTY_PRINT, callback);
+        api.createNamespacedCustomObjectAsync(customResourceGroup, version, namespace, plural, request, PRETTY_PRINT, null,  null, callback);
```
[the remark this answers is not in the document]
Comment (a6dulaleem) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java:311]: As I can see the Implementation of `createNamespacedCustomObjectAsync` is like that if we are passing null as arguments its assigning the default for the params.

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 2]
```diff
@@ -193,13 +193,13 @@ public CompletableFuture<V1PodStatus> getStatusOfPod(final String namespace, fin
         CoreV1Api api = new CoreV1Api();
         K8AsyncCallback<V1PodList> callback = new K8AsyncCallback<>("listPods");
         api.listNamespacedPodAsync(namespace, PRETTY_PRINT, ALLOW_WATCH_BOOKMARKS, null, null, "POD_NAME=" + podName, null,
-                                   null, null, false, callback);
+                null, null, DEFAULT_TIMEOUT_MINUTES * 60, false, callback);
```
[the remark this answers is not in the document]
Comment (a6dulaleem) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: This is the timeout for watch/list the pods. Now we are making it default as we were not returning back from the watching state and the dependent test was failing because the test timeout was happening before watch return. the related test is `ReadTxnWriteScaleWithFailoverTest` and the exception looks like this 
```Watch did not return terminated state for pod readtxnwritescalewithfailovertest-zopwe```

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java [hunk 3]
```diff
@@ -126,33 +127,26 @@ private void verifyPravegaPodRestart(Map<String, V1ContainerStatus> podStatusBef
...
         if (Utils.TLS_AND_AUTH_ENABLED) {
-            pod  = new V1PodBuilder(pod).editSpec().withVolumes(new V1VolumeBuilder().withName("tls-certs")
-                                                  .withSecret(new V1SecretVolumeSourceBuilder().withSecretName(Utils.TLS_SECRET_NAME).build())
-                                                  .build())
-                .editContainer(0)
-                .withVolumeMounts(new V1VolumeMountBuilder().withMountPath(Utils.TLS_MOUNT_PATH).withName("tls-secret").build())
-                .endContainer()
-                .endSpec()
-                .build();
+            pod.getSpec().getVolumes().add(new V1Volume().name("tls-cert").secret(new V1SecretVolumeSource().defaultMode(420).secretName(Utils.TLS_SECRET_NAME)));
```
Comment (abhinb) [inline test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java:148]: is defaultMode a must now? (dont see it before)

**Comment by shshashwat** [comment]
@a6dulaleem, there are a few things which are required on this PR:-

- there are several changes related to indentation which are not required, please see if you can revert them
- The PR description needs to be updated in detail for all of the API you have changed
- If possible provide the ref link also which was used to change the API
These things will help reviewer to understand the need of the changes and will save overall time in review/commit/comment cycles

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java (hunk 3 above)
Comment (RaulGracia) [reply test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java:148]: Also, what does `420` mean? Would it be better to define a constant with that value with a name/comments that explains what it is?

**Review by RaulGracia — APPROVED** [review]
LGTM, assuming that system tests have collected properly the logs with this change.

**Comment by RaulGracia** [comment]
@abhinb @anishakj @shshashwat please, let's wrap up this PR so we can create the 0.12 branch with green system tests.

**Review by anishakj — APPROVED** [review]
LGTM

**Review by abhinb — APPROVED** [review]

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java (hunk 3 above)
Comment (a6dulaleem) [reply test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java]: Tried without the defaultMode. its optional the build is green even without that.

**Review by shshashwat — APPROVED** [review]
LGTM

**Comment by shshashwat** [comment]
@a6dulaleem , please share the system test build no before merge
