### PR TITLE
Issue 1931: moved "-fail" suffix out of container id and move into preceding measurement

### LINKED ISSUE #1931: Metric Naming Problems
**Problem description**
We have a set of filters to break up the stats coming from pravega and create tags for them.  There are new metrics in Pravega that no longer match those filters.  Here are our current telegraf filters:

```
    "*.*.*.pravega.*.* ....source.measurement pravega=1",
    "*.*.*.pravega.*.*.* ....source.measurement.field pravega=1",
    "*.*.*.pravega.*.*.*.*.* ....source.measurement.scope.stream.field pravega=1",
    "*.*.*.pravega.*.*.*.*.*.* ....source.measurement.scope.stream.segment.field pravega=1",
```

We can add a new filter to catch the case where there are 4 items after pravega:

```
    "*.*.*.pravega.*.* ....source.measurement pravega=1",
    "*.*.*.pravega.*.*.* ....source.measurement.field pravega=1",
    "*.*.*.pravega.*.*.*.* ....source.measurement.container.field pravega=1",
    "*.*.*.pravega.*.*.*.*.* ....source.measurement.scope.stream.field pravega=1",
    "*.*.*.pravega.*.*.*.*.*.* ....source.measurement.scope.stream.segment.field pravega=1",
```

Even with this change, we'll have a couple of problems:

1.  These items do not have a source:

```
active_segments
bookkeeper_leger_count
```

2.  There are some container ids that have the format of:

```
0-fail
1-fail
2-fail
```

**Problem location**

Metrics

**Suggestions for an improvement**

Add a source for the active_segments and bookkeeper_leger_count and move the "-fail" suffix to the measurement name and not the container id.

### PR DESCRIPTION
**Pull request by kevinhan88**
…receding measurement as "_fail"; also added source for active_segments

Signed-off-by: kevinhan88 <kevinhan88@gmail.com>

**Change log description**  
moved "-fail" suffix out of container id and move into preceding measurement as "_fail"; also added source for active_segments.

**Purpose of the change**  
Fixes #1931 

**What the code does**  
When fail metric is being created, instead of simply append "-fail" onto the metric name, the code checks if the last segment of metric is an integer (such as container id); if it is, then "_fail" is appended to the preceding measurement instead of the integer itself - this is to easy the filtering of metrics.

**How to verify it**  
Metrics such as "pravega.segmentstore.segmentstore.container.operation.latency_ms.1-fail" now becomes "pravega.segmentstore.segmentstore.container.operation.latency_ms_fail.1"

"segmentstore.active_segments" changes to "segmentstore.container.active_segments"

### CODE REVIEW

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 1]
```diff
@@ -194,4 +202,17 @@ public static String nameFromContainer(String metric, int containerId) {
     public static String globalMetricName(String stringName) {
         return stringName + "_global";
     }
+
+    public static String failMetricName(String metricName) {
```
Comment (andreipaduroiu) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Please add an explanation in the form of a Javadoc for this method. It's hard to tell what it wants to achieve.

Comment (kevinhan88) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Added (was trying to be consist with the rest of the code, and ./gradlew check didn't report missing description)

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 2]
```diff
@@ -194,4 +202,24 @@ public static String nameFromContainer(String metric, int containerId) {
     public static String globalMetricName(String stringName) {
         return stringName + "_global";
     }
+
+    /**
+     * For some metrics such as OpStats, Pravega generates corresponding fail metrics automatically.
+     * This method provides a standard way to create name of fail metric for a given metric
```
Comment (RaulGracia) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Missing last dot.

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 3]
```diff
@@ -194,4 +202,24 @@ public static String nameFromContainer(String metric, int containerId) {
...
+     *
+     * @param metricName - the metric name for which fail metric is created
```
Comment (RaulGracia) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Normally, between the param name and the description there is a space or a series of spaces to align the descriptions (but no hyphens).

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 4]
```diff
@@ -48,6 +49,13 @@
  */
 
 
+import com.google.common.base.Strings;
+import com.google.common.primitives.Ints;
+
+import java.util.Arrays;
```
Comment (RaulGracia) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: This may be unused.

File: shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerImpl.java [hunk 5]
```diff
@@ -13,11 +13,13 @@
 import com.codahale.metrics.Snapshot;
 import com.codahale.metrics.Timer;
 import com.google.common.base.Preconditions;
+import com.google.common.primitives.Ints;
```
Comment (RaulGracia) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/OpStatsLoggerImpl.java]: This seems unused, too.

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 6]
```diff
@@ -194,4 +202,24 @@ public static String nameFromContainer(String metric, int containerId) {
...
+    public static String failMetricName(String metricName) {
+        if (Strings.isNullOrEmpty(metricName)) {
+            return metricName;
+        }
+        String[] tags = metricName.split("\\.");
+        if (tags.length >= 2 && Ints.tryParse(tags[tags.length - 1]) != null) {
+            tags[tags.length - 2] += "_fail";
+            return String.join(".", tags);
+        } else {
+            return metricName + "_fail";
```
Comment (RaulGracia) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Are there cases that fall in this case?

Comment (kevinhan88) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: they are different cases: with / without the last segment as integer (such as container id)

Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: @RaulGracia It might be a good idea to add some unit test for this class. It's doing non-trivial things so it might be good to have those covered. Would you mind creating an issue for that?

Comment (kevinhan88) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Unit tests created already.

Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Ok, I didn't see that. Thanks for pointing out.

**Comment by RaulGracia** [comment]
@kevinhan88 before approving the PR, have you tried to run the controller and segment store locally, execute some operations (e.g., `ConsoleWriter` sample) and check that the `csv` files of metrics created in `/tmp/csv/pravega` have the correct name according to this change?

**Comment by kevinhan88** [comment]
@RaulGracia yes I made some tweak in standalone mode to have metrics generated locally, and checked the changes worked as expected.
