### PR TITLE
Issue 2528: Prevent stalling writer if segment is sealed while handling a segment sealed.

### LINKED ISSUE #2470: Events out of sequence when scaling
**Problem description**
We have one writer writing to several routing keys and one reader reading from the stream.  The writer is writing sequence numbers for each routing key and the reader is making sure that the sequence number is always increasing.

We sometimes see an event be read from the stream out of sequence. This happens ONLY when there is scaling (fixed segment streams don't show this) and in rare instances (11 events out of 2,532,332)

**Problem location**

**Suggestions for an improvement**

Events should be written in the same order that the client wrote them to the stream

### LINKED ISSUE #2528: Read/writes cease after a scaling event on the stream
**Problem description**
When trying to write and read from a stream with the scaling triggered by event rate, we are observing all the reads and writes cease after the initial segment has experienced two to four scaling rounds (right after a major scaling round). We have multiple writers and readers on the stream, and all of them report as healthy. However, no writes happen anymore (the readers are tail readers, so there is nothing to read for them).
There are no visible major errors in pravega logs around the time of the failure.
After the failure, the stream would scale down to one segment, in accordance with no writes happening to it.

We are using this [commit](https://github.com/pravega/pravega/commit/10f7a4559aea762232c01e831071f4723d68a91a) of Pravega.

stopped_writes

**Problem location**
Client?

**Suggestions for an improvement**
The writers should not stop writing to a stream.

### LINKED ISSUE #2575: EventStreamWriterTest.testSegmentSealedInSegmentSealed() does not properly cover the code it was designed to
**Problem description**
The test is meant to cover the case where a segment seal is encountered while resending events that were outstanding against a segment that was sealed. IE: Scaling happened so quickly that the new segments that were created have already been scaled themselves before the writer was able to write to them.
However the test is not actually covering this case because mock of the SegmentOutputStream that is used in the test does not work like the real version, and it's call to flush() does not block or throw SegmentSealedException if the new segment is already sealed.

**Problem location**
EventStreamWriterTest.testSegmentSealedInSegmentSealed() 

**Suggestions for an improvement**
Have the mock behave more like the real implementation.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
* EventStreamWriterImpl: Instead of blocking on all flush calls to complete during a segment seal, call flush once on each segment.

* SegmentOutputStreamImpl: Throw SegmentSealedException inside of flush() if a seal has been encountered.

**Purpose of the change**
In the recent changes to EventStreamWriterImpl (#2528), there was a regression handling the case where a segment seal is encountered while processing the segment seal: scaling has occurred so quickly that while taking the unflushed data from the sealed segment and writing it to the new segment that new segment is itself sealed. 

The bug was caused by a latent issue #2574 which was known but thought harmless interacting with the changes to fix #2528.

This regression was not immediately caught because while there was a unit test designed to cover exactly this case, and verify its correctness, that unit test relied on a mock of a class whose behavior differed from the actual implementation (See #2575) in such a way that the bug did not affect the test but occur in production.

So when a seal occurred and the data was being written to the new segment the events would be put into the in-flight data structure in SegmentOutputStreamImpl. Then in an effort to fix #2470 a call to flush was added in #2471. This meant the call would block on the segment being sealed. This was still not a problem in theory even if the new segment was sealed, because while #2574 would cause that thread to stall a new thread could enter and finish the flush(). However the lock fairness prevented this from working correctly (see #2528). This was in turn fixed by introducing a queue, which meant that the segmentSeal for the newly created segment that the data was just written to would get queued up and processed after the first one was completed. However combined with #2574 this was a problem because it meant that the thread would never complete the first flush call to pull the seal from the queue, which blocked the seal thread, which also held the lock for writes. #2575 prevented this from being spotted pre-commit.

**What the code does**
This code fixes #2528 (the stalling), #2574 (the latent bug) and fixes #2575 (the mock). 
It does this by making SegmentOutputStream.flush() throw if a seal has been encountered. (This is OK because it is already handled in EventOutputStreamImpl). Then in EventOutputStreamImpl the retry on seal loop is moved our of flushInternal() and into flush(). This means that flush is only called once for each segment without blocking on sealed ones when processing a segmentSeal. If the segments are sealed they will run their own callbacks and will endup re-writing the data to the correct segment at that time.

**How to verify it**
The original test should cover this path. It has been checked in a debugger to make sure it is behaving the same as the actual implementation.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -305,7 +308,7 @@ public void wrongHost(WrongHost wrongHost) {
         @Override
         public void segmentIsSealed(SegmentIsSealed segmentIsSealed) {
             log.info("Received SegmentSealed {} on writer {}", segmentIsSealed, writerId);
-            if (state.sealEncountered.compareAndSet(false, true)) {
+            if (state.encounteredSeal()) {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: On receiving a Segment Sealed `EventStreamWriterImpl#handleLogSealed` is invoked. The `SegmentoutputStream` executes it on  `connectionFactory.getInternalExecutor()` with `Retry.indefinitelyWithExpBackoff` .

`handleLogSealed` internally executes it on `retransmitPool` with `Retry.indefinitelyWithExpBackoff`. This causes the thread of `connectionFactory.getInternalExecutor()` which is a limited resource to be blocked until `handleLogSealed` is completed.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 2]
```diff
@@ -332,24 +332,26 @@ private void throwIfClosed() throws TxnFailedException {
...
+    private boolean flushInternal() {
+        boolean success = true;
+        for (SegmentOutputStream writer : selector.getWriters()) {
+            try {
+                writer.flush();
+            } catch (SegmentSealedException e) {
+                // Segment sealed exception observed during a flush. Re-run flush on all the
+                // available writers.
+                success = false;
+                log.warn("Flush failed due to {}, it will be retried.", e.getMessage());
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: we could log the `writerId` here, to simplify debugging.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 3]
```diff
@@ -332,24 +332,26 @@ private void throwIfClosed() throws TxnFailedException {
...
-            success = true;
-            for (SegmentOutputStream writer : selector.getWriters()) {
-                try {
-                    writer.flush();
-                } catch (SegmentSealedException e) {
-                    // Segment sealed exception observed during a flush. Re-run flush on all the available writers.
-                    success = false;
-                    log.warn("Flush failed due to {}, it will be retried.", e.getMessage());
-                }
+    private boolean flushInternal() {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: `Observation`: In the older code state.waitForInflight implied inflight events are empty. Now it is not the case. 

Details:
```
T-nx --> Netty thread.
T-cfx --> Connection factory thread.
T-rx --> RetransmitPool thread.
Q --> Query
```
If we assume a there are two segments `S0` and `S1` and S1 sealed callback is received.
```
`T-n1` ---> processes SegmentSealedCallback --> S1.state.sealEncountered= true -->`T-cf1` --> 
invokes handleLogSealed() --> add to segmentSealedQueue --> `T-r1` --> 
resend(inflight events of S1) --> invoke flush internal --> invoke S0.flush() --> this has inflight 
--> waits until inflight empty.
```
Now, if S0 also encounters segment sealed.
`T-n2` --> SegmentSealedCallback --> S0.state.sealEncountered=true --> S0.state.waitingInflight.released()->
 (This would cause the S0.flush() (`T-r1`) to complete without actually re transmitting the inflight events (it throws SegSealedException))
--> `T-cf2` -- invoke handleLogSealed() 
(`Q`: This thread T-cf2 could be starved and cause the resend of inflight to be delayed, right? )

(is the below scenario even valid?)
Also, if a reconnect() invoked during this interval it would cause the `state.isAlreadySealed()` to return true causing future writes to receive IllegalStateException right?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 1 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: >handleLogSealed internally executes it on retransmitPool with Retry.indefinitelyWithExpBackoff

yes. it is on retransmitPool, and the thread in connectionFactory.getInternalExecutor() is never blocked.

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: ok, got it..
