### PR TITLE
Issue 1702: (SegmentStore) Acking earlier to the producer

### LINKED ISSUE #1702: Ack appends before adding to ReadIndex
**Problem description**
High-level view of how appends are processed in the Segmentstore:
1. Append is received
2. Append is batched with others and sent async to Tier1
3. Tier1 ack comes back
4. Metadata for all appends in batch gets committed to the main metadata
5. All appends in batch get added to ReadIndex (and thus to Rocks) and then to in-memory log.
6. All appends in batch are acked back to the caller.

In some cases it may take up to 1ms for step 5 above to complete. In addition, it is also done under a lock that is used extensively throughout the `OperationProcessor`, and both the ReadIndex-add and the MemLog-add have their own set of locks.

**Problem location**
`OperationProcessor` and `MemoryStateUpdater`.

**Suggestions for an improvement**
Swap steps 5 and 6 (see **Problem Description** above). Complete the Operation future before we add to the read index (but always after persisting to Tier1). This still acks to the caller after durably persisting to Tier1, thus we are in no danger of breaking the exactly-once guarantee. Plus it will be done outside of the `OperationProcessor` lock.

However, there is a concern about swapping 5 and 6. It is possible, in some rare cases, that the caller will want to read the data once they got an ack. But I do not believe that it will be an issue:
1. It will take a lot longer than 1ms for a signal to go back to the caller, the caller figuring it out, then the caller issuing some random read, and that read reaching the same SegmentStore instance.
2. Due to our API limitations, the caller cannot issue random reads anyway until they do a tail read. The tail read will not be triggered until the operations are added to the ReadIndex, so no worries there.

### LINKED ISSUE #2227: Sporadic build failure: ExtendedS3IntegrationTest.testEndToEnd
**Problem description**
We got this test case failing in an internal build and the stack trace is this one:

```
java.util.concurrent.CancellationException: OperationProcessor is shutting down.
	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:125)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:170)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.common.concurrent.Services.stopAsync(Services.java:61)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:183)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:165)
	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:242)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.lambda$shutdownWhenStopped$19(StreamSegmentContainer.java:471)
	at io.pravega.common.concurrent.Services$ShutdownListener.failed(Services.java:119)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:531)
	at com.google.common.util.concurrent.AbstractService$5.call(AbstractService.java:528)
	at com.google.common.util.concurrent.ListenerCallQueue.run(ListenerCallQueue.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
Segment store, extended S3 binding, test failure.

**Suggestions for an improvement**
Track the bug.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
This change seeks to improve write latency for a case when we have lots of smaller operations that are batched together in larger Tier 1 writes. Check out the[ parent issue comment](https://github.com/pravega/pravega/issues/1702#issuecomment-367476456) about benchmarks for comparison.

The (current) process for accepting an operation in the SegmentStore is:
1. Append is received and batched with others and sent async to Tier1
2. Tier1 ack comes back
3. Metadata for all appends in batch gets committed to the main metadata
4. All appends in batch get added to ReadIndex (and thus to Rocks) and then to in-memory log.
5. All appends in batch are acked back to the caller.

This is made worse by the fact that steps 3-4 are done while holding a lock, so if other Tier1 acks come back in the meantime they will be queued up, creating even more latency for those operations involved.

This change moves step (5) earlier in the process, after step (3) and  in parallel with (4), so the new order is:
1. Append is received and batched with others and sent async to Tier1
2. Tier1 ack comes back.
3. Metadata for all appends in batch gets committed to the main metadata
4. Parallel:
    - All appends in batch are acked back to the caller asynchronously.
    - All appends in batch get added to ReadIndex (and thus to Rocks) and then to in-memory log (async).

The lock is only held for a brief moment to execute step 3 and initiate step 4, so we will no longer be compounding latencies should further Tier1 acks come in.

Notes:
- This will not break any of our guarantees. We are still ack-ing after we have durably stored the data in Tier1, so even a crash immediately after sending an ack will not cause the data to get lost.
    - This will not break the guarantee of the data not being available for reads as soon as the ack is sent. This is because the only way to read new data currently is via a tail read, which will be activated just as it was before. Given our current API, it is not possible to issue a read at an arbitrary offset without having processed the data via a tail read prior to that.
- It is possible that if an operation causes a `DataCorruptionException` upon adding to the ReadIndex (this can only happen if we have a bug in our code), the operation will be ack-ed successfully, but the `SegmentContainer` will shut down immediately. However this would have happened even before, the only difference being that the operation wouldn't have been acknowledged before (but the corruption is still there).

**Purpose of the change**
Fixes #1702.
May fix #2227.

**What the code does**
- All in-flight operations in the `OperationProcessor` are now associated with their corresponding `DataFrame`. Upon a `DataFrame` being committed or failed, the appropriate operations are being completed or failed.
    - Previously, they were in a separate list, and we'd have to pick them from there when a frame was committed. This was a rather expensive search, which also involved a couple of list copies being made.
- The `OperationProcessor` has a sub-processor (Memory Commit Processor) which asynchronously handles memory commit operations in the correct order. 
- The `OperationProcessor` acks the operations immediately as it receives the ack for their `DataFrames` from Tier1, without waiting for their memory commit events to finish.
- May have fixed a possible bug that was leading to sporadic build failures when a Segment Delete request would coincide with the `OperationProcessor`'s memory update for that segment. This is impossible to explicitly reproduce, but issue #2227 may have been caused by this.
- A bunch of code has been removed from `OperationProcessor.QueueProcessingState` that looks like it was serving a good purpose, but it actually was never exercised. The modified code has the same effect as before, as verified by the unit tests.

**How to verify it**
Existing unit tests verify this code path extensively with respect to ordering guarantees and behaviors during failure. Issue #1702 shows the measured performance impact to using this approach, especially for small appends.

### CODE REVIEW

**Comment by andreipaduroiu** [comment]
@tkaitchuck That is a good point. I realized I had a problem with the description in the PR (I fixed it now).

The order of events is
> 3. Metadata for all appends in batch gets committed to the main metadata
> 4. All appends in batch are acked back to the caller.

Since the metadata is updated prior to the acks being sent, a call to GetInfo will pick data from the metadata and will return the newly updated segment size & attributes. 

The tail reads will be activated whenever the read index is updated, which hasn't changed from how it was before.

File: common/src/main/java/io/pravega/common/util/BlockingDrainingQueue.java [hunk 1]
```diff
@@ -74,7 +85,23 @@ public BlockingDrainingQueue() {
             pending.cancel(true);
         }
 
-        return result != null ? result : Collections.emptyList();
+        return result != null ? result : new LinkedList<>();
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/util/BlockingDrainingQueue.java]: Collections.emptyList()

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 2]
```diff
@@ -437,7 +484,9 @@ int getPendingCount() {
          */
         void frameSealed(DataFrameBuilder.CommitArgs commitArgs) {
             synchronized (stateLock) {
-                commitArgs.setIndexKey(OperationProcessor.this.metadataUpdater.sealTransaction());
+                commitArgs.setMetadataTransactionId(OperationProcessor.this.metadataUpdater.sealTransaction());
+                commitArgs.setOperations(Collections.unmodifiableList(this.nextFrameOperations));
+                this.nextFrameOperations = new ArrayList<>(MAX_READ_AT_ONCE);
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: This is allocating an array of 1000 every time. This seems excessive. If we can either use a single array without re-allocating or here and in the constructor not pass a size recommendation, it will lower the memory allocated here.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 3]
```diff
@@ -586,47 +605,33 @@ void failOperation(CompletableOperation operation, Throwable failureCause) {
...
          * are not failed (since this method executes while holding the lock).
          *
-         * @param ex         The Exception that triggered the failure.
          * @param commitArgs The CommitArgs that points to the DataFrame which failed to commit.
-         * @param target     A Map where the failure candidates will be collected. Key=Operation, Value=Failure Exception.
+         * @param candidates A Collection where the failure candidates will be collected.
          */
         @GuardedBy("stateLock")
-        private void collectFailureCandidates(Throwable ex, DataFrameBuilder.CommitArgs commitArgs, Map<CompletableOperation, Throwable> target) {
+        private void collectFailureCandidates(DataFrameBuilder.CommitArgs commitArgs, Collection<CompletableOperation> candidates) {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: Looking at this and the caller I think this would be cleaner if this method returned a collection rather than taking the 'candidates' arg to populate.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 4]
```diff
@@ -480,62 +528,31 @@ void commit(DataFrameBuilder.CommitArgs commitArgs) {
                         return;
                     }
 
-                    // Commit any changes to the metadata.
+                    // Collect operations to commit.
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: I think a private method would help here.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java [hunk 5]
```diff
@@ -114,7 +115,12 @@ public UpdateableSegmentMetadata getStreamSegmentMetadata(long streamSegmentId)
 
         @Override
         public InputStream getAppendData(long streamSegmentId, long startOffset, int length) {
-            return this.readIndex.readDirect(streamSegmentId, startOffset, length);
+            try {
+                return this.readIndex.readDirect(streamSegmentId, startOffset, length);
+            } catch (StreamSegmentNotExistsException ex) {
+                // Null is interpreted as "Segment not exists" by the SegmentAggregator.
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java]: Looking at the callers and the other methods on this interface: It might be better to change the signature so that it throws this exception. SegmentAggrigator responds by failing a future or throwing a new exception in the event of null, so it might as well be able to preserve the full stack trace.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java [hunk 6]
```diff
@@ -1539,6 +1542,31 @@ private void activateAllSegments(Collection<String> segmentNames, TestContext co
...
 
+    /**
+     * Blocks until all operations processed so far have been added to the ReadIndex and InMemoryOperationLog.
+     * This is needed to simplify test verification due to the fact that the the OperationProcessor commits operations to
+     * the ReadIndex and InMemoryOperationLog asynchronously, after those operations were ack-ed. This method makes use
+     * of the fact that the OperationProcessor/MemoryStateUpdater will still commit such operations in sequence; it
+     * creates a new segment, writes 1 byte to it and issues a read (actual/future) and waits until it's completed - when
+     * it is, it is guaranteed that everything prior to that has been committed.
+     */
+    @SneakyThrows
```
Comment (tkaitchuck) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java]: Can we narrow this? It looks like the get() at the end should be: using handleInterrupted. So it might be neater to package this as Futures.getAndHandleExceptions()

File: common/src/main/java/io/pravega/common/util/BlockingDrainingQueue.java (hunk 1 above)
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/util/BlockingDrainingQueue.java]: This returns a `Queue`. `List` does not implement `Queue`.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: If we use a single array then we need to make a copy somewhere. I prefer not to.

I removed the default size.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: Good suggestion.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 4 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: Done

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java (hunk 5 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java]: Yes, I did consider that, but inside the Read Index I do a check for the segment's existence first, and then I look up that in that index for the data. If the segment gets deleted exactly after the check but before retrieving the data, we'll be in trouble. Handling that kind of a race properly is more complicated than aggregating this into one.

Plus, the stack trace of `StreamSegmentNotExistsException` is not terribly useful - it itself indicates the segment doesn't exist; where it originates from does not really help much.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java (hunk 6 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java]: There are 3 Exceptions being thrown in this class. Since this is a unit test, I just have the method declare `throws Exception` and let it bubble up.
