### PR TITLE
Issue #2528: Prevent deadlock in EventStreamWriterImpl

### LINKED ISSUE #2528: Read/writes cease after a scaling event on the stream
**Problem description**
When trying to write and read from a stream with the scaling triggered by event rate, we are observing all the reads and writes cease after the initial segment has experienced two to four scaling rounds (right after a major scaling round). We have multiple writers and readers on the stream, and all of them report as healthy. However, no writes happen anymore (the readers are tail readers, so there is nothing to read for them).
There are no visible major errors in pravega logs around the time of the failure.
After the failure, the stream would scale down to one segment, in accordance with no writes happening to it.

We are using this [commit](https://github.com/pravega/pravega/commit/10f7a4559aea762232c01e831071f4723d68a91a) of Pravega.

stopped_writes

**Problem location**
Client?

**Suggestions for an improvement**
The writers should not stop writing to a stream.

### LINKED ISSUE #2545: RetryWithBackoff#retryWhen should return RetryAndThrowConditionally instead of RetryConditionally
**Problem description**
`RetryWithBackOff#retryWhen `returns `RetryConditionally`.This forces the user to invoke `io.pravega.common.util.Retry.RetryConditionally#throwingOn` with RunTimeException, which is essentially redundant.

**Problem location**
io.pravega.common.util.Retry

**Suggestions for an improvement**
retryWhen could return `RetryAndThrowConditionally` with throw type as RuntimeException.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
Simplify locking scheme in EventStreamWriterImpl

**Purpose of the change**
In PR #2471 a bug was introduced. The PR switched from using a ReadWriteLock to use a ReadWriteLock from a StampedLock because the lock was being acquired and released in multiple threads. This introduced an unintended side effect.

The readWriteLock was acquired by the handler for segment seals in read mode with the intention that this would block calls to write, where it is held in write mode. It was not intended to block other calls to segmentSealed or flush where it was also held in read mode. This seemed straightforward, and the code depended on this assumption: *that two calls to the segmentSealed callback could be entered in parallel, so that if one blocked while it was calling flush the other could proceed*. 

As the only lock that was held at that time was a read lock it seemed like a safe assumption. This was not actually the case. The reason is that ReadWriteLock and the ReadWriteLock version of a StampedLock have different semantics with respect to fairness of thread ordering. The original readWriteLock (with fairness set to false) allows additional readers through if the lock was held by a reader, even if a writer was waiting. The stampedLock version, however, blocks the second reader in order to allow the writer an opportunity to go through. 

This difference actually caused #2528. Here is a characterization of the observed scenario:

**Thread 1**

- Invokes the segment sealed callback for segment S1
- Grabs lock in read mode

**Thread 2**

- Client invokes `writeEvent`
- This thread blocks on acquiring the lock

**Thread 1**

- Resumes and calls flush
- Blocks on flush completing

**Thread 3**

- In response to the flush, another segment S2 is determined to be sealed, and this third thread blocks on acquiring the read lock because of the stamped lock behavior.
- All three threads are deadlocked.

**What the code does**
This fixes #2528. It does this by replacing the readWriteLock and threading scheme with a simpler queuing scheme. When a segment is sealed it is added to a queue of sealed segments to process, and a task is added to a background thread to process the seal. The locks are then simplified by splitting it into to two locks one to prevent writes and seals from going in parallel, and a separate on to prevent writes and flushes from going in parallel. This means that there is no way for the system to deadlock, the call to flush won't block other calls to seal, and flushes and seals can proceed in parallel.

This also incidentally fixes #2545, which interfered with the change.

**How to verify it**
A new test is added that with the previous code would fail.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 1]
```diff
@@ -158,41 +148,38 @@ private void handleMissingLog() {
...
+                      * entries that will succeed in being written to a new segment are written and any
+                      * segmentSealedCallbacks that will be called happen before the next write is invoked.
                       */
-                     flushInternal();
-                 }, retransmitPool);
-             }, backgroundThreadPool).handle((r, t) -> {
-                 writeFlushLock.readLock().unlock();
-                 return null;
-             });
+                     synchronized (writeSealLock) {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: My current understanding :
1. `handleLogSealed` is invoked on the netty callback thread. Hence multiple segmentsealed callbacks are mutually exclusive.
2. if there are multiple segment sealed (in event of scaledown) then multiple netty threads are blocked on `writeSealLock`. The single thread which has the lock will handle all the segment sealed requests and for each segment sealed it will flush all segments. (Note: Flush and close can be invoked concurrently here).
3. Now `SegmentOutputStream.flush()` will be blocked until that SegmentOutputstream's inflight is empty. and if this flush encounters segment sealed then the new thread would update the `sealedSegmentQueue` and wait as described in (2).

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: > handleLogSealed is invoked on the netty callback thread. Hence multiple segmentsealed callbacks are mutually exclusive.

It is invoked by netty callback threads, but there is more than one such netty thread so they are not mutually exclusive. 

> Can we avoid blocking the netty threads? Earlier this operation happened on backgroundThreadPool.

It won't block them, it still does occur in a background pool. See line 152.

> if there are multiple segment sealed (in event of scaledown) then multiple netty threads are blocked on writeSealLock. The single thread which has the lock will handle all the segment sealed requests and for each segment sealed it will flush all segments. 

Yes. This is why I switched it to a background thread and a queue. That way the one thread can do them in a loop rather than having multiple threads block.

> Now SegmentOutputStream.flush() will be blocked until that SegmentOutputstream's inflight is empty. and if this flush encounters segment sealed then the new thread would update the sealedSegmentQueue and wait as described in (2)

Correct.

File: client/src/main/java/io/pravega/client/stream/MonotonicStreamClient.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
+/**
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/MonotonicStreamClient.java]: This change is not part of the fix.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 3]
```diff
@@ -118,22 +109,21 @@
...
         ByteBuffer data = serializer.serialize(event);
         CompletableFuture<Void> ackFuture = new CompletableFuture<Void>();
-        writeFlushLock.writeLock().lock();
-        try {
-            SegmentOutputStream segmentWriter = selector.getSegmentOutputStreamForKey(routingKey);
-            while (segmentWriter == null) {
-                log.info("Don't have a writer for segment: {}", selector.getSegmentForEvent(routingKey));
-                handleMissingLog();
-                segmentWriter = selector.getSegmentOutputStreamForKey(routingKey);
+        synchronized (writeFlushLock) {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Why do we synchronize in lines 112 and 113, and not right before line 120? That would reduce the scope of the locks, but I'm not sure there is a concurrency concern with respect to getting the segment writer.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: All those classes are threadsafe, so yes, there is no concurrency concern. The reason for the locks is to ensure that:
a) The segments don't change while the write is occurring. (This could result in a 'late write' to a sealed segment, resulting in an effectively lost event)
b) ensuring that two write calls have a defined order.
The reason writeSealLock needs to be held starting on 113 is to insure (a). The reason the writeFlushLock is held on 112 and not just inside on 120 is because it needs to be the outer lock with the flush lock being the inner one.
