### PR TITLE
Issue 2460: When sending no credentials, exception returned has UNKNOWN status

### LINKED ISSUE #2460: GRPC client: when sending no credentials, exception returned has UNKNOWN status
**Problem description**

In environments where controller/segment store auth is turned on, GRPC get an UNKNOWN StatusRunTimeException if they don't send any credentials.

WARN  [2018-04-11 19:43:23,865] io.pravega.client.stream.impl.ControllerImpl: createStream failed: 
! io.grpc.StatusRuntimeException: UNKNOWN
! at io.grpc.Status.asRuntimeException(Status.java:526)
! ... 15 common frames omitted
! Causing: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNKNOWN
! at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
! at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
! at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source)
! at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)

If they send, bad credentials, then the exception correctly states UNAUTHENTICATED.

**Problem location**

GRPC client only.  (REST code path behaves correctly).

**Suggestions for an improvement**

Both lack of credentials and bad credentials should return UNAUTHENTICATED

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
In case of grpc based authentication, when an auth handler is not specified, the grpc handler code loops through all the handlers and then fails with `UNKNOWN` status. In case of no headers present, the handlers should throw exception.

**Purpose of the change**
This fixes #2460.

**What the code does**

Throw exception when authentication method is not selected.
**How to verify it**
In case the method is not specified, authentication error is observed.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 1]
```diff
@@ -69,6 +70,8 @@
                 context = context.withValue(AUTH_CONTEXT_PARAMS, paramMap);
                 context = context.withValue(INTERCEPTOR_OBJECT, this);
             }
+        } else {
+            throw new RuntimeException(new AuthenticationException("Handler not specified"));
```
Comment (EronWright) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: This scenario seems like a user error, i.e. it is expected.   Does throwing `RuntimeException` here produce a stack trace in the server log, and if so can that be avoided?   Seems a better fix would be:
```
} else {
    call.close(Status.fromCode(Status.Code.UNAUTHENTICATED), headers);
}
```

Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Fixed. Thanks.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 2]
```diff
@@ -69,6 +69,8 @@
                 context = context.withValue(AUTH_CONTEXT_PARAMS, paramMap);
                 context = context.withValue(INTERCEPTOR_OBJECT, this);
             }
+        } else {
+            call.close(Status.fromCode(Status.Code.UNAUTHENTICATED), headers);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: As I understand it, this line is setting the status code to `UNAUTHENTICATED`, but the description of the PR says:

```
Throw exception when authentication method is not selected.
```

It seems to be talking about the caller's code path and not the change in the PR. Please clarify and consider providing a more precise explanation.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 3]
```diff
@@ -69,6 +69,8 @@
...
         }
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Should we be returning `null` like in line 67?

Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Fixed.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 2 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Updated the PR comment.
