### PR TITLE
Issue 5726 : Fix TimeoutException in AuthEnabledInProcPravegaClusterTest

### LINKED ISSUE #5726: Sporadic test failure in AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig
**Problem description**
Found test `AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig` failing sporadically:
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base@11.0.3/java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:415)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.lambda$blockFor$0(EventStreamReaderImpl.java:192)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl$$Lambda$1643/0x000000010095e040.run(Unknown Source)
	at app//io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:115)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.blockFor(EventStreamReaderImpl.java:190)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEventInternal(EventStreamReaderImpl.java:147)
	at app//io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:125)
	at app//io.pravega.local.InProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig(InProcPravegaClusterTest.java:173)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
```
Full log can be found here: [log.txt](https://github.com/pravega/pravega/files/5967681/log.txt)

**Problem location**
`AuthEnabledInProcPravegaClusterTest.testWriteAndReadEventWithValidClientConfig`

**Suggestions for an improvement**
Fix the test.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Ensure standalone is not started for every test, this speeds up tests.
- Disable the REST server for the tests.

**Purpose of the change**  
Fixes #5726 

**What the code does**  
- Ensure standalone is not started for every test
  The older tests brought up Pravega standalone for every @Test method. This PR ensures standalone is brought up per test file.
- Disable REST server on the standalone.
- Speeds up the standalone tests due to this logic.

**How to verify it**  
The tests should pass reliably.

### CODE REVIEW

File: standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java [hunk 1]
```diff
@@ -30,34 +29,17 @@
...
-    String streamName() {
-        return "AuthTestStream";
-    }
-
-    @Override
-    String eventMessage() {
-        return "Test message on the plaintext channel with auth credentials";
-    }
+    @ClassRule
+    public static final PravegaEmulatorResource EMULATOR = new PravegaEmulatorResource(true, false);
```
Comment (andreipaduroiu) [inline standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: I'm curious how this thing works. I don't like it because it's static. How would this behave if we enabled parallel test runs (each class test suite may run in parallel with another)?

Comment (shrids) [reply standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: This is similar to the @BeforeClass annotation, hence it is a static.  Also, i verified that `--parallel` option in gradle does not execute test methods inside a single test file in parallel.

Comment (tkaitchuck) [reply standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: Confirmed. This is fine, provided it's shutdown method actually cleans everything up and frees all ports etc.

File: standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java [hunk 2]
```diff
@@ -118,69 +44,7 @@ ClientConfig prepareValidClientConfig() {
...
-    }
-
-
-    @After
-    public void tearDown() throws Exception {
-        if (localPravega != null) {
-            localPravega.close();
-        }
+    public void testWriteAndReadEventWithValidClientConfig() throws Exception {
+        EMULATOR.testWriteAndReadAnEventWithValidClientConfig("TestScope", "TestStream", msg, prepareValidClientConfig());
```
Comment (tkaitchuck) [inline standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java:48]: Why is this method being moved?

File: standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+    protected void before() throws Exception {
+        pravega.start();
+    }
+
+    @SneakyThrows
+    protected void after() {
+        pravega.close();
+    }
+
+    public void testWriteAndReadAnEventWithValidClientConfig(String scope, String streamName, String message, ClientConfig clientConfig) throws Exception {
```
Comment (tkaitchuck) [inline standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java:93]: It seems like this class could be used by more than one test. Putting this here undermines that.

File: standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java (hunk 1 above)
Comment (andreipaduroiu) [reply standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: Thanks for the clarification @shrids

Comment (shiveshr) [reply standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: can we try BeforeClass

Comment (shrids) [reply standalone/src/test/java/io/pravega/local/AuthEnabledInProcPravegaClusterTest.java:35]: The main benefit of junit rule is you have to write it once and use it as many times as you want. whereas setup() and tearDown() are the methods that have to be written for every TestClass on an ad-hoc basis.

File: standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java (hunk 2 above)
Comment (shrids) [reply standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java]: refactored the code to move the sanity test to a common class.

File: standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java (hunk 3 above)
Comment (shrids) [reply standalone/src/test/java/io/pravega/local/PravegaEmulatorResource.java]: Fixed it.

**Review by tkaitchuck — APPROVED** [review]

**Review by shiveshr — APPROVED** [review]
