### PR TITLE
Issue 1829: (SegmentStore) Ability to recover incomplete Segment Creations.

### LINKED ISSUE #1829: Corrupt statefile keeps the segment in permanent error state
**Problem description**
There can be some reason because of which statefile can be out of sync (Some possibilities can be where segmentstore fails in the middle of `create segment` either before creating a state file or during its creation).
This statefile is never cleaned up via `MetadataCleaner` because of this any future appends will always fail. e.g. `append` calls will always fail as described in the stack trace here:
```
017-08-31 00:34:26,355 2956751 [segment-store-4] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'testMultiReaderWriterTxnScope142044298/testMultiReaderWriterTxnStream/2#transaction.60e8bf69f8c44d18bedd46858ec38d0f', Operation = 'append')
java.io.EOFException: null
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at io.pravega.segmentstore.server.containers.SegmentState.deserialize(SegmentState.java:80)
        at io.pravega.segmentstore.server.containers.SegmentStateStore.deserialize(SegmentStateStore.java:139)
        at io.pravega.segmentstore.server.containers.SegmentStateStore.lambda$readSegmentState$7(SegmentStateStore.java:122)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Problem location**
`SegmentStateStore:readSegmentState`

**Suggestions for an improvement**
`SegmentStateStore:readSegmentState` should take care of the case where statefile exists but is corrupt.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Added the ability to recover from an incomplete call to CreateSegment/CreateTransaction. Since a Segment is created using 3 calls to Storage (Create Segment, Create State File, Write State File), it is possible that a previous call executed the first 1 or 2 of these steps but not the rest, which means that the Segment might not be usable. A subsequent call to createSegment/createTransaction may be able to recover this in certain conditions.
- If the Segment exists, but the State File does not exist or is corrupted, a subsequent call to CreateSegment/CreateTransaction will attempt to rebuild the State File (and return success).
- If the Segment exists and has a non-zero length, and the State File does not exist or is corrupted, a subsequent call to CreateSegment/CreateTransaction will rebuild the State File (and return `StreamSegmentExistsException`)
- If both the Segment and its associated State File exist (and the State File is valid), then `StreamSegmentExistsException` is returned.

Component changes:
- `StreamSegmentMapper`: added ability to recover from an incomplete Segment/Transaction creation that was previously run (see description above)
- `SegmentStateStore`: 
    - Treating empty State files the same as non-existing State files
    - Throwing `DataCorruptionException` if a State File is invalid (non-zero length, but can't be parsed).
- `FutureHelpers`: added exceptionallyCompose which helps return CompletableFutures instead of direct values.

**Purpose of the change**
Fixes #1829.

**What the code does**
See **Change Description** above.

**How to verify it**
New unit tests added; some existing unit tests were updated.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java [hunk 1]
```diff
@@ -263,6 +263,33 @@
...
+     *
+     * @param future  The original CompletableFuture to attach an Exception Listener.
+     * @param handler A Function that consumes a Throwable and returns a CompletableFuture of the same type as the original one.
+     *                This Function will be invoked if the original Future completed exceptionally.
+     * @param <T>     Type of the value of the original Future.
+     * @return A new CompletableFuture that will be completed either with the result of future (if it completed normally),
+     * or with the result of handler when applied to the exception of future, should future complete exceptionally.
+     */
+    public static <T> CompletableFuture<T> exceptionallyCompose(CompletableFuture<T> future, Function<Throwable, CompletableFuture<? extends T>> handler) {
+        CompletableFuture<T> result = new CompletableFuture<>();
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: I think a much simpler implementation of this function would be:
```
           future.handle((u, t) -> {
               if (t == null) {
                   return CompletableFuture.completedFuture(u);
               }
               return handler.apply(t);
           }).thenCompose(f -> f);
```

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java [hunk 2]
```diff
@@ -133,7 +139,7 @@ private ByteArraySegment serialize(SegmentState state) {
         }
     }
 
-    @SneakyThrows(IOException.class)
+    @SneakyThrows
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java]: Why this change

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java [hunk 3]
```diff
@@ -180,14 +177,88 @@ public StreamSegmentMapper(ContainerMetadata containerMetadata, OperationLog dur
...
+    private CompletableFuture<SegmentProperties> handleStorageCreateException(String segmentName, Throwable originalException, TimeoutTimer timer) {
+        if (!(originalException instanceof StreamSegmentExistsException)) {
+            // Some other kind of exception that we can't handle here.
+            return FutureHelpers.failedFuture(originalException);
+        }
+
+        return this.stateStore
+                .get(segmentName, timer.getRemaining())
+                .exceptionally(ex -> {
+                    // Segment exists, but the State File is missing or corrupt. We have the data needed to rebuild it,
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: Is it really a given that we have the data to rebuild it?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java [hunk 4]
```diff
@@ -180,14 +177,88 @@ public StreamSegmentMapper(ContainerMetadata containerMetadata, OperationLog dur
...
+                    // so ignore any exceptions coming this way.
+                    log.warn("{}: Missing or corrupt State File for existing Segment '{}'; recreating.", this.traceObjectId, segmentName, ex);
+                    return null;
+                })
+                .thenComposeAsync(s -> {
+                    if (s == null) {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: I feel like this null is overloaded because it does not differentiate between stateStore.get() throwing vs returning null. 
Perhaps the code would be more clear if this thenComposeAsync and the exceptionally block above were combined into a single handleAsync block

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/InMemoryStateStore.java [hunk 5]
```diff
@@ -42,7 +42,7 @@
     }
 
     @Override
-    @SneakyThrows(IOException.class)
+    @SneakyThrows
```
Comment (tkaitchuck) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/InMemoryStateStore.java]: This doesn't look like it is needed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java]: Because this method now throws `DataCorruptionException` in addition to `IOException`. AFAIK, there's no way of having `@SneakyThrows` declared multiple times.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: We rebuild it using the available info: the attributes given. That's pretty much everything we store in the state file at this point.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java (hunk 4 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: Well, I intentionally coalesce errors from `get` and it actually returning `null` into `null` because, as the description indicates, we treat missing and invalid state files as the same.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/InMemoryStateStore.java (hunk 5 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/InMemoryStateStore.java]: It's the same reason as above.

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java (hunk 1 above)
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: `handle` does not allow returning a `CompletableFuture`. It returns the same type as the one of the original `future`. It has the same signature as `exceptionally`, hence the need for this complication.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java (hunk 2 above)
Comment (tkaitchuck) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentStateStore.java]: DataCorruptionException should be runtime by our definitions...

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentState.java [hunk 6]
```diff
@@ -74,17 +76,22 @@ public void serialize(DataOutputStream target) throws IOException {
...
-    public static SegmentState deserialize(DataInputStream source) throws IOException {
-        byte version = source.readByte();
-        if (version == SERIALIZATION_VERSION) {
-            long segmentId = source.readLong();
-            String segmentName = source.readUTF();
-            Map<UUID, Long> attributes = AttributeSerializer.deserialize(source);
-            return new SegmentState(segmentId, segmentName, attributes);
-        } else {
-            throw new IOException(String.format("Unsupported version: %d.", version));
+    public static SegmentState deserialize(DataInputStream source) throws IOException, DataCorruptionException {
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentState.java]: Did you leave `throws IOException` on purpose? With the new code, we only throw `EOFException`, which extends ÌOException`, so the declaration is fine, but it might be better to reduce the scope.

Is there anything else that throws `IOException` here?

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java [hunk 7]
```diff
@@ -263,6 +263,33 @@
...
+        future.thenAccept(result::complete);
+        future.exceptionally(ex -> {
+            try {
+                FutureHelpers.completeAfter(() -> handler.apply(ex), result);
+            } catch (Throwable ex2) {
```
Comment (fpj) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: really minor, but If you are going to make further changes to this PR, could you please replace `ex2` with something like `innerException`, `innerEx`, or simply something else that isn't a number?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java [hunk 8]
```diff
@@ -180,14 +177,88 @@ public StreamSegmentMapper(ContainerMetadata containerMetadata, OperationLog dur
...
+     * @param attributes  The initial Attributes for the Segment, if any.
+     * @param timer       A TimeoutTimer to determine how much time is left to complete the operation.
+     * @return A CompletableFuture that, when completed, will indicate that the Segment has been successfully created.
+     */
+    private CompletableFuture<Void> createSegmentInStorageWithRecovery(String segmentName, Collection<AttributeUpdate> attributes, TimeoutTimer timer) {
+        return FutureHelpers
+                .exceptionallyCompose(
+                        this.storage.create(segmentName, timer.getRemaining()),
+                        ex -> handleStorageCreateException(segmentName, ExceptionHelpers.getRealException(ex), timer))
+                .thenComposeAsync(si ->
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: Also minor, but could you rename `si` to something more meaningful? from the signature of `getState`, this is a segment properties object, perhaps `segmentProps` if using properties makes it too long.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java [hunk 9]
```diff
@@ -180,14 +177,88 @@ public StreamSegmentMapper(ContainerMetadata containerMetadata, OperationLog dur
...
+                                // Need to create the state file before we throw any further exceptions in order to recover from
+                                // previous partial executions (where we created a segment but no or empty state file).
+                                this.stateStore.put(segmentName, getState(si, attributes), timer.getRemaining())
+                                               .thenRun(() -> {
+                                                   if (si.getLength() > 0) {
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: I need some clarification in the logic here:

1- Shouldn't we check whether the length is greater than zero before the `put` call? The `put` call will write the state file, no?
2- In the case the initial length is greater than zero, aren't we supposed to check whether the content is correct by reading and deserializing it? I saw that if the deserialization fails, then we throw data corruption exception.

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: I think I understand what this is trying to do now and have answered my own questions. The put will write the state file independent of it existing or not and its content. The verification actually happens in `handleStorageCreateException`. 

The length check is still puzzling me a bit, though. I think this is trying to distinguish between the case in which the state file has been partially populated or not populated at all, and in the case it has been partially populated, we return that the segment already exist. If the previous attempt did not complete, then it sounds better this time around to return success rather than segment already exists. what do you think?

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: Actually, from the test cases, it looks like we are not returning segment exists in the case of empty/corrupted state file, so I'm still missing the point of this length check for throwing segment exists.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentState.java (hunk 6 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/SegmentState.java]: Every operation from `DataInputStream` throws `IOException`. I only catch a subset of those, so I still need to leave `IOException` in the `throws` declaration.

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java (hunk 7 above)
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java (hunk 8 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java (hunk 9 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: The contract says that if we return `StreamSegmentExistsException`, then the segment must exist and must be in a usable state. In our case, if we get in here, the segment file does exist, but the state file does not or is corrupted. We need to fix it before returning so that the Controller is assured the segment can be used.

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java (hunk 1 above)
Comment (tkaitchuck) [reply common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: This code works I tested it. Handle can return any type.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java (hunk 4 above)
Comment (tkaitchuck) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: It is not obvious to me that this is correct for some arbitrary throwable. Shouldn't we handle errors differently from the special case of it being empty that we are handling.

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentMapper.java]: Fixed to only ignore `StreamSegmentNotExistsException` and `DataCorruptionException`.
