### PR TITLE
Issue 2641: Stream re-creation fix

### LINKED ISSUE #1012: Can't Delete Or Seal Stream With A Previously Used Name
**Problem description**

I can't delete a stream that had the name of a previous deleted stream in the same scope.

This is on 1260.9653ec6 in the alpha branch.

**Reproduction**

I can consistently reproduce this when:

- I create a scope named `jdm1` 
- I create a stream in it named `kyle`
- I seal `kyle`
- I delete `kyle`
- Later, I create a stream called `kyle`

At this point, I can't delete `kyle` (Precondition failed) or seal `kyle` (Internal Server Error).

**Problem location**

In the APIs:

- DELETE /v1/scopes/{scope-name}/streams/{stream-name}
- PUT v1/scopes/{scope-name}/streams/{stream-name}/state (with sealing payload)

**Suggestions for an improvement**

Let me seal the stream, don't let me create it in the first place, or if this is intentional, give me a more informative message when I try to seal it.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
This PR allows users to re-create streams: 
- The stream entity in the controller is now able to create segment numbers from a given `startingSegmentNumber` onward. This will avoid naming collisions with a previously deleted stream with the same name whose segments are being asynchronously deleted from the segment store. 
- The `AbstractStreamMetadataStore.java` implementations (`ZKMetadataStore.java`, `InMemoryMetadataStore.java`) are responsible for i) persistently storing the highest segment number for a stream (upon a `deleteStream` operation), and ii) to get a safe starting number (upon a `createStream` operation).
- `StreamMetadataTasks.java` takes into account the safe starting segment number calculated by `AbstractStreamMetadataStore.java` to create new segments in the segment store.

**Purpose of the change**
Fixes #1012, #1681, and #2641.

**What the code does**
Until now, all the streams were assumed to start the ids of their segments by `0`; this is a simple assumption but it cannot handle stream re-creation within short time intervals, given that segments in the segment store are deleted asynchronously. That is, if we delete a stream and create another with the same name, the controller could inadvertently ask the segment store to create a segment that is still _being deleted_ and related to the previously deleted stream. To fully support stream re-creations, we need the system to pick a starting segment number for a stream that is higher than the highest segment of the previously deleted stream with the same name. To achieve this, this PR addresses the following points:

- Stream objects in the controller now require a new metadata item: `startingSegmentNumber`. This number will allow the controller to start creating segment numbers for a given stream from `startingSegmentNumber` onward to avoid naming collisions with a previously deleted stream with the same name whose segments are being asynchronously deleted from the segment store. Consequently, `Stream.java` API (controller) adds a new method (`getStartingSegmentNumber`) and modifies the `create` method by adding a new argument (`startingSegmentNumber`).

- `PersistentStreamBase` implicitly benefits `startingSegmentNumber` to get the appropriate segment indexes. That is, for a `startingSegmentNumber > 0` the system creates `startingSegmentNumber` zero entries in the `segmentIndex`. This allows us to avoid modifying most of the logic in `TableHelper`, `SegmentIndexRecord` and `PersistentStreamBase`, as well as to keep the metadata format backward compatible. `PersistentStreamBase` also exposes a new method `getStartingSegmentNumber()` that can be used to get the starting segment number for a stream.

- `AbstractStreamMetadataStore.java` defines two new abstract methods: `recordLastStreamSegment` and `getSafeStartingSegmentNumberFor`. Its respective implementations (`ZKMetadataStore.java`, `InMemoryMetadataStore.java`) are responsible for implementing these methods that are intended to i) persistently store the highest segment number for a stream (upon a `deleteStream` operation) and ii) to get a safe starting number (upon a `createStream` operation). In ZooKeeper, the highest segment number for a stream is stored under `/lastActiveStreamSegment/{stream_path}/{number}` and it remains after the stream has been deleted. Note that this PR does not garbage collects this metadata; this might be achieved with the garbage collection mechanism proposed in PR #2756. 

- While orchestrating the creation workflow for a stream, `StreamMetadataTasks.java` takes into account the result from `getSafeStartingSegmentNumberFor` (encapsulated in a `CreateStreamResponse` object) to safely create new segments in the segment store.

_Parallel stream creations/deletions_: Parallel stream creations and deletions should work in a similar way as they do right now. That is, upon parallel creations, the operation that first hits Zookeeper is the one that will proceed with the creation of the stream, as `PersistentStreamBase` checks this in first place (`checkStreamExists`). All these parallel operations will read the same value from `getSafeStartingSegmentNumberFor`. Once the stream is created, parallel deletions will attempt to delete the Zookeeper metadata tree. Moreover, these parallel deletions may attempt to update the `/lastActiveStreamSegment/{stream_path}/{number}` value, which will be updated only if the new input value represents a segment number higher than the existing one. This is important to ensure that the stream re-creation has a starting segment number `>` than the highest segment of the previously deleted stream. In the case of simultaneous `create` and `delete` operations, we can assume that the first operation to be served is `create` (otherwise `delete` will not even start). Once the `create` operation starts, it sets the metadata of the stream (i.e., `segmentIndex`, `historyTable`) for the new segments to be created. Once the metadata set up is finished, the controller asynchronously creates the segments in the segment store. Let's assume that while the controller is creating segments in the segment store, there is a `delete` operation. In this case, the number of created segments in the segment store will always be lower than the number of initial segments defined in the controller metadata. As we use the controller metadata to get the highest stream segment number upon a `delete` (`getActiveSegments()` call), this means that the `delete` operation will store a `/lastActiveStreamSegment/{stream_path}/{number} >` the highest segment created in the segment store, which will allow us to re-create the stream.

**How to verify it**
All the tests working on new streams (non-recreated) should work as before (unit/integration/system).
Modified unit tests in `TableHelperTests.java` to check the operation of this class with `startingSegmentNumbers>0`.
Added new unit tests in `StreamMetadataStoreTest.java` to check the new operations in `StreamMetadataStore`.
Created new integration test `StreamRecreationTest.java` to check successive re-creations on the same stream.
Modified integration test `EndToEndTruncationTest.java` to test truncation on re-created streams.
Modified integration test `EndToEndWithScaleTest.java` to test scale events on re-created streams.
Updated system test `StreamsAndScopesManagementTest.java` to operate on re-created streams.

### CODE REVIEW

**Comment by RaulGracia** [comment]
[Re-creation of Streams cannot be tested](https://trello.com/c/TpZRqHBf/6-re-creation-of-streams-cannot-be-tested)

**Comment by shiveshr** [comment]
@RaulGracia 
There is one optimization that can be done - instead of storing starting segment number in a separate node per stream while the stream is active, it can be stored as first value in the segment index. 
This is because whenever we have to read a segment record, we first fetch the segment index. So we can look up first record in the index and know how it starts.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 1]
```diff
@@ -202,6 +203,12 @@ ZKScope newScope(final String scopeName) {
         return storeHelper.checkExists(stream.getStreamPath());
     }
 
+    @Override
+    public CompletableFuture<Integer> getSafeStartingSegmentNumberFor(final String scopeName, final String streamName) {
+        return storeHelper.getData(String.format(ZKStoreHelper.DELETED_STREAMS_PATH, getScopedStreamName(scopeName, streamName)))
+                          .handleAsync((data, ex) -> (ex == null) ? BitConverter.readInt(data.getData(), 0) + 1 : 0);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: only for DataNotFoundException should we ignore and default to 0. For everything else, we should log and throw the exception.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 2]
```diff
@@ -1517,4 +1534,9 @@ protected int getTransactionEpoch(UUID txId) {
     abstract CompletableFuture<Data<T>> getWaitingRequestNode();
 
     abstract CompletableFuture<Void> deleteWaitingRequestNode();
+
+    abstract CompletableFuture<Void> createStartingSegmentNumberNode(int startingSegmentNumber);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: we can avoid these two methods if we store the starting segment number in segment index. 
That way we can avoid an additional network call into zookeeper.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 3]
```diff
@@ -53,15 +53,16 @@
...
      * @param historyIndex history index
      * @param historyTable history table
      * @return Segment object
      */
-    public static Segment getSegment(final long segmentId, final byte[] segmentIndex, final byte[] segmentTable,
-                                     final byte[] historyIndex, final byte[] historyTable) {
-        int segmentNumber = getSegmentNumber(segmentId);
+    public static Segment getSegment(final long segmentId, final int startingSegmentNumber, final byte[] segmentIndex,
+                                     final byte[] segmentTable, final byte[] historyIndex, final byte[] historyTable) {
+        int segmentNumber = getSegmentNumber(segmentId) - startingSegmentNumber;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: segment index only stores "offset in segment table". Segment number is implicit. But with starting segment number, we should ensure its semantics/apis stay clean and consistent. 
Currently that is only called from getSegment and there you are handling the segment number by substracting the starting number. But it would be cleaner if you use the actual segment number and change the api there to pass the starting segment number to SegmentIndex instead.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 4]
```diff
@@ -703,7 +709,8 @@ public static boolean isEpochTransitionConsistent(final EpochTransitionRecord ep
         // verify that epoch transition record is consistent with segment table
         if (latest.getCreationEpoch() == epochTransitionRecord.getNewEpoch()) { // if segment table is updated
             epochTransitionRecord.newSegmentsWithRange.entrySet().forEach(segmentWithRange -> {
-                Optional<SegmentRecord> segmentOpt = SegmentRecord.readRecord(segmentIndex, segmentTable, getSegmentNumber(segmentWithRange.getKey()));
+                Optional<SegmentRecord> segmentOpt = SegmentRecord.readRecord(segmentIndex, segmentTable,
+                        getSegmentNumber(segmentWithRange.getKey()) - startingSegmentNumber);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: we should not do such computations here, rather change the api of segmentRecord.readRecord to take startingSegment number and perform this computation in there.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 5]
```diff
@@ -887,18 +894,20 @@ private static HistoryRecord findRecordInHistoryTable(long timestamp, byte[] his
...
-                                            final byte[] segmentTable) {
+                                            final byte[] segmentTable,
+                                            final int startingSegmentNumber) {
         boolean newRangesPredicate = newRanges.stream().noneMatch(x -> x.getKey() >= x.getValue() &&
                 x.getKey() >= 0 && x.getValue() > 0);
 
         List<AbstractMap.SimpleEntry<Double, Double>> oldRanges = segmentsToSeal.stream()
-                .map(segmentId -> SegmentRecord.readRecord(segmentIndex, segmentTable, getSegmentNumber(segmentId)).map(x ->
-                        new AbstractMap.SimpleEntry<>(x.getRoutingKeyStart(), x.getRoutingKeyEnd())))
+                .map(segmentId -> SegmentRecord.readRecord(segmentIndex, segmentTable, getSegmentNumber(segmentId) - startingSegmentNumber)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: same as above

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 3 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: in fact if we add starting segment number as first information in the index, then we dont even need to change the api. and we dont need to pass this information all the time.

**Comment by andreipaduroiu** [comment]
I'm wondering if there might be a simpler way to do this which does not require us to store an additional piece of data in the Metadata Store. 

Do Segment Numbers have to be Integers? Could they be Longs?
If they can be Longs, then we can generate the starting segment number by creating a random number (seeded with current time) as the high-order 32 bits, and then using 0's as the low-order 32 bits. This should allow up to 2^32 segments (just like now), but the randomization of the first 32 bits should ensure, with a decent probability, that two streams with the same name should not have the same segment numbers.

Alternatively we could pick the first 32 bits from a different source; maybe there's already a unique counter somewhere in the Controller.

**Comment by shiveshr** [comment]
@andreipaduroiu the final computed segment id are `Long` but they have two parts, the 32 bit segment number part and 32 bit epoch. 

If we change segment numbers from int to long then the overall id will become 96 bit and that will require far more changes (including to the controller-client wire protocol). 

Secondly, irrespective of the way we compute startingSegmentNumber, we will need to preserve that value and then use it in all our future computations. 
So only thing we will save upon by moving to a long based segment number is maintenance of last segment number for a deleted stream. 
This is not a big complexity introduction and neither is it costly as it doesnt have to be referred except during deletion of a stream and creation of a stream.

**Comment by arvindkandhare** [comment]
> Parallel stream creations/deletions: Parallel stream creations and deletions should work in a similar way as they do right now. That is, upon parallel creations, the operation that first hits Zookeeper is the one that will proceed with the creation of the stream, as PersistentStreamBase checks this in first place (checkStreamExists). All these parallel operations will read the same value from getSafeStartingSegmentNumberFor. Once the stream is created, parallel deletions will attempt to delete the Zookeeper metadata tree. Moreover, these parallel deletions may attempt to update the /lastActiveStreamSegment/{stream_path}/{number} value, which will be updated only if the new input value represents a segment number higher than the existing one. This is important to ensure that the stream re-creation has a starting segment number > than the highest segment of the previously deleted stream. In the case of simultaneous create and delete operations, we can assume that the first operation to be served is create (otherwise delete will not even start). Once the create operation starts, it sets the metadata of the stream (i.e., segmentIndex, historyTable) for the new segments to be created. Once the metadata set up is finished, the controller asynchronously creates the segments in the segment store. Let's assume that while the controller is creating segments in the segment store, there is a delete operation. In this case, the number of created segments in the segment store will always be lower than the number of initial segments defined in the controller metadata. As we use the controller metadata to get the highest stream segment number upon a delete (getActiveSegments() call), this means that the delete operation will store a /lastActiveStreamSegment/{stream_path}/{number} > the highest segment created in the segment store, which will allow us to re-create the stream.

Thanks for detailed comments. This answers my question. Will have another look at the PR.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 1 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Thanks, now the method logs and throws `CompletionException(ex)` in case of an exception different from `StoreException.DataNotFoundException`.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 2 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: That's true, this method has been removed as now the starting segment number is stored in the first position of the `segmentIndex`.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 3 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: With the exception of `createSegmentTableAndIndex` (where the starting segment number is needed as input parameter to be stored in `segmentIndex`), the rest of `TableHelper` methods signatures remain the same.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 4 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: Now `SegmentIndexRecord` is the one take care of this kind of computations, as the starting segment number is stored in the first position of the segment index.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 5 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: See comment above.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java [hunk 6]
```diff
@@ -31,6 +31,8 @@
 
 @Slf4j
 public class ZKStoreHelper {
+    static final String DELETED_STREAMS_PATH = "/lastActiveStreamSegment/%s";
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java]: Please move this constant to ZkStreamMetadataStore

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 7]
```diff
@@ -253,6 +254,22 @@ ZKScope newScope(final String scopeName) {
...
+    @Override
+    public CompletableFuture<Integer> getSafeStartingSegmentNumberFor(final String scopeName, final String streamName) {
+        return storeHelper.getData(String.format(ZKStoreHelper.DELETED_STREAMS_PATH, getScopedStreamName(scopeName, streamName)))
+                          .handleAsync((data, ex) -> {
+                              if (ex == null) {
+                                  return BitConverter.readInt(data.getData(), 0) + 1;
+                              } else if (ex instanceof StoreException.DataNotFoundException) {
+                                  return 0;
+                              } else {
+                                  log.error("Problem found while getting a safe starting segment number for {}: {}.",
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: please remove the second {} as it is not needed. log.error will print the exception stack without it too.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java [hunk 8]
```diff
@@ -21,26 +21,45 @@
...
         } else {
-            return Optional.of(parse(indexTable, segmentNumber));
+            return Optional.of(parse(indexTable, actualSegmentIndex));
         }
     }
 
     public static Optional<SegmentIndexRecord> readLatestRecord(final byte[] indexTable) {
-        return readRecord(indexTable, indexTable.length / INDEX_RECORD_SIZE - 1);
+        final int startingSegmentNumber = BitConverter.readInt(indexTable, STARTING_SEGMENT_NUMBER_POSITION);
+        return readRecord(indexTable, startingSegmentNumber + indexTable.length / INDEX_RECORD_SIZE - 2);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java]: instead of doing `-2` here i would have ```(indexTable.length - STARTING_SEGMENT_NUMBER_RECORD_SIZE) / INDEX_RECORD_SIZE - 1```

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 9]
```diff
@@ -1090,4 +1100,8 @@ public static int getTransactionEpoch(UUID txId) {
     public static long generalizedSegmentId(long segmentId, UUID txId) {
         return computeSegmentId(getSegmentNumber(segmentId), getTransactionEpoch(txId));
     }
+
+    public static int getStartingSegmentNumber(byte[] segmentIndex) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: Please move this method to the SegmentIndexRecord and keep the logic opaque in this class.

**Comment by shiveshr** [comment]
@RaulGracia There is one problem that we have not considered and addressed. 
Once a stream is deleted, we purge all its metadata from the store. However, there could be outstanding requests for the said stream in "request stream". 
These need to be invalidated too. Otherwise they may get replayed upon controller failover and can lead to unwanted situations. 
 
So perhaps with all events posted to request stream (except auto-scale events which anyway are segment specific) we should add "stream starting segment number". 
The event processing should proceed for the stream only if the event was posted for the current version of the stream. Else it should be discarded and ignored. 

Please open a separate issue to address that.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java (hunk 6 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 7 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 9 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java (hunk 8 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java]: I think that the proposed change is not feasible. The root cause is that this PR breaks the coupling between segment index position and segment number. That is, `SegmentIndexRecord.readRecord()` expects _segment numbers_ that will be then converted into the appropriate positions to access the segment index. However, your proposal is directly providing _a segment index position_ as input to `SegmentIndexRecord.readRecord()`. This does not work with the new approach. Instead, `readLatestRecord` needs to infer the last segment number for this stream so that `SegmentIndexRecord.readRecord()` can access to the appropriate index position. In other words, `startingSegmentNumber` is not `STARTING_SEGMENT_NUMBER_RECORD_SIZE`, but the number stored in the first position of the index that represents the stream starting segment number. As an example, this means that if the segment index has `11` positions (`1` position for the starting segment number + `10` indexed segments) and the starting segment number for this stream is `90`, `readLatestRecord` will execute `readRecord(99)` (last segment number for this stream, which differs from its position in the index).

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java]: `readRecord` takes segment number that it needs to read. 
```
latest segment number = startingSegmentNumber + `totalNumberOfRecordsInIndex` - 1
```
prior to this PR the startingSegmentNumber was always `0` and 
```totalNumberOfRecordsInIndex = length/PER_RECORD_SIZE```

However, now that we have put `STARTING_SEGMENT_NUMBER` which takes up STARTING_SEGMENT_NUMBER_RECORD_SIZE` space in the length our computation should change accordingly:

To calculate `totalNumberOfRecords`, we need to deduct `STARTING_SEGMENT_NUMBER_RECORD_SIZE` from total length and then divide it by per record size. 
```totalNumberOfRecords = (length - STARTING_SEGMENT_NUMBER_RECORD_SIZE) / PER_RECORD_SIZE```

The reason you could get away with deducting `2` was because `STARTING_SEGMENT_NUMBER_RECORD_SIZE` is same as `PER_RECORD_SIZE` which is 4 bytes (Integer.BYTES)

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java]: So you probably misunderstood my comment. I am not asking you to deduct startingSegmentNumber but number of bytes taken to store startingSegmentNumber. 
Its only incidental that we use same number of bytes to store an index record and the starting segment number. But we should make the computation more explicit here for future maintainability of the code.

Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentIndexRecord.java]: Thanks, I understood your point and fixed it.

**Comment by RaulGracia** [comment]
After a discussion with @shiveshr, we still need to think how to make this change backward compatible. So please do not merge until we got a decision for that. cc/ @arvindkandhare

**Comment by RaulGracia** [comment]
@shiveshr @arvindkandhare I modified the solution in order to make it backwards compatible as suggested. The main changes w.r.t. the previous solution are:
- The logic of `SegmentIndexRecord` and `TableHelper` is the same as before this PR.
- Instead of storing a `startingSemgmentNumber` as the first position in `segmentIndex`, now the controller creates `N` dummy entries in `segmentIndex` as proposed.

Running system tests to ensure that changes are working correctly (unit and integration tests pass).
