### PR TITLE
Issue 2211: Ensure state.connection is cleared incase of exceptions during SegmentOutputStreamImpl#reconnect()

### LINKED ISSUE #2211: IllegalStateException in SegmentOutputStreamImpl
**Problem description**
Writers logs the following warning repeatedly.
```
2017-12-20 07:12:20,141 527693 [clientInternal-4] WARN  i.p.c.s.i.SegmentOutputStreamImpl - f0976f52-7627-478b-8c1c-440cf5ac6516 Failed to connect: 
java.util.concurrent.CompletionException: java.lang.IllegalStateException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$17(Futures.java:466)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:522)
	at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:486)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 10 common frames omitted
```

**Problem location**
SegmentoutputStreamImpl.

**Suggestions for an improvement**

Fix the issue.
Logs: 
[readwriteandscalewithfailovertest.log.log.zip](https://github.com/pravega/pravega/files/1575506/readwriteandscalewithfailovertest.log.log.zip)

### PR DESCRIPTION
**Pull request by shrids**
Signed-off-by: Sandeep <sandeep.shridhar@emc.com>

**Change log description**
Ensure state.connection is cleared upon exceptions during `SegmentOutputStreamImpl#reconnect()`

**Purpose of the change**
Fixes #2211 

**What the code does**
Ensure state.connection is cleared incase of ConnectionFailedException while sending WireCommand.SetupAppend.

**How to verify it**
Tests should continue to pass.

### CODE REVIEW

**Comment by tkaitchuck** [comment]
The race is as follows:
ConnectionFactory setsUp the connection. But it IMMEDIATLY fails.
So the failure notification before the connection is actually assigned on line 528.
Which does nothing because the connection member was already null.
So the send on line 531 goes out on a connection that has already failed.
Which will throw again, but netty is not invoking the callback again because it already did and we already called close.
The change should fix that

**Comment by tkaitchuck** [comment]
@fpj and I discussed this. There is no good way to ensure a failure cannot occur before assigning newConnection as it would require connection setup and teardown occur with the scope of the lock. So the best thing to do is simply add a comment to the fix. I added a comment to the file.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -530,6 +530,8 @@ void reconnect() {
                          try {
                              connection.send(cmd);
                          } catch (ConnectionFailedException e1) {
+                             state.failConnection(e1); // This needs to be invoked here because call to failConnection
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: I'd rather add this comment between lines 532 and 533 as like this the indentation looks odd. Also, could we add a comment to the `SegmentOutputStreamImpl.State` class? The comment should explain that there is a potential race between `newConnection` and `failedConnection`, which we can't completely avoid because we have conciously made the decision of not putting calls to the connection under a lock

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: done, added additional comments.
