### PR TITLE
Issue 6306 : SLTS - avoid deadlock in truncate

### LINKED ISSUE #6306: SLTS - To avoid deadlock TruncateOperation on system segments should not call deleteBlockIndexEntriesForChunk
**Describe the bug**
1. SLTS stores storage metadata about storage metadata segments themselves in records pinned to memory.
2. To avoid circular dependency , SLTS operation on system segment should NEVER read or write from metadata table segments themselves.
3. There is a redundant deleteBlockIndexEntriesForChunk in TruncateOperation that can lead to unintentional lookup from storage metadata segment in case of SLTS operation on the system segments themselves.
4. This leads to a deadlock,

Location of the bug
https://github.com/pravega/pravega/blob/r0.9/segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java#L109

**To Reproduce**

Run following code with FileSystemIntegrationTests
``` java
    @Test
    public void repro() throws Exception {
        ArrayList<String> segmentNames = new ArrayList<>();
        int instanceId = 0;

        // Phase 1: Create segments and add some appends.
        log.info("Starting Phase 1.");
        try (val builder = createBuilder(++instanceId, true)) {
            val segmentStore = builder.createStreamSegmentService();

            // Create the StreamSegments.
            val count = 1000;
            for (int i = 0; i < count; i++) {
                String segmentName = getSegmentName(i);
                segmentNames.add(segmentName);
                segmentStore.createStreamSegment(segmentName, BASIC_SEGMENT_TYPE, null, TIMEOUT).join();
            }

            log.info("Created Segments: {}.", String.join(", ", segmentNames));
        }

        log.info("Finished.");
    }
```

**Screenshots**

**Additional information**

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
**Change log description**  
Issue 6306 : SLTS - avoid deadlock in truncate on system segments and improve logs.

**Purpose of the change**  
Fixes #6306 and #6297

**What the code does**  

- In case of system segments do not attempt to delete block read index entries.
- Add debug logs for openRead, openWrite and getStreamSegmentInfo methods.
- reduce log noise in system journals

**How to verify it**  
Tests must pass

### CODE REVIEW

File: segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java [hunk 1]
```diff
@@ -72,7 +72,12 @@ protected int getThreadPoolSize() {
     }
 
     protected ChunkMetadataStore getMetadataStore() throws Exception {
-        return new InMemoryMetadataStore(ChunkedSegmentStorageConfig.DEFAULT_CONFIG, executorService());
+        val metadataStore = new InMemoryMetadataStore(ChunkedSegmentStorageConfig.DEFAULT_CONFIG, executorService());
```
Comment (RaulGracia) [inline segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java:75]: Could you please add as a new test the code provided by @andreipaduroiu that reproduces this issue?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java [hunk 2]
```diff
@@ -113,7 +114,9 @@
                                                 }
 
                                                 // Remove read index block entries.
-                                                chunkedSegmentStorage.deleteBlockIndexEntriesForChunk(txn, streamSegmentName, oldStartOffset, segmentMetadata.getStartOffset());
+                                                if (!segmentMetadata.isStorageSystemSegment()) {
```
Comment (RaulGracia) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java:117]: Question: could this problem appear in other operations apart from truncate?

Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java:117]: For read/write this check is already there. This is the only one that I somehow missed and that went undetected. 
(Concat operation is illegal on system segments and will throw an assert).

I have added extra check to the unit tests on system tests to assert on any attempt to read from store.

File: segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java (hunk 1 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java:75]: It was careful log analysis that revealed that deadlock has occurred. The test doesn't itself detect deadlock and fail.
Because of async nature of flush to LTS it is difficult to write such tests.

However here I'm doing something even better - I already have unit tests that invoke complicated read/write/boot scenarios for system tests. Here I have added extra check to the unit tests on system tests to assert on any attempt to read from store. This will detect any unintentional call to metadata store in case of metadata segments and will fail immediately.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/TruncateOperation.java:117]: while today DefragmentOperation is only called inline during concat and concat is not valid operation on system segments.
In near future we may add background defrag. So to avoid future unintentional mistakes I added similar check for DefragmentOperation just as extra precaution.

File: segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java (hunk 1 above)
Comment (RaulGracia) [reply segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java:75]: @sachin-j-joshi I know what entailed to uncover the issue and the fact that @andreipaduroiu reproduced that locally was critical to uncover it. Not only this, all the existing tests were not enough to detect this problem, for this reason the bug got merged (irrespective if it was a previous bug in combination with a recent test). So, is it too much to ask to add a test (perhaps similar to the code used to reproduce this bug) to have more confidence on the fix?

Comment (sachin-j-joshi) [reply segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java:75]: - The dead lock is caused by very complex interactions only possible in fully integrated system.  
- The root cause is re-entrant calls to storage metadata segments during operations on system segments. 
- As a design principle operation on container metadata segment (CMS) and storage metadata segments (SMS) should use only in memory data and should not have any dependency what so ever on any other operation on the same segments. This rule was unintentionally broken. But that did not cause deadlock because we had per segment serialization of requests which was [changed only recently](https://github.com/pravega/pravega/pull/6185/files#diff-e8690fd36836c2a4aa9501f65eddf54431a88ba86c779e3f78f737ab631162d6R756) to serializing on the group
- Solution is to  prevent such reentrant calls. 
- Now - The unit tests make sure no such re-entrant calls are ever made.


Why do you need to have complicated and unreliable tests, when you can check the assumptions of "no circular dependency" on each and every method call on storage system segments?

Yes I think it is difficult to recreate exact end to end test, especially I don't know how best we can detect presence of deadlock and what exactly to assert on? 

Relying on such integration tests to validate does not seem correct approach to me here.- when you can validate more directly We have narrowed down a problem, have a specific fix and then also testing/validating it in component level tests.

Comment (sachin-j-joshi) [reply segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java:75]: To be clear there are already several unit tests that create and test reentry/deadlock scenario.
In unit tests by necessity we use **mock implementation of key value store** and as such it doesn't internally call actual openWrite which is a totally expected re-entrant call here. 

Existing tests -

1. https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/SystemJournalTests.java#L1223
2. 
3. https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java#L2426
4. 
5. https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java#L2558
6. 
7. https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java#L2632
8.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java [hunk 3]
```diff
@@ -252,11 +254,19 @@ public void initialize(long containerEpoch) {
...
                                     LoggerHelpers.traceLeave(log, "openWrite", traceId, retValue);
                                     return retValue;
                                 }, executor);
                             }, executor),
-                    executor);
+                    executor)
+                    .handleAsync( (v, ex) -> {
+                        if (null != ex) {
+                            log.warn("{} openWrite - exception segment={} latency={}.", logPrefix, streamSegmentName, timer.getElapsedMillis(), ex);
+                            handleException(streamSegmentName, ex);
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:266]: This doesn't look like it's covered by tests. 

Also, won't this effectively swallow the exception? Does `handleException` re-throw it? (if that's the case, you're likely 
 double logging it).

Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:266]: same below with the other ones.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java [hunk 4]
```diff
@@ -425,6 +438,8 @@ boolean isStorageSystemSegment(SegmentMetadata segmentMetadata) {
         checkInitialized();
         return executeSerialized(() -> {
             val traceId = LoggerHelpers.traceEnter(log, "seal", handle);
+            Timer timer = new Timer();
+            log.debug("{} seal - segment={} latency={}.", logPrefix, handle.getSegmentName());
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:442]: `seal - started` to be consistent with the rest of the log messages you added.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:266]: Also why not use `exceptionally`? That would have saved you the `if` statement.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java [hunk 5]
```diff
@@ -179,8 +179,9 @@ private void logEnd() {
                                 targetSegmentMetadata.setChunkCount(targetSegmentMetadata.getChunkCount() + sourceSegmentMetadata.getChunkCount());
 
                                 // Delete read index block entries for source.
-                                chunkedSegmentStorage.deleteBlockIndexEntriesForChunk(txn, sourceSegment, sourceSegmentMetadata.getStartOffset(), sourceSegmentMetadata.getLength());
-
+                                if (!sourceSegmentMetadata.isStorageSystemSegment()) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ConcatOperation.java:182]: It would be nice to explain (In a comment) why we are not doing this for storage system segments.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]
Let's also try to add some more tests to 
1) cover the exception handlers you wrote.
2) prove that there is no longer a deadlock. This means you'll need to write a test that deadlocks using the previous code, but should pass with this one.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 3 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:266]: 1. On each SLTS methods there are plenty of tests that pass invalid arguments and cause failures etc. Here is one example https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageTests.java#L228

2. Yes handleException rethrows but doesn't log the exception.
3. Make sense to use `exceptionally `so that I save if

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 4 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:442]: Thanks. I missed that

**Comment by sachin-j-joshi** [comment]
@andreipaduroiu 
https://github.com/pravega/pravega/pull/6307#discussion_r712272662

https://github.com/pravega/pravega/pull/6307#discussion_r712294863

**Review by andreipaduroiu — APPROVED** [review]

**Review by RaulGracia — APPROVED** [review]
