### PR TITLE
Issue 3329:  Remove spurious stacktraces from Kubernetes framework

### LINKED ISSUE #3329: Spurious stack traces in the output Kubernetes framework.
**Problem description**
Ensure spurious stack traces (listed below) are not logged by the Kubernetes framework.

1. 
``` 
2019-01-30 10:58:52,781 1359216 [pravega-k8s-client-3] WARN  i.p.t.s.f.kubernetes.K8sClient - Exception while fetching status of pod, will attempt a retry
    java.net.SocketTimeoutException: timeout
```
2. API conflict exception.
3. Retryable errors with stack traces should not be logged.

**Problem location**
Kubernetes test framework.

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Ensure spurious stack traces are not logged for retry able errors.
- Ensure test logs are preserved across retries during log downloads.
- Wait for log download to complete before starting the next test.

**Purpose of the change**  
Fixes #3329 

**What the code does**  
- Ensure spurious stack traces are not logged for retry able errors.
- Ensure test logs are preserved across retries during log downloads.
- Wait for log download to complete before starting the next test.

**How to verify it**  
All the existing tests should continue to pass.
Update: verified with a system test run on PKS cluster.

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 1]
```diff
@@ -547,20 +551,25 @@ public void deletePVC(String namespace, String name) {
...
                         try {
                             @Cleanup
                             InputStream logStream = logUtility.streamNamespacedPodLog(fromPod);
-                            Files.copy(logStream, Paths.get(toFile));
-                            log.debug("log copy completed for pod {}", podName);
+                            // On every retry this method attempts to download the complete pod logs from from K8s api-server. Due to the
+                            // amount of logs for a pod and the K8s cluster configuration it can so happen that the K8s api-server can
+                            // return truncated logs. Hence, every retry attempt does not overwrite the previously downloaded logs for
+                            // the pod.
+                            String logFile = toFile + "-" + randomAlphanumeric(5) + ".log";
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Instead of an alphanumeric, could we keep the order of logs (i.e., use a number sequence)? This would help people debugging to keep the sense of time while looking across logs.

Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: makes sense, done.

**Comment by shrids** [comment]
[Issue 3329: Remove spurious stacktraces from Kubernetes framework](https://trello.com/c/ImEKrnsm/106-issue-3329-remove-spurious-stacktraces-from-kubernetes-framework)

**Comment by RaulGracia** [comment]
I checked the Jenkins logs and they look much better. I only have seen a couple of exceptions, which I don't know if they need to be shortened as well:
```  
2019-02-05 07:19:22,223 7871 [OkHttp https://husk-nightshift.ecs.lab.emc.com:8443/apis/zookeeper.pravega.io/v1beta1/namespaces/default/zookeeper-clusters/zookeeper] ERROR i.p.t.s.f.kubernetes.K8sClient - Exception observed for method getCustomObject with response code 404
    io.kubernetes.client.ApiException: Not Found
    	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
    	at io.kubernetes.client.ApiClient$1.onResponse(ApiClient.java:837)
    	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
    	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    2019-02-05 07:19:22,224 7872 [OkHttp https://husk-nightshift.ecs.lab.emc.com:8443/apis/zookeeper.pravega.io/v1beta1/namespaces/default/zookeeper-clusters/zookeeper] WARN  i.p.t.s.f.kubernetes.K8sClient - Exception while trying to fetch instance zookeeper of custom resource zookeeper.pravega.io, try to create it. Details: io.kubernetes.client.ApiException: Not Found
```
And also:
```
2019-02-05 07:19:47,685 33333 [OkHttp https://husk-nightshift.ecs.lab.emc.com:8443/api/v1/namespaces/default/pods?pretty=false&includeUninitialized=true&labelSelector=component%3Dpravega-segmentstore&watch=false] WARN  i.p.t.s.f.s.k.PravegaSegmentStoreK8sService - Exception observed while checking status of pods pravega-segmentstore
    java.util.concurrent.CompletionException: java.lang.NullPointerException
    	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
    	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
    	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    	at io.pravega.test.system.framework.kubernetes.K8sClient$K8AsyncCallback.onSuccess(K8sClient.java:608)
    	at io.kubernetes.client.ApiClient$1.onResponse(ApiClient.java:842)
    	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
    	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException: null
```

I leave it to you to considered "spurious" or not :)

However, I took a random log (`readwriteandscalewithfailovertest-n6o7l-1`) and I see the following: the log starts at `2019-02-05 08:42:19,859` and finishes at `2019-02-05 08:47:40,403`. However, the test takes around 13 minutes to complete, so the test driver log is still incomplete. I expected to see other logs such as `readwriteandscalewithfailovertest-n6o7l-2...3...4` to have all the information.

**Comment by shrids** [comment]
Thanks @RaulGracia . I have updated the code to handle the remaining two stack traces. 
Regarding the log issue will investigate why the K8s API server is not returning the complete logs.
