### PR TITLE
Issue 6223: SLTS - GC deleteSegment delete/update metadata in small batches.

### LINKED ISSUE #6223: SLTS - GC deleteSegment needs to delete update/metadata in small batches
**Describe the bug**
SLTS GC deleteSegment needs to delete update/metadata in batches to avoid running into 32MB transaction size limit

**To Reproduce**
1. Create a segment with 500K segment/index entries
2. Delete it
3. GC fails with exception (unable to commit transaction, 32MB transaction size limit)

**Screenshots**
None

**Additional information**

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
Issue 6223: SLTS - GC deleteSegment delete/update metadata in small batches.

**Purpose of the change**  
Fixes #6223 

**What the code does**  
Instead of modifying all metadata for deleted segment in a single transaction, break the delete/update into multiple small batches.

**How to verify it**  
All tests should pass

### CODE REVIEW

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java [hunk 1]
```diff
@@ -262,6 +270,7 @@
         this.garbageCollectionMaxQueueSize = properties.getInt(GARBAGE_COLLECTION_MAX_QUEUE_SIZE);
         this.garbageCollectionSleep = Duration.ofMillis(properties.getInt(GARBAGE_COLLECTION_SLEEP));
         this.garbageCollectionMaxAttempts = properties.getInt(GARBAGE_COLLECTION_MAX_ATTEMPTS);
+        this.garbageCollectionTransactionBatchSize = properties.getInt(GARBAGE_COLLECTION_MAX_TXN_BATCH_SIZE);
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorageConfig.java:273]: `getPositiveInt` ?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 2]
```diff
@@ -293,17 +295,54 @@ public GarbageCollector(int containerId, ChunkStorage chunkStorage,
...
+                                () -> txn.get(currentChunkName.get())
+                                        .thenComposeAsync(metadata -> {
+                                            val chunkMetadata = (ChunkMetadata) metadata;
+                                            CompletableFuture<Void> retFuture = CompletableFuture.completedFuture(null);
+
+                                            // Add to list of chunks to delete
+                                            chunksToDelete.add(chunkMetadata.getName());
+
+                                            // Skip if metadata is possibly deleted in last attempt, we are done.
+                                            if (null == chunkMetadata) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:313]: How can this be null? The previous line assumes it's not.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 3]
```diff
@@ -293,17 +295,54 @@ public GarbageCollector(int containerId, ChunkStorage chunkStorage,
...
+                                    }
+                                    return CompletableFuture.completedFuture(null);
+                                }, storageExecutor)
                                 .thenComposeAsync(v -> this.addChunksToGarbage(txn.getVersion(), chunksToDelete), storageExecutor)
+                                .thenComposeAsync(v -> deleteBlockIndexEntriesForSegment(streamSegmentName, segmentMetadata.getStartOffset(), segmentMetadata.getLength()))
                                 .thenComposeAsync(v -> {
-                                    deleteBlockIndexEntriesForChunk(txn, streamSegmentName, segmentMetadata.getStartOffset(), segmentMetadata.getLength());
-                                    txn.delete(segmentMetadata.getName());
-                                    return txn.commit();
+                                    @Cleanup
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:342]: This `@Cleanup` will close your `innerTxn` before it has a chance to execute everything it needs. It will call `close` after line 345 executes, however line 345 returns a CompletableFuture, which indicates there is an async task which will complete sometime later. How is that task execution going to be affected if `innerTxn` is in a `closed` state?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 4]
```diff
@@ -333,6 +372,17 @@ public GarbageCollector(int containerId, ChunkStorage chunkStorage,
                 }, storageExecutor);
     }
 
+    private CompletableFuture<Void> addTransactionForUpdateBatch(Set<ChunkMetadata> batch, String name) {
+        // create a sub transaction for a batch.
+        @Cleanup
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:377]: Same here.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 5]
```diff
@@ -343,6 +393,48 @@ void deleteBlockIndexEntriesForChunk(MetadataTransaction txn, String segmentName
...
+                () -> !isDone.get(),
+                () -> {
+                    currentBatch.clear();
+                    while (offset.get() < endOffset) {
+                        val name = NameUtils.getSegmentReadIndexBlockName(segmentName, offset.get());
+                        if (currentBatch.size() >= config.getGarbageCollectionTransactionBatchSize()) {
+                            return addTransactionForDeleteBatch(currentBatch, segmentName);
+                        }
+                        currentBatch.add(name);
+                        offset.set( offset.get() + config.getIndexBlockSize());
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:415]: `offset.addAndGet`

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 6]
```diff
@@ -343,6 +393,48 @@ void deleteBlockIndexEntriesForChunk(MetadataTransaction txn, String segmentName
         }
     }
 
+    /**
+     * Delete block index entries for given segment.
+     */
+    CompletableFuture<Void> deleteBlockIndexEntriesForSegment(String segmentName, long startOffset, long endOffset) {
+        val currentBatch = Collections.synchronizedSet(new HashSet<String>());
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:400]: Can you move this to line 408, in which case you don't need to clear it every time and don't need a synchronized set?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java [hunk 7]
```diff
@@ -343,6 +393,48 @@ void deleteBlockIndexEntriesForChunk(MetadataTransaction txn, String segmentName
...
+                    } else {
+                        return CompletableFuture.completedFuture(null);
+                    }
+                },
+                storageExecutor);
+    }
+
+    private CompletableFuture<Void> addTransactionForDeleteBatch(Set<String> batch, String segmentName) {
+        // create a sub transaction for a batch.
+        @Cleanup
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:430]: and here

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java (hunk 3 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java]: Oops forgot to fix that. Good catch.
Fixed now.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java (hunk 6 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java]: done

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/GarbageCollector.java:308]: fixed

**Review by andreipaduroiu — APPROVED** [review]
