### PR TITLE
Issue 1782: Ensure we close connectionFactory during the tear down of AbstractFailoverTest

### LINKED ISSUE #1782: On failure AbstractFailoverTests closes things in the wrong order
**Problem description**
It is normally expected that readers and writers are closed first before the connection factory. This is because closing the connection factory closes the threadpool, which generates lots of errors.
Normally this is the case, but in the event of a test timeout or an exception / hang the test closes the connection factory directly which creates a lot of log noise.

**Problem location**
AbstractFailoverTests

**Suggestions for an improvement**
Close all the readers and writers first before shutting down the connectionFactory

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
* AbstractFailoverTests(`ReadWriteAndAutoScaleWithFailoverTest `and `ReadWriteAndScaleWithFailoverTest`) close ClientFactory( internally ConnectionFactory) in case of an exception before stopping the reader and writer threads. This causes some log noise. The change intends to reduce this noise.

**Purpose of the change**
Fixes #1782

**What the code does**
- Stop readers and writers before closing connectionFactory
- Ensure over all execution of the the test and its setup methods are time limited to 15 mins.

**How to verify it**
- reduced log noise after test execution.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java [hunk 1]
```diff
@@ -97,58 +104,65 @@ public void setup() {
...
         testState.stopReadFlag.set(true);
         testState.stopWriteFlag.set(true);
+        //scale the controller and segmentStore back to 1 instance.
         controllerInstance.scaleService(1, true);
         segmentStoreInstance.scaleService(1, true);
+        //interrupt writers and readers threads if they are still running.
+        testState.writers.forEach(future -> future.cancel(true));
+        testState.readers.forEach(future -> future.cancel(true));
+        clientFactory.close();
+        readerGroupManager.close();
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: shouldn't all these be before controller, segmentstore scaling back to 1 instances each? i mean the last step should be 
```
controllerInstance.scaleService(1, true);
 segmentStoreInstance.scaleService(1, true);
```

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java [hunk 2]
```diff
@@ -97,81 +106,87 @@ public void setup() {
...
         testState.stopReadFlag.set(true);
         testState.stopWriteFlag.set(true);
+        //scale the controller and segmentStore back to 1 instance.
         controllerInstance.scaleService(1, true);
         segmentStoreInstance.scaleService(1, true);
+        //interrupt writers and readers threads if they are still running.
+        testState.writers.forEach(future -> future.cancel(true));
+        testState.readers.forEach(future -> future.cancel(true));
+        clientFactory.close(); //close the clientFactory/connectionFactory.
+        readerGroupManager.close();
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: same comment as above.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java [hunk 3]
```diff
@@ -97,58 +104,65 @@ public void setup() {
...
         executorService.shutdownNow();
         testState.eventsReadFromPravega.clear();
     }
 
 
     @Test(timeout = 12 * 60 * 1000)
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: If we are adding a global timeout, then we can remove this one.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java [hunk 4]
```diff
@@ -97,81 +106,87 @@ public void setup() {
...
         executorService.shutdownNow();
         testState.eventsReadFromPravega.clear();
     }
 
     @Test(timeout = 12 * 60 * 1000)
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: With a global timeout, we don't need this annotation.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java [hunk 5]
```diff
@@ -97,81 +106,87 @@ public void setup() {
...
+        controllerInstance.scaleService(3, true);
+        segmentStoreInstance.scaleService(3, true);
+        Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
 
-            //bring the instances back to 3 before performing failover after scaling
-            controllerInstance.scaleService(3, true);
-            segmentStoreInstance.scaleService(3, true);
-            Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
+        //scale manually
+        log.debug("Number of Segments before manual scale:" + controller.getCurrentSegments(scope, SCALE_STREAM)
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: please replace with:
```
log.debug("Number of Segments before manual scale: {}", controller.getCurrentSegments(scope, SCALE_STREAM)
                           .get().getSegments().size());
```
```

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java [hunk 6]
```diff
@@ -97,81 +106,87 @@ public void setup() {
...
+            if (!scaleStatus.get()) {
+                log.error("Scale operation did not complete", scaleStatus.get());
+                Assert.fail("Scale operation did not complete successfully");
+            }
+        } else {
+            Assert.fail("Scale operation threw an exception");
         }
-        cleanUp(scope, SCALE_STREAM);
+
+        log.debug("Number of Segments post manual scale:" + controller.getCurrentSegments(scope, SCALE_STREAM)
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: Please replace with:

```
log.debug("Number of Segments post manual scale: {}",  controller.getCurrentSegments(scope, SCALE_STREAM)
                   .get().getSegments().size());
```

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java (hunk 1 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: yes, just that any exceptions during the tear down might prevent the `service scale down `from being executed. Do not see a possibility hence updated the code.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java (hunk 2 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java (hunk 3 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: yes, removed it.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java (hunk 5 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: Done.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java (hunk 6 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/ReadWriteAndScaleWithFailoverTest.java]: Done.
