### PR TITLE
Issue 3058: Additional unit tests for Controller Metadata Scalability work

### LINKED ISSUE #3058: More unit tests and bug fixes in Controller metadata scalability work
**Problem description**
Add more unit tests for issue 2943. 

Bugs to fix:
1. Illegal State Exception: Duplicate key

Duplicate Key exception thrown from fetchEpochs method in PersistentStreamBase because we are trying to include identity epoch in the result set twice.

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Duplicate key StreamSegmentRecord(segmentNumber=3, creationEpoch=2, creationTime=1541131738401, keyStart=0.5, keyEnd=1.0)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at io.pravega.controller.store.stream.PersistentStreamBase.newEpochRecord(PersistentStreamBase.java:1532)
```

2. Truncation test data not found exception
```
io.pravega.controller.store.stream.ZooKeeperStreamTest > truncationTest FAILED
    java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: /store/scope/stream993/segmentsSealedSizeMapShardPath/1
        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: /store/scope/stream993/segmentsSealedSizeMapShardPath/1
```

3. Data not found exception
```
io.pravega.controller.store.stream.StoreException$DataNotFoundException: streamCutTest
	at io.pravega.controller.store.stream.PersistentStreamBase.lambda$getSealedSegmentSizeMapShard$185(PersistentStreamBase.java:1444)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at io.pravega.controller.store.stream.PersistentStreamBase.getSealedSegmentSizeMapShard(PersistentStreamBase.java:1439)
	at io.pravega.controller.store.stream.PersistentStreamBase.lambda$sizeBetweenStreamCuts$76(PersistentStreamBase.java:570)
```

**Problem location**
Persistent stream base

**Suggestions for an improvement**
FIx the issue

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
Unit test of all stream metadata operations with large number of epochs spilling over multiple chunks and shards of history time series chunks and sealed segment sizes map shards. 

**Purpose of the change**  
Fixes #3058 

**What the code does**  
`PersistentStreamBase` is updated to expose new @VisibleForTesting` methods for setting unit testable chunk and shard map sizes. New unit tests are added to trigger scenarios where metadata spills over multiple chunks and shards.

Found three issues that have been fixed. 
 1. reduce method in `getEpochsFromHistoryChunk` tried including identity twice if `first` was ahead of `from`, resulting in duplicate exception. Fixed it. 
2. `truncationTest` `DataNotFoundException`: this happened because we were using segment number instead of epoch for finding the sealed shard. Fixed it. 
3. `sizeBetweenStreamCut` fetches `sealedSegmentMapShard` for all segments that are part of its computation. However, if no segment mapping to shard was sealed, then the shard is not created and can result in `DataNotFoundException`. We now handle `DataNotFound` and return `emptyMap` for it. 

Also, `fetchEpochs` now takes `ignoreCache` flag. 
UI call (scale metadata) sends `ignoreCache = false`, whereby taking the cached value.
All other flows that invoke this method will not use the cached metadata for computation, but retrieve the latest value from store so that the answer is always accurate at the time of computation. 
We also make sure when we always fetch history chunks from store until the chunk is full to its capacity. From then onward we can fetch it from cache.  

**How to verify it**  
Unit tests added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 1]
```diff
@@ -55,26 +55,35 @@
...
 import static io.pravega.shared.segment.StreamSegmentNameUtils.computeSegmentId;
 import static io.pravega.shared.segment.StreamSegmentNameUtils.getSegmentNumber;
 import static java.util.stream.Collectors.toMap;
 
 @Slf4j
 public abstract class PersistentStreamBase implements Stream {
-
     private final String scope;
     private final String name;
+    private final AtomicInteger historyChunkSize;
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: I don't understand why these are being added.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 2]
```diff
@@ -55,26 +55,35 @@
...
 
     PersistentStreamBase(final String scope, final String name) {
         this.scope = scope;
         this.name = name;
+        historyChunkSize = new AtomicInteger(HistoryTimeSeries.HISTORY_CHUNK_SIZE);
+        shardSize = new AtomicInteger(SealedSegmentsMapShard.SHARD_SIZE);
+    }
+
+    @VisibleForTesting
+    void setHistoryChunkAndSealedSizeMapShardSizes(int historyChunkSize, int shardSize) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Even though this is flagged as visible for testing, it is opening up for changes to the internal state of the object, no?  Isn't there a better way of achieving the same goal, like a constructor that is visible for testing that takes these values as parameters?

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 3]
```diff
@@ -518,15 +527,16 @@ private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegments
                                 });
     }
 
-    private CompletableFuture<Set<StreamSegmentRecord>> segmentsBetweenStreamCutSpans(Map<StreamSegmentRecord, Integer> spanFrom,
+    @VisibleForTesting
+    CompletableFuture<Set<StreamSegmentRecord>> segmentsBetweenStreamCutSpans(Map<StreamSegmentRecord, Integer> spanFrom,
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Does this method have side-effects? It was private before and I'm worried that we are increasing substantially the visible method surface here for testing purposes.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 4]
```diff
@@ -550,10 +560,11 @@ private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegments
                 }).thenApply(x -> segments);
     }
 
-    private CompletableFuture<Long> sizeBetweenStreamCuts(Map<Long, Long> streamCutFrom, Map<Long, Long> streamCutTo,
+    @VisibleForTesting
+    CompletableFuture<Long> sizeBetweenStreamCuts(Map<Long, Long> streamCutFrom, Map<Long, Long> streamCutTo,
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: The description of the PR talks about:

> We now handle DataNotFound and return emptyMap for it (`sizeBetweenStreamCut`).

I'm not seeing it.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 5]
```diff
@@ -907,7 +919,7 @@ private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegments
                                     activeEpochRecord.getSegments().stream()
                                                           .map(x -> newSegmentRecord(computeSegmentId(getSegmentNumber(x.segmentId()),
                                                                   committingTxnRecord.getNewActiveEpoch()),
-                                                                  timeStamp, x.getKeyStart(), x.getKeyEnd()))
+                                                                  timeStamp + 1, x.getKeyStart(), x.getKeyEnd()))
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Why +1?

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 6]
```diff
@@ -918,7 +930,7 @@ private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegments
                             EpochRecord duplicateActiveEpoch = EpochRecord.builder().epoch(committingTxnRecord.getNewActiveEpoch())
                                                                           .referenceEpoch(activeEpochRecord.getReferenceEpoch())
                                                                           .segments(duplicateActiveSegments)
-                                                                          .creationTime(timeStamp).build();
+                                                                          .creationTime(timeStamp + 1).build();
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Why +1?

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 7]
```diff
@@ -928,7 +940,7 @@ private long findSegmentSplitsMerges(List<StreamSegmentRecord> referenceSegments
                             HistoryTimeSeriesRecord timeSeriesRecordActiveEpoch =
                                     HistoryTimeSeriesRecord.builder().epoch(duplicateActiveEpoch.getEpoch())
                                                            .referenceEpoch(duplicateActiveEpoch.getReferenceEpoch())
-                                                           .creationTime(timeStamp).build();
+                                                           .creationTime(timeStamp + 1).build();
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Why +1?

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 8]
```diff
@@ -1422,13 +1434,24 @@ private TxnStatus handleDataNotFoundException(Throwable ex) {
...
 
-    private CompletableFuture<SealedSegmentsMapShard> getSealedSegmentSizeMapShard(int shard) {
-        return getSealedSegmentSizesMapShardData(shard).thenApply(x -> SealedSegmentsMapShard.fromBytes(x.getData()));
+    @VisibleForTesting
+    CompletableFuture<SealedSegmentsMapShard> getSealedSegmentSizeMapShard(int shard) {
+        return getSealedSegmentSizesMapShardData(shard)
+                .handle((r, e) -> {
+                    if (e != null) {
+                        if (Exceptions.unwrap(e) instanceof DataNotFoundException) {
+                            return SealedSegmentsMapShard.builder().shardNumber(shard).sealedSegmentsSizeMap(Collections.emptyMap()).build();
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Ok, the `emptyMap` is returned here.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: These are being added with a new test visible `setter` that allows us to test this class with smaller chunk sizes.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 3 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: this method only reads and performs computation, doesnt change the metadata state. 
so its visibility (at package level) is safe. 

This class is anyway not instantiated directly and callers deal with `Stream` interface which does not have these apis.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: The changes are to the method sizeBetweenStreamcut calls --> getSealedSegmentSizeMapShard
```
    CompletableFuture<SealedSegmentsMapShard> getSealedSegmentSizeMapShard(int shard) {
        return getSealedSegmentSizesMapShardData(shard)
                .handle((r, e) -> {
                    if (e != null) {
                        if (Exceptions.unwrap(e) instanceof DataNotFoundException) {
                            return SealedSegmentsMapShard.builder().shardNumber(shard).sealedSegmentsSizeMap(Collections.emptyMap()).build();
                        } 
                        throw new CompletionException(e);
                    } else {
                        return SealedSegmentsMapShard.fromBytes(r.getData());
                    }
                });
    }
```

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 5 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: in rolling txn, we create two epochs -> txnDuplicateEpoch, activeDuplicateEpoch..
We want to have our time monotonically increasing. 
Currently they both get the same `time`.

Note: time is only used for UI queries for scaleMetadata which results in calling getEpochsAtTime.
So it doesnt affect any other business logic.. But while testing, having monotonically increasing time gives us an exact result for each value of time.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 6 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: replied above.. duplicateActiveEpoch = txnDuplicateEpoch + 1 
this ensures monotonically increasing..
earlier we used the same time for both.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 2 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: i can have the constructor, but we will need to add the constructor to the derived classes (ZkStream.java and InMemoryStream.java) as they are the classes that are actually instantiated. 
I was trying to avoid that change.. but i think its better to do it that way.. will make the change

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 9]
```diff
@@ -1460,32 +1487,34 @@ private Segment transform(StreamSegmentRecord segmentRecord) {
...
+
                                      boolean ignoreCached = i >= latestChunkNumber;
-                                     return getEpochsFromHistoryChunk(i, fromEpoch, toEpoch, firstEpoch, ignoreCached);
+                                     return getEpochsFromHistoryChunk(i, firstEpoch, toEpoch, ignoreCached);
                                  }).collect(Collectors.toList())))
                 .thenApply(c -> c.stream().flatMap(Collection::stream).collect(Collectors.toList()));
     }
 
-    private CompletableFuture<List<EpochRecord>> getEpochsFromHistoryChunk(int chunk, int fromEpoch, int toEpoch, int firstEpoch, boolean ignoreCached) {
+    private CompletableFuture<List<EpochRecord>> getEpochsFromHistoryChunk(int chunk, int firstEpoch, int toEpoch, boolean ignoreCached) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: I don't understand the change from `from` to `first`. Actually, the previous situation was even more confusing as we had `first`, `from`, and `to`. Can you elaborate on the semantics of the arguments here?

**Comment by fpj** [comment]
Where is this fixed:

> truncationTest DataNotFoundException: this happened because we were using segment number instead of epoch for finding the sealed shard. Fixed it.

I don't see any change to `truncationTest`.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 9 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: so the logic is as follows:
`from` and `to` are supplied by caller. 
They both can lie in different chunks and from is not necessarily the starting entry in the chunk it is found in. 

Using `from` and `to` we can compute the chunk number (modulo operation). 
So we call all the chunks in parallel and ask them to read all epochs between `from` and `to`. 

`first` simply tells this method which is the `first` entry to be read from in the chunk. 
For chunk which contains `from` the `first` is equal to from. For every other chunk the `first` corresponds to first record in the chunk. 

Since HistoryTimeSeries stores epoch deltas, we send the `first` as an optimization that read full record for `first` and then apply epoch deltas in the chunk to compute full entries for all intermediate epochs between from and to.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 10]
```diff
@@ -1442,6 +1465,10 @@ private TxnStatus handleDataNotFoundException(Throwable ex) {
         }).collect(Collectors.toList()));
     }
 
+    private int getShardNumber(long segmentId) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: @fpj 
There were two causes for `DataNotFoundException` while accessing `sealedSegmentSizesMapShard` 
1. getShardNumber was using `segmentNumber` instead of `epoch`
2. If shard was not present, because no segment mapped to the shard was sealed, we now return empty map. 

`1` was causing the existing unit test to fail (this was observed in travis build)
`2` was found through new targeted unit test.
