### PR TITLE
Issue 2773: Do not check for data availability in the stream locally

### LINKED ISSUE #2773: ArrayIndexOutOfBoundsException observed while reading from HDFS Tier2.
**Problem description**

When the reader tries to read from segment (`hulk/small/2.#epoch.0`)  the connection is dropped  due to a `java.lang.ArrayIndexOutOfBoundException` exception (shown below ) while fetching data from HDFS.  

After the configured number of failed retries the reader throws a `RetriesExhaustedException` to the user application.
```
2018-07-18 00:25:28,167 195170520 [storage-io-14] ERROR i.p.s.s.h.h.PravegaRequestProcessor - Error (Segment = 'hulk/small/2.#epoch.0', Operation = 'Read segment')
java.lang.ArrayIndexOutOfBoundsException: null
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.readInternal(HDFSStorage.java:643)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$read$1(HDFSStorage.java:211)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.read(HDFSStorage.java:210)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:180)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:135)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

```
Logs: 
[1091.zip](https://github.com/pravega/pravega/files/2212428/1091.zip)

**Problem location**
Segmentstore.

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by arvindkandhare**
**Change log description**
HDFS implementation checks for data availability locally in the read stream. This ensures that there is enough data available to read without blocking.
The idea is that in case multiple reads are in process the threads are not blocked. This fails in case of longevity runs where data may not be cached ever after multiple calls. At that point it makes sense to block for the read to happen.

**Purpose of the change**
Fixes #2773.

**What the code does**
Removes the availability check on the run.

**How to verify it**
ArrayOutOfBoundsException is not observed.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java [hunk 1]
```diff
@@ -41,6 +42,8 @@
             return new StreamSegmentNotExistsException(segmentName, e);
         } else if (e instanceof FileAlreadyExistsException) {
             return new StreamSegmentExistsException(segmentName, e);
+        } else if (e instanceof EOFException) {
+            throw new ArrayIndexOutOfBoundsException(segmentName);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: This is an odd exception to throw in the case there is no more data to be read. I'd think that the goal of `convertException` is to convert low-level exceptions into a `StreamSegment*` exception that is meaningful to the segment store, otherwise I don't know why we would be doing this.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 2]
```diff
@@ -639,9 +639,6 @@ private int readInternal(SegmentHandle handle, byte[] buffer, long offset, int b
         //There is only one file per segment.
         FileStatus currentFile = findStatusForSegment(handle.getSegmentName(), true);
         try (FSDataInputStream stream = this.fileSystem.open(currentFile.getPath())) {
-            if (offset + length > stream.available()) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: From this removed code, it looks like `FSDataInputStream.available()` was incorrectly interpreted as the total amount of data available in the file, and it isn't according to this documentation:

https://docs.oracle.com/javase/8/docs/api/java/io/FilterInputStream.html?is-external=true#available--

I think removing is the right thing to do.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java (hunk 1 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: This is following the contract at: https://github.com/pravega/pravega/blob/9bcfb22965933c50d5c22d55fb6ebd03482fc49c/segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ReadOnlyStorage.java#L58. But it definitely looks sketchy. If you think this needs change, will create another issue for it.

Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: @fpj is right. The contract says it will throw that exception if the given buffer and bufferOffset & length are incorrect. It does not say anything about the file itself.

I disagree with blindly converting EOFExceptions into ArrayIndexOutOfBoundsExceptions. EOFExceptions can occur because we try to read beyond the end of an InputStream, which generally mean there's a bug somewhere else in our code. It will be almost impossible to pinpoint the source of the problem if all we see in the logs is an ArrayIndexOutOfBoundsException

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 3]
```diff
@@ -639,9 +639,6 @@ private int readInternal(SegmentHandle handle, byte[] buffer, long offset, int b
...
-                throw new ArrayIndexOutOfBoundsException();
-            }
             stream.readFully(offset, buffer, bufferOffset, length);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Maybe add a catch for EOFException here, log it as debug/trace and then simply return. The contract of `SyncStorage` indicates this method should return the number of bytes read, which is less than or equal to `length`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: @arvindkandhare The contract you should be looking at is `SyncStorage`, not `ReadOnlyStorage`, as this is what this class implements.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 4]
```diff
@@ -639,10 +640,9 @@ private int readInternal(SegmentHandle handle, byte[] buffer, long offset, int b
...
+        } catch (EOFException e) {
+            throw new IllegalArgumentException(String.format("Reading at offset (%d) which is beyond the current size of segment.", offset));
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This is not what I asked...

Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: 1. It does not make sense to just consume an error in upper layers and return lesser number of bytes.
2. This is what other tier-2 impls do. It makes sense to keep the behavior similar.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 5]
```diff
@@ -639,10 +640,9 @@ private int readInternal(SegmentHandle handle, byte[] buffer, long offset, int b
         //There is only one file per segment.
         FileStatus currentFile = findStatusForSegment(handle.getSegmentName(), true);
         try (FSDataInputStream stream = this.fileSystem.open(currentFile.getPath())) {
-            if (offset + length > stream.available()) {
-                throw new ArrayIndexOutOfBoundsException();
-            }
             stream.readFully(offset, buffer, bufferOffset, length);
+        } catch (EOFException e) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: `readInternal` is called from `read`. if we throw here, then this exception is going to bubble up. we should be unit testing this behavior of the `read` call for the case that the offset is beyond the end of the file.

Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This case covers this scenario: https://github.com/pravega/pravega/blob/76124d152ec77510970006d1b6b4d1a4a7a317c6/segmentstore/storage/src/test/java/io/pravega/segmentstore/storage/StorageTestBase.java#L216
