### PR TITLE
Issue 1582: Update reader's error handling to handle failure to connect to Pravega node.

### LINKED ISSUE #1582: Reader's handling of errors while establishing connection to a pravega node.
**Problem description**
This issue was observed during the failover test MultiReaderWriterWithFailOverTest
Retry in AsyncSegmentInputStreamImpl should ensure the `ClientConnection` is closed  incase of an errors while establishing connection to the pravega node. This will ensure that when a retry happens the readers reconnects to the pravega node after fetch the endpoint uri from the controller.

Details: from the logs:
Around `11:28:58,285` was when netty callback indicating Connection exception was received and the `connection` was set to null due to this call back. The next getURI was @ `11:28:59,274`. This returned successfully. But the fact is that it retured stale data since the rebalance of segment containers happend 10 seconds later i.e. at `11:29:08`. So now `connection` is not null and hence the retries completed immediately. i.e the connection now points to a SSS server which does not exist.  From the client end we need to ensure that retries re-establish a connection to the SSS.

```
2017-07-12 11:28:59,274 154831 [pool-5-thread-3] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@5288661612631 [testMultiReaderWriterScope14363406/testMultiReaderWriterStream/2].
2017-07-12 11:28:59,280 154837 [grpc-default-executor-2] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE getEndpointForSegment@5288661612631 (elapsed=5522us).
2017-07-12 11:29:08,300 475602 [Curator-LeaderSelector-0] INFO  i.p.c.store.host.ZKHostStore - Successfully updated segment container map
```

**Problem location**
AsyncSegmentInputStreamImpl.java
**Suggestions for an improvement**
Fix the handling of retries in AsyncSegmentInputStreamImpl.

Logs:
[multireaderwriterwithfailovertest.zip](https://github.com/pravega/pravega/files/1147844/multireaderwriterwithfailovertest.zip)

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
AsyncSegmentInputStreamImpl closes ClientConnection in case of error based on the `ReplyProcessor` call backs.  It performs retries in case of exceptions during
* Fetching SegmentEndpoint from controller
* Establishing a connection to pravega node.
* Sending a read for the segment.

This change ensures we close the connection in case of error while establishing connection to pravega node, so that in the next retry we try to re-establish the connection to the pravega node (obtained from the controller)

**Purpose of the change**
Fixes #1582 

**What the code does**
Close the connection in case of errors while establishing connection to pravega node.

**How to verify it**
System tests should pass.
Update: With this change MultiReaderWriterWithFailOverTest passed on my jarvis cluster.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java [hunk 1]
```diff
@@ -23,16 +23,17 @@
 import io.pravega.shared.protocol.netty.PravegaNodeUri;
 import io.pravega.shared.protocol.netty.WireCommands;
 import io.pravega.shared.protocol.netty.WireCommands.SegmentRead;
+import lombok.SneakyThrows;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: Please configure your IDE to put imports in alphabetical order to prevent unneeded extra diffs like this.

Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: ok.
