### PR TITLE
Issue 5510: Create RG fails if Scope for the ReaderGroup does not have the readerGroupsInScope Table

### LINKED ISSUE #5510: Test failures in RestoreBackUpDataRecoveryTest and admin CLI DataRecoveryTest
**Problem description**
The tests in the `RestoreBackUpDataRecoveryTest` (integration tests) and `DataRecoveryTest` (CLI admin tests) classes are failing after applying the changes from PR #5439. Following is the stacktrace from one of the tests:
```
addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
	at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$exceptionalCallback$55(PravegaTablesStoreHelper.java:550)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.pravega.client.connection.impl.RawClient.reply(RawClient.java:126)
	at io.pravega.client.connection.impl.RawClient.access$300(RawClient.java:39)
	at io.pravega.client.connection.impl.RawClient$ResponseProcessor.process(RawClient.java:72)
	at io.pravega.client.connection.impl.FlowHandler.process(FlowHandler.java:204)
	at io.pravega.client.connection.impl.TcpClientConnection$ConnectionReader.run(TcpClientConnection.java:121)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
	at io.pravega.controller.server.SegmentHelper.lambda$updateTableEntries$13(SegmentHelper.java:419)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 8 more
```  

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
If we invoke createReaderGroup API on a Scope that was created before ReaderGroups were added to controller, this scope does not have the "readerGroupsInScope" table and hence addReaderGroupToScope() method fails with this exception:

```
addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
io.pravega.controller.store.stream.StoreException$DataNotFoundException: addNewEntry: key: RG557894633 table: _system/_tables/testMetricsScope/readerGroupsInScope.#.cc5db182-ee86-4171-ad91-59e8f3a421fe
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
. . .
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type UPDATE_TABLE_ENTRIES reason SegmentDoesNotExist
	at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:680)
```

This can happen if createScope() had completed only partially and the Controller crashed before creating the readerGroupsInScope table.

**Purpose of the change**  
Fixes #5510

**What the code does**  
1. Added a createTable() call in addReaderGroupToScope() which attempts to create the `ReaderGroupsInScope` Table if it does not exist. `createTable` is an idempotent and hence invoking it when the table already exists does not do any harm.
2. Added some other code improvements.
3. Fixed flaky test PravegaTablesStreamMetadataStoreTest.

**How to verify it**  
All unit and Integration tests should pass including Recovery related tests

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java [hunk 1]
```diff
@@ -218,7 +218,8 @@ public void refresh() {
 
     public CompletableFuture<Void> addReaderGroupToScope(String readerGroupName, UUID readerGroupId) {
         return getReaderGroupsInScopeTableName()
-                .thenCompose(tableName -> Futures.toVoid(storeHelper.addNewEntry(tableName, readerGroupName, getIdInBytes(readerGroupId))));
+                .thenCompose(tableName -> storeHelper.createTable(tableName).thenCompose(v ->
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java:221]: Is `createTable` an idempotent operation? 

Or will it go to the Segment Store and try to create a table, thus flooding it with create table requests which will fail most of the time. That will create unnecessary churn and logs.

Perhaps a better approach would be to add an exception handler (`Futures.exceptionallyComposeExpecting` ....) which creates the table and retries if it gets an exception that the table did not exist in the first place (i.e., optimistic approach).

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java:221]: `createTable` is an idempotent operation but it would hit the segment store as you suggested.
Will add it the `Futures.exceptionallyComposeExpecting` way.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java [hunk 2]
```diff
@@ -61,7 +61,7 @@ public UpdateReaderGroupTask(final StreamMetadataTasks streamMetaTasks,
         ImmutableSet<String> streamsToBeUnsubscribed = request.getRemoveStreams();
         final RGOperationContext context = streamMetadataStore.createRGContext(scope, readerGroup);
 
-        return RetryHelper.withRetriesAsync(() -> streamMetadataStore.getReaderGroupId(scope, readerGroup, context, executor)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java:64]: how is this change affecting the logic?

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteReaderGroupTask.java [hunk 3]
```diff
@@ -55,7 +55,7 @@ public DeleteReaderGroupTask(final StreamMetadataTasks streamMetaTasks,
       UUID readerGroupId = request.getReaderGroupId();
       long generation = request.getGeneration();
       final RGOperationContext context = streamMetadataStore.createRGContext(scope, readerGroup);
-      return streamMetadataStore.getReaderGroupId(scope, readerGroup, context, executor)
+      return streamMetadataStore.getReaderGroupId(scope, readerGroup)
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteReaderGroupTask.java:58]: why are we removing the context?

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/UpdateReaderGroupTask.java:64]: this is not affect the table creation in any way, just a code improvement.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteReaderGroupTask.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/DeleteReaderGroupTask.java:58]: getReaderGroupId() method does not use those parameters though they are being passed.

File: controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java]: fixed as suggested.

**Review by shiveshr — APPROVED** [review]
LGTM.

**Review by andreipaduroiu — APPROVED** [review]

**Comment by andreipaduroiu** [comment]
Build failure 

```
io.pravega.controller.store.stream.PravegaTablesStreamMetadataStoreTest > testReaderGroups FAILED

    java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: readerGroupRGTest table: _system/_tables/scopeRGTest/readerGroupsInScope.#.40cd0104-8bd9-428b-954d-3f11f0ec60d9

        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)

        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)

        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)

        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:

        io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: readerGroupRGTest table: _system/_tables/scopeRGTest/readerGroupsInScope.#.40cd0104-8bd9-428b-954d-3f11f0ec60d9

            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)

            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)

            at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$23(PravegaTablesStoreHelper.java:294)

            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)

            ... 7 more

```

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]
There is a build failure related to Reader Groups. Please investigate.

**Comment by pbelgundi** [comment]
> There is a build failure related to Reader Groups. Please investigate.

The check that gave this exception has been removed from this test in the last commit, so I don't see why we should see this exception here. 
I see that the last 2 travis builds completed successfully.

**Comment by pbelgundi** [comment]
> There is a build failure related to Reader Groups. Please investigate.

I have removed all calls from testReaderGroups() test case, that could possibly invoke `PravegTablesStoreHelper.getEntry()`, which is what throws this exact exception/error.
I don't see how/why we could possibly get this exception in this test case.

I'm able to reproduce this very intermittently locally ( about 1 in 10 times I run gradle tests and never in the IDE).
To unblock this PR for now, I will remove from the description that this fixes issue 5498, which is for fixing this flaky test and then continue investigation on this later.

**Review by andreipaduroiu — APPROVED** [review]
