### PR TITLE
Issue 3728: Fix for batch client auth issues

### LINKED ISSUE #3728: Batch client auth issues
**Problem description**
Batch client API calls encounter failure when Auth (authentication and authorization) is enabled. 

**Problem location**
See comments by @vijikarthi in https://github.com/pravega/pravega/issues/3296#issuecomment-475811508 for clues.

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Fixes the issue that was causing auth failures when using batch clients with auth-enabled Pravega cluster. 

**Purpose of the change**  
Fixes #3728. 

**What the code does**  
Here are the major changes:
* Main code: 
   - Fixes the issue by setting delegation token in the `ControllerServiceImpl.getSegmentsBetween()` method after authorization. 
   - Improves error logging (albeit slightly) in one place. The existing logged message can be misleading at times.
* Test code:
   - Rearranges the content of `io.pravega.test.integration.BatchClientTest` to allow for different security configurations to be set up by subclasses. 
   - Introduces a new subclass `io.pravega.test.integration.BatchClientWithAuthTest` of the `BatchClientTest`. It configures an auth-enabled environment and reuses the existing tests present in `BatchClientTest` to verify that batch clients work properly with auth-enabled. 
   - Introduces a new test helper class `PasswordAuthHandlerInput` to make it easier to generate and inject input file for the default AuthHandler - PasswordAuthHandler. 

**How to verify it**  
* All unit tests should pass.
* These integration tests in the following classes should pass: 
   - `io.pravega.test.integration.BatchClientWithAuthTest`
   - `io.pravega.test.integration.BatchClientTest`

**Additional Details:**

The root cause turned out to be missing delegation token, as shown below. 

```
2019-05-05 20:04:01,923 92884 [epollEventLoopGroup-6-7] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: /127.0.0.1:49114. Message was WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=274877906945, segmentName=basicTestScope/basicTestStream/0.#epoch.0, delegationToken=)
2019-05-05 20:04:01,923 92884 [epollEventLoopGroup-6-7] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=274877906945, segmentName=basicTestScope/basicTestStream/0.#epoch.0, delegationToken=)
2019-05-05 20:04:01,923 92884 [epollEventLoopGroup-6-7] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalArgumentException: JWT String argument cannot be null or empty.
	at io.jsonwebtoken.lang.Assert.hasText(Assert.java:135)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:479)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:36)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:207)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.getStreamSegmentInfo(PravegaRequestProcessor.java:400)
	at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.getStreamSegmentInfo(DelegatingRequestProcessor.java:60)
	at io.pravega.shared.protocol.netty.WireCommands$GetStreamSegmentInfo.process(WireCommands.java:966)
at 
```

### CODE REVIEW

File: test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+import java.io.FileWriter;
+import java.io.IOException;
+import java.util.Arrays;
+import java.util.List;
+
+/**
+ * This is a helper class for tests and may be used for generating the input file for the PasswordAuthHandler - the
+ * default AuthHandler implementation.
+ */
+public class PasswordAuthHandlerInput {
```
Comment (fpj) [inline test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java]: This class is currently used only in integration tests, and as such, there is no need to share. It also has the issue we discussed in the other PR that `test:common` is not the place for Pravega-specific classes.

I'd rather have it in `test:integration` for the time being.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 2]
```diff
@@ -223,7 +223,7 @@ public void getSegmentsBetween(Controller.StreamCutRange request, StreamObserver
         log.info("getSegmentsBetweenStreamCuts called for stream {} for cuts from {} to {}", request.getStreamInfo(), request.getFromMap(), request.getToMap());
         String scope = request.getStreamInfo().getScope();
         String stream = request.getStreamInfo().getStream();
-        authenticateExecuteAndProcessResults(() -> this.authHelper.checkAuthorization(
+        authenticateExecuteAndProcessResults(() -> this.authHelper.checkAuthorizationAndCreateToken(
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Some methods in this very same class invoke `checkAuthorization` (e.g., the method above with the typo in the name) while others invoke `check AuthorizationAndCreateToken`. I'm not sure what the criteria are for deciding what to call.

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+    protected ControllerWrapper createControllerWrapper() {
+        return new ControllerWrapper(zkTestServer.getConnectString(),
+                false, true,
+                controllerPort, serviceHost, servicePort, containerCount, -1,
+                true, PASSWORD_AUTHHANDLER_INPUT.getPath(), "secret");
+    }
+
+    @Test
+    @Override
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java]: Yes, creating these methods isn't necessary for automated runs. I added them here to have the flexibility of running them individually while debugging.

File: test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java (hunk 1 above)
Comment (ravisharda) [reply test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java]: I kept it here as I am aware of existing test classes other than integration tests that can benefit from it (`ControllerGrpcAuthFocusedTest` is a case in point). I have not updated those existing test classes right now, though. I was thinking we'll move it to the shared project later when we issue #3745. 
What do you say?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 2 above)
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: The former checks for authorization only, while the latter sets a delegation token apart from checking for authorization. The delegation token is used subsequently by the client when talking to the segment store.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 4]
```diff
@@ -445,7 +445,7 @@ public void getDelegationToken(StreamInfo request, StreamObserver<DelegationToke
                         logAndUntrackRequestTag(requestTag);
                         if (ex != null) {
                             Throwable cause = Exceptions.unwrap(ex);
-                            log.error("Controller api failed with error: ", ex);
+                            log.error("Controller api failed with error. " + ex.getMessage(), ex);
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: I've fixed it in the latest commit.

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (fpj) [reply test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java]: Are you planning on keeping or removing them? I'd say we remove them.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 2 above)
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: I get that basic behavior @ravisharda , that's not the point. Why do we need to create a token for some calls and others we don't ? What's different in the call path that makes one require the creation of a token while the other didn't?

Clearly this distinction is what caused the bug because whoever wrote this code did not make the right assessment on whether a token needed to be created or not. I'm asking for some explicit criteria so that we can perhaps review the calls in this very same class and others and validate that they are doing the right thing.

File: test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java (hunk 1 above)
Comment (fpj) [reply test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java]: Let's not abuse the exception. There is no need for this class to be here, and if there is a need to share it, which is not the case in this PR, let's do the work of enabling `shared:test`.

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java]: I've removed the overriding test methods in the latest commit.

File: test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java (hunk 1 above)
Comment (ravisharda) [reply test/testcommon/src/main/java/io/pravega/test/common/PasswordAuthHandlerInput.java]: :) Sure. As suggested, I've moved this class to the project `test:integration` under the package `io.pravega.test.integration.utils`. Hope that works.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 2 above)
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: I completely agree with you. 

As of now, I don't have a complete rule-set that governs whether to set the delegation token or not. I'd need to discover those rules through experimentation and document them. I'd propose that we write up a new Wiki document that details out the auth design, beyond the very high-level design information covered under [this](https://github.com/pravega/pravega/wiki/PDP-23:-Pravega-security----encryption-and-Role-Based-Access-Control) PDP. In that new document, we can cover both the high-level design as well as important rules like these. 

We can cover this separately as part of a different issue if you agree.

Comment (vijikarthi) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: I am not sure if the fix provided here addresses all the API calls of batch client in its entirety (for e.g., the deprecated APIs of `BatchClientFactoryImpl` class)?

File: test/integration/src/main/java/io/pravega/test/integration/utils/PasswordAuthHandlerInput.java [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+    public PasswordAuthHandlerInput(String fileName, String extension) {
+        try {
+            file = File.createTempFile(fileName, extension);
+        } catch (IOException e) {
+            throw new RuntimeException(e);
+        }
+    }
+
+    public void postEntry(Entry entry) {
+        postEntries(Arrays.asList(entry));
```
Comment (vijikarthi) [inline test/integration/src/main/java/io/pravega/test/integration/utils/PasswordAuthHandlerInput.java]: It is good to have a precondition to validate the `entry` for not being null

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java [hunk 6]
```diff
@@ -119,13 +121,42 @@ public void tearDown() throws Exception {
...
 
+    //region Factory methods that may be overridden by subclasses.
+
+    protected ServiceBuilder createServiceBuilder() {
+        return ServiceBuilder.newInMemoryBuilder(ServiceBuilderConfig.getDefaultConfig());
+    }
+
+    protected ControllerWrapper createControllerWrapper() {
+        return new ControllerWrapper(zkTestServer.getConnectString(),
+                false, true,
```
Comment (vijikarthi) [inline test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java]: A variable name explaining what those boolean values represents can be useful instead of passing `true` or `false`

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+
+/**
+ * The tests in this class are intended to verify whether Batch Client works with a Pravega cluster
+ * that has "Auth" (short for authentication and authorization) enabled.
+ *
+ * This class inherits the tests of the parent class. Some of the test methods of the parent are reproduced here as
+ * handles, to enable running an individual test interactively (for debugging purposes).
+ */
+public class BatchClientWithAuthTest extends BatchClientTest {
+
```
Comment (vijikarthi) [inline test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java]: Do we also have a test that includes both `Auth` and `TLS`?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 2 above)
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: @vijikarthi, there seems to be no deprecated API method in `BatchFactoryImpl` interface, There is indeed a deprecated API method in its implementation class `BatchClientFactoryImpl`. I'll verify it to check if works with auth enabled. Could you also specify if there are other batch client API methods that you suspect won't work with auth?

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java (hunk 7 above)
Comment (ravisharda) [reply test/integration/src/test/java/io/pravega/test/integration/BatchClientWithAuthTest.java]: We don't have a batch client test class that includes both `auth` and `TLS` or with only `TLS`. I just added one for `auth` in this PR. I didn't add test classes for TLS, as that change, although desirable, wouldn't be relevant for the current issue and PR. Or maybe it is: how do you know this will work in tandem with `TLS` otherwise. Just thinking out loud. 

What do you say?

File: test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java (hunk 6 above)
Comment (ravisharda) [reply test/integration/src/test/java/io/pravega/test/integration/BatchClientTest.java]: Since it is a simple argument (and not a complex condition/expression), IDE parameter name hints should be enough, assuming the parameter names are aptly-named - which, luckily is the case here as shown in the screenshot below.  

image

File: test/integration/src/main/java/io/pravega/test/integration/utils/PasswordAuthHandlerInput.java (hunk 5 above)
Comment (ravisharda) [reply test/integration/src/main/java/io/pravega/test/integration/utils/PasswordAuthHandlerInput.java]: Sure. I've pushed a new commit that checks arguments for this and other public methods of the class.

**Comment by ravisharda** [comment]
W.r.t. the comment below, please note that this PR is intended to fix only the auth issues specific to batch client API and not the condition that results in the exception below, which in turn shows up whenever auth is enabled, whether you use batch/regular client or even if you don't use any client. 

This exception showed up in my verification of this fix as well but didn't cause the batch client auth tests in class ` `io.pravega.test.integration.BatchClientWithAuthTest` to fail. Also, this exception shows up when running the standalone mode (without the batch client), as you pointed out: the regular client API continue to function properly despite this error. Not to say that the exception is not a problem (it certainly is), but rather that it is orthogonal to this issue and should be addressed separately. Issue #3296, which you have reopened, needs to be addressed for that issue. 

As for the Hadoop connector tests failing with the code in this PR, there might be a different reason for it. I'll need to investigate further.

> I took this branch and tested with Hadoop Connector to see if it resolves the issues mentioned in [#3296 (comment)](https://github.com/pravega/pravega/issues/3296#issuecomment-475811508) but I was still not able to run those secure test case. After that, I tried to run the standalone from this branch (`./gradlew startStandalone`) and I am seeing lot of these warnings.
> 
> ```
> 2019-05-07 16:31:39,766 11294 [grpc-default-executor-1] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
> io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
>         at io.grpc.Status.asRuntimeException(Status.java:530)
>         at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
>         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
>         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
>         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
>         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
>         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
>         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
>         at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
>         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
>         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
>         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
>         at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
>         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
>         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
>         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
>         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> ```

**Comment by ravisharda** [comment]
@vijikarthi After digging into the issue, I've found that the root cause for auth not working with Hadoop Connectors against a server built using the code from this PR is really a bug in Hadoop Connectors class `io.pravega.connectors.hadoop.SecurityHelper.prepareClientConfig()` method. 

Here's what I did to encounter the issue:
1. Configure Hadoop Connector to use auth, by setting the corresponding flag in `SetupUtils` class. 
2. Configure Pravega standalone mode to use auth. Start the server.
3. Run `io.pravega.connectors.hadoop.PravegaConnectorLocalJobITCase.testPravegaConnectorInput()` test. Target the test to run against the standalone mode server.
4. Observer the `auth` errors, especially the ones pertaining to scope/stream that the test creates. 

In the about scenario, the problem appears to be that when `PravegaInputFormat.getSplits()` invokes `io.pravega.connectors.hadoop.prepareClientConfig()`, the called method does not set the credentials properly and as a result, the Batch client API calls fail. If I modify the code inside the method to set the credentials properly, the test passes consistently. 

I believe we need to modify the respective code in Hadoop Connectors project to fix the auth issue encountered there, and that issue is orthogonal to the issue fixed by this PR. In this PR we are only addressing the auth issues specific to batch client API. 

Please take a look and let me know what you think.

**Comment by ravisharda** [comment]
The reason for Hadoop Connectors tests failing when auth (short for authentication and authorization) was enabled, turned out to be an invalid specification for auth method. The test succeeded against a server built using this PR branch, after the system property `pravega.client.auth.method` was changed from to `Basic` (from `Default`). 

I just pushed a new integration test that demonstrates how to configure client credentials via system properties (as opposed to supplying a DefaultCredentials Object to ClientConfig directly).  

https://github.com/pravega/pravega/blob/17e5dee8733b2e342be0cb8a15f2cf98d14a8ebe/test/integration/src/test/java/io/pravega/test/integration/BatchClientAuthTest.java#L82

**Comment by vijikarthi** [comment]
@ravisharda I took your branch and tested with Hadoop Connector by passing the security configuration as system properties. The authentication part worked but it failed on authorization. If I bypass the authorization verification it works properly with your branch. While debugging, I have noticed that the `BatchClientAuthTest` is not using the `SetupUtils` to load the in-memory Pravega cluster instead it is directly making use of `ControllerWrapper` class and it uses the password auth file which was created by the `BatchClientAuthTest::createAuthFile() which basically puts the user credential along with the ACL`. Is there any reason why we can't use `SetupUtils`?

**Comment by ravisharda** [comment]
> Just had one question specific to the timeouts, otherwise the changes look good and I have tested it with Hadoop connector integration test.

Since the client retries for ten times by default regardless of the error, it can take some time before the test encounters an error. [Issue 3653](https://github.com/pravega/pravega/issues/3653) covers this among other issues.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 8]
```diff
@@ -457,7 +457,7 @@ public void getDelegationToken(StreamInfo request, StreamObserver<DelegationToke
                         }
                     });
         } catch (Exception e) {
-            log.error("Controller api failed with authenticator error", e);
+            log.error(e.getMessage(), e);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: we dont need to print exception.message and full error stack both.
