### PR TITLE
Issue 1796: Have no such segment, nack outstanding writes and close the writer.

### LINKED ISSUE #1796: Write to aborted txn never returns
**Problem description**
I have come across a scenario in which a writer was stuck trying to complete the write of an event, but it couldn't because the txn had timed out and aborted. Specifically, here are the two consecutive appends of the same writer thread and the interleaving messages (this is from test case `MultiReaderTxnWriterWithFailoverTest`):
[test.log.zip](https://github.com/pravega/pravega/files/1253896/test.log.zip)

```
2017-08-26 16:45:25,799 11109 [MultiReaderTxnWriterWithFailoverTest-1] DEBUG i.p.t.s.MultiReaderTxnWriterWithFailoverTest - Writing event: 1303 into transaction: 775ba19a-5c2d-4f67-b6f1-aacb226c955c
2017-08-26 16:45:25,800 11110 [MultiReaderTxnWriterWithFailoverTest-1] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/2#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerID: d143d153-542b-4e29-aed1-c3b410daf23e
2017-08-26 16:45:25,800 11110 [MultiReaderTxnWriterWithFailoverTest-1] DEBUG i.p.common.util.ReusableFutureLatch - Running releaser now, runningThread:MultiReaderTxnWriterWithFailoverTest-1
2017-08-26 16:46:22,848 68158 [MultiReaderTxnWriterWithFailoverTest-1] TRACE i.p.c.s.i.SegmentOutputStreamImpl - Sending append request: Append(segment=testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/2#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerId=d143d153-542b-4e29-aed1-c3b410daf23e, eventNumber=1, eventCount=1, data=UnpooledHeapByteBuf(ridx: 0, widx: 82, cap: 82/82), expectedLength=null)
2017-08-26 16:46:22,849 68159 [MultiReaderTxnWriterWithFailoverTest-1] DEBUG i.p.t.s.MultiReaderTxnWriterWithFailoverTest - Writing event: 1307 into transaction: 775ba19a-5c2d-4f67-b6f1-aacb226c955c
```
Note that there was for some reason a 1-minute gap between the two writes, it is possible that there has been a failover even in the middle.

After that, I saw continuously the following pattern of messages:
```
2017-08-26 16:46:22,859 68169 [clientInternal-3] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - Running reconnect for segment:testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c writerID: 53abe18e-dfee-4209-b6c6-bef09cb07b0b
2017-08-26 16:46:22,859 68169 [clientInternal-3] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerID: 53abe18e-dfee-4209-b6c6-bef09cb07b0b
2017-08-26 16:46:22,859 68169 [clientInternal-3] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@5408355552528 [testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c].
2017-08-26 16:46:22,864 68174 [clientInternal-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.16.23.10, port=12345) for testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerID: 53abe18e-dfee-4209-b6c6-bef09cb07b0b
2017-08-26 16:46:22,866 68176 [epollEventLoopGroup-4-8] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.SetupAppend(type=SETUP_APPEND, requestId=2, writerId=53abe18e-dfee-4209-b6c6-bef09cb07b0b, segment=testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c)
2017-08-26 16:46:22,867 68177 [epollEventLoopGroup-4-8] TRACE i.p.s.protocol.netty.CommandDecoder - Decode a message on connection: 172.16.23.10/172.16.23.10:12345. Message was No such segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c
2017-08-26 16:46:22,867 68177 [epollEventLoopGroup-4-8] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.23.10 processing reply: No such segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c
2017-08-26 16:46:22,867 68177 [epollEventLoopGroup-4-8] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c failed due to: No such segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: No such segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c
Caused by: java.lang.IllegalArgumentException: No such segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c
2017-08-26 16:46:22,868 68178 [epollEventLoopGroup-4-8] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerID: 53abe18e-dfee-4209-b6c6-bef09cb07b0b
2017-08-26 16:46:22,868 68178 [epollEventLoopGroup-4-8] WARN  i.p.c.s.i.SegmentOutputStreamImpl - Connection for segment testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c failed due to: null
2017-08-26 16:46:22,868 68178 [epollEventLoopGroup-4-8] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testMultiReaderWriterTxnScope468184854/testMultiReaderWriterTxnStream/1#transaction.775ba19a5c2d4f67b6f1aacb226c955c, writerID: 53abe18e-dfee-4209-b6c6-bef09cb07b0b
```

Showing the writer trying to access the txn segment.

**Problem location**
Client writer.

**Suggestions for an improvement**
The writer should after some retries check whether the txn has aborted and error the operation accordingly.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
When the server sends no such segment back to a writer it should fail the in-flight requests and close the segment as it is never going to complete writing the data successfully.

**Purpose of the change**
Fixes #1796 

**What the code does**
* Handles no such segment by treating it as an unrecoverable state for the segment and nacking everything inflight.
* Have transaction verify that all their writes actually get acked before allowing a commit to be called.

**How to verify it**
* Added two new tests.
* The system tests using transactions should no longer see the issue mentioned in #1796

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java [hunk 1]
```diff
@@ -42,15 +83,22 @@ public UUID getId() {
...
         } catch (SegmentSealedException e) {
             throw new TxnFailedException(e);
         }
     }
 
     @Override
     public void close() throws TxnFailedException {
+        flush();
         try {
             out.close();
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: Based on the below two points I suspect that invoking `flush()` inside `close()` would cause an issue
- out.close() also invokes a flush internally. 
- also NoSuchSegment response would have closed the state of the SegmentOutputStreamImpl  --> hence out.close() will not invoke out.flush() if the state is closed.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: It's not an issue. I'm invoking the flush() here to get the logic above to execute in addition to the normal flushing. The idea being I don't want close() to complete successfully if one of the inflight events fails. Calling out.flush() twice which will occur in this case is a no-op as when there are no inflight events it just returns. Similarly if close() has already been invoked on the output stream, either from segment does not exist or something else it is a no-op and returns. So while flush() and close() may be called more than once, these operations are idempotent.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -297,7 +298,20 @@ public void segmentIsSealed(SegmentIsSealed segmentIsSealed) {
...
+            checkArgument(segmentName.equals(segment), "Wrong segment name %s, %s", segmentName, segment);
+            log.info("Segment being written to {} no longer exists failing all writes", segment);
+            state.setClosed(true);
+            ClientConnection connection = state.getConnection();
+            if (connection != null) {
+                connection.close();
+            }
+            for (PendingEvent toAck : state.removeInflightBelow(Long.MAX_VALUE)) {
+                if (toAck != null) {
+                    toAck.getAckFuture().completeExceptionally(new NoSuchSegmentException(segment));
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: done

File: client/src/main/java/io/pravega/client/segment/impl/NoSuchSegmentException.java [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.segment.impl;
+
+/**
+ * A segment does not exist and hence cannot be written to.
+ */
+public class NoSuchSegmentException extends IllegalStateException {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/NoSuchSegmentException.java]: I don't suppose there's a way we can unify this (and other client-side) exceptions with the ones used server-side?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 4]
```diff
@@ -297,7 +300,21 @@ public void segmentIsSealed(SegmentIsSealed segmentIsSealed) {
 
         @Override
         public void noSuchSegment(NoSuchSegment noSuchSegment) {
-            failConnection(new IllegalArgumentException(noSuchSegment.toString()));
+            String segment = noSuchSegment.getSegment();
+            checkArgument(segmentName.equals(segment), "Wrong segment name %s, %s", segmentName, segment);
+            log.info("Segment being written to {} no longer exists failing all writes", segment);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: add period or semicolon after `exists` and before `failing`

File: client/src/main/java/io/pravega/client/segment/impl/NoSuchSegmentException.java (hunk 3 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/NoSuchSegmentException.java]: We could put them in shared, but I don't want to do that in this PR because it is a non-trivial refactoring. I have filed https://github.com/pravega/pravega/issues/1840

File: client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java [hunk 5]
```diff
@@ -1,27 +1,37 @@
 /**
  * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
  *
- * Licensed under the Apache License, Version 2.0 (the "License");
- * you may not use this file except in compliance with the License.
- * You may obtain a copy of the License at
+ * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: Please revert these changes to license header.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java [hunk 6]
```diff
@@ -1,27 +1,37 @@
...
+ * in compliance with the License. You may obtain a copy of the License at
  *
- *     http://www.apache.org/licenses/LICENSE-2.0
+ * http://www.apache.org/licenses/LICENSE-2.0
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: Same here.

File: client/src/test/java/io/pravega/client/stream/impl/SegmentTransactionTest.java [hunk 7]
```diff
@@ -0,0 +1,64 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/SegmentTransactionTest.java]: Please revert back these changes to the license header format.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java [hunk 8]
```diff
@@ -42,15 +83,22 @@ public UUID getId() {
 
     @Override
     public void flush() throws TxnFailedException {
+        checkFailed();
         try {
             out.flush();
+            synchronized (lock) {
+                removeCompleted();
+                checkFailed();
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: `checkFailed` is inconsistently being invoked under a lock, see line 53.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 9]
```diff
@@ -657,4 +663,41 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
...
+        cf.setExecutor(executor);
+
+        MockController controller = new MockController(uri.getEndpoint(), uri.getPort(), cf);
+        ClientConnection connection = mock(ClientConnection.class);
+        cf.provideConnection(uri, connection);
+        SegmentOutputStreamImpl output = new SegmentOutputStreamImpl(SEGMENT, controller, cf, cid, segmentSealedCallback, RETRY_SCHEDULE);
+        output.reconnect();
+        verify(connection).send(new SetupAppend(1, cid, SEGMENT));
+
+        cf.getProcessor(uri).noSuchSegment(new NoSuchSegment(1, SEGMENT)); // simulate a connection dropped
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: This comment might be misleading. Calling `noSuchSegment` closes the connection:

https://github.com/pravega/pravega/pull/1811/files#diff-698633adec608f170863e75caed6297dR309

so it is a consequence of invoking `noSuchSegment`.  What this is really doing is simulating that the service is returning no such segment and that as a consequence we are closing the connection.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 10]
```diff
@@ -657,4 +663,41 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
...
+        cf.provideConnection(uri, connection);
+        output = new SegmentOutputStreamImpl(SEGMENT, controller, cf, cid, segmentSealedCallback, RETRY_SCHEDULE);
+        output.reconnect();
+        verify(connection).send(new SetupAppend(1, cid, SEGMENT));
+        cf.getProcessor(uri).appendSetup(new AppendSetup(1, SEGMENT, cid, 0));
+        CompletableFuture<Boolean> ack = new CompletableFuture<>();
+        output.write(new PendingEvent("RoutingKey", ByteBuffer.wrap(new byte[] { 1, 2, 3 }), ack));
+        assertFalse(ack.isDone());
+
+        cf.getProcessor(uri).noSuchSegment(new NoSuchSegment(1, SEGMENT)); // simulate a connection dropped
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: Same observation here about the comment.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java (hunk 8 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentTransactionImpl.java]: The lock is not needed. checkFailed uses txnFailedCause but it is an AtomicReference.

I cannot move this particular call outside the lock here because the precondition on the line below must be within the scope of the lock that performed removeCompleted() above and the checkfailed must occur between the two.
