### PR TITLE
Issue 6495: DataFrameReader does not allow to read a corrupted log in BookkeeperLog repair command

### LINKED ISSUE #6495: DataFrameReader does not allow to read a corrupted log in BookkeeperLog repair command
**Describe the bug**
BookkeeperLog Repair command contributed in #6413 uses the `DebugRecoveryProcessor` to read from logs and manipulate them. However, as this class is using `DataFrameReader` as a regular recovery, it is subject to the same preconditions. Thus, if we are manipulating a log that has a duplicate entry, we will not be able to create the backup log because `DataFrameReader` throws `DataCorruptionException` when finding a duplicate entry.

We need to allow these constraints to hold or not, depending on our needs from a CLI perspective.

**To Reproduce**
Try to repair a log with an actual data corruption.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by abhinb**
**Change log description**  
This PR contains the changes for fixing the usage of "data-recovery durableLog-repair" command to repair a DurableDataLog.

**Purpose of the change**  
Fixes #6495

**What the code does**  
The data-recovery durableLog-repair command , helps us to basically fix any inconsistencies by editing the entries in the underlying DurableDataLog(Bookkeeper log). One of the uses of this command could be to remove potential duplicate entries in the Bookkeeper log. This command uses the RecoveryProcessor to recover/read the operations from the Bookkeeper log. The RecoveryProcessor inturn uses the DataFrameReader to read entries from the BK log. This DataFrameReader does check for duplicate entries while reading and errors out in case they are encountered. This erroring out during the repair process using the "data-recovery durableLog-repair" command can foil the entire repair process.

As a fix, a DebugDataFrameReader is introduced that does not throw an exception if it finds duplicate entries from the BK log while reading, it just merely logs it. The "data-recovery durableLog-repair" command is configured to use this.

**How to verify it**  
New tests have been introduced to validate the funcionality.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java [hunk 1]
```diff
@@ -131,6 +141,66 @@ protected void recoverOperation(DataFrameRecord<Operation> dataFrameRecord, Oper
         }
     }
 
+    /**
+     * The ovverridden behaviour in this method is to choose between  using a DebugDataFrameReader and the regular DataFrameReader.
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:145]: Typo `ovverridden` -> overridden

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:145]: Unnecessary blank space in `between using`

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java [hunk 2]
```diff
@@ -131,6 +141,66 @@ protected void recoverOperation(DataFrameRecord<Operation> dataFrameRecord, Oper
...
+    protected int recoverAllOperations(OperationMetadataUpdater metadataUpdater) throws Exception {
+        int skippedOperationCount = 0;
+        int skippedDataFramesCount = 0;
+        int recoveredItemCount = 0;
+
+        // Read all entries from the DataFrameLog and append them to the InMemoryOperationLog.
+        // Also update metadata along the way.
+        DataFrameReader<Operation> reader = this.errorOnDataCorruption.get() ? new DataFrameReader<>(this.getDurableDataLog(), OperationSerializer.DEFAULT, this.getMetadata().getContainerId())
+                : new DebugDataFrameReader<>(this.getDurableDataLog(), OperationSerializer.DEFAULT, this.getMetadata().getContainerId());
+        try ( reader ) {
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:162]: Unnecessary spaces after and before `reader`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessorTests.java [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+     * the DataCorruptionException during the repair process, to help finish the repair.
+     * @throws Exception
+     */
+    @Test
+    public void testRecoveryWithDataCorruption() throws Exception {
+
+        ArrayList<Operation> records = new ArrayList<>();
+        StreamSegmentTruncateOperation tro = new StreamSegmentTruncateOperation(12, 12345);
+        tro.setSequenceNumber(2);
+        //insert duplicates
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessorTests.java:68]: Comments go with `//` + space + start in capitals.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessorTests.java [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+        records.add(tro);
+        records.add(tro);
+
+        //append the duplicate reocrds to the DurableDataLog
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessorTests.java:72]: Same here.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugDataFrameReader.java [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+                    if (!this.getDataFrameInputStream().beginRecord()) {
+                        // We've reached the end of the DataFrameInputStream.
+                        return null;
+                    }
+                    // Attempt to deserialize the next record. If the serialization was bad, this will throw an exception which we'll pass along.
+                    T logItem = this.getSerializer().deserialize(this.getDataFrameInputStream());
+                    DataFrameRecord.RecordInfo recordInfo = this.getDataFrameInputStream().endRecord();
+                    long seqNo = logItem.getSequenceNumber();
+                    if (seqNo <= this.getLastReadSequenceNumber()) {
+                        log.error("Invalid Operation Sequence Number. Expected: larger than {}, found: {}.",
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugDataFrameReader.java:54]: I thin this should be using an `if` and `else` block. If we find a duplicate, we log the error and that's it, we just discard the item read. In the case it is not duplicate, then we return the dataframe. See this https://github.com/RaulGracia/pravega/commit/b763701221e00620042c5fd63d1f6f7fe9bab63a

**Review by RaulGracia — CHANGES_REQUESTED** [review]
In general looks good, I have some minor comments.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java [hunk 6]
```diff
@@ -131,6 +141,66 @@ protected void recoverOperation(DataFrameRecord<Operation> dataFrameRecord, Oper
...
+    /**
+     * The overridden behaviour in this method is to choose between  using a DebugDataFrameReader and the regular DataFrameReader.
+     * The DebugDataFrameReader does not throw exception on finding duplicate entries in the DurableDataLog, which could be used by
+     * repair commands in Admin CLI to fix corrupted log with duplicate entries.
+     * @param metadataUpdater The OperationMetadataUpdater to use for updates.
+     * @return  the number of operations recovered.
+     * @throws Exception any other exception other than DataCorruptionException
+     */
+    @Override
+    protected int recoverAllOperations(OperationMetadataUpdater metadataUpdater) throws Exception {
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:153]: Question: why do we need this? If the `DebugDataFrameReader` has been tweaked to be able to tolerate reading operations with wrong sequence numbers, do we really need to modify this? Or the only purpose of overriding this is just to use `DebugDataFrameReader` instead of `DataFrameReader`? If so, maybe we can isolate the `DataFrameReader` instantiation and reuse the rest of the method implementation inheriting from `DataFrameReader`, right?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java [hunk 7]
```diff
@@ -131,6 +141,66 @@ protected void recoverOperation(DataFrameRecord<Operation> dataFrameRecord, Oper
         }
     }
 
+    /**
+     * The overridden behaviour in this method is to choose between  using a DebugDataFrameReader and the regular DataFrameReader.
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:145]: Extra space in `between using`.

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java (hunk 6 above)
Comment (abhinb) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:153]: this was done to mostly keep the changes localized in "DebugRecoveryProcessor", and not touching "RecoveryProcessor".. But can as well do as you said to abstract out the creation of FrameReader which would induce minimal changes.

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java:153]: Correct, just re-use the rest of this method and only override the instantiation of either `DataFrameBuilder` or `DebugDataFrameBuilder`. Note that in the case of `DebugDataFrameBuilder` we should still be able to choose whether we want to tolerate inconsistent operation numbers or not, as you are doing now.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java (hunk 7 above)
Comment (abhinb) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DebugRecoveryProcessor.java]: this will be removed based on above comment

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java [hunk 8]
```diff
@@ -203,7 +217,7 @@ protected void recoverOperation(DataFrameRecord<Operation> dataFrameRecord, Oper
         }
     }
 
-    private void recordTruncationMarker(DataFrameRecord<Operation> dataFrameRecord) {
+    protected void recordTruncationMarker(DataFrameRecord<Operation> dataFrameRecord) {
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java:220]: Why is this change needed?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java [hunk 9]
```diff
@@ -127,15 +132,15 @@ public int performRecovery() throws Exception {
...
+    protected int recoverAllOperations(OperationMetadataUpdater metadataUpdater) throws Exception {
         long traceId = LoggerHelpers.traceEnterWithContext(log, this.traceObjectId, "recoverAllOperations");
         int skippedOperationCount = 0;
         int skippedDataFramesCount = 0;
         int recoveredItemCount = 0;
 
         // Read all entries from the DataFrameLog and append them to the InMemoryOperationLog.
         // Also update metadata along the way.
-        try (DataFrameReader<Operation> reader = new DataFrameReader<>(this.durableDataLog, OperationSerializer.DEFAULT, this.metadata.getContainerId())) {
+        try (DataFrameReader<Operation> reader = createDataFrameReader()) {
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java:143]: Good.

**Review by RaulGracia — APPROVED** [review]
LGTM, just one minor comment before we can merge.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java (hunk 8 above)
Comment (abhinb) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/RecoveryProcessor.java]: leftover from previous change which is removed now. wil revert this.
