### PR TITLE
Issue 1779: Improve log quality

### LINKED ISSUE #1779: Log noise on shutdown
**Problem description**
When the client is shutdown, there are a lot of spurious exceptions related to the fact that the thread poll is shutdown.

**Problem location**
ConnectionFactoryImpl

**Suggestions for an improvement**
If when the connection factory's thread pool is shutdown, it could use a caller runs policy to allow for a graceful shutdown.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
Improve logging and avoid spurious exceptions, especially related to shutting down the client.

**Purpose of the change**
Fixes #1779
Improves the quality of messages logged.

**What the code does**
* Adds some logging. 
* Prevents some spurious stack traces from being logged.
* Switches the client to use a caller-runs rejection strategy for when the threadpool is shutdown.

**How to verify it**
There should be no impact. All tests should pass.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java [hunk 1]
```diff
@@ -32,21 +34,39 @@
  */
 public final class ExecutorServiceHelpers {
     
+    
+    /**
+     * Creates an returns a thread factory that will create threads with the given name prefix.
```
Comment (fpj) [inline common/src/main/java/io/pravega/common/concurrent/ExecutorServiceHelpers.java]: Typo: "Creates and returns..."
