### PR TITLE
Issue 2659: Fix segment read bytes metric issue

### LINKED ISSUE #2659: Wrong (too low) segment_read_bytes metrics
**Problem description**
For streams with one reader group of tail reader the calculated read byte rates are always lower than write byte rates. 
Looking at the `segment_read_bytes` counter emitted by the segment stores (top chart), we can see that it is much lower than the `segment_write_bytes` counter (bottom_chart):
tiny_read_bytes
tiny_write_bytes

These two charts are for a stream with one segment and a fixed number of segments.
The reader clients report that they read the same amount of bytes as was written by writer clients (and reported by `segment_write_bytes` metrics counter). 
The problem is only with `segment_read_bytes`  metrics.

**Problem location**
Segment store, `segment_read_bytes` metrics

**Suggestions for an improvement**
Segment stores should report correct `segment_read_bytes` metrics

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
*  Increases the `segment_read_bytes` metric counter value in the `handleReadResult` method, rather than from `readResult` length. 

**Purpose of the change**
Fixes #2659 

**What the code does**
*  Increases the `segment_read_bytes` metric counter value in the `handleReadResult` method, rather than from `readResult` length. 

**How to verify it**
`segment_ready_bytes`  should be reported correctly and match with `segment_write_bytes` in a period of time.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 1]
```diff
@@ -237,6 +239,7 @@ private void handleReadResult(ReadSegment request, ReadResult result) {
                     })
                     .exceptionally(e -> handleException(nonCachedEntry.getStreamSegmentOffset(), segment, "Read segment", e));
         }
+
```
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: remove this line please

Comment (Prabha-Veerubhotla) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: done.
