### PR TITLE
Issue 7194: Add timeout to SetupAppend and Provide initial delay option to retry

### LINKED ISSUE #7194: Add timeout to setupAppend and initial delay to reconnect method
**Describe the bug**
Similar to #7133 Here Write() is blocking client to write further.

Problem location
SegmentOutputStreamImpl

Suggestions for an improvement

- Add a timeout to the future 
- Add initial delay to reconnect

### PR DESCRIPTION
**Pull request by a6dulaleem**
**Change log description**  
This PR Basically doing these two thing 

- Adds a timeout (default 30sec) to setting up a connection
- Provide a initial delay option to retry class

**Purpose of the change**  
Fixes #7194 

**What the code does**  
Adds a new timeout as part of the client configuration and triggers a reconnect if a connection cannot be setup within this time.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -99,6 +102,22 @@ class SegmentOutputStreamImpl implements SegmentOutputStream {
     @Getter
     private final long requestId = Flow.create().asLong();
 
+    SegmentOutputStreamImpl(String segmentName, boolean useConnectionPooling, Controller controller, ConnectionPool connectionPool, UUID writerId, Consumer<Segment> resendToSuccessorsCallback, RetryWithBackoff retrySchedule, DelegationTokenProvider tokenProvider) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java:105]: If one of these is for unit tests please annotate it with @VisableForTesting.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -656,13 +678,22 @@ void reconnect() {
                               state.failConnection(e1);
                               throw Exceptions.sneakyThrow(e1);
                           }
+                          // A timeout is added to the future before the call, and it triggers a TimeoutException.
+                          // A late timeout if fine it will just cause a spurious connection close.
+                          // A late success may be a problem because it causes retransmits of the wrong messages.
+                          // In theory the server should guard against this, but that's not ideal to depend on for client correctness.
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java:684]: This relates to the to 540 above. With this change we should be able to update the code there to fail the connection. Please make that change similar to the reverted PR and have the comments here and there cross reference one other.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 3]
```diff
@@ -86,6 +87,7 @@ public class SegmentOutputStreamTest extends LeakDetectorTestSuite {
     private static final String SEGMENT = "test/0";
     private static final String TXN_SEGMENT = "scope/stream/0.#epoch.0#transaction.00000000000000000000000000000001";
     private static final int SERVICE_PORT = 12345;
+    private static final int WAIT_TILL_RECONNECT_NOT_DONE = 50;
```
Comment (tkaitchuck) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java:90]: We shouldn't be doing sleep in unit tests. Let's either run with an inline executor and zeroed delayes so we can get determinism or use AssertEventuallyEquals

**Review by tkaitchuck — CHANGES_REQUESTED** [review]

**Review by tkaitchuck — APPROVED** [review]

**Review by abhinb — APPROVED** [review]
