### PR TITLE
Issue 5481: DR Integration test Flaky

### LINKED ISSUE #5481: Test failure: RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking
**Problem description**
1st stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.lang.IllegalStateException: The number of back-up metadata segments and containers should match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.pravega.segmentstore.server.containers.ContainerRecoveryUtils.updateCoreAttributes(ContainerRecoveryUtils.java:310)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:684
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)
```
2nd stack trace:
```
io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking FAILED
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
        at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking(RestoreBackUpDataRecoveryTest.java:778)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
            at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
            at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.close(BookKeeperLog.java:181)
            at io.pravega.segmentstore.server.logs.DurableLog.lambda$doStop$5(DurableLog.java:249)
            at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
            at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
            at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Problem location**
`RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryWatermarking`

**Suggestions for an improvement**
Test should pass reliably.

### LINKED ISSUE #5512: Test failure: RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryTransactionalWriter
**Problem description**
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.stopDebugSegmentContainersPostFlush(RestoreBackUpDataRecoveryTest.java:541)
	at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.runRecovery(RestoreBackUpDataRecoveryTest.java:687)
	at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testRecovery(RestoreBackUpDataRecoveryTest.java:492)
	at io.pravega.test.integration.RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryTransactionalWriter(RestoreBackUpDataRecoveryTest.java:436)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2086)
	at io.pravega.segmentstore.storage.impl.bookkeeper.Write.fail(Write.java:199)
	at io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLog.lambda$close$1(BookKeeperLog.java:181)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

```
Caused by: java.util.concurrent.CompletionException: io.pravega.segmentstore.contracts.StreamSegmentTruncatedException: [Segment '_system/containers/metadata_0$attributes.index'] Offsets 0-1000 have been deleted.
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:194)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 common frames omitted
Caused by: io.pravega.segmentstore.contracts.StreamSegmentTruncatedException: [Segment '_system/containers/metadata_0$attributes.index'] Offsets 0-1000 have been deleted.
	at io.pravega.segmentstore.storage.rolling.RollingStorage.checkTruncatedSegment(RollingStorage.java:814)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:197)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$read$8(AsyncStorageWrapper.java:131)
	at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:192)
	... 7 common frames omitted
Caused by: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment '_system/containers/metadata_0$attributes.index$offset.0'] The StreamSegment does not exist.
	at io.pravega.segmentstore.storage.mocks.InMemoryStorage.getStreamSegmentData(InMemoryStorage.java:238)
	at io.pravega.segmentstore.storage.mocks.InMemoryStorage.openRead(InMemoryStorage.java:116)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.read(RollingStorage.java:189)
```

**Problem location**
`RestoreBackUpDataRecoveryTest.testDurableDataLogFailRecoveryTransactionalWriter`

**Suggestions for an improvement**
Test should pass reliably.

### PR DESCRIPTION
**Pull request by ManishKumarKeshri**
**Change log description**  
- Removed redundant closing of the containers. 
- Increased cache size. 
- Increased number of segments. 
- Removed FlushToStorage after recovery, as it is not required here, as the container metadata segment exists in the durable log. The purpose of the test is to restore the durable log. 

**Purpose of the change**  
Fixes #5512 
Fixes #5481 

**What the code does**  
Fixes flakiness in DR tests. 

**How to verify it**  
Tests should pass reliably.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 1]
```diff
@@ -307,8 +307,9 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
                                             ExecutorService executorService,
                                             Duration timeout) throws InterruptedException, ExecutionException,
             TimeoutException {
-        Preconditions.checkState(backUpMetadataSegments.size() == containersMap.size(), "The number of " +
-                "back-up metadata segments and containers should match.");
+        Preconditions.checkNotNull(backUpMetadataSegments, "Back up metadata segments");
+        Preconditions.checkState(backUpMetadataSegments.size() <= containersMap.size(), "The number of " +
+                "back-up metadata segments should be less or equal to the number of debug segment containers.");
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:312]: sometimes not all container metadata segments exist in the storage, so their back ups are not created. So, "==" check failed. 
In case `backUpMetadataSegments` is empty, this would still pass, and update attributes will happen.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 2]
```diff
@@ -538,7 +538,6 @@ private void stopDebugSegmentContainersPostFlush(int containerCount, Map<Integer
             throws Exception {
         for (int containerId = 0; containerId < containerCount; containerId++) {
             debugStreamSegmentContainerMap.get(containerId).flushToStorage(TIMEOUT).join();
-            Services.stopAsync(debugStreamSegmentContainerMap.get(containerId), executorService()).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);
             debugStreamSegmentContainerMap.get(containerId).close();
```
Comment (ManishKumarKeshri) [inline test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:541]: I think it's redundant to use both `stopAsync` and `close`.

**Comment by ManishKumarKeshri** [comment]
@sachin-j-joshi and @andreipaduroiu If you can review, that would be great. Thanks.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 3]
```diff
@@ -307,8 +307,7 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
                                             ExecutorService executorService,
                                             Duration timeout) throws InterruptedException, ExecutionException,
             TimeoutException {
-        Preconditions.checkState(backUpMetadataSegments.size() == containersMap.size(), "The number of " +
-                "back-up metadata segments and containers should match.");
+        Preconditions.checkNotNull(backUpMetadataSegments, "Back up metadata segments");
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:310]: sometimes there are not all container metadata segments present in the LTS, so their back up copies didn't get created, and so the test failed. I think just the `notNull` check is sufficient.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 4]
```diff
@@ -364,6 +364,7 @@ public void testDataRecoveryContainerLevel() throws Exception {
                 opFutures.add(container.updateAttributes(segmentName, attributeUpdates, TIMEOUT));
             }
         }
+        Futures.allOf(opFutures).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:367]: On reviewing, I found that this was missed.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 5]
```diff
@@ -147,7 +147,7 @@
     private static final ContainerConfig CONTAINER_CONFIG = ContainerConfig
             .builder()
             .with(ContainerConfig.SEGMENT_METADATA_EXPIRATION_SECONDS, (int) DEFAULT_CONFIG.getSegmentMetadataExpiration().getSeconds())
-            .with(ContainerConfig.MAX_ACTIVE_SEGMENT_COUNT, 100)
+            .with(ContainerConfig.MAX_ACTIVE_SEGMENT_COUNT, 1000)
```
Comment (ManishKumarKeshri) [inline test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:150]: Once it failed due to lack of segments.

File: test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java [hunk 6]
```diff
@@ -534,11 +534,9 @@ private void createBookKeeperLogFactory(PravegaRunner pravegaRunner) throws Dura
 
     // Closes the debug segment container instances in the given map after waiting for the metadata segment to be flushed to
     // the given storage.
-    private void stopDebugSegmentContainersPostFlush(int containerCount, Map<Integer, DebugStreamSegmentContainer> debugStreamSegmentContainerMap)
+    private void stopDebugSegmentContainers(int containerCount, Map<Integer, DebugStreamSegmentContainer> debugStreamSegmentContainerMap)
             throws Exception {
         for (int containerId = 0; containerId < containerCount; containerId++) {
-            debugStreamSegmentContainerMap.get(containerId).flushToStorage(TIMEOUT).join();
```
Comment (ManishKumarKeshri) [inline test/integration/src/test/java/io/pravega/test/integration/RestoreBackUpDataRecoveryTest.java:540]: FlushToStorage is not required here.

File: cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/DurableLogRecoveryCommand.java [hunk 7]
```diff
@@ -174,7 +174,6 @@ private void flushToStorage(Map<Integer, DebugStreamSegmentContainer> debugStrea
     private void stopDebugSegmentContainers(Map<Integer, DebugStreamSegmentContainer> debugStreamSegmentContainerMap)
             throws Exception {
         for (val debugSegmentContainerEntry : debugStreamSegmentContainerMap.entrySet()) {
-            Services.stopAsync(debugSegmentContainerEntry.getValue(), executorService).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);
```
Comment (ManishKumarKeshri) [inline cli/admin/src/main/java/io/pravega/cli/admin/dataRecovery/DurableLogRecoveryCommand.java:177]: As you can see [here](https://github.com/pravega/pravega/issues/5481#issuecomment-762972854), the test sometimes fails at this line. 
Further down, we already close the debug segment containers, so this line is not required. So, removing it.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java [hunk 8]
```diff
@@ -428,7 +428,7 @@ public static void updateCoreAttributes(Map<Integer, String> backUpMetadataSegme
         for (int containerId = 0; containerId < containerCount; containerId++) {
             String backUpMetadataSegment = NameUtils.getMetadataSegmentName(containerId) + fileSuffix;
             String backUpAttributeSegment = NameUtils.getAttributeSegmentName(backUpMetadataSegment);
-            log.debug("Created '{}' as a back of metadata segment of container Id '{}'", backUpAttributeSegment, containerId);
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerRecoveryUtils.java:431]: This was a mistake that is fixed.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java [hunk 9]
```diff
@@ -507,7 +509,7 @@ public static TestContext createContext(ScheduledExecutorService scheduledExecut
         TestContext(ScheduledExecutorService scheduledExecutorService) {
             this.storageFactory = new InMemoryStorageFactory(scheduledExecutorService);
             this.dataLogFactory = new InMemoryDurableDataLogFactory(MAX_DATA_LOG_APPEND_SIZE, scheduledExecutorService);
-            this.cacheStorage = new DirectMemoryCache(Integer.MAX_VALUE / 5);
```
Comment (ManishKumarKeshri) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:510]: Precondition mismatch only happens during io.pravega.test.integration.RestoreBackUpDataRecoveryTest > testDurableDataLogFailRecoveryWatermarking . This test is different from other tests in the way that we write more data (x2) here. I tried increasing the cache storage from `Integer.MAX_VALUE / 5`  to `Integer.MAX_VALUE` , tried running several times, and the issue has not been reproduced yet.

Comment (sachin-j-joshi) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:510]: Is this change really required ?

**Review by sachin-j-joshi — APPROVED** [review]
Looks good to me.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java (hunk 9 above)
Comment (ManishKumarKeshri) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/DebugStreamSegmentContainerTests.java:510]: It helped alleviate `CacheStorage` getting closed issue (which eventually causes Preconditions mismatch).

**Review by andreipaduroiu — APPROVED** [review]
