### PR TITLE
Issue 2052: Use rename to fix fencing issue.

### LINKED ISSUE #2052: HDFSStorage potential corruption due to zombie processes
**Problem description**
Suppose we have two instances of the `HDFSStorage` for the same Container, one with epoch A and one with epoch B = A+1, each running on different hosts. Call them HA and HB. HA and HB should never run concurrently if we do a graceful container failover, however it is possible that they are both running at the same time, and writing to the same Segments, if HA's host loses connection to ZK/BK and still thinks it's the leader for the Container. In that case, both HA and HB will be competing to modify the same Segment, thus leading to issues. 

Most of these issues are resolved using the fencing mechanism built into `HDFSStorage`. However, there is a case that is not handled:
1. HA has an ongoing write to Segment X.
2. While the write is happening, HB open-writes Segment X, which causes the last file of X to be marked as read-only, and after that, its length is retrieved.
3. HA completes the write to Segment X, altering it (and increasing its length) after it was marked as read-only.
4. HB now has the wrong information about the state of Segment X, because one of the files has been modified behind the scenes without it knowing about.

This can lead to a number of issues. See **Example Problematic Stack Traces** below for observed issues.

**Problem location**
HDFSStorage.java

**Suggestions for an improvement**
This is due to the fact that setting permissions in HDFS is not atomic, or even serializable with other writes. They can happen concurrently and any permission change will not affect ongoing writes.

We need to make `FileSystemOperation.makeReadOnly` provide a guarantee that, after its successful completion, the target file will never change. This means it should be able to wait for ongoing writes, if possible. Note that due to the fact that there is no known server-side feature to support this, any solution may not work well in a general case, but it should solve the use case that the Segment Store is concerned about (on each Container there is a single StorageWriter accessing a Segment, and we can only solve this for two SegmentContainer zombie instances competing for the same Segment).
1. We introduce a new XAttr named "WritingInProgress"
2. During a write, we set this XAttr (to `true`) on the target file right before we are about to open the write stream, and clear it when we're done (whether successfully or not).
3. `makeReadOnly` will check for this XAttr's existence after it marks the file as read-only. If it's set, it will need to wait until it's cleared (or a timeout expires).

This should make`makeReadOnly` provide enough guarantees that the file will not change after it returns successfully and the rest of the HDFS fencing code in the SegmentStore should work as expected.

**Example Problematic Stack Traces**
```
java.util.concurrent.CompletionException: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.HadoopIllegalArgumentException): concat: source file /Segment_1000_3 is invalid or empty or underConstruction
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.verifySrcFiles(FSDirConcatOp.java:160)
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.concat(FSDirConcatOp.java:68)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.concat(FSNamesystem.java:1855)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.concat(NameNodeRpcServer.java:983)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.concat(ClientNamenodeProtocolServerSideTranslatorPB.java:579)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:105)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.HadoopIllegalArgumentException): concat: source file /Segment_1000_3 is invalid or empty or underConstruction
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.verifySrcFiles(FSDirConcatOp.java:160)
	at org.apache.hadoop.hdfs.server.namenode.FSDirConcatOp.concat(FSDirConcatOp.java:68)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.concat(FSNamesystem.java:1855)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.concat(NameNodeRpcServer.java:983)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.concat(ClientNamenodeProtocolServerSideTranslatorPB.java:579)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.hdfs.DistributedFileSystem.concat(DistributedFileSystem.java:676)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest$FileSystemFixer.concat(HDFSStorageTest.java:217)
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.combine(FileSystemOperation.java:196)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.cleanup(OpenWriteOperation.java:140)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:123)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)


java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.impl.hdfs.SegmentFilesCorruptedException: Segment 'Segment' has invalid file 'hdfs://localhost:36964/Segment_1000_4'. Declared offset is '1000' but should be '2000'.
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:110)
Caused by: io.pravega.segmentstore.storage.impl.hdfs.SegmentFilesCorruptedException: Segment 'Segment' has invalid file 'hdfs://localhost:36964/Segment_1000_4'. Declared offset is '1000' but should be '2000'.
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.findAll(FileSystemOperation.java:113)
	at io.pravega.segmentstore.storage.impl.hdfs.FileSystemOperation.checkForFenceOut(FileSystemOperation.java:133)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:103)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)


java.util.concurrent.CompletionException: java.lang.AssertionError: New file list would not be contiguous. Combined file ends at offset 3000; Last file begins at 2000.
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorageTest.testZombies(HDFSStorageTest.java:110)
Caused by: java.lang.AssertionError: New file list would not be contiguous. Combined file ends at offset 3000; Last file begins at 2000.
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.cleanup(OpenWriteOperation.java:143)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.fenceOut(OpenWriteOperation.java:123)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:68)
	at io.pravega.segmentstore.storage.impl.hdfs.OpenWriteOperation.call(OpenWriteOperation.java:24)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$supplyAsync$1(HDFSStorage.java:233)
```

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
Use rename to fix fencing issue.
 Added test to test zombie fencing. This unit test is taken from #2058. Thanks @andreipaduroiu for the test. 

The segment is represented by a single file on HDFS. The file is renamed to `segmentName_<epoch>` each time fencing happens.

*Root cause of the issue*:
It is important that segment fencing depends on one of the atomic behavior of the tier-2 implementation. The current implementation does not actually fence out the old writers in some cases. 
Fencing should really mean that all the on-going operations on the file fail. Current implementation leaves a scenario out where an ongoing write succeeds even when fencing happens. This is because it depends on `setattr` to stop writes. This call is not atomic.

The solution:
This PR replaces the `openWrite` implementation with `rename` based implementation.
Here is more info about `rename` being atomic.

from: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/filesystem/introduction.html#Atomicity

```
There are some operations that MUST be atomic. This is because they are often used to implement locking/exclusive access between processes in a cluster.

Creating a file. If the overwrite parameter is false, the check and creation MUST be atomic.
Deleting a file.
Renaming a file.
Renaming a directory.
Creating a single directory with mkdir().
Recursive directory deletion MAY be atomic. Although HDFS offers atomic recursive directory deletion, none of the other Hadoop FileSystems offer such a guarantee (including local FileSystems).
Most other operations come with no requirements or guarantees of atomicity.

```

How the code fixes the current issue(#2052 ):
1. Ongoing writes:
In case of an ownership change, the file is renamed to the latest epoch. The ongoing writes will be ineffective as rename is atomic. (NB: The ongoing writes may continue and return success without the data getting updated. The call to `flush` or `hflush` fails. The failure happens only when call to `complete` happens.)

2. Fencing:
When the segment store with lower epoch tries to write fence the segment, it finds that an higher epoch already exists. In this case the segment store fails the `openWrite` call with `StorageNotPrimaryException`.

HDFS rename and write behavior:
There is some confusion about how HDFS rename works and is atomic. The important nuance to note here is that `write` calls to the stream received after calling `append` may not still throw exception. The exception is thrown when the writer tries to update the metadata at the name node through `complete` call. (`complete` may be called through `flush` or `hflush`. These calls are definitely called when `close` is called on the data stream).

Here is the entry point for HDFS rename:
https://github.com/apache/hadoop/blob/88fba00caa8c8e26f70deb9be5b534e7482620a1/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java#L992

Here is where the lock for the directory is taken:
https://github.com/apache/hadoop/blob/4c57fb0cd9344290a9f4f6422c1457d69465eec7/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java#L483

and here is where the lock is released:
https://github.com/apache/hadoop/blob/4c57fb0cd9344290a9f4f6422c1457d69465eec7/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSDirRenameOp.java#L487.

Now a competing `complete` enters here:
https://github.com/apache/hadoop/blob/88fba00caa8c8e26f70deb9be5b534e7482620a1/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeRpcServer.java#L924

The lock is checked here:
https://github.com/apache/hadoop/blob/ac0d402c6a3af784aa8bdceecf3293c30760346f/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java#L2660

So if there is an ongoing `rename`, this call blocks.
Rename replaces the inode and then the call fails with file not found exception.

 
**Purpose of the change**
Fixes #2052

Reintroduces `rename` as a fix for the issue with file chaining solution.

**What the code does**
Drops the file chaining implements and re-introduces `rename`.

**How to verify it**
Unit tests.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSSegmentHandle.java [hunk 1]
```diff
@@ -48,7 +47,7 @@
     private HDFSSegmentHandle(String segmentName, boolean readOnly, List<FileDescriptor> files) {
         this.segmentName = Exceptions.checkNotNullOrEmpty(segmentName, "segmentName");
         this.readOnly = readOnly;
-        this.files = Exceptions.checkNotNullOrEmpty(files, "files");
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSSegmentHandle.java]: We should get rid of `FileDescriptor`. If we only have one file, then make this a `String` (and put back the null check).

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 2]
```diff
@@ -11,74 +11,77 @@
...
  * </ul>
  * <p>
  * Example: Segment "foo" can have these files
  * <ol>
- * <li> foo_0_1: first file, contains data at offsets [0..1234), written during Container Epoch 1.
- * <li> foo_1234_2: data at offsets [1234..987632), written during Container Epoch 2.
- * <li> foo_987632_3: data at offsets [987632..10568949), written during Container Epoch 3.
- * <li> foo_10568949_4: data at offsets [10568949..current-length-of-segment), written during Container Epoch 4.
- * </ol>
+ * <li> foo_<epoc>: Segement file, owned by a segmentstore running under epoch 1.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: "epoch".

Please fix this everywhere.

Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: typo: "Segment"
"owned by a Segment Container running under epoch "epoch"

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 3]
```diff
@@ -11,74 +11,77 @@
...
+ * <li> foo_<MAX_LONG>: A sealed segment.
  * <p>
- * All but the last file is marked as 'read-only' (except if the segment is Sealed, in which case the last file too is
- * marked as 'read-only').
+ * When a container fails over and needs to reacquire ownership of a segment, it renames the segment file as foo_<current_epoc>.
+ * After creation of the file, the filename is checked again. If there exists any file with higher epoc, the current file is deleted
+ * and access is ceded to the later owner.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: "owner with highest epoch"

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 4]
```diff
@@ -11,74 +11,77 @@
...
 @Slf4j
 class HDFSStorage implements SyncStorage {
+    private static final String PART_SEPARATOR = "_";
+    private static final String NAME_FORMAT = "%s" + PART_SEPARATOR + "%s";
+    private static final String NUMBER_GLOB_REGEX = "[0-9]*";
+    private static final String EXAMPLE_NAME_FORMAT = String.format(NAME_FORMAT, "<segment-name>", "<epoch>");
+    private static final FsPermission READWRITE_PERMISSION = new FsPermission(FsAction.READ_WRITE, FsAction.NONE, FsAction.NONE);
+    private static final FsPermission READONLY_PERMISSION = new FsPermission(FsAction.READ, FsAction.READ, FsAction.READ);
+    private static final int MAX_ATTEMPT_COUNT = 3;
+    private static final long MAX_EPOC = Long.MAX_VALUE;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: epoch

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 5]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
             conf.set("dfs.client.block.write.replace-datanode-on-failure.policy", "NEVER");
         }
 
-        this.context = new FileSystemOperation.OperationContext(epoch, openFileSystem(conf), this.config);
+        this.context = new OperationContext(epoch, openFileSystem(conf), this.config);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Why do we still need `OperationContext`?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 6]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
         log.info("Initialized (HDFSHost = '{}', Epoch = {}).", this.config.getHdfsHostURL(), epoch);
     }
 
-    protected FileSystem openFileSystem(Configuration conf) throws IOException {
-        return FileSystem.get(conf);
+    @Override
+    public SegmentProperties getStreamSegmentInfo(String streamSegmentName) throws StreamSegmentException {
+        long traceId = LoggerHelpers.traceEnter(log, "getStreamSegmentInfo", streamSegmentName);
+        try {
+            return Retry.withExpBackoff( 1, 5, MAX_ATTEMPT_COUNT)
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Store this, all the way up to `run` (excluding it) in a final static variable in the class.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 7]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
     @Override
-    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
-        return call(new CreateOperation(streamSegmentName, this.context));
+    public boolean exists(String streamSegmentName) {
+        long traceId = LoggerHelpers.traceEnter(log, "exists", streamSegmentName);
+        FileStatus status;
+        try {
+            status = findStatusForSegment(streamSegmentName, false);
+        } catch (IOException e) {
+            return false;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Please add an explanation why you return `false` upon an exception.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 8]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+
+        if (offset < 0 || bufferOffset < 0 || length < 0 || buffer.length < bufferOffset + length) {
+            throw new ArrayIndexOutOfBoundsException(String.format(
+                    "Offset (%s) must be non-negative, and bufferOffset (%s) and length (%s) must be valid indices into buffer of size %s.",
+                    offset, bufferOffset, length, buffer.length));
+        }
+
+        Timer timer = new Timer();
+
+        try {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: put this into a final static variable

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 9]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+            return Retry.withExpBackoff(1, 5, MAX_ATTEMPT_COUNT)
+                        .retryingOn(FileNotFoundException.class)
+                        .throwingOn(IOException.class)
+                        .run(() -> {
+                            AtomicInteger totalBytesRead = new AtomicInteger();
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: have `readInternal` return an int which is the total bytes read, and get rid of this AtomicInteger

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 10]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+            HDFSExceptionHelpers.throwException(handle.getSegmentName(), e);
+        }
+
+        LoggerHelpers.traceLeave(log, "seal", traceId, handle);
     }
 
     @Override
     public void unseal(SegmentHandle handle) throws StreamSegmentException {
-        run(new UnsealOperation(asReadableHandle(handle), this.context));
+        try {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Add trace enter/leave

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 11]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+            HDFSExceptionHelpers.throwException(handle.getSegmentName(), e.getCause());
+        }
+        return -1;
     }
 
     @Override
-    public void write(SegmentHandle handle, long offset, InputStream data, int length) throws StreamSegmentException {
-        run(new WriteOperation(asWritableHandle(handle), offset, data, length, this.context));
+    public SegmentHandle openRead(String streamSegmentName) throws StreamSegmentException {
+        try {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: trace enter / leave

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 10 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: and in any other publicly visible method

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 12]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+
+            FileStatus sourceFile;
+            sourceFile = findStatusForSegment(sourceSegment, true);
+            Preconditions.checkState(isSealed(sourceFile.getPath()),
+                    "Cannot concat segment '%s' into '%s' because it is not sealed.", sourceSegment, target.getSegmentName());
+
+            // Concat source files into target and update the handle.
+            makeWrite(sourceFile);
+            this.context.fileSystem.concat(lastFile.getPath(), new Path[]{sourceFile.getPath()});
+            this.context.fileSystem.delete(sourceFile.getPath(), true);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Why is this needed?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 13]
```diff
@@ -136,52 +139,187 @@ public void initialize(long epoch) {
...
+
+            if (isSealed(lastFile.getPath())) {
+                throw new StreamSegmentSealedException(target.getSegmentName());
+            } else if (getEpoc(lastFile) > this.context.epoch) {
+                throw new StorageNotPrimaryException(target.getSegmentName());
+            } else if (lastFile.getLen() != offset) {
+                throw new BadOffsetException(target.getSegmentName(), lastFile.getLen(), offset);
+            }
+
+            FileStatus sourceFile;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: merge these into a single line

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 14]
```diff
@@ -196,65 +334,128 @@ public boolean supportsTruncation() {
...
+            if (getEpocFromPath(lastFile.getPath()) > this.context.epoch) {
+                throw new StorageNotPrimaryException(handle.getSegmentName());
+            }
+        } catch (IOException e) {
+            HDFSExceptionHelpers.throwException(handle.getSegmentName(), e);
+        }
+
+        Timer timer = new Timer();
+        try (FSDataOutputStream stream = this.context.fileSystem.append(lastFile.getPath())) {
+            if (offset != lastFile.getLen()) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: We do not have `lastFile` anymore. Let's remove all that `FileDescriptor` and `OperationContext` and make use of what we have. 

Also you will need to update some of these comments, which were tailored for the multi-file approach.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSSegmentHandle.java (hunk 1 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSSegmentHandle.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 2 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 3 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 4 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 5 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: We do not need this. Dropping the context.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 6 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 7 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 8 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 9 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 10 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 11 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 12 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Removed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 13 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 14 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

**Comment by arvindkandhare** [comment]
[Explore HDFS rename operation to fix HDFS fencing issue.](https://trello.com/c/GwQvdwTs/16-explore-hdfs-rename-operation-to-fix-hdfs-fencing-issue)

**Comment by arvindkandhare** [comment]
[Explore HDFS rename operation to fix HDFS fencing issue.](https://trello.com/c/GwQvdwTs/16-explore-hdfs-rename-operation-to-fix-hdfs-fencing-issue)

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 15]
```diff
@@ -196,86 +331,299 @@ public boolean supportsTruncation() {
...
+            return null;
         }
+
+        val result = Arrays.stream(rawFiles)
+                           .sorted(this::compareFileDescriptors)
+                           .collect(Collectors.toList());
+        return result.get(result.size() -1);
     }
 
+    @SneakyThrows(FileNameFormatException.class)
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 16]
```diff
@@ -196,86 +331,299 @@ public boolean supportsTruncation() {
...
+        assert segmentName != null && segmentName.length() > 0 : "segmentName must be non-null and non-empty";
+        assert epoch >= 0 : "epoch must be non-negative " + epoch;
+        return new Path(String.format(NAME_FORMAT, getPathPrefix(segmentName), epoch));
+    }
+
+    /**
+     * Gets the full HDFS path when sealed
+     */
+    Path getSealedFilePath(String segmentName) {
+        assert segmentName != null && segmentName.length() > 0 : "segmentName must be non-null and non-empty";
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 17]
```diff
@@ -196,86 +331,299 @@ public boolean supportsTruncation() {
...
+     */
+    private String getPathPrefix(String segmentName) {
+        return this.config.getHdfsRoot() + Path.SEPARATOR + segmentName;
+    }
+
+    /**
+     * Gets the full HDFS Path to a file for the given Segment, startOffset and epoch.
+     */
+    Path getFilePath(String segmentName, long epoch) {
+        assert segmentName != null && segmentName.length() > 0 : "segmentName must be non-null and non-empty";
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 18]
```diff
@@ -136,52 +145,178 @@ public void initialize(long epoch) {
...
 
     @Override
-    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
-        return call(new CreateOperation(streamSegmentName, this.context));
+    public boolean exists(String streamSegmentName) {
+        long traceId = LoggerHelpers.traceEnter(log, "exists", streamSegmentName);
+        FileStatus status;
+        try {
+            status = findStatusForSegment(streamSegmentName, false);
+        } catch (IOException e) {
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 19]
```diff
@@ -11,74 +11,83 @@
...
  * <p>
  * Example: Segment "foo" can have these files
  * <ol>
- * <li> foo_0_1: first file, contains data at offsets [0..1234), written during Container Epoch 1.
- * <li> foo_1234_2: data at offsets [1234..987632), written during Container Epoch 2.
- * <li> foo_987632_3: data at offsets [987632..10568949), written during Container Epoch 3.
- * <li> foo_10568949_4: data at offsets [10568949..current-length-of-segment), written during Container Epoch 4.
- * </ol>
+ * <li> foo_<epoch>: Segment file, owned by a segmentstore running under epoch "epoch".
+ * <li> foo_<MAX_LONG>: A sealed segment.
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed. Replaced with `sealed`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java [hunk 20]
```diff
@@ -30,26 +30,23 @@
      *
      * @param segmentName Name of the stream segment on which the exception occurs.
      * @param e           The exception to be translated.
-     * @return Nothing. This method always throws.
+     * @return  The exception to be thrown.
      */
-    static <T> T throwException(String segmentName, Throwable e) throws StreamSegmentException {
+    static <T> StreamSegmentException throwException(String segmentName, Throwable e) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: 1. This method has inconsistent behavior. If it's one of the expected exceptions, it returns a new exception. If not, it quietly re-throws the original exception. It should be either one or the other.
2. If you decide to actually translate the exceptions instead of re-throwing them, then:
    - You should rename this to `convertException`. It doesn't throw anything anymore.
    - You should update the Javadoc

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java [hunk 21]
```diff
@@ -30,26 +30,23 @@
...
+        StreamSegmentException retVal = null;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSExceptionHelpers.java]: What's the point of this?

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 22]
```diff
@@ -121,6 +216,154 @@ protected Storage createStorage() {
...
+
+            // Inexistent segment.
+            AssertExtensions.assertThrows(
+                    "GetInfo succeeded on missing segment.",
+                    s.getStreamSegmentInfo("non-existent", null),
+                    ex -> ex instanceof StreamSegmentNotExistsException);
+        }
+    }
+
+        private void validateProperties(String stage, String segmentName, SegmentProperties sp, long expectedLength, boolean expectedSealed) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: Indentation problem

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 23]
```diff
@@ -121,6 +216,154 @@ protected Storage createStorage() {
...
+            Assert.assertNotNull("No result from GetInfoOperation (" + stage + ").", sp);
+            Assert.assertEquals("Unexpected name (" + stage + ").", segmentName, sp.getName());
+            Assert.assertEquals("Unexpected length (" + stage + ").", expectedLength, sp.getLength());
+            Assert.assertEquals("Unexpected sealed status (" + stage + ").", expectedSealed, sp.isSealed());
+        }
+
+    /**
+     * Tests the ExistsOperation in various scenarios.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: What are the various scenarios?

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 24]
```diff
@@ -121,6 +216,154 @@ protected Storage createStorage() {
...
+        final int epoch = 1;
+        final int offset = 0;
+
+        String segmentName = "foo_open";
+        try (Storage s = createStorage()) {
+            s.initialize(DEFAULT_EPOCH);
+            createSegment(segmentName, s);
+
+            // Not exists.
+            Assert.assertFalse("Unexpected result for missing segment (no files).",
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: This can fit on one line

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 25]
```diff
@@ -11,74 +11,84 @@
...
 
 /**
  * Storage adapter for a backing HDFS Store which implements fencing using file-chaining strategy.
  * <p>
- * Each segment is a collection of ordered files, adopting the following pattern: {segment-name}_{start-offset}_{epoch}.
+ * Each segment is represented by one file, adopting the following pattern: {segment-name}_{epoch}.
  * <ul>
  * <li> {segment-name} is the name of the segment as used in the SegmentStore
- * <li> {start-offset} is the offset within the Segment of the first byte in this file.
  * <li> {epoch} is the Container Epoch which had ownership of that segment when that file was created.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This line is not accurate.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 26]
```diff
@@ -11,74 +11,84 @@
...
  * </ul>
  * <p>
  * Example: Segment "foo" can have these files
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: A segment can have only one file

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 27]
```diff
@@ -11,74 +11,84 @@
...
  * <ol>
- * <li> foo_0_1: first file, contains data at offsets [0..1234), written during Container Epoch 1.
- * <li> foo_1234_2: data at offsets [1234..987632), written during Container Epoch 2.
- * <li> foo_987632_3: data at offsets [987632..10568949), written during Container Epoch 3.
- * <li> foo_10568949_4: data at offsets [10568949..current-length-of-segment), written during Container Epoch 4.
- * </ol>
+ * <li> foo_<epoch>: Segment file, owned by a segmentstore running under epoch "epoch".
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: I asked you previously to correct the spelling of "segmentstore". It should be "Segment Store" throughout the codebase. Please fix this here and everywhere else it appears like that.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 28]
```diff
@@ -11,74 +11,84 @@
...
+ * <li> foo_sealed: A sealed segment.
  * <p>
- * All but the last file is marked as 'read-only' (except if the segment is Sealed, in which case the last file too is
- * marked as 'read-only').
+ * When a container fails over and needs to reacquire ownership of a segment, it renames the segment file as foo_<current_epoch>.
+ * After creation of the file, the filename is checked again. If there exists any file with higher epoc, the current file is deleted
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: I also asked you to fix "epoc" to "epoch".

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 29]
```diff
@@ -11,74 +11,84 @@
...
+    private static final String PART_SEPARATOR = "_";
+    private static final String NAME_FORMAT = "%s" + PART_SEPARATOR + "%s";
+    private static final String SEALED = "sealed";
+    private static final String NUMBER_GLOB_REGEX = "{" + "[0-9]*" + "," + SEALED + "}";
+    private static final String EXAMPLE_NAME_FORMAT = String.format(NAME_FORMAT, "<segment-name>", "<epoch>");
+    private static final FsPermission READWRITE_PERMISSION = new FsPermission(FsAction.READ_WRITE, FsAction.NONE, FsAction.NONE);
+    private static final FsPermission READONLY_PERMISSION = new FsPermission(FsAction.READ, FsAction.READ, FsAction.READ);
+    private static final int MAX_ATTEMPT_COUNT = 3;
+    private static final long MAX_EPOCH = Long.MAX_VALUE;
+
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Too many empty lines

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 30]
```diff
@@ -136,52 +146,174 @@ public void initialize(long epoch) {
...
-    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
-        return call(new CreateOperation(streamSegmentName, this.context));
+    public boolean exists(String streamSegmentName) {
+        long traceId = LoggerHelpers.traceEnter(log, "exists", streamSegmentName);
+        FileStatus status = null;
+        try {
+            status = findStatusForSegment(streamSegmentName, false);
+        } catch (IOException e) {
+            // HDFS could not find the file. Returning false.
+            log.info("Got exception checking if file exists", e);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: `log.warn`.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 31]
```diff
@@ -136,52 +146,174 @@ public void initialize(long epoch) {
...
+        }
     }
 
     @Override
     public void seal(SegmentHandle handle) throws StreamSegmentException {
-        run(new SealOperation(asWritableHandle(handle), this.context));
+        long traceId = LoggerHelpers.traceEnter(log, "seal", handle);
+        handle = asWritableHandle(handle);
+        try {
+            FileStatus lastHandleFile = findStatusForSegment(handle.getSegmentName(), true);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: The segment has only one file. Why `lastHandleFile`?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 32]
```diff
@@ -136,52 +146,174 @@ public void initialize(long epoch) {
...
     }
 
     @Override
     public void unseal(SegmentHandle handle) throws StreamSegmentException {
-        run(new UnsealOperation(asReadableHandle(handle), this.context));
+        long traceId = LoggerHelpers.traceEnter(log, "seal", handle);
+        try {
+            FileStatus status = findStatusForSegment(handle.getSegmentName(), true);
+            if (!isSealed(status.getPath())) {
+                throw new StorageNotPrimaryException(handle.getSegmentName());
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Why throw this kind of exception if the file is not sealed?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 33]
```diff
@@ -136,52 +146,174 @@ public void initialize(long epoch) {
...
+                this.fileSystem.rename(lastHandleFile.getPath(), sealedPath);
+            }
+        } catch (IOException e) {
+            throw HDFSExceptionHelpers.throwException(handle.getSegmentName(), e);
+        }
+        LoggerHelpers.traceLeave(log, "seal", traceId, handle);
     }
 
     @Override
     public void unseal(SegmentHandle handle) throws StreamSegmentException {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: I don't see a unit test for this method.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 34]
```diff
@@ -136,52 +146,174 @@ public void initialize(long epoch) {
...
+            } else if (fileStatus.getLen() != offset) {
+                throw new BadOffsetException(target.getSegmentName(), fileStatus.getLen(), offset);
+            }
+
+            FileStatus sourceFile = findStatusForSegment(sourceSegment, true);
+            Preconditions.checkState(isSealed(sourceFile.getPath()),
+                    "Cannot concat segment '%s' into '%s' because it is not sealed.", sourceSegment, target.getSegmentName());
+
+            // Concat source files into target and update the handle.
+            makeWrite(sourceFile);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Why?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 35]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
 
 
+
     @Override
-    public int read(SegmentHandle handle, long offset, byte[] buffer, int bufferOffset, int length) throws StreamSegmentException {
-        return call(new ReadOperation(asReadableHandle(handle), offset, buffer, bufferOffset, length, this.context));
+    public void write(SegmentHandle handle, long offset, InputStream data, int length) throws StreamSegmentException {
+        long traceId = LoggerHelpers.traceEnter(log, "write", handle, offset, length);
+        handle = asWritableHandle(handle);
+        FileStatus lastFile = null;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: No such thing as last file

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 36]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+
+        Timer timer = new Timer();
+        try (FSDataOutputStream stream = this.fileSystem.append(lastFile.getPath())) {
+            if (offset != lastFile.getLen()) {
+                // Do the handle offset validation here, after we open the file. We want to throw FileNotFoundException
+                // before we throw BadOffsetException.
+                throw new BadOffsetException(handle.getSegmentName(), lastFile.getLen(), offset);
+            } else if (stream.getPos() != offset) {
+                // Looks like the filesystem changed from underneath us. This could be our bug, but it could be something else.
+                // Update our knowledge of the filesystem and throw a BadOffsetException - this should cause upstream code
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This comment does not reflect what is going on in the code.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 37]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
 
     @Override
-    public SegmentProperties getStreamSegmentInfo(String streamSegmentName) throws StreamSegmentException {
-        return call(new GetInfoOperation(streamSegmentName, this.context));
+    public SegmentHandle openWrite(String streamSegmentName) throws StreamSegmentException {
+        long traceId = LoggerHelpers.traceEnter(log, "openWrite", streamSegmentName);
+        int fencedCount = 0;
+        do {
+            try {
+                FileStatus existingFiles = findStatusForSegment(streamSegmentName, true);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: there is more than one file?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 38]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+                    if (getEpocFromPath(existingFiles.getPath()) > this.epoch) {
+                        throw new StorageNotPrimaryException(streamSegmentName);
+                    }
+
+                    Path targetPath = getFilePath(streamSegmentName, this.epoch);
+                    if (!targetPath.equals(existingFiles.getPath())) {
+                        try {
+                            this.fileSystem.rename(existingFiles.getPath(), targetPath);
+                        } catch (FileNotFoundException e) {
+                            //This happens when more than one host is trying to fence and only one of the host goes through
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: There are two sentences in here. Please use punctuation and capitalization to reflect that.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 39]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+                    }
+                }
+                //Ensure that file exists
+                findStatusForSegment(streamSegmentName, true);
+                return HDFSSegmentHandle.write(streamSegmentName);
+            } catch (IOException e) {
+                throw HDFSExceptionHelpers.throwException(streamSegmentName, e);
+            }
+        } while (fencedCount < MAX_ATTEMPT_COUNT);
+        LoggerHelpers.traceLeave(log, "openWrite", traceId, epoch);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: What happens if fencedCount >= MAX_ATTEMPT_COUNT? Returning null is not part of the contract for this method.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 40]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
 
     @Override
-    @SneakyThrows(StreamSegmentException.class)
-    public boolean exists(String streamSegmentName) {
-        return call(new ExistsOperation(streamSegmentName, this.context));
-    }
+    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
+        long traceId = LoggerHelpers.traceEnter(log, "create", streamSegmentName);
+        // Create the segment using our own epoch.
+        FileStatus[] existingFiles = null;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Can there be more than one file?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 41]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+            existingFiles = findAllRaw(streamSegmentName);
+        } catch (IOException e) {
+            throw HDFSExceptionHelpers.throwException(streamSegmentName, e);
+        }
+        if (existingFiles != null && existingFiles.length > 0) {
+            // Segment already exists; don't bother with anything else.
+            throw HDFSExceptionHelpers.throwException(streamSegmentName, HDFSExceptionHelpers.segmentExistsException(streamSegmentName));
+        }
 
+        // Create the first file in the segment.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: There is only one file

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 42]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+        Path fullPath = getFilePath(streamSegmentName, this.epoch);
+        try {
+            // Create the file, and then immediately close the returned OutputStream, so that HDFS may properly create the file.
+            this.fileSystem.create(fullPath, READWRITE_PERMISSION, false, 0, this.config.getReplication(),
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: How do you handle races here in the case when two different hosts with different epochs both made it to this point and both create files with different epochs?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 43]
```diff
@@ -11,74 +11,84 @@
...
- * "foo_0_2". Then they will detect that there is more than one file, and the Container with epoch 1 will back out and
- * yield to the outcome of the Container with Epoch 2. A similar approach is taken for all other operations, with more
- * details in the code for each.
  */
 @Slf4j
 class HDFSStorage implements SyncStorage {
+    private static final String PART_SEPARATOR = "_";
+    private static final String NAME_FORMAT = "%s" + PART_SEPARATOR + "%s";
+    private static final String SEALED = "sealed";
+    private static final String NUMBER_GLOB_REGEX = "{" + "[0-9]*" + "," + SEALED + "}";
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Since you include `SEALED` this cannot be named `NUMBER`.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 44]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+
+    //endregion
+
+    //Region HDFS helper methods.
+
+    /**
+     * Gets an array (not necessarily ordered) of FileStatus objects currently available for the given Segment.
+     * These must be in the format specified by NAME_FORMAT (see EXAMPLE_NAME_FORMAT).
+     */
+    FileStatus[] findAllRaw(String segmentName) throws IOException {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Since this always returns 0 or 1 files, please change this so it doesn't return an array. Also fix the javadoc

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 45]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+     * Gets the full HDFS Path to a file for the given Segment, startOffset and epoch.
+     */
+    Path getFilePath(String segmentName, long epoch) {
+        Preconditions.checkState(segmentName != null && segmentName.length() > 0, "segmentName must be non-null and non-empty");
+        Preconditions.checkState(epoch >= 0, "epoch must be non-negative " + epoch);
+        return new Path(String.format(NAME_FORMAT, getPathPrefix(segmentName), epoch));
+    }
+
+    /**
+     * Gets the full HDFS path when sealed
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: period at the end

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 46]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+     */
+    Path getSealedFilePath(String segmentName) {
+        Preconditions.checkState(segmentName != null && segmentName.length() > 0, "segmentName must be non-null and non-empty");
+        return new Path(String.format(NAME_FORMAT, getPathPrefix(segmentName), SEALED));
+    }
+
+
+    /**
+     * Gets an ordered list of FileDescriptors currently available for the given Segment, and validates that they are consistent.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Are you sure?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 47]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
      *
-     * @param operation The function to execute.
-     * @param <R>       Return type of the operation.
-     * @return Instance of the return type of the operation.
+     * @param segmentName      The name of the Segment to retrieve for.
+     * @param enforceExistence If true, it will throw a FileNotFoundException if no files are found, otherwise an empty
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: "an empty list is returned" ???

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 48]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+        FileStatus[] rawFiles = findAllRaw(segmentName);
+        if (rawFiles == null || rawFiles.length == 0) {
+            if (enforceExistence) {
+                throw HDFSExceptionHelpers.segmentNotExistsException(segmentName);
+            }
+
+            return null;
+        }
+
+        val result = Arrays.stream(rawFiles)
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: findAllRaw returns a single file. No need for any of this here.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 49]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+                           .sorted(this::compareFileDescriptors)
+                           .collect(Collectors.toList());
+        return result.get(result.size() -1);
+    }
+
+    private int compareFileDescriptors(FileStatus f1, FileStatus f2) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: No more file descriptors

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 50]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
-            return operation.call();
-        } catch (Exception e) {
-            return throwException(e, operation);
+            return Long.compare(getEpoc(f1), getEpoc(f2));
+        } catch (FileNameFormatException e) {
+            throw new IllegalStateException(e);
         }
     }
 
+    private long getEpoc(FileStatus status) throws FileNameFormatException {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: getEpoc**h**

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 51]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+        return getEpocFromPath(status.getPath());
+    }
 
-    private <T> T throwException(Throwable e, FileSystemOperation<?> operation) throws StreamSegmentException {
-        String segmentName = operation.getTarget() instanceof SegmentHandle
-                ? ((SegmentHandle) operation.getTarget()).getSegmentName()
-                : operation.getTarget().toString();
-        return HDFSExceptionHelpers.throwException(segmentName, e);
+    private long getEpocFromPath(Path path) throws FileNameFormatException {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: getEpoc**h**FromPath

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 52]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+        String fileName = path.toString();
+        int pos2 = fileName.lastIndexOf(PART_SEPARATOR);
+        if (pos2 <= 0) {
+            throw new FileNameFormatException(fileName, "File must be in the following format: " + EXAMPLE_NAME_FORMAT);
+        }
+        if ( pos2 == fileName.length() - 1 || fileName.regionMatches(pos2 +1, SEALED, 0, SEALED.length()) ) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: space between `+` and `1`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 53]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
-    private HDFSSegmentHandle asWritableHandle(SegmentHandle handle) {
-        Preconditions.checkArgument(!handle.isReadOnly(), "handle must not be read-only.");
-        return asReadableHandle(handle);
+    boolean isReadOnly(FileStatus fs) {
+        return fs.getPermission().getUserAction() == FsAction.READ;
     }
 
     /**
-     * Casts the given handle as a HDFSSegmentHandle irrespective of its isReadOnly value.
+     * Makes the file represented by the given FileDescriptor read-only.
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: What FileDescriptor?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 54]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+    private int readInternal(SegmentHandle handle, byte[] buffer, long offset, int bufferOffset, int length) throws IOException {
+        //There is only one file per segment.
+        FileStatus currentFile = findStatusForSegment(handle.getSegmentName(), true);
+        int totalBytesRead = 0;
+        try (FSDataInputStream stream = this.fileSystem.open(currentFile.getPath())) {
+            if (offset + length > stream.available()) {
+                throw new ArrayIndexOutOfBoundsException();
+            }
+            stream.readFully(offset, buffer, bufferOffset + totalBytesRead, length);
+            totalBytesRead += length;
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: there is no need for `totalBytesRead` in this code

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 55]
```diff
@@ -196,86 +328,302 @@ public boolean supportsTruncation() {
...
+        } catch (EOFException ex) {
+            throw new IOException(
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: `EOFException` is an `IOException`. Do we need to re-throw?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 32 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: `SyncStorage.unseal` says to throw this exception when this Storage instance is no longer primary for this segment. It does not say anything about whether the file is already sealed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 56]
```diff
@@ -196,85 +326,309 @@ public boolean supportsTruncation() {
...
+
+        //If there is a race during creation, delete the file with epoch 0 and throw exception.
+        try {
+            status = findAllRaw(streamSegmentName);
+            if (status != null && status.length > 1) {
+                this.fileSystem.delete(fullPath, true);
+                throw new StreamSegmentExistsException(streamSegmentName);
+            }
+        } catch (IOException e) {
+            log.warn("Exception while deleting a file with epoc 0.", e);
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: epoch

Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 57]
```diff
@@ -196,85 +323,309 @@ public boolean supportsTruncation() {
...
+            log.debug("Created '{}'.", fullPath);
+        } catch (IOException e) {
+            throw HDFSExceptionHelpers.convertException(streamSegmentName, e);
+        }
 
+        //If there is a race during creation, delete the file with epoch 0 and throw exception.
+        try {
+            status = findAllRaw(streamSegmentName);
+            if (status != null && status.length > 1) {
+                this.fileSystem.delete(fullPath, true);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: There must be some property that we can use to justify why deleting this file is safe. I suspect that:
- The file is guaranteed to be empty because it has just been created
- No other server will use this file in any way

Independent of whether this is right or wrong, please expand the the comment to explain why it is safe to delete it.

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 58]
```diff
@@ -67,6 +84,84 @@ public void tearDown() {
...
+                currentHandle.set(newStorage.openWrite(segmentName).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS));
+            } catch (Exception ex) {
+                newStorage.close();
+                throw ex;
+            }
+
+            currentStorage.set(newStorage);
+            try {
+                appends.get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);
+                Assert.fail("Continuous appends on older epoch Adapter did not fail.");
```
Comment (fpj) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: I think this assertion is here only as a safety guard because in principle we should never get here, even in the case the that the appends incorrectly keep going (it is an infinite loop after all).

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 59]
```diff
@@ -11,74 +11,83 @@
...
+import org.apache.hadoop.fs.Path;
+import org.apache.hadoop.fs.permission.FsAction;
+import org.apache.hadoop.fs.permission.FsPermission;
+import org.apache.hadoop.io.IOUtils;
 
 /**
  * Storage adapter for a backing HDFS Store which implements fencing using file-chaining strategy.
  * <p>
- * Each segment is a collection of ordered files, adopting the following pattern: {segment-name}_{start-offset}_{epoch}.
+ * Each segment is represented by one file, adopting the following pattern: {segment-name}_{epoch}.
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: I'm not sure what `represented` means here. A file does not represent a segment, it contains the data of a segment, right? Alternative ways to rephrase this:
- `Each segment maps to one file in the file system`
- `Each segment has a single file in the file system that contains its data`
- `For each segment, there is exactly one file in the file system`

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 60]
```diff
@@ -67,6 +84,84 @@ public void tearDown() {
     }
 
     //region Fencing tests
+    /**
+     * A special case Fencing test that verifies the HDFSStorage fencing mechanism when the "fenced-out" instance keeps
```
Comment (fpj) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: Here is a possible re-write of this comment, please check whether it makes sense:

```
* A special test case of fencing to verify the behavior of HDFSStorage in the presence of an instance that has 
* been fenced out. This case verifies that any ongoing writes properly fail upon fencing. Specifically, we have a 
* fenced-out instance that keeps writing and we verify that the write fails once the the HDFS file is set to 
* read-only. The HDFS behavior is such in this case is that ongoing writes that execute before the rename 
* complete successfully.
```

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java [hunk 61]
```diff
@@ -121,6 +216,153 @@ protected Storage createStorage() {
...
+            // Not exists.
+            Assert.assertFalse("Unexpected result for missing segment (no files).", s.exists("nonexistent", null).join());
+        }
+    }
+
+    /**
+     * Tests a read scenario with no issues or failures.
+     */
+    @Test
+    public void testNormalRead() throws Exception {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: `testNormal***` is the standard nomenclature adopted throughout the codebase. If we change it here we'll need to change it everywhere for consistency sake, which I think is beyond the scope of this PR.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 62]
```diff
@@ -196,85 +323,309 @@ public boolean supportsTruncation() {
...
     @Override
-    @SneakyThrows(StreamSegmentException.class)
-    public boolean exists(String streamSegmentName) {
-        return call(new ExistsOperation(streamSegmentName, this.context));
-    }
+    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
+        // Creates a file with the lowest possible epoch (0).
+        // There is a possible race during create where more than one segmentstore may be trying to create a streamsegment.
+        // If one create is delayed till long time, it is possible that other segmentstore will be able to create the file with
+        // epoch (0) and then rename it to its owned version (segment_<epoch>).
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 63]
```diff
@@ -196,85 +323,309 @@ public boolean supportsTruncation() {
...
 
     @Override
-    @SneakyThrows(StreamSegmentException.class)
-    public boolean exists(String streamSegmentName) {
-        return call(new ExistsOperation(streamSegmentName, this.context));
-    }
+    public SegmentProperties create(String streamSegmentName) throws StreamSegmentException {
+        // Creates a file with the lowest possible epoch (0).
+        // There is a possible race during create where more than one segmentstore may be trying to create a streamsegment.
+        // If one create is delayed till long time, it is possible that other segmentstore will be able to create the file with
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed. Replaced.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 64]
```diff
@@ -196,85 +323,309 @@ public boolean supportsTruncation() {
...
+                        }
+                    }
+                }
+                //Ensure that file exists
+                findStatusForSegment(streamSegmentName, true);
+                return HDFSSegmentHandle.write(streamSegmentName);
+            } catch (IOException e) {
+                throw HDFSExceptionHelpers.convertException(streamSegmentName, e);
+            }
+        } while (fencedCount < MAX_ATTEMPT_COUNT);
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This will happen when all the hosts are trying to get the same file and the authoritative owner always ends up losing the race at each iteration. Both these events are very rare.
I'd like to fix this in `HDFSStorage` itself. Throwing this issue to the caller will complicate the caller design. Here is one proposed fix: If we set the var `MAX_ATTEMPT_COUNT` to a value far larger than the number of hosts then we are sure that the real owner never loses. My recommendation is to put this value to 500. How does this sound?

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java (hunk 58 above)
Comment (fpj) [reply segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: Ah, that's right, you can get here via the get timeout. Thanks for the clarification.

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java (hunk 61 above)
[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorageTest.java]: Ok, agreed that this is outside scope.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 64 above)
[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: > Both these events are very rare.

I agree, but major outages are often caused out of rare events.

> I'd like to fix this in HDFSStorage itself. Throwing this issue to the caller will complicate the caller design.

I agree.

> Here is one proposed fix: If we set the var MAX_ATTEMPT_COUNT to a value far larger than the number of hosts then we are sure that the real owner never loses. My recommendation is to put this value to 500. How does this sound?

I think this is making the implicit assumption that older owners will start first and consequently will exhaust their attempts first, but that's not necessarily true. A segment container owner might be elected and then say pause for arbitrarily long. A new owner can start first.

The property we need to preserve is the following:
- If an instance is the last designated owner of a segment container, then it needs to eventually succeed in the call to rename to a higher epoch.

Basically, if an instance has retried enough and still couldn't make it, then it shouldn't give up in the case it is the authoritative owner according to the controller. What needs to happen is that the instance needs to be able to go back and check that it is still the designated owner to determine whether it should keep retrying or give up. If I recall correctly, we don't have a way to check it from the segment store at the moment, which makes this difficult.

[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: If the new segmentstores (the owners with higher epochs) win the race, the older segmentstores leave the race. So in worst case, at least one segmentstore is out of the race. So at the max the correct owner needs to loop for number of hosts times before he wins the race. I think this loop is bounded and will succeed eventually.
In case of pausing segmentstores, as rename is atomic, change in ownership will fail any further operations on the segment.
Consider an example with 5 hosts. I think each host running the loop 5 times will ensure that the latest owner wins the race always.

[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: @arvindkandhare did you mean to elaborate on an example?

> Consider an example with 5 hosts.

It might actually be sufficient to walk through an example with 2 or 3 hosts. I'm still not sure how you guarantee this:

> So at the max the correct owner needs to loop for number of hosts times

[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Consider 3 hosts A,B,C with epochs 1,2 and 3. The segment name is "foo".The file is currently owned by epoch 0. (i.e. current file name is "foo_0").
Now in case of a race, all three would try to rename the file to "foo_1", "foo_2" and "foo_3". If rename to "foo_1" goes through, segment store 1 leaves the race as it gets the ownership.
So in case of race during rename, at least one segment store leaves the race as it is the owner. So in worst case the real onwer needs to loop for number of segmentstores in the race to win it eventually. Which can be generalized to total number of segmentstores.

[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Ok, got it. It sounds right that the number of attempts should be max number of segment store instances. We might need to optimize it when clusters grow large, but as a first approximation, it seems ok.

I think we re agreeing that the best approach would to set the maximum based on the size of the cluster rather than hardcoding a value? Again, if you want to do it separately, fine by me, but I'd like to have an issue to fix it once we agree what the right fix is.

[the remark this answers is not in the document]
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Here are the issues to track the issues coming out of this thread and offline discussions: #2501, #2503.

[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: I saw there was an issue (#2501) created for this. I disagree with this approach. The Tier2 adapter does not need to know any details above its layer, especially something that high such as "number of segment store instances. The segment store itself does not know that number either and couldn't care less about it. 

Trying to inject such a value into the Tier2 adapters would be really hard, and it would be even harder trying to keep it accurate. We can bring up and stop segment store instances at will.

I suggest you find a different solution to this problem.

[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: @andreipaduroiu please discuss it in the issue, not here.
