### PR TITLE
Issue 3715: replaced the non thread safe map with SimpleMeterRegistry

### LINKED ISSUE #3715: Sporadic failure in EndToEndStatsTest.testStatsCount
**Problem description**
Observed Travis failure in `EndToEndStatsTest` integration test:
```
io.pravega.test.integration.endtoendtest.EndToEndStatsTest > testStatsCount FAILED
    java.lang.NullPointerException
        at io.pravega.test.integration.endtoendtest.EndToEndStatsTest.testStatsCount(EndToEndStatsTest.java:117)
```

**Problem location**
`EndToEndStatsTest`

**Suggestions for an improvement**
Fix the test.

### PR DESCRIPTION
**Pull request by kevinhan88**
**Change log description**  
Replaced the non-thread safe map inside the TestStatsRecorder with solid SimpleMeterRegistry to fix the sporadic multi-threading failure.

**Purpose of the change**  
Fixes #3715 

**What the code does**  
1. Inside `EndToEndStatsTest.TestStatsRecorder`, replaces the non thread safe map with Micrometer `SimpleMeterRegistry`.
2. Use Micrometer API to retrieve counters, instead of the unsafe map get operation.
3. Added `SEGMENT_WRITE_BYTES` tests, in addition to the existing `SEGMENT_WRITE_EVENTS` tests.
4. Added a set to hold strong references to metric objects, to further consolidate the code for the most intensive runtime environment.

**How to verify it**  
Integration test should pass, no matter how many times it repeats.
(The old implementation usually fails after a few hundreds repeats)

### CODE REVIEW

File: test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java [hunk 1]
```diff
@@ -109,32 +115,39 @@ public void testStatsCount() throws Exception {
         EventStreamWriter<String> test = clientFactory.createEventWriter("test", new JavaSerializer<>(),
                 EventWriterConfig.builder().transactionTimeoutTime(10000).build());
 
+        String[] tags = segmentTags(StreamSegmentNameUtils.getQualifiedStreamSegmentName("test", "test", 0L));
+
         for (int i = 0; i < 10; i++) {
             test.writeEvent("test").get();
         }
-        assertEventuallyEquals(10, () -> statsRecorder.getSegments().get(StreamSegmentNameUtils.getQualifiedStreamSegmentName("test", "test", 0L)).get(), 2000);
+        assertEventuallyEquals(10, () -> (int) (statsRecorder.getRegistry().counter(SEGMENT_WRITE_EVENTS, tags).count()), 2000);
```
Comment (RaulGracia) [inline test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: Why the timeouts (last argument) in all the invocations to `assertEventuallyEquals` are different? A 1 or 2 seconds timeout seems reasonable for all the cases, right?

Comment (kevinhan88) [reply test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: @RaulGracia I repeated the test 517 times and finally triggered the problem. The bottom line is that HashMap is not thread safe, it shouldn't be used in a multiple thread env - and indeed the problem happened.

Yes 2 second for regular write assertion, but 10 seconds for transaction write to play it safe (I didn't set these 2 values but I'm ok with the values set).
For the additional Write Byte assertion I added, however, I give it 100ms max waiting instead of 2 second, because this assertion is after Write Event assertion, which should have already waited sufficient time.

Comment (RaulGracia) [reply test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: `HashMap` is not thread-safe, you are right, in the same way that the recently added `HashSet` is neither thread-safe (and you are not using synchronization), right? In the changes of this PR, I see that now there is no "removal" of elements from the `metrics` data structure, which may alleviate the problem. But note that if you had left the "remove" operation (or other update concurrent operations on that data structure), we may probably observe problems too.

Comment (kevinhan88) [reply test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: The strong reference place holder (HashSet) has no consumer hence no concurrent concern of it, however it doesn't hurt to synchronize it; also I changed the HashSet to LinkedList to improve the performance and reduce the memory footprint a bit.
I also changed the name "metrics" to "references" to emphasis it is a place holder, instead of a metrics registry, so there is no need to manage its life-cycle. (The test case will create about 10+ metrics objects, and all the objects will be released when tear down the test case)

**Comment by RaulGracia** [comment]
@kevinhan88 please, let's not change more the code and try to execute Travis and Jenkins build multiple times to verify that the original issue is not reproduced (the version before the last commit has been executed 5 times without errors).

**Comment by kevinhan88** [comment]
@RaulGracia I don't think running multiple Travis/Jenkins is sufficient to trigger this multi-threading issues. I set it up in IDE and the problem was only triggered after hundreds times of test case execution.

**Comment by kevinhan88** [comment]
I'd like to point out one more thing: in addition to fixing the multi-threading issue, I'm also trying to make this particular integration test to be as close to production as possible.
The original code uses a raw HashMap to store counters of metrics, and use map api (instead of metrics api) to access counters, which lost the point of testing, because it could only prove map api works, not metrics api.

**Comment by RaulGracia** [comment]
@kevinhan88 maybe I did not get my point across properly: the original issue (test failure) has been manifesting every few Travis/Jenkins builds (it does not need hundreds of executions). My point is: let's execute multiple times the Travis builds and the Jenkins builds to verify that the original issue is not reproduced again with the changes of this PR. Does it sound reasonable?

File: test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java [hunk 2]
```diff
@@ -109,32 +116,39 @@ public void testStatsCount() throws Exception {
...
 
     private static class TestStatsRecorder implements SegmentStatsRecorder {
+
         @Getter
-        HashMap<String, AtomicInteger> segments = new HashMap<>();
+        SimpleMeterRegistry registry = new SimpleMeterRegistry();
+
+        // A placeholder to keep strong references to metric objects, as caching is skipped in the test.
+        // Note Micrometer registry holds weak references only, so there is chance metric objects without strong references might be garbage collected.
+        private List<Meter> references = Collections.synchronizedList(new LinkedList<Meter>());
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: Please use ArrayList not linked list.

Comment (kevinhan88) [reply test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndStatsTest.java]: fixed

**Comment by RaulGracia** [comment]
@tkaitchuck do you have more comments for this PR?
