### PR TITLE
Issue 2944: Sporadic failure HDFSIntegration.testendtoend

### LINKED ISSUE #2944: Sporadic failure in HDFSIntegrationTest.testEndToEnd
**Problem description**
The test works fine until it executes truncation on segments:
```
2018-09-14 03:45:56,497 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(156)) - Starting Phase 1.
2018-09-14 03:46:01,059 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(162)) - Created Segments: Segment_0, Segment_1, Segment_2, Segment_3, Segment_4, Segment_5, Segment_6, Segment_7, Segment_8, Segment_9.
2018-09-14 03:46:03,057 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(164)) - Created Transactions: Segment_7#transaction.29c6cb6b1dfe4069851e16f3fa201473, Segment_6#transaction.d29023d9a13e455eb2b9b858d0d7fb1c, Segment_5#transaction.92c583a7f14f461d88c4360393feaf00, Segment_4#transaction.4bd5821c20b34740923bf72174e622e4, Segment_9#transaction.253ec8faafc841c7b224a384b6a77612, Segment_8#transaction.409c9e7530614f76af4c6b2d9435f06f, Segment_3#transaction.f760ffdb0a7d4c40aea80738587bc1d8, Segment_2#transaction.e150208b7cb348ca8574010b0719a829, Segment_1#transaction.f97b4b40692a44cfa7d1822f5749aeaa, Segment_0#transaction.3b46345bc1724b5fa9399473316c50b3.
2018-09-14 03:46:04,557 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(170)) - Finished appending data.
2018-09-14 03:46:04,562 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(173)) - Finished Phase 1

2018-09-14 03:46:06,429 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(177)) - Starting Phase 2.
2018-09-14 03:46:07,310 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(182)) - Finished checking reads.
2018-09-14 03:46:08,135 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(186)) - Finished merging transactions.
2018-09-14 03:46:08,137 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(189)) - Finished Phase 2.

2018-09-14 03:46:09,099 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(193)) - Starting Phase 3.
2018-09-14 03:46:10,639 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(200)) - Finished checking reads.
2018-09-14 03:46:17,739 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(205)) - Finished waiting for segments in Storage.
2018-09-14 03:46:18,422 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(208)) - Finished Storage check.
2018-09-14 03:46:18,816 INFO  [Test worker] store.StreamSegmentStoreTestBase (StreamSegmentStoreTestBase.java:testEndToEnd(211)) - Finished checking reads while truncating.
```

After executing `checkReadsWhileTruncating`, there are no more outputs from `HDFSIntegrationTest.testEndToEnd` test, which suggests that the failure appeared when attempting to read `Segment_0` after performing truncation operations at `checkStorage`:

```
io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0$offset.0'] The StreamSegment does not exist.
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSExceptionHelpers.convertException(HDFSExceptionHelpers.java:41)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.getStreamSegmentInfo(HDFSStorage.java:169)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.openHandle(RollingStorage.java:665)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.openRead(RollingStorage.java:124)
    at io.pravega.segmentstore.storage.rolling.RollingStorage.getStreamSegmentInfo(RollingStorage.java:209)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$getStreamSegmentInfo$9(AsyncStorageWrapper.java:140)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.execute(AsyncStorageWrapper.java:221)
    at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$supplyAsync$13(AsyncStorageWrapper.java:181)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Segment_0$offset.0
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSExceptionHelpers.segmentNotExistsException(HDFSExceptionHelpers.java:68)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.findStatusForSegment(HDFSStorage.java:564)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.lambda$getStreamSegmentInfo$0(HDFSStorage.java:160)
    at io.pravega.common.util.Retry$RetryAndThrowBase.run(Retry.java:173)
    at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.getStreamSegmentInfo(HDFSStorage.java:159)
    ... 14 more
```

I compared the lifecycle of that segment in the failed test and the previous passing one, and they look the same:
**Passed Test**
```
2018-09-10 05:01:59,905 INFO  [IPC Server handler 5 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=create    src=/Segment_0$offset.0_0    dst=null    perm=root:supergroup:rw-------    proto=rpc
2018-09-10 05:01:59,948 INFO  [IPC Server handler 3 on 51757] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0$offset.0_0 is closed by DFSClient_NONMAPREDUCE_1179879432_3687
2018-09-10 05:02:00,657 INFO  [IPC Server handler 4 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_0    dst=/Segment_0$offset.0_1    perm=root:supergroup:rw-------    proto=rpc
2018-09-10 05:02:00,661 INFO  [IPC Server handler 6 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=append    src=/Segment_0$offset.0_1    dst=null    perm=null    proto=rpc
2018-09-10 05:02:00,691 INFO  [IPC Server handler 4 on 51757] hdfs.StateChange (FSDirWriteFileOp.java:logAllocatedBlock(725)) - BLOCK* allocate blk_1073741897_1103, replicas=127.0.0.1:40475 for /Segment_0$offset.0_1
2018-09-10 05:02:00,745 INFO  [IPC Server handler 4 on 51757] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0$offset.0_1 is closed by DFSClient_NONMAPREDUCE_1179879432_3687
2018-09-10 05:02:02,390 INFO  [IPC Server handler 4 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_1    dst=/Segment_0$offset.0_2    perm=root:supergroup:rw-------    proto=rpc
2018-09-10 05:02:05,211 INFO  [IPC Server handler 8 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_2    dst=/Segment_0$offset.0_3    perm=root:supergroup:rw-------    proto=rpc
2018-09-10 05:02:11,542 INFO  [IPC Server handler 5 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=concat    src=[/Segment_0#transaction.2e82ec4de9f74eedb09aa856189fa5fe$offset.0_sealed]    dst=/Segment_0$offset.0_3    perm=root:supergroup:rw-------    proto=rpc
2018-09-10 05:02:12,681 INFO  [IPC Server handler 9 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=open    src=/Segment_0$offset.0_3    dst=null    perm=null    proto=rpc
2018-09-10 05:02:13,309 INFO  [IPC Server handler 1 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=setPermission    src=/Segment_0$offset.0_3    dst=null    perm=root:supergroup:r--r--r--    proto=rpc
2018-09-10 05:02:13,310 INFO  [IPC Server handler 3 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_3    dst=/Segment_0$offset.0_sealed    perm=root:supergroup:r--r--r--    proto=rpc
2018-09-10 05:02:13,605 INFO  [IPC Server handler 4 on 51757] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=delete    src=/Segment_0$offset.0_sealed    dst=null    perm=null    proto=rpc
```
**Failed Test**
```
2018-09-14 03:46:03,881 INFO  [IPC Server handler 2 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=create    src=/Segment_0$offset.0_0    dst=null    perm=root:supergroup:rw-------    proto=rpc
2018-09-14 03:46:03,974 INFO  [IPC Server handler 9 on 38720] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0$offset.0_0 is closed by DFSClient_NONMAPREDUCE_1915458050_3886
2018-09-14 03:46:04,459 INFO  [IPC Server handler 8 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_0    dst=/Segment_0$offset.0_1    perm=root:supergroup:rw-------    proto=rpc
2018-09-14 03:46:04,463 INFO  [IPC Server handler 2 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=append    src=/Segment_0$offset.0_1    dst=null    perm=null    proto=rpc
2018-09-14 03:46:04,495 INFO  [IPC Server handler 3 on 38720] hdfs.StateChange (FSDirWriteFileOp.java:logAllocatedBlock(725)) - BLOCK* allocate blk_1073741889_1089, replicas=127.0.0.1:42146 for /Segment_0$offset.0_1
2018-09-14 03:46:04,688 INFO  [IPC Server handler 6 on 38720] hdfs.StateChange (FSDirWriteFileOp.java:completeFile(605)) - DIR* completeFile: /Segment_0$offset.0_1 is closed by DFSClient_NONMAPREDUCE_1915458050_3886
2018-09-14 03:46:07,218 INFO  [IPC Server handler 8 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_1    dst=/Segment_0$offset.0_2    perm=root:supergroup:rw-------    proto=rpc
2018-09-14 03:46:10,024 INFO  [IPC Server handler 6 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_2    dst=/Segment_0$offset.0_3    perm=root:supergroup:rw-------    proto=rpc
2018-09-14 03:46:17,424 INFO  [IPC Server handler 8 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=concat    src=[/Segment_0#transaction.3b46345bc1724b5fa9399473316c50b3$offset.0_sealed]    dst=/Segment_0$offset.0_3    perm=root:supergroup:rw-------    proto=rpc
2018-09-14 03:46:18,419 INFO  [IPC Server handler 0 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=open    src=/Segment_0$offset.0_3    dst=null    perm=null    proto=rpc
2018-09-14 03:46:19,351 INFO  [IPC Server handler 2 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=setPermission    src=/Segment_0$offset.0_3    dst=null    perm=root:supergroup:r--r--r--    proto=rpc
2018-09-14 03:46:19,352 INFO  [IPC Server handler 4 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=rename    src=/Segment_0$offset.0_3    dst=/Segment_0$offset.0_sealed    perm=root:supergroup:r--r--r--    proto=rpc
2018-09-14 03:46:19,592 INFO  [IPC Server handler 6 on 38720] FSNamesystem.audit (FSNamesystem.java:logAuditMessage(7598)) - allowed=true    ugi=root (auth:SIMPLE)    ip=/127.0.0.1    cmd=delete    src=/Segment_0$offset.0_sealed    dst=null    perm=null    proto=rpc
```

We see that there is a `cmd=delete` triggered only for those segments with _even_ segment numbers (`Segment_0`, `Segment_2`,...). This is because `checkReadsWhileTruncating` truncates a segment at a different offset depending on its name, and in the case of even segment numbers truncation occurs beyond its current read offset, which turns into a delete operation in HDFS.

While deleting a segment in Tier 2 (`checkReadsWhileTruncating`) may be a normal part of a segment's lifecycle, it is still not clear why sporadically we get a `StreamSegmentNotExistsException` in this test. 

**Problem location**
`HDFSIntegrationTest.testEndToEnd` 

**Suggestions for an improvement**
Avoid sporadic failures in this test.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
This PR adds retries to `ReadOnlySegmentContainer` read operations for tolerating failures in reads addressed to segments being concurrently truncated.

**Purpose of the change**  
Fixes #2944, #3030.

**What the code does**  
`ReadOnlySegmentContainer` is special as it can only perform reads from Tier 2 storage. However, it may be the case that while one of those containers is reading a given segment, another ongoing operation deletes or truncates that segment, which may cause unexpected failures (e.g., `StreamSegmentNotExistsException`). This PR just adds retries to read operations in `ReadOnlySegmentContainer` with a twofold objective: i) handle concurrent Segment truncations/deletions while `ReadOnlySegmentContainer` is reading, and ii) handle reads related to Segments in Tier 1 but not yet existing in Tier 2. 

**How to verify it**  
`HDFSIntegration` tests should pass consistently. We have executed +70 times all tests under `:segmentstore:server:host:test` without observing any failure. Before that, with 20 runs we could reproduce issue #2944.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java [hunk 1]
```diff
@@ -128,14 +130,20 @@ public boolean isOffline() {
     public CompletableFuture<ReadResult> read(String streamSegmentName, long offset, int maxLength, Duration timeout) {
         Exceptions.checkNotClosed(this.closed.get(), this);
         TimeoutTimer timer = new TimeoutTimer(timeout);
-        return getStreamSegmentInfo(streamSegmentName, false, timer.getRemaining())
-                .thenApply(si -> StreamSegmentStorageReader.read(si, offset, maxLength, MAX_READ_AT_ONCE_BYTES, this.storage));
+        return Retry.withExpBackoff(30, 10, 4)
+                    .retryingOn(StreamSegmentNotExistsException.class)
+                    .throwingOn(RuntimeException.class)
+                    .run(() -> getStreamSegmentInfo(streamSegmentName, false, timer.getRemaining())
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java]: You can move lines 133-135 to a private static final field, and just reference it from here

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java [hunk 2]
```diff
@@ -128,14 +130,20 @@ public boolean isOffline() {
...
     }
 
     @Override
     public CompletableFuture<SegmentProperties> getStreamSegmentInfo(String streamSegmentName, boolean waitForPendingOps, Duration timeout) {
         Exceptions.checkNotClosed(this.closed.get(), this);
-        return this.segmentStateMapper.getSegmentInfoFromStorage(streamSegmentName, timeout);
+        return Retry.withExpBackoff(30, 10, 4)
+                    .retryingOn(StreamSegmentNotExistsException.class)
+                    .throwingOn(RuntimeException.class)
+                    .run(() -> this.segmentStateMapper.getSegmentInfoFromStorage(streamSegmentName, timeout));
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java]: And reference it here too.
