### PR TITLE
Issue 6683: LTS - Fix thread visibility issues

### LINKED ISSUE #6683: Flaky test S3ChunkStorageSystemJournalTests.testSimpleOperationSequence
**Describe the bug**
Sporadically, we see the following test failing in our builds:
```
java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk metadata must not be null.
	at io.pravega.segmentstore.storage.chunklayer.SystemJournal.lambda$applySystemLogOperations$51(SystemJournal.java:892)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk metadata must not be null.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	... 7 more
Caused by: java.lang.IllegalStateException: Chunk metadata must not be null.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.pravega.segmentstore.storage.chunklayer.SystemJournal.lambda$validateChunksInSegmentSnapshot$32(SystemJournal.java:715)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more
```

Also, we see another interesting trace claiming `taskQueue` to be null: 
[test-failure-trace.log](https://github.com/pravega/pravega/files/8449472/test-failure-trace.log)

**To Reproduce**
Run `./gradlew check` to run the tests, this error may happen sporadically.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
Issue 6683: LTS - Fix possible thread visibility issue with SystemJournal serialization.

**Purpose of the change**  
Fixes #6683 

**What the code does**  
1.  The default `RevisionDataInput::readCollection` returns `ArrayList `which is not thread safe. Return `Vector` instead.
2. Replace problematic `Collections.synchronizedList(new ArrayList<ExtendedChunkInfo>()); ` with `new Vector()` in all SLTS code
3. Make use of iterator with `Futures.loop` more thread-safe

Note - 

- It is possible in rare case that the data updated by one thread is not visible to another thread. This can lead to validation failure for snapshot. 
- On my machine I can repro about 1 in 10000 times.  Fix is to use synchronized list (eg. Vector).
- This kind of error does not mean there is a race to read/update same variable at the same time from multiple threads,  instead it means that when different lamdas are executed serially one by one they can be executed on different thread and potentially different processor cores.  That means data cached in first threads processor is not yet flushed to main memory, so second processor reads outdated value from main memory. By using volatile fields (via `Vector`) data guaranteed to be flushed correctly.

**How to verify it**  
All tests should pass.

### CODE REVIEW

**Comment by sachin-j-joshi** [comment]
image

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Do you think that there could be other points in SLTS that may suffer from the same issue? Also, please run system tests on this change.

**Comment by sachin-j-joshi** [comment]
We did fix several of these during beta testing - https://github.com/pravega/pravega/pull/5665
Looks like I still missed a couple places back then. I'll double check if there is anything else I missed.

**Review by abhinb — APPROVED** [review]

**Comment by RaulGracia** [comment]
@sachin-j-joshi apart from running system tests, is there anything missing from this PR? I assume you have synced up with @tkaitchuck on this change, right?

**Comment by sachin-j-joshi** [comment]
Putting it in draft mode -  I was able to still repro the failures. So there is still something else that is missing.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 1]
```diff
@@ -689,28 +690,32 @@ private CompletableFuture<Void> validateSystemSnapshotExistsInTxn(MetadataTransa
...
-                systemSnapshot.getSegmentSnapshotRecords(),
-                segmentSnapshot ->
-                    txn.get(segmentSnapshot.segmentMetadata.getKey())
-                        .thenComposeAsync(m -> validateChunksInSegmentSnapshot(txn, segmentSnapshot), executor)
-                        .thenComposeAsync(vv -> validateSegment(txn, segmentSnapshot.segmentMetadata.getKey()), executor)
-                        .thenApplyAsync(v -> true, executor),
-                executor);
+                () -> iterator.hasNext(),
+                () -> {
+                        synchronized (systemSnapshot.getSegmentSnapshotRecords()) {
```
Comment (tkaitchuck) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:698]: This is non-local reasoning. If SystemSnapshotRecord needs to have some sort of synchronization that class needs to enforce it. Here SystemSnapshotRecord doesn't even specify what type the records are beyond Collection. So even it doesn't even know if it needs to synchronize. I can only assume that this block means that it's being instantiated somewhere with a non-threadsafe collection but I don't actually see that anywhere in this file. Is this line redundant? Or is it being passed as a something other than a vector in some other file?

Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:698]: This line is redundant. I forgot to remove it :(

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 2]
```diff
@@ -1452,7 +1453,7 @@ protected void declareVersions() {
             }
 
             private void read00(RevisionDataInput input, SystemJournalRecordBatchBuilder b) throws IOException {
-                b.systemJournalRecords(input.readCollection(ELEMENT_DESERIALIZER));
+                b.systemJournalRecords(input.readCollection(ELEMENT_DESERIALIZER, () -> new Vector<>()));
```
Comment (tkaitchuck) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: Why is this needed? 
Is the `systemJournalRecords` member variable mutated after the creation of the object?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 3]
```diff
@@ -1694,7 +1695,7 @@ private void write00(SegmentSnapshotRecord object, RevisionDataOutput output) th
 
             private void read00(RevisionDataInput input, SegmentSnapshotRecord.SegmentSnapshotRecordBuilder b) throws IOException {
                 b.segmentMetadata((SegmentMetadata) SEGMENT_METADATA_SERIALIZER.deserialize(input.getBaseStream()));
-                b.chunkMetadataCollection(input.readCollection(ELEMENT_DESERIALIZER));
+                b.chunkMetadataCollection(input.readCollection(ELEMENT_DESERIALIZER, () -> new Vector<>()));
```
Comment (tkaitchuck) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1698]: Why is this needed? Is `chunkMetadataCollection` modified after the object is built?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 4]
```diff
@@ -1769,7 +1770,7 @@ private void write00(SystemSnapshotRecord object, RevisionDataOutput output) thr
             private void read00(RevisionDataInput input, SystemSnapshotRecord.SystemSnapshotRecordBuilder b) throws IOException {
                 b.epoch(input.readCompactLong());
                 b.fileIndex(input.readCompactInt());
-                b.segmentSnapshotRecords(input.readCollection(ELEMENT_DESERIALIZER));
+                b.segmentSnapshotRecords(input.readCollection(ELEMENT_DESERIALIZER, () -> new Vector<>()));
```
Comment (tkaitchuck) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1773]: Why is this needed? Is `segmentSnapshotRecords` modified after it is built?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: Here the issue is **not** concurrent modification - it is the issue of thread visibility. (processor cache flush.  updates made by one thread are not visible to other thread. [java memory model](https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html))

ArrayList created by default is non thread safe data structure. There is no guarantee that changes made by one thread is immediately visible to other thread. 


Advice given here is cumbersome to implement with lots of async code.
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedList-java.util.List-

>   It is imperative that the user manually synchronize on the returned list when iterating over it:
>   List list = Collections.synchronizedList(new ArrayList());
>       ...
>   synchronized (list) {
>       Iterator i = list.iterator(); // Must be in synchronized block
>       while (i.hasNext())
>           foo(i.next());
>   }

That is why given the context and usage (this code get used very rarely and using Vector is not an issue.)

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 3 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1698]: same as above

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 4 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1773]: same as above

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java [hunk 5]
```diff
@@ -602,7 +602,7 @@ public CompletableFuture<StorageMetadata> get(MetadataTransaction txn, String ke
         val txnData = txn.getData();
 
         // Record is found in transaction data itself.
-        TransactionData data = txnData.get(key);
+        val data = txnData.get(key);
```
[the remark this answers is not in the document]
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java:605]: ok. agree

[the remark this answers is not in the document]
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/metadata/BaseMetadataStore.java]: removed.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 2 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: This doesn't apply if this is being used correctly. Which is why I am concerned. If this is suppressing a bug, I fear it is not actually fixed. 
In this case an object is being build with a builder and then it's constructor is called inside the `.build()` which assigned to SystemJournalRecordBatch which is (and should be) a final field. If this list is then never changed (Which is the property I want to make sure holds) then SystemJournalRecordBatch is immutable and no synchronization is required because the construction of everything inside of it has a happens-before relationship to the object itself.
If on the other hand is *not* immutable, then there may be a race between items being added and removed from the list, and the list being read.
If we are following the rule: All data is immutable. Then validating this is trivial. The simplest way to make this clear would to have the member be an `ImmutableList` and use `ImmutableList.builder()` in the call to `readCollection` here.

Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: No systemJournalRecords field is not updated after creation.

image

Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: Definitely not modifying deserialized object.

Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1456]: Ok. Great. Then let's use: `ImmutableList` and use `ImmutableList.builder()` it will make this explicit and have higher performance

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 3 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1698]: Ok. Great. Then let's use: ImmutableList and use ImmutableList.builder() it will make this explicit and have higher performance

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 4 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1773]: Ok. Great. Then let's use: ImmutableList and use ImmutableList.builder() it will make this explicit and have higher performance

**Review by tkaitchuck — APPROVED** [review]
Approving with comments

**Comment by sachin-j-joshi** [comment]
System tests `test-pravega-continuous-1/2136/` passed

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 6]
```diff
@@ -1223,9 +1226,7 @@ private CompletableFuture<SystemSnapshotRecord> createSystemSnapshotRecord(Metad
                                     }
 
                                     // Add to the system snapshot.
-                                    synchronized (systemSnapshot) {
```
Comment (RaulGracia) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1226]: Why this is not needed anymore?

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 7]
```diff
@@ -1034,11 +1037,11 @@ private CompletableFuture<Void> applyChunkAddition(MetadataTransaction txn, Map<
         Preconditions.checkState(null != oldChunkName, "oldChunkName must not be null");
         Preconditions.checkState(null != newChunkName && !newChunkName.isEmpty(), "newChunkName must not be null or empty");
 
-        return txn.get(segmentName)
+        return validateSegment(txn, segmentName)
```
Comment (RaulGracia) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1040]: Ok, but looks unrelated to this change.

**Review by RaulGracia — COMMENTED** [review]
Couple of minor questions before merging.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 6 above)
Comment (RaulGracia) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1226]: Ok, so it was using a plain `new ArrayList<>()` before, right? Not a `Collections.synchronizedList()`

**Review by RaulGracia — APPROVED** [review]

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 6 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:1226]: it was still using Collections.synchronizedList(). but had additional redundant guard which is really unnecessary
