### PR TITLE
Issue 6713: Fixing flakiness in progressingWatermarkWithTimestampAggregationTimeout Test

### LINKED ISSUE #6713: Fix flaky test WatermarkingTest.progressingWatermarkWithTimestampAggregationTimeout
**Describe the bug**
The integration test WatermarkingTest.progressingWatermarkWithTimestampAggregationTimeout needs has been failing intermittently because of its dependency on the timeout values which needs to be fixed.

**To Reproduce**
Run the integration test repeatedly

**Screenshots**
sss

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by SrishT**
Signed-off-by: SrishT <Srishti.Thakkar@emc.com>

**Change log description**  
The integration test WatermarkingTest.progressingWatermarkWithTimestampAggregationTimeout has been failing intermittently because of its dependency on the timeout values, which is being fixed here.

**Purpose of the change**  
Fixes #6713 

**What the code does**  
Tries to overcome the dependence on a random timeout value for the generation of the subsequent watermark by making use of assertEventuallyEquals instead.

**How to verify it**  
All tests should pass

### CODE REVIEW

**Comment by RaulGracia** [comment]
@SrishT any progress with this?

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 1]
```diff
@@ -85,6 +86,34 @@ public static void await(Supplier<Boolean> condition, int checkFrequencyMillis,
...
+
+        while (condition == null || !condition.get() && remainingMillis > 0) {
+            try {
+                result = eval.call();
+                T finalResult = result;
+                condition = () -> (expected == null && finalResult == null)
+                        || (expected != null && expected.equals(finalResult));
+            } catch (Exception e) {
+                throw new RuntimeException(e);
+            }
```
Comment (tkaitchuck) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java:104]: Why this catch? We don't want to necessarily change the exception type.

Comment (SrishT) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java:104]: `eval.call` throws this exception, and the way the catch block handles it has been kept similar to the way things were done prior to the code restructuring.

**Review by tkaitchuck — APPROVED** [review]

**Review by ShwethaSNayak — APPROVED** [review]
LGTM

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 2]
```diff
@@ -85,6 +86,34 @@ public static void await(Supplier<Boolean> condition, int checkFrequencyMillis,
         }
     }
 
+    @SneakyThrows(InterruptedException.class)
```
Comment (ShwethaSNayak) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java:89]: Can you add Java doc for this method for more clarity?

Comment (SrishT) [reply test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: done
