### PR TITLE
Issue 2678: (SegmentStore) Bugfix for StreamSegmentNotExists after container failover

### LINKED ISSUE #2678: During segment container ownership transfer readers get NoSuchSegment
**Problem description**
Readers were reading from a segment on a particular segment container. Then segmentContainer failover happened and post ownership transfer readers failed with NoSuchSegment. 
This lead to readers rereading data from offset 0 in the segment `0#epoch.10` again. 
It repeated 3 times before they were successfully able to read it. 

```
segmentstore_2018-06-08.1.log:2018-06-08 14:24:26,941 103854 [core-10] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
segmentstore_2018-06-08.1.log:2018-06-08 14:24:27,974 104887 [core-24] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
segmentstore_2018-06-08.1.log:2018-06-08 14:24:29,016 105929 [core-28] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Segment 'testReadTxnWriteAutoScaleScope2092305162/testReadTxnWriteAutoScaleStream/0#epoch.10' does not exist and cannot perform operation 'Read segment'.
```

**Problem location**
SegmentStore

**Suggestions for an improvement**
Fix the issue

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in the Segment Store where, in some scenarios, it would cancel a Read request with a `StreamSegmentNotExistsException` immediately after a `SegmentContainer` recovery.

**Background**
What happens during a Segment Merge (high-level steps; there's more detail underneath):
1. Consider two segments, S1, and S2. We want to merge S2 into S1 at offset N.
2. We request the merge into the Segment Store. The merge request is recorded in the Segment Store, and the Read Index for S1 is updated with `beginMerge(S2, N)`, which indicates that offsets [N, N+len(S2)) within S1 will be redirected to S2[0, len(S2)).
    - This is because S2 is not yet merged into S1 in Tier2, hence we need this redirect.
3. Some time later, the StorageWriter picks up the operation and executes the `concat(S2->S1 @ N)` in Tier2.
4. Immediately afterwards, the StorageWriter invokes `completeMerge(S2)` onto S1's read index to notify it of the fact that S2 has been physically merged into S1.
5. Eventually the merge operation is truncated out of Tier1.

Due to the fact that operations 3 and 4 are not atomic, it is possible that a concurrent read arrives at S1@N in the time interval between these two. This can happen in one of two cases:
- Case 1: During normal operations. In this case the delay between 3 and 4 is usually a few milliseconds.
- Case 2: Immediately after recovery. If step 3 has happened, but 5 hasn't happened yet, then immediately after recovery, until the StorageWriter reconciles the state of S1 and S2 in Tier2 with the metadata, if a read comes in at S1@N, it will not be able to be fulfilled until the reconciliation.

Previously there was a hacked solution addressing Case 1 (and Case 2, if the Tier2 reconciliation was just after the read). That solution could not scale gracefully to solve Case 2.

**Fix:**
- If such a read comes in (between steps 3 and 4), there is a chance it will be served from the cache (in which case no problem). But if it needs to be served from Tier2, it will result in a `StreamSegmentNotExistsException`. 
- The same mechanism as before will be used. If we end up in such as situation, instead of retrying after 1 second, we will register a Future Read for the "missing" offset range and associate it with the source segment that was stuffed in there.
- When `completeMerge` is invoked, any Future Reads associated with that merge will be triggered (after the index is updated), which should finally return the correct data.

**Purpose of the change**
Fixes #2678.

**What the code does**
See description.

**How to verify it**
New unit test added and existing test updated to verify this particular behavior.
System tests must pass.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java [hunk 1]
```diff
@@ -46,19 +46,20 @@
 
     //region AutoCloseable Implementation
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java]: If this class is not autocloseable any longer, then we don't need this region.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java [hunk 2]
```diff
@@ -46,19 +46,20 @@
...
 
-    @Override
-    public void close() {
+    List<FutureReadResultEntry> close() {
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java]: I'm wondering if it wouldn't be cleaner to get the list of `FutureReadResultEntry` items separately instead of changing the return value of `close()` and making it not autocloseable.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java [hunk 3]
```diff
@@ -839,7 +873,39 @@ private CompletableReadResultEntry createRedirectedRead(long streamSegmentOffset
...
+
+            // Transform the read result entry into a Future Read, instead of adding it to futureReads, associate it
+            // with this pendingMerge, so that a completeMerge() would finalize it.
+            FutureReadResultEntry futureResult = new FutureReadResultEntry(result.getStreamSegmentOffset(), result.getRequestedReadLength());
+            if (pendingMerge != null && pendingMerge.register(futureResult)) {
+                // We were able to register the result.
+                result = futureResult;
+                log.debug("{}: Registered Pending Merge Future Read {}.", this.traceObjectId, result);
+            } else {
+                // The merge has been unregistered. Our only hope now is that the index has settled and re-invoking this
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java]: This comment mentions the index settling. Is it possible that the index hasn't settled yet, in which case, I'm wondering what would happen to the read?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/FutureReadResultEntryCollection.java]: Fixed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java]: This means that between line(s) 883-887 and this one, `completeMerge` has been invoked and completely executed. That means that it has sealed and unregistered the PendingMerge, so there's nothing to latch on to at this point. We can only re-issue the same call we did in 883 and get a reference to an entry in the newly merged index.

Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java]: OK. The comment gave the impression that it might not have happened, I think it is just the phrasing that confused me.
