### PR TITLE
Issue 4107: Automatic delegation token renewal

### LINKED ISSUE #4107: Delegation token does not renew automatically upon expiry
**Problem description**
Pull request [3887](https://github.com/pravega/pravega/pull/3887) implemented delegation token expiry. As a result, delegation tokens eventually expire. When a client makes a request to segment store using a delegation token that has expired, the segment store rejects the request and the client application encounters a TokenException which looks like the stack trace shown below. 

```
io.pravega.auth.TokenExpiredException: io.jsonwebtoken.ExpiredJwtException: JWT expired at 2019-08-14T11:15:40Z. Current time: 2019-08-14T11:45:04Z, a difference of 1764381 milliseconds.  Allowed clock skew: 0 milliseconds.
        at io.pravega.shared.security.token.JsonWebToken.parseClaims(JsonWebToken.java:161)
        at io.pravega.shared.security.token.JsonWebToken.fetchClaims(JsonWebToken.java:180)
        at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:56)
        at io.pravega.segmentstore.server.host.handler.AppendProcessor.setupAppend(AppendProcessor.java:159)
        at io.pravega.shared.protocol.netty.WireCommands$SetupAppend.process(WireCommands.java:501)
        at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:53)
```

The client application may catch the exception and retry the transaction to recover from the failure. But doing so unnecessarily complicates client application code. 

Rather than throwing an exception to the client application, the client library should automatically get the delegation token renewed. A couple of subtly different alternative options seem to be: 

1. Upon encountering the exception, reauthenticate with the Controller using the credentials supplied by the client application or its environment, obtain a new delegation token and retry the client-to-segment-store transaction transparently.
2. Get the existing delegation token refreshed by the Controller periodically. 

**Problem location**
Pravega Client library

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Introduces automatic token renewal. 

**Purpose of the change**  
Resolves #4107. 

**What the code does**  
Here's what the code does, at a high level:
1. Adds a `DelegationTokenProvider` (as well as related factory and implementation classes) that is used as a proxy for a delegation token in places where a string delegation token was used. 

   For JWT tokens, when the token is retrieved via the `retrieveToken()` method, the provider checks if the delegation token is nearing expiry. If the token is nearing expiry, it refreshes the token, i.e., fetches a new token and returns that one. Otherwise, it returns an existing token. 
   
2. Adds a token handling strategy for tackling these different scenarios: 
    * A JWT token
    * An empty token which occurs when auth is disabled. This strategy is also used in many test cases. 
    * A non-JWT token, which is used in some of the tests. 
    * A null token for cases where a delegation token is not populated in advance and is fetched lazily when needed. 

**How to verify it**  
All tests should pass.

I used the following temporary test suite to verify the changes: 

```java
package io.pravega.test.integration;

import io.pravega.client.security.auth.DelegationTokenProviderFactoryTest;
import io.pravega.client.security.auth.JwtBodyTest;
import io.pravega.client.security.auth.JwtTokenProviderImplTest;
import io.pravega.client.segment.impl.AsyncSegmentInputStreamTest;
import io.pravega.client.segment.impl.ConditionalOutputStreamTest;
import io.pravega.client.segment.impl.SegmentMetadataClientTest;
import io.pravega.client.state.impl.RevisionedStreamClientTest;
import io.pravega.client.stream.impl.EventStreamReaderTest;
import io.pravega.client.stream.impl.SegmentSelectorTest;
import io.pravega.segmentstore.server.host.handler.PravegaRequestProcessorAuthFailedTest;
import io.pravega.shared.protocol.netty.WireCommandsTest;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({
        // New unit test classes focused on the enhancement
        JwtTokenProviderImplTest.class,
        DelegationTokenProviderFactoryTest.class,
        JwtBodyTest.class,

        // Some of the relevant existing unit test classes
        EventStreamReaderTest.class,
        RevisionedStreamClientTest.class,
        AppendTest.class,
        AppendReconnectTest.class,
        ReadTest.class,
        SegmentSelectorTest.class,
        ConditionalOutputStreamTest.class,
        PravegaRequestProcessorAuthFailedTest.class,
        WireCommandsTest.class,
        AsyncSegmentInputStreamTest.class,
        SegmentMetadataClientTest.class,

        // New and existing integration tests related to delegation tokens
        DelegationTokenTest.class
})

public class DelegationTokenTestSuite {
}
```

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java [hunk 1]
```diff
@@ -105,26 +115,37 @@ RawClient getConnection() {
...
         RawClient connection = getConnection();
         long requestId = connection.getFlow().getNextSequenceNumber();
-        return connection.sendRequest(requestId, new GetStreamSegmentInfo(requestId, segmentId.getScopedName(), delegationToken))
+        return connection.sendRequest(requestId, new GetStreamSegmentInfo(
+                requestId, segmentId.getScopedName(), delegationToken.retrieveToken()))
                          .thenApply(r -> transformReply(r, StreamSegmentInfo.class));
     }
     
-    private CompletableFuture<WireCommands.SegmentAttribute> getPropertyAsync(UUID attributeId, String delegationToken) {
+    private CompletableFuture<WireCommands.SegmentAttribute> getPropertyAsync(UUID attributeId, DelegationTokenProxy delegationToken) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: Same here

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -562,6 +567,9 @@ void reconnect() {
                          }
                          return connectionSetupFuture.exceptionally(t -> {
                              Throwable exception = Exceptions.unwrap(t);
+
+                             //controller.getOrRefreshDelegationTokenFor()
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Remove

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProxy.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+package io.pravega.client.security.auth;
+
+/**
+ * A client-side proxy for obtaining a delegation token.
+ *
+ * Note:
+ * Delegation tokens are used by Segment Store services to authorize requests. They are created by Controllers.
+ *
+ */
+public interface DelegationTokenProxy {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProxy.java]: I've modified it to `DelegationTokenProvider` now. Calling it `DelegationTokenSupplier` can make it easy to confuse it with an implementation of the Java Supplier.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+            return delegationToken.get().getValue();
+        }
+    }
+
+    @Override
+    public String refreshToken() {
+        resetToken(newToken());
+        return delegationToken.get().getValue();
+
+        /*if (delegationToken.get().getExpiryTime() != null) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/JwtBody.java [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+package io.pravega.client.security.auth;
+
+import lombok.Builder;
+import lombok.Getter;
+import lombok.Setter;
+
+@Builder
+@Getter
+@Setter
+class JwtBody {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtBody.java]: Sure, I've done the changes as suggested.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+
+    /**
+     * Represents the threshold for triggering delegation token refresh.
+     */
+    private static final int REFRESH_THRESHOLD = 10;
+
+    /**
+     * The Controller gRPC client used for interacting with the server.
+     */
+    @Getter(AccessLevel.PROTECTED)
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: Fixed.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+        }
+        return delegationToken.get().getValue();*/
+    }
+
+    protected String newToken() {
+        return Futures.getAndHandleExceptions(
+                controllerClient.getOrRefreshDelegationTokenFor(scopeName, streamName), RuntimeException::new);
+    }
+
+    private synchronized boolean isTokenNearingExpiry() {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: This too was a leftover in the work-in-progress code.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+
+    @Getter(AccessLevel.PROTECTED)
+    private final String scopeName;
+
+    @Getter(AccessLevel.PROTECTED)
+    private final String streamName;
+
+    @Getter(AccessLevel.PROTECTED)
+    @Setter(AccessLevel.PROTECTED)
+    private AtomicReference<DelegationToken> delegationToken = new AtomicReference<>();
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: I've removed the `@Setter` as it was not needed since the implementation had changed. We still need the `@Getter()` for the `AtomicReference` so that the subclass `NullTokenHandlingStrategy` can make use of it. The `@Getter` has `protected` access level. The object isn't expected to be exposed to callers of the class. Hope that addresses your concern.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java [hunk 9]
```diff
@@ -51,7 +55,13 @@
     private final Object lock = new Object();
     @GuardedBy("lock")
     private RawClient client = null;
-    private final String delegationToken;
+    private final DelegationTokenProxy delegationToken;
+
+    public SegmentMetadataClientImpl(Segment segment, Controller controller, ConnectionFactory connectionFactory,
+                                     String delegationToken) {
+        this(segment, controller, connectionFactory,
+                new DelegationTokenProxyImpl(delegationToken, controller, segment));
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: I've modified the implementation to use a factory `DelegationTokenProviderFactory` for creating an instance of `DelegationTokenProvider` (called `DelegationTokenProxy` earlier), as suggested.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 2 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+        if (token == null || token.trim().equals("")) {
+            return null;
+        }
+        String[] tokenParts = token.split("\\.");
+
+        // JWT is of the format abc.def.ghe. The middle part is the body.
+        String encodedBody = tokenParts[1];
+        String decodedBody = new String(Base64.getDecoder().decode(encodedBody));
+
+        JwtBody jwt = new Gson().fromJson(decodedBody, JwtBody.class);
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: The `JwtTokenHandlingStrategy` localizes the JWT token handling strategy in its own class. If we use a different delegation token format later, we can add a new strategy implementation class and activate it in the `DelegationTokenProviderImpl` class. Hope that addresses your concern about the format lock-in. 

As for the use of the transitive Gson dependency, I've now added Gson as a dependency in the client. We parse the JWT JSON-formatted body to obtain the token expiration time, in order to find out if the token is nearing expiry; To parse the JSON, we are using Gson deserialization, and therefore need it as a dependency. Hope that is OK.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java [hunk 11]
```diff
@@ -105,26 +115,37 @@ RawClient getConnection() {
...
+                throw new TokenException(authTokenCheckReply.toString());
+            }
         } else {
             throw new ConnectionFailedException("Unexpected reply of " + reply + " when expecting a "
                     + klass.getName());
         }
     }
 
-    private CompletableFuture<StreamSegmentInfo> getStreamSegmentInfo(String delegationToken) {
+    private CompletableFuture<StreamSegmentInfo> getStreamSegmentInfo(DelegationTokenProxy delegationToken) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: This was preexisting code, where I had replaced the String argument with a `DelegationTokenProvider` argument. In any case, I have done the change as suggested.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java (hunk 1 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: This was preexisting code, where I had replaced the String argument with a `DelegationTokenProvider` argument. In any case, I have done the change as suggested.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java [hunk 12]
```diff
@@ -0,0 +1,22 @@
...
+ *
+ * Licensed under the Apache License, Version 2.0 (the "License");
+ * you may not use this file except in compliance with the License.
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.security.auth;
+
+public interface DelegationTokenHandlingStrategy {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java]: This interface represents a common interface shared by all algorithms (strategies) used for handling delegation token retrieval and refresh. The strategies differ in their behavior but all provide implementations for this interface. Having an interface here also makes it easier to add mock objects for testing purposes.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 13]
```diff
@@ -0,0 +1,139 @@
...
+     * The Controller gRPC client used for interacting with the server.
+     */
+    private final Controller controllerClient;
+
+    private final String scopeName;
+
+    private final String streamName;
+
+    @Getter(AccessLevel.PROTECTED)
+    private AtomicReference<DelegationToken> delegationToken = new AtomicReference<>();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: final

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 14]
```diff
@@ -0,0 +1,139 @@
...
+    /**
+     * The Controller gRPC client used for interacting with the server.
+     */
+    private final Controller controllerClient;
+
+    private final String scopeName;
+
+    private final String streamName;
+
+    @Getter(AccessLevel.PROTECTED)
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: It doesn't really make sense to have a getter here. Perhaps you want to write a method that returns the actual delegation token?

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 15]
```diff
@@ -0,0 +1,139 @@
...
+    private AtomicReference<DelegationToken> delegationToken = new AtomicReference<>();
+
+    static {
+        REFRESH_THRESHOLD = ConfigurationOptionsExtractor.extractInt(
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: This is not following dependency injection. This will be very difficult to test. Consider if there is a way this can be provided via a config object, through construction, or obtained from the controller.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java [hunk 16]
```diff
@@ -292,7 +295,8 @@ private void handleSegmentTruncated(EventSegmentReader segmentReader) throws Tru
         String delegationToken = groupState.getOrRefreshDelegationTokenFor(segmentId);
 
         @Cleanup
-        SegmentMetadataClient metadataClient = metadataClientFactory.createSegmentMetadataClient(segmentId, delegationToken);
+        SegmentMetadataClient metadataClient = metadataClientFactory.createSegmentMetadataClient(segmentId,
+                DelegationTokenProviderFactory.create(delegationToken, controller, segmentId));
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java]: This is sub optimal. If this provider refreshes the token the delegationToken in this class will still be out of date, so every future call to this method is going to have to refresh the token again even though it just retrieved a token that has not expired.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 17]
```diff
@@ -342,8 +343,8 @@ private void throwIfClosed() throws TxnFailedException {
         UUID txnId = txnSegments.getTxnId();
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
         for (Segment s : txnSegments.getSteamSegments().getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txnId,
-                    config, txnSegments.getSteamSegments().getDelegationToken());
+            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txnId, config,
+                    DelegationTokenProviderFactory.create(txnSegments.getSteamSegments().getDelegationToken(), controller, s));
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Here we are creating many providers. This means when the token expires we will end up refreshing the token `numsegments` times rather than once.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 18]
```diff
@@ -367,7 +368,8 @@ private void throwIfClosed() throws TxnFailedException {
         
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
         for (Segment s : segments.getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txId, config, segments.getDelegationToken());
+            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txId, config,
+                    DelegationTokenProviderFactory.create(segments.getDelegationToken(), controller, s));
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Same here.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 19]
```diff
@@ -0,0 +1,139 @@
...
+        this.scopeName = scopeName;
+        this.streamName = streamName;
+        this.controllerClient = controllerClient;
+    }
+
+    @Override
+    public String retrieveToken() {
+        if (isTokenNearingExpiry()) {
+            log.info("Token is nearing expiry, so refreshing it");
+            return refreshToken();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: This does not guard against many calls to get the token coming in while it is being refreshed. We only want to update the token once if it is near expiry. There are various classes in `common` which might help with this. Perhaps a simpler solution of backgrounding the refresh, and using the current token so that calls in the meantime are not blocked.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 20]
```diff
@@ -0,0 +1,139 @@
...
+
+    @Override
+    public String refreshToken() {
+        resetToken(newToken());
+        return delegationToken.get().getValue();
+    }
+
+    protected String newToken() {
+        return Futures.getAndHandleExceptions(
+                controllerClient.getOrRefreshDelegationTokenFor(scopeName, streamName), RuntimeException::new);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: SHould this have retries? Perhaps look at `Retry`?

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 21]
```diff
@@ -313,8 +315,10 @@ private StreamCut computeEndStreamCut(Stream stream, Map<Segment, Long> endSegme
                 if (endPositions.containsKey(s)) {
                     totalLength += endPositions.get(s);
                 } else {
+                    DelegationTokenProvider delegationTokenProvider = DelegationTokenProviderFactory.create(
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Again this would probably make sense to share across segments.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 22]
```diff
@@ -176,8 +179,11 @@ void removeSegmentWriter(Segment segment) {
     private void createMissingWriters(Consumer<Segment> segmentSealedCallBack, String delegationToken) {
         for (Segment segment : currentSegments.getSegments()) {
             if (!writers.containsKey(segment)) {
+                DelegationTokenProvider tokenProvider = DelegationTokenProviderFactory.create(delegationToken,
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: This should be passed in rather than constructed here.

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java [hunk 23]
```diff
@@ -177,8 +179,10 @@ private void throwIfClosed() throws TxnFailedException {
         UUID txnId = txnSegments.getTxnId();
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
         for (Segment s : txnSegments.getSteamSegments().getSegments()) {
+            DelegationTokenProvider tokenProvider = DelegationTokenProviderFactory.create(
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: Again this is one per-segment and not reused between calls.

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java [hunk 24]
```diff
@@ -197,7 +201,8 @@ private void throwIfClosed() throws TxnFailedException {
         
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
         for (Segment s : segments.getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txId, config, segments.getDelegationToken());
+            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txId, config,
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: Same here.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java [hunk 25]
```diff
@@ -0,0 +1,74 @@
...
+     * @param segment the {@link Segment}, for which a delegation token is to be obtained
+     * @return a new {@link DelegationTokenProvider} instance
+     * @throws NullPointerException if {@code controller} or {@code segment} is null
+     */
+    public static DelegationTokenProvider create(Controller controller, Segment segment) {
+        return create(null, controller, segment);
+    }
+
+    /**
+     * Creates a {@link DelegationTokenProvider} instance with null delegation token.
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java]: Fixed.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 13 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Done.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java (hunk 16 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java]: Sure, I've made the change that you've suggested in the latest commit.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 17 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Fixed.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 18 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Reusing the delegation token provider as suggested.

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java (hunk 23 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: I've made this change in the latest commit.

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java (hunk 24 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java [hunk 26]
```diff
@@ -0,0 +1,98 @@
...
+
+import com.google.common.annotations.VisibleForTesting;
+import io.pravega.client.stream.impl.Controller;
+import lombok.AccessLevel;
+import lombok.Getter;
+import lombok.NonNull;
+import lombok.extern.slf4j.Slf4j;
+
+@Slf4j
+public class DelegationTokenProviderImpl implements DelegationTokenProvider {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: I am afraid I don't agree with you on this. I had started out without this abstraction and was finding complex/hard-to-decipher logic in `DelegationTokenProviderImpl` comprising of many if/else conditions etc. to tackle various scenarios arising out of conditions such as a specified JWT token at construction time, unspecified (lazily fetched tokens) token at construction time, empty token (when auth is disabled), etc. That is when I ended up refactoring the code into strategy pattern to separate the various strategies into their own respective classes, which in turn made it easier for me to inspect the logic for correctness and to write unit tests to prove that. 

Please give it another look and let me know if you still strongly disagree.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: There isn't any configuration parameter to be specified by the client application unless the client application developer intends to modify the time-based threshold for a refreshing token (refreshes token if it is about to expire in 5 seconds, by default). 

Plus the format used for delegation tokens - JWT currently - is opaque to the client application. The application doesn't care or need to know. It's an internal thing between the client library code and the Controller. 

A good thing about parsing the expiry time from the token alone is that we can potentially use/pass other params through the delegation token, without having to change the Controller gRPC API that returns delegation token for the scope and stream. For example, we might decide later to also verify the entity that has created the delegation token in the future. Changing the Controller API for each of such changes may not work out very well. 

Please consider these aspects as well, and reassess the mechanism. Please let me know.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java]: Please see my response to a similar comment here: https://github.com/pravega/pravega/pull/4215#discussion_r330050019.

File: client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java [hunk 27]
```diff
@@ -72,7 +73,8 @@ public StreamCutHelper(Controller controller, ConnectionFactory connectionFactor
 
     private SegmentInfo segmentToInfo(Segment s) {
         @Cleanup
-        SegmentMetadataClient client = segmentMetadataClientFactory.createSegmentMetadataClient(s, latestDelegationToken.get());
+        SegmentMetadataClient client = segmentMetadataClientFactory.createSegmentMetadataClient(s,
+                DelegationTokenProviderFactory.create(latestDelegationToken.get(), controller, s));
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java]: Sorry, I didn't quite understand this comment. The `latestDelegationToken` is an atomic reference containing the String delegation token. In the code shown above, we use that token to create a DelegationTokenProvider using the factory. 

Am I missing something?

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 14 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Sure, I've removed it now. The accessor was being accessed by a child class, and therefore it was having a getter. I've now modified it as per your suggestion.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 15 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Sure, I've made it an instance variable now and have added overloaded constructors so that the configuration may be injected via the constructor for testing purposes.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 19 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: I wanted to avoid the use of locks, even though in some cases the code will indeed lead to the delegation token wrapped by AtomicReference getting replaced multiple times unnecessarily. A background refresh will also require locks. What do you say?

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 22 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Sorry, I didn't understand how constructing the `DelegationTokenProvider` object in the calling method help here. Could you please explain your comment?

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 20 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: I think we should add it if needed later. I haven't encountered a scenario in my testing so far where retry was needed. I'll defer to your opinion though. Please let me know.

File: build.gradle [hunk 28]
```diff
@@ -238,6 +238,7 @@ project('client') {
         compile project(":shared:controller-api")
         compile group: 'io.netty', name: 'netty-transport-native-epoll', version: nettyVersion
         compile group: 'com.google.guava', name: 'guava', version: guavaVersion
+        compile group: 'com.google.code.gson', name: 'gson', version: gsonVersion
```
Comment (andreipaduroiu) [inline build.gradle]: You're adding a new dependency to the client. Is this absolutely necessary? How big is the JAR? I would prefer not to make the client bigger than it currently is.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java [hunk 29]
```diff
@@ -0,0 +1,20 @@
...
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.security.auth;
+
+/**
+ * Strategy for handling delegation tokens of various kinds, such as null, empty, JWT, non-JWT strings, etc.
+ */
+public interface DelegationTokenHandlingStrategy {
+
+    String retrieveToken();
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java]: Javadoc for **all** publicly visible methods, especially on interfaces.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java [hunk 30]
```diff
@@ -0,0 +1,33 @@
...
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.security.auth;
+
+/**
+ * A client-side proxy for obtaining a delegation token from the server.
+ *
+ * Note: Delegation tokens are used by Segment Store services to authorize requests. They are created by Controllers at
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java]: "Controllers" -> "the Controller"

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java [hunk 31]
```diff
@@ -0,0 +1,33 @@
...
+ * client's behest.
+ */
+public interface DelegationTokenProvider {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java]: Why does this have the same methods as the Strategy interface above? Can you merge them?

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java [hunk 32]
```diff
@@ -0,0 +1,74 @@
...
+ */
+package io.pravega.client.security.auth;
+
+import com.google.common.base.Preconditions;
+import io.pravega.client.segment.impl.Segment;
+import io.pravega.client.stream.impl.Controller;
+import io.pravega.common.Exceptions;
+
+/**
+ * Creates a {@link DelegationTokenProvider} instance.
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java]: A proper Javadoc would be "Factory class for DelegationTokenProvider instances"

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java [hunk 33]
```diff
@@ -0,0 +1,98 @@
...
+     * Constructs a new object with the specified specified delegation token.
+     *
+     * <p>
+     * Intended for use mainly for testing purposes.
+     */
+    @VisibleForTesting
+    DelegationTokenProviderImpl(@NonNull String token) {
+        if (token.trim().equals("")) {
+            strategy = new EmptyTokenHandlingStrategy();
+            log.debug("Set DelegationTokenHandlingStrategy as {}", EmptyTokenHandlingStrategy.class);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: Please do not log every time you create an object. This will pollute the log files like crazy. Move your logging to the upstream code that instantiates this.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java [hunk 34]
```diff
@@ -0,0 +1,74 @@
...
+     * Creates a {@link DelegationTokenProvider} instance with the specified delegation token.
+     *
+     * @param delegationToken an existing delegation token to populate the {@link DelegationTokenProvider} instance with
+     * @param controller  the {@link Controller} client used for obtaining a delegation token from the Controller
+     * @param segment the {@link Segment}, for which a delegation token is to be obtained
+     * @return a new {@link DelegationTokenProvider} instance
+     */
+    public static DelegationTokenProvider create(String delegationToken, Controller controller,
+                                                 Segment segment) {
+        Preconditions.checkNotNull(controller, "Argument controller is null");
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java]: You do not need all these null checks here. The constructor of DelegationTokenProviderImpl already has nullchecks.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java [hunk 35]
```diff
@@ -0,0 +1,98 @@
...
+    /**
+     * Constructs a new object with the specified {@code controller}, {@code scopeName} and {@code streamName}.
+     *
+     * @param controller the {@link Controller} client used for obtaining a delegation token from the Controller
+     * @param scopeName the name of the scope tied to the segment, for which a delegation token is to be obtained
+     * @param streamName the name of the stream tied to the segment, for which a delegation token is to be obtained
+     */
+    DelegationTokenProviderImpl(@NonNull Controller controller, @NonNull String scopeName, @NonNull String streamName) {
+        strategy = new NullJwtTokenHandlingStrategy(controller, scopeName, streamName);
+        log.debug("Set DelegationTokenHandlingStrategy as {}", NullJwtTokenHandlingStrategy.class);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: here too

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java [hunk 36]
```diff
@@ -0,0 +1,98 @@
...
+     * @param delegationToken the initial delegation token
+     * @param controller the {@link Controller} client used for obtaining a delegation token from the Controller
+     * @param scopeName the name of the scope tied to the segment, for which a delegation token is to be obtained
+     * @param streamName the name of the stream tied to the segment, for which a delegation token is to be obtained
+     */
+    DelegationTokenProviderImpl(String delegationToken, @NonNull Controller controller,
+                                       @NonNull String scopeName, @NonNull String streamName) {
+        if (delegationToken == null) {
+            strategy = new NullJwtTokenHandlingStrategy(controller, scopeName, streamName);
+            log.debug("Set DelegationTokenHandlingStrategy as {}", NullJwtTokenHandlingStrategy.class);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: and here

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java [hunk 37]
```diff
@@ -0,0 +1,98 @@
...
+        }
+    }
+
+    /**
+     * Returns the delegation token. It returns existing delegation token if it is not close to expiry. If the token
+     * is close to expiry, it obtains a new delegation token and returns that one instead.
+     *
+     * @return String the delegation token JWT compact value
+     */
+    public String retrieveToken() {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: `@Override`

And below.

File: client/src/main/java/io/pravega/client/security/auth/JwtBody.java [hunk 38]
```diff
@@ -0,0 +1,52 @@
...
+
+    // See https://tools.ietf.org/html/rfc7519#page-9 for additional details about these fields.
+
+    /**
+     * The "sub" (for subject) claim of the JWT body.
+     */
+    @SerializedName("sub")
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtBody.java]: What is the goal of serialization? Is it to pass data between client and server? If so, you need to use `VersionedSerializer`.

I observe this is the only place where you use `google.gson`; if true, then please remove this reference and use the `VersionedSerializer` which exists in common and which has back&forward compatibility features.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 39]
```diff
@@ -0,0 +1,153 @@
...
+
+    private final String scopeName;
+
+    private final String streamName;
+
+    private final AtomicReference<DelegationToken> delegationToken = new AtomicReference<>();
+
+    JwtTokenHandlingStrategy(Controller controllerClient, String scopeName, String streamName) {
+        this(controllerClient, scopeName, streamName, ConfigurationOptionsExtractor.extractInt(
+                "pravega.client.auth.token-refresh.threshold",
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: These strings are good candidates for putting into static final fields.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 19 above)
Comment (andreipaduroiu) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Then you should try to use optimistic concurrency. Make use of the primitives offered by `AtomicReference` to do compare-and-set to guard against updating it to a stale value.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 20 above)
Comment (andreipaduroiu) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: You should have retries. Calls over the wire are bound to fail for whatever reasons. Having an exp-backoff retry will save you a lot of trouble in the future.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java [hunk 40]
```diff
@@ -105,53 +115,64 @@ RawClient getConnection() {
             throw new NoSuchSegmentException(reply.toString());
         } else if (reply instanceof WrongHost) {
             throw new ConnectionFailedException(reply.toString());
+        } else if (reply instanceof WireCommands.AuthTokenCheckFailed) {
+            WireCommands.AuthTokenCheckFailed authTokenCheckReply = (WireCommands.AuthTokenCheckFailed) reply;
+            if (authTokenCheckReply.isTokenExpired()) {
+                log.info("Delegation token expired");
+                throw new TokenExpiredException(authTokenCheckReply.toString());
+                // closeConnection(reply);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: delete this line

File: common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java [hunk 41]
```diff
@@ -0,0 +1,45 @@
...
+ * you may not use this file except in compliance with the License.
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.common.util;
+
+import lombok.NonNull;
+
+public class ConfigurationOptionsExtractor {
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java]: Javadoc for this class and all of its public methods.

File: common/src/test/java/io/pravega/common/util/ConfigurationOptionsExtractorTests.java [hunk 42]
```diff
@@ -0,0 +1,45 @@
...
+
+public class ConfigurationOptionsExtractorTests {
+
+    @Test
+    public void testExtractInteger() {
+        String propertyName = this.getClass().getSimpleName() + ".testExtractInteger." + ".test.property";
+        System.setProperty(propertyName, "5");
+        assertSame(5, ConfigurationOptionsExtractor.extractInt(propertyName,
+                "test_property_1", 1));
+        System.clearProperty(propertyName);
```
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/util/ConfigurationOptionsExtractorTests.java]: Put this in a `finally` block to ensure it is always cleaned, regardless of the outcome of your test.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 43]
```diff
@@ -355,9 +356,14 @@ private void handleException(UUID writerId, long requestId, String segment, long
             log.warn("Bad attribute update by {} on segment {}.", writerId, segment, u);
             connection.send(new InvalidEventNumber(writerId, requestId, clientReplyStackTrace));
             connection.close();
+        } else if (u instanceof TokenExpiredException) {
+            log.warn("Token was found as expired when writer {} was writing on segment {}", writerId, segment, u);
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: "Token expired for writer {} on segment {}."

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 44]
```diff
@@ -947,11 +948,16 @@ private Void handleException(long requestId, String segment, long offset, String
             invokeSafely(connection::send, new SegmentRead(segment, offset, true, false, EMPTY_BYTE_BUFFER, requestId), failureHandler);
         } else if (u instanceof CancellationException) {
             log.info(requestId, "Closing connection {} while performing {} due to {}.",
-                     connection, operation, u.toString());
+                    connection, operation, u.toString());
             connection.close();
+        } else if (u instanceof TokenExpiredException) {
+            log.warn(requestId, "Token was found as expired during operation '{}'.", operation, u);
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: 1. "Expired token during operation `{}`"
2. We don't care about the full stack trace here. Do not log `u`.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 45]
```diff
@@ -947,11 +948,16 @@ private Void handleException(long requestId, String segment, long offset, String
...
+            invokeSafely(connection::send, new AuthTokenCheckFailed(requestId, clientReplyStackTrace,
+                    AuthTokenCheckFailed.ERROR_CODE_TOKEN_EXPIRED), failureHandler);
         } else if (u instanceof TokenException) {
-            log.warn(requestId, "Token verification failed during '{}'.", operation);
-            invokeSafely(connection::send, new AuthTokenCheckFailed(requestId, clientReplyStackTrace), failureHandler);
+            log.warn(requestId, "Token exception encountered during operation '{}'.", operation, u);
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Think carefully if you need to log the full stack trace of just exception message (`u.toString()`).

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 19 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: @andreipaduroiu The problem is not the re-writing of the value, the problem is fetching it multiple times. 

@ravisharda How about the following, have an atomic reference and an atomic boolean to indicate if it is being fetched. If the token is actually expired: Fetch the token and wait for the new value. If the token is near but not yet expired, and the AtomicBoolean is false, set it to true (with compare and set), then trigger a background fetch of the token and get a new token, but return to the caller the one already in memory. 

This way in the happy case where the token gets refreshed before expiry only one caller ever refreshes the token. And we avoid the need for any locking

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java (hunk 29 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenHandlingStrategy.java]: Sure, I've added the JavaDocs in the latest commit I have pushed.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java (hunk 32 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java (hunk 34 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderFactory.java]: Sure. I've removed these now.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java (hunk 36 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java (hunk 35 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java (hunk 30 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java]: Fixed. :)

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 20 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Sorry, I take it back. There are retries built into that method.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java (hunk 33 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: I was logging these at a debug level and it's going to be in the client logs. In any case, I can't help but agree that these were logging way too much. I've now removed these debug statements.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java (hunk 37 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 39 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Sure, done.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java (hunk 40 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentMetadataClientImpl.java]: Done.

File: common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java (hunk 41 above)
Comment (ravisharda) [reply common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java]: Done.

File: common/src/test/java/io/pravega/common/util/ConfigurationOptionsExtractorTests.java (hunk 42 above)
Comment (ravisharda) [reply common/src/test/java/io/pravega/common/util/ConfigurationOptionsExtractorTests.java]: Sure, that's a good idea too. I've pushed this change.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 43 above)
Comment (ravisharda) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Done.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 44 above)
Comment (ravisharda) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Fixed.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 14 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: I don't see this change.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: > There isn't any configuration parameter to be specified by the client application unless the client application developer intends to modify the time-based threshold for a refreshing token (refreshes token if it is about to expire in 5 seconds, by default).

Correct, there is no reason to modify that.

> Plus the format used for delegation tokens - JWT currently - is opaque to the client application. The application doesn't care or need to know. It's an internal thing between the client library code and the Controller.

Isn't this change undoing all of that? The client library is now using json to decode the jwt token. Instead of doing that, the controller could simply return two fields in the reply.

> A good thing about parsing the expiry time from the token alone is that we can potentially use/pass other params through the delegation token, without having to change the Controller gRPC API

I agree we should be able to use/pass other parameters through the delegation token to the server. I don't agree that we should use them to pass data to the client. The client-controller API is already versioned, supports adding fields, and has a defined protocol. All other changes in client-server communication happen there. There is no advantage in circumenting that for one code path.

If on the other hand the token remains opaque to the client, then we can put whatever we want in there without the client code knowing or caring about it. The server can then use this additional information as appropriate.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java [hunk 46]
```diff
@@ -0,0 +1,155 @@
...
+        delegationToken.set(new DelegationToken(token, expTime));
+        this.scopeName = scopeName;
+        this.streamName = streamName;
+        this.controllerClient = controllerClient;
+        this.tokenRefreshThreshold = tokenRefreshThreshold;
+    }
+
+    @Override
+    public String retrieveToken() {
+        if (isTokenNearingExpiry()) {
```
Comment (sarlaccpit) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: I have a general confusion/concern about the entirety of the PR, which might be based on me not understanding the overall code as a whole, or it may be my concern is legitimate. Please help me figure out which.

Here's my thing:

To my understanding, the authentication/authorization flow goes like this:
- step 1: the client initiates a conversation with the controller.   In that phase, the client calls the Credentials interface, https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/stream/impl/Credentials.java#L32 configured in the environment; depends on the plugin implementation etc.  Some decision is made there to grant an opaque token (opaque to Pravega and specific to the plugin implementation) to OK the client's intentions.
- step 2: as a result of that, a delegation token (opaque to the plugin impl. from above, and format specific to Pravega) is issued by the controller, with an expiry
- step 3: that d-token is used over and over again between the client and SS, until expiry.  

- step 4: the code above looks like essentially we would automatically refresh the d-token indefinitely, with no questions asked, no challenge.   I thought, that when the d-token expires, the client should go right back to step 1 and get challenged again to present its credentials.  (the implementation of the plugin itself can have its own meanings of caching, refreshing tokens etc etc.), oblivious of Pravega.     The d-token has its own configurable expiry, which is great and the deployer can decide what that length of time should be.  But once that runs out, shouldn't it be thrown right back to step 1?    Imagine the user initially used in step 1 no longer exists.  The d-token essentially lives on forever, always refreshing, until the end of time.  that doesn't work right?

It's possible I missed something; let me know.

Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: @sarlaccpit A couple of clarifications: 

1. Your description looks correct for steps 1, 2 and 3. (Assuming you were referring to the delegation token as being distinct from the token token in the Credentials interface). 
2. Regarding step 4, upon delegation token renewal the client is reauthenticated: 
https://github.com/pravega/pravega/blob/5c38d07f24f46f988c09a4345dd5d06b8bcfa770/controller/src/main/java/io/pravega/controller/server/rpc/auth/AuthInterceptor.java#L77.

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java (hunk 23 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: It's there in the latest code. 

https://github.com/pravega/pravega/blob/5d21e6a484657f8c9dc0a6c74d7337e8560bb19b/client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java#L181-L186

File: client/src/main/java/io/pravega/client/security/auth/DelegationToken.java [hunk 47]
```diff
@@ -0,0 +1,34 @@
...
+     *   2) ""  : an empty value used by callers when auth is disabled.
+     *   3) a non-empty JWT compact string of the format
+     *       <base64-encoded-header-json>.<base64-encoded-body-json>.<base64-encoded-signature>
+     */
+    private final String value;
+
+    /**
+     * Caches the expiration time of the current token, so that the token does not need to be parsed upon every retrieval.
+     */
+    private final Long expiryTime;
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/security/auth/DelegationToken.java]: this can be replaced by primitive type `long`.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 48]
```diff
@@ -341,9 +343,14 @@ private void throwIfClosed() throws TxnFailedException {
                 RuntimeException::new);
         UUID txnId = txnSegments.getTxnId();
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
+        DelegationTokenProvider tokenProvider = null;
         for (Segment s : txnSegments.getSteamSegments().getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txnId,
-                    config, txnSegments.getSteamSegments().getDelegationToken());
+            if (tokenProvider == null) {
+                // We can share token providers across segments as delegation tokens are scope + stream specific.
+                tokenProvider = DelegationTokenProviderFactory.create(txnSegments.getSteamSegments().getDelegationToken(),
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: nit: typo `getSteamSegment()` to `getStreamSegments()`

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 49]
```diff
@@ -341,9 +343,14 @@ private void throwIfClosed() throws TxnFailedException {
                 RuntimeException::new);
         UUID txnId = txnSegments.getTxnId();
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
+        DelegationTokenProvider tokenProvider = null;
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: we can initialize it here removing the if block below . (same below too...)

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 50]
```diff
@@ -341,9 +343,14 @@ private void throwIfClosed() throws TxnFailedException {
...
         for (Segment s : txnSegments.getSteamSegments().getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txnId,
-                    config, txnSegments.getSteamSegments().getDelegationToken());
+            if (tokenProvider == null) {
+                // We can share token providers across segments as delegation tokens are scope + stream specific.
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: The eventStreamWriter is specific to a given scope and stream. Can we create one token provider per EventStreamWriter ?

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java (hunk 31 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java]: Sure, done.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProviderImpl.java]: Sounds good to me. I've made the change to merge the two interfaces into one in the latest push.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 14 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: The latest code has this change. 

https://github.com/pravega/pravega/blob/3cfb2bef8e8e2965fad5389a258332b1f1586251/client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java#L56-L58

File: client/src/main/java/io/pravega/client/security/auth/DelegationToken.java (hunk 47 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationToken.java]: I wanted to allow the possibility of having an unspecified expiry time here. Hope that makes sense.

File: client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/ValidJwtTokenHandlingStrategy.java]: I see the value of making the token opaque to the client. 

However, the expiry time we are extracting is part of the JWT formatted token, so I believe it'd be overkill to also send it out of band via the Controller's response to the client's request for delegation token, when it is already part of the token. The JWT token itself is a self-contained object containing everything necessary to process the token, including the registered claim `exp` (expiration time) (https://tools.ietf.org/html/rfc7519#page-9). 

Also, to clarify about my assertion about passing other data via delegation token, I was only referring to data necessary for processing a delegation token, such as registered claims listed [here](https://tools.ietf.org/html/rfc7519#page-9). 

That being said, I've modified the code now to avoid the dependency for `Gson`. 

I hope that works.

File: client/src/main/java/io/pravega/client/security/auth/JwtBody.java (hunk 38 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtBody.java]: I've modified the code now to avoid the client's dependency for Gson for JSON parsing. I now use regex to extract the expiry time from the JWT token. Gson is used for easier unit testing only. Does that work?

File: build.gradle (hunk 28 above)
Comment (ravisharda) [reply build.gradle]: I've modified the code now to avoid the dependency for Gson. I now use regex to extract the expiry time from the JWT token. Gson is now used for easier unit testing only. I hope that works.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 45 above)
Comment (ravisharda) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Since the TokenException is a generic one, it'd be useful to see the stacktrace in the logs to determine the cause. This exception should rarely occur if it occurs at all. `TokenExpiredException`, on the other hand, is a specific exception; So, for `TokenExpiredException` we only log the exception message.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 49 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: The reason I initialized it like this is to avoid having to initializing it on a per-segment basis. So, here, we initialize it once depending on whether the `tokenProvider` is null. 

https://github.com/pravega/pravega/blob/5d21e6a484657f8c9dc0a6c74d7337e8560bb19b/client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java#L346-L352

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 48 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Sure. This was an existing code with a typo. I've changed it to `getStreamSegments()` in the last commit. You sure have a keen eye. :)

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 50 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Sure, I've made the change as suggested in the latest commit I've pushed.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java (hunk 19 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenHandlingStrategy.java]: Thanks @tkaitchuck and @andreipaduroiu. I've modified the code as suggested by both of you in the latest commit.  Please take a look and see if it makes sense.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 51]
```diff
@@ -0,0 +1,236 @@
...
+            return delegationToken.get().getValue();
+        }
+    }
+
+    @Override
+    public String refreshToken() {
+        log.trace("Entered refreshToken().");
+        DelegationToken existingToken = this.getCurrentToken();
+        if (isTokenBeingRefreshed.get()) {
+            log.debug("Token is already under refresh.");
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: When you log these messages, it will help a lot to include context in them. Take a look at some of the classes inside the segment store and how they do it (i.e., `StreamSegmentContainer.java`, `SegmentAggregator.java`, etc.). You should probably include the scope/stream/segment name in all these messages.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 52]
```diff
@@ -0,0 +1,236 @@
...
+
+            // Wait for the token to finish refreshing
+            while (!isTokenBeingRefreshed.get()) {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I don't understand this busy wait loop at all.

1. you can simplify it by looping on the condition of `isTokenBeingRefreshed.compareAndSet(false, true)` returning false. When it returns true, you got it and can reset the token.
2. You set `isTokenBeingRefreshed` to false inside `resetToken`. That makes your logic pretty hard to follow. You should be modifying it in the same level of the code, not in different methods.
3. Why the busy-wait loop and why sleep 200ms in between? `resetToken` does absolutely nothing interesting. It performs a `compareAndSet` which is an atomic operation and it has its own synchronization primitives. I don't understand why you need a busy loop at all here.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 53]
```diff
@@ -0,0 +1,236 @@
...
+
+    private boolean isTokenNearingExpiry() {
+        Long currentTokenExpirationTime = this.delegationToken.get().getExpiryTime();
+
+        // currentTokenExpirationTime can be null if the server returns a null delegation token
+        return currentTokenExpirationTime != null && isWithinRefreshThreshold(currentTokenExpirationTime);
+    }
+
+    private boolean isWithinRefreshThreshold(Long expirationTime) {
+        Preconditions.checkNotNull(expirationTime);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: for private method, it's best to use `assert expirationTime != null`. This will be checked in unit and system tests, but it won't be enabled in production so it will make your code faster at runtime.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 54]
```diff
@@ -0,0 +1,236 @@
...
+    }
+
+    @VisibleForTesting
+    Long parseExpirationTime(String json) {
+        Long result = null;
+        if (json != null && !json.trim().equals("")) {
+            // Sample inputs:
+            //    {"sub":"subject","aud":"segmentstore","iat":1569837384,"exp":1569837434}
+            //    {"sub": "subject","aud": "segmentstore","iat": 1569837384,"exp": 1569837434}
+            Pattern pattern = Pattern.compile("\"exp\":\\s?(\\d+)");
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Do you need to compile the pattern every time you invoke this method? You can stash this in a private static final field.

File: client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java [hunk 55]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.security.auth;
+
+import io.pravega.client.stream.impl.Controller;
+import lombok.NonNull;
+
+/**
+ * Provider for handling null initialized tokens. This provider is similar as {@link JwtTokenProviderImpl}, except
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java]: similar to

File: client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java [hunk 56]
```diff
@@ -0,0 +1,184 @@
...
+                token, mock(Controller.class), "somescope", "somestream");
+        assertEquals(token, objectUnderTest.retrieveToken());
+    }
+
+    @Test
+    public void testExpirationTimeIsNullIfExpInBodyIsNotSet() {
+
+        // See decoded parts at https://jwt.io/.
+        //
+        // The body decodes to:
```
Comment (tkaitchuck) [inline client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java]: These seem like the encoding logic should be here so that the string can actually be expressed like this in code rather than as a comment where it isn't clear how someone can add more tests like this.

File: client/src/test/java/io/pravega/client/security/auth/NullInitializedTokenProviderImplTest.java [hunk 57]
```diff
@@ -0,0 +1,91 @@
...
+import java.util.function.Supplier;
+
+import static io.pravega.client.security.auth.JwtTestUtils.createJwtBody;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertTrue;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+@Slf4j
+public class NullInitializedTokenProviderImplTest extends JwtTokenProviderImplTest {
```
Comment (tkaitchuck) [inline client/src/test/java/io/pravega/client/security/auth/NullInitializedTokenProviderImplTest.java]: Just because two classes extend one another does not mean their tests have to, or should.

File: client/src/test/resources/logback-test.xml [hunk 58]
```diff
@@ -17,7 +17,7 @@
         </encoder>
     </appender>
 
-    <root level="DEBUG">
+    <root level="INFO">
```
Comment (tkaitchuck) [inline client/src/test/resources/logback-test.xml]: I think this can be reverted.

File: common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java [hunk 59]
```diff
@@ -0,0 +1,74 @@
...
+     * both are specified, the value from system property is returned. If neither are specified, it returns
+     * the {code defaultValue}.
+     *
+     * @param systemProperty the system property to extract the configuration value from
+     * @param environmentVariable the environment variable to extract the configuration value from
+     * @param defaultValue the value to be returned if neither {@code systemProperty} or {@code environmentVariable} is
+     *                     specified
+     * @return the specified or default configuration value
+     */
+    public static String extractString(@NonNull String systemProperty, @NonNull String environmentVariable,
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java]: Is this used anywhere? Can it be made private?

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 60]
```diff
@@ -0,0 +1,236 @@
...
+ * Provides JWT-based delegation tokens.
+ */
+@Slf4j
+public class JwtTokenProviderImpl implements DelegationTokenProvider {
+
+    /**
+     * Represents the threshold for triggering delegation token refresh.
+     */
+    @VisibleForTesting
+    static final int DEFAULT_REFRESH_THRESHOLD = 5;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: This name should be suffixed with a unit.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 61]
```diff
@@ -1516,10 +1516,31 @@ public boolean mustLog() {
 
     @Data
     public static final class AuthTokenCheckFailed implements Reply, WireCommand {
+        public final static int ERROR_CODE_TOKEN_CHECK_FAILED = 0;
+        public final static int ERROR_CODE_TOKEN_EXPIRED = 1;
         final WireCommandType type = WireCommandType.AUTH_TOKEN_CHECK_FAILED;
         final long requestId;
         final String serverStackTrace;
 
+        // -1 indicates un-specified (for backward compatibility)
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Rather than being comments, and expressed as an interger. This should be an Enum where each value has an integer. Then the upper layers don't need to compare against those statics they can directly switch or do an IF on the values of the enum, and the encoding/decoding from an integer is contained within this class.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 62]
```diff
@@ -1529,12 +1550,16 @@ public void process(ReplyProcessor cp) {
...
+            out.writeInt(errorCode);
         }
 
         public static WireCommand readFrom(ByteBufInputStream in, int length) throws IOException {
             long requestId = in.readLong();
             String serverStackTrace = (in.available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
-            return new AuthTokenCheckFailed(requestId, serverStackTrace);
+
+            // errorCode is a new field and wasn't present earlier. Doing this to allow it to work with older clients.
+            int errorCode = in.available()  >= Integer.BYTES ? in.readInt() : -1;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: As this is adding a new field, you should bump the version number of the protocol incase at some point we want to make this mandatory, we can add that number as the lower bound. (We shouldn't do that now, but we should increase the constant at the top of the file)

File: client/src/test/resources/logback-test.xml (hunk 58 above)
Comment (ravisharda) [reply client/src/test/resources/logback-test.xml]: Done.

File: client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java (hunk 56 above)
Comment (ravisharda) [reply client/src/test/java/io/pravega/client/security/auth/JwtTokenProviderImplTest.java]: Sure, I've modified the code to address this and pushed the change.

File: client/src/test/java/io/pravega/client/security/auth/JwtBodyTest.java [hunk 63]
```diff
@@ -0,0 +1,63 @@
...
+        assertEquals("segmentstore", jwtBody.getAudience());
+        assertEquals(new Long(1569837384), jwtBody.getIssuedAtTime());
+        assertEquals(new Long(1569837434), jwtBody.getExpirationTime());
+    }
+
+    @Test
+    public void test() {
+        String json = //"{\"sub\":\"subject\",\"aud\":\"segmentstore\",\"iat\":1569837384,\"exp\":1569837434}";
+
+        "{\"sub\":\"subject\",\"aud\":\"segmentstore\",\"iat\":1569837384,\"exp\": 1569837434}";
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/test/java/io/pravega/client/security/auth/JwtBodyTest.java]: This was leftover code. I've removed it in the latest commit.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 64]
```diff
@@ -83,6 +85,7 @@
     private final ConcurrentLinkedQueue<Segment> sealedSegmentQueue = new ConcurrentLinkedQueue<>();
     private final ExecutorService retransmitPool;
     private final Pinger pinger;
+    private DelegationTokenProvider tokenProvider;
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: This couldn't have been made final as we were initializing it lazily. However and as you have also mentioned in another comment, the provider should be modified to allow callers to pass a delegation token obtained later. Once I do that, I should be able to make this variable final.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 65]
```diff
@@ -0,0 +1,236 @@
...
+     */
+    private final Controller controllerClient;
+
+    private final String scopeName;
+
+    private final String streamName;
+
+    private final AtomicReference<DelegationToken> delegationToken = new AtomicReference<>();
+
+    private AtomicBoolean isTokenBeingRefreshed = new AtomicBoolean(false);
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: It was an oversight to miss this. I've fixed it in the latest commit.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 54 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Yes, it makes sense to cache the pattern in a private static final field. I've now modified it.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 53 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Yes, that makes sense to use asserts for private methids. I've removed the preconditions check and replaced it with an `assert`, in the latest commit.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 51 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've modified the log statements to include additional context.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 66]
```diff
@@ -0,0 +1,236 @@
...
+            log.info("Token is nearing expiry");
+            return refreshToken();
+        } else {
+            return delegationToken.get().getValue();
+        }
+    }
+
+    @Override
+    public String refreshToken() {
+        log.trace("Entered refreshToken().");
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've modified it to use `LoggerHelpers.traceEnter/traceLeave`. Luckily, the class was accessible from here.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 65 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: It was an oversight. I've fixed it now.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 60 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've added the unit of time as a suffix now.

Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've added the unit of time as a suffix now.

File: client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java [hunk 67]
```diff
@@ -0,0 +1,33 @@
...
+ */
+public class NullInitializedTokenProviderImpl extends JwtTokenProviderImpl {
+
+    public NullInitializedTokenProviderImpl(@NonNull Controller controllerClient, @NonNull String scopeName, @NonNull String streamName) {
+            super(controllerClient, scopeName, streamName);
+    }
+
+    @Override
+    public String retrieveToken() {
+        if (this.getCurrentToken() == null) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java]: Yes, it makes sense to remove the `NullInitialiedTokenProviderImpl` class. It doesn't add significant specialized behavior but resulted in a good deal of complexity. I've removed it now. 

Also, thanks for sharing your thoughts about structuring class hierarchies for easier review. I can't agree with you more.

File: client/src/test/java/io/pravega/client/security/auth/NullInitializedTokenProviderImplTest.java (hunk 57 above)
Comment (ravisharda) [reply client/src/test/java/io/pravega/client/security/auth/NullInitializedTokenProviderImplTest.java]: I understand that a test class doesn't have to extend another test class just because the objects they test are from classes that form a class hierarchy. The reason for having the `NullInitializedTokenProviderImplTest` test class extend from the `JwtTokenProviderImplTest` test class was that the tests present in latter were also applicable for the former. In any case, now the child test class is removed as `NullInitializedTokenProcviderImpl` is removed too, so this comment is not applicable now.

File: client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java (hunk 55 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/NullInitializedTokenProviderImpl.java]: I've removed this class now.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 52 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Yes, it was quite ugly. I've now modified this part of the code significantly, which resolves these issues.

[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've now modified this part of the code significantly, which resolves these issues. Please take a relook at this and see if it looks good now.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 68]
```diff
@@ -0,0 +1,236 @@
...
+    @VisibleForTesting
+    boolean isWithinRefreshThreshold(Instant currentInstant, Instant expiration) {
+        return currentInstant.plusSeconds(tokenRefreshThreshold).getEpochSecond() >= expiration.getEpochSecond();
+    }
+
+    protected boolean resetToken(DelegationToken existingToken, DelegationToken newToken) {
+        boolean isTokenResetSuccessful = delegationToken.compareAndSet(existingToken, newToken);
+        if (isTokenResetSuccessful) {
+            log.debug("Successfully reset token");
+            isTokenBeingRefreshed.compareAndSet(true, false);
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I agree with you. I've now modified this part of the code significantly, which resolves this issue.

File: client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java [hunk 69]
```diff
@@ -0,0 +1,33 @@
...
+     * @return a delegation token
+     */
+    String retrieveToken();
+
+    /**
+     * Refresh and retrieve delegation token.
+     *
+     * @return a new delegation token
+     */
+    String refreshToken();
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/DelegationTokenProvider.java]: When I initially wrote this interface, I had anticipated the need for refreshing tokens and had this method there. It's not really required given that the refresh occurs transparently, and so I've removed this method.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 70]
```diff
@@ -0,0 +1,236 @@
...
+                log.debug("Token refresh status setting to 'true' failed.");
+            }
+        }
+        String result = delegationToken.get().getValue();
+        log.trace("Exiting refreshToken()");
+        return result;
+    }
+
+    protected DelegationToken newToken() {
+        String token = Futures.getAndHandleExceptions(
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, that was a great idea. I've now used it to block on the caller side rather than using a busy loop.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java (hunk 64 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: I've now introduced a method to populate existing tokens into the DelegationTokenrovider. Accordingly, I was able to make this variable final. The change is present in the latest commit.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 71]
```diff
@@ -442,4 +446,10 @@ private void noteTimeInternal(long timestamp) {
         controller.noteTimestampFromWriter(writerId, stream, timestamp, position);
     }
 
+    private void initializeTokenProviderIfEmpty(StreamSegments streamSegments) {
+        if (this.tokenProvider == null) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: The modified implementation doesn't use it.

File: client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java [hunk 72]
```diff
@@ -442,4 +446,10 @@ private void noteTimeInternal(long timestamp) {
...
+            tokenProvider = DelegationTokenProviderFactory.create(streamSegments.getDelegationToken(), controller,
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java]: Sure, I've added a new method to the `DelegationTokenProvider` interface to populate tokens piggybacking on other messages. Accordingly, this part of the code has also changed.

File: common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java (hunk 59 above)
Comment (ravisharda) [reply common/src/main/java/io/pravega/common/util/ConfigurationOptionsExtractor.java]: I've reduced the visibility as suggested.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 73]
```diff
@@ -0,0 +1,234 @@
...
+     * is close to expiry, it obtains a new delegation token and returns that one instead.
+     *
+     * @return String the delegation token JWT compact value
+     */
+    @Override
+    public String retrieveToken() {
+        if (this.delegationToken.get() == null) {
+            return this.refreshToken();
+        } else if (isTokenNearingExpiry()) {
+            log.info("Token is nearing expiry");
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I'm not sure this log line is helpful. There isn't really any context. This should include the stream name etc.
Also it might be more of a debug level.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 74]
```diff
@@ -0,0 +1,234 @@
...
+            return refreshToken();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: It seems like this should trigger the refresh, but not actually block the thread waiting for the result, and just return the current token after triggering it.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 75]
```diff
@@ -0,0 +1,234 @@
...
+        return currentInstant.plusSeconds(refreshThresholdInSeconds).getEpochSecond() >= expiration.getEpochSecond();
+    }
+
+    @VisibleForTesting
+    String refreshToken() {
+        long traceEnterId = LoggerHelpers.traceEnter(log, "refreshToken", this.scopeName, this.streamName);
+        CompletableFuture<Void> currentRefreshFuture = tokenRefreshFuture.get();
+        if (currentRefreshFuture == null) {
+            log.debug("Initiated token refresh for scope {} and stream {}", this.scopeName, this.streamName);
+            this.tokenRefreshFuture.set(this.recreateToken());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: This should be a compareAndSet incase some other thread raced this one.
This can be accomplished by creating a future and setting it, and then passing the future to recreate token so it can complete that.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 76]
```diff
@@ -0,0 +1,234 @@
...
+        } else {
+            log.debug("Token is already under refresh for scope {} and stream {}", this.scopeName, this.streamName);
+        }
+        tokenRefreshFuture.get().join(); // Block until the token is refreshed
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I don't see any error handling here. 
There needs to be test coverage of this, because as far as I can tell the current behaviour is that if ever one call to refreshTheToken throws, no future call will ever be issued and every single call to obtain the token will fail on this line.
This would leave the client in an unrecoverable state.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 77]
```diff
@@ -0,0 +1,234 @@
...
+        this.tokenRefreshFuture.compareAndSet(currentRefreshFuture, null); // Token is already refreshed, so resetting the future to null.
+
+        LoggerHelpers.traceLeave(log, "refreshToken", traceEnterId, this.scopeName, this.streamName);
+        return delegationToken.get().getValue();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: There is no point in a private method returning a member variable. The caller can access this themselves.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 78]
```diff
@@ -0,0 +1,234 @@
...
+        long traceEnterId = LoggerHelpers.traceEnter(log, "refreshToken", this.scopeName, this.streamName);
+        CompletableFuture<Void> currentRefreshFuture = tokenRefreshFuture.get();
+        if (currentRefreshFuture == null) {
+            log.debug("Initiated token refresh for scope {} and stream {}", this.scopeName, this.streamName);
+            this.tokenRefreshFuture.set(this.recreateToken());
+        } else {
+            log.debug("Token is already under refresh for scope {} and stream {}", this.scopeName, this.streamName);
+        }
+        tokenRefreshFuture.get().join(); // Block until the token is refreshed
+        this.tokenRefreshFuture.compareAndSet(currentRefreshFuture, null); // Token is already refreshed, so resetting the future to null.
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: This can be done in recreateToken() in the future chain.

File: test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java [hunk 79]
```diff
@@ -109,4 +110,109 @@ private void writeAnEvent(int tokenTtlInSeconds) throws ExecutionException, Inte
...
+            Runnable runnable = () -> {
+                @Cleanup
+                EventStreamWriter<String> writer = clientFactory.createEventWriter(streamName,
+                        new JavaSerializer<String>(),
+                        EventWriterConfig.builder().build());
+
+                for (int i = 0; i < 10; i++) {
+                    String msg = "message: " + i;
+                    try {
+                        writer.writeEvent(msg).get();
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java]: I think you might want join() instead of .get()

File: client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java (hunk 27 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java]: I don't see a easy and safe way of doing it, as we piggyback on a delegation token obtained in one method to initialize a DelegationTokenProvider in another method, and both these can happen concurrently. Could we live with this?

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java (hunk 61 above)
Comment (ravisharda) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Sure, that's a good idea. I've modified the code to use an enum in the auth token check failed wire command to represent error codes.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java (hunk 62 above)
Comment (ravisharda) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Sure, done.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 73 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Done.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 77 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Not returning the value makes the calling code `retrieveToken()` look overly complicated. I think we should leave it as is, as a result.

File: test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java (hunk 79 above)
Comment (ravisharda) [reply test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java]: Sure, that simplifies this code. I've made the change as suggested.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java [hunk 80]
```diff
@@ -309,12 +311,17 @@ private StreamCut computeEndStreamCut(Stream stream, Map<Segment, Long> endSegme
         }
         return unread.thenApply(unreadVal -> {
             long totalLength = 0;
+            DelegationTokenProvider tokenProvider = null;
             for (Segment s : unreadVal.getSegments()) {
                 if (endPositions.containsKey(s)) {
                     totalLength += endPositions.get(s);
                 } else {
+                    if (tokenProvider == null) {
+                        tokenProvider = DelegationTokenProviderFactory.create(
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: I've added a `populateToken()` method to the `DelegationTokenProvider` interface that can be used to populate tokens retrieved later through piggybacking into the provider. However, that doesn't seem useful here as there is no instance variable for holding the provider. I didn't want to modify the logic of this class in a big way, so I didn't try introducing a new `DelegationTokenProvider` instance variable in this class. Could we live with this?

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 81]
```diff
@@ -174,10 +177,16 @@ void removeSegmentWriter(Segment segment) {
     }
 
     private void createMissingWriters(Consumer<Segment> segmentSealedCallBack, String delegationToken) {
+        DelegationTokenProvider tokenProvider = null;
         for (Segment segment : currentSegments.getSegments()) {
             if (!writers.containsKey(segment)) {
+                if (tokenProvider == null) {
+                    tokenProvider = DelegationTokenProviderFactory.create(delegationToken,
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Please see my comments in https://github.com/pravega/pravega/pull/4215#discussion_r333707009. What do you say?

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java [hunk 82]
```diff
@@ -176,14 +178,19 @@ private void throwIfClosed() throws TxnFailedException {
                 RuntimeException::new);
         UUID txnId = txnSegments.getTxnId();
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
-        for (Segment s : txnSegments.getSteamSegments().getSegments()) {
+        DelegationTokenProvider tokenProvider = null;
+        for (Segment s : txnSegments.getStreamSegments().getSegments()) {
+            if (tokenProvider == null) {
+                tokenProvider = DelegationTokenProviderFactory.create(
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: Please see my comments in https://github.com/pravega/pravega/pull/4215#discussion_r333707009. What do you say?

File: client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java [hunk 83]
```diff
@@ -196,8 +203,13 @@ private void throwIfClosed() throws TxnFailedException {
         }
         
         Map<Segment, SegmentTransaction<Type>> transactions = new HashMap<>();
+        DelegationTokenProvider tokenProvider = null;
         for (Segment s : segments.getSegments()) {
-            SegmentOutputStream out = outputStreamFactory.createOutputStreamForTransaction(s, txId, config, segments.getDelegationToken());
+            if (tokenProvider == null) {
+                tokenProvider = DelegationTokenProviderFactory.create(segments.getDelegationToken(), controller, s);
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java]: Please see my comments in https://github.com/pravega/pravega/pull/4215#discussion_r333707009. What do you say?

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java (hunk 80 above)
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: At the top of the loop instead of `DelegationTokenProvider tokenProvider = null;`
You can do `DelegationTokenProvider tokenProvider = DelegationTokenProviderFactory.create(...)`;
Then here you don't need this `if`. You can just call `populateToken(unreadVal.getDelegationToken())`

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 22 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: I've modified this class to have a `DelegationTokenProvider` object as instance variable, which is in turn populated with the latest delegation token that is received. So, this issue is now resolved.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 81 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Actually, I was able to fix this, as described [here](https://github.com/pravega/pravega/pull/4215#discussion_r333890387).

File: client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java (hunk 27 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java]: My last assertion was incorrect. There is a way to achieve what you have suggested, with the recent introduction of `populateToken()` method in  `DelegationTokenProvider`. I'll do the change and push it in the next commit. I'll leave this comment as unresolved until I push the change.

[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/admin/impl/StreamCutHelper.java]: I've pushed this change in a recent commit.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java (hunk 80 above)
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: We also need both `scope name` and `stream name` to be able to initialize the `DelegationTokenProvider` here. The scope name is present as an instance variable, but not the stream name. So, I haven't been able to make this change, and I am using a `Segment` object for the purpose, which contains both scope name and stream name.  Is there a way I can obtain the stream name without going through any hoops?

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 74 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: The intention here was indeed to block for the new token when the existing one is nearing expiry.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 75 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've fixed it now.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 76 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I've taken care of it. Please see if it looks good now.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 78 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I have changed this block of code significantly. Please take a look and see if you still have this comment. I wanted to have both state mutations of the future to and from null in the same method so it is easy to understand the logic.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 84]
```diff
@@ -0,0 +1,236 @@
...
+            //    {"sub": "subject","aud": "segmentstore","iat": 1569837384,"exp": 1569837434}
+            Pattern pattern = Pattern.compile("\"exp\":\\s?(\\d+)");
+            Matcher matcher = pattern.matcher(json);
+            if (matcher.find()) {
+               // Will look like this, if a match is found: "exp": 1569837434
+               String matchedString = matcher.group();
+
+               String[] expiryTimeFieldParts = matchedString.split(":");
+               if (expiryTimeFieldParts != null && expiryTimeFieldParts.length == 2) {
+                   result = Long.parseLong(expiryTimeFieldParts[1].trim());
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Fixed.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 85]
```diff
@@ -126,111 +175,70 @@ public JwtTokenProviderImpl(String token, Controller controllerClient, String sc
...
-               String[] expiryTimeFieldParts = matchedString.split(":");
-               if (expiryTimeFieldParts != null && expiryTimeFieldParts.length == 2) {
-                   result = Long.parseLong(expiryTimeFieldParts[1].trim());
-               }
-            }
-        }
-        return result;
+    private CompletableFuture<Void> recreateToken() {
+        return controllerClient.getOrRefreshDelegationTokenFor(scopeName, streamName)
+                .thenApply(s -> new DelegationToken(s, extractExpirationTime(s)))
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Please combine these 2 callbacks into one. There's no need to add overhead when you can just have one callback that does both of these.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java (hunk 80 above)
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java]: Yes: `fromStreamCut.asImpl().getStream()`

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 86]
```diff
@@ -0,0 +1,245 @@
...
+
+    @VisibleForTesting
+    static Long extractExpirationTime(String token) {
+        if (token == null || token.trim().equals("")) {
+            return null;
+        }
+        String[] tokenParts = token.split("\\.");
+
+        // JWT is of the format abc.def.ghe. The middle part is the body.
+        String encodedBody = tokenParts[1];
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I've handled this condition in the latest commit that I've just pushed.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 87]
```diff
@@ -0,0 +1,245 @@
...
+               // Should look like this, if a proper match is found: "exp": 1569837434
+               String matchedString = matcher.group();
+
+               String[] expiryTimeFieldParts = matchedString.split(":");
+               if (expiryTimeFieldParts != null && expiryTimeFieldParts.length == 2) {
+                   try {
+                       result = Long.parseLong(expiryTimeFieldParts[1].trim());
+                   } catch (NumberFormatException e) {
+                       // ignore
+                       log.debug(e.getMessage());
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've made this change as suggested.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 88]
```diff
@@ -1516,9 +1516,34 @@ public boolean mustLog() {
 
     @Data
     public static final class AuthTokenCheckFailed implements Reply, WireCommand {
+
+        final ErrorCode errorCode;
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: I've modified the layout of the fields according to serialization order, as suggested.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java (hunk 85 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: Sure, I've collapsed the two callbacks into one as suggested.
