### PR TITLE
Issue 1383: Fixing port conflicts in parallel gradle builds. Also enabled gradle parallel builds by default

### LINKED ISSUE #1383: gradle parallel build fails due to port conflicts
**Problem description**
TestUtils.getAvailableListenPort() does not provide unique ports when executed in a multi-process environment, which is the case when we enable parallel gradle builds.

**Problem location**
TestUtils.getAvailableListenPort

**Suggestions for an improvement**
We could see the port start value randomly for a given process so that the port ranges used to fetch free ports don't clash.

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
When we use TestUtils.getAvailableListenPort() from parallel processes this method starts scanning for ports in the same sequence and hence can cause port conflicts when they find the same port to be available. To avoid this we will now start scanning for ports from a randomized start index within the same range. The probability of port clashes will reduce significantly.

**Purpose of the change**
Fixes #1383 

**What the code does**
Avoids port clashes.

**How to verify it**
Enable gradle parallel builds (Enable org.gradle.parallel=true in gradle properties) and execute ./gradlew clean build

### CODE REVIEW

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java [hunk 1]
```diff
@@ -22,8 +23,11 @@
 public class TestUtils {
     // Linux uses ports from range 32768 - 61000.
     private static final int BASE_PORT = 32768;
-    private static final int MAX_PORT_COUNT = 28232;
-    private static final AtomicInteger NEXT_PORT = new AtomicInteger(1);
+    private static final int MAX_PORT_COUNT = 28233;
+
+    // We use a random start position here to avoid ports conflicts when this method is executed from multiple processes
+    // in parallel. This is needed since the processes will contend for the same port sequence.
+    private static final AtomicInteger NEXT_PORT = new AtomicInteger(new Random().nextInt(MAX_PORT_COUNT));
```
Comment (shrids) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: This implies two test tasks e.g: :client:test and :controller:test running as different processes can fall in the same range, with a low probability.

**Comment by shrids** [comment]
Property `maxParallelForks ` is 1 by default.  This indicates the max number of forked test processes to execute in parallel.  By enabling `org.gradle.parallel=true` we are ensuring that the Test task of different projects are run in parallel, but tests internal to a sub-project / test task are run sequentially.

File: test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java (hunk 1 above)
Comment (skrishnappa) [inline test/testcommon/src/main/java/io/pravega/test/common/TestUtils.java]: Yes, earlier it was guaranteed to clash, now its a low probability

**Comment by skrishnappa** [comment]
>> Property maxParallelForks is 1 by default
@shrids Since we have many modules sub tasks I see that all the launched gradle processes (8 on my setup) is active. Also on travis the build time has reduce to 12 mins, from 20. I guess we can experiment with maxParallelForks too and improve this further. Filed a task for this #1385

File: gradle.properties [hunk 2]
```diff
@@ -55,3 +55,6 @@ bookkeeperBaseTag=pravega/bookkeeper
 signing.keyId=05949AF6
 # This will be defaulted to ~/.gnupg/secring.gpg if not provided as a command line property
 signing.secretKeyRingFile=
+
+# Enable parallel builds
+org.gradle.parallel=true
```
Comment (fpj) [inline gradle.properties]: Let's do this separately, I'd rather not mix up concerns here.

Comment (skrishnappa) [inline gradle.properties]: Reverted. We can enable this as part of issue #1385.
