### PR TITLE
Issue 6444: Duplicate DataFrames detected upon ledger rollover

### LINKED ISSUE #6444: Duplicate DataFrames detected upon ledger rollover
**Describe the bug**
In one of our test cluster, we observed the following some time back:
- This is a partial DU issue. All the user and system data are still present in the system after the fix.
- Segment Container 12 was stuck in an unrecoverable state permanently.
- The reason for Segment Container 12 to be unrecoverable was the duplication of 2 entries (Data Frames) in the associated Durable Log + the need to recover the container while the data duplication was in place.
- The fact that the duplicate entries are the 2 last ones of one ledger and the 2 first ones of the next ledger suggest that the problem could have happened during ledger rollover.
- Network glitches could be also a contributing factor for this issue; i.e., it is also possible that the root cause is associated with Segment Store's Bookkeeper client retrying writes during network glitches/partitions.

We have modified the code of the CLI to recover all entries, irrespective of whether they have the right sequence ids or not (i.e., we skip the actual recovery, we just want to see the DataFrames output). With this, we have been able to locate the problem: there are exactly 2 DataFrames repeated (374119, 374120) in consecutive ledgers 1020740 and 1068746: 

```
Begin DataFrame: Sequence = 17179884211, LedgerId = 1020740, EntryId = 15027.
 @[11,191]: UpdateAttributesOperation: SequenceNumber = 374118, SegmentId = 12, Attributes = 5.
End DataFrame: Length=191/202.
Begin DataFrame: Sequence = 17179884212, LedgerId = 1020740, EntryId = 15028.
 @[11,92]: UpdateAttributesOperation: SequenceNumber = 374119, SegmentId = 12, Attributes = 2.
End DataFrame: Length=92/103.
Begin DataFrame: Sequence = 17179884213, LedgerId = 1020740, EntryId = 15029.
 @[11,190]: StreamSegmentAppendOperation: SequenceNumber = 374120, SegmentId = 12, Offset = 30393482, Length = 154, Attributes = 0.
End DataFrame: Length=190/201.
Begin DataFrame: Sequence = 21474836480, LedgerId = 1068746, EntryId = 0.
 @[11,92]: UpdateAttributesOperation: SequenceNumber = 374119, SegmentId = 12, Attributes = 2.
End DataFrame: Length=92/103.
Begin DataFrame: Sequence = 21474836481, LedgerId = 1068746, EntryId = 1.
 @[11,190]: StreamSegmentAppendOperation: SequenceNumber = 374120, SegmentId = 12, Offset = 30393482, Length = 154, Attributes = 0.
End DataFrame: Length=190/201.
Begin DataFrame: Sequence = 21474836482, LedgerId = 1068746, EntryId = 2.
 @[11,111]: StreamSegmentAppendOperation: SequenceNumber = 374121, SegmentId = 12, Offset = 30393636, Length = 76, Attributes = 0.
End DataFrame: Length=111/122.
```

[container-recover-all-entries.log](https://github.com/pravega/pravega/files/7588719/container-recover-all-entries.log)

The rest of entries seem ok. This problem seems related to handling outstanding writes while rolling over ledgers (perhaps while Bookkeeper connectivity failures happen).

**To Reproduce**
Hard to do, only observed once. We have build this tool to detect this kind of issues proactively: https://github.com/pravega/pravega/pull/6427

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Add a mechanism to safely discard duplicate DataFrames upon Segment Container recovery.

**Purpose of the change**  
Fixes #6444.

**What the code does**  
The problem consists of that, in very rare situations, we could have one or a small number of entries duplicate during a rollover due to the original issue described in #6444. To solve this problem, this PR proposed to safely discard duplicate entries in Bookkeeper Logs, as follows:
- `DataFrameReader` is able to discard duplicate log items read if:
  - The sequence number of the new log item read is lower than the last sequence number read (indicates a duplicate).
  - The duplicate entry is related to one of the recently tracked log entries:
    - The max number of tracked entries is defined in `maxOverlapToCheckForDuplicates`.
  - The internal information of the `DataFrame` is the same both the existing and the duplicate entry.
    - We use `DataFrameRecord.RecordInfo` from both entry to do that comparison that goes beyond the sequence number.
- If the duplicate entry is related to a log entry before `maxOverlapToCheckForDuplicates` or if the comparison of `DataFrameRecord.RecordInfo` do not match, a `DataCorruptionException` is thrown anyway.
- In case of setting `maxOverlapToCheckForDuplicates=0`, `DataFrameReader` does not tolerate duplicates (existing behavior).

**How to verify it**  
Added tests to simulate duplication of entries (using different values for `maxOverlapToCheckForDuplicates`).
DR testing being performed using the discard duplicates approach to see if there is any side effect.
System tests passed: test-pravega-continuous/4590

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 1]
```diff
@@ -105,12 +105,13 @@ public DataFrameRecord<T> getNext() throws DataCorruptionException, DurableDataL
                     DataFrameRecord.RecordInfo recordInfo = this.dataFrameInputStream.endRecord();
                     long seqNo = logItem.getSequenceNumber();
                     if (seqNo <= this.lastReadSequenceNumber) {
-                        throw new DataCorruptionException(String.format("Invalid Operation Sequence Number. Expected: larger than %d, found: %d.",
-                                this.lastReadSequenceNumber, seqNo));
+                        // In case there is a duplicate entry, we can safely discard it (see https://github.com/pravega/pravega/issues/6444)
+                        log.warn("Invalid Operation Sequence Number. Expected: larger than {}, found: {}. Discarding entry.",
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:109]: Is there a way to actually verify if both entries are indeed same (same payload not not just the seqNo) ?

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:109]: We depart from the assumptions that i) only one `BookkeeperLog` writes to its own ledgers (this is guaranteed by fencing), ii) the `OperationProcessor` keeps the strict monotonically increasing sequence numbers of operations (this is  checked in `OperationProcessor` and `SreamSegmentContainerMetadata`).

Assuming that, there could be other scenarios: i) there are duplicate entries but one of them is partially written or corrupted (in this case, the CRC check in Bookkeeper may notice an integrity problem in the entry contents), ii) The entry is correctly written, but is unrelated to Pravega (this would trigger a deserialization error during recovery).

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:109]: We depart from the assumptions that i) only one `BookkeeperLog` writes to its own ledgers (this is guaranteed by fencing), ii) the `OperationProcessor` keeps the strict monotonically increasing sequence numbers of operations (this is  checked in `OperationProcessor` and `SreamSegmentContainerMetadata`).

Assuming that, there could be other scenarios: i) there are duplicate entries but one of them is partially written or corrupted (in this case, the CRC check in Bookkeeper may notice an integrity problem in the entry contents), ii) The entry is correctly written, but is unrelated to Pravega (this would trigger a deserialization error during recovery).

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java]: @sachin-j-joshi I have added verification of internal info of the DataFrame to have certainty (beyond the sequence number) that the entry is actually the same.

**Comment by RaulGracia** [comment]
Based on a suggestion from @andreipaduroiu, I have added the following changes to this PR:
- Discard duplicates if the contents of log items are the same (this is done comparing `DataFrameRecord.RecordInfo` from the original and duplicate entries).
- Keep track of a limited amount of read entries from the log to check for duplicates. By default, this number is 0, which leads to the original behavior in which no duplicates are tolerated.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 2]
```diff
@@ -45,6 +49,10 @@
     @Setter (AccessLevel.PROTECTED)
     private long lastReadSequenceNumber;
     private boolean closed;
+    private final String traceObjectId;
+    @Getter (AccessLevel.PACKAGE)
+    private final AtomicInteger maxOverlapToCheckForDuplicates = new AtomicInteger(0); // Default, no tolerance to repeated elements.
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:54]: Why is this mutable and not just a constant? If it's for testing perhaps a better way would be to make a method as a getter and override it in the test.

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java]: Fixed: set this as a final int set via constructor.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 3]
```diff
@@ -137,5 +170,87 @@ public DataFrameRecord<T> getNext() throws DataCorruptionException, DurableDataL
...
+    private boolean compareDataFrameEntryInfos(DataFrameRecord.EntryInfo originalEntryInfo, DataFrameRecord.EntryInfo duplicateEntryInfo) {
+        return originalEntryInfo.getFrameOffset() == duplicateEntryInfo.getFrameOffset()
+                && originalEntryInfo.getLength() == duplicateEntryInfo.getLength();
+    }
+
+    /**
+     * Helper class to keep track of recent read items from the log in order to check if it is safe to discard duplicate
+     * entries that could have been written to the log.
+     */
+    private static class DuplicateEntryTracker {
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:230]: If it's intended this should be annotated @NotThreadSafe.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 4]
```diff
@@ -45,6 +48,10 @@
     @Setter (AccessLevel.PROTECTED)
     private long lastReadSequenceNumber;
     private boolean closed;
+    private final String traceObjectId;
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:51]: DataFrameReader does not appear to be thread safe. If that OK and intended it should be annotated as @NotThreadSafe

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:51]: Yes, I think it is intended because is supposed to be executed by one thread upon bootstrap. But yes, we can add that annotation to the class to make it explicit.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java (hunk 3 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:230]: Sure.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 5]
```diff
@@ -104,13 +127,23 @@ public DataFrameRecord<T> getNext() throws DataCorruptionException, DurableDataL
                     T logItem = this.serializer.deserialize(this.dataFrameInputStream);
                     DataFrameRecord.RecordInfo recordInfo = this.dataFrameInputStream.endRecord();
                     long seqNo = logItem.getSequenceNumber();
+                    trackLastReadLogItem(seqNo, recordInfo);
                     if (seqNo <= this.lastReadSequenceNumber) {
-                        throw new DataCorruptionException(String.format("Invalid Operation Sequence Number. Expected: larger than %d, found: %d.",
-                                this.lastReadSequenceNumber, seqNo));
+                        // We have found a repeated item while reading the log. We need to discriminate between a harmless
+                        // duplicate entry or some other kind of data corruption.
+                        if (isHarmlessDuplicateEntry(seqNo, recordInfo)) {
```
Comment (abhinb) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:134]: since this is done for every item read during recovery, would this affect recovery times in case of large recoveries?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 6]
```diff
@@ -137,5 +170,87 @@ public DataFrameRecord<T> getNext() throws DataCorruptionException, DurableDataL
...
+        if (!duplicateEntryTracker.containsKey(seqNo)) {
+            log.warn("{}: Seems that we have found a duplicate {}, but it exceeds the max number of tracking elements {}.",
+                    this.traceObjectId, seqNo, this.maxOverlapToCheckForDuplicates);
+            return false;
+        }
+
+        // To determine if duplicate log entry is harmless, we use the available internal information of a DataFrame to
+        // check for equality: i) length of DataFrameRecord.EntryInfo list, and ii) compare that all DataFrameRecord.EntryInfo
+        // have the same length and offset within the DataFrame.
+        boolean harmlessDuplicate = duplicateEntryTracker.getEntriesFor(seqNo).size() == recordInfo.getEntries().size();
```
Comment (abhinb) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:206]: cant we fail-fast here?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java (hunk 5 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:134]: This is not done for each item: as you can see, this is inside the `if (seqNo <= this.lastReadSequenceNumber)` block, so this will be only executed in the exceptional case that we find a duplicate.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java (hunk 6 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:206]: Well, it will fail anyway as soon as the next `for` completes, as the `harmlessDuplicate` boolean is updated with `&=`. I could add another `if` clause to return `false` directly, but I thought this makes the code simpler.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java [hunk 7]
```diff
@@ -45,6 +51,10 @@
     @Setter (AccessLevel.PROTECTED)
     private long lastReadSequenceNumber;
     private boolean closed;
+    private final String traceObjectId;
+    @Getter (AccessLevel.PACKAGE)
```
Comment (shshashwat) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java:55]: are we using the getter or intended to use that?

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrameReader.java]: Good catch, you are right this is not necessary anymore.

**Comment by RaulGracia** [comment]
We are carrying out intensive DR tests to reproduce the issue with the code in this PR, and it seems to be dealing well with the original problem. These are some reproductions of the issue:
```
0-pravega-segmentstore-24613ac0-2022-05-25T07-43-31Z.log.gz:2022-05-25 07:26:51,064 4025132 [core-30] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667273. Discarding entry.
0-pravega-segmentstore-24613ac0-2022-05-25T07-43-31Z.log.gz:2022-05-25 07:26:51,064 4025132 [core-30] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667274. Discarding entry.
0-pravega-segmentstore-24613ac0-2022-05-25T07-43-31Z.log.gz:2022-05-25 07:41:51,930 4925998 [core-12] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667273. Discarding entry.
0-pravega-segmentstore-24613ac0-2022-05-25T07-43-31Z.log.gz:2022-05-25 07:41:51,930 4925998 [core-12] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667274. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,200 13424 [core-29] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1483, found: 1483. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,413 13637 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1314. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,413 13637 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1315. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,413 13637 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1316. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,413 13637 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1317. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,414 13638 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1318. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:26,414 13638 [core-25] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1319. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:27,449 14673 [core-14] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 629, found: 628. Discarding entry.
0-pravega-segmentstore-7df42c32-2022-05-23T12-15-10Z.log.gz:2022-05-23 12:01:27,449 14673 [core-14] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 629, found: 629. Discarding entry.
0-pravega-segmentstore-8062dc70-2022-05-24T13-35-27Z.log.gz:2022-05-24 13:35:24,014 4702057 [core-14] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 8324993, found: 8324993. Discarding entry.
0-pravega-segmentstore-8062dc70-2022-05-24T13-35-27Z.log.gz:2022-05-24 13:35:24,969 4703012 [core-22] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 822780, found: 817186. Discarding entry.
0-pravega-segmentstore-8062dc70-2022-05-24T13-35-27Z.log.gz:2022-05-24 13:35:24,970 4703013 [core-22] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 822780, found: 817187. Discarding entry.
1-pravega-segmentstore-22c48108-2022-05-25T09-25-54Z.log.gz:2022-05-25 09:03:44,847 9005141 [core-13] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667273. Discarding entry.
1-pravega-segmentstore-22c48108-2022-05-25T09-25-54Z.log.gz:2022-05-25 09:03:44,847 9005141 [core-13] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 667274, found: 667274. Discarding entry.
1-pravega-segmentstore-a6cb6273-2022-05-23T12-14-49Z.log.gz:2022-05-23 12:01:08,990 4633513 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1483, found: 1483. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1314. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1315. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1316. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1317. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1318. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,950 6906561 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1319, found: 1319. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,996 6906607 [core-12] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 629, found: 628. Discarding entry.
2-pravega-segmentstore-088c66fd-2022-05-23T15-10-37Z.log.gz:2022-05-23 12:01:08,996 6906607 [core-12] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 629, found: 629. Discarding entry.
2-pravega-segmentstore-ca7f9b5f-2022-05-25T11-25-00Z.log.gz:2022-05-25 08:52:21,468 13433 [core-27] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 11087147, found: 11087147. Discarding entry.
2-pravega-segmentstore-ca7f9b5f-2022-05-25T11-25-00Z.log.gz:2022-05-25 09:03:44,890 696855 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1436411, found: 1436410. Discarding entry.
2-pravega-segmentstore-ca7f9b5f-2022-05-25T11-25-00Z.log.gz:2022-05-25 09:03:44,890 696855 [core-9] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 1436411, found: 1436411. Discarding entry.
```

However, inspecting the logs, I realize that in one case, the recovery process attempted to read 2 operations that go far behind the expectation:
```
0-pravega-segmentstore-8062dc70-2022-05-24T13-35-27Z.log.gz:2022-05-24 13:35:24,969 4703012 [core-22] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 822780, found: 817186. Discarding entry.
0-pravega-segmentstore-8062dc70-2022-05-24T13-35-27Z.log.gz:2022-05-24 13:35:24,970 4703013 [core-22] WARN  i.p.s.server.logs.DataFrameReader - Invalid Operation Sequence Number. Expected: larger than 822780, found: 817187. Discarding entry.
```
That is, the `RecoveryProcessor` read operation `822780`, but it got `817186` and `817187`, which are much older operations that the expected for the normal behavior of the issue we are dealing with. The problem is that with the suggestion of keeping just a subset of operations to compare "equality" against a repeated entry, this case would anyway get a `DataCorruptionException`. The reason is that, by default, we keep `MAX_OVERLAP_TO_CHECK_DUPLICATES = 25` to check for equality, and these entries are much older than the last 25 operations (around 5600 operations older). cc/ @andreipaduroiu @abhinb @tkaitchuck @sachin-j-joshi

**Comment by RaulGracia** [comment]
@tkaitchuck @sachin-j-joshi @abhinb this change has been successfully tested for several days inducing unexpected pod restarts. We can see in the logs that this change properly discards duplicate entries in logs when they appear. Please, let's do another pass so we can merge this one.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM

**Review by abhinb — APPROVED** [review]
