### PR TITLE
Issue 1621: Increased gRPC client keepalive timeout to 6 minutes

### LINKED ISSUE #1621: Controller gRPC server is rejecting client keep-alives
**Problem description**
The gRPC server is rejected client keep-alive pings with the following exceptions, hence all gRPC calls taking longer than 1 minute fails:

Jul 20, 2017 11:02:42 AM io.grpc.netty.NettyClientHandler$1 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jul 20, 2017 11:02:42 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 120,000,000,000
2017-07-20 11:02:42,709 61492 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call failed with server error: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings
2017-07-20 11:02:42,710 61493 [grpc-default-executor-0] WARN  i.p.c.stream.impl.ControllerImpl - scaleStream failed: 
java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
    at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onError(ControllerImpl.java:660)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
    at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Bandwidth exhausted
HTTP/2 error code: ENHANCE_YOUR_CALM
Received Goaway
too_many_pings
    at io.grpc.Status.asRuntimeException(Status.java:543)
    ... 11 common frames omitted
2017-07-20 11:02:42,710 61493 [grpc-default-executor-0] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE scaleStream@3186427135754 (elapsed=59805415us).

**Problem location**
ControllerImpl

**Suggestions for an improvement**
Increase the keep-alive timeout to be within the gRPC server's permissible value.

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
Increased keepalive timeout to 6 minutes from 1 minute. The earlier 1 minute keep-alives were being rejected by the gRPC server since it was less than the permissible server keep-alive limit of 5 minutes. 

**Purpose of the change**
Fixes #1621 

**What the code does**
Increases keepalive timeout

**How to verify it**
Added test case to simulate long running RPC with different keep-alive timeout configuration

### CODE REVIEW

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java [hunk 1]
```diff
@@ -539,17 +545,49 @@ public void deleteScope(ScopeInfo request, StreamObserver<DeleteScopeStatus> res
...
+                .scalingPolicy(ScalingPolicy.fixed(1))
+                .build());
+        AssertExtensions.assertThrows("Should throw Exception", createStreamStatus,
+                throwable -> throwable instanceof StatusRuntimeException);
+
+        // Verify that the same RPC with permissible keepalive time succeeds.
+        int serverPort2 = TestUtils.getAvailableListenPort();
+        ServerImpl testServer = NettyServerBuilder.forPort(serverPort2)
+                .addService(testServerImpl)
+                .permitKeepAliveTime(5, TimeUnit.SECONDS)
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Should this be 5 minutes instead?

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java [hunk 2]
```diff
@@ -539,17 +545,49 @@ public void deleteScope(ScopeInfo request, StreamObserver<DeleteScopeStatus> res
...
+                .build()
+                .start();
+        controller = new ControllerImpl(NettyChannelBuilder.forAddress("localhost", serverPort2)
+                .keepAliveTime(10, TimeUnit.SECONDS).usePlaintext(true));
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: I'm confused about these configuration values, should this be really 10 seconds?

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java (hunk 1 above)
Comment (skrishnappa) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Should be anything >=5. With exactly 5 there could be timing related issues which I want to avoid. Hence using a greater value here.

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java (hunk 2 above)
Comment (skrishnappa) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: This is to simulate the issue here. Default server keepalive is 5 min, so to verify keepalive we need to wait longer than this. Hence to reduce test time I have created a test server with a lower keepalive bound. Setting client once with keepalive less than the bound and once greater than.

Comment (skrishnappa) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Also grpc does not accept a value less than 10s, so using the lowest possible value here

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java (hunk 1 above)
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: It should be MINUTES, not SECONDS, right?

Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: I think I see the confusion now. The default minimum keepalive is 5 minutes, but here you are setting it to 5 seconds to reduce test time.

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java [hunk 3]
```diff
@@ -539,17 +545,49 @@ public void deleteScope(ScopeInfo request, StreamObserver<DeleteScopeStatus> res
...
     public void tearDown() {
-        fakeServer.shutdown();
+        testGRPCServer.shutdownNow();
+    }
+
+    @Test
+    public void testKeepAlive() throws IOException, ExecutionException, InterruptedException {
+
+        // Verify that keep-alive timeout less than permissible by the server results in a failure.
+        ControllerImpl controller = new ControllerImpl(NettyChannelBuilder.forAddress("localhost", serverPort)
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Here we are setting the client keepalive value to 10s, but the default is 5 minutes, so we expect it to fail, yes?

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java (hunk 2 above)
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: OK here we are setting the server minimum to 5s, but the client side to 10s, so it should be ok.

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java (hunk 3 above)
Comment (skrishnappa) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Yes that's right, that's why we assert that it throws the grpc exception
