### PR TITLE
Issue 2273: Prevent stalling reader following a connection failure. 

### LINKED ISSUE #2273: Reader does not respond post Segment container migration.
**Problem description**
It was observed that the Controller's AbortEvent processor is not able to read events from _abortStream when the Segment container migration happen. (This issue was observed during the ControllerFailover system test run.) 
On further investigation it was observed that the `reader.readNextEvent(timeout)` is blocked for more than 10 mins i.e the AbortEvent was never read from the _abortStream.

The logs found during the current investigation are listed below.

1) Test logs: test aborts the transaction.
```2018-01-23 06:40:04,075 9802 [Time-limited test] INFO  i.p.t.system.ControllerFailoverTest - Trying to abort transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, by sending request to controller at tcp://172.16.18.21:9092```

2)Controller writes to abortStream.
```scrambler-slave-1-container-2/controller.log:2018-01-23 06:40:04,133 2922513 [controllerpool-3] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, sent request to _abortStream
scrambler-slave-1-container-2/controller.log:2018-01-23 06:42:09,594 3047974 [controllerpool-63] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77, sent request to _abortStream
```
3) Controller reads the abort stream event @ 06:57 17 mins after the event was written.
```scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,101 3965481 [controllerpool-59] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77 on stream testFailoverScopegepsh/testFailoverStreamJscoF
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,304 3965684 [controllerpool-11] DEBUG i.p.c.s.e.r.AbortRequestHandler - Aborting transaction 7a16b5ca-14b4-4f53-8fe0-a2f2057e0e77 on stream testFailoverScopegepsh/testFailoverStreamJscoF
```

4) The additional logging indicates the client read @ 06:36:12 never completed.

``` scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:36:12,963 2691343 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Attempt to read event EventProcessor[abortStreamReaders:0]
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:15,383 3953763 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Attempt to read event EventProcessor[abortStreamReaders:0]
scrambler-slave-1-container-2/controller_2018-01-23.21.log:2018-01-23 06:57:27,043 3965423 [EventProcessor[abortStreamReaders:0]] DEBUG i.p.c.e.impl.EventProcessorCell - ==> Event read EventProcessor[abortStreamReaders:0] is EventReadImpl(eventSequence=Sequence(highOrder=0, lowOrder=307), event=null, position=PositionImpl(ownedSegments=[Segment(scope=_system, streamName=_abortStream, segmentNumber=1), Segment(scope=_system, streamName=_abortStream, segmentNumber=0)]), eventPointer=null, checkpointName=921294f9-3db9-4b41-906e-4c6fcf51323f) 
```
5) 
After the read request @06:36:12, the reader loses connection to _abortStream/0. 
Then it receives
```2018-01-23 06:36:14,809 2693189 [EventProcessor[abortStreamReaders:0]] WARN  i.p.c.s.impl.SegmentInputStreamImpl - Encountered an exception while reading for Segment(scope=_system, streamName=_abortStream, segmentNumber=1)
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
```
After this there are 12 such attempts to connect to the _abortStream/1 and then there are no logs related to connection attempts.
```
2018-01-23 06:38:38,817 2837197 [epollEventLoopGroup-2-6] INFO  i.p.c.s.i.AsyncSegmentInputStreamImpl - Closing connection to segment Segment(scope=_system, streamName=_abortStream, segmentNumber=0) with exception: {}
io.pravega.shared.protocol.netty.ConnectionFailedException: null
    at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:58)
```

Interestingly this issue was never seen once the controller disabled automatic checkpointing.

[controller_2018-01-23.21.log.zip](https://github.com/pravega/pravega/files/1662530/controller_2018-01-23.21.log.zip)

**Problem location**
Reader.

**Suggestions for an improvement**
Investigate further and fix the issue.

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**
Previously if `AsyncSegmentInputStream` threw a `RetriesExhaustedException`, the `issueRequestIfNeeded()` method would get invoked creating a new request, then when `handleRequest()` was invoked by the `read()` call, the timeout would be ignored and the call would block. 
This changes the logic to not issue a new request inside of `handleRequest()` so it will instead throw rather than issuing a new request and blocking on it. This will prevent the reader from stalling on one segment following an extended connection failure.

**Purpose of the change**
Fixes #2273 

**What the code does**
Throws the exception rather than re-issuing the request. This way the request is already completed in `handleRequest()`.

**How to verify it**
New unit test added to assert correct behavior.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 1]
```diff
@@ -168,10 +168,15 @@ private boolean dataWaitingToGoInBuffer() {
...
-        if (outstandingRequest.isCompletedExceptionally()) {
-            issueRequestIfNeeded();
+        SegmentRead segmentRead;
+        try {
+            segmentRead = outstandingRequest.join();
+        } catch (Exception e) {
+            if (Exceptions.unwrap(e) instanceof SegmentTruncatedException) {
+                receivedTruncated = true;
+            }
+            throw e;
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: The exceptions that can be thrown by outstandingRequest.join() are 
1. RetriesExhaustedException (This will be thrown by EventStreamReader.readNextEvent(timeout))
2. ConnectionClosedException. (this will never happen in the case here.)
3. SegmentTruncatedException (this is already handled in the code.)


`SegmentInputStreamImpl#issueRequestIfNeeded` currently reissues a read if `outstandingRequest `completes exceptionally and if the exception is not an `ERROR `or `InterruptedException `or `CancellationException`.

1) We could Modify IssueRequestIfNeeded to handle RetriesExhaustedExeption too right?
2) Why even have this check since AysncSegmentInputStream.read() will not have any other exceptions apart from the 3 listed above.

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Excellent points. By handling this in handelRequest() we can simplify issueRequestIfNeeded().
I've updated the code to reflect this.
