### PR TITLE
Issue 2466: Accept standalone config through system properties.

### LINKED ISSUE #2466: Standalone mode should use config.properties for SSL configuration
**Problem description**
The standalone module serves as an in-process emulator and as a standalone program.  When used as a program, it would be best to use `config.properties` rather than use a hardcoded SSL configuration (see [InProcPravegaCluster](https://github.com/pravega/pravega/blob/1ab37524d535d453ebfc4bc92f3342f6f715c9d6/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L320) and [LocalPravegaEmulator](https://github.com/pravega/pravega/blob/1ab37524d535d453ebfc4bc92f3342f6f715c9d6/standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java#L61)).  It is questionable as to whether `../config` is appropriate in any case.

**Problem location**
- `io.pravega.local.LocalPravegaEmulator`
- `io.pravega.local.InProcPravegaCluster`

**Suggestions for an improvement**
1. Remove the hardcoded config elements.
2. Add commented-out sections to the default `config.properties`.
3. Do not rely on any external files in emulation library mode.
4. Fix `startStandalone` task in `build.gradle` (at this time it crashes with invalid config location).
5. Add the `config` directory to the distribution output for standalone module so that the following works as expected:
```
$ gradle standalone:installDist
$ cd standalone\build\install\pravega-standalone
$ bin/pravega-standalone
```

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
- Move security related config in standalone from hard coding to config.
- Update tests to use this.

**Purpose of the change**
This fixes #2466. The config can be specified through system properties. Currently standalone does not pick the config up from config properties.

**What the code does**
Removes hard coding of security related config from `standalone` and accepts it from system properties.

**How to verify it**
1. Unit tests 
2. Specify properties through system properties and see them changed in the standalone/

### CODE REVIEW

File: docker/pravega/entrypoint.sh [hunk 1]
```diff
@@ -112,6 +112,12 @@ configure_standalone() {
     add_system_property "singlenode.zkPort" "2181"
     add_system_property "singlenode.controllerPort" "9090"
     add_system_property "singlenode.segmentstorePort" "12345"
+    add_system_property "singlenode.certFile" "./config/cert.pem"
+    add_system_property "singlenode.keyFile" "./config/key.pem"
+    add_system_property "singlenode.passwdFile" "./config/passwd"
```
Comment (EronWright) [inline docker/pravega/entrypoint.sh]: Could these config paths be made more reliable by basing them on the script path?  e.g. ([ref](https://stackoverflow.com/a/246128/3026310))
```
BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
add_system_property "singlenode.certFile" "${BINDIR}/../config/cert.pem"
```

Otherwise we're assuming that the current directory is the installation root.

Comment (EronWright) [reply docker/pravega/entrypoint.sh]: Maybe the default should be an insecure cluster, and avoid baking in these secrets.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java [hunk 2]
```diff
@@ -266,12 +275,12 @@ private void startLocalSegmentStore(int segmentStoreId) throws Exception {
                         .with(ReadIndexConfig.CACHE_POLICY_MAX_SIZE, 128 * 1024 * 1024L))
                 .include(AutoScalerConfig.builder()
                         .with(AutoScalerConfig.CONTROLLER_URI, "tcp://localhost:" + controllerPorts[0])
```
Comment (EronWright) [inline standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: The auto-scaler's controller-uri, shouldn't it be using a different uri scheme depending on `enableTls`?

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java [hunk 3]
```diff
@@ -20,6 +20,12 @@
     public final static Property<Integer> SEGMENTSTORE_PORT = Property.named("segmentstorePort", 6000);
     public final static Property<Integer> CONTROLLER_PORT = Property.named("controllerPort", 9090);
     public final static Property<Integer> REST_SERVER_PORT = Property.named("restServerPort", 9091);
+    public final static Property<String> CERT_FILE = Property.named("certFile", "../config/cert.pem");
+    public final static Property<String> KEY_FILE = Property.named("keyFile", "../config/key.pem");
+    public final static Property<String> PASSWD_FILE = Property.named("passwdFile", "../config/passwd");
+    public final static Property<String> USER_NAME = Property.named("userName", "admin");
+    public final static Property<String> PASSWD = Property.named("passwd", "1111_aaaa");
+
```
Comment (EronWright) [inline standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: Why do we have these default values?   If you want a 'secure by default' configuration, you need to generate a cert and generate a passwd file.  If not, these defaults complicate life without a real benefit.

File: standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java [hunk 4]
```diff
@@ -52,6 +52,11 @@ public void setUp() throws Exception {
                                            .restServerPort(TestUtils.getAvailableListenPort())
                                            .enableAuth(authEnabled)
                                            .enableTls(tlsEnabled)
+                                           .certFile("../config/cert.pem")
+                                           .keyFile("../config/key.pem")
+                                           .passwdFile("../config/passwd")
+                                           .userName("admin")
+                                           .passwd("1111_aaaa")
```
Comment (EronWright) [inline standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java]: These lines assume that the working directory of the test is the standalone directory, is that OK?   Is the gradle project configured to that effect?

Comment (arvindkandhare) [reply standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java]: Yes. The tests work with gradle.

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java (hunk 3 above)
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: `secure by default` is chosen by `enableAuth` and `enableTls` settings. These defaults are here so that users can just set one value to toggle between secure and insecure options.
The default is insecure.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java (hunk 2 above)
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: Fixed. Choosing scheme based on config setting.

File: docker/pravega/entrypoint.sh [hunk 5]
```diff
@@ -112,6 +112,7 @@ configure_standalone() {
     add_system_property "singlenode.zkPort" "2181"
     add_system_property "singlenode.controllerPort" "9090"
     add_system_property "singlenode.segmentstorePort" "12345"
+
```
Comment (andreipaduroiu) [inline docker/pravega/entrypoint.sh]: I don't think this change is necessary.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java [hunk 6]
```diff
@@ -101,15 +101,19 @@
 
     private String zkUrl;
     private boolean startRestServer = true;
+    private String userName;
```
Comment (andreipaduroiu) [inline standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: make all of these `final`

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java [hunk 7]
```diff
@@ -101,15 +101,19 @@
...
+    private String passwd;
+    private String certFile;
+    private String keyFile;
+    private String passwdFile;
 
     @Builder
     public InProcPravegaCluster(boolean isInProcZK, String zkUrl, int zkPort, boolean isInMemStorage,
```
Comment (andreipaduroiu) [inline standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: This constructor's arg list is getting pretty big. Should we consider just passing in `SingleNodeConfig` and picking the values from there? That will also help reduce the number of private fields since we can just hold a pointer to the config object.

File: standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java [hunk 8]
```diff
@@ -22,7 +21,9 @@
     private final InProcPravegaCluster inProcPravegaCluster;
 
     @Builder
-    private LocalPravegaEmulator(int zkPort, int controllerPort, int segmentStorePort, int restServerPort, boolean enableAuth, boolean enableTls) {
+    private LocalPravegaEmulator(int zkPort, int controllerPort, int segmentStorePort, int restServerPort,
```
Comment (andreipaduroiu) [inline standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java]: Same comment about the constructor as for `InProcPravegaCluster`

File: standalone/src/main/java/io/pravega/local/SingleNodeConfig.java [hunk 9]
```diff
@@ -20,6 +20,15 @@
     public final static Property<Integer> SEGMENTSTORE_PORT = Property.named("segmentstorePort", 6000);
     public final static Property<Integer> CONTROLLER_PORT = Property.named("controllerPort", 9090);
     public final static Property<Integer> REST_SERVER_PORT = Property.named("restServerPort", 9091);
+    public final static Property<String> CERT_FILE = Property.named("certFile", "../config/cert.pem");
+    public final static Property<String> KEY_FILE = Property.named("keyFile", "../config/key.pem");
+    public final static Property<String> PASSWD_FILE = Property.named("passwdFile", "../config/passwd");
```
[the remark this answers is not in the document]
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/SingleNodeConfig.java]: Removed defaults.

File: docker/pravega/entrypoint.sh (hunk 5 above)
Comment (arvindkandhare) [reply docker/pravega/entrypoint.sh]: Removed.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java (hunk 6 above)
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: Using class level builder pattern now.

File: standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java (hunk 7 above)
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java]: Using class level lombok builder pattern to ease this.

File: standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java (hunk 8 above)
Comment (arvindkandhare) [reply standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java]: Using class level lombok builder pattern.

**Comment by EronWright** [comment]
Waiting for @fpj to review.

File: build.gradle [hunk 10]
```diff
@@ -519,10 +519,11 @@ project('standalone') {
     mainClassName = "io.pravega.local.LocalPravegaEmulator"
     applicationDefaultJvmArgs = ["-server", "-Xmx4g", "-XX:+HeapDumpOnOutOfMemoryError",
                                  "-Dlogback.configurationFile=PRAVEGA_APP_HOME/conf/logback.xml",
+                                 "-Dsinglenode.configurationFile=PRAVEGA_APP_HOME/conf/standalone-config.properties",
                                  "-Dlog.dir=PRAVEGA_APP_HOME/logs",
                                  "-Dlog.name=pravega",
                                  "-Xdebug",
-                                 "-Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=y"]
+                                 "-Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n"]
```
Comment (fpj) [inline build.gradle]: This change has been already merged here:

https://github.com/pravega/pravega/pull/2489

Comment (arvindkandhare) [reply build.gradle]: Fixed. Synced with the latest master.
