### PR TITLE
Issue 4702: (SegmentStore) Fixed a deadlock condition in the Read Index.

### LINKED ISSUE #4702: Read Index Deadlock with concurrent Storage Reads that hit a full cache
**Problem description**
Steps:
1. Segment 1: Storage Read Complete -> Ack -> Insert in Index -> Acquire (ReadIndex1.Lock[Thread1]) -> Insert in Cache [Request1]
 2. Segment 2: Storage Read Complete -> Ack -> Insert in Index -> Acquire (ReadIndex2.Lock[Thread2]) -> Insert in Cache [Request2]
 3. Cache is full. Deadlock occurs if:
 3.1. [Request1] invokes Cache Eviction, which wants to acquire ReadIndex2.Lock, but it is owned by Thread2.
 3.2. [Request2] invokes Cache Eviction, which wants to acquire ReadIndex1.Lock, but it is owned by Thread1.

**Problem location**
Read Index/CacheManager/Cache

**Suggestions for an improvement**
Break the deadlock by choosing a victim and have it back off and retry.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
Signed-off-by: Andrei Paduroiu <andrei.paduroiu@emc.com>

**Change log description**  
- Changed the `CacheManager` to reject additional concurrent cache cleanup requests if one is ongoing (as opposed from using a mutex to serialize them).
- Changed the `DirectMemoryCache` to use an exp backoff retry if it cannot clean up the cache after it detected the cache was full.

**Purpose of the change**  
Fixes #4702.

**What the code does**  
See #4702 for a description of a scenario that leads to this. 
The problem arises if 2 concurrent Storage reads complete at about the same time, and both want to insert into a full cache at the same time. Each callback would execute on its own thread, acquire the Read Index lock associated with their segment, then acquire the Cache Manager eviction lock (whomever does it first), and the Cache Manager would attempt to clean up the index by accessing the other Read Indices (leading to a deadlock).

This has been fixed in 2 steps:
1. Removed the Cache Manager lock altogether. If another request comes in while a cache eviction is in progress, the second request will be rejected. 
2. Changed the Streaming Cache (`DirectMemoryCache`) to use an exp backoff retry in case it is unable to trigger a cache eviction
    - Previously it would retry immediately and give up as soon as the CM said nothing could be done.
    - Now it will try up to 5 times, waiting 50-250ms in between requests. 
    - If after 5 attempts it is not able to do anything, then it will throw up a `CacheFullException`
        - This is the same as before, except that now it adds the extra delays in between checks.
    - On the append path, a `CacheFullException` will shut down the container (this has not changed)
    - On the Storage Read Path, a `CacheFullException` has no effect on the request. The original request has already been ack-ed/sent to the client before the attempt to write to the cache. If we cannot write to the cache due to cache full, we will log a warning now so we can trace this in the logs.

**How to verify it**  
New, specific unit test added that verifies this exact situation. The unit test would not complete if there were a deadlock.

### CODE REVIEW

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java [hunk 1]
```diff
@@ -399,15 +403,23 @@ private DirectMemoryBuffer getNextAvailableBuffer() {
...
         throw new CacheFullException(String.format("%s full: %s.", DirectMemoryCache.class.getSimpleName(), getState()));
     }
 
-    private boolean tryCleanup() {
+    private void tryCleanup(int attempts) {
         val c = this.tryCleanup.get();
-        return c != null && c.get();
+        if (c != null && !c.get()) {
+            // Unable to clean up the cache. Wait a bit, then try again.
+            int sleepMillis = attempts * this.retryDelayBaseMillis.get();
```
Comment (tkaitchuck) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java:418]: RetryPolicy in common is built to do this.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java [hunk 2]
```diff
@@ -47,17 +49,15 @@
...
     @GuardedBy("lock")
     private final Collection<Client> clients;
     private final ScheduledExecutorService executorService;
-    @GuardedBy("lock")
-    private int currentGeneration;
-    @GuardedBy("lock")
-    private int oldestGeneration;
-    @GuardedBy("lock")
-    private CacheState lastCacheState;
+    private final AtomicInteger currentGeneration;
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java:57]: As usual when changing from course locking to fine locking make double sure there aren't code paths that implicitly assume that another thread isn't going to change something in the mean time. For example here one might make the assumption that currentGeneration would not change in the middle of a method, or that current and oldest generation are different or that older is newer that current etc.

**Comment by RaulGracia** [comment]
@tkaitchuck @andreipaduroiu this PR has been validated and works, we will need to cherry pick it to 0.7, so please let's see if we can merge it soon.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/cache/DirectMemoryCache.java:418]: That was my first choice, however `Retry` only retries on exceptions. Here I retry based on the response from a method.

**Comment by RaulGracia** [comment]
@andreipaduroiu it looks like a new experiment has shown some problem with this branch, it will be good to check if the issue is related to these changes or not before merging (my previous commend was based on incomplete testing, apparently).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/CacheManager.java:57]: Agreed. In this class, the only thing changing the internal state is `applyCachePolicyInternal`, which is guarded by the lock. I decided to make all these fields `AtomicXYZ` because I didn't want to acquire some lock just to query them. To be clear, `applyCachePolicyInternal` modifies these values, but they are queried in other places as well, which should be OK for thread safety purposes.

The only exception to this rule is `this.clients`, which keeps track of all the Cache Manager's Clients, and is a collection that is modified when new segments are activated or evicted from memory, hence out of the control of the Cache Manager. However, no external APIs are invoked while using the `clients` lock, so no chance for deadlock there.
