### PR TITLE
Issue 6314: ContainerEventProcessor close method may exhaust threads if executed in bursts

### LINKED ISSUE #6314: ContainerEventProcessor close method may exhaust threads if executed in bursts
**Describe the bug**
In a deployment with hundreds of Segment Containers, instances normally start sequentially. This means that Segment Store 0 initially has assigned all the containers, and then Segment Store 1 comes and takes half of them, so on and so forth. In a scenario with hundreds of Segment Containers, we have found that Segment Store 0 run out of `core` threads and the reason for that is that threads are waiting in the `close()` method of `ContainerEventProcessor`. This is the thread dump:

```
"core-1" #13 daemon prio=5 os_prio=0 cpu=750.46ms elapsed=3638.49s tid=0x00007fd11ce6e800 nid=0x3d waiting on condition  [0x00007fd0dee9e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x0000000617e93600> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.CompletableFuture.timedGet(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.CompletableFuture.get(java.base@11.0.11/Unknown Source)
	at io.pravega.common.concurrent.Futures.lambda$await$1(Futures.java:100)
	at io.pravega.common.concurrent.Futures$$Lambda$1589/0x00000008008a0040.run(Unknown Source)
	at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:121)
	at io.pravega.common.concurrent.Futures.await(Futures.java:98)
	at io.pravega.common.concurrent.Futures.await(Futures.java:85)
	at io.pravega.common.concurrent.AbstractThreadPoolService.close(AbstractThreadPoolService.java:69)
	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl$EventProcessorImpl.close(ContainerEventProcessorImpl.java:339)
	at io.pravega.segmentstore.server.containers.StorageEventProcessor.close(StorageEventProcessor.java:114)
	at io.pravega.segmentstore.storage.chunklayer.GarbageCollector.close(GarbageCollector.java:599)
	at io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.close(ChunkedSegmentStorage.java:701)
	at io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.close(ChunkedSegmentStorage.java:690)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.close(StreamSegmentContainer.java:268)
	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.unregisterContainer(StreamSegmentContainerRegistry.java:203)
	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.lambda$startContainerInternal$1(StreamSegmentContainerRegistry.java:186)
	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry$$Lambda$706/0x0000000800638440.run(Unknown Source)
	at io.pravega.common.concurrent.Services$ShutdownListener.terminated(Services.java:126)
	at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:95)
	at com.google.common.util.concurrent.AbstractService$3.call(AbstractService.java:92)
	at com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue.run(ListenerCallQueue.java:205)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.11/Unknown Source)
	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/Unknown Source)
	at java.lang.Thread.run(java.base@11.0.11/Unknown Source)
```
Every time a `ContainerEventProcessor` invokes `close()`, it calls `super.close()` which invokes `AbstractThreadPoolService.close()` that does a `Futures.await()`. This seems to be holding the thread, and after closing dozens of containers, we run out of threads. 

**To Reproduce**
Deploy a cluster with hundreds of Containers, this problem can happen on these instances that have closed in a short period of time many of them.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Replace call to `super.close()` by `super.stopAsync()` in `EventProcessorImpl.close()` method to avoid locking threads until the service is stopped.

**Purpose of the change**  
Fixes #6314.

**What the code does**  
Use `super.stopAsync()` in `EventProcessorImpl.close()` to stop the `EventProcessorImpl` service. Before, the `close()` method in `EventProcessorImpl` called `super.close()`, which contains a `Futures.await()` call that blocks a thread until the service is stopped. Now, there are no blocking calls in the `close()` call of `EventProcessorImpl`.

**How to verify it**  
Modified test to validate that the `EventProcessorImpl` service is actually stopped. All other tests should pass.

### CODE REVIEW

**Comment by RaulGracia** [comment]
@andreipaduroiu system tests have passed with this one.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 1]
```diff
@@ -329,14 +329,14 @@ long getOutstandingBytes() {
...
-         * This method stop the service (superclass), auto-unregisters from the existing set of active
+         * This method stops the service (superclass), auto-unregisters from the existing set of active
          * {@link EventProcessor} instances (via onClose callback), and closes the metrics.
          */
         @Override
         public void close() {
             if (!this.closed.getAndSet(true)) {
                 log.info("{}: Closing EventProcessor.", this.traceObjectId);
-                super.close();
+                super.stopAsync();
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:339]: Can we attach a shutdown listener (`Services.onStop`) that will log an info when this actually is closed. It may be useful in debugging to make sure that the processor is indeed shut down (even after a while).

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java]: Added the shutdown listener for better debugging.

**Comment by OlegKashtanov** [comment]
With 54 SS and 432 containers totally the Pravega cluster was deployed successfully.
The scopes and streams were created. Under the high workload with 40 clients (40 streams) the test was finished successfully: all streams were created and sealed, deleted after the test.

**Review by andreipaduroiu — APPROVED** [review]
