### PR TITLE
Issue 6045: Storage - StorageReadManager does not correctly handle failures in Storage::openRead

### LINKED ISSUE #6045: Storage - StorageReadManager does not correctly handle failures in Storage::openRead
**Describe the bug**
Currently the `StorageReadManager `saves the return value of `Storage::openRead` in a member field.
This instance of `CompletableFuture `is used for all the subsequent calls.

_Expected behavior_

- In case failure in `Storage::openRead` the member variable is not initialized and hence next time attempt will be made to re-initialize it
- The code should retry only the transient errors and not permeant errors.
- The initialization should be thread/safe and/or serialized so that there is no race between two concurrent calls
_Actual behavior_
- In case failure the failed future is saved and then `openRead `is never retried again.  This leads to situation where once failed the `StorageReadManager` is stuck in failed state forever.
- Also, there is a possibility of race condition during initialization which can results in concurrent calls to `openRead`

**To Reproduce**
This bug is hard to reproduce in end to end testing. However it should be very easy to reproduce in a unit test.

Inspecting code here shows the problem
- https://github.com/pravega/pravega/blob/r0.9/segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java#L195
- https://github.com/pravega/pravega/blob/r0.9/segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java#L136

**Screenshots**
N/A

**Additional information**
N/A

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
Correctly handle failures in Storage::openRead when initializing StorageReadManager by caching handle only when openRead call is successful.
**Purpose of the change**  
Fixes #6045 

**What the code does**  
Cache handle only when openRead call is successful.

Failures in openRead are rare and may include mostly transient but also non-transient errors.  The best course of action here is to not cache exception state.

**How to verify it**  
Existing unit test has been modified for given scenario.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java [hunk 1]
```diff
@@ -201,7 +201,12 @@ private Request findOverlappingRequest(Request request) {
     private CompletableFuture<SegmentHandle> getHandle() {
         synchronized (this.lock) {
             if (this.handle == null) {
-                this.handle = storage.openRead(this.segmentName);
+                return storage.openRead(this.segmentName)
+                        .thenApply(h -> {
+                            // only cache when successful.
+                            this.handle =  CompletableFuture.completedFuture(h);
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java:207]: Nit: extra space after `=`.

**Review by RaulGracia — APPROVED** [review]
LGTM, one minor comment.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java [hunk 2]
```diff
@@ -201,7 +201,12 @@ private Request findOverlappingRequest(Request request) {
     private CompletableFuture<SegmentHandle> getHandle() {
         synchronized (this.lock) {
             if (this.handle == null) {
-                this.handle = storage.openRead(this.segmentName);
+                return storage.openRead(this.segmentName)
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java:204]: If you get multiple concurrent requests for reading from this segment, this will `openRead` for each such request until one of them succeeds and assigns the handle. 

The previous approach was storing the future in the `this.handle` for the first request coming in, and any requests that come in while `openRead` is executing will piggyback onto that one.

Please fix this code to what it was before, but add an exception handler to reset `this.handle` to `null` if an exception happens during `openRead`.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StorageReadManager.java]: Thanks. Good catch. Totally forgot about that.

**Review by andreipaduroiu — APPROVED** [review]
