### PR TITLE
Issue 6451: ContainerKeyIndex may be throttling updates to system critical segments

### LINKED ISSUE #6451: ContainerKeyIndex may be throttling updates to system critical segments
**Describe the bug**
`ContainerKeyIndex` manages the caching and updates of KV for a collection of Table Segments. Internally, it contains a `SegmentTracker` to keep track of the indexing progress and recovery of each Table Segment. In particular, one of the mechanisms that `SegmentTracker` has to prevent Table Segment indexing from lagging too much is throttling of incoming operations. Such a throttle may be total (i.e., no new operations are processed) if the unindexed size goes beyond a given amount of data (e.g., 128MB).

Now, let's assume that LTS is not available for some time and operations keep being be stored in tier 1, while the `StorageWriter` cannot make progress. If many of these operations are Table Segment operations, it can be the case that there are more than 128MB of unindexed data for a particular Table Segment. If in this situation there is a container recovery, all these outstanding data not moved to tier 2 needs to be reprocessed, leaving one or more Table Segments still accumulating a large amount of unindexed data.

For the unindexed data to decrease, the `StorageWriter` needs to start and make progress. To do so, once it reads the recovered operations from Tier 1, it needs to instantiate the right `SegmentAggregator` and start making progress. In some cases, this implies to `openWrite` the appropriate chunk on LTS and perform a metadata update. Unfortunately, the mentioned metadata update implies a `put` on a Table Segment, and in the case that it is accumulating too much unindexed data, that `put` operation will get stuck, and so the `StorageWrite`. Therefore, this can leave the system in a deadlock state.

**To Reproduce**
1. Generate more than 128MB of unindexed data on a Table Segment (e.g., frequent KV updates on a Table Segment while LTS is unavailable).
2. Recover the container for that Table Segment.
3. There are chances that `StorageWriter` gets blocked while trying to instantiate a `SegmentAggregator` that requires to perform a metadata update on the Table Segment with +128MB of unindexed data.

**Screenshots**
n/a

**Additional information**
As a way to fix this problem. we need prevent `ContainerKeyIndex` from throttling internal, system critical segments.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Adds a new property for KVTables named "systemcritical.unindexed.bytes.max" that defines the amount of unindexed data we allow to system-critical KVTable Segments (defaulted to 256MB, 2x the amount of unindexed data we allow to regular segments).

**Purpose of the change**  
Fixes #6451 .

**What the code does**  
In some cases, when LTS is faulty or unavailable for some time, a single Segment Container can accumulate around 1M Operations before the throttler starts inducing max delays. However, we have seen that, in practice, this can lead to an accumulation of a lot of updates on KVTable Segments, and specially on system-critical ones. If the system gets to this state, it may happen that the `StorageWriter` cannot start upon a container recovery, as during its initialization it may be necessary to perform updates on some system-critical KVTables. 

This PR essentially does two things to mitigate this problem:
- First, in a similar spirit to what the ingestion path does by not throttling system-critical Segments, we provide by default a higher (2x) throttling threshold (i.e., unindexed data length) to system-critical KVTable Segments. This should prevent up to some extent to get into the issue that motivates this PR.
- Second, the unindexed data length that we allow to system-critical Segments is now defined by a configuration parameter, namely `systemcritical.unindexed.bytes.max`. This will allow us, in the case we find the same issue, to increase the credit only in the relevant KVTable Segments, instead on the whole system (which may lead to high memory pressure).

**How to verify it**  
Added new tests to validate that system-critical and regular segments get the right amount of credits.

### CODE REVIEW

**Review by abhinb — APPROVED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java [hunk 1]
```diff
@@ -842,13 +847,15 @@ void updateSegmentIndexOffset(long segmentId, long indexOffset, int processedSiz
...
+            // Apply credit-based throttling only for segments that are not system-critical.
+            long totalCredits = canThrottle.test(segment) ? config.getMaxUnindexedLength() : Long.MAX_VALUE;
             AsyncSemaphore throttler;
             synchronized (this) {
                 throttler = this.throttlers.getOrDefault(segment.getSegmentId(), null);
                 if (throttler == null) {
                     val si = segment.getInfo();
                     long initialDelta = Math.max(0, si.getLength() - IndexReader.getLastIndexedOffset(si));
-                    throttler = new AsyncSemaphore(config.getMaxUnindexedLength(), initialDelta, String.format("%s-%s", containerId, segment.getSegmentId()));
+                    throttler = new AsyncSemaphore(totalCredits, initialDelta, String.format("%s-%s", containerId, segment.getSegmentId()));
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java:858]: Make sure that when you release the throttle, you also account for this case. 

Also let's add some unit tests too so that we're covered here.

**Comment by sachin-j-joshi** [comment]
The current change basically postpones the problem by increasing the limit, which is fine but there are two things
- major issue is - we'll still have the same deadlock sometime somewhere.
- minor issue is - What is a new a safe limit ? is 8 times sufficient ?

Also, 
We need to log WARN/ERROR when system critical segments are actually throttled. This is extremely important to know, as the end result is a deadlock and halting of the container.
It would also be helpful to know size of indexed pending data.

The other problem - if we never run into this problem and go into deadlock then how do we get out of it? Perhaps changing config value is the solution here but we need to document it somewhere.

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]
See above comment.

**Comment by realAaronWu** [comment]
> The current change basically postpones the problem by increasing the limit, which is fine but there are two things
> 
> * major issue is - we'll still have the same deadlock sometime somewhere.
> * minor issue is - What is a new a safe limit ? is 8 times sufficient ?
> 
> Also, We need to log WARN/ERROR when system critical segments are actually throttled. This is extremely important to know, as the end result is a deadlock and halting of the container. It would also be helpful to know size of unindexed pending data.
> 
> The other problem - if we ever run into this problem and go into deadlock then how do we get out of it? Perhaps changing config value is the solution here but we need to document it somewhere.

Can we force apply changes for system critical segments instead of increasing credits? If the side effect is just lengthy delays upon a subsequent recovery?

**Comment by RaulGracia** [comment]
@sachin-j-joshi @realAaronWu  I have addressed the comment of the warning: now if we have a system-critical table segment that runs out of credit, it will be logged with a warning.

I want to be clear regarding the approach of this PR: it may not be completely solving the deadlock, because the deadlock we observe is in itself an unfortunate corner case of the design we have involving (hash-based) Table Segments + SLTS. As you know, there is an inherent circular dependency in hash-based Table Segments, as the updates go through the ingestion pipeline and are stored in tier 1 (and cached), but they don't actually make effect until the Storage Writer workflow makes the changes in the underlying BTree index backed on storage. If the ingestion pipeline makes progress but Tier 2 is unavailable, the Storage Writer won't be able to make progress and unindexed data will be accumulated. On top of that, we also have SLTS which also depends on performing updates (not only reads) to Table Segments for initializing (another circular dependency), and these updates may be related to Table Segments that have accumulated a lot of unindexed data, so they cannot accept any further update until the amount of unindexed data is reduced, which is not going to happen.

This PR just does 2 things:
- It distinguishes the amount of credit (i.e., unindexed data length) that we allow to regular or system-critical Segments. In the case we find the same problem again, updating the new configuration value will unblock the cluster inducing minimal memory pressure (as the configuration change would only impact system-critical segments instead of all of them). Before, in similar situations we have increased credit on all Table Segments.
- The new default allows system-critical Table Segments to accumulate up to 2x the amount of data than regular ones. This is expected to reduce the chances that this happens again. However, we do not know the upper bound in terms of unindexed data for a hash-based Table Segment, which implies that we don't know if this could happen again. We need an empirical evaluation of that (and perhaps new metrics) to understand this in depth. I have created a new issue to track this activity, which can help us to be sure whether this change completely removes the problem or not: #6467.

Note that in the case that as part of #6467 we set a right default that i) is the upper bound of the maximum unindexed data that a system-critical Table Segment can accumulate, ii) we evaluate that the memory pressure of this new default is not going to be a problem during recoveries, then I would say that the problem would be definitively solved. In a similar spirit than the circular dependency of SLTS metadata with Tier 1 was solved by adding a throttling exception in the write path for system-critical Segments.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM.

Let's run system tests and other sanity tests before merging.

**Comment by RaulGracia** [comment]
@sachin-j-joshi system tests have passed (`test-pravega-continuous-1/1864/`)
