### PR TITLE
Issue 1565: ensure we pass the right scope to client factory

### LINKED ISSUE #1565: ReadWithAutoScale Test passes incorrect scope while creating a client factory.
**Problem description**
ReadWithAutoScale System test passes incorrect scope while creating a client factory.
**Problem location**
ReadWithAutoScaleTest.java

**Suggestions for an improvement**
ensure the right scope is used while creating the client factory.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
* Fixes an issue in `ReadWithAutoScaleTest`
* Ensures we pass the right scope to client factory. 
* Refactored the code to reuse the scope in AbstractScaleTests, but with a different stream name.

**Purpose of the change**
Fix the incorrect scope being passed to the client factory.

**What the code does**
Fixes #1565 

**How to verify it**
Tests should pass.
Update: System test passes with this change.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java [hunk 1]
```diff
@@ -63,8 +63,7 @@
 @RunWith(SystemTestRunner.class)
 public class ReadWithAutoScaleTest extends AbstractScaleTests {
 
-    private final static String SCOPE = "testReadAutoScale" + new Random().nextInt(Integer.MAX_VALUE);
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java]: so the scope from abstractScaleTests is taken throughout the code.. right?

Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/ReadWithAutoScaleTest.java]: yes
