### PR TITLE
Issue 2599: Ensure spurious warnings are not thrown by AsyncSegmentInputStreamImpl

### LINKED ISSUE #2599: Suppress spurious warnings from `AsyncSegmentInputStreamImpl` on close
**Problem description**
When you close the reader, spurious warnings are emitted about the connection being closed.   

```
2018-05-17 00:55:08,644 WARN  io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl    - Exception while reading from Segment : examples/wordcount/0
io.pravega.client.stream.impl.ConnectionClosedException
	at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl.close(AsyncSegmentInputStreamImpl.java:149)
	at io.pravega.client.segment.impl.SegmentInputStreamImpl.close(SegmentInputStreamImpl.java:242)
	at io.pravega.client.stream.impl.EventStreamReaderImpl.close(EventStreamReaderImpl.java:250)
	at io.pravega.connectors.flink.FlinkPravegaReader.run(FlinkPravegaReader.java:170)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:86)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:55)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:94)
	at org.apache.flink.streaming.runtime.tasks.StoppableSourceStreamTask.run(StoppableSourceStreamTask.java:40)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:264)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
The spurious warning originates in `AsyncSegmentInputStreamImpl::read`.   

**Suggestions for an improvement**
If `ConnectionClosedException` is a planned event (as opposed to an unplanned connection failure) then perhaps the warning should simply not be emitted when that exception type is seen.  Also note that `SegmentInputStreamImpl::close` cancels the outstanding async request before closing the underlying async stream.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  

Ensure spurious warnings are not thrown by the AsyncSegmentInputStreamImpl for a planned close() invocation.

**Purpose of the change**  
Fixes #2599 

**What the code does**  
When AsyncSegmentInputStreamImpl.close() is invoked ensure no spurious warnings are thrown.
 

**How to verify it**  
The spurious warn message should be observed on closing the reader.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java [hunk 1]
```diff
@@ -162,7 +162,10 @@ public boolean isClosed() {
 
         return backoffSchedule.retryWhen(t -> {
             Throwable ex = Exceptions.unwrap(t);
-            log.warn("Exception while reading from Segment : {}", segmentId, ex);
+            log.debug("Exception while reading from Segment : {}", segmentId, ex);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: let's not log it twice. Better to have an else branch
