### PR TITLE
Issue 2030: Ensure connection state cleanup happens incase of netty failure during reconnect operation.

### LINKED ISSUE #2030: IllegalState exception observed in EventStreamWriter.
**Problem description**
On a connection reconnect observing the following stacktrace:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.pravega.common.concurrent.Futures.lambda$delayedFuture$17(Futures.java:466)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: null
    at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
    at io.pravega.client.segment.impl.SegmentOutputStreamImpl.lambda$null$4(SegmentOutputStreamImpl.java:518)
    at io.pravega.common.concurrent.Futures.lambda$delayedFuture$19(Futures.java:486)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    ... 10 common frames omitted
```

**Problem location**
SegmentOutputStreamImpl

**Suggestions for an improvement**
Ensure the reconnect operations is retried in case of a netty exception.

### PR DESCRIPTION
**Pull request by shrids**
Signed-off-by: shrids <sandeep.shridhar@emc.com>

**Change log description**
- Ensure connection cleanup happens in case of `io.pravega.shared.protocol.netty.ConnectionFailedException` while establishing connection to a SegmentStore.

**Purpose of the change**
Fixes #2030

**What the code does**
- Ensure IllegalStateException is not thrown during ConnectionFailedException during reconnects.

**How to verify it**
Tests should pass.
(Testing in progress)

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -526,6 +526,7 @@ void reconnect() {
                          try {
                              connection.send(cmd);
                          } catch (ConnectionFailedException e1) {
+                             state.failConnection(e1);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: it is an intuitive change, but I want understand your thought process to come to the conclusion that this line here is needed. I suppose that we are now failing the connection elsewhere while we should, but I want to hear your detailed explanation, please.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 2]
```diff
@@ -115,6 +115,28 @@ public void testConnectAndConnectionDrop() throws Exception {
...
+        MockController controller = new MockController(uri.getEndpoint(), uri.getPort(), cf);
+        ClientConnection connection = mock(ClientConnection.class);
+        //simulate a Netty Exception and ensure retry happens.
+        doThrow(new ConnectionFailedException("Netty Exception")).doNothing().when(connection).send(any(SetupAppend
+                .class));
+        cf.provideConnection(uri, connection);
+        SegmentOutputStreamImpl output = new SegmentOutputStreamImpl(SEGMENT, controller, cf, cid, segmentSealedCallback, RETRY_SCHEDULE);
+        output.reconnect();
+        verify(connection).send(new SetupAppend(1, cid, SEGMENT));
+
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: Minor: remove new line.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 1 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: The following operations are performed by `state.setupConnection.releaser` :
1. Get the endpoint (Segment Store) details of the given segment.
2. Use `connectionFactory.establishConnection()` to establish a connection to the Segment Store.
Once the `io.pravega.client.netty.impl.ClientConnection` is returned by the `establishConnection()` method a `SetupAppend` is send over this connection.

The issue we are observing is that once a client connection is successfully returned by the connectionFactory an `ConnectionFailedException` is received while sending the `SetupAppend`. Due to this exception the reconnect logic is retried causing the Precondition checkstate to fail.
This causes the reconnect logic to be invoked indefinitely there by blocking all operations for this SegmentOutputStream.

By invoking state.failConnection() we are ensuring that the connection is torn down in this error scenario.

Note: `io.netty.channel.ChannelInboundHandlerAdapter#channelRegistered` needs to be invoked for the channel to be not null. In this corner case we are seeing
that `io.netty.bootstrap.Bootstrap#connect(java.lang.String, int)` completed successfully but the `channelRegistered()` method was not invoked causing the send operation to fail.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java (hunk 2 above)
Comment (shrids) [reply client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: done.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 1 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: What's the intention of the sneaky throw following this line? It feels like the intention is to break the retry loop, but we are actually retrying unconditionally, so it won't break. Is the right way to fix this not to retry unconditionally? In fact, what happens if the reconnect breaks loop with an exception?

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: `io.pravega.common.util.ReusableFutureLatch` : An exception thrown within the releaser (Runnable)  will cause none of the waiting futures to be notified .

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: This change is not correct. The throw on the line below will already trigger a retry. The problem this is trying to address is that the retry keeps failing becauses close is never being called on the connection so the loop always fails in the same place. However this is an artifact of channelUnregisted not being invoked. Similar to the channelRegistered issue mentioned above, this is likely a result in a change in the way netty handles things. I think it is our fault though. Reading their documentation it looks like we should be overriding the callbacks for channelActive and channelInactive rather than registered and unregistered. (We previously made this change in a PR and ended up backing it out.) I think we should make that change as see if it fixes the problem of the connect and retries when send fails.

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Updated the code to use callbacks `channelActive, channelInactive` rather than `channelRegistered, channelUnregistered`.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 3]
```diff
@@ -115,28 +115,6 @@ public void testConnectAndConnectionDrop() throws Exception {
     }
 
     @Test(timeout = 10000)
-    public void testNettyConnectionFailure() throws Exception {
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: This test case still holds with the recent changes, no?

Comment (shrids) [reply client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: yes, I have reverted the changes.

File: client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java [hunk 4]
```diff
@@ -119,6 +120,9 @@ public void initChannel(SocketChannel ch) throws Exception {
                 @Override
                 public void operationComplete(ChannelFuture future) {
                     if (future.isSuccess()) {
+                        Channel ch = future.channel();
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java]: Perhaps rather than blocking here, we could get a future and have result set upon it's completion. This would avoid tieing up the thread

Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java]: Updated the code with a Future based implementation to prevent tieing up the the thread. Please review it.
Also, `future.channel()` is a non-blocking operation as the `ChannelFuture` is already completed. This is used to only for logging purposes.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 5]
```diff
@@ -60,6 +60,7 @@
 import static org.mockito.Mockito.verifyNoMoreInteractions;
 import static org.mockito.Mockito.times;
 
+
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: Unnecessary change.

Comment (shrids) [reply client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: removed it.

File: client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java [hunk 6]
```diff
@@ -114,25 +114,31 @@ public void initChannel(SocketChannel ch) throws Exception {
...
                 }
             });
         } catch (Exception e) {
-            result.completeExceptionally(new ConnectionFailedException(e));
+            connectionComplete.completeExceptionally(new ConnectionFailedException(e));
         }
-        return result;
+
+        CompletableFuture<Void> channelRegisteredFuture = new CompletableFuture<>(); //check if channel is registered.
+        handler.completeWhenRegistered(channelRegisteredFuture);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java]: I think we are changing the behavior of this call unnecessarily. Previously it was returning a possibly incomplete future, and now we are trying to complete the future before returning. Why can't we return an incomplete future rather than blocking?

The problem I see is with this `completeWhenRegistered` method. It is correct that the future needs to complete when registered, but I don't see the need of blocking it until complete. Does it make sense?

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java [hunk 7]
```diff
@@ -167,28 +169,42 @@ public void close() {
...
-            }
-            return ch;
-        } catch (TimeoutException e) {
-            throw new ConnectionFailedException("Channel is not active. Connection to " + connectionName + "is not " +
-                    "established.");
+    void completeWhenRegistered(final CompletableFuture<Void> future) {
+        if (isRegistered.get()) { // channelRegistered is already invoked, complete the future.
+            future.complete(null);
+        } else {
+            BinaryOperator<CompletableFuture<Void>> accumulate = (prev, current) -> {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: Should we do a private method rather than declaring it like this for clarity?

File: client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java (hunk 6 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java]: Ok, I made a second pass and I understand better now what you are trying to do. It seems fine to me.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java (hunk 7 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: done, refactored the code.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java [hunk 8]
```diff
@@ -59,6 +63,10 @@ public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
         super.channelRegistered(ctx);
         Channel c = ctx.channel();
         channel.set(c);
+        isRegistered.set(true);
+        if (null != registeredFuture.get()) { //complete the pending future.
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: Technically for this to be correct, registeredFuture.get() should be assigned to a local variable and if it is not null complete should be called.

File: client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java [hunk 9]
```diff
@@ -165,7 +176,38 @@ private Channel getChannel() throws ConnectionFailedException {
...
         return ch;
     }
-    
+
+    /**
+     * This function completes the input future when the channel is registered.
+     *
+     * @param future CompletableFuture which will be completed once the channel is registered.
+     */
+    void completeWhenRegistered(final CompletableFuture<Void> future) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: I have already created a class in common to solve this problem. 
Take a look at ReusableFutureLatch. It works like a reusable latch but instead of threads blocking on it, futures are registered with it, and when it is released all the features are completed. (Any late registrations are completed immediately)

Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: done.

Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/ClientConnectionInboundHandler.java]: done, used reusableFutureLatch.
