### PR TITLE
Issue 3916: (SegmentStore) Reduce logging verbosity of IllegalContainerStateException

### LINKED ISSUE #3916: Reduce log verbosity of IllegalContainerStateException(Starting)
**Problem description**
This is too verbose
```
2019-06-14 15:49:52,988 9426171 [epollEventLoopGroup-11-1] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: STARTING.
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:770)
	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.forSegment(StreamSegmentContainer.java:540)
	at io.pravega.segmentstore.server.tables.ContainerTableExtensionImpl.newIterator(ContainerTableExtensionImpl.java:326)
	at io.pravega.segmentstore.server.tables.ContainerTableExtensionImpl.keyIterator(ContainerTableExtensionImpl.java:266)
	at io.pravega.segmentstore.server.tables.TableService.lambda$keyIterator$7(TableService.java:101)
	at io.pravega.segmentstore.server.tables.TableService.lambda$invokeExtension$9(TableService.java:119)
	at io.pravega.segmentstore.server.store.SegmentContainerCollection.invoke(SegmentContainerCollection.java:72)
	at io.pravega.segmentstore.server.tables.TableService.invokeExtension(TableService.java:118)
	at io.pravega.segmentstore.server.tables.TableService.keyIterator(TableService.java:100)
	at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.readTableKeys(PravegaRequestProcessor.java:729)
	at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.readTableKeys(DelegatingRequestProcessor.java:135)
	at io.pravega.shared.protocol.netty.WireCommands$ReadTableKeys.process(WireCommands.java:1736)
	at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
ServerConnectionInboundHandler, AppendProcessor, PravegaRequestProcessor

**Suggestions for an improvement**
Make less verbose.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Reduced logging verbosity of `IllegalContainerStateException` when logged from `AppendProcessor`, `PravegaRequestProcessor` or `ServerConnectionInboundHandler`.

**Purpose of the change**  
Fixes #3916.

**What the code does**  
- Logging `IllegalContainerStateException` as a WARN instead of an ERROR and not showing the stack trace.

**How to verify it**  
Run system tests and verify these don't show up as errors, but other errors still show up

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 1]
```diff
@@ -358,11 +359,19 @@ private void handleException(UUID writerId, long requestId, String segment, long
...
         } else {
-            log.error("Error (Segment = '{}', Operation = 'append')", segment, u);
+            logError(segment, u);
             connection.close(); // Closing connection should reinitialize things, and hopefully fix the problem
         }
     }
 
+    private void logError(String segment, Throwable u) {
+        if (u instanceof IllegalContainerStateException) {
+            log.warn("Error (Segment = '{}', Operation = 'append'): {}.", segment, u.toString());
```
Comment (RaulGracia) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Is the `toString()` here reducing considerably the stacktrace?

Comment (fpj) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Here is a reference to the documentation:

https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#toString--

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java]: Yes. `toString` will return the name of the class and the message. It will not include the stack trace.
