### PR TITLE
Issue 1865: (BugFix) BookKeeperLog can stop processing writes if an unhandled exception occurs

### LINKED ISSUE #1865: BookKeeperLog stalls when an unhandled exception occurrs.
**Problem description**
If an unhandled exception occurs in `processWritesSync`, the `BookKeeperLog` will stop processing writes, even if there are writes pending in the queue.

**Problem location**
`BookKeeperLog`

**Suggestions for an improvement**
Retry write processor if an unhandled exception bubbles up.

**Context** 
The following errors happened
```
2017-09-09 07:02:09,247 46811503 [BookKeeperClientWorker-orderedsafeexecutor-3-0] WARN  o.a.bookkeeper.client.PendingAddOp - Write did not succeed: L99 E10305 on 172.16.27.13:3181, rc = -23
2017-09-09 07:02:09,247 46811503 [BookKeeperClientWorker-orderedsafeexecutor-3-0] INFO  o.a.bookkeeper.client.LedgerHandle - Handling failure of bookie: 172.16.27.13:3181 index: 0
2017-09-09 07:02:09,342 46811598 [BookKeeperClientWorker-orderedsafeexecutor-5-0] WARN  o.a.bookkeeper.client.PendingAddOp - Write did not succeed: L101 E14547 on 172.16.27.15:3181, rc = -23
2017-09-09 07:02:09,342 46811598 [BookKeeperClientWorker-orderedsafeexecutor-5-0] INFO  o.a.bookkeeper.client.LedgerHandle - Handling failure of bookie: 172.16.27.15:3181 index: 0
2017-09-09 07:02:09,342 46811598 [BookKeeperClientWorker-orderedsafeexecutor-5-0] WARN  o.a.b.c.RackawareEnsemblePlacementPolicy - Failed to choose a bookie from /default-rack : excluded [<Bookie:172.16.27.13:3181>, <Bookie:172.16.27.10:3181>, <Bookie:172.16.27.15:3181>], fallback to choose bookie randomly from the cluster.
2017-09-09 07:02:09,343 46811599 [BookKeeperClientWorker-orderedsafeexecutor-5-0] WARN  o.a.b.c.RackawareEnsemblePlacementPolicy - Failed to choose a bookie from /default-rack : excluded [<Bookie:172.16.27.13:3181>, <Bookie:172.16.27.10:3181>, <Bookie:172.16.27.15:3181>], fallback to choose bookie randomly from the cluster.
2017-09-09 07:02:09,343 46811599 [BookKeeperClientWorker-orderedsafeexecutor-5-0] ERROR o.a.bookkeeper.client.LedgerHandle - Could not get additional bookie to remake ensemble, closing ledger: 101
2017-09-09 07:02:09,343 46811599 [BookKeeperClientWorker-orderedsafeexecutor-5-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 101 due to error -6
2017-09-09 07:02:09,343 46811599 [BookKeeperClientWorker-orderedsafeexecutor-5-0] ERROR o.a.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L101 E14547
2017-09-09 07:02:09,248 46811504 [BookKeeperClientWorker-orderedsafeexecutor-3-0] WARN  o.a.b.c.RackawareEnsemblePlacementPolicy - Failed to choose a bookie from /default-rack : excluded [<Bookie:172.16.27.13:3181>, <Bookie:172.16.27.10:3181>, <Bookie:172.16.27.15:3181>], fallback to choose bookie randomly from the cluster.
2017-09-09 07:02:09,344 46811600 [BookKeeperClientWorker-orderedsafeexecutor-3-0] WARN  o.a.b.c.RackawareEnsemblePlacementPolicy - Failed to choose a bookie from /default-rack : excluded [<Bookie:172.16.27.13:3181>, <Bookie:172.16.27.10:3181>, <Bookie:172.16.27.15:3181>], fallback to choose bookie randomly from the cluster.
2017-09-09 07:02:09,344 46811600 [BookKeeperClientWorker-orderedsafeexecutor-3-0] ERROR o.a.bookkeeper.client.LedgerHandle - Could not get additional bookie to remake ensemble, closing ledger: 99
2017-09-09 07:02:09,344 46811600 [BookKeeperClientWorker-orderedsafeexecutor-3-0] ERROR o.a.bookkeeper.client.LedgerHandle - Closing ledger 99 due to error -6
2017-09-09 07:02:09,344 46811600 [BookKeeperClientWorker-orderedsafeexecutor-3-0] ERROR o.a.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L99 E10305
2017-09-09 07:02:09,742 46811998 [ZKC-connect-executor-0-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: 
2017-09-09 07:02:09,743 46811999 [ZKC-connect-executor-0-EventThread] WARN  o.a.b.meta.AbstractZkLedgerManager - Conditional update ledger metadata failed: 
2017-09-09 07:02:09,743 46811999 [BookKeeperClientWorker-orderedsafeexecutor-5-0] ERROR o.a.bookkeeper.client.LedgerHandle - Error update ledger metadata for ledger 101 : -9
2017-09-09 07:02:09,743 46811999 [BookKeeperClientWorker-orderedsafeexecutor-5-0] WARN  o.a.bookkeeper.client.LedgerHandle - Close failed: Error while using ZooKeeper
2017-09-09 07:02:09,743 46811999 [BookKeeperClientWorker-orderedsafeexecutor-3-0] ERROR o.a.bookkeeper.client.LedgerHandle - Error update ledger metadata for ledger 99 : -9
2017-09-09 07:02:09,743 46811999 [ZKC-connect-executor-0-EventThread] ERROR o.a.b.meta.AbstractZkLedgerManager - Could not read metadata for ledger: 99
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /pravega/pravega-cluster/bookkeeper/ledgers/L0000000099
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:355)
    at org.apache.bookkeeper.zookeeper.ZooKeeperClient$18$1.processResult(ZooKeeperClient.java:912)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:564)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
2017-09-09 07:02:09,744 46812000 [ZKC-connect-executor-0-EventThread] INFO  o.a.b.z.ZooKeeperWatcherBase - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.
2017-09-09 07:02:09,743 46811999 [BookKeeperClientWorker-orderedsafeexecutor-3-0] WARN  o.a.bookkeeper.client.LedgerHandle - Close failed: Error while using ZooKeeper
2017-09-09 07:02:09,942 46812198 [segment-store-11] INFO  i.p.s.s.h.stat.AutoScaleProcessor - received traffic for hulk/smallScale/622 with twoMinute rate = 1.6077807821810803 and targetRate = 3
2017-09-09 07:02:09,943 46812199 [segment-store-38] INFO  i.p.s.s.h.stat.AutoScaleProcessor - received traffic for hulk/smallScale/626 with twoMinute rate = 3.1936789193663424 and targetRate = 3
2017-09-09 07:02:10,998 46813254 [ZKC-connect-executor-0-SendThread(11.6.245.168:31886)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 11.6.245.168/11.6.245.168:31886. Will not attempt to authenticate using SASL (unknown error)
2017-09-09 07:02:10,999 46813255 [ZKC-connect-executor-0-SendThread(11.6.245.168:31886)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 11.6.245.168/11.6.245.168:31886, initiating session
2017-09-09 07:02:11,001 46813257 [ZKC-connect-executor-0-SendThread(11.6.245.168:31886)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 11.6.245.168/11.6.245.168:31886, sessionid = 0x10000198e01001e, negotiated timeout = 10000
2017-09-09 07:02:11,001 46813257 [ZKC-connect-executor-0-EventThread] INFO  o.a.b.z.ZooKeeperWatcherBase - ZooKeeper client is connected now.
```
Ledger 99 and 101 were both affected, however for some reason the BookKeeper client was not able to read metadata for Ledger 99 during the client-side reconciliation process. That lead to an exception to be bubbled up and essentially kill the write processor.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in `BookKeeperLog` that could cause it to stall the Write Processor if an unhandled exception bubbled up to the main method.
- Both the `WriteProcessor` and `RolloverProcessor` use the `SequentialAsyncProcessor` to control their behavior. If either of their main methods would let an exception bubble out of them, it would be possible for them not to be reinvoked again, even if there was work left to do.
- `SequentialAsyncProcessor` has been fixed to catch all exceptions, run them through an exception handler and re-run the task if the handler indicates so.
- `BookKeeperLog` will auto-close if either the `WriteProcessor` or `RolloverProcessor` fail to execute more than a number of times in a row (based on an existing config value).

**Purpose of the change**
Fixes #1865.

**What the code does**
See **Change Log Description**.

**How to verify it**
A unit test has been added for `SequentialAsyncProcessor`. Some unit tests were added for `BookKeeperLog` to verify behavior for ZK failures. Unfortunately it is nearly impossible to create a unit test that reproduces the problem described in issue #1865, since both BK and ZK need to fail in the correct order and (possibly) resume functioning at the right time(s) in order for that behavior to be triggered.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 1]
```diff
@@ -709,16 +728,30 @@ private void rollover() {
...
             log.debug("{}: Rollover: swapped ledger and metadata pointers (Old = {}, New = {}) and closed old ledger.",
                     this.traceObjectId, oldLedger.getId(), newLedger.getId());
-        } catch (Throwable ex) {
-            if (!ExceptionHelpers.mustRethrow(ex)) {
-                log.error("{}: Rollover failure; log may be unusable.", ex);
-            }
+        } finally {
+            // It's possible that we have writes in the queue that didn't get picked up because they exceeded the predicted
+            // ledger length. Invoke the Write Processor to execute them.
+            this.writeProcessor.runAsync();
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Please clarify one thing for me. If there is an exception thrown in the try block, then the point of running the write processor to pick up the remaining writes (if any) would be to fail them and make sure they are retried?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 2]
```diff
@@ -709,16 +728,30 @@ private void rollover() {
...
+     *
+     * @param exception    The causing exception.
+     * @param failureCount The number of consecutive failures.
+     * @return True if the RolloverProcessor should be reinvoked, false otherwise.
+     */
+    private boolean handleRolloverFailure(Throwable exception, int failureCount) {
+        log.error("{}: Rollover failure (attempt {}/{}); log may be unusable.", this.traceObjectId, failureCount, this.config.getMaxWriteAttempts(), exception);
+        if (failureCount >= this.config.getMaxWriteAttempts()) {
+            log.warn("{}: Too many rollover failures; closing.", this.traceObjectId);
+            close();
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Please clarify one this for me here. What's the ultimate consequence of closing the `BookKeeperLog`? I can see that `BookKeeperLog.close` closes the write and rollover processors, the write queue, and any remaining open ledger. What happens to the container, though? Does it instantiate `BookKeeperLog` again? Does it kill itself?

Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: BookKeeperLog should close when it did its best at its job. When it cannot do that anymore (whether it was fenced out or it has retried sufficient times) it will consider that all hope is lost, give up, and close. The Container will detect this via an `ObjectClosedException` and will shut down itself as well, which will give the Controller/ZKSegmentContainerManager a chance to restart it fresh.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: The Write Processor first checks if the current ledger is closed. If rollover failed, then the current ledger is closed, and it will reinvoke the rollover processor to do its job again. You may argue that the `handleRolloverFailures` already retriggers it, which is correct, but the `SequentialAsyncProcessor` will only execute it once, so there's no harm in doing so. This is cleaner than having a `try-catch-finally` block with some code in `catch` to figure out what to do. The addition of error handling in the SequentialAsyncProcessor eliminated this need by it itself tracking errors and invoking the handler.

File: common/src/main/java/io/pravega/common/concurrent/SequentialAsyncProcessor.java [hunk 3]
```diff
@@ -70,6 +81,19 @@ public void runAsync() {
...
+                } catch (Throwable ex) {
+                    int c = this.consecutiveFailedAttempts.incrementAndGet();
+                    if (ExceptionHelpers.mustRethrow(ex)) {
+                        close();
+                    }
+
+                    boolean retry = this.errorHandler.apply(ex, c);
+                    if (retry) {
+                        synchronized (this) {
+                            this.runAgain = true;
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/concurrent/SequentialAsyncProcessor.java]: the purpose of `runAgain` is to register a request that someone else wants to invoke this task while it's already running (the processor, by definition, won't run the task multiple times concurrently). If such a request comes along, it will be recorded in this variable and the `while` loop will make sure to reinvoked the task exactly once.

In this `catch` block, I am making use of it since the error handler asked us to re-run the task one more time.
