### PR TITLE
Issue 1858: DataAppended should have an event range for client validation

### LINKED ISSUE #1858: DataAppended should provide an event range as a check
**Problem description**
DataAppended currently has a eventNumber which indicates that all events below this number have been processed successfully. As a safety check to prevent bugs we should also add a lower number to explicitly pass the range. This way the client can check the server to make sure that it isn't skipping any events or processing things out of order. Obviously this should never happen anyway, but having a clear exception in the log if it ever should would go a long way to catching such a bug early.

**Problem location**
WireCommands.DataAppended

**Suggestions for an improvement**
Add an additional long to create a range of events. Then verify this range on the client.

### PR DESCRIPTION
**Pull request by fpj**
**Change log description**
This adds a new field previousEventNumber in the server response command DataAppended. The field represents the previously acknowledged event number. This is used on the client to verify that no acknowledgements have been missed. If a gap is detected, the connection is re-established.

**Purpose of the change**
Fixes #1858

**What the code does**
Fixes #1858

Set of changes originally proposed by @moizsj in PR #1893 .

**How to verify it**
Unit and integration tests have been added.

### CODE REVIEW

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 1]
```diff
@@ -521,12 +522,14 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeLong(writerId.getLeastSignificantBits());
             out.writeLong(eventNumber);
+            out.writeLong(previousEventNumber);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             UUID writerId = new UUID(in.readLong(), in.readLong());
             long offset = in.readLong();
-            return new DataAppended(writerId, offset);
+            long previousEventNumber = in.readLong();
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: This is not compatable. If a new client reads data from an old server it will get an exception here.

Comment (fpj) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: We haven't actually agreed whether we support a new client talking to an old server. We haven't discarded the option of not supporting such a scenario as upgrades in live systems typically prefer to upgrade servers first. The decision on what to do here will depend on the outcome of [PDP 21](https://github.com/pravega/pravega/wiki/PDP-21:-Protocol-revisioning).

Comment (tkaitchuck) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: ok... but this does not comply with the rest of the PDP either. It has not incremented the version number, and if you want to make it backward compatible, the versions sent by the client and the server in the Hello need to be changed to exclude the old version.

Comment (fpj) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Let's agree about what to do here. There are three options I see:

1. I reintroduce the length check, and maybe bump up the current version
2. I bump up both current version and old version to say that previous versions are incompatible
3. I leave as is

Under the PDP guidelines, I believe we need to do either 1 or 2. Given that no one really needs to upgrade Pravega at this point, I'd say that it is fine to do 3, which I understand makes it incompatible, but given that all current applications are currently testing, they should really upgrade immediately. Doing 1 or 2 right now might be a good idea so that we can start getting the gist of making such changes.

Do you have any preference? I don't have any strong preference at this point.

Comment (tkaitchuck) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: I'd prefer to do 1. We can easily transition to removing the length check at any future date. 
version bump: per the PDP we should, but I'm not sure it is required, especially if we have a length check.
