### PR TITLE
Issue 2783: BookieFailoverTest sporadic failure

### LINKED ISSUE #2783: BookieFailoverTest sporadic failure
**Problem description**
`BookieFailoverTest` sporadically fails as some readers get `RetriesExhaustedException`. Note this failure is not consistent: in a Jarvis cluster the current version of the test passes consistently, whereas this does not happen in Jenkins system test builds. Writers and readers process all the events correctly.

**Problem location**
`BookieFailoverTest.java`

**Suggestions for an improvement**
This could related to an excessive sleep timeout for a Bookie failover test.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
Fixed sporadic failure in `BookieFailoverTest.java` by reducing the sleep interval used in the test between the failover and recovery events.

**Purpose of the change**
Fixes #2783.

**What the code does**
This PR basically reduces the sleep interval in `BookieFailoverTest` to `20s`, which is expected to be low enough to prevent readers from getting `RetriesExhaustedException` while testing the recovery capabilities of the segment store under Bookie failures. At the time of creating this PR, we had 3 green Jenkins system test builds in a row using this sleep interval.

**How to verify it**
`BookieFailoverTest` should pass consistently both in Jenkins builds and custom clusters.

### CODE REVIEW

**Comment by fpj** [comment]
Thanks for figuring this out, @RaulGracia . Relying on timing in tests is a bad idea overall. I can understand how this change makes the test pass, but we really need to stop having sleeps in the code and build the necessary infrastructure to avoid doing it. I'm ok with checking this in for now, but I really need to see this pattern changing long term, which needs to happen as this is a brand new test case and we are still doing it.

**Comment by RaulGracia** [comment]
I agree that there should be better ways of coordinating the activity of tests; as far as I know this will be addressed in #1608.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 1]
```diff
@@ -189,22 +190,22 @@ public void bookieFailoverTest() throws ExecutionException, InterruptedException
...
+            log.info("Write count is {} after {} seconds sleep after bookie failover.", writeCountBeforeSleep, BOOKIE_FAILOVER_WAIT_MILLIS / 1000);
 
-            log.info("Sleeping for {} seconds.", WAIT_AFTER_FAILOVER_MILLIS / 1000);
-            Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
+            log.info("Sleeping for {} seconds.", BOOKIE_FAILOVER_WAIT_MILLIS / 1000);
+            Exceptions.handleInterrupted(() -> Thread.sleep(BOOKIE_FAILOVER_WAIT_MILLIS));
 
             long writeCountAfterSleep  = testState.getEventWrittenCount();
-            log.info("Write count is {} after {} seconds sleep after bookie failover.", writeCountAfterSleep, WAIT_AFTER_FAILOVER_MILLIS / 1000);
+            log.info("Write count is {} after {} seconds sleep after bookie failover.", writeCountAfterSleep, BOOKIE_FAILOVER_WAIT_MILLIS / 1000);
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: this log seems incorrect, I mean by the time we are checking the write count its already 2* (BOOKIE_FAILOVER_WAIT_MILLIS/1000). Can you just correct it, please?

Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: You are right, fixed.
