### PR TITLE
Issue 6419: Internal Reader Groups cannot read events on Controller restart

### LINKED ISSUE #6419: On Controller restarts, sometimes events from internal Streams cannot be read and processed.
**Describe the bug**
Occasionally on Controller restarts, ControllerEventProcessor is not able to read events from one or more internal streams. 
This seems to happen because in EventProcessorGroupImpl we remove a reader from the znode before marking the readerOffline and so if a crash happens after the removal but before the reader was marked offline the reader is never removed from the internal reader group and so segment assignment never changes to the new reader brought up by the current Controller.

**To Reproduce**
Hard to reproduce but occurs occasionally on multiple Controller restarts.

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
This PR fixes the problem created by removing readers from the checkpoint store prior to declaring them offline. In rare cases when the Controller fails after removing a reader from the ZKCheckpointStore but before invoking reader.readerOffline , this issue manifests. It causes an old reader to stay in the ReaderGroup and continue to hold segments due to which they cannot be assigned to a reader created by the new Controller.

**Purpose of the change**  
Fixes #6419

**What the code does**  
Changed method EventProcessorGroupImpl.notifyProcessFailure() to first seal the Reader Group then mark each reader Offline and remove the Reader from checkpoint store only after it has been successfully marked offline on the Reader Group. 

**How to verify it**  
All tests should pass.

### CODE REVIEW

**Comment by pbelgundi** [comment]
Working on adding code coverage.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 1]
```diff
@@ -265,10 +264,18 @@ public void notifyProcessFailure(String process) throws CheckpointStoreException
...
 
             for (Map.Entry<String, Position> entry : map.entrySet()) {
-                //Notify reader group about failed readers
+                // 1. Remove failed readers from Reader Group
                 log.info("{} Notifying readerOffline reader={}, position={}", this.objectId, entry.getKey(), entry.getValue());
                 readerGroup.readerOffline(entry.getKey(), entry.getValue());
+
+                // 2. Clean up reader from checkpoint store
+                log.info("{} removing reader={} from checkpoint store", this.objectId, entry.getKey());
+                checkpointStore.removeReader(process, readerGroup.getGroupName(), entry.getKey());
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:273]: Should'nt we follow the same pattern for `io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl#shutDown` ?

**Review by shrids — CHANGES_REQUESTED** [review]

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Good Catch. Fixed.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 2]
```diff
@@ -204,8 +199,41 @@ protected void shutDown() {
...
+                        cell.awaitTerminated();
+                        log.info("Termination of event processor cell: {} completed successfully.", cell);
+                    } catch (Exception e) {
+                        log.warn("Failed terminating event processor cell {}.", cell, e);
+                    }
+                }
+
+                // Finally, clean up Reader Group data from Checkpoint store.
+                try {
+                    cleanupReaderGroup(actorSystem.getProcess(), readerPositions);
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:231]: cleanupReaderGroup invokes `readerGroup.readerOffline(` on every reader here. It is not required since readers are marked offline @ `io.pravega.controller.eventProcessor.impl.EventProcessorCell.Delegate#shutDown` during the stop of the eventProcessor cell.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 3]
```diff
@@ -204,8 +199,41 @@ protected void shutDown() {
...
+                } catch (CheckpointStoreException e) {
+                    log.warn("Error removing Reader Group {} from checkpoint store. " + readerGroup.getGroupName(), e);
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:233]: I think this log is wrong, as it is concatenating `readerGroup.getGroupName()` and also placing a `{}` for it. You may just replace `+` by `,`.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 4]
```diff
@@ -214,64 +242,50 @@ protected void shutDown() {
...
-                    return;
-                } else {
-                    throw e;
-                }
+            log.debug("Attempting to seal Reader Group {} for Controller {}", readerGroup.getGroupName(), controllerId);
+            // Change Reader Group State to SEALED so no new Readers can join
+            readerPositions = checkpointStore.sealReaderGroup(controllerId, readerGroup.getGroupName());
+        } catch (CheckpointStoreException e) {
+            if (!e.getType().equals(CheckpointStoreException.Type.NoNode)) {
+                throw e;
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:268]: The behavior has slightly changed here in the case of an exception different to not finding the zNode, right? In the previous code, in that case the method returns `null` whereas now it will return an empty map. I suppose that it does not change anything downstream, right? (e.g., a null check after this method)

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 5]
```diff
@@ -204,8 +199,41 @@ protected void shutDown() {
...
+                // If any of the following operations error out, the fact is just logged.
+                // And some other controller process would clean-up the reader group data
+                // its readers and their position objects from checkpoint store.
+
+                // Seal the Reader Group
+                Map<String, Position> readerPositions = ImmutableMap.of();
+                try {
+                    readerPositions = sealReaderGroup(actorSystem.getProcess());
+                } catch (CheckpointStoreException e) {
+                    log.warn("Error sealing Reader Group {}.", readerGroup.getGroupName(), e);
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:211]: Code coverage needs to be improved for this PR. In the codecov report, most of these catch blocks are never exercised. As the issue that this PR is fixing happens in the non-happy path, I suspect that is when these catch blocks will get exercised. My suggestion: i) break down the different steps in `shutDown()` into individual functions, ii) make them package protected and tag them with `@VisibleForTesting` so it is easier to test them individually, iii) for testing the whole workflow of `shutDown()`, you can `spy()` an `EventProcessorGroupImpl` object an make specific methods, like `sealReaderGroup`, throw whatever exception and see how the rest of the shutdown workflow behaves in the presence of that event.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Looks good, I left some comments.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:268]: There is no change in behavior of `sealReaderGroup` : https://github.com/pravega/pravega/blob/f010db50b47a3461904a09506657fda0d34b8b19/controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java#L127

Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:268]: The refactored _if statement_  just does the same thing in a more concise way.....

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Yes. Thanks for catching this. fixed.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Ok. didn't realize cell.stopAsync() does readerOffline as well... Fixed.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:211]: working on coverage...

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 6]
```diff
@@ -204,8 +199,51 @@ protected void shutDown() {
...
+                    cell.stopAsync();
+                }
+                // Await termination of cells
+                for (EventProcessorCell<T> cell : eventProcessorMap.values()) {
+                    try {
+                        cell.awaitTerminated();
+                        log.info("Termination of event processor cell: {} completed successfully.", cell);
+                    } catch (Exception e) {
+                        log.warn("Failed terminating event processor cell {}.", cell, e);
+                        throw e;
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:226]: If an exception is thrown here then the controller would not remove the checkpointStore reader? The older code would attempt to remove the reader(s) fromthe checkpointStore even in such a scenario. Is this change in behaviour intended?

Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:226]: The addition of line `throw e`  here is intentional. If we fail to stop the EventProcessor cell there is a possibility that the Readers in corresponding reader group were not made offline and without that we do not want t remove them from the checkpoint store.
The expectation here is that another controller will sweep entries for these readers and declare them offline as part of notifyProcessFailure.......
Alternatively, if invoking the readerOffline() is an idempotent operation we could attempt doing it again here by invoking cleanupReaderGroup...

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 7]
```diff
@@ -204,8 +199,51 @@ protected void shutDown() {
...
+                        //Remove reader from Checkpoint Store
+                        log.info("{} Removing reader={} from checkpoint store", this.objectId, reader);
+                        checkpointStore.removeReader(controllerId, readerGroup.getGroupName(), reader);
+                    }
+
+                    // Finally, remove reader group from the checkpoint store
+                    log.info("Removing reader group {} from process {}", readerGroup.getGroupName(), controllerId);
+                    checkpointStore.removeReaderGroup(actorSystem.getProcess(), readerGroup.getGroupName());
+                } catch (CheckpointStoreException e) {
+                    log.warn("Error removing Reader Group {} from checkpoint store. ", readerGroup.getGroupName(), e);
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:243]: Ok. will fix this

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 8]
```diff
@@ -214,64 +252,50 @@ protected void shutDown() {
...
-                log.info("{} Notifying readerOffline reader={}, position={}", this.objectId, entry.getKey(), entry.getValue());
+    private void cleanupReaderGroup(String controllerId, Map<String, Position> readerPositions) throws CheckpointStoreException {
+            for (Map.Entry<String, Position> entry : readerPositions.entrySet()) {
+                // 1. Remove failed readers from Reader Group in State Synchronizer
+                log.info("{} Notifying readerOffline reader={}, position={} for Reader Group {}", this.objectId, entry.getKey(), entry.getValue(), readerGroup.getGroupName());
                 readerGroup.readerOffline(entry.getKey(), entry.getValue());
+
+                // 2. Remove reader from Checkpoint Store
+                log.info("{} Removing reader={} from checkpoint store", this.objectId, entry.getKey());
+                checkpointStore.removeReader(controllerId, readerGroup.getGroupName(), entry.getKey());
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:293]: Ok. Handled this.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 9]
```diff
@@ -214,64 +252,50 @@ protected void shutDown() {
...
-                if (e.getType().equals(CheckpointStoreException.Type.NoNode)) {
-                    return;
-                } else {
-                    throw e;
-                }
+            log.debug("Attempting to seal Reader Group {} for Controller {}", readerGroup.getGroupName(), controllerId);
+            // Change Reader Group State to SEALED so no new Readers can join
+            readerPositions = checkpointStore.sealReaderGroup(controllerId, readerGroup.getGroupName());
+        } catch (CheckpointStoreException e) {
+            if (!e.getType().equals(CheckpointStoreException.Type.NoNode)) {
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:277]: nit: This act of suppressing the NoNode exception can be done inside the ZKCheckpointStore and we could eliminate this method from EventProcessorGroupImpl.

**Review by shrids — APPROVED** [review]
+1 from my end. All my blocking review comments have been addressed.

@pbelgundi There is a pending refactor comment and a checkstyle issue. Please fix it.
Also, please run system tests against and validate the behaviour when the controller count is reduced to 0 and brought back up.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 9 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:277]: That does not feel like the right thing to do. For a remove operation, if the node is already removed it should be idempotent so there is no benefit in throwing the NoNode Exception, but that cannot be said about sealReaderGroup. I'd want the checkpoint store method to throw an exception and we handle it here, cause here we know its fine to not be able to find that node....

**Review by RaulGracia — CHANGES_REQUESTED** [review]
LGTM, but we need at least one system test green build with this change.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:211]: fixed

**Comment by pbelgundi** [comment]
> LGTM, but we need at least one system test green build with this change.



> LGTM, but we need at least one system test green build with this change.

Yes thats in progress, will update here once done.

**Review by RaulGracia — APPROVED** [review]
