### PR TITLE
Issue 2465: log better grpc errors.

### LINKED ISSUE #2465: Improve SSL-related error messages
**Problem description**
When the client fails to connect to the controller due to an SSL error, the only warning that is emitted is:
```
21:13:51,914 WARN  io.pravega.client.stream.impl.ControllerImpl                  - gRPC call failed with server error: UNAVAILABLE
```

I've seen two scenarios where this occurs:
1. A mismatch where the client attempts a non-SSL connection to an SSL-enabled controller.
2. An SSL negotiation failure.

Turning up the verbosity, one sees:
```
21:13:51,891 DEBUG io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext  - verification of certificate failed
java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:221)
	at io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:644)
	at io.pravega.shaded.io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:482)
	at io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1020)
	at io.pravega.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1127)
	at io.pravega.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:210)
	at io.pravega.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)
	at io.pravega.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.pravega.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.pravega.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.pravega.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.pravega.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.pravega.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.pravega.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.pravega.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.pravega.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.pravega.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.pravega.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.pravega.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.pravega.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.pravega.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.pravega.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.pravega.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.pravega.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.pravega.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.pravega.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Problem location**

**Suggestions for an improvement**
Emit `ERROR` log events and throw a useful error message after the retries are exhausted.

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
Currently the grpc errors printed are not helpful/actionable. They are hidden behind layers of Pravega and `grpc` exception chain. It will help the user debug it if we could print the complete exception chain.

**Purpose of the change**
Fixes #2465.

**What the code does**
1. Adds a test case for SSL failure.
2. Logs the exception chain when a `grpc` call fails.

**How to verify it**
The test case passes.
The complete exception chain is printed in case of a cert failure.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/Exceptions.java [hunk 1]
```diff
@@ -212,6 +212,18 @@ public static void checkNotClosed(boolean closed, Object targetObject) throws Ob
         }
     }
 
+    /**
+     * Logs the exception and its cause to error log.
+     *
+     * @param t   The exception to be logged.
+     */
+    public static void unwrapAndLogException(Throwable t) {
+       log.error("Exception :", t);
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/Exceptions.java]: This is a nice utility, however we lose some valuable information by doing so. When you invoke `log.error` (or any other method), this will be recorded as coming from `Exceptions` and not from whatever class is invoking this (we also lose the line number as well).

File: common/src/main/java/io/pravega/common/Exceptions.java [hunk 2]
```diff
@@ -212,6 +212,18 @@ public static void checkNotClosed(boolean closed, Object targetObject) throws Ob
         }
     }
 
+    /**
+     * Logs the exception and its cause to error log.
+     *
+     * @param t   The exception to be logged.
+     */
+    public static void unwrapAndLogException(Throwable t) {
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/Exceptions.java]: Why is this method needed? If a throwable has a cause set the cause will automatically be logged when the exception is logged. That log.error line below will log the full chain of causes.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java [hunk 3]
```diff
@@ -968,6 +968,7 @@ public void onNext(T value) {
         @Override
         public void onError(Throwable t) {
             log.warn("gRPC call failed with server error: {}", t.getMessage());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: It would be better if this told us more about which message got the failure. Maybe we could include the request in the log here.

**Comment by EronWright** [comment]
This PR seems focused on server-side logging, but arguably more important is the client experience because the client is probably at fault in SSL scenarios.   Could the client throw higher-level exceptions that better communicate the issue?

File: common/src/main/java/io/pravega/common/Exceptions.java (hunk 1 above)
Comment (arvindkandhare) [reply common/src/main/java/io/pravega/common/Exceptions.java]: Dropping this method as `log.error` or `warn` itself goes through the chains.

File: common/src/main/java/io/pravega/common/Exceptions.java (hunk 2 above)
Comment (arvindkandhare) [reply common/src/main/java/io/pravega/common/Exceptions.java]: There was an issue with the call to `log.error`. Fixed it. We do not need this method. `log.error` fixes this.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java (hunk 3 above)
Comment (arvindkandhare) [reply client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: Fixed. Added more details to the log.

**Comment by arvindkandhare** [comment]
The exceptions is in the chained exception. After this fix, the error will also be logged. Are you saying Pravega client needs to translate the chained exceptions to Pravega client specifi exceptions?

> This PR seems focused on server-side logging, but arguably more important is the client experience because the client is probably at fault in SSL scenarios. Could the client throw higher-level exceptions that better communicate the issue?

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java [hunk 4]
```diff
@@ -957,17 +958,25 @@ public void close() {
...
+
         @Override
         public void onNext(T value) {
             result = value;
         }
 
         @Override
         public void onError(Throwable t) {
-            log.warn("gRPC call failed with server error: {}", t.getMessage());
+            log.warn("gRPC call for {} with trace id {} failed with server error.", traceId, method, t);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: your arguments are in the wrong order

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java [hunk 5]
```diff
@@ -957,17 +958,25 @@ public void close() {
...
     private static final class RPCAsyncCallback<T> implements StreamObserver<T> {
+        private final long traceId;
+        private final String method;
         private T result = null;
         private final CompletableFuture<T> future = new CompletableFuture<>();
 
+        RPCAsyncCallback(long traceId, String method) {
+            this.traceId = traceId;
+            this.method = method;
+
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: extra line

File: common/src/main/java/io/pravega/common/Exceptions.java [hunk 6]
```diff
@@ -10,16 +10,16 @@
...
-
 import java.util.concurrent.CompletionException;
 import java.util.concurrent.ExecutionException;
 import lombok.SneakyThrows;
+import lombok.extern.slf4j.Slf4j;
 
 /**
  * Helper methods that perform various checks and throw exceptions if certain conditions are met.
  */
+@Slf4j
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/Exceptions.java]: Undo all changes to this class.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java (hunk 4 above)
Comment (arvindkandhare) [reply client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: Fixed.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java (hunk 5 above)
Comment (arvindkandhare) [reply client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: Fixed.

File: common/src/main/java/io/pravega/common/Exceptions.java (hunk 6 above)
Comment (arvindkandhare) [reply common/src/main/java/io/pravega/common/Exceptions.java]: Fixed.
