### PR TITLE
Issue 6563: Fix operationlogsize metric

### LINKED ISSUE #6563: OperationLog size metric needs to be fixed
**Describe the bug**
OperationLog size metric in the SegmentStore Grafana dashboard does not display the operation log size correctly.

**To Reproduce**
One simple experiment to prove the case is we can bring down Tier-2 while clients are writing data. We expect the metric to constantly increase since the log is getting filled with operations. But instead we see that there are sudden dips in the metric which is wrong

**Screenshots**
N/A

**Additional information**
N/A

### PR DESCRIPTION
**Pull request by abhinb**
Signed-off-by: Abhin Balur <Abhin_Balur@dell.com>

**Change log description**  
Fixes the OpeartionLog size metric in Grafana dashboard for SegmentStore.

**Purpose of the change**  
Fixes #6563 

**What the code does**  
Fixes the OpeartionLog size metric in Grafana dashboard for SegmentStore. This metric was originally a 
counter which was leading to wrong operation log sizes being reported when in actuality it should have been a guage.

**How to verify it**  
Bring up Grafana dashboards for SegmentStore. View the operationlog size graph while writing data to Pravega.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java [hunk 1]
```diff
@@ -37,9 +37,7 @@
 import java.util.concurrent.TimeUnit;
 import lombok.val;
 
-import static io.pravega.shared.MetricsTags.containerTag;
-import static io.pravega.shared.MetricsTags.eventProcessorTag;
-import static io.pravega.shared.MetricsTags.throttlerTag;
+import static io.pravega.shared.MetricsTags.*;
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java:40]: This kind of imports are not allowed.

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java (hunk 1 above)
Comment (abhinb) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java]: corrected...didnt come up in checkstyle though...doesnt checkstyle catch this?

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java]: Yes, it should have been detected by checkstyle.

Comment (shshashwat) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentStoreMetrics.java]: Strange to see that this was not caught by the checkstyle. otherwise such things are always handled during the build part itself.

**Review by RaulGracia — APPROVED** [review]
LGTM, let me know when system tests pass. Also, I assume that you have tested this locally and the metric is being reported correctly in Grafana.
