### PR TITLE
Issue 4157: Support for Divergent TLS configuration for Controller and Segment Store

### LINKED ISSUE #4157: Configuration flag to allow TLS-disabled Controller to connect to TLS-enabled Segment Store
**Problem description**
In some deployment configurations, TLS is disabled for Controller service endpoints, while it is enabled for Segment Store service endpoints. This happens when you terminate TLS at a reverse proxy or a Kubernetes Ingress for Controller service instances, while you terminate TLS directly at the service for Segment Store instances. 

Under such a configuration, TLS is configured as disabled for the Controller. But then, Controller assumes that TLS is also disabled for the Segment Store, and therefore encounters an exception of the following form when it attempts to connect to the Segment Store: 

```
Caused by: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: _system table: _system/_tables/scopes
	at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:515)
	... 36 common frames omitted
Caused by: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: _system table: _system/_tables/scopes
	at io.pravega.controller.store.stream.StoreException.create(StoreException.java:105)
	at io.pravega.controller.store.stream.PravegaTablesStoreHelper.lambda$null$49(PravegaTablesStoreHelper.java:483)
	... 36 common frames omitted
Caused by: io.pravega.controller.server.WireCommandFailedException: WireCommandFailed with type READ_TABLE reason ConnectionFailed
	at io.pravega.controller.server.SegmentHelper.lambda$sendRequest$26(SegmentHelper.java:639)
	... 36 common frames omitted
```

Correspondigly, on the Segment Store side, one'd observe exceptions as shown below: 

```
2019-09-06 07:02:16,435 19060160 [epollEventLoopGroup-11-2] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection /100.64.65.143:16317
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1140)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1101)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1212)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:
```

**Problem location**

**Suggestions for an improvement**
Introduce a new optional configuration flag that tells a Controller that TLS is enabled for Segment Store, even if that is not the case for itself.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Adds support for enabling TLS for segment store while keeping it disabled for Controller. 

See the description section of issue #4157 to understand the motivation. 

**Purpose of the change**  
Resolves #4157  

**What the code does**  
1. Adds an optional Controller configuration to declare that Segment Store has TLS enabled, even while it is not so for the Controller. This can be set by declaring using one of the following: 
   * Java system property `controller.auth.segmentStoreTlsEnabled=true` via the manifest (containerized deployments) or command line (manual deloyments)
   * `controller.auth.segmentStoreTlsEnabled=true` in Controller config file
   * Environment variable `TLS_ENABLED_FOR_SEGMENT_STORE=true`
2. Adds additional flags in Client Config to support cases where the Controller URI has non-TLS schemes (`tcp` and `pravega`), but Segment Store has TLS enabled. See `ClientConfig` for these changes. 
3. Use a new Client Config flag in `AutoScaleProcessor` to connect to Controller over Plaintext channel, even while AutoScaleProcessor itself has TLS enabled. 
4. Modify the client-side Controller proxy `ControllerImpl` to use the new flags suitably. The same proxy is used by both external clients (on the application side), as well as internal clients (AutoScaleProcessor-to-Controller communications).
5. Modify the client-side Segment Store proxy `ConnectonPoolImpl` to use the new flag that determines whether segment store TLS is enabled. 

**How to verify it**  
See [this](https://gist.github.com/ravisharda/22312836b4692d93e864b50177e85e6e) Gist on how to verify it.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java [hunk 1]
```diff
@@ -38,6 +38,8 @@
     private final boolean controllerClusterListenerEnabled;
     private final TimeoutServiceConfig timeoutServiceConfig;
 
+    private final String tlsEnabledForSegmentStore;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java]: why is this a string and not a boolean?

Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/impl/ControllerServiceConfigImpl.java]: The value of this field can be true/false/empty. If we make this a boolean, it'll need to be either true/false. I could make it `Optional<Boolean>`, but using `Optional<>` as a method argument is considered as anti-pattern by many.

File: client/src/main/java/io/pravega/client/ClientConfig.java [hunk 2]
```diff
@@ -66,12 +66,50 @@
...
-        if (scheme == null) {
-            return false;
+        if (deriveTlsEnabledFromControllerURI) {
+            String scheme = this.controllerURI.getScheme();
+            if (scheme == null) { // scheme is null when URL is of the kind //<hostname>:<port>
+                return false;
+            }
+            return scheme.equals("tls") || scheme.equals("ssl") || scheme.equals("pravegas");
+        } else {
+            return enableTlsToController && enableTlsToSegmentStore;
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/ClientConfig.java]: `isEnableTls()` maintains its semantics as before to indicate whether TLS is enabled - for both Controller and Segment Store. So, it uses `AND`. 

We now also have the two flags `enableTlsToController` and `enableTlsToSegmentStore` and corresponding getters for cases where you have it enabled for one and not for the other. When that happens `isEnableTls()` will return false.

File: client/src/main/java/io/pravega/client/ClientConfig.java [hunk 3]
```diff
@@ -66,12 +66,50 @@
...
+    private final boolean enableTlsToController;
+
+    /**
+     * An optional property representing whether to enable TLS for client's communication with the Controller.
+     *
+     * If this property and {@link #enableTlsToController} are not set, and the scheme used in {@link #controllerURI}
+     * is {@code tls} or {@code pravegas}, TLS is automatically enabled for both client-to-Controller and
+     * client-to-Segment Store communications.
+     */
+    private final boolean enableTlsToSegmentStore;
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/ClientConfig.java]: similar question as above.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java [hunk 4]
```diff
@@ -50,6 +50,8 @@
      */
     boolean isControllerClusterListenerEnabled();
 
+    String getTlsEnabledForSegmentStore();
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java]: java doc, should it return boolean ?

File: controller/src/main/java/io/pravega/controller/util/Config.java [hunk 5]
```diff
@@ -74,6 +74,7 @@
     public static final String TLS_TRUST_STORE;
     public static final String TOKEN_SIGNING_KEY;
     public static final int ACCESS_TOKEN_TTL_IN_SECONDS;
+    public static final String TLS_ENABLED_FOR_SEGMENT_STORE;
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/util/Config.java]: https://github.com/pravega/pravega/blob/7f76baa4674f1e572cc0571bb22f505ae0583076/controller/src/main/java/io/pravega/controller/util/Config.java#L71
Here the config`TLS_ENABLED` of type boolean is for controller alone right ?

File: client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java [hunk 6]
```diff
@@ -259,7 +259,8 @@ public void initChannel(SocketChannel ch) throws Exception {
      */
     private SslContext getSslContext() {
         final SslContext sslCtx;
-        if (clientConfig.isEnableTls()) {
+        if (clientConfig.isEnableTls() || clientConfig.isEnableTlsToSegmentStore()) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/netty/impl/ConnectionPoolImpl.java]: Sure, that's a good idea. I've made the change as suggested, while also modifying the ClientConfig interface a bit. Please take a look and see if it looks good.

File: client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java [hunk 7]
```diff
@@ -159,7 +159,8 @@ public ControllerImpl(ManagedChannelBuilder<?> channelBuilder, final ControllerI
                                 .retryingOn(StatusRuntimeException.class)
                                 .throwingOn(Exception.class);
 
-        if (config.getClientConfig().isEnableTls()) {
+        if (config.getClientConfig().isEnableTls() || config.getClientConfig().isEnableTlsToController()) {
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java]: Sure, I've made the change. The code looks simpler now.

File: client/src/main/java/io/pravega/client/ClientConfig.java [hunk 8]
```diff
@@ -66,12 +66,50 @@
...
+    private final boolean deriveTlsEnabledFromControllerURI;
+
+    /**
+     * An optional property representing whether to enable TLS for client's communication with the Controller.
+     *
+     * If this property and {@link #enableTlsToSegmentStore} are not set, and the scheme used in {@link #controllerURI}
+     * is {@code tls} or {@code pravegas}, TLS is automatically enabled for both client-to-Controller and
+     * client-to-Segment Store communications.
+     */
+    private final boolean enableTlsToController;
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/ClientConfig.java]: Since the ClientConfig constructor is package-private, I suppose it is not intended to be used by users. What do you say? I can override the constructor to add some validation to prevent such a possibility, but I believe that may be overkill since the constructor's accessibility is limited.

File: client/src/main/java/io/pravega/client/ClientConfig.java [hunk 9]
```diff
@@ -66,12 +66,50 @@
      */
     private final int maxConnectionsPerSegmentStore;
 
+    /**
+     * An internal property that determines whether TLS enabled is derived from Controller URI. It cannot be set
```
[the remark this answers is not in the document]
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/ClientConfig.java]: Sure, I have made the change in the latest commit. I am using `Getter(AccessLevel.NONE)`.

File: client/src/main/java/io/pravega/client/ClientConfig.java (hunk 3 above)
Comment (ravisharda) [reply client/src/main/java/io/pravega/client/ClientConfig.java]: Sure, I have made the change in the latest commit. I am using Getter(AccessLevel.NONE).

File: controller/src/main/java/io/pravega/controller/util/Config.java (hunk 5 above)
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/util/Config.java]: Yes, that is right. Segment store has its own set of environment variables (in `ServiceConfig`).

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java (hunk 4 above)
Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/ControllerServiceConfig.java]: Sure, have added the Java doc. 

As for making it a boolean, @shiveshr had a similar comment, to which I responded in https://github.com/pravega/pravega/pull/4163#discussion_r324076746. 

Please see if it makes sense.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 10]
```diff
@@ -173,20 +175,25 @@ protected void startUp() {
...
+            }
+
+            connectionFactory = new ConnectionFactoryImpl(clientConfigBuilder.build());
             segmentHelperRef.compareAndSet(null, new SegmentHelper(connectionFactory, hostStore));
 
             GrpcAuthHelper authHelper = new GrpcAuthHelper(serviceConfig.getGRPCServerConfig().get().isAuthorizationEnabled(),
                     serviceConfig.getGRPCServerConfig().get().getTokenSigningKey(),
                     serviceConfig.getGRPCServerConfig().get().getAccessTokenTTLInSeconds());
-            
+
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: nit: revert

Comment (ravisharda) [reply controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: The blank line is the same as before, but there are new lines added to the code above the `GrpcAuthHelper` instantiation, which might be causing this difference. The formatting looks OK in the fil when viewing it standalone:

https://github.com/pravega/pravega/blob/ea1aadd4920cc27aa4e59b0d318ffd90c117edf9/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L196

Am I missing something?
