### PR TITLE
Issue 3921: SegmentHelper should not throw a ConnectionFailedException incase of TableSegmentIsEmpty response for deleteTableSegment

### LINKED ISSUE #3921: SegmentHelper should not throw a ConnectionFailedException incase of TableSegmentIsEmpty response for deleteTableSegment
**Problem description**
Observing the following stack trace with the latest master.

```
2019-06-18 01:50:06,489 3487457 [epollEventLoopGroup-2-1] WARN  i.p.c.s.s.PravegaTablesStoreHelper - exception of unknown type thrown delete table: _system/_tables/testReadTxnWriteAutoScaleScope34623
0808/testReadTxnWriteAutoScaleStream/transactionsInEpoch-4.#.fb7c1f21-b793-4761-adf7-655e5f417d36
io.pravega.shared.protocol.netty.ConnectionFailedException: Unexpected reply of Table Segment is not empty: _system/_tables/testReadTxnWriteAutoScaleScope346230808/testReadTxnWriteAutoScaleStream/transactionsInEpoch-4.#.fb7c1f21-b793-4761-adf7-655e5f417d36 when expecting one of class io.pravega.shared.protocol.netty.WireCommands$SegmentDeleted, class io.pravega.shared.protocol.netty.WireCommands
$NoSuchSegment
        at io.pravega.controller.server.SegmentHelper.transformReply(SegmentHelper.java:1105)
        at io.pravega.controller.server.SegmentHelper.lambda$deleteTableSegment$5(SegmentHelper.java:519)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.netty.impl.RawClient.reply(RawClient.java:104)
        at io.pravega.client.netty.impl.RawClient.access$300(RawClient.java:36)
        at io.pravega.client.netty.impl.RawClient$ResponseProcessor.process(RawClient.java:63)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
```

**Problem location**

SegmentHelper.java

**Suggestions for an improvement**
We should throw a `new WireCommandFailedException(type, WireCommandFailedException.Reason.TableSegmentNotEmpty)` instead of throwing a blanket 
`ConnectionFailedException` .

All other operations on SegmentHelper should be reviewed accordingly.

### PR DESCRIPTION
**Pull request by huide9**
Signed-off-by: huide9 <huide9@gmail.com>

**Change log description**  
Modify to throw correct exception instead using an unmatching exception info.

**Purpose of the change**  
fixes #3921

**What the code does**  
* change to use matching exception for TableSegmentIsEmpty reply
* add WireCommandType info into exception so can get find out the operation type

**How to verify it**  
UT case modified to verify the changes. The matching excpetion reason: *WireCommandFailedException.Reason.TableSegmentNotEmpty*  should be caught correctly.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/SegmentHelper.java [hunk 1]
```diff
@@ -1089,17 +1097,23 @@ private void closeConnection(Reply reply, RawClient client) {
...
             log.info(reply.getRequestId(), "{} {} {}.", requestType.getSimpleName(), qualifiedStreamSegmentName,
                     reply.getClass().getSimpleName());
             return true;
         } else if (reply instanceof WireCommands.NoSuchSegment) {
-            throw new NoSuchSegmentException(reply.toString());
+            throw new WireCommandFailedException(type, WireCommandFailedException.Reason.SegmentDoesNotExist);
         } else if (reply instanceof WireCommands.WrongHost) {
-            throw new ConnectionFailedException(reply.toString());
+            throw new WireCommandFailedException(type, WireCommandFailedException.Reason.UnknownHost);
+        } else if (reply instanceof WireCommands.TableSegmentNotEmpty) {
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/server/SegmentHelper.java]: Why can't you put this in the Map you have at the top of this class?

Comment (huide9) [reply controller/src/main/java/io/pravega/controller/server/SegmentHelper.java]: the map is for expectedReplies

**Comment by RaulGracia** [comment]
System tests are passing with this PR. Please, let's try to merge this soon so it can be cherry picked to `0.5`.
