### PR TITLE
Issue 1596: Fix use of negative in modulo operation.

### LINKED ISSUE #1596: ArrayIndexOutOfBounds during readNextEvent
**Problem description**
During recent stress tests the readers failed with ArrayIndexOutOfBounds during readNextEvent.

Test had been running for 1 day and 23 hours and the readers at this point had read 2,763,000 events.

**Problem location**

The following stack traces show the issue, unfortunately I have no other information from the environment.

```
java.lang.ArrayIndexOutOfBoundsException: -1
java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at io.pravega.client.stream.impl.Orderer.nextSegment(Orderer.java:35)
at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:86)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

and another run:

```
java.lang.ArrayIndexOutOfBoundsException: -3
at java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at io.pravega.client.stream.impl.Orderer.nextSegment(Orderer.java:35)
at io.pravega.client.stream.impl.EventStreamReaderImpl.readNextEvent(EventStreamReaderImpl.java:86)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.PravegaReader.start(PravegaReader.java:78)
at com.emc.nautilus.pravega.taskexecutor.workers.readers.ReaderWorkerManager.lambda$start$0(ReaderWorkerManager.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

**Suggestions for an improvement**

Handle whatever issue causes the IndexOutOfBounds

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
 Fix use of negative in modulo operation.

**Purpose of the change**
Fixes #1596. Operator was returning values in a round-robin manner. This was done with a counter and a modulo operator. This broke when the integer wrapped around and the result became negative. 

**What the code does**
Uses MathHelpers.abs to avoid the negative value. 

**How to verify it**
The stress tests should no longer fail with ArrayIndexOutOfBounds

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/Orderer.java [hunk 1]
```diff
@@ -32,13 +33,13 @@ SegmentInputStream nextSegment(List<SegmentInputStream> segments) {
             return null;
         }
         for (int i = 0; i < segments.size(); i++) {
-            SegmentInputStream inputStream = segments.get(counter.incrementAndGet() % segments.size());
+            SegmentInputStream inputStream = segments.get(MathHelpers.abs(counter.incrementAndGet()) % segments.size());
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/Orderer.java]: under what conditions would this be negative? When it overflows?

Just checking because this would mean we have about 2 billion segments attached to a stream. That's unless you repeatedly call this method on an arbitrary list of segments, some of which are repeated.

Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/Orderer.java]: yes, overflow. You are correct we call this every time a client calls readNextEvent()

Comment (shiveshr) [inline client/src/main/java/io/pravega/client/stream/impl/Orderer.java]: reaching 2B segments would be huge!
@maddisondavid what is the routing key used while writing events?
Lets say a fixed routing key was used. So all traffic goes to a single segment each time.
Then if a segment is split every 10 minutes, and remainder are merged (as 2 or 3 neighbours) every 20 minutes, to reach 2 billion it will take O(million minutes). 

i dont think overflow would have happened because there are other things that will start breaking at that number, like 
1. the segment table with each record for a segment being 16 bytes. that will make it about 32 gb of a node data in zookeeper. same for history table and index table.
merely reading that from the zk or writing back to zk will take hours.
(the tables are designed for maximum of O(M) segments so that it stays within few mbs of data at worst. 
2. processing through that data, all of it happens in memory --> controller will start getting OOM before we are handing O(B) segments. 

So it would be hard to believe that we had an overflow. things would break much before the overflow would happen.
