### PR TITLE
Issue 3624: BugFix - Segment Seal and reconnect race causes io.netty.util.IllegalReferenceCountException

### LINKED ISSUE #3624: Observing "Exception: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock" error in Segmentstore while running IO
**Observing "Exception: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock" error in Segmentstore while running IO**

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2210.81867f3
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: adrianmo/pravega-operator:0.3.2
```
**Segmentstore log error:**
```
2019-04-12 08:18:34,438 10687508 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: b3bf83dd-7262-49d3-9b8b-b2f30947ae18 on segment: longevity/smash/47.#epoch.27
2019-04-12 08:18:34,539 10687609 [epollEventLoopGroup-11-1] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.pravega.shared.protocol.netty.AppendDecoder.processCommand(AppendDecoder.java:102)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:55)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:36)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 28 common frames omitted
```

### PR DESCRIPTION
**Pull request by shrids**
Note: additional debug statements have been added which will be removed after testing.
**Change log description**  
Fix a bug in event writers to prevent connections from being established to sealed / truncated segments.

**Purpose of the change**  
Fixes #3624

**What the code does**  
Segment writers (`SegmentOutputStream`) on sending an event to the SegmentStore will receive a `WireCommands.SegmentIsSealed` in case the segment is sealed. On receiving the `SegmentIsSealed`  the segment writers invokes a callback to write all the inflight events to the successor segments.

Now, if there is a connection drop before the inflight events for the specific segment writer is resent to the successors then the current segment writer would also try to establish a client connection (establish connection , setup appends and retransmit all inflight) to the same sealed segment. 

This race causes the same inflight events to be sent by the segment writer while setting up client connection and by the callback for resending it to successor segments. This will cause `io.netty.util.IllegalReferenceCountException` since netty automatically invokes `ByteBuf.release()` when data is sent out on the netty pipeline.

The fix ensures we do not try to re establish connection for a sealed segment.

**How to verify it**  
Longevity testing in progress. 
All the existing and newly added tests should continue to pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -363,6 +363,7 @@ public void appendSetup(AppendSetup appendSetup) {
                     if (e == null) {
                         state.connectionSetupComplete(connection);
                     } else {
+                        log.debug("Error while sending inflight during setup append for writer " + writerId, e);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: I think this is just going to double log the exception. failConnection should already be logging.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -496,7 +497,16 @@ public void flush() throws SegmentSealedException {
...
+            } catch (SegmentSealedException | NoSuchSegmentException e) {
+                if (StreamSegmentNameUtils.isTransactionSegment(segmentName)) {
+                    log.warn("Exception observed during a flush on a transaction segment, this indicates that the transaction is " +
+                                     "commited/aborted. Details: {}", e.getMessage());
+                    failConnection(e);
+                } else {
+                    log.info("Exception observed while obtaining connection during flush. Details: {} ", e.getMessage());
+                }
             } catch (Exception e) {
+                log.warn("Exception observed while obtaining connection during flush", e);
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Again, double logging.

**Comment by tkaitchuck** [comment]
We should run the system tests on this branch before merging.

**Comment by shrids** [comment]
Update: Added junits and the system test run was successful.
ref: https://asd-nautilus-jenkins.isus.emc.com/job/test-pravega-continuous/1991/

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 1 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: removed it.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 2 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: removed it.

**Comment by RaulGracia** [comment]
@shrids has been @sumit-bm able to confirm that the issue is not reproduced in a longevity run?

**Comment by shrids** [comment]
@RaulGracia , A longevity run has been started by @vedanthh , it is going strong for the last 5 hours.
