### PR TITLE
Issue 5852: Speed up build verification

### LINKED ISSUE #5852: Execute unit tests in parallel
Today only one unit test executes at a time. However this constraint is not mandatory. 
Gradle supports running multiple tests in parallel. We should take advantage of this.

This will require a lot of testing to make sure that tests aren't implicitly assuming they are the only test running.

### LINKED ISSUE #5864: Tests involving PravegaEmulatorResource sometimes fail in setup
**Describe the bug**
AuthEnabledInProcPravegaClusterTest
InProcPravegaClusterTest
SecurePravegaClusterTest

All sometimes fail before the test even begins.

**To Reproduce**
This is easiest to reproduce on Jankins.

**Additional context**
This seems to relate to the following sequence:
```
2021-03-18 19:51:59,996 52850 [Test worker] DEBUG o.a.z.s.persistence.FileTxnSnapLog - Opening datadir:/tmp/zookeeper3117588788010371194inproc snapDir:/tmp/zookeeper3117588788010371194inproc
2021-03-18 19:51:59,997 52851 [Test worker] INFO  o.a.zookeeper.server.ZKDatabase - zookeeper.snapshotSizeFactor = 0.33
2021-03-18 19:51:59,997 52851 [Test worker] INFO  o.a.z.server.ZooKeeperServer - minSessionTimeout set to 6000
2021-03-18 19:51:59,997 52851 [Test worker] INFO  o.a.z.server.ZooKeeperServer - maxSessionTimeout set to 60000
2021-03-18 19:51:59,997 52851 [Test worker] INFO  o.a.z.server.ZooKeeperServer - Created server with tickTime 3000 minSessionTimeout 6000 maxSessionTimeout 60000 datadir /tmp/zookeeper3117588788010371194inproc/version-2 snapdir /tmp/zookeeper3117588788010371194inproc/version-2
2021-03-18 19:52:00,019 52873 [Test worker] INFO  o.a.z.server.ServerCnxnFactory - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
2021-03-18 19:52:00,019 52873 [Test worker] INFO  i.p.s.s.i.b.ZooKeeperServiceRunner - Starting Zookeeper server at localhost:8116 ...
2021-03-18 19:52:00,020 52874 [Test worker] INFO  o.a.z.server.NIOServerCnxnFactory - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 4 worker threads, and 64 kB direct buffers.
2021-03-18 19:52:00,043 52897 [Test worker] INFO  o.a.z.server.NIOServerCnxnFactory - binding to port localhost/127.0.0.1:8116
2021-03-18 19:52:00,079 52933 [Test worker] INFO  o.a.z.s.persistence.FileTxnSnapLog - Snapshotting: 0x0 to /tmp/zookeeper3117588788010371194inproc/version-2/snapshot.0
2021-03-18 19:52:00,079 52933 [Test worker] INFO  o.a.z.s.persistence.FileTxnSnapLog - Snapshotting: 0x0 to /tmp/zookeeper3117588788010371194inproc/version-2/snapshot.0
2021-03-18 19:52:00,101 52955 [Test worker] DEBUG o.a.z.server.ZooKeeperServer - ZKShutdownHandler is not registered, so ZooKeeper server won't take any action on ERROR or SHUTDOWN server state changes
2021-03-18 19:52:00,883 53737 [Delegate] DEBUG i.p.c.s.impl.EventStreamReaderImpl - Empty event returned for reader cb4d2f54-275a-481c-a2cf-37a33a5cbbc3 
2021-03-18 19:52:00,883 53737 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Event processor SHUTDOWN EventProcessor[scaleGroup:0:cb4d2f54-275a-481c-a2cf-37a33a5cbbc3], state=STOPPING
2021-03-18 19:52:00,883 53737 [Delegate] INFO  i.p.c.e.impl.EventProcessorCell - Closing reader for EventProcessor[scaleGroup:0:cb4d2f54-275a-481c-a2cf-37a33a5cbbc3]
2021-03-18 19:52:00,883 53737 [Delegate] INFO  i.p.c.s.impl.EventStreamReaderImpl - Closing reader EventStreamReaderImpl( id=cb4d2f54-275a-481c-a2cf-37a33a5cbbc3) at position null.
2021-03-18 19:52:00,883 53737 [Delegate] DEBUG i.p.c.s.i.SegmentMetadataClientImpl - Getting segment info for segment: _system/_RGscaleGroup/0.#epoch.0
2021-03-18 19:52:00,883 53737 [Delegate] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: localhost:8111: for containerId: 0
```
Here the `Delegate` thread encountered an empty stream and then proceeds to shutdown.

This may relate to https://github.com/pravega/pravega/issues/5726

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**  
Reduce build times by running tests in parallel.
Fix many flakey test, and other test issues.

**Purpose of the change**  
Attempts to parallelize where possible
Fixes #5852

**What the code does**  
This mainly affect tests and build process. A few patches that were causing build failures are included.
This fixes #5864, #5008, #5657, #5515, #3691, #5565, #4966. And many others not previously reported.

**How to verify it**  
We need to actually run several builds to make sure this works, and does not introduce race conditions, ooms etc.

### CODE REVIEW

**Comment by tkaitchuck** [comment]
Need to deturmine if this is related:
```
io.pravega.controller.store.client.StoreClientFactoryTest > testZkSessionExpiryRetry FAILED
    java.lang.AssertionError: expected:<3> but was:<4>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.controller.store.client.StoreClientFactoryTest.testZkSessionExpiryRetry(StoreClientFactoryTest.java:89)
```

**Comment by tkaitchuck** [comment]
Also: 
```
io.pravega.test.integration.ControllerMetricsTest > streamMetricsTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.test.integration.ControllerMetricsTest.streamMetricsTest(ControllerMetricsTest.java:210)
```

File: bindings/src/test/java/io/pravega/storage/hdfs/HDFSStorageTest.java [hunk 1]
```diff
@@ -64,7 +65,7 @@
 
     @Before
     public void setUp() throws Exception {
-        this.baseDir = Files.createTempDirectory("test_hdfs").toFile().getAbsoluteFile();
+        this.baseDir = Files.createTempDirectory("test_hdfs_" + UUID.randomUUID().toString()).toFile().getAbsoluteFile();
```
Comment (eolivelli) [inline bindings/src/test/java/io/pravega/storage/hdfs/HDFSStorageTest.java:68]: Why aren't we using junit TemporaryFolder rule?

Comment (tkaitchuck) [reply bindings/src/test/java/io/pravega/storage/hdfs/HDFSStorageTest.java]: Done

**Comment by RaulGracia** [comment]
Related to #1385.

**Comment by RaulGracia** [comment]
Build is failing with a compile error:
```
/home/travis/build/pravega/pravega/controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java:15: error: package com.google.gson.internal does not exist
import com.google.gson.internal.LinkedTreeMap;
                               ^
/home/travis/build/pravega/pravega/controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java:58: error: cannot find symbol
    private final LinkedTreeMap<String, Integer> orderedScopes = new LinkedTreeMap<>();
                  ^
  symbol:   class LinkedTreeMap
  location: class InMemoryStreamMetadataStore
2 errors
```

File: shared/metrics/src/test/java/io/pravega/shared/metrics/MeterRegisterTest.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+        StatsProvider statsProvider = MetricsProvider.getMetricsProvider();
+        statsProvider.startWithoutExporting();
+    }
+    
+    @Test
+    public void testMeterRegister() {
+        initMetrics();
+        CompositeMeterRegistry registry = Metrics.globalRegistry;
+        Timer success = Timer.builder("name").tags().publishPercentiles(OpStatsData.PERCENTILE_ARRAY).register(registry);
+        success.record(100, TimeUnit.MILLISECONDS);
```
Comment (co-jo) [inline shared/metrics/src/test/java/io/pravega/shared/metrics/MeterRegisterTest.java:35]: Meter operations are NOOP'd until there is a `SimpleMeterRegistry` belonging to the composite.

https://micrometer.io/docs/concepts#_composite_registries

**Comment by ManishKumarKeshri** [comment]
Increasing the timeout in `StorageTestBase` to 60s would fix most of the `HDFSSimpleStorage` and `HDFSStorage` related tests.

File: client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java [hunk 3]
```diff
@@ -194,6 +195,7 @@ public void pruneUnusedConnections() {
     }
 
     @Override
+    @Synchronized
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java:198]: Did not understand the reason for this change here.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java [hunk 4]
```diff
@@ -159,7 +158,7 @@ public LocalController(ControllerService controller, boolean authorizationEnable
             case INVALID_STREAM_NAME:
                 throw new IllegalArgumentException("Illegal stream name: " + streamConfig);
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java:159]: we could log the stream name here too...

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/GRPCServer.java [hunk 5]
```diff
@@ -50,8 +52,9 @@ public GRPCServer(ControllerService controllerService, GRPCServerConfig serverCo
         this.config = serverConfig;
         GrpcAuthHelper authHelper = new GrpcAuthHelper(serverConfig.isAuthorizationEnabled(),
                 serverConfig.getTokenSigningKey(), serverConfig.getAccessTokenTTLInSeconds());
-        ServerBuilder<?> builder = ServerBuilder
+        ServerBuilder<?> builder = NettyServerBuilder
                 .forPort(serverConfig.getPort())
+                .withChildOption(ChannelOption.SO_REUSEADDR, true)
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/GRPCServer.java:57]: 👍  This should prevent port already in use on the GRPC server side.

File: client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java (hunk 3 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/connection/impl/ConnectionPoolImpl.java]: Removed

File: build.gradle [hunk 6]
```diff
@@ -88,6 +88,13 @@ allprojects {
         mavenLocal()
     }
 
+    gradle.projectsEvaluated {
+        tasks.withType(JavaCompile) {
+            sourceCompatibility = JavaVersion.VERSION_1_8
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply build.gradle]: Removed

File: .github/workflows/gradle.yml [hunk 7]
```diff
@@ -157,14 +157,39 @@ jobs:
...
-          segmentstore:storage:test
-          segmentstore:storage:impl:test
+          segmentstore:server:host:test
           bindings:test
           --parallel ${{env.GRADLE_OPTS}}
-      - name: Segment Store Host Tests      # Run this separately since it conflicts with segmentstore:storage:impl:test.
+      - name: Codecov
+        uses: codecov/codecov-action@v1.0.15
+
+  unit_storeage:
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply .github/workflows/gradle.yml]: Fixed

File: .github/workflows/gradle.yml [hunk 8]
```diff
@@ -157,14 +157,39 @@ jobs:
...
+        with:
+          path: ${{env.TEST_OUTPUT_CACHE_PATH}}
+          key: ${{github.run_id}}-${{github.job}}
+      - name: Segment Store Unit tests
         run: >
           ./gradlew
-          segmentstore:server:host:test
+          segmentstore:storage:test
+          segmentstore:storage:impl:test
+          bindings:test
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply .github/workflows/gradle.yml]: Removed

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]
This is great work. Thanks for doing it.

I left a few small comments/questions. 

Also, let's create an issue and reference it from within this PR.

File: .github/workflows/gradle.yml [hunk 9]
```diff
@@ -190,10 +214,15 @@ jobs:
         with:
           path: ${{env.TEST_OUTPUT_CACHE_PATH}}
           key: ${{github.run_id}}-${{github.job}}
+      - name: Static analysis tests
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply .github/workflows/gradle.yml:217]: Yes. We want to run spotbugs on all of our code. It's here as opposed the the build step so that it can run in parallel to the unit tests.

File: gradle/java.gradle [hunk 10]
```diff
@@ -90,11 +90,12 @@ plugins.withId('java') {
         testLogging.showExceptions = true
         testLogging.showStackTraces = true
         testLogging.events = ["FAILED"]
-        maxParallelForks = System.properties['maxParallelForks'] ? System.properties['maxParallelForks'].toInteger() : 1
+        maxParallelForks = System.properties['maxParallelForks'] ? System.properties['maxParallelForks'].toInteger() : 4
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply gradle/java.gradle:93]: Is there a way to obtain the number of cores?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 11]
```diff
@@ -339,8 +339,6 @@ private void doStop(Throwable cause) {
                     Throwable failureCause = getFailureCause(this.durableLog, this.writer, this.metadataCleaner);
                     if (failureCause == null) {
                         failureCause = cause;
-                    } else if (cause != null && failureCause != cause) {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:342]: When I was debugging some of the tests this error path caused a ref cycle which would in a different part of the code caused a OutOfStackSpace error because it sent error message processing into an infinite loop. 
I am not aware of this having been encountered anywhere else.

File: .travis.yml [hunk 12]
```diff
@@ -22,6 +22,7 @@ jobs:
   include:
     # Travis CI build has been deprecated in favor of GitHub Actions.
     - stage: build
+      name: check
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply .travis.yml:25]: Perhaps. We can do that in another PR.

File: gradle/wrapper/gradle-wrapper.properties [hunk 13]
```diff
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
+distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-bin.zip
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply gradle/wrapper/gradle-wrapper.properties:3]: I upgraded gradle. However since I started this PR gradle was upgraded by someone else. So it now shouldn't make any difference. I will revert.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java [hunk 14]
```diff
@@ -78,20 +83,21 @@
...
-                            .execute(), BK_EXCEPTION_HANDLER) );
+            CompletableFuture<WriteHandle> future = bookKeeper.newCreateLedgerOp()
+                .withEnsembleSize(config.getBkEnsembleSize())
+                .withWriteQuorumSize(config.getBkWriteQuorumSize())
+                .withAckQuorumSize(config.getBkAckQuorumSize())
+                .withDigestType(config.getDigestType())
+                .withPassword(config.getBKPassword())
+                .withCustomMetadata(createLedgerCustomMetadata(logId))
+                .execute();
+            return Futures.getAndHandleExceptions(future, BK_EXCEPTION_HANDLER, 20, TimeUnit.SECONDS);
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/Ledgers.java]: Done

File: test/testcommon/src/main/java/io/pravega/test/common/SerializedClassRunner.java [hunk 15]
```diff
@@ -0,0 +1,31 @@
...
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.test.common;
+
+import org.junit.runner.notification.RunNotifier;
+import org.junit.runners.BlockJUnit4ClassRunner;
+import org.junit.runners.model.InitializationError;
+
+public class SerializedClassRunner extends BlockJUnit4ClassRunner {
```
Comment (fpj) [inline test/testcommon/src/main/java/io/pravega/test/common/SerializedClassRunner.java:16]: For completeness, why did you have to write this class and what's that `RunNotifier`?

File: .github/workflows/gradle.yml [hunk 16]
```diff
@@ -78,7 +78,7 @@ jobs:
           path: ${{env.BUILD_CACHE_PATH}}
           key: ${{github.run_id}}
       - name: Compile & Static Analysis
```
Comment (fpj) [inline .github/workflows/gradle.yml:80]: Since we are moving static analysis to `unit_other`, this should be changed to just `Compile`.

**Review by fpj — CHANGES_REQUESTED** [review]

File: test/testcommon/src/main/java/io/pravega/test/common/SerializedClassRunner.java (hunk 15 above)
Comment (tkaitchuck) [reply test/testcommon/src/main/java/io/pravega/test/common/SerializedClassRunner.java:16]: Added a Javadoc.
It's needed for some metrics tests which cannot be run in parallel.
RunNotifier is a Junit class. It's not really being used here except as a pass-through to the parent implementation.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java [hunk 17]
```diff
@@ -262,7 +263,7 @@ public void testSegmentRestoration() throws Exception {
      *
      * @throws Exception If an exception occurred.
      */
-    @Test
+    @Test(timeout = 120000)
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/store/StreamSegmentStoreTestBase.java:266]: It sometimes failed before.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java [hunk 18]
```diff
@@ -95,7 +95,7 @@
     private static final Duration SHORT_TIMEOUT = Duration.ofMillis(20);
 
     @Rule
-    public Timeout globalTimeout = Timeout.seconds(TIMEOUT.getSeconds());
+    public Timeout globalTimeout = Timeout.seconds(2 * TIMEOUT.getSeconds());
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/reading/ContainerReadIndexTests.java:98]: Yes

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/BookKeeperIntegrationTestBase.java [hunk 19]
```diff
@@ -67,6 +68,8 @@ protected ServiceBuilderConfig getBuilderConfig(ServiceBuilderConfig.Builder con
         String id = Integer.toString(instanceId);
         return configBuilder
                 .makeCopy()
+                .include(BookKeeperConfig.builder().with(BookKeeperConfig.BK_ENFORCE_MIN_NUM_RACKS_PER_WRITE, false)
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/BookKeeperIntegrationTestBase.java:71]: This is forcing it off.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java [hunk 20]
```diff
@@ -52,7 +51,7 @@
     public static final String TLS_KEY_STORE = "tlsKeyStore";
     public static final String PROPERTY_LEDGERS_DIR = "ledgersDir"; // File System path to store ledger data.
 
-    private static final InetAddress LOOPBACK_ADDRESS = InetAddress.getLoopbackAddress();
+    private static final String LOOPBACK_ADDRESS = "127.0.0.1";
```
[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java:54]: Instead of hardwiring `127.0.0.1`, could we instead say use `java.net.preferIPv4Stack` for tests?

**Review by andreipaduroiu — APPROVED** [review]
All my comments have been addressed.

**Review by shrids — APPROVED** [review]
No new comments from my end.

**Comment by fpj** [comment]
I see that this integration test failed:

```
io.pravega.test.integration.ControllerMetricsTest > streamMetricsTest FAILED
    java.lang.AssertionError: Number of iterations and latency count do not match. Expected: greater than or equal to 3. Actual: 0.
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.pravega.test.common.AssertExtensions.assertGreaterThanOrEqual(AssertExtensions.java:419)
        at io.pravega.test.integration.ControllerMetricsTest.streamMetricsTest(ControllerMetricsTest.java:224)
```

**Comment by RaulGracia** [comment]
@fpj this test seems failing on `master` as well: https://github.com/pravega/pravega/issues/5657

**Comment by shrids** [comment]
All the tests have passed here.  @tkaitchuck the github action check for "Segment Store Unit Tests" seems to be hung.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
I see that this PR is failing consistently in Jenkins. While most of the tests failing are already known flaky tests, merging this PR now would lead to blocking merges to master. Blocking this PR just for safety until Jenkins builds pass consistently.

**Comment by RaulGracia** [comment]
@tkaitchuck the header of the project has recently changed, so you need to update it in the new files added in this PR or otherwise checkstyle complains.

**Comment by RaulGracia** [comment]
@tkaitchuck it looks like there is a checktyle issue in `shared:metrics`:
```
19:22:02  > Task :shared:metrics:checkstyleTest FAILED
19:22:02  [ant:checkstyle] [ERROR] /var/jenkins_home/workspace/pravega-branch-builder@2/shared/metrics/src/test/java/io/pravega/shared/metrics/MeterRegisterTest.java:2: Line does not match expected header line of ' * Copyright Pravega Authors\.'. [RegexpHeader]
```

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java [hunk 21]
```diff
@@ -82,41 +80,40 @@
...
             bookiePorts.add(TestUtils.getAvailableListenPort());
         }
 
+        String ledgersPath = "/pravega/bookkeeper/ledgers/" + testId;
         val runner = BookKeeperServiceRunner.builder()
                                             .startZk(true)
-                                            .zkPort(BK_PORT.get())
-                                            .ledgersPath("/pravega/bookkeeper/ledgers")
+                                            .zkPort(zkPort)
+                                            .ledgersPath(ledgersPath)
```
Comment (fpj) [inline segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java:116]: Haven't you used ledgers path + zkPort before? Should we use the same here? This is what I'm thinking about:

https://github.com/pravega/pravega/pull/4999/files#diff-7cb38ef4f69c054db7f40fc17995e399cfbc2c96cc35ec1e5d40a969e3bb3aedR62

File: shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerProxy.java [hunk 22]
```diff
@@ -99,17 +99,21 @@ public StatsLogger createScopeLogger(String scope) {
...
-            T metric = createMetric.apply(keys.getRegistryKey());
-            return createProxy.apply(metric, keys.getCacheKey(), cache::remove);
+        Consumer<V> closeCallback = m -> cache.remove(m.getProxyName(), m);
+        return cache.computeIfAbsent(keys.getCacheKey(), k -> {            
+            T newMetric = createMetric.apply(keys.getRegistryKey());
+            return createProxy.apply(newMetric, keys.getCacheKey(), closeCallback);
         });
     }
-
+
```
Comment (fpj) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerProxy.java:115]: Minor: extra spaces

File: shared/metrics/src/test/java/io/pravega/shared/metrics/BasicMetricTest.java [hunk 23]
```diff
@@ -16,21 +16,23 @@
 package io.pravega.shared.metrics;
 
 import io.pravega.shared.MetricsTags;
+import io.pravega.test.common.SerializedClassRunner;
```
Comment (fpj) [inline shared/metrics/src/test/java/io/pravega/shared/metrics/BasicMetricTest.java:19]: It is odd that it is not recognizing this file as Java, is this just a UI bug?

File: test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndCBRTest.java [hunk 24]
```diff
@@ -59,23 +57,23 @@
 public class EndToEndCBRTest extends AbstractEndToEndTest {
 
     private static final long CLOCK_ADVANCE_INTERVAL = 60 * 1000000000L;
-
-    @Test
+
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndCBRTest.java:60]: Minor: extra spaces.

**Review by fpj — COMMENTED** [review]
It looks good, I only have a few minor points.

File: segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java (hunk 21 above)
Comment (tkaitchuck) [reply segmentstore/storage/impl/src/test/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogTests.java:116]: From the above:
```
 String ledgersPath = "/pravega/bookkeeper/ledgers/" + testId;
 ```
 Where testId is:
 ```
 String testId = Long.toHexString(System.nanoTime());
 ```
 This serves much the same function. Either way it ensures that parallel tests won't collide in their directories.

File: shared/metrics/src/test/java/io/pravega/shared/metrics/BasicMetricTest.java (hunk 23 above)
Comment (tkaitchuck) [reply shared/metrics/src/test/java/io/pravega/shared/metrics/BasicMetricTest.java:19]: No idea. It's working for me.

File: common/src/main/java/io/pravega/common/concurrent/Futures.java [hunk 25]
```diff
@@ -217,6 +238,43 @@
             }
         }
     }
+    
+    /**
+     * Calls get on the provided future, passing a timeout, handling interrupted, and transforming
+     * the executionException into an exception of the type whose constructor is provided.
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply common/src/main/java/io/pravega/common/concurrent/Futures.java]: Done

**Comment by fpj** [comment]
I'm not sure why it is stuck here `Segment Store Unit Tests`. The PR is renaming the action in the workflow configuration, so I'm not sure why that is happening. Are we missing some other configuration change with respect to actions?

**Comment by andreipaduroiu** [comment]
@fpj this is hanging even for master builds. Not something specific to this PR but it did start happening recently.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 26]
```diff
@@ -142,14 +143,6 @@ protected final void shutDown() throws Exception {
                 } catch (Exception e) {
                     log.info("Exception while closing EventProcessorCell reader from checkpointStore: {}.", e.getMessage());
                 }
-
-                // Next, clean up the reader and its position from checkpoint store
-                log.info("Cleaning up checkpoint store for {}", objectId);
-                try {
-                    checkpointStore.removeReader(process, readerGroupName, readerId);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:149]: why are we removing this.. this is a zookeeper node which needs to be cleaned up.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 27]
```diff
@@ -369,6 +364,7 @@ private void replaceCell(String readerId) {
             log.info("Stopping event processor cell: {}", cell);
             try {
                 cell.stopAsync();
+                checkpointStore.removeReader(cell.getProcess(), readerGroup.getGroupName(), readerId);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:367]: why not remove the reader from inside cell.stop which terminates the reader and only after that we remove it. here we could be removing it prematurely.

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java [hunk 28]
```diff
@@ -161,11 +160,11 @@ public LocalController(ControllerService controller, boolean authorizationEnable
         return this.controller.createStream(scope, streamName, streamConfig, System.currentTimeMillis()).thenApply(x -> {
             switch (x.getStatus()) {
             case FAILURE:
-                throw new ControllerFailureException("Failed to createing stream: " + streamConfig);
+                throw new ControllerFailureException("Failed to create stream: " + streamConfig);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/LocalController.java:163]: thank you :)

File: gradle/java.gradle [hunk 29]
```diff
@@ -94,12 +94,13 @@ plugins.withId('java') {
         testLogging.showCauses = true
         testLogging.showExceptions = true
         testLogging.showStackTraces = true
-        testLogging.events = ["FAILED"]
-        maxParallelForks = System.properties['maxParallelForks'] ? System.properties['maxParallelForks'].toInteger() : 1
+        testLogging.events = ["STARTED", "PASSED", "SKIPPED", "FAILED"]
```
Comment (shrids) [inline gradle/java.gradle:97]: the reason why only FAILED event was present ref: https://github.com/pravega/pravega/pull/5441#pullrequestreview-563051076

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java [hunk 30]
```diff
@@ -189,6 +190,8 @@ private BookKeeper startBookKeeperClient() throws Exception {
             config.setEnforceMinNumRacksPerWriteQuorum(this.config.isEnforceMinNumRacksPerWriteQuorum());
             config.setMinNumRacksPerWriteQuorum(this.config.getMinNumRacksPerWriteQuorum());
             config.setProperty(CommonConfigurationKeys.NET_TOPOLOGY_SCRIPT_FILE_NAME_KEY, this.config.getNetworkTopologyFileName());
+        } else {
+            config = config.setEnsemblePlacementPolicy(DefaultEnsemblePlacementPolicy.class);
```
Comment (shrids) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java:194]: Is the reason for this change related to the below WARN message observed on Segment store ?
```
2021-02-26 05:38:20,547 13644 [core-1] WARN  o.a.b.client.BookieWatcherImpl - New ensemble: [nautilus-bookie-2.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181, nautilus-bookie-0.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181, nautilus-bookie-1.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181] is not adhering to Placement Policy. quarantinedBookies: []
```

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 27 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java:367]: it would make a difference if we are unable to do a clean shutdown (where we use the last reader position and report it offline at that position.. 
say all of that failed but we removed the reader postion from zookeeper, then another controller will not be able to correctly failover this reader.

**Review by shiveshr — CHANGES_REQUESTED** [review]
Please address the comment about removing the reader from checkpoint store

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 26 above)
Comment (tkaitchuck) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:149]: I moved it into checkpointStore:
https://github.com/pravega/pravega/pull/4999/files#diff-36211c36a9b83866c7fae956d50dce693373d12d9d9e29bf550bd4d52b52851bR161-R164

File: gradle/java.gradle (hunk 29 above)
Comment (tkaitchuck) [reply gradle/java.gradle:97]: I removed the duplicate on start.
Given that there is parallelization I don't consider 'passed' and 'started' redundant anymore, because it allows you to infer which are running at the same time.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java (hunk 30 above)
Comment (tkaitchuck) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java:194]: Yes.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 27 above)
Comment (tkaitchuck) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: While I agree it would be cleaner, my motivation for not doing it inside the cell, is because it causes problems on shutdown. 
Specifically if the checkpointStore needs to be written to, then every cell will need to timeout writing to it. As there are many cells this results in very long delays in the tests. In fact it is the largest single contributor of integration test time.

I have addressed the concern raised here about this being too soon by moving it after the await.

**Review by shiveshr — APPROVED** [review]
LGTM

File: .github/workflows/gradle.yml [hunk 31]
```diff
@@ -29,18 +29,24 @@ on:
...
     ~/.m2
   GLOBAL_CACHE_KEY: gradle-m2-java-11
   GLOBAL_CACHE_RESTORE_KEYS: |
     gradle-m2-java-
     gradle-m2
-  # We cache the source code, resources and build output. This is generated on the build job and reused in dependent jobs.
-  BUILD_CACHE_PATH: ./*
+  # We cache the class files, resources and build output. This is generated on the build job and reused in dependent jobs.
+  BUILD_CACHE_PATH: |
+    .gradle
```
Comment (andreipaduroiu) [inline .github/workflows/gradle.yml:40]: Can you verify that this change won't impact workflow re-runs?

The point of all these caches is to have a particular job finish right away if it previously completed successfully and we re-run the whole workflow.

File: .github/workflows/gradle.yml [hunk 32]
```diff
@@ -101,14 +112,14 @@ jobs:
         uses: actions/cache@v2.1.0
         with:
           path: ${{env.BUILD_CACHE_PATH}}
-          key: ${{github.run_id}}
+          key: ${{github.ref}}
```
Comment (andreipaduroiu) [inline .github/workflows/gradle.yml:115]: What is the effect of this change? `run_id` would cache the output for re-runs of the same workflow.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

**Comment by fpj** [comment]
@andreipaduroiu about this comment: https://github.com/pravega/pravega/pull/4999#issuecomment-814938595

I checked, for example, this PR: https://github.com/pravega/pravega/pull/5914

and it doesn't have that problem. Where else are you seeing it happening?

File: .github/workflows/gradle.yml (hunk 32 above)
Comment (tkaitchuck) [reply .github/workflows/gradle.yml:115]: Now instead of being tied to a github actions run, it's tied to the source. (PR or Branch). This means that multiple pushes to the same branch can avoid re-executing if the tests for that target passed and no related code was changed just like the do locally.

File: .github/workflows/gradle.yml (hunk 31 above)
Comment (tkaitchuck) [reply .github/workflows/gradle.yml:40]: I am checking

Comment (tkaitchuck) [reply .github/workflows/gradle.yml:41]: Confirmed

**Comment by andreipaduroiu** [comment]
@fpj It's an unpredictable problem. Doesn't happen for every build; it happens for some. It is also something relatively recent. I don't remember it hanging prior to about a month ago.

**Review by andreipaduroiu — APPROVED** [review]

**Review by fpj — APPROVED** [review]

**Comment by RaulGracia** [comment]
@tkaitchuck Thanks, the Jenkins build on this branch is passing successfully now:
```
pravega-branch-builder/1132/
pravega-branch-builder/1134/
```
However, it is just taking around 10-15 minutes less to execute than the regular builds without this PR: 62min vs 75-77min. Is that the expected speed up?

**Review by RaulGracia — APPROVED** [review]
