### PR TITLE
Issue 6315: Exception on transactions open metric count computation

### LINKED ISSUE #6315: Exception when computing the open transaction count metric
**Describe the bug**
When computing the open transaction count metric we invoke getEntryCount() API on Segment store for the transactionsInEpoch-n table. However the wire command that is used for this operation is not added to EXPECTED_SUCCESS_REPLIES map in SegmentHelper leading to this exception:
```
2021-09-20 17:36:39,340 15037792 [eventprocessor-19] INFO  i.p.c.s.e.r.CommitRequestHandler - [requestId=-5245660236538869285] Committing transaction 00000000-0000-0000-0000-000000001657 on stream demo/streamprocessing1
2021-09-20 17:36:39,380 15037832 [ClientSocketReaders-4] ERROR i.p.controller.server.SegmentHelper - [requestId=-5245660236538869285] Unexpected reply GetTableSegmentInfo _system/_tables/demo/streamprocessing1/transactionsInEpoch-0.#.a4fa6f45-b49d-4364-b91e-597c6e9ff78e TableSegmentInfo 2165638474760192.
2021-09-20 17:36:39,380 15037832 [ClientSocketReaders-4] WARN  i.p.c.s.PravegaTablesStoreHelper - [requestId=-5245660236538869285] exception of unknown type thrown GetInfo table: _system/_tables/demo/streamprocessing1/transactionsInEpoch-0.#.a4fa6f45-b49d-4364-b91e-597c6e9ff78e
java.lang.NullPointerException: null
        at io.pravega.controller.server.SegmentHelper.handleExpectedReplies(SegmentHelper.java:900)
        at io.pravega.controller.server.SegmentHelper.handleReply(SegmentHelper.java:843)
        at io.pravega.controller.server.SegmentHelper.lambda$getTableSegmentInfo$14(SegmentHelper.java:498)
```

**Additional information**
To fix add expected replies for `WireCommand.GetTableSegmentInfo` to  EXPECTED_SUCCESS_REPLIES map and unexpected(error) replies to EXPECTED_FAILING_REPLIES map.

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Added entries for expected and failing replies for `WireCommands.GetTableSegmentInfo` in SegmentHelper

**Purpose of the change**  
Fixes #6315 

**What the code does**  
Added entries to maps EXPECTED_SUCCESS_REPLIES & EXPECTED_FAILING_REPLIES in SegmentHelper so expected and failing replies for this WireCommand are handled properly.

**How to verify it**  
All tests should pass.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 1]
```diff
@@ -979,8 +962,7 @@ private Void handleException(long requestId, String segment, long offset, String
             log.info(requestId, "Segment '{}' already exists and cannot perform operation '{}'.",
                      segment, operation);
             invokeSafely(connection::send, new SegmentAlreadyExists(requestId, segment, clientReplyStackTrace), failureHandler);
-
-        } else if (u instanceof StreamSegmentNotExistsException) {
```
Comment (shrids) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: is this change required?

Comment (pbelgundi) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: `TableStore.getInfo` API can throw 2 types of exceptions:
StreamSegmentNotExistsException
BadSegmentTypeException

So both need to be handled.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Please, add a test to validate this change.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: BadSegmentTypeException would be an unexpected exception for any request by the Controller.

Comment (pbelgundi) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: An "Exception" is not expected behavior, but if there is any possibility that it could be thrown we need to handle that. What concern do you see with adding that check?

**Comment by pbelgundi** [comment]
> Please, add a test to validate this change.

Yes. On it.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: `WireCommands.OperationUnsupported` seems more apt for scenarios where Table operations are attempted to be performed over a Stream segment.

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: for e.g: Invoking deleteTableSegment() on a Stream Segment should not return a NoSuchSegment as it would imply the tablesegment is already deleted.

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: `BadSegmentTypeException` will be thrown if you try to get info on a non-table segment (i.e., stream segment) using the `GetTableSegmentInfo` API. If you encounter it, it's likely a code bug and should be handled as "Precondition failed/Illegal Argument" - it shouldn't be retried as it is not an internal server error or transient error.

So I would find it misleading to return NoSuchSegment if you encounter that one. The segment does exist, but it is of the wrong type.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (pbelgundi) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: For `WireCommand.GetTableSegmentInfo` Controller does not do retries on getting a `NoSuchSegment` response but just fails the request. 
From Controller's pov "StreamSegmentNotExistsException" and "BadSegmentTypeException" both mean a TableSegment by that name does not exist on SS and so returning a "NoSuchSegment" would be the right thing to do.

**Comment by pbelgundi** [comment]
> Please, add a test to validate this change.

Added tests.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (pbelgundi) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: I have removed the check for `BadSegmentTypeException` since it does not need to be added by this PR.

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java:983]: A `BadSegmentTypeException` would cause the Segmentstore to close an exception and throw an `IllegalStateException`. Could you please create an issue for this?

**Review by shrids — APPROVED** [review]
The changes to fix the NPE looks good. Please address the remaining comments.

File: controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java [hunk 2]
```diff
@@ -391,6 +391,36 @@ public void getSegmentInfo() {
...
+        assertEquals(100L, tableInfo.getLength());
+        assertEquals(10, tableInfo.getKeyLength());
+
+        String tableNotExists = "tableNotExists";
+        CompletableFuture<WireCommands.TableSegmentInfo> result1 = helper.getTableSegmentInfo(tableNotExists, "", 1L);
+        requestId = ((MockConnection) (factory.connection)).getRequestId();
+        factory.rp.process(new WireCommands.NoSuchSegment(requestId, tableNotExists, "", -1));
+        AssertExtensions.assertThrows("",
+                () -> result1.join(),
+                ex -> Exceptions.unwrap(ex) instanceof WireCommandFailedException && ((WireCommandFailedException) Exceptions.unwrap(ex)).getReason().equals(WireCommandFailedException.Reason.SegmentDoesNotExist)
```
[the remark this answers is not in the document]
Comment (pbelgundi) [reply controller/src/test/java/io/pravega/controller/server/SegmentHelperTest.java:415]: Ok

**Review by andreipaduroiu — APPROVED** [review]

**Review by RaulGracia — APPROVED** [review]
