### PR TITLE
Issue 6109: Change metric computation for Open Transaction Count to be based on Table Segment Entry Count

### LINKED ISSUE #6109: Open Transactions Count metric computation leads to large number of key iteration calls to Segment Store
**Describe the bug**
Open Transactions Count is computed at the end of each commit event processing by iterating over all epochs with transactions and entries in each transactionsInEpoch table in Stream metadata. This computation is very expensive an on high transactional workload sometimes causes the Segment Store to go OOM.

**Additional information**
This iteration can be avoided if Segment Store can expose an API to provide the number of keys in a Table Segment. 
This API can tell us the number of keys in each transactionsInEpoch table and save many key iterations.

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Open Transactions Count metric computation has been changed to use the GetTableSegmentInfo WireCommand to get the count of number of entries in each transactionsInEpochTable.

**Purpose of the change**  
Fixes #6109

**What the code does**  
In the code that generates open transactions metric count, removed key iteration calls to transactionsInEpoch Table and replaced it with GetTableSegmentInfo call that returns the number of entries in a table segment.

**How to verify it**  
All Unit, Integration and System tests should pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 1]
```diff
@@ -980,7 +980,7 @@ public OperationContext createStreamContext(String scopeName, String streamName,
         return Futures.completeOn(streamObj.completeCommittingTransactions(record, context), executor)
                 .thenAcceptAsync(result -> {
                     streamObj.getNumberOfOngoingTransactions(context).thenAccept(count ->
-                            TransactionMetrics.reportOpenTransactions(scope, stream, count));
+                            TransactionMetrics.reportOpenTransactions(scope, stream, count.intValue()));
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java:983]: Just FYI it is theoretically possible this will overflow, although I find it hard to believe we may have more than 2 billion open transactions per stream at any given time.

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java [hunk 2]
```diff
@@ -848,17 +848,15 @@ private String getWritersTableName(String id) {
...
-    private CompletableFuture<Integer> getNumberOfOngoingTransactions(int epoch, OperationContext context) {
+    private CompletableFuture<Long> getNumberOfOngoingTransactions(int epoch, OperationContext context) {
         Preconditions.checkNotNull(context, "operation context cannot be null");
 
         AtomicInteger count = new AtomicInteger(0);
         return getTransactionsInEpochTable(epoch, context)
-                .thenCompose(epochTableName -> storeHelper.getAllKeys(epochTableName, context.getRequestId())
-                                                          .forEachRemaining(x -> count.incrementAndGet(), executor)
-                                                          .thenApply(x -> count.get()));
+                .thenCompose(epochTableName -> storeHelper.getEntryCount(epochTableName, context.getRequestId()));
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStream.java:859]: Nice!

**Review by andreipaduroiu — APPROVED** [review]

**Review by shiveshr — APPROVED** [review]
LGTM
