### PR TITLE
Issue 3279: Client is performing blocking operations inside Netty Event Loop

### LINKED ISSUE #3279: Client is performing blocking operations inside Netty Event Loop
**Problem description**
We have seen in #3192 that new version of Netty throws a BlockingOperationException because we are performing a blocking operation (Promise#get) inside Netty event loop; Netty is telling us that this can lead to a deadlock.

**Problem location**
SegmentHelper

**Suggestions for an improvement**
Do not perform a blocking operation, but use ClientConnection#sendAsync.
ClientConnection#sendAsync is to be enhanced so that is able to notify network errors.

### PR DESCRIPTION
**Pull request by eolivelli**
**Change log description**  
- enable ClientConnection callers to be notified of errors
- switch to ClientConnection#sendAsync in SegmentHelper and RawClient in order not to perform blocking calls inside Netty EventLoops

**Purpose of the change**  
Fixes #3279

**What the code does**  
Add a CompletedCallback parameter to ClientConnection#sendAsync.
Replace calls to ClientConnection#send in SegmentHelper and RawClient with sendAsync, this way we won't perform a blocking operation inside the Netty event loop.

**How to verify it**  
Tests must pass.
Cherry picking this change on top of #3192 will make tests which are failing due to BlockingOperationException pass

### CODE REVIEW

**Comment by eolivelli** [comment]
@tkaitchuck You are right.

To me this refactoring makes it cleaner the interface, some points:
1) It looks like a code smell to have a *async method which throws an exception
2) the stacktrace is preserved
3) there is a direct connection between the call which is failing, so it is easier to understand and debug
4) the caller can be acknowledged of the end of the write, so you can easily implement more complex flows

So overall this can ve seen mostly as a cosmetic refactoring (apart from fixing the issue of the potential deadlock) but it makes things clearer to me and more maintainable for the future

**Comment by eolivelli** [comment]
I have to finish to fix tests

**Comment by tkaitchuck** [comment]
The code looks fine, but it appears this deadlocks one of the client tests.

**Comment by eolivelli** [comment]
Sure
I will fix those tests as soon as I have cycles.

**Comment by eolivelli** [comment]
@tkaitchuck 
All tests are passing on my laptop.

I found one flaky test AppendProcessorTest#testAppendFails but it should not be related to this patch, did you ever seen it fail ?

**Comment by eolivelli** [comment]
@adrianmo this branch now is fixed, you  can try it for  #3192

**Comment by eolivelli** [comment]
io.pravega.segmentstore.server.host.handler.AppendProcessorTest > testAppendFails FAILED
    org.mockito.exceptions.verification.NeverWantedButInvoked: 
    dynamicLogger.incCounterValue(
        "segmentstore.segment.write_bytes_global",
        8L
    );
    Never wanted here:
    -> at io.pravega.segmentstore.server.host.handler.AppendProcessorTest.testAppendFails(AppendProcessorTest.java:368)
    But invoked here:
    -> at io.pravega.segmentstore.server.host.handler.AppendProcessor.handleAppendResult(AppendProcessor.java:302)
        at io.pravega.segmentstore.server.host.handler.AppendProcessorTest.testAppendFails(AppendProcessorTest.java:368)

**Comment by eolivelli** [comment]
@tkaitchuck  @fpj 
The drop on codecoverage may be due to the new "CompletedCallback" which I have added, by they are actually useful for handling errors which are not tested.

I think this patch is good to go
if we commit this one we can unlock @adrianmo work on BK

**Comment by tkaitchuck** [comment]
That test failure is unrelated to this change and being worked on: https://github.com/pravega/pravega/issues/3292

File: controller/src/main/java/io/pravega/controller/server/SegmentHelper.java [hunk 1]
```diff
@@ -611,27 +611,20 @@ public void authTokenCheckFailed(WireCommands.AuthTokenCheckFailed authTokenChec
...
-                resultFuture.completeExceptionally(cause);
-            } else if (cause instanceof ConnectionFailedException) {
-                resultFuture.completeExceptionally(new WireCommandFailedException(cause, request.getType(), WireCommandFailedException.Reason.ConnectionFailed));
-            } else {
-                resultFuture.completeExceptionally(new RuntimeException(cause));
+            } else {                
+                connection.sendAsync(request, cfe -> {
+                    if (cfe != null) {
+                        Throwable cause = Exceptions.unwrap(cfe);
+                        if (cause instanceof WireCommandFailedException) {
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/SegmentHelper.java]: In my opinion we should never get a WireCommanFailedException, since cfe ie the exception received by netty when it does `writeAndFlush`.

File: client/src/main/java/io/pravega/client/netty/impl/RawClient.java [hunk 2]
```diff
@@ -117,27 +117,31 @@ private void closeConnection(Throwable exceptionToInflightRequests) {
...
                 requests.put(requestId, reply);
             }
-            try {
-                c.send(request);
-            } catch (ConnectionFailedException e) {
-                closeConnection(e);
-            }
+            c.sendAsync(request, cfe -> {
+                if (cfe != null) {
+                    synchronized (lock) {
```
[the remark this answers is not in the document]
Comment (eolivelli) [reply client/src/main/java/io/pravega/client/netty/impl/RawClient.java]: You are right @shrids, we will clean up the map in closeConnection.

I think it is better to remove the *requestId* here as well, I find it is clearer, that request won't ever be answered.

**Comment by eolivelli** [comment]
@shrids thanks.
checking your logs now.

I am a bit in trouble in setting up the system tests.
It is not clear to me how to run system tests against my local version of Pravega
the guide speaks only about using a docker registry

File: client/src/main/java/io/pravega/client/netty/impl/RawClient.java [hunk 3]
```diff
@@ -117,27 +117,31 @@ private void closeConnection(Throwable exceptionToInflightRequests) {
...
+
     public <T extends Request & WireCommand> CompletableFuture<Reply> sendRequest(long requestId, T request) {
         return connection.thenCompose(c -> {
             log.debug("Sending request: {}", request);
             CompletableFuture<Reply> reply = new CompletableFuture<>();
             synchronized (lock) {
                 requests.put(requestId, reply);
             }
-            try {
-                c.send(request);
```
Comment (eolivelli) [inline client/src/main/java/io/pravega/client/netty/impl/RawClient.java]: This is actually a behaviour change, because before this change the sendRequest returned a CompletableFuture only "after" sending the request on the wire (c.send is blocking), now we are returning the CompletableFuture as soon as possible.
This in theory should not be a problem.

I can try to change this call by "composing" with a wait for the completion of the sendAsync.

In my new change the returned CompletableFuture will *complete* only "after" the command has been sent on the wire.
In theory the caller of this method  should not matter about this causality because on the wire we can always have delays.
I wonder if the system test which is failing is buggy and relies on some fortunate sequences of events.

what you you think @tkaitchuck @shrids ?

Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/netty/impl/RawClient.java]: It's worth trying. But I don't see how this would affect the append path...

**Comment by tkaitchuck** [comment]
So, I think that test failure has nothing to do with this PR. I think it's just a bad assertion in the test, because where I grep for: "Reading event caa1faf1-5e77-4b71-a857" I see all the events being read and all in the correct order. (It looks like the test is not handling re-balance correctly.)

**Comment by eolivelli** [comment]
@tkaitchuck 
Makes sense to me. Agreed
