### PR TITLE
Issue 6523: ContainerEventProcessor internal segment continuous truncations prevent StorageWriter batching

### LINKED ISSUE #6509: SLTS GC activity spikes when LTS is unavailable
**Describe the bug**
When LTS is unavailable, SLTS GC increases substantially its activity. This may be harmful to the system, as there is no possibility to move data from system-critical Segments to LTS, which may fill the in-memory operation log. In the following, I attach a screenshot with metrics that evidences such a behavior:
gc-activity-tier2-offline

Apparently, the increase in SLTS GC activity is related to the retries of `StorageWriter` failing to contact with LTS.

**To Reproduce**
Create a local Pravega deployment and make LTS unavailable. Logs and metrics will show that GC activity becomes high form that point onwards.

**Screenshots**
See above.

**Additional information**
n/a.

### LINKED ISSUE #6523: ContainerEventProcessor internal segment continuous truncations prevent StorageWriter batching
**Describe the bug**
`SegmentAggregator` batches for either some time or data size operations for a Segment to be moved to LTS. However, as we can see in the flushing algorithm, there are exceptions that will trigger the flushing irrespective of the accumulated data. And the fact of having truncations on a Segment is one of such conditions: https://github.com/pravega/pravega/blob/6f58cbd09b9713fac6633894755a0e35b109e801/segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java#L207

Today, the `ContainerEventProcessor` used by SLTS GC works in iterations that read, process and then truncate the processed operations. This means that the internal Segment in `ContainerEventProcessor` does frequent truncations that preclude the operation batching to come into play when moving data to LTS. In turn, every time that there is a flush to storage in no-append mode, SLTS will create a new chunk for a Segment and store it in SLTS GC (that is, in `ContainerEventProcessor`), which will process the data and truncate the Segment, thus triggering another immediate storage flush. And so on.

While this cycle is by design, the main problem here is that the system is creating a lot of background traffic and very tiny chunks for this GC Segments when no-append mode is enabled. We can substantially reduce this problem by performing less frequent truncations from the `ContainerEventProcessor` viewpoint. 

**To Reproduce**
Enable DEBUG logs on Pravega with no-append mode enabled. You will see frequent logs like:
```
2022-01-11 09:23:49,378 4812000 [storage-io-89] DEBUG i.p.s.s.chunklayer.WriteOperation - ChunkedSegmentStorage[4] write - New chunk added - op=702610983, segment=_system/containers/event_processor_GC.queue.4_4, chunk=_system/containers/event_processor_GC.queue.4_4.E-225-O-257924710.e525ade2-3d20-4368-aaaa-60a0938bd70b, offset=257924710.
2022-01-11 09:23:58,246 4820868 [storage-io-194] DEBUG i.p.s.s.chunklayer.WriteOperation - ChunkedSegmentStorage[4] write - New chunk added - op=657749303, segment=_system/containers/event_processor_GC.queue.4_4, chunk=_system/containers/event_processor_GC.queue.4_4.E-225-O-257926005.14c2d626-a6c0-4f75-9797-06fec06a1113, offset=257926005
```
As well as logs from `OperationProcessor` for updates to GC and storage_metadata segments.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Adds the possibility to configure the truncation data side to `ContainerEventProcessor`. Set to 128KB the default truncation size for SLTS GC. Also, refresh the internal `DirectSegmentAccess` on each processing iteration of `ContainerEventProcessor`. Increased `ContainerEventProcessor` timeout from 100ms to 1 second, to reduce log noise when there are no items to process.

**Purpose of the change**  
Fixes #6523.
Fixes #6509.

**What the code does**  
This PR adds the ability to `ContainerEventProcessor` to configure length at which processed data is truncated. This can help to induce too frequent truncation in the internal Segment of the `ContainerEventProcessor`, which leads the `StorageWriter` to not  be able to batch operations on that Segment. This PR contains the following changes:
- Added a new property called `processedDataTruncationSizeInBytes` in `ContainerEventProcessor` to define how much data needs to be processed before actually truncating the internal Segment.
- For SLTS GC, just configured the `ContainerEventProcessor` to truncate the internal Segment every 128KB. That is enough to prevent the original problem reported in #6523. Note that, as it is a low level parameter, it is defined as a constant in `StorageEventProcessor` rather than exposing it via the configuration of SLTS GC (adds complexity and seems unnecessary).
- In `ContainerEventProcessor`, apart from the existing attribute `segmentStartOffset` that was essentially the same as the start offset of the Segment, we added two new ones: `processedUpToOffset` (it tracks the offset of the data processed) and `segmentLength` (tracks more accurately segment length without querying the Segment). When `processedUpToOffset - segmentLength >= processedDataTruncationSizeInBytes`, then the current iteration of the `ContainerEventProcessor` truncates the internal Segment.

Apart from the previous changes, we have fixed an additional (day 0) bug in `ContainerEventProcessor`: this class was caching long term `DirectSegmentAccess` objects related to the internal truncation Segment. According to the documentation: https://github.com/pravega/pravega/blob/e1913b8fed98ee339abcd0da999eaf9b61fa943e/segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainer.java#L84
Caching for long time `DirectSegmentAccess` objects is discouraged as the state of that object can become stale quickly. This was the root cause for the problems we had developing this PR, as the `ContainerEventProcessor` after some time of operation either did not found the metadata of its internal Segment and/or it started to work with some random Segment name. 

Finally, Increased `ContainerEventProcessor` timeout from 100ms to 1 second, to reduce log noise when there are no items to process.

**How to verify it**  
All existing tests are passing. Added new test for new functionality.
System tests have passed:
test-pravega-continuous-1/1928
test-pravega-continuous-1/1930
test-pravega-continuous/4334

A 2 day longevity has passed:
pravega-longevity/1050

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java [hunk 1]
```diff
@@ -43,6 +43,9 @@
 public class StorageEventProcessor implements AbstractTaskQueueManager<GarbageCollector.TaskInfo> {
 
     private final static GarbageCollector.TaskInfo.Serializer SERIALIZER = new GarbageCollector.TaskInfo.Serializer();
+    // For SLTS GC, truncating the ContainerEventProcessor internal Segment every 1MB is enough to prevent unnecessary
+    // storage metadata activity that may occur if we truncate it too frequently.
+    private final static long CONTAINER_EVENT_PROCESSOR_TRUNCATE_DATA_SIZE = 1024 * 1024;
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java:48]: I wonder if this could be config value.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 2]
```diff
@@ -288,7 +288,8 @@ public EventProcessorImpl(@NonNull String name, int containerId, @NonNull Direct
             this.closed = new AtomicBoolean(false);
             this.failedIteration = new AtomicBoolean(false);
             // Set with actual value when upon initialization.
-            this.segmentStartOffset = new AtomicLong(segment.getInfo().getStartOffset());
+            this.processedUpToOffset = new AtomicLong(segment.getInfo().getStartOffset());
+            this.lastTruncationOffset = new AtomicLong(0);
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:292]: should this be getStartOffset as well ? 
otherwise on first iteration getOutstandingBytes will give wrong answer and shouldTruncate will be true

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java [hunk 3]
```diff
@@ -87,14 +87,15 @@ public void testBasicContainerEventProcessor() throws Exception {
     public static void testBasicContainerEventProcessor(ContainerEventProcessor containerEventProcessor) throws Exception {
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java:87]: should we add test to specifically test this change?

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]
Minor comments.
Otherwise looks good

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java (hunk 1 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java:48]: I mentioned this in the PR: It is configurable at the `ContainerEventProcessor` level. But, really, this is going to be hardly used by anyone, so I decided to make it a constant from the "client", which is the `StorageEventProcessor`. I could expose this in the same way as `maxItemsAtOnce`, but I just don't see the value of it. I can do it anyway if you feel that it is better that way.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java (hunk 3 above)
Comment (RaulGracia) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java:89]: Yes, I have added one just now.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 2 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:292]: Yes, good catch. The first iteration after a container restart, this would be normally truncate the Segment (after that first iteration, things would work again)

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java (hunk 1 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StorageEventProcessor.java:48]: I guess that's fine for now.

**Review by sachin-j-joshi — COMMENTED** [review]
LGTM.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 4]
```diff
@@ -484,19 +487,44 @@ private EventsReadAndTruncationLength deserializeEvents(BufferView inputData) {
...
+            Preconditions.checkState(truncationOffset <= this.segment.getInfo().getLength());
             return this.segment.truncate(truncationOffset, this.containerOperationTimeout)
-                               .thenAccept(v -> {
-                                   // Update the startSegmentOffset after truncation.
-                                   this.segmentStartOffset.addAndGet(readResult.getTruncationLength());
-                                   // Report latency metrics upon complete processing iteration.
-                                   this.metrics.batchProcessingLatency(iterationTime.getElapsedMillis());
-                               });
+                    .thenAccept(v -> {
+                        // Reset the truncation offset to the new one.
```
Comment (abhinb) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:525]: would a metric indicating truncated or processed bytes so far be indicative of anything?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 5]
```diff
@@ -427,8 +429,8 @@ protected Duration getShutdownTimeout() {
          */
         private void reconcileStartOffset() {
             long newStartOffset = segment.getInfo().getStartOffset();
-            log.info("{}: Reconciling start offset from {} to {}.", this.traceObjectId, this.segmentStartOffset.get(), newStartOffset);
-            this.segmentStartOffset.set(newStartOffset);
+            log.info("{}: Reconciling start offset from {} to {}.", this.traceObjectId, this.processedUpToOffset.getAndSet(newStartOffset), newStartOffset);
+            log.info("{}: Reconciling last truncation offset from {} to {}.", this.traceObjectId, this.lastTruncationOffset.getAndSet(newStartOffset), newStartOffset);
```
Comment (abhinb) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:433]: maybe we can keep the sets outside of the log lines.

**Comment by RaulGracia** [comment]
I have done a local test in which I have made `StorageProcessor` to instruct `ContainerEventProcessor` to truncate the internal segment every 1MB (existing behavior in this PR) and another forcing `ContainerEventProcessor` to always truncate, as it was before (i.e., setting truncation length to 0). After the system is started, I shut down HDFS as tier 2. 
Visibly, we observe that when configured to 0, the behavior is similar to the existing one, so the system starts inducing a lot of GC activity as a result of the constant writes to Tier 2 related to the GC segment. On the other hand, when the internal GC segment is truncated every 1MB, this is enough to break the continuous loop of GC activity induced by constantly truncate the GC segment.
- Truncating internal GC segment every 1MB:
gc-metrics-truncation-1MB

- Truncating internal GC segment per event processor iteration (existing behavior):
gc-metrics-truncation-always

@abhinb please, try to reproduce a similar experiment with this PR to make sure that we are on the same page, and specifically to inspect the amount of system critical table segment credits are consumed with the code in this PR.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 4 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:525]: In the case of error, we already output the start offset of the segment and the processing offset, but there are no metrics for these. I don't think that we need a metric for this neither.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 5 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java]: Done.

**Comment by abhinb** [comment]
Hi @RaulGracia 
I tried a couple of runs with this PR to check accumulation of credits due to GC; but did not really see any increase as such, rather it was in few KB's.

image

Also i think it would be worth checking the behavior once with slower LTS writes, as noted in the observation [here](https://github.com/pravega/pravega/issues/6467#issuecomment-1013380475), which i ll try by introducing delays while writing to LTS.

**Comment by RaulGracia** [comment]
@abhinb @sachin-j-joshi I have observed an issue related to this change in system tests and longevity, so I still need to make changes.

**Review by abhinb — APPROVED** [review]

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java [hunk 6]
```diff
@@ -38,7 +38,7 @@
     public static final Property<Integer> MAX_ACTIVE_SEGMENT_COUNT = Property.named("segment.active.count.max", 25000, "maxActiveSegmentCount");
     public static final Property<Integer> MAX_CONCURRENT_SEGMENT_EVICTION_COUNT = Property.named("segment.eviction.concurrent.count.max", 2500, "maxConcurrentSegmentEvictionCount");
     public static final Property<Integer> MAX_CACHED_EXTENDED_ATTRIBUTE_COUNT = Property.named("extended.attribute.cached.count.max", 4096, "maxCachedExtendedAttributeCount");
-    public static final Property<Integer> EVENT_PROCESSOR_ITERATION_DELAY_MS = Property.named("eventprocessor.iteration.delay.ms", 100);
+    public static final Property<Integer> EVENT_PROCESSOR_ITERATION_DELAY_MS = Property.named("eventprocessor.iteration.delay.ms", 1000);
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerConfig.java:41]: Yes, to do not flood with debug messages the logs so much. This does not impact on processing performance, as it only takes place when either there are no events to process or when there is a failure. I have changed this parameter from `1000` to `100` during the longevity run and observed no difference in term of batch processing latency.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java [hunk 7]
```diff
@@ -189,24 +194,11 @@ public static void testFaultyHandler(ContainerEventProcessor eventProcessorServi
         AssertExtensions.assertEventuallyEquals(true, () -> retries.get() == 10, 10000);
     }
 
-    /**
-     * Check that multiple EventProcessors can work in parallel under the same {@link ContainerEventProcessor}, even in if
-     * some of them are faulty.
-     *
-     * @throws Exception
-     */
-    @Test(timeout = TIMEOUT_SUITE_MILLIS)
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorTests.java:198]: I removed this intentionally because with the change in refreshing segment, mocking this test is quite difficult. On the other hand, this very exact logic is properly tested with real Segments in `StreamSegmentContainerTests` (in fact, we have several tests that are testing the same logic and the only change is to use a `MockSegment` (`ContainerEventProcessorTests`) or a real one (`StreamSegmentContainerTests`)). Therefore, due to the complexity of instrumenting the mock to do what I need and the fact that the logic is actually validated already with a real Segment, I just decided to remove it (it is providing no extra validation and make it to work is cumbersome).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 8]
```diff
@@ -403,37 +416,59 @@ protected Duration getShutdownTimeout() {
...
         }
 
         /**
          * In case of a non-expected exception, we reset the segmentStartOffset value to the real one available in the
          * Segment's metadata.
          */
-        private void reconcileStartOffset() {
-            long newStartOffset = segment.getInfo().getStartOffset();
+        private void reconcileOffsets() {
+            refreshSegment().join();
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java]: I changed the code to avoid joining the future.

**Comment by RaulGracia** [comment]
@sachin-j-joshi I have triggered a couple of system test builds to verify that the last change does not induce any problem.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM.

Thanks a lot for making this change and thoroughly testing it.
