### PR TITLE
Issue 4471: Fix controller client channel termination logic.

### LINKED ISSUE #4471: Fix controller client channel termination logic
**Problem description**
-    Ensure the client waits before the termination is completed.
 -   Ensure exceptions related to the credential plugin are handled and the channel is closed.
This issue is one of the reason for issue #4401 

**Problem location**
ControllerImpl.java

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
* Ensure the client waits before the termination is completed.
* Ensure exceptions related to the credential plugin are handled and the channel is closed.

**Purpose of the change**  
Fixes #4471

**What the code does**  
`io.grpc.ManagedChannel#shutdownNow` only triggers a forceful shutdown. Although forceful, the shutdown process is still not instantaneous. The fix ensures `io.grpc.ManagedChannel#awaitTermination` is used to handle this. 

**How to verify it**  
All the existing and newly added tests should continue to pass.

### CODE REVIEW

File: client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java [hunk 1]
```diff
@@ -882,6 +884,30 @@ public void tearDown() {
...
+        }
+        // Setup mocks.
+        ClientConfig cfg = spy(ClientConfig.builder()
+                .credentials(new DefaultCredentials("pass", "user"))
+                .trustStore(SecurityConfigDefaults.TLS_CA_CERT_PATH)
+                .controllerURI(URI.create((testSecure ? "tls://" : "tcp://") + "localhost:" + serverPort))
+                .build());
+        doThrow(new IllegalStateException("Exception thrown by cred plugin")).when(cfg).getCredentials();
+        ControllerImplConfig controllerCfg = new ControllerImplConfig(1, 1, 1, 1, 1000, cfg);
+             AssertExtensions.assertThrows(IllegalStateException.class, () -> new ControllerImpl(channelBuilder, controllerCfg, this.executor));
```
Comment (ravisharda) [inline client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: Could we verify that `closeChannel()` of the class under test is invoked when an exception occurs? That'd verify the primary change.

Comment (shrids) [reply client/src/test/java/io/pravega/client/stream/impl/ControllerImplTest.java]: I have enabled this verification by enabling `mock-maker-inline` extension of mockito.
