### PR TITLE
Issue 1695: Fail the test if any error while closing the writer/reader in failover system tests

### LINKED ISSUE #1695: Ensure system tests fail if exceptions are thrown while closing readers and writers in the clean-up phase
**Problem description**
In the cleanup phase of the test when the readers and writers are being closed any failures should result in a test failure.

**Problem location**
Failover Tests in system tests.

**Suggestions for an improvement**
Assert.fail() incase of any exceptions thrown by readers and writers.

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
`Assert.fail(" ")`  if any error in `writer.close()` or `reader.close()`
**Purpose of the change**
We are just logging the error when we confront an error while closing readers/writers.
**What the code does**
Fixes #1695 
**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 1]
```diff
@@ -216,6 +217,7 @@ private void closeReader(EventStreamReader<Long> reader) {
             reader.close();
         } catch (Throwable e) {
             log.error("Error while closing reader", e);
+            Assert.fail("Error while closing reader. Test failure");
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: I think you need to do
`testState.getReadException.set(e);` because this may be in another thread.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 2]
```diff
@@ -179,6 +179,7 @@ private void closeWriter(EventStreamWriter<Long> writer) {
             writer.close();
         } catch (Throwable e) {
             log.error("Error while closing writer", e);
+            Assert.fail("Error while closing writer. Test failure");
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: I think you need to do
`testState.getWriteException.set(e);` because this may be in another thread.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java [hunk 3]
```diff
@@ -329,6 +330,7 @@ private void closeReadersAndWriters() {
                 writer.close();
             } catch (Throwable e) {
                 log.error("Error closing writer", e);
+                Assert.fail("Error while closing writer. Test failure");
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: Same here

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 4]
```diff
@@ -311,7 +312,8 @@ private void cleanUp() {
             try {
                 writer.close();
             } catch (Throwable e) {
-                log.error("Error closing reader", e);
+                log.error("Error closing writer", e);
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Here and below: If you simply don't catch the exception, it will go up the stack and fail the test with the full stacktrace.

Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java (hunk 3 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiReaderTxnWriterWithFailoverTest.java]: not catching the exception as below.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 2 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: done.

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: done.
