### PR TITLE
Issue 3489: FileSystemStorage should write data synchronously to avoid data loss

### LINKED ISSUE #3489: FileSystemStorage should write data synchronously to avoid data loss
**Problem description**
Currently the FileSystemStorage implementation uses FileChannel to write data. However it does not use force() to sync data to disk. 
In other words, data is not guaranteed to be written to disk immediately, because data is transferred only to the  buffer cache. This can result in data loss if the server crashes before data is written to the disk.

**Problem location**
io.pravega.storage.filesystem.FileSystemStorage

**Suggestions for an improvement**
Call FileChannel.force after each write
or open the file using [StandardOpenOption.SYNC](https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html#SYNC).

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Call FileChannel.force() at the end of write and concat.

**Change log description** 
Call FileChannel.force() at the end of write and concat.
This prevents data loss if the server crashes before data is written to the disk. Without this the data written is not guaranteed to be written to disk immediately, as data is transferred only to the buffer cache. 

**Purpose of the change**  
Fixes #3489 

**What the code does**  
Call FileChannel.force() at the end of write and concat.

**How to verify it**  
System tests should pass. There is should be no DataCorruptionException in the logs.

### CODE REVIEW

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java [hunk 1]
```diff
@@ -319,6 +319,7 @@ private Void doWrite(SegmentHandle handle, long offset, InputStream data, int le
                     totalBytesWritten += bytesWritten;
                     length -= bytesWritten;
                 }
+                channel.force(true);
```
Comment (fpj) [inline bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: Can you justify why we also need to force a metadata sync? You need to reason about what part of the metadata you are actually updating.

Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: I think you are right. We don't need to explicitly synchronize metadata to update file size on disk, it should be already done as part of data sync itself.

Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: doublechecked fdatasync() documentation, filesize changes automatically trigger metadata flush . 

> It does not flush modified metadata _unless that metadata is needed in order to allow a subsequent data retrieval to be correctly handled_. On the other hand, a change to the file size, would require a metadata flush.

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java [hunk 2]
```diff
@@ -319,6 +319,7 @@ private Void doWrite(SegmentHandle handle, long offset, InputStream data, int le
                     totalBytesWritten += bytesWritten;
                     length -= bytesWritten;
                 }
+                channel.force(false);
```
Comment (andreipaduroiu) [inline bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: Actually, since you are in here, would you mind fixing the File size check at line 307?

We can check the file size and throw Bad Offset exception after we've opened the FileChannel by checking `FileChannel.size`.

At least this should reduce the number of IO calls a bit.

Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: sure.

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java [hunk 3]
```diff
@@ -303,28 +303,29 @@ private Void doWrite(SegmentHandle handle, long offset, InputStream data, int le
...
-                    long bytesWritten = channel.transferFrom(sourceChannel, offset, length);
-                    assert bytesWritten > 0 : "Unable to make any progress transferring data.";
-                    offset += bytesWritten;
-                    totalBytesWritten += bytesWritten;
-                    length -= bytesWritten;
-                }
+        long totalBytesWritten = 0;
+        try (FileChannel channel = FileChannel.open(path, StandardOpenOption.WRITE)) {
+            long fileSize = channel.size();
+            if (fileSize != offset) {
```
Comment (fpj) [inline bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: The condition in the old code to throw bad offset is that the filesize is smaller than than the offset, but here it is changing to different (`!=`), why?

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java [hunk 4]
```diff
@@ -303,28 +303,29 @@ private Void doWrite(SegmentHandle handle, long offset, InputStream data, int le
...
+            // the underlying InputStream, which is not desirable if it is to be reused.
+            ReadableByteChannel sourceChannel = Channels.newChannel(data);
+            while (length != 0) {
+                long bytesWritten = channel.transferFrom(sourceChannel, offset, length);
+                assert bytesWritten > 0 : "Unable to make any progress transferring data.";
+                offset += bytesWritten;
+                totalBytesWritten += bytesWritten;
+                length -= bytesWritten;
+            }
+            channel.force(false);
```
Comment (fpj) [inline bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: Ok, we are going with only forcing the metadata update in the case it is strictly necessary, which we are delegating to the underlying OS implementation, yes?

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java (hunk 3 above)
Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: To make it consistent with how other storage (HDFS and S3) are checking the same conditions. @andreipaduroiu suggested the change and I agree with the suggestion.

File: bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java (hunk 4 above)
Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/filesystem/FileSystemStorage.java]: Yes. In this case the underlying OS will most sync metadata. (Which will happen most of the time with mostly append-only writes in our case.)
