### PR TITLE
Issue 1512: Fix segment splits and merges metrics

### LINKED ISSUE #1512: Segment Splits are being reported as Merges in Metrics
**Problem description**
Currently, we have a Pravega Scaling test that looks like its scaling, but the splits are being reported as merges.

**Problem location**
We are using build 0.1.0-1470.e5e9896 that includes the changes from https://github.com/pravega/pravega/pull/1447.

**Suggestions for an improvement**
Looking at the code, it assumes the order of scaleMetadataList.  We might to make sure that list is sorted chronologically.  

Also, in the loops to calculate the total spits in merges, it overwrites the value on each loop.  Is that expected or should it be adding to the total on each iteration?

### PR DESCRIPTION
**Pull request by Abhijeet-Jadhav**
**Change log description**
Corrects reporting of segment splits and merges metrics.

**Purpose of the change**
Fixes #1512 

**What the code does**
Doesn't assume the reporting order of underlying controller API and counts splits/merges.

**How to verify it**
./gradlew startStandalone task generates few metrics in /tmp/csv folder

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 1]
```diff
@@ -633,11 +633,20 @@ private Scope getScope(final String scopeName) {
         return getScaleMetadata(scopeName, streamName, null, executor).thenApply(scaleMetadataList -> {
             long size = scaleMetadataList.size();
             long totalNumSplits = 0;
-
-            for (int i = 0, j = 1; j < size; j++) {
-                long countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
-                long countSplitsEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumSplits = (countSplitsEventI < countSplitsEventJ) ? (countSplitsEventJ - countSplitsEventI) : 0;
+            long countSplitsEventI, countSplitsEventI1;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: the naming is unusual.. countSplitsEvnt I and countSplitsEvent I1 ?

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 2]
```diff
@@ -633,11 +633,20 @@ private Scope getScope(final String scopeName) {
...
+
+            if (isDescendingOrder(scaleMetadataList)) {
+                for (int i = 0; i < size; i++) {
+                    countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
+                    countSplitsEventI1 = scaleMetadataList.get(i+1).getSegments().size();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: index out of bound?

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 3]
```diff
@@ -633,11 +633,20 @@ private Scope getScope(final String scopeName) {
...
-
-            for (int i = 0, j = 1; j < size; j++) {
-                long countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
-                long countSplitsEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumSplits = (countSplitsEventI < countSplitsEventJ) ? (countSplitsEventJ - countSplitsEventI) : 0;
+            long countSplitsEventI, countSplitsEventI1;
+
+            if (isDescendingOrder(scaleMetadataList)) {
+                for (int i = 0; i < size; i++) {
+                    countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: how is number of events == splits?

Note. in a scale operation you can have both splits and merges:
take following example where segments 0,1,2 result in creation of {3, 4, 5, 6} 
where:
{0, 1} merge into {3}
and {2} splits into {4, 5, 6}
so you have a split of 3 and a merge of 2 in the above example. 
thats what you need to count.. i am not sure what is being counted here. its only counting number of active segments that are there in scaleMetadataList.get(i)

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 4]
```diff
@@ -648,17 +657,38 @@ private Scope getScope(final String scopeName) {
...
-            for (int i = 0, j = 1; j < size; j++) {
-                long countMergesEventI = scaleMetadataList.get(i).getSegments().size();
-                long countMergesEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumMerges = (countMergesEventI > countMergesEventJ) ? (countMergesEventI - countMergesEventJ) : 0;
+            long countMergesEventI, countMergesEventI1;
+
+            if (isDescendingOrder(scaleMetadataList)) {
+                for (int i = 0; i < size; i++) {
+                    countMergesEventI = scaleMetadataList.get(i).getSegments().size();
+                    countMergesEventI1 = scaleMetadataList.get(i + 1).getSegments().size();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: look at the previous comment on getSplits..

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 5]
```diff
@@ -633,11 +633,20 @@ private Scope getScope(final String scopeName) {
...
             long size = scaleMetadataList.size();
             long totalNumSplits = 0;
-
-            for (int i = 0, j = 1; j < size; j++) {
-                long countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
-                long countSplitsEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumSplits = (countSplitsEventI < countSplitsEventJ) ? (countSplitsEventJ - countSplitsEventI) : 0;
+            long countSplitsEventI, countSplitsEventI1;
+
+            if (isDescendingOrder(scaleMetadataList)) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: as discussed, we dont need if block here..
you can compare timestamps of scaleMetadataList.get(i).getTimestamp and scaleMetadataList.get(i+1).getTimestamp and based on that figure out direction and compute splits and merges. 
you dont need isdescending check

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 6]
```diff
@@ -648,17 +657,38 @@ private Scope getScope(final String scopeName) {
...
             return totalNumMerges;
         });
     }
 
+    private boolean isDescendingOrder(List<ScaleMetadata> scaleMetadataList) {
+        int size = scaleMetadataList.size();
+        boolean isDescendingOrder = true;
+        for (int i = 0; i < size - 1; i++) {
+            if (scaleMetadataList.get(i).getTimestamp() < scaleMetadataList.get(i+1).getTimestamp()) {
+                isDescendingOrder = false;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: why even have a for loop if you are breaking after comparing the first two?

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 1 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 5 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: As discussed offline, its convenient to have that check.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 3 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 2 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 4 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 6 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 7]
```diff
@@ -646,19 +637,54 @@ private Scope getScope(final String scopeName) {
 
     private CompletableFuture<Long> findNumMerges(String scopeName, String streamName, Executor executor) {
         return getScaleMetadata(scopeName, streamName, null, executor).thenApply(scaleMetadataList -> {
-            long size = scaleMetadataList.size();
+            int size = scaleMetadataList.size();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: both these methods have a lot of duplication.. you can consolidate them into a single helper method and call that..

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 8]
```diff
@@ -646,19 +637,54 @@ private Scope getScope(final String scopeName) {
...
 
             return totalNumMerges;
         });
     }
 
+    private boolean isDescendingOrder(List<ScaleMetadata> scaleMetadataList) {
+        int size = scaleMetadataList.size();
+        boolean isDescendingOrder = true;
+        if (size > 1) {
+            if (scaleMetadataList.get(0).getTimestamp() < scaleMetadataList.get(1).getTimestamp()) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: you can simply do 
isDescendingOrder = scaleMetadataList.get(0).getTimestamp() < scaleMetadataList.get(1).getTimestamp()

Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: The above will return NPE if there is just one record.

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: if (size > 1) {
  return scaleMetadataList.get(0).getTimestamp() < scaleMetadataList.get(1).getTimestamp();
} else {
    return true;
}

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 7 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Done. Thanks for feedback.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 8 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 9]
```diff
@@ -614,49 +614,46 @@ private Scope getScope(final String scopeName) {
...
-            long size = scaleMetadataList.size();
-            long totalNumSplits = 0;
-
-            for (int i = 0, j = 1; j < size; j++) {
-                long countSplitsEventI = scaleMetadataList.get(i).getSegments().size();
-                long countSplitsEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumSplits = (countSplitsEventI < countSplitsEventJ) ? (countSplitsEventJ - countSplitsEventI) : 0;
+            int size = scaleMetadataList.size();
+            long totalNumSplits = 0, totalNumMerges = 0;
+            List<Segment> segmentList1, segmentList2;
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Check the Oracle Java Conventions:
http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141270.html#18761

One declaration per line.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 10]
```diff
@@ -614,49 +614,46 @@ private Scope getScope(final String scopeName) {
...
-    private CompletableFuture<Long> findNumMerges(String scopeName, String streamName, Executor executor) {
-        return getScaleMetadata(scopeName, streamName, null, executor).thenApply(scaleMetadataList -> {
-            long size = scaleMetadataList.size();
-            long totalNumMerges = 0;
-
-            for (int i = 0, j = 1; j < size; j++) {
-                long countMergesEventI = scaleMetadataList.get(i).getSegments().size();
-                long countMergesEventJ = scaleMetadataList.get(j).getSegments().size();
-                totalNumMerges = (countMergesEventI > countMergesEventJ) ? (countMergesEventI - countMergesEventJ) : 0;
+    private int findSegmentSplitsMerges(List<Segment> segmentsList1, List<Segment> segmentsList2) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Can we give more meaningful names other than 1 and 2? Is it supposed to be high and low?

Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: We use that method both ways by passing parameters interchangeably. So, we can't give a meaningful names like referenceList or targetList.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 9 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 11]
```diff
@@ -614,49 +614,48 @@ private Scope getScope(final String scopeName) {
...
+        int count = 0;
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: This is confusing. I'm not sure what the invariants are here as it is not written anywhere. I'll have to walk through an example to understand war's happening here.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 10 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: this method has a reference and target.. caller decides what to pass in reference and target lists based on whether they want to find splits or merges.. so as fpj suggested, you should change the name.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 11 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: If i understand your example you are saying 
`i` has S0 
`i+1` has S, S'
`i+2` has S2 which is a merge of S and S'

the algo will take s0 and find that it has 2 overlaps in `i+1`. So there is a split. 
for computing merge, it will reverse and compute splits between i + 1 and i.. Since both segments S and S' will have exactly one overlap, the split count will be 0 for either. So number of merges = 0.
now between `i +1` and `i+2` ->
splits = 0 (because S has 1 overlap and S' has 1 overlap)
merges = 1 (because S2 has 2 overlaps - S and S').

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: However, there is a more important question is of semantics.. 
how do we define splits and merges when its a remap of m segments into n.. 
[note: in disjoint splits and merges its obvious].. 

but we should agree on a definition in case where m segments remap into n segments. 

We will take a simple example and run the above algo and check the output: 
Take for example 2 segments 
i: S0 [0, 0.5), S1 [0.5, 1.0) 
i +1: S2[0.0, 0.33), S3[0.33, 0.66), S4[0.66, 1.0)

(forward computation - `i `and `i+1`)
S0 has 2 overlaps. S1 has 2 overlaps. 
splits = 2 (S0'overlaps -1 + S1'overlaps -1). 

{reverse computation- `i+1` and `i`}
S2 has 1 overlap, S3 has 2 overlaps, S4 has 1 overlap
merges = (S2'overlap - 1 + S3'overlaps - 1 + S4'overlap - 1) = 1

Now is this definition and result along the expected lines. Depends on the definition of splits and merges.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 12]
```diff
@@ -614,49 +614,48 @@ private Scope getScope(final String scopeName) {
...
+        for (Segment segment1 : segmentsList1 ) {
+            int overlaps = 0;
+            for (Segment segment2 : segmentsList2) {
+                if (segment1.overlaps(segment2)) {
+                    overlaps++;
+                }
+                if (overlaps > 1) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Another question of semantics: if one segment splits into 3, do we want to count it as 1 split or 2?

You have chosen to return it as 1 split.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 10 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: done.

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java (hunk 11 above)
Comment (Abhijeet-Jadhav) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: Added unit test to cover these cases:

- Only splits
- Both splits and merges
- Only merges

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java [hunk 13]
```diff
@@ -130,34 +133,95 @@ public void testScaleMetadata() throws Exception {
...
+        // Case: Only splits, S0 split into S2, S3, S4 and S1 split into S5, S6,
+        //  total splits = 2, total merges = 3
+        // time t1, total segments 5, S2 {0.0, 0.2}, S3 {0.2, 0.4}, S4 {0.4, 0.5}, S5 {0.5, 0.7}, S6 {0.7, 1.0}
+        AbstractMap.SimpleEntry<Double, Double> segment2 = new AbstractMap.SimpleEntry<>(0.0, 0.2);
+        AbstractMap.SimpleEntry<Double, Double> segment3 = new AbstractMap.SimpleEntry<>(0.2, 0.4);
+        AbstractMap.SimpleEntry<Double, Double> segment4 = new AbstractMap.SimpleEntry<>(0.4, 0.5);
+        AbstractMap.SimpleEntry<Double, Double> segment5 = new AbstractMap.SimpleEntry<>(0.5, 0.7);
+        AbstractMap.SimpleEntry<Double, Double> segment6 = new AbstractMap.SimpleEntry<>(0.7, 1.0);
+        List<java.util.AbstractMap.SimpleEntry<Double, Double>> newRanges1 = Arrays.asList(segment2, segment3, segment4, segment5, segment6);
+        scale(scope, stream, scaleIncidents.get(0).getSegments(), newRanges1);
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: I thought we had stopped calling it incidents. I thought @shiveshr was calling it records, but we have also mentioned occurrences or instances.

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java [hunk 14]
```diff
@@ -130,34 +133,95 @@ public void testScaleMetadata() throws Exception {
...
+        scaleIncidents = store.getScaleMetadata(scope, stream, null, executor).get();
+        assertTrue(scaleIncidents.size() == 2);
+        org.apache.commons.lang3.tuple.Pair<Long, Long> pairSplitsMerges1 = store.findNumSplitsMerges(scope, stream, executor).get();
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: Please do not use pair, use simple entry.

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java [hunk 15]
```diff
@@ -130,34 +133,95 @@ public void testScaleMetadata() throws Exception {
...
+
+        // Case: Only splits, S0 split into S2, S3, S4 and S1 split into S5, S6,
+        //  total splits = 2, total merges = 3
+        // time t1, total segments 5, S2 {0.0, 0.2}, S3 {0.2, 0.4}, S4 {0.4, 0.5}, S5 {0.5, 0.7}, S6 {0.7, 1.0}
+        AbstractMap.SimpleEntry<Double, Double> segment2 = new AbstractMap.SimpleEntry<>(0.0, 0.2);
+        AbstractMap.SimpleEntry<Double, Double> segment3 = new AbstractMap.SimpleEntry<>(0.2, 0.4);
+        AbstractMap.SimpleEntry<Double, Double> segment4 = new AbstractMap.SimpleEntry<>(0.4, 0.5);
+        AbstractMap.SimpleEntry<Double, Double> segment5 = new AbstractMap.SimpleEntry<>(0.5, 0.7);
+        AbstractMap.SimpleEntry<Double, Double> segment6 = new AbstractMap.SimpleEntry<>(0.7, 1.0);
+        List<java.util.AbstractMap.SimpleEntry<Double, Double>> newRanges1 = Arrays.asList(segment2, segment3, segment4, segment5, segment6);
```
Comment (fpj) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: I'm not sure why you have the full qualified class name here. Please use imports.

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java (hunk 13 above)
Comment (Abhijeet-Jadhav) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: Done, changed to records.

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java (hunk 14 above)
Comment (Abhijeet-Jadhav) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: Done.

File: controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java (hunk 15 above)
Comment (Abhijeet-Jadhav) [inline controller/src/test/java/io/pravega/controller/store/stream/ZKStreamMetadataStoreTest.java]: Done.
