### PR TITLE
Issue 3342: Increase the read timeout to avoid test failure 

### LINKED ISSUE #3342: Sporadic build failure: TlsEnabledInProcPravegaClusterTest
**Problem description**
Encountered following test failure during travis build:
```
io.pravega.local.TlsEnabledInProcPravegaClusterTest > testWriteAndReadEventWhenConfigurationIsProper FAILED
    java.lang.AssertionError: expected:<Test event over TLS channel> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.local.TlsEnabledInProcPravegaClusterTest.testWriteAndReadEventWhenConfigurationIsProper(TlsEnabledInProcPravegaClusterTest.java:121)
```

**Problem location**
TLS enabled cluster test

**Suggestions for an improvement**
Fix the test

### PR DESCRIPTION
**Pull request by ravisharda**
Signed-off-by: Ravi Sharda <ravi.sharda@emc.com>

**Change log description**  
Increase read timeouts (tripled) to avoid test failures under abnormal delays in build/test environments. 

**Purpose of the change**  
Fixes #3342. 

**What the code does**  
Increases the read timeout. 

**How to verify it**  
Tests in TlsEnabledInProcPravegaClusterTest pass consistently.

### CODE REVIEW

File: standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java [hunk 1]
```diff
@@ -115,7 +115,7 @@ public void testWriteAndReadEventWhenConfigurationIsProper() throws ExecutionExc
 
         // Keeping the read timeout large so that there is ample time for reading the event even in
         // case of abnormal delays in test environments.
-        EventRead<String> event = reader.readNextEvent(50000);
+        EventRead<String> event = reader.readNextEvent(150000);
```
Comment (fpj) [inline standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: why do we need to increase so much the read timeout? it is kind of harmless to do it, but it does not look like the test case requires a timeout of over 2 minutes.

Comment (ravisharda) [reply standalone/src/test/java/io/pravega/local/TlsEnabledInProcPravegaClusterTest.java]: It is not expected that such a large timeout would actually be needed in the build/test environments, but I used it just to reduce the chances of test failures due to unexpected and excessive delays. Should I reduce it to something like 100,000 ms, instead?

**Comment by andreipaduroiu** [comment]
@ravisharda @fpj is there any progress on this? Virtually every build is failing with this and it's really starting to affect our productivity. 

Does this point to an underlying issue with the application or is it related to TLS functionality?

**Comment by ravisharda** [comment]
@andreipaduroiu 
The investigation and analysis are still on. More on this below.

When we looked at the logs from a previous system test build, we noticed a bunch of errors in the log, including a message ``Rescheduling ControllerNameResolver task for after 120000 ms``, which seemed to indicate that the name resolver was sleeping for 2 minutes. There was also an SSL/TLS certificate issue visible in the logs.
 
Today, I created server certificates/keys and other PKI material to setup SSL/TLS afresh: this was to ensure that these materials were created and installed properly. The standalone mode seems to work w.r.t. reader/writer apps and controller REST endpoints using these new material, but I still see a different error (#2580) in the logs that I was trying to resolve. This is happening in SegmentOutputStreamImpl when it invokes connectionFactory.establishConnection(uri, responseProcessor). 

In the meantime, a workaround is to trigger the tests again.

**Comment by fpj** [comment]
Approving this PR as a temporary change, until we fix the root cause in #3372.
