### PR TITLE
Issue 6139: (SegmentStore) Improving Table Segment Pre-Caching and Background Indexing

### LINKED ISSUE #6139: Unable to recover SLTS Metadata Table if severely backed up
**Describe the bug**
Upon every iteration of the Storage Writer, it picks new operations to process. If any of those operations references a Segment it wasn't previously working with, it will create a new `SegmentAggregator` for it and fetch information from the `Storage` adapter. If the `Storage` adapter is implemented by SLTS, that would result in a SLTS Metadata Table request. If that segment isn't available for reading (freshly after a recovery - not fully preindexed), we would not be able to initialize those segments. This would lead to the Storage writer to not even attempt to flush any segments, hence the SLTS metadata table stands no chance of being indexed -> deadlock.

**To Reproduce**
1. Need to have at least 1 non-system segment. Call this segment A.
2. Cause the SLTS Metadata Table (SLTS_META) to exceed 128MB in unindexed data. 
3. Cause the owning container to failover.
4. Upon recovery, the Storage Writer will process the recovered operations.
4.1. It will successfully recover the SLTS metadata table (initialize it)
4.2. When trying to initialize segment A, it will call SLTS_META.getInfo(A). This will be rejected/timed out because the `ContainerTableExtensionImpl` detected that SLTS_META is not fully indexed but it refuses to preindex due to it having too much unindexed data (> 128MB).
4.3. The Storage Writer logs and error and starts a new iteration.

There is no way out of this situation. Step 4.2 above would always fail due to SLTS_META not being ready. However the only way at this point for SLTS_META to be ready is if the Storage Writer makes indexing progress on it. However the StorageWriter cannot, because it trips over step 4.2. It is deadlocked.

**Discarded solutions**
These solutions were either attempted or thought of but would not resolve the issue in all cases:
1. Change StorageWriter to still try to flush even if it's unable to initialize Segment Aggregators. This does not cover the case when the SLTS metadata table segment is not already active in the Storage Writer.
2. Increase the pre-index recovery limits. This cannot go over 2GB due to internal constraints (`BufferView` can hold at most 2GB of data, even if composite). If we are backed up even more than that, this won't work.

**Sugested Solution**
- Make the preindex recovery thresholds configurable. This enables an operator to temporarily raise them to as much as needed.
- Change the `WriterTableProcessor` indexer and the `ContainerKeyIndex` pre-index task to process the unindexed tail in small batches vs all at once.
    - For example, if the backup is 3GB, it can do that in about 30 x 100MB batches instead of trying to gulp all 3GB at once.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Made `TableExtensionConfig` externally-configurable. This should allow us to properly tweak this if we have to (for debugging/repair purposes).
- Changed `ContainerKeyIndex` pre-caching to execute in batches, no bigger than 128MB. This will enable precaching of larger segments without the risk of running out of memory.
- Changed `WriterTableProcessor` to index a maximum of 128MB at once, even if the backlog is bigger. Remaining unindexed data will be processed in later iterations.

**Purpose of the change**  
Fixes #6139.

**What the code does**  
- `TableExtensionConfig` 
    - This defines the major config points for the `ContainerTableExtensionConfig` component. The original purpose was to make unit testing easier.
    - This change converts it to an externally-configurable component (just like any other config components) which should enable us to tweak these values if we need to get the Pravega cluster out of a bad state.
- `ContainerKeyIndex` pre-caching
    - Using an async loop to break down the pre-cache segment range into smaller ranges and process them in sequence. This way, no more than 128MB (or whatever is configured) of data will be read in memory at any given time.
 - `WriterTableProcessor`
     - Changed the `flush` behavior to cap the amount of data to process at 128MB. The actual exact amount of data will vary, as it will try to stop on an append boundary (otherwise it may try to stop in the middle of a table entry).

**How to verify it**  
All existing unit tests must pass - this was an "idempotent" change.
Some unit tests have been updated to check for new cases and new unit tests have been added to verify the same.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/util/TypedProperties.java [hunk 1]
```diff
@@ -155,9 +154,43 @@ public boolean getBoolean(Property<Boolean> property) throws ConfigurationExcept
...
+    /**
+     * Gets the value of an Integer property only if it is greater than 0.
+     *
+     * @param property The Property to get.
+     * @param strict   If true, then the value must be strictly greater than 0; otherwise 0 is accepted.
+     * @return The property value or default value, if no such is defined in the base Properties.
+     * @throws ConfigurationException When the given property name does not exist within the current component and the property
+     *                                does not have a default value set, or when the property cannot be parsed as a positive Integer.
+     */
+    public int getPositiveInt(Property<Integer> property, boolean strict) {
```
Comment (sachin-j-joshi) [inline common/src/main/java/io/pravega/common/util/TypedProperties.java:169]: I think it is better to have a separate overload
`public int getNonNegativeInt(Property<Integer> property)`
instead of passing strict.

Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/util/TypedProperties.java:169]: Done.

**Review by RaulGracia — APPROVED** [review]
LGTM, but it would be great to test this change on a saturated cluster to see how it behaves in a situation similar to the original issue.

**Review by sachin-j-joshi — APPROVED** [review]
Looks okay to me.
