### PR TITLE
Issue 5297, 6088: Upgrades required to run on ARM64 & TLS 1.3

### LINKED ISSUE #5297: ADD ARM64 support to Pravega
**Problem description**

Hi Team,

I am interested in adding ARM64 support to Pravega and ARM64 jobs in Travis-CI.

Travis-CI link in the Readme.md shows that the build takes around 1 hr 20 mins to complete. However, free travis jobs have a minimum time limit of 50 mins, hence my build terminates without completion after 50 mins, and I am unable to use Travis utility to build pravega.
I have tried building pravega locally on Ubuntu: Xenial x86_64 system with JDK set to openjdk11, following below commands:
~~~
$ ./gradlew assemble
$ ./gradlew check
~~~ 
**./gradlew assemble** completed successfully, but **./gradlew check** failed over executing some  BookKeeper test cases. Brief errored logs are below:
~~~
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testOpenCloseClient FAILED
    io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testEnableDisable FAILED
    java.util.concurrent.CompletionException: java.util.concurrent.CancellationException: BookKeeperLog has been closed.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testAppendSequence FAILED
    java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: io.pravega.segmentstore.storage.WriteFailureException: Active Ledger is closed.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testExclusiveWriteLock FAILED
    io.pravega.segmentstore.storage.DurableDataLogException: Unable to open-fence ledger 203.

> Task :segmentstore:storage:impl:test FAILED
> Task :segmentstore:storage:impl:jacocoTestReport

~~~

For adding ARM64 support to pravega, I have made the below changes to the source code:

_1. Updated “protoc-gen-grpc-java” version to 1.26.0 (aarch64 support has been added  to this package from 1.26.0 onwards)
2. Added dependency “com.google.code.gson:gson” with version ‘2.8.6’ to build.gradle file, in <project('controller')> and <project('cli:user')>
3. Removed -Werror flag from java options.
4. Updated nettyVersion to 4.1.51.Final.
5. Updated ‘protobufProtocVersion’ to ‘4.0.0-rc-2’.
6. Changed classifier to ‘aarch64’ for “netty-transport-native-epoll” dependency in project('client') in build.gradle file.
7. Changed value of arch to arm64 in pravega/test/system/aws/slave_script.sh and pravega/test/system/aws/master_script.sh files, and set JAVA_HOME accordingly.
8. Set JAVA_HOME to ‘/usr/lib/jvm/java-8-openjdk-arm64’ in pravega/deployment/aws/installer/entry_point_template.yml and pravega/deployment/aws/aws.tf files._

And then ran above commands for the build. 
**./gradlew assemble** completed successfully, but **./gradlew check** failed over executing test cases below:
~~~
io.pravega.segmentstore.server.tables.WriterTableProcessorTests > testFlushCompactions FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds

> Task :segmentstore:server:test FAILED
> Task :segmentstore:server:jacocoTestReport

~~~

If you are interested, I am happy to contribute.

Can you please provide me with some pointers that can help me to move further with pravega build on both x86_64 and ARM64 platforms?

**Problem location**
N/A

**Suggestions for an improvement**
N/A

### PR DESCRIPTION
**Pull request by derekm**
**Change log description**  
Upgrades required to build on ARM AArch64 boards. Upgrade also enables TLS 1.3.

**Purpose of the change**  
Fixes #5297, #6088

**What the code does**  
Upgrades gRPC and Protobuf to versions that support ARM & TLS 1.3.

Suppresses warnings where APIs `ManagedChannelBuilder.nameResolverFactory(Factory)` and `JsonParser.parse(String)` are deprecated.

Adds Gson where required, it was no longer available transitively.

**How to verify it**  
Built on https://coral.ai/products/dev-board
Ran pravega-cli against a remote Pravega cluster

### CODE REVIEW

**Comment by derekm** [comment]
Forces a Netty upgrade that breaks at runtime.

**Comment by andreipaduroiu** [comment]
@derekm What is the purpose of this PR? As you stated above, it clearly introduces a runtime problem.

**Comment by derekm** [comment]
@andreipaduroiu -- This is the result of a weekend project. I have a few ARM devices around the house running weewx for weather station and ZoneMinder for cameras. I wanted to see if I could add a Coral.ai device and Pravega, with Pravega Client on the Pis and the Coral.

This PR allows me to build Pravega on the Coral (ARM64 w/ 1 GB RAM), but obviously Netty doesn't like it at runtime.

In pushing the code off the device, I created this PR to see CI results, since I couldn't reliably run the tests on the device.

We can close this PR, if needed. I wanted to raise the issue of working on ARM, and it looks like we can get there with some moderate upgrades. Please advise. :)

**Comment by andreipaduroiu** [comment]
Well the reason I asked was because there are massive unit and integration test failures in this PR build. They are likely a result of one or more of these upgrades.

**Comment by derekm** [comment]
@andreipaduroiu According to https://github.com/grpc/grpc-java/pull/6441#issuecomment-563322497, I can try 1.26 instead of latest, so I was going to give this one more go...

File: client/src/main/java/io/pravega/client/control/impl/ControllerResolverFactory.java [hunk 1]
```diff
@@ -133,6 +133,7 @@ public String getDefaultScheme() {
          * @param enableDiscovery   Whether to use the controller's discovery API.
          * @param executor          The executor to run resolve tasks on.
          */
+        @SuppressWarnings("deprecation")
```
Comment (shiveshr) [inline client/src/main/java/io/pravega/client/control/impl/ControllerResolverFactory.java:136]: which api that we use is deprecated? shall we update the code to use the replacement api?

Comment (derekm) [reply client/src/main/java/io/pravega/client/control/impl/ControllerResolverFactory.java:136]: ManagedChannelBuilder#nameResolverFactory() becomes marked as deprecated

elsewhere, JsonParser#parse() also become marked as deprecated

**Comment by derekm** [comment]
The build is now passing. I haven't tested the latest changes on the ARM64 board yet, but I would expect Pravega client to work on aarch64 with these changes. While working on another issue, I realized what the fix would be for this PR.

**Comment by derekm** [comment]
Can confirm Pravega CLI works on aarch64:
```
mendel@red-dog:~/pravega-0.10.0-2814.02b05d0-SNAPSHOT$ ./bin/pravega-cli
Pravega User CLI Tool.
        Usage instructions: https://github.com/pravega/pravega/wiki/Pravega-User-CLI

Initial configuration:
        controller-uri=localhost:9090
        default-segment-count=4
        timeout-millis=60000
        max-list-items=1000
        pretty-print=true
        auth-enabled=false
        auth-username=
        auth-password=
        tls-enabled=false
        truststore-location=

Type "help" for list of commands, or "exit" to exit.

> config set controller-uri=192.168.1.73:9090

> config list
        controller-uri=192.168.1.73:9090
        default-segment-count=4
        timeout-millis=60000
        max-list-items=1000
        pretty-print=true
        auth-enabled=false
        auth-username=
        auth-password=
        tls-enabled=false
        truststore-location=

> scope create my-scope
Scope 'my-scope' created successfully.

> stream create my-scope/my-stream
Stream 'my-scope/my-stream' created successfully.

> stream append my-scope/my-stream 5
Appending 5 Event(s) with payload prefix 'f70c77e6-22c8-48c0-8f4f-a4cc088d62f7' having routing key 'null'.
Done.

> stream read my-scope/my-stream
Press 'q <enter>' to cancel ongoing operation.
        f70c77e6-22c8-48c0-8f4f-a4cc088d62f7_0
        f70c77e6-22c8-48c0-8f4f-a4cc088d62f7_1
        f70c77e6-22c8-48c0-8f4f-a4cc088d62f7_2
        f70c77e6-22c8-48c0-8f4f-a4cc088d62f7_3
        f70c77e6-22c8-48c0-8f4f-a4cc088d62f7_4
q
Done.

> exit
```
On machine:
```
$ uname -a
Linux red-dog 4.14.98-imx #1 SMP PREEMPT Sat Jan 30 00:42:30 UTC 2021 aarch64 GNU/Linux
```

**Review by shiveshr — APPROVED** [review]

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Let's execute few branch builders in Jenkins and system tests before merging this one, so we are sure that these dependency upgrades do not cause any issue.

File: gradle.properties [hunk 2]
```diff
@@ -20,7 +20,7 @@ dockerExecutable=/usr/bin/docker
 apacheCommonsCsvVersion=1.5
 apacheCommonsCompressVersion=1.20
 apacheCuratorVersion=4.0.1
```
Comment (RaulGracia) [inline gradle.properties:22]: Wondering if it makes sense to upgrade Apache curator to `4.3.1`, as this version seems quite old. Looking at the release notes of Apache Curator 4.3.0, it seems that ir works with Zookeeper client `3.5.7`: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12345141
Maybe it makes sense to upgrade our Zookeeper dependency to `3.5.7` as well (instead of `3.5.9`) to work just with 1 Zookeeper dependency.

**Comment by RaulGracia** [comment]
@derekm looks like a good time to retake this one :)

File: gradle.properties (hunk 2 above)
Comment (derekm) [reply gradle.properties:24]: @RaulGracia -- Should we go ahead with these upgrades in this PR or another PR?

File: gradle.properties [hunk 3]
```diff
@@ -56,10 +57,10 @@ marathonClientVersion=0.6.2
 micrometerVersion=1.2.0
 mockitoVersion=3.3.3
 jacocoVersion=0.8.5
-nettyVersion=4.1.50.Final
-nettyBoringSSLVersion=2.0.30.Final
-protobufGradlePlugin=0.8.9
-protobufProtocVersion=3.13.0
+nettyVersion=4.1.59.Final
+nettyBoringSSLVersion=2.0.36.Final
```
Comment (andreipaduroiu) [inline gradle.properties:61]: Let's coordinate with #5747 which is also upgrading these libraries. That PR upgrades them to smaller versions though.

Comment (derekm) [reply gradle.properties:61]: @andreipaduroiu Did you mean #6090?

Comment (andreipaduroiu) [reply gradle.properties:61]: Yes. Sorry about that.

File: gradle.properties [hunk 4]
```diff
@@ -56,10 +57,10 @@ marathonClientVersion=0.6.2
 micrometerVersion=1.2.0
 mockitoVersion=3.3.3
 jacocoVersion=0.8.5
-nettyVersion=4.1.50.Final
-nettyBoringSSLVersion=2.0.30.Final
-protobufGradlePlugin=0.8.9
-protobufProtocVersion=3.13.0
+nettyVersion=4.1.59.Final
```
Comment (medvedevigorek) [inline gradle.properties:60]: @derekm let's update netty and other relevant libraries to their latest stable versions. There is 4.1.65 version available which is considered latest stable and recommended by Netty.

Comment (derekm) [reply gradle.properties:60]: @medvedevigorek -- Upgrading to latest seems to break the HDFS connector. I'll try incrementing through the versions and see where it breaks or if we're already at the latest working version.

**Review by sarlaccpit — APPROVED** [review]

**Review by RaulGracia — APPROVED** [review]
LGTM, system tests are green.
