### PR TITLE
Issue 2120: Handle StreamConfiguration with null retention policy

### LINKED ISSUE #2120: NPE if retention policy is null
**Problem description**
` i.p.c.s.r.StreamCutBucketService - Exception thrown while performing auto retention for stream StreamImpl(scope=testscopeL2wJzZtZz1, streamName=_RGtestreadergroupBNqoMYPgHK)
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
`

**Problem location**
Controller, retention

**Suggestions for an improvement**
Ensure that we only include streams for retention that have a retention policy supplied. 
Also add precondition checks to verify if retention is present before performing any computation on retention policy.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: shivesh ranjan <shivesh.ranjan@gmail.com>

**Change log description**
* Does not add stream to the retention bucket if it has null retention policy.

* Checks during stream configuration updates whether retention policy is added or removed from previous configuration and add or remove stream from the bucket accordingly.

**Purpose of the change**
Fixes #2120

**What the code does**
If a stream configuration has a null retention policy, then stream should not be considered for auto-retention. 

AutoRetention is performed on all streams that are part of some bucket. 
So we should not add stream to the bucket if it has null retention policy. 
Similarly, during configuration update, we should check if retention policy is added or removed from previous configuration and add or remove stream from the bucket respectively.

**How to verify it**
Unit test added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java [hunk 1]
```diff
@@ -626,11 +628,18 @@ public void setRequestEventWriter(EventStreamWriter<ControllerEvent> requestEven
                                 .thenCompose(y -> {
                                     final OperationContext context = streamMetadataStore.createContext(scope, stream);
 
-                                    return withRetries(() ->
-                                            streamMetadataStore.addUpdateStreamForAutoStreamCut(scope, stream,
-                                                    config.getRetentionPolicy(), context, executor)
-                                            .thenCompose(v ->  streamMetadataStore.setState(scope, stream, State.ACTIVE,
-                                                    context, executor)), executor)
+                                    return withRetries(() -> {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: The change overall looks good. One high-level comment I have is that I find in general a bad idea to use `null` to indicate the absence of something. In this case, "something" is a retention policy. Could we instead use a constant that represents the absence of a policy in a stream configuration? We would need to make changes to the client to do this.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java [hunk 2]
```diff
@@ -610,7 +611,8 @@ public void setRequestEventWriter(EventStreamWriter<ControllerEvent> requestEven
                 });
     }
 
-    private CompletableFuture<CreateStreamStatus.Status> createStreamBody(String scope, String stream,
+    @VisibleForTesting
+    CompletableFuture<CreateStreamStatus.Status> createStreamBody(String scope, String stream,
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Is there a different way to create a createStream request for tests that does not require changing the visibility of this method? This is probably the most obvious way, but I'm wondering if we can test the same functionality making a higher-level call, e.g., by issuing a real request to create a stream to the tested controller part.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: I absolutely agree. Should i open a different issue for it or address it here?

Comment (fpj) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Ok.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java (hunk 2 above)
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Ok.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: opened issue https://github.com/pravega/pravega/issues/2167
