### PR TITLE
Issue 7258: Handling evicted operations before flushing to storage.

### LINKED ISSUE #7249: StreamSegmentMapOperation operation creation fail with error message "StreamSegment Id has not been assigned" using command `data-recovery durableLog-repair` in pravega-admin cli
**Describe the bug**
Using pravega-admin CLI, when created StreamSegmentMapOperation operation and tried to save it, operation creation failed with error message "java.lang.IllegalStateException: StreamSegment Id has not been assigned." Also it stores wrong epoch.

**To Reproduce**
1.  Open pravega-admin CLI in Terminal from {pravega_home}/bin/pravega-admin location
2. Configure pravega-admin CLI with bookkeeper and zookeeper
3. Enter command `bk list` to see segment container list
4. Disable one of segment container to take back of it, for example segment container '0'. Enter command `bk disable 0` to disable segment container '0'.
5. Enter command `data-recovery durableLog-repair 0`
6. Select option 1.
7. It will ask to select edit action on DurableLog, enter 'add'
8. It will ask 'At which Operation sequence number would you like to add new Operations?', enter any Operation sequence number for example '959425' as it is present in Operation list.
9. It will ask 'Type one of the following Operations to instantiate: [DeleteSegmentOperation|MergeSegmentOperation|MetadataCheckpointOperation|StorageMetadataCheckpointOperation|StreamSegmentAppendOperation|StreamSegmentMapOperation|StreamSegmentSealOperation|StreamSegmentTruncateOperation|UpdateAttributesOperation]' , enter 'StreamSegmentMapOperation'.
10. It will ask 'Input the name of the Segment:', enter any segment name like 'testscope/teststream2/1.#epoch.0'.
11. It will ask 'Input the offset of the Segment:', enter any offset number like '12345'
12. It will ask 'Input the length of the Segment:', enter any length like '123456'.
13. It will ask 'Input the storage length of the Segment:', enter any length like '123456'.
14. It will ask 'Is the Segment sealed? [true/false]:
15. It will ask 'Is the Segment sealed in storage? [true/false]:
16. It will ask 'Is the Segment deleted? [true/false]:
17. It will ask 'Is the Segment deleted in storage? [true/false]:
18. It will ask 'You are about to start adding Attributes to the SegmentProperties instance. 
Do you want to continue?[yes|no]', enter 'no'
19. It will ask 'Input last modified timestamp for the Segment (milliseconds):' enetrr any valid timestamp in milliseconds like '1692955015398'
20. It will ask 'You can add more Operations at this sequence number or not. 
Do you want to continue?[yes|no]', enter 'no'
21. It will ask 'You can continue adding edits to the original DurableLog. 
Do you want to continue?[yes|no]', enter 'no'.
22. It will display some Operation details and ask 
'Do you want to continue?[yes|no]', enter 'yes'
23. It will ask 'Deleting existing medatadata from Repair Log (if any)', enter 'yes'
After that it will print bellow error stack: 
Error serializing operation UpdateAttributesOperation: SequenceNumber = 959425, SegmentId = 24, Attributes = 10
java.lang.IllegalStateException: StreamSegment Id has not been assigned.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.pravega.segmentstore.server.logs.operations.StreamSegmentMapOperation$Serializer.beforeSerialization(StreamSegmentMapOperation.java:182)
	at io.pravega.segmentstore.server.logs.operations.StreamSegmentMapOperation$Serializer.beforeSerialization(StreamSegmentMapOperation.java:161)
	at io.pravega.common.io.serialization.VersionedSerializer$MultiType.serialize(VersionedSerializer.java:668)
	at io.pravega.segmentstore.server.logs.DataFrameBuilder.append(DataFrameBuilder.java:148)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand$AbstractLogProcessor.writeAndConfirm(DurableDataLogRepairCommand.java:663)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand$EditingLogProcessor.applyAddEditOperation(DurableDataLogRepairCommand.java:815)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand$EditingLogProcessor.accept(DurableDataLogRepairCommand.java:755)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand$EditingLogProcessor.accept(DurableDataLogRepairCommand.java:708)
	at io.pravega.common.function.Callbacks.invokeSafely(Callbacks.java:101)
	at io.pravega.segmentstore.server.logs.DebugRecoveryProcessor.recoverOperation(DebugRecoveryProcessor.java:124)
	at io.pravega.segmentstore.server.logs.RecoveryProcessor.recoverAllOperations(RecoveryProcessor.java:177)
	at io.pravega.segmentstore.server.logs.RecoveryProcessor.performRecovery(RecoveryProcessor.java:113)
	at io.pravega.segmentstore.server.logs.DebugRecoveryProcessor.performRecovery(DebugRecoveryProcessor.java:55)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand.readDurableDataLogWithCustomCallback(DurableDataLogRepairCommand.java:598)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand.execute(DurableDataLogRepairCommand.java:186)
	at io.pravega.cli.admin.AdminCLIRunner.execCommand(AdminCLIRunner.java:136)
	at io.pravega.cli.admin.AdminCLIRunner.processCommand(AdminCLIRunner.java:123)
	at io.pravega.cli.admin.AdminCLIRunner.interactiveMode(AdminCLIRunner.java:104)
	at io.pravega.cli.admin.AdminCLIRunner.doMain(AdminCLIRunner.java:89)
	at io.pravega.cli.admin.AdminCLIRunner.main(AdminCLIRunner.java:69)
Number of operations read from DurableLog: 338
There have been errors while creating the edited version of the DurableLog.
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand.execute(DurableDataLogRepairCommand.java:187)
	at io.pravega.cli.admin.AdminCLIRunner.execCommand(AdminCLIRunner.java:136)
	at io.pravega.cli.admin.AdminCLIRunner.processCommand(AdminCLIRunner.java:123)
	at io.pravega.cli.admin.AdminCLIRunner.interactiveMode(AdminCLIRunner.java:104)
	at io.pravega.cli.admin.AdminCLIRunner.doMain(AdminCLIRunner.java:89)
	at io.pravega.cli.admin.AdminCLIRunner.main(AdminCLIRunner.java:69)
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at io.pravega.cli.admin.dataRecovery.DurableDataLogRepairCommand.execute(DurableDataLogRepairCommand.java:187)
	at io.pravega.cli.admin.AdminCLIRunner.execCommand(AdminCLIRunner.java:136)
	at io.pravega.cli.admin.AdminCLIRunner.processCommand(AdminCLIRunner.java:123)
	at io.pravega.cli.admin.AdminCLIRunner.interactiveMode(AdminCLIRunner.java:104)
	at io.pravega.cli.admin.AdminCLIRunner.doMain(AdminCLIRunner.java:89)
	at io.pravega.cli.admin.AdminCLIRunner.main(AdminCLIRunner.java:69)

**Additional information**
The root cause of issue is in StreamSegmentMapOperation operation creation it should ask input for segment id as well, so that segment id get saved in StreamSegmentMapOperation.

### PR DESCRIPTION
**Pull request by dada-dell-emc**
**Change log description**  
Original Problem:
Please see the issue described in #7258.

What the PR does:
The PR does below 2 things:
1. Fixes the problem described in #7258 by ignoring operations on evicted segments, in the rare case that it happens.
2. Fixes gaps in the durableLogRecovery command which can be used to simulate #7258, which are:
(Added segment id input while creating `StreamSegmentMapOperation` operation. Added original epoch in original data log)

**Purpose of the change**  
Fixes #7249 and #7258.
Also the change has been verified via system tests and longevity runs to make sure it doesnt have any side effects.

**What the code does**  
1. As part of fixing #7258 , we ignore operations on segments that are already evicted in StorageWriter.
2. Fixes durableLogRepair command. (this command was used to simulate #7258) by:
          a. Setting the right epoch on BK log post repair.(the epoch was reset to 1 always)
          b. Provision for setting segmentId on the StreamSegmentMapOperation.
  
**How to verify it**  
Use the repro steps of issue #7249. Upgrade Pravega to an image containing the fix.

### CODE REVIEW

**Review by tkaitchuck — APPROVED** [review]

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java [hunk 1]
```diff
@@ -812,6 +812,67 @@ public void testAttributeIterators() throws Exception {
...
 
+    /**
+     * The below test validates a case where the container does not bail out
+     * post container recovery where the StorageWriter has to deal with an Operation
+     * on a segment that was originally evicted out( not present in metadata) yet
+     * the Operation still exists in the BK Log and read during recovery and hence
+     * processed by StorageWriter.
+     * @throws Exception in case of exception.
+     */
+    @Test(timeout = 300000)
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java:823]: Please, reduce this timeout a bit.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java [hunk 2]
```diff
@@ -303,6 +303,19 @@ private CompletableFuture<Void> processMetadataOperation(MetadataOperation op) {
     }
 
     private CompletableFuture<Void> processSegmentOperation(SegmentOperation op) {
+        val segmentMetadata = this.dataSource.getStreamSegmentMetadata(op.getStreamSegmentId());
+        if ( segmentMetadata == null ) {
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:307]: Can you elaborate a little bit on the type of recovery process you are doing to get to this point? It is quite strange that an operation that has passed through the `OperationProcessor` has no metadata, basically because the `OperationProcessor` is intended to create and/or update the metadata of segments that it processes. 

What is more important: what are the consequences of not processing this operation? Should the log be a warning? Should it be better to understand if we need to add any further "checks" at the `OperationProcessor` level to prevent an inconsistent state rather than just skipping unexpected operations at this point of the write path? cc/ @tkaitchuck

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:307]: Also, please remove spaces after `( ` and before ` )`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java [hunk 3]
```diff
@@ -812,6 +812,67 @@ public void testAttributeIterators() throws Exception {
         localContainer.stopAsync().awaitTerminated();
     }
 
+    /**
+     * The below test validates a case where the container does not bail out
+     * post container recovery where the StorageWriter has to deal with an Operation
+     * on a segment that was originally evicted out( not present in metadata) yet
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java:818]: Please, fix spaces in parenthesis.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java (hunk 2 above)
Comment (abhinb) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java:307]: This PR had the issue creation pending which is now updated in the description of the PR which elaborates the issue more.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java (hunk 1 above)
Comment (tkaitchuck) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java:823]: If the test is taking close to this long, we need to find a way to make it faster.

Comment (abhinb) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java:823]: sorry..this takes much lesser..will update with the right value.

Comment (dada-dell-emc) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java]: timeout value changed to 10000ms

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java (hunk 3 above)
Comment (dada-dell-emc) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java]: Fixed the spaces

**Review by abhinb — APPROVED** [review]
