### PR TITLE
Issue 2804: Client reply with server stack trace on error

### LINKED ISSUE #2804: Serialize stack traces when an error is encountered.
**Problem description**
When the Controller or Server encounters an error while processing a request from the client, it replies with an appropriate error type, but not all information is preserved. Sometimes it would be useful to see a stack trace from the other process listed as a cause when the exception get's logged on the client. This way the need to correlate data between multiple logs is avoided.

**Problem location**
Client <-> Server and Client <-> controller wire protocols.

**Suggestions for an improvement**
We could add an addition string field onto our error responses and serialize additional information that the client can log.

For security purposes, we might want to keep this feature behind a configuration switch and turn it off by default. We may not want to expose server-side stacks to the client as that may give a possible attacker some information about server-side vulnerabilities that they may take advantage of. I know at least some enterprises are very sensitive to this, which is why I recommend putting this behind a switch.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
This PR allows Pravega to send server-side stack traces to clients upon failed requests to ease debugging activities:
- Pravega servers and controller instances may now attach internal server-side stack traces to clients on failed requests.
- Due to security reasons, this behavior is activated via configuration switches in both components.

**Purpose of the change**
Fixes #2804.

**What the code does**
This code enables Pravega Servers and Controller instances to send stack traces to the client as part of the reply on a failed request.

On the one hand, `PravegaRequestProcessor` and `AppendProcessor` in the SegmentStore are now capable of sending server traces to the client, given that error messages in `WireCommands` now include a new serializable field `serverStackTrace` to encapsulate that information. In both cases, the server-side stack trace is sent to the client if we set `pravegaservice.replyWithStackTraceOnError=true` in the `config.properties` file.

On the other hand, this PR includes changes in `ControllerServiceImpl` to allow the Controller to reply clients with server-side traces on GRPC calls. To activate this behavior, we need to set `REPLY_WITH_STACK_TRACE_ON_ERROR = true` in the `reference.conf` file.

**How to verify it**
All tests should be working as before this PR. Moreover, when activating the `replyWithStackTraceOnError` option, we should see new traces in client logs. In the following, there is an example of the effects of activating the `replyWithStackTraceOnError` option in the test driver log of system tests.

_Without SegmentStore client traces (i.e., standard behavior):_
```
2018-09-10 10:10:10,497 122959 [epollEventLoopGroup-5-4] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Received SegmentSealed WireCommands.SegmentIsSealed(type=SEGMENT_IS_SEALED, requestId=7068, segment=testAutoScale16234781/testScaleUp/0.#epoch.0, serverStackTrace=) on writer 1069d20d-6d8d-427e-a0be-fcd677ad844e
```

_With SegmentStore client traces:_
```
2018-09-10 09:42:41,939 123922 [epollEventLoopGroup-5-2] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Received SegmentSealed WireCommands.SegmentIsSealed(type=SEGMENT_IS_SEALED, requestId=7810, segment=testAutoScale1415837769/testScaleUp/0.#epoch.0, serverStackTrace=io.pravega.segmentstore.contracts.StreamSegmentSealedException: [Segment 'testAutoScale1415837769/testScaleUp/0.#epoch.0'] The StreamSegment is sealed and cannot be modified.
    at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:228)
    at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:312)
    at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
    at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:364)
    at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:283)
    at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
    at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
) on writer fe64b810-dac7-4774-a3c7-c9fcfe2f16a3
```

### CODE REVIEW

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 1]
```diff
@@ -121,13 +122,15 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeUTF(correctHost);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
             String correctHost = in.readUTF();
-            return new WrongHost(requestId, segment, correctHost);
+            String serverStackTrace = in.readUTF();
```
Comment (eolivelli) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: This way a *new* client won't be able to read a response from an *old* server version. Is this expected ? Or is there some other versioning mechanism?

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 2]
```diff
@@ -121,13 +124,16 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeUTF(correctHost);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
             String correctHost = in.readUTF();
-            return new WrongHost(requestId, segment, correctHost);
+            String serverStackTrace = (length > Long.BYTES + 2 * UTF_HEADER_BYTES + segment.getBytes().length + correctHost.getBytes().length) ?
```
Comment (shrids) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: ` ((ByteBufInputStream) in).available()` this would return the remaining bytes too right?
(ref: `io.pravega.shared.protocol.netty.WireCommandType#readFrom` this takes ByteBufInputStream as an input)

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java (hunk 1 above)
Comment (RaulGracia) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Thanks for your comment @eolivelli. I addressed it by checking whether an error message contains `serverStackTrace` field or not before actually attempting to read it. By doing this, messages from older clients will still be compatible. I also increase the protocol version number to denote the change introduced.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 3]
```diff
@@ -121,13 +123,15 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeUTF(correctHost);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
             String correctHost = in.readUTF();
-            return new WrongHost(requestId, segment, correctHost);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: The interface this implements actually has a ByteBufInputStream in the interface. So you can change the type of in in the signature on line 129 to ByteBufInputStream without having to change any other code.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 4]
```diff
@@ -151,12 +156,14 @@ public void process(ReplyProcessor cp) {
...
             out.writeLong(requestId);
             out.writeUTF(segment);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
-            return new SegmentIsSealed(requestId, segment);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: See above.

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 5]
```diff
@@ -182,13 +190,15 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeLong(startOffset);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
             long startOffset = in.readLong();
-            return new SegmentIsTruncated(requestId, segment, startOffset);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: see above

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 6]
```diff
@@ -212,12 +223,14 @@ public void process(ReplyProcessor cp) {
...
             out.writeLong(requestId);
             out.writeUTF(segment);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
-            return new SegmentAlreadyExists(requestId, segment);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: See above

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 7]
```diff
@@ -246,12 +260,14 @@ public void process(ReplyProcessor cp) {
...
             out.writeLong(requestId);
             out.writeUTF(segment);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String segment = in.readUTF();
-            return new NoSuchSegment(requestId, segment);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: see above

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 8]
```diff
@@ -281,17 +298,19 @@ public void writeFields(DataOutput out) throws IOException {
...
             out.writeLong(writerId.getLeastSignificantBits());
             out.writeLong(eventNumber);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             UUID writerId = new UUID(in.readLong(), in.readLong());
             long eventNumber = in.readLong();
-            return new InvalidEventNumber(writerId, eventNumber);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: See above

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 9]
```diff
@@ -320,12 +340,14 @@ public void process(ReplyProcessor cp) {
...
             out.writeLong(requestId);
             out.writeUTF(operationName);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
             String operationName = in.readUTF();
-            return new OperationUnsupported(requestId, operationName);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: See above

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 10]
```diff
@@ -1310,11 +1333,13 @@ public void process(ReplyProcessor cp) {
         @Override
         public void writeFields(DataOutput out) throws IOException {
             out.writeLong(requestId);
+            out.writeUTF(serverStackTrace);
         }
 
         public static WireCommand readFrom(DataInput in, int length) throws IOException {
             long requestId = in.readLong();
-            return new AuthTokenCheckFailed(requestId);
+            String serverStackTrace = (((ByteBufInputStream) in).available() > 0) ? in.readUTF() : EMPTY_STACK_TRACE;
```
Comment (tkaitchuck) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: see above
