### PR TITLE
Issue 3341: Fix Javadoc build warnings in segmentstore:server

### LINKED ISSUE #3341: Clean up warnings in build for pravega
Problem description
    Modules in the pravega build have a large number of warnings. 

  Pravega/pravega modules

Make modifications to eliminate the warnings - hopefully to improve build time and clarity. In a couple of cases the code examples in Javadoc were truncated.

### PR DESCRIPTION
**Pull request by huide9**
Signed-off-by: huide9 <huide9@gmail.com>

**Change log description**  
*removes build warning/error with javadocs

**Purpose of the change**  
*fixes #3341 

**What the code does**  
remove all warnings found in `segmentstore:server`

**How to verify it**  
`./gradlew segemntstore:server:build`

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/OperationLogFactory.java [hunk 1]
```diff
@@ -21,6 +21,7 @@
      * @param readIndex         A ReadIndex that can be used to store new appends in.
      * @throws NullPointerException     If any of the arguments are null.
      * @throws IllegalArgumentException If the metadata is already in recovery mode.
+     * @return The Sequential Log object.
      */
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/OperationLogFactory.java]: The OperationLog instance.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/ReadIndexFactory.java [hunk 2]
```diff
@@ -20,6 +20,7 @@
      *
      * @param containerMetadata A Container Metadata for this ReadIndex.
      * @param storage           A ReadOnlyStorage to use for reading data that is not in the cache.
+     * @return The ReadIndex object for StreamSegments.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/ReadIndexFactory.java]: The ReadIndex instance.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainerFactory.java [hunk 3]
```diff
@@ -20,6 +20,7 @@
      * Creates a new instance of a SegmentContainer.
      *
      * @param containerId The Id of the container to create.
+     * @return The instance of a SegmentContainer.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentContainerFactory.java]: The SegmentContainer instance.

Please use this phrasing pattern everywhere this is the case.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java [hunk 4]
```diff
@@ -17,39 +17,46 @@
...
 
     /**
      * Gets a value indicating the id of the Container this StreamSegment belongs to.
+     * @return The Container Id.
      */
     int getContainerId();
 
     /**
      * Gets a value indicating whether this StreamSegment has been merged into another.
+     * @return true if StreamSegment merged, false otherwise.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java]: is merged

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java [hunk 5]
```diff
@@ -17,39 +17,46 @@
...
     /**
      * Gets a value indicating whether this StreamSegment has been deleted in Storage.
      * This is different from isDeleted(), which returns true if the StreamSegment has been deleted in the Metadata or in Storage.
+     * @return true if this StreamSegment has been deleted in Storage, false otherwise.
      */
     boolean isDeletedInStorage();
 
     /**
      * Gets a value indicating the length of this StreamSegment for the part that exists in Storage Only.
+     * @return The lenght of the StreamSegment.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java]: length

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/TruncationMarkerRepository.java [hunk 6]
```diff
@@ -58,13 +58,15 @@
      * setValidTruncationPoint().
      *
      * @param operationSequenceNumber The Sequence number to query.
+     * @return true if the given Operation Sequence Number is valid, false otherwise.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/TruncationMarkerRepository.java]: "is a valid truncation point"

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/WriterFlushResult.java [hunk 7]
```diff
@@ -81,20 +81,23 @@ public WriterFlushResult withFlushResult(WriterFlushResult flushResult) {
 
     /**
      * Gets a value indicating the total amount of data flushed, in bytes.
+     * @return The total amount (byte) of data flushed.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/WriterFlushResult.java]: (bytes)

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/WriterFlushResult.java]: Same below

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java [hunk 8]
```diff
@@ -103,6 +103,7 @@ static DataFrame ofSize(int maxSize) {
      * When creating new frames (write mode), this value may be less than the 'maxLength' provided in the constructor.
      * When reading frames from a source (read mode), this value may be less than the size of the source.
      * This value is serialized with the frame.
+     * @return The length (byte) of the frame, including the header, contents and other control.
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java]: (bytes)

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DataFrame.java]: "other control structures needed to serialize the frame"
