### PR TITLE
Issue 5712: Internally idempotent conditional append 

### LINKED ISSUE #5712: Prevent case of a successful append that throws in StateSynchronizer.
**Problem description**
A state synchronizer can end up calling an update function more than needed if the conditional append it performs succeeds but it believes that it has failed.

**Problem location**
ConditionalOutputStreamImpl and SynchronizerUpdate functions

**Suggestions for an improvement**
Making the update functions idempotent should prevent this from causing problems. 
To fix the underlying issue the ConditionalOutputStreamImpl needs to treat InvalidEventNumber as a retryable exception so that it will re-connect and resolve if the event was sent or not using the event number from the AppendSetup in the event that upon the first retry the AppendSetup received stale data.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**  
* Allows ConditionalOutputStream to internally retry InvalidEventNumber exceptions
* Changes reader group updates to double check the assumptions they make before updating the reader group.

**Purpose of the change**  
Fixes #5712

**What the code does**  
Makes ConditionalOutputStream retry InvalidEventNumber replies from the server as introduced in https://github.com/pravega/pravega/pull/5710 which will allow the retry to resolve the ambiguity of whether or not a conditional append was successful if the connection drops before an ack can be received.

### CODE REVIEW

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]
Preemptively blocking until ready to merge. (I have not yet reviewed)

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java [hunk 1]
```diff
@@ -126,19 +127,22 @@ private boolean transformDataAppended(Reply reply) {
...
         closeConnection(reply.toString());
         if (reply instanceof WireCommands.NoSuchSegment) {
             throw new NoSuchSegmentException(reply.toString());
         } else if (reply instanceof SegmentIsSealed) {
             throw Exceptions.sneakyThrow(new SegmentSealedException(reply.toString()));
         } else if (reply instanceof WrongHost) {
             throw Exceptions.sneakyThrow(new ConnectionFailedException(reply.toString()));
+        } else if (reply instanceof InvalidEventNumber) {
+            throw Exceptions.sneakyThrow(new ConnectionFailedException(
+                    "Got stale data from setupAppend on segment " + segmentId + " for ConditionalOutputStream."));
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java:145]: Including the writer-id will help us to easily co-relate logs from the Segment store

File: common/src/main/java/io/pravega/common/util/Retry.java [hunk 2]
```diff
@@ -187,7 +187,11 @@ private RetryAndThrowBase(RetryWithBackoff params) {
                     Exceptions.handleInterrupted(() -> Thread.sleep(sleepFor));
 
                     delay = Math.min(params.maxDelay, params.multiplier * delay);
-                    log.debug("Retrying command {} Retry #{}, timestamp={}", r.toString(), attemptNumber, Instant.now());
+                    log.debug("Retrying command {} due to \"{}\" Retry #{}, timestamp={}",
```
Comment (shrids) [inline common/src/main/java/io/pravega/common/util/Retry.java:190]: +1

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java (hunk 1 above)
Comment (andreipaduroiu) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java:145]: Writer Id + event number would be even better.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 3]
```diff
@@ -187,16 +187,23 @@ boolean handleEndOfSegment(SegmentWithRange segmentCompleted) throws ReaderNotIn
         AtomicBoolean reinitRequired = new AtomicBoolean(false);
         boolean result = sync.updateState((state, updates) -> {
             if (!state.isReaderOnline(readerId)) {
+                log.error("Reader " + readerId + " is offline according to the state but is attempting to update it.");
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:190]: I believe this should be a `warn`. No actual error got caught, but it is an invalid/unexpected condition.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 4]
```diff
@@ -187,16 +187,23 @@ boolean handleEndOfSegment(SegmentWithRange segmentCompleted) throws ReaderNotIn
...
-                reinitRequired.set(false);
-                //This check guards against another checkpoint having started.
-                if (state.getCheckpointForReader(readerId) == null) {
-                    updates.add(new SegmentCompleted(readerId, segmentCompleted, segmentToPredecessor));
-                    return true;
-                }
+                return false;
+            } 
+            if (!state.getSegments(readerId).contains(segmentCompleted.getSegment())) {
+                log.error("Reader " + readerId + " is does not own the segment " + segmentCompleted + "but is attempting to release it.");
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:195]: Same here.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 5]
```diff
@@ -490,7 +497,12 @@ void checkpoint(String checkpointName, PositionInternal lastPosition) throws Rea
                 reinitRequired.set(true);
             } else {
                 reinitRequired.set(false);
-                updates.add(new CheckpointReader(checkpointName, readerId, lastPosition.getOwnedSegmentsWithOffsets()));
+                String cpName = state.getCheckpointForReader(readerId);
+                if (cpName.equals(checkpointName)) {
+                    updates.add(new CheckpointReader(checkpointName, readerId, lastPosition.getOwnedSegmentsWithOffsets()));
+                } else {
+                    log.error("{} was asked to checkpoint for {} but the state says its next checkpoint should be {}", readerId, checkpointName, cpName);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:504]: and here

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java (hunk 3 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:190]: Our definition of error is "Something bad happened that can't be automatically be handled"
It meets this criteria. If this line is reached a user will have to reinitialize the reader because we cannot get it back into a good state.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java (hunk 4 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:195]: See above.

File: client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java (hunk 1 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/ConditionalOutputStreamImpl.java:145]: Added

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java (hunk 5 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:504]: This one I agree. Changed.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java (hunk 3 above)
Comment (andreipaduroiu) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java:190]: OK. Got it.

**Review by andreipaduroiu — APPROVED** [review]
