### PR TITLE
Issue 3328: Wrong target log path in Docker Swarm Pravega services

### LINKED ISSUE #3328: Wrong target log path in Docker Swarm Pravega services
**Problem description**
In the Docker Swarm system test framework, the container that runs Pravega services (Controller/Segment Store) is instructed to mount a (source) volume in the host machine (`logs-volume`) and link it to a target folder in the container (`/tmp/logs`) to persistently store logs. However, the actual location in the container where logs are stored is `/opt/pravega/logs`, which means that currently logs of stopped containers are lost as they have not been persistently stored. 

**Problem location**
`PravegaSegmentStoreDockerService`
`PravegaControllerDockerService`

**Suggestions for an improvement**
Fix the target location for logs when mounting the volume.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Renamed and standardize log volumes.

**Purpose of the change**  
Fixes #3328.

**What the code does**  
This PR fixes the path used to mount the logs directory of Pravega services on the host machine. This allows us to persistently store Pravega logs in the host machine, so they can survive to the lifecycle of containers. 

**How to verify it**  
Now logs are being persistently stored in the host machine:
```
[root@xxx-slave-2 ~]# ls /var/lib/docker/volumes/logs-volume/_data/
segmentstore_2019-01-30.0.log.gz  segmentstore_2019-01-30.1.log.gz  segmentstore_2019-01-30.2.log.gz  segmentstore_2019-01-30.3.log.gz  segmentstore.log
[root@xxx-slave-2 ~]# ls /var/lib/docker/volumes/volume-logs/_data/
controller_2019-01-30.0.log.gz  controller.log
```

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ public void start(final boolean wait) {
     }
 
     private ServiceSpec setServiceSpec() {
-        Mount mount = Mount.builder().type("Volume").source("volume-logs").target("/tmp/logs").build();
+        Mount mount = Mount.builder().type("Volume").source("volume-logs").target("/opt/pravega/logs").build();
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: @RaulGracia Does this implies the cluster node has  a volume `/volume-logs` for controller instances and `/logs-volume` for all segmentstore instances?

Also, if a segmentstore is stopped and scheduled again on the same slave node will it cause the logs files to be overwritten?

Comment (adrianmo) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/PravegaControllerDockerService.java]: The volume does not necessary need to exist in the cluster node. If it doesn't exist, it will be created dynamically, otherwise, it'll be reused.

However, the volume names used (`volume-logs`, `logs-volume`) do not look good. Maybe we could change that to `logs-controller` and `logs-segmentstore`, or similar.

**Comment by RaulGracia** [comment]
Found the following behavior upon a Controller container restart on the same node:
```
2019-01-30 16:20:15,503 1699218 [Delegate] DEBUG i.p.c.s.i.ReaderGroupStateManager - Update group state for reader aea9f226-901f-41e8-ad2e-5721d8d117af
2019-01-30 16:20:15,503 1699218 [clientInternal-24] DEBUG i.p.c.s.i.SegmentMetadataClientImpl - Getting segment info for segment: _system/_RGscaleGroup/0.#epoch.0
2019-01-30 16:20:15,503 1699218 [clientInternal-24] DEBUG i.p.client.netty.impl.RawClient - Sending request: WireCommands.GetStreamSegmentInfo(type=GET_STREAM_SEGMENT_INFO, requestId=1037, segmentName=_system/_RGscaleGroup/0.#epoch.0, delegationToken=)
2019-01-30 16:20:56,547 248  [main] INFO  io.pravega.controller.util.Config - Controller configuration:
2019-01-30 16:20:56,597 298  [main] INFO  io.pravega.controller.util.Config - user.country = Quoted("US")
2019-01-30 16:20:56,598 299  [main] INFO  io.pravega.controller.util.Config - sun.cpu.isalist = Quoted("")
2019-01-30 16:20:56,598 299  [main] INFO  io.pravega.controller.util.Config - config.controller.server.publishedRPCPort = Quoted("9090")
2019-01-30 16:20:56,599 300  [main] INFO  io.pravega.controller.util.Config - ZK_MAX_RETRIES = ConfigInt(5)
```
As can be seen, the logs for the new container are just appended after the last related to the previous container one on the same node.
Regarding rotation, the previous snippet was on file `controller_2019-01-30.2.log` that has as last line:
```
2019-01-30 16:53:47,544 634593 [controllerpool-71] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #71, timestamp=2019-01-30T16:53:47.544Z
```
The next rotated log file `controller_2019-01-30.3.log` starts by:
```
2019-01-30 16:53:49,271 636320 [Delegate] DEBUG i.p.c.s.i.ReaderGroupStateManager - Update group state for reader e4416403-bb43-43f0-8867-248bc33ec4a8
```
So, the rotation mechanism seems to take into account existing log files and continues creating new ones from the highest log file number onwards.
