### PR TITLE
Issue 1753: (SegmentStore) BugFix for Orphan Transaction Metadata

### LINKED ISSUE #1753: Durablelog recovery on failover fails with invalid parent segment id for a transaction
**Problem description**
this looks like a scenario where a transaction is being recovered before the parent segment and parent segment is not found (maybe because it is not recovered yet/does not exist at all).
```
2017-08-15 06:28:25,504 2613997 [segment-store-21] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED. {}
java.lang.IllegalArgumentException: parentStreamSegmentId: Invalid Parent Segment Id.
        at io.pravega.common.Exceptions.checkArgument(Exceptions.java:118)
        at io.pravega.segmentstore.server.containers.StreamSegmentContainerMetadata.mapStreamSegmentId(StreamSegmentContainerMetadata.java:173)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.copySegmentMetadata(ContainerMetadataUpdateTransaction.java:626)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.commit(ContainerMetadataUpdateTransaction.java:257)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.commit(OperationMetadataUpdater.java:150)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.commitAll(OperationMetadataUpdater.java:134)
        at io.pravega.segmentstore.server.logs.DurableLog.recoverFromDataFrameLog(DurableLog.java:400)
        at io.pravega.segmentstore.server.logs.DurableLog.performRecovery(DurableLog.java:327)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
**Problem location**

segmentstore durable log recovery.

**Suggestions for an improvement**
None.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in StreamSegmentContainerMetadata where it would be possible to evict a Parent SegmentMetadata while at least one of its Transaction Metadatas was still active.
- This is possible if the `getEvictionCandidates` needs to trim off the result due to a max cap restriction (we are instructed to only clean up so many items at once)
- Repro case:
    - We have Segment A with N transactions (A1->AN) 
    - We have an eviction cap of M <= N
    - A and A1..AN are all eligible for eviction, and A is not the Most Recently Used 
    - Since we can only evict M (M <= N) and have N+1 segments eligible, we will only evict the least recently used M. In this case, this includes segment A and N-1 of its transactions, leaving one transaction orphaned in the metadata.
- This would not cause any issues until that transaction would have to be merged or a recovery happens (during which we try to access its parent).

**Purpose of the change**
Fixes #1753.

**What the code does**
- I determined it would be too difficult to handle this in `getEvictionCandidates` and decided to tackle it in `cleanup` (which is the better place anyway, since a number of changes could have been made to the Metadata between the calls which narrowed down the eviction scope).
- `cleanup` now counts the exact number of active transactions per Segment, by subtracting those that will be removed from the total count (which is computed on the fly).

**How to verify it**
All pre-existing unit tests must pass. New unit test added to test this exact scenario.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java [hunk 1]
```diff
@@ -289,15 +293,26 @@ public void setContainerEpoch(long value) {
     @Override
     public Collection<SegmentMetadata> cleanup(Collection<SegmentMetadata> evictionCandidates, long sequenceNumberCutoff) {
         long adjustedCutoff = Math.min(sequenceNumberCutoff, this.lastTruncatedSequenceNumber.get());
+        HashMap<Long, Integer> txnCounts = new HashMap<>();
         Collection<SegmentMetadata> evictedSegments = new ArrayList<>(evictionCandidates.size());
         synchronized (this.lock) {
-            // Find those segments that have active transactions associated with them.
-            Set<Long> activeTransactions = getSegmentsWithActiveTransactions(adjustedCutoff);
+            // Count how many total transactions per parent segment there are.
+            this.metadataById
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java]: The logic seems right to me as we count the number of active txns per parent, and next subtract the txn segments that are eviction candidates. We only really evict in the case the parent has no remaining active txn segment (active txn segment not being evicted).

The one thing I'm wondering is whether we can do better than a linear scan over `metadataById` to determine the txn counts. Can't we keep a counter per parent segment and simply look at the counter of non-txn eviction candidates?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java [hunk 2]
```diff
@@ -289,15 +293,26 @@ public void setContainerEpoch(long value) {
...
+                    .stream()
+                    .filter(m -> m.isTransaction() && isEligibleForEviction(m, adjustedCutoff))
+                    .forEach(m -> updateValue(txnCounts, m.getParentId(), -1));
 
             // Remove those candidates that are still eligible for removal and which do not have any active transactions.
             evictionCandidates
                     .stream()
-                    .filter(m -> isEligibleForEviction(m, adjustedCutoff) && !activeTransactions.contains(m.getId()))
+                    .filter(m -> isEligibleForEviction(m, adjustedCutoff)
+                            && txnCounts.getOrDefault(m.getId(), 0) <= 0)
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java]: I think `txnCounts.getOrDefault(m.getId(), 0)` cannot be less than zero, so should we make it more specific and replace the inequality sign `<=` with `==` to be more specific?

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java [hunk 3]
```diff
@@ -609,6 +609,55 @@ public void testCleanup() {
         }
     }
 
+    /**
+     * Tests the ability to evict Segment Metadatas that are not in use anymore, subject to a cap. This test focuses in
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java]: Minor: Replace `Segment Metadatas` with either `Segment Metadata` or `Segment Metadata instances`.

Comment (andreipaduroiu) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadataTests.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java (hunk 2 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerMetadata.java]: Makes sense. In the worst case this will only reduce the number of segments evicted, not increase it, so it shouldn't cause issues.
