### PR TITLE
Issue 5062: Handle SegmentSealedException during Append Setup

### LINKED ISSUE #4351: Improve AppendProcessorTest considering the recent AppendProcessor improvement
**Problem description**
We recently made some improvement to AppendProcessor which seems caused some test instability to AppendProcessorTest.

**Problem location**
```
io.pravega.segmentstore.server.host.handler.AppendProcessorTest.testOutstandingByteTracking
Error Message
java.lang.AssertionError: single connection outstanding greater than total outstanding
Stacktrace
java.lang.AssertionError: single connection outstanding greater than total outstanding
	at io.pravega.segmentstore.server.host.handler.ConnectionTracker.shouldContinueReading(ConnectionTracker.java:101)
	at io.pravega.segmentstore.server.host.handler.ConnectionTracker.updateOutstandingBytes(ConnectionTracker.java:75)
	at io.pravega.segmentstore.server.host.handler.AppendProcessor.adjustOutstandingBytes(AppendProcessor.java:196)
	at io.pravega.segmentstore.server.host.handler.AppendProcessor.append(AppendProcessor.java:181)
	at io.pravega.segmentstore.server.host.handler.AppendProcessorTest.testOutstandingByteTracking(AppendProcessorTest.java:681)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Suggestions for an improvement**
Per Andrei, this looks a test issue so some improvement might be necessary for AppendProcessTest

### LINKED ISSUE #5062: Return appendSetup on sealed segment.
**Problem description**
On the line:
https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java#L160
If the segment is sealed the catch block here:
https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java#L171
will result in a `SegmentIsSealed` reply being sent. 
This means that the client won't be able to resolve the status of which messages were processed or not from before it's disconnection. 

**Problem location**
`AppendProcessor.setupAppend`

**Suggestions for an improvement**
Instead the catch block for `StreamSegmentSealedException` should call:
```
store.getAttributes(newSegment, Collections.singleton(writer), false, TIMEOUT)
```
and then use the result to return an `AppendSetup` similar to the happy path today.

### PR DESCRIPTION
**Pull request by ravibeta**
**Change log description**  
This change handles segment sealed on append operation.

**Purpose of the change**  
Fixes #5062 and an internal defect corresponding to appending a segment after it has been sealed.

**What the code does**  
treats the append like write

**How to verify it**  
ran tests
2020-08-12 14:10:19,472 6436 [Time-limited test] WARN i.p.c.s.i.SegmentOutputStreamImpl - Segment cannot be appended because it is already sealed for writer 9481b08e-326e-4ed6-957c-3b5c343e316c ]]

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 1]
```diff
@@ -161,14 +163,32 @@ public void setupAppend(SetupAppend setupAppend) {
                 .whenComplete((attributes, u) -> {
                     try {
                         if (u != null) {
+                            if (u instanceof StreamSegmentSealedException) {
+                                throw u;
+                            }
                             handleException(writer, setupAppend.getRequestId(), newSegment, "setting up append", u);
                         } else {
+                            SegmentProperties sp = this.store.getStreamSegmentInfo(newSegment, TIMEOUT).join();
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:171]: Invoking `join` here will eventually lead to a thread pool exhaustion.

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:171]: Also why are you doing this for successful operations?

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 2]
```diff
@@ -161,14 +163,32 @@ public void setupAppend(SetupAppend setupAppend) {
                 .whenComplete((attributes, u) -> {
                     try {
                         if (u != null) {
+                            if (u instanceof StreamSegmentSealedException) {
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:166]: This is an inelegant way of handling this. Please use an `exceptionally` clause before the `whenComplete` to do this.

Better yet, use `Futures.exceptionallyComposeExpecting` with `StreamSegmentSealedException.class` as its expected exception and add your special handling code in the callback.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 3]
```diff
@@ -161,14 +163,32 @@ public void setupAppend(SetupAppend setupAppend) {
...
+                                throw new StreamSegmentSealedException(newSegment);
+                            }
                             long eventNumber = attributes.getOrDefault(writer, Attributes.NULL_ATTRIBUTE_VALUE);
                             this.writerStates.putIfAbsent(Pair.of(newSegment, writer), new WriterState(eventNumber));
                             connection.send(new AppendSetup(setupAppend.getRequestId(), newSegment, writer, eventNumber));
                         }
                     } catch (Throwable e) {
-                        handleException(writer, setupAppend.getRequestId(), newSegment, "handling setupAppend result", e);
+                        if (e instanceof StreamSegmentSealedException || e.getCause() instanceof StreamSegmentSealedException) {
+                            log.info("Segment '{}' is sealed and {} cannot perform append, disabling caching of attribute value...", newSegment, writer);
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:181]: 1. This should not be info.
2. "disabling caching of attribute value" is misleading. We are not disabling anything, just passing an arg to a method. Disabling may be perceived as "disabling across the board".

I do not see the value of this log message here since the segment store logs its calls with all args.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 4]
```diff
@@ -161,14 +163,32 @@ public void setupAppend(SetupAppend setupAppend) {
...
+                            Map<UUID, Long> newAttributes = store.getAttributes(newSegment, Collections.singleton(writer), false, TIMEOUT).join();
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:182]: Again, you are using `join`

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 5]
```diff
@@ -161,14 +163,32 @@ public void setupAppend(SetupAppend setupAppend) {
...
+                            long eventNumber = Attributes.NULL_ATTRIBUTE_VALUE;
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:183]: This code looks copy pasted from above. If you use my suggestion above, you will not need this duplication.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 1 above)
Comment (ravibeta) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:171]: Yes Andrei, I could not find SegmentSealed exception raised until here.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 2 above)
Comment (ravibeta) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:166]: Yes Andrei

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 3 above)
Comment (ravibeta) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:181]: Yes Andrei

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 4 above)
Comment (ravibeta) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:182]: Yes Andrei.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java (hunk 5 above)
Comment (ravibeta) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:183]: Yes Andrei.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java [hunk 6]
```diff
@@ -157,20 +157,22 @@ public void setupAppend(SetupAppend setupAppend) {
...
-                            this.writerStates.putIfAbsent(Pair.of(newSegment, writer), new WriterState(eventNumber));
-                            connection.send(new AppendSetup(setupAppend.getRequestId(), newSegment, writer, eventNumber));
-                        }
-                    } catch (Throwable e) {
-                        handleException(writer, setupAppend.getRequestId(), newSegment, "handling setupAppend result", e);
-                    }
-                });
+        Futures.exceptionallyComposeExpecting(
+                store.getAttributes(newSegment, Collections.singleton(writer), true, TIMEOUT),
+                e -> e instanceof StreamSegmentSealedException, () -> store.getAttributes(newSegment, Collections.singleton(writer), false, TIMEOUT))
```
Comment (ravibeta) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:162]: @andreipaduroiu  could you please review this line, I believe it does not work as intended.  Thanks

Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java:162]: This looks good, however I want some way of logging that we are indeed running into some sealed segment. At the same time, I do not want to pollute the logs with useless messages. Looking through this class, it seems that a subsequent append via this connection-writer will stumble across a sealed segment which will take care of some logging and cleanup (OK - nothing to do there).

I just took a look at the `getAttributes` call inside the Segment Store and it turns out we are not logging the `cache` argument. Would you mind editing line 933 in `StreamSegmentContainer.java` and add the `cache` parameter to that `logRequest` call please? That way we will be able to see the first and the second call in the logs with proper args.
