### PR TITLE
Issue 1428: Fix duplicate Segment Id bug

### LINKED ISSUE #1428: Segment Container Fails to start due to DataCorruptionException while scaling up Segement Store service instances
**Problem description**
Segment Container fails to start when SSS is scaled from 1 instance to 3 instances. 
Segment Container 1 fails to start  with the following exception.
`io.pravega.segmentstore.server.DataCorruptionException: Unable to update metadata for Log Operation StreamSegmentAppendOperation: SequenceNumber = 71161, SegmentId = -9223372036854775806, Offset = 0, Length = 90, Attributes = 2`

`Caused by: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'testAutoScale102956883/testTxnScaleUp/0#transaction.bed5027e32c5415e89a2e91ab04b0879'] The StreamSegment does not exist.
`

When SSS was scaled to 3 instances stream creation failed.
Segment Container 1 failure: (It never came up on SSS-2). It failed with the above exception.
**Problem location**
SSS, while running system test MultiSegmentStoreTest.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Fixed a bug in the ContainerMetadataUpdateTransaction that could potentially create duplicate Segment Ids. SegmentIds should be generated starting from the current Operation Sequence number (which guarantees a unique id to begin with), however due to a bug in the code, this was being generated off the newly assigned sequence number (which would only be set during recovery, and always starts off at `Long.MIN_VALUE`). This has been fixed to work as before.

**Purpose of the change**
Fixes #1428. Please refer to this issue's comments for the complete steps to repro the problem.

**What the code does**
Fixes a bug introduced by #1330 / #1391.

**How to verify it**
Look at the code, make sure unit tests pass. New assertion has been introduced to validate new segment id is a positive number.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java [hunk 1]
```diff
@@ -114,13 +114,8 @@
...
         this.newSegments = new HashMap<>();
         this.newSegmentNames = new HashMap<>();
-        if (baseMetadata.isRecoveryMode()) {
-            this.newSequenceNumber = ContainerMetadata.INITIAL_OPERATION_SEQUENCE_NUMBER;
-        } else {
-            this.newSequenceNumber = Long.MIN_VALUE;
-        }
-
         this.sealed = false;
+        resetNewSequenceNumber();
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: One clarification here. The description of the pull request says:

> however due to a bug in the code, this was being generated off the
> newly assigned sequence number (which would only be set during
> recovery, and always starts off at Long.MIN_VALUE).

But if the base metadata is in recovery mode, then we set it to a different constant:

```
if (baseMetadata.isRecoveryMode()) {
             this.newSequenceNumber = ContainerMetadata.INITIAL_OPERATION_SEQUENCE_NUMBER;
 } else {
             this.newSequenceNumber = Long.MIN_VALUE;
 }
```

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java [hunk 2]
```diff
@@ -505,11 +501,12 @@ private long generateUniqueSegmentId() {
         // The ContainerMetadata.SequenceNumber is always guaranteed to be unique (it's monotonically strict increasing).
         // It can be safely used as a new unique Segment Id. If any clashes occur, just keep searching up until we find
         // a non-used one.
-        long segmentId = Math.max(this.baseMetadata.getOperationSequenceNumber(), ContainerMetadata.NO_STREAM_SEGMENT_ID + 1);
+        long segmentId = this.realMetadata.getOperationSequenceNumber();
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: Another clarification question. I don't fully understand why we use op sequence numbers to be segment ids. Is this use op sequence number just opportunistic or is there any other reason for doing it this way? I guess I don't understand how this logic of assigning ids works.

Following the code flow, I can see that: `preProcessMetadataOperation`-> `assignUniqueSegmentId` -> `generateUniqueSegmentId` in the case the segment has no id in the mapping.

Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: When we assign segment ids, I want them to be unique. I can either generate a random number and hope it's unique, but since not all segments are in memory, it's impossible to do it that way. Another thing that is guaranteed to be unique is the Operation Sequence Number. It is a monotonically strict-increasing number, which changes with every new operation. Since the only way to assign a SegmentId to a Segment is via an Operation, this guarantees uniqueness.  The subsequent while loop is just a fail-safe in case we do end up with some sort of duplicate.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java (hunk 1 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ContainerMetadataUpdateTransaction.java]: This `newSequenceNumber` is only set (and should only be used) during recovery, when we need to restore the ContainerMetadata's SequenceNumber to what it was before. In normal operations this does not get touched. If you check out the methods that set this value, they first check that the metadata is not in recovery mode. 

The bug was that I was using this value when I was assigning new segment ids. Since in that case this value was always Long.MIN_VALUE, there was a good chance of segment id collision (if a previous segment got evicted or deleted), hence the bug described in the original issue (not the PR).
