### PR TITLE
Issue 6939: handle ctrl c signal for controller

### LINKED ISSUE #6939: Pravega Controller process does not handle properly Cntrl+C signal
**Describe the bug**
When running Pravega locally where Controller and Segment Store are running as separate processes, the Controller does not handle properly the `Cntrl+C` signal. It gets stuck during shutdown and the user is forced to kill the process from outside:
```
2022-11-03 15:16:32,901 1031912 [ControllerServiceStarter STOPPING] INFO  i.p.c.server.bucket.BucketService - WatermarkingService: Cancellation for all background work for bucket 99 issued
2022-11-03 15:16:32,901 1031912 [ControllerServiceStarter STOPPING] INFO  i.pravega.client.stream.impl.Pinger - Closing Pinger periodic task
2022-11-03 15:16:32,902 1031913 [watermarkingpool-10] INFO  i.p.c.server.bucket.BucketManager - WatermarkingService: bucket service stopped
2022-11-03 15:16:32,903 1031914 [ControllerServiceStarter STOPPING] INFO  i.pravega.client.stream.impl.Pinger - Closing Pinger periodic task
2022-11-03 15:16:32,904 1031915 [ControllerServiceStarter STOPPING] INFO  i.pravega.client.stream.impl.Pinger - Closing Pinger periodic task
2022-11-03 15:16:32,932 1031943 [RESTServer STOPPING] INFO  io.pravega.shared.rest.RESTServer - REST server terminated
2022-11-03 15:16:32,932 1031943 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - REST Server shutdown.
2022-11-03 15:16:32,932 1031943 [ControllerServiceStarter STOPPING] INFO  i.p.c.s.ControllerServiceStarter - GRPC Server shutdown.

(Shutdown sequence is stuck here)
```
This does not happen when running the Segment Store process.

**To Reproduce**
1. Build Pravega and unzip the distribution artifact.
2. Open a console in the distribution folder and run the controller `./bin/pravega-controller`.
3. Then, try to shut down the process using `Cntrl+C`.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by AnkurAnand11**
**Change log description**  
Pravega Controller process does not handle properly Cntrl+C signal when the SegmentStore instance is down

**Purpose of the change**  
Fixes #6939 

**What the code does**  
Issue: When running Pravega locally where Controller and Segment Store are running as separate processes, once the SegmentStore instance is down and then if we try to bring down the controller instance giving ctrl+c signal, the controller gets stuck at shutting down its event processors job. basically what is happening is in the EventProcessorCell class, it is trying to connect to SegmentStore indefinitely in order to read the next event and gets stuck there.
Changes: When shutdown is issued for eventProcessors, in the stopAsync method of the EventProcessorCell , it checks if the Delegate thread isnot null and the interruptDelegate flag is set tot rue, it tries to interrupt the thread so that it proceeds with the shut down.

**How to verify it**  
(Optional: steps to verify that the changes are effective)

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 1]
```diff
@@ -84,6 +85,8 @@ private class Delegate extends AbstractExecutionThreadService {
         private final EventProcessorConfig<T> eventProcessorConfig;
         private EventRead<T> event;
         private final CheckpointState state;
+        private Thread currentThread;
+        private AtomicBoolean interruptFlag = new AtomicBoolean(false);
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:89]: Replace these two with a single AtomicReference<Thread>. Then you can compare and set to null and interupt the returned thread. This way the member variable can be made final which we need for thread safety.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 2]
```diff
@@ -84,6 +85,8 @@ private class Delegate extends AbstractExecutionThreadService {
         private final EventProcessorConfig<T> eventProcessorConfig;
         private EventRead<T> event;
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:86]: I realize you didn't write this, but this does not need to be a member variable. It can just made a parameter to the `handleException` method as all of the calls are local so it can simply be passed as an argument.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 3]
```diff
@@ -146,6 +152,15 @@ protected final void shutDown() throws Exception {
             }
         }
 
+        @Override
+        protected void triggerShutdown() {
+            log.info("Event processor triggerShutdown called for {}", objectId);
+            if (this.currentThread != null && Thread.State.WAITING.equals(this.currentThread.getState())) {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:158]: Regardless of the state it should interrupt.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 2 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:86]: `handleException` method is being called from three places -> inside `startUp()` , `run()` and `restart()` . May be that is why `event` is made as member variable.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 1 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Replaced the currentThread variable to `AtomicReference<Thread>` . Needed the interruptFlag to check the condition in triggerShutdown().

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 4]
```diff
@@ -76,14 +77,16 @@
...
+    private final Delegate delegate;
 
     private class Delegate extends AbstractExecutionThreadService {
 
         private final long defaultTimeout = 2000L;
         private final EventProcessorConfig<T> eventProcessorConfig;
         private EventRead<T> event;
         private final CheckpointState state;
+        private AtomicBoolean interruptFlag = new AtomicBoolean(false);
+        private AtomicReference<Thread> currentThread = new AtomicReference<>();
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:89]: final

**Comment by AnkurAnand11** [comment]
Ran system test suite on development-system test 1 and all the test cases have passed . Build 5002

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 4 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: done.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 1 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Replaced the two with a single AtomicReference.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 3 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: Handled the condition check in the stopAsync method's parameter of EventProcessorCell class.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 5]
```diff
@@ -146,6 +149,16 @@ protected final void shutDown() throws Exception {
             }
         }
 
+        @Override
+        protected void triggerShutdown() {
+            log.info("Event processor triggerShutdown called for {}", objectId);
+            Thread thread = this.currentThread.getAndSet(null);
+            if (thread != null && this.interruptFlag.get()) {
```
[the remark this answers is not in the document]
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: removed the member variable.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java [hunk 6]
```diff
@@ -265,10 +268,16 @@ final void startAsync() {
         }
     }
 
-    final void stopAsync() {
+    final void stopAsync(Boolean interruptDelegate) {
```
Comment (Amit-Singh40) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java:271]: Can we use primitive boolean here as null is not being passed anywhere. That will also reduce additional check Boolean.TRUE.equals(interruptDelegate)

**Comment by anju-c-das** [comment]
LGTM

**Review by tkaitchuck — APPROVED** [review]
Please fix above comment. Otherwise looks good.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java (hunk 6 above)
Comment (AnkurAnand11) [reply controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorCell.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ControllerFailoverTest.java [hunk 7]
```diff
@@ -145,4 +145,17 @@ public void testStop() throws Exception {
         controllerWrapper.awaitRunning();
         controllerWrapper.close();
     }
+
+    @Test(timeout = 180000)
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/ControllerFailoverTest.java:149]: Does this test really take this long? 3 minutes is a very long time to add to our pre-submit for just this one test. 
Currently we run 900 tests in under 20 minutes, so adding 3 just for this would be a major loss. Can we find a way to make this faster?

**Review by tkaitchuck — CHANGES_REQUESTED** [review]
Looking at the above, there are a number of failures in unit tests related to shutdown.
This may be related to this PR, if we have to retry commits many times this will be a problem.

File: test/integration/src/test/java/io/pravega/test/integration/ControllerFailoverTest.java (hunk 7 above)
Comment (AnkurAnand11) [reply test/integration/src/test/java/io/pravega/test/integration/ControllerFailoverTest.java]: Once the SS is down and controller is shut down, in the eventProcessor there is a readeroffline api which is again trying to connect to SS with a finite number of retries, so there is the delay. I have tried to simulate the scenario using a unit test.

File: controller/src/test/java/io/pravega/controller/eventProcessor/impl/EventProcessorTest.java [hunk 8]
```diff
@@ -369,6 +369,58 @@ public void testEventProcessorCell() throws CheckpointStoreException, Reinitiali
...
+                .decider((Throwable e) -> ExceptionHandler.Directive.Stop)
+                .config(config)
+                .build();
+        EventProcessorCell<TestEvent> cell = new EventProcessorCell<>(eventProcessorConfig, reader,
+                new EventStreamWriterMock<>(), system.getProcess(), READER_ID, 0, checkpointStore);
+
+        cell.startAsync();
+        cell.awaitStartupComplete();
+
+        Thread.sleep(1000); //To ensure stopAsync call is made after eventProcessor run has been called
```
Comment (tkaitchuck) [inline controller/src/test/java/io/pravega/controller/eventProcessor/impl/EventProcessorTest.java:419]: Can this be made to an `assertEventuallyEquals`? That would allow it to only take as long as needed.

Comment (AnkurAnand11) [reply controller/src/test/java/io/pravega/controller/eventProcessor/impl/EventProcessorTest.java]: Here I gave sleep of 1sec just to make sure stopAsync call is made after the eventProcessors cell's run method is called. Anyway, I have moved the stopAsync call to be invoked when reader.readNextEvent is called and removed the sleep of 1 sec.
