### PR TITLE
Issue 1378: Consolidate StoreExceptions

### LINKED ISSUE #1367: Revisit and consolidate Controller Exceptions
**Problem description**
Presently we have a lot of checked exceptions of different type all over the place in controller. 
it is generally a good idea to consolidate them component wise and throw the component exception (e.g. StoreException) and set specific traits and types in the exception using which we callers can handle them. 

**Problem location**
Controller Exceptions

**Suggestions for an improvement**
Consolidate exceptions

### LINKED ISSUE #1378: ZKStoreHelper should only throw StoreExceptions
**Problem description**
ZKStoreHelper throws some custom exceptions which clutters the exception flows. 
It should only throw StoreExceptions and its sub types.

**Problem location**
ZKStoreHelper 

**Suggestions for an improvement**
Make the custom exceptions subtype of StoreException

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
Removed unwanted custom exceptions and using only subtypes of StoreException

**Purpose of the change**
Fixes #1378 

**What the code does**
Uses only StoreException for ZKStore failures

**How to verify it**
All existing tests should pass

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/timeout/TimerWheelTimeoutService.java [hunk 1]
```diff
@@ -95,8 +94,8 @@ public void run(Timeout timeout) throws Exception {
                         // at a later point of time.
                         if (ex != null) {
                             Throwable error = getRealCause(ex);
-                            if (error instanceof WriteConflictException ||
-                                    error instanceof DataNotFoundException ||
+                            if (error instanceof StoreException.WriteConflictException ||
+                                    error instanceof StoreException.NodeNotFoundException ||
                                     error instanceof TransactionNotFoundException ||
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/timeout/TimerWheelTimeoutService.java]: `TransactionNotFoundException` could be mapped to `StoreException.NodeNotFound`, and `OperationOnTxNotAllowedException` could be mapped to `StoreException.IllegalState` isn't it?

Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/timeout/TimerWheelTimeoutService.java]: Done

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java [hunk 2]
```diff
@@ -59,7 +59,7 @@ public ZKStoreHelper(final CuratorFramework cf, Executor executor) {
             } catch (KeeperException.NodeExistsException e) {
                 throw StoreException.create(StoreException.Type.NODE_EXISTS, path);
             } catch (Exception e) {
-                throw StoreException.create(StoreException.Type.UNKNOWN, path);
+                throw new StoreException.UnknownException(path, e);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java]: I think this is not really `UNKNOWN`, but `UNSPECIFIED`, no?

File: controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java [hunk 3]
```diff
@@ -253,8 +252,8 @@ public void getStream(final String scopeName, final String streamName, final Sec
                         .entity(ModelHelper.encodeStreamResponse(streamConfig))
                         .build())
                 .exceptionally(exception -> {
-                    if (exception.getCause() instanceof DataNotFoundException
-                            || exception instanceof DataNotFoundException) {
+                    if (exception.getCause() instanceof StoreException.NodeNotFoundException
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java]: Is node specific to zk?

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 4]
```diff
@@ -81,142 +81,142 @@ public String getScopeName() {
 
         @Override
         public CompletableFuture<Void> delete() {
-            return FutureHelpers.failedFuture(new DataNotFoundException(stream));
+            return FutureHelpers.failedFuture(StoreException.create(StoreException.Type.NODE_NOT_FOUND, stream));
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: Is node specific to zk metadata?

File: test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java [hunk 5]
```diff
@@ -223,7 +223,7 @@ private static void getSegmentsForNonExistentStream(Controller controller) throw
             
             System.err.println("SUCCESS: Positions cannot be fetched for non existent stream");
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java]: This is probably for a different issue, but why are we still using `System.err` here rather than slf4j log messages?

File: controller/src/main/java/io/pravega/controller/store/stream/StoreException.java [hunk 6]
```diff
@@ -114,12 +134,42 @@ public NodeNotEmptyException() {
     }
 
     /**
+     * Exception type when you are attempting to update a stale value.
+     */
+    public static class WriteConflictException extends StoreException {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: here and elsewhere, retryability trait is lost. we need to retain retryable trait by implementing retryable exceptions wherever it was originally so.

File: controller/src/main/java/io/pravega/controller/store/stream/Stream.java [hunk 7]
```diff
@@ -236,22 +236,22 @@
     /**
      * Commits a transaction
      * If already committed, return TxnStatus.Committed
-     * If aborted, throw OperationOnTxNotAllowedException
+     * If aborted, throw IllegalStateException
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/Stream.java]: should we retain explicit 'throws' with method signature

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java (hunk 2 above)
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStoreHelper.java]: Basically it defines the class of errors that do not fall into any known error types. I am not sure whether `UNSPECIFIED` suits the bill.

File: controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java (hunk 3 above)
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java]: I agree, `node` is too ZK specific, `data` sounds better.

File: controller/src/main/java/io/pravega/controller/store/stream/StoreException.java (hunk 6 above)
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: An exception which is retryable in one context may not be retryable in another context, hence decorating exceptions with retryable trait may not be always possible. We could instead have pre-defined predicates that classify retryable exceptions. These predicates can be reused in multiple contexts.

File: controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java (hunk 3 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java]: +1, updated all exceptions to use data instead of node now.

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java (hunk 4 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: updated to data

File: test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java (hunk 5 above)
Comment (skrishnappa) [inline test/integration/src/test/java/io/pravega/test/integration/controller/server/ControllerServiceTest.java]: Replaced with log.info(), since its a low risk change I guess its fine to make this change in this PR itself.

File: controller/src/main/java/io/pravega/controller/store/stream/StoreException.java (hunk 6 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: good catch, totally missed this when moving the class. Updated to use the trait now to keep functionality same as before.

File: controller/src/main/java/io/pravega/controller/store/stream/StoreException.java [hunk 8]
```diff
@@ -23,33 +24,38 @@
      * Enum to describe the type of exception.
      */
     public enum Type {
-        NODE_EXISTS,
-        NODE_NOT_FOUND,
-        NODE_NOT_EMPTY,
+        DATA_EXISTS,
+        DATA_NOT_FOUND,
+        DATA_NOT_EMPTY,
```
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: Adding @fpj comment from a different PR here:
"I only have one comment about node not empty referring to a parent that still has children. I'm not sure there is anything we can do given that it is an exception type that exists already, but if we can give a more descriptive name, then better"

File: controller/src/main/java/io/pravega/controller/store/stream/Stream.java (hunk 7 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/Stream.java]: This is not a checked exception so we don't this in the declaration. Also there are other exceptions this method can throw so this declaration doesn't seem right. Have retained the javadoc though.

File: controller/src/main/java/io/pravega/controller/store/stream/StoreException.java (hunk 8 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: The NotEmpty is derived from the equivalent name given to the zookeeper exception for node which contains children. Been thinking of a few names but not convincing.

Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/store/stream/StoreException.java]: Renamed this to DATA_CONTAINS_ELEMENTS
