### PR TITLE
Issue 7213: Handle lock transfer in case of unreliable network

### LINKED ISSUE #7213: Handle ZNode persistent lock transfer in case of multiple controller restarts
**Describe the bug**
The createStream() API follows a bunch of processes in the following order:-

- Creates a persistent znode in zookeeper for this specific createStreamTask.
- Acquires a mutually exclusive lock on this znode.
- Does the necessary processing for creating the Stream.
- Releases the lock.
- Deletes the znode.
Now, because of network unavailability if the connection between the zk and controller gets lost the controller will perform a soft reboot and and new host ID will be generated. There could be a scenario when the persistent znode is already created and while the stream creation is in progress, the connectivity gets lost and controller performs a soft reboot. Now as soon as the new controller with new host id `c1` comes up, the sweepers will start sweeping the left over tasks from the previous controller let's say 'c0' and it will try to transfer lock of the persistent node by passing the parameters as oldHostId = `c0`, newHostId = 'c1'. If the connectivity gets lost before the lock is transferred and a new controller comes up with host id 'c2'.
Now, the LockData contains the information of the lock holder as `c0` but the sweeper task would pass on the method parameters as oldHostId = `c1`, newHostId = 'c2' which will not match with the LockData and it will throw `LockFailedException` the the same task won't ever get completed and hence would stop the client application to progress further.

**To Reproduce**
This is a very rare case scenario but can happen in a cluster. To reproduce this locally, lock transfer method can be called with the above explained scenario.

**Screenshots**
N/A
**Additional information**
In the above explained scenario, the following logs will be observed continuously as the controller will keep on retrying.
`Controller API call with tag createStream.scopeName-streamName failed with: Failed locking resource scopeName/streamName.`

### PR DESCRIPTION
**Pull request by shshashwat**
**Change log description**  
The changes are to remove the if condition during the transfer lock method. If the lock is acquired by a dead host, the sweeper task will try to transfer lock of the persistent node to the new host, however if during this process the controller dies and a new controller comes up then because of the condition the lock transfer will never take place and hence the stream creation will be impacted and the client application will always be in a stuck mode. 

**Purpose of the change**  
Fixes #7213 

**What the code does**  
A simple change to remove the `if` block from two places 
one during the transfer lock and second during the get task method.

**How to verify it**  
Build should pass and system test should pass

### CODE REVIEW

**Comment by shshashwat** [comment]
System 5153 succeeded

**Review by sachin-j-joshi — APPROVED** [review]
LGTM

**Comment by sachin-j-joshi** [comment]
Let us validate with system tests before merging.

**Comment by shshashwat** [comment]
> Let us validate with system tests before merging.

@sachin-j-joshi , system test on test-1 succeeded. the build no is 5153

File: controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java [hunk 1]
```diff
@@ -79,22 +80,16 @@ Void transferLock(final Resource resource,
             Stat stat = new Stat();
             byte[] data = client.getData().storingStatIn(stat).forPath(getTaskPath(resource));
             LockData lockData = LockData.deserialize(data);
-            if (lockData.isOwnedBy(oldOwner, oldThreadId)) {
-                lockData = new LockData(owner, threadId, lockData.getTaskData());
+            log.info("Transfer lock with the lockData.getHostId {}, oldOwner {}, oldThreadId {}, " +
```
Comment (abhinb) [inline controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java:83]: will this log line after the ZK set data(87-88) will be useful in cases of debugging?

**Review by abhinb — APPROVED** [review]

File: controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java (hunk 1 above)
Comment (shshashwat) [reply controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java:83]: It was added before so that during the lock transfer it would be easier to track in case of any error before updating the client

File: controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java [hunk 2]
```diff
@@ -162,12 +157,7 @@ public CompletableFuture<Optional<TaskData>> getTask(final Resource resource,
                     return Optional.empty();
                 } else {
                     LockData lockData = LockData.deserialize(data);
-                    if (lockData.isOwnedBy(owner, tag)) {
-                        return Optional.of(TaskData.deserialize(lockData.getTaskData()));
-                    } else {
-                        log.debug("Resource {} not owned by pair ({}, {})", resource.getString(), owner, tag);
-                        return Optional.empty();
-                    }
```
Comment (Bhupender-Y) [inline controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java:170]: Can it impact actually running controller instance? What happens if two controller instances get createStream request for same stream ?

Comment (shshashwat) [reply controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java:170]: Ideally the request won't land onto multiple controllers. The main task `createStream` will go to only one running instance. If somehow that instance goes down then other controller's sweeper task will try to fetch the pending tasks by calling `getTask` method.

Comment (Bhupender-Y) [reply controller/src/main/java/io/pravega/controller/store/task/ZKTaskMetadataStore.java:170]: Got it. This **getTask** method will be used during sweeper task only and will not impact normal createStream flow.

**Review by Bhupender-Y — APPROVED** [review]
LGTM
