### PR TITLE
Issue 4079: Keep Alive failure should invoke `ProcessingFailure` for all clients immediately.

### LINKED ISSUE #4079: KeepAlive failure causes the writer to wait for connection to be established.
**Problem description**
This issue was observed in the system test run `/jenkins/job/test-pravega-continuous/2182/`
The failover test `readwriteandautoscalewithfailovertest` failed since the writers were not able to establish connection.

*Details:*

[1]
// the test waits for all the writers to complete.
```
readwriteandautoscalewithfailovertest-iown9-2.log:2019-08-05 08:48:02,102 842412 [Time-limited test] INFO  i.p.t.system.AbstractReadWriteTest - Wait for writers execution to complete
```

[2]
// 4 writers were used by the test only 3 completed.
```
readwriteandautoscalewithfailovertest-iown9-2.log:2019-08-05 08:48:02,160 842470 [ReadWriteAndAutoScaleWithFailoverTest-main-2] INFO  i.p.t.system.AbstractReadWriteTest - Completed writing
readwriteandautoscalewithfailovertest-iown9-2.log:2019-08-05 08:48:02,181 842491 [ReadWriteAndAutoScaleWithFailoverTest-main-3] INFO  i.p.t.system.AbstractReadWriteTest - Completed writing
readwriteandautoscalewithfailovertest-iown9-2.log:2019-08-05 08:48:02,202 842512 [ReadWriteAndAutoScaleWithFailoverTest-main-1] INFO  i.p.t.system.AbstractReadWriteTest - Completed writing
```

[3]
```
// the 4th writer was stuck waiting while trying to connect to the segment.
2019-08-05 08:47:32,213 812523 [ReadWriteAndAutoScaleWithFailoverTest-main-5] DEBUG i.p.t.system.AbstractReadWriteTest - Event write count before write call 18481
2019-08-05 08:47:32,213 812523 [ReadWriteAndAutoScaleWithFailoverTest-main-5] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: testReadWriteAndAutoScaleScope48983609/testReadWriteAndAutoScaleStream/4.#epoch.2, writerID: e631ac54-bd03-40e4-af77-2f097feeba65
```

[4] The reconnection with segment store was stuck since establishing a connection ( this involves establishing network connection -> send `SETUP_APPEND` -> wait until the SSS 
responds) is not failed when a `KeepAlive` failure causes the connection to be terminated 

```
./readwriteandautoscalewithfailovertest-iown9-2.log:2019-08-05 08:46:58,503 778813 [clientInternal-2-1] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - Running reconnect for segment testReadWriteAndAutoScaleScope48983609/testReadWriteAndAutoScaleStream/4.#epoch.2 writer e631ac54-bd03-40e4-af77-2f097feeba65
2019-08-05 08:46:58,503 778813 [clientInternal-2-1] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment testReadWriteAndAutoScaleScope48983609/testReadWriteAndAutoScaleStream/4.#epoch.2, writer e631ac54-bd03-40e4-af77-2f097feeba65
2019-08-05 08:46:58,503 778813 [clientInternal-2-1] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getEndpointForSegment@4641419227133928 [testReadWriteAndAutoScaleScope48983609/testReadWriteAndAutoScaleStream/4.#epoch.2].
2019-08-05 08:46:58,505 778815 [grpc-default-executor-14] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE getEndpointForSegment@4641419227133928 (elapsed=2012us).
2019-08-05 08:46:58,505 778815 [clientInternal-2-1] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=172.24.22.16, port=12345) for testReadWriteAndAutoScaleScope48983609/testReadWriteAndAutoScaleStream/4.#epoch.2, writerID: e631ac54-bd03-40e4-af77-2f097feeba65
...
// the connection is killed before there is a response from SSS.
2019-08-05 08:47:14,100 794410 [epollEventLoopGroup-4-1] WARN  i.p.client.netty.impl.FlowHandler - Keep alive failed, killing connection 172.24.22.16 due to DefaultChannelPromise@1185f4c1(uncancellable)
// The keep alive failure kill the connection

```
**Problem location**
KeepAlive handling.

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Ensure all the `ReplyProcessor`s are intimated immediately in the case that sending a `WireCommands.KeepAlive` fails.

**Purpose of the change**  
Fixes #4079 

**What the code does**  
Pravega client sends periodic `KeepAlives` and sending a `KeepAlive` will fail if the connection is dropped. Also, netty invokes `io.pravega.client.netty.impl.FlowHandler#channelUnregistered` as soon as the connection is disconnected.

It was observed during a system test run( https://jenkins-server/jenkins/job/test-pravega-continuous/2182/)  that `channelUnregistered()`, which is used to communicate the connection failure, was never invoked as the `KeepAliveTask` task failed. This can cause writers waiting for the connection setup to complete (waiting for `SetupAppend`) to wait until the netty call back is invoked.

This PR ensures the client immediately intimates all the `ReplyProcessor`s about the connection failure before closing the `Channel`

**How to verify it**  
All the existing and newly added tests should continue to pass.
(System tests have passed with this change `/job/test-pravega-continuous/2190/`)

### CODE REVIEW

File: client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java [hunk 1]
```diff
@@ -266,12 +271,14 @@ public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws E
     @Override
     public void close() {
         if (closed.compareAndSet(false, true)) {
-            Channel ch = channel.get();
+            Channel ch = channel.getAndSet(null);
             if (ch != null) {
                 log.debug("Closing channel {} ", ch);
                 final int openFlowCount = flowIdReplyProcessorMap.size();
                 if (openFlowCount != 0) {
                     log.warn("{} flows are not closed", openFlowCount);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: I'm wondering if this log message makes sense because I believe we are closing the flows with the next line, is it right?

Comment (shrids) [reply client/src/main/java/io/pravega/client/netty/impl/FlowHandler.java]: I have improved the logging now.
