### PR TITLE
Issue 5963: SLTS - writeSnapshotInfo should not block in case of cache throttle.

### LINKED ISSUE #5963: SLTS : writeSnapshotInfo should not block in case of cache throttle
**Describe the bug**
_Expected behavior_
- writeSnapshotInfo should not block in case of cache throttle

_Actual behavior_
- the storage bootstrap is stuck 

**To Reproduce**
This issue will manifest whenever there is cache throttling while container is recovering from failure.
It may be hard to repro, but low memory env. should help with repro. 

**Screenshots**
```
2021-04-22 08:55:01,256 185533 [core-10] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[7] Enter RecoveryMode.
2021-04-22 08:55:03,160 187437 [core-10] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[7]: Exit RecoveryMode.
2021-04-22 08:55:03,160 187437 [core-10] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[7] Exit RecoveryMode.
2021-04-22 08:55:03,163 187440 [core-10] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[7]: Started.
2021-04-22 08:55:03,163 187440 [core-10] INFO  i.p.s.server.logs.DurableLog - DurableLog[7]: Started (Online).
```
SLTS init starts
```
2021-04-22 08:55:03,166 187443 [core-10] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[7]: Initializing storage.
2021-04-22 08:55:03,167 187444 [core-10] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[7]: Read SLTS snapshot. SnapshotInfo(epoch=3, snapshotId=1)
However same time there is a cache throttle.
2021-04-22 08:55:04,712 188989 [core-19] WARN  i.p.s.server.logs.Throttler - Throttler[7]: Processing delay = 25000ms (Max=true, Reason=Cache).
```
SLTS found snapshot by reading core attributes
`2021-04-22 08:55:05,486 189763 [storage-io-77] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[7] Done finding snapshots. Snapshot found and parsed. SnapshotInfo(epoch=3, snapshotId=1)`
```
Nothing happens as we are stuck with this throttle
2021-04-22 08:55:05,749 190026 [core-15] WARN  i.p.s.server.logs.Throttler - Throttler[7]: Processing delay = 25000ms (Max=true, Reason=Cache).
```
for hours
`2021-04-23 02:26:38,082 63282359 [core-23] WARN  i.p.s.server.logs.Throttler - Throttler[7]: Processing delay = 25000ms (Max=true, Reason=Cache)`
Looks this is where everything is stuck.

**Additional information**
There are two aspect to solution
1. Currently the container metadata segment is not marked "critical" which means update to it may be throttled. Which means writeSnapshotInfo gets into blocked state.  So one part of fix is to make that segment "critical"
2. The method `writeSnapshotInfo` should use timeout.

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
Signed-off-by: Sachin Joshi <sachin.joshi@emc.com>

**Change log description**  
SLTS : writeSnapshotInfo should not block in case of cache throttle

**Purpose of the change**  
Fixes #5963 

**What the code does**  
-  Make container metadata segment a Critical segment
-  Does not create snapshot during bootstrap
-  Minor clean up

**How to verify it**  
All tests should pass.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java [hunk 1]
```diff
@@ -97,10 +97,8 @@
                 .map(e -> new AttributeUpdate(e.getKey(), AttributeUpdateType.None, e.getValue()))
                 .collect(Collectors.toList());
 
-        // Container Metadata Segment is a System Table Segment. It is Internal, but it is not Critical (i.e., does not
-        // prevent the good functioning of the Segment Store). It is OK if "modify" operations on this segment are
-        // throttled as that would not prevent the Segment Store from making forward progress.
-        val segmentType = SegmentType.builder().tableSegment().system().internal().build();
+        // Container Metadata Segment is a System Table Segment. It is Internal, and Critical.
+        val segmentType = SegmentType.builder().tableSegment().critical().internal().build();
```
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java:101]: This is a system segment. Please put that back.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java [hunk 2]
```diff
@@ -496,12 +497,23 @@ public void initialize() throws Exception {
...
+        if (lastSavedSystemSnapshot.get() != null) {
+            boolean shouldSave = true;
+            if (lastSavedSnapshotInfo.get() == null) {
+                log.debug("SystemJournal[{}] Saving first snapshot info new={}.", containerId, lastSavedSystemSnapshotId.get());
+            } else if (lastSavedSnapshotInfo.get().getSnapshotId() < lastSavedSystemSnapshotId.get()) {
+                log.debug("SystemJournal[{}] Saving new snapshot info new={} old={}.", containerId,
+                        lastSavedSystemSnapshotId.get(), lastSavedSnapshotInfo.get().getSnapshotId());
+            } else {
+                shouldSave = false;
+                log.trace("SystemJournal[{}] Snapshot info is up to date", containerId);
```
Comment (andreipaduroiu) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:509]: We rarely enable trace. Would it be ok to make this debug?

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java (hunk 1 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/TableMetadataStore.java:101]: Thanks good catch.
Completely missed that.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/SystemJournal.java:509]: It will create lot of useless spam.
I think I'll just remove it.

**Comment by sachin-j-joshi** [comment]
@andreipaduroiu I have addressed the comments and added more logs.

**Review by andreipaduroiu — APPROVED** [review]
