### PR TITLE
Issue 2523: Remove race condition in the EndToEndChannelLeakTest.

### LINKED ISSUE #2523: EndToEndChannelLeakTest  test failure
**Problem description**
EndToEndChannelLeakTest  fails sporadically.
```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakMultiReader FAILED
    java.lang.AssertionError: expected:<5> but was:<4>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakMultiReader(EndToEndChannelLeakTest.java:207)
```
**Problem location**
EndToEndChannelLeakTest.java

**Suggestions for an improvement**
Fix the race condition in the test.

### PR DESCRIPTION
**Pull request by shrids**
Signed-off-by: Sandeep <sandeep.shridhar@emc.com>

**Change log description**
Refactor and remove the race condition in EndToEndChannelLeakTest#testDetectChannelLeakMultiReader.

**Purpose of the change**
Fixes #2523 

**What the code does**
Remove race condition while checking for open sockets.

**How to verify it**
The tests should continue to pass.

### CODE REVIEW

File: test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java [hunk 1]
```diff
@@ -177,43 +177,40 @@ public void testDetectChannelLeakMultiReader() throws Exception {
...
                 ReaderConfig.builder().build());
-
-        //Total 5 sockets are open at this point : Writer has 1 connection to segment 0 of stream +
-        //Reader has 4 connections to the reader group (read, write, metadata, and conditionalUpdates)
-        assertEquals(5, connectionFactory.getActiveChannelCount());
-        int channelCount = 5;
-
-        //Read an event.
+        //Creating a reader spawns a revisioned stream client which opens 4 sockets ( read, write, metadataClient and conditionalUpdates).
+        expectedChannelCount += 4;
```
Comment (tkaitchuck) [inline test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java]: An assertion was removed here that should be still present.

Comment (shrids) [reply test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndChannelLeakTest.java]: Removed the assertion here as the `operationComplete` callback (ref: https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/netty/impl/ConnectionFactoryImpl.java#L157) might or might not be completed when the check for activeChannel count for a value of 5 is performed.

Modified the test to ensure that we check the channel count when we are absolutely sure that connection has been established.
