### PR TITLE
Issue 3213: Fix System test framework and test issues.

### LINKED ISSUE #3213: Kubernetes framework errors.
**Problem description**
Couple of issues with the existing system test and framework
1. 
Log download fails on slower clusters.
```
   2018-12-17 05:43:14,742 328500 [pravega-k8s-client-1] ERROR i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: RequestFailed, Details: Error while copying files
    io.kubernetes.client.ApiException: Logs request failed: 400
```

2. Pravega operator version is not configurable.
3. A read time out on slower clusters should not cause PravegaTest to fail.
**Problem location**

K8sClient.java,  PravegaTest.java

**Suggestions for an improvement**
Increase the retries to handle errors on slower clusters.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Ensure pravega operator version is configurable.
- Increase retries for log download.
- Fix bug in PravegaTest.

**Purpose of the change**  
Fixes #3213

**What the code does**  
- On slower / resource starved clusters log download would fail as the pod creation would take a longer time. Now the framework retries for  a longer duration.
- A bug in PravegaTest has been fixed which caused the test to exit when the read timed out.
- Pravega operator is now configurable.

**How to verify it**  
All the tests should continue to pass.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java [hunk 1]
```diff
@@ -37,19 +37,16 @@
     @Getter(lazy = true)
     private final ConnectionFactory connectionFactory = new ConnectionFactoryImpl(ClientConfig.builder().build());
     @Getter(lazy = true)
-    private final ControllerImpl controller = createController();
+    private final ClientFactoryImpl clientFactory = new ClientFactoryImpl(SCOPE, new ControllerImpl(
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java]: Could we use the `controller` attribute as input for the `clientFactory`?

File: test/system/src/test/java/io/pravega/test/system/PravegaTest.java [hunk 2]
```diff
@@ -155,7 +155,7 @@ public void simpleTest() {
                 fail("Reinitialization Exception is not expected");
             }
             // try reading until all the written events are read, else the test will timeout.
-        } while ((event.getEvent() != null || event.isCheckpoint()) && readCount < NUM_EVENTS);
+        } while ((event.getEvent() == null || event.isCheckpoint()) && readCount < NUM_EVENTS);
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/PravegaTest.java]: With this change, if the event is a regular read (contains data and is not a checkpoint), the loop will exit, right?

Looking at the logs, the problem I see is the following:

- The writer seems to correctly write events to the Stream (segment store logs): 
```
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=testScopeSampleYndrFi/testStreamSampleY/0.#epoch.0, offset=0, suggestedLength=1048576, delegationToken=)
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: read [testScopeSampleYndrFi/testStreamSampleY/0.#epoch.0, 0, 1048576]
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.reading.ContainerReadIndex - ReadIndex[3]: read (StreamSegmentId = 12402, Offset = 0, MaxLength = 1048576).
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[3-12402]: Read (Offset = 0, MaxLength = 1048576).
2018-12-17 09:13:57,496 12934343 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xa441dab2, L:/xxx:12345] READ: [id: 0x026f5ed8, L:/xxx:12345 - R:/xxx:56880]
2018-12-17 09:13:57,496 12934343 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xa441dab2, L:/xxx:12345] READ COMPLETE
```

- The client issues the `READ_SEGMENT` request:
```
2018-12-17 09:13:57,491 3485 [grpc-default-executor-0] TRACE i.p.c.s.i.AsyncSegmentInputStreamImpl - Sending read request WireCommands.ReadSegment(type=READ_SEGMENT, segment=testScopeSampleYndrFi/testStreamSampleY/0.#epoch.0, offset=0, suggestedLength=1048576, delegationToken=)
```

- The segment store receives that request:
```
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=testScopeSampleYndrFi/testStreamSampleY/0.#epoch.0, offset=0, suggestedLength=1048576, delegationToken=)
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[3]: read [testScopeSampleYndrFi/testStreamSampleY/0.#epoch.0, 0, 1048576]
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.reading.ContainerReadIndex - ReadIndex[3]: read (StreamSegmentId = 12402, Offset = 0, MaxLength = 1048576).
2018-12-17 09:13:57,493 12934340 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[3-12402]: Read (Offset = 0, MaxLength = 1048576).
2018-12-17 09:13:57,496 12934343 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xa441dab2, L:/xxx:12345] READ: [id: 0x026f5ed8, L:/10.200.91.79:12345 - R:/xxx:56880]
2018-12-17 09:13:57,496 12934343 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xa441dab2, L:/xxx:12345] READ COMPLETE
```

- But the client is not able to read any data:
```
2018-12-17 09:13:58,497 4491 [Time-limited test] DEBUG io.pravega.test.system.PravegaTest - Read event: null.
```

Perhaps, a possible cause for this is that the timeout may be too low in this infrastructure (it was not the case before, though).

Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/PravegaTest.java]: In a second execution, it looks like a single event was read, which may indicate that read can happen, but the timeout is too short:
```
Caused by: java.lang.AssertionError: Read count should be equal to write count expected:<100> but was:<1>
```

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 3]
```diff
@@ -548,16 +548,16 @@ public void deletePVC(String namespace, String name) {
      */
     public CompletableFuture<Void> downloadLogs(final V1Pod fromPod, final String toFile) {
 
-        return Retry.withExpBackoff(500, 10, 2)
+        return Retry.withExpBackoff(500, 10, 3)
```
[the remark this answers is not in the document]
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: done.

File: test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java (hunk 1 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/AbstractScaleTests.java]: removed redundant changes.

File: test/system/src/test/java/io/pravega/test/system/PravegaTest.java (hunk 2 above)
Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/PravegaTest.java]: the test tries to read until it has read the required number of events. Else the test will timeout.

File: test/system/src/test/java/io/pravega/test/system/PravegaTest.java [hunk 4]
```diff
@@ -155,7 +155,7 @@ public void simpleTest() {
                 fail("Reinitialization Exception is not expected");
             }
             // try reading until all the written events are read, else the test will timeout.
-        } while ((event.getEvent() != null || event.isCheckpoint()) && readCount < NUM_EVENTS);
+        } while (readCount < NUM_EVENTS);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/PravegaTest.java]: This is weakening the verification, why? We don't really expect read timeouts, so perhaps the right way of fixing this is to increase the timeout value.

Comment (shrids) [reply test/system/src/test/java/io/pravega/test/system/PravegaTest.java]: done.

**Comment by RaulGracia** [comment]
Waiting for Jenkins build from @anishakj before approving this PR.

**Comment by shrids** [comment]
[Issue 3213: Fix PravegaTest and BatchClientTest.](https://trello.com/c/kDuI0ZEv/65-issue-3213-fix-pravegatest-and-batchclienttest)
