### PR TITLE
Issue 4590: (SegmentStore) Fixed Read Index concurrent Tier 2 read bug (Part 2)

### LINKED ISSUE #4590: DataCorruptionException in StorageWriter when fetching Read Index contents
**Problem description**
The Storage Writer occasionally trips over a problem where it cannot read data from the Read Index.

Symptoms:
1. Storage Writer has just flushed data to Tier 2 up to offset `B`. 
2. Read Index evicts range `[A, B)` (`A` < `B`)
3. Two concurrent Read Index read requests end up reinserting range `[A, B)` twice
    -  First one completes at time t1 and a new Cache Entry `[A, B)` is created.
4. An Append happens at offset `B` of length `L`. This gets appended to the cache entry at the previous step.
5. The second Read index read request completes with range `[A, B)`.
    - This ends up overwriting the entry created at step 3 and updated at step 4.
    - This is accompanied by a `WARN` in the logs that the second insert overrode the first one
4. The Storage Writer correctly complains that it cannot read offsets `[B, B+L)`.

Alternate situations:
- It is possible to run into this problem even if the concurrent Tier 2 reads do not begin at the same offset, but have overlapping ranges. PR #4596 addresses this as well.

In addition the `WARN` printed out in the logs has cache entries reversed (old is new, new is old). 

Specific examples:
(Note these have been edited to output the correct values for OldLength and NewLength.
```
2020-03-03 10:51:16,364 86007109 [core-21] WARN  i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[10-7]: Insert overrode existing entry (Offset = 7747897, OldLength = 11088, NewLength = 10954).
2020-03-03 10:51:16,605 86007350 [core-25] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[10]: Iteration[112516].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 7, Offsets = [7758851-7758985), SeqNo = 671834'.
```

and another one:
```
2020-03-03 11:15:51,819 87457206 [core-27] WARN  i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[16-296681]: Insert overrode existing entry (Offset = 6153848, OldLength = 1301, NewLength = 680).
2020-03-03 11:15:53,278 87458665 [core-10] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[16]: Iteration[55258].CriticalError.
io.pravega.segmentstore.server.DataCorruptionException: Unable to retrieve CacheContents for 'AggregatedAppend: SegmentId = 296681, Offsets = [6154528-6156006), SeqNo = 534738'.
```

**Problem location**
Segment Store. Either Read Index or Segment Aggregator.

**Suggestions for an improvement**
Fix the problem.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
Fixed a (second) bug in StreamSegmentReadIndex where it would have been possible for two concurrent Storage read requests to override one another, resulting in potential (in-memory) data loss should there be an append executed in between the two.

**Purpose of the change**  
Fixes #4590.

**What the code does**  
See #4592 for details on the first bug.
#4592 handled the case when the concurrent reads began at  exactly the same Segment offset. This PR covers an additional case when two or more concurrent Tier 2 reads (resulting from cache misses) do not necessarily start at the same offset, but have at least one overlapping byte.

This PR aims to completely eliminate duplicated data in the Read Index due to such situations. Having Read Index entries that overlap can cause inconsistent read behaviors depending on what offset your read originated; this can also cause recently appended data to vanish from the read index (see parent issue for how this can happen).

**How to verify it**  
New unit tests added to verify this specific scenario.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java [hunk 1]
```diff
@@ -577,41 +586,67 @@ private CacheIndexEntry addSingleEntryToCacheAndIndex(BufferView data, long offs
...
+                    CacheIndexEntry newEntry;
+                    int dataAddress = this.cacheStorage.insert(dataToInsert);
+                    try {
+                        newEntry = new CacheIndexEntry(segmentOffset, dataToInsert.getLength(), dataAddress);
+                        ReadIndexEntry overriddenEntry = addToIndex(newEntry);
+                        assert overriddenEntry == null : "Insert overrode existing entry; " + segmentOffset + ":" + dataToInsert.getLength();
+                        lastInsertedEntry = newEntry;
+                    } catch (Throwable ex) {
+                        // Clean up the data we inserted if we were unable to add it to the index.
+                        this.cacheStorage.delete(dataAddress);
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java]: Is this line reachable? (in practice)

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java]: No. Not really. If we end up here then some exception got thrown from `addToIndex` and we must make sure we delete the data from the cache otherwise it will stay there forever. The only exception thrown from there is an `ObjectClosedException`, which indicates the whole index is about to close (or has just been) so we must clean up anyway.
