### PR TITLE
Issue 6502: Make hardcoded values in ThrottlerCalculator configurable

### LINKED ISSUE #6502: Make hardcoded values in ThrottlerCalculator as configurable.
**Describe the bug**
Various different constants used in ThrottlerCalculator are hardcoded. They should be made configurable.

Especially following 

- static final int MAX_BATCHING_DELAY_MILLIS = 50;
- static final int MAX_DELAY_MILLIS = 25000;
- static final int OPERATION_LOG_MAX_SIZE = 1_000_000;

**To Reproduce**
Visual code inspection

**Screenshots**
None

**Additional information**
None

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Allow configuration of several ThrottlerCalculator (`maxBatchingDelayMillis`, `maxDelayMillis`, `operationLogTargetSize`, `operationLogMaxSize`);

**Purpose of the change**  
Fixes #6502.

**What the code does**  
Some of the constants in `ThrottleCalculator` have a key importance in how throttling behaves in Pravega. While the existing defaults have been carefully chosen, we want to expose some of these values, as it may be interesting to work with them in different scenarios. To add these throttling configuration parameters, this PR changes the following:
- Add the following parameters to override the corresponding default values in `ThrottleCalculator`: `throttler.max.batching.delay.millis`, `throttler.max.delay.millis`, `throttler.operation.log.size.target`, `throttler.operation.log.size.max`. Note that the default values for these properties are the same as always.
- Added POJO class `ThrottlerSettings` to encapsulate throttling specific configuration and be passed from `DurableLog` to `OperationProcessor` and used to instantiate `ThrottlerCalculator`.

**How to verify it**  
No changes in throttling logic. All existing tests should pass. System tests passed.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerSettings.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+ */
+@Data
+class ThrottlerSettings {
+
+    private final int maxBatchingDelayMillis;
+    private final int maxDelayMillis;
+    private final int operationLogMaxSize;
+    private final int operationLogTargetSize;
+
+    public ThrottlerSettings(DurableLogConfig config) {
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerSettings.java:32]: Let's use name `ThrottlerConfig` to keep convention and move new configs into it (instead of DurableLogConfig).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java [hunk 2]
```diff
@@ -32,6 +32,10 @@
     public static final Property<Integer> CHECKPOINT_COMMIT_COUNT = Property.named("checkpoint.commit.threshold.count", 300, "checkpointCommitCountThreshold");
     public static final Property<Long> CHECKPOINT_TOTAL_COMMIT_LENGTH = Property.named("checkpoint.commit.length.total", 256 * 1024 * 1024L, "checkpointTotalCommitLengthThreshold");
     public static final Property<Integer> START_RETRY_DELAY_MILLIS = Property.named("start.retry.delay.millis", 60 * 1000, "startRetryDelayMillis");
+    public static final Property<Integer> MAX_BATCHING_DELAY_MILLIS = Property.named("throttler.max.batching.delay.millis", ThrottlerCalculator.MAX_BATCHING_DELAY_MILLIS);
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java:35]: Let's move these constants to its own class `ThrottlerConfig`.
Component name is `throttler`
These are not only related to Durable log

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java [hunk 3]
```diff
@@ -81,6 +82,10 @@
      */
     @VisibleForTesting
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java:83]: please remove this and other constants in code
```
static final int OPERATION_LOG_MAX_SIZE = 1_000_000;
static final int MAX_DELAY_MILLIS = 25000; 
```
in short whatever is coming from config should not be constant.

I suggest move all magic constants to config.

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]
0. Please remove the actual constants defined in ThrottleCalculator
1. Move all new configs to new class `ThrottlerConfig` (This becomes your new ThrottlerSettings)
2. Another important magic number to be replaced is 0.95. How is this related with operationLogTargetSize ? 
3. Use validation method getPositiveInt
Also If possible see if making individual Throttler classes non static reduces code change without need to change constructors for passing config values. (Or may be you can pass ThrottleConfig to constructor)

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java [hunk 4]
```diff
@@ -86,6 +115,21 @@ private DurableLogConfig(TypedProperties properties) throws ConfigurationExcepti
             throw new ConfigurationException(String.format("Property '%s' must be a positive integer.", START_RETRY_DELAY_MILLIS));
         }
         this.startRetryDelay = Duration.ofMillis(startRetryDelayMillis);
+
+        // Throttler configuration.
+        this.maxBatchingDelayMillis = properties.getInt(MAX_BATCHING_DELAY_MILLIS);
+        checkPositiveIntegerPropertyValue(MAX_BATCHING_DELAY_MILLIS, this.maxBatchingDelayMillis);
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java]: Right, totally forgot that I added that method.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java [hunk 5]
```diff
@@ -81,6 +82,10 @@
...
     static final int OPERATION_LOG_TARGET_SIZE = (int) (OPERATION_LOG_MAX_SIZE * 0.95);
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java]: This is just defining that `OPERATION_LOG_TARGET_SIZE` is 95% of what `OPERATION_LOG_MAX_SIZE` is. In practice, it basically means that, for `OperationLog` throttler, the delays will start to be induced when the in-memory log reaches 950K operations (95% of 1M), and the delay will be maximum when the operation log reaches `OPERATION_LOG_MAX_SIZE` (increasing in a linear manner). I shared a plot of how this throttler behaves internally, please take a look.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerSettings.java (hunk 1 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerSettings.java]: Throttling is a sub-component of the `DurableLog` and for this reason is configured in that place. The same happens with the metadata checkpoints, as you can see that they are also configured as part of the `DurableLog` and not as a separate component. To follow the current structure, I called the class `ThrottlerPolicy` to be consistent with other classes that do the same, like `MetadataCheckpointPolicy`.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java (hunk 2 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/DurableLogConfig.java]: Answered above (throttling is a subcomponent of `DurableLog` and is configured there, as metadata checkpoints).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java (hunk 3 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/ThrottlerCalculator.java]: All these constants are moved to `ThrottlerPolicy` class. Now, the `ThrottlerClaculator` just performs calculations and the configuration part is encapsulated in `ThrottlerPolicy`.

**Comment by RaulGracia** [comment]
As a safety check, I have configured these new parameters in Pravega on a local deployment:
1) We see that the configuration parameters are loaded:
```
segmentstore_2022-01-09_18.0.log.gz:2022-01-09 18:58:47,869 840  [main] INFO  i.p.s.server.host.ServiceStarter - durablelog.throttler.operation.log.size.max = 100
segmentstore_2022-01-09_18.0.log.gz:2022-01-09 18:58:47,870 841  [main] INFO  i.p.s.server.host.ServiceStarter - durablelog.throttler.operation.log.size.target = 50
segmentstore_2022-01-09_18.0.log.gz:2022-01-09 18:58:47,870 841  [main] INFO  i.p.s.server.host.ServiceStarter - durablelog.throttler.max.delay.millis = 1000
segmentstore_2022-01-09_18.0.log.gz:2022-01-09 18:58:47,870 841  [main] INFO  i.p.s.server.host.ServiceStarter - durablelog.throttler.max.batching.delay.millis = 20
```
2) None of the batching delays was larger than 20ms (instead of the 50ms default), as configured:
```
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:05,589 356502 [core-20] DEBUG i.p.s.server.logs.Throttler - Throttler[3]: Processing delay = 10ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:05,931 356844 [core-27] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 10ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:05,993 356906 [core-10] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 17ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,012 356925 [core-22] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 9ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,228 357141 [core-3] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 11ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,549 357462 [core-26] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 6ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,560 357473 [core-27] DEBUG i.p.s.server.logs.Throttler - Throttler[2]: Processing delay = 6ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,626 357539 [core-18] DEBUG i.p.s.server.logs.Throttler - Throttler[3]: Processing delay = 17ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,648 357561 [core-13] DEBUG i.p.s.server.logs.Throttler - Throttler[3]: Processing delay = 15ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:06,766 357679 [core-29] DEBUG i.p.s.server.logs.Throttler - Throttler[3]: Processing delay = 9ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:07,046 357959 [core-21] DEBUG i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 10ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:07,582 358495 [core-4] DEBUG i.p.s.server.logs.Throttler - Throttler[2]: Processing delay = 9ms (Max=false, Reason=Batching).
segmentstore_2022-01-09_19.9.log.gz:2022-01-09 19:09:07,594 358507 [core-4] DEBUG i.p.s.server.logs.Throttler - Throttler[2]: Processing delay = 8ms (Max=false, Reason=Batching).

```

3) I stopped tier 2 and wrote some events to see the other throttling parameters. Visibly, when we have more than the configured `100` operations of max log size, we observed max throttling (of 1 second, as configured as well):
```
segmentstore_2022-01-09_19.4.log.gz:2022-01-09 19:07:17,454 248367 [core-13] DEBUG i.p.s.server.logs.Throttler - Throttler[2]: Throttling interrupted while actively throttling (Source = OperationLog, Remaining = 990).
segmentstore_2022-01-09_19.4.log.gz:2022-01-09 19:07:17,454 248367 [core-13] WARN  i.p.s.server.logs.Throttler - Throttler[2]: Processing delay = 1000ms (Max=true, Reason=OperationLog).
```

This shows that the new configuration parameters do actually take effect when set with non-default values.

**Comment by RaulGracia** [comment]
System tests have passed `test-pravega-continuous/4289`

**Review by sachin-j-joshi — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
lgtm

**Review by abhinb — APPROVED** [review]
