### PR TITLE
Issue 4591: Fixed ExtendedS3 exists()

### LINKED ISSUE #4591: ExtendedS3Storage: incorrect implementation of exists
**Problem description**
Currently the ExtendedS3Storage implements exists() by calling listObjects with given path and checking whether list returned is empty or not.
For the path that corresponds with full path to the object this is correct. However this breaks when the path checked is a prefix. In this case list of other object matching that prefix will be returned and the code will incorrectly determine that object exists. 

**Problem location**
ExtendedS3Storage . doExists

**Suggestions for an improvement**
Instead of listObjects use getObjectMetadata.

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
**Change log description**  
This change uses getObjectMetadata instead of listObjects to implement exists.
This fixes the current problem where listObject based check behaves incorrectly when prefix instead of full path is provided as parameter.

**Purpose of the change**  
Fixes #4591 
**What the code does**  
This change uses getObjectMetadata instead of listObjects to implement exists.

**How to verify it**  
Unit tests, System Tests and longevity tests should pass and should not show the incorrect behavior anymore.

### CODE REVIEW

File: bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java [hunk 1]
```diff
@@ -263,18 +262,10 @@ private StreamSegmentInformation doGetStreamSegmentInfo(String streamSegmentName
 
     private boolean doExists(String streamSegmentName) {
         try {
-            ListObjectsResult result = client.listObjects(config.getBucket(), config.getPrefix() + streamSegmentName);
-            return !result.getObjects().isEmpty();
+            S3ObjectMetadata result = client.getObjectMetadata(config.getBucket(),
+                    config.getPrefix() + streamSegmentName);
```
Comment (medvedevigorek) [inline bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java]: _streamSegmentName_ is actually a stream segment name but do we actually create objects with such names? I thought   for each segment there will be objects like _streamSegmentName$header_ or _streamSegmentName$attributes_. So if we simple check for presence of an object with _streamSegmentName_ we always get object not found. Am i missing something here?

Comment (sachin-j-joshi) [reply bindings/src/main/java/io/pravega/storage/extendeds3/ExtendedS3Storage.java]: The layer above this component (RollingStorage) passes the names like _streamSegmentName$header_ or _streamSegmentName$attributes_ to this component.

**Comment by sachin-j-joshi** [comment]
@andreipaduroiu the system tests and short longevity tests passed. (We don't see this issue. Fix worked.)
