### PR TITLE
Issue 1651: Fix the issues while closing readers in multireaderwriterfailover system test

### LINKED ISSUE #1651: Exception while closing readers in multireaderwriterfailovertest
**Problem description**
```
 StackTrace:
java.lang.RuntimeException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
    at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:194)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.readEventData(SegmentInputStreamImpl.java:122)
    at io.pravega.client.segment.impl.SegmentInputStreamImpl.read(SegmentInputStreamImpl.java:104)
    at io.pravega.client.segment.impl.SegmentInputStream.read(SegmentInputStream.java:54)
    at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:141)
    at io.pravega.client.state.impl.RevisionedStreamClientImpl$StreamIterator.next(RevisionedStreamClientImpl.java:116)
    at io.pravega.client.state.impl.StateSynchronizerImpl.fetchUpdates(StateSynchronizerImpl.java:77)
    at io.pravega.client.state.impl.StateSynchronizerImpl.conditionallyWrite(StateSynchronizerImpl.java:174)
    at io.pravega.client.state.impl.StateSynchronizerImpl.updateState(StateSynchronizerImpl.java:105)
    at io.pravega.client.stream.impl.ReaderGroupStateManager.readerShutdown(ReaderGroupStateManager.java:134)
    at io.pravega.client.stream.impl.ReaderGroupStateManager.readerShutdown(ReaderGroupStateManager.java:126)
    at io.pravega.client.stream.impl.EventStreamReaderImpl.close(EventStreamReaderImpl.java:211)
```

**Problem location**
System tests - Multireaderwriterfailovertest

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
Handles the exception while closing readers in failover system test.

**Purpose of the change**
The test fails on the retries exhausted exception thrown by `reader.close()`.

**What the code does**
Fixes #1651 

**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 1]
```diff
@@ -309,12 +303,19 @@ public void multiReaderWriterWithFailOverTest() throws Exception {
         log.info("Test {} succeeds ", "MultiReaderWriterWithFailOver");
     }
 
+    private void cleanUp() throws Exception {
```
Comment (shiveshr) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: dont you want to catch exceptions while cleaning up and react to them accordingly.

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done.
