### PR TITLE
Issue 3164: Remove redundant handleException invocation.

### LINKED ISSUE #3164: Log spam when performing conditional appends
**Problem description**
When a conditional attribute update fails it logs at ERROR level. Example:
```
ERROR i.p.s.s.h.h.PravegaRequestProcessor - [requestId=1075] Error (Segment = 'longevity/_RGlongevitysmallScaleforgetful0/0.#epoch.0', Operation = 'updateSegmentAttribute')
io.pravega.segmentstore.contracts.BadAttributeUpdateException: [Segment 'longevity/_RGlongevitysmallScaleforgetful0/0.#epoch.0'] Bad Attribute Update (AttributeId = 7df9a874-246c-c9d6-9397-cdd19ead68c5, Value = 1054480, UpdateType = ReplaceIfEquals): Expected existing value to be '-9223372036854775808', actual '557151'..
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessAttributes(SegmentMetadataUpdateTransaction.java:429)
        at io.pravega.segmentstore.server.logs.SegmentMetadataUpdateTransaction.preProcessOperation(SegmentMetadataUpdateTransaction.java:274)
        at io.pravega.segmentstore.server.logs.ContainerMetadataUpdateTransaction.preProcessOperation(ContainerMetadataUpdateTransaction.java:321)
        at io.pravega.segmentstore.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:224)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperation(OperationProcessor.java:364)
        at io.pravega.segmentstore.server.logs.OperationProcessor.processOperations(OperationProcessor.java:283)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Problem location**
SegmentStore

**Suggestions for an improvement**
Log at debug without the stack trace.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Ensure Conditional attribute update failure is not logged at ERROR level.

**Purpose of the change**  
Fixes #3164 

**What the code does**  
The method `io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor#updateSegmentAttribute` used to invoke `handleException()` twice , once via `whenComplete(..)` and once via `exceptionally(...)` block.
This additional invocation of `handleException()` has been removed.
This change also ensures that the log spam during conditional appends is removed.

**How to verify it**  
No changes to functionality, all the existing tests should continue to pass.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 1]
```diff
@@ -323,20 +323,19 @@ public void updateSegmentAttribute(UpdateSegmentAttribute updateSegmentAttribute
...
-                        if (Exceptions.unwrap(e) instanceof BadAttributeUpdateException) {
-                            log.debug("Updating segment attribute {} failed due to: {}", update, e.getMessage());
-                            connection.send(new SegmentAttributeUpdated(requestId, false));
+                    .whenComplete((v, e) -> {
+                        LoggerHelpers.traceLeave(log, operation, trace, e);
+                        if (e == null) {
+                            connection.send(new SegmentAttributeUpdated(requestId, true));
                         } else {
-                            handleException(requestId, segmentName, operation, e);
+                            if (Exceptions.unwrap(e) instanceof BadAttributeUpdateException) {
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: The point of the second "redundant" `handleException` is to make sure that the code in `whenComplete` doesn't throw any exceptions itself, thus leaving the connection hanging.

I recommend you put the contents of the `whenComplete` in a `try-catch` block and use `handleException` in the `catch`.

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: The only place inside `whenComplete` where exceptions could be thrown is the `connection.send()`, which is because the connection is not present. 
I have updated the code to use the pattern`.thenAccept(..).exceptionally(...)`. Let me know if this is better.

**Comment by shrids** [comment]
[Issue 3164: Remove redundant handleException invocation](https://trello.com/c/saCHA6jE/61-issue-3164-remove-redundant-handleexception-invocation)

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 2]
```diff
@@ -323,20 +323,19 @@ public void updateSegmentAttribute(UpdateSegmentAttribute updateSegmentAttribute
...
                             log.debug("Updating segment attribute {} failed due to: {}", update, e.getMessage());
                             connection.send(new SegmentAttributeUpdated(requestId, false));
                         } else {
                             handleException(requestId, segmentName, operation, e);
                         }
-                    }
-                })
-                .exceptionally(e -> handleException(requestId, segmentName, operation, e));
+                        return null;
+                    });
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Previously if the connection.send threw an exception handleException would be invoked. This is no longer the case in the new version.

Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: updated the code to have a try catch within the `whenComplete` block.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Updated the code with a `try-catch` block inside `whenComplete`.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 3]
```diff
@@ -323,20 +327,23 @@ public void updateSegmentAttribute(UpdateSegmentAttribute updateSegmentAttribute
...
+                            if (Exceptions.unwrap(e) instanceof BadAttributeUpdateException) {
+                                log.debug("Updating segment attribute {} failed due to: {}", update, e.getMessage());
+                                invokeSafely(connection::send, new SegmentAttributeUpdated(requestId, false), failureHandler);
+                            } else {
+                                handleException(requestId, segmentName, operation, e);
+                            }
                         }
-                    }
-                })
-                .exceptionally(e -> handleException(requestId, segmentName, operation, e));
```
Comment (shrids) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: `exceptionally` statement has been removed since it will not be invoked if there is an exception thrown during the execution of `whenComplete` method. Also, an exception thrown by ` segmentStore.updateAttributes` would cause both the `whenComplete` and `exceptionally` blocks to be executed.
