### PR TITLE
Issue 1477: Async read retries

### LINKED ISSUE #1477: Readers sometimes ignore timeouts on readNextEvent
**Problem description**
If during a call to EventStreamReader.readNextEvent() the connection fails, the timeout will be ignored and the request will block until the read is complete.

**Problem location**
SegmentInputStreamImpl

**Suggestions for an improvement**
Utilize the background threadpool to do reads rather than relying on the ReadFuture mechanism.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
Change read requests to use the threadPool for retries rather than relying on the caller's thread.

**Purpose of the change**
Fixes #1477

**What the code does**
Switches from using a ReadFuture to a standard completablefuture. This simplifies the calling code and lets the connection library be explicit about failures on send.

**How to verify it**
Some of the unit tests needed changes to verify the new behaviour. All pass.

### CODE REVIEW

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java [hunk 1]
```diff
@@ -183,12 +183,11 @@
      * @param <ResultT>            Type of the result.
      * @param <ExceptionT>         Type of the Exception.
      * @throws ExceptionT       If thrown by the future.
-     * @throws TimeoutException If the timeout expired prior to the future completing.
-     * @return The result of calling future.get().
+     * @return The result of calling future.get() or null if the timeout expired prior to the future completing.
      */
     @SneakyThrows(InterruptedException.class)
     public static <ResultT, ExceptionT extends Exception> ResultT getAndHandleExceptions(Future<ResultT> future,
-                                                                                         Function<Throwable, ExceptionT> exceptionConstructor, long timeoutMillis) throws TimeoutException, ExceptionT {
```
Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: The only caller of this version of the method is in SegmentInputStreamImpl.readEventData()

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java [hunk 2]
```diff
@@ -177,22 +128,26 @@ public void close() {
...
+    public CompletableFuture<SegmentRead> read(long offset, int length) {
         Exceptions.checkNotClosed(closed.get(), this);
         WireCommands.ReadSegment request = new WireCommands.ReadSegment(segmentId.getScopedName(), offset, length);
-        
-        ReadFutureImpl read = new ReadFutureImpl(request);
+
+        return backoffSchedule.retryingOn(ConnectionFailedException.class)
+                              .throwingOn(ConnectionClosedException.class)
+                              .runAsync(() -> {
+                                  return getConnection().thenCompose(c -> sendRequestOverConnection(request, c));
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: If `getConnection() `fails then we need to convert the exception to `ConnectionFailedException`, so that retry kicks in.

Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: I think `getConnection` could also fail due to an error accessing the controller to get the end point. What happens in that case, is it a connection failed in this case?

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java [hunk 3]
```diff
@@ -177,22 +128,26 @@ public void close() {
...
         }
-        getConnection().thenAccept((ClientConnection c) -> {
-            log.debug("Sending read request {}", read);
-            c.sendAsync(read.request);
-        }).exceptionally(e -> {
-            read.completeExceptionally(new CompletionException(e));
-            return null;
-        });
-        return read;
+        log.debug("Sending read request {}", request);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java]: This feels more like tracing than debugging.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 4]
```diff
@@ -95,55 +98,60 @@ public long getOffset() {
...
         } finally {
             if (!success) {
+                outstandingRequest = null;
                 offset = originalOffset;
                 buffer.clear();
             }
         }
     }
 
+    private ByteBuffer readEventData(long timeout) throws EndOfSegmentException {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: I didn't compare line by line here, but it feels like you are just moving code around for organization purposes, is that right?

File: client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java [hunk 5]
```diff
@@ -40,20 +47,30 @@ public void testRetry() throws ConnectionFailedException {
...
-        assertFalse(readFuture.isSuccess());
+        
         WireCommands.SegmentRead segmentRead = new WireCommands.SegmentRead(segment.getScopedName(), 1234, false, false, ByteBuffer.allocate(0));
-        WireCommands.SegmentRead result = Async.testBlocking(() -> in.getResult(readFuture), () -> {
-            processor.segmentRead(segmentRead);
-        });
-        verify(c).send(new WireCommands.ReadSegment(segment.getScopedName(), 1234, 5678));
-        assertTrue(readFuture.isSuccess());
-        assertEquals(segmentRead, result);
+        Mockito.doAnswer(new Answer<Void>() {
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java]: Do you want to do one with connection closed as well?

**Comment by Prabha-Veerubhotla** [comment]
I have run the system tests with the changes in this PR. In the logs of MultiReaderWriterWithFailoverTest case, 
I couldnt see the reads happening. 
There are no reads happening, i can just the logs `reading event ` but no increase in read count .So reads are not happening right from the setup `Test with  2 controller, SSS instances running and without a failover scenario
2017-07-07 12:14:04,788 5196 [pool 5-thread-9] INFO  i.p.t.s.MultiReaderWriterWithFailOverTest - Read count 0 and write count 5`. I can see the connection failed exception many times .`Closing connection with exception: io.pravega.shared.protocol.netty.ConnectionFailedException`

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java (hunk 4 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Yes, the only functional change is that the while loop that used to be at the top outside of the try is now included in the try.

**Comment by tkaitchuck** [comment]
@Prabha-Veerubhotla I think you are mis-reading those logs. I see entries like:
> 2017-07-07 12:14:05,165 5573 [pool-5-thread-7] DEBUG i.p.t.s.MultiReaderWriterWithFailOverTest - Reading event 14
> 2017-07-07 12:14:05,165 5573 [pool-5-thread-7] DEBUG i.p.t.s.MultiReaderWriterWithFailOverTest - Event read count 14

Which clearly indicates that reads are happening. During the particular run of the test 46 events are written and all 46 are read.
The line you saw 
> Read count 0 and write count 5

Is logged immediately after triggering the readers to start in background threads, with no delay, so it shouldn't be surprising that no reads occurred before that point. The test run ultimately fails, but due to exception from when the controller is taken offline. But that has nothing to do with this PR.

**Comment by Prabha-Veerubhotla** [comment]
Yes, you are right @tkaitchuck . The writes/reads stopped far later as discussed offline. Sorry, for the confusion.

File: client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java (hunk 5 above)
Comment (tkaitchuck) [inline client/src/test/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamTest.java]: done
