### PR TITLE
Issue 6653: Pravega-Admin CLI controller describe-stream throws Exception accessing the metadata store

### LINKED ISSUE #6653: Pravega-Admin CLI : controller describe-stream throws Exception accessing the metadata store
Using cli command to describe existing stream in Pravega-Admin CLI , gives below error:
 

> controller describe-stream testingScopeCreation3 stream3 Exception accessing the metadata store: java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$StoreConnectionException: get entry: key: testingScopeCreation3 table: _system/_tables/scopes

Here,

testingScopeCreation3 -> scope name

stream3 -> stream name

 

scope testingScopeCreation3 created using the POST:

 

root@ubuntu2004:~# kubectl exec pravega-pravega-segment-store-0 -- curl -u POST "http://10.243.41.54:10080/v1/scopes" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"scopeName\": \"testingScopeCreation3\" }" -w %{http_code}
Enter host password for user 'POST':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    77  100    37  100    40    211    228 --:--:-- --:--:-- --:--:--   442{"scopeName":"testingScopeCreation3"}

stream stream3 is created in the scope testingScopeCreation3:

 

 

curl -s -X POST 'http://10.243.41.54:10080/v1/scopes/testingScopeCreation3/streams' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{
> "streamName": "stream3",
> "scalingPolicy": {
> "type": "BY_RATE_IN_EVENTS_PER_SEC",
> "targetRate": 1,
> "scaleFactor": 1,
> "minSegments": 1
> },
> "retentionPolicy": {
> "type": "LIMITED_DAYS",
> "value": 0
> }
> }'
{"scopeName":"testingScopeCreation3","streamName":"stream3","scalingPolicy":{"type":"BY_RATE_IN_EVENTS_PER_SEC","targetRate":1,"scaleFactor":1,"minSegments":1},"retentionPolicy":{"type":"LIMITED_DAYS","value":0,"timeBasedRetention":{"days":0,"hours":0,"minutes":0}},"tags":[],"timestampAggregationTimeout":0,"rolloverSizeBytes":0}

Displaying the stream stream3 using the GET:

 

 

root@ubuntu2004:~# curl -s GET 'http://10.243.41.54:10080/v1/scopes/testingScopeCreation3/streams'
{"streams":[{"scopeName":"testingScopeCreation3","streamName":"stream3","scalingPolicy":{"type":"BY_RATE_IN_EVENTS_PER_SEC","targetRate":1,"scaleFactor":1,"minSegments":1},"retentionPolicy":{"type":"LIMITED_DAYS","value":0,"timeBasedRetention":{"days":0,"hours":0,"minutes":0}},"tags":[],"timestampAggregationTimeout":0,"rolloverSizeBytes":0}]}

 

Steps to reproduce: 

    Enter the specific pod where the pravega-Admin CLI is copied ,here it is bookkeeper:

                kubectl exec -it bookkeeper-bookie-1 – /bin/sh

    Go to the path where it is copied -> cd /krupa/pravega-0.11.0
    Run  ./bin/pravega-admin   to launch CLI.
    Perform following commands in the CLI:
        > controller list-scopes    //Lists the scopes in the system
        > controller list-streams testingScopeCreation3  //lists streams in given scope
        > controller describe-stream testingScopeCreation3 stream3,  
            Expectation : Should get the details of given stream.
            Actual : Throws Exception accessing the metadata store: java.util.concurrent.CompletionException:

 

NOTE : Same issue is seen in a system with Authentication_enabled as well.

### PR DESCRIPTION
**Pull request by kuldeepk3**
**Change log description**  
Updated controller describe-stream command to use rest api to fetch the required details.

**Purpose of the change**  
Fixes #6653

**What the code does**  
Changes to use rest api for getting stream details.

**How to verify it**  
Admin-cli command `controller describe-stream <scope-name> <stream-name>` can be used to verify the same

### CODE REVIEW

**Review by RaulGracia — CHANGES_REQUESTED** [review]

File: cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java [hunk 1]
```diff
@@ -130,44 +123,6 @@ public void testDescribeReaderGroupCommand() {
...
-        Properties properties = new Properties();
-        properties.setProperty("cli.store.metadata.backend", CLIConfig.MetadataBackends.ZOOKEEPER.name());
-        cliConfig().getConfigBuilder().include(properties);
-        commandArgs = new CommandArgs(Arrays.asList(scope, testStream), cliConfig());
-        new ControllerDescribeStreamCommand(commandArgs).execute();
-        properties.setProperty("cli.store.metadata.backend", CLIConfig.MetadataBackends.SEGMENTSTORE.name());
-        cliConfig().getConfigBuilder().include(properties);
-    }
-
     static String executeCommand(String inputCommand, AdminCommandState state) throws Exception {
```
Comment (anirudhkovuru) [inline cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java:126]: You can remove these methods and classes since they were only used for the old test. The `executeCommand` method and the `TestingDescribeStreamCommand`.

File: cli/admin/src/test/java/io/pravega/cli/admin/controller/SecureControllerCommandsTest.java [hunk 2]
```diff
@@ -70,7 +70,7 @@
         boolean isStreamCreated = streamManager.createStream(scope, testStream, StreamConfiguration.builder()
                 .scalingPolicy(ScalingPolicy.fixed(1))
                 .build());
-
+
```
Comment (anirudhkovuru) [inline cli/admin/src/test/java/io/pravega/cli/admin/controller/SecureControllerCommandsTest.java:73]: nit: remove the blank space

**Review by anirudhkovuru — CHANGES_REQUESTED** [review]

File: cli/admin/src/main/java/io/pravega/cli/admin/controller/ControllerDescribeStreamCommand.java [hunk 3]
```diff
@@ -53,65 +39,10 @@ public void execute() {
...
-                segmentHelper.close();
-                store.close();
-            }
-        } catch (Exception e) {
-            System.err.println("Exception accessing the metadata store: " + e.getMessage());
-        }
+        @Cleanup
+        val context = createContext();
+        // Print the response sent by the Controller.
+        prettyJSONOutput(executeRESTCall(context, "/v1/scopes/" + getCommandArgs().getArgs().get(1) + "/streams/" + getCommandArgs().getArgs().get(0)));
```
[the remark this answers is not in the document]
Comment (kuldeepk3) [reply cli/admin/src/main/java/io/pravega/cli/admin/controller/ControllerDescribeStreamCommand.java]: added the required test

File: cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java (hunk 1 above)
Comment (kuldeepk3) [reply cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java]: removed unused util methods

File: cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java [hunk 4]
```diff
@@ -15,58 +15,20 @@
...
-import java.util.Set;
-import java.util.stream.Collectors;
-import java.util.stream.IntStream;
-
-import static io.pravega.cli.admin.utils.TestUtils.createAdminCLIConfig;
-import static io.pravega.cli.admin.utils.TestUtils.createPravegaCluster;
-import static io.pravega.cli.admin.utils.TestUtils.getCLIControllerRestUri;
-import static io.pravega.cli.admin.utils.TestUtils.getCLIControllerUri;
-import static io.pravega.cli.admin.utils.TestUtils.prepareValidClientConfig;
+import static io.pravega.cli.admin.utils.TestUtils.*;
```
Comment (RaulGracia) [inline cli/admin/src/test/java/io/pravega/cli/admin/controller/ControllerCommandsTest.java:31]: Use single class imports.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Looks like the coverage check is not passing, and you see in Codecov what is missing to cover by tests?

**Review by RaulGracia — APPROVED** [review]
LGTM (assuming this has been tested on a real cluster).
