### PR TITLE
Issue 6732: Unexpected Pravega pod restarted in system tests

### LINKED ISSUE #6732: Unexpected Pravega pod restarted at test-pravega-continuous-1
**Describe the bug**
This issue is causing systems test cases to fail and it is intermittent. 

**To Reproduce**

**Screenshots**

**Additional information**
Add any other information about the problem here, including the root cause if known.

### PR DESCRIPTION
**Pull request by kuldeepk3**
Signed-off-by: Kuldeep Kumar <kuldeep.kumar3@dell.com>

**Change log description**  
There are system test failure due to `java.lang.AssertionError: Failing test due to Pravega pod restart`. This happens to different test cases at different executions.

**Purpose of the change**  
Fixes #6732 

**What the code does**  
Adding antiaffinity for segment store pod w.r.t zookeeper pod. 

**How to verify it**  
Running the system tests multiple time and verify that there are no failures due to `java.lang.AssertionError: Failing test due to Pravega pod restart` and also zookeeper pod should not restart.

### CODE REVIEW

**Comment by abhinb** [comment]
@kuldeepk3  how many consecutive runs are successful with this change? is it tested both on TPC and TPC-1?

**Comment by kuldeepk3** [comment]
Locally I ran and verified after 8-10 runs and regarding execution on TCP / TCP-1 , am planning to execute them.

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java [hunk 1]
```diff
@@ -137,6 +138,7 @@ private Map<String, Object> getPravegaOnlyDeployment(String zkLocation, int cont
                 .put("longtermStorage", tier2Spec())
                 .put("segmentStoreJVMOptions", getSegmentStoreJVMOptions())
                 .put("controllerjvmOptions", getControllerJVMOptions())
+                .put("segmentStorePodAffinity", getPodAntiAffinity())
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java:141]: If this is an anti-affinity policy for Segment Store pod only, then rename the method to express that, like `getSegmentStoreAntiAffinityPolicy()`. As all the other methods related to Segment Store.

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java [hunk 2]
```diff
@@ -161,6 +163,20 @@ private Map<String, Object> getPravegaOnlyDeployment(String zkLocation, int cont
                 .build();
     }
 
+    private Object getPodAntiAffinity() {
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java:166]: My understanding of this approach is that, during system tests, the restarts of Segment Store pods make sometimes Zookeeper pods to get evicted to get enough resources and this causes unexpected restarts that are marked as test failures. With this policy, the idea is to prevent as much as possible this situation to happen, right? Have you monitored the location of Segment Store and Zookeeper pods to check up to which point this policy is enforced?

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java (hunk 1 above)
Comment (kuldeepk3) [reply test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/AbstractService.java:139]: sure will rename it.

**Review by RaulGracia — APPROVED** [review]
