### PR TITLE
Issue 2670: Reset state conditionally

### LINKED ISSUE #2670: Stream State in controller metadata can fail to reset in Truncate or Update Workflows
**Problem description**
Workflows on Controller follow a pattern where they will update a workflow specific metadata followed by setting the state to indicate the processing it is going to perform on the updated metadata. 
The metadata update acts as a barrier for accepting only one request of a particular type at any point in time. And state is a barrier used to ensure only one processing happens at any point in time. 

After completing the processing, the metadata state is changed to allow it to accept newer requests. Followed by state being reset to `ACTIVE` so that any other workflow an be performed. 
All this processing is idempotent accept for two workflows (TRUNCATION and UPDATE_CONFIGURATION) where if controller crashes after having reset the metadata but not having reset the state, we can be left with either TRUNCATING or UPDATING states. These should be reset correctly. 
 

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**
There is a bug in TruncateStreamTask and UpdateStreamTask where, upon completion of processing, if we fail before resetting the state, when the processing is retried it will find that the work is already complete and it exits. It should also check and reset the state conditionally in such scenarios. (Note: we already handle this situation correctly for scale. but it is not handled in update and truncate stream tasks).

**Purpose of the change**
Fixes #2670 

**What the code does**
In UpdateStreamTask and TruncateStreamTask we should never have the state set to UPDATING or TRUNCATING if the corresponding records are not in updating states. 
We can reach such situations if, in previous attempt to process the event, we update the metadata record but crashed before resetting the state. The event's processing will be retried and if we encounter stream state to refer to a processing but the work is already complete, then we should reset the state. 

**How to verify it**
Unit tests added

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java [hunk 1]
```diff
@@ -61,7 +61,11 @@ public TruncateStreamTask(final StreamMetadataTasks streamMetadataTasks,
         return streamMetadataStore.getTruncationRecord(scope, stream, true, context, executor)
                 .thenCompose(property -> {
                     if (!property.isUpdating()) {
-                        throw new TaskExceptions.StartException("Truncate Stream not started yet.");
+                        // if the state is TRUNCATING but the truncation record is not updating, we should reset the state to ACTIVE.
+                        return streamMetadataStore.resetStateConditionally(scope, stream, State.TRUNCATING, context, executor)
+                                .thenApply(x -> {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java]: x is not used. You can invoke thenRun()

File: controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java [hunk 2]
```diff
@@ -61,7 +61,11 @@ public TruncateStreamTask(final StreamMetadataTasks streamMetadataTasks,
         return streamMetadataStore.getTruncationRecord(scope, stream, true, context, executor)
                 .thenCompose(property -> {
                     if (!property.isUpdating()) {
-                        throw new TaskExceptions.StartException("Truncate Stream not started yet.");
+                        // if the state is TRUNCATING but the truncation record is not updating, we should reset the state to ACTIVE.
+                        return streamMetadataStore.resetStateConditionally(scope, stream, State.TRUNCATING, context, executor)
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java]: A couple of clarification questions:
1- This seems to be some form of rolling forward. To roll forward, we must be absolutely sure that this is the only possible state transition, otherwise we risk having an inconsistent state. Can you convince me that this is the only possible state transition at this point.

2- In the description of the PR, you say that this is already addressed for scaling operations. However, looking at `ScaleOperationTask`, I don't see the same pattern. Maybe that's ok, but I'd like to understand why.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/server/eventProcessor/requesthandlers/TruncateStreamTask.java]: >  1- This seems to be some form of rolling forward. To roll forward, we must be absolutely sure that this is the only possible state transition, otherwise we risk having an inconsistent state. Can you convince me that this is the only possible state transition at this point.

for each type of processing we do things in following way:
1. set some metadata barrier specific to the type of processing
2. set state to identify the processing
3. process
4. remove metadata barrier
5. reset state to active

`1` can be done by manual call (for example manual scale and manual truncation apis) or by some background system processing.

If we ever find "state" without its corresponding metadata barrier, it means the processing was already completed.  So we can reset the state. 
For example, if the state is SCALING but there is no epochTransitionRecord, it means scaling completed and we can reset the state to ACTIVE. 
Similarly, if the state is TRUNCATING but the truncationRecord's updating flag is false, it means previous truncation completed and we can reset the state to ACTIVE. 

The method `resetStateConditionally` checks if the state is "desired state" then only reset it to ACTIVE. 

> 2- In the description of the PR, you say that this is already addressed for scaling operations. However, looking at ScaleOperationTask, I don't see the same pattern. Maybe that's ok, but I'd like to understand why.
The same thing for scale is done in PersistentStreamBase.createNewSegments where we fetch epochTransition and if it is null but the state is SCALING, we reset it to ACTIVE
