### PR TITLE
Issue 2534: Fixing the issues in MultiController system test

### LINKED ISSUE #2534: Test failure due to incorrect controller URI in Segment Store.
**Problem description**
*Observations*: ( Stream Name: testAutoScale2021607227/testTxnScaleUpWithRead)

1. Scale event from AutoScaleProcessor in SSS.
```
vagrant@INENSHRIDSL5C:/mnt/c/Sandeep/logs/archive-1062/archive/results/logs$ grep -r "sending request for scale" | grep "testAutoScale2021607227/testTxnScaleUpWithRead"                               
scrambler-slave-5-container-1/segmentstore_2018-04-24.364.log:2018-04-24 21:03:58,569 6103723 [core-22] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0
scrambler-slave-5-container-1/segmentstore_2018-04-24.368.log:2018-04-24 21:04:38,570 6143724 [cache-maintenance-0] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale down for testAutoScale2021607227/testTxnScaleUpWithRead/0
```

2. The writer(`id: 09986380-7a3f-43c0-9710-ce6738688d0f`) is not able to write events to `_system/_requeststream`.
```
2018-04-24 21:03:58,569 6103723 [core-22] DEBUG i.p.s.s.h.stat.AutoScaleProcessor - cool down period elapsed for testAutoScale2021607227/testTxnScaleUpWithRead/0
2018-04-24 21:03:58,569 6103723 [core-22] DEBUG i.p.s.s.h.stat.AutoScaleProcessor - triggering scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0 with number of splits 100
2018-04-24 21:03:58,569 6103723 [core-22] INFO  i.p.s.s.h.stat.AutoScaleProcessor - sending request for scale up for testAutoScale2021607227/testTxnScaleUpWithRead/0
2018-04-24 21:03:58,573 6103727 [core-22] DEBUG i.p.c.s.i.SegmentOutputStreamImpl - (Re)connect invoked, Segment: _system/_requeststream/0, writerID: 09986380-7a3f-43c0-9710-ce6738688d0f
```

3.
The getEndpointForSegment call fails as with GRPC error `UNAVAILABLE`.
```
2018-04-24 21:03:33,730 6078884 [clientInternal-3] INFO  i.p.c.s.i.SegmentOutputStreamImpl - Fetching endpoint for segment _system/_requeststream/0, writerID: 09986380-7a3f-43c0-9710-ce6738688d0f
2018-04-24 21:03:33,732 6078886 [grpc-default-executor-12] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call failed with server error: UNAVAILABLE```
```Retries fail to connect to Controller.
2018-04-24 21:05:04,925 6170079 [grpc-default-executor-12] WARN  i.p.c.stream.impl.ControllerImpl - getEndpointForSegment failed:
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 172.16.18.23/172.16.18.23:9092
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) 
```
```2018-04-24 21:05:04,925 6170079 [grpc-default-executor-12] WARN  i.p.c.s.i.SegmentOutputStreamImpl - 09986380-7a3f-43c0-9710-ce6738688d0f Failed to connect:
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE 
```

**Problem location**
To be investigated.
(Why is Segment store configured with a non -existent controller?)

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
Signed-off-by: PrabhaVeerubhotla <vvlprabha@gmail.com>

**Change log description**

Multicontroller test is unique in its way that it brings all the controller instances to zero and checks for `RetriesExhaustedException` trying to create a scope. 
When this last controller instance is brought down, the segment store which is running has the incorrect controller URI and cause the next test to fail, unable to resolve the controller URI.

Also, due to unintentional changes with #2432, the test does not use `pravega://` controller URI to test the controller functionality.
 
**Purpose of the change**
Fixes #2534 

**What the code does**
Fixes the two issues mentioned in the issue :
*   Use a diff. service name `multicontroller` for multicontroller test. 
*    Few changes in pravegacontrollerdocker service to accommodate controller with new service name 
in multicontrollertest
*    As the resources are not  enough to have 4 controller instances running at a time, start the test with 
2 rather than 3 controller instances. 
 *   Test the discover based controller uris (with pattern "pravega://" ) by using appropriate controlleclient instance.

Changes:  
  *  Creates a new method which can use `service name` as a parameter to create the marathon/docker instance. Modifies the already existing one to use the  new method.
*    Creates  multicontroller instance on different controller and rest ports when deploying via docker swarm.
  *  In multicontroller test,  creates two controllerimpl instances  , one using `tcp://` controller uri and other with `pravega://` controller uri , pass them appropriately when creating scope. 

**How to verify it**
The tests should pass.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 1]
```diff
@@ -46,7 +46,9 @@
     private static final ScheduledExecutorService EXECUTOR_SERVICE = Executors.newSingleThreadScheduledExecutor();
 
     private Service controllerService1 = null;
-    private ControllerImpl controllerClient = null;
+    private Service segmentStoreService = null;
+    private ControllerImpl controllerClientDirect = null;
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Why is this not using an atomic reference like the URI counterpart?

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 2]
```diff
@@ -98,24 +108,34 @@ public void getControllerInfo() {
...
+                .build(),
+                EXECUTOR_SERVICE);
+        controllerClientDiscover = new ControllerImpl(ControllerImplConfig.builder()
+                .clientConfig(ClientConfig.builder()
+                        .controllerURI(controllerURIDiscover.get())
+                        .build())
+                .build(),
+                EXECUTOR_SERVICE);
+
+        segmentStoreService = Utils.createPravegaSegmentStoreService(zkUris.get(0), controllerURIDirect.get());
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Why do we have `segService` and `segmentStoreService`? Why do we need both? Sounds like we are creating a segment store twice in this test case.

Also, this method is about getting a controller info, so it is unclear why it should be creating a segment store instance here.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 3]
```diff
@@ -98,24 +108,34 @@ public void getControllerInfo() {
...
+        log.debug("Pravega host service details: {}", segmentStoreService.getServiceDetails());
+
     }
 
     @After
-    public void tearDown() {
+    public void tearDown() throws ExecutionException {
         ExecutorServiceHelpers.shutdown(EXECUTOR_SERVICE);
         if (controllerService1 != null && controllerService1.isRunning()) {
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: If the test explicitly kills all the instances of the controller in `multiControllerTest`, are the lines inside the `if` block going to be executed ever? This impacts on whether clients are closed or not.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 4]
```diff
@@ -72,6 +74,14 @@ public static void setup() throws MarathonException, ExecutionException {
         final List<String> uris = conUris.stream().filter(uri -> DOCKER_BASED ? uri.getPort() == Utils.DOCKER_CONTROLLER_PORT
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Empty line needed before previous comment line.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 5]
```diff
@@ -160,30 +180,30 @@ public void multiControllerTest() throws ExecutionException, InterruptedExceptio
...
+                controllerClientDirect.createScope("scope" + RandomStringUtils.randomAlphanumeric(10)),
                 throwable -> throwable instanceof RetriesExhaustedException);
         if (!DOCKER_BASED) {
             log.info("Test pravega:// with no controller instances running");
             AssertExtensions.assertThrows("Should throw RetriesExhaustedException",
-                    controllerClient.createScope("scope" + RandomStringUtils.randomAlphanumeric(10)),
+                    controllerClientDiscover.createScope("scope" + RandomStringUtils.randomAlphanumeric(10)),
                     throwable -> throwable instanceof RetriesExhaustedException);
         }
         log.info("multiControllerTest execution completed");
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Empty line needed after closing code block.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: using it now.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 2 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: This was mainly to fetch the running segment store instance and kill it, now that we are using a different service name `multi-controller` , we no longer need this part of the code.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 3 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: using atomic reference for controller client, and removed the earlier line from the if block.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 4 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: not using this code anymore.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 5 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: added.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 6]
```diff
@@ -81,7 +79,7 @@ public void getControllerInfo() {
         List<URI> zkUris = zkService.getServiceDetails();
         log.info("zookeeper service details: {}", zkUris);
 
-        controllerService1 = Utils.createPravegaControllerService(zkUris.get(0));
+        controllerService1 = Utils.createPravegaControllerService("multicontroller", zkUris.get(0));
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Could we rename this variable as `controllerService`?

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 7]
```diff
@@ -160,30 +157,31 @@ public void multiControllerTest() throws ExecutionException, InterruptedExceptio
...
     private void withControllerURIDiscover() throws ExecutionException, InterruptedException {
         if (!DOCKER_BASED) {
             Assert.assertTrue(createScopeWithSimpleRetry(
-                    "scope" + RandomStringUtils.randomAlphanumeric(10), controllerURIDiscover.get()).get());
+                    "scope" + RandomStringUtils.randomAlphanumeric(10), controllerClientDiscover.get()).get());
         }
     }
 
-    CompletableFuture<Boolean> createScopeWithSimpleRetry(String scopeName, URI controllerURI) {
+    CompletableFuture<Boolean> createScopeWithSimpleRetry(String scopeName, ControllerImpl controllerClient) {
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Passing URI (similar to the previous version : https://git.io/vpgre) and creating controller client is better since,
a. We can test how the client behaves with changed controller instance count.
b. The intent of the last part of the test with controller instance count as 0 is to verify that if all the controllers are down then the pravega:// uri scheme will not be able to fetch the controller. But in this case since we are using the client which is already created it will contact the already running controller(with service id "controller")

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 6 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java (hunk 7 above)
Comment (Prabha-Veerubhotla) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: changed back to creating client every time we scale the controller instances.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 8]
```diff
@@ -181,13 +162,23 @@ private void withControllerURIDiscover() throws ExecutionException, InterruptedE
...
         // Need to retry since there is a delay for the mesos DNS name to resolve correctly.
         return Retry.withExpBackoff(500, 2, 10, 5000)
                 .retryingOn(Exception.class)
                 .throwingOn(IllegalArgumentException.class)
-                .runAsync(() -> controllerClient.createScope(scopeName), EXECUTOR_SERVICE);
+                .runAsync(() -> createScope(scopeName, controllerURI), EXECUTOR_SERVICE);
+    }
+
+    private CompletableFuture<Boolean> createScope(String scopeName, URI controllerURI) {
+        final ControllerImpl controllerClient = new ControllerImpl(ControllerImplConfig.builder()
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: we should close the client finally.

**Comment by RaulGracia** [comment]
[Fix system test build (scaleTestsWithReader failing consistently)](https://trello.com/c/2lGk7O8o/18-fix-system-test-build-scaletestswithreader-failing-consistently)

**Comment by RaulGracia** [comment]
[Fix system test build (scaleTestsWithReader failing consistently)](https://trello.com/c/2lGk7O8o/18-fix-system-test-build-scaletestswithreader-failing-consistently)

**Comment by RaulGracia** [comment]
[Fix system test build (scaleTestsWithReader failing consistently)](https://trello.com/c/2lGk7O8o/18-fix-system-test-build-scaletestswithreader-failing-consistently)
