### PR TITLE
Issue #3624: Fix backward compatibility issue with WireCommands.

### LINKED ISSUE #3624: Observing "Exception: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock" error in Segmentstore while running IO
**Observing "Exception: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock" error in Segmentstore while running IO**

**Environment details: PKS / K8 with medium cluster:**
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: 0.5.0-2210.81867f3
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: adrianmo/pravega-operator:0.3.2
```
**Segmentstore log error:**
```
2019-04-12 08:18:34,438 10687508 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: b3bf83dd-7262-49d3-9b8b-b2f30947ae18 on segment: longevity/smash/47.#epoch.27
2019-04-12 08:18:34,539 10687609 [epollEventLoopGroup-11-1] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
        at io.pravega.shared.protocol.netty.AppendDecoder.processCommand(AppendDecoder.java:102)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:55)
        at io.pravega.shared.protocol.netty.AppendDecoder.decode(AppendDecoder.java:36)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 28 common frames omitted
```

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**  
* Remove unneeded requestId on AppendBlock.

**Purpose of the change**  
Fixes #3624

**What the code does**  
In #3562 a requestId was added to each wire command so that replies could be associated with the appropriate command. This was not strictly necessary (but should have been harmless) for AppendBlock as it gets combined with AppendBlockEnd before being processed and is never replied to individually. The problem was that the logic which was intended to check for the presence of the new field would incorrectly always detect it's presence. This meant that using an older client with a newer server would fail as soon as an append was attempted. This change removes the unneeded field altogether. This returns AppendBlock to it's original format.

### CODE REVIEW

**Comment by fpj** [comment]
If you have retriggered, then it apparently failed again, and if so, I'm not convinced this is a coincidence.

```
io.pravega.local.TlsEnabledInProcPravegaClusterTest > testWriteAndReadEventWhenConfigurationIsProper FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 50000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.local.TlsEnabledInProcPravegaClusterTest.testWriteAndReadEventWhenConfigurationIsProper(TlsEnabledInProcPravegaClusterTest.java:96)
```

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 1]
```diff
@@ -524,34 +524,29 @@ public static WireCommand readFrom(DataInput in, int length) throws IOException
...
             out.writeLong(writerId.getLeastSignificantBits());
-            out.writeLong(requestId);
             // Data not written, as it should be null.
         }
 
         public static WireCommand readFrom(ByteBufInputStream in, int length) throws IOException {
             UUID writerId = new UUID(in.readLong(), in.readLong());
-            byte[] data = new byte[length - Long.BYTES * 3];
-            long requestId = (in.available() >= Long.BYTES) ? in.readLong() : -1L;
+            byte[] data = new byte[length - Long.SIZE * 2];
```
Comment (shrids) [inline shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: This should be changed to 
```
byte[] data = new byte[length - Long.BYTES * 2];

**Comment by tkaitchuck** [comment]
> This limits our ability to identify a specific append block, though, which we may not be doing right now, but we might want to do it in the future, e.g., for debugging purposes.

The id is still in the appendBlockEnd, so we can still identify it. Its just redundant to specify it twice. That is why no code was actually using it.
