### PR TITLE
Issue1617: NullPointerExceptions from ControllerClusterListener

### LINKED ISSUE #1617: Controller logs filled with NullPointerExceptions from ControllerClusterListener
**Problem description**
The controller logs have NullPointerExceptions constantly:

```
2017-07-18 19:27:41,487 3243201 [controllerpool-31] WARN  i.p.c.f.ControllerClusterListener - java.lang.NullPointerException
2017-07-18 19:27:51,488 3253202 [controllerpool-61] WARN  i.p.c.f.ControllerClusterListener - java.lang.NullPointerException
```

I looked in `io.pravega.controller.fault.ControllerClusterListener` and added logging any exceptions in `log.warn` statements and found the stack trace to be:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.pravega.common.concurrent.FutureHelpers.lambda$delayedFuture$22(FutureHelpers.java:438)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at io.pravega.controller.fault.ControllerClusterListener.lambda$null$10(ControllerClusterListener.java:136)
	at io.pravega.common.concurrent.FutureHelpers.lambda$delayedFuture$24(FutureHelpers.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 10 common frames omitted
```

which is caused by a `sweeper` being `null` in this block of code:

```
    private CompletableFuture<Void> sweepAll(Supplier<Set<String>> processes) {
        return FutureHelpers.allOf(sweepers.stream().map(sweeper -> RetryHelper.withIndefiniteRetriesAsync(() -> {
            if (!sweeper.isReady()) {
                log.trace("sweeper not ready, retrying with exponential backoff");
                throw new RuntimeException("sweeper not ready");
            }
            return sweeper.sweepFailedProcesses(processes);
        }, e -> log.warn(e.getMessage(), e), executor)).collect(Collectors.toList()));
    }
````

The constructor of `ControllerClusterListener` takes a vararg array `final FailoverSweeper ... sweepers` which has one of the arguments being `null` which is causing this.

**Problem location**
`io.pravega.controller.server.ControllerServiceStarter` is passing in 3 FailoverSweepers, and one is `null`:
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L163
The `controllerEventProcessors` field is passed in as the first argument of this vararg and it is `null`, it is initialized later in the code (and only if certain conditions exist):
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L177

**Suggestions for an improvement**
The initialization of `controllerEventProcessors` most likely needs to be moved up before the controllerClusterListener.  There would still be a condition that can occur where it would be `null` (when `! serviceConfig.getEventProcessorConfig().isPresent()`) so the constructor of `ControllerClusterListener`'s constructor should strip out any `null` values from the list of sweepers.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
```
Caused by: java.lang.NullPointerException: null
	at io.pravega.controller.fault.ControllerClusterListener.lambda$null$10(ControllerClusterListener.java:136)
	at io.pravega.common.concurrent.FutureHelpers.lambda$delayedFuture$24(FutureHelpers.java:458)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 10 common frames omitted
```

which is caused by a sweeper being null in this block of code:

```
    private CompletableFuture<Void> sweepAll(Supplier<Set<String>> processes) {
        return FutureHelpers.allOf(sweepers.stream().map(sweeper -> RetryHelper.withIndefiniteRetriesAsync(() -> {
            if (!sweeper.isReady()) {
                log.trace("sweeper not ready, retrying with exponential backoff");
                throw new RuntimeException("sweeper not ready");
            }
            return sweeper.sweepFailedProcesses(processes);
        }, e -> log.warn(e.getMessage(), e), executor)).collect(Collectors.toList()));
    }
```
**Purpose of the change**
Fixes #1617.
io.pravega.controller.server.ControllerServiceStarter is passing in 3 FailoverSweepers, and one is null:
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L163
The controllerEventProcessors field is passed in as the first argument of this vararg and it is null, it is initialized later in the code (and only if certain conditions exist):
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L177
**What the code does**

We move creation of controller cluster listener only after all sweepers are started (which includes eventprocessors). 

**How to verify it**
added preconditions and asserts to flag the issue. All existing tests should pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 1]
```diff
@@ -47,16 +47,17 @@
     private final List<FailoverSweeper> sweepers;
 
     public ControllerClusterListener(final Host host, final Cluster cluster,
-                                     final ScheduledExecutorService executor, final FailoverSweeper... sweepers) {
+                                     final ScheduledExecutorService executor, final List<FailoverSweeper> sweepers) {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: This list could be mutable, which would cause issues if the caller changed it after the fact. Either restrict this type to ImmutableList or make a defensive copy.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 2]
```diff
@@ -184,6 +177,23 @@ protected void startUp() {
                         .thenAcceptAsync(x -> controllerEventProcessors.startAsync(), controllerExecutor);
             }
 
+            // Setup and start controller cluster listener after all sweepers have been initialized.
+            if (serviceConfig.isControllerClusterListenerEnabled()) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: I can't really assess the impact of moving this code here. Is this going to create any problem, like a cyclic dependency such as the one we had before? I'm worried that this code wasn't here before for some reason.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 3]
```diff
@@ -184,6 +177,23 @@ protected void startUp() {
...
+                cluster = new ClusterZKImpl((CuratorFramework) storeClient.getClient(), ClusterType.CONTROLLER);
+                List<FailoverSweeper> failoverSweepers = new ArrayList<>();
+                failoverSweepers.add(taskSweeper);
+                failoverSweepers.add(txnSweeper);
+                if (serviceConfig.getEventProcessorConfig().isPresent()) {
+                    assert controllerEventProcessors != null;
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: If `controllerEventProcessors` is null at this point, then the expected behavior is that the controller exits? As I understand it, the only possibility for it to be null is if `serviceConfig.getEventProcessorConfig().isPresent()` is false, is it right?

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: yes, if config is present we should have created the eventprocessor.. hence the assert.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java (hunk 2 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: there shouldnt be any.. the earlier dependency was removed by making cluster listener sweeper type agnostic.. and none of the sweepers depends on cluster listener.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 1 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: made a defensive copy

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 4]
```diff
@@ -156,16 +159,6 @@ protected void startUp() {
...
-                cluster = new ClusterZKImpl((CuratorFramework) storeClient.getClient(), ClusterType.CONTROLLER);
-                controllerClusterListener = new ControllerClusterListener(host, cluster, controllerExecutor,
-                        controllerEventProcessors, taskSweeper, txnSweeper);
-
-                log.info("Starting controller cluster listener");
-                controllerClusterListener.startAsync();
-            }
-
             controllerService = new ControllerService(streamStore, hostStore, streamMetadataTasks,
                     streamTransactionMetadataTasks, new SegmentHelper(), controllerExecutor, cluster);
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: The variable `cluster` was initialized in the above block that created `ControllerClusterListener`. Since that block is now moved below, `ControllerService` constructor is called with uninitialized `cluster`, which is problematic. Possibly, we could initialize `cluster` before creating `ControllerService`, but move the `ControllerClusterListener` creation below, as is done in this change.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java [hunk 5]
```diff
@@ -184,6 +177,23 @@ protected void startUp() {
                         .thenAcceptAsync(x -> controllerEventProcessors.startAsync(), controllerExecutor);
             }
 
+            // Setup and start controller cluster listener after all sweepers have been initialized.
+            if (serviceConfig.isControllerClusterListenerEnabled()) {
+                cluster = new ClusterZKImpl((CuratorFramework) storeClient.getClient(), ClusterType.CONTROLLER);
```
Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: This `cluster` needs to be created before creating ControllerService above at line 162-163.

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java [hunk 6]
```diff
@@ -57,7 +58,7 @@ public ControllerClusterListener(final Host host, final Cluster cluster,
         this.host = host;
         this.cluster = cluster;
         this.executor = executor;
-        this.sweepers = sweepers;
+        this.sweepers = Lists.newArrayList(sweepers);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: Did you mean to use `Collections.unmodifiableList` or perhaps Guava's `ImmutableList` here?

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java (hunk 4 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: So initializing cluster before controller service seems like the way to go.. 

```
            if (serviceConfig.isControllerClusterListenerEnabled()) {
                cluster = new ClusterZKImpl((CuratorFramework) storeClient.getClient(), ClusterType.CONTROLLER);
            }

            controllerService = new ControllerService(streamStore, hostStore, streamMetadataTasks,
                    streamTransactionMetadataTasks, new SegmentHelper(), controllerExecutor, cluster);

```

File: controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java (hunk 6 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/fault/ControllerClusterListener.java]: no, this list is internal to this class, so making it immutable is not required because we have control over what happens to this list. 
the original comment tom had was valid because we were setting reference to an externally supplied mutable list which the caller can himself modify.

File: controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java (hunk 5 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java]: done
