### PR TITLE
Issue 1375: Changes to TimeoutServiceTest.testPingFailureMaxExecutionTimeExceeded

### LINKED ISSUE #1375: TimeoutServiceTest is flakey
**Problem description**
```
io.pravega.controller.timeout.TimeoutServiceTest > testPingFailureMaxExecutionTimeExceeded FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at io.pravega.controller.timeout.TimeoutServiceTest.testPingFailureMaxExecutionTimeExceeded(TimeoutServiceTest.java:339)
```

**Problem location**
https://github.com/pravega/pravega/blob/d378b26e24383ee86cc5131a03d90bcb16b98587/controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java#L339

### PR DESCRIPTION
**Pull request by bhargav-gulavani**
**Change log description**
Existing TimeoutServiceTest.testPingFailureMaxExecutionTimeExceeded attempts to fail lease renewal by supplying a lease value to pingTxn API that exceeds maxExecutionTime by 1ms. This test fails intermittently if pingTxn API gets executed 1ms before expectation. Fixing this problem by supplying a lease value that exceeds maxExecutionTime by much more than 1ms.

**Purpose of the change**
Fixes #1375 

**What the code does**
As described above.

**How to verify it**
Test cases in TimeoutServiceTest.

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java [hunk 1]
```diff
@@ -507,11 +477,6 @@ private TxnId convert(UUID uuid) {
     }
 
     private <T> void checkError(CompletableFuture<T> future, Class<? extends Throwable> expectedException) {
-        try {
-            future.join();
-            Assert.assertTrue(false);
-        } catch (CompletionException ce) {
-            Assert.assertEquals(expectedException, ce.getCause().getClass());
-        }
+        AssertExtensions.assertThrows("Failed future", future, e -> e.getClass().equals(expectedException));
```
Comment (skrishnappa) [inline controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: We could do "e instanceOf expectedException" right?

File: controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java [hunk 2]
```diff
@@ -319,29 +319,14 @@ public void testPingFailureMaxExecutionTimeExceeded() throws InterruptedExceptio
...
-        Assert.assertEquals(PingTxnStatus.Status.OK, pingStatus.getStatus());
-
-        result = timeoutService.getTaskCompletionQueue().poll((long) (0.75 * LEASE), TimeUnit.MILLISECONDS);
-        Assert.assertNull(result);
-
-        status = streamStore.transactionStatus(SCOPE, STREAM, txData.getId(), null, executor).join();
-        Assert.assertEquals(TxnStatus.OPEN, status);
-
-        pingStatus = timeoutService.pingTxn(SCOPE, STREAM, txData.getId(), LEASE + 1);
+        PingTxnStatus pingStatus = timeoutService.pingTxn(SCOPE, STREAM, txData.getId(), 3 * LEASE);
```
Comment (skrishnappa) [inline controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: I guess we want a leave value > MAX_EXECUTION_TIME here. can make this explicit by using MAX_EXECUTION_TIME or comment that 3 * LEASE is > MAX_EXECUTION_TIME

Comment (bhargav-gulavani) [inline controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: Added a comment.

File: controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java (hunk 1 above)
Comment (bhargav-gulavani) [inline controller/src/test/java/io/pravega/controller/timeout/TimeoutServiceTest.java]: No, expectedException is only a variable of type Class, `e instanceOf expectedException` does not even compile.
