### PR TITLE
Issue 3462: Fix Segmentstore's Kubernetes bootstrapping

### LINKED ISSUE #3462: No SegmentStore docker init failure when deploying with failed services in K8s
**Problem description**
Deploying Pravega cluster with external access enabled and LoadBalancer as the service type,
I'm observing segment store servers to be in a running state when LoadBalancer services have not come up properly.

Checking the SegmentStore logs, I'm observing the following:
```
Running in a Kubernetes environment and managed by the Pravega Operator with external access enabled
Trying to obtain the external service endpoint...
Found external service endpoint: null:12345
Checking whether NFS mounting is required
```
This means that the `init_kubernetes.sh` script does not fail when `PUBLISHED_ADDRESS` variable comes back with a `null` value.

**Problem location**
SegmentStore docker init script 
https://github.com/pravega/pravega/blob/master/docker/pravega/scripts/init_kubernetes.sh

**Suggestions for an improvement**
`init_kubernetes.sh` should fail if either `PUBLISHED_ADDRESS` or `PUBLISHED_PORT` get a `null` value.

### PR DESCRIPTION
**Pull request by adrianmo**
**Change log description**  
- Replace "null" return values with "" (empty string) to consider the value as invalid and keep the process in the retry loop.
- Refactor how the external service endpoint is obtained to reduce duplicated code.

**Purpose of the change**  
Fix #3462 

**What the code does**  
Updates the `init_kubernetes.sh` file.

**How to verify it**  
@jkhalack will be able to test the change in an environment where this error can be easily reproduced. 

---
Signed-off-by: Adrián Moreno <adrian@morenomartinez.com>

### CODE REVIEW

**Comment by adrianmo** [comment]
@jkhalack I have built the Docker images from this branch to facilitate your testing:
```
adrianmo/pravega:0.5.0-2156.6adddf0-SNAPSHOT
adrianmo/bookkeeper:0.5.0-2156.6adddf0-SNAPSHOT
```
Thanks!

File: docker/pravega/scripts/init_kubernetes.sh [hunk 1]
```diff
@@ -42,29 +45,25 @@ init_kubernetes() {
...
         if [ "${service_type}" == "LoadBalancer" ]; then
-            export PUBLISHED_ADDRESS=$( k8 "${ns}" "services" "${podname}" ".status.loadBalancer.ingress[0].ip" )
-            export PUBLISHED_PORT=$( k8 "${ns}" "services" "${podname}" ".spec.ports[].port" )
             while [ -z ${PUBLISHED_ADDRESS} ] || [ -z ${PUBLISHED_PORT} ]
             do
-                echo "LoadBalancer external address and port could not be obtained. Waiting 30 seconds and trying again..."
-                sleep 30
+                echo "Trying to obtain LoadBalancer external endpoint..."
+                sleep 10
                 export PUBLISHED_ADDRESS=$( k8 "${ns}" "services" "${podname}" ".status.loadBalancer.ingress[0].ip" )
```
Comment (Tristan1900) [inline docker/pravega/scripts/init_kubernetes.sh]: Might be a problem here. When `PUBLISHED_ADDRESS` is `null`, it can still exit the while loop. Maybe we can add something like `export PUBLISTSH_ADDRESS="null"` and `[ "${PUBLISHED_ADDRESS}" != "null" ]` . What do you think?

Comment (adrianmo) [reply docker/pravega/scripts/init_kubernetes.sh]: @Tristan1900 with the changes made to the `k8` function, `PUBLISHED_ADDRESS` and `PUBLISHED_PORT` should never be "null". Am I missing something?

Comment (Tristan1900) [reply docker/pravega/scripts/init_kubernetes.sh]: Right! Sorry didn't see that.

**Comment by Tristan1900** [comment]
LGTM!

**Comment by Tristan1900** [comment]
Update for verification. 
I ran HelloWorldReader/Writer sample against this PR and it works as expected in NightShift2 and GKE. NightShift1 for some reasons cannot provide an external address so segmentstore stuck at init stage forever. I think the problem is in NightShift1 and has nothing to do with this PR.

**Comment by adrianmo** [comment]
Thanks @Tristan1900 and @jkhalack for testing the changes!

**Comment by adrianmo** [comment]
@fpj this is good to go.
