### PR TITLE
Issue 5507: Fix the atTail check in integration test testReceivingReadCall 

### LINKED ISSUE #5507: Integration test failure: io.pravega.test.integration.ReadTest.testReceivingReadCall
**Problem description**
Found this integration test failing: https://travis-ci.org/github/pravega/pravega/jobs/753908662
```
io.pravega.test.integration.ReadTest > testReceivingReadCall FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.test.integration.ReadTest.testReceivingReadCall(ReadTest.java:166)
```

**Problem location**
`ReadTest.testReceivingReadCall`

**Suggestions for an improvement**
Make the test to pass consistently.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Fix incorrect atTail assertion  in the test ReadTest > testReceivingReadCall

**Purpose of the change**  
Fixes #5507 

**What the code does**  
Fix incorrect atTail assertion  in the test ReadTest > testReceivingReadCall

**How to verify it**  
The test should cease being flaky.

### CODE REVIEW

File: test/integration/src/test/java/io/pravega/test/integration/ReadTest.java [hunk 1]
```diff
@@ -163,9 +163,14 @@ public void testReceivingReadCall() throws Exception {
             SegmentRead result = (SegmentRead) AppendTest.sendRequest(channel, new ReadSegment(segmentName, actual.writerIndex(), 10000, "", 1L));
             assertEquals(segmentName, result.getSegment());
             assertEquals(result.getOffset(), actual.writerIndex());
-            assertTrue(result.isAtTail());
             assertFalse(result.isEndOfSegment());
             actual.writeBytes(result.getData());
+            if (actual.writerIndex() < actual.capacity()) {
```
Comment (RaulGracia) [inline test/integration/src/test/java/io/pravega/test/integration/ReadTest.java:168]: Looks like you could take advantage of the `if` block below to collapse both the assertion logic and the sleep, right?

Comment (shrids) [reply test/integration/src/test/java/io/pravega/test/integration/ReadTest.java:168]: improved the code.

**Review by RaulGracia — APPROVED** [review]
