### PR TITLE
Issue 5166: In deleteScope(deleteStreams) method, handle seal stream failures

### LINKED ISSUE #5166: In deleteScope(deleteStreams) method, attempt to delete the stream even if seal fails.
**Problem description**
In the new delete scope method which attempts to list and delete the streams, we first attempt to seal followed by deleting the stream. But a seal stream can fail if a stream was partially created and is left in creating state. So we should attempt to delete the stream even if the seal fails. If the stream was in creating or sealed state, delete would succeed, otherwise it would fail, whereby failing deletescope method.  

**Problem location**
StreamManagerImpl

**Suggestions for an improvement**
Fix the issue. Throw appropriate exception.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
Handle seal stream failures in deleteScope(deleteStreams) method which would attempt to delete the stream even if seal fails. Such attempts may fail unless the stream was stuck in creating state. 

**Purpose of the change**  
Fixes #5166 

**What the code does**  
In delete scope we first attempt to seal the stream and if it fails, we handle the exception and directly proceed to delete the stream. If delete stream also fails we throw delete scope failed exception

**How to verify it**  
Unit test added

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/DeleteScopeFailedException.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.stream;
+
+/**
+ * Delete scope failed, typically because we failed to seal and delete the streams. 
+ */
+public class DeleteScopeFailedException extends RuntimeException {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/DeleteScopeFailedException.java:15]: A checked exception would make this more clear to the user right?

**Review by shrids — COMMENTED** [review]
LGTM ...

**Review by shrids — APPROVED** [review]
+1
