### PR TITLE
Issue 1200: (SegmentStore) SegmentIds are sticky throughout Container lifetime

### LINKED ISSUE #1200: (SegmentStore) Recovery fails if segment gets evicted and reactivated
**Problem description**
On restarting the segmentstore, recovery fails with the following exception. As this is happening with one of the system stream segments, controller is in unstable state:
```
017-05-04 00:29:31,622 42122 [segment-store-0] ERROR i.p.service.server.logs.DurableLog - DurableLog[2] Recovery FAILED. {}
io.pravega.service.server.DataCorruptionException: Unable to update metadata for Log Operation StreamSegmentMapOperation: SequenceNumber = 43301, Id = 43300, Name = _system/_commitStream/0, Length = 0, Sealed = false
        at io.pravega.service.server.logs.DurableLog.recoverOperation(DurableLog.java:415)
        at io.pravega.service.server.logs.DurableLog.recoverFromDataFrameLog(DurableLog.java:389)
        at io.pravega.service.server.logs.DurableLog.performRecovery(DurableLog.java:328)
        at io.pravega.service.server.logs.DurableLog.lambda$doStart$0(DurableLog.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.pravega.service.server.logs.MetadataUpdateException: [Container 2] Operation 43301 wants to map a StreamSegment Name that is already mapped in the metadata. Name = '_system/_commitStream/0', Existing Id = 1429..
        at io.pravega.service.server.logs.OperationMetadataUpdater$UpdateTransaction.preProcessMetadataOperation(OperationMetadataUpdater.java:467)
        at io.pravega.service.server.logs.OperationMetadataUpdater$UpdateTransaction.preProcessOperation(OperationMetadataUpdater.java:408)
        at io.pravega.service.server.logs.OperationMetadataUpdater.preProcessOperation(OperationMetadataUpdater.java:227)
        at io.pravega.service.server.logs.DurableLog.recoverOperation(DurableLog.java:411)
        ... 10 common frames omitted
```

**Problem location**
Possible root cause:
1. Segment X exists in metadata.
2. Metadata cleanup where Segment X gets evicted.
3. Segment X gets reactivated, with a new ID.
4. Failover. The recovery will fail because it will try to re-map the segment again.

**Suggestions for an improvement**
TBD

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
SegmentIds (internal to the SegmentStore), once assigned initially, will have the same value throughout the life of a Segment. Instead of assigning a new SegmentId every time a Segment becomes active again, the SegmentId is persisted in the SegmentState (next to the attributes) and reloaded upon subsequent activations of the segment.
- `SegmentState`/`SegmentStateStore`: persisting/loading SegmentId.  
- `StreamSegmentMapper`: loading segment id from SegmentStateStore if available.
- `OperationMetadataUpdater`: not assigning segment id if already assigned.
- `SegmentMetadata` has a flag that indicates whether it is active or not. Evicted segments become inactive. This tells the `ReadIndex` and `StorageWriter` that a segment has become inactive and they have to take action on that (i.e., refresh).
    - The `ReadIndex` and `StorageWriter` have been slightly changed to look for this flag when checking for evicted segments and do any necessary cleanup based on that.

**Purpose of the change**
Fixes #1200 (and some possible other bugs that may come in the future as well).

**What the code does**
SegmentId is persisted in the State Store, and reloaded with every segment activation.

**How to verify it**
This was one of the solutions to the problem reported in #1200. There were several other solutions to the problem, but all were clumsy, complex and hard to test. This was by far the most elegant solution.

Two major new unit tests were added. One to `DurableLogTests` that verifies that remapping a Segment with the same Id works well for recovery (and that remapping with a different one fails), and one to `StreamSegmentContainerTests` that verifies the E2E scenario where a segment is forgotten and then reactivated, after which a recovery is done and it is verified to work well.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentContainerMetadata.java [hunk 1]
```diff
@@ -302,7 +302,8 @@ public void setContainerEpoch(long value) {
                     .stream()
                     .filter(m -> isEligibleForEviction(m, adjustedCutoff) && !activeTransactions.contains(m.getId()))
                     .forEach(m -> {
-                        this.metadataById.remove(m.getId());
+                        StreamSegmentMetadata removedMetadata = this.metadataById.remove(m.getId());
+                        removedMetadata.markInactive();
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentContainerMetadata.java]: If this is removed from the metadataById map how anyone going to see mark?

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java [hunk 2]
```diff
@@ -345,63 +345,78 @@ private SegmentState getState(SegmentProperties source, Collection<AttributeUpda
...
      * failed, then this Future will complete with that exception.
      */
-    private CompletableFuture<Long> submitToOperationLogWithRetry(SegmentProperties streamSegmentInfo, long parentStreamSegmentId, Duration timeout) {
-        return retryWithCleanup(() -> submitToOperationLog(streamSegmentInfo, parentStreamSegmentId, timeout));
+    private CompletableFuture<Long> submitToOperationLogWithRetry(SegmentInfo segmentInfo, long parentStreamSegmentId, Duration timeout) {
+        return retryWithCleanup(() -> submitToOperationLog(segmentInfo, parentStreamSegmentId, timeout));
     }
 
     /**
      * Submits a StreamSegmentMapOperation or TransactionMapOperation to the OperationLog. Upon completion, this operation
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java]: Is this Javadoc still accurate?

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java [hunk 3]
```diff
@@ -345,63 +345,78 @@ private SegmentState getState(SegmentProperties source, Collection<AttributeUpda
...
             }
 
             return logAddResult
-                    .thenApply(seqNo -> completeAssignment(streamSegmentInfo.getName(), mapping.getStreamSegmentId()));
+                    .thenApply(seqNo -> completeAssignment(properties.getName(), mapping.getStreamSegmentId()));
         }
     }
 
     /**
+     * Transfers the segment id from the given segment info to the given mapping, if any,
```
Comment (tkaitchuck) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java]: Here and in the method name, I found the word "transfer" confusing, as it seemed to apply some sort of ownership, like that some other mapping could lose the segmentId.

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentContainerMetadata.java (hunk 1 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentContainerMetadata.java]: The `StreamSegmentReadIndex` and `SegmentAggregator` classes keep pointers to the objects themselves. They do not re-request them every time they need them (since they need them a lot, I did not want to slow things down with hash table lookups). As such, I need a way to notify those components that their metadata instance has become inactive and they need to do something about it (that something is close & recreate themselves, which is a mechanism that was already in place)

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java (hunk 2 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java]: Good observation. I fixed the JavaDoc throughout this class.

File: segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java (hunk 3 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/service/server/containers/StreamSegmentMapper.java]: Renamed to "apply"
