### PR TITLE
Issue 4927 deleteKeyValueTableTest fails for InMemoryKVTableStore when using KVTOperationContext

### LINKED ISSUE #4927: deleteKeyValueTableTest fails for InMemoryKVTableStore when using KVTOperationContext
**Problem description**
deleteKeyValueTableTest() in InMemoryControllerImplServiceTest.java fails with timeout exception for InMemoryKVTableStore when using KVTOperationContext.
The same when invoked for PravegaTablesStore works fine.
This could be due to some issue with the test code or with InMemoryKVStore implementation.

**Problem location**
io/pravega/controller/server/v1/InMemoryControllerImplServiceTest.java --> deleteKeyValueTableTests()

### PR DESCRIPTION
**Pull request by pbelgundi**
**Change log description**  
The root cause was that in case of InMemoryKVTableMetadataStore, when KVTOperationContext was used to get a reference to the KeyValueTable, it kept pointing to a deleted KVTable object. As a result, the state of the KVTable never changed from DELETING to UNKNOWN as was expected after a deleteKVTable operation.

**Purpose of the change**  
Fixes #4927, #4960 

**What the code does**  
In case of an InMemoryKVTableMetadataStore, using KVTOperationContext is unnecessary as all data is already stored in Memory. Removed use of KVTOperationContext in getKVTable() method of InMemoryKVTableMetadataStore and now the test works as expected.

**How to verify it**  
All Unit and Integration tests should pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 1]
```diff
@@ -57,20 +51,12 @@ KeyValueTable newKeyValueTable(String scope, String kvTableName) {
 
     @Override
     public KeyValueTable getKVTable(String scope, final String name, KVTOperationContext context) {
-        KeyValueTable kvt;
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:60]: why is this being changed? what was wrong with taking the kvt from the context?

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 2]
```diff
@@ -57,20 +51,12 @@ KeyValueTable newKeyValueTable(String scope, String kvTableName) {
...
-            assert kvt.getScopeName().equals(scope);
-            assert kvt.getName().equals(name);
-        } else {
-            if (!scopes.containsKey(scope)) {
-                return new InMemoryKVTable(scope, name);
-            }
-            InMemoryScope kvtScope = scopes.get(scope);
-            Optional<InMemoryKVTable> kvTable = kvtScope.getKVTableFromScope(name);
-            kvt = kvTable.orElse(new InMemoryKVTable(scope, name));
+        if (!scopes.containsKey(scope)) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:54]: why is the check on scopes? 
shouldnt the check be on table.. if the table doesnt exist, create it.. else return an already created table.. and this should be concurrency protected.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:54]: and why are we creating kvt object if the scope doesnt exist?
this logic seems incorrect.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 3]
```diff
@@ -40,14 +39,9 @@
     @GuardedBy("$lock")
     private Map<String, InMemoryScope> scopes = new HashMap<>();
 
-    private final AtomicInt96 counter;
-
-    private final Executor executor;
 
     public InMemoryKVTMetadataStore(Executor executor) {
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:43]: Remove `executor` from the argument list.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:60]: There is no advantage in taking KVT from context in case of InMemoryStore as all data is already in memory.
When using KVT from context, the KVTable object is available in the context though it is removed from the scope. Besides it has State="Deleting" which causes the isDeleted() method to never compete.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:43]: Ok. Sure.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:54]: This was added because scopes created in StreamStore are not available inside KVTStore. Will fix this as part of fix for issue #4960.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:60]: what is the delete method doing? perhaps it should be implemented such that it marks the entry as deleted and removes the entry from the map. 

that way context will be able to get the correct value as well.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 2 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:54]: still, the condition being added here with scopes doesnt exist seems to be introducing an incorrectness. Perhaps we should fix 4960 first before we fix this.

Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:54]: Sure. I can raise the PR for 4960 and merge this after that.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 1 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:60]: It should all fall in place once Scopes are implemented correctly in InMemoryKVTMetadataStore.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java]: Fixed as part of this PR.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 3 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 4]
```diff
@@ -36,48 +36,44 @@
...
-            kvt = context.getKvTable();
-            assert kvt.getScopeName().equals(scope);
-            assert kvt.getName().equals(name);
-        } else {
-            if (!scopes.containsKey(scope)) {
-                return new InMemoryKVTable(scope, name);
+    @Synchronized
+    KeyValueTable newKeyValueTable(String scope, String name) {
+        if (this.streamStore.getScopes().containsKey(scope)) {
+            InMemoryScope kvtScope = this.streamStore.getScopes().get(scope);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:52]: streamstore.getScopes is returning a map which is not synchronization protected in its access here.. 
instead expose a syncrhonized method on the stream store for getting the scope.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 5]
```diff
@@ -36,48 +36,44 @@
...
     @Override
     public Scope newScope(String scopeName) {
         return getScope(scopeName);
     }
 
+    @Override
+    @Synchronized
+    public KeyValueTable getKVTable(String scope, final String name, KVTOperationContext context) {
+        if (this.streamStore.getScopes().containsKey(scope)) {
+            InMemoryScope kvtScope = this.streamStore.getScopes().get(scope);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:69]: same here.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 6]
```diff
@@ -98,20 +94,26 @@ public Scope newScope(String scopeName) {
...
+        return Futures.completeOn(CompletableFuture.completedFuture(this.streamStore.getScopes().containsKey(scope)), executor);
     }
 
     @Override
     @Synchronized
     public CompletableFuture<Boolean> checkTableExists(String scopeName, String kvt) {
-        return CompletableFuture.completedFuture((InMemoryScope) getScope(scopeName)).thenApply(scope -> scope.checkTableExists(kvt));
+        return Futures.completeOn(checkScopeExists(scopeName).thenCompose(exists -> {
+            if (exists) {
+                return CompletableFuture.completedFuture((InMemoryScope) getScope(scopeName))
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:105]: you dont need to do `CompletableFuture.completedFuture().thenApply`.
Instead you can compute the value and then do CompletableFuture.completedFuture(value)

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 7]
```diff
@@ -98,20 +94,26 @@ public Scope newScope(String scopeName) {
...
+                        .thenApply(scope -> scope.checkTableExists(kvt));
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:106]: isnt scope.checkTableExists returning a future?
if so, shouldnt this be thenCompose?

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:52]: Sure.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 6 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:105]: sure.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:52]: fixed

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:69]: fixed

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 7 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java]: fixed

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:52]: creating an immutable map each time its accessed here is costly as it will make a copy. 
instead you can use `Collections.unmodifiableMap` which actually creates a wrapper decoration on the map which prohibits any changes to the map

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java [hunk 8]
```diff
@@ -41,7 +41,7 @@
     private HashMap<String, Integer> streamsPositionMap;
 
     @GuardedBy("$lock")
-    private TreeMap<String, InMemoryKVTable> kvTablesMap;
+    private final TreeMap<String, InMemoryKVTable> kvTablesMap =  new TreeMap<String, InMemoryKVTable>();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: this can be reverted except the `final` keyword.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java [hunk 9]
```diff
@@ -57,7 +57,6 @@ public String getName() {
     public CompletableFuture<Void> createScope() {
         this.sortedStreamsInScope = new TreeMap<>(Integer::compare);
         this.streamsPositionMap = new HashMap<>();
-        this.kvTablesMap =  new TreeMap<String, InMemoryKVTable>();
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:60]: it is more consistent to initialize this in the contructor as all other fields are also initialized in the constructor.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:60]: also, all other fields are non final. as we set them to null in deleteScope. though logically that doesnt really give us anything. but since that is the pattern being used for all other objects, i would suggest we keep the same pattern for this field too.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:52]: actually i dont see you returning an immutable map.

immutable map is one in which you cannot add/remove/replace any entries. 

setting the field as final doesnt make it immutable, it just means that field cannot be assigned a different value. but the object that the field refers to can still be immutable, as is the case here.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java [hunk 10]
```diff
@@ -175,4 +165,7 @@ public void refresh() {
         return CompletableFuture.completedFuture(null);
     }
 
+    public KeyValueTable getKeyValueTable(String name) {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:168]: kvTablesMap is guarded by $lock so add synchronized annotation for this method

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java [hunk 11]
```diff
@@ -74,7 +75,7 @@ public InMemoryStreamMetadataStore(Executor executor) {
     }
 
     public Map<String, InMemoryScope> getScopes() {
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java:77]: please add synchronized here as well as this is reading the `scopes` map which is concurrency protected.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 9 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:60]: I don't like the idea of having data members point to null values and wouldn't want to repeat the same just for consistency.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 4 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java]: Changed as discussed.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 5 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java]: changed as discussed.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 8 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: Why?

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 10 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:170]: done

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java (hunk 11 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java]: removed this method as discussed.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 8 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: no i mean init in constructor

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 9 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:60]: we should never be accessing a "deleted" scope object. 
The purpose of setting all fields in the scope object to null should not cause NPE. And if it does, it would point to a bug that should be fixed.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 8 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: Construction initialization is good for usecases where the values used in building the object need to be passed to the constructor. Initializing at the time of declaration also takes away the need to synchronize the constructor and I don't see any downsides with initializing it this way.

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 9 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:60]: Whenever possible, I'd want to avoid null references to class data members in the code, as a good coding practice...

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 8 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: no downside, just consistency as other objects are initialized in the constructor.

Also constructor is implicitly synchronized and you dont need to synchronize a constructor.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java [hunk 12]
```diff
@@ -98,20 +97,25 @@ public Scope newScope(String scopeName) {
...
 
     @Override
     @Synchronized
     public Scope getScope(final String scopeName) {
-        if (scopes.containsKey(scopeName)) {
-            return scopes.get(scopeName);
+        if (this.streamStore.scopeExists(scopeName)) {
+            return this.streamStore.getScope(scopeName);
         } else {
             return new InMemoryScope(scopeName);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:120]: is there a check that ensures that "create" is called on the scope object before it is used. 
this is returning the scope object, but where does it get added to the store?

File: controller/src/main/java/io/pravega/controller/store/InMemoryScope.java (hunk 8 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/InMemoryScope.java:44]: Ok.

File: controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java (hunk 12 above)
Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:120]: This is implemented in same lines as similar method in InMemoryMetadataStore:
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/store/stream/InMemoryStreamMetadataStore.java#L117

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:120]: yes, but it looks incorrect in both places. we need to see if getScope should return scope not found if the scope does not exist in the store.

Comment (pbelgundi) [reply controller/src/main/java/io/pravega/controller/store/kvtable/InMemoryKVTMetadataStore.java:120]: I agree, but it may need significant code refactoring as there are multiple dependent methods that would break.
Filed: https://github.com/pravega/pravega/issues/5021

**Comment by andreipaduroiu** [comment]
@pbelgundi Looks like I can't merge this due to codecov complaining ....
