### PR TITLE
Issue 2357: (SegmentStore) Extended attributes

### LINKED ISSUE #2357: Extended Attributes
**Problem description**
We need a more general Key-Value store in the Segment store, subject to the following:
- Key-Values are associated with Segments.
- Key is of type `Segment + UUID`, Value is of type `Long`
- There should be no limit as to how many of these there can be
    - In practice we may choose a limit, but it will not be as restricted as Core Attributes
- Attribute Arithmetic (CAS, Accumulate) is still needed on these ,but we are flexible - we can rely on a new operation to pull them out of hibernation and make them useful.
- We need the ability to update a Key-Value atomically with a Segment Store operation (`append` and `concat` for now)

**Problem location**
Segment Store.

**Suggestions for an improvement**

**General**
- We keep attributes as they are(`UUID->Long`).
- **Core attributes** vs **Extended attributes**
    - Core: whatever is defined in `Attributes` with a `WELL_KNOWN_PREFIX` (i.e., if `isDynamic` returns false)
        - Core attributes (only) are serialized into the State file, and are recovered after a failover
    - Extended: anything which is not core.
        - Extended attributes are not serialized into the State file, and thus not recovered immediately after a failover. They are stored in a special file (see below). However, upon setting, they will be cached in the in-memory SegmentMetadata until eviction.
- Usage flow, during append setup:
    1. Call `StreamSegmentStore.getInfo(Segment)` and get the segment's attribute value for that writer.
    2. If nothing, fetch that value from Extended Attributes (using new API)
    3. Execute a CAS operation (append/updateAttributes) that updates this attribute. The SSS will work as it does today, but it will also update the Extended Attribute value iff the operation succeeds. The CAS will need to be tailored based on the outcome of 1. above (if not in memory, then CAS against null, otherwise CAS against existing value).
    4. In case of a failover or segment eviction (lots of inactivity), the segment will be evicted. If it gets reactivated, we'll go back to step 1.
- Each segment has an "attribute" sub-segment.
    - This has all the attribute updates, and periodic consolidations (checkpoints). The attribute subsegment is always truncated at the beginning of a checkpoint.
    - The main segment will have two extra Core Attributes:
        - `LastAttributeSnapshotOffset`: the offset within the attribute subsegment where the last valid checkpoint begins.
        - `LastAttributeSnapshotLength`: the length of the last checkpoint.
    - Fetching latest Attribute value
        - We look into the in-memory segment; if not there, we look up in the attribute segment (see AttributeIndex)
    - Writing: 
        - We always append. After a recovery, it's OK if we re-write the same data multiple times, as we only care about the latest value.
        - When the attribute segment exceeeds some configurable threshold after the last checkpoint ends, we create a new checkpoint, write it, then truncate the segment and update main segment's pointer.

**Segment Store Changes**
- StreamSegmentStore API
    - We add getExtendedAttribute(SegmentName, UUID attribute)
        - This will check in-memory segment; if none, go to attribute sub-segment.
- `OperationProcessor/ContainerMetadataUpdateTransaction`
    - Every operation that updates attributes will set the value in memory, just like core attributes. 
    - Sub-class `BadAttributeUpdateException` with a `NoSuchAttributeException` to more accurately describe the cause of the failure. The Wire Protocol's `setupAppend`/`append` will make use of this.
- `StorageWriter`:
    - Will transfer the updates for non-core attributes to the attrib segment via appends (it can do minor aggregations if needed).
    
**AttributeIndex**
- `CompletableFuture<Void> write(Segment, List<Attribute(UUID, Long)>)`
   - Storage.write(END, serialized values)
   - If length >= some size, create snapshot.
- `private CompletableFuture<Void> snapshot()`
   - Load last snapshot, beginning at LastCheckpointOffset. Create an in-memory hash.
   - Read through the end of the Attribute Segment, fetching attribute values, and updating the in-memory hash.
   - Write the new shapshot, sorting the Attributes by Key (will make lookups for large snapshots easier).
   - Update main attribute pointer. NOTE: this must be done via OperationProcessor to ensure attributes are not overridden.
- `CompletableFuture<Long> get(Segment, UUID)`
   - get LastAttributeSnapshotOffset+Length from main segment
   - Read snapshot and get initial attribute value
   - Scan the remaining segment and look for updated values for this attribute.
   - Return latest value
- Each snapshot and attribute update write will need to use `VersionedSerializer` to allow future format changes. Bonus points for compressing them as well.

**Future enhancements**
Please refer to #2419.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
Implemented Extended Attributes in the Segment Store.

Overview:
- Before: All attributes were stored in the Segment Metadata (memory), checkpointed with it and stored in the Segment's State File when it got evicted from memory. There were "Well Known" and" Dynamic" Attributes. There is a limit of 1024 attributes in total.
- With this change:
    - Well Known Attributes are renamed to Core Attributes, and Dynamic Attributes are now called Extended Attributes.
    - Core Attributes are always present in the Segment's Metadata, State File and checkpoints. The 1024 limit is preserved.
    - Extended Attributes are durably stored in a shadow segment (Attribute Segment). They can be fetched using a new API, and loaded into the Segment's Metadata. They will not be checkpointed or serialized. If an Extended Attribute is present in memory (Segment's Metadata), it is guaranteed that this value is the latest.

API Changes:
- `StreamSegmentStore.getStreamSegmentInfo`
    - The attributes returned will always contain Core attributes, but they will only include those Extended Attributes that are currently loaded in memory.
- `StreamSegmentStore.getAttributes`
    - Allows fetching any kind of attribute, Core or Extended, either via the Segment's Metadata or from the Attribute Index. Also allows loading the desired Extended Attributes into memory (conditionally) so that they may participate in conditional updates.

`AttributeIndex`/`ContainerAttributeIndex`
- New component added whose responsibility is to durably store Extended Attributes, compact them, and return the latest stored value.
    - There is one `AttributeIndex` per segment, and one `ContainerAttributeIndex` per container, the latter managing many instances of the former.
- It is backed by an append only shadow Segment stored directly in Tier2 (changes to this Segment do not go through the main Segment Store Processor, since that would essentially double the memory requirements for each segment that we handle).
- Any updates are appended as a single write at the end of the segment.
- Based on configuration, after a number of updates, the current changes are compacted into a Snapshot and written at the end of the segment, after which the segment is truncated where the snapshot begins (a snapshot contains the latest values for each involved attribute).
    - When a snapshot is created, there are two Core Attributes updated on the main segment that point to the location of this snapshot (offset + length).
- Reading involves scanning the attribute segment beginning at the latest snapshot offset until the end of the attribute segment, and returning the latest value(s) for those attributes

`StorageWriter`/`SegmentAggregator`
- Process `UpdateAttributeOperations` in addition to `SegmentAppendOperations`, and, for each batch, aggregate the attribute updates together.
- When a batch for a segment is flushed to Tier2, the attributes associated with that batch are also written as a single update to the `AttributeIndex`, which (as described above), persists them into the Attribute Segment.
- Most of the changes here deal with proper reconciliation after a failover or other Tier2 write error. Since the Attribute Segment is different from the main Segment, and thus we need two distinct operations to execute (which cannot be done atomically), we want to make sure that we don't get a false reconciliation in case we did reconcile the data in the segment but not the attributes.

`StreamSegmentContainer`
- Implementing `getAttributes` (see API above) that fetches the values of attributes, first from the in-memory Segment Metadata, and then (what's remaining) from the `AttributeIndex`. Optionally loading those missing values into memory using a conditional update.
- `SegmentAppendOperations` and `UpdateAttributesOperations` are automatically retried (once) if they fail with a `BadAttributeUpdateException` which was due to a missing Extended Attribute from memory (all other exceptions are re-thrown and not re-attempted). 
    - If this does happen, the missing attributes are auto-loaded by means of `getAttributes` (using a conditional update) before re-attempting the unaltered original operation.

**Purpose of the change**
Fixes #2357.

**What the code does**
Covered in "Change log description" above.
For future enhancements which will be done later (caching included), please refer to #2419.

**How to verify it**
- Many new unit tests added for AttributeIndex
- Many unit tests updated and some added for `SegmentAggregator` and `StreamSegmentContainer`
- Unit tests for `AppendProcessor` updated for new behavior.
- System tests (from this branch) must pass.
    - Branch build 411 passed successfully.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/FileSystemOperation.java [hunk 1]
```diff
@@ -193,7 +193,9 @@ FileDescriptor combine(FileDescriptor target, List<FileDescriptor> sources, bool
             }
 
             // Finally, concatenate the source files into the target.
-            this.context.fileSystem.concat(target.getPath(), toConcat);
+            if (toConcat.length > 0) {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/FileSystemOperation.java]: This may end up being wiped away completely with #2401 , but this became really bothersome during the testing of this PR.

**Comment by andreipaduroiu** [comment]
[Segment Store: Extended Attributes (Initial)](https://trello.com/c/UpsLEiuE/3-segment-store-extended-attributes-initial)

**Comment by andreipaduroiu** [comment]
[Segment Store: Extended Attributes (Initial)](https://trello.com/c/UpsLEiuE/3-segment-store-extended-attributes-initial)

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndex.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+     * Deletes any existing attribute data pertaining to the given Segment.
+     *
+     * @param metadata The SegmentMetadata for the Segment whose Attribute data to delete.
+     * @param timeout  Timeout for the operation.
+     * @return A CompletableFuture that, when completed, will indicate that the operation finished.
+     */
+    CompletableFuture<Void> delete(SegmentMetadata metadata, Duration timeout);
+
+    /**
+     * Removes all internal indices that point to the given StreamSegments.
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndex.java]: Done. This just removes the objects from memory and not actually deleting the data.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+        SegmentMetadata sm = this.containerMetadata.getStreamSegmentMetadata(streamSegmentId);
+        if (sm.isDeleted()) {
+            return Futures.failedFuture(new StreamSegmentNotExistsException(sm.getName()));
+        }
+
+        // Figure out if we already have this AttributeIndex cached. If not, we need to initialize it.
+        CompletableFuture<AttributeIndex> result;
+        AtomicReference<SegmentAttributeIndex> toInitialize = new AtomicReference<>();
+        synchronized (this.attributeIndices) {
+            result = this.attributeIndices.computeIfAbsent(streamSegmentId, id -> {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java]: Actually no. We put an un-completed CompletableFuture in that map, which others may pick up. When other callers call `then***` on it, that code will only execute when this future completes. The code underneath this `synchronized` block deals with completing that future, which is dependent on the initialization being done.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 4]
```diff
@@ -0,0 +1,668 @@
...
+            .throwingOn(Exception.class);
+
+    /**
+     * Calls to get() and put() can execute concurrently, which means we can have concurrent reads and writes from/to the
+     * Attribute Segment, which in turn means we can truncate the segment while reading from it. We need to retry reads
+     * if we stumble across a segment truncation.
+     */
+    private static final Retry.RetryAndThrowBase<Exception> READ_RETRY = Retry
+            .withExpBackoff(10, 2, 10, 1000)
+            .retryWhen(ex -> Exceptions.unwrap(ex) instanceof StreamSegmentTruncatedException)
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Fixed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 5]
```diff
@@ -0,0 +1,668 @@
...
+     *
+     * @param timeout Timeout for the operation.
+     * @return A CompletableFuture that, when completed, will indicate the operation has succeeded.
+     */
+    CompletableFuture<Void> initialize(Duration timeout) {
+        TimeoutTimer timer = new TimeoutTimer(timeout);
+        String attributeSegmentName = StreamSegmentNameUtils.getAttributeSegmentName(this.segmentMetadata.getName());
+        Preconditions.checkState(this.attributeSegment.get() == null, "SegmentAttributeIndex is already initialized.");
+        return Futures
+                .exceptionallyCompose(
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: I added `Futures.exceptionallyComposeExpecting`

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 6]
```diff
@@ -0,0 +1,668 @@
...
+    }
+
+    //endregion
+
+    //region AttributeSegmentReader
+
+    /**
+     * Async reader for the Attribute Segment from Storage.
+     */
+    private static class AttributeSegmentReader implements AsyncReadResultHandler {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: done

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 7]
```diff
@@ -482,6 +511,111 @@ public boolean isOffline() {
...
+     *                        be added to that (using a conditional updateAttributes() call) before completing.
+     * @param timer           Timer for the operation.
+     * @return A CompletableFuture that, when completed normally, will contain the desired result. If the operation failed,
+     * it will be completed with the appropriate exception. If cache==true and the conditional call to updateAttributes()
+     * could not be completed because of a conflicting update, it will be failed with BadAttributeUpdateException, in which
+     * case a retry is warranted.
+     */
+    private CompletableFuture<Map<UUID, Long>> getAndCacheAttributes(SegmentMetadata segmentMetadata, Collection<UUID> attributeIds, boolean cache, TimeoutTimer timer) {
+        // Collect Core Attributes and Cached Extended Attributes.
+        Map<UUID, Long> result = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: this is a private variable to this method and is not used concurrently by multiple threads.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 8]
```diff
@@ -482,6 +511,111 @@ public boolean isOffline() {
...
+            // No need for extra complicated handling.
+            return this.durableLog.add(operation, timer.getRemaining());
+        }
+
+        return Futures.exceptionallyCompose(
+                this.durableLog.add(operation, timer.getRemaining()),
+                ex -> {
+                    // We only retry BadAttributeUpdateExceptions if it has the PreviousValueMissing flag set.
+                    ex = Exceptions.unwrap(ex);
+                    if (ex instanceof BadAttributeUpdateException && ((BadAttributeUpdateException) ex).isPreviousValueMissing()) {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: Ah yes, but I can't. If you look closer, I also re-throw the exception if the missing attribute was a Core Attribute. That is a genuine exception which should be passed back to the caller. I can't do that with `exceptionallyExpecting`, which decides exclusively on the exception.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java [hunk 9]
```diff
@@ -992,43 +1062,63 @@ private FlushArgs getFlushArgs() throws DataCorruptionException {
...
-                    String.format("Unable to reconcile operation '%s' because no append data is associated with it.", op), this.metadata, storageInfo));
-        }
+    private CompletableFuture<FlushResult> reconcileAppendOperation(AggregatedAppendOperation op, SegmentProperties storageInfo, TimeoutTimer timer) {
+        CompletableFuture<Void> result;
+        AtomicInteger reconciledBytes = new AtomicInteger();
+        AtomicBoolean reconciledSuccessful = new AtomicBoolean(false);
+        if (op.getLength() > 0) {
+            // This operation has data. Read data from Storage, and compare byte-by-byte.
+            InputStream appendStream = this.dataSource.getAppendData(op.getStreamSegmentId(), op.getStreamSegmentOffset(), (int) op.getLength());
+            if (appendStream == null) {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java]: Done.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java [hunk 10]
```diff
@@ -1091,22 +1185,57 @@ private void verifySame(InputStream appendStream, byte[] storageData, StorageOpe
...
+    /**
+     * Handles expected Attribute-related exceptions. Since the attribute index is a separate segment from the main one,
+     * it is highly likely that it may get temporarily out of sync with the main one, thus causing spurious StreamSegmentSealedExceptions
+     * or StreamSegmentNotExistsExceptions. If we get either of those, and they are consistent with our current state, the
+     * we can safely ignore them; otherwise we should be rethrowing them.
+     */
+    private CompletableFuture<Void> handleAttributeException(CompletableFuture<Void> future) {
+        return Futures.exceptionallyExpecting(
+                future,
+                ex -> (ex instanceof StreamSegmentSealedException && this.metadata.isSealedInStorage())
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java]: `exceptionallyExpecting` does all the legwork of unwrapping it so I don't need to.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 11]
```diff
@@ -0,0 +1,663 @@
...
+            return CompletableFuture.completedFuture(null);
+        } else {
+            AttributeCollection c = new AttributeCollection(values);
+            if (shouldSnapshot()) {
+                // We are overdue for a snapshot. Create one while including the new values. No need to also write them
+                // separately.
+                return createSnapshot(c, false, timeout);
+            } else {
+                // Write the new values separately, as an atomic append.
+                return Futures.toVoid(appendConditionally(() -> CompletableFuture.completedFuture(serialize(c)),
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: In the case I'm calling put on a single key-value, I think this is doing an append for that single key-value pair, which is not going to be very efficient.

For consistency, I believe we need this value to be made durable before we can proceed, and Tier 2 writes are not expected to have low latency, so the updates of attributes can hurt performance.

Could you elaborate on what's wrong with my understanding or in general why updating this way is not a problem?

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: This API is only invoked by the `StorageWriter`/`SegmentAggregator` and it already aggregates multiple updates into a single one. It collects all attribute updates for all Appends/Updates it normally aggregates, so a single call to this API will be the result of possibly a lot of individual updates. 

For example, if we have lots of 100-byte appends on the same segment, the SW will wait 30s or until it fills 1MB, thus possibly aggregating 10K such appends together. That means it will include 10K attribute updates, combined into a single call to this API. Also note that multiple updates to the same attribute will be coalesced into a single value (the last one).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 12]
```diff
@@ -0,0 +1,663 @@
...
+     */
+    private CompletableFuture<AttributeCollection> readAllSinceLastSnapshot(Duration timeout) {
+        CompletableFuture<AttributeCollection> result = READ_RETRY.runAsync(() -> {
+            if (isMainSegmentDeleted()) {
+                // Verify if the main segment has been deleted and stop now if needed.
+                return handleMainSegmentDeleted(timeout);
+            }
+
+            long lastSnapshotOffset = getLastSnapshotOffset();
+            int readLength = (int) Math.min(Integer.MAX_VALUE, this.attributeSegment.get().getLength() - lastSnapshotOffset);
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Does this yields that a single snapshot can be at most 2.14GB in size? If this is correct, could it be interesting to mention this limitation at some point of the config/doc?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 13]
```diff
@@ -482,6 +511,109 @@ public boolean isOffline() {
...
+                result.put(attributeId, v);
+            } else if (!Attributes.isCoreAttribute(attributeId)) {
+                extendedAttributeIds.add(attributeId);
+            }
+        });
+
+        // Collect remaining Extended Attributes.
+        CompletableFuture<Map<UUID, Long>> r = this.attributeIndex
+                .forSegment(segmentMetadata.getId(), timer.getRemaining())
+                .thenComposeAsync(idx -> idx.get(extendedAttributeIds, timer.getRemaining()), this.executor);
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: A clarification: the call to `idx.get` here will induce a call to `readAllSinceLastSnapshot`, which performs a read of the snapshot in the attribute segment perhaps unnecessarily in the case we have collected all attributes by Line 583. In the case my interpretation is correct, is it worth checking before reading the snapshot from the attribute segment?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 14]
```diff
@@ -0,0 +1,663 @@
...
+     *                      Snapshots generated as part of Seals, all of those must complete in order for the operation to
+     *                      be considered successful.
+     * @param timeout       Timeout for the operation.
+     * @return A CompletableFuture that, when completed, will indicate that the operation has completed successfully.
+     */
+    private CompletableFuture<Void> createSnapshot(AttributeCollection newAttributes, boolean mustComplete, Duration timeout) {
+        TimeoutTimer timer = new TimeoutTimer(timeout);
+
+        // The serialization may be invoked multiple times, based on whether the appendConditionally() requires a retry.
+        Supplier<CompletableFuture<ArrayView>> s = () ->
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: A clarification: here we are generating a new snapshot by merging the attributes in the last snapshot with the new attributes. Does it mean that we never really get rid of attributes, unless they are explicitly deleted?

 I'm asking because of the case of writer ids, in which we can have a writer crashing and never coming back. We will never get rid of the corresponding writer id, and worse, we will keep accumulating such ids.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 12 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Each attribute-value pair in the snapshot takes 24 bytes. IF we ever reach the maximum then we'll have about 100M attributes. We'll run into trouble way before that reaches. This whole thing is designed to work well with up to 1M attributes (for which the snapshot will be about 24MB).

File: config/config.properties [hunk 15]
```diff
@@ -418,6 +418,29 @@ extendeds3.url=localhost:9020
...
 ##endregion
 
+##region AttributeIndex Settings
+
+# The maximum number of attribute updates processed before a Snapshot is triggered.
+# Valid values: Positive integer.
+# Recommended values: Between 10000 and 100000. Smaller values will cause more frequent snapshots, leading to possibly
+# more churn on the asynchronous StorageWriter but with faster reads, while higher values will cause less frequent snapshots,
+# which could cause increased seek times during reads.
+#attributeindex.updateCountThresholdForSnapshot=50000
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply config/config.properties]: This is on a per-segment basis. Given the aggregation that we do in the StorageWriter, I doubt we'll have more than a few dozen updates per second, per segment.

Consider these extremes:
- Lots of writers, lots of small writes: We'll aggregate and dump to Tier2 when we accumulate 1MB. This will coalesce all those writes/updates into one per writer per 1MB written to the segment.
- Few writers, large writes: Still bounded by the 1MB limit, but the number of attribute updates in TIer2 will be much smaller
- Single writer, many writes: only one update per 1MB written.

The first scenario will case the most updates. If that's the case, then we'll have more frequent snapshots. That's perfectly acceptable, since we want to compress updates into a compact form for easier reading.

And this number is configurable by the customer, if they feel they are not getting a good performance out of the system.

File: config/config.properties [hunk 16]
```diff
@@ -418,6 +418,29 @@ extendeds3.url=localhost:9020
...
+
+# The maximum read request length (bytes) to use when reading from Storage. Reads will be done by issuing sequential requests
+# with this value as a maximum read length. This is also used as a minimum bound for Attribute Segment Rolling Policy if
+# Auto-calculation was requested.
+# Valid values: positive integer.
+# Recommended values: multiples of 1MB. The higher the value, the better the read performance, at the expense of using a
+# single storage thread for longer periods of times, which may be unfair to other components waiting to work with Storage.
+#attributeindex.readBlockSize=1048576
+
+# The Attribute Rolling Segment Rolling Policy (size of each individual segment chunk, in bytes).
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply config/config.properties]: Each "Rolling Segment" has a "Rolling Policy". It appears twice, but each is attributed to a different term.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java [hunk 17]
```diff
@@ -17,17 +17,6 @@
  * Defines an immutable StreamSegment Metadata.
  */
 public interface SegmentMetadata extends SegmentProperties {
-    /**
-     * The maximum number of attributes that a single Segment can have at any given time. Due to serialization constraints
-     * there needs to be a hard limit as to how many attributes each segment can have.
-     */
-    int MAXIMUM_ATTRIBUTE_COUNT = 1024;
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java]: Coming up in a future PR. I will file that once this PR is merged in since it's built on top of that.

#2419

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java (hunk 13 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: `extendedAttributeIds` only contains those attribute ids from `attributeIds` that we were unable to fetch from memory (see the construction above). If this method is called with an empty collection, it will just return, without invoking `readAllSinceLastSnapshot`.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 14 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: The only way to get rid of an attribute is to set its value to `Attributes.NULL_ATTRIBUTE_VALUE`. Otherwise I cannot remove it. 

The problem with writer ids never getting cleaned up is beyond the scope of this PR and should be addressed in the Client/Wire Protocol.

File: common/src/main/java/io/pravega/common/concurrent/Futures.java [hunk 18]
```diff
@@ -279,6 +279,56 @@
         }).thenCompose(f -> f);
     }
 
+    /**
+     * Same as CompletableFuture.exceptionally(), except that it allows certain types of exceptions..
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply common/src/main/java/io/pravega/common/concurrent/Futures.java]: Fixed

File: config/config.properties [hunk 19]
```diff
@@ -418,6 +418,29 @@ extendeds3.url=localhost:9020
 
 ##endregion
 
+##region AttributeIndex Settings
+
+# The maximum number of attribute updates processed before a Snapshot is triggered.
+# Valid values: Positive integer.
+# Recommended values: Between 10000 and 100000. Smaller values will cause more frequent snapshots, leading to possibly
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply config/config.properties]: Fixed

File: segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java [hunk 20]
```diff
@@ -99,7 +134,9 @@
      *                          because it needs to wait for pending ops to complete.
      * @param timeout           Timeout for the operation.
      * @return A CompletableFuture that, when completed normally, will contain the result. If the operation failed, the
-     * future will be failed with the causing exception.
+     * future will be failed with the causing exception. Note that this result will only contain those attributes that
+     * are loaded in memory (if any) or Core Attributes. To ensure that Extended Attributes are also included, consider using
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java]: Fixed

File: config/config.properties (hunk 16 above)
[the remark this answers is not in the document]
Comment (fpj) [reply config/config.properties]: Ok, it might be semantically correct, but it is difficult to parse. Can we say, for example, `The rolling policy of the attribute rolling segment`?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/SegmentMetadata.java]: Ok

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 14 above)
Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: It is fine to declare it outside scope, but I'm not sure we can address it in the client/wire protocol simply because a crashed client won't remember its writer id. We might need to expire.

Would you mind creating an issue so that we can discuss and converge on a plan of action?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java (hunk 13 above)
Comment (fpj) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: You're right, that was pretty straightforward actually.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 14 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: #2509

File: config/config.properties (hunk 16 above)
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply config/config.properties]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java [hunk 21]
```diff
@@ -0,0 +1,152 @@
...
+        }
+
+        if (toInitialize.get() == null) {
+            // We already have it cached - return its future (which should be already completed or will complete once
+            // its initialization is done).
+            return result;
+        } else {
+            try {
+                // Need to initialize the AttributeIndex and complete the future that we just registered.
+                // If this fails
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java]: This comment line seems incomplete. Did you mean to talk about the call to `indexInitializationFailed`?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 22]
```diff
@@ -0,0 +1,663 @@
...
+        if (isMainSegmentDeleted()) {
+            // Verify if the main segment has been deleted and stop now if needed.
+            return handleMainSegmentDeleted(timer.getRemaining());
+        }
+
+        long offset = as.getLength();
+        return getSerialization.get().thenComposeAsync(data ->
+                Futures.exceptionallyCompose(
+                        this.storage
+                                .write(as.handle, offset, data.getReader(), data.getLength(), timer.getRemaining())
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: I'm interested in the recovery path here. From the code, `write` throws `BadOffsetException` when offset doesn't match length. In the presence of a concurrent write, the offset check will fail and it will throw. I suppose that the snapshot in the attribute segment is consistent because of the semantics of conditional append. 

Retrying seems fine because a successful append is conditional on the instance knowing the previous snapshot so that the merge is consistent. The only possibility of a problem that I'm wondering about is the one of the number of retries exhausting. In this case, would the segment container stop?

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java [hunk 23]
```diff
@@ -0,0 +1,698 @@
...
+
+        AssertExtensions.assertThrows(
+                "seal() worked with Storage failure.",
+                () -> idx.seal(TIMEOUT),
+                ex -> ex instanceof IntentionalException);
+    }
+
+    /**
+     * Tests the case when Snapshots fail due to OperationLogFailure. The snapshot itself must have recorded in the file,
+     * but the Offset & Length attributes never updated on the main Segment.
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java]: Better not to use ampersand as it might confuse the javadoc compiler. Use `and` directly.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java [hunk 24]
```diff
@@ -0,0 +1,698 @@
...
+
+        // This call should trigger a snapshot. We want to use a different attribute so we can properly test the reconciliation
+        // algorithm by validating the written value for the other attribute.
+        idx.put(attributeId2, 0L, TIMEOUT).join();
+        Assert.assertEquals("Unexpected value after reconciliation.", lastWrittenValue.get(), (long) idx.get(attributeId, TIMEOUT).join());
+        Assert.assertEquals("Unexpected value for second attribute after reconciliation.", 0L, (long) idx.get(attributeId2, TIMEOUT).join());
+    }
+
+    /**
+     * Tests reading from the Attribute Segment but while a truncation was in progress. Scenario:
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java]: Remove `but`.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 25]
```diff
@@ -0,0 +1,663 @@
...
+     * @param mustComplete  Whether the update of the main Segment's attributes must execute successfully in order for this
+     *                      operation to be considered complete. For auto-generated Snapshots, since the Snapshot itself is
+     *                      already written to the AttributeSegment, it is not mandatory for the OperationLog Add &
+     *                      Attribute Segment Truncation operations to complete, as there will be no data loss. However, for
+     *                      Snapshots generated as part of Seals, all of those must complete in order for the operation to
+     *                      be considered successful.
+     * @param timeout       Timeout for the operation.
+     * @return A CompletableFuture that, when completed, will indicate that the operation has completed successfully.
+     */
+    private CompletableFuture<Void> createSnapshot(AttributeCollection newAttributes, boolean mustComplete, Duration timeout) {
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Can we add an info message to indicate that we are creating a snapshot? Or is it going to be too frequent?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 26]
```diff
@@ -0,0 +1,663 @@
...
+     * This method does not perform any retries.
+     *
+     * @param getSerialization A Supplier that, when invoked, returns a CompletableFuture whose result will be the requested
+     *                         serialization.
+     * @param timer            Timer for the operation. Used for timeouts.
+     * @return A CompletableFuture that, when completed, will contain information about the data that was just written.
+     */
+    private CompletableFuture<WriteInfo> appendConditionallyOnce(Supplier<CompletableFuture<ArrayView>> getSerialization, TimeoutTimer timer) {
+        // We want to make sure that the serialization we generate is accurate based on the state of the Attribute Segment.
+        // This is to protect against potential corruptions due to concurrency: for example we picked data for a Snapshot,
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Do we have test cases to validate that corruption isn't possible due to concurrent access?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 27]
```diff
@@ -0,0 +1,663 @@
...
+        TimeoutTimer timer = new TimeoutTimer(timeout);
+
+        // The serialization may be invoked multiple times, based on whether the appendConditionally() requires a retry.
+        Supplier<CompletableFuture<ArrayView>> s = () ->
+                readAllSinceLastSnapshot(timer.getRemaining())
+                        .thenApplyAsync(c -> {
+                            c.mergeWith(newAttributes);
+                            return serialize(c);
+                        }, this.executor);
+        return appendConditionally(s, timer)
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Can we actually log (info or debug) the number of attributes we have in a snapshot? It would be good to give the ability to track growth, and I'm not sure metrics is a better path.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 28]
```diff
@@ -0,0 +1,663 @@
...
+     */
+    private static final Retry.RetryAndThrowBase<Exception> APPEND_RETRY = Retry
+            .withExpBackoff(10, 2, 10, 1000)
+            .retryingOn(BadOffsetException.class)
+            .throwingOn(Exception.class);
+
+    /**
+     * Calls to get() and put() can execute concurrently, which means we can have concurrent reads and writes from/to the
+     * Attribute Segment, which in turn means we can truncate the segment while reading from it. We need to retry reads
+     * if we stumble across a segment truncation.
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: `stumble upon`

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java [hunk 29]
```diff
@@ -86,6 +92,27 @@ public int getId() {
             return this.operationLog.truncate(upToSequence, timeout);
         }
 
+        @Override
+        public CompletableFuture<Void> persistAttributes(long streamSegmentId, Map<UUID, Long> attributes, Duration timeout) {
+            TimeoutTimer timer = new TimeoutTimer(timeout);
+            return this.attributeIndex
+                    .forSegment(streamSegmentId, timer.getRemaining())
+                    .thenCompose(ai -> ai.put(attributes, timer.getRemaining()));
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java]: Is this the primary call that we make to `SegmentAttributeIndex.put`  to populate the attribute index of a segment?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java (hunk 21 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexImpl.java]: Yes. Fixed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 22 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: No, we only stop the container in case of `DataCorruptionException`, which can only be thrown upon reading (if we find a corrupted AttributeIndex).

If we get two or more concurrent calls, one of them will succeed and the rest will fail. Your scenario will happen if we have more than 10 concurrent calls (max retries == 10) and two of these will be so unlucky that they will execute at the exact same time (with an exp backoff, the probability of this is pretty remote). In that case, they will simply fail, and the `StorageWriter` will just reattempt them later. 

It may be worthwhile to say that this concurrent append thing was added for future-proofing. Currently, there is only one append to any Segment Attribute Index going on at any given time, due to the sequential nature of the Storage Writer.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java [hunk 30]
```diff
@@ -160,6 +161,11 @@ public boolean isOffline() {
         return unsupported("updateAttributes");
     }
 
+    @Override
+    public CompletableFuture<Map<UUID, Long>> getAttributes(String streamSegmentName, Collection<UUID> attributeIds, boolean cache, Duration timeout) {
+        return unsupported("getAttributes");
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ReadOnlySegmentContainer.java]: I haven't yet seen a practical application of the ROSS, and as such, I decided to minimize the scope of this PR to what will really be needed at the moment. Should the ROSS actually be used and a need for such extended attributes exist in it, we can implement them at that time.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 31]
```diff
@@ -482,6 +511,109 @@ public boolean isOffline() {
 
     //region Helpers
 
+    /**
+     * Processes the given AttributeUpdaterOperation with exactly one retry in case it was rejected because an attribute update
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: Fixed.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 32]
```diff
@@ -482,6 +511,109 @@ public boolean isOffline() {
...
+        // Collect remaining Extended Attributes.
+        CompletableFuture<Map<UUID, Long>> r = this.attributeIndex
+                .forSegment(segmentMetadata.getId(), timer.getRemaining())
+                .thenComposeAsync(idx -> idx.get(extendedAttributeIds, timer.getRemaining()), this.executor);
+
+        if (cache && !segmentMetadata.isSealed() && extendedAttributeIds.size() > 0) {
+            // Add them to the cache if requested.
+            r = r.thenComposeAsync(extendedAttributes -> {
+                // Update the in-memory Segment Metadata using a special update (AttributeUpdateType.None, which should
+                // complete IFF the attribute is not currently set). If it has some value value, then a concurrent update
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: changed it to the ordinary "if". I originally reused some blurb from conditional appends...

File: shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java [hunk 33]
```diff
@@ -49,7 +49,7 @@
     public static final int TYPE_PLUS_LENGTH_SIZE = 8;
     public static final int MAX_WIRECOMMAND_SIZE = 0x007FFFFF; // 8MB
     
-    public static final long NULL_ATTRIBUTE_VALUE = Long.MIN_VALUE; //This is the same as SegmentMetadata.NULL_ATTRIBUTE_VALUE
+    public static final long NULL_ATTRIBUTE_VALUE = Long.MIN_VALUE; //This is the same as Attributes.NULL_ATTRIBUTE_VALUE
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply shared/protocol/src/main/java/io/pravega/shared/protocol/netty/WireCommands.java]: Not really. These packages have nothing in common and do not depend on each other.

File: segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java [hunk 34]
```diff
@@ -9,49 +9,86 @@
...
+     * have a null value.
+     *
+     * @param attributes The Map of Attribute Ids to Values to filter from.
+     * @return A new Map containing only Core Attribute Ids and Values (from the original map).
      */
-    public static boolean isDynamic(UUID attributeId) {
-        return attributeId.getMostSignificantBits() != WELL_KNOWN_ID_PREFIX;
+    public static Map<UUID, Long> getCoreNonNullAttributes(Map<UUID, Long> attributes) {
+        return attributes.entrySet().stream()
+                         .filter(e -> Attributes.isCoreAttribute(e.getKey()) && e.getValue() != NULL_ATTRIBUTE_VALUE)
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java]: Yes. We use `Attributes.NULL_ATTRIBUTE_VALUE` to indicate we want to remove an attribute when we invoke `updateAttributes` or any other kind of operation that manages attributes.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java [hunk 35]
```diff
@@ -0,0 +1,663 @@
...
+            this.attributes = new HashMap<>();
+        }
+
+        private AttributeCollection(Map<UUID, Long> attributes) {
+            this.attributes = attributes == null ? new HashMap<>() : attributes;
+        }
+
+        private void mergeWith(AttributeCollection other) {
+            other.attributes.forEach((attributeId, value) -> {
+                if (value == Attributes.NULL_ATTRIBUTE_VALUE) {
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Yes. This is where we remove them from the `SegmentAttributeIndex`. This logic is similar to that in `SegmentMetadataUpdateTransaction` that does the same and removes them from the in-memory metadata.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java (hunk 23 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java]: fixed

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java (hunk 24 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/attributes/ContainerAttributeIndexTests.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 25 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: There is a debug message at line 346. I don't want to make this info since this is per segment, so we might end up polluting the logs with this.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 26 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: Yes: `testConditionalUpdates`. That is the most we can test; we rely on writes to Tier2 to be atomic (i.e., if we write a sequence of N bytes, it will go in at once, and not be broken up).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 27 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: In line 413, we debug-log the number of bytes written. In line 346, we debug-log the offset & length of the snapshot, in bytes.

I don't pass along the number of attributes to these methods (I'll need new classes) so I can't record those, but if we divide the length of the written data by 24 (UUID+Long), we get a rough estimate of the number of attributes in that write.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java (hunk 28 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/attributes/SegmentAttributeIndex.java]: fixed

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java (hunk 29 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriterFactory.java]: Yes. The `StorageWriter`'s `SegmentAggregator`s will accumulate a number of attribute updates in their own buffers (just like they do with regular data), and will invoke this method to persist them into the SegmentAttributeIndex/Tier2. Only after both this and the regular data write to tier2 will the `SegmentAggregator`s acknowledge that those operations have been durably persisted in Tier2.
