### PR TITLE
Issue 2369: Update controller table queries and operations to handle variable sized rows 

### LINKED ISSUE #2369: Update controller table queries and operations to handle variable sized rows
**Problem description**
Presently controller's stream stores queries and business logic is dependent on certain properties of its records like fixed row sizes, and certain markers within the tables that help with navigation. 
Once we introduce versioning in controller, we can have variable sized rows. So we should update our business logic around tables to handle such a change.   

**Problem location**
Controller stream store. 

**Suggestions for an improvement**
Add separate index for segment and history tables. These indexes should be updated before updating the respective tables because updates to both table and index cannot to atomic. This means we can end up in a situation that index was updated while we failed before updating the table. In such situations, we should identify a partial update and erase dangling indexes and overwrite them with new index.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
1. Add index to segment and history table and update all queries such that indexes are used for optimal access. 
2. New serialization for SegmentRecord and HistoryRecord. 

**Purpose of the change**
Fixes #2369

**What the code does**
Adds new Segment Index and Replaces index table with a history index. 
The index allows for variable sized rows in the table. 
All queries rely on indexed entries in the code. We always update Index before the entry in the table. Because repopulating the entry from the tabled record could be error prone. 
This becomes more interesting when we add multiple rows into segment table. If in a previous iteration only index was updated while the table entry was not updated, we erase all stray index entries and overwrite them with new entries that match the record that we write in the actual table. 

**How to verify it**
New unit tests added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java [hunk 1]
```diff
@@ -498,10 +501,45 @@ public void refresh() {
...
+        return store.checkExists(segmentPath)
+                .thenCompose(exists -> {
+                    if (!exists) {
+                        return store.deletePath(segmentIndexPath, false)
+                            .thenCompose(v -> store.createZNodeIfNotExist(segmentIndexPath, data.getData()));
+                    } else {
+                        return CompletableFuture.completedFuture(null);
+                    }
+                })
+                .thenApply(x -> cache.invalidateCache(segmentIndexPath));
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStream.java]: thenRun

File: controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java [hunk 2]
```diff
@@ -9,62 +9,87 @@
...
+            } else {
+                return Optional.of(parse(segmentTable, indexRecord.get().getSegmentOffset()));
+            }
         }
-        return Optional.of(parse(segmentTable, offset));
+
+        return Optional.empty();
     }
 
+    @SneakyThrows
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java]: `SneakyThrows(IOException.class)`

File: controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryRecord.java [hunk 3]
```diff
@@ -9,238 +9,173 @@
...
+     * @return returns history record immediately preceeding given record. If the given record is first record
+     * in the table then return empty.
+     */
+    public static Optional<HistoryRecord> fetchPrevious(final HistoryRecord record, final byte[] historyIndex, final byte[] historyTable) {
+        return readRecord(record.epoch - 1, historyIndex, historyTable, true);
     }
 
-    private static int tailLengthOffset(int segmentCount) {
-        return scaleTimeOffset(segmentCount) + Long.BYTES;
+    @SneakyThrows
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryRecord.java]: `SneakyThrows(IOException.class)`

And really, it can throw a legitimate IOException at you, so I don't understand why you want to suppress its declaration.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java [hunk 4]
```diff
@@ -9,62 +9,87 @@
...
-                toDouble(table, offset + 2 * Integer.BYTES + Long.BYTES),
-                toDouble(table, offset + 2 * Integer.BYTES + Long.BYTES + Double.BYTES));
+        InputStream bas = new ByteArrayInputStream(table, offset, table.length - offset);
+        return SERIALIZER.deserialize(bas);
     }
 
-    private static double toDouble(byte[] b, int offset) {
-        return Double.longBitsToDouble(BitConverter.readLong(b, offset));
+    @SneakyThrows
+    byte[] toByteArray() {
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java]: In order to avoid all this byte array copying everywhere, I recommend changing this to return `ArrayView` and keep using it until you really have no choice but copy it to a byte array. For instance, many APIs allow taking a byte array with offset + length, so no need for any additional copies.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 5]
```diff
@@ -71,111 +71,126 @@ public static Segment getSegment(final int number, final byte[] segmentTable) {
...
+                segments = new ArrayList<>();
+                // all segments from stream cut that have epoch >= this epoch
+                List<Integer> fromStreamCut = truncationRecord.getCutEpochMap().entrySet().stream()
+                        .filter(x -> x.getValue() >= record.getEpoch())
+                        .map(Map.Entry::getKey)
+                        .collect(Collectors.toList());
+
+                segments.addAll(fromStreamCut);
+                // put remaining segments as those that dont overlap with ones taken from streamCut.
+                segments.addAll(record.getSegments().stream().filter(x -> fromStreamCut.stream().noneMatch(y ->
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: 1. No need for a collector here. Simply invoke `.forEach(segments::add)` which will prevent the additional list creation.

2. Also, you are looping several times over `fromStreamCut` and invoking `getSegment(y, segmentIndex, segmentTable)`. I suggest you pre-cache these values in a local map.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 6]
```diff
@@ -308,23 +332,23 @@ public static long getSizeTillStreamCut(final byte[] indexTable, final byte[] hi
...
             final Segment segment,
-            final byte[] indexTable,
+            final byte[] historyIndex,
             final byte[] historyTable) {
-        Optional<HistoryRecord> historyRecordOpt = readEpochHistoryRecord(segment.getEpoch(), indexTable, historyTable);
+        Optional<HistoryRecord> historyRecordOpt = HistoryRecord.readRecord(segment.getEpoch(), historyIndex, historyTable, false);
         if (!historyRecordOpt.isPresent()) {
-            // cant compute predecessors because the creation event is not present in history table yet.
+            // cant compute predecessors because the segment creation entry is not present in history table yet.
             return new ArrayList<>();
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: `Collections.emptyList()`

here and below

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 7]
```diff
@@ -340,49 +364,65 @@ public static long getSizeTillStreamCut(final byte[] indexTable, final byte[] hi
...
+                                                    ByteArrayOutputStream indexStream) {
         IntStream.range(0, newRanges.size())
                 .forEach(
-                        newRange -> {
+                        x -> {
                             try {
-                                segmentStream.write(new SegmentRecord(startingSegmentNumber + newRange,
-                                        creationEpoch, timeStamp, newRanges.get(newRange).getKey(), newRanges.get(newRange).getValue())
+                                int offset = segmentStream.size();
+                                segmentStream.write(new SegmentRecord(startingSegmentNumber + x,
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: This is an excellent example of `toByteArray` being redundant. If you had returned `ArrayView`, you would have called `write(av.array(), av.arrayOffset(), av.length())` which would only copy the data once, vs allocating an array just so that you can copy it wholly.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java (hunk 5 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: > Also, you are looping several times over fromStreamCut and invoking getSegment(y, segmentIndex, segmentTable). I suggest you pre-cache these values in a local map.

getSegment is an O(1) fetch from the segment and index blobs. Its not a remote call.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/SegmentRecord.java]: done

File: controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryRecord.java (hunk 3 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryRecord.java]: Its a checked exception that we will have to handle everywhere else.

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 8]
```diff
@@ -276,6 +278,55 @@ private void handleStreamMetadataExists(final long timestamp, CompletableFuture<
...
+        Preconditions.checkNotNull(data);
+        Preconditions.checkNotNull(data.getData());
+
+        CompletableFuture<Void> result = new CompletableFuture<>();
+        synchronized (lock) {
+            if (segmentIndex == null) {
+                result.completeExceptionally(StoreException.create(StoreException.Type.DATA_NOT_FOUND,
+                        "Segment index for stream: " + getName()));
+            } else if (segmentIndex.getVersion().equals(data.getVersion())) {
+                segmentIndex = new Data<>(Arrays.copyOf(data.getData(), data.getData().length), data.getVersion() + 1);
```
[the remark this answers is not in the document]
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: done

**Comment by shiveshr** [comment]
@andreipaduroiu 

>    I thought we split this PR into two, when only the second one contained serialization changes. I see quite a bit of Versioned Serialization in here.

The two classes that we were changing (SegmentRecord and HistoryRecord) we updated their serialization here as well. For all other objects (around 10 of the remaining ones) we have a separate follow up PR to address it. 

>    I strongly recommend changing the toByteArray to something like toArrayView. There are countless cases where a new byte array is unnecessarily created & copied from somewhere just so that it is again copied somewhere else. ArrayView would prevent many of those copies from happening.

Done

**Comment by shiveshr** [comment]
[Use custom serialization with version on controller metadata](https://trello.com/c/rmd8xTsI/15-use-custom-serialization-with-version-on-controller-metadata)

**Comment by shiveshr** [comment]
[Use custom serialization with version on controller metadata](https://trello.com/c/rmd8xTsI/15-use-custom-serialization-with-version-on-controller-metadata)

**Comment by shiveshr** [comment]
[Use custom serialization with version on controller metadata](https://trello.com/c/rmd8xTsI/15-use-custom-serialization-with-version-on-controller-metadata)

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 9]
```diff
@@ -71,111 +72,126 @@ public static Segment getSegment(final int number, final byte[] segmentTable) {
...
-        }).orElse(Collections.emptyList());
+        }
+        return segments;
     }
 
-    public static void validateStreamCut(List<AbstractMap.SimpleEntry<Double, Double>> list) {
+    /**
+     * Method to validate a given stream Cut.
+     * A stream cut is valid if it covers the entire key space without any overlaps in ranges for segments that form the
+     * streamcut. It throws Invalid argument exception if the supplied stream cut does not satisfy the invariants.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: Add a @link to the exception reference.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java [hunk 10]
```diff
@@ -0,0 +1,49 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java]: Please do not reformat the license header.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+import io.pravega.common.io.serialization.RevisionDataOutput;
+import io.pravega.common.io.serialization.VersionedSerializer;
+import io.pravega.controller.store.stream.tables.HistoryRecord;
+
+import java.io.DataInput;
+import java.io.DataOutput;
+import java.io.IOException;
+import java.util.ArrayList;
+
+public class HistoryRecordSerializer extends VersionedSerializer.WithBuilder<HistoryRecord, HistoryRecord.HistoryRecordBuilder> {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java]: Where are you unit-testing the seriaization/deserialization? I think this is being exercised implicitly, and I'd rather see some explicit unit tests that focus on it alone, please.

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 12]
```diff
@@ -276,6 +278,56 @@ private void handleStreamMetadataExists(final long timestamp, CompletableFuture<
...
+    @Override
+    CompletableFuture<Data<Integer>> getSegmentIndex() {
+        synchronized (lock) {
+            if (this.segmentIndex == null) {
+                return Futures.failedFuture(StoreException.create(StoreException.Type.DATA_NOT_FOUND, getName()));
+            }
+
+            return CompletableFuture.completedFuture(copy(this.segmentIndex));
+        }
+
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: Eliminate unnecessary new line.

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 13]
```diff
@@ -289,8 +341,9 @@ private void handleStreamMetadataExists(final long timestamp, CompletableFuture<
 
     @Override
     CompletableFuture<Segment> getSegmentRow(int number) {
-        return getSegmentTable()
-                .thenApply(x -> TableHelper.getSegment(number, x.getData()));
+        return getSegmentIndex()
+            .thenCompose(segmentIndex -> getSegmentTable()
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: Indentation is incorrect.

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 14]
```diff
@@ -331,45 +385,47 @@ private void handleStreamMetadataExists(final long timestamp, CompletableFuture<
...
     }
 
     @Override
-    CompletableFuture<Void> updateIndexTable(Data<Integer> updated) {
+    CompletableFuture<Void> updateHistoryIndex(Data<Integer> updated) {
         Preconditions.checkNotNull(updated);
         Preconditions.checkNotNull(updated.getData());
 
         final CompletableFuture<Void> result = new CompletableFuture<>();
+        Data<Integer> copy = updatedCopy(updated);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: Currently, this copy is performed under a lock, but this PR is proposing to copy outside the lock. Could you justify why this change is correct?

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java [hunk 15]
```diff
@@ -610,6 +666,7 @@ private void handleStreamMetadataExists(final long timestamp, CompletableFuture<
     @Override
     CompletableFuture<Void> updateMarkerData(int segmentNumber, Data<Integer> data) {
         CompletableFuture<Void> result = new CompletableFuture<>();
+        Data<Integer> next = updatedCopy(data);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: Same here about copying under a lock.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 16]
```diff
@@ -170,11 +171,12 @@ public String getScopeName() {
     private CompletableFuture<StreamTruncationRecord> computeTruncationRecord(StreamTruncationRecord truncationRecord,
                                                                               Map<Integer, Long> streamCut) {
         log.debug("computing truncation for stream {}/{}", scope, name);
-        return getHistoryTableFromStore()
-                .thenCompose(history -> getSegmentTableFromStore()
-                        .thenCompose(segment -> getIndexTable()
-                                .thenApply(index -> TableHelper.computeTruncationRecord(index.getData(), history.getData(),
-                                        segment.getData(), streamCut, truncationRecord))));
+        return getHistoryIndexFromStore()
+                .thenCompose(historyIndex -> getHistoryTableFromStore()
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: I think it is better to align the beginning of the lines rather than cascading like this.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 17]
```diff
@@ -622,27 +640,33 @@ private long findSegmentSplitsMerges(List<Segment> referenceSegmentsList, List<S
...
         // take max(scaleTime, lastScaleTime + 1, System.currentTimeMillis)
-        long lastScaleTime = HistoryRecord.readLatestRecord(historyTable, true)
-                .map(HistoryRecord::getScaleTime).orElse(0L);
+        long lastScaleTime = TableHelper.getEpochScaleTime(activeEpoch, historyIndex, historyTable);
         long scaleEventTime = Math.max(System.currentTimeMillis(), scaleStartTime);
         long segmentCreationTimestamp = Math.max(scaleEventTime, lastScaleTime + 1);
 
-        final byte[] updated = TableHelper.updateSegmentTable(nextSegmentNumber, newEpoch,
-                segmentTable.getData(), newRanges, segmentCreationTimestamp);
+        // Note: if segment index was updated in an earlier attempt but segment was not, we need to overwrite previous index update!
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: `... overwrite the previous index update` it is missing `the`.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 18]
```diff
@@ -622,27 +640,33 @@ private long findSegmentSplitsMerges(List<Segment> referenceSegmentsList, List<S
...
+        // this is because new offsets may be different. we cannot update segment table before index because then
+        // we would not be able to read from segment table as we dont know the starting offsets for segments.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: `dont` -> `don't`

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 19]
```diff
@@ -695,35 +719,37 @@ private long findSegmentSplitsMerges(List<Segment> referenceSegmentsList, List<S
...
+                        .thenCompose(historyTable -> {
+                            CompletableFuture<Boolean> result = new CompletableFuture<>();
+
+                            if (TableHelper.isNewEpochCreated(historyIndex.getData(), historyTable.getData())) {
+                                deleteEpochNode(epoch)
+                                        .whenComplete((r, e) -> {
+                                            if (e != null) {
+                                                Throwable ex = Exceptions.unwrap(e);
+                                                if (ex instanceof StoreException.DataNotEmptyException) {
+                                                    // cant delete as there are transactions still running under epoch node
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: `cant` -> `can't`

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 20]
```diff
@@ -1138,17 +1168,18 @@ private void checkState(State currState, State expectedState) {
...
                         .thenCompose(historyTable -> {
-                            final HistoryRecord lastRecord = HistoryRecord.readLatestRecord(historyTable.getData(),
+                            final HistoryRecord lastRecord = HistoryRecord.readLatestRecord(historyIndex.getData(), historyTable.getData(),
                                     false).get();
 
                             // idempotent check
                             if (lastRecord.getEpoch() > activeEpoch) {
-                                boolean idempotent = lastRecord.isPartial() &&
-                                        lastRecord.getSegments().containsAll(createdSegments) && lastRecord.getEpoch() == newEpoch;
+                                boolean idempotent = lastRecord.isPartial() && lastRecord.getSegments().containsAll(createdSegments);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: This term has been removed `lastRecord.getEpoch() == newEpoch`, why?

File: controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java [hunk 21]
```diff
@@ -0,0 +1,52 @@
...
+import io.pravega.common.util.BitConverter;
+import lombok.Data;
+
+import java.util.Optional;
+
+@Data
+/**
+ * Class corresponding to a record/row in Index table.
+ * Each row is fixed size
+ * Row: [eventTime, pointer-into-history-table]
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java]: `eventTime` here is confusing, what do you mean with event time?

File: controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java [hunk 22]
```diff
@@ -71,111 +72,126 @@ public static Segment getSegment(final int number, final byte[] segmentTable) {
...
-                            .collect(Collectors.toList());
-
-                    segments.addAll(fromStreamCut);
-                    // put remaining segments as those that dont overlap with ones taken from streamCut.
-                    segments.addAll(record.getSegments().stream().filter(x -> fromStreamCut.stream().noneMatch(y ->
-                            getSegment(x, segmentTable).overlaps(getSegment(y, segmentTable))))
-                            .collect(Collectors.toList()));
-                }
+                // case 3: overlap between requested epoch and stream cut.
+                // take segments from stream cut that are from or aftergit re this epoch.
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/TableHelper.java]: `... from or after this epoch.`

File: controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java [hunk 23]
```diff
@@ -0,0 +1,52 @@
...
+ */
+public class HistoryIndexRecord {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java]: Are we supposed to be getting rid of `IndexRecord` in this PR? I don't see it being removed.

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java]: Index Record is replaced with HistoryIndexRecord

File: controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java (hunk 21 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/HistoryIndexRecord.java]: EpochCreationTime or scale time..  Will update the comment

File: controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java (hunk 14 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/InMemoryStream.java]: We are copying the input that we receive because it is mutable and outside the control of this class. 
We dont need to copy it within a lock though as what we want to protect under lock is when we flip the reference to this new copied object.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 16 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: This is because thenCompose is being called on the method call inside thenCompose block. 
This is done so that the value from each future is available at all those below it.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 20 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: it is already captured in the if condition `lastRecord.getEpoch() > activeEpoch`. 
Let me try to recollect if there was any other specific reason for the same though.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java (hunk 11 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java]: The unit test i had added for all serialization/deserialization will be included in the follow up PR.

File: controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java (hunk 10 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/tables/serializers/HistoryRecordSerializer.java]: Done
