### PR TITLE
Issue 2746: PravegaRequestProcessor should send an empty Read result before cancelling Read request.

### LINKED ISSUE #2746: PravegaRequestProcessor closes connection to idle/empty segments causing Readers to fail with RetriesExhaustedException.
**Problem description**

Read request to idle segments are canceled which intern causes PravegaRequestProcessor(PRP) to close the connection. Since it is an empty/idle segment the read calls are never returned and in due time the connection is closed by PRP. The client(reader) has no way of knowing the reason for connection drop and it retries connecting.
The reader tries to reconnect for the configured retry attempts(9) and when all the attempts fail throws a `RetriesExhaustedException`

Relevant log snippets:

[1] Client failing with RetriesExhaustedException.
```
controller_server_2018-07-07.1178.log:2018-07-07 13:33:38,297 116363017 [pool-8-thread-2] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
controller_server_2018-07-07.1178.log-java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
--
controller_server_2018-07-07.1178.log:2018-07-07 13:33:49,111 116373831 [pool-8-thread-4] ERROR c.e.n.h.t.w.readers.PravegaReader - Reader finished with Error
controller_server_2018-07-07.1178.log-java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
```

[2] 
The segment to which the connection failed multiple times...
```
2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
io.pravega.shared.protocol.netty.ConnectionFailedException: null
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)
controller_server_2018-07-07.1164.log:2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-4] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #9, timestamp=2018-07-07T13:23:34.773Z	
2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
io.pravega.shared.protocol.netty.ConnectionFailedException: null
        at io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor.connectionDropped(AsyncSegmentInputStreamImpl.java:60)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelUnregistered(ClientConnectionInboundHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:160)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1337)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:835)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:830)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)
controller_server_2018-07-07.1164.log:2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-3] DEBUG io.pravega.common.util.Retry - Retrying command. Retry #9, timestamp=2018-07-07T13:23:34.773Z
```

[3] There are two readers and both the readers have attempted to reconnect after a connection drop.
```
vagrant@ :/mnt/c/Sandeep/logs/1037/var/lib/mesos/slave/slaves/aede22df-d9ed-4f68-9f82-a4f9c7435e97-S2/frameworks/aede22df-d9ed-4f68-9f82-a4f9c7435e97-0005/executors/d4bf5662-de0d-4ace-8d1e-5fd164e67812/runs/8256a890-16da-4019-90dc-bac35220c096$ grep -r " Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118" ./
./controller_server_2018-07-07.1049.log:2018-07-07 11:58:17,905 110642625 [epollEventLoopGroup-5-7] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1049.log:2018-07-07 11:58:17,910 110642630 [epollEventLoopGroup-5-6] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1070.log:2018-07-07 12:13:21,360 111546080 [epollEventLoopGroup-5-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1070.log:2018-07-07 12:13:21,363 111546083 [epollEventLoopGroup-5-5] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1084.log:2018-07-07 12:23:22,954 112147674 [epollEventLoopGroup-5-5] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1084.log:2018-07-07 12:23:22,954 112147674 [epollEventLoopGroup-5-6] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1098.log:2018-07-07 12:33:24,476 112749196 [epollEventLoopGroup-5-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1098.log:2018-07-07 12:33:24,476 112749196 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1118.log:2018-07-07 12:48:26,663 113651383 [epollEventLoopGroup-5-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1118.log:2018-07-07 12:48:26,663 113651383 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1131.log:2018-07-07 12:58:28,255 114252975 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1131.log:2018-07-07 12:58:28,255 114252975 [epollEventLoopGroup-5-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1151.log:2018-07-07 13:13:31,300 115156020 [epollEventLoopGroup-5-5] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1151.log:2018-07-07 13:13:31,304 115156024 [epollEventLoopGroup-5-6] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1164.log:2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-3] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1164.log:2018-07-07 13:23:34,773 115759493 [epollEventLoopGroup-5-4] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1178.log:2018-07-07 13:33:38,294 116363014 [epollEventLoopGroup-5-1] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
./controller_server_2018-07-07.1178.log:2018-07-07 13:33:38,298 116363018 [epollEventLoopGroup-5-2] WARN  i.p.c.s.i.AsyncSegmentInputStreamImpl - Exception while reading from Segment : hulk/smallScale/1725.#epoch.1118
```

[4] Corresponding PRP logs for client errors mentioned @ [3]
The connection was closed due to `CancellationException` for a ReadRequest.
```
2018-07-07 11:58:17,904 111188479 [core-25] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 11:58:17,904 111188479 [core-25] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:13:21,352 112091927 [core-19] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:13:21,354 112091929 [core-19] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:23:22,952 112693527 [core-26] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:23:22,952 112693527 [core-26] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:33:24,474 113295049 [core-8] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:33:24,474 113295049 [core-8] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:48:26,660 114197235 [core-25] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:48:26,660 114197235 [core-25] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 12:58:28,249 114798824 [core-16] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0 
2018-07-07 12:58:28,250 114798825 [core-16] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:13:31,298 115701873 [core-19] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:13:31,299 115701874 [core-19] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:23:34,769 116305344 [core-18] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:23:34,769 116305344 [core-18] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:33:38,293 116908868 [core-24] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:33:38,293 116908868 [core-24] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
2018-07-07 13:36:24,952 117075527 [core-17] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
```

[5] PRP Logs with the stacktrace pointing to the reason for `CancellationException` 									
```									
pravega/pravega_segmentstore  STDOUT 2018-07-07 11:58:17,904 111188479 [core-25] ERROR i.p.s.s.h.h.PravegaRequestProcessor - => Error during operation: Read segment for segment: hulk/smallScale/1725.#epoch.1118 for requestId: 0
pravega/pravega_segmentstore  STDOUT java.util.concurrent.CancellationException: null
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.reading.ContainerReadIndex.closeIndex(ContainerReadIndex.java:384)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.reading.ContainerReadIndex.cleanup(ContainerReadIndex.java:251)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.close(StreamSegmentReadIndex.java:149)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.containers.MetadataCleaner.lambda$runOnceInternal$6(MetadataCleaner.java:155)
pravega/pravega_segmentstore  STDOUT    at io.pravega.segmentstore.server.containers.StreamSegmentContainer.notifyMetadataRemoved(StreamSegmentContainer.java:613)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
pravega/pravega_segmentstore  STDOUT    at java.lang.Thread.run(Thread.java:748)
pravega/pravega_segmentstore  STDOUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
pravega/pravega_segmentstore  STDOUT 2018-07-07 11:58:17,904 111188479 [core-25] INFO  i.p.s.s.h.h.PravegaRequestProcessor - Closing connection [id: 0xb3bcf962, L:/172.16.17.25:12345 - R:/172.16.17.23:47062] while performing Read segment due to null.
```								

**Problem location**
PravegaRequestProcessor

**Suggestions for an improvement**

Do not just drop a connection while cancelling a read request as the client has no way of know why the connection was dropped. Perhaps an emptyRead result should be sent before dropping the connection.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**

Ensure an empty `WireCommands.SegmentRead` is sent while cancelling pending read requests.

**Purpose of the change**
Fixes #2746

**What the code does**
On receiving a `CancellationException` for a read request ensure PravegaRequestProcessor sends and empty SegmentRead message.

**How to verify it**
All the existing tests and newly added tests should pass.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 1]
```diff
@@ -399,6 +400,17 @@ public void createSegment(CreateSegment createStreamsSegment) {
                 });
     }
 
+    private Void handleReadException(long readOffset, String segment, Throwable u) {
```
Comment (fpj) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: I think the reason why you are creating a separate `handleReadException` rather than deal with `CancellationException` in `handleException` is that you need to know that it is a `CancellationException` out of a read request and you don't want to handle generally `CancellationException` in `handleException`.

Assuming this reasoning is correct, `CancellationException` by itself is not giving enough information for us to handle the exception appropriately. The overall flow looks ok, but the idea of handling the exception separately is not aligned with the rest of the code in PRP. 

Two options I can think of to deal with this:
1- The exception that the segment store throws should have a narrower scope, e.g., `ReadCancellationException`.
2- In `handleReadResult`, we wrap `CancellationException` with something else, e.g., `ReadCancellationException` so that we can disambiguate in `handleException`.

The idea would be to catch and handle the exception in `handleException` rather than add this new method.

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java [hunk 2]
```diff
@@ -181,6 +182,32 @@ public void testReadSegmentEmptySealed() {
         verifyNoMoreInteractions(store);
     }
 
+    @Test(timeout = 20000)
+    public void testReadSegmentEmpty() {
```
Comment (fpj) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java]: Good test case.

Comment (shrids) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessorTest.java]: improved the test case name.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 1 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: ok, improved `handleException` based on the review comment.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 3]
```diff
@@ -421,6 +436,10 @@ private Void handleException(long requestId, String segment, String operation, T
             int containerId = ((ContainerNotFoundException) u).getContainerId();
             log.warn("Wrong host. Segment = '{}' (Container {}) is not owned. Operation = '{}').", segment, containerId, operation);
             connection.send(new WrongHost(requestId, segment, ""));
+        } else if ( u instanceof ReadCancellationException) {
+            log.info("Closing connection {} while reading segment {} due to CancellationException.", connection, segment);
+            connection.send(new SegmentRead(segment, requestId, true, false, EMPTY_BYTE_BUFFER));
+            connection.close();
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: I don't think closing the connection is actually needed with this reply added.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 4]
```diff
@@ -594,4 +613,13 @@ private Long ignoreSegmentSealed(Throwable ex) {
 
         return null;
     }
+
+    /**
+     * Custom exception to indicate a {@link CancellationException} during a Read segment operation.
+     */
+    private class ReadCancellationException extends IllegalStateException {
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Why does this extend IllegalState? Reads being canceled is not an illegal state. This could extend CancellationException, or RuntimeException.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java [hunk 5]
```diff
@@ -175,7 +176,7 @@ public void readSegment(ReadSegment readSegment) {
                     handleReadResult(readSegment, readResult);
                     readStreamSegment.reportSuccessEvent(timer.getElapsed());
                 })
-                .exceptionally(ex -> handleException(readSegment.getOffset(), segment, "Read segment", ex));
+                .exceptionally(ex -> handleException(readSegment.getOffset(), segment, "Read segment", wrapCancellationException(ex)));
```
Comment (tkaitchuck) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: I'm not sure this is the right solution. At the very least segemntStore's java doc should specify what occurs when TIMEOUT is reached. But in general it might be better for it to return the ReadResult such as it is without waiting further.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 3 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: yes, connection.close() is not required. Removed it.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 4 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: `java.util.concurrent.CancellationException` extends IllegalStateException. Changed it to extend RuntimeException.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 5 above)
Comment (fpj) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: My initial reaction to the PR changes was similar. I also felt that perhaps the exception out of the segment store was not being sufficiently precise, but the alternative I have given was to wrap it in PRP. I assumed that cancellation exception for a read out of the segment store can only be due to a timeout, but perhaps my assumption is incorrect?

In general, I don't think it hurts to have the segment store throwing a more precise exception because we never know whether we will need to throw something different in the future for that same call.

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: The Segment has been inactive for a while, so the segment store is evicting it from memory, hence closing its read index and cancelling all pending future reads. A Pending Future read does not qualify as "keeping it active" because, if that were the case, it would keep most segments active for no reason.

What is so imprecise about `CancellationException`? It means the future read has been cancelled due to internal system triggers. It does not mean it was cancelled due to an error. The same exception is thrown when the container is shutting down.

IMO, the behavior in this case is to go back to the client and figure out if the read is still needed. If so, then simply reinvoke it (from the client), as the segment may now live on another host.

Comment (fpj) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: @andreipaduroiu I think you are clarifying that cancellation exception only happens due to a timeout. Perhaps because it is an unchecked exception, it isn't documented in the javadoc, but the user of the API could incorrectly think that it is being cancelled due to an error. If it is not too inconvenient, I'd rather resolve the ambiguity by qualifying the cancellation exception.

If changing the exception raised isn't a good path, then at least clarify in the javadoc what happens when a timeout occurs, like @tkaitchuck suggested. Currently, the javadoc says:

```
* @param timeout           Timeout for the operation.
```

but it doesn't say what happens as a consequence of the timeout. From experience, we learned that it throws `CancellationException`, but it was still not clear if that's the only case until @andreipaduroiu chimed in.

Comment (andreipaduroiu) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Cancellation Exception happens due to the segment getting evicted or the container shutting down. Timeouts are not enforced in the segment store.

FYI, this is a CompletableFuture that's being waited upon. It should totally be expected that a Future be cancelled.

Comment (fpj) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Ok, so what I'm reading is that the handling of `CancellationException` should be uniform, and I think the recommendation so far is to return an empty `SegmentRead` result. But, I'm wondering why we can't simply be honest to the client and say that the request was cancelled. The client can decide whether to issue another read, throw an error up the call path, or something else. I'm not convinced that it is a good idea to mask it from the reader.

If this observation makes sense, then the follow-up question is how a client should treat a cancelled read request, is it always retryable?

**Comment by shrids** [comment]
[PravegaRequestProcessor should send an empty ReadResult when read requests are cancelled.](https://trello.com/c/iwbdLXlN/38-pravegarequestprocessor-should-send-an-empty-readresult-when-read-requests-are-cancelled)

**Comment by shrids** [comment]
[PravegaRequestProcessor should send an empty ReadResult when read requests are cancelled.](https://trello.com/c/iwbdLXlN/38-pravegarequestprocessor-should-send-an-empty-readresult-when-read-requests-are-cancelled)

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java (hunk 5 above)
Comment (shrids) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java]: Updated the java doc for `StreamSegmentStore.read()` and created issue https://github.com/pravega/pravega/issues/2748 for handling CancellationException due to Segment container shutdown.

File: segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java [hunk 6]
```diff
@@ -114,6 +114,7 @@
      * consume the read data. If the operation failed, the future will be failed with the causing exception.
      * @throws NullPointerException     If any of the arguments are null.
      * @throws IllegalArgumentException If any of the arguments are invalid.
+     * @throws java.util.concurrent.CancellationException If the segment container is shutting down or the segment is evicted from memory.
```
Comment (andreipaduroiu) [inline segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java]: This is incorrect. The `read` method itself does not throw this `CancellationException`. The CompletableFuture that is returned may be cancelled, in which case it will complete exceptionally with such an exception.

Please remove this line. You may add a blurb in the `@return` tag, however I find that redundant, since every `CompletableFuture` out there may be cancelled.

Comment (shrids) [reply segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/StreamSegmentStore.java]: ok, updated the `@return` tag of the javadoc.
