### PR TITLE
Issue 3721: Multicontroller test failure in system tests

### LINKED ISSUE #3721: Multicontroller system test is failing in docker swarm
**Problem description**
 Multicontroller test is failing in docker swarm, as the test is not deploying the bookies. Due to that segment store is not coming up. With the latest kVs changes, this test is ensuring segment store is running. This test fails consistently if the test is ran alone.
```
08:22:49  > Task :test:system:startSystemTestsWithDocker FAILED
08:22:49  
08:22:49  io.pravega.test.system.MultiControllerTest > classMethod FAILED
08:22:49      io.pravega.test.system.framework.TestFrameworkException: Unable to create service
08:22:49          at io.pravega.test.system.framework.services.docker.DockerBasedService.start(DockerBasedService.java:193)
08:22:49          at io.pravega.test.system.framework.services.docker.PravegaSegmentStoreDockerService.start(PravegaSegmentStoreDockerService.java:67)
08:22:49          at io.pravega.test.system.AbstractSystemTest.ensureSegmentStoreRunning(AbstractSystemTest.java:74)
08:22:49          at io.pravega.test.system.MultiControllerTest.initialize(MultiControllerTest.java:61)
08:22:49  
08:22:49          Caused by:
08:22:49          java.util.concurrent.TimeoutException
08:22:49              at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
08:22:49              at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
08:22:49              at io.pravega.test.system.framework.services.docker.DockerBasedService.lambda$start$18(DockerBasedService.java:189)
08:22:49              at io.pravega.common.Exceptions.handleInterrupted(Exceptions.java:115)
08:22:49              at io.pravega.test.system.framework.services.docker.DockerBasedService.start(DockerBasedService.java:189)
```

**Problem location**
System test of multicontroller

**Suggestions for an improvement**
Make sure test start bookies

### PR DESCRIPTION
**Pull request by anishakj**
Signed-off-by: anishakj <anisha.kj@dell.com>

**Change log description**  
 Start bookkeeper instances in Multicontrollertest initialization.

**Purpose of the change**  
Fixes #3721.

**What the code does**  
With Kvs changes, Multicontroller test is ensuring segment store is running, but the test was not starting bookie instances.  Now bookie instances are started in initialization.

**How to verify it**  
system tests should pass

### CODE REVIEW

**Comment by RaulGracia** [comment]
Now the build seems to work as expected. @anishakj, please remove all the changes related to logging and leave only the changes in `MultiControllerTest.java`.

**Comment by anishakj** [comment]
> Now the build seems to work as expected. @anishakj, please remove all the changes related to logging and leave only the changes in `MultiControllerTest.java`.

Removed the debugging logs added

**Comment by RaulGracia** [comment]
@anishakj as we discussed earlier, it would be great to get the feedback from @shrids about the behavior of `DockerBasedService.isRunning()` method when there is a Docker service with 0 replicas left in a test, as this was the main cause for problems in the subsequent tests executed after `MultiControllerTest`. Now this issue is fixed by leaving one instance at the end of `MultiControllerTest`, but maybe it is preferable to improve `isRunning()` method to properly handle situations in which a service has 0 replicas.

File: test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java [hunk 1]
```diff
@@ -140,6 +141,7 @@ public void multiControllerTest() throws ExecutionException, InterruptedExceptio
                     throwable -> throwable instanceof RetriesExhaustedException);
         }
 
+        Futures.getAndHandleExceptions(controllerService.scaleService(1), ExecutionException::new);
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: If the change in `isRunning()` is correct, we can remove this line.

Comment (anishakj) [reply test/system/src/test/java/io/pravega/test/system/MultiControllerTest.java]: Reverted that

**Comment by RaulGracia** [comment]
@anishakj the system test build with this branch had 25 test failures, so it looks that something is wrong with that change.

**Comment by anishakj** [comment]
> @anishakj the system test build with this branch had 25 test failures, so it looks that something is wrong with that change.

The change made in `isRunning` wont work for `scaleService(0)`

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 2]
```diff
@@ -73,22 +73,44 @@ public String getID() {
...
             //list the service with filter 'serviceName'
             Service.Criteria servicecriteria = Service.Criteria.builder().serviceName(serviceName).build();
             List<Service> serviceList = Exceptions.handleInterruptedCall(
                     () -> dockerClient.listServices(servicecriteria));
             log.info("Service list size {}", serviceList.size());
+            if (!serviceList.isEmpty()) {
+                long replicas = Exceptions.handleInterruptedCall(
+                        () -> dockerClient.inspectService(serviceList.get(0).id()).spec().mode().replicated().replicas());
+                log.info("Replicas {}", replicas);
+                if (replicas > 0 && isSynced() == true){
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: You can replace `isSynced() == true` by just `isSynced()`.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 3]
```diff
@@ -73,22 +73,44 @@ public String getID() {
...
+            log.error("Unable to list docker services", e);
+        }
+        return value;
+    }
+
+    public boolean isSynced() {
+        boolean value = false;
+        int taskRunningCount = 0;
+        try {
+            //list the service with filter 'serviceName'
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Please, according to the code guidelines comments starts with a space and caps.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 4]
```diff
@@ -73,22 +73,44 @@ public String getID() {
...
+                    return true;
+                }
+            } 
+        } catch (DockerException e) {
+            log.error("Unable to list docker services", e);
+        }
+        return value;
+    }
+
+    public boolean isSynced() {
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Is this method used outside this class? Otherwise this can be made private.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 5]
```diff
@@ -97,21 +119,22 @@ public boolean isRunning() {
...
+                log.info("isSynced:Replicas {}", replicas);
+                log.info("isSynced:Task running count {}", taskRunningCount);
                 if (((long) taskRunningCount) == replicas) {
                     return true;
                 }
             }
         } catch (DockerException e) {
             log.error("Unable to list docker services", e);
         }
+        log.info ("returning false from isSynced:");
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: This log message can be changed to something like `service is not synced` or similar. Moreover, if you are adding the prefix of `isSynced` to all the messages, add it here as well or remove it from the other ones.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 6]
```diff
@@ -97,21 +119,22 @@ public boolean isRunning() {
...
         return value;
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: If `value = false` and it is not changed, you can just remove the `value` parameter and return `false` here directly.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 7]
```diff
@@ -154,14 +177,15 @@ public boolean isRunning() {
     public CompletableFuture<Void> scaleService(final int instanceCount) {
         try {
             Preconditions.checkArgument(instanceCount >= 0, "negative value: %s", instanceCount);
+            log.info("in scaleservice and instancecount is {}", instanceCount);
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Please, remove all the log messages that you feel that are not needed after merging this PR. In the case you want to add new ones, please make them to start in caps and make them as clear as possible (e.g., `instancecount` -> `instance count`).

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 8]
```diff
@@ -184,11 +208,23 @@ public void stop() {
...
+            //list the service with filter 'serviceName'
+            Service.Criteria servicecriteria = Service.Criteria.builder().serviceName(serviceName).build();
+            List<Service> serviceList = Exceptions.handleInterruptedCall(
+                    () -> dockerClient.listServices(servicecriteria));
+            log.info("Service list size {}", serviceList.size());
+            if (!serviceList.isEmpty()) {
+                 String serviceId = serviceList.get(0).id();
+                 Service service = Exceptions.handleInterruptedCall(() -> dockerClient.inspectService(serviceId));     
+                 Exceptions.handleInterrupted(() -> dockerClient.updateService(serviceId, service.version().index(),serviceSpec));
+            }
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Please, put the `else` as `} else {`.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 9]
```diff
@@ -184,11 +205,22 @@ public void stop() {
...
     public void start(final boolean wait, final ServiceSpec serviceSpec) {
         try {
-            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterruptedCall(() -> dockerClient.createService(serviceSpec));
+            // List the service with filter 'serviceName'
+            Service.Criteria servicecriteria = Service.Criteria.builder().serviceName(serviceName).build();
+            List<Service> serviceList = Exceptions.handleInterruptedCall(
+                    () -> dockerClient.listServices(servicecriteria));
+            log.info("Service list size {}", serviceList.size());
+            if (!serviceList.isEmpty()) {
+                 String serviceId = serviceList.get(0).id();
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Can we avoid invoking dockerClient.listServices() to fetch the id ? 
If the id is not a constant then this code snippet of fetching id can be refactored out to a separate method.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 10]
```diff
@@ -72,10 +72,30 @@ public String getID() {
...
+        try {
+            // List the service with filter 'serviceName'
+            Service.Criteria servicecriteria = Service.Criteria.builder().serviceName(serviceName).build();
+            List<Service> serviceList = Exceptions.handleInterruptedCall(
+                    () -> dockerClient.listServices(servicecriteria));
+            log.info("Service list size {}", serviceList.size());
+            if (!serviceList.isEmpty()) {
+                long replicas = Exceptions.handleInterruptedCall(
+                        () -> dockerClient.inspectService(serviceList.get(0).id()).spec().mode().replicated().replicas());
+                log.info("Replicas {}", replicas);
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fetching the replica count can also be refactored to a separate method.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 2 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 3 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 4 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Changed to private

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 5 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 7 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 8 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 9 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: serviceId is not constant. Added separate method for fetching id and replicas.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 10 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 11]
```diff
@@ -63,23 +63,44 @@ public String getID() {
         try {
             List<Service> serviceList = Exceptions.handleInterruptedCall(
                     () -> dockerClient.listServices(criteria));
-            serviceId = serviceList.get(0).id();
+            log.info("Service list size {}", serviceList.size());
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: This change implies `getID()` can return a null value.
Also, looking at the code we can directly use the field `final String serviceName;` as the id, right? This would imply `getID()` directly returns the `serviceName`. 
The logic of fetching the docker specific id for the given `serviceName` using `com.spotify.docker.client.messages.swarm.Service#id` can be a helper function. This would simplify the code further.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 12]
```diff
@@ -94,31 +115,28 @@ public boolean isRunning() {
...
         }
-        return value;
+        log.info("Service is not synced");
+        return false;
     }
 
     CompletableFuture<Void> waitUntilServiceRunning() {
-        log.debug("IS RUNNING {}", isRunning());
-        return Futures.loop(() -> !isRunning(), //condition
+        log.debug("IS RUNNING {}", isSynced());
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: this log statement can be improved to include the service name too.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java [hunk 13]
```diff
@@ -184,11 +199,17 @@ public void stop() {
...
     public void start(final boolean wait, final ServiceSpec serviceSpec) {
         try {
-            ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterruptedCall(() -> dockerClient.createService(serviceSpec));
+            String serviceId = getID();
+            if (serviceId != null) {
+                 Service service = Exceptions.handleInterruptedCall(() -> dockerClient.inspectService(serviceId));
+                 Exceptions.handleInterrupted(() -> dockerClient.updateService(serviceId, service.version().index(), serviceSpec));
+            } else {
+                ServiceCreateResponse serviceCreateResponse = Exceptions.handleInterruptedCall(() -> dockerClient.createService(serviceSpec));
+                assertNotNull(serviceCreateResponse.id());
```
Comment (shrids) [inline test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Can we use `org.junit.Assert#assertNotNull(java.lang.String, java.lang.Object)`? This will simplify debugging.

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 11 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 12 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

File: test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java (hunk 13 above)
Comment (anishakj) [reply test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java]: Fixed

**Comment by anishakj** [comment]
There are only 3 failures seen in system tests, and are  not related to this PR
