### PR TITLE
Issue 3889: Improve test code for ControllerServiceImplTest to enable debugging and avoid false positives

### LINKED ISSUE #3889: Flaky test: testCreateStreamThrowsLockFailed
**Problem description**
The test was observed failing a couple of times. In one of the unsuccessful runs, I observed the following in the logs:

```
2019-06-04 23:25:48,105 284949 [testpool-4] DEBUG io.pravega.controller.task.TaskBase - Host=host, Tag=e058992c-ea2d-4fee-8fd7-50fb7e6408c0 acquired lock on resource Resource(string=scope1/locking)
2019-06-04 23:25:48,105 284949 [testpool-7] DEBUG io.pravega.controller.task.TaskBase - Host=host, Tag=e058992c-ea2d-4fee-8fd7-50fb7e6408c0 completed executing task on resource Resource(string=scope1/locking)
2019-06-04 23:25:48,106 284950 [testpool-2] DEBUG io.pravega.controller.task.TaskBase - Host=host, Tag=07ac51a5-1985-4b39-bbba-5d96a4adb7ed acquired lock on resource Resource(string=scope1/locking)
2019-06-04 23:25:48,106 284950 [testpool-7] DEBUG io.pravega.controller.task.TaskBase - Host=host, Tag=e058992c-ea2d-4fee-8fd7-50fb7e6408c0 unlock attempt completed on resource Resource(string=scope1/locking)
2019-06-04 23:25:48,107 284951 [testpool-13] DEBUG io.pravega.controller.task.TaskBase - Host=host, Tag=07ac51a5-1985-4b39-bbba-5d96a4adb7ed completed executing task on resource Resource(string=scope1/locking)
```

According to the test case, this scenario is not possible because the first thread and acquiring the lock and completing the task before the second thread has a chance to request the lock and throw lock failed, which is the desired behavior in this test case.

**Problem location**
Controller unit testing.

**Suggestions for an improvement**
Find the race and fix it.

### PR DESCRIPTION
**Pull request by fpj**
**Change log description**  
* Adds more log messages to test code to enable debugging in the case the issue hits again.

* Resets the latch variable once both threads have requested lock concurrently in TaskMetadataStoreForTests  implementations.

**Purpose of the change**  
Fixes #3889 

**What the code does**  
Even though the test failures have happened on Jenkins, I have not been able to reproduce the issue locally or on Jenkins even with branch builds. This PR is proposing two defensive changes:

- It adds more log messages so that we get a better sense of the flow in the case the problem hits again.
- It resets the latch variable once we have that both threads have requested the lock concurrently.

The changes are in both `ZKTaskMetadataStoreForTests` and  `InMemoryTaskMetadataStoreForTests`. 

It also adds the creation of scopes to the test case. The absence of calls to create the scope were introducing errors in the logs because the test case was trying to create streams on a non-existing scope. That is harmless in the context of the test case, but better to fix to avoid misleading errors in the logs.

**How to verify it**  
Build must succeed.

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java [hunk 1]
```diff
@@ -309,11 +309,16 @@ public void testCreateStreamThrowsLockFailed() {
         // Check that concurrent calls to create a stream throw FailedLockingException
         final ScalingPolicy policy = ScalingPolicy.fixed(2);
         final StreamConfiguration configuration = StreamConfiguration.builder().scalingPolicy(policy).build();
+
+        ResultObserver<CreateScopeStatus> result = new ResultObserver<>();
+        this.controllerService.createScope(ScopeInfo.newBuilder().setScope("locking-scope").build(), result);
```
Comment (RaulGracia) [inline controller/src/test/java/io/pravega/controller/server/v1/ControllerServiceImplTest.java]: Minor: please, make the scope name a variable to be used throughout the test case.
