### PR TITLE
Issue 5803: Flakey StreamMetrics test.

### LINKED ISSUE #5803: Sporadic test failure StreamMetricsTest.testStreamsAndScopesBasicMetricsTests
**Describe the bug**
Found the test `StreamMetricsTest.testStreamsAndScopesBasicMetricsTests` has been failing sporadically: https://github.com/pravega/pravega/pull/5744/checks?check_run_id=2025218244
```
io.pravega.test.integration.StreamMetricsTest > testStreamsAndScopesBasicMetricsTests FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.pravega.test.integration.StreamMetricsTest.testStreamsAndScopesBasicMetricsTests(StreamMetricsTest.java:226)
```

**To Reproduce**
Sporadic failure when executing `gradlew build`

**Expected behavior**
Make the test consistently passing.

**Screenshots**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by co-jo**
**Change log description**  
* Use the proper tag set when reading various meters.

**Purpose of the change**  
Fixes #5803.

**What the code does**  
* Minor clean-ups.
* Instead of relying on chance that we will return the expected metric, supply the *exact* tag set required to ensure the proper meter is returned.

Because we do not supply any tags, during this call `return Metrics.globalRegistry.find(metricsName).tags(tags).counter();` micrometer will fetch *all* meters (belonging to the appropriate type) with id `metricsName`. It has to make a choice which to return if there are several, so it simply chooses one at random:

```
    public Counter counter() {
        return findOne(Counter.class);
    }
   ...
    private <M extends Meter> M findOne(Class<M> clazz) {
        return meterStream()
                .filter(clazz::isInstance)
                .findAny()
                .map(clazz::cast)
                .orElse(null);
    }
```

The test failures of `StreamMetricsTest.testStreamsAndScopesBasicMetricsTests` were not because the value what not propagated to micrometer but because we were doing an assert on the wrong counter.

I observed this by adding some log statements before the failing assert:

```
 > 2021-03-11 20:27:21,836 780931 [Time-limited test] INFO  i.p.t.integration.StreamMetricsTest - Counters@@@: 2
 > 2021-03-11 20:27:21,847 780942 [Time-limited test] INFO  i.p.t.integration.StreamMetricsTest - counter: MeterId{name='pravega.controller.scope.create_failed', tags=[tag(host=fv-az182-967),tag(scope=_system),tag(stream=)]} 0.0
 > 2021-03-11 20:27:21,848 780943 [Time-limited test] INFO  i.p.t.integration.StreamMetricsTest - counter: MeterId{name='pravega.controller.scope.create_failed', tags=[tag(host=fv-az182-967),tag(scope=failedScope),tag(stream=)]} 1.0
 > 2021-03-11 20:27:21,849 780944 [Time-limited test] INFO  i.p.t.integration.StreamMetricsTest - actual counter: MeterId{name='pravega.controller.scope.create_failed', tags=[ta182-967),tag(scope=_system),tag(stream=)]} 0.0
```
**How to verify it**  

* Run the integration tests.

### CODE REVIEW

File: test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java [hunk 1]
```diff
@@ -211,29 +212,35 @@ public void testStreamsAndScopesBasicMetricsTests() throws Exception {
...
+        StreamMetrics.getInstance().createStreamFailed(failedScope, failedStream);
+        StreamMetrics.getInstance().deleteStreamFailed(failedScope, failedStream);
+        StreamMetrics.getInstance().updateStreamFailed(failedScope, failedStream);
+        StreamMetrics.getInstance().truncateStreamFailed(failedScope, failedStream);
+        StreamMetrics.getInstance().sealStreamFailed(failedScope, failedStream);
+        StreamMetrics.getInstance().createReaderGroupFailed(failedRG, failedRG);
+        StreamMetrics.getInstance().deleteReaderGroupFailed(failedRG, failedRG);
+        StreamMetrics.getInstance().updateReaderGroupFailed(failedRG, failedRG);
+        StreamMetrics.getInstance().updateTruncationSCFailed(failedRG, failedRG);
+        assertEquals(1, (long) MetricRegistryUtils.getCounter(MetricsNames.CREATE_SCOPE_FAILED, failedScopeTags).count());
```
Comment (RaulGracia) [inline test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java:233]: Why assertions do not fail for any of the previous assertions? They are not using tags to fetch the right metrics neither. Is it just a matter of luck?

**Review by RaulGracia — COMMENTED** [review]
Looks good, just one question.

File: test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java (hunk 1 above)
Comment (co-jo) [reply test/integration/src/test/java/io/pravega/test/integration/StreamMetricsTest.java:233]: I believe some changed must have been introduced recently that caused a metric with id `MetricsName.CREATE_SCOPE_FAILED` to be created during one of the other tests, and is not cleaned up in time. I added another log statement at the very beginning of the test and shows that 

```
 > 2021-03-11 20:27:21,847 780942 [Time-limited test] INFO  i.p.t.integration.StreamMetricsTest - counter: MeterId{name='pravega.controller.scope.create_failed', tags=[tag(host=fv-az182-967),tag(scope=_system),tag(stream=)]} 0.0
```

exists at the beginning of the test in failing runs. So before it is likely there was only one metric with said id, so it always ended up returning the expected metric.

**Review by RaulGracia — APPROVED** [review]
