### PR TITLE
Issue 1376: Multi reader and writer test case with failover scenarios

### LINKED ISSUE #1376: Implement a simple Reader Writer Test case with controller, segmentstore fail over scenarios
**Problem description**
This task is to implement a test case with some readers, writers writing and reading a  fixed number of events in the following cases:
1. 2 controller, SSS instances
2. With 1 SSS instance failure
3. With 1 controller instance failure
4. With 1 controller, 1 SSS instances down

**Problem location**
System Tests

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
A simple test case which does the following :
Setup : 3 Controller, 3 SSS instances running.
Step 1. 5 writers, 5 readers  writing and reading the events in parallel.  
Step 2. Failover cases will get executed in the below order : -
a. SSS failover
b. controller failover
c. SSS and controller failover
Step3 : Event read count and even write count  after failover are compared with previous values(before failover) , to ensure reads and writes are happening inspite of crashes.
Step 4: At the end, we wait for read counts to be matched with write counts and then stop the writers, readers.

**Purpose of the change**
Adding new system test cases to cover failover.

**What the code does**
Fixes #1376

**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+        //2. Start 3 bookies
+        Service bkService = new BookkeeperService("bookkeeper", zkUri);
+        if (!bkService.isRunning()) {
+            bkService.start(true);
+        }
+        List<URI> bkUris = bkService.getServiceDetails();
+        log.debug("Bookkeeper service details: {}", bkUris);
+
+        //3. start 2 instances of pravega controller
+        Service conService = new PravegaControllerService("controller", zkUri, 2, 0.1, 700.0);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: No need to hard code the CPU and memory, we can use the `scaleService` api to scale it to two instances.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+        if (!conService.isRunning()) {
+            conService.start(true);
+        }
+        List<URI> conUris = conService.getServiceDetails();
+        log.debug("Pravega Controller service  details: {}", conUris);
+
+        //4.start 2 instances of pravega segmentstore
+        Service segService = new PravegaSegmentStoreService("segmentstore", zkUri, conUris.get(0), 2, 0.1, 1000.0);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: remove hardcoding of cpus and memory, `scaleServiceAPI ` can be used.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 3]
```diff
@@ -0,0 +1,267 @@
...
+        log.info("Pravega Controller service instance details: {}", conURIs);
+
+        // Verify segment stores is running.
+        segmentStoreInstance = new PravegaSegmentStoreService("segmentstore", zkUri, conURIs.get(0), 2, 0.1, 1000.0);
+        Assert.assertTrue(segmentStoreInstance.isRunning());
+        log.info("Pravega segment store instance details: {}", segmentStoreInstance.getServiceDetails());
+    }
+
+    @Test(timeout = 600000)
+    public void multiReaderWriterTest() throws InterruptedException, URISyntaxException, ExecutionException  {
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: we can use throws Exception.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+        log.info("Test with 1 controller  and 1 SSS instance down");
+        readWriteTest();
+    }
+
+    private void readWriteTest() throws InterruptedException, ExecutionException {
+
+        String scope = "testMultiReaderWriterScope" + new Random().nextInt(Integer.MAX_VALUE);
+        String readerGroupName = "testMultiReaderWriterReaderGroup" + new Random().nextInt(Integer.MAX_VALUE);
+
+        //20  readers -> 20 stream segments ( to have max read parallelism)
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: The number of segments in the stream is 5, right?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+        URI zkUri = zkUris.get(0);
+
+        // Verify controller is running.
+        controllerInstance = new PravegaControllerService("controller",  zkUri, 2, 0.1, 700.0);
+        Assert.assertTrue(controllerInstance.isRunning());
+        List<URI> conURIs = controllerInstance.getServiceDetails();
+        log.info("Pravega Controller service instance details: {}", conURIs);
+
+        // Verify segment stores is running.
+        segmentStoreInstance = new PravegaSegmentStoreService("segmentstore", zkUri, conURIs.get(0), 2, 0.1, 1000.0);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: use `getControllerURI()` method?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 6]
```diff
@@ -0,0 +1,267 @@
...
+        Boolean createStreamStatus = controller.createStream(config).get();
+        log.debug("Create stream status {}", createStreamStatus);
+         eventsReadFromPravega = new ConcurrentLinkedQueue<>();
+
+         //stopWriteFlag = new AtomicBoolean(false);
+         stopReadFlag = new AtomicBoolean(false);
+         eventData = new AtomicLong(); //data used by each of the writers.
+         eventReadCount = new AtomicLong(); // used by readers to maintain a count of events.
+
+        log.info("events read from pravega {}", eventsReadFromPravega);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: it is empty here, we could remove this log statement . Formatting also needs to be updated.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 7]
```diff
@@ -0,0 +1,267 @@
...
+
+        //create 20 readers
+        log.info("creating {} readers", NUM_READERS);
+        List<CompletableFuture<Void>> readerList = new ArrayList<>();
+        for (int i = 0; i < NUM_READERS; i++) {
+            log.info("starting reader{}", i);
+            readerList.add(startReader("reader"+i, clientFactory, readerGroupName,
+                    eventsReadFromPravega, eventData, eventReadCount, stopReadFlag));
+        }
+        while (NUM_EVENTS != eventsReadFromPravega.size()) {
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: We need to wait until all writers have finished execution and only then check the number of events read.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 8]
```diff
@@ -0,0 +1,267 @@
...
+            Thread.sleep(5);
+        }
+        stopReadFlag.set(true);
+
+        log.info("All writers have stopped. Setting Stop_Read_Flag. Event Written Count:{}, Event Read " +
+                    "Count: {}", eventData.get(), eventsReadFromPravega.size());
+        //stop reading when no. of reads= no. of writes
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: We need to check for duplicates too.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java [hunk 9]
```diff
@@ -0,0 +1,267 @@
...
+                    new JavaSerializer<Long>(),
+                    EventWriterConfig.builder().build());
+            try {
+                for (int i = 0; i < 1000; i++) {
+                       long value = data.incrementAndGet();
+                       log.debug("writing event {}", value);
+                       writer.writeEvent(String.valueOf(value), value);
+                }
+                } catch (Throwable e) {
+                    log.warn("test exception writing events: {}", e);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: any exception here should fail the test, right?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 1 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 2 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 5 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: `getControllerURI()` returns only 1 URI of controller.
Here, I have 2 instances.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 3 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 4 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: fixed

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 6 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: Formatted

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 7 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: added to wait upon a list of completable futures

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 8 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java (hunk 9 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterTest.java]: yes, fixed

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 10]
```diff
@@ -0,0 +1,277 @@
...
+        readWriteTest();
+
+        //scale down 1 instance of both controller, SSS
+        segmentStoreInstance.scaleService(1, true);
+        Thread.sleep(60000);
+        log.info("Test with 1 controller  and 1 SSS instance down");
+        readWriteTest();
+    }
+
+    private void readWriteTest() throws InterruptedException, ExecutionException {
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: I don't see any cleanup being done here. The writers and readers should be closed and the stream/reader group should be deleted afterwards.

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 11]
```diff
@@ -0,0 +1,262 @@
...
+            this.server.startListening();
+
+            // 3. Start  controller service
+            this.controllerWrapper = new ControllerWrapper(zkTestServer.getConnectString(), false,
+                    controllerPort, serviceHost, servicePort, containerCount);
+            this.controllerWrapper.awaitRunning();
+            this.controller = controllerWrapper.getController();
+        } catch (Exception e) {
+            log.error("Error during setup", e);
+            throw e;
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Is it better to rethrow or assert fail?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 12]
```diff
@@ -0,0 +1,262 @@
...
+        log.info("Create stream status {}", createStreamStatus);
+
+        eventsReadFromPravega = new ConcurrentLinkedQueue<>();
+        stopReadFlag = new AtomicBoolean(false);
+        eventData = new AtomicLong(); //data used by each of the writers.
+        eventReadCount = new AtomicLong(); // used by readers to maintain a count of events.
+
+        ClientFactory clientFactory = new ClientFactoryImpl(scope, controller);
+        //start writing events to the stream with 5 writers
+        log.info("creating {} writers", NUM_WRITERS);
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: The description of the pull request says 20, but here we are running 5.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 13]
```diff
@@ -0,0 +1,262 @@
...
+import static java.util.concurrent.TimeUnit.SECONDS;
+import static org.junit.Assert.assertEquals;
+
+@Slf4j
+public class ReadWriteTest {
+
+    private static final String STREAM_NAME = "testMultiReaderWriterStream" + new Random().nextInt(Integer.MAX_VALUE);
+    private static final int NUM_WRITERS = 5;
+    private static final int NUM_READERS = 5;
+    private static final long NUM_EVENTS = 500;
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: The description of the pull request says 1000.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 14]
```diff
@@ -0,0 +1,262 @@
...
+            if (this.zkTestServer != null) {
+                this.zkTestServer.close();
+                this.zkTestServer = null;
+            }
+        } catch (Exception e) {
+            log.warn("Exception while tearing down", e);
+        }
+    }
+
+    @Test(timeout = 600000)
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Do we really need 10 minutes or could we timeout earlier?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 15]
```diff
@@ -0,0 +1,262 @@
...
+                    }
+                } catch (ReinitializationRequiredException e) {
+                    log.warn("Test Exception while reading from the stream", e);
+                    break;
+                }
+            }
+            reader.close();
+        });
+    }
+
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Unnecessary new lines.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 16]
```diff
@@ -0,0 +1,307 @@
...
+        List<CompletableFuture<Void>> readerList = new ArrayList<>();
+        String readerName = "reader" + new Random().nextInt(Integer.MAX_VALUE);
+        //start reading events
+        for (int i = 0; i < NUM_READERS; i++) {
+            log.info("starting reader{}", i);
+            readerList.add(startReader(readerName + i, clientFactory, readerGroupName,
+                    eventsReadFromPravega, eventData, eventReadCount, stopReadFlag));
+        }
+
+        Thread.sleep(50);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Why do we need this sleep call?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 17]
```diff
@@ -0,0 +1,307 @@
...
+
+        log.info("All writers have stopped. Setting Stop_Read_Flag. Event Written Count:{}, Event Read " +
+                "Count: {}", eventData.get(), eventsReadFromPravega.size());
+        assertEquals(NUM_EVENTS, eventsReadFromPravega.size());
+        assertEquals(NUM_EVENTS, new TreeSet<>(eventsReadFromPravega).size()); //check unique events.
+        //stop reading when no. of reads= no. of writes
+        log.debug("test {} succeed", "multiReaderWriterTest");
+
+        //seal a stream
+        CompletableFuture<Boolean> sealsStreamStatus = controller.sealStream(scope, STREAM_NAME);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Typo in `sealsStreamStatus`.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 18]
```diff
@@ -0,0 +1,307 @@
...
+
+    }
+
+    private CompletableFuture<Void> startNewWriter(final AtomicLong data,
+                                                   final ClientFactory clientFactory) {
+        return CompletableFuture.runAsync(() -> {
+            final EventStreamWriter<Long> writer = clientFactory.createEventWriter(STREAM_NAME,
+                    new JavaSerializer<Long>(),
+                    EventWriterConfig.builder().build());
+            for (int i = 0; i < 1000; i++) {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Should we have another static variable for this number of events and make `NUM_EVENTS` a function of that value?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 19]
```diff
@@ -0,0 +1,307 @@
...
+    }
+
+    @After
+    public void tearDown() {
+        controllerInstance.stop();
+        segmentStoreInstance.stop();
+    }
+
+    @Test(timeout = 600000)
+    public void multiReaderWriterWithFailOverTest() throws Exception {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: What about a test case that fails a controller instance?

**Comment by fpj** [comment]
@shrids @tkaitchuck could you either +1 or make further comments to this pull request, please?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 20]
```diff
@@ -0,0 +1,307 @@
...
+
+        log.info("Test with 2 controller, SSS instances running and without a failover scenario");
+        readWriteTest();
+
+        //scale down SSS by 1 instance
+        segmentStoreInstance.scaleService(1, true);
+        Thread.sleep(60000);
+        log.info("Test with 1 SSS instance down");
+        readWriteTest();
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Answering to the above comment:
The same method readWriteTest() is called multiple times after different failovers.
L144-> test with 2SSS, 2 controller instances (2S,2C)
L150-> test with 1SSS failover(2S,2C)->(1S,2C)
L158-> test with 1 controller failover(1S,2C)->(2S,2C)->(2S,1C)
L164-> test with 1 controller, 1SSS instance down (2S,1C)->(1S,1C).
*(A,B) -> A- #instances of pravega Segmentstore service , B- #instances of pravega controller service.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 11 above)
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Assert fail eats up the real exception and stack trace, the `log` statement will not appear in the build logs, so we have no debug information if test fails here. Hence we should rethrow, or better, not catch the exception because we are not doing anything useful with it.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 21]
```diff
@@ -0,0 +1,262 @@
...
+            if (this.server != null) {
+                this.server.close();
+                this.server = null;
+            }
+            if (this.zkTestServer != null) {
+                this.zkTestServer.close();
+                this.zkTestServer = null;
+            }
+        } catch (Exception e) {
+            log.warn("Exception while tearing down", e);
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Could we rethrow the exception, or avoid catching it, because the log statement shall not appear in debug logs.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 22]
```diff
@@ -0,0 +1,262 @@
...
+        for (i = 0; i < NUM_READERS; i++) {
+            log.info("starting reader{}", i);
+            readerList.add(startReader(readerName + i, clientFactory, readerGroupName,
+                    eventsReadFromPravega, eventData, eventReadCount, stopReadFlag));
+        }
+
+        log.info("online readers {}", readerGroupManager.getReaderGroup(readerGroupName).getOnlineReaders());
+
+        //wait for writers completion
+        for (i = 0; i < writerList.size(); i++) {
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Instead of the loop, try using `FutureHelpers.allOf(writerList)` to have the same effect.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 23]
```diff
@@ -0,0 +1,262 @@
...
+            log.info("get on writer list {} ", writerList.get(i).get());
+            CompletableFuture.allOf(writerList.get(i));
+        }
+
+        // wait for reads = writes
+        while (NUM_EVENTS != eventsReadFromPravega.size()) {
+            Thread.sleep(5);
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: What is the purpose of this `Thread.sleep`?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 24]
```diff
@@ -0,0 +1,262 @@
...
+        return CompletableFuture.runAsync(() -> {
+            final EventStreamReader<Long> reader = clientFactory.createReader(id,
+                    readerGroupName,
+                    new JavaSerializer<Long>(),
+                    ReaderConfig.builder().build());
+            log.info("exit flag before reading {}", exitFlag.get());
+            log.info("readcount before reading {}", readCount.get());
+            log.info("write count before reading {}", writeCount.get());
+
+            while (!(exitFlag.get() && readCount.get() == writeCount.get())) {
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: `exitFlag` is not really required here, why not just have the condition `while (readCount.get() <= writeCount.get())`?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 25]
```diff
@@ -0,0 +1,262 @@
...
+                    log.info("writing event {}", value);
+                    writer.writeEvent(String.valueOf(value), value);
+                    writer.flush();
+                } catch (Throwable e) {
+                    log.warn("test exception writing events: {}", e);
+                    break;
+                }
+            }
+            writer.close();
+
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Redundant new line.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 26]
```diff
@@ -0,0 +1,262 @@
...
+                    new JavaSerializer<Long>(),
+                    EventWriterConfig.builder().build());
+            for (int i = 0; i < 100; i++) {
+                try {
+                    long value = data.incrementAndGet();
+                    log.info("writing event {}", value);
+                    writer.writeEvent(String.valueOf(value), value);
+                    writer.flush();
+                } catch (Throwable e) {
+                    log.warn("test exception writing events: {}", e);
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: It may not be a good idea to gobble exception here.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 27]
```diff
@@ -0,0 +1,262 @@
...
+                    final Long longEvent = reader.readNextEvent(SECONDS.toMillis(60)).getEvent();
+                    log.info("reading event {}", longEvent);
+                    if (longEvent != null) {
+                        //update if event read is not null.
+                        readResult.add(longEvent);
+                        readCount.incrementAndGet();
+                    }
+                } catch (ReinitializationRequiredException e) {
+                    log.warn("Test Exception while reading from the stream", e);
+                    break;
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: May not be a good idea to gobble exception here.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 28]
```diff
@@ -0,0 +1,262 @@
...
+
+    @Test(timeout = 600000)
+    public void multiReaderWriterWithFailOverTest() throws Exception {
+        for (i = 0; i < 2; i++) {
+            readWriteTest(i);
+        }
+        log.info(" all tests are successful");
+    }
+
+    private void readWriteTest(int i) throws InterruptedException, ExecutionException {
```
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Can we share this method across integration test and system test?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 24 above)
Comment (bhargav-gulavani) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Ignore the previous comment. I understand `exitFlag` is useful, and it ensures premature termination of readers while writers are still writing events.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 11 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Done. not catching the exception.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 12 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Yes, updated.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 13 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Yes, updated.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 14 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: No, 5 mins will be sufficient. Reduced to  300s

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 15 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 16 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Not needed. Removed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 17 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Fixed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 18 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Yes, added one 
```private static final int NUM_EVENTS_BY_WRITER = 1000;```

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 21 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Not catching.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 22 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: done.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 23 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Waiting for  #total no. of events written = #events read and then  set stopReadFlag to true(stop reading events).

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 25 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: fixed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 29]
```diff
@@ -0,0 +1,377 @@
...
+        if (!conService3.isRunning()) {
+            conService3.start(true);
+        }
+
+        List<URI> conUris3 = conService3.getServiceDetails();
+        log.debug("Pravega Controller service instance3  details: {}", conUris3);
+
+
+        //4.start 2 instances of pravega segmentstore
+        Service segService1 = new PravegaSegmentStoreService("segmentstore1", zkUri, conUris1.get(0));
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: We should pass pravega://controllerURI  to all instances of the SSS service.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 30]
```diff
@@ -0,0 +1,377 @@
...
+        //20  readers -> 20 stream segments ( to have max read parallelism)
+        ScalingPolicy scalingPolicy = ScalingPolicy.fixed(20);
+        StreamConfiguration config = StreamConfiguration.builder().scope(scope)
+                .streamName(STREAM_NAME).scalingPolicy(scalingPolicy).build();
+
+        //get Controller Uri
+        Service conService = new PravegaControllerService("controller1", null);
+        List<URI> ctlURIs = conService.getServiceDetails();
+        URI controllerUri = ctlURIs.get(0);
+        Controller controller = getController(controllerUri);
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: looks like only controller1 is being used here, so controller2 and controller3 failure will have no effect on the client.
To try to use all controllers you need to use tcp://uri1,uri2,ur3, or pravega:// urls; see MultiControllerTest.java for how this is constructed.

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

**Comment by Prabha-Veerubhotla** [comment]
@fpj @shrids @skrishnappa @bhargav-gulavani @tkaitchuck  please check the updated code.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 31]
```diff
@@ -0,0 +1,432 @@
...
+        log.info("sealing stream {}", STREAM_NAME);
+        assertTrue(sealStreamStatus.get());
+        CompletableFuture<Boolean> sealStreamStatus1 = controller.sealStream(scope, "_RG" + readerGroupName);
+        log.info("sealing stream {}", "_RG" + readerGroupName);
+        assertTrue(sealStreamStatus1.get());
+        //delete all streams
+        CompletableFuture<Boolean> deleteStreamStatus = controller.deleteStream(scope, STREAM_NAME);
+        log.info("deleting stream {}", STREAM_NAME);
+        assertTrue(deleteStreamStatus.get());
+        CompletableFuture<Boolean> deleteStreamStatus1 = controller.deleteStream(scope, "_RG" + readerGroupName);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: `ReaderGroupManager.deleteReaderGroup()` api can be used.

Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 32]
```diff
@@ -0,0 +1,423 @@
...
+        for (int i = 0; i < NUM_EVENTS_BY_WRITER; i++) {
+            try {
+                long value = data.incrementAndGet();
+                log.debug("Writing event {}", value);
+                writer.writeEvent(String.valueOf(value), value);
+            } catch (Throwable e) {
+                log.warn("Test exception writing events: {}", e);
+                break;
+            }
+        }
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: include a writer.flush() before exiting this function

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 33]
```diff
@@ -0,0 +1,423 @@
...
+                    readerGroupName,
+                    new JavaSerializer<Long>(),
+                    ReaderConfig.builder().build());
+            readerList.add(reader);
+        }
+
+        log.info("Test with 2 controller, SSS instances running and without a failover scenario");
+        // start writing asynchronously
+        CompletableFuture<Void> writerFuture = CompletableFuture.runAsync(() -> {
+            writerList.forEach(writer -> startWriting(eventData, writer));
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: The writers are executed one after another and not in parallel. Is this the intent? if yes then a single writer should suffice.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 34]
```diff
@@ -0,0 +1,423 @@
...
+        });
+        //start reading asynchronously
+        CompletableFuture<Void> readerFuture = CompletableFuture.runAsync(() -> {
+            readerList.forEach(reader -> startReading(eventsReadFromPravega, eventData, eventReadCount, stopReadFlag, reader));
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Same as the writers, if we want parallel readers we may have to create List<CompletableFuture>

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 35]
```diff
@@ -0,0 +1,423 @@
...
+        log.info("All writers have stopped. Setting Stop_Read_Flag. Event Written Count:{}, Event Read " +
+                "Count: {}", eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), new TreeSet<>(eventsReadFromPravega).size()); //check unique events.
+        log.debug("{} with 2 controller, 2 SSS instances succeeds", "multiReaderWriterTest");
+
+        //scale down 1 SSS instance
+        segmentStoreInstance.scaleService(2, true);
+        Thread.sleep(60000);
+        log.info("Scaling down  1 SSS instance");
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: 2 SSS

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 36]
```diff
@@ -0,0 +1,423 @@
...
+        stopReadFlag.set(true);
+        //wait for readers completion
+        readerFuture.get();
+        log.info("All writers have stopped. Setting Stop_Read_Flag. Event Written Count:{}, Event Read " +
+                "Count: {}", eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), new TreeSet<>(eventsReadFromPravega).size()); //check unique events.
+        log.debug("{} with 2 controller, 2 SSS instances succeeds", "multiReaderWriterTest");
+
+        //scale down 1 SSS instance
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: 2 SSS

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 37]
```diff
@@ -0,0 +1,423 @@
...
+        stopReadFlag.set(true);
+        //wait for readers completion
+        readerFuture1.get();
+        log.info("All writers have stopped. Setting Stop_Read_Flag. Event Written Count:{}, Event Read " +
+                "Count: {}", eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), eventsReadFromPravega.size());
+        assertEquals(eventData.get(), new TreeSet<>(eventsReadFromPravega).size()); //check unique events.
+        log.debug("{} with SSS failover succeeds", "multiReaderWriterTest");
+
+        //scale down 1 controller instance
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: 2 controllers

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 38]
```diff
@@ -0,0 +1,423 @@
...
+        Thread.sleep(60000);
+        log.info("Test with controller failover");
+
+        eventsReadFromPravega = new ConcurrentLinkedQueue<>();
+        stopReadFlag.set(false);
+        eventData = new AtomicLong(); //data used by each of the writers.
+        eventReadCount = new AtomicLong(); // used by readers to maintain a count of events.
+
+        // start writing asynchronously
+        CompletableFuture<Void> writerFuture2 = CompletableFuture.runAsync(() -> {
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: The readers and writers test code is repeated for every scenario, this code can be reused by moving to a common function.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 39]
```diff
@@ -0,0 +1,252 @@
...
+            readerList.add(startNewReader(readerName + i, clientFactory, readerGroupName,
+                    eventsReadFromPravega, eventData, eventReadCount, stopReadFlag));
+        }
+        log.info("Online readers {}", readerGroupManager.getReaderGroup(readerGroupName).getOnlineReaders());
+
+        //wait for writers completion
+        FutureHelpers.allOf(writerList);
+        // wait for reads = writes
+        while (TOTAL_NUM_EVENTS != eventsReadFromPravega.size()) {
+            Thread.sleep(5);
```
Comment (skrishnappa) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: This sleep here can be replaced with thread wait/notify mechanism. wait() on an object here. Any reader which hits the condition(TOTAL_NUM_EVENTS != eventsReadFromPravega.size()) can notify() the object

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 40]
```diff
@@ -0,0 +1,423 @@
...
+        });
+        //start reading asynchronously
+        CompletableFuture<Void> readerFuture = CompletableFuture.runAsync(() -> {
+            readerList.forEach(reader -> startReading(eventsReadFromPravega, eventData, eventReadCount, stopReadFlag, reader));
+        });
+        //wait for writers completion
+        writerFuture.get();
+        //wait till #.reads = #.writes
+        while (NUM_EVENTS != eventsReadFromPravega.size()) {
+            Thread.sleep(5);
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: This sleep here can be replaced with thread wait/notify mechanism

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 32 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 38 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: moved to readWriteTest()

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 37 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Fixed. `//Scale down controller instances to 2`

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 35 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done `log.info("Scaling down SSS instances from 3 to 2");`

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 36 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done `//Scale down SSS instances to 2`

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 34 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 33 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 41]
```diff
@@ -0,0 +1,423 @@
...
+        log.debug("Pravega Controller service  details: {}", conUris);
+
+        // Fetch all the RPC endpoints and construct the client URIs.
+        final List<String> uris = conUris.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+                .collect(Collectors.toList());
+
+        URI controllerURI = URI.create("tcp://" + String.join(",", uris));
+        log.info("Controller Service direct URI: {}", controllerURI);
+
+        //4.start 2 instances of pravega segmentstore
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 42]
```diff
@@ -0,0 +1,423 @@
...
+
+        //2. Start 3 bookies
+        Service bkService = new BookkeeperService("bookkeeper", zkUri);
+        if (!bkService.isRunning()) {
+            bkService.start(true);
+        }
+        List<URI> bkUris = bkService.getServiceDetails();
+        log.debug("Bookkeeper service details: {}", bkUris);
+
+        //3. start 2 instances of pravega controller
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 43]
```diff
@@ -0,0 +1,252 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: It shouldn't have these `<p>` tags.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 44]
```diff
@@ -0,0 +1,252 @@
...
+    @Test(timeout = 200000)
+    public void readWriteTest() throws InterruptedException, ExecutionException {
+
+        String scope = "testMultiReaderWriterScope";
+        String readerGroupName = "testMultiReaderWriterReaderGroup";
+        //20  readers -> 20 stream segments ( to have max read parallelism)
+        ScalingPolicy scalingPolicy = ScalingPolicy.fixed(20);
+        StreamConfiguration config = StreamConfiguration.builder().scope(scope)
+                .streamName(STREAM_NAME).scalingPolicy(scalingPolicy).build();
+        StreamManager streamManager = new StreamManagerImpl(controller);
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: I suppose we could also use try-with-resource rather than the annotation.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 45]
```diff
@@ -0,0 +1,387 @@
+/**
+ * Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
+ * <p>
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Remove `<p >`.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 46]
```diff
@@ -0,0 +1,387 @@
...
+    public void tearDown() {
+        if (controllerInstance != null && controllerInstance.isRunning()) {
+            controllerInstance.stop();
+        }
+        if (segmentStoreInstance != null && segmentStoreInstance.isRunning()) {
+            segmentStoreInstance.stop();
+        }
+    }
+
+    @Test(timeout = 600000)
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Do we really need 10 minutes?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 47]
```diff
@@ -0,0 +1,387 @@
...
+        //Scale down controller instances to 2
+        controllerInstance.scaleService(2, true);
+        log.info("Scaling down controller instances from 3 to 2");
+        List<URI> conURIs = controllerInstance.getServiceDetails();
+        // Fetch all the RPC endpoints and construct the client URIs.
+        final List<String> uris = conURIs.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+                .collect(Collectors.toList());
+        controllerURIDirect = URI.create("tcp://" + String.join(",", uris));
+        log.info("Controller Service direct URI: {}", controllerURIDirect);
+        Thread.sleep(60000);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: I don't understand this thread.sleep, why do we need it here? even more important, could we do a better blocking scheme that does not require sleeping for a specific amount of time, like using wait/notify or count down latches?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 48]
```diff
@@ -0,0 +1,387 @@
...
+        stopReadFlag.set(false);
+        eventData = new AtomicLong(); //data used by each of the writers.
+        eventReadCount = new AtomicLong(); // used by readers to maintain a count of events.
+
+        readWriteTest(writerList, readerList);
+        log.debug("{} with controller failover succeeds", "multiReaderWriterTest");
+
+        //Scale down SSS, controller to 1 instance each.
+        segmentStoreInstance.scaleService(1, true);
+        Thread.sleep(60000);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Same comment about the thread sleep.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 49]
```diff
@@ -0,0 +1,387 @@
...
+        if (controllerInstance != null && controllerInstance.isRunning()) {
+            controllerInstance.stop();
+        }
+        if (segmentStoreInstance != null && segmentStoreInstance.isRunning()) {
+            segmentStoreInstance.stop();
+        }
+    }
+
+    @Test(timeout = 600000)
+    public void multiReaderWriterWithFailOverTest() throws Exception {
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: This test case is good, but I still think we can do better than this. What I'd like to test is:

- Start writers and readers
- At some random point of the execution, crash a segment store server
- At some random point of the execution, crash a controller instance

As is, it is too deterministic and crashes never happen at deterministic points of an execution. Could we change the test case to do this?

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 44 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 50]
```diff
@@ -0,0 +1,252 @@
...
+        ClientFactory clientFactory = new ClientFactoryImpl(scope, controller);
```
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: using `try-with-resource`

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 51]
```diff
@@ -0,0 +1,252 @@
...
+        log.info("Creating {} writers", NUM_WRITERS);
+        List<CompletableFuture<Void>> writerList = new ArrayList<>();
+        for (i = 0; i < NUM_WRITERS; i++) {
+            log.info("Starting writer{}", i);
+            writerList.add(startNewWriter(eventData, clientFactory));
+        }
+
+        //create a reader group
+        log.info("Creating Reader group : {}", readerGroupName);
+        ReaderGroupManager readerGroupManager = new ReaderGroupManagerImpl(scope, controller, clientFactory);
```
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: using `try-with-resource`

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 39 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: done.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 40 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 43 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: removed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 45 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 47 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: This is required for marathon to process the scale instance request , for scaling down the service.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 48 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: answered above

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 49 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done.
1. start readers and writers
2. do a failover and check if reads and writes are still happening.
3. after covering all the failover cases, stop writers and then wait for # of reads = # of writes.

**Comment by Prabha-Veerubhotla** [comment]
DO NOT MERGE- testing in progress

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 52]
```diff
@@ -0,0 +1,403 @@
...
+
+            //close all the writers
+            writerList.forEach(writer -> writer.close());
+            //close all readers
+            readerList.forEach(reader -> reader.close());
+            //delete readergroup
+            log.info("Deleting readergroup {}", readerGroupName);
+            readerGroupManager.deleteReaderGroup(readerGroupName);
+        }
+            //seal the stream
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Indentation here seems incorrect.

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 53]
```diff
@@ -0,0 +1,260 @@
...
+            log.info("Creating {} writers", NUM_WRITERS);
+            List<CompletableFuture<Void>> writerList = new ArrayList<>();
+            for (int i = 0; i < NUM_WRITERS; i++) {
+                log.info("Starting writer{}", i);
+                writerList.add(startNewWriter(eventData, clientFactory));
+            }
+
+            //create a reader group
+            log.info("Creating Reader group : {}", readerGroupName);
+
```
Comment (fpj) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Unnecessary new lines.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 54]
```diff
@@ -0,0 +1,403 @@
...
+        readerList.forEach(reader -> {
+            CompletableFuture<Void> readerFuture = startReading(eventsReadFromPravega, eventData, eventReadCount, stopReadFlag, reader);
+            writerFutureList.add(readerFuture);
+        });
+
+        log.info("Test with 2 controller, SSS instances running and without a failover scenario");
+        eventWriteCount1 = eventData;
+        eventReadCount1 =  eventReadCount;
+
+        //Scale down SSS instances to 2
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Instead of having the scaling happening here, which is a bit odd because it is not directly related to reading and writing, perhaps we should have a different method that we call say `performScaling()` and we call it immediately after `readWriteTest` in the main test case method. Another option is that we move all this code related to scaling to the main test case method. I'm fine either way.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 55]
```diff
@@ -0,0 +1,403 @@
...
+        segmentStoreInstance.scaleService(2, true);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: We may want to randomize the timing of the scaling with a call to sleep with a random value.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 47 above)
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: controllerInstance.scaleService(2, true); here scaleService is a blocking call i.e. it will wait until there are two instances of controller service. Hence, `Thread.sleep()` is not required if the intent is to wait for marathon scale process to finish.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 52 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 53 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 54 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: added performScaling()

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 55 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 56]
```diff
@@ -0,0 +1,424 @@
...
+        log.debug("Pravega Segmentstore service  details: {}", segUris);
+    }
+
+    @Before
+    public void setup() {
+
+        //Start 1 instance of zookeeper
+        Service zkService = new ZookeeperService("zookeeper");
+        if (!zkService.isRunning()) {
+            zkService.start(true);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: ZKService is started in @Environment method, no need to start it again right?

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 57]
```diff
@@ -0,0 +1,424 @@
...
+        //2. Start 3 bookies
+        Service bkService = new BookkeeperService("bookkeeper", zkUri);
+        if (!bkService.isRunning()) {
+            bkService.start(true);
+        }
+        List<URI> bkUris = bkService.getServiceDetails();
+        log.debug("Bookkeeper service details: {}", bkUris);
+
+        //3. start 3 instances of pravega controller
+        Service conService = new PravegaControllerService("controllerFailover1", zkUri);
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: We can reuse the Controller Service with id "controller" which is started by other tests. We need not have a new instance of Controller service. The pattern in MultiSegmentStore test can be followed.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 58]
```diff
@@ -0,0 +1,424 @@
...
+        segmentStoreInstance.scaleService(1, true);
+        controllerInstance.scaleService(1, true);
+        log.info("Scaling down  to 1 controller, 1 SSS instance");
+        List<URI> conURIs1 = controllerInstance.getServiceDetails();
+        // Fetch all the RPC endpoints and construct the client URIs.
+        final List<String> uris1 = conURIs1.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+                .collect(Collectors.toList());
+        controllerURIDirect = URI.create("tcp://" + String.join(",", uris1));
+        log.info("Controller Service direct URI: {}", controllerURIDirect);
+        eventWriteCount4 = eventData;
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: eventWriteCount4 should be of type long, please modify all other variables used to take a snapshot to long.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 56 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: yeah, just verifying is it is running

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 58 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: changed

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 47 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: removed

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 46 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: No, reduced it to 5 mins.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 29 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: one

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 28 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: No , not a good idea as we discussed

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 26 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: logging the appropriate message and breaking out of loop

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java (hunk 27 above)
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: logging the warning and break out of reading loop.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 59]
```diff
@@ -0,0 +1,427 @@
...
+
+            //wait for writers completion
+            log.info("wait for writers exceution to complete");
+            FutureHelpers.allOf(writerFutureList);
+
+            //set the stop read flag to true
+            stopReadFlag.set(true);
+
+            // wait for reads = writes
+            synchronized (waitCondition) {
```
Comment (skrishnappa) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Since we are using the stop flag and doing FutureHelpers.allOf(readerFutureList) for synchronization, we don't need wait/notify mechanism. Review if this is still required and remove it otherwise.

**Comment by skrishnappa** [comment]
Looks good with just a few code cleanups

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 60]
```diff
@@ -0,0 +1,427 @@
...
+    private Long eventWriteCount4;
+    private Long eventReadCount1;
+    private Long eventReadCount2;
+    private Long eventReadCount3;
+    private Long eventReadCount4;
+    private ConcurrentLinkedQueue<Long> eventsReadFromPravega;
+    private Service controllerInstance = null;
+    private Service segmentStoreInstance = null;
+    private URI controllerURIDirect = null;
+    private final Object waitCondition = new Object();
```
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Replace waitcondition with a reusable Latch, a semephore, or something similar. That would avoid the need to synchronize and would prevent the race condition where the notification comes before the wait.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 61]
```diff
@@ -0,0 +1,427 @@
...
+            segmentStoreInstance.stop();
+        }
+    }
+
+    @Test(timeout = 300000)
+    public void multiReaderWriterWithFailOverTest() throws Exception {
+
+        String scope = "testMultiReaderWriterScope" + new Random().nextInt(Integer.MAX_VALUE);
+        String readerGroupName = "testMultiReaderWriterReaderGroup" + new Random().nextInt(Integer.MAX_VALUE);
+        //10  readers -> 10 stream segments ( to have max read parallelism)
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 62]
```diff
@@ -0,0 +1,427 @@
...
+        Thread.sleep(new Random().nextInt(50000) + 3000);
+
+        //Scale down controller instances to 2
+        controllerInstance.scaleService(2, true);
+        log.info("Scaling down controller instances from 3 to 2");
+        List<URI> conURIs = controllerInstance.getServiceDetails();
+        // Fetch all the RPC endpoints and construct the client URIs.
+        final List<String> uris = conURIs.stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
+                .collect(Collectors.toList());
+        controllerURIDirect = URI.create("tcp://" + String.join(",", uris));
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: removed

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 63]
```diff
@@ -0,0 +1,427 @@
...
+        assertTrue(eventReadCount4 > eventReadCount3);
+        //ensure writes are happening
+        assertTrue(eventWriteCount4 > eventWriteCount3);
+    }
+
+    private CompletableFuture<Void> startWriting(final AtomicLong data, final EventStreamWriter<Long> writer, final AtomicBoolean stopWriteFlag) {
+        return CompletableFuture.runAsync(() -> {
+            while (!stopWriteFlag.get()) {
+                try {
+                    long value = data.incrementAndGet();
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: added delay of 100ms

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 60 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java [hunk 64]
```diff
@@ -0,0 +1,427 @@
...
+@RunWith(SystemTestRunner.class)
+public class MultiReaderWriterWithFailOverTest {
+    private static final String STREAM_NAME = "testMultiReaderWriterStream";
+    private static final int NUM_WRITERS = 20;
+    private static final int NUM_READERS = 20;
+    private AtomicBoolean stopReadFlag;
+    private AtomicBoolean stopWriteFlag;
+    private AtomicLong eventData;
+    private AtomicLong eventReadCount;
+    private Long eventWriteCount1;
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: done

File: test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java [hunk 65]
```diff
@@ -0,0 +1,258 @@
...
+                        //update if event read is not null.
+                        readResult.add(longEvent);
+                        readCount.incrementAndGet();
+                    }
+                    //notify if num. of reads = num. of writes
+                    if (TOTAL_NUM_EVENTS == eventsReadFromPravega.size()) {
+                        synchronized (waitCondition) {
+                            waitCondition.notify();
+                            log.info("Closing reader {}", reader);
+                            reader.close();
```
Comment (Prabha-Veerubhotla) [inline test/integration/src/test/java/io/pravega/test/integration/ReadWriteTest.java]: Done

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 46 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: We need as there is a sleep of 1 min after each scale.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 47 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: Sorry for the confusion , this is actually needed. this is the time it takes for writes to continue after scale. So the writers need to wait atleast until this much time.
Relevant logs to prove the same
```
2017-06-23 06:35:42,953 19399 [grpc-default-executor-0] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: 172.16.19.3:12345 for containerId: 1
 2017-06-23 06:36:31,061 67507 [grpc-default-executor-0] DEBUG i.p.c.store.host.ZKHostStore - Found owning host: 172.16.19.13:12345 for containerId: 1
```
approx 1min time needed for ownership change.

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 59 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: yes not needed after doing a .get()

File: test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java (hunk 60 above)
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/MultiReaderWriterWithFailOverTest.java]: using FutureHelpers.allOf(readerFutureList).get()
