### PR TITLE
Issue 1517: Replacing Jersey's Netty container with grizzly2 which fixes the response truncation issue

### LINKED ISSUE #1517: Scaling-Events REST API response is truncated
**Problem description**
The controller Scaling-Events REST API (`/v1/scopes/hulk/streams/smallScale/scaling-events?from=1498758856064&to=1498845256064`) is truncated at ~64000 bytes, before it is complete. The JSON is in turn invalid.

This is similar to #926. The resolution in that case was to limit the number of streams return in the list endpoint.

**Problem location**
The REST server implementation.

**Suggestions for an improvement**
Increase response size.

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
Jersey + Netty has a buffer overflow issue - https://github.com/jersey/jersey/issues/3500 due to which we cannot stream large http responses in our REST APIs. Now replaced netty with the grizzly2 implementation which is much more widely used in the jersey framework. 

**Purpose of the change**
Fixes #1517 , #926 

**What the code does**
Replaced Jersey's netty container implementation with grizzly2.

**How to verify it**
Included tests to send large response body. Also all existing REST API tests should pass.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java [hunk 1]
```diff
@@ -67,7 +69,7 @@ protected void startUp() {
         long traceId = LoggerHelpers.traceEnterWithContext(log, this.objectId, "startUp");
         try {
             log.info("Starting REST server listening on port: {}", this.restServerConfig.getPort());
-            channel = NettyHttpContainerProvider.createServer(baseUri, resourceConfig, false);
+            httpServer = GrizzlyHttpServerFactory.createHttpServer(baseUri, resourceConfig, true);
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java]: what is the last boolean param and just curious, Netty.createServer had a boolean for blocking where we chose false. 
And here Grizzly.createServer its true.

File: controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java [hunk 2]
```diff
@@ -81,9 +83,9 @@ protected void shutDown() throws Exception {
         long traceId = LoggerHelpers.traceEnterWithContext(log, this.objectId, "shutDown");
         try {
             log.info("Stopping REST server listening on port: {}", this.restServerConfig.getPort());
-            channel.close();
+            final GrizzlyFuture<HttpServer> shutdown = httpServer.shutdown(30, TimeUnit.SECONDS);
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java]: Q: As per the below example there is a shutdownNow() api too, any particular reason for usng the above?

`https://github.com/jersey/jersey/blob/master/examples/server-async/src/main/java/org/glassfish/jersey/examples/server/async/App.java`

File: controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java (hunk 1 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java]: Here 3rd param is to start the server. Setting to true here otherwise it will only configure the server and we need to explicitly call httpServer.start() to start listening.

File: controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java (hunk 2 above)
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/server/rest/RESTServer.java]: Giving some time here to complete existing calls so that shutdown is graceful. shutdownNow will terminate ongoing requests immediately.

**Comment by jonny-miller** [comment]
I tested this using docker-compose and found that the REST server was not being exposed when run in a container because it is only binding to localhost.  I think you would need to update the docker-compose.yml file for the controller to include `REST_SERVER_IP: 0.0.0.0` as an environment variable for the controller so it binds to all interfaces.

**Comment by skrishnappa** [comment]
@jonny-miller I have made 0.0.0.0 as the default listen port now.
