### PR TITLE
Issue 6593: Fix operationlogsize metric based test

### LINKED ISSUE #6593: Fix test failures due to operationlogsize metric
**Describe the bug**
Fix test failures due to operationlogsize metric on r0.11. The recent cherry pick to r0.11 branch (https://github.com/pravega/pravega/pull/6592) is failing tests which needs to be fixed. This commit could have introduced a flaky test.

**To Reproduce**
Run unit tests and we might see a failure of io.pravega.segmentstore.server.SegmentStoreMetricsTests.testOperationProcessorMetrics.

**Screenshots**
N/A

**Additional information**
N/A

### PR DESCRIPTION
**Pull request by abhinb**
**Change log description**  
Fix operationlogsize metric based test.

**Purpose of the change**  
Fixes #6593 

**What the code does**  
There was an issue with how the gauge is retrieved in the test. Basically in the test while reporting the gauge we report the OperationLog Size metric/gauge  for a specific container. However while retrieving the gauge we query the MetricRegistryUtils which return the operationlogsize for all containers. There is a precondition check where we expect only one gauge to be retrieved(since we are querying for only one container). However this container id wasnt passed resulting in gauges for all containers to be retrieved thereby failing the Precondition Check. 
The fix passes the right container id while retrieving the gauge.

**How to verify it**  
Unit tests should pass.

### CODE REVIEW

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java [hunk 1]
```diff
@@ -230,8 +230,8 @@ public void testOperationProcessorMetrics() throws Exception {
                 new TestCompletableOperation(30));
         op.operationsFailed(opf);
         assertEquals(20, (int) MetricRegistryUtils.getTimer(MetricsNames.OPERATION_LATENCY, containerTag).totalTime(TimeUnit.MILLISECONDS));
-        SegmentStoreMetrics.reportOperationLogSize(1000, 1);
-        AssertExtensions.assertEventuallyEquals(true, () -> MetricRegistryUtils.getGauge(MetricsNames.OPERATION_LOG_SIZE).value() == 1000, 2000);
+        SegmentStoreMetrics.reportOperationLogSize(1000, containerId);
+        AssertExtensions.assertEventuallyEquals(true, () -> MetricRegistryUtils.getGauge(MetricsNames.OPERATION_LOG_SIZE, containerTag(containerId)).value() == 1000, 2000);
```
Comment (RaulGracia) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java:234]: Why this only fails sometimes? If the container is wrong, shouldn't it be failing consistently?

Comment (abhinb) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/SegmentStoreMetricsTests.java:234]: If this test has been passing at times, it would mean, when the gauge was retrieved only the container for which the gauge was created was registered. Might have to do with timing of the test. But with the change i see the test consistently passes on internal Jenkins builds and GH Actions.

**Review by RaulGracia — APPROVED** [review]
