### PR TITLE
Issue 6067: Auto scaledown is triggered for segments with steady traffic between target/2 and target rates. 

### LINKED ISSUE #6067: Auto scale down happening even with steady traffic just below target rate
**Describe the bug**
AutoscaleProcessor is sending scale down signals for steady traffic segments too. This is because of a bug where we rely on a cache entry expiration for determining whether a segment has received any traffic or not in a long time. 
Ideally the cache access should have been triggered everytime the traffic was reported to AutoScaleProcessor. However, it only accessed cache if the traffic was either resulting in scale ups or scale downs. This meant that for steady traffic, the logic presumes that there is no traffic reported for the said segment, and upon cache expiration, it automatically triggers a scale down request for it.

**To Reproduce**
1. Create a stream with two segments
2. write steady traffic into the two segments between targetrate/2 and targetrate
3. observe scale downs happening with scale down event containing flag with "silent" segment. 

**Screenshots**

**Additional information**
The root cause is that we do not access cache everytime the traffic is reported, leading to this problem. This can be mitigated by simply accessing the cache for each traffic report.

### PR DESCRIPTION
**Pull request by ldr7**
Signed-off-by: Atharva <Atharva.Joshi@dell.com>

**Change log description**  
Adds a get cache call in the report method for AutoScaleProcessor and adds a test covering the scenario.  

**Purpose of the change**  
Fixes #6067 

**What the code does**  

- Adds a get cache call in every report so that the last access time is updated. 
- Adds a test covering the scenario. Report is called on a segment before cache expiry and its ensured that cache cleanup does not evict the segment from the cache.
- Implements constructors in AutoScaleProcessor to enable the test.
- Creates classes in SimpleCacheTests to enable the test.
- Adds a test time dependency for segmentstore:host on common:test. 

**How to verify it**  
Run the unit test - AutoScaleProcessorTest.testCacheGetOnReport

### CODE REVIEW

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 1]
```diff
@@ -1,12 +1,12 @@
 /**
  * Copyright Pravega Authors.
- *
+ * <p>
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:3]: please revert changes to the license

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 2]
```diff
@@ -21,26 +21,37 @@
...
 import io.pravega.shared.NameUtils;
 import io.pravega.shared.controller.event.AutoScaleEvent;
 import io.pravega.test.common.AssertExtensions;
 import io.pravega.test.common.SecurityConfigDefaults;
 import io.pravega.test.common.ThreadPooledTestSuite;
+
 import java.net.URI;
 import java.time.Duration;
-import java.util.List;
+import java.util.*;
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:34]: please explicitly import the desired files

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 3]
```diff
@@ -76,14 +87,15 @@ public void writerCreationTest() throws Exception {
...
                 () -> failingWriterProcessor.bootstrapOnce(clientFactory, w),
                 e -> Exceptions.unwrap(e) instanceof RuntimeException);
 
-        // report but since the cooldown time hasnt elapsed, no scale event should be attempted. So no writer should be initialized yet. 
+        // report but since the cooldown time hasnt elapsed, no scale event should be attempted. So no writer should 
+        // be initialized yet. 
         failingWriterProcessor.report(segmentStreamName, 1, 0L, 10.0, 10.0, 10.0, 10.0);
         assertFalse(failingWriterProcessor.isInitializeStarted());
-        
+
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:98]: nit: revert

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 4]
```diff
@@ -107,7 +119,7 @@ public void writerCreationTest() throws Exception {
         doAnswer(x -> writerMock).when(clientFactory).createEventWriter(any(), any(), any());
 
         processor.notifyCreated(segmentStreamName);
-        
+
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:122]: nit: revert

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 5]
```diff
@@ -116,17 +128,18 @@ public void writerCreationTest() throws Exception {
         AssertExtensions.assertEventuallyEquals(writerMock, () -> processor.getWriterFuture().join(), 10000L);
         AutoScaleEvent event = queue.take();
         assertEquals(event.getDirection(), AutoScaleEvent.DOWN);
-        
+
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:131]: revert

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 6]
```diff
@@ -116,17 +128,18 @@ public void writerCreationTest() throws Exception {
...
         processor.close();
-        
+
         // create third writer, this time supply the writer directly
-        EventStreamWriter<AutoScaleEvent> writer = spy(createWriter(e -> { }));
-        
+        EventStreamWriter<AutoScaleEvent> writer = spy(createWriter(e -> {
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:135]: revert

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 7]
```diff
@@ -367,4 +390,37 @@ protected void setTimeMillis(long time) {
...
+        String streamSegmentName1 = NameUtils.getQualifiedStreamSegmentName(SCOPE, STREAM1, 0L);
+        monitor.setTimeMillis(0L);
+        currentTime.set(0L);
+        monitor.notifyCreated(streamSegmentName1);
+        monitor.put(streamSegmentName1, new ImmutablePair<>(5L, 5L));
+        monitor.setTimeMillis(30L);
+        currentTime.set(30L);
+        monitor.report(streamSegmentName1, 10L, 0L, 10D, 10D, 10D, 10D);
+        monitor.setTimeMillis(80L);
+        currentTime.set(80L);
```
Comment (shiveshr) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:419]: set time such that T2 - T1 is > expiry time.. note expiry time that you have set in the test is 60000 ms. 
and here monitor.setTimeMillis is stting the time in millis.

File: test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpTest.java [hunk 8]
```diff
@@ -48,38 +52,42 @@
 @Slf4j
 public class EndToEndAutoScaleUpTest {
     static final StreamConfiguration CONFIG = StreamConfiguration.builder()
-                                                                 .scalingPolicy(ScalingPolicy.byEventRate(10, 2, 3))
-                                                                 .build();
+            .scalingPolicy(ScalingPolicy.byEventRate(10, 2, 1))
```
Comment (shiveshr) [inline test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpTest.java:55]: revert

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java (hunk 7 above)
Comment (ldr7) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:419]: shouldn't T2-T0 > expiry time while T2-T1 < expiry time so that we can conclude that report updates latest access time successfully?

File: test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpTest.java (hunk 8 above)
Comment (ldr7) [reply test/integration/src/main/java/io/pravega/test/integration/demo/EndToEndAutoScaleUpTest.java]: Done

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java (hunk 7 above)
Comment (shiveshr) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:420]: sorry, yes, t2-t0 ? expiry.

**Review by shiveshr — APPROVED** [review]
LGTM. the coverage needs to improve

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java [hunk 9]
```diff
@@ -105,14 +111,20 @@
...
         this.writer = new CompletableFuture<>();
         this.clientFactory = clientFactory;
         this.startInitWriter = new AtomicBoolean(false);
-
-        this.cache = new SimpleCache<>(MAX_CACHE_SIZE, configuration.getCacheExpiry(), (k, v) -> triggerScaleDown(k, true));
-
+        
+        if (simpleCache == null) {
+            this.cache = new SimpleCache<>(MAX_CACHE_SIZE, configuration.getCacheExpiry(), (k, v) -> {
+                System.out.println("added::Scaling down segment" + k );
```
Comment (RaulGracia) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java:122]: Please, remove prints from the code.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java [hunk 10]
```diff
@@ -265,13 +283,14 @@ private void writeRequest(AutoScaleEvent event, Runnable successCallback) {
...
         log.info("received traffic for {} with twoMinute rate = {} and targetRate = {}", streamSegmentName, twoMinuteRate, targetRate);
+        cache.get(streamSegmentName);
         // note: we are working on caller's thread. We should not do any blocking computation here and return as quickly as
         // possible.
         // So we will decide whether to scale or not and then unblock by asynchronously calling 'writeEvent'
         long currentTime = getTimeMillis();
         if (currentTime - startTime > configuration.getCooldownDuration().toMillis()) {
             log.debug("cool down period elapsed for {}", streamSegmentName);
-
+
```
Comment (RaulGracia) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java:293]: Nit: unnecessary change.

**Review by RaulGracia — CHANGES_REQUESTED** [review]

**Comment by RaulGracia** [comment]
@ldr7 can you please check the the test coverage?

**Comment by OlegKashtanov** [comment]
Conducted the auto scale test. Didn't observe significant instability in segment counts of user streams. Looks good.

File: build.gradle [hunk 11]
```diff
@@ -494,6 +494,7 @@ project('segmentstore:server:host') {
         compile project(':segmentstore:server')
         compile group: 'ch.qos.logback', name: 'logback-classic', version: qosLogbackVersion
         testCompile project(':test:testcommon')
+        testCompile project(path:':common', configuration:'testRuntime')
```
Comment (andreipaduroiu) [inline build.gradle:497]: Why is this needed?

File: common/src/test/java/io/pravega/common/util/SimpleCacheTests.java [hunk 12]
```diff
@@ -495,4 +499,12 @@ private long value(long key) {
         Collections.shuffle(list, random);
         return list;
     }
+    
+    public static class TestSimpleCache<KeyT, ValueT> extends SimpleCache<KeyT, ValueT> {
```
Comment (andreipaduroiu) [inline common/src/test/java/io/pravega/common/util/SimpleCacheTests.java:503]: What is the point of this?

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java [hunk 13]
```diff
@@ -265,6 +280,7 @@ private void writeRequest(AutoScaleEvent event, Runnable successCallback) {
 
     void report(String streamSegmentName, long targetRate, long startTime, double twoMinuteRate, double fiveMinuteRate, double tenMinuteRate, double twentyMinuteRate) {
         log.info("received traffic for {} with twoMinute rate = {} and targetRate = {}", streamSegmentName, twoMinuteRate, targetRate);
+        cache.get(streamSegmentName);
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java:283]: Why?

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java (hunk 5 above)
Comment (andreipaduroiu) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:135]: Please revert all formatting changes to this class. It helps a lot with the signal-to-noise ratio for reviews.

File: common/src/test/java/io/pravega/common/util/SimpleCacheTests.java (hunk 12 above)
Comment (andreipaduroiu) [reply common/src/test/java/io/pravega/common/util/SimpleCacheTests.java:503]: I see where you use this. Please consider using `moq` (i.e., `mock(SimpleCache.class)`) if you need to mock its behavior - that will also make your unit test more focused and not rely on the `SimpleCache` behavior.

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 14]
```diff
@@ -367,4 +393,87 @@ protected void setTimeMillis(long time) {
         }
     }
 
+    @Test
+    public void testCacheGetOnReport() {
+        final int infiniteSize = Integer.MAX_VALUE;
+        final AtomicLong currentTime = new AtomicLong();
+        val evictions = new ArrayList<Map.Entry<Long, Long>>();
+        io.pravega.common.util.SimpleCacheTests.TestSimpleCache<String, Pair<Long, Long>> testSimpleCache =
```
Comment (andreipaduroiu) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:401]: Consider using `moq`. This way you won't have to add yet another dependency to this project.

**Review by andreipaduroiu — CHANGES_REQUESTED** [review]

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java (hunk 13 above)
Comment (ldr7) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java:283]: The get method updates the latest access time for the contents. In case of steady traffic below target rate, neither the upscale nor downscale process occurs.  As a result, we have cache expiry and needless downscaling. This line prevents expiry when there is steady traffic.

File: common/src/test/java/io/pravega/common/util/SimpleCacheTests.java (hunk 12 above)
Comment (ldr7) [reply common/src/test/java/io/pravega/common/util/SimpleCacheTests.java:503]: `SimpleCache` does not provide a mechanism to set the supplier which is used as a clock. In unit tests, the clock has to be manipulated for setting time.  To do that the package private constructor has to be used. Hence a new class has been created for testing with a public constructor to which the supplier for clock can be provided.

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java (hunk 14 above)
Comment (ldr7) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:397]: Reverted the formatting changes.  Addressed the point on mocks earlier.

File: build.gradle (hunk 11 above)
Comment (ldr7) [reply build.gradle:497]: Since the new class(`TestSimpleCache`) is needed (covered in the next comment), a test time dependency would have to be introduced.

File: common/src/test/java/io/pravega/common/util/SimpleCacheTests.java (hunk 12 above)
Comment (andreipaduroiu) [reply common/src/test/java/io/pravega/common/util/SimpleCacheTests.java:503]: I realized that as I went further down this PR. I suggested using some mocks to help with your unit tests. Have you tried that?  I prefer to leave adding new dependencies as a last resort as they are very hard to undo and may complicate refactoring work later on.

**Comment by RaulGracia** [comment]
@ldr7 please look at this error, normally it means that you have not closed some resources and it has been detected as a leak:
```
* What went wrong:
Execution failed for task ':segmentstore:server:host:test'.
> Process 'Gradle Test Executor 5' finished with non-zero exit value 99
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/6.5.1/userguide/java_testing.html#sec:test_execution
```

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java [hunk 15]
```diff
@@ -366,5 +383,110 @@ protected void setTimeMillis(long time) {
...
+                        .with(AutoScalerConfig.CACHE_CLEANUP_IN_SECONDS, 150)
+                        .with(AutoScalerConfig.CACHE_EXPIRY_IN_SECONDS, 60).build(), executorService()),
+                e -> e instanceof NullPointerException);
 
+        AutoScalerConfig config = AutoScalerConfig.builder()
+                .with(AutoScalerConfig.CONTROLLER_URI, "tcp://localhost:9090")
+                .with(AutoScalerConfig.TLS_ENABLED, false)
+                .build();
+        ClientConfig objectUnderTest = AutoScaleProcessor.prepareClientConfig(config);
+        EventStreamClientFactory eventStreamClientFactory = EventStreamClientFactory.withScope(SCOPE, objectUnderTest);
```
Comment (shrids) [inline segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:463]: @Cleanup

Comment (ldr7) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:466]: Done

**Comment by RaulGracia** [comment]
@ldr7 the leak seems to still be there:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
Execution failed for task ':segmentstore:server:host:test'.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings
> Process 'Gradle Test Executor 5' finished with non-zero exit value 99
56 actionable tasks: 7 executed, 49 up-to-date
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/6.5.1/userguide/java_testing.html#sec:test_execution
  ```

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java [hunk 16]
```diff
@@ -122,6 +131,12 @@
         }
     }
 
+    @VisibleForTesting
+    AutoScaleProcessor(@NonNull AutoScalerConfig configuration, @NonNull ScheduledExecutorService executor, SimpleCache<String, Pair<Long, Long>> simpleCache) {
+        this(configuration, createFactory(configuration), executor, simpleCache);
```
Comment (shrids) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java:136]: I delomboked this code and it translates to the following
```java
 AutoScaleProcessor(@NonNull AutoScalerConfig configuration, @NonNull ScheduledExecutorService executor, SimpleCache<String, Pair<Long, Long>> simpleCache) {
        this(configuration, createFactory(configuration), executor, simpleCache);
        if (configuration == null) {
            throw new java.lang.NullPointerException("configuration is marked non-null but is null");
        }
        if (executor == null) {
            throw new java.lang.NullPointerException("executor is marked non-null but is null");
        }
    }
```
In case of a null value passed the factory is never closed.
Perhaps this is the cause of System.exit(99) you are facing.

Comment (ldr7) [reply segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java]: Have removed that constructor.

File: common/src/test/java/io/pravega/common/util/SimpleCacheTests.java (hunk 12 above)
Comment (ldr7) [reply common/src/test/java/io/pravega/common/util/SimpleCacheTests.java]: Have mocked the cache.  Added dependency has been removed.

**Comment by RaulGracia** [comment]
@pbelgundi @ldr7 why this PR has been closed?

**Comment by ldr7** [comment]
I do not know why the PR has been closed.

**Comment by RaulGracia** [comment]
@ldr7 ok, will reopen then.

**Review by RaulGracia — APPROVED** [review]

File: segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/server/host/src/test/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessorTest.java:3]: @ldr7 Please revert this.

**Review by andreipaduroiu — COMMENTED** [review]
Looks good. Please revert the copyright header changes in that file and we should be good to go.

**Review by andreipaduroiu — APPROVED** [review]
