### PR TITLE
Issue 1532: ZKSegmentContainerMonitor should handle all exceptions

### LINKED ISSUE #1532: ZKSegmentContainerMonitor halts if exception is thrown by the scheduled executor
**Problem description**
ZKSegmentContainerMonitor halts if StreamSegmentContainerRegistry throws an exception

**Problem location**
ZKSegmentContainerMonitor.
When we use ScheduledExecutorService.scheduleWithFixedDelay(), the scheduler halts if the Runnable throws any exception. We need to ensure the scheduled thread does not throw any exceptions, otherwise the scheduler is halted.

**Suggestions for an improvement**
Catch all exceptions

### PR DESCRIPTION
**Pull request by skrishnappa**
**Change log description**
ZKSegmentContainerMonitor uses ScheduledExecutorService.scheduleWithFixedDelay() to setup up a monitor at regular intervals. The monitor is not scheduled if it throws any exception -
 https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleWithFixedDelay(java.lang.Runnable,%20long,%20long,%20java.util.concurrent.TimeUnit)
Now handling all exceptions so the segmentcontainer monitor is not halted on exceptions.

**Purpose of the change**
Fixes #1532 

**What the code does**
Handles all container start/stop exceptions so that they can be retries in the next schedule.

**How to verify it**
Added test case for startContainer throwing exception.

### CODE REVIEW

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java [hunk 1]
```diff
@@ -196,51 +202,63 @@ private void checkAssignment() {
...
-                            // The pending task has to be removed after the handle is removed to avoid inconsistencies
-                            // with the container state.
-                            // Using finally block to ensure this is always called, otherwise this will prevent other
-                            // tasks from being attempted for this container id.
-                            this.pendingTasks.remove(containerId);
-                        }
-                    });
+            try {
+                return registry
+                        .stopContainer(handle, CLOSE_TIMEOUT_PER_CONTAINER)
```
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: would it make sense to wrap stop container in a retry.indefinitely block to be sure that we have stopped the container?

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java [hunk 2]
```diff
@@ -196,51 +202,63 @@ private void checkAssignment() {
...
-                .startContainer(containerId, INIT_TIMEOUT_PER_CONTAINER)
-                .whenComplete((handle, ex) -> {
-                    try {
-                        if (ex == null) {
-                            if (this.handles.putIfAbsent(handle.getContainerId(), handle) != null) {
-                                log.warn("Starting container {} succeeded but handle is already registered.",
-                                        handle.getContainerId());
+        try {
+            return this.registry
+                    .startContainer(containerId, INIT_TIMEOUT_PER_CONTAINER)
```
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: similarly add some retries for start container. so that we are sure we retry few times to start the container.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java [hunk 3]
```diff
@@ -157,34 +157,40 @@ public void close() {
...
+                        desiredList, runningContainers, containersPendingTasks, containersToBeStarted,
+                        containersToBeStopped);
 
-            // Initiate the start and stop tasks asynchronously.
-            containersToBeStarted.forEach(this::startContainer);
-            containersToBeStopped.forEach(this::stopContainer);
-        } else {
-            log.warn("No segment container assignments found");
+                // Initiate the start and stop tasks asynchronously.
+                containersToBeStarted.forEach(this::startContainer);
```
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: if we start containers asynchronously and in parallel a subsequent run of this method could start conflicting opearations on these containers (like we could end up with both start and stop container for the same container. should we have some protection against it?

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java [hunk 4]
```diff
@@ -196,51 +202,63 @@ private void checkAssignment() {
...
-                        // The pending task has to be removed in the end to avoid inconsistencies since containerhandle
-                        // should be available immediately after the task is complete.
-                        // Also need to ensure this is always called, hence doing this in a finally block.
-                        this.pendingTasks.remove(containerId);
-                    }
-                });
+                    });
+        } catch (Throwable e) {
+            // The pending task has to be removed on all failures to enable retries.
+            this.pendingTasks.remove(containerId);
```
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: not clear about how pending tasks is being handled in this class. could you please describe it once.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java (hunk 2 above)
Comment (skrishnappa) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: The monitor thread runs at regular intervals to ensure container start/stop state is correctly maintained (hence failures are retried).

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java (hunk 3 above)
Comment (skrishnappa) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: These protections are already in place. No 2 operations for the same container can happen in parallel.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java (hunk 4 above)
Comment (skrishnappa) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: The pending tasks state is used to ensure no 2 operations for the same container happen in parallel. We check this state before attempting to start/stop a container. So if container 1 has a previously pending task (starting/stopping), we postpone the start/stop operation to the next iteration of this monitor task.

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java (hunk 2 above)
Comment (shiveshr) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: yes but waiting for next schedule means we delay stopping or starting the container by that duration (say a minute or so). it may be a good idea to perform retries until we perform the desired operation or the requirements (desired goal state) has changed.. for example if a container had to be started in one iteration and we were unable to start and subsequently controller reassigned that container to another host, this host should not attempt to start the container.
that brings me to the question -- how is that handled -- if a container was reassigned before our asynchronous processing was performed, when processing starts/resumes what do we do about that?

Comment (skrishnappa) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: We check desired goal state before every start/stop attempt. Also the retries happen every 10 seconds and failures shouldn't happen often, so keeping the design simple here (earlier we used chaining to retry start/stop failures immediately which complicated the code and introduced too many states and corner cases)

File: segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java (hunk 1 above)
Comment (skrishnappa) [inline segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ZKSegmentContainerMonitor.java]: Currently we assume failed containers to be in stopped state. Need to review whether retrying stopContainer has any affect. Have filed #1537 to address this since its not in scope for this PR.
