### PR TITLE
Issue 2613: EventStreamWriter should handle NoSuchSegment due to truncation gracefully.

### LINKED ISSUE #2613: EventStreamWriter should handle WireCommands.NoSuchSegment gracefully.
**Problem description**
Stream Truncation can cause the Segment Store to return `WireCommands.NoSuchSegment` to an EventStreamWriter. The EventStreamWriter should fetch the deleted segment's successors and ensure the events are written to that segment instead of throwing NoSuchSegmentException to the user.

**Problem location**
EventStreamWriter.

**Suggestions for an improvement**
Fix the issue.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
- Ensure `EventStreamWriter#writeEvent()` fetches a segment's successors incase it is deleted by stream truncation; ensure the inflight events are written to the successor segments.
- In case of stream deletion ensure the future returned by `EventStreamWriter#writeEvent()` is completed exceptionally.

**Purpose of the change**
Fixes #2613

**What the code does**
Ensure `EventStreamWriter#writeEvent()` fetches a segment's successors in the case it is deleted by stream truncation; ensure the inflight events are written to the successor segments. 
The below example describes a scenario in detail.
```
1. Stream StreamA has segments S0, S1 at epoch 0. 
2. Writer W1 is writing events to this stream.
3. Now Controller scales down StreamA to have S2 and it also truncates the stream at S2 offset 0.
4. W1.writeEvent() will receive WireCommands.NoSuchSegment from SegmentStore. 
   It should fetch the successors (S2) and write events into it.
```

**How to verify it**
All the existing and newly added tests should pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 1]
```diff
@@ -302,39 +303,24 @@ public void wrongHost(WrongHost wrongHost) {
...
-            for (PendingEvent toAck : state.removeInflightBelow(Long.MAX_VALUE)) {
-                if (toAck != null) {
-                    toAck.getAckFuture().completeExceptionally(exception);
-                }
-            }
-            state.releaseIfEmptyInflight();
+            log.info("Segment being written to {} by writer {} no longer exists due to Stream Truncation, resending to the newer segment.",
+                    noSuchSegment.getSegment(), writerId);
+            //update state indicating that no such segment was encountered.
+            state.noSuchSegmentEncountered.getAndSet(true);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: use `set()`

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 2]
```diff
@@ -379,6 +365,18 @@ public void appendSetup(AppendSetup appendSetup) {
             }
         }
 
+        private void retryOnWriteFail(WireCommand wireCommand) {
+            if (state.encounteredSeal()) {
+                Retry.indefinitelyWithExpBackoff(retrySchedule.getInitialMillis(), retrySchedule.getMultiplier(),
+                        retrySchedule.getMaxDelay(),
+                        t -> log.error(writerId + " to invoke sealed callback: ", t))
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Use proper logging formatting.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 3]
```diff
@@ -126,14 +130,22 @@ public Segment getSegmentForEvent(String routingKey) {
...
+            //stream is deleted, hence successors is null.
+            writers.get(sealedSegment).getUnackedEventsOnSeal()
+                    .forEach(pendingEvent -> pendingEvent.getAckFuture()
+                            .completeExceptionally(new NoSuchSegmentException(sealedSegment.toString())));
+            return Collections.emptyList();
+        } else {
+            currentSegments = currentSegments.withReplacementRange(successors);
+            createMissingWriters(segmentSealedCallback, currentSegments.getDelegationToken());
+            log.debug("Fetch unacked events for segment: {}, and adding new segments {}", sealedSegment, currentSegments);
+            List<PendingEvent> toResend = writers.get(sealedSegment).getUnackedEventsOnSeal();
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Use `writers.remove` to both get and remove - so you only access the collection once.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 4]
```diff
@@ -126,14 +130,22 @@ public Segment getSegmentForEvent(String routingKey) {
...
-        createMissingWriters(segmentSealedCallback, newStreamSegments.getDelegationToken());
-        log.debug("Fetch unacked events for segment: {}, and adding new segments {}", sealedSegment, newStreamSegments);
-        List<PendingEvent> toResend = writers.get(sealedSegment).getUnackedEventsOnSeal();
-        writers.remove(sealedSegment); //remove this sealed segment writer.
-        return toResend;
+        if (successors == null) {
+            //stream is deleted, hence successors is null.
+            writers.get(sealedSegment).getUnackedEventsOnSeal()
+                    .forEach(pendingEvent -> pendingEvent.getAckFuture()
+                            .completeExceptionally(new NoSuchSegmentException(sealedSegment.toString())));
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: This is really dangerous. Never complete a Future while holding a lock. The Future's downstream handlers may execute synchronously on this thread while holding your lock, which can quickly lead to a deadlock.

First collect your targets while holding the lock, then complete those futures outside of the lock.

File: client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java [hunk 5]
```diff
@@ -776,39 +772,34 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
     public void testNoSuchSegment() throws Exception {
         UUID cid = UUID.randomUUID();
         PravegaNodeUri uri = new PravegaNodeUri("endpoint", SERVICE_PORT);
-
         MockConnectionFactoryImpl cf = new MockConnectionFactoryImpl();
-        ScheduledExecutorService executor = mock(ScheduledExecutorService.class);
-        implementAsDirectExecutor(executor); // Ensure task submitted to executor is run inline.
-        cf.setExecutor(executor);
-
+        @Cleanup("shutdown")
```
Comment (andreipaduroiu) [inline client/src/test/java/io/pravega/client/segment/impl/SegmentOutputStreamTest.java]: There is a unit test base class to handle async unit tests which takes care of all the creation and cleanup of Thread Pools.

Have this test class extend from `ThreadPooledTestSuite`, override the `getThreadPoolSize` and have it return 0 (I believe that is the default). Then use `executorService()` to access the Thread Pool.

File: test/integration/src/test/java/io/pravega/test/integration/ReadFromDeletedStreamTest.java [hunk 6]
```diff
@@ -54,11 +54,12 @@ public void testDeletedAndRecreatedStream() throws Exception {
         @Cleanup
         MockClientFactory clientFactory = streamManager.getClientFactory();
         // Mocking pravega service by putting scale up and scale down requests for the stream
-        @Cleanup
```
Comment (andreipaduroiu) [inline test/integration/src/test/java/io/pravega/test/integration/ReadFromDeletedStreamTest.java]: Why no cleanup anymore? If your test fails prior to reaching line 63, this will stay open and won't release any resources it acquired.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 7]
```diff
@@ -492,6 +490,9 @@ public void flush() throws SegmentSealedException {
             }
             state.waitForInflight();
             Exceptions.checkNotClosed(state.isClosed(), this);
+            if (state.noSuchSegmentEncountered.get()) {
+                throw new NoSuchSegmentException(segmentName + " is not present due to truncation or deletion.");
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: I think this should be thrown as a SegmentSealedException for the benifit of EventStreamWriterImpl's handling.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 8]
```diff
@@ -126,14 +130,22 @@ public Segment getSegmentForEvent(String routingKey) {
...
-    private List<PendingEvent> updateSegmentsUponSealed(StreamSegments newStreamSegments, Segment sealedSegment,
+    private List<PendingEvent> updateSegmentsUponSealed(StreamSegmentsWithPredecessors successors, Segment sealedSegment,
                                                         Consumer<Segment> segmentSealedCallback) {
-        currentSegments = newStreamSegments;
-        createMissingWriters(segmentSealedCallback, newStreamSegments.getDelegationToken());
-        log.debug("Fetch unacked events for segment: {}, and adding new segments {}", sealedSegment, newStreamSegments);
-        List<PendingEvent> toResend = writers.get(sealedSegment).getUnackedEventsOnSeal();
-        writers.remove(sealedSegment); //remove this sealed segment writer.
-        return toResend;
+        if (successors == null) {
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: This really should be split into two methods as there is no common code between the if and else case. 
Given that it is only called in one place, this shouldn't be a problem.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 7 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: In a scenario where the stream is deleted post writer creation a `flush()`  or `close()` might stuck indefinitely if we throw a SegmentSealedException. This PR changes the behavior of the writer as shown below (Let me know if we should change it )

behaviour

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 1 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: done.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 2 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: updated it.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 3 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: done.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 4 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Thank for pointing it out. Updated the code to cancel all the futures on an executor.

File: test/integration/src/test/java/io/pravega/test/integration/ReadFromDeletedStreamTest.java (hunk 6 above)
Comment (shrids) [reply test/integration/src/test/java/io/pravega/test/integration/ReadFromDeletedStreamTest.java]: close() is invoked in the next line.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 7 above)
Comment (tkaitchuck) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: In the case where `flushInternal()` is called, either due to a seal or `flush()` being called, and
it goes down this codepath:
https://github.com/pravega/pravega/pull/2612/files#diff-60053e16af1ab55e04df790f148a7bcaR103
because there are successors to the deleted segment, doesn't this change mean that:
https://github.com/pravega/pravega/pull/2612/files#diff-3c18ee5eb24224b2c2fdcce1e56f97eeR347
Should also be catching `NoSuchSegmentException`, because we want the unacked events to be written to the new segment. 

Yes, you are correct doing this nieevly would result in an infinate loop. We have to think about how to best do that.

I am also worried about duplicates in this case. IE: It is technically possible that there was an unacked append outstanding against the server, and the segment was deleted by retention. Then before the ack or lack there of could be returned to the client the connection dropped. In this case the reconnect will fail because the segment does not exist. So the client will have no way of knowing if the append made it or not. I'm not sure how big of a problem it is because the event even if written would have been immediately deleted. But it is still theoretically possible it could have been read. We could and probably should impose the limitation that truncation will not delete the currently active segment. (And maybe impose some minimum time limit before deleting it so as to avoid this complication)

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Updated the writer behavior; now `flush()` on receiving `NoSuchSegment` response from SegmentStore will retry sending the inflight events by fetching the deleted segment's successors (simiilar to segment sealed scenario). The updated behavior of writer is shown below.

image

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 9]
```diff
@@ -379,6 +362,18 @@ public void appendSetup(AppendSetup appendSetup) {
             }
         }
 
+        private void retryOnWriteFail(WireCommand wireCommand) {
+            if (state.encounteredSeal()) {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: One clarification: we only execute the retry loop in the case the state implies that the segment is sealed, but the situation in `noSuchSegment` isn't the one of a segment sealed, instead, the segment is gone due to truncation. Are we checking for the right state here? Are we overloading segment sealed to also mean deleted segments due to truncation?

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: SegmentOutputStream changes `SegmentOutputStreamImpl.State` is to `Seal`  and invokes the callback from EventStreamWriter which resends all the inflight events to the correct segments and does an flush on every segment.
The behavior on receiving `noSuchSegment` and `segmentIsSealed` is same, all the inflight events must be re-sent to the correct segments.

Comment (fpj) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: I understand that the behavior is the same as in both cases the writer needs to go after the successors, but the naming is odd. Refactoring should be done in a separate PR, but I suggest we change the naming to reflect correctly that this not only about sealing, it is more like state == `needSuccessors`.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 10]
```diff
@@ -379,6 +362,18 @@ public void appendSetup(AppendSetup appendSetup) {
...
+                Retry.indefinitelyWithExpBackoff(retrySchedule.getInitialMillis(), retrySchedule.getMultiplier(),
+                        retrySchedule.getMaxDelay(),
+                        t -> log.error("Error while invoking SegmentSealed call back for writer: {}", writerId, t))
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Another instance of the naming being awkward, this code can be invoked by `noSuchSegment` as well.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 11]
```diff
@@ -82,9 +83,20 @@ public Segment getSegmentForEvent(String routingKey) {
...
+                controller.getSuccessors(sealedSegment), t -> {
+                    log.error("Error while fetching successors for segment: {}", sealedSegment, t);
+                    return null;
+                });
+
+        if (successors == null) {
+            // Stream is deleted, complete all pending writes exceptionally.
+            log.error("Pending writes for Segment: {} completed with NoSuchSegmentException", sealedSegment);
+            removeWriter(sealedSegment).forEach(event -> event.getAckFuture()
+                    .completeExceptionally(new NoSuchSegmentException(sealedSegment.toString())));
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: If the stream is deleted, then the event writer cannot keep going, how are we exposing this to the application?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 12]
```diff
@@ -379,6 +362,18 @@ public void appendSetup(AppendSetup appendSetup) {
...
+                        .runInExecutor(() -> {
+                            log.debug("Invoking SealedSegment call back for {} on writer {}", wireCommand, writerId);
+                            callBackForSealed.accept(Segment.fromScopedName(getSegmentName()));
+                        }, connectionFactory.getInternalExecutor());
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: This is undoing your recent change to delay release until after invoking the callback.

Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: done, merged with the latest to include those changes.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 9 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: done, updated it to `state.needSuccessors`.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 11 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: The writer future will complete with NoSuchSegmentException. Added an integration test case to verify this behavior.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java [hunk 13]
```diff
@@ -379,6 +362,18 @@ public void appendSetup(AppendSetup appendSetup) {
             }
         }
 
+        private void retryOnWriteFail(WireCommand wireCommand) {
```
[the remark this answers is not in the document]
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: Renamed the method name to `invokeResendCallBack()`; updated the naming for the callback too.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 11 above)
Comment (fpj) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Right, but I'm asking about the high-level behavior, what's it that we are exposing to the application? I suppose we are throwing some runtime exception.

File: client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java [hunk 14]
```diff
@@ -109,4 +121,46 @@ public void testSameRoutingKey() {
...
+        when(controller.getCurrentSegments(scope, streamName))
+                .thenReturn(CompletableFuture.completedFuture(streamSegments));
+        //trigger refresh.
+        selector.refreshSegmentEventWriters(segmentSealedCallback);
+
+        //simulate stream deletion where controller.getSuccessors() is completed exceptionally.
+        when(controller.getSuccessors(segment0))
+                .thenAnswer(i -> {
+                    CompletableFuture<StreamSegmentsWithPredecessors> result = new CompletableFuture<>();
+                    result.completeExceptionally(new RuntimeException());
```
Comment (fpj) [inline client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java]: Can we use the precise exception that is supposed to be thrown, primarily for education purposes?

Comment (shrids) [reply client/src/test/java/io/pravega/client/stream/impl/SegmentSelectorTest.java]: The controller throws `io.pravega.controller.store.stream.StoreException$DataNotFoundException` which is type RuntimeException. Using RuntimeException as it is not visible to the client.
I have documented the exception in the test.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java (hunk 10 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java]: updated the code.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java (hunk 11 above)
Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: Apart from completing the write future with an exception the subsequent `writer.writeEvent(..)` will cause a `RuntimeException()` to be thrown to the application.
Note: `writer.flush()` will not throw any exception to the application.

**Comment by fpj** [comment]
System tests build has passed for this branch.

File: client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java [hunk 15]
```diff
@@ -82,9 +83,20 @@ public Segment getSegmentForEvent(String routingKey) {
     public List<PendingEvent> refreshSegmentEventWritersUponSealed(Segment sealedSegment, Consumer<Segment>
             segmentSealedCallback) {
         StreamSegmentsWithPredecessors successors = Futures.getAndHandleExceptions(
-                controller.getSuccessors(sealedSegment), RuntimeException::new);
-        return updateSegmentsUponSealed(currentSegments.withReplacementRange(successors), sealedSegment,
-                segmentSealedCallback);
+                controller.getSuccessors(sealedSegment), t -> {
+                    log.error("Error while fetching successors for segment: {}", sealedSegment, t);
+                    return null;
```
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: This is lumping together the controller throwing an exception and the stream being deleted into the same code path. I don't think this is correct. 
It the controller throw just throw and let it be retried.

Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java]: This change is based on :
* The `controller` client has its own retry mechanism 
 `io.pravega.client.stream.impl.ControllerImpl#retryConfig` which retries on grpc exception `io.grpc.StatusRuntimeException`.

* If this exception is thrown then the `EventStreamWriter.flush()` for an existing writer instance would be blocked if the Stream is deleted, since the method `handleLogSealed` will retry on an exception.
