### PR TITLE
Issue 2200: Properly handle ReinitializationRequiredException in client

### LINKED ISSUE #2199: Make ReinitializationRequiredException runtime
**Problem description**
Right now ReinitializationRequiredException is a checked exception. This issue is to consider making it a runtime exception. Per our guidelines here: https://github.com/pravega/pravega/wiki/Contributing#exception-structure
This case treads the line between checked and unchecked. The application is expected to do something about it and does need to handle it. But the way they should handle it is by restarting. It's also an open question as to how expected this should be. The exception is thrown if a host is declared dead when it is in fact alive. This obviously shouldn't occur, but depending on the algorithm employed, it may be a possibility. 

**Problem location**
EventStreamReader

### LINKED ISSUE #2200: Call close when ReinitializationRequiredException is thrown.
**Problem description**
When ReinitializationRequiredException is thrown the client should close itself so that the caller is not forced to do so. Thus avoiding any resource leak associated with the reader.

**Problem location**
EventStreamReaderImpl

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**
* Make ReinitializationRequiredException Runtime
* Always call close when ReinitializationRequiredException is thrown.

**Purpose of the change**  
Fixes #2199 and Fixes #2200.

**What the code does**  
Moves the wrapping try-catch-rethrow from the site where the exception is generated to readNextEvent which is the only public method that can throw the exception. Because we need to explicitly handle this case internally but an external caller no longer needs to, the exception is split into two:
* The internal Cause ReaderNotInReaderGroupException which is checked an explicitly handled.
* The public exception ReinitializationRequiredException which is the same as before but now extends from RuntimeException instead of Exception.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 1]
```diff
@@ -173,7 +173,7 @@ void handleEndOfSegment(Segment segmentCompleted, boolean fetchSuccesors) throws
             }
         });
         if (reinitRequired.get()) {
-            throw new ReinitializationRequiredException();
+            throw new ReaderNotInReaderGroupException();
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java]: We can pass the readerId here.

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java [hunk 2]
```diff
@@ -255,7 +255,7 @@ boolean releaseSegment(Segment segment, long lastOffset, long timeLag) throws Re
         releaseTimer.reset(calculateReleaseTime(readerId, state));
         acquireTimer.reset(calculateAcquireTime(readerId, state));
         if (!state.isReaderOnline(readerId)) {
-            throw new ReinitializationRequiredException();
+            throw new ReaderNotInReaderGroupException();
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupStateManager.java]: We can pass readerId here.

File: client/src/main/java/io/pravega/client/stream/ReaderNotInReaderGroupException.java [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+public class ReaderNotInReaderGroupException extends Exception {
+
+    private static final long serialVersionUID = 1L;
+
+    @Getter
+    private final String readerId;
+    
+    public ReaderNotInReaderGroupException(String readerId) {
+        super("Reader: "+readerId);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/ReaderNotInReaderGroupException.java]: Shouldn't checkstyle complain about the lack of spaces around `+` ?

File: client/src/main/java/io/pravega/client/stream/ReaderNotInReaderGroupException.java [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+ * you may not use this file except in compliance with the License.
+ * You may obtain a copy of the License at
+ *
+ *     http://www.apache.org/licenses/LICENSE-2.0
+ */
+package io.pravega.client.stream;
+
+import lombok.Getter;
+
+public class ReaderNotInReaderGroupException extends Exception {
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/stream/ReaderNotInReaderGroupException.java]: Please add Javadoc explaining what this exception means.
