### PR TITLE
Issue 6861: Refactor LargeEventTest in System Tests

### LINKED ISSUE #6861: Refactor LargeEventTest in System Tests
**Describe the bug**
LargeEventTest in system tests does not adequately test the LargeEvent writing functionality.

**To Reproduce**
Observe that the event writer does not have large events enabled in `largeEventSimpleTest` in `io/pravega/test/system/LargeEventTest.java`

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by ns-dell**
**Change log description**  
- Enabling large events in `EventStreamWriter` in `LargeEventTest.largeEventSimpleTest`

**Purpose of the change**  
- Closes #6861 

**What the code does**  
- Enables large events in `EventWriterConfig` for `EventStreamWriter` so that LargeEvent logic may be executed.

**How to verify it**  
- Successful system test run: pravega-development-system-tests-2/2275.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/LargeEventTest.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public void largeEventSimpleTest() {
         @Cleanup
         EventStreamWriter<ByteBuffer> writer = clientFactory.createEventWriter(STREAM_NAME,
                                                                                  new ByteBufferSerializer(),
-                                                                                 EventWriterConfig.builder().build());
+                                                                                 EventWriterConfig.builder().enableLargeEvents(true).build());
```
Comment (RaulGracia) [inline test/system/src/test/java/io/pravega/test/system/LargeEventTest.java:112]: Are the events being written larger than `Serializer.MAX_EVENT_SIZE`? The events being written are exactly of `Serializer.MAX_EVENT_SIZE` bytes, which I don't know if this exercises the large even path. Also, we can just try larger events just to see how it works with really large ones (e.g., `10 * Serializer.MAX_EVENT_SIZE`, for instance).

**Review by RaulGracia — CHANGES_REQUESTED** [review]

**Comment by RaulGracia** [comment]
@ns-dell Now we can see that the large event path is actually being exercised. We can see in the logs that transient segments are being created for the Stream created in the `LargeEventTest`:
```:2022-09-13T19:44:42.17500667Z stdout F 2022-09-13 19:44:42,173 6905934 [epollEventLoopGroup-9-3] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Received request: WireCommands.CreateTransientSegment(type=CREATE_TRANSIENT_SEGMENT, requestId=21474836481, writerId=83bf524c-da08-4f0a-8fda-82ac190c67f7, parentSegment=testScopeSampleYqqbl7/testStreamSampleY/0.#epoch.0)
```
And appends are happening to this segment:
```
2022-09-13T19:44:42.25093819Z stdout F 2022-09-13 19:44:42,250 6906011 [epollEventLoopGroup-9-3] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Received request: Append(segment=testScopeSampleYqqbl7/testStreamSampleY/0.#epoch.0#transient.83bf524cda084f0a8fda82ac190c67f7.404f223abed14756b704d324434cd644, writerId=83bf524c-da08-4f0a-8fda-82ac190c67f7, eventNumber=0, eventCount=1, data=AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 0, widx: 8388608, cap: 8388608/8388608, unwrapped: PooledUnsafeDirectByteBuf(ridx: 8388660, widx: 8388660, cap: 12582912)), expectedLength=0, flowId=21474836483)
2022-09-13T19:44:42.251083511Z stdout F 2022-09-13 19:44:42,251 6906012 [epollEventLoopGroup-9-3] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: appendWithOffset [testScopeSampleYqqbl7/testStreamSampleY/0.#epoch.0#transient.83bf524cda084f0a8fda82ac190c67f7.404f223abed14756b704d324434cd644, 8388608]
2022-09-13T19:44:42.318773725Z stdout F 2022-09-13 19:44:42,318 6906079 [epollEventLoopGroup-9-3] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Received request: Append(segment=testScopeSampleYqqbl7/testStreamSampleY/0.#epoch.0#transient.83bf524cda084f0a8fda82ac190c67f7.404f223abed14756b704d324434cd644, writerId=83bf524c-da08-4f0a-8fda-82ac190c67f7, eventNumber=1, eventCount=1, data=AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 0, widx: 8388608, cap: 8388608/8388608, unwrapped: PooledUnsafeDirectByteBuf(ridx: 8388660, widx: 8388660, cap: 12582912)), expectedLength=8388608, flowId=21474836484)
2022-09-13T19:44:42.318928792Z stdout F 2022-09-13 19:44:42,318 6906079 [epollEventLoopGroup-9-3] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: appendWithOffset [testScopeSampleYqqbl7/testStreamSampleY/0.#epoch.0#transient.83bf524cda084f0a8fda82ac190c67f7.404f223abed14756b704d324434cd644, 8388608]
```

I have checked with other system tests builds, and these log lines do not appear, meaning that we were not exercising this code path.

**Review by RaulGracia — APPROVED** [review]
