### PR TITLE
Issue 1510: List streams in scope throws exception if there is partially created stream with no configuration

### LINKED ISSUE #1510: Bug: list streams in scope can fail if a stream is getting created and we try to fetch its metadata
**Problem description**
ListStreamsInScope api implementation assumes that if a znode for stream is present, its metadata would also be available.
However, there could be a race with stream creation or there could be a partially created stream that had failed. Such streams may or may not have configurtion. So a getConfiguration api call may throw DataNotFoundException.
ListStreamsInScope should handle this correctly.  

**Problem location**
AbstractStreamMetadataStore.java

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
If a stream is only partially created, with no configuration created yet (or failed) then `liststreamsinscope` api fails to list streams. 

**Purpose of the change**  
Fixes #1510 

**What the code does**  
Ignores streams for which we get data not found exception while doing getConfiguration. 

**How to verify it**  
Unit test added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java [hunk 1]
```diff
@@ -229,12 +230,20 @@ public OperationContext createContext(String scope, String name) {
...
     public CompletableFuture<Map<String, StreamConfiguration>> listStreamsInScope(final String scopeName) {
         return getScope(scopeName).listStreamsInScope().thenCompose(streams -> {
-            HashMap<String, CompletableFuture<StreamConfiguration>> result = new HashMap<>();
+            HashMap<String, CompletableFuture<Optional<StreamConfiguration>>> result = new HashMap<>();
             for (String s : streams) {
                 Stream stream = getStream(scopeName, s, null);
-                result.put(stream.getName(), stream.getConfiguration());
+                result.put(stream.getName(), 
+                        Futures.exceptionallyExpecting(stream.getConfiguration(), 
+                                e -> e instanceof StoreException.DataNotFoundException,
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: What if data not found is actually due to some form of data corruption? We will never know it and will continuously exclude the stream, no?

Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java]: If for whatever reason any stream does not have its configuration present, we should not fail listing of all other streams.
Presently the failure could happen for several reasons -- 
1. a partially created failed stream with no configuration record created
(presence of such streams currently causes consistent failure to list streams in scope)
2. an on-going stream creation where we have not gotten around to creating its configuration.
(this would be transient and subsequent attempts to list streams in scope should succeed)
3. an ongoing delete stream where configuration metadata is removed but the stream root metadata is not yet cleaned up.
(this is also transient).  
4. metadata corruption leading to configuration being deleted.
(though this is unlikely unless someone goes and messes up the metadata, but any such corruption will render stream unusable for many scenarios. In any case, if we want admin to be able to list such streams and know their status, we should address it in a separate issue).

The objective of this issue is to NOT fail listing of streams for the `listStreamsInScope` api for any of these above reasons. And this fix addresses them.

If we want to have the ability to list failed/corrupted streams with their corresponding status we should have a separate issue for the same.
