### PR TITLE
Issue 1298: Correct gauge metrics

### LINKED ISSUE #1298: Gauge type of metrics reports incorrect values
**Problem description**
The open transaction gauge metric doesn't decrease when the transaction is committed.

**Problem location**
Metrics framework.

**Suggestions for an improvement**
Report correct values for gauge metrics.

### PR DESCRIPTION
**Pull request by Abhijeet-Jadhav**
**Change log description**
Corrected reporting of gauge metrics.

**Purpose of the change**
Fixes #1298 

**What the code does**
Corrects gauge metrics.

**How to verify it**
MetricsProviderTest

### CODE REVIEW

File: shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java [hunk 1]
```diff
@@ -57,7 +58,9 @@ public void onRemoval(RemovalNotification<String, Counter> removal) {
                     @Override
                     public void onRemoval(RemovalNotification<String, Gauge> removal) {
                         Gauge gauge = removal.getValue();
-                        metrics.remove(gauge.getName());
+                        if (removal.getCause() != RemovalCause.REPLACED) {
```
Comment (fpj) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java]: Don't we need to apply this change to all `onRemoval` calls in this class?

Comment (Abhijeet-Jadhav) [inline shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java]: Yes, we need to, modified other `onRemoval ` calls.
