### PR TITLE
Issue 3223: RetentionTest failure

### LINKED ISSUE #3223: RetentionTest failure
**Problem description**
Retention test is failing in the new system test platform. The reason is that retention is not performed on a Stream. Looking at the Controller logs, we observed the following operations on the retention znode (`buckets/0`):

```
controller_2018-12-18.1.log:2018-12-18 05:59:26,367 417658 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeDataChanged path:/pravega/pravega/buckets/0/ekNibXNRakhiMC9ITFNvenFmamVX for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 05:59:27,646 418937 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeDeleted path:/pravega/pravega/buckets/0/ekNibXNRakhiMC9ITFNvenFmamVX for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 05:59:26,105 417396 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/pravega/pravega/buckets/0 for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 05:59:26,367 417658 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeDataChanged path:/pravega/pravega/buckets/0/ekNibXNRakhiMC9ITFNvenFmamVX for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 05:59:27,646 418937 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeDeleted path:/pravega/pravega/buckets/0/ekNibXNRakhiMC9ITFNvenFmamVX for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 05:59:27,647 418938 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/pravega/pravega/buckets/0 for sessionid 0x10029a7d9350034
controller_2018-12-18.1.log:2018-12-18 06:00:22,348 473639 [ControllerServiceMain-SendThread(xxx:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got WatchedEvent state:SyncConnected type:NodeDeleted path:/pravega/pravega/buckets/0 for sessionid 0x10029a7d9350034
```

Apparently, the last `NodeDeleted` operation is against the root node `path:/pravega/pravega/buckets/0`, which is not supposed to happen. This occurs before `RetentionTest`, but may be the root cause for this test to fail, as is the only one validating the retention service.

**Problem location**
Retention service.

**Suggestions for an improvement**
Prevent root znode to be deleted.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
This PR explicitly creates Controller bucket zNodes before a change listener is registered. By doing this, we make sure that a bucket zNode is not of type "container", which may be the case if it is created by Curator as a parent of an actual zNode. This prevents Zookeeper from automatically deleting bucket zNodes in its internal process of garbage collection of empty containers.

**Purpose of the change**  
Fixes #3223.

**What the code does**  
This PR initializes the Stream bucket znode when we register a listener for changes on that bucket.

The reason for doing so is the following: Zookeeper recently (v`3.5+`) introduced a new kind of nodes called `containers` ([ref](https://issues.apache.org/jira/browse/ZOOKEEPER-2163)). This kind of nodes differ from traditional zNodes in the following: once a `container` is populated and then emptied (i.g., all its child nodes have been deleted), it is candidate for garbage collection in Zookeeper (see [ContainerManager.java](https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/server/ContainerManager.java)):
```
...
Once started, it periodically checks container nodes that have a cversion > 0 and have no children. A
delete is attempted on the node.
...
```

By default, Curator exploits this feature when available. This implies that, when creating a zNode with a non-existent parent, Curator can create a `container` for the parent node and a zNode for the child one (i.e., `PERSISTENT`). 

This was the case for the issue that motivates this PR. Before the execution of `RetentionTest`, another test (`RestAPITest`) created and deleted a Stream with a retention policy, so it was added and removed from a Stream bucket (`buckets/0`). Curator seems to create `bucket/0` as a `container` and, according to the previous description of `ContainerManager`, the bucket node was candidate for garbage collection (i.e., filled, and then emptied) before the execution of `RetentionTest`. Once Zookeeper removes that bucket, the retention service (`StreamCutBucketService`) stops working, given that the watch on the bucket is broken. 

To avoid empty Stream buckets from being deleted, this PR explicitly creates the bucket node as a zNode. This prevents Curator from making it of type `container` and suffices to prevent Zookeeper from deleting it. 

Note: We also tried to use the option `CuratorFrameworkFactory.builder().dontUseContainerParents()`, but it seems to do not work as expected when used jointly with `creatingParentsIfNeeded()`.

**How to verify it**  
Locally replayed failure scenario of `RetentionTest` and works. 
System test build passes entirely (only `BookieFailoverTest` has been disabled).
All tests should be passing as before.

### CODE REVIEW

**Comment by RaulGracia** [comment]
[RetentionTest failure](https://trello.com/c/p8dU4ZQI/80-retentiontest-failure)

**Comment by shrids** [comment]
From the curator java docs observing that 
`client.create().creatingParentsIfNeeded()` would cause the parent nodes to be created with `org.apache.zookeeper.CreateMode#PERSISTENT` type by default.

`org.apache.curator.framework.api.CreateModable#withMode` javadoc also indicates that by default the CreateMode is Persistent.

**Comment by RaulGracia** [comment]
Yes @shrids, you are right. But apparently, this behavior is not completely honored. Even using `dontUseContainerParents()` in `CuratorFrameworkFactory` doesn't fix the problem.

The difference between `master` and this PR is the following.

In `master`, a Stream bucket is created by the first task (either `StreamMetadataTasks` or `UpdateStreamTask`) that invokes `addUpdateStreamForAutoStreamCut()`. So the creation of the bucket zNode is automatically performed as a parent of a Stream that goes into that bucket:

```
String retentionPath = String.format(RETENTION_PATH, bucket, encodedScopedStreamName(scope, stream));
byte[] serialize = SerializationUtils.serialize(retentionPolicy);
...
storeHelper.createZNodeIfNotExist(retentionPath, serialize);
```

In this PR, we first create the bucket as a znode before adding any Stream (in `registerBucketChangeListener`):

```
storeHelper.addNode(bucketRoot)
```

This avoids that Curator creates the bucket parent (`.../buckets/x`) in the process of registering the first Stream on that bucket, and thus set its type to `container`.

This leads to two considerations:
- Are there other znodes that we believe that are not going to be deleted, but they actually are in some cases? For instance, I see these attempts to automatically delete znodes in ZK logs of a system test run, which originated the problem that this PR tries to solve:
```
2019-01-11 07:59:22,326 [myid:1] - INFO  [ContainerManagerTask:ContainerManager@119] - Attempting to delete candidate container: /pravega/pravega/cluster/faulthandlerleader
2019-01-11 07:59:22,332 [myid:1] - INFO  [ContainerManagerTask:ContainerManager@119] - Attempting to delete candidate container: /pravega/pravega/cluster/controllers
```
- Should be create and issue in the Curator project? Apparently, the behavior that we are encountering is not the one specified in the docs, so maybe it would be useful to create an issue for that in Curator.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 1]
```diff
@@ -321,6 +322,9 @@ public void unregisterBucketOwnershipListener() {
     public void registerBucketChangeListener(int bucket, BucketChangeListener listener) {
         Preconditions.checkNotNull(listener);
 
+        String bucketRoot = String.format(BUCKET_PATH, bucket);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: This change does not seem right. There are other listeners in this class too, like the ownership one. Also, this is the wrong place to do this. If we are to create this bucket znode, it should be during the process of acquiring ownership, not while registering a listener. 

I need to do some further investigation before making a concrete proposal here.

Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Follow-up question: why not create all necessary persistent znodes during the initialization of the controller process?

https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/Main.java

Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: @fpj This is another possibility that may be interesting, given that I observed the same phenomenon related to other znodes. This can be done when instantiating a new `ZKStreamMetadataStore` object. In fact, `ZKHostStore` does something similar in the method `tryInit()`, but instead of ensuring that the znode is created in the constructor, it is check on every call to Zookeeper. I will try to find a better, broader znode initialization approach.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 2]
```diff
@@ -45,6 +46,7 @@
 
 @Slf4j
 @RunWith(SystemTestRunner.class)
+@Ignore
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: This was a temporary change for testing purposes, is reverted now.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 1 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Following your suggestion, I added a new method to `StreamMetadataStore` interface called `initializeMetadataStore()`. In the case of `ZKStreamMetadataStore`, it contains the logic to initialize the Stream buckets. This method is invoked in `ControllerServiceStarter`, just after the `StreamMetadataStore` object gets created. This may be a suitable "centralized" point to initialize all the necessary metadata items to facilitate maintenance.

Note that this solution fixes the reported problem (system tests are passing with the current version of the code) and could be easily cherry-picked to previous versions. But it could subject to changes in PR #3230, given that the initialization of "buckets" will be done for multiple services, not just for the retention service.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 3]
```diff
@@ -460,6 +463,35 @@ public void unregisterBucketListener(int bucket) {
                           });
     }
 
+    /**
+     * When managing the Controller's metadata in Zookeeper, we explicitly create parent bucket zNodes (so they are of
+     * type "zNode"). Otherwise, they may be inadvertently created as Zookeeper "containers" by Curator. This would lead
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Can you point in this comment to curator documentation that says this, please?

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 4]
```diff
@@ -460,6 +463,35 @@ public void unregisterBucketListener(int bucket) {
...
+     * these zNodes to be candidates for automatic removal by Zookeeper if they become empty.
+     */
+    @Override
+    public void initializeMetadataStore() {
+        List<CompletableFuture<Void>> initializationFutures = new ArrayList<>();
+        Retry.RetryWithBackoff retryPolicy = Retry.withExpBackoff(100, 2, 10);
+        Predicate<Throwable> isDataExistsException = ex -> Exceptions.unwrap(ex) instanceof StoreException.DataExistsException;
+        for (int bucket = 0; bucket < bucketCount; bucket++) {
+            final String bucketPath = String.format(BUCKET_PATH, bucket);
+            initializationFutures.add(retryPolicy.retryWhen(isDataExistsException.negate()).run(() ->
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Does curator have its own retry mechanism? Do we need to retry ourselves?

File: controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java [hunk 5]
```diff
@@ -1098,4 +1098,9 @@
      * @return CompletableFuture which indicates completion of processing.
      */
     CompletableFuture<Void> deleteWaitingRequestConditionally(String scope, String stream, String processorName, OperationContext context, ScheduledExecutorService executor);
+
+    /**
+     * This method initializes any piece of metadata that is necessary for the correct operation of the Controller.
+     */
+    void initializeMetadataStore();
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java]: Out of curiosity: say that we want to destroy a cluster, would we need code to also delete the initialization metadata? Maybe that would be done externally, via a script or something.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 3 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Added a reference for this. Actually, the first line of the page says: `NOTE: Most Curator recipes will autocreate parent nodes of paths given to the recipe as CreateMode.CONTAINER`.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 4 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Done.

File: controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java (hunk 5 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/StreamMetadataStore.java]: Changed the approach according to the suggestions from @shiveshr. Now the buckets (including `ownership` znode) get initialized in `StreamCutService`.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 6]
```diff
@@ -460,6 +463,35 @@ public void unregisterBucketListener(int bucket) {
...
+                            log.debug("Stream bucket already initialized: {}.", bucketPath);
+                        } else {
+                            throw new CompletionException("Unexpected exception initializing Stream bucket.", ex);
+                        }
+                        return null;
+                    })));
+        }
+
+        // Make sure that Stream buckets are created after leaving this method.
+        Futures.allOf(initializationFutures).join();
```
[the remark this answers is not in the document]
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: Changed the approach according to the suggestions from @shiveshr. Now the buckets (including `ownership` znode) get initialized in `StreamCutService`.

**Comment by RaulGracia** [comment]
@fpj @shiveshr Please, let me know if the current approach reasonably satisfies the existing points of view on this issue. If so, I will run system tests again with the latest changes.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 7]
```diff
@@ -460,6 +461,38 @@ public void unregisterBucketListener(int bucket) {
...
+    /**
+     * When managing the Controller's metadata in Zookeeper, we explicitly create parent bucket zNodes (so they are of
+     * type "zNode"). Otherwise, they may be inadvertently created as Zookeeper "containers" by Curator. This would lead
+     * these zNodes to be candidates for automatic removal by Zookeeper if they become empty. For more information on
+     * the use of Zookeeper containers in Curator recipes, visit: https://curator.apache.org/curator-recipes/index.html
+     */
+    @Override
+    public CompletableFuture<Void> createBucketsRoot() {
+        List<CompletableFuture<Void>> initializationFutures = new ArrayList<>();
+        initializationFutures.add(initializeZNode(BUCKET_OWNERSHIP_PATH)); // Also initialize ownership zNode.
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: please also add the root path explicitly as well.. 
following should be done:
"/buckets"
"/buckets/ownership"
"buckets/<bucket-id>"

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 8]
```diff
@@ -460,6 +461,38 @@ public void unregisterBucketListener(int bucket) {
...
+        for (int bucket = 0; bucket < bucketCount; bucket++) {
+            final String bucketPath = String.format(BUCKET_PATH, bucket);
+            initializationFutures.add(initializeZNode(bucketPath));
+        }
+
+        return Futures.allOf(initializationFutures);
+    }
+
+    private CompletableFuture<Void> initializeZNode(String zNodePath) {
+        return storeHelper.addNode(zNodePath).handle(
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: instead of addNode please use 
``` 
CompletableFuture<Integer> createZNodeIfNotExist(final String path, final boolean createParent) 
```

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java (hunk 7 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: we also want to chain `bucketRootPath --> bucketOwnershipPath --> ListOf bucketPath` rather than run them concurrently as bucket path creation may fail if bucketRootPath is not yet created.

File: controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java [hunk 9]
```diff
@@ -460,6 +461,38 @@ public void unregisterBucketListener(int bucket) {
...
+    /**
+     * When managing the Controller's metadata in Zookeeper, we explicitly create parent bucket zNodes (so they are of
+     * type "zNode"). Otherwise, they may be inadvertently created as Zookeeper "containers" by Curator. This would lead
+     * these zNodes to be candidates for automatic removal by Zookeeper if they become empty. For more information on
+     * the use of Zookeeper containers in Curator recipes, visit: https://curator.apache.org/curator-recipes/index.html
+     */
+    @Override
+    public CompletableFuture<Void> createBucketsRoot() {
+        List<CompletableFuture<Void>> initializationFutures = new ArrayList<>();
+        initializationFutures.add(initializeZNode(BUCKET_ROOT_PATH).thenCompose(v -> initializeZNode(BUCKET_OWNERSHIP_PATH)));
```
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/store/stream/ZKStreamMetadataStore.java]: it should be following:
```
return initializeZNode(BUCKET_ROOT_PATH)
.thenCompose(v -> initializeZNode(BUCKET_OWNERSHIP_PATH))
.thenCompose(v -> {
        for (int bucket = 0; bucket < bucketCount; bucket++) {
            final String bucketPath = String.format(BUCKET_PATH, bucket);
            initializationFutures.add(initializeZNode(bucketPath));
        }
         return Futures.allOf(initializationFutures); 
})
