### PR TITLE
Issue 1692: Sporadic No Value Present error for getSuccessors call

### LINKED ISSUE #1692: Systemtest: Controller getSuccessors API fails with message "No value found"
**Problem description**
In one of the system test runs we find large number of the following exception:

2017-08-02 06:37:55,751 323093 [clientInternal-1] TRACE i.p.c.stream.impl.ControllerImpl - ENTER getSuccessors@11982395992477 [Segment(scope=testReadWriteAndAutoScaleScope1369069020, streamName=testReadWriteAndAutoScaleStream, segmentNumber=5)].
2017-08-02 06:37:55,774 323116 [grpc-default-executor-5] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call failed with server error: INTERNAL: No value present
2017-08-02 06:37:55,775 323117 [grpc-default-executor-5] WARN  i.p.c.stream.impl.ControllerImpl - getSuccessors failed:
java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: INTERNAL: No value present
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onError(ControllerImpl.java:722)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: No value present
        at io.grpc.Status.asRuntimeException(Status.java:543)
        ... 11 common frames omitted
2017-08-02 06:37:55,775 323117 [grpc-default-executor-5] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE getSuccessors@11982395992477 (elapsed=23708us).

We could not capture the controller server logs when this happened. "No value present" is typically used by **NoSuchElementException**. So guess is that the API failed in the Controller Service with NoSuchElementException exception.

**Problem location**
Controller's getSuccessors API

**Suggestions for an improvement**
Investigate why the controller API can fail with this error. Since we don't have controller logs for this particular run we need check if this issue reproduces and investigate further.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
The issue was that while creating segments in segment table, we can supply an old timestamp (time when scale request was generated). This timestamp can be older than the previous scale operation's timestamp in the history table. 
This caused our search logic in history table to look include records which were older than segment creation record which broke the search logic. 

So as a fix, we have done two things here -> 
1. ensure that segment creation time is strictly greater than timestamp on previous scale record in history table. 
2. Ensure that even if segment start time is less than previous scale record in history table, our computation is able to handle it. 

Another low probability chance when we may find record in history table but not in segment table:

While doing get Successor, we should first fetch history table followed by segment table. 
This is because while performing scale we first write to segment table and then to history table. 

Currently code concurrently fetches history and segment tables. 
The problem that can happen now is if there is a race with scale, then getHistoryTable may get the updated table while getSegmentTable may retrieve older value. This will cause getSuccessors to throw `No value present` when it tries to retrieve new segment from the segmentTable.

This is very low probability because after we create segments in segment table, we contact SSS to create segments in segment store. only after that do we create partial record in history table.
for a get successor to come and get updated history table but stale segment table while trying to fetch them both concurrently is less likely though theoretically possible.
 
**Purpose of the change**
Fixes #1692

**What the code does**
Three things:
1. Ensure segment creation times in segment table is always monotonically increasing and greater than previous scale's time. 
2. Ensure that even if segment creationTime is less than previous scale time, the core logic in table helper is able to compute and find successors correctly. 
3. Ensures that in getSuccessors computation on controller's stream store, we first fetch history table, followed by segment table in thenCompose of getHistoryTable's future. 

**How to verify it**
Two new unit test added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 1]
```diff
@@ -238,41 +239,48 @@ public String getScopeName() {
...
-            List<Integer> candidates = TableHelper.findSegmentSuccessorCandidates(segment,
-                    indexTableFuture.getNow(null).getData(),
-                    historyTableFuture.getNow(null).getData());
-            return findOverlapping(segment, candidates);
-        });
+        return getHistoryTable()
+                .thenApply(historyTable -> {
+                    CompletableFuture<Segment> segmentFuture = getSegment(number);
+                    CompletableFuture<Data<T>> indexTableFuture = getIndexTable();
+                    return new ImmutableTriple<>(historyTable, segmentFuture, indexTableFuture);
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: You can change this `thenApply` to `thenCompose` and return `CompletableFuture.allOf` instead of `ImmutableTriple`. The behavior is identical but your code will be much cleaner and you'll have fewer callbacks to worry about.

Comment (andreipaduroiu) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Oh I see what you did. You actually need the result of all of them. Then You can use `FutureHelpers.allOfWithResults` which will return an array (or list) in the same order in which you passed them to the function.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 2]
```diff
@@ -238,41 +239,48 @@ public String getScopeName() {
...
-                        list -> new SimpleImmutableEntry<>(successor, list.stream().map(Segment::getNumber).collect(Collectors.toList()))));
-            }
-            return FutureHelpers.allOfWithResults(resultFutures);
-        }).thenApply(list -> list.stream().collect(Collectors.toMap(e -> e.getKey().getNumber(), e -> e.getValue())));
+        // Ensure the order, we should first get history table followed by segment table because during scale we first write to
+        // segment table followed by history table. So if a record exists in history table, then we are guaranteed to find it in
+        // segment table.
+        return verifyLegalState()
+                .thenCompose(legal -> getHistoryTable()
+                        .thenApply(historyTable -> new ImmutableTriple<>(historyTable, getIndexTable(), getSuccessorsForSegment(number)))
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Same here.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 3]
```diff
@@ -283,19 +291,17 @@ public String getScopeName() {
...
-
-        return all.thenCompose(x -> {
-            final Segment segment = segmentFuture.getNow(null);
-            List<Integer> candidates = TableHelper.findSegmentPredecessorCandidates(segment,
-                    indexTableFuture.getNow(null).getData(),
-                    historyTableFuture.getNow(null).getData());
-            return findOverlapping(segment, candidates);
-        }).thenApply(list -> list.stream().map(e -> e.getNumber()).collect(Collectors.toList()));
+        return verifyLegalState().thenCompose(x -> getHistoryTable()
+                .thenApply(historyTable -> new ImmutableTriple<>(historyTable, getSegment(number), getIndexTable())))
```
Comment (andreipaduroiu) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: And here.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: actually not all of them are future.. first one is data and other two are futures. So using FutureHelpers.allOfWithResults would still need to be paired up with the data..

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 4]
```diff
@@ -375,7 +381,14 @@ public String getScopeName() {
 
                         log.info("Scale {}/{} for segments started. Creating new segments. SegmentsToSeal {}", scope, name, sealedSegments);
                         // fresh run
-                        return scaleCreateNewSegments(newRanges, scaleTimestamp, segmentTable, activeEpoch);
+                        // Ensure that segment.creation time is monotonically increasing after each new scale
+                        long lastScaleTime = HistoryRecord.readLatestRecord(historyTable.getData(), true).map(HistoryRecord::getScaleTime).orElse(0L);
+
+                        long scaleEventTime = Math.max(System.currentTimeMillis(), scaleTimestamp);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: `scaleTimestamp` must have occurred in the past, so the max will always be `System.currentTimeMillis()`. `scaleTimestamp` will never be larger.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java [hunk 5]
```diff
@@ -375,7 +381,14 @@ public String getScopeName() {
...
+
+                        long segmentCreationTimestamp = Math.max(scaleEventTime, lastScaleTime + 1);
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: I think the logic we trying to implement here is that `segmentCreationTimestamp` should be `lastScaleTime + 1` in the case the `scaleTimestamp` is smaller than `lastScaleTime`.

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 4 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: Because of controller clock skews, a scaleTime set by another controller can be higher than the System.currentTimeInMillis on this controller.
Hence we take the max of prevScaleTS+1, System.currentTimeInMillis and scaleTimestamp

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 5 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: replied above

File: controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java (hunk 4 above)
Comment (fpj) [reply controller/src/main/java/io/pravega/controller/store/stream/PersistentStreamBase.java]: ok, makes sense, but let's add a comment explaining what's going with this logic, please.
