### PR TITLE
Issue 5494: fix test SecureConnectionFactoryImplTest.getActiveChannelTestWithConnectionPooling

### LINKED ISSUE #5494: Unit test failure: SecureConnectionFactoryImplTest.getActiveChannelTestWithConnectionPooling
**Problem description**
Stack trace:
```
io.pravega.client.connection.impl.SecureConnectionFactoryImplTest > getActiveChannelTestWithConnectionPooling FAILED
    java.lang.AssertionError: Expected active channel count is 0 expected:<0> but was:<1>
```

**Problem location**
`SecureConnectionFactoryImplTest.getActiveChannelTestWithConnectionPooling`

**Suggestions for an improvement**
Test should pass reliably.

### PR DESCRIPTION
**Pull request by Tristan1900**
**Change log description**  
SecureConnection test doesn't enable security config on the client side. This leads to a client connection failure and this failure causes a race condition of closing the underlying TcpConnection.

**Purpose of the change**  
Fix #5494 

**What the code does**  
Enable TLS on client side

**How to verify it**  
No `javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER` error should occur in the test and `ClientSocketReaders` should be only closed due to connection is closed but not `EOFException`

### CODE REVIEW

File: client/src/test/java/io/pravega/client/connection/impl/ConnectionFactoryImplTest.java [hunk 1]
```diff
@@ -142,7 +142,10 @@ public void authTokenCheckFailed(WireCommands.AuthTokenCheckFailed authTokenChec
 
     @Test
     public void getActiveChannelTestWithConnectionPooling() throws InterruptedException, ConnectionFailedException {
```
Comment (shrids) [inline client/src/test/java/io/pravega/client/connection/impl/ConnectionFactoryImplTest.java:144]: Test `getActiveChannelTestWithoutConnectionPooling` also has a similar issue ...

Comment (Tristan1900) [reply client/src/test/java/io/pravega/client/connection/impl/ConnectionFactoryImplTest.java:144]: Thanks!

**Review by tkaitchuck — APPROVED** [review]

**Review by andreipaduroiu — APPROVED** [review]
