### PR TITLE
Issue 3484: (SegmentStore) Cleaning up some log messages

### LINKED ISSUE #3484: Various Segment Store Fixes and Improvements
**Problem description**
- Make the following DEBUG-level
```
2019-02-16 18:30:39,485 279364746 [core-2] INFO  i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[3-654902]: Exit RecoveryMode.`
`2019-02-16 18:33:02,651 279507912 [core-24] INFO  i.p.s.server.logs.DurableLog - DurableLog[3]: MetadataCheckpointOperation queued.`
`2019-03-19 02:12:21,594 7616232 [core-23] INFO  i.p.s.s.a.SegmentAttributeBTreeIndex - AttributeIndex[124362]: Cleared all cache entries (0)
```
- Consider not logging if this is 0
```
2019-03-19 02:12:21,190 7615828 [core-21] DEBUG i.p.s.s.c.StreamSegmentMetadata - StreamSegment[118615]: Evicted 0 attribute(s).
```
- Add Container Id here:
```
2019-03-19 02:11:01,226 7535864 [core-16] DEBUG i.p.s.s.c.StreamSegmentMetadata - StreamSegment[115918]: Sealed = true.
```
- Fix these spurious errors:
```
2019-02-16 18:24:07,370 278972631 [CacheManager RUNNING] ERROR i.p.s.server.CacheManager - CacheManager: Error.
java.lang.IllegalArgumentException: size must be a non-negative number
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at io.pravega.segmentstore.server.CacheManager$CacheStatus.<init>(CacheManager.java:411)
    at io.pravega.segmentstore.server.CacheManager$CacheStatus.withUpdatedSize(CacheManager.java:422)
    at io.pravega.segmentstore.server.CacheManager$CacheStatus.access$000(CacheManager.java:386)
    at io.pravega.segmentstore.server.CacheManager.applyCachePolicy(CacheManager.java:218)
    at io.pravega.segmentstore.server.CacheManager.runOneIteration(CacheManager.java:120)
```

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Changed some log messages from INFO to DEBUG.
- Removed duplicated log messages or irrelevant messages (i.e., when it said it didn't do anything).
- Fixed a spurious bug in `CacheManager` that would have caused a stack trace to be logged but with no side effects.

**Purpose of the change**  
Fixes #3484.

**What the code does**  
See Change Log Description above. These are non-functional changes.
These changes were collected while parsing many GBs of logs during recent system test debugging sessions and are meant to reduce noise and improve accuracy.

**How to verify it**  
Non-functional changes. Build must pass.

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 1]
```diff
@@ -220,6 +219,7 @@ protected void doStart() {
         if (this.durableLog.isOffline()) {
             // Attach a listener to the DurableLog's awaitOnline() Future and initiate the services' startup when that
             // completes successfully.
+            log.info("{}: DurableLog is OFFLINE. Not starting secondary services yet.");
```
Comment (RaulGracia) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: This has an extra `{}`, or a missing argument in the call.

Comment (andreipaduroiu) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java]: Fixed. Thank you.
