### PR TITLE
Issue 1620, 1628: ControllerEventProcessor failover handling bugs

### LINKED ISSUE #1620: Event Processor's creation of readergroup node is not idempotent
**Problem description**
If readergroup record is attempted to be created again it fails with 
Error creating commit event processor group NodeExists for /pravega/pravega-cluster/eventProcessors/172.16.22.8-c349da3c-2abc-4345-857b-3f76e95ce708/commitStreamReaders

This results in event processors to fail repeatedly and never start. 

**Problem location**
EventProcessor and ZkCheckpointStore.

**Suggestions for an improvement**
Ignore readerGroup exists error because process-id is unique and wont clash with any other processes' attempt to readergroup creation. 
So we are sure that if this exists, then this current process has created it in a previous iteration and hence attempting to recreate readergroup record should be idempotent.

### LINKED ISSUE #1628: EventProcessor failover fails with exception 'ReaderGroup is not empty'
**Problem description**
```
2017-07-21 03:43:04,625 4823 [controllerpool-57] ERROR i.p.c.s.e.ControllerEventProcessors - Error notifying failure of process=controller.marathon.mesos-1bc1846d-5992-486e-8f24-b74f5cb33c18 in event processor group EventProcessorGroup[abortStreamReaders]
io.pravega.controller.store.checkpoint.CheckpointStoreException: ReaderGroup is not empty.
        at io.pravega.controller.store.checkpoint.ZKCheckpointStore.removeReaderGroup(ZKCheckpointStore.java:130)
        at io.pravega.controller.eventProcessor.impl.EventProcessorGroupImpl.notifyProcessFailure(EventProcessorGroupImpl.java:218)
        at io.pravega.controller.server.eventProcessor.ControllerEventProcessors.lambda$null$19(ControllerEventProcessors.java:301)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Problem location**
EventProcessorGroupImpl

**Suggestions for an improvement**
Fix the issue so that event processor failover can succeed.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
#1620 creation of readergroup is not idempotent. This can cause exceptions to be thrown if it is attempted again. 
#1628 clean up of old readergroup was not happening with node not empty because the process was incorrectly supplied as active process rather than the one being failed over.

**Purpose of the change**
Fixes #1628 
Fixes #1620 

**What the code does**
makes create reader group idempotent.
fixes the bug which passed process for which readergroup has to be cleaned up incorrectly

**How to verify it**
all unit tests should pass. 
system tests should no longer show these issues.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 1]
```diff
@@ -82,7 +82,13 @@
 
     void initialize() throws CheckpointStoreException {
 
-        checkpointStore.addReaderGroup(actorSystem.getProcess(), eventProcessorConfig.getConfig().getReaderGroupName());
+        try {
+            checkpointStore.addReaderGroup(actorSystem.getProcess(), eventProcessorConfig.getConfig().getReaderGroupName());
+        } catch (CheckpointStoreException e) {
+            if (!e.getType().equals(CheckpointStoreException.Type.NodeExists)) {
+                throw e;
+            }
```
Comment (skrishnappa) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: debug log the exception in else block.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 2]
```diff
@@ -82,7 +82,13 @@
 
     void initialize() throws CheckpointStoreException {
 
-        checkpointStore.addReaderGroup(actorSystem.getProcess(), eventProcessorConfig.getConfig().getReaderGroupName());
+        try {
+            checkpointStore.addReaderGroup(actorSystem.getProcess(), eventProcessorConfig.getConfig().getReaderGroupName());
+        } catch (CheckpointStoreException e) {
+            if (!e.getType().equals(CheckpointStoreException.Type.NodeExists)) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: Let's at least add a warn log message here in the case we don't throw (node exists).

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java [hunk 3]
```diff
@@ -82,7 +82,13 @@
 
     void initialize() throws CheckpointStoreException {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: If I understand it correctly, initialize can be called multiple times, which causes the problem with adding reader groups. If this is right, then we need to make sure that initialize is idempotent. Would it make sense to add a test case that invokes initialize twice and make sure that nothing is thrown?

Comment (bhargav-gulavani) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: I share the concern raised by @fpj.

Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: I will add a test for this and verify that nothing else is not breaking.

**Comment by skrishnappa** [comment]
>> I dont think we should do that because we also need to individually tell ReaderGroup about readerOffline and there is no bulk api to do that.

Yes readerOffline will still be there, but removerReader calls will go.

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 2 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: done

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 1 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: done

File: controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java (hunk 3 above)
Comment (shiveshr) [inline controller/src/main/java/io/pravega/controller/eventProcessor/impl/EventProcessorGroupImpl.java]: there isnt a simple test that i can author here because there is no existing event processor group unit test where i could call initialize twice.. 
i can add a test where i mock most of the things. 
And controllerEventProcessor should ensure its initialize is also idempotent (if its not testing it already)
