### PR TITLE
Issue 4639: Table store helper to retry only on unknownhost and auth failure for update requests

### LINKED ISSUE #4639: Controller's table client should not retry for updates on Connection Exceptions
**Problem description**
While interacting with segment store for table queries, we retry on store exceptions for all requests. 
This can have undesired effect for conditional updates because they can now fail with write conflict exception. 
Ideally retry for updates should be done for WrongHost but not for other connection failure exceptions. 

**Problem location**
PravegaTableStoreHelper.java

**Suggestions for an improvement**
Fix the issue. do not retry on connection failure exceptions for updates.

### PR DESCRIPTION
**Pull request by shiveshr**
Signed-off-by: Shivesh Ranjan <shivesh.ranjan@gmail.com>

**Change log description**  
For table update calls, retry should be done only for WrongHost and auth failed but not for other store connection failure exceptions.

**Purpose of the change**  
Fixes #4639 

**What the code does**  
 While interacting with segment store for table queries, we retry on store exceptions for all requests.
This can have undesired effect for conditional updates because they can now fail with write conflict exception.

**How to verify it**  
Unit test added.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java [hunk 1]
```diff
@@ -176,7 +178,7 @@ public void invalidateCache(String table, String key) {
                 new TableEntryImpl<>(new TableKeyImpl<>(key.getBytes(Charsets.UTF_8), KeyVersion.NOT_EXISTS), value));
         Supplier<String> errorMessage = () -> String.format("addNewEntry: key: %s table: %s", key, tableName);
         return withRetries(() -> segmentHelper.updateTableEntries(tableName, entries, authToken.get(), RequestTag.NON_EXISTENT_ID),
-                errorMessage)
+                errorMessage, true)
```
Comment (shrids) [inline controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java]: This change causes a slight change in the behavior of the controller wrt to createScope().

```
This change prevents retries in the case of `ConnectionDropped` or `ConnectionFailed`. In the case of `createScope()` 
workflow, this will prevent retries by the controller. And in this scenario the retries of the client would used.
```

**Comment by shrids** [comment]
pravega-branch-builder/2266/  - system test run is in progress.

File: controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java (hunk 1 above)
Comment (shiveshr) [reply controller/src/main/java/io/pravega/controller/store/stream/PravegaTablesStoreHelper.java]: Yes, that is correct. But its not necessarily a behaviour change (except the bug fix). Its just fail faster rather than retry. 
Most updates happen from workflows. 
Some happen in the context of client calls.

**Comment by shrids** [comment]
`/job/test-pravega-continuous/2729/` System test run with this change is successful.
