### PR TITLE
Issue 1414: (SegmentStore) Tier1 Error Handling

### LINKED ISSUE #1414: BookKeeper error handling
After #1330 is done, the following fixes & improvements need to be done to `BookKeeperLog`:
1. Be able to properly recover from a BookKeeper error. For example, if BookKeeper closes a ledger, the `BookKeeperLog` does not reopen it.
2. Handle Operations With Unknown Outcomes. These can happen when connection to BK/ZK is lost during a write; the write eventually times out or fails with an exception, however the write has been committed to the ledger. 

Both of these can take advantage of the retry mechanism in `BookKeeperLog`:
- All writes are queued up and we have a write processor that goes through them and attempts/reattempts to execute them (Existing Behavior).
- When a `LedgerClosedException` is caught (which is the result of a rollover), trigger a new Ledger Rollover. This will close the current ledger (no-op if already closed) and create a new one.
- When a write fails, usually we get back the attempted entry id for that write. If it happens to be before the `lastAddConfirmed` for its attempted ledger, then this write succeeded. Otherwise it needs to be retried.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
BookKeeperLog:
- Observation before all: BookKeeper always closes the Ledger should an error occur.
- Added ability to recover from BookKeeper ledger failures.  In such cases, writes are retried, but not before opening a new ledger and updating the writes to be applied to the new ledger (with order being preserved). 
- Writes with unknown outcomes. In such cases, we go to the BK Server to fetch the LastAddConfirmed to see if the writes actually succeeded or not. This is done by open-fencing the ledger for which the write was applied, which guarantees agreement on the LastAddConfirmed value.
- After getting the value, suspect writes are checked against LastAddConfirmed (if their entry id is less than or equal, then they succeeded, otherwise they need a retry).
- Auto-closes when it detects a permanent write failure (and fails all subsequent queued writes). A permanent write failure is when a non-retryable error was detected or when the maximum number of retries for that write has been exhausted.
- All cancelled writes are now failed using CancellationException instead of the more obscure ObjectClosedException when the OperationProcessor is shutting down.
- Unit Tests
    - Added a bunch of unit tests that force-fail a bookie and observe the behavior of BookKeeperLog.

Segment Store (OperationProcessor et al):
- Auto-shuts down in case of DurableDataLog (Tier1) write failures - this is now done for any kind of failure, not just for DataCorruptionException or DataLogNotPrimaryException. The reason for this is that we do not have a clean way of completely ensuring write order in this case and the best way (at the moment) of reconciling this is to force a full container recovery. A bit of a brutal approach, but it avoids having to write complex code in order to support other, less drastic, approaches.
- All cancelled operations are now failed using CancellationException instead of the more obscure ObjectClosedException when the OperationProcessor is shutting down.
- DataFrameBuilder: no longer auto-flushing upon close. Since this object is owned throughout the lifetime of an OperationProcessor, it is closed whenever the OperationProcessor is closed, so no need for this feature anymore.

**Purpose of the change**
Fixes #1414.

**What the code does**
Better Tier1 error handling.

**How to verify it**
Unit tests added/updated to verify behavior.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 1]
```diff
@@ -308,23 +336,76 @@ private boolean processWrites(List<Write> toExecute) {
...
+    /**
+     * Reliably gets the LastAddConfirmed for the WriteLedger
+     *
+     * @param writeLedger       The WriteLedger to query.
+     * @param lastAddsConfirmed A Map of LedgerIds to LastAddConfirmed for each known ledger id. This is used as a cache
+     *                          and will be updated if necessary.
+     * @return The LastAddConfirmed for the WriteLedger.
+     */
+    @SneakyThrows(DurableDataLogException.class)
+    private long tryGetLastAddConfirmed(WriteLedger writeLedger, Map<Long, Long> lastAddsConfirmed) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Why is it `try`? it always returns a lac, except when it sneaky throws a durable data log exception.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 2]
```diff
@@ -308,23 +336,76 @@ private boolean processWrites(List<Write> toExecute) {
...
+        long ledgerId = writeLedger.ledger.getId();
+        long lac = lastAddsConfirmed.getOrDefault(ledgerId, -1L);
+        if (lac < 0) {
+            if (writeLedger.isRolledOver()) {
+                // This close was not due to failure, rather a rollover - hence lastAddConfirmed can be relied upon.
+                lac = writeLedger.ledger.getLastAddConfirmed();
+            } else {
+                // Ledger got closed. This could be due to some external factor, and lastAddConfirmed can't be relied upon.
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: One situation in which the ledger can get closed is when the container ownership changes, yes? What happens in this case?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 3]
```diff
@@ -396,13 +473,17 @@ private void handleWriteException(int responseCode, Write write) {
         try {
             if (ex instanceof BKException.BKLedgerFencedException) {
                 // We were fenced out.
-                ex = new DataLogWriterNotPrimaryException("Log not primary anymore.", ex);
+                ex = new DataLogWriterNotPrimaryException("BookKeeperLog is not primary anymore.", ex);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: One invariant that we need to preserve is that an old container owner never fences out a new container owner. When I read this change, it made me wonder whether there is any situation in which this invariant can be violated.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java [hunk 4]
```diff
@@ -68,11 +69,35 @@ public void close() throws Exception {
     //region BookKeeper operations
 
     /**
+     * Suspends the BookieService with the given index (does not stop it).
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java]: What does it mean to suspend the bookie service? I understand intuitively, but I´m not sure what it is actually doing.

Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java]: Ok, this is what it is doing:

```
/**
     * Suspend processing of requests in the bookie (for testing)
     */
    @VisibleForTesting
    public void suspendProcessing() {
        LOG.debug("Suspending bookie server, port is {}", conf.getBookiePort());
        nettyServer.suspendProcessing();
    }
```

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java [hunk 5]
```diff
@@ -264,24 +253,24 @@ private void processOperations(Queue<CompletableOperation> operations) {
...
-                if (isFatalException(realCause)) {
+                if (isFatalException(ex)) {
                     // If we encountered a fatal exception, it means we detected something that we cannot possibly recover from.
                     // We need to shutdown right away (this will be done by the main loop).
 
                     // But first, fail any Operations that we did not have a chance to process yet.
-                    cancelIncompleteOperations(operations, realCause);
-                    throw Lombok.sneakyThrow(realCause);
+                    cancelIncompleteOperations(operations, ex);
+                    throw Lombok.sneakyThrow(ex);
```
Comment (fpj) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: I know this is not changing from the previous code, but I want to understand why you are sneaky throwing it here rather than simply throwing.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 2 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: That will trigger a `LedgerFencedException` which will shut down the adapter, and the container. That is a whole different story.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 3 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: As explained above, fencing triggers a separate exception which causes a container shutdown. I don't think this will be an issue.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java (hunk 4 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperServiceRunner.java]: Yes, it simulates the Bookie not being available by turning off its Netty interface.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java (hunk 5 above)
Comment (andreipaduroiu) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/OperationProcessor.java]: If I didn't do this, then the compiler would bug me about not declaring checked exceptions (Throwable is a checked exception from its POV). The two solutions are either doing this or adding a very general `@SneakyThrows` on the whole method. The problem with the latter is that it throws a blanket over the entire method, which could lead to some other real exceptions not being declared.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 1 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I think that's why. Because it may fail and it is not guaranteed. Do you think it's better to just name it `get` without `try`?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 6]
```diff
@@ -308,23 +336,76 @@ private boolean processWrites(List<Write> toExecute) {
...
+            if (w.isDone() || !w.getWriteLedger().ledger.isClosed()) {
+                continue;
+            }
 
-        // Get the writes to execute from the queue.
-        return this.writes.getWritesToExecute(maxTotalSize);
+            // Write likely failed because of LedgerClosedException. Need to check the LastAddConfirmed for each
+            // involved Ledger and see if the write actually made it through or not.
+            long lac = tryGetLastAddConfirmed(w.getWriteLedger(), lastAddsConfirmed);
+            if (w.getEntryId() >= 0 && w.getEntryId() <= lac) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: The entry id is given in the response to an add entry, but if `lac < w.getEntryId()`, then we haven't added this entry yet. Are we simply guessing what the entry id will be and setting it initially to the write? It is not hard to guess given that it increases sequentially, but I wonder if this is what we are doing, guessing the entry id for the write ahead of time.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 7]
```diff
@@ -308,23 +336,76 @@ private boolean processWrites(List<Write> toExecute) {
...
+                // Write was actually successful. Complete it and move on.
+                w.complete();
+                anythingChanged = true;
+            } else if (currentLedger.ledger.getId() != w.getWriteLedger().ledger.getId()) {
+                // Current ledger has changed; attempt to write to the new one.
+                w.setWriteLedger(currentLedger);
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Ok, I think I understand what is going on. We change the ledger to write this entry to, but I'm wondering what is the mechanism that will trigger a new attempt to write.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 6 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I am relying on the callback to always be invoked even if failed. If it doesn't get invoked then other not-so-good things can happen ,such as a result Future being left uncompleted indefinitely. From my experience, the callback is always invoked, regardless of what kind of failure (yes, even BK/ZK timeouts).

If `lac < entryId`, then the write did not make it. After that the write processor will update the Write to point to the next (active) ledger and it will be retried there. The ordering in the log is still guaranteed because we never attempt writing to ledger N+1 until all writes to ledger N are done, and writes are always kept in the WriteQueue (preserving order) and attempted in that order.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 7 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Here (in this line) you are in `handleClosedLedger`. This is invoked by the `processPendingWrites` which is invoked by the `writeProcessor` (you need to open the whole file for context - check out the constructor). The `writeProcessor` is invoked by:
- A new write being queued
- A write completing (success or failure)
- Rollover completing.

To add more context:
- handleClosedLedgers is invoked just before attempting to write - so right after this method exits the writes are being sent out
- WriteProcessor is built in such a way that regardless of how many requests to have it run, there is only one active execution at any given time (they don't overlap). If multiple requests come in while it's executing, it only re-executes once (not how many times it got requested) - that's because a single execution takes care of everything, so more than one is just wasting CPU.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 1 above)
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: `fetch`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 6 above)
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I think my question wasn't clear. I'd like to know how the entry id of the write is set. The entry id from a bk perspective is only set upon a successful add entry, but it sounds like the segment store entry ids can be set before that as per the code above. I'm trying to understand how we are setting it.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 1 above)
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I think `fetch` is better.

Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Done.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 6 above)
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Actually BK seems to work a bit differently. The BK Client assigns an entry id when I call `asyncAddEntry`. That Entryid is then passed back to me via the callback regardless of whether the write succeeded or not (so even if it failed). Plus, if it failed, then the Ledger closes.

If you look at the `addCallback` method, then you'll see it takes an 'entryId' argument - which is given by BK.
