### PR TITLE
Issue 2234: (Segment Store) Cleaning up empty ledgers upon recovery

### LINKED ISSUE #2234: Incomplete recoveries can lead to a lot of empty ledgers
**Problem description**
For a particular Container, a recovery failure after fencing the BookKeeperLog can lead to an excessive number of empty ledgers in that Log, thus leading to substantially increased recovery times.

This is due to the fact that, upon a successful Log fencing, a new (empty) ledger is created and the BookKeeperLog metadata is updated to reflect that in ZK. However, if the recovery fails (see #2233 as an example), the system will attempt a new recovery, thus creating a new ledger, and going on in an endless loop.

**Problem location**
`DurableDataLog`/`BookKeeperLog`.

**Suggestions for an improvement**
Upon a successful BookKeeperLog open-fencing with more than 1 previous ledger (before adding a new one), if the second-to-last is empty, delete it and remove it from the metadata. We cannot delete the last one because it may be actively written to and is used as a base for fencing.

Example:
1. Suppose we have Log A with Ledgers 1,2,3. Ledgers 1 and 2 are closed, and Ledger 2 is empty.
2. Another instance of the Container causes Log A to be open-fenced, and it will have Ledgers 1,2,3,4 (3 is now closed and 4 is just opened). 
3. Since Ledger 2 is empty, it can be safely removed from the chain, and the Log would now have 1,3,4 with 1 and 3 being closed).

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**
* Keeps track of Ledger Status
* Removes empty ledgers from BookKeperLog metadata
* Deletes empty ledger removed in step 2 above.

**Purpose of the change**
Fixes #2234.

**What the code does**
During each initialization, the `BookKeeperLog` creates a new BK Ledger and adds it to the BookKeeperLog metadata (stored in ZK). However, if, after this, the Container Recovery fails or otherwise succeeds but it doesn't write data to it until the next failover, we can end up with a lot of empty ledgers in the Log, which will significantly slow down future recoveries. The first scenario (recovery failure) is more likely to lead to such a situation, since whatever problem caused it to fail in the first place will occur every subsequent time.

To alleviate this, the `BookKeeperLog` will keep track of Ledger Status (Empty|NotEmpty|Unknown). A ledger's status is initially Unknown, and upon initialization (the open-fence phase), it will read the LAC from BK and determine whether it is empty or not. Ledgers that are determined to be empty will be removed from the `BookKeeperLog` metadata and subsequently deleted from BK.

One exception to the deletion is the last 2 Ledgers in the Log. Those will be kept regardless of status, since they actively participate in the fencing process - we need to ensure that the previous writers to them know they have been fenced out and that this wasn't some other kind of error.

**How to verify it**
New unit tests added to verify desired behavior.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java [hunk 1]
```diff
@@ -15,18 +15,25 @@
...
+@NotThreadSafe
 class LogMetadata {
     //region Members
 
-    private static final byte SERIALIZATION_VERSION = 0;
+    /**
+     * Version 0: Base.
+     * Version 1: Added LedgerMetadata.Status.
+     */
+    private static final byte SERIALIZATION_VERSION = 1;
```
Comment (tkaitchuck) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: Does this make the change store incompatible?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 2]
```diff
@@ -202,30 +204,47 @@ public void close() {
...
+            LedgerMetadata ledgerMetadata = newMetadata.getLedger(newLedger.getId());
             assert ledgerMetadata != null : "cannot find newly added ledger metadata";
             this.writeLedger = new WriteLedger(newLedger, ledgerMetadata);
-            this.logMetadata = metadata;
-            log.info("{}: Initialized.", this.traceObjectId);
+            this.logMetadata = newMetadata;
+            ledgersToDelete = getLedgerIdsToDelete(oldMetadata, newMetadata);
         }
+
+        // Delete the orphaned ledgers from BookKeeper.
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: To clarify one thing, in the case that the server crashes right at this point, the orphaned ledgers would remain orphaned forever (unless we manually remove them), is it right? I'm saying this because we update the zk metadata before we remove the ledgers, which makes sense as the other way around gives us a consistency issue.

To be sure that we eventually remove orphaned ledgers, we would need to record the need to remove those ledgers in persistent store until we make sure that they are actually removed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 3]
```diff
@@ -635,18 +655,27 @@ private LogMetadata loadMetadata() throws DataLogInitializationException {
...
+     * @param clearEmptyLedgers If true, the new metadata will not not contain any pointers to empty Ledgers. Setting this
+     *                          to true will not remove a pointer to the last few ledgers in the Log (controlled by
+     *                          Ledgers.MIN_FENCE_LEDGER_COUNT, even if they are indeed empty (this is so we don't interfere
+     *                          with any ongoing fencing activities as another instance of this Log may not have yet been
+     *                          fenced out).
      * @return A new instance of the LogMetadata, which includes the new ledger.
      * @throws DurableDataLogException If an Exception occurred.
      */
-    private LogMetadata updateMetadata(LogMetadata currentMetadata, LedgerHandle newLedger) throws DurableDataLogException {
+    private LogMetadata updateMetadata(LogMetadata currentMetadata, LedgerHandle newLedger, boolean clearEmptyLedgers) throws DurableDataLogException {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: I think that we need this flag because we only want to clean up empty ledgers upon initialization, while metadata updates can occur at other times too. Is my understanding correct?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 4]
```diff
@@ -635,18 +655,27 @@ private LogMetadata loadMetadata() throws DataLogInitializationException {
     /**
      * Updates the metadata and persists it as a result of adding a new Ledger.
      *
-     * @param currentMetadata The current metadata.
-     * @param newLedger       The newly added Ledger.
+     * @param currentMetadata   The current metadata.
+     * @param newLedger         The newly added Ledger.
+     * @param clearEmptyLedgers If true, the new metadata will not not contain any pointers to empty Ledgers. Setting this
+     *                          to true will not remove a pointer to the last few ledgers in the Log (controlled by
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: There is one parenthesis that isn't closing.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java [hunk 5]
```diff
@@ -140,6 +141,63 @@ LogMetadata truncate(LedgerAddress upToAddress) {
                 .withUpdateVersion(this.updateVersion.get());
     }
 
+    /**
+     * Removes LedgerMetadatas for those Ledgers that are known to be empty.
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: `LedgerMetadatas` -> `LedgerMetadata`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java [hunk 6]
```diff
@@ -140,6 +141,63 @@ LogMetadata truncate(LedgerAddress upToAddress) {
...
+     *
+     * @param skipCountFromEnd The number of Ledgers to spare, counting from the end of the LedgerMetadata list.
+     * @return A new instance of LogMetadata with the updated ledger list.
+     */
+    LogMetadata removeEmptyLedgers(int skipCountFromEnd) {
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: Just so that I understand, what's the reason for having this argument rather than directly use `Ledgers.MIN_FENCE_LEDGER_COUNT` to compute the cut-off?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java [hunk 7]
```diff
@@ -140,6 +141,63 @@ LogMetadata truncate(LedgerAddress upToAddress) {
...
+        for (int i = cutoffIndex; i < this.ledgers.size(); i++) {
+            newLedgers.add(this.ledgers.get(i));
+        }
+
+        return new LogMetadata(this.epoch, Collections.unmodifiableList(newLedgers), this.truncationAddress)
+                .withUpdateVersion(this.updateVersion.get());
+    }
+
+    /**
+     * Updates the LastAddConfirmed on individual LedgerMetadatas based on the provided argument.
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: `LedgerMetadatas` -> `LedgerMetadata instances`

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java [hunk 8]
```diff
@@ -140,6 +141,63 @@ LogMetadata truncate(LedgerAddress upToAddress) {
...
+        if (lastAddConfirmed.isEmpty()) {
+            // Nothing to change.
+            return this;
+        }
+
+        val newLedgers = this.ledgers.stream()
+                .map(lm -> {
+                    long lac = lastAddConfirmed.getOrDefault(lm.getLedgerId(), Long.MIN_VALUE);
+                    if (lm.getStatus() == LedgerMetadata.Status.Unknown && lac != Long.MIN_VALUE) {
+                        LedgerMetadata.Status e = lac == Ledgers.NO_ENTRY_ID
```
Comment (fpj) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: If I remember correctly, there is a corner case here. If we have written exactly one entry, then the last add confirmed will be no entry because the bookies need a second entry to confirm the first.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: No

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 2 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: This is a problem we had before and nothing new. Check out #1165 .

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: Yes. We update metadata upon truncation too. I don't want to do this "cleanup" then because it would be useless anyway. I only want to do this upon initialization, because that's when we are most likely to run into empty ledgers due to incomplete recoveries.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 6 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: I didn't want LogMetadata to have a dependency on Ledgers.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 8 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: My unit tests write exactly one entry, so this must work.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 4 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: fixed

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 5 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: fixed

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 7 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: fixed

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 8 above)
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: The bk client updates its local copy of `lastAddConfirmed`, so if we are getting the value from the same handle that is being used to write, then it is fine.

The second case is when we open a closed ledger. When we open a closed ledger, the ledger handle will be initialized with the entry id in the ledger metadata, so this case is also fine.

The third case is a handle for an open ledger. In the case, the `lastAddConfirmed` value of the ledger handle is `INVALID_ENTRY_ID`.

Could you confirm that all ledger handles in `this.ledgers` are such that they are either closed or are the ones being used to add entries to the ledger?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 2 above)
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: ok.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 4 above)
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: ok.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java (hunk 3 above)
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java]: ok.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 6 above)
Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: ok.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java (hunk 8 above)
Comment (andreipaduroiu) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: The unit test (check out `BooKeeperLogTests.java`) does this:
- Loop around 100 times; at every loop
    - Initialize the log (new ledger added)
    - Every 10 such initializations, write exactly one entry
    - Close the log
- Every time it opens the log, it verifies the metadata is as expected (empty ledgers only are removed) as well as the BK ledgers themselves are removed.

So yes, all ledgers in here are all previously closed (normally or fenced out) or the one that is currently open for writes (that is the last one). However, this method is called prior to creating the new ledger, so all the ledgers in here are previously closed and their LAC is fetched upon opening.

Comment (fpj) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java]: Ok.
