### PR TITLE
Issue 2642: Fix IllegalStateException observed while removing reader.

### LINKED ISSUE #2642: RemoveReader throws IllegalStateException.
**Problem description**
Reader throws
`java.lang.IllegalStateException: No offset in lastPosition for assigned segment: _system/_requeststream/0`

**Problem location**
ReaderGroupState

**Suggestions for an improvement**
With the serialization changes to ReaderGroupState deserialization of type Map with value null will return an empty map instead of null.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**
Ensure RemoveReader handles empty `ownedsegments` similar to a null value.

**Purpose of the change**
Fixes #2642 

**What the code does**
Ensure RemoveReader handles ownedSegments handles empty map.

**How to verify it**
All the existing tests and system tests should pass.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java [hunk 1]
```diff
@@ -519,7 +519,7 @@ void update(ReaderGroupState state) {
                     Entry<Segment, Long> entry = iter.next();
                     Segment segment = entry.getKey();
                     Long offset;
-                    if (ownedSegments == null) {
+                    if (ownedSegments == null || ownedSegments.isEmpty()) {
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: Two questions:

1- In which cases do we expect it to be null and which cases we expect it to be empty? I'm wondering, for example, whether `ownedSegments` being `null` is actually an error. If so, we should consider having a precondition. 
2- There are a bunch of `null` checks in this file alone. I'm wondering if any of those should be checking for empty set instead. Did you check?

Comment (shrids) [reply client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java]: >whether ownedSegments being null is actually an error.

ownedSegments is null in the example shown in the integration test when reader is made offline with position object as null.

>  I'm wondering if any of those should be checking for empty set instead. Did you check?

No, I have not yet checked it.
