### PR TITLE
Issue 2601: Checking status of HDFS before public methods are executed

### LINKED ISSUE #2601: HDFSStorage does not respect closed status
**Problem description**
HDFSStorage does not make use of the closed status. Method `ensureInitializedAndNotClosed` is never used.

This *must* be invoked when any public method is invoked. 

For example, I keep getting this failure locally every now and then, and I traced it to a closed adapter:

```
(trimmed)
Caused by: java.lang.NullPointerException
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.findAllRaw(HDFSStorage.java:501)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.findStatusForSegment(HDFSStorage.java:543)
	at io.pravega.segmentstore.storage.impl.hdfs.HDFSStorage.seal(HDFSStorage.java:239)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.sealActiveChunk(RollingStorage.java:518)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.seal(RollingStorage.java:335)
	at io.pravega.segmentstore.storage.rolling.RollingStorage.delete(RollingStorage.java:445)
(trimmed)
```

**Problem location**
HDFSStorage.

**Suggestions for an improvement**
Invoke `ensureInitializedAndNotClosed` when calling any public method.

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**
The public APIs for `HDFSStorage` does not check for status of the service before executing public method.

**Purpose of the change**
This fixes #2601.

**What the code does**
Checks status of HDFS.
 
**How to verify it**

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 1]
```diff
@@ -152,6 +152,7 @@ public void initialize(long epoch) {
 
     @Override
     public SegmentProperties getStreamSegmentInfo(String streamSegmentName) throws StreamSegmentException {
+        ensureInitializedAndNotClosed();
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: How about openWrite, openRead, write, read, seal, truncate, concat, etc.?

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 2]
```diff
@@ -187,7 +189,7 @@ private boolean isSealed(Path path) throws FileNameFormatException {
         return getEpochFromPath(path) == MAX_EPOCH;
     }
 
-    protected FileSystem openFileSystem(Configuration conf) throws IOException {
+    FileSystem openFileSystem(Configuration conf) throws IOException {
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Any reason why we can't make this private?

Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This is overridden by the test(`HDFSStorageTest`).

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java (hunk 1 above)
Comment (arvindkandhare) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: Fixed.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java [hunk 3]
```diff
@@ -186,6 +186,7 @@ public boolean exists(String streamSegmentName) {
     }
 
     private boolean isSealed(Path path) throws FileNameFormatException {
+        ensureInitializedAndNotClosed();
```
Comment (andreipaduroiu) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/hdfs/HDFSStorage.java]: This is a private method; no need to do so here.
