### PR TITLE
Issue [2824] [2816]: Document and refactor delegation token creation in controller.

### LINKED ISSUE #2816: Token verification fails during longevity.
**Problem description**

Token verification failure causes readers to throw RetriesExhaustedException on a longevity setup. The failure was observed after 3days 16hours into the test.

```
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - Received delegationtoken: eyJhbGciOiJIUzUxMiJ9.eyJodWxrL3NtYWxsU2NhbGUiOiJSRUFEX1VQREFURSJ9.K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng for segment: hulk/smallScaleSlow/4679.#epoch.3038 and operation: Read Segment
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] INFO  i.p.s.s.h.d.TokenVerifierImpl - Could not find a matching claim READ for resource hulk/smallScaleSlow/4679.#epoch.3038 in claims header={alg=HS512},body={hulk/smallScale=READ_UPDATE},signature=K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng
2018-08-04 20:29:06,796 317897935 [epollEventLoopGroup-3-1] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Delegation token verification failed for segment: hulk/smallScaleSlow/4679.#epoch.3038, token: eyJhbGciOiJIUzUxMiJ9.eyJodWxrL3NtYWxsU2NhbGUiOiJSRUFEX1VQREFURSJ9.K2M3OZ8ViXZmVDo-mSFyEyJ-FkN7UJN6VUVAbuy2lygEZlyut2WyokimCadV4_um4YEiD4aolj3AGWn91YR4ng, operation: Read Segment
2018-08-04 20:29:06,797 317897936 [epollEventLoopGroup-3-1] WARN  i.p.s.s.h.h.PravegaRequestProcessor - Authentication error during 'Read Segment' on Segment = hulk/smallScaleSlow/4679.#epoch.3038.
io.pravega.common.auth.AuthenticationException: Token verification failed
    at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.verifyToken(PravegaRequestProcessor.java:186)
    at io.pravega.segmentstore.server.host.handler.PravegaRequestProcessor.readSegment(PravegaRequestProcessor.java:167)
    at io.pravega.shared.protocol.netty.DelegatingRequestProcessor.readSegment(DelegatingRequestProcessor.java:45)
    at io.pravega.shared.protocol.netty.WireCommands$ReadSegment.process(WireCommands.java:665)
    at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:46)

```
Logs: 
[a9dd4541-b6c3-4b43-a6eb-3e5453d7473f-1533414547110.zip](https://github.com/pravega/pravega/files/2265724/a9dd4541-b6c3-4b43-a6eb-3e5453d7473f-1533414547110.zip)

**Problem location**
Security.

**Suggestions for an improvement**
Fix the issue.

### LINKED ISSUE #2824: Possible privilege elevation using delegation token
**Problem description**
Reviewing the `PravegaInterceptor` class, there is a troubling block of code ([ref](https://github.com/pravega/pravega/blob/ce32932b7b6ea03e9c784b028e0c4d804fe84c95/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L80)) that produces a powerful delegation token, as fallback logic when no interceptor is in the GRPC thread-local context.    Seems that the caller must call `retrieveDelegationToken` from the GRPC thread or else the user will silently be granted a powerful level of access.  

**Problem location**
`io.pravega.controller.server.rpc.auth.PravegaInterceptor`

**Suggestions for an improvement**

Consider reworking the code to grant no privileges when explicit information isn't available, and consider accepting the `Context` as a parameter (rather than rely on a thread-local) into such utility methods as `retrieveDelegationToken`.   This would force the caller to be aware of which context is being retrieved, and make the overall behavior more explicit when using futures.

### PR DESCRIPTION
**Pull request by arvindkandhare**
Signed-off-by: arvindkandhare <arvind.kandhare@emc.com>

**Change log description**  
Split delegationtoken creation and document it. Ensure that the token remains in effect throughout the context of the `grpc` call.

**Purpose of the change**  
Ensure that there is no misunderstanding and a correct delegation token is created.
Fixes #2824, fixes #2816.

**What the code does**  
Removes `retrieveDelegationToken` from `PravegaInterceptor`. Its functionality is replaced in two ways: 
- `delegationToken` lambda parameter in `grpc` context - in case of delegationtoken created in a `grpc` context it is shared with the code using a lambda parameter. This stays in context till the time the lambda call is executing. 
- `retrieveMasterToken` - This is supposed to be called for controller to segmentstore communications. This returns a token which has access to all the resources. The controller owns all the resources and should be able to work on these for internal operations.

**How to verify it**  
`SecureStreamMetadataTests`, `FailingSecureStreamMetadataTests` amd `FailingSecurePravegaClusterTests` passes.

### CODE REVIEW

**Comment by EronWright** [comment]
One of my main concerns is that the `Context` object, which holds the state, is accessed as a thread-local.   Pravega often uses an async programming style, so it seems dangerous to be relying on thread-local values any more than necessary.   May I suggest that the `Context` object be made more explicit.

**Comment by arvindkandhare** [comment]
1. From the issue #2824:
> the user will silently be granted a powerful level of access.
I think this particular concern is taken care of and is documented properly. Do let me know whether we are in sync on this.

2. About this comment:
>One of my main concerns is that the Context object, which holds the state, is accessed as a thread-local. Pravega often uses an async programming style, so it seems dangerous to be relying on thread-local values any more than necessary. May I suggest that the Context object be made more explicit.

Will add a test case which covers two ongoing `grpc` calls and ensures that delegation tokens are not exchanged. If it causes an issue, will fix it.

**Comment by arvindkandhare** [comment]
[Delegation token handling refactoring](https://trello.com/c/HEVhxEAP/32-delegation-token-handling-refactoring)

**Comment by arvindkandhare** [comment]
[Delegation token handling refactoring](https://trello.com/c/HEVhxEAP/32-delegation-token-handling-refactoring)

File: shared/authplugin/src/main/java/io/pravega/auth/AuthException.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
 
 //Represents exceptions during authorization/authentication
 
-public class AuthException extends Exception {
+public class AuthException extends RuntimeException {
```
Comment (fpj) [inline shared/authplugin/src/main/java/io/pravega/auth/AuthException.java]: Why changing to unchecked?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 2]
```diff
@@ -372,32 +379,33 @@ public boolean checkAuthorization(String resource, AuthHandler.Permissions expec
...
+        return "";
     }
 
-    private String getCurrentDelegationToken() {
+    private String createDelegationToken(String resource, AuthHandler.Permissions expectedLevel, String tokenSigningKey) {
         if (isAuthEnabled) {
-            return PravegaInterceptor.retrieveDelegationToken(tokenSigningKey);
-        } else {
-            return "";
+            Map<String, Object> claims = new HashMap<>();
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: This code is almost identical to the one in `PravegaInterceptor` for `retrieveMasterToke`:

https://github.com/pravega/pravega/pull/2825/files#diff-bbac312563b334a3ae8acef0ac22365dR91

the only difference I could spot is the `claims`. Could you explain why splitting this way makes any difference with respect to escalation? If you have explained it somewhere else, please point me to it.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 3]
```diff
@@ -86,36 +82,22 @@
         return this.handler.authorize(resource, AUTH_CONTEXT_TOKEN.get());
     }
 
-    public static String retrieveDelegationToken(String tokenSigningKey) {
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: This bullet point in the PR description refers to this method:

> retrieveDelegationToken - which is supposed to be called from a grpc context.

but given that you are getting rid of this method and by context, I suspect that you are referring to this other method instead:

https://github.com/pravega/pravega/pull/2825/files#diff-1715d2b863069928c3a29b043e89efd0R396

If this is right, could you fix the description, please?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 4]
```diff
@@ -372,32 +379,33 @@ public boolean checkAuthorization(String resource, AuthHandler.Permissions expec
...
+
+            claims.put(resource, String.valueOf(expectedLevel));
+
+            return Jwts.builder()
+                       .setSubject("segmentstoreresource")
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Why is the subject `segmentstoreresource`?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 5]
```diff
@@ -322,20 +327,22 @@ public void getDelegationToken(io.pravega.controller.stream.api.grpc.v1.Controll
...
 
     // Convert responses from CompletableFuture to gRPC's Observer pattern.
-    private static <T> void authenticateExecuteAndProcessResults(Predicate<Void> authenticator,
-                                                                 Supplier<CompletableFuture<T>> call, final StreamObserver<T> streamObserver) {
-        if (authenticator.test(null)) {
-            CompletableFuture<T> result = call.get();
+    private static <T> void authenticateExecuteAndProcessResults(Supplier<String> authenticator,
+                                                                 Function<String, CompletableFuture<T>> call, final StreamObserver<T> streamObserver) {
+        try {
+            String delegationToken;
```
Comment (fpj) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Is it resolving #2816 because we have a `delegationToken` per invocation of this method?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 6]
```diff
@@ -352,15 +359,15 @@ public void getDelegationToken(io.pravega.controller.stream.api.grpc.v1.Controll
...
+        } catch (Exception e) {
             log.error("Controller api failed with authenticator error");
             streamObserver.onError(Status.UNAUTHENTICATED
                     .withDescription("Authentication failed")
                     .asRuntimeException());
         }
     }
 
-    public boolean checkAuthorization(String resource, AuthHandler.Permissions expectedLevel) {
+    private String checkAuthorization(String resource, AuthHandler.Permissions expectedLevel) throws AuthorizationException {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: There isn't any reason for this to return a string. It should be void

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 7]
```diff
@@ -372,32 +379,33 @@ public boolean checkAuthorization(String resource, AuthHandler.Permissions expec
...
             }
-            return true;
-        } else {
-            return true;
         }
+        return "";
     }
 
-    public boolean checkAuthorizationWithToken(String resource, AuthHandler.Permissions expectedLevel) {
+    private String checkAuthorizationWithToken(String resource, AuthHandler.Permissions expectedLevel) throws AuthorizationException {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: This method name is strange. It is called 'checkAuthorizationWithToken' but it's actually creating a token. Can you clarify the name?

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java [hunk 8]
```diff
@@ -816,7 +815,7 @@ public void close() throws Exception {
 
     public String retrieveDelegationToken() {
         if (authEnabled) {
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Here, and above, and below, the 'if (authEnabled)' block is repeated. I think it would be better to move these methods out behind an interface, and have two implementations. One for auth enabled and one without auth. That way this conditional logic does not need to be repeated.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 5 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Yes. This is correct. I think the updated description covers this. Do let me know if you know any further details.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 4 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: This is the meaning of subject tag for JWT. https://tools.ietf.org/html/rfc7519#section-4.1.2
My intention behind naming it `segmentstoreresource` was that rest of the claims are related to this. Do share if you have any other suggestions for this.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 3 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Fixed the description.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 2 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: There was no escalation in the present code.
But the API decided whether to create a master token or not based on the context. It is possible that any future code may inadvertently call this API without realizing the side effects. This is true about separating the code with a flag too.
The refactoring duplicates code but ensures that there is no such chance.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java (hunk 8 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: The `authEnabled` is used only at one place. Do you think converting to an interface still makes sense?

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 7 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Renamed to `checkAuthorizationAndCreateToken`. Do let me know whether this makes sense.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 6 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: it is returning an empty string as it is one of the parameters to `authenticateExecuteAndProcessResults`. This is used in cases which does not need a token to be created. It returns an empty string instead of a valid token.

File: controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java (hunk 8 above)
Comment (tkaitchuck) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: It appears in several places. See StreamTransactionMetadataTasks:685, ControllerServiceImpl:371, 389, 397 
There is no harm in having multiple small classes. My above comments on ControllerServiceImpl would not have come up if the auth code had it's own class as then it would be more clear what it was doing and there would be a clear place for documentation.

Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java]: Refactored the auth handling code to a helper class.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java [hunk 9]
```diff
@@ -86,36 +82,22 @@
...
-                                  .setAudience("segmentstore")
-                                  .setClaims(claims)
-                                  .signWith(SignatureAlgorithm.HS512, tokenSigningKey.getBytes())
-                                  .compact();
-        }
+    /**
+     * Retrieves a master token for internal controller to segmentstore communication.
+     * @param tokenSigningKey Signing key for the JWT token.
+     * @return A new master token which has highest privileges.
+     * Throws an error if this is called from a grpc context.
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: I don't see where the logic to throw in such a context is.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java [hunk 10]
```diff
@@ -352,52 +353,20 @@ public void getDelegationToken(io.pravega.controller.stream.api.grpc.v1.Controll
...
-            }
-            if (allowedLevel.ordinal() < expectedLevel.ordinal()) {
-                return false;
-            }
-            return true;
-        } else {
-            return true;
-        }
+    private String checkAuthorization(String resource, AuthHandler.Permissions expectedLevel) {
+        return this.authHelper.checkAuthorization(resource, expectedLevel);
```
Comment (tkaitchuck) [inline controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: These two could probably be inlined, as they are private.

Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: Inlined the calls.

File: controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java (hunk 9 above)
Comment (arvindkandhare) [reply controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java]: Updated the comment. It was out of sync with the code.

File: controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java (hunk 4 above)
Comment (EronWright) [reply controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java]: To expand on this, the subject field of a JWT typically contains a username, because the claims of the token are in regards to a user.   For identity tokens, the claims are about the subject's identity (e.g. their email address, user id).   For access tokens, the claims are about the subject's permissions w.r.t a particular resource.   For example:
"Subject 'eron' has 'read permission for X' according to issuer 'Pravega Controller'.  The audience for this information is the 'Pravega Segment Store' ."

A better use for the subject field in this case would be the username of the authenticated user, for logging purposes in the segment store.
