### PR TITLE
Issue 3467: Monitor Pravega pods for restart during a system test run.

### LINKED ISSUE #3467: Fail system test if Pravega container restart is observed.
**Problem description**
System tests currently deploys Pravega on a Kubernetes cluster and runs tests against it. The tests should fail if there is a restart of the Pravega pods during a specific run.

The restart of pod can happen due to muliple reasons like
- K8s sees that the pod is not responding. (liveness probe failure)
- The jvm process crashes due to OOM or any other exception.
- the Pravega pods are consuming more resources limits set.

**Problem location**
K8SequentialExecutor

**Suggestions for an improvement**
Improve the framework.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
Monitor Pravega pod for restart during every system test run. A pod restart during the test run will fail the corresponding test and log the reason for the pravega pod failure.

**Purpose of the change**  
Fixes #3467 

**What the code does**  
The code now fetches the container Status of Pravega pods during every system test run. Incase the restart count of the Pravega pod is greater than what was observed during the start of the test then the  corresponding test is failed with the details.
Example output while simulating a pod restart  (used `docker kill <containerId>`  to simulate a Pravega pod failure)
```
io.pravega.test.system.PravegaTest > simpleTest FAILED
    java.lang.AssertionError: Failing test due to Pravega pod restart.
{pravega-pravega-controller-6fcf5658c8-7c6t6=class V1ContainerStatus {
        containerID: docker://3d9ad5cde103e5fbffc72a3f410aa49a4f081bf914d84b1ebef53608c9a2e3f7
        lastState: class V1ContainerState {
            running: null
            terminated: class V1ContainerStateTerminated {
                containerID: docker://2b2aed2e0ef4b5c54d9d006ae93314e92876d2b93b8ec9dc38e564d8a86a1d48
                exitCode: 137
                finishedAt: 2019-03-15T04:17:59.000-04:00
                message: null
                reason: Error
                signal: null
                startedAt: 2019-03-15T03:49:18.000-04:00
            }
   restartCount: 5       
   ....   
        state: class V1ContainerState {
            running: class V1ContainerStateRunning {
                startedAt: 2019-03-15T04:18:05.000-04:00
            }
            terminated: null
            waiting: null
        }
    }}
``` 
This also logs the container id, which can be used to fetch the logs from `fluentd` to understand more about the cause of failure.

**How to verify it**  
All the existing tests should continue to pass. 
Verified the behavior by performing `docker kill <containerId>` , which causes K8s to restart the pod causing the test to fail with this error.

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 1]
```diff
@@ -204,12 +219,23 @@ public V1Namespace createNamespace(final String namespace) {
...
+    }
+
+    /**
+     * Method to fetch all restarted pods which match a label.
+     * @param namespace Namespace on which the pod(s) reside.
+     * @param labelName Name of the label.
+     * @param labelValue Value of the label.
+     * @return Future representing the list of pod status.
+     */
+    public CompletableFuture<Map<String, V1ContainerStatus>> getRestartedPods(String namespace, String labelName, String labelValue) {
```
Comment (shiveshr) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: is it possible that this will cascade to other tests once first test fails with a restart?

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 2]
```diff
@@ -204,12 +219,23 @@ public V1Namespace createNamespace(final String namespace) {
...
+        return getPodsWithLabel(namespace, labelName, labelValue)
+                     .thenApply(v1PodList -> v1PodList.getItems().stream()
+                                                      .filter(pod -> pod.getStatus().getContainerStatuses().size() != 0 && (pod.getStatus().getContainerStatuses().get(0).getRestartCount() != 0))
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Maybe `!pod.getStatus().getContainerStatuses().isEmpty()` could be clearer here.

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java [hunk 3]
```diff
@@ -75,6 +83,23 @@
 
     }
 
+    private Map<String, V1ContainerStatus> getPravegaPodStatus(K8sClient client) {
+        return Futures.getAndHandleExceptions(
+                client.getRestartedPods("default", "app", "pravega-cluster"),
```
Comment (RaulGracia) [inline test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java]: We need to be sure of what we need to include to check for restarts. I agree that a Controller and Segment Store restart should be interpreted as a failure. This may be also extended to unexpected ZK and BK pod restarts. However, we need to make sure that we do not include any of the other pods available by default in the cluster (e.g., fluentd).

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 4]
```diff
@@ -185,16 +185,31 @@ public V1Namespace createNamespace(final String namespace) {
...
     /**
      * Method to fetch the status of all pods which match a label.
      * @param namespace Namespace on which the pod(s) reside.
      * @param labelName Name of the label.
      * @param labelValue Value of the label.
      * @return Future representing the list of pod status.
      */
-    @SneakyThrows(ApiException.class)
     public CompletableFuture<List<V1PodStatus>> getStatusOfPodWithLabel(final String namespace, final String labelName, final String labelValue) {
+        return getPodsWithLabel(namespace, labelName, labelValue)
```
Comment (adrianmo) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Even if we are using only one label at the moment, this method should support multiple labels to cover future usages.

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java [hunk 5]
```diff
@@ -204,12 +219,23 @@ public V1Namespace createNamespace(final String namespace) {
...
+     * @param labelName Name of the label.
+     * @param labelValue Value of the label.
+     * @return Future representing the list of pod status.
+     */
+    public CompletableFuture<Map<String, V1ContainerStatus>> getRestartedPods(String namespace, String labelName, String labelValue) {
+        return getPodsWithLabel(namespace, labelName, labelValue)
+                     .thenApply(v1PodList -> v1PodList.getItems().stream()
+                                                      .filter(pod -> pod.getStatus().getContainerStatuses().size() != 0 && (pod.getStatus().getContainerStatuses().get(0).getRestartCount() != 0))
+                                                      .collect(Collectors.toMap(pod -> pod.getMetadata().getName(),
+                                                                                // currently this supports only one container per pod.
```
Comment (adrianmo) [inline test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Include this comment to the method Javadoc to let users know about this limitation.

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java (hunk 1 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: No, the code only fails a test if there is a restart of pods (with the provided label) during the course of execution of the test by comparing the restart count of the pods before and after the tests.

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java (hunk 3 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java]: At present with the label `app=pravega-cluster` tracks the restart counts for bookies, Segment store and Controller.

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java (hunk 5 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: fixed.

File: test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java (hunk 4 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/kubernetes/K8sClient.java]: Created a new method.

File: test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java (hunk 3 above)
Comment (shrids) [reply test/system/src/main/java/io/pravega/test/system/framework/services/kubernetes/K8SequentialExecutor.java]: Updated the code to track zk pod status .
