### PR TITLE
Issue 1816: Fix the wrong backoffsecs in segmentstore deployment with system test framework

### LINKED ISSUE #1816: Correct the backoffseconds used to deploy pravega segmentstore service using system test framework
**Problem description**
The current backoff seconds used for segmentstore deployment as a marathon app is `7200s` = 120 mins.
So if `segmentstore service` fails to deploy for the first time,
the task launch will be delayed by a factor of backofffactor^(n-1)* backoffsecs 
so the attempts will be at :
 try1: 1.15^0*7200s
 try2: 1.15^1*7200s
.
.
.
This delays the service deployment a lot. This need to be fixed to use the default values. 
**Problem location**
System tests- PravegaSegmentStoreService.java

**Suggestions for an improvement**
Use the default value

### PR DESCRIPTION
**Pull request by Prabha-Veerubhotla**
**Change log description**
*Correct the wrong value of backoffsecs used in segmentstore deployment.

**Purpose of the change**
Fixes #1816 

**What the code does**
Backoffsecs used for pravega segmentstore deployment is incorrect.

**How to verify it**
Run system tests

### CODE REVIEW

File: test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java [hunk 1]
```diff
@@ -95,7 +94,6 @@ public void stop() {
     private App createPravegaSegmentStoreApp() {
         App app = new App();
         app.setId(this.id);
-        app.setBackoffSeconds(BACK_OFF_SECS);
```
Comment (fpj) [inline test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java]: If we remove this line, then back is zero or does it have a default?

Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java]: The default values are : 
``` "backoffSeconds": 1,
    "backoffFactor": 1.15,
    "maxLaunchDelaySeconds": 3600,
```
controller is using these default values .

Comment (Prabha-Veerubhotla) [reply test/system/src/main/java/io/pravega/test/system/framework/services/PravegaSegmentStoreService.java]: The configuration was initially taken from PravegaGroup.json and  the change came in with this commit https://github.com/pravega/pravega/commit/06c6bc53e501f26712194788955919d4f37af5ff#diff-3ca244c82e953ba6417156aac99d3bc6R80.
Also,  that json deploys pravega in groups, so there will be a difference in the way of deployment.
