### PR TITLE
Issue 6745: Handle Controller connectivity with ZK

### LINKED ISSUE #6745: Handle Controller connectivity with ZK in case of ZK restart or Session Timing Out
**Describe the bug**
Controller sometimes is not able to re-establish connection with ZK in case of either session timing out and a new connection request is initiated or in case of ZK pods restarts. It happens sometimes and not always. This issue is followed by the event when the Curator's `ConnectionStateManager` State changes to `LOST` or `SUSPENDED`.

**To Reproduce**
1. Perform a restart on zk pods several times (~20+) which will make the zk unavailable for 10+ minutes

**Additional information**
Currently controller doesn't create a new instance of curator client but tries to reuse the existing one and that causes further exception sometimes with the below log messages:-
`Input argument for new ZooKeeper client (ip:port, ip:port, ip:port, 10000, false) changed with respect to existing client (cluster-zookeeper-client:port, 10000, false).`

### PR DESCRIPTION
**Pull request by shshashwat**
Signed-off-by: Shashwat Sharma <shashwat_sharma@dell.com>

**Change log description**  
Updated the code to return a new instance of Curator client in case of zk restarts.

**Purpose of the change**  
Fixes #6745 

**What the code does**  
Currently the controller doesn't create a new instance of the curator client if the client is not null and it uses the same client to re-establish the connection which is not correct as the system may assign a new IP to the hostname of the new ZooKeeper instance. We see the below log line and the controller doesn't get re-connected
`Input argument for new ZooKeeper client (ip:port, ip:port, ip:port, 10000, false) changed with respect to existing client (cluster-zookeeper-client:port, 10000, false)`

**How to verify it**  
Jenkins builds are passing
Performed experiments in Kubernetes with 3 zk instances that has been intentionally restarted one after another several times (40+ times) and the Controller is able to re-connect and resume it's operation. Used Admin-cli to perform a few more operation as creating scope/listing scope to verify this further.

### CODE REVIEW

File: controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java [hunk 1]
```diff
@@ -121,38 +121,16 @@ static class ZKClientFactory implements ZookeeperFactory {
...
-                    Preconditions.checkArgument(this.sessionTimeout == sessionTimeout, "sessionTimeout differs");
-                    Preconditions.checkArgument(this.canBeReadOnly == canBeReadOnly, "canBeReadOnly differs");
-                    this.client.register(watcher);
-                } catch (IllegalArgumentException e) {
-                    log.warn("Input argument for new ZooKeeper client ({}, {}, {}) changed with respect to existing client ({}, {}, {}).",
-                        connectString, sessionTimeout, canBeReadOnly, this.connectString, this.sessionTimeout, this.canBeReadOnly);
-                    closeClient(client);
-                }
             }
+            this.client = new ZooKeeper(this.connectString, this.sessionTimeout, watcher, this.canBeReadOnly);
```
Comment (RaulGracia) [inline controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:131]: It looks like the Controller was keeping the same Curator client instance and probably this was for a reason. Do you know why? Do you know what are the potential implications of just re-creating the Curator client? (e.g., consistency, problems during Controller failovers, etc.)

Comment (shshashwat) [reply controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:131]: Checking the history says that this was introduced with the first commit itself. Obviously this is a good idea to re-use instance if available but we observed few instances where it was causing issues as explained as PR description. Moreover this is the same way we are using in Segment Stores as well and haven't found any issue with this approach. Ref:- https://github.com/pravega/pravega/blob/c9ffea2e6d1243e6a02fbc785f50130ae417150f/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/ServiceStarter.java#L308 introduced with PR:- https://github.com/pravega/pravega/pull/3842 to handle similar issue on SSS.
I also do not see any potential implication of re-creating the Curator Client

**Comment by shshashwat** [comment]
> @shshashwat while this seems to fix the issue it is not clear why. Could you please provide some explanation as to why not re-using the client fixes the problem?

The system may assign a new IP to the hostname of the new ZooKeeper instance in case of a zk restart. We see the below log lines appearing continuously when we face this issue of zk connectivity with controller and the controller doesn't get re-connected
`Input argument for new ZooKeeper client (ip:port, ip:port, ip:port, 10000, false) changed with respect to existing client (cluster-zookeeper-client:port, 10000, false)`

File: controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java (hunk 1 above)
Comment (ShwethaSNayak) [inline controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:131]: Java doc can be added to provide little brief on reason behind creating new zkClientFactory on session expiry instead of re-using existing one.

Comment (shshashwat) [reply controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:133]: okay, added the comment

**Review by ShwethaSNayak — APPROVED** [review]
LGTM

**Comment by abhinb** [comment]
LGTM

File: controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java (hunk 1 above)
Comment (RaulGracia) [reply controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:133]: Question: aren't we closing this Zookeeper client? If there is a disconnection (i.e., connection lost exception in Curator) from Zookeeper, we just re-create the Zookeeper client without closing the previous one?

Comment (shshashwat) [reply controller/src/main/java/io/pravega/controller/store/client/StoreClientFactory.java:133]: right now we are overriding the previous one with new one. In fact we can actually close the previous one and then create a new one.

**Review by RaulGracia — APPROVED** [review]

**Review by abhinb — APPROVED** [review]

**Comment by shshashwat** [comment]
@RaulGracia, System tests passed #TPC1-2169
