### PR TITLE
Issue 5498: Fix flaky unit test PravegaTablesStreamMetadataStoreTest.testReaderGroups

### LINKED ISSUE #5498: Unit test failure: PravegaTablesStreamMetadataStoreTest.testReaderGroups
**Problem description**
Stack trace:
```
io.pravega.controller.store.stream.PravegaTablesStreamMetadataStoreTest > testReaderGroups FAILED
    java.util.concurrent.CompletionException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: readerGroup table: _system/_tables/scope/readerGroupsInScope.#.0a9a9fea-2d54-4e8c-8b52-8984c5a83107
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: readerGroup table: _system/_tables/scope/readerGroupsInScope.#.0a9a9fea-2d54-4e8c-8b52-8984c5a83107
            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:90)
            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:70)
            at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$23(PravegaTablesStoreHelper.java:294)
            at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
            ... 7 more
```

**Problem location**
`PravegaTablesStreamMetadataStoreTest.testReaderGroups`

**Suggestions for an improvement**
Test should pass reliably.

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
The api call `store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId())` in the test was not followed by join() and hence this future did not complete prior to the following createReaderGroup() call in some cases. 
Hence the failure.

**Purpose of the change**  
Fixes #5498 

**What the code does**  
added join() after `store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId())`
Also added some more assertions to confirm the created completed successfully.

**How to verify it**  
All Unit and Integration tests should pass.
Test `PravegaTablesStreamMetadataStoreTest.testReaderGroups()` should always pass.

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java [hunk 1]
```diff
@@ -1971,14 +1971,18 @@ public void testReaderGroups() throws Exception {
                 .startingStreamCuts(startSC)
                 .endingStreamCuts(endSC).build();
         final RGOperationContext rgContext = store.createRGContext(scopeRGTest, rgName);
-        store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId());
+        store.addReaderGroupToScope(scopeRGTest, rgName, rgConfig.getReaderGroupId()).join();
```
Comment (pbelgundi) [inline controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java:1974]: This is the real fix.

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java [hunk 2]
```diff
@@ -1971,14 +1971,18 @@ public void testReaderGroups() throws Exception {
...
         store.createReaderGroup(scopeRGTest, rgName, rgConfig, System.currentTimeMillis(), rgContext, executor).join();
+        UUID readerId = store.getReaderGroupId(scopeRGTest,rgName).get();
```
Comment (shiveshr) [inline controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java:1976]: nit: please call this readerGroupId as readerId is a separate concept and can be misleading for anyone reading the code.

**Review by shiveshr — APPROVED** [review]

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java (hunk 2 above)
Comment (pbelgundi) [reply controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: done
