### PR TITLE
Issue 4495: Recording WARN and ERROR log entries as metrics.

### LINKED ISSUE #4495: Pravega Metrics for logged ERRORs and WARNs
**Problem description**
It would be nice if we could create 2 new metrics that tracked the number of errors and warning we log. This will enable us to quickly determine if we see an increase in errors (per component or overall) by looking at a metric dashboard.

**Problem location**
All components.

**Suggestions for an improvement**
This can be done in a non-invasive way using the Log4j configuration:
1. Custom appender.
    - We create a custom appender  that implements `Appender<ILoggingEvent>`
    - We override the `Appender.doAppend(ILoggingEvent)` method and intercept only those events that have `getLevel()` equal to `Level.ERROR` or `Level.WARN`.
    - We create Counters (`logged_errors` and `logged_warnings`) and increment their value accordingly. For extra accuracy, we can pass `ILoggingEvent.getLoggerName()` as a custom tag so we can filter out by component.
2. Wire up custom appender using `logback.xml`:
    - Define custom appender `<appender name="Metrics" class="path-to-custom-appender-class">`
    - Link it up. Modify `<root level="...">` by adding `<appender-ref ref="Metrics"/>`

** Example implementation**

MetricsAppender.java
```
public class MetricsAppender implements ch.qos.logback.core.Appender<ILoggingEvent> {
    private static final DynamicLogger DYNAMIC_LOGGER = MetricsProvider.getDynamicLogger();

    @Override
    public String getName() {
        return "Metrics Appender";
    }

    @Override
    public void doAppend(ILoggingEvent o) throws LogbackException {
        if (o.getLevel() == Level.ERROR) {
            DYNAMIC_LOGGER.incCounterValue("logged_errors", 1, o.getLoggerName());
        } else if (o.getLevel() == Level.WARN) {
            DYNAMIC_LOGGER.incCounterValue("logged_warnings", 1, o.getLoggerName());
        }
    }

   // Removed unimplemented methods for brevity.
}
```

logback.xml
```
<configuration scan="true">
   <!-- All other appenders defined here -->

    <appender name="Metrics" class="io.pravega.segmentstore.server.host.MetricsAppender"/>
    <root level="${log.level:-DEBUG}">
        <appender-ref ref="consoleAppender"/> <!-- Preexisting appender -->
        <appender-ref ref="Metrics"/>
    </root>
</configuration>
```

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Recording all WARNs and ERRORs as metrics with logging class name and exception name as tags.

**Purpose of the change**  
Fixes #4495.

**What the code does**  
- Created a new Log Appender to intercept all log entries that have severity set to WARN or ERROR. 
- All these are reported into metrics via 2 distinct counters (one for WARN, one for ERROR), and using the source class/log name as a tag, and exception name (if any) as another tag.

**How to verify it**  
Unit tests updated. A longevity with metrics should also be run to verify this.

### CODE REVIEW

**Comment by RaulGracia** [comment]
@andreipaduroiu this proposal is really great. If we could get as a tag not only the class logger sending the log (to know the component originating the error/warn), but also the exception being thrown it would be great because:
1) We could see in the dashboard at the same time "which" component is experiencing problems and "what" is the problem being thrown.
2) We could create alerts based on logged exceptions (e.g., if we find `DataCorruptionException` send alert).

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java [hunk 1]
```diff
@@ -64,6 +64,10 @@
     // PREFIX can be loaded from config when config becomes dependency.
     public static final String PREFIX = "pravega" + ".";
 
+    // Metrics for all services
+    public static final String LOG_ERRORS = PREFIX + "logged_errors";     // Counter
```
Comment (kevinhan88) [inline shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: Why not just name as ERROR_COUNTER, WARN_COUNTER? LOG_ERRORS sounds logs more than counter.

**Comment by kevinhan88** [comment]
Yes this approach to generate summary of Error/Warnings, together with another initiative to export all logs as metrics, could potentially change the way we view and use logs. I'm also eager to see how it helps.

**Comment by kevinhan88** [comment]
Strong recommend we implement this as Rate (Meter) instead of Counter, thinking the eventual use case:
Counter only gives us the total of errors/warns ever since.
Rate tells us not only the total, but also the distribution of them, which is even more useful for us to spot the patterns.

File: shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java (hunk 1 above)
Comment (andreipaduroiu) [reply shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java]: That would be inconsistent with the naming of the other metrics defined in this class.

Plus, I want the name "Log" in it so that I can make it clear that the source of the information is the logs, and not something else.

**Comment by kevinhan88** [comment]
I suggested the rewording of the original issue as below:
It would be nice if we could create 2 new metrics that track events of errors and warning ...

**Comment by RaulGracia** [comment]
I have tested this PR and it works fine, this will be very useful to understand rapidly the problems of the system:
log-metrics

**Comment by RaulGracia** [comment]
@andreipaduroiu one question: should we also add `CRITICAL` messages to this PR? I don't know how widely used are they in our code base, but perhaps we should move some `ERROR` messages to `CRITICAL` (in another PR, of course).

**Comment by andreipaduroiu** [comment]
@RaulGracia 
We don't use CRITICAL in our code base. Just TRACE, DEBUG, INFO, WARN and ERROR. So I think we should be good for now.
