### PR TITLE
Issue 6616: Pinned Segments my not be pinned after a container restart

### LINKED ISSUE #6616: Pinned Segments my not be pinned after a container restart
**Describe the bug**
The problem seems to be as follows:

1) The `ContainerEventProcessor` is working fine for a long while:

```
2022-02-22 13:20:15,891 14441 [core-17] INFO i.p.c.c.AbstractThreadPoolService - EventProcessor[36-2]: Started.
2022-02-22 13:20:15,891 14441 [core-17] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2] Starting processing.
2022-02-22 13:21:25,322 83872 [core-27] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 1843648.
2022-02-22 13:23:20,353 198903 [core-28] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 1975747.
2022-02-22 13:25:18,853 317403 [core-6] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 2108347.
2022-02-22 13:27:06,222 424772 [core-24] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 2240797.
2022-02-22 13:28:59,823 538373 [core-11] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 2373397.
2022-02-22 13:30:54,800 653350 [core-13] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Truncating ContainerEventProcessor segment 2 at offset 2505997.
```
2) After some time of inactivity (at least from the logs), we see that the internal segment used by `ContainerEventProcessor` gets evicted from metadata. Note that this should never happen, given that the internal segment for `ContainerEventProcessor` is marked as "pinned", which means non-evictable:

```
2022-02-22 14:42:19,673 4938223 [core-4] INFO i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[36]: EvictedStreamSegments Count = 1, Active = 3
2022-02-22 14:42:19,673 4938223 [core-5] INFO i.p.s.s.writer.SegmentAggregator - StorageWriter[36-2]: State changed from Writing to Closed.
2022-02-22 14:42:19,673 4938223 [core-4] INFO i.p.s.server.CacheManager - CacheManager Unregistered ReadIndex[36-2] (_system/containers/event_processor_GC.queue.36_36).
2022-02-22 14:42:19,673 4938223 [core-4] INFO i.p.s.s.reading.ContainerReadIndex - ReadIndex[36]: Cleaned up ReadIndices for [2] inactive or deleted Segments.
2022-02-22 14:42:19,673 4938223 [core-4] INFO i.p.s.s.a.ContainerAttributeIndexImpl - ContainerAttributeIndex[36]: Cleaned up Attribute Indices for 1 Segment(s).
2022-02-22 14:42:19,673 4938223 [core-23] INFO i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[36-2]: Closed.
```

3) Immediately after, we see that a new Segment Id (7502194) is assigned to the internal `ContainerEventProcessor` (`_system/containers/event_processor_GC.queue.36_36`). This is bad, because it means that `ContainerEventProcessor` is all of a sudden working with a new Segment (with offsets that have nothing to do with the original one):

```
2022-02-22 14:42:19,756 4938306 [core-26] INFO i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[36]: MapStreamSegment SegmentId = 7502194, Name = '_system/containers/event_processor_GC.queue.36_36', Active = 4
2022-02-22 14:42:19,756 4938306 [core-8] INFO i.p.s.server.CacheManager - CacheManager Registered ReadIndex[36-7502194] (_system/containers/event_processor_GC.queue.36_36).
```

4) This leads to different types of errors, including serialization errors and `StreamSegmentTruncationExceptions`:

```
2022-02-22 18:41:23,826 19282376 [core-3] ERROR i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Error deserializing events (SegmentId = 7502194, Initial offset = 2505997, Processed offset = 2549575, Read length = 192, Truncation length = 0).
2022-02-22 18:41:23,827 19282377 [core-3] INFO i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Need to reconcile offsets for Segment _system/containers/event_processor_GC.queue.36_36.
2022-02-22 18:41:23,827 19282377 [core-3] WARN i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[36-2]: Processing iteration failed, retrying.
```

Looking at the code of how Segments are pinned, we see that the "pinned" flag is neither serialized and stored in Container metadata Table Segment:
https://github.com/pravega/pravega/blob/77cdbf0d3c1b52c10788d9561b95ee71bd55c6d3/segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java#L159
And it is not being part of attributes neither:
https://github.com/pravega/pravega/blob/77cdbf0d3c1b52c10788d9561b95ee71bd55c6d3/segmentstore/contracts/src/main/java/io/pravega/segmentstore/contracts/Attributes.java#L31

So, apparently this "pinned" flag is only "carried" when a Segment has operations that update its metadata (`UpdateableSegmentMetadata`). If so, the pinned flag is being copied over the current Segment metadata in memory.

However, if you have a pinned Segment that is inactive for some time and the Bookkeeper log gets truncated beyond the offset of the last metadata update Operation for this Segment, the pinned flag may be lost. What is worse, is that it seems that the only way to mark is as pinned si when registering the Segment:
https://github.com/pravega/pravega/blob/77cdbf0d3c1b52c10788d9561b95ee71bd55c6d3/segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/MetadataStore.java#L485

The code above in `submitAssignment()` runs `getMapSegmentId()` and then applies the "pinned" flag to the operation if the Segment does not exist in metadata. However, if the Segment has been already created, it just returns the metadata ir contains, which may not have been marked as pinned. Also, we cannot submit a new `MapStreamSegmentId` operation in this case, as the Segment has been already created. So, effectively, we can mark as "pinned" the Segment only once and then it is just a matter of luck (i.e., how frequent metadata updates the Segment has and the frequency of metadata cleanups) that it stops being pinned, which may have problematic consequences.

**To Reproduce**
1. I have deployed Pravega locally (Bookkeeper standalone, HDFS and Pravega Controller/Segment Store). I have also added more logs to the `MetadataStore:submitAssignment()` function. 
2. I have started the cluster and looked for the new added logs. In particular, we see that the SLTS GC internal segments are created and pinned:
```
2022-03-03 09:57:33,750 53661 [storage-io-54] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[2]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? true (we want it to be? true)
2022-03-03 09:57:33,748 53659 [storage-io-190] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[2]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.2_2: 2
2022-03-03 09:57:33,750 53661 [storage-io-190] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[2]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? true (we want it to be? true)
2022-03-03 09:57:34,026 53937 [storage-io-83] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.0_0: 2
2022-03-03 09:57:35,478 55389 [storage-io-168] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[3]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.3_3: 2
2022-03-03 09:57:35,479 55390 [storage-io-168] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[3]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? true (we want it to be? true)
```
3. Then, I have restarted the Segment Store. In this case, we see some SLTS GC Segments that are pinned, but for Container 3 the "pinned" flag is lost (`Is Pinned? false`):
```
2022-03-03 09:58:33,483 9256 [core-4] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.0_0: 2
2022-03-03 09:58:33,484 9257 [core-4] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? true (we want it to be? true)
2022-03-03 09:58:33,484 9257 [core-4] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-2]: Refreshing Segment Id = 2, Start = 0, Length = 5277, StorageLength = 4893, Sealed(M/S) = false/false, Deleted = false, Name = _system/containers/event_processor_GC.queue.0_0 (pinned = true).
2022-03-03 09:58:35,048 10821 [core-4] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.0_0: 2
2022-03-03 09:58:35,049 10822 [core-4] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? true (we want it to be? true)
2022-03-03 09:58:35,049 10822 [core-4] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-2]: Refreshing Segment Id = 2, Start = 0, Length = 5277, StorageLength = 4893, Sealed(M/S) = false/false, Deleted = false, Name = _system/containers/event_processor_GC.queue.0_0 (pinned = true).
2022-03-03 09:58:35,479 11252 [core-12] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[3]: Found segmentId in submitAssignment _system/containers/event_processor_GC.queue.3_3: 2
2022-03-03 09:58:35,479 11252 [core-12] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[3]: Is valid segmentId in submitAssignment 2, just returning it. Is Pinned? false (we want it to be? true)
2022-03-03 09:58:35,479 11252 [core-12] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[3-2]: Refreshing Segment Id = 2, Start = 0, Length = 5773, StorageLength = 5389, Sealed(M/S) = false/false, Deleted = false, Name = _system/containers/event_processor_GC.queue.3_3 (pinned = false).
```
This demonstrates the existing bug for pinned segments that seems to have been there for long time, actually.

**Screenshots**
n/a

**Additional information**
Need to evaluate whether we have to add the "pinned" flag in the `MetadataCheckpoint` or if we could induce some other operation in  `MetadataStore:submitAssignment()` that could update the pinned flag.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Fixed a bug in how Segments are pinned via `MetadataStore::registerPinnedSegment` that was directly accessing the in-memory metadata without going through the underlying implementation of metadata store (e.g., Table Segments). Also, refactored the way the internal Segment for `ContainerEventProcessor` is created and pinned to memory.

**Purpose of the change**  
Fixes #6616.

**What the code does**  
This PR fixes 2 points: i) a problem in `MetadataStore::registerPinnedSegment`, which should not be called from outside as it was being done, and ii) refactors the way the internal Segment for `ContainerEventProcessor` is created and pinned to memory. The changes are as follows:
- The old `MetadataStore::registerPinnedSegment` was internally calling `MetadataStore::submitAssignment`, which was supposed to be only accessed via subclasses that extend `MetadataStore`, like `TableMetadataStore`. We should never do that, as this method performs a change in the in-memory metadata only, so no actual persistence of the Segment is done by invoking it. This, in addition to the fact of losing the `pinned` flag and therefore having the internal Segment for `ContainerEventProcessor` as a candidate for eviction, was the root cause for the problem we have observed.
  - Now, the new method `MetadataStore::pinSegmentToMemory` replaces `MetadataStore::registerPinnedSegment` and only pins a Segment to memory if it exists.
  - To this end, we have added a new callback in `StreamSegmentContainer::pinSegment()` to perform the actual pin to memory operation. Note that, conversely to other operations, this method directly sets the `pinned` flag to the in-memory metadata of a Segment, if it does exist. This is because the `pinned` flag is a "volatile" piece of information; i.e., it is not stored neither in metadata checkpoints nor in Table Segment metadata. For this reason, we could skip the normal workflow to update the metadata of a Segment via a `ContainerMetadata UpdateTransaction`, which would require a new Operation that could break backwards compatibility. (The alternative would be to forget about being able to pin Segments to memory altogether, at least in `ContainerEventProcessor`)

- `ContainerEventProcessor` has new method `tryCreateInternalSegment()` that does the actual call to `createStreamSegment`. This ensures that the Segment is properly persisted in metadata.
  - Once the Segment is created, we pin it to memory via `MetadataStore::pinSegmentToMemory` method.

**How to verify it**  
All tests should pass, included the modified ones for the functionality changes.
System tests are passing.

_System tests log analysis_:
Without this PR, we observed in the system test logs that `ContainerEventProcessor` could be associated with new Segments having much higher ids than the expected ones. This was visible on any system test run, as it induced multiple container restarts. With this change, we always see `ContainerEventProcessor` being associated with the right Segment id:
```
2022-03-07 18:46:01,726 77027 [core-10] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-3]: Closing 
2022-03-07 16:48:41,423 82259 [core-2] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-2]: Closing EventProcessor.
2022-03-07 16:48:41,423 82259 [core-2] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-3]: Closing EventProcessor.
2022-03-07 18:54:33,117 82619 [core-23] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-2]: Closing 
2022-03-07 18:54:33,118 82620 [core-23] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[0-3]: Closing EventProcessor.
...
2022-03-07 16:50:11,619 192944 [core-16] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[1-2]: Closing 
2022-03-07 16:50:11,619 192944 [core-16] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[1-3]: Closing 
2022-03-07 18:23:13,700 192818 [core-3] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[1-2]: Closing 
2022-03-07 18:23:13,700 192818 [core-3] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[1-3]: Closing EventProcessor.
...
2022-03-07 18:41:03,673 7130061 [core-4] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[2-2]: Closing 
2022-03-07 18:41:03,673 7130061 [core-4] INFO  i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[2-3]: Closing EventProcessor.
```

_Local issue reproduction_: I have tried the same experiment as in #6616. Now, we see that in a local Pravega deployment all the Segments are being pinned, even after multiple restarts (temporarily added new log for checking this):
```
2022-03-09 11:27:42,544 139463 [core-26] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[0]: Segment 3 (_system/containers/event_processor_GC.queue.0_0) is pinned? true needs to be? false.
2022-03-09 11:27:42,621 139540 [core-14] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[1]: Segment 3 (_system/containers/event_processor_GC.queue.1_1) is pinned? true needs to be? false.
2022-03-09 11:27:43,395 140314 [core-13] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[3]: Segment 3 (_system/containers/event_processor_GC.queue.3_3) is pinned? true needs to be? false.
2022-03-09 11:27:43,482 140401 [core-11] INFO  i.p.s.s.containers.MetadataStore - MetadataStore[2]: Segment 3 (_system/containers/event_processor_GC.queue.2_2) is pinned? true needs to be? false.
```

### CODE REVIEW

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 1]
```diff
@@ -123,12 +130,34 @@
      * {@link ContainerEventProcessor.EventProcessor} based on its name.
      */
     @VisibleForTesting
-    static Function<String, CompletableFuture<DirectSegmentAccess>> getOrCreateInternalSegment(SegmentContainer container,
-                                                                                               MetadataStore metadataStore,
-                                                                                               Duration timeout) {
-        return s -> metadataStore.registerPinnedSegment(getEventProcessorSegmentName(container.getId(), s),
-                SYSTEM_CRITICAL_SEGMENT, null, timeout) // Segment should be pinned.
-                .thenCompose(l -> container.forSegment(getEventProcessorSegmentName(container.getId(), s), timeout));
+    Function<String, CompletableFuture<DirectSegmentAccess>> getOrCreateInternalSegment(SegmentContainer container,
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:133]: Is this method getting called for every access ?
Because in that case we would be calling metadataStore.pinSegmentToMemory on each access.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 2]
```diff
@@ -123,12 +130,34 @@
...
+        return s -> tryCreateInternalSegment(container, s, timeout)
+                .thenCompose(v -> container.forSegment(getEventProcessorSegmentName(container.getId(), s), timeout))
+                .thenApply(directAccessSegment -> {
+                    metadataStore.pinSegmentToMemory(getEventProcessorSegmentName(container.getId(), s), timeout); // Segment should be pinned.
+                    return directAccessSegment;
+                });
+    }
+
+    private CompletableFuture<Void> tryCreateInternalSegment(SegmentContainer container, String eventProcessorName, Duration timeout) {
+        synchronized (eventProcessorMap) {
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:145]: Does this need to be synchronized?  It will end up serializing on each and every call to `ContainerEvenProcessor`.
`eventProcessorMap `is already `ConcurrentHashMap `, so may be `computeIfAbsent `is better?

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java [hunk 3]
```diff
@@ -989,6 +989,18 @@ private void shutdownWhenStopped(Service component, String componentName) {
...
+    private CompletableFuture<Boolean> pinSegment(long segmentId, String segmentName, boolean pin, Duration timeout) {
+        Preconditions.checkNotNull(segmentName, "SegmentName cannot be null.");
+        Preconditions.checkArgument(segmentId != ContainerMetadata.NO_STREAM_SEGMENT_ID, "Segment must have a valid id.");
+
+        UpdateableSegmentMetadata segmentMetadata = this.metadata.getStreamSegmentMetadata(segmentId);
+        if (segmentMetadata != null && pin) {
+            segmentMetadata.markPinned();
+            return CompletableFuture.completedFuture(true);
+        }
+        return CompletableFuture.completedFuture(false);
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:1001]: looks like we can get rid of parameter `boolean pin`.
It's never called with false value.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 1 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:133]: Right, I just pinned it once after we create/instantiate it.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 2 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java]: Maybe not, as we are just checking the content of that entry and not modifying anything. I have removed the synchronized block and changed the condition to do just one get.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java (hunk 3 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/StreamSegmentContainer.java:1001]: Could be, but this is perhaps more explicit (just kept the structure used for this flag in other places).

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 4]
```diff
@@ -123,12 +130,32 @@
...
+                    .exceptionally(e -> {
+                        val ex = Exceptions.unwrap(e);
+                        if (e.getCause() instanceof StreamSegmentExistsException) {
+                            log.info("{}: ContainerEventProcessor Segment {} already exists.", this.traceObjectId, segmentName);
+                            return null;
+                        }
+                        log.error("{}: Unexpected problem creating internal Segment {}.", this.traceObjectId, segmentName, ex);
+                        throw new CompletionException(ex);
+                    })
+                    .thenAccept(v -> metadataStore.pinSegmentToMemory(getEventProcessorSegmentName(container.getId(), eventProcessorName), timeout)); // Pin the Segment in memory.
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: Need to move 
`.thenAccept(v -> metadataStore.pinSegmentToMemory(getEventProcessorSegmentName(container.getId(), eventProcessorName), timeout));`

before `.exceptionally`

Otherwise the metadataStore.pinSegmentToMemory is called even after StreamSegmentExistsException

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 5]
```diff
@@ -123,12 +130,32 @@
...
+                                                                                        MetadataStore metadataStore,
+                                                                                        Duration timeout) {
+        return s -> tryCreateAndPinInternalSegment(container, metadataStore, s, timeout)
+                .thenCompose(v -> container.forSegment(getEventProcessorSegmentName(container.getId(), s), timeout));
+    }
+
+    private CompletableFuture<Void> tryCreateAndPinInternalSegment(SegmentContainer container, MetadataStore metadataStore,
+                                                                   String eventProcessorName, Duration timeout) {
+        CompletableFuture<EventProcessor> eventProcessorFuture = this.eventProcessorMap.get(eventProcessorName);
+        if (eventProcessorFuture == null || !eventProcessorFuture.isDone()) {
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:143]: Now the thread safety is gone after you remove synchronized. check and put are two separate operations and not atomic anymore

Look into [ConcurrentHashMap::computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-) on how to do atomic check and add.

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 4 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: goal here is to avoid calling metadataStore.pinSegmentToMemory on every call

Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: Also note that - in general, we need to be careful with putting code that returns CompletableFuture inside synchronize blocks.
Because it is only the creation of CompletableFuture that runs in synchronize not the actual execution of lambda that eventually completes the future. In other words it is possible that code that we really want to run in synchronized block ends up running unprotected outside the block.

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: >Otherwise the metadataStore.pinSegmentToMemory is called even after StreamSegmentExistsException

This is exactly what we want, because the fact that the Segment exists does not mean that it is pinned to memory. Irrespective of whether the Segment is new or not, we want to pin it.

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: > goal here is to avoid calling metadataStore.pinSegmentToMemory on every call.

`pinSegmentToMemory` is not called every time. If you look at the code, there is an `if` clause that prevents any further call to this method (and to the `createStreamSegment` method) once the event processor has been initialized.

Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:156]: > In other words it is possible that code that we really want to run in synchronized block ends up running unprotected outside the block.

The only thing I would like to synchronize is the access to the map, that's it. If the map does not contain the expected future or it is not complete, we will trigger the segment creating and pin it to memory. If it exist and it is complete, we are doing nothing. In the worst case, what could happen is to issue a Segment creation and pin just after the Event Processor is removed from the map (e.g., during shutdown?), which I believe is harmless: either the operation will succeed (i.e., finding that the Segment already exists and not pinning it to memory, because it is already pinned) or not (failing the operation because the container is shut down already), but that's it. I don't see any other downside of this approach at the moment.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 5 above)
Comment (RaulGracia) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:143]: `computeIfAbsent` does not work here, because we also want to check if the future is present but not complete. Perhaps the [ConcurrentHashMap::compute](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#compute-K-java.util.function.BiFunction-) could work, but I'm not convinced that we need atomicity here by embedding all this logic inside the compute. This is going to be used in 3 scenarios:
- _Initialization_: Inside `createEventProcessor()`, which is a private function with called from a synchronized block in `forConsumer()` or `forDurableQueue()`. The initialization logic guarantees that there will be only one concurrent initialization, irrespective of how many threads call from outside. The initialization logic uses the output future of `getOrCreateInternalSegment`, so this is fine.
- _Regular operation_: During its operation, `tryCreateAndPinInternalSegment()` will always get a complete future related to the Event Processor at hand. This access to the map is synchronized (with the same lock as other accesses, the map itself) and it will just skip the whole logic of creating/pinning the internal Segment.
- _Shutdown_: In the worst case, shutdown can happen just after we check the event processor map. This will either be inducing an attempt to create and pin the same segment, which is not going to happen because the Segment is already created and pinned. Or the operation will fail because the Segment Container is already being shutdown.

At the moment, I don't really see an actual problem that could happen from this.

**Comment by RaulGracia** [comment]
To provide a bit more of information on the usage of `getOrCreateInternalSegment`, in the last system test build I see:
1. The message `Created internal Segment` logged after creating the Segments only appears 8 times (2 GC segments x 4 containers). This is the expected one.
2. The message `ContainerEventProcessor Segment {} already exists` appears 152 times. This messages is expected to appear after every container recovery, and given that  we have 4 containers and perform multiple failovers, it is also expected. In other words, this is not logged (and therefore executed) on each processing iteration.
3. The message `Unexpected problem creating internal Segment` only appears 2 times. As I mentioned before, this can happen during Segment Container shutdown:
```
2022-03-10T10:47:20.429043677Z stdout F 2022-03-10 10:47:20,427 2581936 [core-26] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: Stopping.
2022-03-10T10:47:20.429048643Z stdout F 2022-03-10 10:47:20,427 2581936 [core-26] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[2]: Failed due to component failure.
2022-03-10T10:47:20.429054577Z stdout F 2022-03-10 10:47:20,427 2581936 [Thread-232-EventThread] DEBUG o.a.b.client.MetadataUpdateLoop - UpdateLoop(ledgerId=788,loopId=4fe5dab7) success
2022-03-10T10:47:20.429697708Z stdout F 2022-03-10 10:47:20,427 2581936 [core-26] ERROR i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[2]: Unexpected problem creating internal Segment _system/containers/event_processor_GC.failed.queue.2_2.
2022-03-10T10:47:20.429705635Z stdout F io.pravega.common.ObjectClosedException: Object 'MultiKeySequentialProcessor' has been closed and cannot be accessed anymore.
...
2022-03-10T10:47:30.298208342Z stdout F 2022-03-10 10:47:30,298 2591807 [core-30] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Stopping.
2022-03-10T10:47:30.298212699Z stdout F 2022-03-10 10:47:30,298 2591807 [storage-io-66] DEBUG i.p.s.s.chunklayer.ReadOperation - ChunkedSegmentStorage[1] read - found chunk to read - op=1146797483, segment=_system/containers/metadata_1, chunk=ChunkMetadata(name=_system/containers/metadata_1.E-1-O-0.e93e58d8-35a5-4838-b658-479d5fcee026, length=2308271, nextChunk=null, status=1), startOffset=0, length=2308271, readOffset=71492.
2022-03-10T10:47:30.298217118Z stdout F 2022-03-10 10:47:30,298 2591807 [core-30] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: Failed due to component failure.
2022-03-10T10:47:30.298233959Z stdout F 2022-03-10 10:47:30,298 2591807 [storage-io-66] DEBUG i.p.s.s.chunklayer.ReadOperation - ChunkedSegmentStorage[1] read - chunk lookup - op=1146797483, segment=_system/containers/metadata_1, offset=71492, scanned=0, latency=0.
2022-03-10T10:47:30.298329215Z stdout F 2022-03-10 10:47:30,298 2591807 [core-30] ERROR i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[1]: Unexpected problem creating internal Segment _system/containers/event_processor_GC.failed.queue.1_1.
2022-03-10T10:47:30.298341954Z stdout F io.pravega.common.ObjectClosedException: Object 'MultiKeySequentialProcessor' has been closed and cannot be accessed anymore.
```
But it does not have further consequences. When the Segment Container restarts, the Event Processor resumes its activity:
```
2022-03-10 11:32:50,882 15751 [core-2] DEBUG i.p.s.s.c.ContainerEventProcessorImpl - EventProcessor[1-3]: Finished iteration for EventProcessor (Name = GC.queue.1, Start offset = 131999, Processed offset = 218511, Failed iteration = false).
```

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java [hunk 6]
```diff
@@ -123,12 +132,36 @@
...
-    static Function<String, CompletableFuture<DirectSegmentAccess>> getOrCreateInternalSegment(SegmentContainer container,
-                                                                                               MetadataStore metadataStore,
-                                                                                               Duration timeout) {
-        return s -> metadataStore.registerPinnedSegment(getEventProcessorSegmentName(container.getId(), s),
-                SYSTEM_CRITICAL_SEGMENT, null, timeout) // Segment should be pinned.
-                .thenCompose(l -> container.forSegment(getEventProcessorSegmentName(container.getId(), s), timeout));
+    Function<String, CompletableFuture<DirectSegmentAccess>> getOrCreateInternalSegment(SegmentContainer container,
+                                                                                        MetadataStore metadataStore,
+                                                                                        Duration timeout) {
+        return s -> tryCreateAndPinInternalSegment(container, metadataStore, s, timeout)
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:138]: tryCreateAndPinInternalSegment is called on every access.

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 2 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:145]: ok I missed  that call is made from synchronised block in createEventProcessor

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 5 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:149]: > inside createEventProcessor(), which is a private function with called from a synchronized block in forConsumer() or forDurableQueue().

I think that statement answers my question -

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 6 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:138]: > inside createEventProcessor(), which is a private function with called from a synchronized block in forConsumer() or forDurableQueue().

I think that statement answers my question

File: segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java (hunk 5 above)
Comment (sachin-j-joshi) [reply segmentstore/server/src/main/java/io/pravega/segmentstore/server/containers/ContainerEventProcessorImpl.java:149]: In this case putting this logic still works because 
```
CompletableFuture<EventProcessor> result) {
        return segmentSupplier.apply(name) --> this statement is executed in synchronized block
```

and so `tryCreateAndPinInternalSegment `and `eventProcessorFuture = this.eventProcessorMap.get(eventProcessorName);` happen to be executed in synchronized block.


So in this case code seems to be thread safe.

**Review by sachin-j-joshi — APPROVED** [review]
LGTM
