### PR TITLE
Issue 4409: Reset tokenRefreshFuture upon exception in obtaining a new delegation token

### LINKED ISSUE #4409: JWTTokenProvider does not handle errors
**Problem description**
When the JWTTokenProvider has a DNS issue during refresh the `currentRefreshFuture` never gets cleared which means subsequent `refreshToken` calls skip over the `recreateToken` call.  This leads to the TokenProvider getting locked as it never recovers even when the DNS fault has been resolved.

**Problem location**
https://github.com/pravega/pravega/blob/813b0babd4cbf99db3f4c2fb44273f9d25c555e7/client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java#L225

The `currentRefreshFuture.thenApply` has no provision for an exceptionally completed future which means the `this.tokenRefreshFuture.compareAndSet(handleToCurrentRefreshFuture, null);` ever gets called to clear the `tokenRefreshFuture`.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Fix a bug that prevents `tokenRefreshFuture` from getting reset, preventing the `DelegationTokenProvider` from working properly after errors such as a failed attempt to obtain a new delegation token.  The `tokenRefreshFuture` remained in `iscompletedExceptionally` state forever, and therefore the `JwtTokenProviderImpl` failed to retrieve token post that event. 

**Purpose of the change**  
Fixes #4409 

**What the code does**  
Resets `tokenRefreshFuture` shared variable to `null` if there is an exception in obtaining a new delegation token, so that the logic to refresh the token will be executed again on next attempt. 

**How to verify it**  
All existing and new tests must pass. 
System tests must pass, with and without `auth` enabled.

### CODE REVIEW

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 1]
```diff
@@ -239,6 +240,12 @@ boolean isWithinRefreshThreshold(Instant currentInstant, Instant expiration) {
                     this.tokenRefreshFuture.compareAndSet(handleToCurrentRefreshFuture, null);
                     LoggerHelpers.traceLeave(log, "refreshToken", traceEnterId, this.scopeName, this.streamName);
                     return delegationToken.get().getValue();
+                })
+                .exceptionally(ex -> {
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: We can use `.whenComplete((v, t) -> { }`. It would simplify the code here.

Comment (shrids) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: we an use `whenComplete((token, throwable) -> {}` if `this.recreateToken()` returns a CompletableFuture<DelegationToken>. This would simplify the code right ?

Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: The [JavaDocs ](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) for CompletableFuture says that `whenComplete` _"returns a new CompletionStage with the same result or exception as this stage, that executes the given action when this stage completes"_.

In this piece of code, we are not returning the result of the previous CompletionStage (except for the exception itself), but are rather returning an object extracted inside this stage: `delegationToken.get().getValue()`. 

Therefore, I believe that `whenComplete` is not a good choice here.

Comment (shrids) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: I think if we modify `this.recreateToken()` returns a CompletableFuture<String> or CompletableFuture<DelegationToken> then this would simply the code here.

Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: As discussed, I have modified the code to remove duplication via use of the `handle()` method.

File: client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java [hunk 2]
```diff
@@ -226,20 +229,25 @@ boolean isWithinRefreshThreshold(Instant currentInstant, Instant expiration) {
...
-                    LoggerHelpers.traceLeave(log, "refreshToken", traceEnterId, this.scopeName, this.streamName);
-                    return delegationToken.get().getValue();
-                });
+        return currentRefreshFuture.handle((v, ex) -> {
+            this.tokenRefreshFuture.compareAndSet(handleToCurrentRefreshFuture, null);
+            LoggerHelpers.traceLeave(log, "refreshToken", traceEnterId, this.scopeName, this.streamName);
+            if (ex != null) {
+                log.warn("Encountered an exception in when refreshing token for scope {} and stream {}",
+                        this.scopeName, this.streamName, Exceptions.unwrap(ex));
+                throw ex instanceof CompletionException ? (CompletionException) ex : new CompletionException(ex);
```
Comment (shrids) [inline client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: we can simply throw `ex` wrapped inside a CompletationException.

Comment (ravisharda) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: The intention of throwing the existing exception is to avoid creating a new exception object unnecessarily.

Comment (shiveshr) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: if you dont want to "handle" the returned value/exception, then you can use `whenComplete`

Comment (shrids) [reply client/src/main/java/io/pravega/client/security/auth/JwtTokenProviderImpl.java]: ok. `controllerClient.getOrRefreshDelegationTokenFor(scopeName, streamName)` will not throw an exception of type CompletationException.
