### PR TITLE
Issue 4721: Auto-reconciliation of BookKeeperLog Metadata.

### LINKED ISSUE #4721: Protect Segment Store metadata against Zookeeper client inconsistent replies
**Problem description**
There is general issue in the Segment Store when dealing with Zookeeper metadata under network/connectivity problems. In a nutshell, the `BookkeeperLog` class, which is intended to manage the metadata Bookkeeper ledgers in Zookeeper, can get a `BadVersionException`, which is expected to fail the write to Zookeeper, but the data has been actually written. This leads the Zookeeper metadata managed by the Segment Store to be in an inconsistent state. This is a summary of one instance of this problem:

1) The problems start around "2020-04-16 02:59:32", in which Segment Store 0 has problems connecting to Zookeeper:
```
2020-04-16 02:59:32,369 1812318246 [ZKC-connect-executor-0-EventThread] INFO o.a.b.z.ZooKeeperWatcherBase - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.
...
2020-04-16 02:59:33,771 1812319648 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server nautilus-pravega-zookeeper-client/yyy:2181. Will not attempt to authenticate using SASL (unknown error)
2020-04-16 02:59:33,772 1812319649 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /xxx:60894, server: nautilus-pravega-zookeeper-client/zzz:2181
2020-04-16 02:59:33,774 1812319651 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] WARN org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x3005595379a7d2e has expired
2020-04-16 02:59:33,774 1812319651 [ZKC-connect-executor-0-EventThread] INFO o.a.b.meta.AbstractZkLedgerManager - ZooKeeper client expired on ledger manager.
2020-04-16 02:59:33,774 1812319651 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x3005595379a7d2e has expired, closing socket connection
2020-04-16 02:59:33,774 1812319651 [ZKC-connect-executor-0-EventThread] ERROR o.a.b.z.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
2020-04-16 02:59:33,775 1812319652 [ZKC-connect-executor-0-EventThread] INFO o.a.b.zookeeper.ZooKeeperClient - ZooKeeper session 3005595379a7d2e is expired from nautilus-pravega-zookeeper-client:2181.
2020-04-16 02:59:33,775 1812319652 [ZKC-connect-executor-0-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x3005595379a7d2e
2020-04-16 02:59:33,777 1812319654 [ZKC-connect-executor-0] INFO o.a.b.zookeeper.ZooKeeperClient - Reconnecting zookeeper nautilus-pravega-zookeeper-client:2181.
```

2) Around this time, we observe that a new ledger is created (`1090530`) for Container 0 in Segment Store 0. Note that this snippet is from 30 seconds after the previous one, and there still are problems connecting to Zookeeper:
```
2020-04-16 02:59:46,985 1812332862 [ZKC-connect-executor-0-EventThread] INFO o.a.b.client.LedgerCreateOp - Ensemble: [nautilus-bookie-2.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181, nautilus-bookie-4.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181, nautilus-bookie-1.nautilus-bookie-headless.nautilus-pravega.svc.cluster.local:3181] for ledger: 1090530
2020-04-16 02:59:46,985 1812332862 [core-19] INFO i.p.s.s.i.bookkeeper.BookKeeperLog - Log[0]: Created Ledger 1090530.
2020-04-16 02:59:59,472 1812345349 [core-2] INFO i.p.s.server.CacheManager - CacheManager Registered io.pravega.segmentstore.server.tables.ContainerKeyCache@27f53aab.
2020-04-16 02:59:59,472 1812345349 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] WARN org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 12487ms for sessionid 0x2006ed9c323157e
2020-04-16 02:59:59,472 1812345349 [ZKC-connect-executor-0-SendThread(nautilus-pravega-zookeeper-client:2181)] INFO org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 12487ms for sessionid 0x2006ed9c323157e, closing socket connection and attempting reconnect
```

3) After creating the Ledger, the Segment Store tries to update the metadata of ledgers in Zookeeper, but it **fails (?)** because "apparently" it has been fenced out by another Segment Store:
```
2020-04-16 03:00:04,610 1812350487 [core-19] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED.
io.pravega.segmentstore.storage.DataLogWriterNotPrimaryException: Unable to acquire exclusive write lock for log (path = 'pravega/nautilus/segmentstore/containers/0/0/0').
...
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /pravega/nautilus/segmentstore/containers/0/0/0
```
In any case, getting a `BadVersionException` means that the **addition of ledger `1090530` to the Zookeeper metadata has failed (i.e., not committed)**.

4) This is strange, because in theory Segment Store 0 owns Container 0, but we can see that there is some churn in the ownership of containers during this time:
```
Segment Store 0
2020-04-16 02:56:27,286 1812133163 [core-12] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [16, 1, 33, 17, 34, 2, 19, 22], Current = [16, 1, 17, 33, 2, 34, 19, 22], PendingTasks = [], ToStart = [], ToStop = []. 2020-04-16 02:57:41,368 1812207245 [core-12] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [16, 32, 1, 33, 17, 34, 2, 19, 21, 22], Current = [16, 1, 17, 33, 2, 34, 19, 22], PendingTasks = [], ToStart = [32, 21], ToStop = [].
2020-04-16 02:58:11,741 1812237618 [core-26] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [1, 33, 17, 34, 2, 19, 21, 22], Current = [16, 32, 1, 17, 33, 2, 34, 19, 21, 22], PendingTasks = [], ToStart = [], ToStop = [16, 32].
2020-04-16 02:59:34,186 1812320063 [core-28] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [], Current = [1, 17, 33, 2, 34, 19, 21, 22], PendingTasks = [], ToStart = [], ToStop = [1, 17, 33, 2, 34, 19, 21, 22]. 2020-04-16 02:59:46,971 1812332848 [core-2] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 17, 33, 2, 34, 19, 21], Current = [], PendingTasks = [], ToStart = [0, 16, 17, 33, 2, 34, 19, 21], ToStop = [].
2020-04-16 02:59:59,498 1812345375 [core-7] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 17, 33, 2, 34, 19, 21], Current = [], PendingTasks = [0, 16, 17, 33, 2, 34, 19, 21], ToStart = [], ToStop = [].
```
```
Segment Store 3
2020-04-16 02:46:35,841 1811466360 [core-20] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [32, 0, 18, 3, 35, 21, 37, 27], Current = [32, 0, 18, 35, 3, 37, 21, 27], PendingTasks = [], ToStart = [], ToStop = []. 
2020-04-16 02:56:43,468 1812073987 [core-9] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [32, 0, 18, 3, 35, 21, 37, 27], Current = [32, 0, 18, 35, 3, 37, 21, 27], PendingTasks = [], ToStart = [], ToStop = [].
2020-04-16 02:58:02,150 1812152669 [core-3] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [], Current = [32, 0, 18, 35, 3, 37, 21, 27], PendingTasks = [], ToStart = [], ToStop = [32, 0, 18, 35, 3, 37, 21, 27].
2020-04-16 02:58:14,091 1812164610 [core-28] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 18, 35, 3, 4, 27], Current = [27], PendingTasks = [27], ToStart = [0, 16, 32, 18, 35, 3, 4], ToStop = [].
2020-04-16 02:58:26,058 1812176577 [core-26] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 18, 35, 3, 4, 27], Current = [], PendingTasks = [0, 16, 32, 18, 3, 35, 4], ToStart = [27], ToStop = [].
2020-04-16 02:58:37,624 1812188143 [core-20] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 18, 35, 3, 4, 27], Current = [], PendingTasks = [0, 16, 32, 18, 3, 35, 4, 27], ToStart = [], ToStop = [].
2020-04-16 02:58:47,625 1812198144 [core-2] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 18, 35, 3, 4, 27], Current = [], PendingTasks = [0, 16, 32, 18, 3, 35, 4, 27], ToStart = [], ToStop = [].
2020-04-16 02:58:57,625 1812208144 [core-11] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 18, 35, 3, 4, 27], Current = [32, 16, 35, 3, 4, 27], PendingTasks = [0, 18], ToStart = [], ToStop = [].
2020-04-16 02:59:22,388 1812232907 [core-14] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 16, 32, 1, 18, 35, 3, 4, 22, 27], Current = [32, 0, 16, 18, 35, 3, 4, 27], PendingTasks = [], ToStart = [1, 22], ToStop = [].
2020-04-16 02:59:46,968 1812257487 [core-13] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [32, 1, 18, 35, 3, 4, 22, 27], Current = [32, 0, 16, 1, 18, 35, 3, 4, 22, 27], PendingTasks = [], ToStart = [], ToStop = [0, 16].
2020-04-16 03:09:47,934 1812858453 [core-21] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [32, 1, 18, 35, 3, 4, 22, 27], Current = [32, 1, 18, 35, 3, 4, 22, 27], PendingTasks = [], ToStart = [], ToStop = [].
```
```
Segment Store 4
2020-04-16 02:56:28,561 1812031775 [core-10] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [4, 20, 36, 7, 26, 10, 43, 30], Current = [4, 36, 20, 7, 26, 10, 43, 30], PendingTasks = [], ToStart = [], ToStop = []. 
2020-04-16 02:57:40,461 1812103675 [core-9] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 4, 20, 36, 37, 7, 26, 10, 43, 30], Current = [4, 36, 20, 7, 26, 10, 43, 30], PendingTasks = [], ToStart = [0, 37], ToStop = [].
2020-04-16 02:58:11,704 1812134918 [core-13] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [20, 36, 37, 7, 26, 10, 43, 30], Current = [0, 4, 36, 20, 37, 7, 26, 10, 43, 30], PendingTasks = [], ToStart = [], ToStop = [0, 4].
2020-04-16 02:59:22,363 1812205577 [core-10] INFO i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [33, 20, 36, 37, 7, 26, 10, 43, 30], Current = [36, 20, 37, 7, 26, 10, 43, 30], PendingTasks = [], ToStart = [33], ToStop = [].
``` 

5) In any case, once the Segment Store gets a `BadVersionException` when attempting to update the Zookeeper metadata in the `BookkeeperLog:initialize()` method, the recently created ledger `1090530` is correctly deleted from Bookkeeper. This works fine.

6) But here is the problem: the ledger `1090530` created for Container 0 has been correctly deleted from Bookkeeper, **but it appears in the Zookeeper metadata managed by the Segment Store**. This means that the `BadVersionException` got from the Zookeeper client (Curator), actually wrote the ledger id in Zookeeper. The consequence of this is that when the Container tries to recover, it complains given that there is a ledger in the Zookeeper metadata that does not exists in Bookkeeper:

```
2020-04-16 03:00:08,362 1812354239 [core-28] INFO i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Starting.
2020-04-16 03:00:08,362 1812354239 [core-28] INFO i.p.s.server.logs.DurableLog - DurableLog[0]: Starting.
2020-04-16 03:00:08,368 1812354245 [core-29] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED.
io.pravega.segmentstore.storage.DurableDataLogException: Unable to open-fence ledger 1090530.
...
Caused by: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
...
2020-04-16 03:03:09,555 1812535432 [core-5] INFO i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Starting.
2020-04-16 03:03:09,555 1812535432 [core-5] INFO i.p.s.server.logs.DurableLog - DurableLog[0]: Starting.
2020-04-16 03:03:09,562 1812535439 [core-4] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED.
io.pravega.segmentstore.storage.DurableDataLogException: Unable to open-fence ledger 1090530.
...
Caused by: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsException: No such ledger exists
```

This means that, under some concrete circumstances in which network has glitches and the Zookeeper client is attempting to reconnect, we could have a `BadVersionException` response from the client that actually writes the data to Zookeeper. We need to protect the Segment Store against this kind of situations.

**Problem location**
`BookkeeperLog`, and any other place in which metadata in Zookeeper is updated by the Segment Store.

**Suggestions for an improvement**
If it is not possible to find and get a fix for the Curator client, we need to add some defensive code to prevent this situation.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- BookKeeperLog.persistMetadata will auto-reconcile the metadata if it gets a `NodeExistsException` or `BadVersionException` from ZooKeeper while doing a CAS update. 

**Purpose of the change**  
Fixes #4721.

**What the code does**  
- See #4721 for why this is needed.
- The `BookKeeperLog` will attempt to read the metadata from ZK and compare it to what it wanted to persist in the first place. If identical (except for versions), it will consider the update to have gone through, otherwise it will rethrow the original exception.

**How to verify it**  
New unit test added.

### CODE REVIEW

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 1]
```diff
@@ -870,6 +864,38 @@ private void persistMetadata(LogMetadata metadata, boolean create) throws Durabl
...
+    /**
+     * Verifies the given {@link LogMetadata} against the actual one stored in ZooKeeper.
+     *
+     * @param metadata The Metadata to check.
+     * @return True if the metadata stored in ZooKeeper is an identical match to the given one, false otherwise. If true,
+     * {@link LogMetadata#getUpdateVersion()} will also be updated with the one stored in ZooKeeper.
+     */
+    private boolean reconcileMetadata(LogMetadata metadata) {
+        try {
+            val actualMetadata = loadMetadata();
```
Comment (RaulGracia) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:888]: there is a case in which `loadMetadata()` can return `null`. Maybe this is handled by the `equals` generated by Lombok, but just wanted to create awareness on this corner case.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java [hunk 2]
```diff
@@ -840,28 +840,22 @@ private LogMetadata updateMetadata(LogMetadata currentMetadata, LedgerHandle new
...
+            Stat result = create
+                    ? createZkMetadata(serializedMetadata)
+                    : updateZkMetadata(serializedMetadata, metadata.getUpdateVersion());
             metadata.withUpdateVersion(result.getVersion());
         } catch (KeeperException.NodeExistsException | KeeperException.BadVersionException keeperEx) {
-            // We were fenced out. Clean up and throw appropriate exception.
-            throw new DataLogWriterNotPrimaryException(
-                    String.format("Unable to acquire exclusive write lock for log (path = '%s%s').", this.zkClient.getNamespace(), this.logNodePath),
-                    keeperEx);
+            if (reconcileMetadata(metadata)) {
```
Comment (RaulGracia) [inline segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLog.java:848]: If we reached this point and we get a `BadVersionException` for an update that has been actually committed (origin of the issue), this PR can fix the problem (by not throwing, so keeping the BK ledgers along with the new ledger metadata) in the case that the `zkClient` has a session established with the server. However, as the origin of this issue itself is closely related to the instability of the network, it may be the case that the `reconcileMetadata()` fails as it is not able to load the current state (whatever it is) from Zookeeper (session may be lost or suspended). If I'm not mistaken, this will leave us in the same situation: the Zookeeper session will be re-established sooner or later, then the `initialize()` method will get executed upon a container recovery, and the same symptom will appear when executing `Ledgers.fenceOut()` (the metadata for a ledger is in ZK, but the ledger is not in BK), so the container will keep restarting indefinitely. The question is: what do we do at this point in the code if we cannot know what is the state of the data in Zookeeper? Should we try to reconcile when the container restarts again?
