### PR TITLE
Issue 1538: Make updateStream's state update idempotent

### LINKED ISSUE #1538: Bug: Setting state to updating is not idempotent in stream store
**Problem description**
We first set state to Updating following by updating the configuration. 
If controller fails after setting the state but before updating the configuration, the setting of state to Updating is not idempotent as it checks and processes only if original state is Active.  

**Problem location**
Controller Stream Metadata Store

**Suggestions for an improvement**
fix the bug by allowing to run update for both Active and Updating states.

### PR DESCRIPTION
**Pull request by shiveshr**
**Change log description**
We first set state to Updating following by updating the configuration.
If controller fails after setting the state but before updating the configuration, the setting of state to Updating is not idempotent as it checks and processes only if original state is Active.

**Purpose of the change**
Fixes #1538

**What the code does**
Allows `updateStream` to run if state is updating. 

**How to verify it**
unit test added

### CODE REVIEW

File: controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java [hunk 1]
```diff
@@ -427,6 +427,41 @@ public void scaleTest() throws Exception {
...
+        final StreamConfiguration configuration = StreamConfiguration.builder().scope(scope).streamName(stream).scalingPolicy(policy).build();
+
+        long start = System.currentTimeMillis();
+        store.createScope(scope).get();
+
+        store.createStream(scope, stream, configuration, start, null, executor).get();
+        store.setState(scope, stream, State.ACTIVE, null, executor).get();
+
+        // region idempotent
+        final StreamConfiguration configuration2 = StreamConfiguration.builder().scope(scope).streamName(stream).scalingPolicy(policy).build();
```
Comment (skrishnappa) [inline controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: Trying to update with same configuration, maybe you can try with a different config to exercise different flows?

Comment (shiveshr) [inline controller/src/test/java/io/pravega/controller/store/stream/StreamMetadataStoreTest.java]: update configuration is protected under task lock.. with this PR we are not changing that.. Which means a configuration cannot conflict with another until previously started update completes.

**Comment by shiveshr** [comment]
@skrishnappa this was found through code review on 711, where i noticed this bug.
