### PR TITLE
Issue 7104: Delayed future cancelation

### LINKED ISSUE #7104: Client doesn't exit properly if connection factory closed while connections are in use.
**Describe the bug**
If a client is in the middle of reconnecting with backoff and the application closes the connection factory, this will shutdown the thread pool while there are retry tasks queued. Because the task is queued and not active, the thread will not be interrupted, and no cancelation exception will propagate upwards to the application layer.

It is not recommended to close the connectionFactory first, but we must guard against this behavior anyway.

### LINKED ISSUE #7327: Flaky test StorageLoaderTest.testSlowModeWithInMemoryStorage
**Describe the bug**
This test is making our builds to fail quite often:
```
io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage FAILED. Output (Last 300 lines):
 > 2023-11-24 08:18:56,959 186185 [Test worker] WARN  i.p.s.s.h.s.TLSConfigChangeEventConsumer - Invoked for null watchEvent
 > 2023-11-24 08:18:56,959 186185 [Test worker] INFO  i.p.s.s.h.s.TLSConfigChangeHandler - Current reload count = 1
 > 2023-11-24 08:19:14,871 190192 [Time-limited test] WARN  i.p.c.c.ExecutorServiceHelpers - One or more threads from pool ThreadPoolScheduledExecutorService(runner=java.util.concurrent.ThreadPoolExecutor@58347e4d[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 62]) did not shutdown properly. Waiting tasks: []
 > 2023-11-24 08:19:14,872 190193 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'core' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,878 190199 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'storage-io' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,894 190215 [Time-limited test] WARN  i.p.c.c.ExecutorServiceFactory - Created Thread Pool 'low-priority-cleanup' with leak detection level set to 'Aggressive'. THE VM WILL BE HALTED IF A LEAK IS DETECTED. DO NOT USE IN PRODUCTION.
 > 2023-11-24 08:19:14,898 190219 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=FILESYSTEM, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=HDFS, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=EXTENDEDS3, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=S3, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=GCP, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,899 190220 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=AZURE, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,900 190221 [Time-limited test] INFO  i.p.s.server.host.StorageLoader - Loading INMEMORY, trying StorageFactoryInfo(name=INMEMORY, storageLayoutType=CHUNKED_STORAGE)
 > 2023-11-24 08:19:14,900 190221 [Time-limited test] INFO  i.p.s.server.CacheManager - CacheManager Registered io.pravega.segmentstore.server.tables.ContainerKeyCache@47a81781.
 > 2023-11-24 08:19:14,901 190222 [Time-limited test] INFO  i.p.c.concurrent.DelayedProcessor - TableCompactor[0]: Started. Iteration Delay = 30000 ms.
 > 2023-11-24 08:19:14,905 190226 [Time-limited test] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Registered SegmentContainer 0.
 > 2023-11-24 08:19:14,905 190226 [Time-limited test] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Starting.
 > 2023-11-24 08:19:14,906 190227 [Time-limited test] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Starting.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovery started.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Enter RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Reset.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0] Enter RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0]: Cleared.
 > 2023-11-24 08:19:14,906 190227 [core-5] WARN  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0]: Reached the end of the DataFrameLog and could not find any MetadataCheckpointOperations after reading 0 Operations and 0 Data Frames.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.server.logs.RecoveryProcessor - RecoveryProcessor[0] Recovery completed. Epoch = 1, Items Recovered = 0, Time = 0ms.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: Exit RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0] Exit RecoveryMode.
 > 2023-11-24 08:19:14,906 190227 [core-5] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Started.
 > 2023-11-24 08:19:14,909 190230 [core-5] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: MetadataCheckpointOperation(1) stored.
 > 2023-11-24 08:19:14,909 190230 [core-5] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Started (Online).
 > 2023-11-24 08:19:14,910 190231 [core-12] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Initializing storage with epoch 1
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] BOOT started.
 > 2023-11-24 08:19:14,910 190231 [core-9] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] reading snapshot info from store.
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] Read Snapshot info from store. Info = null
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - Chunk containing SnapshotInfo does not exist. This is ok if this is new installation. Chunk name = _system/containers/_sysjournal.container0.snapshot_info
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] No Snapshot info available from storage. This is ok if this is new installation
 > 2023-11-24 08:19:14,910 190231 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] No Snapshot info available. This is ok if this is new installation
 > 2023-11-24 08:19:14,915 190236 [test-1] INFO  i.p.s.s.chunklayer.SystemJournal - SystemJournal[0] BOOT complete - applied 0 records in 10 journals. Total time = 4 ms.
 > 2023-11-24 08:19:14,915 190236 [core-14] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,915 190236 [core-14] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Initializing Metadata Store.
 > 2023-11-24 08:19:14,917 190238 [core-14] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: MapStreamSegment SegmentId = 1, Name = '_system/containers/metadata_0', Active = 1
 > 2023-11-24 08:19:14,917 190238 [core-14] INFO  i.p.s.s.c.TableMetadataStore - MetadataStore[0]: Metadata Segment pinned. Name = '_system/containers/metadata_0', Id = '1'
 > 2023-11-24 08:19:14,918 190239 [core-17] INFO  i.p.s.s.m.LocalSegmentContainerManager - Container 0 has been registered.
 > 2023-11-24 08:19:14,918 190239 [Time-limited test] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopping.
 > 2023-11-24 08:19:14,918 190239 [Time-limited test] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Stopping.
 > 2023-11-24 08:19:14,919 190240 [core-14] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Unexpected exception in OperationProcessor while processing items for commitProcessor, rethrowing.
 > java.util.concurrent.CancellationException: null
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2402)
 > 	at io.pravega.common.util.AbstractDrainingQueue.cancelPendingTake(AbstractDrainingQueue.java:94)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.closeQueue(OperationProcessor.java:461)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:199)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:257)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:531)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:513)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:156)
 > 	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.close(LocalSegmentContainerManager.java:95)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.closeComponent(ServiceBuilder.java:347)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:156)
 > 	at io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
 > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > 2023-11-24 08:19:14,919 190240 [core-14] INFO  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Completing and closing commitProcessor. OperationProcessor running? false, queueProcessor running? false.
 > 2023-11-24 08:19:14,919 190240 [core-14] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: commitProcessor completed exceptionally java.util.concurrent.CompletionException: java.util.concurrent.CancellationException.
 > 2023-11-24 08:19:14,920 190241 [core-18] WARN  i.p.s.s.logs.OperationProcessor - OperationProcessor[0]: Unexpected exception in OperationProcessor while processing items for queueProcessor, rethrowing.
 > java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
 > 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2404)
 > 	at io.pravega.common.util.AbstractDrainingQueue.close(AbstractDrainingQueue.java:76)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.closeQueue(OperationProcessor.java:451)
 > 	at io.pravega.segmentstore.server.logs.OperationProcessor.doStop(OperationProcessor.java:199)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.logs.DurableLog.doStop(DurableLog.java:257)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:531)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.doStop(StreamSegmentContainer.java:513)
 > 	at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:285)
 > 	at io.pravega.common.concurrent.Services.stopAsync(Services.java:67)
 > 	at io.pravega.segmentstore.server.store.StreamSegmentContainerRegistry.stopContainer(StreamSegmentContainerRegistry.java:156)
 > 	at io.pravega.segmentstore.server.mocks.LocalSegmentContainerManager.close(LocalSegmentContainerManager.java:95)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.closeComponent(ServiceBuilder.java:347)
 > 	at io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:156)
 > 	at io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
 > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
 > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
 > 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
 > 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: java.util.concurrent.CancellationException: null
 > 	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2402)
 > 	... 29 common frames omitted
 > 2023-11-24 08:19:14,920 190241 [core-18] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: RecoverFromStorage mode is false 
 > 2023-11-24 08:19:14,920 190241 [core-18] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Not recovering from storage. No need to adjust lengths
 > 2023-11-24 08:19:14,920 190241 [core-18] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Ignoring delayed start error due to Segment Container shutting down.
 > java.util.concurrent.CompletionException: io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
 > 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
 > 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
 > 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
 > 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 > 	at io.pravega.common.concurrent.ThreadPoolScheduledExecutorService$ScheduledRunnable.run(ThreadPoolScheduledExecutorService.java:197)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 > 	at java.base/java.lang.Thread.run(Thread.java:829)
 > Caused by: io.pravega.segmentstore.server.IllegalContainerStateException: Container 0 is in an invalid state for this operation. Expected: RUNNING; Actual: STOPPING.
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.ensureRunning(StreamSegmentContainer.java:1219)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.createStreamSegment(StreamSegmentContainer.java:670)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.tryCreateAndPinInternalSegment(ContainerEventProcessorImpl.java:151)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.lambda$getOrCreateInternalSegment$1(ContainerEventProcessorImpl.java:138)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.createEventProcessor(ContainerEventProcessorImpl.java:254)
 > 	at io.pravega.segmentstore.server.containers.ContainerEventProcessorImpl.forConsumer(ContainerEventProcessorImpl.java:216)
 > 	at io.pravega.segmentstore.server.containers.StorageEventProcessor.addQueue(StorageEventProcessor.java:90)
 > 	at io.pravega.segmentstore.storage.chunklayer.GarbageCollector.initialize(GarbageCollector.java:185)
 > 	at io.pravega.segmentstore.storage.chunklayer.ChunkedSegmentStorage.finishBootstrap(ChunkedSegmentStorage.java:232)
 > 	at io.pravega.segmentstore.server.containers.StreamSegmentContainer.lambda$startWhenDurableLogOnline$10(StreamSegmentContainer.java:365)
 > 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
 > 	... 6 common frames omitted
 > 2023-11-24 08:19:14,921 190242 [Time-limited test] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopping.
 > 2023-11-24 08:19:14,921 190242 [Time-limited test] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[0]: Stopped.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.server.CacheManager - CacheManager Unregistered io.pravega.segmentstore.server.tables.ContainerKeyCache@47a81781.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.s.s.tables.ContainerKeyIndex - KeyIndex[0]: Closed.
 > 2023-11-24 08:19:14,922 190243 [core-19] INFO  i.p.c.concurrent.DelayedProcessor - TableCompactor[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.t.FixedKeyLengthTableSegmentLayout - TableExtension[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.t.ContainerTableExtensionImpl - TableExtension[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - SegmentContainer[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - StorageWriter[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.c.c.AbstractThreadPoolService - OperationProcessor[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.server.logs.DurableLog - DurableLog[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.a.ContainerAttributeIndexImpl - ContainerAttributeIndex[0]: Closed.
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed metadataStore
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed garbageCollector
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed taskQueue
 > 2023-11-24 08:19:14,923 190244 [core-19] INFO  i.p.s.s.c.ChunkedSegmentStorage - ChunkedSegmentStorage[0] Closed chunkStorage
 > 2023-11-24 08:19:14,923 190244 [Time-limited test] INFO  i.p.s.server.CacheManager - CacheManager Closed.
 > 2023-11-24 08:19:14,924 190245 [core-19] INFO  i.p.s.s.c.ContainerEventProcessorImpl - ContainerEventProcessor[0]: Closing ContainerEventProcessor service.

io.pravega.segmentstore.server.host.StorageLoaderTest > testSlowModeWithInMemoryStorage FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
        at java.base@11.0.21/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.21/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.21/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
        at java.base@11.0.21/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
        at app//io.pravega.common.concurrent.ThreadPoolScheduledExecutorService.awaitTermination(ThreadPoolScheduledExecutorService.java:242)
        at app//io.pravega.common.concurrent.ExecutorServiceHelpers.shutdown(ExecutorServiceHelpers.java:197)
        at app//io.pravega.segmentstore.server.store.ServiceBuilder.close(ServiceBuilder.java:162)
        at app//io.pravega.segmentstore.server.host.StorageLoaderTest.testSlowModeWithInMemoryStorage(StorageLoaderTest.java:247)
```

**To Reproduce**
Frequently seen in our builds: https://github.com/pravega/pravega/actions/runs/6969546123/job/18989554932

**Screenshots**
n/a

**Additional information**
n/a

### LINKED ISSUE #7375: Flakey test: EndToEndChannelLeakTest.testDetectChannelLeakSegmentSealed
**Describe the bug**
A flakey test has been observed several times:

```
io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest > testDetectChannelLeakSegmentSealed FAILED
    java.util.concurrent.TimeoutException: Timeout expired prior to the condition becoming true. Expected value: 0 observed: 1
        at io.pravega.test.common.TestUtils.awaitEvaluateExpr(TestUtils.java:121)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:68)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:53)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.assertChannelCount(EndToEndChannelLeakTest.java:513)
        at io.pravega.test.integration.endtoendtest.EndToEndChannelLeakTest.testDetectChannelLeakSegmentSealed(EndToEndChannelLeakTest.java:311)
```
An example of this is:
https://github.com/pravega/pravega/actions/runs/7753263574/job/21144325636

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**  
Makes sure that delayed futures, async loops, and exponential backoff get canceled if the theread pool they are running on is shutdown, and a cancelation exception is propagated upwards.

**Purpose of the change**  
Fixes #7104
Also fixes #7327
Also fixes #7375 

**What the code does**  
Modifies the thread pool to supply a CompletableFuture to the caller of delay task so that this can be awaited rather than chaining another future off thread pool task. Similarly for Futures.loop and backoff the cancelation of the future and failure to submit another task to the pool are propagated to the result future.

Additionally: The style formatter had a pathological case when dealing with indentation of nested runnables as arguments as often occurs in async code. There is a new capability to deal with this, as such the format style is updated. (Due to the version update this is very noisy, but there is only one real change)

**How to verify it**  
New unit tests are added. However it should be run through system and other tests, as a sanity check because additional exceptions are being introduced which would have been silent before.

### CODE REVIEW

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]
I suggest we separate formatting/style related changes into it's own separate PR and not pollute this PR. Also, while handleException change in ChunkedSegmentStorage is nice to have, it is not necessary and seems unrelated to this PR. Let's include that somewhere else.

Keeping the changes in this PR short and focused will help us in case we need to cherry pick and backport this.


FutureSuplier seems like a good way avoid conflict between ScheduledFuture::get and Supplier:get in CancellableFuture

File: client/src/test/java/io/pravega/client/stream/impl/LargeEventWriterTest.java [hunk 1]
```diff
@@ -426,7 +426,7 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
         assertTrue(succeeded.getAndSet(false));
     }
     
-    @Test(timeout = 5000)
+    @Test(timeout = 10000)
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/test/java/io/pravega/client/stream/impl/LargeEventWriterTest.java:429]: This test failed four runs in a row. I am not sure how to merge anything without this change...
The issue appears to be specific to this test. It is being caused by a very long load time for slf4j being loaded because a mock class is being read for the first time, as this requires reading a file on disk.

File: checkstyle/eclipse.xml
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply checkstyle/eclipse.xml:1]: Yeah. See my comment in the PR description. It is basically changing only one value in the config. But as it is a new property I had to update the version, which caused it to change the format. The only semantic difference relates to the indentation for nesting futures. All the deltas in this PR and formatted with it, which should give you an idea for how it looks.

File: controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java [hunk 2]
```diff
@@ -43,13 +39,16 @@
...
 import java.util.stream.IntStream;
+import lombok.val;
+import org.apache.commons.lang3.tuple.ImmutablePair;
+import org.apache.commons.lang3.tuple.Pair;
+import org.slf4j.LoggerFactory;
 
 import static io.pravega.controller.store.PravegaTablesStoreHelper.BYTES_TO_UUID_FUNCTION;
 import static io.pravega.controller.store.PravegaTablesStoreHelper.UUID_TO_BYTES_FUNCTION;
-import static io.pravega.controller.store.stream.PravegaTablesStreamMetadataStore.DATA_NOT_FOUND_PREDICATE;
+import static io.pravega.controller.store.stream.AbstractStreamMetadataStore.DATA_NOT_FOUND_PREDICATE;
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply controller/src/main/java/io/pravega/controller/store/PravegaTablesScope.java:51]: Nope. Reverted.

File: segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java [hunk 3]
```diff
@@ -179,9 +181,11 @@ private BookKeeper startBookKeeperClient() throws Exception {
         } else {
             config = config.setEnsemblePlacementPolicy(DefaultEnsemblePlacementPolicy.class);
         }
-
-        return BookKeeper.newBuilder(config)
-                         .build();
+        final ClientConfiguration c = config;
+        return Retry.withExpBackoff(100, 10, 3)
+                    .retryingOn(IOException.class)
+                    .throwingOn(RuntimeException.class)
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/BookKeeperLogFactory.java:187]: It was, but I see where it's not clear. I updated it.

File: common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java [hunk 4]
```diff
@@ -93,9 +93,13 @@ public ThreadPoolScheduledExecutorService(int corePoolSize, ThreadFactory thread
         runner.prestartAllCoreThreads();
     }
 
+    public static interface ScheduledChainableFuture<R> extends ScheduledFuture<R>, FutureSuplier<R> {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply common/src/main/java/io/pravega/common/concurrent/ThreadPoolScheduledExecutorService.java]: Done

File: common/src/main/java/io/pravega/common/concurrent/Futures.java [hunk 5]
```diff
@@ -644,16 +644,21 @@ public static <T> void onTimeout(CompletableFuture<T> future, Consumer<TimeoutEx
...
     public static CompletableFuture<Void> delayedFuture(Duration delay, ScheduledExecutorService executorService) {
-        CompletableFuture<Void> result = new CompletableFuture<>();
         if (delay.toMillis() == 0) {
             // Zero delay; no need to bother with scheduling a task in the future.
-            result.complete(null);
+            return CompletableFuture.completedFuture(null);
         } else {
-            ScheduledFuture<Boolean> sf = executorService.schedule(() -> result.complete(null), delay.toMillis(), TimeUnit.MILLISECONDS);
-            result.whenComplete((r, ex) -> sf.cancel(true));
+            if (executorService instanceof ThreadPoolScheduledExecutorService) {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply common/src/main/java/io/pravega/common/concurrent/Futures.java:651]: Done

File: client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java [hunk 6]
```diff
@@ -291,6 +293,40 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
...
+            @Override
+            public Void answer(InvocationOnMock invocation) throws Throwable {
+                WireCommands.GetStreamSegmentInfo request = invocation.getArgument(0);
+                requestIds.add(request.getRequestId());
+                if (requestIds.size() == 1) {
+                    ReplyProcessor processor = cf.getProcessor(endpoint);
+                    processor.connectionDropped();
+                } else {
+                    cf.close();
+                    ReplyProcessor processor = cf.getProcessor(endpoint);
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java]: Pulled up

File: client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java [hunk 7]
```diff
@@ -291,6 +293,40 @@ public Void answer(InvocationOnMock invocation) throws Throwable {
         assertEquals(123, length);
     }
     
+    @Test(timeout = 10000)
+    public void testShutdownDurringReconnect() throws Exception {
```
[the remark this answers is not in the document]
Comment (tkaitchuck) [reply client/src/test/java/io/pravega/client/segment/impl/SegmentMetadataClientTest.java]: fixed

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java [hunk 8]
```diff
@@ -273,7 +273,7 @@ public CompletableFuture<SegmentHandle> openWrite(String streamSegmentName) {
                     .handleAsync( (v, ex) -> {
                         if (null != ex) {
                             log.debug("{} openWrite - exception segment={} latency={}.", logPrefix, streamSegmentName, timer.getElapsedMillis(), ex);
-                            handleException(streamSegmentName, ex);
+                            throw handleException(streamSegmentName, ex);
```
Comment (sachin-j-joshi) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:276]: This change is not needed.

The method doesn't actually return any value.
```
private RuntimeException handleException(String streamSegmentName, Throwable e) {
        val ex = Exceptions.unwrap(e);
        if (ex instanceof StorageMetadataWritesFencedOutException) {
            throw new CompletionException(new StorageNotPrimaryException(streamSegmentName, ex));
        }
        if (ex instanceof ChunkStorageFullException) {
            throw new CompletionException(new StorageFullException(streamSegmentName, ex));
        }
        throw new CompletionException(ex);
    }
```

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java [hunk 9]
```diff
@@ -989,11 +990,11 @@ <R> CompletableFuture<R> executeParallel(Callable<CompletableFuture<R>> operatio
         }, this.executor);
     }
 
-    static <T extends AutoCloseable, R> CompletableFuture<R> tryWith(T closeable, Function<T, CompletableFuture<R>> function, Executor executor) {
-        return function.apply(closeable)
+    static <R> CompletableFuture<R> tryWith(MetadataTransaction txn, Function<MetadataTransaction, CompletableFuture<R>> function, Executor executor) {
```
Comment (sachin-j-joshi) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:993]: This change is irrelevant and not needed in this PR.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java [hunk 10]
```diff
@@ -105,46 +104,44 @@ public CompletableFuture<Void> call() {
                 chunkedSegmentStorage.getLogPrefix(), System.identityHashCode(this), handle.getSegmentName(), offset, length);
 
         val streamSegmentName = handle.getSegmentName();
-        return ChunkedSegmentStorage.tryWith(chunkedSegmentStorage.getMetadataStore().beginTransaction(false, handle.getSegmentName()),
```
Comment (sachin-j-joshi) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:108]: These changes seem to be unrelated with delayed future cancelation..

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java [hunk 11]
```diff
@@ -105,46 +104,44 @@ public CompletableFuture<Void> call() {
...
+                        chunkedSegmentStorage.getExecutor());
+                }, chunkedSegmentStorage.getExecutor());
+            }, chunkedSegmentStorage.getExecutor()).exceptionally(ex -> {
+                throw handleException(ex);
+            });
     }
 
-    private Object handleException(Throwable e) {
+    private RuntimeException handleException(Throwable e) {
         log.debug("{} write - exception op={}, segment={}, offset={}, length={}.",
```
Comment (sachin-j-joshi) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:145]: These changes seem to be unrelated with delayed future cancelation..

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java [hunk 12]
```diff
@@ -157,7 +154,7 @@ private Object handleException(Throwable e) {
         throw new CompletionException(ex);
     }
 
-    private Object postCommit() {
+    private Void postCommit() {
```
Comment (sachin-j-joshi) [inline segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:157]: These changes seem to be unrelated with delayed future cancelation..

**Review by sachin-j-joshi — CHANGES_REQUESTED** [review]

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 8 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:276]: The method doesn't return any value it always throws. The reason the method signature shows it returning a RuntimeException is so that it can be called in this way. This does two things: 1) Makes it clear to someone looking at the call site that an exception is being thrown. 2) It helps with automated tools that make the assumption that methods will return when they are doing flow analysis. For example if a function ends in a call to handleException there will be an error about not calling return, when of course if there is a return call below it will be unreachable.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java (hunk 9 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/ChunkedSegmentStorage.java:993]: I just tested reverting this line and it gave me multiple compile errors.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java (hunk 11 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:145]: Reverting this results in compile errors for me.

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java (hunk 10 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:108]: Reverted

File: segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java (hunk 12 above)
Comment (tkaitchuck) [reply segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/chunklayer/WriteOperation.java:157]: Reverted

**Review by sachin-j-joshi — APPROVED** [review]
LGTM.
Let's run system tests before merging.

Also waiting for code coverage report.

**Comment by tkaitchuck** [comment]
System tests all pass
