### PR TITLE
Issue 6664: Caching of Request Ids for Request Tracker causes OOM on Controller

### LINKED ISSUE #6664: Caching of Request Ids for Request Tracker causes OOM on Controller
**Describe the bug**
In Controller logs I see the same request for `getURI-test100sssFailScopeVwUZG/_MARKstream-325` being tagged multiple times... infact 100s of times which indicates that in a short interval of time the same request is repeated too many times and before the earlier requests can be answered new requests keep coming in.... all these requests are for the MarkStream and most likely invoked by the Watermarking service.
```
687968806628, 5300827836292785080, 8719272431282860608, -7538067772377576593, 887738531512122747, -6479707821409959817, -7673954003711956361, -7843287761868123805, -7368018701339472680, 4633224097332690045, -7323511335041751699, 7025463663885140196, -5137407570473596366, -5249123331997901278, 2642209689035550778, -4408328145795195295, 2443024723475605495, 4922849640639549426, 4149871622623371498, -6556286854987474107, -8274578765410444296, -7305435419343779418, 4412560459875680833, 2117622605376286706, 8799819366878030200, 9071801182383703500, 5543149021395808389, 563740400927151296, -6459931799334233492, -7152583425866031179, 5907518409908567831, -7550620186579641169, 4664011875410076541, 6455551794110768628, -5532940123484932986, 2421668931542069968, 4124085076871203520, 761039478478262128, 8100150582706962676, -8746781205249885846, 7380971824612816311, 1874158410868117662, -7432997760868954343, 5764325676132165602, -2119040546905532538, -1156473476463703281, 2051443891642291533, -5989036103817683186, -7528992278733835229, 5275212961539916192, -5335901208009968775, -3164550244836994606, 183899367826385619, -6759737619924278341, -3958280133830128233, -9180956035845235042, -584448265310558312, 7771379848917023199, 723919182223462394, 2125213954818853404, -208941099295492671, -1657968524778748169, -596851047937760993, 1861636478018420248, -569292677819944949, 4411664800405997803, 556035124227937037, 8374506671100529111, 2127796140468895589, 828191988336702881, -2038303052841360391, 6913042054615117778, -470008545262691197, 7122531318275976202, -7864567799234352513, -4659257734115101787, -2247637463236475659, 8611325933837361965, 1474903257530332227, -251979719258336101, -4315554996716763698, 1225129516433290349, 2565182981567994845, -8958944668473312830, -8784478068265608688, -5732731468483368200, 8319197205462409911, 4865690852754242062, 3649316445395674919, 5010956325791174194, 1463799615389479444, 1612337382065297291, 2060166507225367709, -469312041477224902, 9171404536743417218, 6159497557697273517, 7969041521109184810, 4364156152602606756, 7980916550595288951, 5520820720651785245, 2270158010357242462, -3209162931053497351, -1613900409786374492, -2971163022066196925, -2915850470219518456, -2854301542137630362, -5913249372225019444, . . .-2414470442516095675]
request ids associated with same descriptor: getURI-test100sss
FailScopeVwUZG/_MARKstream-325/0.#epoch.0. Propagating only first one: -2258451022683104641.

These request descriptors are Cached by Controller in memory, but there is no upper limit on how many request Ids would get stored against the same request descriptor and so in cases like these this list grows very long hogging a lot of memory.
This is also evident from the heap dump which shows about 60-70% of heap being filled with LocalCache Entries and RequestTracker. (See attached file heap-RequestTracker)

The way we do caching for RequestIds needs to be revisited, because clearly in situations like these it seems to unnecessarily occupy a lot of heap memory.

**To Reproduce**
Restart Segment Store several times ~20 times.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Limit max number of parallel request ids for a given request descriptor in `RequestTracker`.

**Purpose of the change**  
Fixes #6664.

**What the code does**  
Sets a limit of max parallel request ids (`MAX_PARALLEL_REQUESTS`) for a given request descriptor in `RequestTracker`. Note that the most recent `MAX_PARALLEL_REQUESTS` request ids are kept in cache.

**How to verify it**  
New tests added to verify that the limit holds. System tests are green with this PR (TPC 4432).

### CODE REVIEW

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java [hunk 1]
```diff
@@ -170,6 +174,9 @@ public void trackRequest(String requestDescriptor, long requestId) {
             }
 
             requestIds.add(requestId);
+            if (requestIds.size() > MAX_PARALLEL_REQUESTS) {
+                requestIds.remove(1); // Delete the oldest parallel request id to bound the size of this list.
+            }
             ongoingRequests.put(requestDescriptor, requestIds);
```
Comment (andreipaduroiu) [inline common/src/main/java/io/pravega/common/tracing/RequestTracker.java:180]: You're putting this in the cache every time you invoke this method. This is expensive and unnecessary. Consider putting it just after line 173 (first if block).

Also consider using `SimpleCache`.

Comment (RaulGracia) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java:179]: We need to put every new `requestId` in the cache and associate it with the `requestDescriptor`, as the intent is to track every `requestId` that attempts to do some action (in the Controller, so far). For this reason we have 1 `requestDescriptor` that can be associated to multiple concurrent `requestIds`. The only thing I have added is a limit to the amount of `requestIds` that could be associated to a particular `requestDescriptor`, given that in situations in which the Controller cannot complete a given action (e.g., Segment Store is unavailable), the `requestIds` keep accumulating for each retry, thus consuming more heap. I'm not sure if I understand your comment here (specially considering that these are constant time iserts on a map).

I have switched to `SimpleCache` as you have suggested, so we can remove this Guava cache dependency.

**Comment by RaulGracia** [comment]
Sure @shshashwat, system tests are green `test-pravega-continuous/4448`.

**Review by shshashwat — APPROVED** [review]
LGTM

**Comment by RaulGracia** [comment]
@pbelgundi @andreipaduroiu can we wrap up this one?

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java [hunk 2]
```diff
@@ -38,13 +39,15 @@
...
+    @VisibleForTesting
+    static final int MAX_PARALLEL_REQUESTS = 10;
     private static final String INTER_FIELD_DELIMITER = "-";
     private static final int MAX_CACHE_SIZE = 1000000;
     private static final int EVICTION_PERIOD_MINUTES = 10;
 
     private final Object lock = new Object();
     @GuardedBy("lock")
-    private final Cache<String, List<Long>> ongoingRequests;
+    private final SimpleCache<String, List<Long>> ongoingRequests;
```
Comment (pbelgundi) [inline common/src/main/java/io/pravega/common/tracing/RequestTracker.java:50]: What is the advantage of replacing google guava Cache with Simple Cache?
Google cache enables using Soft/Weak references for cache entries which enables fast reclamation of heap memory.

**Review by pbelgundi — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java (hunk 2 above)
Comment (RaulGracia) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java:50]: My understanding is that @andreipaduroiu suggested this to unify the usage of caches across Pravega, which makes sense. Anyway, irrespective of the implementation of Guava cache, without this PR we could get OOM anyway, and I think that with this PR we will be ok in terms of heap irrespective of the cache implementation used.

Comment (pbelgundi) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java:50]: The objective of this PR is to reduce the amount of memory consumed by Request Tracker and I don;t see how this change would do that. I understand using the same library across components is a good idea but the changes in this PR need to focus on reducing the memory occupied by RequestTracker.

**Review by pbelgundi — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java (hunk 2 above)
Comment (RaulGracia) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java]: Ok, we can do the switch to `SimpleCache` separately.

**Comment by pbelgundi** [comment]
PDP-31 states the intent of Request Tracker as:
"
to attach global tags to client requests that propagate through other Pravega components
"

However, in the code, I see that Request Ids generated by Request Tracker are almost never created on the Client, but are created inside ControllerServiceImpl which is a Controller (server side) class.
Assuming that the purpose of this class is to track all replays of the same request using the same request Id, I don;t see why we store a list of requestIds against a request descriptor:
```
[ongoingRequests](https://github.com/pravega/pravega/blob/a5f5d670b7f2340b8388a9a2b216aa7e5b4d7151/common/src/main/java/io/pravega/common/tracing/RequestTracker.java#L47)
```

**Comment by RaulGracia** [comment]
@pbelgundi I addressed your comment restoring again the Guava cache and answered your comment. Let me know if there is anything else to address in this PR.

**Comment by pbelgundi** [comment]
> @pbelgundi I addressed your comment restoring again the Guava cache and answered your comment. Let me know if there is anything else to address in this PR.

My comment wasn't so much about the use of Guava or Simple Cache, but more about what does it take to reduce the memory footprint of Request Tracker objects as in case of connectivity issues with Segment Store since these seem to be piling up in memory causing the Controller to go OOM.
We seem to be trying to limit the length of concurrent request id queue using - MAX_PARALLEL_REQUESTS (hard coded to 10) however this limit is already provided to Guava Cache by the "maximumSize" parameter and set to `1000000`.
Instead of adding entries to the cache and removing them, it may be better to just change the value of this parameter to a more reasonable setting, since I don't see why we would ever want to store as many request Ids in memory.

**Comment by RaulGracia** [comment]
@pbelgundi I have addressed your comment and replied to your question. If you have no further observations, please merge this PR.

**Comment by RaulGracia** [comment]
@pbelgundi any further comments on this PR?

**Comment by pbelgundi** [comment]
> @pbelgundi the memory consumption in the `RequestTracker` has 2 dimensions:
> 
> 1. Number of **entries in the cache**, limited by `MAX_CACHE_SIZE=1000000`. This has been always limited.
> 2. Number of **request ids per entry** (i.e. request descriptor). This was not limited before and it is what this PR is addressing by adding `MAX_PARALLEL_REQUESTS=10`. Without the current change, it could happen that a Controller or a Client is retrying always the same action due to some issue (e.g., "create Stream X"). In a extreme case, this would result on having only 1 entry in the cache (therefore, the 1 million limit is respected and does not help), but the list of request ids in this cache entry would keep growing without bounds by adding new request ids. Now this is now fixed.
> 
> > Instead of adding entries to the cache and removing them, it may be better to just change the value of this parameter to a more reasonable setting, since I don't see why we would ever want to store as many request Ids in memory.
> 
> Well, I can set the limit of the `RequestTracker` to something lower (like 100K). But this is a different issue, because this would only impact on dimension 1, and what this PR fixes is dimension 2. Anyway, I will reduce the max amount entries to keep in cache, just in case it helps in any way to reduce memory (in an scenario of retries, it will make no difference, though).

Ok. I see. 
If we always use and log only the first request Id, what is the value in storing other request Ids? Wouldn't it help to store only 1 request Id per Request Descriptor?

**Comment by RaulGracia** [comment]
@pbelgundi I have already answered that above:

> As I mentioned, in RequestTracker we have an idempotent Stream operation (create-stream-xxx) related to a client-generated request id yyy. In general, the cache will only contain a pair of these per operation. However, there could be cases in which multiple clients are attempting to do the same action and we want to track all of them (if possible). For instance, if we have 2 clients trying to create the same stream, the RequestTracker entry will look like: [create-stream-xxx: [yyy, zzz]. For consistency, we always pick the first request id associated to a request descriptor, as the Controller guarantees for idempotent operations guard us to be processing 2 operations for the same Stream. Therefore, we just care about the request id that is actually doing the processing and we keep using the same "primary" request id throughput its lifecycle (otherwise, we would be mixing multiple request ids and it would be pointless). The other outstanding request ids from other clients are also logged when requests are untracked (it may not be super useful, but it gives a bit more of information). Also, the point of having track of these parallel requests is to know when to "delete" the entry from the RequestTracker (if you only keep one, then you don't know when is the last request processed to remove that safely from the cache, unless you add a counter).

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java [hunk 3]
```diff
@@ -38,8 +38,10 @@
 @Slf4j
 public final class RequestTracker {
 
+    @VisibleForTesting
+    static final int MAX_PARALLEL_REQUESTS = 10;
     private static final String INTER_FIELD_DELIMITER = "-";
-    private static final int MAX_CACHE_SIZE = 1000000;
+    private static final int MAX_CACHE_SIZE = 100000;
```
Comment (sachin-j-joshi) [inline common/src/main/java/io/pravega/common/tracing/RequestTracker.java:44]: Does it make sense to make it a configurable property ?

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java [hunk 4]
```diff
@@ -167,10 +171,14 @@ public void trackRequest(String requestDescriptor, long requestId) {
             List<Long> requestIds = ongoingRequests.getIfPresent(requestDescriptor);
             if (requestIds == null) {
                 requestIds = Collections.synchronizedList(new ArrayList<>());
```
Comment (sachin-j-joshi) [inline common/src/main/java/io/pravega/common/tracing/RequestTracker.java:173]: As we recently discovered `Collections.synchronizedList(new ArrayList<>());` is not thread safe when iterators are used. 
Please double check if we are using iterators on this collection anywhere. 
either add synchronized while using or change this to Vector something more thread safe.

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java (hunk 3 above)
Comment (RaulGracia) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java:44]: This has not been a problem in severa years this has been set to that value, and even though I just reduced it by 10x lower based on the reviews. We could create a parameter for that in a separate PR, but I doubt that this is going to be used by anyone nor solve the problem we are discussing in this PR.

**Comment by pbelgundi** [comment]
> @pbelgundi I have already answered that above:
> 
> > As I mentioned, in RequestTracker we have an idempotent Stream operation (create-stream-xxx) related to a client-generated request id yyy. In general, the cache will only contain a pair of these per operation. However, there could be cases in which multiple clients are attempting to do the same action and we want to track all of them (if possible). For instance, if we have 2 clients trying to create the same stream, the RequestTracker entry will look like: [create-stream-xxx: [yyy, zzz]. For consistency, we always pick the first request id associated to a request descriptor, as the Controller guarantees for idempotent operations guard us to be processing 2 operations for the same Stream. Therefore, we just care about the request id that is actually doing the processing and we keep using the same "primary" request id throughput its lifecycle (otherwise, we would be mixing multiple request ids and it would be pointless). The other outstanding request ids from other clients are also logged when requests are untracked (it may not be super useful, but it gives a bit more of information). Also, the point of having track of these parallel requests is to know when to "delete" the entry from the RequestTracker (if you only keep one, then you don't know when is the last request processed to remove that safely from the cache, unless you add a counter).

It is still not clear how "RequestTracker entry will look like: [create-stream-xxx: [yyy, zzz]" maps to different values for different clients. What is more than 10 clients place the same request on Controller at a the same time. With MAX_PARALLEL set to 10 will we be able to track the flows separately for each client

File: common/src/main/java/io/pravega/common/tracing/RequestTracker.java (hunk 4 above)
Comment (RaulGracia) [reply common/src/main/java/io/pravega/common/tracing/RequestTracker.java:173]: There is no iteration over the list of `requestIds` associated to a request.

**Comment by RaulGracia** [comment]
> It is still not clear how a RequestTracker entry like: [create-stream-xxx: [yyy, zzz] maps to different values for different clients. Which part is the clientId here? 

Client ids are each of the elements in the list `[yyy, zzz]`. The RequestTracker just tracks the action being done "create stream X" with the request ids from the clients doing so "`yyy, zzz`". So you can see what is the client doing the operation in the server, as well as the workflow of the operation.

> What if more than 10 clients place the same request on Controller at a the same time. With MAX_PARALLEL set to 10 would we be able to track the flows separately for each client

We have to put a limit to the max number of parallel request ids to limit the amount of memory the list of request ids will consume in case of continuous retries if the cluster is in bad state. If the cluster is in that bad state, I don't think the request ids are really relevant, because there is a problem in the server side or the environment that may cause the cluster to be in that state. In normal conditions, having more than 10 parallel requests means that there would be more than 10 clients doing the same operation on the same Stream (create, delete, etc), which normally take tens of milliseconds to complete. In the case this happens, for the additional parallel requests, we would probably lose track of them, as we are not allowing to keep their client request ids, and when untracking them from the cache it would return `RequestTag.NON_EXISTENT_ID`.

**Review by pbelgundi — APPROVED** [review]
