### PR TITLE
Issue 1687: Make reading more robust

### LINKED ISSUE #1687: RetriesExhaustedException is wrapped inside a RuntimeException is thrown by the reader
**Problem description**
Reader throws a RuntimeException with cause as RetriesExhaustedException.
`2017-08-01 13:28:39,872 573961 [Time-limited test] INFO  i.p.t.system.AbstractFailoverTests - Unable to read events: {}
java.lang.RuntimeException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException
    at io.pravega.common.concurrent.FutureHelpers.getAndHandleExceptions(FutureHelpers.java:194)`

**Problem location**
Observed inside system test
Reader.

### PR DESCRIPTION
**Pull request by tkaitchuck**
**Change log description**
* Prevents throwing exceptions when reads are failing
* Adds assertions to make sure the data returned is from the correct offset.
* Adds unit tests.

**Purpose of the change**
Fixes #1687 , and make the system tests more reliable. 

**What the code does**
Handles exceptions more explicitly, so as to avoid propagating them up to there application where possible. 

**How to verify it**
All tests should pass including new tests.

### CODE REVIEW

File: test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java [hunk 1]
```diff
@@ -194,11 +194,6 @@ private void closeWriter(EventStreamWriter<Long> writer) {
                         log.debug("Read timeout");
                     }
                 } catch (Throwable e) {
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/AbstractFailoverTests.java]: During a failover scenario `e` can be an instance of RetriesExhaustedException . (We have observed this during yesterday's system test run.)

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java [hunk 2]
```diff
@@ -109,6 +109,19 @@
     public static <T> boolean isSuccessful(CompletableFuture<T> f) {
         return f.isDone() && !f.isCompletedExceptionally() && !f.isCancelled();
     }
+    
+    /**
+     * If the future has failed returns the exception that caused it. Otherwise returns null.
+     * @return null or the exception that caused the Future to fail.
```
Comment (Prabha-Veerubhotla) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: Please fix this javadoc parameters. 
add these  after the first line and before @ return.
 +      *
 +     * @param future   The future to inspect.
 +     * @param <T> The Type of the future's result.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 3]
```diff
@@ -164,12 +169,25 @@ private void handleRequest() {
...
     /**
      * @return If there is enough room for another request, and we aren't already waiting on one
      */
     private void issueRequestIfNeeded() {
-        if (!receivedEndOfSegment && outstandingRequest == null && buffer.capacityAvailable() > readLength) {
-            outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+        if (!receivedEndOfSegment && buffer.capacityAvailable() > readLength) {
+            if (outstandingRequest == null) {
+                outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+            } else if(outstandingRequest.isCompletedExceptionally()) {
```
Comment (Prabha-Veerubhotla) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Pls fix this. there should be space after if.

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java [hunk 4]
```diff
@@ -35,4 +35,6 @@
 
     @Override
     public abstract void close();
+    
+    public abstract boolean isClosed();
 }
```
Comment (Prabha-Veerubhotla) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java]: there should be new line added after the brace in line 40.

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java [hunk 5]
```diff
@@ -35,4 +35,7 @@
 
     @Override
     public abstract void close();
+    
+    public abstract boolean isClosed();
+
```
Comment (Prabha-Veerubhotla) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java]: sorry for the confusion, the new line should be added after `}`  and not before. 
I guess that is the end of file.
it should be 
```
     @Override
      public abstract void close();
+    
+    public abstract boolean isClosed();
}
+
```

File: common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java [hunk 6]
```diff
@@ -109,6 +109,21 @@
     public static <T> boolean isSuccessful(CompletableFuture<T> f) {
         return f.isDone() && !f.isCompletedExceptionally() && !f.isCancelled();
     }
+    
+    /**
+     * If the future has failed returns the exception that caused it. Otherwise returns null.
```
Comment (Prabha-Veerubhotla) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: add a new line after this line. the following is the expectation.
```
/**
     * If the future has failed returns the exception that caused it. Otherwise returns null.
     *
     * @param future   The future to inspect.
     * @param <T> The Type of the future's result.
     * @return null or the exception that caused the Future to fail.
     */
```

Comment (tkaitchuck) [inline common/src/main/java/io/pravega/common/concurrent/FutureHelpers.java]: done

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 7]
```diff
@@ -164,12 +169,25 @@ private void handleRequest() {
...
      */
     private void issueRequestIfNeeded() {
-        if (!receivedEndOfSegment && outstandingRequest == null && buffer.capacityAvailable() > readLength) {
-            outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+        if (!receivedEndOfSegment && buffer.capacityAvailable() > readLength) {
+            if (outstandingRequest == null) {
+                outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+            } else if (outstandingRequest.isCompletedExceptionally()) {
+                Throwable e = FutureHelpers.getException(outstandingRequest);
+                log.warn("Encountered an exception while reading for " + asyncInput.getSegmentId(), e);
```
Comment (andreipaduroiu) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: use formatting `{}` instead of string concatenation. That will prevent your string from being concat every time, while it can be done in the background, and only if needed.

Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: I have to do that due to the way the arguments work to the log method. There is no way to do formatting and log an exception in the same log line

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java [hunk 8]
```diff
@@ -164,12 +169,25 @@ private void handleRequest() {
...
      * @return If there is enough room for another request, and we aren't already waiting on one
      */
     private void issueRequestIfNeeded() {
-        if (!receivedEndOfSegment && outstandingRequest == null && buffer.capacityAvailable() > readLength) {
-            outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+        if (!receivedEndOfSegment && buffer.capacityAvailable() > readLength) {
+            if (outstandingRequest == null) {
+                outstandingRequest = asyncInput.read(offset + buffer.dataAvailable(), readLength);
+            } else if (outstandingRequest.isCompletedExceptionally()) {
+                Throwable e = FutureHelpers.getException(outstandingRequest);
```
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Is there really no exception for which we should not send a read request? It feels a bit too open to do it unconditionally, but I don't know what exceptions we should be getting here.

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java [hunk 9]
```diff
@@ -100,6 +100,8 @@ public void setup() {
 
     @After
     public void tearDown() {
+        testState.stopReadFlag.set(true);
```
Comment (fpj) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: This change seems to be unrelated. Are you trying to cover the case in which the test case doesn't stop the reader and writers, and execute tear down, e.g., when the test times out?

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java (hunk 7 above)
Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: as far as I can tell, with version slf4j 1.7.x and up, you can do what @andreipaduroiu is suggesting. we are on 1.7.25.

Comment (fpj) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: in fact, to try it out, I have just been able to compile this:
```
log.debug("Pravega Segmentstore service  details: {}", segUris, new Exception("Test"));
```

File: test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java (hunk 9 above)
Comment (tkaitchuck) [inline test/system/src/test/java/io/pravega/test/system/ReadWriteAndAutoScaleWithFailoverTest.java]: In the test run that was the impetus for this PR, there was a lot of log noise at the end because this was not done.

File: client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java (hunk 8 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/SegmentInputStreamImpl.java]: Changed

File: client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java (hunk 5 above)
Comment (tkaitchuck) [inline client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStream.java]: Fixed
