### PR TITLE
Issue 2779: BookieFailoverTest timeout error

### LINKED ISSUE #2779: BookieFailoverTest is not passing consistently
**Problem description**
`BookieFailoverTest` is failing due to a timeout error. Looking into the logs, it seems that readers are not properly created (5 are expected, but only 1 seems to be actually created and working). This may cause the test to wait indefinitely for a reader that did not actually start working.

**Problem location**
`BookieFailoverTest.java`

**Suggestions for an improvement**
Give additional time for the test to create  all the readers, before doing a bookie failover.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
This PR fixes the timeout error in `BookieFailoverTest` as follows: 
- Added a sleep in `BookieFailoverTest` to allow readers to get properly created. 
- Sleep intervals during failover have been set to match with other failovers in `AbstractFailoverTests`. 

**Purpose of the change**
Fixes #2779.

**What the code does**
The code adds one sleep interval between the creation of readers and the bookie failover event. Without this sleep interval, not all the readers were created and, what is worse, some of them were assumed to be created by the test but never started due to the Bookie failure. Now, all the readers get properly created and consume events. 
Moreover, the sleep intervals during failover have been set in the same way than `AbstractFailoverTests` (shorter intervals). The reason for this change is that extend the failover period for a too long period of time makes readers to get a `RetriesExhaustedException`. While having this exception does not prevent the test to write/read all the events, `AbstractFailoverTests` is instructed to fail the test if any reader gets an unexpected exception as this one.

**How to verify it**
`BookieFailoverTest` should pass consistently in system test builds.

### CODE REVIEW

**Comment by RaulGracia** [comment]
[Fix bookie-failover system test failure](https://trello.com/c/wT0LnCp1/39-fix-bookie-failover-system-test-failure)

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 1]
```diff
@@ -188,42 +188,46 @@ public void bookieFailoverTest() throws ExecutionException, InterruptedException
...
+            long writeCountAfterSleep  = testState.getEventWrittenCount();
+            log.info("Write count after bookie failover after {} seconds sleep {}.", WAIT_AFTER_FAILOVER_MILLIS / 1000, writeCountAfterSleep);
 
-            Assert.assertTrue(writeCounteAfterSleep == writeCounteBeforeSleep);
-            log.info("Writes failed when bookie is scaled down");
+            Assert.assertEquals("Unexpected writes performed during Bookie failover.", writeCountAfterSleep, writeCountBeforeSleep);
+            log.info("Writes failed when bookie is scaled down.");
 
-            //Bring back the bookie which was killed
+            // Bring back the bookie which was killed.
```
Comment (shrids) [inline test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: We should wait after bringing BK nodes up and before stopping the writers, right?

Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: According to your comment, I added a new sleep before `stopWriters()` to maximize the probabilities to do not fail on  `Assert.assertTrue(finalWriteCount > writeCountAfterSleep)`.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 2]
```diff
@@ -188,42 +188,48 @@ public void bookieFailoverTest() throws ExecutionException, InterruptedException
...
 
-            log.info("Sleeping for 1 min");
-            Exceptions.handleInterrupted(() -> Thread.sleep(1 * 60 * 1000));
+            log.info("Sleeping for {} seconds.", WAIT_AFTER_FAILOVER_MILLIS / 1000);
+            Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
 
-            long writeCounteBeforeSleep  = testState.getEventWrittenCount();
-            log.info("Write count after bookie failover after 1 min sleep {}", writeCounteBeforeSleep);
+            long writeCountBeforeSleep  = testState.getEventWrittenCount();
+            log.info("Write count after bookie failover after {} seconds sleep {}.", WAIT_AFTER_FAILOVER_MILLIS / 1000, writeCountBeforeSleep);
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: Can you make it `Write count after {} seconds sleep after bookie failover is: {}` or 
`Write count is {} after {} seconds sleep after bookie failover. ` 
Just to avoid confusion of the two parameters one after and before the sleep

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 3]
```diff
@@ -188,42 +188,48 @@ public void bookieFailoverTest() throws ExecutionException, InterruptedException
...
 
-            log.info("Sleeping for 1 min");
-            Exceptions.handleInterrupted(() -> Thread.sleep(1 * 60 * 1000));
+            log.info("Sleeping for {} seconds.", WAIT_AFTER_FAILOVER_MILLIS / 1000);
+            Exceptions.handleInterrupted(() -> Thread.sleep(WAIT_AFTER_FAILOVER_MILLIS));
 
-            long writeCounteAfterSleep  = testState.getEventWrittenCount();
-            log.info("Write count after bookie failover after 2 mins sleep {}", writeCounteAfterSleep);
+            long writeCountAfterSleep  = testState.getEventWrittenCount();
+            log.info("Write count after bookie failover after {} seconds sleep {}.", WAIT_AFTER_FAILOVER_MILLIS / 1000, writeCountAfterSleep);
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: same as above.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java [hunk 4]
```diff
@@ -188,42 +188,48 @@ public void bookieFailoverTest() throws ExecutionException, InterruptedException
...
 
-            Assert.assertTrue(writeCounteAfterSleep == writeCounteBeforeSleep);
-            log.info("Writes failed when bookie is scaled down");
+            Assert.assertEquals("Unexpected writes performed during Bookie failover.", writeCountAfterSleep, writeCountBeforeSleep);
+            log.info("Writes failed when bookie is scaled down.");
 
-            //Bring back the bookie which was killed
```
Comment (Prabha-Veerubhotla) [inline test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: Can you change this to `//Bring up a new instance of bookie `
The old comment is bit misleading, this new bookie can come up on any node and doesn't have to exactly replace the old one.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java (hunk 2 above)
Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: Log message changed..

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java (hunk 3 above)
Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: Log message changed.

File: test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java (hunk 4 above)
Comment (RaulGracia) [reply test/system/src/test/java/io/pravega/test/system/BookieFailoverTest.java]: Comment changed.
