### PR TITLE
Issue 3805: (SegmentStore) BugFix - StorageWriter not shutting down if Tier 2 fencing detected.

### LINKED ISSUE #3805: StorageWriter does not shut down if it detects Tier 2 Segment fenced out.
**Problem description**
By design, if a fencing exception was detected in the Tier 1 log or any Tier 2 segment, the container instance should shut down. A fencing exception occurs if a newer instance of the owning container is instantiated and has taken ownership of those resources.

It appears that this was never implemented for Tier 2 Segment files.

**Problem location**
`StorageWriter.java`

**Suggestions for an improvement**
Stop the StorageWriter when `StorageNotPrimaryException` is encountered.

### PR DESCRIPTION
**Pull request by andreipaduroiu**
**Change log description**  
- Fixed a bug in `StorageWriter` where it would not shut down (at all) if it detected `StorageNotPrimaryException`.

**Purpose of the change**  
Fixes #3805.

**What the code does**  
- Added `StorageNotPrimaryException` to the list of "critical" errors after which the `StorageWriter` must auto-shut down if it detects.
    - This is already thrown correctly by `SegmentAggregator` and a `StorageWriter` shutdown is already correctly handled upstream (triggering an entire container shutdown).

**How to verify it**  
Added unit test.

### CODE REVIEW

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java [hunk 1]
```diff
@@ -232,6 +234,49 @@ public void testWithStorageTransientErrors() throws Exception {
...
+     */
+    @Test
+    public void testWithStorageNotPrimaryErrors() throws Exception {
+        testWithStorageCriticalErrors(
+                context -> new ErrorInjector<>(c -> true, () -> new StorageNotPrimaryException("intentional")),
+                ex -> ex instanceof StorageNotPrimaryException);
+    }
+
+    /**
+     * Tests the StorageWriter in a configurable scenarion where the Storage component throws a critical (container-stopper)
```
Comment (sachin-j-joshi) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: scenarion

Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: Typo: `scenarion`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java [hunk 2]
```diff
@@ -232,6 +234,49 @@ public void testWithStorageTransientErrors() throws Exception {
...
+     * exception and verifies its handling of the situation.
+     *
+     * @param createErrorInjector          Creates an ErrorInjector that will cause the Storage component to enter an
+     *                                     errored state and throw an exception back at the StorageWriter.
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: `erroneous state` or `incorrect state` rather than `errored state`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: fixed.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java [hunk 3]
```diff
@@ -232,6 +234,49 @@ public void testWithStorageTransientErrors() throws Exception {
...
+                // care must be taken not to block a thread while waiting for it.
+                context.storage.append(corruptedSegmentHandle, new ByteArrayInputStream(corruptionData), corruptionData.length);
+
+                // Return some other kind of exception.
+                return new TimeoutException("Intentional");
+            };
+            return new ErrorInjector<>(c -> !corruptionHappened.getAndSet(true), exceptionSupplier);
+        };
+
+        testWithStorageCriticalErrors(createErrorInjector, ex -> ex instanceof ReconciliationFailureException);
```
Comment (fpj) [inline segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: I'm not sure how `TimeoutException` becomes `ReconciliationFailureException` for this scenario, could you elaborate?

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java [hunk 4]
```diff
@@ -273,7 +301,9 @@ public void testWithStorageCorruptionErrors() throws Exception {
                 ex -> ex instanceof IllegalStateException);
 
         ServiceListeners.awaitShutdown(context.writer, TIMEOUT, false);
-        Assert.assertTrue("Unexpected failure cause for StorageWriter.", Exceptions.unwrap(context.writer.failureCause()) instanceof ReconciliationFailureException);
+        System.out.println(context.writer.failureCause());
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: fixed

[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: I fixed this. I added it for my own debugging

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java [hunk 5]
```diff
@@ -232,6 +234,49 @@ public void testWithStorageTransientErrors() throws Exception {
      */
     @Test
     public void testWithStorageCorruptionErrors() throws Exception {
+        AtomicBoolean corruptionHappened = new AtomicBoolean();
```
[the remark this answers is not in the document]
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: `AtomicBoolean` constructor initializes to `false`.

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java (hunk 1 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: fixed

File: segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java (hunk 3 above)
Comment (andreipaduroiu) [reply segmentstore/server/src/test/java/io/pravega/segmentstore/server/writer/StorageWriterTests.java]: TimeoutException is thrown after we wrote garbage data to Tier 2.
The StorageWriter will retry the error.
Since it will pass the same offset, it will get `BadOffsetException`.
Since it gets `BadOffsetException`, it enters `ReconciliationMode.
Since we wrote garbage data which does not match what it should have been, the `StorageWriter` is failed with `ReconciliationFailureException`, which is a flavor of `DataCorruptionException`.
